deckhouse/deckhouse

- docs/site/_includes/getting_started/yandex/STEP_ENV.md
- docs/site/_includes/getting_started/yandex/STEP_ENV_RU.md
Argument for add-access-binding command is folder name, not cloud name
We can check that in command help:
```sh
$ yc resource-manager folder add-access-binding --help
Add access binding for the specified folder
Usage:
yc resource-manager folder add-access-binding <FOLDER-NAME>|<FOLDER-ID> [Flags...] [Global Flags...]
...
```
> Fix documentation for creating access binding on Yandex Cloud

- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_pod.go
- modules/500-upmeter/images/upmeter/pkg/probe/controlplane.go
Failing to delete pod doesn't indicate that there is a problem with scheduler so test shouldn't fail in this case.
I've increased deletion timeout to 20 seconds because that what we have left before next round of test is executed in worst case scenario:
5s of creation + 20s of scheduling + 20s of deletion + 10s of GC + 5s just in case = 60s
Fixes #35
> Increase pod deletion timeout in Upmeter scheduler monitoring

- tools/validation/copyright.go
- tools/validation/copyright_test.go
Copyright validation was failed for golang files with multiple one line comments on top file. If add new line before comments validation passed.
Passed:
```
// ...
// ...
```
Not passed:
```
// ...
// ...
```
PR's with correct copyright comments failed on copyright validation
```changes
module: ci
type: fix
description: Copyright validation was failed for golang files with multiple one line comments on top file. If add new line before comments validation passed.
note: none
```
> [ci][validators] Golang copyright one line comments without previous new line

- tools/validation/no_cyrillic.go
Add necessary two spaces before line and cursor
Test cases for "No Cyrillic" validator did not pass
```changes
```
> [ci][validators] Fix "No Cyrillic" validator formatting

- modules/500-upmeter/openapi/config-values.yaml
- modules/500-upmeter/openapi/doc-ru-config-values.yaml
- modules/500-upmeter/templates/upmeter/statefulset.yaml
Allows to configure exact node where upmeter statefulset will schedule. 
Useful when e.g. system nodes are places in multiple availability zones and at the same time disks are not multi-zonal (#347).
```changes
module: upmeter
type: feature
description: Assign more specific nodes for the server pod
```
> [upmeter] Node selector and toleration settings for server

- modules/020-deckhouse/hooks/update_deckhouse_image.go
- modules/020-deckhouse/hooks/update_deckhouse_image_test.go
Fix update deckhouse hook behavior
Second run of the hook with Manual update mode enabled leaded to the wrong behavior and always applied release
```changes
type: fix
description:  "Fix Deckhouse Manual update mode."
```
> [deckhouse] fix update hook Manual mode

- modules/500-upmeter/images/upmeter/pkg/probe/checker/http.go
Return fail probe status when cannot dial endpoint.
Unknown check status is false positive. When something is unavailable, the check should fail. Before the change, the HTTP checker fails on non-200 status code or when body cannot be read. Network unavailability was treated differently.
Resolves #348 
```changes
module: upmeter
type: fix 
description: HTTP probe status is "down" when it cannot connect to endpoint, instead of "unknown"
note: Unavailable Prometheus is not considered "up" anymore, like everything else that depends on it
```
> [upmeter] HTTP checker: fail when cannot dial

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/nodes.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/controller.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/namespace/namespace.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/namespace/namespaces.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/pod.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/ingress-nginx/vhost/vhost_detail.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/ingress-nginx/vhost/vhosts.json
We add regression in [commit](https://github.com/deckhouse/deckhouse/commit/41b17676c122daf9dcfb0f5dff0d9ee867115506) 
Dashboard does not have refresh
Refresh does not work in part of dashboards 
```changes
module: monitoring
type: fix
description: Refresh does not work on some dashboards
```
> [ingress-nginx][monitoring-k8s] Fix. Revert refresh on grafana dashboard

- modules/020-deckhouse/hooks/update_deckhouse_image.go
- modules/020-deckhouse/hooks/update_deckhouse_image_test.go
First DeckhouseRelease in the cluster led to panic
Fix possible panic
```changes
type: fix 
description: Fix panic on a first DeckhouseRelease CR
```
> [deckhouse] fix update deckhouse hook

- modules/030-cloud-provider-yandex/openapi/config-values.yaml
- modules/030-cloud-provider-yandex/openapi/doc-ru-config-values.yaml
When we refact yandex-cloud-provider module we forget add additionalExternalNetworkIDs in openapi spec
Deckhouse does not converge
```changes
module: yandex-cloud-provider
type: fix
description: Add additionalExternalNetworkIDs config in openapi spec, because dechouse does not converge if this field exists in cluster
```
> [yandex-cloud-provider] Fix. Add additionalExternalNetworkIDs config in openapi spec

- modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
- modules/402-ingress-nginx/crds/ingress-nginx.yaml
- modules/402-ingress-nginx/openapi/values.yaml
- modules/402-ingress-nginx/template_tests/controller_test.go
- modules/402-ingress-nginx/templates/controller/controller.yaml
- modules/402-ingress-nginx/webhooks/validating/ingressnginxcontroller
- Add additional `.spec.defaultSSLCertificate.secretRef` field for IngressNginxController that controlls the value of `--default-ssl-certificate` argument of the particular nginx-ingress-controller.
Solves [#273](https://github.com/deckhouse/deckhouse/issues/273).
```changes
module: ‎ingress-nginx‎
type: feature
description: "Add the ability to set a default certificate."
```
> [ingress-nginx] add the ability to set a default certificate

- modules/101-cert-manager/docs/FAQ.md
- modules/101-cert-manager/docs/FAQ_RU.md
Instructions for connection Vault with cert-manager
Hashicorp instruction has a few mistakes. This guide fixes it and gives our users a way to integrate a Vault Issuer into their infrastructure
```changes
type: feature
description: Instructions for connection Vault with cert-manager
note: only docs change
```
> [cert-manager] vault integration docs

- .github/ci_templates/build.yml
- .github/ci_templates/tests.yml
- .github/ci_templates/web.yml
- .github/workflow_templates/build-and-test_release.yml
- .github/workflow_templates/deploy-channel.multi.yml
- .github/workflow_templates/deploy-web.multi.yml
- .github/workflow_templates/schedule-cleanup.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_release.yml
- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-early-access.yml
- .github/workflows/deploy-rock-solid.yml
- .github/workflows/deploy-stable.yml
- .github/workflows/deploy-web-stage.yml
- .github/workflows/deploy-web-test.yml
- .github/workflows/schedule-cleanup.yml
Add 'regular' label to schedule non-e2e jobs.
Sometimes non-e2e jobs are accidentally scheduled to the wrong runner. Additional label for runners prevents this situation.
> [ci] feat(ci): use 'regular' label to schedule non e2e jobs

- modules/101-cert-manager/crds/crd-certificaterequests.yaml
- modules/101-cert-manager/crds/crd-certificates.yaml
- modules/101-cert-manager/crds/crd-challenges.yaml
- modules/101-cert-manager/crds/crd-clusterissuers.yaml
- modules/101-cert-manager/crds/crd-issuers.yaml
- modules/101-cert-manager/crds/crd-orders.yaml
- modules/101-cert-manager/docs/README.md
- modules/101-cert-manager/docs/README_RU.md
- modules/101-cert-manager/images/cert-manager-acme-solver/Dockerfile
- modules/101-cert-manager/images/cert-manager-cainjector/Dockerfile
- modules/101-cert-manager/images/cert-manager-controller/Dockerfile
- modules/101-cert-manager/images/cert-manager-webhook/Dockerfile
and fix readme
Upgrade cert-manager to v1.6.1 version
v1.6.1 has some bug fixes and improved logs on errors
Also, fix README
```changes
type: feature
description: Upgrade cert-manager to v1.6.1
note: cert-manager controller will be restarted. Cert-manager's CRD with version v1/alphaX is no longer supported
```
> [cert-manager] Upgrade to v1.6.1

- modules/300-prometheus/images/grafana/Dockerfile
Bump Grafana version to 8.2.7
https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/
```changes
module: prometheus
type: fix
description: "Bump Grafana version to fix zero-day path traversal bug (CVE-2021-43798)"
```
> [prometheus] Bump Grafana to 8.2.7

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/node.yaml
Alerts that are tightly coupled with node state should have tier cluster. Also refactored impact and likelihood labels into severity_level.
Correct labels for alerts should fix their routing.
> [monitoring-kubernetes] Set label `tier: cluster` on node alerts

- candi/bashible/common-steps/node-group/002_integrate_kubernetes_data_device.sh.tpl
Fix for automatic volume mount after reboot in ubuntu 20.04. Solves https://github.com/deckhouse/deckhouse/issues/341.
There is a problem in azure with the ubuntu 20.04 image — the kubernetes-data volume isn't mounted after a reboot.
```changes
type: fix
description: Cluster bootstrab on Azure works for Ubuntu 20.04
```
> [bashible] kubernetes-data volume mount fix

- modules/020-deckhouse/monitoring/prometheus-rules/deckhouse.yaml
We know about the problem and waiting for fix to be released. For now, we want to reduce flaky alerts.
> [deckhouse] Ignore flaky queues in D8DeckhouseQueueIsHung alert

- ee/fe/modules/600-secret-copier/docs/README.md
- ee/fe/modules/600-secret-copier/docs/README_RU.md
- ee/fe/modules/600-secret-copier/hooks/handler.go
- ee/fe/modules/600-secret-copier/hooks/handler_test.go
- Implement create–or–update logic for proper reconcile.
- Add support of namespace label-selector in `secret-copier.deckhouse.io/target-namespace-selector` annotation value.
Rarely deckhouse queue hangs on the following error:
```
module hook '600-secret-copier/hooks/handler.go' failed: can't create secret object `namespace/test`: secrets "test" already exists
```
```changes
module: secret-copier
type: feature
description: "Implement create–or–update logic for proper reconcile."
note: |
Add support of namespace label-selector in `secret-copier.deckhouse.io/target-namespace-selector` annotation value.
```
> [secret-copier] create or update target secrets

- modules/300-prometheus/docs/FAQ.md
- modules/300-prometheus/docs/FAQ_RU.md
Improved Prometheus FAQ about Lens access.
```changes
module: prometheus
type: feature
description: "Improved Prometheus FAQ about Lens access."
```
> [prometheus] fixed FAQ about Lens

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/namespace/namespaces.json
In 'Namespaces' dashboard, VPA '%' is calculated as the count of _VPA providing requests_ divided by the _count of active controllers_. Sometimes existing VPA do not target any controller or the controllers are not active. hence, the dashboard tale shows VPA covering more than 100% of controllers.
This PR fixes the expression. It calculates the VPA coverage as the division of _VPA providing requests and targeting active controllers_ divided by the _count of active controllers_.
Fixes #334
```changes
module: "monitoring-kubernetes"
type: "fix"
description: "Filter VPA by actual controllers to calculate VPA coverage"
```
> Count only VPA targeting existing controllers with existing pods

- modules/300-prometheus/images/grafana/grafana_home_dashboard.json
* Fix panel titles
* Fix queries
There may be a variety of CRI/OS in the cluster, which makes the home dashboard output ugly and unreadable information on version panels. The second issue is that there may be Prometheus/Grafana instances in user namespaces, which will affect the shown versions of Deckhouse modules.
```changes
module: prometheus
type: fix
description: Make Grafana home dashboard queries to only show the top-used versions  
```
> [prometheus] Grafana home dashboard queries improvements

- modules/150-user-authn/hooks/discover_publish_api_cert.go
- modules/150-user-authn/hooks/discover_publish_api_cert_test.go
* Delete secret if it is unused by the publish API ingress
1. It looks confusing when you see all the secrets in the namespace.
2. Without this change, Prometheus sends alerts that there are orphaned secrets (which is excessive, we do not have a real problem in the cluster).
```changes
type: fix
description: Delete publish API secrets with not matching names to avoid the orphaned secrets alerts
```
> [user-authn] Delete not matching secrets on publish api mode change

- modules/402-ingress-nginx/docs/USAGE.md
- modules/402-ingress-nginx/docs/USAGE_RU.md
Clarify inlet LoadBalancer usage with MetalLB.
There was a request for our support about such a case.
```changes
type: feature
description: |
Add an example of usage LoadBalancer inlet with MetalLB.
```
> [ingress-nginx] clarify inlet LoadBalancer usage with MetalLB

- candi/bashible/bundles/ubuntu-lts/all/002_install_apparmor_profiles.sh.tpl
- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
Fixed node-exporter apparmor profile.
With standard CRI AppArmor profile we got errors:
```
type=AVC msg=audit(1639955582.902:93693): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=315073 comm="node_exporter" requested_mask="read" denied_mask="read" peer="unconfined
```
```changes
module: monitoring-kubernetes
type: fix
description: "Fixed node-exporter apparmor profile."
```
> [prometheus] fixed node-exporter apparmor profile

- ee/modules/600-flant-integration/openapi/config-values.yaml
- ee/modules/600-flant-integration/openapi/doc-ru-config-values.yaml
The plan parameter was removed from the OpenAPI specification
The plan parameter was removed from the configuration in 1.29 and now we can remove it from the OpenAPI specification.
```changes
module: flant-integration
type: fix
description: Remove the plan parameter from the OpenAPI specification
```
> [flant-integration] Remove the plan parameter from the openAPI specification

- go.mod
- go.sum
- modules/020-deckhouse/monitoring/prometheus-rules/deckhouse.yaml
Add alert for broken deckhouse config
(Close #87)
We don't have in place validation for deckhouse config values cm. If someone put wrong values into it we can miss a problem and will be surprised by broken/abnormally working Deckhouse
```changes
type: feature
description: Add alert if deckhouse config is broken
```
> [deckhouse] Add alert for invalid config

- ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring/cronjob.yaml
CronJobFailed alert bugfix.
The alert didn't work.
```changes
module: extended-monitoring
type: fix
description: CronJobFailed alert bugfix.
```
> [extended-monitoring] CronJobFailed alert expr fix

- .github/scripts/js/ci.js
- .github/scripts/js/constants.js
- .github/workflow_templates/suspend-channel.multi.yml
- .github/workflows/suspend-alpha.yml
- .github/workflows/suspend-beta.yml
- .github/workflows/suspend-early-access.yml
- .github/workflows/suspend-rock-solid.yml
- .github/workflows/suspend-stable.yml
- canary.json
- modules/020-deckhouse/crds/deckhouse-release.yaml
- modules/020-deckhouse/crds/doc-ru-deckhouse-release.yaml
- modules/020-deckhouse/hooks/check_deckhouse_release.go
- modules/020-deckhouse/hooks/check_deckhouse_release_test.go
- modules/020-deckhouse/hooks/internal/v1alpha1/deckhouse_release.go
- modules/020-deckhouse/hooks/update_deckhouse_image.go
- modules/020-deckhouse/hooks/update_deckhouse_image_test.go
- werf.yaml
For a large number of clusters on a release channel, we want to have the ability to spread release in time
Spreaded release will generate less load and become more stable
Closes https://github.com/deckhouse/deckhouse/issues/332
```changes
type: feature
description: Add canary deckhouse release update
```
> [deckhouse] Add canary deployment for releases

- docs/site/.helm/templates/20-ingress.yaml
Switch Certificate resource version for the site from `certmanager.k8s.io/v1alpha1` to `cert-manager.io/v1`
> [site] Bump a Certificate version to v1

- modules/020-deckhouse/hooks/check_deckhouse_release.go
- modules/020-deckhouse/hooks/check_deckhouse_release_test.go
- modules/020-deckhouse/hooks/update_deckhouse_image.go
- modules/020-deckhouse/monitoring/prometheus-rules/alerting.yaml
Change alert severity level based on pending manual releases
(Close https://github.com/deckhouse/deckhouse/issues/340)
We can miss the low severity alert but if we have a few pending releases - something is going wrong.
We want to increase the level and pay more attention for the alert
```changes
type: feature
description: Different severity level based on pending DeckhouseReleases count
```
> [deckhouse] severity level based on releases count

- .github/ci_templates/scripts.yml
- .github/scripts/js/README.md
- .github/scripts/js/ci.js
- .github/scripts/js/error.js
- .github/scripts/validation_run.sh
- .github/workflow_templates/build-and-test_release.yml
- .github/workflow_templates/deploy-channel.multi.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflow_templates/on-push-main-or-tag.yml
- .github/workflows/build-and-test_release.yml
- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-early-access.yml
- .github/workflows/deploy-rock-solid.yml
- .github/workflows/deploy-stable.yml
- .github/workflows/deploy-web-stage.yml
- .github/workflows/deploy-web-test.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- .github/workflows/on-push-main-or-tag.yml
- Run build and test on push to release-* branches and tags with suffixes.
- No commenting for now, use curl to start e2e and deploy workflows for tags.
There is no way to release v1.29.0 without support for pre-release tags.
> [github] fix(ci): support for release branches and pre-release tags

- .github/ci_templates/helper_jobs.yml
- .github/scripts/js/constants.js
- .github/workflows/build-and-test_dev.yml
- .github/workflows/on-pull-request-labeled.yml
- .github/workflows/validation.yml
Rename label.
A forgotten change from #483.
> [github] fix(ci): rename ok-to-test to status/ok-to-test

- ee/fe/modules/500-okmeter/images/okagent/Dockerfile
Bump `oksupervisor`
The updating mechanism was fixed. The supervisor used to roll back okagent in case of any problem with its new version and never tried to update it again. 
```changes
module: okmener
type: fix
description: Bump oksupervisor version to fix updating problems
```
> [okmeter] Bump version to fix agents updating process

- modules/810-deckhouse-web/openapi/values.yaml
Add missing fields in schema for custom certificate copy.
The missing 'ca.crt' hangd deckhouse queue
```changes
module: deckhouse-web
type: fix 
description: "Added missing 'ca.crt' field to internal values schema"
```
> Fix deckhouse-web internal schema

- candi/bashible/bashible.sh.tpl
- candi/bashible/bundles/centos-7/bootstrap.sh.tpl
- candi/bashible/common-steps/node-group/050_configure_and_start_containerd.sh.tpl
- modules/040-node-manager/images/bashible-apiserver/pkg/template/context_builder.go
If registry auth was not found. bashible render  `<no value>` string instead empty value
```changes
type: fix 
description: fix incorrect auth value for containerd config only
```
> [bashible] Fix `<no value>` if registry auth is empty

- .github/scripts/validation_run.sh
- .github/workflow_templates/validation.yml
- .github/workflows/validation.yml
Use upload-artifact and download-artifact to download diff only once.
This change helps to avoid Github throttling when validation workflow downloads diff 3 times.
Also, fix `diffFile` in validation script after #507 (#483)
> [github] fix(ci): Download diff for pull request once

- modules/460-log-shipper/templates/daemonset.yaml
- modules/470-chrony/openapi/config-values.yaml
- modules/470-chrony/templates/daemonset.yaml
Add Label `workload-resource-policy.deckhouse.io=every-node` to `vector-agent` and `chrony` VPAs, to make them take part in resources requests calculations.
Sometimes `vector-agent` and `chrony` requests resources that are not considered by our automated logic that tends to Pod become un-schedulable.
```changes
module: log-shipper
type: fix
description: |
Add VPA label `workload-resource-policy` to make it take part in resources requests calculations.
---
module: chrony
type: fix
description: |
Add VPA label `workload-resource-policy` to make it take part in resources requests calculations.
```
> [log-shipper] [chrony] add workload-resource-policy label to VPA

- ee/fe/modules/340-extended-monitoring/docs/README.md
- ee/fe/modules/340-extended-monitoring/docs/README_RU.md
- ee/fe/modules/340-extended-monitoring/images/cert-exporter/Dockerfile
- ee/fe/modules/340-extended-monitoring/template_tests/cert_exporter_test.go
- ee/fe/modules/340-extended-monitoring/template_tests/image_availability_test.go
- ee/fe/modules/340-extended-monitoring/templates/cert-exporter/deployment.yaml
- ee/fe/modules/340-extended-monitoring/templates/cert-exporter/pdb.yaml
- ee/fe/modules/340-extended-monitoring/templates/cert-exporter/podmonitor.yaml
- ee/fe/modules/340-extended-monitoring/templates/cert-exporter/rbac-for-us.yaml
- ee/fe/modules/340-extended-monitoring/templates/cert-exporter/rbac-to-us.yaml
- ee/fe/modules/340-extended-monitoring/templates/events-exporter/deployment.yaml
- ee/fe/modules/340-extended-monitoring/templates/events-exporter/pdb.yaml
- ee/fe/modules/340-extended-monitoring/templates/events-exporter/podmonitor.yaml
- ee/fe/modules/340-extended-monitoring/templates/events-exporter/rbac-for-us.yaml
- ee/fe/modules/340-extended-monitoring/templates/events-exporter/rbac-to-us.yaml
- ee/fe/modules/340-extended-monitoring/templates/extended-monitoring-exporter/deployment.yaml
- ee/fe/modules/340-extended-monitoring/templates/extended-monitoring-exporter/pdb.yaml
- ee/fe/modules/340-extended-monitoring/templates/extended-monitoring-exporter/podmonitor.yaml
- ee/fe/modules/340-extended-monitoring/templates/extended-monitoring-exporter/rbac-for-us.yaml
- ee/fe/modules/340-extended-monitoring/templates/extended-monitoring-exporter/rbac-to-us.yaml
- ee/fe/modules/340-extended-monitoring/templates/image-availability-exporter/deployment.yaml
- ee/fe/modules/340-extended-monitoring/templates/image-availability-exporter/pdb.yaml
- ee/fe/modules/340-extended-monitoring/templates/image-availability-exporter/podmonitor.yaml
- ee/fe/modules/340-extended-monitoring/templates/image-availability-exporter/rbac-for-us.yaml
- ee/fe/modules/340-extended-monitoring/templates/image-availability-exporter/rbac-to-us.yaml
This PR adds cert-exporter to the extended-monitoring module
cert-exporter allows to track certificates expiration.
fixes https://github.com/deckhouse/deckhouse/issues/365
```changes
module: extended-monitoring
type: feature
description: Add cert-exporter
note: |
Added cert-exporter to track certificates expiration
```
> [extended-monitoring] Add cert-exporter

- modules/150-user-authn/webhooks/validating/dex_authenticator
Add validation webhook for DexAuthenticators
Close https://github.com/deckhouse/deckhouse/issues/453
Pair `applicationName` and `applicationIngressClassName` have to be unique through all DexAuthenticators. Without this check duplicated DexAuthenticator will fail inside the Deckhouse queue, which makes it hard to debug. We can handle this situation in the very beginning and prevent duplicated DexAuthenticator to be created.
```changes
type: feature
description: Validation webhook for preventing duplicate DexAuthenticators to be created.
```
> [user-authn] Add DexAuthenticator validation webhook

- ee/modules/140-user-authz/images/webhook/web/hook/handler.go
- ee/modules/140-user-authz/images/webhook/web/hook/handler_test.go
Allow empty group and API version subject access reviews 
Some tools like `k9s` and `kubectl can-i` do not bother filling API versions correctly, so we must satisfy their puzzling desires.
```changes
module: user-authz
type: fix 
description: Allow empty group and apiVersion requests in user-authz webhook
```
> [user-authz] Allow empty group and api version

- .github/dependabot.yml
Set limit to opened pull requests by dependabot
There are a lot of PRs from dependabot that we are not ready to review.
> [ci] Reduce dependabot PRs quantity

- .github/workflow_templates/deploy-channel.multi.yml
- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-early-access.yml
- .github/workflows/deploy-rock-solid.yml
- .github/workflows/deploy-stable.yml
Add 'editions' parameter to deploy only specified editions.
We don't want to deploy pre-release tags for CE edition before testing FE edition.
> [github] feat(ci): editions parameter to filter editions on deploy

- go_lib/hooks/copy_custom_certificate/hook.go
Refactor to use structs instead of maps on serialization
When serializing empty slices in `map[string][]byte`, they are omitted in values.
```changes
module: global
type: fix
description: Fix serialization of empty strings in secrets
```
> [global] copy custom certificate: serialize with struct, not map

- ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
- ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/exporter-health.yaml
- ee/fe/modules/340-extended-monitoring/templates/monitoring.yaml
This PR adds cert-exporter alerts to the extended-monitoring module
follows-up #479
fixes #365
```changes
module: extended-monitoring
type: feature
description: Add cert-exporter alerts
note: |
Added alerts to track certificates expiration and cert-exporter health
```
> [extended-monitoring] Add cert-exporter alerts

- modules/150-user-authn/webhooks/validating/dex_authenticator
Fix webhook
Webhook denies the request to update an existing DexAuthenticator. Ignore updating object with the same namespace/name
```changes
type: fix
description: Ignore updating an existing DexAuthenticator
```
> [user-authn] Fix DexAuthenticator validation webhook

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
- modules/020-deckhouse/docs/internal/IMAGE_COPIER.md
- modules/020-deckhouse/images/images-copier/generate-copier-secret.sh
Fix instructions for switching registry and image copier
Instructions had errors and users cannot switch registry
```changes
module: docs
type: fix
description: Fix instructions for switching registry and image copier
```
> [docs] Fix instructions for switching registry and image copier

- modules/031-local-path-provisioner/images/local-path-provisioner/Dockerfile
- modules/031-local-path-provisioner/images/local-path-provisioner/patches/README.md
- modules/031-local-path-provisioner/images/local-path-provisioner/patches/fix-directory-or-create.patch
This PR:
- updating local-path-provisioner 0.0.20 --> 0.0.21
- enables building from source code
- and applies patch from https://github.com/rancher/local-path-provisioner/pull/224
There is known problem https://github.com/rancher/local-path-provisioner/issues/137 which was confirmed by maintainer. It was [fixed](https://github.com/rancher/local-path-provisioner/issues/138) by me about year ago but then reverted due to silly problem on maintainers side.
I do not give up hope that it will be united one time, as for now I suggest the permanent fix on our side.
```changes
module: local-path-provisioner
type: fix
description: "Update local-path-provisioner v0.0.21, include fix"
note: |
Protect PVs to be reused in case of unmounted storage.
```
> [local-path-provisioner] Update and build from source

- modules/402-ingress-nginx/images/controller-0-46/patches/nginx-tpl.patch
- modules/402-ingress-nginx/images/controller-0-48/patches/nginx-tpl.patch
- modules/402-ingress-nginx/images/controller-0-49/patches/nginx-tpl.patch
- modules/402-ingress-nginx/images/controller-1-0/patches/nginx-tpl.patch
Added "pcre_jit on" to nginx.tmpl for controller-0.46 and above.
For controller versions 0.46 and above, this parameter has been lost.
```changes
type: fix
description: Added "pcre_jit on" to nginx.tmpl for controller-0.46 and above
note: |
Ingress Controller >= 0.46 will be restarted
```
> [ingress-nginx] add pcre_jit on in nginx.tmpl for controller-0.46 and above

- modules/101-cert-manager/templates/annotations-converter/mutatingwebhookconfiguration.yaml
- modules/101-cert-manager/templates/legacy/cert-manager/deployment.yaml
- modules/101-cert-manager/templates/legacy/cert-manager/pdb.yaml
- modules/101-cert-manager/templates/legacy/cert-manager/podmonitor.yaml
- modules/101-cert-manager/templates/legacy/webhook/apiservice.yaml
- modules/101-cert-manager/templates/legacy/webhook/deployment.yaml
- modules/101-cert-manager/templates/legacy/webhook/pdb.yaml
- modules/101-cert-manager/templates/legacy/webhook/service.yaml
- modules/101-cert-manager/templates/webhook/mutatingwebhookconfiguration.yaml
- modules/101-cert-manager/templates/webhook/validatingwebhookconfiguration.yaml
Disable legacy cert-manager (0.10.1) for 1.22 kubernetes
Legacy cert-manager APIs for webhooks and APIServices are not supported by 1.22 K8s. It leads to wrong behavior (ex. NS is stuck on deleting). We have to disable unsupported versions of the APIs by disabling legacy cert-manager.
```changes
type: fix
description:  Disable legacy cert-manager for >= 1.22 kubernetes
note: Legacy cert-manager resources (`certmanager.k8s.io`) will not be supported in 1.22+ clusters
```
> [cert-manager] Disable legacy cert-manager for K8s >= 1.22

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/controller.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/namespace/namespace.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/namespace/namespaces.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/pod.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/ingress-nginx/namespace/namespace_detail.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/ingress-nginx/namespace/namespaces.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/ingress-nginx/vhost/vhost_detail.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/ingress-nginx/vhost/vhosts.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/kubernetes-cluster/controller-detail.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/kubernetes-cluster/controllers.json
Migrate old tables to new. 
Replace from `__cell` variable to `__value`.
Add time interval to urls.
- `__cell` variable does not work for new table
- some tables did not migrate to 'new table'. Old tables are deprecated
- some urls did not contain time interval. It is not conveniently
```changes
module: grafana
type: fix
description: Migrate old tables to new and replace from __cell variable to __value and add time interval to url
```
> [monitoring][grafana] Migrate old tables to new and replace from __cell variable to __value and add time interval to url

- .github/ci_templates/helper_jobs.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_release.yml
- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-early-access.yml
- .github/workflows/deploy-rock-solid.yml
- .github/workflows/deploy-stable.yml
- .github/workflows/deploy-web-stage.yml
- .github/workflows/deploy-web-test.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- .github/workflows/on-pull-request-labeled.yml
- .github/workflows/schedule-cleanup.yml
- .github/workflows/suspend-alpha.yml
- .github/workflows/suspend-beta.yml
- .github/workflows/suspend-early-access.yml
- .github/workflows/suspend-rock-solid.yml
- .github/workflows/suspend-stable.yml
- .github/workflows/validation.yml
Skip CI checks for Prs made by our bot.
Validations fail on changelog PRs. We want to avoid the inconvenience.
> [CI] Skip checks for automation PRs

- ee/modules/110-istio/openapi/values.yaml
Missing customCertificateData in openapi fix.
There was an error:
```
Module hook start '110-istio/hooks/https/copy_custom_certificate'
Module hook start
Module hook failed, requeue task to retry after delay. Failed count is 13. Error: 2 errors occurred:
* istio.internal.customCertificateData is a forbidden property
```
```changes
module: istio
type: fix
description: "Missing customCertificateData in openapi fix."
```
> [istio][openapi] missing customCertificateData fix

- candi/bashible/common-steps/all/001_disable_ntp_on_node.sh.tpl
Disable ntp.service on nodes due to d8-chrony module is work.
```changes
type: fix
description: "Disable ntp.service on nodes due to d8-chrony module is work."
```
> [bashible] disable ntp.service on nodes

- modules/999-helm/monitoring/prometheus-rules/deprecated-versions.yaml
Provide an actual description for deprecated resources API versions alerts.
Our alerts about deprecated resources API versions contain description about Kubernetes 1.16+.
```changes
module: helm
type: fix
description: |
Provide an actual description for deprecated resources API versions alerts.
```
> [helm] provide actual alerts description

- modules/040-control-plane-manager/openapi/config-values.yaml
The `controlPlaneManager.apiserver.loadBalancer.annotations` value does not accept anything.
OpenAPI validation works correctly with annotations value.
```changes
type: fix
description: "LoadBalancer annotations are able to be set"
```
> [control-plane-manager] Fix LoadBalancer config values

- ee/modules/600-flant-integration/templates/pricing/config.yaml
- ee/modules/600-flant-integration/templates/pricing/daemonset.yaml
Changes in `pricing` Grafana Agent:
- Add a replica label to handle HA in the remote-write backend.
- Turn off sending metadata.
We need properly de-duplicate metrics on the backend side.
```changes
module: flant-integration
type: fix
description: |
Implement proper HA remote-write and reduce outgoing traffic amount.
```
> [flant-integration] add a replica label to handle ha in the remote-write backend

- .github/ci_templates/helper_jobs.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/on-pull-request-labeled.yml
- .github/workflows/validation.yml
Use another API method to get fresh info about the pull request.
API method [list-pull-requests-associated-with-a-commit](https://docs.github.com/en/rest/reference/commits#list-pull-requests-associated-with-a-commit) can't get open PRs for `main` branch in fork. Ooops.
Use [list pull requests](https://docs.github.com/en/rest/reference/pulls#list-pull-requests) method with head label to get opened PR.
> [ci] fix getting pull request info

- modules/020-deckhouse/hooks/cleanup_deckhouse_releases.go
- modules/020-deckhouse/hooks/cleanup_deckhouse_releases_test.go
Hook for fixing and cleaning Deckhouse Releases
Old releases could have the situation when more than 1 Deployed releases exist. We have to fix this situation.
Also, we have to cleanup Outdated releases, left only last 10
```changes
type: feature
description: Cleanup deckhouse Outdated releases (> 10)
```
> [deckhouse] Cleanup and fix deckhouse releases

- .github/workflows/changelog.yml
Fixes passing secrets to the workflow for external PRs
Changelog workflow cannot collect changes from external PRs
> Changelog CI: allow adding from external PRs

- docs/documentation/_plugins/openapi.rb
Don't show a parameter's default value in an OpenAPI specification on the site if it is an empty array or hash.
> [site] Don't show a parameter's default value in an OpenAPI spec

- .github/actions/milestone-changelog/action.yml
Changelog fetches only 30 last PRs since it is default `gh pr list` behavior. We ensure we get all of the changes. E.g. there at least 131 PRs for milestone v1.30.0.
Our changelog is incomplete.
> [Changelog CI] Fix missing changes

- .github/workflow_templates/build-and-test_release.yml
- .github/workflows/build-and-test_release.yml
werf converge requires checkout.
Checkout is a must for self-hosted runners. We end up deploying site and documentation to production environment using images built 2 days ago from PR.
> [ci] checkout sources before deploy site and docs

- dhctl/pkg/config/meta.go
- modules/040-node-manager/hooks/add_control_plane_role_to_master_ng.go
- modules/040-node-manager/hooks/add_control_plane_role_to_master_ng_test.go
Add label `node-role.kubernetes.io/control-plane` for master node group when cluster bootstrap.
Add migration to add label `node-role.kubernetes.io/control-plane` to node template for master nodegroup
Only one master node has `control-plane` role
```changes
module: dhctl
type: fix
description: All master nodes will have `control-plane` role in new clusters.
```
```changes
module: global
type: feature
description: All master nodes will have `control-plane` role in new exist clusters. 
note: Add migration for adding role. Bashible steps will be rerunned on master nodes.
```
> [dhctl][global] Add control-plane role for master node group

- ee/modules/110-istio/openapi/config-values.yaml
- ee/modules/110-istio/openapi/doc-ru-config-values.yaml
- ee/modules/110-istio/template_tests/module_test.go
- ee/modules/110-istio/templates/alliance/ingressgateway/service.yaml
The module option `alliance.ingressGateway.nodePort.port` to set a static port for NodePort-type ingressgateway Service.
In some environments, we need to explicitly set the port number. So we will be able to configure some firewall rules for example.
```changes
module: istio
type: feature
description: `alliance.ingressGateway.nodePort.port` option to set a static port for NodePort-type ingressgateway Service.
```
> [istio][ingressgateway] static port for NodePort inlet

- modules/101-cert-manager/hooks/legacy_orphan_secrets_metrics.go
- modules/101-cert-manager/hooks/legacy_orphan_secrets_metrics_test.go
- modules/101-cert-manager/hooks/orphan_secrets_metrics.go
- modules/101-cert-manager/hooks/orphan_secrets_metrics_test.go
- modules/101-cert-manager/monitoring/prometheus-rules/certificate.yaml
Add dynamic annotation for alert description
We have 2 hooks for orphan secrets - for legacy and actual cert-manager. But annotation was hardcoded into the alert's description. I propose to add label with desired annotation and pass it to the description
```changes
type: feature
description: Actualize annotation to delete in the orphan secrets alert description
```
> [cert-manager] Add dynamic annotation for orphan-secrets alert description

- candi/bashible/common-steps/node-group/089_setup_timer_to_run_docker_stuck_containers_cleaner.sh.tpl
Create bash script which parce dockerd logs, found none terminating containers, verify that containers is our (deckhouse owner) and remove it
Sometimes Docker fails to stop the container with an error, which leads to pods being stuck in terminating.
```changes
type: feature
description: Docker face slapper (pods stuck in terminating)
note: New step added
```
> [bashible] Docker face slapper (pods stuck in terminating)

- docs/site/.helm/values.yaml
Use the Stable version of the documentation by default on the site (instead of the Latest version).
> [site] Use the Stable version of the documentation by default

- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-openstack.yml
Fix openstack e2e test running
E2E test for openstack does not run
> [ci] Fix openstack e2e test running

- .github/scripts/js/constants.js
Fix google cloud platform e2e test running
Google cloud platform e2e tests don't run
> [ci] Fix google cloud platform e2e test running

- modules/140-user-authz/docs/USAGE.md
- modules/140-user-authz/docs/USAGE_RU.md
Fix doc
The right option is the `groups`
> [user-authz] Doc: fix subject access groups option name

- candi/openapi/node_group.yaml
- docs/documentation/_data/i18n.yml
- docs/documentation/_plugins/openapi.rb
OpenAPI specification site render updates:
- Show examples from OpenAPI specs as YAML
- Don't  show minimal length for string type if it is 1
```changes
type: fix
description: Show examples from OpenAPI specs (module configuration and CR page) as YAML.
```
> [docs] OpenAPI generation updates

- ee/fe/modules/340-monitoring-applications/monitoring/prometheus-rules/applications/nats/nats.yaml
- ee/fe/modules/340-monitoring-applications/monitoring/prometheus-rules/applications/php-fpm/php-fpm.yaml
- ee/fe/modules/340-monitoring-applications/monitoring/prometheus-rules/applications/rabbitmq/rabbitmq.yaml
- modules/030-cloud-provider-yandex/openapi/values.yaml
- modules/101-cert-manager/monitoring/prometheus-rules/certificate.yaml
- modules/340-monitoring-kubernetes-control-plane/monitoring/prometheus-rules/kube-controller-manager.yaml
- modules/340-monitoring-kubernetes-control-plane/monitoring/prometheus-rules/kube-scheduler.yaml
- modules/340-monitoring-kubernetes-control-plane/monitoring/prometheus-rules/kubernetes.tpl
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/coreos/general.yaml
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/coreos/kube-state-metrics.yaml
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/coreos/kubelet.tpl
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/coreos/node.yaml
fixes #534 
As mentioned in https://github.com/deckhouse/deckhouse/pull/512#discussion_r776390092:
> The severity annotation is deprecated, please use severity_level [1-9] instead.
```changes
module: monitoring
type: fix
description: "Replace severity by severity_level"
note: |
The severity annotation is deprecated, use severity_level [1-9] instead.
```
> [monitoring] Replace severity by severity_level

- modules/020-deckhouse/templates/namespace.yaml
- modules/300-prometheus/docs/FAQ.md
- modules/300-prometheus/docs/FAQ_RU.md
- modules/300-prometheus/docs/internal/PROMETHEUS_TARGETS_DEVELOPMENT.md
- modules/300-prometheus/docs/internal/PROMETHEUS_TARGETS_DEVELOPMENT_RU.md
- modules/300-prometheus/templates/prometheus/prometheus.yaml
- modules/340-monitoring-custom/monitoring/prometheus-rules/warnings/warnings.yaml
Change `podMonitorNamespaceSelector` and `serviceMonitorNamespaceSelector` from label `heritage: deckhouse` to new custom `prometheus.deckhouse.io/monitor-watcher-enabled` label. Because we do not want give an opportunity for usage `heritage: deckhouse` label for non-deckhouse namespaces, but we need pass namespace selectors into Prometheus resource. We can not implement OR logic with LabelSelector and we should change labels.
Add `prometheus.deckhouse.io/monitor-watcher-enabled` to `d8-monitoring` namespace. All own Pod and Service Monitor located in `d8-monitoring` namespace.
Add FAQ for connect user-space Service/Pod Monitors to Prometheus.
Change alert description about custom monitors.
Custom monitors alert logic did not change, because it already has correct logic.
There is no way …
> [prometheus][deckhouse] Add supporting ServiceMonitors and PodMonitors from user-space

- docs/site/_includes/getting_started/bm/step_cluster_setup.html
- docs/site/_includes/getting_started/bm/step_cluster_setup_ru.html
- docs/site/_includes/getting_started/global/partials/getting-started-setup.js.liquid
- docs/site/_includes/getting_started/global/step_cluster_setup.html
- docs/site/_includes/getting_started/global/step_cluster_setup_ru.html
Don't let use the `example.com` in publicDomainTemplate in Getting Started.
> [site] Fix getting started

- ee/fe/modules/340-monitoring-applications/monitoring/prometheus-rules/applications/nats/nats.yaml
- ee/fe/modules/340-monitoring-applications/monitoring/prometheus-rules/applications/php-fpm/php-fpm.yaml
- ee/fe/modules/340-monitoring-applications/monitoring/prometheus-rules/applications/rabbitmq/rabbitmq.yaml
- modules/030-cloud-provider-yandex/openapi/values.yaml
- modules/101-cert-manager/monitoring/prometheus-rules/certificate.yaml
- modules/340-monitoring-kubernetes-control-plane/monitoring/prometheus-rules/kube-controller-manager.yaml
- modules/340-monitoring-kubernetes-control-plane/monitoring/prometheus-rules/kube-scheduler.yaml
- modules/340-monitoring-kubernetes-control-plane/monitoring/prometheus-rules/kubernetes.tpl
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/coreos/general.yaml
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/coreos/kube-state-metrics.yaml
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/coreos/kubelet.tpl
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/coreos/node.yaml
fixes regression bug introduced in [#534 ](https://github.com/deckhouse/deckhouse/pull/599)
As mentioned in https://github.com/deckhouse/deckhouse/pull/512#discussion_r776390092:
> The severity annotation is deprecated, please use severity_level [1-9] instead.
```changes
module: monitoring
type: fix
description: "Fix severity_level annotations"
note: |
The severity_level annotation value must be a string.
```
> [monitoring] Fix severity_level annotations

- .github/workflow_templates/deploy-channel.multi.yml
- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-early-access.yml
- .github/workflows/deploy-rock-solid.yml
- .github/workflows/deploy-stable.yml
Remove debug lines.
`exit 0` line makes deploy to channel jobs stop immediately.
> [ci] fix: remove exit 0

- ee/fe/modules/450-keepalived/templates/statefulset.yaml
Change VPA update mode to initial.
This change will prevent unnecessary updates resources of keepalived pods. A restart of keepalived leads to traffic loss because virtual IP changes the host.
```changes
module: keepalived
type: fix
description: Change VPA update mode to initial.
```
> [keepalived] Change VPA update mode to initial

- candi/bashible/bundles/centos-7/node-group/031_install_containerd.sh.tpl
- candi/bashible/bundles/debian/node-group/031_install_containerd.sh.tpl
- candi/bashible/bundles/ubuntu-lts/node-group/031_install_containerd.sh.tpl
There can be a situation when docker-ce is installed not from registry packages. So bashible fails on the next step because it assumes that containerd is installed correctly.
Fix switch from docker to containerd.
```changes
type: fix
description: Fix remove of docker
```
> [bashible] Fix remove of docker

- ee/modules/110-istio/hooks/alliance_metadata_merge.go
Correct decision to deploy ingressgateway for multiclusters.
It was impossible to set up ingressgateways for multicluster from scratch. Loop dependency.
```changes
module: istio
type: fix
description: Correct decision to deploy ingressgateway for multiclusters.
```
> [istio][multicluster] multiclustersNeedIngressGateway fix

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
- modules/020-deckhouse/docs/internal/IMAGE_COPIER.md
- modules/020-deckhouse/images/images-copier/generate-copier-secret.sh
Change command order (begin patch Deckhouse Deployment, after patch deckhouse-registry secret)
It is more safety than change deckhouse-registry secret first, because kube-apiserver, etcd images can changed to new incorrect registry and connot be pulled
> [deckhouse][image-copier] Change order of commands in docs and secret generator

- .github/ci_templates/helper_jobs.yml
- .github/scripts/js/ci.js
- .github/scripts/validation_run.sh
- .github/workflows/build-and-test_dev.yml
- .github/workflows/on-pull-request-labeled.yml
- .github/workflows/validation.yml
Checkout PR sources using head commit (refs/pull/NUM/head) instead of virtual merge commit (refs/pull/NUM/merge).
`refs/pull/NUM/merge` refers to a PR branch merge into main branch. This commit may change during the build process. Later jobs will use different commit SHA and fail.
> [ci] use head commit of PR for predictable builds

- modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/control-plane-status.json
- modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/kube-etcd3.json
…er metrics
Sorted tables for api server metrics have been added to improve the presentation of metrics in grafana and simplify debugging of any problems with apiserver.
```changes
module: monitoring-kubernetes-control-plane
type: feature
description: "Sorted tables for api server metrics have been added."
```
> [monitoring-kubernetes-control-plane] Added sorted tables for apiserver metrics

- modules/150-user-authn/hooks/generate_kubernetes_dex_client_app_secret.go
- modules/150-user-authn/hooks/generate_kubernetes_dex_client_app_secret_test.go
No fill kubernetesDexClientAppSecret value because default empty is present in openapi spec.
Deckhouse does not converge
> [user-authn] Fix. No fill kubernetesDexClientAppSecret value

- modules/470-chrony/templates/bashible-step.yaml
Bashible step fix — missed openntpd.service and time-sync.target in list.
```changes
module: chrony
type: fix
description: Bashible step fix — missed openntpd.service and time-sync.target in list.
```
> [chrony] fix ntp services list in bashible step

- modules/040-control-plane-manager/hooks/requirements.go
- modules/040-control-plane-manager/hooks/requirements_test.go
Wrong semver lib was used
Blang semver lib doesn't parse Major.Minor versions, like "1.19" while Mastermind lib does. We have both cases of kubernetes versions inside the Deckhouse. So, it's better to use Mastermind lib
```changes
type: fix 
description: Fix requirements check semver lib
```
> [deckhouse] fix requirements semver

- ee/fe/modules/340-extended-monitoring/templates/cert-exporter/podmonitor.yaml
- ee/fe/modules/340-extended-monitoring/templates/events-exporter/podmonitor.yaml
- ee/fe/modules/340-extended-monitoring/templates/extended-monitoring-exporter/podmonitor.yaml
- ee/fe/modules/340-extended-monitoring/templates/image-availability-exporter/podmonitor.yaml
- ee/fe/modules/500-okmeter/templates/monitoring.yaml
- ee/fe/modules/600-secret-copier/templates/empty-helm-workaround.yaml
- ee/fe/modules/600-secret-copier/templates/monitoring.yaml
- ee/modules/110-istio/templates/monitoring.yaml
- ee/modules/350-node-local-dns/templates/monitoring.yaml
- helm_lib/templates/_monitoring_grafana_dashboards.tpl
- helm_lib/templates/_monitoring_prometheus_rules.tpl
- modules/020-deckhouse/templates/monitoring.yaml
- modules/040-control-plane-manager/templates/monitoring.yaml
- modules/040-node-manager/templates/monitoring.yaml
- modules/040-terraform-manager/templates/terraform-auto-converger/podmonitor.yaml
- modules/040-terraform-manager/templates/terraform-state-exporter/podmonitor.yaml
- modules/050-network-policy-engine/templates/podmonitor.yaml
- modules/101-cert-manager/templates/monitoring.yaml
- modules/402-ingress-nginx/templates/monitoring.yaml
- modules/460-log-shipper/templates/monitoring.yaml
- modules/470-chrony/templates/monitoring.yaml
- modules/500-upmeter/templates/monitoring.yaml
- modules/999-helm/templates/empty-helm-workaround.yaml
- modules/999-helm/templates/monitoring.yaml
- testing/matrix/linter/rules/modules/modules.go
- testing/matrix/linter/rules/modules/monitoring.go
* Move clause to deploy Prometheus CRDs to the helm_lib code
* Refactor monitroing.yaml files
* Add linter
We need this linter to not forget to add enable monitoring if there are dashboards and alert rules. The content of the trigger file is predictable, so we can also validate it to avoid logical mistakes.
```changes
module: testing
type: feature
description: Add monitoring trigger linter for modules
```
> [testing] Add monitoring linter

- deckhouse-controller/pkg/helpers/openstack/supports-online-disk-resize.go
- ee/modules/600-flant-integration/hooks/pricing/envs_from_global_values_and_kubectl.go
- ee/modules/600-flant-integration/hooks/pricing/envs_from_nodes.go
- global-hooks/discovery/kubernetes_version.go
- go.mod
- go.sum
- modules/340-monitoring-kubernetes/hooks/choose_nodes_for_ebpf_exporter.go
Remove extra semver lib usage
We use 2 semver libs, from Mastermind and Blang. They have a bit different behavior in some cases, so we decided to left only Mastermind library to avoid bugs. 
```changes
module: chore
type: fix
description: Remove extra semver lib
```
> [chore] remove extra semver lib

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/ebpf-exporter.yaml
Match only systemd cgroup driver CRIs.
`label_replace` regexes are not suitable for the kubelet cgroup driver.
> [monitoring-kubernetes] Match OOM kills only on systemd cgroup driver

- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/go.sum
- dhctl/pkg/operations/bootstrap.go
- werf.yaml
If we do not have bastion host, we will see error `no such file or directory` for `abort` command.
It is not error, because we can not have bastion host.
This PR check on exists key in cache before get it from cache and output error in error cases only.
Confusing error message in `abort` command
```changes
module: dhctl
type: fix
description: Do not print error about not exists bastion host key for abort command.
```
> [dhctl] Do not print error about not exists bastion host key for abort command

- ee/fe/modules/450-keepalived/docs/USAGE.md
- ee/fe/modules/450-keepalived/docs/USAGE_RU.md
Fix keepalived module examples node labels
```changes
type: fix
description: Fix keepalived module examples in the documentation.
```
> [docs]  Fix keepalived module examples node labels

- modules/402-ingress-nginx/docs/FAQ.md
- modules/402-ingress-nginx/docs/FAQ_RU.md
Add documentation article "How to enable HorizontalPodAutoscaling for IngressNginxController".
To make users familiar with how Ingress HPA works
```changes
type: feature
description: Add documentation article "How to enable HorizontalPodAutoscaling for IngressNginxController".
```
> [docs] Add an article about ingress-nginx HPA configuring

- modules/999-helm/monitoring/prometheus-rules/deprecated-versions.yaml
By following the deprecation guide, you can clarify any API version upgrade nuances.
```changes
module: helm
type: fix
description: Add deprecation guide link to deprecated resources alerts.
```
> [helm] Add deprecation guide link to alerts

- global-hooks/calculate_resources_requests.go
- testing/hooks/validation/exported_struct_test.go
Export struct validator skips structs called like ` n := &Struct{}` or `n := new(Struct)`
We check FilterResult with unexported fields and such kind of declaration is out of the validator scope
```changes
module: testing
type: fix
description: Fix export struct validator corner case
```
> [validators] handle export validator case with pointer

- candi/openapi/cluster_configuration.yaml
- global-hooks/openapi/config-values.yaml
- global-hooks/openapi/values.yaml
- helm_lib/templates/_module_https.tpl
- testing/matrix/linter/controller.go
Add more x-examples for matrix tests purposes.
Refact `helm_lib_module_uri_scheme` template util, because it needed enabled `cert-manager` and we want use it before enabling `cert-manager` module.  
Need more matrix testes for better covering template testing.
Cluster does not bootstrap without refactor `helm_lib_module_uri_scheme`.
> [global] Refact x-examples on global values and fix helm_lib_module_uri_scheme

- global-hooks/migrate/configmigrator.go
- global-hooks/migrate/flant_integration_remove_kubeall_team.go
- global-hooks/migrate/flant_integration_remove_kubeall_team_test.go
Delete deprecated field from deckhouse config.
Lets us we clean the openapi schema in future releases.
```changes
module: flant-integration
type: fix 
description: Remove "kubeall.team" field from deckhouse configmap
```
> [global] Migration: remove "flantIntegration.kubeall.team" from deckhouse config

- docs/site/_config.yml
Added the 'experimental' warning to namespace-configurator module documentation pages.
```changes
type: fix
description: "Add the 'experimental' warning to namespace-configurator module documentation pages"
```
> [documentation] Add experimental warning to namespace-configurator module

- candi/bashible/bundles/centos-7/node-group/031_install_containerd.sh.tpl
- candi/bashible/bundles/debian/node-group/031_install_containerd.sh.tpl
- candi/bashible/bundles/ubuntu-lts/node-group/031_install_containerd.sh.tpl
- modules/007-registrypackages/images/containerd-fe/werf.inc.yaml
Fixed build of containerd-fe registry package.
After release of registry packages with content tagging, we lost patch in containerd-fe package 
```changes
module: registry-packages
type: fix
description: "Fixed build of containerd-fe registry package."
```
> [registry-packages] fix containerd-fe build

- candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
Increase kubelet log rotation size.
This change will increase log buffer and effective logline count while viewing logs via kubectl or collecting them externally.
```changes
type: feature
description: Log rotation changed from 10 Mi / 10 files to 50 Mi / 4 files.
note: kubelet will restart, neither docker nor containerd won't restart. The change affects **only** containerd CRI.
```
> [bashible] Increase kubelet log rotation chunk size

- modules/020-deckhouse/templates/deployment.yaml
- testing/matrix/linter/rules/rules.go
Add image pull policy Always to deckhouse template
Prevent to restart deckhouse with incorrect creds passed into `deckhouse-registry` secret  
```changes
type: fix
description: Add image pull policy Always to deckhouse template
note: Deckhouse-controller can be restarted while updating
```
> [deckhouse] Add image pull policy Always to deckhouse template

- docs/site/_includes/getting_started/aws/partials/resources.yml.ha.inc
- docs/site/_includes/getting_started/aws/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/aws/partials/resources.yml.production.inc
- docs/site/_includes/getting_started/aws/partials/resources.yml.unonode.inc
- docs/site/_includes/getting_started/azure/partials/resources.yml.ha.inc
- docs/site/_includes/getting_started/azure/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/azure/partials/resources.yml.production.inc
- docs/site/_includes/getting_started/azure/partials/resources.yml.unonode.inc
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_BM.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_BM_RU.md
- docs/site/_includes/getting_started/bm/partials/user.yml.inc
- docs/site/_includes/getting_started/gcp/partials/resources.yml.ha.inc
- docs/site/_includes/getting_started/gcp/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/gcp/partials/resources.yml.production.inc
- docs/site/_includes/getting_started/global/select_revision.html
- docs/site/_includes/getting_started/openstack/partials/resources.yml.ha.inc
- docs/site/_includes/getting_started/openstack/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/openstack/partials/resources.yml.production.inc
- docs/site/_includes/getting_started/openstack/partials/resources.yml.unonode.inc
- docs/site/_includes/getting_started/vsphere/partials/resources.yml.ha.inc
- docs/site/_includes/getting_started/vsphere/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/vsphere/partials/resources.yml.production.inc
- docs/site/_includes/getting_started/yandex/partials/resources.yml.ha.inc
- docs/site/_includes/getting_started/yandex/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/yandex/partials/resources.yml.production.inc
- docs/site/js/getting-started.js
Generate a new password on the install step in the getting started for security purposes. Add a notice to use the generated password only for testing.
> [docs] Regenerate password in getting started

- modules/402-ingress-nginx/monitoring/grafana-dashboards/kubernetes-cluster/controller-detail.json
Add panels with nginx ingress metrics (memory, CPU, reloads, handled requests)
Closes https://github.com/deckhouse/deckhouse/issues/681
```changes
type: feature
description: Add panels to Grafana dashboards with detailed nginx statistic
```
> [ingress-nginx] Add detailed nginx statistic

- .gitlab/ci_includes/image_versions.yml
Remove excess `BASE_SCRATCH` key from `.gitlab/image_versions.yml`.
Github workflows render script fails if image_versions has double keys
```changes
module: ci
type: fix
description: |
remove excess `BASE_SCRATCH` key from `.gitlab/image_versions.yml`.
note: <what to expect>
```
> [ci] fix: remove double BASE_SCRATCH from image_versions

- modules/007-registrypackages/images/nginx-ubuntu/werf.inc.yaml
Fix build of nginx package for ubuntu 16.
```changes
module: registry-packages
type: fix
description: "Fix build of nginx package for ubuntu 16."
note:
```
> [registry-packages] fix build of nginx package for ubuntu 16

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_release.yml
Pull release-channel-version image before tagging.
'Build EDITION' jobs fail with 'No such image' error if release-channel-version image not available on the runner.
```changes
module: ci
type: fix
description: |
Pull release-channel-version image before tagging.
```
> [ci] fix: pull release-channel-version image before tagging

- dhctl/pkg/log/process.go
- dhctl/pkg/log/process_test.go
Close [issue](https://github.com/deckhouse/deckhouse/issues/272) 
Add all process to stack for pretty process logger for prevent panic from logboek
Cluster bootstrap can not be bootstrapped
```changes
module: dhctl
type: fix 
description: Fix potential panic for bashible logs in `dhctl bootstrap` command
```
> [core][dhctl] Fix potential panic for bashible logs in `dhctl bootstrap` command

- ee/modules/110-istio/docs/USAGE.md
- ee/modules/110-istio/docs/USAGE_RU.md
Canary usage doc fix.
```changes
module: istio
type: fix
description: Canary usage doc fix.
```
> [istio] canary usage doc fix

- candi/bashible/bashbooster/55_distro_version.sh
Fixed redhat version detection in bashible.
Bashible detection of distro version fails in case of Redhat distro due to VERSION_ID from /etc/os-release has minor part (for example 7.7 instead of 7 in Centos).
```changes
type: fix
description:"Fixed redhat version detection in bashible."
note:
```
> [bashible] fix redhat version detection

- modules/150-user-authn/images/dex/Dockerfile
- modules/150-user-authn/images/dex/patches/README.md
- modules/150-user-authn/images/dex/patches/bitbucket-teams.patch
Patch added.
https://github.com/dexidp/dex/pull/2390
```changes
type: fix
description: Migrate BitbucketCloud connector to utilizing workspaces API.
```
> [user-authn] Bitbucket migrate to workspaces

- candi/bashible/common-steps/all/063_install_kubelet_forker.sh.tpl
Fix kubelet slow start on reboot.
This PR closes ussue #https://github.com/deckhouse/deckhouse/issues/335
```changes
module: candi
type: fix
description: "Fix kubelet slow start on reboot."
note:
```
> [candi] fix kubelet slow start on reboot

- global-hooks/openapi/config-values.yaml
- global-hooks/openapi/openapi-case-tests.yaml
Add number type for `modules.resourcesRequests.everyNode.cpu` and `modules.resourcesRequests.masterNode.cpu`
Cannot use floats for example `1.25` for cpu objects
```changes
module: global
type: fix
description: Add number type for `modules.resourcesRequests.everyNode.cpu` and `modules.resourcesRequests.masterNode.cpu`
```
> [global] Add number type for `modules.resourcesRequests.everyNode.cpu` and `modules.resourcesRequests.masterNode.cpu`

- candi/bashible/common-steps/node-group/090_node_users.sh.tpl
Fix nodeuser creation script.
```changes
module: candi
type: fix
description: "Fix nodeuser creation script."
note: 
```
> [candi] fix nodeuser script

- modules/101-cert-manager/docs/USAGE.md
- modules/101-cert-manager/docs/USAGE_RU.md
Fix documentation
Certificate requirements were changed in a new cert-manager CRD and our documentation doesn't respect it
```changes
type: fix
description: fix certificate requirements documentation
```
> [cert-manager] fix docs about Certificate DNSNames

- modules/040-node-manager/hooks/update_node_group_status.go
- modules/040-node-manager/hooks/update_node_group_status_test.go
Fix event creation for kubernetes <= 1.19
`events.k8s.io/v1` API was opened for publicity in k8 1.20, before it was available only for scheduler. K8s tries to convert `events.k8s.io/v1` to `core.io/v1` but it can't convert events that bind to ClusterScope resources properly.
We can figure out a version of the k8s and create an event of the necessary type.
```changes
module: node-group
type: fix
description: Fix event creation for NG when new Machine provisioning process is failed
```
> [node-manager] handle k8s <1.20 in NG error events creation process

- modules/402-ingress-nginx/templates/controller/admission.yaml
Provide proper validating webhook configuration for Ingress Nginx Controller v1.0.
Ingress Nginx Controller supports only modern versions of ingresses and different validation path.
```changes
module: ingress-ngnix
type: fix
description: |
Proper validating webhook configuration for k8s 1.22+.
```
> [ingress-ngnix] proper validating webhook configuration for 1.22 k8s

- modules/460-log-shipper/monitoring/prometheus-rules/vector-agent.yaml
As for now, Deckhouse sends the alert if the log-shipper module is enabled without any CRs in the cluster (basically, this is true for most of the CE clusters).
This is a regression caused by https://github.com/deckhouse/deckhouse/pull/638
```changes
module: log-shipper
type: fix
description: Fire the alert only if there are more pods absent than allowed by the DaemonSet status.
```
> [log-shipper] Fix vector pods absent alert

- modules/040-node-manager/templates/bashible-apiserver/deployment.yaml
It removes unnecessary dependency between the node-manager module and the vertical-pod-autoscaler module.
```changes
type: fix
description: Do not deploy VPA for bashible-apiserver if autoscaler is not enabled
```
> [node-manager] Do not deploy VPA for bashible-apiserver if autoscaler is not enabled

- docs/site/_includes/getting_started/vsphere/partials/config.yml.standard.ee.inc
- ee/candi/cloud-providers/vsphere/docs/CLUSTER_CONFIGURATION.md
- ee/candi/cloud-providers/vsphere/docs/CLUSTER_CONFIGURATION_RU.md
- ee/candi/cloud-providers/vsphere/layouts/standard/base-infrastructure/main.tf
- ee/candi/cloud-providers/vsphere/layouts/standard/base-infrastructure/outputs.tf
- ee/candi/cloud-providers/vsphere/openapi/cloud_discovery_data.yaml
- ee/candi/cloud-providers/vsphere/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/vsphere/terraform-modules/master-node/main.tf
- ee/candi/cloud-providers/vsphere/terraform-modules/master-node/variables.tf
- ee/candi/cloud-providers/vsphere/terraform-modules/static-node/main.tf
- ee/candi/cloud-providers/vsphere/terraform-modules/static-node/variables.tf
Added ability to install deckhouse in vsphere installations with disabled DRS ability.
When DRS in vsphere vcenter is disabled, we cannot create additional resource pools and deckhouse installation fails.
```changes
module: cloud-provider-vsphere
type: feature
description: "Added ability to install deckhouse in vsphere installations with disabled DRS ability."
note: 
```
> [cloud-provider-vsphere] support of non-drs installations

- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
Enable systemd collector in the node-exporter.
One of our clients requested this. It is also beneficial to monitor (in the future) various systems services that are created by the bashible.
```changes
module: monitoring-kubernetes
type: feature
description: Enable systemd collector in the node-exporter
```
> [monitoring-kubernetes] Enable systemd collector in the node-exporter

- candi/control-plane-kubeadm/config.yaml.tpl
Enabled TTLAfterFinished on Kubernetes <1.21
It is a useful feature that was a long time in beta. Allows to clean up old jobs automatically.
```changes
type: feature
description: | 
Enabled TTLAfterFinished on Kubernetes <1.21
Allows to clean up old jobs automatically. 
https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/
```
> [control-plane-manager] Enabled TTLAfterFinished on older clusters

- ee/modules/110-istio/templates/alliance/metadata-exporter/deployment.yaml
- ee/modules/110-istio/templates/kiali/deployment.yaml
- ee/modules/110-istio/templates/operator/deployment.yaml
- modules/302-vertical-pod-autoscaler/hooks/set_maxallowed.go
- modules/302-vertical-pod-autoscaler/hooks/set_maxallowed_test.go
- testing/matrix/linter/apply.go
This PR improves hook max_allowed work.
1. If the new calculated max_allowed values for pods are less than 10% less than the old values, the values are not changed.
2. Hook starts only when Deckhouse pod becomes ready.
Also this PR fixes VPA linter and fixes some errors in vpa in istio module.
Vpa hook which set max_allowed values causes to massive pod restart on deckhouse version update.
```changes
module: vertical-pod-autoscaler
type: fix
description: |
1. If the new calculated max_allowed values for pods are less than 10% of old values, the values are not changed.
2. Hook starts only when Deckhouse pod becomes ready.
```
> [vertical-pod-autoscaler] vpa improvements

- ee/modules/110-istio/docs/USAGE_RU.md
Usage doc fix.
```changes
module: docs
type: fix
description: Fix Istio usage documentation.
```
> [istio] usage doc fix

- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- Save bootstrap.log and templates for failed e2e tests.
- Use unique names for artifacts to save logs for each job.
Logs and templates are useful to reproduce e2e tests later.
```changes
module: ci
type: fix | feature
description: save e2e logs for failed tests
```
> [ci] fix: save logs for failed e2e tests

- .github/ci_templates/build.yml
- .github/workflow_templates/build-and-test_dev.yml
- .github/workflow_templates/build-and-test_release.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_release.yml
Use deckhouse registry as second-repo for proper stages caching. The same commands use in modules build.
These commands keep cache synchronized when dev-registry cleaned.
```changes
module: ci
type: fix
description: proper werf build commands with two registries
```
> [ci] fix: proper werf build commands with two registries

- candi/bashible/common-steps/all/099_reboot.sh.tpl
Speed up reboot master node on cluster bootstrap.
When master node reboots after bootstrap, reboot takes long time due to reboot process waits containerd-shim processes stops. This is known containerd isue https://github.com/containerd/containerd/issues/386
```changes
module: candi
type: fix
description: "Speed up reboot master node on cluster bootstrap."
```
> [candi] speed up reboot master node on cluster bootstrap

- modules/340-monitoring-kubernetes-control-plane/monitoring/prometheus-rules/kubernetes.tpl
Fix command recommendation
Proper instruction
```changes
module: monitoring-kubernetes-control-plane
type: fix 
description: Proper kubectl command in alert description
```
> Fix alert instruction for apiserver logs

- candi/control-plane-kubeadm/config.yaml.tpl
- modules/040-control-plane-manager/templates/_scheduler_config.tpl
- modules/040-control-plane-manager/templates/daemonset.yaml
Specify a scheduler config.
Define a scheduler config that spreads Pods between zones with finer granularity than before.
```changes
type: feature
description: Define default config that spreads Pods between zones with finer granularity than before.
```
> [control-plane-manager] Default scheduler config

- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/pkg/app/bootstrap.go
- dhctl/pkg/kubernetes/actions/resources/resources.go
- dhctl/pkg/template/resources.go
- dhctl/pkg/template/resources_test.go
- dhctl/pkg/template/testdata/resources/with_tmp.yaml
- dhctl/pkg/template/testdata/resources/without_tmp.yaml
Add parameterization for bootstrapped resources.
Now, we can template resources for bootstrap with cloud discovery data.
We can add YandexInstanceClass for ephemeral nodes by providing the resources.yaml file for executing dhctl.
On executing terraform to create initial resources, we discover subnets ids for all zones.  It would be convenient if we could use these subnets in YandexInstanceClass to connect instances to subnets created on a previous step.
```changes
module: dhctl
type: feature
description: Add a templating feature for Kubernetes resources сreated by dhctl.
```
> [dhctl] Add parameterization for bootstrapped kube-resources

- candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
- candi/openapi/node_group.yaml
Allow users to configure kubelet log rotation.
Based on a choice of a log collector and volume of logging it is desirable to configure kubelet log rotation.
```changes
type: feature
description: Allows changing kubelet log rotation via new NodeGroup parameters: `containerLogMaxSize` and `containerLogMaxFiles`.
```
> [candi] Configurable kubelet log rotation

- .github/actions/milestone-changelog/action.yml
Skip changelog PR in the list of fetched PRs for the changelog generation.
Reduces the risk of failing workflow due to too big argument passed to an action.
This is a just a cosmetic change addressing useless changelog generations.
```changes
module: ci
type: fix
description: Skip automatic PRs in changelog
note: At least changelog will not participate in changelog action when it is merged
```
> Changelog: skip auto-generated PRs

- candi/control-plane-kubeadm/config.yaml.tpl
- modules/040-control-plane-manager/openapi/config-values.yaml
- modules/040-control-plane-manager/openapi/doc-ru-config-values.yaml
- modules/040-control-plane-manager/templates/_admission_control_config.tpl
- modules/040-control-plane-manager/templates/daemonset.yaml
Allow enabling additional admission plugins as well as defaulting some of them
There are some useful admission controllers. Some of them are worth force-enabling.
```changes
type: feature
description: |
Allow changing a list of active admission plugins via `controlPlaneManager.apiserver.admissionPlugins` configuration.
ExtendedResourceToleration and EventRateLimit are always enabled.
```
> [control-plane-manager] Allow enabling additional admission plugins as well as defaulting some of them

- candi/tools/discover_new_kubernetes_patchversions.sh
- candi/tools/functions.sh
- candi/version_map.yml
Update Kubernetes components to the latest patch versions.
Fix discover new patch versions script.
Using the latest stable upstream versions helps to avoid debugging bugs that are already fixed.
```changes
module: global
type: fix
description: Update Kubernetes components to the latest patch versions
note: Kubernetes control-plane components and kubelet will restart for 1.20, 1.21 and 1.22 minor versions.
```
> Update kubernetes patch versions

- modules/402-ingress-nginx/crds/ingress-nginx.yaml
- modules/402-ingress-nginx/openapi/config-values.yaml
Temporary disable 1.0 version from NginxIngressController CRD
1.0 ingress-controller is not ready - it's not working properly. We have to fix it before using
```changes
type: fix
description: temporary remove support of 1.0 controller
```
> [ingress-nginx] Temporary remove 1.0 version from CRD

- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
node-manager doc fix — remove registry packages cache during cleanup.
```changes
type: fix
description: Doc fix — remove registry packages cache during cleanup.
```
> [node-manager][doc] Node cleanup doc fix

- candi/version_map.yml
Kubernetes 1.19 was marked (#394) as EOL by mistake. Show on the site that Kubernetes 1.19 is fully supported by Deckhouse.
```changes
module: docs
type: fix
description: Mark K8s v1.19 as fully supported by Deckhouse.
```
> [docs] Make K8s 1.19 available for installation

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_release.yml
Add documentation about building deckhouse images for branches and tags.
It explains changes made in PR #777 to ease changing build process in the future.
```changes
module: ci
type: fix
description: Add documentation about building deckhouse images for branches and tags.
```
> [ci] fix: more documentation for PR#777, clean semicolons

- candi/bashible/bashbooster/55_distro_version.sh
Fix centos distro version detection.
```changes
module: candi
type: fix
description: "Fix centos distro version detection"
```
> [bashible] fix centos distro version detection

- modules/040-node-manager/images/bashible-apiserver/pkg/template/context.go
Add file with error on failed context building
We can lose errors in bashible-apiserver logs and it becomes complicated to debug some corner-case situations
```changes
type: feature
description: Add file with context-building error on failure
```
> [node-manager] add error file when bashible context failed

- dhctl/README.md
- ee/candi/bashible/bundles/astra/all/000_install_ca_certificates.sh.tpl
- ee/candi/bashible/bundles/astra/all/001_install_mandatory_packages.sh.tpl
- ee/candi/bashible/bundles/astra/node-group/031_install_containerd.sh.tpl
- ee/candi/bashible/bundles/astra/node-group/031_install_docker.sh.tpl
- ee/candi/bashible/bundles/astra/node-group/032_install_linux_kernel.sh.tpl
- ee/candi/bashible/bundles/astra/node-group/051_install_kubernetes_api_proxy.sh.tpl
- ee/candi/bashible/detect_bundle.sh
All Astra Linux editions are now available in one image with version 1.7. Previously only 2.12 orel was supported.
Extended Astra Linux support.
```changes
module: candi
type: fix
description: Support Astra Linux 1.7
```
> [candi] Support astra 1.7

- modules/402-ingress-nginx/images/controller-0-33/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-0-46/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-0-48/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-0-49/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-1-0/rootfs/etc/nginx/lua/pbmetrics.lua
Add the `xx` suffix to the `status_class` label of the `ingress_nginx_detail_backend_responses_total` metric.
This PR fixes panels for ingress-nginx controllers in Grafana. As for now, users an only see zeros in some tables, e.g.
```changes
type: fix
summary: "Expose status class label values with the xx suffix. Fix info about backends on dashboards."
impact: |
All ingress controllers >= 0.33 will restart.
```
> [ingress-nginx] Expose status class label values with the xx suffix

- .github/pull_request_template.md
- CONTRIBUTING.md
Add PR template to explain modern changes block
Helps describe PRs our way
```changes
section: repo
type: feature
summary: Updated PR template and the contribution guide
```
> Changelog schema template and link

- .github/ci_templates/e2e_tests.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Save 'dev/install' image name and use `docker run` to start e2e tests.
`werf run` could rebuild some stages and it makes e2e test last more than 30 minutes.
```changes
module: ci
type: fix
description: use docker run to start e2e tests
```
> [ci] fix: use tagged dev/install image to run in e2e tests

- docs/documentation/_data/i18n.yml
- docs/documentation/_includes/warning-latest.html
- docs/documentation/_layouts/page.html
- docs/site/css/docs.scss
Added warning about viewing the latest documentation version - an unreleased version.
```changes
module: docs
type: feature
description: Warning about viewing documentation of an unreleased Deckhouse version
```
> [docs] Add warning about viewing an unreleased version

- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/pkg/kubernetes/actions/resources/resources.go
- dhctl/pkg/template/resources.go
- dhctl/pkg/template/resources_test.go
- dhctl/pkg/template/testdata/resources/order.yaml
- dhctl/pkg/template/testdata/resources/same_kind_order.yaml
- dhctl/pkg/util/fs/create_test.go
- dhctl/pkg/util/fs/random.go
Create additional kube resurces in order instead create group by GVK
If you need to create namespace and resource in this namespace, you can get error because dhctl can create resource before namespace. It happens because we group resources by GVK into map and maps in go are unordered.
```changes
module: dhctl
type: feature
description: Create additional kube resources in order
```
> [dhctl] Create additional kube resources in order

- .github/actions/milestone-changelog/action.yml
- .github/scripts/js/changelog-find-pulls.js
- .github/workflows/changelog.yml
Fix triggering changelog workflow by merging the changelog PR
This change leaves us without useless workflows and useless PRs
```changes
section: ci
type: fix
summary: Fixed self-trigger of changelog PR
```
> Changelog: fix self-trigger

- modules/040-node-manager/images/bashible-apiserver/pkg/template/context_builder.go
Sort node-users output in bashible-apiserver
Users are not sorted and their order could be different => we can have different checksum for bashible
```changes
type: fix
summary: Sort node users for persistance
```
> [node-manager] sort node users by name

- modules/040-node-manager/templates/early-oom/daemonset.yaml
The previous configuration ensured almost constant OOMs on small-sized Nodes.
The amount of available memory is calculated as a minimum of 512 MB and 5% of the total node memory. If the amount of free node memory is less than the calculated value, the oom is triggered.
```changes
type: fix
summary: Fix constant OOM on small-sized nodes.
```
> [node-manager] Fix constant OOM on small-sized nodes

- candi/bashible/detect_bundle.sh
- ee/candi/bashible/detect_bundle.sh
- ee/modules/040-node-manager/.build.yaml
- ee/modules/040-node-manager/openapi/config-values.yaml
- ee/modules/040-node-manager/openapi/openapi-case-tests.yaml
- ee/modules/040-node-manager/openapi/values.yaml
- tools/build_includes/modules-EE.yaml
- tools/build_includes/modules-FE.yaml
- tools/build_includes/modules-with-dependencies-EE.yaml
- tools/build_includes/modules-with-dependencies-FE.yaml
- tools/build_includes/modules-with-exclude-EE.yaml
- tools/build_includes/modules-with-exclude-FE.yaml
[candi] Proper work with astra bundle in EE/FE.
Because Astra Linux bundle exists only in EE/FE edition, we remove `astra` from allowedBundles.
```changes
module: candi
type: fix
description: "Proper work with astra bundle in EE/FE."
```
> [candi] proper work with astra bundle in EE/FE

- candi/version_map.yml
- docs/documentation/_data/supported_versions.yml
- docs/documentation/_includes/SUPPORTED_VERSIONS.md
Add Astra Linux versions to the "Supported Kubernetes and OS versions" page
```changes
section: docs
type: fix
summary: Add Astra Linux to the "Supported Kubernetes and OS versions" page
```
> [docs] Update supported Kubernetes and OS versions page

- .github/scripts/js/changelog-find-pulls.js
URL to PRs are now correct
Now URLs point to github JSON API
```changes
section: ci
type: fix 
summary: Fixed PR URL in changelog
```
> Changelog: fix PR URL

- go.mod
- go.sum
Update addon-operator for deckhouse. 
We need to add new improvements to deckhouse.
In new version, cronjobs hooks will be started after first converge.
```changes
type: feature
summary: 
impact: Now, cronjobs hooks will be started after first converge.
```
> [global] Update addon-operator

- ee/fe/modules/340-extended-monitoring/images/events-exporter/Dockerfile
- ee/fe/modules/340-extended-monitoring/templates/events-exporter/deployment.yaml
Reduce event metrics cardinality.
```changes
module: extended-monitoring
type: feature
description: Update events_exporter and omit the message field. 
```
> [extended-monitoring] Bump events exporter to v0.0.2

- ee/modules/030-cloud-provider-openstack/templates/cloud-controller-manager/secret.yaml
Related issue https://github.com/deckhouse/deckhouse/issues/841
```changes
type: fix
summary: Fix LE certificates ordering for balancers with PROXY PROTOCOL enabled
```
> [cloud-provider-openstack] Fix certificates ordering for balancers with PROXY PROTOCOL enabled

- ee/modules/140-user-authz/images/webhook/cache/cache.go
- ee/modules/140-user-authz/images/webhook/cache/cache_test.go
- ee/modules/140-user-authz/images/webhook/web/hook/handler.go
- ee/modules/140-user-authz/images/webhook/web/hook/handler_test.go
- ee/modules/140-user-authz/images/webhook/web/server.go
- ee/modules/140-user-authz/templates/webhook/daemonset.yaml
- ee/modules/140-user-authz/templates/webhook/rbac-for-us.yaml
* Implement the check method
* Add it to liveness probe
* Increase liveness probe thresholds
This will help us restart a pod if the API becomes unavailable for it (we faced a problem once).
```changes
type: fix
summary: Add proper liveness probe which checks that webhook can access Kubernetes API
```
> [user-authz] Webhook probe

- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/elasticsearch/elasticsearch.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/etcd3/etcd3.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/memcached/memcached.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/mongodb/mongodb.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/nats/nats-legacy.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/nats/nats.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/php-fpm/php-fpm.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/prometheus/prometheus.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/rabbitmq/rabbitmq-legacy.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/rabbitmq/rabbitmq.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/redis/redis.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/sidekiq/sidekiq.json
- ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/uwsgi/uwsgi.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/ntp.json
- modules/500-upmeter/monitoring_test/grafana-dashboards/kubernetes-cluster/upmeter/dns_5m.json
- modules/500-upmeter/monitoring_test/grafana-dashboards/kubernetes-cluster/upmeter/hpa_5m.json
- modules/500-upmeter/monitoring_test/grafana-dashboards/kubernetes-cluster/upmeter/trickster_5m.json
Deckhouse provides stateless Grafana, which is configured by custom resources. This is fiction, that you can change anything using GUI.
```changes
module: global
type: fix
description: Make dashboards immutable (that weren't already).
```
> [global] Make dashboards immutable

- docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA.liquid
- docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA_RU.liquid
Add requirement to the getting started on bare metal that master node shouldn't have container runtime packages.
```changes
section: docs
type: fix
summary: Add requirement to the getting started on bare metal that master node shouldn't have container runtime packages.
```
> [docs] Update getting started for bare metal cluster

- candi/bashible/common-steps/node-group/090_node_users.sh.tpl
Fix nodeUser password set error.
```changes
section: candi
type: fix
summary:  Fix nodeUser password set error.
```
> [candi] fix nodeUser password set error

- candi/control-plane-kubeadm/config.yaml.tpl
- go.mod
- modules/021-kube-proxy/templates/configmap.yaml
- modules/402-ingress-nginx/hooks/manual_daemonset_update.go
- modules/402-ingress-nginx/hooks/manual_daemonset_update_test.go
- modules/402-ingress-nginx/templates/controller/controller.yaml
Add maxSurge==1 for clusters >=1.21 k8s version.
Add hook for manual Daemonset rollout for <1.21 clusters
Ingress controller pod terminating and only then creating a new pod during rollout. This could be a problem in some heavy-loaded clusters. Adding maxSurge changes this behavior.
Sometime native DaemonSet rollout removes two pods concurrently instead of sequential update. We can handle this situation by manual rollout control via the hook. It seems like a bug in old k8s version, guess we can disabled it after everyone will upgrade to 1.21+
```changes
type: fix
summary: Manual update for ingress controllers
impact: ingress nginx controllers will be removed manually by hook
```
> [ingress-nginx] max surge and manual rollout

- modules/402-ingress-nginx/hooks/manual_daemonset_update.go
- modules/402-ingress-nginx/hooks/manual_daemonset_update_test.go
Remove pod in background. Also use ControllerRevision as point of truth about controller generation
Ingress pod can be in a terminating state for some time and hook fails with timeout error
Also DS can write a wrong generation
```changes
type: fix
summary: remove pod in a background
```
> [ingress-nginx] background remove of a pod

- .github/ci_templates/build.yml
- .github/ci_templates/helper_jobs.yml
- .github/scripts/js/ci.js
- .github/scripts/js/constants.js
- .github/workflow_templates/build-and-test_dev.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_release.yml
- .github/workflows/on-pull-request-labeled.yml
- .github/workflows/validation.yml
Use 'edition/ce' and 'edition/ee' labels to set active edition for pull request. It affects build-and-test workflow and e2e tests.
- We use one tag 'prNUM' for deckhouse images related to PR (since #494 ).
- Default edition is FE. It is used to build images when new PR is opened.
- Add 'edition/*' label to enable CE or EE edition and build new 'prNUM' tag.
- Bot toggles 'edition/*' labels: when 'edition/ce' is added, bot removes 'edition/ee' label and vice versa.
- Remove 'edition/*' labels to build FE again.
We need to test changes in pull requests using deckhouse images built not only for FE but also for CE or EE.
```changes
section: ci
type: feature
summary: Added 'edition/ce' and 'edition/ee' labels to set edition for build and tests.
```
> [ci] feat: build CE and EE editions for dev branches

- modules/040-node-manager/webhooks/conversion/node_group
Fix jq
If there is more than one Hybrid NodeGroup in the cluster then conversion works only for one of NodeGroups.
> [node-manager] Fix alpha2_to_v1 conversion for CloudPermanent NodeGroup type

- ee/fe/modules/500-okmeter/templates/daemonset.yaml
```changes
type: fix
summary: Make all the data okagent relies on persistent
impact: Expect okmeter DaemonSet rollout restart
```
> [okmeter] Make okagent data persistent

- modules/810-deckhouse-web/openapi/config-values.yaml
Delete default value for externalAuthentication
It is impossible to disable external authentication with current default values. The `auth.password` field is always removed by the hook because the external authentication field always exists.
```changes
section: deckhouse-web
type: fix
summary: Do not set external authentication by default.
```
> [deckhouse-web] Do not set external authentication by default

- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Lower case cluster prefix for e2e to fix error:
```
1 error occurred:
* cloud.prefix should match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
```
Fix broken e2e tests.
```changes
section: ci
type: fix
summary: cluster prefix in lower case
```
> [ci] fix: lowercase for cluster prefix

- modules/040-node-manager/images/bashible-apiserver/pkg/template/steps_storage.go
Use step number with leading zeroes for custom steps.
When we use NodeGroupConfigurations, we set number for custom step. But in system steps numbers with leading zeroes, so we cannot fit in our custom step in system steps.
```changes
type: fix
summary: Use step number with leading zeroes for custom steps.
```
> [node-manager] use step number with leading zeroes for custom steps

- global-hooks/discovery/kubernetes_version.go
- global-hooks/discovery/kubernetes_version_test.go
- go_lib/dependency/http/http.go
Use dedicated HTTP client to check Kubernetes API servers versions.
It helps us declare which server name should be allowed for the TLS certificate. In some managed Kubernetes services, e.g., DigitalOcean Kubernetes, Azure Kubernetes Service, certificates for kube-apiservers are permitted only to be accessed by cluster IP and some common domains. The `kubernetes.default.svc` is a cluster domain-independent choice, which should always be present in the certificate allowed DNS names list.
```changes
type: fix
summary: Validate that the Kubernetes API endpoints certificate is signed for the kubernetes.default.svc domain.
```
> [control-plane-manager] Kubernetes version certificate validation fix

- modules/340-monitoring-kubernetes/templates/kubelet/service-monitor.yaml
Add the `container="POD"` label to all advisor metrics for pause containers. There will be more metrics in Prometheus for installations with the Contained CRI.
Fixes https://github.com/deckhouse/deckhouse/issues/822
```changes
type: fix
summary: 'Add the container="POD" label to all advisor metrics for pause containers.'
```
> [monitoring-kubernetes] Add POD labels to containerd pause container metrics

- candi/cloud-providers/yandex/layouts/standard/base-infrastructure/main.tf
- candi/cloud-providers/yandex/layouts/standard/variables.tf
- candi/cloud-providers/yandex/layouts/with-nat-instance/base-infrastructure/main.tf
- candi/cloud-providers/yandex/layouts/with-nat-instance/variables.tf
- candi/cloud-providers/yandex/layouts/without-nat/base-infrastructure/main.tf
- candi/cloud-providers/yandex/layouts/without-nat/variables.tf
- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/terraform-modules/master-node/main.tf
- candi/cloud-providers/yandex/terraform-modules/static-node/main.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/main.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/outputs.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/variables.tf
Support existing subnets in Yandex.Cloud.
Sometimes, a user creates subnets before installing a cluster. Interconnect is the main example, which requires pre-created subnets.
```changes
type: feature
summary: Support existing subnets in Yandex.Cloud
```
> [candi] Support existing subnets in Yandex.Cloud

- candi/control-plane-kubeadm/config.yaml.tpl
- modules/040-control-plane-manager/openapi/config-values.yaml
- modules/040-control-plane-manager/openapi/doc-ru-config-values.yaml
- modules/040-control-plane-manager/templates/daemonset.yaml
1. Support bound service account tokens in Kubernetes >=1.21
2. Support TokenRequest API in all support Kubernetes versions
Currently, we do not support the aforementioned API nor [Bound Service Account Tokens](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md).
```changes
type: feature
description: |
1. Support bound service account tokens in Kubernetes >=1.21
2. Support TokenRequest API in all supported Kubernetes versions
```
> [control-plane-manager] Support bound service account tokens and TokenRequest API

- candi/bashible/common-steps/node-group/041_configure_sysctl_tuner.sh.tpl
- candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
- candi/bashible/common-steps/node-group/070_start_sysctl_tuner.sh.tpl
1. Step with sysctl-tuner script divided to 2 separate steps  - configure and run.
2. In kubelet added ability of tune sysctl parameters of pods - https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#enabling-unsafe-sysctls
1. We divide sysctl tuner step into 2 separate steps to have ability to reconfigure sysctl-tuner.sh script with NodeGroupConfiguration custom step.
2. This ability is asked by our clients.
```changes
section: candi
type: feature
summary: Divided sysctl-tuner to 2 separate steps and enable unsafe sysctls in kubelet config.
```
> [candi] divided sysctl-tuner to 2 separate steps and enable unsafe sysctls in kubelet config

- candi/control-plane-kubeadm/config.yaml.tpl
- modules/040-control-plane-manager/hooks/ensure_secret_encryption_key.go
- modules/040-control-plane-manager/hooks/ensure_secret_encryption_key_test.go
- modules/040-control-plane-manager/images/control-plane-manager/control-plane-manager
- modules/040-control-plane-manager/openapi/config-values.yaml
- modules/040-control-plane-manager/openapi/doc-ru-config-values.yaml
- modules/040-control-plane-manager/openapi/values.yaml
- modules/040-control-plane-manager/template_tests/template_test.go
- modules/040-control-plane-manager/templates/_encryption_config.tpl
- modules/040-control-plane-manager/templates/daemonset.yaml
- modules/040-control-plane-manager/webhooks/validating/d8-secret-encryption-key-configuration
Enables use of encryption at rest mode for apiserver (https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/)
Encryption at rest solves problem with unencrypted secrets in etcd storage.
```changes
type: feature
summary: Encryption at rest.
```
> [control-plane-manager] Encryption at rest

- deckhouse-controller/cmd/deckhouse-controller/main.go
- go.mod
- go.sum
- testing/hooks/init.go
Dependencies:
- addon-operator v1.0.4
- shell-operator v1.0.8
Changes:
- more debug commands: queue main, list snapshots
- set log level to debug in runtime
- continuous checking config, metric with errors counter
New features to ease debugging.
```changes
type: feature
summary: update shell-operator and addon-operator
```
> [deckhouse-controller] feat: update core operators

- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Make cluster prefix shorter.
```
metadata.labels: Invalid value: "d8-node-terraform-state-candi-1904234594-containerd-1-21-master-0": must be no more than 63 characters
```
```changes
section: ci
type: fix
summary: shorten cluster prefix for e2e
```
> [ci] fix: shorten cluster prefix to fix "too long value" error

- modules/460-log-shipper/hooks/generate_config.go
It is hard to say whether the config was updated or not.
```changes
type: feature
summary: Fire an event if a config file was created/updated.
```
> [log-shipper] Fire an event if a config file was created/updated

- modules/150-user-authn/images/dex/Dockerfile
Remove unnecessary dependency on dex image
```changes
type: fix
summary: Remove unnecessary dependency on dex image for build
```
> [user-authn] Fix dex build

- .github/ci_templates/build.yml
- .github/ci_templates/tests.yml
- .github/workflow_templates/build-and-test_dev.yml
- .github/workflow_templates/build-and-test_release.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_release.yml
- modules/150-user-authn/images/dex/Dockerfile
Tests running — migration from `werf run` to `docker run`.
After [build optimization](https://github.com/deckhouse/deckhouse/pull/616), the tests image werf.yaml become quite complicated, so it takes a lot of time to just run the ready-to-use image via `werf run`. So we use `docker run`.
```changes
section: ci
type: fix
summary: Tests running — migration from `werf run` to `docker run`.
```
> [ci] tests run optimization

- ee/modules/600-flant-integration/templates/pricing/config.yaml
Added grafana-agent proxy_url option for proxy support if global proxy configuration is set.
```changes
section: flant-pricing
type: feature
summary: Added grafana-agent proxy_url option for proxy support if global proxy configuration is set.
```
> [flant-integration] added grafana-agent proxy_url option

- modules/500-upmeter/images/upmeter/pkg/probe/checker/d8_clusterconfiguration.go
Upmeter agent ID is generated as a string containing hexadecimal number. It is used as UpmeterHookProbe custom resource name and label value. The manifest for the CR is generated from text YAML template, there the ID is substituted unquoted.
When the ID consists of digits only, it is considered a number. The resulting manifests is rendered invalid on the creation of the CR object. This results in the downtime of "deckhouse/cluster-configuration" probe.
Fixes #994 , which is a floating bug.
```changes
type: fix 
summary: Fixed floating causing false downtime of deckhouse/cluster-configuration probe 
```
> [upmeter] Fix numbers for string fields in yaml for UpmeterHookProbe CR template

- modules/101-cert-manager/monitoring/prometheus-rules/certificate.yaml
Remove D8CertmanagerOrphanSecretsWithoutCorrespondingCertificateResources
Closes https://github.com/deckhouse/deckhouse/issues/879
```changes
type: fix
summary: Remove D8CertmanagerOrphanSecretsWithoutCorrespondingCertificateResources
```
> [cert-manager] remove D8CertmanagerOrphanSecretsWithoutCorrespondingCertificateResources

- candi/cloud-providers/gcp/openapi/doc-ru-instance_class.yaml
- candi/cloud-providers/gcp/openapi/instance_class.yaml
The "Сloud provider — GCP: custom resource" article reviewing and fixing.
```changes
section: docs
type: fix
description: "Review and fix the 'Сloud provider — GCP: custom resource' article."
```
> [docs] Fix article text in «Сloud provider — GCP: custom resource» page

- modules/030-cloud-provider-gcp/docs/CONFIGURATION_RU.md
- modules/030-cloud-provider-gcp/openapi/config-values.yaml
- modules/030-cloud-provider-gcp/openapi/doc-ru-config-values.yaml
The "Cloud provider — GCP: configuration" article reviewing and fixing.
```changes
module: docs
type: fix
description: "Review and fix the 'Cloud provider — GCP: configuration' article."
```
> [docs] Fix article text in «Cloud provider — GCP: configuration» page

- werf.yaml
Add condition for import from terraform-provider-vsphere artifact.
Fix error: 
```
Error: unable to generate default repo: unable to load werf config: no such artifact `terraform-provider-vsphere`!
```
```changes
section: ci
type: fix
summary: fix build for CE
```
> [ci] fix(build): no such artifact `terraform-provider-vsphere` for CE

- go.mod
- go.sum
- modules/020-deckhouse/hooks/check_deckhouse_release.go
- modules/020-deckhouse/hooks/update_deckhouse_image.go
Update [addon](https://github.com/flant/addon-operator/pull/300) and shell [operators](https://github.com/flant/shell-operator/pull/360).
Deckhouse cannot self update if converge was not done.
It was be when we will have error during first converge and after fix it Deckhouse cannot get update. 
And we will need update image manually. 
```changes
type: fix
summary: Update addon-operator and shell-operator
impact: Updating core component. We start schedule some hooks before first converge.
---
type: fix
summary: `Update Deckhouse` and `check Deckhouse release` hooks now schedule without waiting first converge.
```
> [deckhouse] Fix deckhouse cannot self update if converge was not done and update addon-operator

- candi/cloud-providers/gcp/docs/ENVIRONMENT.md
- candi/cloud-providers/gcp/docs/ENVIRONMENT_RU.md
The "Cloud provider — GCP: Preparing environment" article reviewing and fixing.
```changes
module: docs
type: fix
description: "Review and fix the 'Cloud provider — GCP: Preparing environment' article."
```
> [docs] Fix article text in «Cloud provider — GCP: Preparing environment» page

- modules/030-cloud-provider-yandex/openapi/values.yaml
Add existingZoneToSubnetIDMap field to openapi/values.yaml to fix error on install:
```
cloud-provider-yandex/taskRunner: Module hook failed, requeue task to retry after delay. Failed count is 18. Error: 2 errors occurred:
* cloudProviderYandex.internal.providerClusterConfiguration.existingZoneToSubnetIDMap is a forbidden property
```
Installation failed when set `existingZoneToSubnetIDMap` in `YandexClusterConfiguration`
```changes
section: cluster-provider-yandex
type: fix
summary: add existingZoneToSubnetIDMap field to openapi/values.yaml
```
> [cluster-provider-yandex] fix: existingZoneToSubnetIDMap is a forbidden property

- candi/cloud-providers/aws/layouts/with-nat/base-infrastructure/main.tf
Fixed zone selection for bastion in WithNAT layout.
Specifying a zone for a bastion resulted in the error "Inconsistent conditional result types"
```changes
type: fix
summary: Fixed zone selection for bastion in WithNAT layout
```
> [cloud-provider-aws] fix zone selection for bastion in WithNAT layout

- modules/150-user-authn/templates/dex/config.yaml
Fixed `.spec.ldap.bindPW` escaping in `DexProvider`
The `\` character in the config turned into `\\`
```changes
type: fix
summary: Fixed .spec.ldap.bindPW escaping in DexProvider
```
> [user-authn] fix .spec.ldap.bindPW escaping in DexProvider

- ee/candi/cloud-providers/openstack/layouts/simple-with-internal-network/master-node/main.tf
- ee/candi/cloud-providers/openstack/layouts/simple-with-internal-network/variables.tf
- ee/candi/cloud-providers/openstack/layouts/simple/master-node/main.tf
- ee/candi/cloud-providers/openstack/layouts/simple/variables.tf
- ee/candi/cloud-providers/openstack/layouts/standard-with-no-router/master-node/main.tf
- ee/candi/cloud-providers/openstack/layouts/standard-with-no-router/variables.tf
- ee/candi/cloud-providers/openstack/layouts/standard/base-infrastructure/main.tf
- ee/candi/cloud-providers/openstack/layouts/standard/master-node/main.tf
- ee/candi/cloud-providers/openstack/terraform-modules/kubernetes-data/main.tf
- ee/candi/cloud-providers/openstack/terraform-modules/kubernetes-data/variables.tf
- ee/candi/cloud-providers/openstack/terraform-modules/master/main.tf
- ee/candi/cloud-providers/openstack/terraform-modules/providers.tf
- ee/candi/cloud-providers/openstack/terraform-modules/static-node/main.tf
- ee/candi/cloud-providers/openstack/terraform-modules/variables.tf
- specify availability_zone for volumes created by dhctl
- ignore volume availability_zone changes
- add wait_until_associated flag for openstack_compute_floatingip_associate_v2
Fixes known issues with OpenStack clouds:
- volume types require availability_zone to be set
- floating IP can be attached in background, and it's better to specifically wait for this process to be completed
```changes
type: fix
summary: Set volume availability zone in dhctl on bootstrap
```
> [cloud-provider-openstack] Set volume availability zone in dhctl on bootstrap

- ee/modules/110-istio/openapi/config-values.yaml
- ee/modules/110-istio/openapi/doc-ru-config-values.yaml
- ee/modules/110-istio/template_tests/module_test.go
- ee/modules/110-istio/templates/control-plane/iop.yaml
nodeSelector and tolerations customization for control-plane
In some complex installations there could be need to schedule istiod to separate nodes.
```changes
section: istiod
type: feature
summary: nodeSelector and tolerations customization for control-plane
```
> [istio] nodeSelector and tolerations customization for control-plane

- modules/020-deckhouse/crds/deckhouse-release.yaml
- modules/020-deckhouse/crds/doc-ru-deckhouse-release.yaml
- modules/020-deckhouse/hooks/check_deckhouse_release.go
- modules/020-deckhouse/hooks/check_deckhouse_release_test.go
- modules/020-deckhouse/hooks/internal/v1alpha1/deckhouse_release.go
- werf.yaml
Add changelog into DeckhouseRelease CR. Only enabledModules will be written in changelog
It will look like:
```yaml
kind: DeckhouseRelease
approved: false
metadata:
creationTimestamp: null
name: v1-31-0
spec:
changelog:
cert-manager:
fixes:
- pull_request: https://github.com/deckhouse/deckhouse/pull/999
summary: Remove D8CertmanagerOrphanSecretsWithoutCorrespondingCertificateResources
global:
features:
- description: All master nodes will have  role in new exist clusters.
note: Add migration for adding role. Bashible steps will be rerunned on master
nodes.
pull_request: https://github.com/deckhouse/deckhouse/pull/562
- description: Update Kubernetes patch versions.
pull_request: …
```
> [deckhouse] Add changelog to DeckhouseRelease

- modules/402-ingress-nginx/images/controller-0-33/Dockerfile
- modules/402-ingress-nginx/images/controller-0-33/patches/README.md
- modules/402-ingress-nginx/images/controller-0-33/patches/deny-invalid-auth-locations.patch
- modules/402-ingress-nginx/images/controller-0-46/Dockerfile
- modules/402-ingress-nginx/images/controller-0-46/patches/README.md
- modules/402-ingress-nginx/images/controller-0-46/patches/deny-invalid-auth-locations.patch
- modules/402-ingress-nginx/images/controller-0-48/Dockerfile
- modules/402-ingress-nginx/images/controller-0-48/patches/README.md
- modules/402-ingress-nginx/images/controller-0-48/patches/deny-invalid-auth-locations.patch
- modules/402-ingress-nginx/images/controller-0-49/Dockerfile
- modules/402-ingress-nginx/images/controller-0-49/patches/README.md
- modules/402-ingress-nginx/images/controller-0-49/patches/deny-invalid-auth-locations.patch
- modules/402-ingress-nginx/images/controller-1-0/Dockerfile
- modules/402-ingress-nginx/images/controller-1-0/patches/README.md
- modules/402-ingress-nginx/images/controller-1-0/patches/deny-invalid-auth-locations.patch
This is a patch that will help to avoid the explosion of sensitive data if the invalid auth URL is provided accidentally.
```changes
type: feature
summary:  Deny locations with invalid auth URL
impact: Ingress controllers of version >=0.33 will be restarted.
```
> [ingress-nginx] Deny locations with invalid auth URL

- candi/bashible/common-steps/node-group/089_setup_timer_to_run_docker_stuck_containers_cleaner.sh.tpl
- escape curly braces to prevent faulty bash script rendering
- get repo tag for comparison with pattern
```
if ! image="$(docker container inspect "$container_id" -f '<no value>' 2> /dev/null)"; then
echo_err "Container $container_id was not found or it was remove on previous run"
continue
fi
```
```changes
section: candi
type: fix
summary: Fix docker-stuck-containers-cleaner unit
```
> [candi] Fix docker-stuck-containers-cleaner unit

- docs/site/_includes/getting_started/global/partials/INSTALL_OTHER.liquid
- docs/site/_includes/getting_started/global/partials/INSTALL_OTHER_RU.liquid
Add `--ask-become-pass` option to the bare metal bootstrap command in the Getting Started.
```changes
section: docs
type: fix
summary: "Ask sudo password in the Getting Started when bootstrapping bare metal cluster."
```
> [docs][getting-started] Ask sudo password when bootstrapping bare metal cluster

- .github/ci_templates/tests.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_release.yml
Add `--pull always` flag to use recent 'tests' image.
Images for dev branches are not removed from standalone runners, so `docker run` uses obsolete image when running on the same runner again.
```changes
section: ci
type: fix
summary: always push recent 'tests' image
```
> [ci] fix: always pull tests image when running tests

- modules/031-linstor/images/linstor-server/Dockerfile
linstor-server v1.18 just been [released](https://github.com/LINBIT/linstor-server/releases/tag/v1.18.0). 
This PR is switching version of linstor-server from `v1.18-rc3` to `v1.18`
```changes
type: feature
summary: Switch rc to stable release
```
> [linstor] Switch rc to stable release

- candi/version_map.yml
Update kubernetes patch versions.
```changes
section: candi
type: feature
summary: Update kubernetes patch versions.
impact: Kubernetes control-plane components and kubelet on nodes will restart
```
> [candi] update kubernetes patch versions

- ee/modules/110-istio/hooks/alliance_metadata_merge.go
- ee/modules/110-istio/hooks/alliance_metadata_merge_test.go
- ee/modules/110-istio/images/api-proxy/main.go
* multicluster api access token `apiJWT` issuing for a year instead of a day.
* api-proxy logging improvements.
It is workaround for embarrassing [bug](https://github.com/istio/istio/issues/37925) which confuses us during debug (unwanted error messages).
api-proxy logging improvements also help us to debug multicluster problems.
```changes
section: istio
type: fix
summary: apiJWT exp prolongation and api-proxy logging improvements
```
> [istio][api-proxy] logging improvements

- dhctl/pkg/config/meta.go
- modules/040-node-manager/hooks/add_control_plane_role_to_master_ng.go
- modules/040-node-manager/hooks/add_control_plane_role_to_master_ng_test.go
Add node.kubernetes.io/exclude-from-external-load-balancers label on control-plane nodes with dhctl for new clusters.
Add migration for exists clusters.
In kubeadm v1.21 label node.kubernetes.io/exclude-from-external-load-balancers is added to all control-plane nodes. Deckhouse clusters have this label only on the first control-plane node that was bootstrapped by dhctl.
```changes
section: dhctl
type: fix
summary: Add node.kubernetes.io/exclude-from-external-load-balancers label on control-plane nodes
impact: IngressNginxController Pods with the LoadBalancer.* inlets on master nodes will be excluded from load balancing
```
> [dhctl] Add `node.kubernetes.io/exclude-from-external-load-balancers` label on control-plane nodes

- .github/workflow_templates/deploy-channel.multi.yml
- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-early-access.yml
- .github/workflows/deploy-rock-solid.yml
- .github/workflows/deploy-stable.yml
- Add jobs to control editions when approving deploy to environment.
- Add tag name to deploy job.
- Output errors as annotations.
Approvers should see what they approve.
```changes
section: ci
type: feature
summary: Add jobs to control editions when approving deploy to environment
```
> [ci] feat: jobs to control editions when approving deploy

- candi/bashible/bundles/debian/all/001_install_mandatory_packages.sh.tpl
- candi/bashible/bundles/debian/node-group/031_install_containerd.sh.tpl
- candi/bashible/bundles/debian/node-group/031_install_docker.sh.tpl
- candi/bashible/bundles/debian/node-group/032_install_linux_kernel.sh.tpl
- candi/bashible/bundles/debian/node-group/051_install_kubernetes_api_proxy.sh.tpl
- candi/bashible/detect_bundle.sh
- candi/version_map.yml
- modules/007-registrypackages/images/conntrack-debian/scripts/install
- modules/007-registrypackages/images/conntrack-debian/scripts/uninstall
- modules/007-registrypackages/images/conntrack-debian/werf.inc.yaml
- modules/007-registrypackages/images/virt-what-debian/scripts/install
- modules/007-registrypackages/images/virt-what-debian/scripts/uninstall
- modules/007-registrypackages/images/virt-what-debian/werf.inc.yaml
Debian is the default bundle now. If we can't discover distro then we try bootstrap up it as Debian 9.
Support of distros based on Debian.
```changes
section: candi
type: feature
summary: Use Debian bundle as default
```
> [candi] Use Debian bundle as default

- modules/140-user-authz/crds/crd.yaml
- modules/140-user-authz/webhooks/validating/cluster_authorization_rule
Add validation webhook
* Validate ServiceAccount name using regex
* Validate that namespace of the ServiceAccount is provided
* Validate that namespace is not provided for the Group and UIser subjects
```changes
type: fix
summary: Add more validations for the ClusterAuthorizationRule subjects section
```
> [user-authz] Validate service account names

- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Proper image name in e2e tests for release tags.
E2e tests fail for release tags. See [run](https://github.com/deckhouse/deckhouse/runs/5598080185?check_suite_focus=true).
```changes
section: ci
type: fix
summary: Proper image name in e2e tests for release tags
```
> [ci] fix: proper image name in e2e tests for release tags

- docs/documentation/_data/sidebars/main.yml
- ee/candi/cloud-providers/openstack/docs/CLUSTER_CONFIGURATION.md
- ee/candi/cloud-providers/openstack/docs/CLUSTER_CONFIGURATION_RU.md
- ee/candi/cloud-providers/openstack/docs/ENVIRONMENT.md
- ee/candi/cloud-providers/openstack/docs/ENVIRONMENT_RU.md
- ee/candi/cloud-providers/openstack/docs/LAYOUTS.md
- ee/modules/030-cloud-provider-openstack/docs/README.md
- ee/modules/030-cloud-provider-openstack/docs/README_RU.md
- modules/030-cloud-provider-azure/docs/CR.md
- modules/030-cloud-provider-azure/docs/CR_RU.md
- modules/030-cloud-provider-gcp/docs/CR.md
- modules/030-cloud-provider-gcp/docs/CR_RU.md
- modules/030-cloud-provider-yandex/docs/CR.md
- modules/030-cloud-provider-yandex/docs/CR_RU.md
Fixing of the "Cloud Provider" pages headers and OpenStack names.
```changes
section: docs
type: fix
summary: "Fix "Cloud Provider" page headers and OpenStack names"
```
> [docs] Cloud Provider page headers and OpenStack names

- helm_lib/templates/_monitoring_prometheus_rules.tpl
- modules/040-node-manager/template_tests/module_test.go
Fix incorrect prometheus rules fo k8s 1.19.
Added tests for 'spec.groups' lenght for autoscaler and mcm prometeus rules 
Cluster with k8s 1.19 can not bootstrap
```changes
type: fix
summary: Fix incorrect prometheus rules fo k8s 1.19
```
> [node-manager] Fix incorrect prometheus rules fo k8s 1.19.

- modules/040-node-manager/hooks/internal/v1/nodegroup.go
- modules/040-node-manager/hooks/internal/v1alpha2/nodegroup.go
Fixup configurable kubelet log rotation.
When we set kubelet.containerLogMaxSize or kubelet.containerLogMaxFiles in nodeGroup, these settings were not applied to nodes.
```changes
type: fix
summary: Fixup configurable kubelet log rotation.
```
> [node-manager] fixup configurable kubelet log rotation

- werf.yaml
Fix CI
CI fails with single quote
```changes
section: ci
type: fix 
summary: Minor fix. Fix single quote.
```
> Fix changelog build

- werf.yaml
Fix quotes
CI fails
```changes
section: ci
type: fix
summary: Fix quotes in werf.yaml
```
> [ci] Fix changelog

- ee/candi/cloud-providers/openstack/layouts/simple-with-internal-network/master-node/main.tf
- ee/candi/cloud-providers/openstack/layouts/simple/master-node/main.tf
- ee/candi/cloud-providers/openstack/layouts/standard-with-no-router/master-node/main.tf
- ee/candi/cloud-providers/openstack/layouts/standard/base-infrastructure/main.tf
- ee/candi/cloud-providers/openstack/layouts/standard/master-node/main.tf
- ee/candi/cloud-providers/openstack/terraform-modules/master/main.tf
- ee/candi/cloud-providers/openstack/terraform-modules/master/variables.tf
- ee/candi/cloud-providers/openstack/terraform-modules/static-node/main.tf
- ee/candi/cloud-providers/openstack/terraform-modules/volume-zone/main.tf
- ee/candi/cloud-providers/openstack/terraform-modules/volume-zone/outputs.tf
- ee/candi/cloud-providers/openstack/terraform-modules/volume-zone/variables.tf
- ee/candi/cloud-providers/openstack/terraform-modules/volume-zone/versions.tf
Add terraform module volume-zone that helps to discover correct zone for OpenStack volumes. This module checks if provided compute zone exists for volumes. If it doesn't exist than no availability zone is set, and we assume that the default zone will be used.
Some private OpenStack clouds have different availability zones for volumes and computes.
```changes
section: candi
type: fix
summary: Automatically discover zone for volumes in OpenStack
```
> [candi] Automatically discover zone for volumes in OpenStack

- go.mod
- go.sum
Changes since v1.0.4:
- fix: add flag to start scheduling 'schedule' hook before first converge done. (Merged earlier in #977)
- fix: beforeHelm hook got empty snapshots for some bindings.
We use "beforeHelm" hooks to generate certificates if snapshots are empty. But "beforeHelm" hook got empty snapshots for bindings with `executeHookOnSynchronization: false` despite existing objects in cluster.
```changes
type: fix
summary: Fix empty snapshots in beforeHelm hooks.
```
> [deckhouse-controller] feat: update addon-operator to v1.0.5

- modules/300-prometheus/openapi/config-values.yaml
- modules/300-prometheus/openapi/values.yaml
- modules/340-monitoring-kubernetes/openapi/config-values.yaml
- modules/460-log-shipper/openapi/config-values.yaml
- modules/470-chrony/openapi/config-values.yaml
We have wrong case for kilobytes selector in memory requests
It wouldn't work
```changes
type: fix
summary: Fix kilobyte selector for memory requests (k instead of K)
```
> [global] Fix memory spelling for config

- modules/020-deckhouse/hooks/check_deckhouse_release.go
Suppress error on changelog unmarshaling error
If changelog yaml has some lint errors - release hook will fail
```changes
type: fix
summary: Warn on failed changelog build
```
> [deckhouse] fix changelog build during DeckhouseRelease

- modules/020-deckhouse/crds/deckhouse-release.yaml
- modules/020-deckhouse/hooks/update_deckhouse_image.go
Fix deckhouse CRD and generate timestamp for CR status message
Need to preserve any fields in CRD
```changes
type: fix 
summary: Fix DeckhouseRelease CRD
```
> [deckhouse] fix CRD and status generation

- modules/101-cert-manager/templates/annotations-converter/mutatingwebhookconfiguration.yaml
Change annotations converter mutatingwebhook timeout to 10 sec.
When object is relatively big, mutating webhook falls with error ```Internal error occurred: failed calling webhook "annotations-converter.webhook.cert-manager.io": Post "[https://annotations-converter-webhook.d8-cert-manager.svc:443/mutate?timeout=3s](https://annotations-converter-webhook.d8-cert-manager.svc/mutate?timeout=3s)": context deadline exceeded```
```changes
type: fix
summary: Change annotations converter mutatingwebhook timeout to 10 sec
```
> [cert-manager] Change annotations converter mutatingwebhook timeout to 10 sec

- ee/fe/modules/340-extended-monitoring/images/extended-monitoring-exporter/src/extended-monitoring.py
- ee/fe/modules/340-extended-monitoring/templates/extended-monitoring-exporter/podmonitor.yaml
* Start webserver immediately after running extended monitoring exporter
* Return 400 for the readiness probe requests if metrics cache is not populated
```
[2022-03-23 05:51:25,357] - Starting metrics loop
[2022-03-23 05:51:25,360] - Starting server
127.0.0.1 - - [23/Mar/2022 05:51:26] "GET /ready HTTP/1.1" 400 -
[2022-03-23 05:51:27,246] - Metrics are collected successfully. Batches quantity: 183
127.0.0.1 - - [23/Mar/2022 05:51:30] "GET /healthz HTTP/1.1" 200 -
127.0.0.1 - - [23/Mar/2022 05:51:30] "GET /ready HTTP/1.1" 200 -
127.0.0.1 - - [23/Mar/2022 05:51:40] "GET /healthz HTTP/1.1" 200 -
127.0.0.1 - - [23/Mar/2022 05:51:40] "GET /ready HTTP/1.1" 200 -
127.0.0.1 - - [23/Mar/2022 05:51:49] "GET /metrics HTTP/1.1" 200 -
127.0.0.1 - …
```
> [extended-monitoring] Start webserver immediately for the extended-monitoring-exporter

- ee/fe/modules/500-openvpn/templates/openvpn/authenticator.yaml
- ee/modules/110-istio/templates/kiali/authenticator.yaml
- modules/300-prometheus/templates/grafana/authenticator.yaml
- modules/500-dashboard/templates/dashboard/authenticator.yaml
- modules/500-upmeter/templates/status/authenticator.yaml
- modules/500-upmeter/templates/webui/authenticator.yaml
- modules/810-deckhouse-web/openapi/values.yaml
- modules/810-deckhouse-web/templates/authenticator.yaml
* Add a clause to set authenticator ingress certificate secret name
Urgent fix
```changes
type: fix
summary: Do not set ingress TLS certificate secret name if HTTPS mode is the OnlyInURI
impact: Fix deploy of DexAuthenticators to clusters with the OnlyInURI HTTPS mode
```
> [user-authn] Fix DexAuthenticator object template for https mode OnlyInURI

- docs/site/_includes/getting_started/kind/STEP_PREPARE.md
- docs/site/_includes/getting_started/kind/STEP_PREPARE_RU.md
pin the kindest/node version for cluster
Deckhouse doesn't always support latest kindest/node version. I suggest pin image version for solve this problem.
<details>
<summary>Screenshot</summary>
</details>
```changes
section: docs
type: fix
summary: "Pin kindest/node version"
```
> [docs] pin kindest/node image version

- ee/modules/030-cloud-provider-vsphere/hooks/handle_compatibility_flag.go
Get correct value from config
Compatibility mode doesn't work
```changes
type: fix
summary: Fix handle of compatibilityFlag in Deckhouse config
impact_level: medium
```
> [cloud-provider-vsphere] Fix handle of compatibilityFlag in Deckhouse config

- modules/301-prometheus-metrics-adapter/templates/config-map.yaml
Fix prometheus metrics adapter external metrics
This behavior was broken at November by applying 0.9.1 PMA version.
By default from version 0.9.0 PMA enforces to pass namespace label to a query.
By setting `namespaced:  false` we allow PMA to accept external metrics from all namespaces.
Then, if the metrics needed by your HPA need to be selected with a specific namespace label value, you should set it directly in a HPA's label selector.
Example: 
```
- type: External
external:
metric:
name: rmq_queue_length
selector:
labelSelector:
queue: my-queue
namespace: example
```
```changes
section: prometheus-metrics-adapter
type: fix
summary:  Restore HPA external metrics behavior
impact: Disable enforced namespace passing to a …
```
> [prometheus-metrics-adapter] remove namespace enforcing

- go.mod
- go.sum
- https://github.com/flant/shell-operator/pull/376
- https://github.com/flant/addon-operator/pull/310
Too much log messages on new releases.
```changes
type: fix
summary: Set debug level for snapshot info messages
```
> chore: update shell-operator, set debug level for snapshot info

- modules/020-deckhouse/hooks/update_deckhouse_image.go
- modules/020-deckhouse/hooks/update_deckhouse_image_test.go
Disable reaction on release events
We run hook every 15 seconds. I don't think we need this reaction which can lead to some artifacts
```changes
type: fix
summary: disable hook reaction on DeckhouseRelease events
```
> [deckhouse] disable release event

- ee/modules/030-cloud-provider-vsphere/images/vsphere-csi-plugin/Dockerfile
- ee/modules/030-cloud-provider-vsphere/templates/csi/cm.yaml
- ee/modules/030-cloud-provider-vsphere/templates/csi/controller.yaml
- modules/031-linstor/template_tests/module_test.go
- modules/031-linstor/templates/linstor-controller/linstorcontroller.yaml
- modules/031-linstor/templates/linstor-csi/linstorcsidriver.yaml
- modules/031-linstor/templates/linstor-ha-controller/deployment.yaml
- modules/031-linstor/templates/linstor-scheduler/deployment.yaml
- modules/031-linstor/templates/piraeus-operator/deployment.yaml
This PR enables automatic HA mode for LINSTOR server and all related components
Better high-avability for LINSTOR installations
```changes
type: fix
summary: LINSTOR module now supports high-availability
impact: Multimaster clusters will automatically turn LINSTOR into HA-mode
```
> [linstor] Enable HA mode

- .github/workflow_templates/suspend-channel.multi.yml
- .github/workflows/suspend-alpha.yml
- .github/workflows/suspend-beta.yml
- .github/workflows/suspend-early-access.yml
- .github/workflows/suspend-rock-solid.yml
- .github/workflows/suspend-stable.yml
- Put version into job name for easy approvement.
- Add suspend_tag input to suspend any version manually.
Fix problems in suspend workflow after failed suspend for v1.31.0.
```changes
section: ci
type: fix
summary: Fix suspend forkflow
```
> [ci] fix: detect version to suspend

- ee/modules/030-cloud-provider-vsphere/images/vsphere-csi-plugin/Dockerfile
- ee/modules/030-cloud-provider-vsphere/templates/csi/cm.yaml
- ee/modules/030-cloud-provider-vsphere/templates/csi/controller.yaml
This PR reverts last update of vSphere csi-driver as it is not properly tested yet
By an accident the changes of https://github.com/deckhouse/deckhouse/pull/1121 were merged from with https://github.com/deckhouse/deckhouse/pull/1147 we need to finish e2e tests before merging this.
> revert: Update vsphere csi-driver and enable snapshots

- global-hooks/discovery/cluster_dns_address.go
> fix: fixing a typo in the error message

- modules/031-linstor/monitoring/grafana-dashboards/storage/linstor_drbd.json
- modules/031-linstor/monitoring/prometheus-rules/drbd-devices.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-controller.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-csi-controller.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-csi-node.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-ha-controller.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-node.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-scheduler.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-storage-pools.yaml
- modules/031-linstor/monitoring/prometheus-rules/piraeus-operator.yaml
- modules/031-linstor/templates/monitoring.yaml
This PR introduces Grafana dashboard for LINSTOR and DRBD:
Observability for LINSTOR.
fixes https://github.com/deckhouse/deckhouse/issues/907
```changes
---
type: feature
summary: Grafana dashboard for LINSTOR
impact: Added Grafana dashboard to monitor LISNTOR cluster and DRBD resources
---
type: feature
summary: added alerts for LINSTOR
impact: Add alerts with the recommended course of action to monitor LINSTOR, Piraeus-operator, capacity of storage-pools and resources states
```
> [linstor] grafana dashboard and alerts

- modules/020-deckhouse/hooks/cleanup_deckhouse_releases.go
- modules/020-deckhouse/hooks/cleanup_deckhouse_releases_test.go
- modules/020-deckhouse/hooks/update_deckhouse_image.go
Fix hook which cleanup old Releases and also run it only at startup
Hook as invalid logic and sometimes in a race DeckhouseRelease can become Outdated
```changes
type: fix
summary: Fix cleanup DeckhouseReleases hook
```
> [deckhouse] Fix cleanup hook

- .github/workflow_templates/dispatch-slash-command.yml
- .github/workflows/dispatch-slash-command.yml
Fixed 'state is null' in slash command dispatcher workflow.
Workflow should not fail on regular comments.
```changes
section: ci
type: fix
summary: Fixed 'state is null' in slash command dispatcher workflow.
```
> [ci] fix: state is null in slash command dispatcher

- modules/031-linstor/templates/bashible-step.yaml
DRBD devices should not be queried by the LVM commands, so we configure global_filter in lvm.conf
fixes https://github.com/deckhouse/deckhouse/issues/1067
fixes https://github.com/deckhouse/deckhouse/issues/1174
upstream issue https://github.com/piraeusdatastore/piraeus-operator/issues/182
```changes
type: fix
summary: Add DRBD devices to blacklist on nodes
impact: DRBD devices should not be queried by LVM and multipath commands So we add DRBD devices into blacklist for multipath and configure global_filter in lvm.conf for them
```
> [linstor] Add DRBD devices to blacklist on nodes

- modules/031-linstor/templates/bashible-step.yaml
During installing drbd-utils on the node user can face with the following warning, just because the official config has 8 spaces instead of 4.
See https://github.com/LINBIT/drbd-utils/blob/dbd316a84044a83c8df2d6cca61da370e17d5dda/scripts/multipath/drbd.conf
to avoid warning while installing drbd-utils on the node 
```
Preparing to unpack .../drbd-utils_9.15.0-1_amd64.deb ...
Unpacking drbd-utils (9.15.0-1) ...
Setting up drbd-utils (9.15.0-1) ...
Configuration file '/etc/multipath/conf.d/drbd.conf'
==> File on system created by you or by a script.
==> File also in package provided by package maintainer.
What would you like to do about it ?  Your options are:
Y or I  : install the package maintainer's version
N or O  : keep your currently-installed version
D     : show the differences …
```
> [linstor] fix indents for multipath conf

- ee/modules/110-istio/templates/kiali/configmap.yaml
`istio.tracing.kiali.jaegerURLForUsers` parameter bugfix.
The `istio.tracing.kiali.jaegerURLForUsers` didn't work due to bug.
```changes
section: istio
type: fix
summary: `istio.tracing.kiali.jaegerURLForUsers` parameter bugfix.
```
> [istio][kiali] jaegerURLForUsers fix

- modules/301-prometheus-metrics-adapter/openapi/openapi-case-tests.yaml
- testing/openapi_cases/library.go
- testing/openapi_cases/openapi_cases_test.go
- Use "helmValues" in positive or negative cases if values.yaml to test effect of x-required-from.
- Use "x-test-focus: true" to run only specific cases.
1. Delete `modules/000-prom-test` before merging.
1. Documentation validation failed because of this example module.
Fix #186
```changes
section: tests
type: feature
summary: Support x-required-for-helm, add x-test-focus
```
> [tests] feat: support x-required-for-helm, add x-test-focus

- modules/040-node-manager/webhooks/validating/node_group
Add validation that NodeGroup has maxPerZone greater than minPerZone
More validations less errors from clients
```changes
type: fix
summary: Validate NodeGroup has maxPerZone greater than minPerZone
```
> [node-manager] Validate NodeGroup has maxPerZone greater than minPerZone

- modules/402-ingress-nginx/templates/controller/admission.yaml
Admission webhook was broken during the k8s 1.22 preparation
Ingresses could not be validated
```changes
type: fix
summary: Fix ingress admission webhook
```
> [ingress-nginx] restore admission webhook

- candi/bashible/common-steps/node-group/089_setup_timer_to_run_docker_stuck_containers_cleaner.sh.tpl
Ignore signal check because it can be 3 or 15 or some other.
This container was ignored but should have been considered stuck.
```
Mar 29 19:43:59 kube-master-1 dockerd[1848]: time="2022-03-29T19:43:59.088143054Z" level=info msg="Container 43e187a13c0a6d5e6115a578c7b853a0f883dc0b880d4b91753e4c9eaeec08e8 failed to exit within 30 seconds of signal 3 - using the force"
```
```changes
section: candi
type: fix
summary: Fix docker stuck containers cleaner pattern check
```
> [candi] Fix docker stuck containers cleaner pattern check

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_release.yml
Fix typo:  DECKHOUSE_REGISTRY_PATH -> DECKHOUSE_REGISTRY_HOST
Build for tag not run second werf build.
```changes
section: ci
type: fix
summary: Fix build for tags.
```
> [ci] fix: no second build for tag because of variable name typo

- ee/modules/110-istio/hooks/external_auth.go
AuthURL fix in external_auth.go hook.
There was wrong namespace for AuthURL in external_auth.go hook.
```changes
section: istio
type: fix
summary: AuthURL fix in external_auth.go hook.
```
> [istio] dex authn hook fix

- docs/site/_includes/getting_started/global/partials/INSTALL_OTHER.liquid
- docs/site/_includes/getting_started/global/partials/INSTALL_OTHER_RU.liquid
Getting started - Installing in a private environment: The `dont-use-public-control-plane-images` parameter was added to the dhctl command and was removed from the docker command.
It was a bug.
```changes
section: docs
type: fix
summary: Fix "Getting started - Installing in a private environment".
```
> [docs] Fix getting started

- .github/ci_templates/build.yml
- .github/ci_templates/tests.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_release.yml
Use gzip+base64 encoding to pass tests image name containing non-secret secrets between jobs.
tests_image_name may contain rw registry host. Github runner masks this host in base64 encoded output tests fail.  This host is non-secret, so it should be passed.
See [ValueEncoders.cs](https://github.com/actions/runner/blob/main/src/Sdk/DTLogging/Logging/ValueEncoders.cs).
```changes
section: ci
type: fix
summary: Pass tests_image_name output with rw registry host
```
> [ci] fix: avoid secret masking for tests_image_name output

- candi/openapi/init_configuration.yaml
Removed configOverrides requirement from InitConfiguration.
There is no **need** to specify this option.
```changes
section: candi
type: fix
summary: configOverrides field in the InitConfiguration is not required anymore
```
> [candi] Do not require configOverrides in the InitConfiguration

- dhctl/pkg/config/load.go
- dhctl/pkg/config/meta.go
- dhctl/pkg/config/meta_test.go
Trim ending slash from imagesRepo.
For example, `registry.deckhouse.io/deckhouse/ce/` -> `registry.deckhouse.io/deckhouse/ce`
And add some logs for preparing MetaConfig.
We got incorrect images in bashible steps (`registry.deckhouse.io/deckhouse/ce/:image-for-sandbox`) and we cannot finish bootstrap.
```changes
section: dhctl
type: fix
summary: Trim ending slash for imagesRepo
```
> [dhctl] Trim ending slash for imagesRepo

- modules/300-prometheus/templates/grafana/service.yaml
- modules/300-prometheus/templates/grafana/servicemonitor.yaml
Add bigger sample limit to Grafana service
The number of Grafana metrics grows with time and can exceed the default limit of 1000.
```changes
type: fix 
summary: Set Grafana sample limit to 5000
```
> [Prometheus] Add bigger sample limit to Grafana service

- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
Added more clarity to the section "How do I change the node-group of a static node" in the node-manager FAQ.
Fix: #1042 
```changes
section: docs
type: fix
summary: Added more clarity to the section 'How do I change the node-group of a static node' in the node-manager FAQ.
```
> [docs][node-manager] Update FAQ

- candi/bashible/common-steps/cluster-bootstrap/070_install_control_plane.sh.tpl
- dhctl/pkg/config/meta.go
- modules/040-node-manager/hooks/add_control_plane_role_to_master_ng.go
- modules/040-node-manager/hooks/add_control_plane_role_to_master_ng_test.go
Remove "node.kubernetes.io/exclude-from-external-load-balancers" label from control-plane nodes.
With this label we cannot use external load balancers with pods are scheduled to control-plane nodes.
```changes
section: dhctl
type: fix 
summary: Remove "node.kubernetes.io/exclude-from-external-load-balancers" label from control-plane nodes
---
type: fix 
summary: Add migration to remove "node.kubernetes.io/exclude-from-external-load-balancers" label from control-plane nodes
impact_level: hight
impact: |
node.kubernetes.io/exclude-from-external-load-balancers label will be deleted from master node group and can not be set manually in current release.
Without "node.kubernetes.io/exclude-from-external-load-balancers" label traffic can be directed to …
```
> [dhctl][candi][node-manager] Remove "node.kubernetes.io/exclude-from-external-load-balancers" label from control-plane nodes

- modules/500-upmeter/images/upmeter/.golangci.yaml
- modules/500-upmeter/images/upmeter/Makefile
- modules/500-upmeter/images/upmeter/pkg/agent/sender/client.go
- modules/500-upmeter/images/upmeter/pkg/check/series_test.go
- modules/500-upmeter/images/upmeter/pkg/db/connect.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/http.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/smoke_mini.go
- modules/500-upmeter/images/upmeter/pkg/server/remotewrite/syncer.go
- modules/500-upmeter/images/upmeter/pkg/server/server.go
- modules/500-upmeter/images/upmeter/pkg/util/env.go
Specify User-Agent in all HTTP requests
Makes it easier to track Upmeter in logs, makes it distinguishable from "Go-http-client/2.0"
```changes
type: chore
summary: Add User-Agent header to all requests
```
> [Upmeter] Add user-agents to http requests

- ee/modules/030-cloud-provider-vsphere/cloud-instance-manager/machine-class.checksum
- modules/030-cloud-provider-aws/cloud-instance-manager/machine-class.checksum
- modules/030-cloud-provider-azure/cloud-instance-manager/machine-class.checksum
- modules/030-cloud-provider-gcp/cloud-instance-manager/machine-class.checksum
- modules/030-cloud-provider-yandex/cloud-instance-manager/machine-class.checksum
- modules/040-node-manager/hooks/machineclass_checksum_assign_test.go
Ignore disk size when calculating checksum if disk size is equal to default size.
This is to prevent the checksum changing when specifying in the instance class a disk size equal to the default value.
```changes
section: cloud-provider
type: fix
summary: Ignore disk size when calculating checksum if disk size is equal to default size
```
> [cloud-provider] ignore default disk size for checksum calculation

- modules/150-user-authn/templates/dex/ingress.yaml
The rate limit is too strict at its current state. The rate limiter permanently blocks random users from authentication for environments where all users connect to the cluster through the VPN with the same IP address.
```changes
type: fix
summary: Increase authentication rate limit x2
```
> [user-authn] Increase authentication rate limit

- modules/150-user-authn/openapi/config-values.yaml
- modules/150-user-authn/openapi/openapi-case-tests.yaml
It was ok to have numbers in ids. Adding such a strict validation might break someone's configuration, which previously worked fine.
```changes
type: fix
summary: Allow having numbers in kubeconfig-generator ids
```
> [user-authn] Allow having numbers in kubeconfig-generator ids

- modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/control-plane-status.json
- modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/kube-etcd3.json
Improved dashboards for kube-apiserver and etcd.
New dashboards make it easy to detect problems with kube-apiserver and etcd.
```changes
section: grafana
type: feature
summary: Improved dashboards for kube-apiserver and etcd.
```
> [grafana] improved dashboards for kube-apiserver and etcd

- modules/500-upmeter/images/upmeter/pkg/kubernetes/access.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/smoke_mini.go
Resolve cluster domain with trailing dot.
Lets us avoid name search latency and expose DNS queries to the internet DNS.
```changes
type: fix
summary: Upmeter no longer exposes DNS queries to the Internet
```
> [Upmeter] Add trailing dot to cluster domain resolving

- ee/modules/030-cloud-provider-openstack/openapi/config-values.yaml
Value of `podNetworkMode` must be discovered from cloud-discovery-data and can be overwritten from Deckhouse config.
Default value broke automatic discovery that worked previously.
```changes
type: fix
summary: Remove default podNetworkMode from config-values
```
> [cloud-provider-openstack] Remove default podNetworkMode from config-values

- modules/402-ingress-nginx/monitoring/grafana-dashboards/ingress-nginx/vhost/vhost_detail.json
Closes https://github.com/deckhouse/deckhouse/issues/754?utm=ford_plain-number-sign
```changes
type: fix
summary: Make the VHost Detail dashboard show all locations by default
```
> [ingress-nginx] VHost Detail: select all locations by default

- modules/150-user-authn/docs/USAGE.md
- modules/150-user-authn/docs/USAGE_RU.md
Dex usage doc fix due to new default Gitlab settings.
The `Expire access tokens` checkbox is turned on by default in fresh Gitlab versions.
```changes
type: fix
summary: Dex usage doc fix due to new default Gitlab settings.
```
> [user-authn] Dex usage doc fix due to new default Gitlab settings

- candi/cloud-providers/aws/layouts/standard/base-infrastructure/main.tf
- candi/cloud-providers/aws/layouts/with-nat/base-infrastructure/main.tf
- candi/cloud-providers/aws/layouts/without-nat/base-infrastructure/main.tf
- candi/cloud-providers/aws/terraform-modules/security-groups/main.tf
- candi/cloud-providers/aws/terraform-modules/security-groups/outputs.tf
Allow ssh access to master nodes only from bastion (created by dhctl) for with-nat layout.
This will improve security.
```changes
type: fix
summary: Allow ssh access to master nodes only from bastion for with-nat layout
```
> [cloud-provider-aws] allow ssh access to master nodes only from bastion

- candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
**##** Description
Added kubelet container logs parameters for notManaged mode.
```changes
section: candi
type: feature
summary: added kubelet container logs parameters for notManaged mode
```
> [candi] added kubelet container logs parameters for notManaged mode

- modules/470-chrony/templates/daemonset.yaml
Increased `chronyc tracking` livenessProbe timeout to 15 seconds.
Sometimes chrony daemon takes longer than 5 seconds to provide tracking information, this leads to constant restarts of chrony container.
```changes
type: fix
summary: chrony's container livenessProbe's timeout increased from 5 to 15 seconds
```
> [chrony] Increase livenessProbe timeout

- docs/documentation/_plugins/openapi.rb
In some cases, the openAPI schema generator didn't display the mandatory use of the parameter.
```changes
section: docs
type: fix
summary: Proper display of the mandatory use of the parameter.
```
> [docs] Proper display of the mandatory use of the parameter on the site

- docs/documentation/Makefile
- docs/documentation/pages/search.html
- docs/documentation/pages/search_ru.html
- docs/documentation/search-index.json
- docs/documentation/werf-git-section.inc.yaml
- docs/documentation/werf.yaml
- docs/site/LOCAL_DEV.md
Added development mode to Jekyll in the documentation part of the site. Jekyll runs with trace and profiler In this mode.
Read docs/site/LOCAL_DEV.md for info.
```changes
section: docs
type: fix
summary: Add development mode to Jekyll in the documentation part of the site. Jekyll runs with trace and profiler In this mode.
```
> [docs] Add development mode

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/ebpf-exporter.yaml
Removed unneeded metrics for pod level OOMs so that many-to-many matching error won't happen.
Fixed error:
```
found duplicate series for the match group {} on the right hand-side of the operation: [{__name__="ebpf_exporter_oom_kills", cgroup_path="/sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0391ccfb_b24a_44d3_bd23_27509e4e2830.slice/cri-containerd-9e8ce7cf657f09d15451b077a13848b0f560c7e2296ff0464f97d3ea0ef06a90.scope", container="kube-rbac-proxy", global_oom="0", instance="172.16.2.230:9434", job="ebpf-exporter", node="kube-stage-3commas-staging-spot-0256e204-7d49b-2lgdg", tier="cluster"}, 
{__name__="ebpf_exporter_oom_kills", cgroup_path="/sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0367bc0c_f874_4d18_ac4a_490 …
```
> [monitoring-kubernetes] Removed many-to-many matching case in ebpf-exporter recording rules

- modules/040-node-manager/webhooks/validating/node_group
NodeGroup validation to forbid minPerZone = 0 while maxPerZone > 0.
(I am not sure it is a relevant solution, there could be NG without nodes but they must autoscale after deploying some Pod with appropriate nodeSelector).
Closes #1241.
```changes
section: node-group
type: feature
summary: NodeGroup validation to forbid minPerZone = 0 while maxPerZone > 0
```
> [node-group] minPerZone = 0 while maxPerZone > 0 validation

- modules/031-linstor/images/linstor-csi/Dockerfile
- modules/031-linstor/images/linstor-server/Dockerfile
upstream issue: https://github.com/piraeusdatastore/linstor-csi/pull/158
Every mkfs command reports:
```
mke2fs 1.44.5 (15-Dec-2018)\next2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/drbd1000 is mounted.\
```
These messages appear in csi-provisioned volumes events.
Better UX
```changes
type: fix
summary: fix mtab warning for mkfs commands
```
> [linstor] fix mtab warning for mkfs commands

- modules/042-kube-dns/images/sts-pods-hosts-appender-webhook/main.go
- modules/042-kube-dns/templates/sts-pods-hosts-appender-webhook/deployment.yaml
- modules/042-kube-dns/templates/sts-pods-hosts-appender-webhook/service.yaml
Changed sts-pods-hosts-appender-webhook probes from tcpSocket to httpGet.
Fixes https://github.com/deckhouse/deckhouse/issues/1165.
```changes
type: fix
summary: Changed sts-pods-hosts-appender-webhook probes from tcpSocket to httpGet.
```
> [kube-dns][sts-pods-hosts-appender-webhook] probes tcp -> http

- go_lib/set/set_test.go
- modules/040-node-manager/hooks/discover_apiserver_endpoints.go
Fix panic when we get nil instead of a string
When pod is nt ready, the hooks panics and blocks deckhouse main queue
```changes
type: fix
summary: Fix panic
```
> [node-mananger] fix panic in apiserver endpoints discovery

- candi/bashible/common-steps/cluster-bootstrap/070_install_control_plane.sh.tpl
Add proper labels and taints on cluster bootstrap to master nodes.
On previous generation of bootstrap scripts we loose some taints on master nodes.
```changes
section: candi
type: fix
summary: add proper labels and taints on cluster bootstrap to master nodes
```
> [candi] add proper labels and taints on cluster bootstrap to master nodes

- modules/040-control-plane-manager/hooks/audit_policy.go
- modules/040-control-plane-manager/hooks/audit_policy_test.go
Add listing object from all namespaces to default audit policy.
Helps debugging kube-apiserver OOMs caused by list operations.
```changes
type: feature
summary: Add listing object from all namespaces to default audit policy.
```
> [control-plane-manager] Add list from all namespaces to audit log by default

- docs/documentation/_includes/openapi-tippy.html
Increased maximum width of tears in openAPI schemas as the log parameters path didn't fit tip's maximum width.
```changes
section: docs
type: fix
summary: Increased maximum width of tears in openAPI schemas as the log parameters path didn't fit tip's maximum width.
```
> [docs] Increase maximum width of tips in openAPI schemas

- candi/bashible/bashible.sh.tpl
Add check that first line of new bashible contains string `#!/usr/bin/env bash`.
Sometimes bashible.sh is empty. It can happen if bashible-new.sh contains empty line. But I can't reproduce it. So I just add more checks to prevent this situation.
```changes
section: candi
type: fix
summary: Protect bashible.sh from corruption
```
> [candi] Protect bashible.sh from corruption

- candi/bashible/common-steps/all/001_set_short_hostname.sh.tpl
- modules/021-kube-proxy/images/init-container/nodeport-bind-address.sh
Set short hostname if itsn't and force short hostname for kube-dns'es nodeport-bind-address.sh init-container.
Recently we [decided](https://fox.flant.com/sys/antiopa/-/merge_requests/2517) to set short hostname only on first bashible run due to some hostnamectl + dbus issues. But there were cases when someone changed the hostname to fqdn style, so we now set hostname short if it isn't.
Closes https://github.com/deckhouse/deckhouse/issues/1043.
```changes
type: fix
summary: Set short hostname if itsn't and force short hostname for kube-dns'es nodeport-bind-address.sh init-container
impact: kube-proxy pods will restart.
```
> [candi][kube-proxy] set short hostname if itsn't and force short hostname for nodeport-bind-address.sh

- modules/150-user-authn/hooks/discover_publish_api_cert.go
Closes https://github.com/deckhouse/deckhouse/issues/1045
```changes
type: fix
summary: Do not wait for deleting publish API secret
```
> [user-authn] Do not wait for deleting publish API secret

- .github/ci_templates/helper_jobs.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/on-pull-request-labeled.yml
- .github/workflows/validation.yml
Add `state: "all"` to pull request filter, it is [default to "open"](https://docs.github.com/en/rest/reference/pulls#list-pull-requests).
Prevent failing on unlabel closed pull requests.
```changes
section: ci
type: chore
summary: Prevent failing on unlabel closed pull requests.
```
> [ci] fix: support closed PRs in pull_request_info_job

- ee/modules/600-flant-integration/templates/madison/additional-alert-relable-config.yaml
As for now, all global problems are marked as application-level issues, which is not accurate. For example, alerts about node-local-dns pods being unavailable are application-level now.
```changes
type: fix
summary: Set the tier = cluster label for alerts without the namespace label
```
> [prometheus] Alerts with no namespace go to clusters

- modules/300-prometheus/templates/alertmanager/additional-configs-secret.yaml
Handle path prefix in CustomAlertmanager CR
Path prefix was forgotten in templates
```changes
type: fix
summary: Handle path prefix for CustomAlertmanager
```
> [prometheus] handle custom alertmanager path

- modules/300-prometheus/docs/FAQ_RU.md
Description
Clarification in GrafanaAdditionalDatasource documentation to make it easier to find and specify the correct DataSource type
The documentation is not precise enough, which leads to problems when specifying the datasource type
> Clarify GrafanaAdditionalDatasource type option RU

- docs/documentation/.helm/templates/20-ingress.yaml
- docs/site/.helm/templates/20-ingress.yaml
Remove ingressClassName from the site Ingress templates
```changes
section: docs
type: chore
summary: Remove ingressClassName from the site Ingress templates
```
> [docs] Remove ingressClassName from the site Ingress templates

- ee/fe/modules/500-openvpn/openapi/values.yaml
Add forgotten param effectiveStorageClass to openapi spec
```changes
type: fix
summary: Add forgotten param effectiveStorageClass to openapi spec
```
> [openvpn] add forgotten param effectiveStorageClass to openapi spec

- modules/300-prometheus/hooks/prometheus_disk.go
Fixed panic when AllowVolumeExpansion is nil.
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x23c3973]
goroutine 64 [running]:
github.com/deckhouse/deckhouse/modules/300-prometheus/hooks.applyStorageClassFilter(0xc000434940, 0x700, 0xc0116d6000, 0xc005d26180, 0xc0031f3100)
/deckhouse/modules/300-prometheus/hooks/prometheus_disk.go:107 +0x113
github.com/flant/addon-operator/pkg/module_manager.NewHookConfigFromGoConfig.func1(0xc000434940, 0xc000434940, 0xc0031f3100, 0x685, 0x700)
/go/pkg/mod/github.com/flant/addon-operator@v1.0.6-0.20220328102438-d32b26271231/pkg/module_manager/global_hook_config.go:313 +0x2f
github.com/flant/shell-operator/pkg/kube_events_manager.ApplyFilter(0x0, 0x0, 0xc001664770, …
```
> [prometheus] Fix null pointer dereference in prometheus_disk.go hook

- .github/scripts/js/constants.js
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Add CI for running e2e 1.23 kubernetes tests
```changes
section: ci
type: chore
summary: Add 1.23 kubernetes e2e tests
```
> [ci] add 1.23 for e2e tests

- ee/fe/modules/500-openvpn/hooks/easyrsa_migration.go
Fixed sts api version in migration hook
This solves the problem of deleting the old sts in the migration hook
```changes
type: fix
summary: Fixed statefulSet apiVersion in a migration hook.
```
> [openvpn] fix sts api version in migration hook

- ee/fe/modules/500-openvpn/openapi/config-values.yaml
- ee/fe/modules/500-openvpn/openapi/doc-ru-config-values.yaml
Set default value for loadbalancer object in the OpenAPI schema
This fixes a bug in the OpenAPI schema that occurs when using the LoadBalancer inlet.
```changes
type: fix
summary: Set default value for loadbalancer object in the OpenAPI schema.
```
> [openvpn] Set default value for loadbalancer object in the OpenAPI schema

- modules/031-linstor/docs/FAQ.md
- modules/031-linstor/docs/FAQ_RU.md
Describe one error case from @duckhawk, when nodes were eventually evicted from the cluster due to long downtime.
Better UX
```changes
type: chore
summary: Add an error case to FAQ, when nodes were eventually evicted from the cluster
```
> [linstor] Update FAQ: add error case

- .github/pull_request_template.md
Describe `impact_level` better in PR template.
It is not clear when to set it.
```changes
section: ci
type: chore
summary: Better doc for `impact_level`.
```
> Chore: update changes description in PR template

- ee/candi/cloud-providers/vsphere/openapi/cluster_configuration.yaml
- ee/modules/030-cloud-provider-vsphere/hooks/vsphere_cluster_configuration.go
- ee/modules/030-cloud-provider-vsphere/hooks/vsphere_cluster_configuration_test.go
1. If `zoneTagCategory` is not set, set to default `k8s-zone`.
2. If `regionTagCategory` is not set, set to default `k8s-region`.
3. Error if `zones` is not set in module config in Hybrid cluster mode.
Module config values for cloud-provider-vpshere module overrides values from secret `d8-provider-cluster-configuration`.
But in hybrid mode, we cannot have secret, and defaults from secret do not work. So we need to check additionally config values from module and use defaults if they are not set.
```changes
type: fix
summary: setting default values in hybrid mode.
```
> [cloud-provider-vsphere] setting default values in hybrid mode

- modules/500-upmeter/images/upmeter/pkg/probe/checker/http.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/prometheus.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/prometheus_metrics_adapter.go
Use timeout in insecure HTTP client in agent.
Probe checks won't be able to stuck indefinitely.
```changes
type: fix
summary: Use finite timeout in agent insecure HTTP client
```
> [upmeter] use timeout in insecure client

- modules/500-dashboard/images/dashboard/Dockerfile
Dashboard upgrade from 2.2.0 to 2.5.1
Closes https://github.com/deckhouse/deckhouse/issues/1276.
```changes
type: chore
summary: Dashboard upgrade from 2.2.0 to 2.5.1
```
> [dashboard] upgrade from 2.2.0 to 2.5.1

- modules/031-linstor/images/piraeus-operator/patches/README.md
- modules/031-linstor/images/piraeus-operator/patches/restore-evicted-satellites.diff
This PR adding patch to automatically restore evicted nodes in linstor 
LINSTOR automatically evict the nodes from the cluster after 2 hours of unavailability.
This adds functionality to automatically recover such nodes if they came back.
```changes
type: fix
summary: automatically recover evicted nodes in LINSTOR
```
> [linstor] satellites: restore evicted satellites if pod exists

- ee/modules/110-istio/templates/kiali/configmap.yaml
(cherry picked from commit 00d4b7a3a8c66cd1e5dc457ae5b97b2fb950f44c) #1196 
`istio.tracing.kiali.jaegerURLForUsers` parameter bugfix.
The `istio.tracing.kiali.jaegerURLForUsers` didn't work due to bug.
```changes
section: istio
type: fix
summary: The `istio.tracing.kiali.jaegerURLForUsers` parameter bugfix.
```
> [istio][kiali] jaegerURLForUsers fix (#1196)

- candi/cloud-providers/aws/layouts/standard/base-infrastructure/main.tf
- candi/cloud-providers/aws/layouts/with-nat/base-infrastructure/main.tf
- candi/cloud-providers/aws/layouts/without-nat/base-infrastructure/main.tf
- candi/cloud-providers/aws/terraform-modules/security-groups/main.tf
- candi/cloud-providers/aws/terraform-modules/security-groups/outputs.tf
Reverts deckhouse/deckhouse#1217.
[PR #1217](deckhouse/deckhouse#1217) breaks terraform state and manual operations required, so auto converge doesn't work. Further work will be done in https://github.com/deckhouse/deckhouse/pull/1301.
```changes
type: fix
summary: Allow ssh access to master nodes only from bastion for with-nat layout
```
> Revert "[cloud-provider-aws] allow ssh access to master nodes only from bastion"

- .github/render-workflows.sh
Add --user option for proper permission on generated workflows.
Prevent "file is readonly" warnings for Linux users.
```changes
section: ci
type: chore
summary: Add --user option for proper permission on generated files on Linux
```
> [ci] fix: --user option for proper permission on generated files

- .github/ci_templates/build.yml
- .github/ci_templates/e2e_tests.yml
- .github/ci_templates/helper_jobs.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflow_templates/validation.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_release.yml
- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-early-access.yml
- .github/workflows/deploy-rock-solid.yml
- .github/workflows/deploy-stable.yml
- .github/workflows/deploy-web-stage.yml
- .github/workflows/deploy-web-test.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- .github/workflows/schedule-cleanup.yml
- .github/workflows/suspend-alpha.yml
- .github/workflows/suspend-beta.yml
- .github/workflows/suspend-early-access.yml
- .github/workflows/suspend-rock-solid.yml
- .github/workflows/suspend-stable.yml
- testing/cloud_layouts/script.sh
Dhctl doesn't support different repos for deckhouse image and module images. Use dev-registry and tag suffixes for e2e tests in test repositories as a workaround.
Chore: finally remove CI_PIPELINE_CREATED_AT.
We need to run e2e tests in test repositories.
```changes
section: ci
type: fix
summary: Fix image name for running e2e tests in test repositories
```
> [ci] fix: proper image name for e2e in test repos

- candi/bashible/common-steps/node-group/052_configure_kubernetes_api_proxy.sh.tpl
Copy /etc/kubernetes/kubernetes-api-proxy/nginx.conf file from etc/kubernetes/kubernetes-api-proxy/nginx_new.conf if etc/kubernetes/kubernetes-api-proxy/nginx.conf is absent.
When kubernetes-api-proxy starts for first time, it needs /etc/kubernetes/kubernetes-api-proxy/nginx.conf file. But file is absent.
This PR  fixes this in kubernetes-api-proxy configuration script.
```changes
section: candi
type: fix
summary: fix startup config in kubernetes api proxy configuration script
```
> [candi] fix startup config in kubernetes api proxy configuration script

- modules/045-snapshot-controller/templates/snapshot-controller/deployment.yaml
- modules/045-snapshot-controller/templates/snapshot-validation-webhook/deployment.yaml
Fix `replicas` and `minAvailable` for snapshot-controller
Manifests for snapshot-controller contain mistake it does not allow deckhouse to deploy the release:
```
{"binding":"ReloadAllModules","event.type":"OperatorStartup","level":"error","module":"snapshot-controller","msg":"ModuleRun failed in phase 'CanRunHelm'. Requeue task to retry after delay. Failed count is 38. Error: helm upgrade failed: post-upgrade hooks failed: unable to build kubernetes object for post-upgrade hook snapshot-controller/templates/snapshot-controller/deployment.yaml: error validating \"\": error validating data: [ValidationError(PodDisruptionBudget.spec): unknown field \"replicas\" in io.k8s.api.policy.v1beta1.PodDisruptionBudgetSpec, ValidationError(PodDisruptionBudget.spec): unknown field \"strategy\" in …
```
> [snapshot-controller] Fix deployment

- dhctl/pkg/kubernetes/actions/deckhouse/log.go
Add InsecureSkipTLSVerifyBackend option for requesting deckhouse logs.
Some times dhctl can not get logs for deckhouse pod and bootstrap finish with timeout error.
```changes
section: dhctl
type: fix
summary: Add InsecureSkipTLSVerifyBackend option for requesting deckhouse logs
```
> [dhctl] Add InsecureSkipTLSVerifyBackend option for requesting deckhouse logs

- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/pkg/config/meta.go
- dhctl/pkg/kubernetes/actions/deckhouse/log.go
- dhctl/pkg/operations/bootstrap.go
- modules/040-node-manager/hooks/create_master_node_group.go
- modules/040-node-manager/hooks/create_master_node_group_test.go
Move creating master ng to hook from dhctl.
In hook, if master node group exists, hook should not affect any changes in master node group.
Right way to creating master node group in node-manager immediately after deploy node group crd.
And we have race between creating master node group and control-plane manager. Control plane manager can redeploy kubelet config  faster than creating master node group from dhctl and we can get negative effects (can not get logs, because cert regenerated without node ip, etc...)
```changes
type: feature
summary: Add hook for creating master node group
---
section: dhctl
type: feature
summary: Remove creating master node group
```
> [node-manager][dhctl] Move creating master ng to hook from dhctl

- ee/fe/modules/600-namespace-configurator/hooks/handler.go
- ee/fe/modules/600-namespace-configurator/hooks/handler_test.go
Exclude namespaces by heritage labels.
Upmeter deletes namespaces faster than deckhouse can put labels or annotations on them.
```changes
section: namespace-configurator
type: fix
summary: Exclude upmeter probe namespaces from namespace-configurator snapshots.
```
> [namespace-configurator] Ignore upmeter probe namespaces

- modules/300-prometheus/docs/USAGE.md
- modules/300-prometheus/docs/USAGE_RU.md
Add app-root annotation for example `Connecting Prometheus to an external Grafana instance`
By default our prometheus redirect from `/` to `/prometheus/graph`.
Who use our example, will get 404 error for `https://domain/` url.
> [prometheus] Add app-root annotation for example `Connecting Prometheus to an external Grafana instance`

- deckhouse-controller/cmd/deckhouse-controller/main.go
- go.mod
- go.sum
- set runtime config dependency in operator instance (related: https://github.com/flant/addon-operator/pull/318 https://github.com/flant/shell-operator/pull/352)
- set debug log level for 'snapshot info' messages (related: https://github.com/flant/shell-operator/pull/376)
Fix server side error on running `addon-operator config list`, reduce noise in logs.
```changes
section: ci
type: chore
summary: Fix error on 'config list' command, log level for snapshot info
```
> [deckhouse-controller] fix: error on 'config list' command, log level for snapshot info

- docs/documentation/_plugins/openapi.rb
This reverts commit 3ec2847b0bc7c7ba6190c1ecef73aa25c98d8943 (#1272).
Changes in #1272 were wrong.
```changes
section: docs
type: fix
summary: Revert OpenAPI generator changes.
```
> Revert "[docs] Fix openAPI schema generator (#1272)"

- modules/500-upmeter/images/upmeter/cmd/upmeter/main.go
- modules/500-upmeter/images/upmeter/cmd/upmeter/parse_args.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_deployment.go
- modules/500-upmeter/templates/upmeter-agent/daemonset.yaml
- modules/500-upmeter/templates/upmeter/statefulset.yaml
Move disabled probes from env variable to cmd args to correctly use kingpin library for the handling of a slice of strings.
Fixes ignored disabled probes when there are more than one of them
Low impact level because it is a follow-up fix after the bug was introduced
```changes
type: fix
summary: Fix the application of disabled probes
```
> [Upmeter] Fix setting disabled probes

- candi/cloud-providers/azure/openapi/cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/doc-ru-instance_class.yaml
- candi/cloud-providers/azure/openapi/instance_class.yaml
- candi/cloud-providers/azure/terraform-modules/master-node/main.tf
- candi/cloud-providers/azure/terraform-modules/master-node/variables.tf
- candi/cloud-providers/azure/terraform-modules/static-node/main.tf
- candi/cloud-providers/azure/terraform-modules/static-node/variables.tf
- modules/030-cloud-provider-azure/cloud-instance-manager/machine-class.checksum
- modules/030-cloud-provider-azure/cloud-instance-manager/machine-class.yaml
- Accelerated networking is enabled by default for new machine-controller-manager instances.
- If you want your existing nodes to have accelerated networking enabled, you have to [roll out update](https://deckhouse.io/en/documentation/v1/modules/040-node-manager/faq.html#how-do-i-redeploy-ephemeral-machines-in-the-cloud-with-a-new-configuration) them or just delete.
- To disable set `.spec.acceleratedNetworking` to `false` in AzureInstanceClass.
- The master and static nodes are set to `acceleratedNetworking=false` by default to automatically add it to AzureClusterConfiguration, which will allow us to change the default value later without any problems.
- To enable set `.spec.acceleratedNetworking` to `true` and do `dhctl converge`.
[Accelerated …
> [cloud-provider-azure] Enable accelerated networking for new machine-controller-manager instances

- modules/460-log-shipper/images/vector/Dockerfile
- modules/460-log-shipper/images/vector/reloader
Use pkill instead of pidof.
By executing pkill reloader sends a reloading signal to every vector process, which is technically correct.
Closes #1427
```changes
type: fix
summary: Send reloading signal to all vector processes in a container on config change.
```
> [log-shipper] Fix reloading signal

- docs/documentation/_data/sidebars/main.yml
Added the Storage section to the sidebar of the site. The section has the following modules:
- linstor
- ceph-csi
- local-path-provisioner
```changes
section: docs
type: fix
summary: Added the Storage section to the sidebar of the site.
```
> [docs] New sidebar section on the site - Storage

- modules/460-log-shipper/hooks/internal/vector/config/testdata/config_3.json
- modules/460-log-shipper/hooks/internal/vector/model/destination.go
- modules/460-log-shipper/hooks/internal/vector/model/model.go
- modules/460-log-shipper/hooks/testdata/es-5x.json
- modules/460-log-shipper/hooks/testdata/multiline.json
- modules/460-log-shipper/hooks/testdata/multiple-dests.json
- modules/460-log-shipper/hooks/testdata/namespaced-source.json
- modules/460-log-shipper/hooks/testdata/one-dest.json
- modules/460-log-shipper/hooks/testdata/pair-datastream.json
- modules/460-log-shipper/hooks/testdata/simple-pair.json
Migrate fields according to the guide
https://vector.dev/highlights/2021-12-28-0-19-0-upgrade-guide/#elasticsearch-sink-deprecated-fields
```changes
type: fix
summary: Migrate deprecated elasticsearch fields
```
> [log-shipper] Migrate deprecated elasticsearch fields

- modules/460-log-shipper/hooks/internal/vector/destination.go
- modules/460-log-shipper/hooks/internal/vector/model.go
- modules/460-log-shipper/hooks/internal/vector/testdata/config/config_3.json
- modules/460-log-shipper/hooks/testdata/es-5x.json
- modules/460-log-shipper/hooks/testdata/multiline.json
- modules/460-log-shipper/hooks/testdata/multiple-dests.json
- modules/460-log-shipper/hooks/testdata/namespaced-source.json
- modules/460-log-shipper/hooks/testdata/one-dest.json
- modules/460-log-shipper/hooks/testdata/pair-datastream.json
- modules/460-log-shipper/hooks/testdata/simple-pair.json
Backport https://github.com/deckhouse/deckhouse/pull/1453
```changes
type: fix
summary: Migrate deprecated elasticsearch fields
```
> [log-shipper] elasticsearch upgrade fix

- docs/documentation/_data/i18n.yml
- docs/documentation/_includes/SUPPORTED_VERSIONS.md
- docs/documentation/werf-git-section.inc.yaml
- docs/documentation/werf.yaml
- modules/810-deckhouse-web/images/web/werf.inc.yaml
Mark Kubernetes version used by default in the supported versions table.
```changes
section: docs
type: fix
summary: Highlight default Kubernetes version in the supported versions table on the site.
```
> [docs] Highlight default Kubernetes version

- candi/cloud-providers/aws/docs/LAYOUTS.md
- candi/cloud-providers/aws/docs/LAYOUTS_RU.md
- docs/site/_includes/getting_started/aws/partials/config.yml.standard.ce.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.standard.ee.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.with_nat.ce.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.with_nat.ee.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.without_nat.ce.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.without_nat.ee.inc
- docs/site/_includes/getting_started/aws/partials/resources.yml.ha.inc
- docs/site/_includes/getting_started/aws/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/aws/partials/resources.yml.production.inc
Change the diskType from the gp2 to gp3 in the Getting started for AWS.
```changes
section: docs
type: fix
summary: Change the diskType from the gp2 to gp3 in the Getting started for AWS.
```
> [docs] Change the diskType from the gp2 to gp3 in the Getting started for AWS

- docs/site/_includes/head-site.html
Sets sidebar accordion mode to false to not collapse the expanded item of the sidebar when expanding the item.
```changes
section: docs
type: feature
summary: Don't collapse the expanded item in the sidebar when expanding the item.
```
> [docs] Disable accordion mode in the sidebar

- ee/fe/modules/340-extended-monitoring/images/image-availability-exporter/Dockerfile
- ee/fe/modules/340-extended-monitoring/monitoring/prometheus-rules/image-availability/exporter-health.yaml
- ee/fe/modules/340-extended-monitoring/template_tests/image_availability_test.go
- ee/fe/modules/340-extended-monitoring/templates/image-availability-exporter/deployment.yaml
1. Fixed alerting so that quick exporter malfunctions won't generate a useless grouping alert.
2. Fixed stuck Prometheus scrapes.
Upstream PR: https://github.com/deckhouse/k8s-image-availability-exporter/pull/48
The main change is a bugfix to a stuck metrics scrape.
```changes
type: fix
summary: Exporter won't get suck on scrapes and it won't generate a useless grouping alert
```
> [extended-monitoring] Image availability exporter v0.3.2

- modules/040-node-manager/hooks/update_node_group_status.go
Events with messages longer than 1024 bytes fail apiserver validation.
Avoid hook failures:
```
Module hook failed, requeue task to retry after delay. Failed count is 1. Error: 1 error occurred:
* Create object: events.k8s.io/v1/Event/default/: Event "ng-node-qgvpq" is invalid: message: Invalid value: "": can have at most 1024 characters
```
```changes
type: fix
summary: Truncate event message to allowed maximums in update_node_group_status hook
```
> [node-manager] Truncate event message to allowed maximums in update_node_group_status hook

- candi/bashible/common-steps/node-group/051_remove_old_kubernetes_api_proxy.sh.tpl
Fixed race condition between old kubernetes-api-proxy-configrator and new kubernetes-api-proxy bashible step.
When we migrate from old kubernetes-api-proxy-configurator to kubernetes-api-proxy static pod, we stop kubernetes-api-proxy-configurator.timer.
But in some cases old kubernetes-api-proxy-configurator runs in parallel with step 052_configure_kubernetes_api_proxy.sh and damages /etc/kubernetes/kubernetes-api-proxy/nginx_new.conf file.
To prevent this, we also need to stop kubernetes-api-proxy-configurator.service.
```changes
section: candi
type: fix
summary: fixed race condition between old kubernetes-api-proxy-configurator and bashible step
```
> [candi] fixed race condition between old kubernetes-api-proxy-configurator and bashible step

- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/instance_class.yaml
- modules/030-cloud-provider-yandex/cloud-instance-manager/machine-class.checksum
- modules/030-cloud-provider-yandex/cloud-instance-manager/machine-class.yaml
- modules/030-cloud-provider-yandex/hooks/yandex_cluster_configuration_test.go
* New instances created by `machine-controller-manager` will use the `standard-v3` platform by default.
* If you need to change the platform for existing instances, you have to roll out update them or just delete machines in `d8-cloud-instance-manager` namespace.
* To change the default platform, use the `.spec.platformID` parameter in `YandexInstanceClass`.
* The master and static nodes are set to default platform `standard-v2` to be automatically added to `YandexClusterConfiguration`, which will allow us to change the default value later without any problems.
* To change the platform, use the `.masterNodeGroup.instanceClass.platform` parameter in `YandexClusterConfiguration` and run `dhctl converge`.
When setting a default value in a spec, it will be set in all YandexInstanceClass …
> [cloud-provider-yandex] Change default platform to standard-v3 for new instances created by machine-controller-manager

- canary.json
Set 6 waves and 30m between them for the canary deployment of the stable release channel.
```changes
section: chore
type: fix
summary: Set 6 waves and 30m between them for the canary deployment of the stable release channel.
```
> [chore] Update canary deploy settings for the stable release channel

- docs/site/_includes/channel-menu.html
- docs/site/werf.yaml
Bump web-router to use Sprig functions. Update the channel menu template to hide a patch version number in the dropdown menu on the site
```changes
section: docs
type: feature
summary: Hide a patch version number in the dropdown menu on the site.
```
> [docs] Hide a patch version number in the dropdown menu on the site

- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
- dhctl/pkg/app/bootstrap.go
- dhctl/pkg/config/meta.go
- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
- docs/site/_includes/getting_started/global/partials/INSTALL_OTHER.liquid
- docs/site/_includes/getting_started/global/partials/INSTALL_OTHER_RU.liquid
- go.sum
Use images for control-plane from Deckhouse registry.
Deprecate and show warning if client use `dont-use-public-control-plane-images` flag.
In some regions and in closed environments clients can not use public images for control plane.
Now dhctl use our images and clients do not need to use special flag.
```changes
section: dhctl
type: feature 
summary: For new Deckhouse installations images for control-plane (image for pause container, for example) will be used from the Deckhouse registry.
```
> [dhctl] Use images for control-plane from Deckhouse registry instead public images

- ee/fe/modules/500-openvpn/images/easyrsa-migrator/easyrsa-migrator.go
Regardless of the status of the certificate, if the file was not found, we try to read it from the pki/revoked directory.
In some older installations, certificates were left in the pki/revoked directory after unrevoke. This bug has already been fixed a long time ago.
```changes
type: fix
summary: improved migration to secrets
```
> [openvpn] improved migration to secrets

- go_lib/hooks/storage_class_change/hook.go
- modules/500-upmeter/templates/upmeter-agent/daemonset.yaml
- modules/500-upmeter/templates/upmeter/statefulset.yaml
Upmeter server does not work with emptydirs because migrations init container is skipped on emptyDir
Upmeter does not work on emptydirs
```changes
type: fix
summary: Fix non-working upmeter server on emptyDirs
```
> [upmeter] Fix missing init container with migrations for emptyDir

- modules/040-node-manager/templates/node-group/_bootstrap_script.tpl
Fix unset variable error for static nodes bootstrap
After bootstrap node can not reboot because script is terminated. We used unset variable.  
```changes
type: fix
summary: Static node can not reboot after bootstrap.
```
> [node-manager] Static node can not reboot after bootstrap.

- candi/cloud-providers/aws/layouts/standard/base-infrastructure/main.tf
- candi/cloud-providers/aws/layouts/with-nat/base-infrastructure/main.tf
- candi/cloud-providers/aws/layouts/without-nat/base-infrastructure/main.tf
- candi/cloud-providers/aws/terraform-modules/vpc-peering/main.tf
- candi/cloud-providers/aws/terraform-modules/vpc-peering/variables.tf
Added the ability to configure peering connections to the without-nat and standard layouts.
This is necessary to simplify the configuration of the peering connection and eliminate possible errors during manual configuration.
```changes
module: cloud-provider-aws
type: feature
description: Added the ability to configure peering connections to the without-nat and standard layouts.
```
> [cloud-provider-aws] add peering for without-nat and standard layouts

- docs/site/_includes/getting_started/global/step_cluster_setup.html
- docs/site/_includes/getting_started/global/step_cluster_setup_ru.html
Don't add layout description to the link title attribute in the Getting Started as the description content format is not suitable for the title.
```changes
section: docs
type: fix
summary: Don't add layout description to the link title attribute in the Getting Started as the description content format is not suitable for the title.
```
> [docs] Don't add layout description to the link title attribute in the Getting Started

- docs/site/_includes/getting_started/kind/STEP_PREPARE.md
- docs/site/_includes/getting_started/kind/STEP_PREPARE_RU.md
The `kind` image used in the Getting Started changed to v1.21. The reason is that there are some problems in v1.22 we need to investigate. 
```changes
section: docs
type: fix
summary: The `kind` image used in the Getting Started changed to v1.21.
```
> [docs] Switch to K8s v1.21 in the "Getting started: installing in kind"

- modules/150-user-authn/templates/dex-authenticator/service.yaml
Change dex-authenticator's port name from `http` to `https`.
In istio-enabled namespaces there is problem with protocol mismatch. dex-authenticator's istio sidecar tries to handle dex service as pure http.
```changes
type: fix
summary: Change dex-authenticator's port name from `http` to `https`
```
> [user-authn] dex-authenticator's port name to https

- modules/500-upmeter/images/smoke-mini/smoke-mini.go
- modules/500-upmeter/templates/smoke-mini/services.yaml
Access smoke-mini neighbors via cluster ip service in neighbor-via-service probe.
Fixes the initial design of neighbor-via-service probe.
```changes
type: fix
summary: Fix the correctness of neighbor-via-service probe by using ClusterIP service type.
```
> [upmeter] Fix neighbor-via-service probe

- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Add preferredDuringSchedulingIgnoredDuringExecution rule for main and longterm Prometheus.
It's always preferable to schedule Prometheus pods on different nodes. For example, if VPA is disabled or its max resources are too low, pods can still be scheduled to the same node. That leads too constant OOM on this node.
```changes
type: feature
summary: Prefer to schedule main and longterm prometheus on different nodes
impact: Prometheus main and longterm will restart
```
> [prometheus] Prefer to schedule main and longterm prometheus on different nodes

- .editorconfig
- modules/300-prometheus/images/grafana/Dockerfile
- modules/300-prometheus/images/grafana/patches/build_go.patch
- modules/300-prometheus/images/grafana/patches/feat_prometheus_extra_vars.patch
- modules/300-prometheus/images/grafana/patches/fix_heatmap_thin_bars_on_ff.patch
- Update Grafana to 8.5.2
- Update statusmap to 0.5.1
- Build: remove workaround from go-builder
- Build: remove deprecated yarn options
- Build: increase max_old_space_size to 8000 (since 8.3.0)
- Custom variables: support interpolation on backend
Use latest Grafana.
```changes
type: feature
summary: Use Grafana 8.5.2
```
> [prometheus] Grafana 8.5.2, statusmap 0.5.1

- modules/500-upmeter/images/status/src/en.ts
- modules/500-upmeter/images/upmeter/pkg/db/dao/episode5m_test.go
- modules/500-upmeter/images/upmeter/pkg/db/migrations/agent/0002_rename_extensions.down.sql
- modules/500-upmeter/images/upmeter/pkg/db/migrations/agent/0002_rename_extensions.up.sql
- modules/500-upmeter/images/upmeter/pkg/db/migrations/server/0009_rename_extensions.down.sql
- modules/500-upmeter/images/upmeter/pkg/db/migrations/server/0009_rename_extensions.up.sql
- modules/500-upmeter/images/upmeter/pkg/probe/group_controlplane.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_scaling.go
- modules/500-upmeter/images/upmeter/pkg/probe/load.go
- modules/500-upmeter/images/upmeter/pkg/probe/load_test.go
- modules/500-upmeter/images/upmeter/pkg/server/server_test.go
- modules/500-upmeter/images/webui/src/app/i18n/en.ts
Renaming things according to mk8s terms of service
- added migrations
- fixed tests
- fixed naming in web ui
- fixed naming on status page
Comply with SLA availability groups from the Terms of Service
```changes
type: chore
summary: Renamed current state of groups and probes according to SLA in the Terms of Service
```
> [upmeter] Rename scaling to extensions, cp/access to cp/apiserver

- modules/021-cni-cilium/hooks/enable_node_routes.go
- modules/021-cni-cilium/hooks/enable_node_routes_test.go
Fixed a hook so it won't ever return nil.
We rely on this value in Helm templates: `Error: helm upgrade failed: error validating \"\": error validating data: unknown object type \"nil\" in ConfigMap.data.auto-direct-node-routes\n"`.
The error was introduced via a last-minute change in the original Cilium PR that [removed](https://github.com/deckhouse/deckhouse/pull/592#discussion_r869625527) defaulting in OpenAPI.
```changes
type: fix
summary: Fixed value modifying hook so that it won't ever leave a value as nil
```
> [cni-cilium] Fixed value modifying hook

- dhctl/pkg/config/meta.go
- dhctl/pkg/config/meta_test.go
- modules/040-node-manager/images/bashible-apiserver/pkg/template/context_builder.go
Close #194
Add support in dhctl and bashible-apiserver.
if registryDockerCfg does not contain "auth" field, use username and password fields to construct registry.auth parameter for bashible.
We should support old docker config format.
We can not bootstrap cluster and bashible does not work, if we change deckhouse-registry secret in old format. 
```changes
section: dhctl
type: fix
summary: Old dockerCfg format support (construct auth from username and password)
---
type: fix
summary: Old dockerCfg format support in bashible-apiserver (construct auth from username and password)
```
> [dhctl][node-manager] Old dockerCfg format support (construct auth from username and password)

- modules/030-cloud-provider-yandex/templates/cni.yaml
Set  `simple-bridge` default CNI for Yandex
We had `simple-bridge` default CNI before cilium. With current setup all yandex clusters will redeploy CNI, which is not good.
```changes
section: cloud-provider
type: fix 
summary: Rollback Yandex default CNI
```
> rollback default CNI for yandex cloud

- modules/300-prometheus/crds/doc-ru-prometheusremotewrite.yaml
- modules/300-prometheus/crds/prometheusremotewrite.yaml
- modules/300-prometheus/openapi/values.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Add two options - bearerToken (for everyone) and customAuthToken (for okmeter)
Only basic auth is allowed right now, which is not flexible enough. 
```changes
type: feature
summary: Add token auth for Prometheus remote write
```
> [prometheus] Add token auth for remote write

- modules/465-pod-reloader/docs/README.md
Fixed typo in the documentation.
> [docs] Fix typo

- modules/460-log-shipper/templates/daemonset.yaml
Add probes with higher thresholds 
Closes https://github.com/deckhouse/deckhouse/issues/1596
```changes
type: fix
summary: Add probes for kube-rbac-proxy container.
```
> [log-shipper] Add probes for kube-rbac-proxy container

- modules/460-log-shipper/templates/podmonitor.yaml
Drop some metrics. Vector cannot expire metrics in its current state.
Closes #1574 
```changes
type: fix
summary: Reduce the amount of exported metrics by log-shipper agents. Fixes metrics leak for dynamic environments.
```
> [log-shipper] Drop metrics with the file label

- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
Completely disabled systemd collector.
node-exporter's systemd-collector does not work correctly without adding a new mount inside node-exporter container. It also generates tons of high cardinality metrics that should be narrowed down by providing a regex of monitored systemd Units to the node-exporter. All this work has been done in https://github.com/deckhouse/deckhouse/pull/1587, but since there is no push from customers to use these feature, we'll disable it.
```changes
type: fix
summary: Disabled node-exporter's systemd collector. It was not working correctly, so no one is dependent on it.
```
> Revert "[monitoring-kubernetes] Enable systemd collector in the node-exporter (#768)"

- candi/bashible/common-steps/node-group/050_configure_and_start_docker.sh.tpl
- candi/bashible/common-steps/node-group/051_pull_kubernetes_api_proxy.sh.tpl
Prepull kubernetes-api-proxy image.
To avoid problems when we change from system kubernetes-api-proxy to static pod kubernetes-api-proxy.
```changes
section: candi
type: fix
summary: Prepull kubernetes-api-proxy image to avoid problems when we change from system kubernetes-api-proxy to static pod kubernetes-api-proxy.
```
> [kubernetes-api-proxy] prepull image

- docs/documentation/modules_generate_cr.sh
Jekyll sanitizes the data filename, so we must delete dots from the file name to access data.
If the CRD file contains a dot in the name, it doesn't render
```changes
section: docs
type: fix
summary: Fixed rendering CRD file with a dot in the name.
```
> [docs] Fix rendering CRD file with a dot in the name

- modules/460-log-shipper/crds/cluster-logging-config.yaml
It is required to avoid misconfiguration like the following:
```yaml
...
spec:
type: KubernetesPods
file:
include: ["/var/log/*"]
```
```changes
type: fix
summary: Provide structural schemas for log-shipper CRDs
```
> [log-shipper] Provide structural schemas for log-shipper CRDs

- modules/500-upmeter/images/upmeter/pkg/check/episode.go
- modules/500-upmeter/images/upmeter/pkg/server/api/episode.go
- modules/500-upmeter/images/upmeter/pkg/server/entity/episode.go
- modules/500-upmeter/images/upmeter/pkg/server/remotewrite/controller.go
- modules/500-upmeter/images/upmeter/pkg/server/remotewrite/exporter.go
- modules/500-upmeter/images/upmeter/pkg/server/remotewrite/syncer.go
- modules/500-upmeter/images/upmeter/pkg/server/server.go
- modules/500-upmeter/templates/upmeter-agent/daemonset.yaml
- modules/500-upmeter/templates/upmeter/statefulset.yaml
Fix potential error looop in remote write exporter. Add minor enhancements.
Fixes potential bug in telemetry collection.
```changes
type: chore
summary: Switched the logging of upmeter metrics on info level while exporting.
---
type: fix
summary: Fixed potential error loops in remote write exporter
impact: If a storage responds with 4xx error, the unaccepted metrics will not be re-sent.
---
type: fix
summary: 'Added missing User-Agent header to remote write exporter, defined as `Upmeter/1.0 (Deckhouse <edition> <version>)`'
```
> [upmeter] Remote write exporter: don't retry sending metrics on 4xx errors from storage

- modules/020-deckhouse/monitoring/prometheus-rules/deckhouse.yaml
Use new metrics names in alert rules.
Errors related metrics was renamed in https://github.com/flant/addon-operator/pull/133
```changes
type: fix
summary: Use new metrics names in alert rules.
impact: Re-enable alerts on hook errors.
```
> [prometheus] fix: rename errors related metrics

- docs/site/_includes/getting_started/existing/STEP_FINISH.md
- docs/site/_includes/getting_started/existing/STEP_FINISH_RU.md
- docs/site/_includes/getting_started/global/STEP_FINISH.md
- docs/site/_includes/getting_started/global/STEP_FINISH_RU.md
- docs/site/_includes/getting_started/kind/STEP_FINISH.md
- docs/site/_includes/getting_started/kind/STEP_FINISH_RU.md
- modules/140-user-authz/docs/USAGE.md
- modules/140-user-authz/docs/USAGE_RU.md
Now Deckhouse deploys a certificate for the published API with a different name for each mode, so I added a kubectl command to dynamically pick the name of the certificate from the corresponding ingress resource.
```changes
type: fix
summary: Fix gitlab-runner access rights doc
```
> [user-authz] Fix gitlab-runner access rights doc

- modules/460-log-shipper/hooks/generate_config_test.go
- modules/460-log-shipper/hooks/internal/handler/apply.go
- modules/460-log-shipper/hooks/internal/handler/generator.go
- modules/460-log-shipper/hooks/internal/vector/transform/default.go
- modules/460-log-shipper/hooks/internal/vector/transform/transforms_test.go
- modules/460-log-shipper/hooks/testdata/file-to-elastic.json
Dedot transform drops all entries without pod labels
```changes
type: fix
summary: Fix integration of the File source with the Elasticsearch destination.
```
> [log-shipper] No dedot for file

- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
```changes
type: fix
summary: Correctly set Prometheus version to enable headers for remote write
```
> [prometheus] Fixes for remote write headers

- .github/scripts/js/changelog-find-sections.js
Fixes module discovery with regex applied to dir names.
Fixes missing "keepalived" as known module
```changes
section: ci
type: fix
summary: 'Fixed missing modules in changelog (e.g. keepalived due to /ee/ regex)'
```
> CI: fix regex in module discovery

- docs/site/.helm/templates/20-ingress.yaml
Temporarily disable using `certificateOwnerRef:` in a Certificate resource of the site (was set in https://github.com/deckhouse/deckhouse/pull/1601). 
Will be enabled when Deckhouse v1.33 is on the production web cluster.
```changes
section: docs
type: fix
summary: disable using `certificateOwnerRef:` in a Certificate resource of the site
```
> [docs] Disable certificateOwnerRef

- .github/actions/milestone-changelog/action.yml
- .github/scripts/js/changelog-find-sections.js
Fixes module discovery with regex applied to dir names.
Fixes missing "keepalived" as known module
```changes
section: ci
type: fix
summary: 'Fixed missing modules in changelog (e.g. keepalived due to /ee/ regex)'
```
> [Upmeter] Fix (again) sections discovery

- ee/modules/040-terraform-manager/images/terraform-manager-openstack/werf.inc.yaml
- modules/040-terraform-manager/images/base-terraform-manager/werf.inc.yaml
- modules/040-terraform-manager/images/terraform-manager-aws/werf.inc.yaml
- modules/040-terraform-manager/images/terraform-manager-azure/werf.inc.yaml
- modules/040-terraform-manager/images/terraform-manager-yandex/werf.inc.yaml
- werf.yaml
Migrate from werf ansible to werf shell for terraform based images.
Move terraform and cloud providers into artifacts images.
Terraform based images can not build.
Ansible step is trying use its own CA certificates and we can not download terraform and terrafrom plugins.
```changes
section: dhctl
type: fix
summary: Migrate from werf ansible to werf shell image builds for terraform based images
```
```changes
type: fix
summary: Migrate from werf ansible to werf shell image builds for terraform based images
```
> [terraform-manager][ci]  Migrate from werf ansible to werf shell image builds for terraform based images

- .github/ci_includes/terraform_versions.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_release.yml
- .github/workflows/deploy-web-stage.yml
- .github/workflows/deploy-web-test.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- .github/workflows/schedule-cleanup.yml
Upgrade yandex cloud terraform provider
Close #1576
```changes
section: candi
type: feature
summary: Upgrade Yandex Cloud terraform provider to 0.74.0
---
type: feature
summary: Upgrade Yandex Cloud terraform provider to 0.74.0
```
> [candi][terraform-manager] Upgrade Yandex Cloud terraform provider to 0.74.0

- .github/actions/milestone-changelog/action.yml
Add sign-off for commit messages from bot
Lets changelog PRs pass DCO check.
```changes
section: ci
type: chore
summary: "Added sign-off line to bot's commit messages"
```
> [CI] Sign-off commits by bot

- ee/modules/110-istio/template_tests/module_test.go
- ee/modules/110-istio/templates/control-plane/iop.yaml
- helm_lib/templates/_resources_management.tpl
Add ephemeral-storage configurator to `helm_lib_resources_management_pod_resources` function.
There are `helm_lib_module_ephemeral_storage_only_logs` and `helm_lib_module_ephemeral_storage_logs_with_extra` functions which configure the ephemeral-storage requests. It was impossible to set ephemeral-storage with `helm_lib_resources_management_pod_resources` one.
```changes
type: feature
summary: Add ephemeral-storage configurator to `helm_lib_resources_management_pod_resources` function.
impact: istiod will restart.
```
> [helm_lib] ephemeral-storage to helm_lib_resources_management_pod_resources

- go.mod
- go.sum
Bring fix from shell-operator to restore separate metrics storage for hooks.
- https://github.com/flant/shell-operator/pull/388
- https://github.com/flant/addon-operator/pull/323
No metrics from hooks when separate port for hook metrics is in use after applying https://github.com/flant/shell-operator/pull/388 and https://github.com/flant/addon-operator/pull/315.
```changes
type: fix
summary:  Restore separate metrics storage for hooks.
```
> [deckhouse-controller] fix: restore hook metrics

- docs/site/_includes/getting_started/gcp/partials/resources.yml.production.inc
- docs/site/_includes/getting_started/yandex/partials/resources.yml.production.inc
Adds taints in the resource file for the production environment (Getting started, Google Cloud).
Adds comments in the Yandex resource file.
Closes #1669 
```changes
section: docs
type: fix
summary: Added taints in the resource file for the production environment
```
> [docs][getting started][gcp] Add taints in the resource file for the production environment

- modules/007-registrypackages/images/kubernetes-cni-centos/scripts/install
Fix kubernetes-cni install script for centos
In centos, kubernetes-cni package depends on kubelet package, and, to install it alone, added `--nodeps` rpm flag to install script.
```changes
section: candi
type: fix
summary: fix kubernetes-cni install script for centos
```
> [candi] fix kubernetes-cni install script for centos

- Makefile
- ee/modules/600-flant-integration/hooks/license_test.go
- modules/040-node-manager/hooks/discover_standby_ng_test.go
- testing/library/sandbox_runner/runner.go
- werf.yaml
GolangCI Linter upgrade to 1.46.2
The 1.42.0 version is no longer available, so we need to upgrade.
```changes
section: ci
type: chore
summary: GolangCI Linter upgrade to 1.46.2
```
> [ci] GolangCI Linter upgrade to 1.46.2

- dhctl/Makefile
- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/pkg/kubernetes/client/client.go
golangci-lint update to 1.46.2 for dhctl.
There are floating problems with 1.42.0 version.
```changes
section: ci
type: fix
summary: golangci-lint update to 1.46.2 for dhctl.
```
> [ci] dhctl golangci-lint update to 1.46.2

- modules/007-registrypackages/images/containerd-centos/werf.inc.yaml
fix containerd registry package build for centos-8.
https://github.com/deckhouse/deckhouse/issues/1693
```changes
section: candi
type: fix
summary: fix containerd registry package build for centos-8
```
> [candi] fix containerd registry package build for centos-8

- global-hooks/openapi/config-values.yaml
- global-hooks/openapi/doc-ru-config-values.yaml
Add all in-box Deckhouse's ClusterIssuers to the documentation
Documentation can lead to some misunderstanding cause of limited list of ClsuterIssuers
```changes
section: docs
type: chore
summary: Add all available ClusterIssuers to the documentation
```
> [docs] Add all available inbox ClusterIssuers to the documentation

- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/doc-ru-cluster_configuration.yaml
Remove master node `coreFraction` setting from YandexClusterConfiguration openapi spec
We don't allow using non-100% `coreFraction` on master nodes and we don't have realisation.
```changes
section: candi
type: fix
summary: Remove master node `coreFraction` setting from YandexClusterConfiguration openapi spec
```
> [candi][yandex] Remove master node coreFraction setting from openapi

- docs/site/_data/topnav.yml
Change the documentation default page to the Overview page.
```changes
section: docs
type: fix
summary: The documentation default page has been changed to the Overview page.
```
> [docs] Change the documentation default page to the Overview page.

- candi/cloud-providers/yandex/openapi/doc-ru-instance_class.yaml
- candi/cloud-providers/yandex/openapi/instance_class.yaml
There was a misspelling in the preemptible parameter in the YandexInstanceClass resource, which led to the search on the site for the word preemptible not giving the correct results.
```changes
type: fix
summary: Fixed misspelling in the YandexInstanceClass resource
```
> [docs] Fix misspelling in the YandexInstanceClass resource

- ee/modules/110-istio/openapi/config-values.yaml
- ee/modules/110-istio/openapi/values.yaml
- modules/020-deckhouse/openapi/config-values.yaml
- modules/040-control-plane-manager/openapi/config-values.yaml
- modules/040-control-plane-manager/openapi/values.yaml
- modules/300-prometheus/openapi/config-values.yaml
- modules/460-log-shipper/openapi/config-values.yaml
- modules/500-cilium-hubble/openapi/config-values.yaml
- modules/810-deckhouse-web/openapi/config-values.yaml
Matrix tests optimizations.
The matrix tests take too much time to execute.
```changes
section: ci
type: chore
summary: Matrix tests optimizations.
impact: low
```
> [testing] Matrix tests optimizations

- modules/300-prometheus/hooks/prometheus_disk.go
- modules/300-prometheus/hooks/prometheus_disk_test.go
Set disk retention size to 80%.
When small disks are used in clusters with a large number of metrics, disk cleanup does not have time to complete and space runs out.
```changes
type: fix
summary: Set disk retention size to 80%
```
> [prometheus] rollback disk retention size to 80%

- modules/040-node-manager/docs/internal/ETCD_RECOVERY.md
Disaster recovery etcd documentation updates.
Updates the documentation so that it corresponds to the Russian version. The ETCD_RECOVERY file sheds light on various etcd recovery methods  after failures.
```changes
section: docs
type: feature
summary: Disaster recovery etcd documentation updates.
```
> [docs] Disaster recovery etcd doc updates

- helm_lib/templates/_csi_controller.tpl
helm_lib _csi_controller.tpl fix — checksum annotation only for CCM
As usual, we forgot about ceph-csi.
```changes
type: fix
summary: helm_lib _csi_controller.tpl fix — checksum annotation only for CCM
```
> [helm_lib] _csi_controller.tpl annotation only for CCM

- modules/099-ceph-csi/templates/registry.yaml
Add registry secret to d8-ceph-csi namespace
Automates the access to images, fixes the secret absence which is references in the ceph-csi daemonset.
```changes
type: fix
summary: Fixed missing registry secret
```
> [Ceph-csi] add registry secret 

- docs/site/_includes/getting_started/bm-private/partials/config.yml.default.ce.inc
- docs/site/js/getting-started-private.js
There was http[s] instead of HTTP[S] value for the registryScheme parameter in the getting started config.yml for private environment. The right value is HTTP[S].
```changes
section: docs
type: fix
summary: Fixed incorrect the `registryScheme` parameter in the getting started 
```
> [docs] Fix incorrect the `registryScheme` parameter in the getting started

- .github/actions/milestone-changelog/action.yml
- Add version to commit message
- Add link to full changelog in PR body
- Identify to see merged changelog commit
- Simplify the creation of release message
```changes
section: ci
type: chore
summary: Added release version to chengelog commit message and full changelog link to PR body
```
> [CI] add version to changelog commit message 

- modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.20/002-non-type-lb.patch
- modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.21/002-non-type-lb.patch
- modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.22/002-non-type-lb.patch
- modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.23/002-non-type-lb.patch
Correct conversion from int to string.
Fixes wrong request
```
I0608 16:35:48.701512       1 log_handler.go:34] AWS API Send: elasticloadbalancing CreateTargetGroup &{CreateTargetGroup POST / <nil> <nil>} {
HealthCheckIntervalSeconds: 10,
HealthCheckPath: "/healthz",
HealthCheckPort: "盞",
```
That leads to an error
```
failed to ensure load balancer: error creating load balancer target group: "ValidationError: Health check port '绔' must be within '1-65535'
```
```changes
type: fix
summary: Fix LoadBalancer type none target group creation
```
> [cloud-provider-aws] Fix LoadBalancer type none target group creation

- modules/040-node-manager/docs/internal/CLUSTER_AUTOSCALER.md
- modules/040-node-manager/templates/cluster-autoscaler/deployment.yaml
Change scale-down-after-add timer for cluster-autoscaler to prevent node flapping
We have 2m scale-down-after-add parameter, node is scaling up, then some huge app is not able to become ready in time and node is scaling down. We can increase cooldown window and wait at least 10 minutes after scaling-up
```changes
type: fix
summary: cluster-autoscaler: increase node cooldown after scaling-up to prevent flapping (10m instead of 2m)
```
> [node-manager] change CA scale-down timing

- modules/031-linstor/docs/FAQ.md
- modules/031-linstor/docs/FAQ_RU.md
Describe some failed cases when linstor-node can't load drbd module.
Sometimes users could face with problems of loading DRBD module.
This doc trying to cover some of those cases
```changes
type: fix
summary: Add failed cases when drbd module cannot be loaded
```
> [linstor] Add failed cases when drbd module cannot be loaded

- modules/402-ingress-nginx/images/controller-0-33/patches/README.md
- modules/402-ingress-nginx/images/controller-0-33/patches/ingress-class.patch
Add patch for working with ingress class resource
If ingress class resource exists but ingress object does not have neither annotation nor spec field IngressClassName, then controller panics
```changes
type: fix
summary: Fix workability of 0.33 controller with IngressClass resource.
```
> [ingress-nginx] Add patch for ingress-controller 0.33

- modules/402-ingress-nginx/images/controller-0-46/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-0-48/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-0-49/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-1-1/rootfs/etc/nginx/lua/pbmetrics.lua
Fix wildcard vhost label in ingress-controller metrics
Fixes https://github.com/deckhouse/deckhouse/issues/1425.
```changes
type: fix
summary: Fix wildcard vhost label in ingress-controller metrics
impact: Ingress controller pods will be restarted
```
> [ingress-nginx] Fix wildcard vhost metrics

- modules/402-ingress-nginx/images/controller-0-33/Dockerfile
Forgot to add patch to Dockerfile
It doesn' work :)
```changes
type: fix 
summary: Fix build of the ingress-nginx 0.33 controller.
```
> [ingress-nginx] add patch apply to dockerfile

- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/kubernetes/actions/converge/node.go
- dhctl/pkg/operations/bootstrap.go
- dhctl/pkg/operations/converge/infra/hook/controlplane/hook.go
- dhctl/pkg/operations/converge/infra/hook/node.go
- dhctl/pkg/system/ssh/cmd/scp.go
- dhctl/pkg/system/ssh/cmd/ssh.go
Add `-o PasswordAuthentication=no` parameter to ssh command to prevent waiting enter password when user pass incorrect ssh key
Add confirmation for waiting Deckhouse controller readiness and control-plane node readiness.
Do not output Deckhouse logs when getting node group cloud config for created node groups.  
Close #1202
Close #1200
```changes
section: dhctl 
type: feature
summary: Add confirmation for waiting Deckhouse controller readiness and control-plane node readiness.
```
```changes
section: dhctl 
type: fix
summary: Exclude password authentication check while connecting to host
```
> [dhctl] Some improvements and fixes

- modules/500-openvpn/hooks/set_search_domains.go
- modules/500-openvpn/hooks/set_search_domains_test.go
Added check for the existence of the pushToClientSearchDomains parameter in the config.
This fixes a bug that does not allow you to set additional domains.
```changes
type: fix
summary: Fixes a bug that does not allow you to set additional domains.
```
> [openvpn] fix set_search_domains hook

- go.mod
- go.sum
Stop excess log messages about WaitForSynchronization tasks. See: https://github.com/flant/addon-operator/pull/324
To much log messages after merging #1472 :
```
{"binding":"ConvergeModules","event.type":"OperatorStartup","level":"info","module":"prometheus","msg":"ModuleRun task for module 'prometheus', phase 'WaitForSynchronization' with doModuleStartup, trigger is OperatorStartup","queue":"main","task.flow":"start","task.id":"c8a3c465-d2c1-4ff9-96c7-a92f7272cb14","time":"2022-06-08T10:57:18Z"}
{"binding":"ConvergeModules","event.type":"OperatorStartup","level":"info","module":"prometheus","msg":"ModuleRun task for module 'prometheus', phase 'WaitForSynchronization' with doModuleStartup, trigger is OperatorStartup","queue":"main","task.flow":"start","task.id":"c8a3c465-d2c1-4ff9-96c7-a92 …
```
> [deckhouse-controller] fix: do not log messages about WaitForSynchronization tasks

- modules/031-linstor/images/drbd-driver-loader/Dockerfile
DRBD requires newer spatch version:
```
INFO: spatch not recent enough, need spatch version >= 1.0.8
```
Latest cherry-pick https://github.com/deckhouse/deckhouse/pull/1726#issuecomment-1151173849 made inposible the drbd module building on Deckhouse <1.33:
```changes
type: fix
summary: Fix drbd module building.
```
> [linstor] fix: spatch not recent enough

- dhctl/pkg/system/ssh/checks.go
Fix typo
```changes
section: dhctl
type: chore
summary:  Fix typo in warning
```
> [dhctl] Fix typo in warning

- modules/500-upmeter/hooks/probe_deckhouse_configuration.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/d8_clusterconfiguration.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_configmap.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_deployment.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_namespace.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_pod.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/smoke_mini.go
- modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
Add alerts for garbage left by upmeter probes.
We should clean the garbage when it cannot be deleted. Moreover, upmeter agent does not delete
garbage by labels, it only tracks objects by name within single run.
```changes
type: chore
summary: Added alerts for garbage objects left by probes
```
> [Upmeter] Add alerts for probe garbage

- modules/101-cert-manager/templates/cert-manager/clusterissuer-letsencrypt-staging.yaml
- modules/101-cert-manager/templates/cert-manager/clusterissuer-letsencrypt.yaml
Respect global ingress class for LE cluster issuer
Now we can use LE cluster issuer only with default (unset) ingress class. It wouldn't work in some situations
```changes
type: fix
summary: Respect global ingress class in the LE cluster-issuer
```
> [cert-manager] default ingress class for LE cluster-issuer

- candi/bashible/bundles/ubuntu-lts/node-group/035_pull_pause.sh.tpl
- candi/bashible/common-steps/node-group/050_configure_and_start_containerd.sh.tpl
- candi/tools/discover_new_kubernetes_patchversions.sh
- dhctl/pkg/template/testdata/resources/order.yaml
- modules/000-common/images/csi-external-attacher/werf.inc.yaml
- modules/000-common/images/csi-external-provisioner/werf.inc.yaml
- modules/000-common/images/csi-external-resizer/werf.inc.yaml
- modules/000-common/images/csi-external-snapshotter/werf.inc.yaml
- modules/000-common/images/csi-livenessprobe/werf.inc.yaml
- modules/000-common/images/csi-node-driver-registrar/werf.inc.yaml
- modules/000-common/images/pause/werf.inc.yaml
- modules/021-kube-proxy/images/kube-proxy/werf.inc.yaml
- modules/040-control-plane-manager/images/kube-scheduler/werf.inc.yaml
- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
- modules/042-kube-dns/hooks/sts_discovery_test.go
- modules/045-snapshot-controller/images/snapshot-controller/Dockerfile
- modules/045-snapshot-controller/images/snapshot-validation-webhook/Dockerfile
- modules/301-prometheus-metrics-adapter/images/k8s-prometheus-adapter/Dockerfile
- modules/302-vertical-pod-autoscaler/images/admission-controller/Dockerfile
- modules/302-vertical-pod-autoscaler/images/updater/Dockerfile
- modules/340-monitoring-kubernetes-control-plane/hooks/discovery_test.go
- modules/402-ingress-nginx/images/controller-0-46/Dockerfile
- modules/402-ingress-nginx/images/controller-0-48/Dockerfile
- modules/402-ingress-nginx/images/controller-0-49/Dockerfile
- modules/402-ingress-nginx/images/controller-1-1/Dockerfile
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_deployment.go
Change kubernetes registry as it changes in the upstream
- https://groups.google.com/a/kubernetes.io/g/dev/c/DYZYNQ_A6_c/m/FpHqeVR2BAAJ
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/3000-artifact-distribution
- https://github.com/kubernetes/kubernetes/pull/109938
Keep upstream components available
```changes
type: chore
summary: Switched to new official kubernetes registry
impact: All nginx ingress pods of controllers >=0.46 will be restarted
---
section: candi
type: chore
summary: Switched to new official kubernetes registry
---
type: chore
summary: Switched to new official kubernetes registry
impact: All control plane pods will be restarted
---
section: dhctl
type: chore
summary: …
```
> Change k8s registry

- candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
Feature gate was not enabled on Kubernetes 1.20.
Kubelet did not start on Kubernetes 1.20.
```changes
section: candi
type: fix
summary: kubelets did not start on k8s 1.20
```
> [candi] Enable GracefulNodeShutdown flag on k8s 1.20

- modules/300-prometheus/templates/grafana/deployment.yaml
Grafana introduced their new alerting system, which is enabled by default for our Grafana version
https://grafana.com/docs/grafana/v8.5/alerting/
With the new alerting system, it is impossible to provision alert managers and add alerts to dashboards using Deckhouse custom resources. The only opportunity, for now, is to return back legacy alerts.
With this
```changes
type: fix
summary: Enable legacy alerting system for Grafana
```
> [prometheus] Enable legacy alerting system for Grafana

- modules/040-node-manager/hooks/remove_csi_taints.go
- modules/040-node-manager/hooks/remove_csi_taints_test.go
- modules/042-kube-dns/templates/deployment.yaml
Remove `csi-not-bootstrapped` taint only after at least one CSI driver is properly registered in the CSINode object.
Closes https://github.com/deckhouse/deckhouse/issues/1613
```changes
type: fix
summary: Remove `csi-not-bootstrapped` taint only after at least one CSI driver is properly registered in the CSINode object.
```
> [global-hooks] Remove CSI taints only after `spec.drivers` are filled

- modules/600-namespace-configurator/docs/CONFIGURATION.md
- modules/600-namespace-configurator/docs/CONFIGURATION_RU.md
The namespace-configurator module was mistakenly listed as disabled by default.
```changes
section: namespace-configurator
type: fix
summary: The namespace-configurator module was mistakenly listed as disabled by default in the documentation.
```
> [docs][namespace-configurator] Fix the configuration page.

- dhctl/pkg/kubernetes/actions/deckhouse/install.go
- dhctl/pkg/kubernetes/actions/manifests/manifests.go
- dhctl/pkg/operations/bootstrap.go
- dhctl/pkg/operations/bootstrap/checks.go
- dhctl/pkg/operations/bootstrap_test.go
Prevent to break already bootstrapped cluster when bootstrap new cluster.
Before apply deckhouse manifests, we check cluster UUID now, and if we will get different uuid (none empty) from cache and from cluster, we will return error. 
Close #1657
```changes
section: dhctl
type: feature
summary: Prevent to break already bootstrapped cluster when bootstrap new cluster
```
> [dhctl] Prevent to break already bootstrapped cluster when bootstrap new cluster

- candi/cloud-providers/yandex/terraform-modules/vpc-components/main.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf
Change NAT-instance zone and CIDR for internal address algorithm:
- if has intenalSubnetID get zone from it
- if has externalSubnetID get zone from it and choose CIDR from our created subnet or passed subnet
- if client passed subnet choice from it.
- else choice `ru-central1-a` zone and use our created CIDR.
`ru-central1-c` zone was deprecated.
https://cloud.yandex.ru/docs/overview/concepts/ru-central1-c-deprecation
```changes
type: feature
summary: Move NAT-instance to ru-central1-a for new instances.
impact: |
`ru-central1-c` zone was [deprecated](https://cloud.yandex.ru/docs/overview/concepts/ru-central1-c-deprecation).
For new clusters NAT-instance will be created in `ru-central1-a` zone. For old instances you should add to …
```
> [cloud-provider-yandex] Move NAT-instance to ru-central1-a and opportunity choice zone with externalSubnetID and internalSubnetID for new instances

- modules/031-linstor/templates/piraeus-operator/deployment.yaml
- modules/031-linstor/templates/piraeus-operator/podmonitor.yaml
Remove `/metrics-cr` endpoint
There was a regression after updating piraeus-operator to 1.8 https://github.com/deckhouse/deckhouse/pull/1559
Piraeus-operator does not export `/metrics-cr` endpoint anymore.
```changes
type: fix
summary: fix monitoring of piraeus-operator
```
> [linstor] fix monitoring of piraeus-operator

- dhctl/pkg/kubernetes/actions/deckhouse/log.go
- dhctl/pkg/kubernetes/actions/deckhouse/log_test.go
Signed-off-by: Ivan Mikheykin <ivan.mikheykin@flant.com>
- fix: detect Converge ends from new log messages from latest addon-operator
- fix: detect stderr as error
Dhctl parses deckhouse logs and detect events. Latest addon-operator change messages, so update is needed.
```changes
section: dhctl
type: fix
summary: Detect events from latest addon-operator log messages.
```
> [dhctl] fix: detect events from new log messages from latest addon-operator

- go.mod
- go.sum
Restore exponential backoff for delays between failed hooks restarts.
Failed hook restarts every second after merging #1472.
See also: https://github.com/flant/shell-operator/pull/407 and https://github.com/flant/addon-operator/pull/326.
```changes
type: fix
summary: Restore exponential backoff for delays between failed hooks restarts.
```
> [deckhouse-controller] fix: restore exponential backoff for failed hooks

- modules/150-user-authn/images/kubeconfig-generator/already_logged.patch
Kubelogin is a recommended way to authenticate with a kubectl because of https://github.com/deckhouse/deckhouse/issues/1151
Let's make the kubelogin tab active by default in attempt to improve UX.
```changes
type: feature
summary: Make kubelogin tab active by default
```
> [user-authn] Make kubelogin tab active by default

- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
Add node reboot step in clean up node FAQ.
Reboot helps to remove existing CNI interface. It helps to avoid problems with network configuration.
```
Warning  FailedCreatePodSandBox  0s               kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ab1ffcf6c6b4ae067799d20cd6bc8aba44f675e5600d4106086f6d4b9f058f5d" network for pod "early-oom-wrnm7": networkPlugin cni failed to set up pod "early-oom-wrnm7_d8-cloud-instance-manager" network: failed to set bridge addr: "cni0" already has an IP address different from 10.123.97.1/24
10: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000 …
```
> [node-manager][docs] Add node reboot step in clean up node FAQ

- modules/040-control-plane-manager/openapi/config-values.yaml
- modules/040-control-plane-manager/openapi/doc-ru-config-values.yaml
Fix link to quota-backend-bytes in openapi spec
Incorrect link view in documentation
```changes
type:chore
summary: Fix link to quota-backend-bytes
```
> [control-plane-manager] Fix link to quota-backend-bytes

- modules/040-control-plane-manager/monitoring/prometheus-rules/etcd-maintenance.yaml
Fix D8KubeEtcdDatabaseSizeCloseToTheLimit alert expression.
Because on the left side and on the right side will get vectors we should ignore `node` label (`d8_etcd_quota_backend_total ` has not it) and we should use Many-to-one matches because `d8_etcd_quota_backend_total ` always is one value. 
Expression in alert always return empty result. We can not receive alert about small space for etcd db. 
```changes
type: fix 
summary: Fix D8KubeEtcdDatabaseSizeCloseToTheLimit alert expression
```
> [control-plane-manager] Fix D8KubeEtcdDatabaseSizeCloseToTheLimit  expression

- modules/500-upmeter/hooks/disabled_probes.go
- modules/500-upmeter/hooks/disabled_probes_test.go
- modules/500-upmeter/images/upmeter/Makefile
- modules/500-upmeter/images/upmeter/pkg/agent/sender/client.go
- modules/500-upmeter/images/upmeter/pkg/agent/sender/sender.go
- modules/500-upmeter/images/upmeter/pkg/check/checker.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/base.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/certificate_secret.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/d8_clusterconfiguration.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/http.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_configmap.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_controlplane.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_daemonset.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_deployment.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_garbagecollection.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_listing.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_namespace.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_pod.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/smoke_mini.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_controlplane.go
- modules/500-upmeter/images/upmeter/pkg/probe/load_test.go
- modules/500-upmeter/images/upmeter/pkg/server/server_test.go
- modules/500-upmeter/images/webui/src/app/i18n/en.ts
- modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
- modules/500-upmeter/templates/upmeter-agent/rbac-for-us.yaml
Add basic probe for cert-manager
More availability checks in SLA by design epic
```changes
type: feature
summary: Added basic probe for cert-manager in 'control-plane' availability group
```
> [Upmeter] Add basic probe for cert-manager

- modules/021-cni-cilium/templates/agent/daemonset.yaml
- modules/021-cni-cilium/templates/configmap.yaml
- modules/021-cni-cilium/templates/operator/deployment.yaml
Cilium's port were colliding with protobuf-exporter.
Moved metric ports.
```changes
type: fix
summary: Changed metrics ports so they won't clash with protobuf-exporter
```
> [cilium] Changed ports to not clash with Ingress Nginx Controller's protobuf-exporter

- modules/040-control-plane-manager/templates/service.yaml
- modules/040-node-manager/docs/FAQ.md
We'll allocate from the end of the [default](https://github.com/kubernetes/kubernetes/blob/0520d75838d28007896c9af9eff2485ae8b84e86/pkg/kubeapiserver/options/options.go#L26) NodePort range.
Kubernetes' port allocation algorithm starts from the beginning. By choosing the port from the end, we are safe from port collisions.
```changes
type: feature
summary: Bolt-on healthCheckNodePort of the control-plane Service and trafficPolicy: Local
```
> [control-plane-manager] Bolt-on healthCheckNodePort of the control-plane Service and trafficPolicy: Local

- modules/031-linstor/templates/linstor-controller/linstorcontroller.yaml
Make linstor-controller listen on IPv4-only address.
Fixes https://github.com/deckhouse/deckhouse/issues/1804.
```changes
type: fix
summary: Make the `linstor-controller` listen on IPv4-only address.
```
> [linstor] listen on IPv4 address

- modules/031-linstor/docs/FAQ.md
- modules/031-linstor/docs/FAQ_RU.md
Document how to set StorageClass by default
Since SotrageClasses generated dynamically we need to explain how to specify StorageClass by default.
```changes
type: chore
summary: document how to set StorageClass by default
```
> [linstor] Document default StorageClass

- Makefile
- modules/040-node-manager/docs/FAQ.md
- tools/cve/base-images.sh
- tools/cve/release.sh
Add two commands to generate Deckhouse CVE reports
This PR allows us to easily generate reports using one of the most popular tools - [trivy](https://github.com/aquasecurity/trivy).
With these reports, developers can check that there are no new critical dependencies introduced.
```changes
section: ci
type: chore
summary: Add CVE report scripts
```
> [chore] Add CVE report scripts

- deckhouse-controller/cmd/deckhouse-controller/main.go
- deckhouse-controller/entrypoint.sh
Remove default for start command to prevent starting second instance of operator.
Accidental invoking deckhouse-controller without arguments starts an operator. This behaviour complicates diagnostics.
```changes
type: fix
summary: Display help when deckhouse-controller is invoked without arguments.
```
> [deckhouse-controller] fix: display help when deckhouse-controller is invoked without arguments

- modules/020-deckhouse/hooks/check_deckhouse_release.go
- modules/020-deckhouse/hooks/check_deckhouse_release_test.go
- modules/020-deckhouse/hooks/update_deckhouse_image.go
- modules/020-deckhouse/hooks/update_deckhouse_image_test.go
Suspend only pending releases. Apply first release automatically on deckhouse bootstrap
Improve update process. Suspending deployed release leads to implicit behavior. Also as first pending release
```changes
type: feature
summary: Automatically apply first release on deckhouse bootstrap
```
> [deckhouse] improve deckhouse update process

- modules/045-snapshot-controller/templates/snapshot-controller/deployment.yaml
- modules/045-snapshot-controller/templates/snapshot-validation-webhook/deployment.yaml
Reduce amount of replicas for snapshot-controller to a maximum of 2
If amount of system-nodes less than master-nodes, then some replicas of snapshot-controller always stuck in `Pending`
```changes
type: fix
summary: Reduce amount of replicas for snapshot-controller to a maximum of 2
impact: low
```
> [snapshot-controller] Reduce amount of replicas for snapshot-controller to a maximum of 2

- modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/Dockerfile
- modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/loop
- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
Managed clusters (EKS, Yandex, GKE) with deckhouse as module couldn't work with kubelet-eviction-threshold-exporter because they don't have crictl and also socket can have different passes. But all of them have /etc/containerd/config.toml, so we can parse it and extract root direction
kubelet-eviction-threshold-exporter doesn't work in platform managed kubernetes.
```
kubelet-eviction-threshold-exporter /bin/loop: line 33: crictl: command not found      
```
```changes
type: fix
summary: Make `kubelet-eviction-threshold-exporter` workable in managed kubernetes platforms (AWS, GKE, Yandex, etc)
```
> [monitoring-kubernetes] node-exporter: parse containerd config

- modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/deprecated-resources.json
Add GKE-like dashboard to Grafana to analyze deprecated APIs
```changes
type: feat
summary: Deprecated APIs dashboard
```
> [monitoring-kubernetes-control-plane] Deprecated APIs dashboard

- modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
Fix duplicating group in alerting rules.
Fix error:
```
level=info ts=2022-06-28T14:09:25.981513368Z caller=rules.go:340 component=prometheusoperator msg="Invalid rule" err="424:3: groupname: \"d8.upmeter.resources\" is repeated in the same file"
level=error ts=2022-06-28T14:09:25.981577258Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="sync \"d8-monitoring/main\" failed: Invalid rule"
```
```changes
type: fix
summary: Fix duplicating groups in alerting rules
```
> [upmeter] Fix duplicating groups in alerting rules

- modules/402-ingress-nginx/templates/controller/hpa.yaml
We have to calculate average CPU load for all pods in a DaemonSet but we are calculating the summary of them at the moment
HPA works wrong, ordering too many new replicas
```changes
type: fix
summary: fix hpa calculating for IngressNginxController. Calculate average CPU load instead of summary
```
> [ingress-nginx] hpa: measure average cpu usage for DaemonSet

- ee/modules/030-cloud-provider-openstack/hooks/discover_volume_types.go
- ee/modules/030-cloud-provider-openstack/hooks/discover_volume_types_test.go
If volume type name has spaces, replace spaces with dashes for StorageClass name
Some OpenStack clouds have volumes with spaces in names
```
+--------------------------------------+---------+-----------+
| ID                                   | Name    | Is Public |
+--------------------------------------+---------+-----------+
| bb49fb86-7279-44ed-ae1f-7a55e1771754 | SSD R1  | True      |
```
For such volume type name Deckhouse tries to create StorageClass with name `ssd r1` but this is forbidden.
```changes
type: fix
summary: Support for volume type with spaces in name
```
> [cloud-provider-openstack] Support for volume type with spaces in name

- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
Create containerd directory if it does not exist.
Pod could run if host does not contain containerd directory (docker runtime for example). FileOrCreate does not create parent directory
```changes
type: fix 
summary: Fixed handling absent containerd directory
```
> [monitoring-kubernetes] handle absent containerd directory

- ee/modules/030-cloud-provider-openstack/hooks/get_cni_secret.go
- ee/modules/030-cloud-provider-openstack/openapi/values.yaml
- ee/modules/030-cloud-provider-openstack/templates/cni.yaml
- ee/modules/030-cloud-provider-vsphere/hooks/get_cni_secret.go
- ee/modules/030-cloud-provider-vsphere/openapi/values.yaml
- ee/modules/030-cloud-provider-vsphere/templates/cni.yaml
- global-hooks/enable_cni_test.go
- go_lib/hooks/get_cni_secret/hook.go
- modules/000-common/hooks/get_cni_secret.go
- modules/000-common/hooks/get_cni_secret_test.go
In existing clusters cni parameters stored in kube-system/d8-cni-configuration secret. 
We stores parameters from existing secret in module internal values, and recreate secret with this parameters.
Thus, if cluster have a configured cni (cni-flannel for example), it will continue to use configured cni.
If there is no secret (new installation, first run), we install cni-cilium as cni in the d8-cni-configuration secret.
We want to replace cni-flannel with cni-cilium for all new installations in vsphere and openstack clouds.
For existing clusters we should not change cni.
```changes
type: feature
summary: cni-cilium set as default cni (replaces cni-flannel) for openstack and vsphere.
```
> [cni-cilium] set as default cni

- modules/013-helm/hooks/metrics.go
- modules/013-helm/hooks/metrics_test.go
- modules/013-helm/hooks/startup_metrics.go
- modules/013-helm/monitoring/prometheus-rules/deprecated-versions.yaml
Fix release namespace detection.
Add helm_version to the metric.
Add 1.24 k8s unsupported APIs.
Helm release namespace unmarshalling from resource sometimes gives wierd results. Getting namespace from secret/cm is more predictable.
Adding `helm_version` value to metrics makes the process of figuring out a deprecated release easier.
```changes
section: helm
type: fix 
summary: Fix namespace detection for helm releases with unsupported/deprecated resources.
```
> [helm] Fix release namespace detection and add helm_version to metric

- candi/version_map.yml
Chore: updating k8s control plane images
Usual upstream sync
```changes
section: candi
type: chore
summary: "Upgraded patch versions of Kubernetes images: v1.21.14, v1.22.11, and v1.23.8"
impact: "kube-scheduler and kube-proxy (except 1.21) will restart"
```
> Update versions of Kubernetes images

- ee/modules/110-istio/templates/podmonitor.yaml
PodMonitor fix for data-plane with fresh istio version.
There was PodMonitor's labelSelector which used the `istio.io/rev` label to detect istio data-plane pods. Now there isn't such label. Now we use `service.istio.io/canonical-name`.
```changes
section: istio
type: fix
summary: Data-plane metrics scrape fix for fresh istio versions.
```
> [istio] PodMonitor fix for fresh istio version

- modules/470-chrony/monitoring/prometheus-rules/chrony.yaml
- Replace metric `node_ntp_sanity metrics` with `node_timex_sync_status`
- Calculate node's clock drift using metric `node_ntp_offset_seconds`
Alert `NTPDaemonOnNodeDoesNotSynchronizeTime` was triggered if difference between node time and chrony server time was bigger than 1ms. But chrony doesn't act as ntpd that just instantly corrects time.
> In normal operation, chronyd slews the time when it needs to adjust the system clock. For example, to correct a system clock which is 1 second slow, chronyd slightly increases the amount by which the system clock is advanced on each clock interrupt, until the error is removed. Note that at no time does time run backwards with this method.
> On most Unix systems it is not desirable to …
> [chrony] Refactor alerts

- modules/040-node-manager/templates/node-group/_bootstrap_script.tpl
Fix unbound variable bootstrap_job_log_pid when bootstrap static-node
Fix error while bootstrap static node:
```
/var/lib/bashible/bootstrap.sh: line 255: bootstrap_job_log_pid: unbound variable
```
and node can not reboot
Node MUST reboot after bootstrap static-node if kernel was installed.
Error `/var/lib/bashible/bootstrap.sh: line 255: bootstrap_job_log_pid: unbound variable` must gone when bootstrap static-node.
```changes
type: fix
summary: Fix unbound variable bootstrap_job_log_pid when bootstrap static-node
```
> [node-manager] Fix unbound variable bootstrap_job_log_pid when bootstrap static-node

- helm_lib/templates/_node_affinity.tpl
- modules/101-cert-manager/template_tests/module_test.go
- modules/460-log-shipper/monitoring/prometheus-rules/log-shipper-agent.yaml
- modules/460-log-shipper/templates/daemonset.yaml
- modules/460-log-shipper/templates/namespace.yaml
* Tolerate ToBeDeletedByClusterAutoscaler for all nodes strategy
* Change the logic of log-shipper alerts
* Remove the extended monitoring annotation from the log-shipper namespace to avoid duplicated alerts
1. The log-shipper module has the node selector property. It means not all nodes in the cluster carry log-shipper agents.
2. New alert uses DamonSet status data, which is more accurate and filled by Kubernetes. Kubernetes knows, that a node has tainted and should not carry a pod.
3.  ToBeDeletedByClusterAutoscaler should also be tolerated because if a system pod is restarted accidentally, it will not be able to schedule on a node back.
4. All monitoring components have the cluster-medium priority class. The log-shipper agents had …
> [log-shipper] Fix DaemonSet alerts

- dhctl/Makefile
- werf.yaml
There is a linter in the deckhouse testing container. The downloading process fails from time to time which forces us to rerun tests (so annoying).
N/A
```changes
section: ci
type: chore
summary:  Do not download linter for dhctl every time
impact_level: ow
```
> [dhctl][ci] Do not download linter for dhctl

- modules/040-node-manager/templates/node-group/_bootstrap_script.tpl
Fix bootstrap script
Cloud node does not join
Cloud nodes must join
```changes
type: fix
summary: Fix bootstrap script
```
> [node-manager] Fix bootstrap script

- deckhouse-controller/entrypoint.sh
Remove precautions from entrypoint.sh to make it compatible with container restarts.
Socket file checking precaution not works properly on container restart. Previous deckhouse-controller execution left UNIX socket file and deploy/deckhouse hangs in CrashLoopBack state.
1. Edit cm/deckhouse with error config values
2. Restart deploy/deckhouse
3. Run kubectl -n d8-system logs deploy/deckhouse
4. Currently it will print a single line "deckhouse-controller is already started"
5. With changes it should print error about config values.
```changes
type: fix
summary: Remove precautions from entrypoint.sh to make it compatible with container restarts.
```
> [deckhouse-controller] fix: 'already started' error on container restart

- modules/150-user-authn/monitoring/prometheus-rules/dex.yaml
- modules/150-user-authn/templates/dex/config.yaml
- modules/150-user-authn/templates/dex/deployment.yaml
- modules/150-user-authn/templates/dex/podmonitor.yaml
- modules/150-user-authn/templates/dex/rbac-for-us.yaml
- modules/150-user-authn/templates/dex/rbac-to-us.yaml
- modules/150-user-authn/templates/monitoring.yaml
* Refactor liveness and readiness probes align with the [official Dex helm chart](https://github.com/dexidp/helm-charts/blob/da8d7fe3369b2c9cf89a59ae7f86a6f1cf449cf7/charts/dex/templates/deployment.yaml#L95-L102). The liveness probe endpoint returns an ok message without checking database connectivity.
* Collect metrics from Dex (there are approximately 40 metrics). 
* Add a simple alert that Prometheus can scrape one of Dex targets.
1. Previous Dex liveness probes led to container restarts, which was a cause of pods lying in the backoff loop status
2. At least simple monitoring is required to detect problems with Dex
Dex pod will be restarted.
```changes
type: fix
summary: Refactor Dex probes, and collect metrics …
```
> [user-authn] Refactor dex probes

- modules/101-cert-manager/crds/crd-certificaterequests.yaml
- modules/101-cert-manager/crds/crd-certificates.yaml
- modules/101-cert-manager/crds/crd-challenges.yaml
- modules/101-cert-manager/crds/crd-clusterissuers.yaml
- modules/101-cert-manager/crds/crd-issuers.yaml
- modules/101-cert-manager/crds/crd-orders.yaml
- modules/101-cert-manager/images/cert-manager-acme-solver/werf.inc.yaml
- modules/101-cert-manager/images/cert-manager-cainjector/werf.inc.yaml
- modules/101-cert-manager/images/cert-manager-controller/patches/certificate_owner_ref.patch
- modules/101-cert-manager/images/cert-manager-controller/werf.inc.yaml
- modules/101-cert-manager/images/cert-manager-webhook/werf.inc.yaml
Bump cert-manager version from 1.7.1 to 1.8.2
- cert-manager v1.8.2 introduces [exponential backoff after failed certificate issuance](https://github.com/cert-manager/cert-manager/blob/f8900ad1d8cc9b7c3697d7554911e2959fa56480/design/20220118.certificate-issuance-exponential-backoff.md).
Previously, a failed issuance was retried every hour which — especially in larger cert-manager installations — could cause rate limits to be hit as well as overwhelm external services. Failed attempts
are now retried with a binary exponential backoff starting with 1h then 2h, 4h up to a maximum of 32h. As part of the new backoff behavior, a new failedIssuanceAttempts field was added to the
Certificate spec to track the number of currently failed issuances. …
> [cert-manager] bump version to 1.8.2

- dhctl/pkg/operations/converge/infra/hook/controlplane/hook.go
…
Do not try remove label dhctl.deckhouse.io/node-for-converge if node object was deleted during converge
Close #1927
If converged node contains deckhouse pod and converged node has destructive converge has not errors
```changes
section: dhctl
type: fix
summary: Do not try remove label dhctl.deckhouse.io/node-for-converge if node object was deleted during converge
```
> [dhctl] Do not try remove label dhctl.deckhouse.io/node-for-converge if node object was deleted during converge

- Makefile
- docs/documentation/Makefile
- docs/documentation/werf.yaml
- docs/site/Makefile
- docs/site/werf.yaml
Added targes for building and stopping containers with the documentation:
- `make docs` — to build and run containers with the documentation ([werf](werf.io) is required). 
- `make docs-dev` — to build and run containers with the documentation in dev mode (allow uncommitted files). 
- `make docs-down` — to stop and remove the documentation containers. 
Fix Makefile to build documentation on mac.
Use public images when building through Makefiles.
Working:
- `make docs`
- `make docs-dev`
- `make docs-down`
```changes
section: docs
type: feature
summary: Add targets for documentation to the Makefile.
```
> [docs] Update Makefile for building documentation

- modules/402-ingress-nginx/hooks/minimal_ingress_nginx_version.go
Refactor startup hook, use kubeclient instead of snapshots
Snopshots don't work at startup phase. We have an extra run of the hook without any usefulness
```changes
type: fix
summary: Refactor startup hook
```
> [ingress-nginx] Refactor startup hook

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
- modules/020-deckhouse/docs/internal/IMAGE_COPIER.md
- modules/020-deckhouse/images/images-copier/generate-copier-secret.sh
image-copier one-liner to detect if there are Pods with irrelevant registry.
It is handy to check if all the pods were updated after re(over?)push.
```changes
type: chore
summary: image-copier one-liner to detect if there are Pods with irrelevant registry.
```
> [deckhouse] image-copier one-liner to detect if there are Pods with irrelevant registry

- modules/460-log-shipper/docs/internal/demo/README.md
- modules/460-log-shipper/docs/internal/demo/all-pods-pipeline.yaml
- modules/460-log-shipper/docs/internal/demo/audit-logs-pipeline.yaml
- modules/460-log-shipper/docs/internal/demo/audit-policy.yaml
- modules/460-log-shipper/docs/internal/demo/clean_up.sh
- modules/460-log-shipper/docs/internal/demo/grafana-additional-datasource.yaml
- modules/460-log-shipper/docs/internal/demo/loki.txt
Add docs to demonstrate the log-shipper module
This is an example to demonstrate how the log-shipper module is actually working. 
```changes
type: chore
summary:  Add files for a demo
```
> [log-shipper] Add files for a demo

- modules/042-kube-dns/hooks/legacy_metrics.go
- modules/042-kube-dns/hooks/legacy_metrics_test.go
- modules/042-kube-dns/images/coredns/Dockerfile
- modules/042-kube-dns/images/coredns/patches/README.md
- modules/042-kube-dns/images/coredns/patches/support-alpha-tolerate-unready-endpoints-annotation.patch
- modules/042-kube-dns/monitoring/prometheus-rules/kubernetes/dns.yaml
1. Patched coredns v1.9.3.
2. Alert that informs user about the required migration from a deprecated annotation.
Contains patch that persuades coredns to respect deprecated `service.alpha.kubernetes.io/tolerate-unready-endpoints` annotation.
```changes
---
type: fix
summary: Updated CoreDNS to v1.9.3. With patches to persuade coredns to respect deprecated Service annotation `service.alpha.kubernetes.io/tolerate-unready-endpoints`. Alerts the user to the need for migrating from deprecated annotation.
---
type: fix
summary: Updated CoreDNS to v1.9.3.
```
> [kube-dns][node-local-dns] coredns v1.9.3 with patch

- dhctl/pkg/system/ssh/frontend/waiting.go
Increase attempts to wait ssh master node connect
Some clouds provide machines slowly. Our openstack provider is slow and e2e tests were failed often.
Openstack e2e always pass.
```changes
section: dhctl
type: chore
summary: Increase attempts to wait ssh master node connect
```
> [dhctl] Increase attempts to wait ssh master node connect

- modules/101-cert-manager/images/cert-manager-controller/patches/certificate_owner_ref.patch
Cert-manager patch was broken during the version migration
Secrets don't have ownerRef field and are not deleted on cert removal
```changes
type: fix
summary: Fix patch for cert-manager certificate owner ref field
```
> [cert-manager] fix secret owner ref

- ee/fe/modules/340-monitoring-applications/monitoring/prometheus-rules/applications/prometheus/prometheus.yaml
- ee/fe/modules/340-monitoring-applications/monitoring/prometheus-rules/warnings/warnings.yaml
- ee/modules/110-istio/monitoring/prometheus-rules/federation.yaml
- ee/modules/110-istio/monitoring/prometheus-rules/multicluster.yaml
- ee/modules/110-istio/monitoring/prometheus-rules/revisions.yaml
- ee/modules/350-node-local-dns/monitoring/prometheus-rules/node-local-dns.yaml
- ee/modules/600-flant-integration/monitoring/prometheus-rules/grafana-agent.yaml
- ee/modules/600-flant-integration/monitoring/prometheus-rules/sending-alerts.yaml
- modules/013-helm/monitoring/prometheus-rules/deprecated-versions.yaml
- modules/020-deckhouse/monitoring/prometheus-rules/deckhouse.yaml
- modules/031-linstor/monitoring/prometheus-rules/drbd-devices.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-controller.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-csi-controller.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-csi-node.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-ha-controller.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-node.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-scheduler.yaml
- modules/031-linstor/monitoring/prometheus-rules/linstor-storage-pools.yaml
- modules/031-linstor/monitoring/prometheus-rules/piraeus-operator.yaml
- modules/042-kube-dns/monitoring/prometheus-rules/kubernetes/dns.yaml
- modules/300-prometheus/monitoring/prometheus-rules/base.tpl
- modules/300-prometheus/monitoring/prometheus-rules/emptydir.yaml
- modules/300-prometheus/monitoring/prometheus-rules/grafana.yaml
- modules/300-prometheus/monitoring/prometheus-rules/longterm-target-down.yaml
- modules/500-okmeter/monitoring/prometheus-rules/alerting.yaml
- modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
Fix deckhouse group alerts label selectors
`plk_create_group_if_not_exists__` and `plk_grouped_by__` labels should be equal.
```changes
type: fix
summary:  fix deckhouse group alerts label selectors
```
> [prometheus] fix deckhouse group alerts label selectors

- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Add attempt number for DHCTL_PREFIX.
Now directory for workflow attempt is `/mnt/cloud-layouts/layouts/ACTION_ID-ATTEMPT_NUMBER-BLAH_BLAH`
Restarting e2e tests does not work. Error is `Temporary dir already exists: /mnt/cloud-layouts/layouts/BLAH-BLAH-BLAH. ERROR!`
Tested [here](https://github.com/deckhouse/deckhouse-test-2/runs/7250334046?check_suite_focus=true)
```changes
section: ci
type: fix
summary: Fix restart e2e tests
```
> [ci] Fix restart e2e tests

- modules/300-prometheus/templates/trickster/deployment.yaml
Use normal liveness probe
Deckhouse installs the most (and it seems like the last) up to date version of trickster. We probably should not bump his head every time Prometheus is unavailable, because all bugs are fixed now.
Trickster will restart and probably freeze. Need to check it.
```changes
type: fix
summary: Do not restart Trickster if Prometheus is unavailable
```
> [prometheus] Have a mercy on trickster

- Makefile
- candi/tools/discover_new_kubernetes_patchversions.sh
- candi/tools/functions.sh
- candi/tools/update_kubernetes_patchversions.sh
Automatic patchversions update makefile target.
This PR adds Makefile targets to update versions_map file to latest versions of kubernetes control-plane components patchversions. Later we should add GA, to periodically run auto-update and generate PRs for updated versions.
```changes
section: candi
type: chore
summary: Automatic patchversions update makefile target.
```
> [candi] Automatic patchversions update makefile target

- docs/documentation/werf.yaml
- docs/site/werf.yaml
Use public images when building documentation locally. 
```changes
section:test
type: fix
summary: Use public images when building documentation locally. 
```
> [tests] Use public images when building documentation locally

- modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
Use label selector to get logs from all upmeter agents.
Without it we select logs only from one pod.
```
kubectl -n d8-upmeter logs ds/upmeter-agent | head -n 1
Found 3 pods, using pod/upmeter-agent-wrmp7
{"level":"info","msg":"Starting upmeter agent. ID=1d069532","time":"2022-07-10T07:32:21Z"}
```
```changes
type: fix
summary: Fix kubectl logs command in alerts D8UpmeterProbeGarbage
```
> [upmeter] Fix kubectl logs command in alerts D8UpmeterProbeGarbage

- modules/500-upmeter/images/status/.prettierrc.yml
- modules/500-upmeter/images/status/package-lock.json
- modules/500-upmeter/images/status/package.json
- modules/500-upmeter/images/status/rollup.config.js
- modules/500-upmeter/images/status/src/App.svelte
- modules/500-upmeter/images/status/src/Group.svelte
- modules/500-upmeter/images/status/src/StatusText.svelte
- modules/500-upmeter/images/status/src/en.ts
On status page (status.<clusterPublicDomain>)
- Added descriptions for avaiability groups "nodegroups" and "nginx".
- Rephrased other descriptions for uniformity.
Status page should be descriptive.
The page looks not like it was forgotten or abandoned
```changes
type: chore
summary: Added descriptions for avaiability groups "nodegroups" and "nginx".
```
> [upmeter] Fix status page descriptions

- modules/500-upmeter/images/upmeter/go.mod
- modules/500-upmeter/images/upmeter/pkg/agent/agent.go
- modules/500-upmeter/images/upmeter/pkg/monitor/downtime/monitor.go
- modules/500-upmeter/images/upmeter/pkg/monitor/hookprobe/monitor.go
- modules/500-upmeter/images/upmeter/pkg/monitor/node/monitor.go
- modules/500-upmeter/images/upmeter/pkg/monitor/remotewrite/monitor.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_daemonset.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_daemonset_test.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_nodegroup.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/smoke_mini_test.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_monitoring_and_autoscaling.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_nodegroups.go
- modules/500-upmeter/images/upmeter/pkg/probe/load.go
- modules/500-upmeter/images/upmeter/pkg/probe/load_test.go
- modules/500-upmeter/images/upmeter/pkg/server/api/incidents.go
- modules/500-upmeter/images/upmeter/pkg/server/remotewrite/controller.go
- modules/500-upmeter/images/upmeter/pkg/server/server.go
Use node informer for listing nodes instead of direct listing in API
It reduces the load on kube-apiserver in relatively big clusters.
Upmeter will work as expected.
```changes
type: chore
summary: Tracking nodes switched to informer instead of direct listing requests
```
> [upmeter] Use informer for Nodes

- modules/020-deckhouse/images/webhook-handler/werf.inc.yaml
- modules/200-operator-prometheus/images/prometheus-operator/Dockerfile
- modules/200-operator-prometheus/images/prometheus-operator/patches/README.md
- modules/200-operator-prometheus/images/prometheus-operator/patches/scrape-params.patch
- modules/200-operator-prometheus/images/prometheus-operator/patches/scrape-timestamp-align.patch
- modules/300-prometheus/images/prometheus/Dockerfile
- modules/300-prometheus/images/prometheus/sample_limit_annotation.patch
- modules/300-prometheus/images/prometheus/successfully_sent_metric.patch
- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
* bump Prometheus version (v2.36.0)
* enable `scrape.timestamp-tolerance=10ms` flag
* enable `snapshot-on-shutdown` feature
There were some TSDB optimizations during last year, and there are also optimizations in Go runtime. The RAM consumption graph is attached to highlight the difference.
The first gap - Prometheus update 2.28 -> 2.36
The second gap - `scrape.timestamp-tolerance=10ms` flag is enabled
CPU and Disk consumption is slightly better than it was before.
Prometheus will be restarted. I hope that it will consume fewer resources.
```changes
type: feature
summary: Update Prometheus to v2.36.2 (decrease memory consumption)
impact: Prometheus pods will be restarted.
```
> [prometheus] Update prometheus to v2.36.2

- modules/020-deckhouse/hooks/check_deckhouse_release.go
- modules/020-deckhouse/hooks/check_deckhouse_release_test.go
Add [possibility](https://www.google.com/search?rlz=1C5CHFA_enRU916RU916&q=possibility&spell=1&sa=X&ved=2ahUKEwjmtr7byOT4AhUlmYsKHbPKD-AQkeECKAB6BAgBEDI) to resume suspended release
We can suspend a release because of some circumstances but it does not mean that the release is broken. We want to have a possibility to resume the deploy process of that release
```changes
type:feature
summary: Possibility to resume a suspended release
```
> [deckhouse] Possibility to resume suspended release

- modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
- modules/402-ingress-nginx/openapi/config-values.yaml
Alert about old ingress controllers deprecation
Controllers before 1.0 are outdated. We shouldn't support them anymore and should push everyone to migrate to 1.1
```changes
type: chore
summary: Mark Ingress controllers below 1.1 as deprecated
impact: Fire alerts about deprecated ingress controllers
```
> [ingress-nginx] Alert: old ingress controller versions deprecation

- docs/documentation/_includes/openapi-tippy.html
- docs/documentation/_plugins/openapi.rb
Add the description field of the `items` structure to the description of the parent parameter.
Increase notification maximum width (in tippy).
```changes
section: docs
type: fix
summary: Fixed OpenAPI render
```
> [docs] Update OpenAPI render and increase notification maxwidth

- candi/bashible/common-steps/node-group/050_configure_and_start_docker.sh.tpl
- candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
Use cgroupfs as cgroup driver for docker 20.
Recent docker versions (20+) used in Ubuntu 22.04, Debian 11, and Centos 8 use systemd v2 as cgroup driver by default. But we expect use of cgroupfs driver. This PR adds config option to daemon.json to use cgroupfs as cgroup driver.
```changes
section: candi
type: fix
summary: use cgroupfs as cgroup driver for docker 20
```
> [candi] use cgroupfs as cgroup driver for docker 20

- modules/020-deckhouse/images/webhook-handler/werf.inc.yaml
- modules/300-prometheus/images/prometheus/Dockerfile
https://prometheus.io/docs/introduction/release-cycle/
```changes
type: chore
summary: Update Prometheus to the latest LTS version
```
> [prometheus] Update to 2.37.0 (LTS)

- docs/site/.helm/templates/20-ingress.yaml
This PR reverts commit d21615f5eb8f9d364be7362686b3008fccc646fd (#1647).
```changes
section: chore
type: fix
summary: Set `certificateOwnerRef` to `false` in the documentation Ingress.
```
> Revert "[docs] Disable certificateOwnerRef (#1647)"

- docs/site/_includes/head.html
Fix URL in meta tags on site pages.
There was an incorrect page preview.
```changes
section: docs
type: fix
summary: Fix URL in meta tags on site pages.
```
> [docs] Fix meta tags in page header on the site

- modules/150-user-authn/templates/dex/config.yaml
`insecureNoSSL` is present in the `DexProvider` spec, but is not respected in the code.
```changes
type: fix
summary: Fix LDAP insecureNoSSL support
```
> [user-authn] LDAP: Add insecureNoSSL

- modules/301-prometheus-metrics-adapter/images/prometheus-reverse-proxy/Dockerfile
- modules/301-prometheus-metrics-adapter/images/prometheus-reverse-proxy/app/go.mod
- modules/301-prometheus-metrics-adapter/images/prometheus-reverse-proxy/app/go.sum
- modules/301-prometheus-metrics-adapter/images/prometheus-reverse-proxy/app/server/middleware.go
- modules/301-prometheus-metrics-adapter/images/prometheus-reverse-proxy/app/server/server.go
- modules/301-prometheus-metrics-adapter/images/prometheus-reverse-proxy/app/server/server_test.go
Bugfix for a previos refactoring.
```changes
section: prometheus-metrics-adapter
type: fix
summary: Fix panic in prometheus-reverse-proxy
```
> [prometheus-metrics-adapter] Fix panic

- modules/500-upmeter/hooks/clean_probe_garbage.go
- modules/500-upmeter/images/upmeter/pkg/probe/run/id.go
- modules/500-upmeter/images/upmeter/pkg/probe/run/id_test.go
Cleans garbage caused by a bug.
Automatically resolves an alert about upmeter garbage objects.
The UpmeterHookProbe object named "35d78cbb" will be deleted, and corresponding alert will stop firing.
```changes
type: fix
summary: Added the auto-clean of garbage UpmeterHookProbe object produced by a bug
```
> [Upmeter] Fix UpmeterHookProbe garbage

- modules/500-upmeter/hooks/clean_probe_garbage.go
Ignore inexisting objects in garbage cleaning hook
Unstuck deckhouse main queue
Dechouse queue does not hang
```changes
section: upemter
type: chore
summary: Fixed up garbage cleaning
```
> [Upmeter] Fixup NotFound error on garbage cleaning

- modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
Fix instructions in the alert
Hard to debug error with a wrong command
```changes
summary: Fix debug instructions in the `NginxIngressConfigTestFailed` alert
```
> [ingress-nginx] fix alert debug commands

- candi/cloud-providers/aws/openapi/doc-ru-cluster_configuration.yaml
Fix the typo, "tags" mentioned where it is "security groups"
```changes
section: docs
type: chore
summary: Fix the typo in the docs of `additionalSecurityGroup`.
```
> [doc] Fix security-group doc typo in AWSClusterConfiguration

- ee/modules/110-istio/monitoring/prometheus-rules/revisions.yaml
D8IstioDataPlanePatchVersionMismatch alert description fix.
There was wrong command in description.
```changes
section: istio
type: fix
summary: D8IstioDataPlanePatchVersionMismatch alert description fix
```
> [istio] D8IstioDataPlanePatchVersionMismatch alert description fix

- modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
Update the `D8IngressNginxControllerVersionDeprecated` alert description.
```changes
type: fix
summary: Update the `D8IngressNginxControllerVersionDeprecated` alert description.
```
> [ingress-nginx] Update the `D8IngressNginxControllerVersionDeprecated` alert description

- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
- Ignore rootfs mounts to `/home/kubernetes/`
- Remove node-exporter collector settings collector.filesystem.ignored-fs-types
GKE uses `/home/kubernetes/` for rootfs mount points, and we want to ignore it.
```changes
type: fix
summary: Ignore containers rootfs mount point for node-exporter in GKE
```
> [monitoring-kubernetes] Ignore containers rootfs mount point for node-exporter in GKE

- ee/modules/350-node-local-dns/templates/configmap.yaml
Kubelet has issue when config map mounted to pod is deleted before pod is removed. And pod hangs in `Terminating` state.
We moved `node-local-dns` to `kube-system` namespace in 1.34 release. Helm removes `node-local-dns` cm before some pods were terminated, and a lot of pods can be stuck in `Terminating` state. To fix it, we should restart kubelet on every node with stuck pod.
Exclude manual actions during moving `node-local-dns` to `kube-system` namespace.
```changes
type: fix
summary: Reverted the `node-local-dns` ConfigMap, to prevent the `node-local-dns` Pods from getting stuck in the Terminating state during moving to `kube-system`.
```
> [node-local-dns] Revert configmap node-local-dns to prevent stuck node-local-dns pod in Terminating state during moving to kube-system namespace

- modules/300-prometheus/templates/prometheus/servicemonitor.yaml
Rollback prometheus-module ServiceMonitor label selector to `app=prometheus`.
If enterprise edition is used or monitoring-applications module is disabled, then ServiceMonitor from prometheus module is deploed. In #1446 we broke services labels, so now they are just fixed to work as before.
```changes
type: fix
summary: Rollback prometheus-module ServiceMonitor label selector to `app=prometheus`.
```
> [prometheus] Rollback prometheus-module ServiceMonitor label selector to `app=prometheus`

- ee/modules/350-node-local-dns/templates/rbac-for-us.yaml
- modules/040-control-plane-manager/hooks/audit_policy_basic_targets_generated.go
Kubelet has issue when service-account mounted to pod is deleted before pod is removed. And pod hangs in Terminating state.
We moved node-local-dns to kube-system namespace in 1.34 release. Helm removes `node-local-dns` service account before some pods were terminated, and a lot of pods can be stuck in Terminating state. To fix it, we should restart kubelet on every node with stuck pod.
Exclude manual actions during moving node-local-dns to kube-system namespace.
Node local dns pods should not stuck in terminating status in `d8-system` namespace
```changes
type: fix
summary: Revert service account to prevent Pod from getting stuck in a Terminating state.
```
> [node-local-dns] Revert service account for prevent pod stuck in Terminating state

- ee/modules/350-node-local-dns/images/coredns/start.sh
Check if `SHOULD_SETUP_IPTABLES` environment variable is set to yes.
Coredns can't start on freshly created nodes because `nodelocaldns` network device is not created.
```
Listen: listen tcp 192.168.0.10:53: bind: cannot assign requested address
```
Coredns works on freshly created nodes.
```changes
type: fix
summary: Correct check on coredns startup.
impact: The `node-local-dns` will restart.
```
> [node-local-dns] Correct check on coredns startup

- .github/scripts/js/ci.js
Fix e2e labels detection after refactoring in #1886
Refactoring breaks slash commands for release process.
Slash commands works in release issues. ( `/e2e/run/aws`, `/e2e/use/k8s/1.20`, etc.)
```changes
section: ci
type: fix
summary: Fix slash command detection for release issues
```
> [ci] fix: detect if slash command is a known e2e label

- helm_lib/templates/_node_affinity.tpl
- modules/101-cert-manager/template_tests/module_test.go
Tolerate even candidate taint
Some system pods can't be scheduled during CA scaling
```changes
section: candi
type: chore
summary: Tolerate CA DeletionCandidateOfClusterAutoscaler taint for some system pods
```
> [candi] Add toleration to CA for any_node_tolerations role

- testing/cloud_layouts/OpenStack/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/Static/infra.tpl.tf
Update tenant for e2e tests using OpenStack.
Move e2e test to a separate Openstack project.
```changes
type: chore
summary: Update info for e2e tests using OpenStack.
```
> [testing] Move e2e tests using OpenStack to another project

- modules/460-log-shipper/monitoring/grafana-dashboards/applications/vector.json
Dashboard refactoring
1. Add Rate panels
2. Add panels to show how many events went through each stage for the current $__range
```changes
type: chore
summary: Refactor throughput panels on log-shipper dashboard
```
> [log-shipper] Update dashboard

- candi/control-plane-kubeadm/config.yaml.tpl
- modules/040-control-plane-manager/templates/daemonset.yaml
Added feature gate `EndpointSliceTerminatingCondition` for  Kubernetes 1.20.
Started from Kubernetes 1.21 feature gate `EndpointSliceTerminatingCondition` is enabled by default.
Cilium supports the use of this feature gate starting from Kubernetes 1.20, so we enabled this feature gate  in Kubernetes 1.20 (https://docs.cilium.io/en/latest/gettingstarted/kubeproxy-free/#graceful-termination)
```changes
type: feature
summary: Added feature gate `EndpointSliceTerminatingCondition` for Kubernetes 1.20.
impact: all control-plane components should be restarted.
```
> [control-plane-manager] added feature gate EndpointSliceTerminatingCondition for Kubernetes 1.20

- candi/bashible/common-steps/node-group/069_start_kubelet.sh.tpl
Start kubelet forcibly if it was not started. We check that kubelet is not running `069_start_kubelet.sh`
Seldom, kubelet can be not started. But after `069_start_kubelet.sh` kubelet should start. 
`kubelet` should be always running.
```changes
type: fix
summary: Start kubelet manually if it is not running
```
> [bashible] Start kubelet forcibly if it is not running

- candi/version_map.yml
Forbid using Docker 18.* 
Allow only 19.* and 20.* versions.
We have troubles on 18.* Docker during release new Deckhouse version.
Docker often stuck and we should reboot node.
On nodes with Docker 18.* bashible should request disruptive update on step `031_install_docker.sh` 
```changes
type: feature
summary: Forbid using Docker 18.*
impact: |
After upgrading Deckhouse all nodes with Docker 18.* will request `disruptive update`. You will receive `NodeRequiresDisruptionApprovalForUpdate` if you have manual `approvalMode` in NodeGroup.
```
> [bashible] Forbid using Docker 18.* 

- modules/021-cni-cilium/images/cilium/Dockerfile
- modules/021-cni-cilium/images/cilium/patches/003-fix-bwmap-delete-errors.patch
- modules/021-cni-cilium/images/cilium/patches/README.md
Bandwidth controller metrics are not erroring out now. Also added logging to three controllers so that we can diagnose possible issues better.
Full justification is available here: https://github.com/cilium/cilium/pull/20611
We've had a strange issue with bandwidth controller metrics, which generated garbage alerts.
Useless metrics are not generated anymore, garbage alerts are not present either.
```changes
type: fix
summary: Bandwidth controller metrics are not erroring out now. Also added logging to three controllers so that we can diagnose possible issues better.
```
> [cni-cilium] Fixed bandwidth controller metrics

- modules/300-prometheus/templates/grafana/service.yaml
- modules/300-prometheus/templates/grafana/servicemonitor.yaml
- modules/300-prometheus/templates/prometheus/longterm/service.yaml
- modules/300-prometheus/templates/prometheus/service.yaml
- modules/300-prometheus/templates/prometheus/servicemonitor.yaml
- modules/300-prometheus/templates/trickster/service.yaml
- modules/300-prometheus/templates/trickster/servicemonitor.yaml
Always use ServiceMonitors from the prometheus module
These monitors are used for CE instalations, but for FE monitors from the monitoring-applications module are used. 
Using the same monitors for all editions will help us to reduce the number of bugs.
```changes
type: fix
summary: Always use ServiceMonitors from the prometheus module for Promethues, Grafana and Trickster.
```
> [prometheus] Always use custom monitors

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
- modules/040-control-plane-manager/docs/internal/ETCD_RECOVERY.md
Add information about backup and restore `/etc/kubernetes` directory.
In some cases restoring `/etc/kubernetes` directory is necessary. 
N/A
```changes
section: docs
type: chore
summary: Add information about backup and restore etcd-server keys and certificates.
```
> [docs][control-plane-manager] Add information about backup and restore etcd-server keys and certificates

- candi/bashible/bundles/debian/node-group/031_install_containerd.sh.tpl
Use Debian buster containerd package by default when exact Debian version can't be discovered.
Incorrect version of runc is installed that leads to various problems. For example,
```
Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:370: starting container process caused: unknown capability "CAP_PERFMON": unknown
```
```changes
section: candi
type: fix
summary: Use Debian buster containerd package by default
```
> [candi] Use Debian buster containerd package by default

- modules/040-node-manager/images/bashible-apiserver/pkg/template/context.go
- modules/040-node-manager/images/bashible-apiserver/pkg/template/steps_storage.go
Add more logs to the bashible-apiserver
It's hard to debug some situations with bashible-apiserver with detailed logs. Add more logging to the watchers on error and also add logs to the context rebuild
```changes
type: chore
summary: Add more verbosity to the bashible-apiserver logs
impact: bashible-apiserver will restart
```
> [node-manager] increase bashible-apiserver verbosity

- .github/ci_templates/helper_jobs.yml
- .github/workflow_templates/build-and-test_dev.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/on-pull-request-labeled.yml
- .github/workflows/validation.yml
Test improvements:
- Skip code-related tests if only documentation changes.
- Run some documentation-related jobs only if documentation changes.
Ref: #1628 
There is no need to run code tests if only the documentation has changed. Code testing takes time; eliminating unnecessary testing steps will save a lot of time passing the pipeline.
CI must not run code tests if only documentation changes. Documentation-related CI validation jobs must only run if documentation changes. 
```changes
section: tests
type: feature
summary: Not run code tests in only documentation changes. Run documentation-related validations if documentation changes.
```
> [ci][tests] Test improvements

- .github/ci_templates/alerting.yaml
- .github/ci_templates/e2e_tests.yml
- .github/workflow_templates/e2e-daily.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Rerender workflow fix for daily e2e tests.
Move alerts sending steps to separate template.
Fix alert trigger.
Fix DHCTL_PATH for creation multiple directories on runner.
Daily e2e runs with incorrect schedule.
E2E test do not run for all providers (only one 2).
Alerts about workflow problems do not send.
```changes
section: ci
type: fix
summary: Fix daily e2e tests
```
> [ci] Fix daily e2e tests

- .github/workflows/build-and-test_dev.yml
- .github/workflows/on-pull-request-labeled.yml
- .github/workflows/validation.yml
Signed-off-by: Ivan Mikheykin <ivan.mikheykin@flant.com>
Run render-workflows after #2142 
Files in workflows directory should be rendered from workflows_templates.
Running render-workflows.sh in main branch should tell `Render success. No changes.`
```changes
section: ci
type: chore
summary: render workflows
```
> [ci] render workflows

- candi/bashible/bundles/debian/node-group/031_install_docker.sh.tpl
- candi/bashible/bundles/ubuntu-lts/node-group/031_install_docker.sh.tpl
Forbid use `docker.io` package. We always should use `docker-ce` package.
See also #2134 
If node has `docker.io` package bashible will stuck waiting for approve disruptive update. 
```changes
type: feature
summary: Forbid use docker.io package
impact: After upgrading Deckhouse all nodes with installed docker.io package will request `disruptive update`. You will receive `NodeRequiresDisruptionApprovalForUpdate` if you have manual `approvalMode` in NodeGroup.
impact_level: hight
```
> [bashible] Forbid use docker.io package

- candi/bashible/common-steps/node-group/069_start_kubelet.sh.tpl
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/node.yaml
- Fix bash for start kubelet step
- Decrease threshold of NodeSUnreclaimBytesUsageHigh alert
- FIxes bash error 
```
test.sh: line 4: [: too many arguments
test.sh: line 4: [: bb-flag?: unary operator expected
```
- Alert should fire earlier. The previous threshold looks too high for small control-plane nodes with 8 GB RAM.
```changes
section: candi
type: fix
summary: Fix bash for start kubelet step
```
```changes
type: fix
summary: Decrease threshold of NodeSUnreclaimBytesUsageHigh alert
```
> [candi][monitoring-kubernetes] Bugfixes

- .github/ci_templates/build.yml
- .github/workflow_templates/build-and-test_pre-release.yml
- .github/workflows/build-and-test_pre-release.yml
- Add new workflow. 'dev' workflow is not suitable because PR is mandatory
and 'release' workflow will push to production registry.
- Run on push to release-* branches to be detectable in 'Actions' tab.
We should test commits in release branches before putting tags.
Workflow started on pushing to release-* branches.
```changes
section: ci
type: chore
summary: build and test for release branches
```
> [ci] build and test for release branches

- modules/500-upmeter/images/upmeter/cmd/upmeter/parse_args.go
- modules/500-upmeter/images/upmeter/pkg/agent/agent.go
- modules/500-upmeter/images/upmeter/pkg/agent/sender/client.go
- modules/500-upmeter/images/upmeter/pkg/agent/sender/sender.go
- modules/500-upmeter/templates/upmeter-agent/daemonset.yaml
Set more sane timeouts to upmeter-agent sender.
Reduces dummy logs about reached timeout and request cancellations.
Reduced or diminished logging or cancelled requests in upmeter-agent
```changes
type: fix
summary: Tweak HTTP sending timeouts to reduce cancellation logs
```
> [upmeter] Tweak agent HTTP timeout

- modules/020-deckhouse/docs/FAQ.md
- modules/020-deckhouse/docs/FAQ_RU.md
- modules/020-deckhouse/docs/USAGE.md
- modules/020-deckhouse/docs/USAGE_RU.md
Moves section about collecting debug information to the FAQ.
```changes
type: fix
summary: Move section about collecting debug information to the FAQ
```
> [docs][deckhouse] Move section about collecting debug information to the FAQ

- modules/040-node-manager/hooks/remove_bashible_apiserver.go
Delete old bashible-apiserver deployment
Release 1.34.12 contains fixed bashible-apiserver but before it we have to remove old deployment to avoid context race
```changes
type: fix
summary: Remove bashible-apiserver deployment to avoid race condition
```
> remove bashible apiserver

- modules/040-node-manager/images/bashible-apiserver/pkg/template/context.go
Fix #2185 
Bashible-api-server does not build
N/A
```changes
type: fix
summary: Fix undefined src variable in bashible-api-server
```
> [node-manager][bashible-api-server] Fix undefined src variable

- candi/bashible/common-steps/node-group/003_discover_node_ip.sh.tpl
Exclude virtual interfaces like flannel, cni0 etc. from node ip autodiscover.
When staticClusterConfiguration is not set, we try to autodiscover node ip address.
If the node has only one interface discover is ok, but when flannel is deployed in cluster, the second interface appears and autodiscover step fails.
```changes
section: candi
type: fix
summary: fix discover node ip bashible step
```
> [candi] fix discover node ip bashible step

- ee/modules/110-istio/images/metadata-discovery/hooks/ingressgateways
- ee/modules/110-istio/images/metadata-discovery/hooks/services
- ee/modules/110-istio/images/metadata-exporter/main.go
Don't export unready ingressgateway nodes via metadata-exporter for multiclusters and federations.
metadata-exporter exposes NotReady and cordoned nodes. It leads to unwanted connection errors.
metadata-exporter won't export unwanted nodes.
```changes
section: istio
type: fix
summary: Don't export unready ingressgateway nodes via metadata-exporter for multiclusters and federations.
```
> [istio] don't export unready ingressgateway nodes via metadata-exporter

- canary.json
- modules/040-node-manager/hooks/remove_bashible_apiserver.go
- modules/040-node-manager/templates/bashible-apiserver/deployment.yaml
Delete old bashible-apiserver deployment
Release 1.34.13 contains fixed bashible-apiserver but before it we have to remove old deployment to avoid context race
```changes
type: fix
summary: Remove bashible-apiserver deployment to avoid race condition
```
> [node-manager] Bashbile apiserver migration

- modules/300-prometheus/templates/prometheus/prometheus.yaml
Signed-off-by: Maksim Nabokikh <maksim.nabokikh@flant.com>
X-Auth -> X-Auth-Token
```changes
type: fix
summary: Use X-Auth-Token header for remote write credentials according to the doc.
```
> [prometheus] X-Auth-Token

- modules/031-linstor/monitoring/grafana-dashboards/storage/linstor_drbd.json
fix timestamp on linstor dashboard
The current timestamp is hardcoded to specific time
Update linstor-dashboard
```changes
type: fix
summary: fix timestamp on linstor dashboard
```
> [linstor] fix timestamp on dashboard

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/node.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/nodes.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/controller.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/namespace/namespace.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/namespace/namespaces.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/pod.json
Fix units on networks graphs.  Use bytes/s instead of bits/s for receive and transmit.
Closes https://github.com/deckhouse/deckhouse/issues/2110
```changes
type: chore
summary: Fix units for network graphs
```
> [monitoring-kubernetes] Fix units for network graphs

- ee/modules/110-istio/hooks/revisions_monitoring.go
- ee/modules/110-istio/hooks/revisions_monitoring_test.go
- ee/modules/110-istio/monitoring/prometheus-rules/revisions.yaml
Data plane versions monitoring refactoring. 
Fixes https://github.com/deckhouse/deckhouse/issues/2049.
```changes
section: istio
type: feature
summary: Data plane versions monitoring refactoring. 
```
> [istio] Data plane versions monitoring refactoring

- candi/cloud-providers/yandex/openapi/instance_class.yaml
- modules/030-cloud-provider-yandex/cloud-instance-manager/machine-class.yaml
- Fix docs for platformID, real default is `standard-v3`
- Explicitly set default in YandexMachineClass and fix docs
Real defaults differ from described in docs.
Machine-controller-manager don't roll out machines in Yandex cloud after release.
```changes
type: fix
summary: Fix defaults for diskType and platformID
```
> [cloud-provider-yandex] Fix defaults for diskType and platformID

- testing/matrix/linter/rules/modules/modules.go
- testing/matrix/matrix_test.go
Calculate focused modules before running module linter in matrix tests.
Ignore errors in other modules while testing one module.
Running 
```
FOCUS=openvpn go test ./testing/matrix/ -v
```
should not complain about errors in other modules.
```changes
type: fix
summary: support focusing for matrix tests linter
```
> [testing] support focusing for matrix tests linter

- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
- dhctl/cmd/dhctl/commands/config.go
- dhctl/cmd/dhctl/main.go
- dhctl/pkg/app/render.go
- dhctl/pkg/config/base.go
Fix panic in `config render bashible-bundle`.
In some cases we need to render `bootstrap.sh` and `bootstrap-networks.sh` for debug. I added `config render master-bootstrap-scripts` command for it.
Move loading meta config from file func to config module. 
Panic when run command.
N/A
```changes
section: dhctl
type: fix
summary: Fix `config render bashible-bundle` command and add `config render master-bootstrap-scripts` command
```
> [dhctl] Fix `config render bashible-bundle` command and add `config render master-bootstrap-scripts` command

- modules/402-ingress-nginx/webhooks/validating/ingressnginxcontroller
Add validation webhook
Ingress controllers < 1.1 are forbidden for k8s >= 1.22. We have to notify users about it and deny creation of such controllers
```changes
type: feature
summary: Validate ingress controllers compatibility with k8s version
```
> [ingress-nginx] add validation for controller version

- candi/cloud-providers/gcp/terraform-modules/base-infrastructure/variables.tf
Fixed bug preventing from bootstrap in GCP with "Standard" layout. The workaround for this is to remove "standard" section from init configuration at all.
The error from terraform, when `providerClusterConfiguration.standard` is prerent:
> Unusitable values for right operand: bool required
The problem is that right operand can become either `false`, which is ok, or an object, which is an error for && operation.
```
... && lookup(var.providerClusterConfiguration, "standard", false) ? ...
```
This place needs to be improved for type safety.
```changes
section: candi
type: fix
summary: Fixed cloudNATAddresses discovery when bootstrapping cluster in GCP with sandard layout
```
> [candi] Fix GCP terraform discovery of cloudNATAddresses

- .github/scripts/js/constants.js
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Add e2e tests for k8s 1.24
CI runs from the main branch. We have to merge tests before 1.24 release branch
```changes
section: ci
type: feature
summary: Add k8s 1.24 e2e tests
```
> [ci] Add e2e tests for 1.24

- .github/workflow_templates/deploy-channel.multi.yml
- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-early-access.yml
- .github/workflows/deploy-rock-solid.yml
- .github/workflows/deploy-stable.yml
- modules/020-deckhouse/docs/internal/RELEASE.md
- modules/020-deckhouse/hooks/check_deckhouse_release.go
- modules/020-deckhouse/hooks/check_deckhouse_release_test.go
- modules/020-deckhouse/hooks/update_deckhouse_image.go
- modules/020-deckhouse/hooks/update_deckhouse_image_test.go
- modules/402-ingress-nginx/hooks/requirements.go
Add cooldown feature for a release. Via this setting we can specify, when a release will be ready to be applied in a cluster. Release will download as soon as available and will wait for the specified cooldown time
Sometimes we want to have more flexible release process. Ex: create release at Friday and make it available at Monday. Also we can notify users about release automatically.
```changes
type: feature
summary: Add ability to postpone a release for applying inside a cluster
```
> [deckhouse] add release cooldown

- modules/300-prometheus/openapi/config-values.yaml
Prometheus doc vpa example fix.
There was weird example.
```changes
type: chore
summary: Prometheus doc vpa example fix.
```
> [prometheus] vpa example in doc fix

- .github/CODEOWNERS
Signed-off-by: Evgeny Samoylov <EvgenySamoylov@users.noreply.github.com>
Add cilium to the codeowners file.
Cilium is part of the platform now and needs to be managed and reviewed by its codeowners.
> Add cilium to codeowners

- werf.yaml
Fix indent
We have changed build step for changelog and indent became broken
```changes
section: ci
type: fix
summary: Fix indent
```
> [ci] fix indent on changelog build

- modules/500-upmeter/hooks/clean_probe_garbage.go
The hook can stuck main queue because of missing CRDs, e.g. `certifiates.cert-manager.io`. The PR make the hook tolerate API errors and report them with warning.
Avoids stucking queues in clusters where cert-manager module is off.
The main queue will not stuck
```changes
type: fix
summary: Fixed bug when cleaning old upmeter probe garbage resulting in errors stucks Deckhouse main queue
```
> [upmeter] Tolerate errors in hook cleaning garbage

- .github/workflow_templates/on-pull-request-backport.yml
- .github/workflows/on-pull-request-backport.yml
Fix commit SHA passed to the action
GITHUB_SHA is overwritten by github
```changes
section: ci
type: chore
summary: Fix SHA of the passing commit
```
> [ci] fix backport commit sha

- modules/031-linstor/monitoring/grafana-dashboards/storage/linstor_drbd.json
(cherry picked from commit 3544c53b1fe8f1140fa7bcbfbbb970750f4770b6)
#2147 
Fix timestamp on linstor dashboard
The current timestamp is hardcoded to specific time
Update linstor-dashboard
```changes
type: fix
summary: fix timestamp on linstor dashboard
```
> [linstor] fix timestamp on linstor dashboard (#2147)

- modules/500-upmeter/hooks/clean_probe_garbage.go
(cherry picked from commit aed6c02d69eb1d98b78c3ecd672ae48fa48d75d5)
Ref: #2221 
The hook can stuck main queue because of missing CRDs, e.g. `certifiates.cert-manager.io`. The PR make the hook tolerate API errors and report them with warning.
Avoids stucking queues in clusters where cert-manager module is off.
The main queue will not stuck
```changes
type: fix
summary: Fixed bug when cleaning old upmeter probe garbage resulting in errors stucks Deckhouse main queue
```
> [upmeter] Tolerate errors in hook cleaning garbage (#2264)

- modules/402-ingress-nginx/template_tests/controller_test.go
- modules/402-ingress-nginx/templates/controller/controller.yaml
Publish service for LB controllers
Ingress nginx controller publishes external IP for controller nodes. It is correct for HostPort controllers but unworkable for LoadBalancer controllers. With publish service controller will mirror the address of the service endpoints to the load-balancer status of the satisfied ingress objects. 
```changes
type: fix
summary: Add publish-service for LB controllers to update ingress status correctly
impact: LB ingress controllers will restart
impact_level: high 
```
> [ingress-nginx] publish service for LB controllers status

- ee/modules/110-istio/hooks/migration_remove_kiali_crds.go
- ee/modules/110-istio/hooks/migration_remove_kiali_crds_test.go
Delete an obsolete and no longer used CRD monitoringdashboards.monitoring.kiali.io
This CRD is no longer used
CRD monitoringdashboards.monitoring.kiali.io will be removed
Fixes (#1978)
```changes
section: istio
type: chore
summary: Delete an obsolete and no longer used CRD monitoringdashboards.monitoring.kiali.io (#1978)
```
> [istio] remove kiali CRD (#1978)

- modules/040-control-plane-manager/hooks/effective_kubernetes_version.go
- modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
Add an alert about deprecated kubernetes version
In the release 1.36 we will remove support of the 1.19 k8s version. We want to warn users about it
```changes
type: feature
summary: Add an alert about deprecated kubernetes version
```
> [control-plane-manager] alert k8s deprecated

- modules/031-linstor/images/drbd-driver-loader/Dockerfile
This PR fixes problem of building DRBD module on Rocky Linux
fixes https://github.com/deckhouse/deckhouse/issues/2268
drbd module compiled and successfully injected
```changes
type: fix
summary: add missing libelf-dev to kernel-module-injector
```
> [linstor] add missing libelf-dev to kernel-module-injector image

- modules/020-deckhouse/hooks/update_deckhouse_image.go
- modules/020-deckhouse/hooks/update_deckhouse_image_test.go
Ignore shutdown and evicted pods on deckhouse image upgrade
Shutdown and Evicted pods are presented in the snapshot and bring a mess to the controller logic. We have to ignore such kind of pods
```changes
type: fix 
summary: Ignore evicted and shutdown pods on the deckhouse update process. They could block the update
```
> [deckhouse] ignore shutdown pods on update

- ee/modules/600-flant-integration/monitoring/prometheus-rules/sending-alerts.yaml
Add `for: 5m` to D8PrometheusMadisonErrorSendingAlertsToBackend.
This helps to fix flaky alerts.
```changes
type: fix
summary: Add for to D8PrometheusMadisonErrorSendingAlertsToBackend
```
> [flant-integration] Add for to D8PrometheusMadisonErrorSendingAlertsToBackend

- ee/modules/600-flant-integration/monitoring/prometheus-rules/sending-alerts.yaml
Compare percent of errors with 0.
Wrong expression leads to alerts when there are no problems.
```changes
type: fix
summary: Fix expression for D8PrometheusMadisonErrorSendingAlertsToBackend
```
> [flant-integration] Fix expression for D8PrometheusMadisonErrorSendingAlertsToBackend

- ee/modules/600-flant-integration/images/flant-pricing/hooks/prometheus_metrics.sh
Added new distros supported by deckhouse.
Deckhouse supports now new distro versions, like ubuntu 22.04 or centos-8. But flant-pricing cannot detect them.
```changes
type: fchore
summary: added new distros supported by deckhouse
```
> [flant-integration] added new distros supported by deckhouse

- ee/modules/110-istio/templates/control-plane/iop.yaml
Don't exclude d8-namespaces from istiod discovery.
There are problems with dex-authenticator which is widely used in d8 modules. It isn't accessible from istio-enabled ingress controllers.
d8-namespaces are being discovered by istiod.
```changes
section: istio
type: fix
summary: Don't exclude d8-namespaces from istiod discovery.
```
> [istio] Don't exclude d8-namespaces from istiod discovery

- modules/031-linstor/docs/FAQ.md
- modules/031-linstor/docs/FAQ_RU.md
```changes
type: chore
summary: Add note about adding exiting pools using general configuration method
```
> [linstor] Add note about adding exiting pools using general configuration method

- modules/600-namespace-configurator/hooks/handler.go
- modules/600-namespace-configurator/hooks/handler_test.go
React to module values changes
If module values are changed, the hook applies new rules only on namespace changes. This is a problem and fixed by executing the hook before helm (even if there is no helm chart in the module).
```changes
section: namespace-configurator
type: fix
summary: React to module values changes
```
> [namespace-configurator] add run hook OnBeforeHelm

- .github/ci_templates/tests.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- testing/library/helm/render.go
- testing/matrix/linter/controller.go
- testing/matrix/linter/run.go
- testing/matrix/matrix_test.go
* Always load the Chart variable from the disk
* Avoid excessive `CoalesceValues` run
* Refactor the matrix tests suit a little
* Bump go to v1.18.4 (**the real fix!**)
Fixes the flakiness of matrix tests.
```changes
type: fix
summary: Fixes the flakiness of matrix tests.
```
> [testing] Always try to load chart

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
Added a second option to getting an etcd leader into the documentation.
```changes
section: docs
type: fix
summary: Added a second option to getting an etcd leader.
```
> [docs] Add a second option to getting an etcd leader

- candi/openapi/node_group.yaml
Fix typo in the NodeGroup example.
Close: #2180 
```changes
section: docs
type: fix
summary: Fix typo in the NodeGroup example
```
> [docs] Fix typo in the NodeGroup example

- modules/402-ingress-nginx/hooks/get_ingress_controllers.go
- modules/402-ingress-nginx/hooks/get_ingress_controllers_test.go
- modules/402-ingress-nginx/templates/controller/controller.yaml
We don't want to inject defaultControllerVersion to IngressNginxController CR
All templates fallback to defaultControllerVersion only if `.spec.controllerVersion` is not set explicitly in CR. 
```changes
type: fix
summary: Change defaultControllerVersion without deckhouse reboot
```
> [ingress-nginx] fix defaultControllerVersion inheritance

- ee/modules/110-istio/hooks/revisions_monitoring.go
- ee/modules/110-istio/hooks/revisions_monitoring_test.go
- ee/modules/110-istio/monitoring/prometheus-rules/revisions.yaml
- werf.yaml
Signed-off-by: Pavel Tishkov <pavel.tishkov@flant.com>
Removed all metrics for tracking istio revisions except d8_istio_pod_revisions. All alert logic is implemented in promql.
Added an alert (D8IstioPodsWithoutIstioSidecar) tracking pods without istio sidecar, in namespaces where the inject should happen. 
There is overengineered revisions_monitoring.go.
The following metrics will no longer be generated:
- d8_istio_desired_revision_is_not_installed
- d8_istio_data_plane_without_desired_revision
- d8_istio_actual_data_plane_revision_ne_desired
- d8_istio_data_plane_patch_version_mismatch
```changes
section: istio
type: chore
summary: refactor istio revision monitoring
```
> [istio] refactor revisions monitoring

- tools/validation/doc_changes.go
Added testing of the following files:
- openapi/cluster_configuration.y[a]?ml
- openapi/instance_class.y[a]?ml
- openapi/node_group.y[a]?ml
The Documentation validator doesn't cover some OpenAPI specs. E.g. spec of a module configuration, instanceClass, and nodeGroup specs.
[Example](https://github.com/deckhouse/deckhouse/runs/7952034332?check_suite_focus=true).
```changes
type: fix
summary: Fix doc validation file filter
```
> [testing] Fix doc validation file filter

- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
- docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS.md
- docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS_RU.md
Add api. domain into a hosts lists in the getting started
```changes
section: docs
type: fix
summary: Add `api.` domain into a hosts lists in the getting started.
```
> [docs] Add api. domain into a hosts lists in the getting started

- tools/validation/copyright.go
Skip copyright validation for the `.github/CODEOWNERS` file.
```changes
section: ci
type: chore
summary: Skip copyright validation for the `.github/CODEOWNERS` file
```
> [ci] Skip copyright validation for the `.github/CODEOWNERS` file

- candi/bashible/bundles/centos/node-group/031_install_containerd.sh.tpl
- candi/bashible/bundles/debian/node-group/031_install_containerd.sh.tpl
- candi/bashible/bundles/ubuntu-lts/node-group/031_install_containerd.sh.tpl
Fix docker-containerd migration.
1. On Ubuntu 22.04 on migration from docker to containerd crictl never installs.
2. On other distros, sometimes, containerd-shim locks directory /var/lib/docker and migration fails.
```changes
section: candi
type: fix
summary:  fix docker-containerd migration
```
> [bashible] fix docker-containerd migration

- modules/402-ingress-nginx/images/controller-0-33/Dockerfile
- modules/402-ingress-nginx/images/controller-0-33/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-0-46/Dockerfile
- modules/402-ingress-nginx/images/controller-0-46/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-0-48/Dockerfile
- modules/402-ingress-nginx/images/controller-0-48/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-0-49/Dockerfile
- modules/402-ingress-nginx/images/controller-0-49/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-1-1/Dockerfile
- modules/402-ingress-nginx/images/controller-1-1/rootfs/etc/nginx/lua/pbmetrics.lua
- Premature removal
`Premature timer expiration happens when the Nginx worker process is trying to shut down, as in an Nginx configuration reload triggered by the HUP signal or in an Nginx server shutdown.`
It seems like a good idea to send collected metrics on a worker shutdown. We are not using recursive timers, so can skip premature handler. Also we can close the tcp socket on premature
- Remove table copy
`Lua is single-threaded by design, one and only one thread can access the data at same moment.`
We can avoid an extra copy of a metrics table. Like an node event-loop nginx stops main thread execution when calls a timer's callback function, so we can avoid extra time and memory consumption
- We can backport it to 1.35, cause it …
> [ingress-nginx] pbmetrics improvement

- .github/ci_templates/build.yml
- .github/workflow_templates/build-and-test_dev.yml
- .github/workflow_templates/build-and-test_pre-release.yml
- .github/workflow_templates/build-and-test_release.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
Adds a check if the repository contains the actual GitHub workflow (that no one forgot to regenerate it).
Sometimes, after changing CI templates, authors forget to regenerate workflows.
- CI has to fail completely if workflow templates have been changed, but workflow has not been regenerated.
- CI should not fail if workflow templates have been changed and workflow has been regenerated.
```changes
type: chore
summary: Added a check if the repository contains the actual GitHub workflow (that no one forgot to regenerate it).
```
> [testing][ci] Add a check if the repository contains the actual CI workflow

- ee/modules/110-istio/monitoring/prometheus-rules/revisions.yaml
Fix `D8IstioDataPlaneVersionMismatch` alert.
There is an error in processing the alert.
```changes
section: istio
type: fix
summary: Fixed `D8IstioDataPlaneVersionMismatch` alert.
```
> [istio] Fix revision monitoring alert

- candi/control-plane-kubeadm/config.yaml.tpl
- modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/kube-etcd3.json
This PR adds GRPC request handling time and etcd peer RTT graphs to etcd dashboard.
Fixes #614. 
* etcd parameter `--metrics=extensive` added (enables `grpc_server_handling_seconds_bucket` metric)
* `grpc_server_handling_seconds_bucket` and `etcd_network_peer_round_trip_time_seconds_bucket` .99 quantile graphs added to etcd dashboard
Resulted panels look like this:
```changes
type: feature
summary: Add GRPC request handling time and etcd peer RTT graphs to etcd dashboard
impact: Etcd pods' restart, triggering leader elections and affecting Kubernetes API performance until all etcd pods use new configuration.
```
> [prometheus] Add dashboard etcd response time data

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/capacity-planning/capacity-planning.json
This is a big update to our capacity planning dashboard. 
With this it is possible to find:
* How many resources are requested
* How many requested resources are used
* Top container that make the impact
```changes
type: feature
summary: New Capacity Planning dashboard.
```
> [monitoring-kubernetes] New Capacity Planning dashboard

- dhctl/pkg/log/logger.go
- dhctl/pkg/log/options.go
- dhctl/pkg/system/ssh/frontend/waiting.go
* Changes font colour for bold blocks from white to normal
* Fail if there is empty host for ssh connection
```changes
section: dhctl
type: fix
summary: Changes font colour for bold blocks from white to normal
---
section: dhctl
type: fix
summary: Fail if there is empty host for ssh connection
```
> [dhctl] Change color, fix empty host connection attempts

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/node.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/nodes.json
* Change steppedLine property for CPU graphs
* Add sorting
Copy properties of the official dashboard
```changes
type: fix
summary: Change steppedLine to false for CPU panels and add sorting.
```
> [grafana-dashboards] Change steppedLine to false for CPU panels (#2368)

- modules/300-prometheus/images/grafana-dashboard-provisioner/Dockerfile
- modules/300-prometheus/images/grafana-dashboard-provisioner/hooks/dashboard_provisioner.sh
Fix and optimize grafana dashboard provisioner
Sometimes current provisioner script generates errors like:
```
find: /etc/grafana/dashboards/Main: No such file or directory"
```
cause of glob matching. I think we can use rsync for synchronizing tmp and target directories. It copies all files and then delete absent files, which generates more atomic changes for grafana dashboards
Grafana will not miss all dashboard on update
```changes
type: fix
summary: Fix grafana dashboard provisioner - avoid missing all dashboard on update
```
> [prometheus] fix grafana dashboard provisioner

- modules/020-deckhouse/hooks/update_deckhouse_image.go
Fix panic when have `Shutdown` Deckhouse pods. 
Cluster also can have evicted and shutdown pods. That was missed before
```
Schedule","queue":"/modules/deckhouse/update_deckhouse_image","task.flow":"start","task.id":"5c338ba4-2c0f-4bf8-9224-f0864d62894a","time":"2022-09-02T06:27:15Z"}
panic: interface conversion: go_hook.FilterResult is nil, not hooks.deckhousePodInfo
goroutine 1069 [running]:
github.com/deckhouse/deckhouse/modules/020-deckhouse/hooks.tagUpdate(0xc0023b4240, 0x2f37638, 0xc000201b60, 0x0, 0x0)
/deckhouse/modules/020-deckhouse/hooks/update_deckhouse_image.go:350 +0xc9f
github.com/deckhouse/deckhouse/modules/020-deckhouse/hooks.updateDeckhouse(0xc0023b4240, 0x2f37638, 0xc000201b60, 0x0, 0xc00044e518) …
```
> [deckhouse] Filter deckhouse pod by phase in update_deckhouse_image hook for prevent panic when have evicted pods

- docs/site/pages/index.html
- docs/site/pages/index_ru.html
- release.yaml
Change release requirements and documentation.
Kubernetes 1.19 is not supported anymore.
```changes
type: chore
summary: Change requirements for the 1.36 release.
```
> [deckhouse] change release requirements

- modules/042-kube-dns/templates/configmap.yaml
Prefer that cluster coredns uses UDP when communicating with upstream DNS servers. Dampens negative effects of [enabling](https://github.com/deckhouse/deckhouse/commit/00a3784fd9426fdb7c422d8454a0aa96506bb6a6) `serve_stale` option. 
We've observed a marked increase in kernel CPU usage after Deckhouse release v1.35.
coredns executes a massive amount of `connect(2)` syscall.
node-local-dns's coredns [uses](https://github.com/coredns/coredns/blob/66f2ac7568ccb0178cc9ce6dbd7320bcd3428d64/plugin/cache/cache.go#L127) TCP to prefetch and serve stale requests. This means that the forward plugin in kube-dns' coredns [attempts](https://github.com/coredns/coredns/blob/5b65a58d4883e91312fcb79911f71eb5a5993b47/plugin/forward/connect.go#L85) to use TCP to connect to its upstream DNS servers as well. …
> [kube-dns] prefer_udp

- ee/modules/110-istio/images/operator-v1x13/Dockerfile
- ee/modules/110-istio/images/pilot-v1x13/Dockerfile
- ee/modules/110-istio/images/proxyv2-v1x13/Dockerfile
Signed-off-by: Pavel Tishkov <pavel.tishkov@flant.com>
Bump istio version from 1.13.3 to 1.13.7
https://istio.io/latest/news/releases/1.13.x/
Istio 1.13.7 release contains a fixes for [CVE-2022-31045](https://istio.io/latest/news/security/istio-security-2022-005/#cve-2022-31045), [ISTIO-SECURITY-2022-005](https://istio.io/latest/news/security/istio-security-2022-005) and bug fixes to improve robustness.
Updating the patch version of istio will cause the `D8IstioDataPlaneVersionMismatch` alert to appear. To make the alert disappear, you must recreate all workloads so that the sidecar runs with the current version.
```changes
section: istio
type: chore
summary: bump istio version from 1.13.3 to 1.13.7
impact: | 
Updating the patch version of istio will cause the …
```
> [istio] bump istio version to 1.13.7

- candi/bashible/detect_bundle.sh
- dhctl/pkg/operations/bootstrap.go
- dhctl/pkg/template/bundle.go
Render detect_bundle.sh as template before execute
`detect_bundle.sh` pass to new cloud node via `user-data`. In AWS `user-data` has content size limit to 16kb.
For decrease size we remove comments via helm-template.
E2e should pass
```changes
section: dhctl
type: fix 
summary: Render detect_bundle.sh as template before execute.
```
> [candi][dhctl] Render `detect_bundle.sh` as template before execute

- ee/modules/110-istio/openapi/config-values.yaml
- ee/modules/110-istio/template_tests/module_test.go
- ee/modules/110-istio/templates/global-auth-policy.yaml
Signed-off-by: Pavel Tishkov <pavel.tishkov@flant.com>
Fix tlsMode param behavior.
Closes https://github.com/deckhouse/deckhouse/issues/2138
tlsMode: "Off" must totally disable the mutual tls, but it doesn't.
PERMISSIVE mode is applied to all incoming traffic. No policies were explicitly applied to outgoing traffic.
Default tlsMode now is: MutualPermissive.
PERMISSIVE mode is applied to all incoming traffic. 
ISTIO_MUTUAL mode is applied to all outgoing traffic. 
```changes
section: istio
type: fix
summary: Fix tlsMode param behavior.
```
> [istio] fix tlsMode param behavior

- modules/500-upmeter/images/upmeter/pkg/monitor/downtime/monitor.go
- modules/500-upmeter/images/upmeter/pkg/monitor/hookprobe/monitor.go
- modules/500-upmeter/images/upmeter/pkg/monitor/node/monitor.go
- modules/500-upmeter/images/upmeter/pkg/monitor/remotewrite/monitor.go
- modules/500-upmeter/templates/upmeter-agent/daemonset.yaml
EnableKubeEventCb should be enabled after setting the handler.
```changes
type: fix
summary: Fix deckhouse probe by placing EnableKubeEventCb call properly.
```
> [upmeter] Fix EnableKubeEventCb

- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/script.sh
Restore ubuntu image in e2e test
RedOS testing was used in the yandex.cloud with docker. It could not be boostrapped with error
```
│ │ bb-rp [INFO] Installing package 'docker-ce'
│ │ warning: docker-ce.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
│ │ error: Failed dependencies:
│ │ 	libcgroup is needed by docker-ce-3:19.03.15-3.el7.x86_64
│ │ Failed to execute step /var/lib/bashible/bundle_steps/031_install_docker.sh ... retry in 10 seconds.
│ └ Run step 031_install_docker.sh (40.82 seconds) FAILED
```
[here](https://github.com/deckhouse/deckhouse/runs/8266852873?check_suite_focus=true)
```changes
section: e2e
type: chore
summary: Use ubuntu image instead of redos for yandex cloud
```
> [e2e] Fix docker test in Yandex.Cloud

- modules/042-kube-dns/templates/service.yaml
kube-dns ExternalName Service fix — clusterDomain is taken into account.
It is impossible to resolve `kube-dns.kube-system.svc` hostname in clusters with non-standard clusterDomain.
```changes
type: fix
summary: kube-dns ExternalName Service fix — clusterDomain is taken into account.
```
> [kube-dns] clusterDomain is taken into account in kube-dns ExternalName Service

- .github/ci_templates/e2e_tests.yml
- .github/scripts/js/ci.js
- .github/scripts/js/git-ref.js
- .github/scripts/js/specs/git-ref.test.js
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- testing/cloud_layouts/script.sh
Added e2e tests to check deckhouse version updates.
```changes
section: e2e-tests
type: feature
summary: Added e2e tests to check deckhouse version updates
```
> [testing] added e2e tests to check deckhouse version updates

- modules/041-linstor/templates/linstor-controller/linstorcontroller.yaml
- modules/041-linstor/templates/linstor-scheduler/deployment.yaml
- modules/041-linstor/templates/tests/03-pod-with-volume.yaml
Correct image tags for LINSTOR
https://github.com/deckhouse/deckhouse/pull/2033 introduced new way of specifying docker image. However some images are not specified correctly.
Make linstor module able to deploy
```changes
type: fix
summary: fix image tag regression
```
> [linstor] fix image tag regression

- modules/045-snapshot-controller/templates/snapshot-validation-webhook/deployment.yaml
Snapshot-validation-webhook deployed on master but uses maxSurge value for system nodes.
Snapshot-validation-webhook able to update with single master
```changes
type: fix
summary: Fix `maxSurge` for `snapshot-validation-webhook`.
```
> [snapshot-controller] Fix maxSurge for snapshot-validation-webhook

- modules/021-cni-cilium/hooks/set_cilium_mode.go
- modules/021-cni-cilium/hooks/set_cilium_mode_test.go
In #2252 we forgot case when node routes should be set in static clusters.
In this PR we fix this case.
```changes
type: fix
summary:  Fix cilium mode for static clusters.
impact: "`cilium-agents` will be restarted."
```
> [cni-cilium] fix cilium mode for static clusters

- modules/002-deckhouse/hooks/internal/updater/updater.go
Remove useless messages
We have status and message for it. Left messages only for Pending status, because spamming with common messages does not look comfortable for reading
```
v1-34-13   true       Outdated   25d              Last Deployed release outdated
v1-35-0    true       Outdated   20d              Last Deployed release outdated
v1-35-1    true       Outdated   20d              Last Deployed release outdated
v1-35-2    true       Outdated   20d              Last Deployed release outdated
v1-35-3    true       Outdated   19d              Last Deployed release outdated
v1-35-4    true       Outdated   12d              Last Deployed release outdated
v1-35-5    true       Outdated   7d21h            Last Deployed release outdated …
```
> [deckhouse] remove messages on deckhouse releases

- modules/002-deckhouse/hooks/internal/updater/updater.go
- modules/002-deckhouse/hooks/update_deckhouse_image_test.go
Remove version data from release updating cm. This field is unused and was added for more verbosity. At the moment it creates problems and does not generate useful load
Avoid stucked D8IsUpdating alert
```changes
type: fix 
summary: Fix stucked `DeckhouseUpdating` alert during the deckhouse update process.
```
> [deckhouse] Fix deckhouse update cm

- modules/460-log-shipper/hooks/generate_config_test.go
- modules/460-log-shipper/hooks/internal/composer/composer.go
Skip pipeline if it has no existed destinations
The `generate_configuration` hook panics if lined destination is not in the cluster.
```changes
type: fix
summary: Ignore pipelines without destinations
```
> [log-shipper] Ignore pipelines without destinations

- .github/workflow_templates/on-pull-request-backport.yml
- .github/workflows/on-pull-request-backport.yml
Backport action supports only `vX.Y.Z` milestone format and fails on `X.Y.Z`. I guess we can support both versions
Don't fail on another milestone version
```changes
section: ci
type: chore
summary: Handle `X.Y.Z` milesone version
```
> [ci] Handle milestone format for backport

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/capacity-planning/capacity-planning.json
Add panels to find undersized pods (by CPU and Memory)
Closes https://github.com/deckhouse/deckhouse/issues/2435
```changes
type: feature
summary: Add underrequested pods to the Capacity Planning dashboard.
```
> [monitoring-kubernetes] Add underrequested pods

- ee/modules/110-istio/template_tests/module_test.go
- ee/modules/110-istio/templates/global-auth-policy.yaml
Wrong behavior of the default DestinationRule with istio tlsMode: MutualPermissive.
We don't need default DestinationRule at all when istio tlsMode is MutualPerissive.
Default DestinationRule will not be created if istio tlsMode = MutualPerissive
```changes
section: istio
type: fix
summary: Fix default `tlsMode` behavior.
```
> [istio] fix tlsMode MutialPermissive

- candi/bashible/common-steps/node-group/003_discover_node_ip.sh.tpl
Fix discover node ip on debian-based distros
In discover node ip step we detect node physical interface by `ls -l /sys/class/net/ | grep -vE "virtual|total" | awk '{print $9}'`.
But output of `ls -l /sys/class/net/ | grep -vE "virtual|total"` differs between rh-based and ubuntu-based distros.
In ubuntu:
```
root@dev-master-0:~# ls -l /sys/class/net/ | grep -vE "virtual|total"
lrwxrwxrwx 1 root root 0 Sep 14 18:26 ens3 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/net/ens3
```
in debian:
```
root@dev-master-0:~# ls -l /sys/class/net/ | grep -vE "virtual|total"
total 0
lrwxrwxrwx 1 root root 0 Sep 14 22:04 eth0 -> ../../devices/pci0000:00/0000:00:03.0/virtio0/net/eth0
```
```changes
section: candi
type: fix
summary: fix discover …
```
> [candi] fix discover node ip on debian-based distros

- .github/ci_templates/tests.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
Mount `~/deckhouse-bin-cache` to `/deckhouse/bin` into Docker container during matrix tests.
Such mount would allow to cache temporary binaries needed during the tests on runners.
This PR needed to implement #2426.
* Docker bind mount added to `matrix_run_args` template;
* Workflows `build-and-test_{dev,pre-release,release}.yml` rendered;
* Directory `~/deckhouse-bin-cache` created on runner during matrix tests;
* Directory `~/deckhouse-bin-cache` mounted to `/deckhouse/bin/` during matrix tests.
```changes
section: ci
type: chore
summary: Add binary cache for matrix tests
```
> [ci][testing] Add binary cache for matrix tests

- modules/500-upmeter/images/status/src/App.svelte
Fix hardcoded localhost in upmeter statuspage
It does no fetch the data in clusters
Statupage works again
```changes
type: fix
summary: Fix non-working statuspage by removing hardcoded localhost in backend URL
```
> [upmeter] Fix statuspage backend URL

- candi/bashible/common-steps/node-group/041_configure_sysctl_tuner.sh.tpl
- ee/modules/030-cloud-provider-openstack/templates/cni.yaml
- modules/021-cni-cilium/hooks/migrate_cni_secret.go
- modules/021-cni-cilium/hooks/migrate_cni_secret_test.go
- modules/021-cni-cilium/hooks/set_cilium_mode.go
- modules/021-cni-cilium/hooks/set_cilium_mode_test.go
- modules/021-cni-cilium/openapi/values.yaml
- modules/021-cni-cilium/template_tests/module_test.go
- modules/021-cni-cilium/templates/configmap.yaml
1. Revert bpf masquerading mode for all cilium installations except openstack.
2. Added setting rp_filter to 0 for all interfaces in sysctl_tuner script.
1. on openstack installations with bpf masquerading traffic from cluster to external floating ip does not work (floating ip added as node ExternalIP, and cilium does not masquerade traffic from another node to node with floating ip).  For all another installations bpf masquerade mode is preferred.
2. In systemd >=245 default rp_filter = 2, so in some cases without bpf masquerading traffic from pods to another pods on the same node does not work.
```changes
type: chore
summary: |
Reverted bpf masquerading mode for all cilium installations except in OpenStack. …
```
> [cni-cilium] Revert bpf masquerade for all cilium installations except openstack.

- modules/041-linstor/templates/linstor-affinity-controller/deployment.yaml
linstor-affinity-controller can't start:
```
Error: unknown flag: --leader-election-lease-name
```
linstor-affinity-controller is starting and working with no errors
```changes
type: fix
summary: Fix linstor-affinity-controller leader election.
```
> [linstor] fix linstor-affinity-controller leader election

- modules/040-node-manager/hooks/yandex_preemptibly_delete_preemtible_instances.go
- modules/040-node-manager/hooks/yandex_preemptibly_delete_preemtible_instances_test.go
1. Node's CreationTimestamp provides accurate metrics on when VM was actually created.
2. Added `allowFailure: true` to take into account that MCM deletes a Machine object for a long time (until drain finishes).
Machines were deleted in quick succession since hook failed and was restarted quickly after a backoff.
Machines are deleted in batches every 15 minutes.
```changes
type: fix
summary: Fixed a bug with spot Machine deletion in Yandex.Cloud. It now correctly deletes machines in 15 minute intervals.
```
> [node-manager] Subscribe to Node's CreationTimestamp instead of Machine's field in yandex_preemptibly_delete_preemtible_instances.go

- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
Better way to ignore kubelet mounts for node-exporter.
There are custom setups where kubelet data could be mounted in non-standard path like `/mnt/data/kubelet`. In this case, the exporter exports hundreds of unwanted metrics.
```changes
type: fix
summary: Better way to ignore kubelet mounts for node-exporter.
```
> [monitoring-kubernetes] exclude serviceaccount mounts for node-exporter

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/node.yaml
Fire alert only if current value of node_memory_SUnreclaim_bytes is already greater than 10% of total memory.
When a new node with big total memory is just created, then prediction works incorrectly.
```changes
type: fix
summary: Check current `node_memory_SUnreclaim_bytes` in the `NodeSUnreclaimBytesUsageHigh` alert.
```
> [monitoring-kubernetes] Check current node_memory_SUnreclaim_bytes in NodeSUnreclaimBytesUsageHigh alert

- modules/002-deckhouse/hooks/update_deckhouse_image_test.go
Fix temporary failing test
Test fails due to inner context reasons. Make it separated test
```changes
type: fix
summary: Fix test with inner context
```
> [deckhouse] fix test

- modules/040-node-manager/images/machine-controller-manager/werf.inc.yaml
[Update](https://github.com/deckhouse/mcm/pull/2) govmomi in MCM to the latest stable version.
govmomi commit: https://github.com/vmware/govmomi/pull/1997/commits/7cdad997ab5e78fb1ab86d12db1dfd8f6620e004
MCM fails to create a VM if a Network is a member of a Distributed Virtual Switch.
MCM successfully create a VM with a Network under Distributed Virtual Switch.
```changes
type: fix
summary: Updated govmomi to the latest version so that VMs with Networks under Distributed Virtual Switch can be created.
```
> [node-manager] Update govmomi in mcm

- .github/ci_templates/e2e_tests.yml
- .github/scripts/js/ci.js
- .github/scripts/js/constants.js
- .github/scripts/js/e2e-commit-status.js
- .github/scripts/js/time.js
- .github/workflow_templates/build-and-test_dev.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
The [Commit statuses API](https://docs.github.com/en/rest/commits/statuses#about-the-commit-statuses-api) was used when doing this PR.
After all tests pass successfully, a workflow will start and sets the `E2e test` status to 'pending'. In this status PR check will show `Some checks haven’t completed yet` message. 
After running the e2e test, we change the status of the `E2e test` to `success` or `failure` depending on the result of the test. Cancelled test will have `failrue` state.
`failrue` status shows `Some checks were not successful` message in the PR checks,  success - `All checks have passed`. `Details` link follows to e2e action run.
It is also possible to put the label `skip/e2e`, which will change the status of `E2e test` to `success`. Unfortunately the API does not provide a …
> [ci] Make executing a single e2e test mandatory to accept the PR

- candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf
Add routes to netplan config in user-data for NAT instance.
If we have `nodeNetworkCIDR` set to 192.168.199.0/24 then we have 3 subnets. NAT instance knows only routes to the subnet where it's located, but has no routes to other subnets in VPC. So network on nodes in other subnets doesn't work properly. This pr creates correct routes for the whole VPC:
```
192.168.199.0/24 dev eth1 proto static scope link
```
Network is already configured similarly for master nodes using bashible:
```
root@p-k-aksenov-tmp-ks-master-0:~# cat /etc/netplan/999-cim-eth1.yaml 
network:
version: 2
ethernets:
eth1:
dhcp4: true
dhcp4-overrides:
use-hostname: false
use-routes: false
match:
macaddress: d0:1d:10:f8:95:5d
routes:
- to: 192.168.199.0/24 …
```
> [candi][cloud-provider-yandex] Fix routes for multi-zonal clusters when using WithNATInstance layout

- modules/021-cni-cilium/templates/configmap.yaml
When we run cilium in VXLAN mode `install-no-conntrack-iptables-rules` option should be disabled.
```changes
type: fix
summary: fix error running in VXLAN mode
```
> [cni-cilium] fix error running in VXLAN mode.

- modules/021-cni-cilium/templates/configmap.yaml
Changed two cilium config fields.
1. Changed DNS response to handle all resolvers better (looking at you, Alpine)
2. CNP and CCNP status updates were found to be clobbering apiserver performance with their count and size. Disabled them completely, since no use has been found for them.
1. All distributions are properly supported when using FQDN policies
2. CNP and CCNP Status updates no longer clog the apiserver
```changes
type: feature
summary: |
1. All distributions are properly supported when using FQDN policies
2. CNP and CCNP Status updates no longer clog the apiserver
```
> [cni-cilium] ConfigMap changes

- ee/modules/110-istio/monitoring/prometheus-rules/revisions.yaml
fixed `D8IstioActualDataPlaneRevisionNeDesired` alert 
This alert also triggers if there is no istio-sidecar in the pod, although there is a separate alert for this `D8IstioPodsWithoutIstioSidecar`
Alert does not triggers on pods without istio-sidecar
```changes
section: istio
type: fix
summary: Fixed `D8IstioActualDataPlaneRevisionNeDesired` alert.
```
> [istio] fix D8IstioActualDataPlaneRevisionNeDesired alert

- .github/scripts/js/ci.js
Add example to release issue template on how to run e2e test with switch releases.
Fix absent documentation in #2283.
Command to run e2e test with switch release should be in new release issue.
```changes
section: ci
type: fix
summary: Add example to release issue template on how to run e2e test with switch releases.
impact: low
```
> [ci] add documentation on how to run e2e test with switch releases

- modules/402-ingress-nginx/template_tests/controller_test.go
- modules/402-ingress-nginx/templates/controller/configmap.yaml
- modules/402-ingress-nginx/templates/controller/fake-ingress.yaml
- modules/402-ingress-nginx/templates/controller/secret.yaml
Generate ingress for tracking IngressNginxController `additionalHeaders` field like this:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
labels:
heritage: deckhouse
name: testname-custom-headers-reload
namespace: d8-ingress-nginx
spec:
ingressClassName: nginx
rules:
- host: reload-testname.deckhouse.io
http:
paths:
- backend:
service:
name: fakeservice
port:
name: https
path: /d18475119d75d3c873bd30e53f4615ef66bf84d9ae1508df173dcc114cfecbb4
pathType: ImplementationSpecific
```
where:
`testname` - the name on IngressNginxController CR
`path` - checksum of all additionalHeaders
When we change a list of additionalHeaders in a IngressNginxController CR it does not trigger configuration reload and …
> [ingress-nginx] reload controller config on custom headers change

- modules/340-monitoring-deckhouse/monitoring/prometheus-rules/deckhouse.yaml
…rom D8DeckhouseQueueIsHung alert
Remove queue /modules/deckhouse/update_deckhouse_image from D8DeckhouseQueueIsHung alert.
Hook in this queue starts every 15 sec,  but standard prometheus scrape interval is 30 sec, so alert in this queue is false positive.
```changes
type: chore
summary: remove queue /modules/deckhouse/update_deckhouse_image from D8DeckhouseQueueIsHung alert to prevent false positive triggers.
```
> [monitoring] remove queue /modules/deckhouse/update_deckhouse_image from D8DeckhouseQueueIsHung alert

- ee/modules/110-istio/template_tests/module_test.go
- ee/modules/110-istio/templates/alliance/ingressgateway/podmonitor.yaml
Signed-off-by: Pavel Tishkov <pavel.tishkov@flant.com>
Added podmonitor resource for scraping metrics from istio ingress gateway
Closes https://github.com/deckhouse/deckhouse/issues/2492
There are metrics from istio ingress gateway
```changes
section: istio
type: chore
summary: Added podmonitor resource for scraping metrics from istio ingress gateway
```
> [istio] add podmonitor for istio ingress gateway

- modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificates-exporter-health.yaml
Remove D8CertExporterStuck alert.
1. `D8CertExporterStuck` alert contains mistake.
2. We have named [TargetDown alert](https://github.com/deckhouse/deckhouse/blob/af6a01a90a0e79a0a4242b0c58ca0a3a940cb7ac/modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificates-exporter-health.yaml#L4) for cert-exporter and `D8CertExporterStuck` alert is unnecessary.
`D8CertExporterStuck` should go out
```changes
type: fix
summary: Remove D8CertExporterStuck alert
```
> [extended-monitoring] Remove `D8CertExporterStuck` alert

- candi/bashible/bashible.sh.tpl
- candi/bashible/bundles/centos/bootstrap.sh.tpl
- candi/bashible/bundles/ubuntu-lts/bootstrap.sh.tpl
- testing/cloud_layouts/script.sh
Fix bashible output to english only.
In some localized distros LANG is set to ru.UTF-8. We wants english output.
```changes
section: candi
type: chore
summary: Only english output from bashible scripts
```
> [candi] fix bashible output to english

- candi/cloud-providers/aws/openapi/cluster_configuration.yaml
- docs/site/_includes/getting_started/aws/partials/config.yml.standard.ce.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.standard.ee.inc
Getting rid of unused `associatePublicIPToNodes` and `associatePublicIPToMasters` args.
It confuses people with Standard layout installed.
```changes
section: candi
type: fix
summary: Got rid of unused `associatePublicIPToNodes` and `associatePublicIPToMasters` args in AWS Standard layout.
```
> [cloud-provider-aws] Getting rid of unused associatePublicIPToNodes arg

- modules/040-node-manager/monitoring/prometheus-rules/early-oom.tpl
Signed-off-by: Andrey Polovov <andrey.polovov@flant.com>
D8EarlyOOMPodIsNotReady alert description fix
Just more convenient description.
```changes
type: fix
summary: Fixed the `D8EarlyOOMPodIsNotReady` alert description.
```
> [node-manager][early-oom] alert description fix

- go_lib/hooks/tls_certificate/order_certificate.go
Re-issue certificate 15 dayes before expiration
We have prometheus alert `CertificateSecretExpiredSoon` that starts firing 14 days before
ceertificate expiration. We need to re-issue certificate earlier to avoid useless alerts.
Useless `CertificateSecretExpiredSoon` alerts do not fire.
```changes
type: fix
summary: Changed certificate re-issue time to 15 days before expiration to avoid useless `CertificateSecretExpiredSoon` alerts.
```
> [go_lib] Re-issue certificates 15 days before expiration

- modules/300-prometheus/images/grafana/Dockerfile
Input lags in Grafana were reported by users. This PR bumps Grafana patch version that fixes the problem.
Fix UX in Grafana.
No input lag in grafana inputs.
```changes
type: fix
summary: Fixed input lag by bumping grafana version to 8.5.13
```
> [prometheus] Bump grafana to 8.5.13 to fix input lag

- ee/modules/110-istio/monitoring/prometheus-rules/revisions.yaml
fix D8IstioDataPlaneWithoutIstioInjectionConfigured alert description
It doesn't work in real clusters.
```changes
section: istio
type: fix
summary: Fix `D8IstioDataPlaneWithoutIstioInjectionConfigured` alert description.
```
> [istio] fix D8IstioDataPlaneWithoutIstioInjectionConfigured alert description

- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
Forbid using additional properties in `nodeGroups[*]` and `nodeGroups[*].instanceClass` for YandexClusterConfiguration
For example, next configuration was passed but configuration was incorrect.
```
nodeGroups:
- name: khm
replicas: 1
externalIPAddresses: # should not allow
- Auto
instanceClass:
cores: 2
memory: 4096
imageID: fd8vqk0bcfhn31stn2ts
coreFraction: 50
zones:  # should not allow
- ru-central1-c
```
Static node was created but was not bootstrapped with above configuration in WithoutNAT layout.
```changes
section: cloud-provide-yandex
type: fix
summary: Fix allowing additional properties for nodeGroups[*] and nodeGroups[*].instanceClass
```
> [cloud-provider-yandex] Fix allowing additional properties for nodeGroups[*] and nodeGroups[*].instanceClass

- global-hooks/calculate_resources_requests.go
- global-hooks/calculate_resources_requests_test.go
Reduce percent from 50 to 40.
There was refactoring of resources requests in 1.36. Several problems with over-requests occurred after release, and because of it, some DaemonSet pods get stuck in pending state. It seems correct to just reduce percent.
```changes
type: fix
summary: Reduce static requests for control-plane pods
impact: Control-plane components will restart.
```
> [global-hooks] Reduce static requests for control-plane pods

- ee/modules/110-istio/hooks/deprecated_module_params_monitoring.go
- ee/modules/110-istio/hooks/deprecated_module_params_monitoring_test.go
- ee/modules/110-istio/monitoring/prometheus-rules/deprecated_params.yaml
Added an alert that config parameter `tlsMode` will be removed in deckhouse version 1.38.0. 
This alert is needed to warn users using that  config parameter.
Users using the `tlsMode` parameter will receive a warning alert
The part of https://github.com/deckhouse/deckhouse/issues/2562
```changes
section: istio
type: chore
summary: Added an alert that `tlsMode` module parameter will be removed in deckhouse v1.38.0. 
```
> [istio] add an alert for deprecated tlsMode param

- tools/release/d8-pull.sh
CE does not need docker login
Currently script fails on CE without license
```changes
section: tools
type: fix 
summary: Fix d8-pull.sh script for CE
```
> [tools] fix d8-pull.sh script for CE edition

- .github/ci_templates/e2e_tests.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Add timeout for bootstrap and cleanup e2e cluster steps
Cluster bootstrap/cleanup jobs can stuck. For example, we had situation when e2e for static cluster can not finish because ssh-client stuck without responsibility and job did not finish. Now, we limit job execution with [timeout-minutes field](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes)
[Tested here](https://github.com/deckhouse/deckhouse-test-2/actions/runs/3130665891)
```changes
section: ci
type: feature
summary: Add timeout for bootstrap and cleanup e2e cluster steps
```
> [ci] Add timeout for bootstrap and cleanup e2e cluster steps

- helm_lib/templates/_node_affinity.tpl
- modules/101-cert-manager/template_tests/module_test.go
This PR adds linstor taints to `helm_lib_internal_node_problems_tolerations`:
```yaml
- key: drbd.linbit.com/lost-quorum
- key: drbd.linbit.com/force-io-error
- key: drbd.linbit.com/ignore-fail-over
```
LINSTOR module can add specific taints on nodes which will prevent CNI pods scheduled
fixes https://github.com/deckhouse/deckhouse/issues/2518
Able to schedule CNI-plugin pod on nodes with storage problems 
```changes
type: fix
summary: fix scheduling cni pods on tainted nodes
impact: CNI plugin pods and kube-proxy will be restarted
```
> [linstor] fix: scheduling cni on tainted nodes

- ee/modules/600-flant-integration/images/flant-pricing/hooks/node_metrics.sh
Fixes the bug where we count control plane nodes as VMs for charge.
Fixes telemetry correctness
```changes
type: fix
summary: Fixed telemetry reporting control-plane nodes as nodes for charge.
```
> [flant-integration] Fix erronous control-plane accounting in VMs

- testing/cloud_layouts/script.sh
e2e upgrade test — deckhouse pod ready timeout fix.
3 minutes aren't enough to upgrade d8.
```changes
type: fix
summary: e2e upgrade test — deckhouse pod ready timeout fix.
impact: low
```
> [testing] e2e deckhouse ready timeout fix

- modules/041-linstor/templates/nodegroupconfiguration-install-kernel-headers.yaml
This PR improves logic for detecting kernel-headers package
Unlike DEB, RPM based distros does not include package name into kernel version.
We need additional detection for package name.
RPM-based distros using non-default kernel able to install kernel-headers for it.
```changes
type: fix
summary: Improve kernel-headers detection for СentOS.
```
> [linstor] Improve kernel-headers detection for centos

- .golangci.yaml
- go_lib/set/set.go
- modules/460-log-shipper/hooks/generate_config_test.go
- modules/460-log-shipper/hooks/internal/composer/config.go
- modules/460-log-shipper/hooks/internal/vector/destination/common.go
- modules/460-log-shipper/hooks/internal/vector/destination/elasticsearch.go
- modules/460-log-shipper/hooks/internal/vector/destination/logstash.go
- modules/460-log-shipper/hooks/internal/vector/destination/loki.go
- modules/460-log-shipper/hooks/internal/vector/destination/vector.go
- modules/460-log-shipper/hooks/internal/vector/source/file.go
- modules/460-log-shipper/hooks/internal/vector/source/kubernetes.go
- modules/460-log-shipper/hooks/internal/vector/transform/elasticsearch.go
- modules/460-log-shipper/hooks/internal/vector/transform/extra_fields.go
- modules/460-log-shipper/hooks/internal/vector/transform/filter.go
- modules/460-log-shipper/hooks/internal/vector/transform/multiline.go
- modules/460-log-shipper/hooks/internal/vector/transform/source.go
- modules/460-log-shipper/hooks/internal/vector/transform/testdata/extra-labels.json
- modules/460-log-shipper/hooks/internal/vector/transform/testdata/filters.json
- modules/460-log-shipper/hooks/internal/vector/transform/testdata/multiline.json
- modules/460-log-shipper/hooks/internal/vector/transform/throttle.go
- modules/460-log-shipper/hooks/internal/vector/transform/transforms.go
- modules/460-log-shipper/hooks/internal/vector/transform/transforms_test.go
- modules/460-log-shipper/hooks/testdata/file-to-elastic.json
- modules/460-log-shipper/hooks/testdata/file-to-vector.json
- modules/460-log-shipper/hooks/testdata/many-to-one.json
- modules/460-log-shipper/hooks/testdata/multiline.json
- modules/460-log-shipper/hooks/testdata/one-dest.json
- modules/460-log-shipper/hooks/testdata/throttle.json
Two bugs were spotted and fixed:
* Parse JSON rule is added even if there are no log filter rules.
* Only the last works for many sources that point to a single destination.
```changes
type: fix
summary: Stop generating pointless 'parse_json' transform, which improves performance.
---
type: fix
summary: Fix the bug when the many sources point to the same input and only the last is working.
```
> [log-shipper] Fix many source to one destination pipelines

- ee/modules/110-istio/monitoring/prometheus-rules/controlplane.yaml
fix `D8IstioAdditionalControlplaneDoesntWork` alert
Inaccurate label selection leads to erroneous triggering of the alert
No false alarms
```changes
section: istio
type: fix
summary: fix `D8IstioAdditionalControlplaneDoesntWork` alert
```
> [istio] fix D8IstioAdditionalControlplaneDoesntWork alert

- modules/500-upmeter/templates/upmeter-agent/daemonset.yaml
Reducing QPS and burst
Reduces the load on etcd and apiserver in multi-control-plane clusters. The change decreases the
latency by the cost of throttling in Upmeter Agent. We'll need to investigate the issue and probably
optimize the Agent code.
Kube-apiserver latency decreases.
```changes
type: fix
summary: Reduces QPS and burst in `upmeter-agent` to reduce `kube-apiserver` latency in multi-control-plane setups.
```
> [upmeter] Reduce QPS and busrt for kube-client

- ee/modules/110-istio/hooks/patch_injector_configmap.go
- ee/modules/110-istio/hooks/patch_injector_configmap_test.go
- go.mod
Cpu limits for istio-proxy sidecars has been removed.
In some cases the isiot-proxy gets throttled, we want to get rid of the CPU limits set for istio-proxy.
All istio-proxy sidecars will be creater without cpu limits.
```changes
section: istio
type: chore
summary: Cpu limits for istio-proxy sidecars has been removed.
```
> [istio] remove cpu limist for istio-proxy

- ee/modules/110-istio/hooks/patch_injector_configmap.go
- ee/modules/110-istio/hooks/patch_injector_configmap_test.go
- werf.yaml
Fixed filter and hook logic
Improving the hook performance
-
```changes
section: istio
type: fix
summary: Fixed filter and hook logic
```
> [istio] fix patch injector configmap hook 

- modules/500-upmeter/images/status/src/App.svelte
- modules/500-upmeter/images/status/src/lib/StatusText.svelte
- modules/500-upmeter/images/upmeter/pkg/server/api/public_status.go
The status page is empty when the upmeter server responds with status 500 due to empty data.
That is being fixed.
Fixes #2611
Status page explicitly sais it has no data to show
```changes
type: fix
summary: Fixed empty status page when there is no data in the upmeter server.
```
> [upmeter] Fix silent status page on empty data

- modules/150-user-authn/images/dex/Dockerfile
- modules/150-user-authn/images/dex/patches/README.md
- modules/150-user-authn/images/dex/patches/connector-data.patch
It fixes the problem, that in some cases connector data is picked from the refresh token instead of offline session
```changes
type: fix
summary: Do not use connectorData field of refresh token objects to refresh tokens
```
> [user-authn] Fix bug in Dex with the connectorData field

- modules/040-node-manager/templates/early-oom/daemonset.yaml
Added VPA for early-oom daemonset.
Previously early-oom has static resources requests and limits(and requests = limits). On big nodes (>100 cpu) early-oom pod needs more cpu than allowed by limit. Standard solution - use VPA to calculate requests based on real cpu usage.
```changes
type: fix
summary: Added VPA for early-oom daemonset.
```
> [node-manager] added VPA for early-oom daemonset

- candi/bashible/common-steps/node-group/050_configure_and_start_docker.sh.tpl
docker logout on nodes if registry auth is removed.
When kubelet downloads kubernetes-api-proxy, pause images, static prod images, it needs 
access to registry. So we execute docker login to registry on nodes. But when we change Deckhouse release from EE to CE, registry authentication is not needed anymore. This PR removes unused credentials for docker. 
```changes
section: candi
type: chore
summary: docker logout on nodes if registry auth is removed
```
> [candi] docker logout on nodes if registry auth is removed

- modules/500-upmeter/images/upmeter/pkg/agent/agent.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/base.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/certificate_secret.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/d8_clusterconfiguration.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_basic_lifecycle.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_basic_lifecycle_test.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_configmap.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_controller_lifecycle.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_controller_lifecycle_test.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_controlplane.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_daemonset.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_namespace.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_nodegroup.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_pod.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_scheduling.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_scheduling_test.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_statefulset.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_controlplane.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_deckhouse.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_extensions.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_loadbalancing.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_monitoring_and_autoscaling.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_nginx.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_nodegroups.go
- modules/500-upmeter/images/upmeter/pkg/probe/load.go
- modules/500-upmeter/images/upmeter/pkg/probe/load_test.go
- modules/500-upmeter/images/upmeter/pkg/server/server.go
Optimizes the preflight check to reduce the load of similar /version requests.
Reduces the throttling in checks.
Less throttling in upmeter-agent resulting in more frequent update of probe results
```changes
type: fix
summary: Reduced API calls throttling by the deduplication of preflight checks in probes.
```
> [upmeter] Optimize control-plane preflight check
