modules/300-prometheus/images/prometheus/patches/fix-cve.patch
Bump lib golang/glog version to fix cve. 
Vulnerability fixes.
Not necessary.
```changes
type: chore
summary: Bump lib golang/glog version to fix cve. 
```
=> [prometheus] bump golang/glog version to fix cve

modules/300-prometheus/templates/grafana/deployment-v10.yaml, modules/300-prometheus/templates/grafana/ingress-v10.yaml
Fixed CVEs
```changes
type: fix
summary: Fix grafana CVEs
```
=> [prometheus] Fix grafana CVEs

ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/patches/001-fix-empty-shared-bandwidth-id-sending.patch, ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/patches/README.md, ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/patches/comment_some_fields.patch, ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/werf.inc.yaml, ee/modules/030-cloud-provider-huaweicloud/templates/cloud-controller-manager/rbac-for-us.yaml
Prevent sending empty shared bandwidth identifier in HTTP requests to create `EIP`.
If we try to create an `EIP` with an empty shared bandwidth ID, the `EIP` will be automatically deleted, for example:
```json
{
"bandwidth": {
"id": "",
"charge_mode": "traffic",
"name": "d8-ingress-nginx_nginx-load-balancer",
"share_type": "PER",
"size": 5
},
"publicip": {
"type": "5_bgp"
}
}
```
```changes
type: fix
summary: Fix `EIP` creation in `cloud-controller-manager`.
```
=> [huaweicloud] Fix `EIP` creation in `cloud-controller-manager`

modules/040-terraform-manager/images/terraform-manager-aws/patches/gomod_update.patch, modules/040-terraform-manager/images/terraform-manager-aws/werf.inc.yaml
cve fix terraform-manager-aws and bump go version
cve fix
```changes
type: fix
summary: cve fix terraform-manager-aws and bump go version
```
=> [terraform-manager] cve fix terraform-manager-aws

modules/110-istio/images/proxyv2-v1x19x7/werf.inc.yaml
Return missed `librt.so.1` and `libpthread.so.0` libraries.
If we run Istio 1.19.7 and try to add sidecars for applications, a pod startup error will occur due to the lack of a libraries for envoy proxy operation.
Sidecars and ingressgateway do not work in Istio version 1.19.7. We have a failure in the operation of applications deployed in the cluster.
```changes
section: istio
type: fix
summary: Return missed `librt.so.1` and `libpthread.so.0` libraries
impact: ingressgateway pods in d8-istio namespace will be restarted, it is advisable to restart application pods with istio sidecars.
```
=> [istio] Fix missing libraries for envoy 

modules/160-multitenancy-manager/docs/USAGE.md, modules/160-multitenancy-manager/docs/USAGE_RU.md
Updated the GitHub links for template descriptions in USAGE.md to point to the correct 'templates' directory instead of the 'default' directory.
```changes
type: chore
summary: Update Project template paths in the documentation.
```
=> [multitenancy-manager][docs] update template paths

modules/040-terraform-manager/images/terraform-manager-gcp/patches/README.md, modules/040-terraform-manager/images/terraform-manager-gcp/patches/go_mod.patch, modules/040-terraform-manager/images/terraform-manager-gcp/patches/remove_routes_on_deletion.patch, modules/040-terraform-manager/images/terraform-manager-gcp/werf.inc.yaml
cve fix terraform-manager-gcp and bump go version
```changes
type: fix
summary: cve fix terraform-manager-gcp and bump go version
```
=> [terraform-manager] cve fix terraform-manager-gcp

candi/version_map.yml, modules/040-node-manager/images/cluster-autoscaler/patches/1.27/README.md, modules/040-node-manager/images/cluster-autoscaler/patches/1.27/go_mod.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.28/README.md, modules/040-node-manager/images/cluster-autoscaler/patches/1.28/go_mod.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.29/README.md, modules/040-node-manager/images/cluster-autoscaler/patches/1.29/go_mod.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.30/README.md, modules/040-node-manager/images/cluster-autoscaler/patches/1.30/go_mod.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.31/README.md, modules/040-node-manager/images/cluster-autoscaler/patches/1.31/go_mod.patch, modules/040-node-manager/images/cluster-autoscaler/werf.inc.yaml, modules/040-node-manager/images/machine-controller-manager/werf.inc.yaml
security
```changes
type: fix
summary: fixed cve in images cluster-autoscaler and machine-controller-manager
```
=> [node-manager] fixed cve in images cluster-autoscaler and machine-controller-manager 

modules/000-common/images/kubernetes/patches/1.28/005-gomod.patch, modules/000-common/images/kubernetes/patches/1.29/005-gomod.patch, modules/000-common/images/kubernetes/patches/1.30/005-gomod.patch, modules/000-common/images/kubernetes/patches/1.31/005-gomod.patch
Add patches to kubernetes to fix CVE
Security improvement to fix CVE in dependencies
Fix CVE in 1.68 release
```changes
type: chore
summary: Add patches to kubernetes to fix CVE.
```
=> [common] Kubernetes CVE fixes

modules/007-registrypackages/images/crictl/patches/1.27.1/go_mod.patch, modules/007-registrypackages/images/crictl/patches/1.28.0/go_mod.patch
Update patches to fix CVE
Security improvement to fix CVE in dependencies
Fix CVE in 1.68 release
```changes
type: chore
summary: pdate crictl patches to fix CVE.
```
=> [crictl] Update patches

modules/007-registrypackages/images/ecr-credential-provider/patches/1.27/gomod.patch, modules/007-registrypackages/images/ecr-credential-provider/patches/1.28/gomod.patch, modules/007-registrypackages/images/ecr-credential-provider/patches/1.29/gomod.patch, modules/007-registrypackages/images/ecr-credential-provider/patches/1.30/gomod.patch, modules/007-registrypackages/images/ecr-credential-provider/patches/1.31/gomod.patch, modules/007-registrypackages/images/ecr-credential-provider/werf.inc.yaml
Update ecr-credential-provider build and fix CVEs
Security improvement to fix CVE in dependencies
Fix CVE in 1.68 release
```changes
type: chore
summary: Update ecr-credential-provider build and fix CVE.
```
=> [registrypackages] Update ecr-credential-provider build and fix CVEs

tools/cve/trivy-wrapper.sh
Added trivy parameter to filter out false positive reports
To filter out false positive reports
```changes
section: tools
type: fix
summary: none
impact: none
```
=> [CVE] Trivy scanners vuln

werf_cleanup.yaml
Increase limits for stored images in dev-registry:
- 21 days (from 14 days) for main branch;
- 4 latest release branches (from 3);
- 10 latest release tags (from 3).
Also limit number of stored versions for release branches and release tags to 1.
As available volume for stored built images was increased recently, we now want to keep more previous versions in dev-registry.
```changes
section: ci
type: chore
summary: Increase limits for werf-cleanup.
```
=> [ci] Increase limits for werf-cleanup

modules/040-terraform-manager/images/base-terraform-manager/patches/001-go-mod.patch
Partiality fix `github.com/hashicorp/go-getter` and `github.com/hashicorp/go-slug` CVE's
Improve security
```changes
section: 
type: chore
summary: Fix terraform CVE's
```
=> [terraform-manager] Fix terraform CVE's

modules/021-cni-cilium/templates/configmap.yaml
When cilium neighbor discovery is enabled (by default) and a neighboring node is not available, cilium sends ARP requests for the IP address of this node to all network interfaces, thereby misleading certain switches (they start thinking that the sender's IP address belongs to two (or more) ports) and cyclically sends traffic to one port, then to another, then to one, then to another..
I don't see a case where this behavior can help us. I suggest disabling this artificial intelligence of cilium by default
[https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#neighbor-discovery](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#neighbor-discovery)
before:
after:
This solves the problem of traffic "freezing" on L3 switches
```changes …
```
=> [cni-cilium] l2 neigh discovery (arp flood) disabled

candi/terraform_versions.yml, ee/candi/cloud-providers/dynamix/terraform-modules/master-node/variables.tf, ee/candi/cloud-providers/dynamix/terraform-modules/versions.tf, ee/modules/030-cloud-provider-dynamix/images/capd-controller-manager/werf.inc.yaml, ee/modules/030-cloud-provider-dynamix/images/cloud-controller-manager/werf.inc.yaml, ee/modules/030-cloud-provider-dynamix/images/cloud-data-discoverer/werf.inc.yaml, ee/modules/030-cloud-provider-dynamix/images/dynamix-csi-driver/werf.inc.yaml, ee/modules/040-terraform-manager/images/terraform-manager-dynamix/patches/readme.md, ee/modules/040-terraform-manager/images/terraform-manager-dynamix/patches/update_gomod.patch, ee/modules/040-terraform-manager/images/terraform-manager-dynamix/werf.inc.yaml
cve fix dynamix cloud provider and bump go version
cve fix
```changes
type: fix
summary: cve fix dynamix cloud provider and bump go version
```
=> [terraform-manager] cve fix terraform-manager-dynamix

modules/015-admission-policy-engine/hooks/trivy_provider_registry_secrets.go, modules/015-admission-policy-engine/hooks/trivy_provider_registry_secrets_test.go
It fixes incorrect trivy-provider secret when using anonymous registry cred secret. 
Fixes #12000
Anonymous cred will be:
```
{"auths":{"registry.rmorozov.ru/dev":{}}}
```
```changes
type: fix
summary: Fix the trivy provider hook to support anonymous registry cred secret.
```
=> [admission-policy-engine] fix the trivy provider hook to support anonymous cred registry secret

candi/openapi/dhctl/ssh_configuration.yaml, dhctl/cmd/dhctl/commands/terraform.go, dhctl/pkg/config/connection.go, dhctl/pkg/config/connection_test.go, dhctl/pkg/config/load.go, dhctl/pkg/operations/converge/converger.go
This PR fixes `--connection-config` option in dhctl CLI, it is broken in current version.
Ability to pass sudoPassword using SSHConfig kind in `--connection-config` yaml configuration file (non-interactively).
Non-interactive declarative way to specify connection settings with the option `--connection-config` is now fully available in  dhctl CLI. In previous versions of deckhouse it only worked in the dhctl-server, but it was broken in dhctl-cli: private ssh-keys was not added into the agent properly.
SudoPassword needed for full support of different connection options.
=> [dhctl] Fix broken connection-config in CLI and support sudoPassword in SSHConfig

candi/openapi/dhctl/ssh_configuration.yaml, dhctl/cmd/dhctl/commands/terraform.go, dhctl/pkg/config/connection.go, dhctl/pkg/config/connection_test.go, dhctl/pkg/config/load.go, dhctl/pkg/operations/converge/converger.go
This PR fixes `--connection-config` option in dhctl CLI, it is broken in current version.
Ability to pass sudoPassword using SSHConfig kind in `--connection-config` yaml configuration file (non-interactively).
Non-interactive declarative way to specify connection settings with the option `--connection-config` is now fully available in  dhctl CLI. In previous versions of deckhouse it only worked in the dhctl-server, but it was broken in dhctl-cli: private ssh-keys was not added into the agent properly.
SudoPassword needed for full support of different connection options.
```changes
section: dhctl
type: fix
summary: fix broken connection-config in CLI and support sudoPassword in SSHConfig
```
=> [dhctl] Fix broken connection-config in CLI and support sudoPassword in SSHConfig (1.68)

ee/modules/030-cloud-provider-huaweicloud/images/caphc-controller-manager/werf.inc.yaml, ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/patches/0001-bump-deps.patch, ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/werf.inc.yaml, ee/modules/030-cloud-provider-huaweicloud/images/cloud-data-discoverer/werf.inc.yaml, ee/modules/030-cloud-provider-huaweicloud/images/huaweicloud-csi-driver/patches/0001-bump-deps.patch, ee/modules/030-cloud-provider-huaweicloud/images/huaweicloud-csi-driver/werf.inc.yaml
This PR fixes CVEs, bumps go to 1.23, uses images, src-artifact in cloud-provider-huaweicloud module. 
to fix known CVEs. 
```changes
type: fix
summary: CVE fix, bump go to 1.23, use images, src-artifact
```
=> [cloud-provider-huaweicloud] bump go, use images, src-artifact

ee/modules/030-cloud-provider-huaweicloud/images/caphc-controller-manager/werf.inc.yaml, ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/patches/0001-bump-deps.patch, ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/werf.inc.yaml, ee/modules/030-cloud-provider-huaweicloud/images/cloud-data-discoverer/werf.inc.yaml, ee/modules/030-cloud-provider-huaweicloud/images/huaweicloud-csi-driver/patches/0001-bump-deps.patch, ee/modules/030-cloud-provider-huaweicloud/images/huaweicloud-csi-driver/werf.inc.yaml
This PR fixes CVEs, bumps go to 1.23, uses images, src-artifact in cloud-provider-huaweicloud module. 
to fix known CVEs. 
```changes
type: fix
summary: CVE fix, bump go to 1.23, use images, src-artifact
```
=> [cloud-provider-huaweicloud] bump go, use images, src-artifact (#11631)

modules/110-istio/images/common-v1x19x7/patches/002-go-mod.patch, modules/110-istio/images/common-v1x19x7/patches/README.md
Fix new CVE in Istio version 1.19.7.
```changes
section: istio
type: chore
summary: Fix new CVE in Istio version 1.19.7.
```
=> [istio] Fix new CVE in 1.19.7 version

modules/021-cni-cilium/images/bin-cilium/patches/006-add-pod-prioroty-managment.patch, modules/021-cni-cilium/images/bin-cilium/patches/007-fix-restoring-cep-for-dead-local-endpoint.patch, modules/021-cni-cilium/images/bin-cilium/patches/README.md
A `network.deckhouse.io/pod-common-ip-priority` label allows you to share a single IP between  several Pods and to switch the actual owner.
Label may have numeric values in range 0-4294967295. A lower value means a higher pod priority for the same address. By default, pod without a label have the lowest priority (4294967295).
During the VM migration process (in DVP), two pods with the same address are created and packets are randomly delivered to them. This label is used to force delivery of packets to the selected virtual machine pod during the migration process.
In cluster two pods share single ip4 address. By default cilium will randomly use a pod for this ip4 address.
To force network packet delivery to a specific pod it must have higher priority then another pod.
Two pods in cluster …
=> Cilium add label for pod ip priority management

modules/021-cni-cilium/templates/operator/deployment.yaml
Increasing the `leader-election` timeouts for the cilium-operator.
In clusters with heavily loaded master-nodes, the cilium-operator may experience difficulty updating the `leader-election-lease` within the allocated time, which can result in frequent restarts of the cilium-operator pods.
```changes
type: chore
summary: Improved the stability of the cilium-operator.
```
=> [cni-cilium] Improving the stability of the cilium-operator.

modules/101-cert-manager/templates/webhook/mutatingwebhookconfiguration.yaml, modules/101-cert-manager/templates/webhook/validatingwebhookconfiguration.yaml
Restore the [original](https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml#L17) webhook name
Cert-manager has the hardcoded regexp [inside](https://github.com/cert-manager/cert-manager/blob/v1.16.2/pkg/util/cmapichecker/cmapichecker.go#L59). Some feature couldn't work without this check.
```changes
type: fix
summary: Restore the original webhook name to match the cert-manager's library regexp.
```
=> [cert-manager] Rename webhooks

docs/documentation/_data/deckhouse-alerts.yml, modules/040-node-manager/monitoring/prometheus-rules/standby-deployment-unavailable.yaml, modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring/application-controllers.yaml
When we reach max nodes in node group we can recieve KubernetesControllersMalfunctioningInNamespace alert for standby-holder. It is false positive alert.
To receive correct alerts for standby-holder deployments. 
```changes
type: chore
summary: Separate alert of DeploymentReplicasUnavailable for Standby-Holder
```
=> [extended-monitoring] Separate alert of DeploymentReplicasUnavailable for Standby-Holder

docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA.liquid, docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA_RU.liquid
Deleted information about CLI in zVirt provider at GS.
```changes
section: docs
type: chore
summary: Deleted information about CLI in zVirt provider at GS.
```
=> [docs] Deleted information about CLI in zVirt provider at GS

modules/302-vertical-pod-autoscaler/templates/recommender/deployment.yaml
As described here https://github.com/kubernetes/autoscaler/issues/6368 vpa recommender can consume a lot of RAM. Resource consumption increases with a large number of pods and with frequent deployment rollouts.
This commentary details the mechanisms for storing and cleaning data inside the VPA https://github.com/kubernetes/autoscaler/issues/6368#issuecomment-1963800975.
The simplest solution is to enable the memory-saver option. This should reduce RAM consumption, since not all pods use VPA
```
--memory-saver 	Bool 	false 	If true, only track pods which have an associated VPA
```
In large clusters, VPA recommender can consume a large amount of RAM over time
Example memory usage:
- 10 Deployment
- every Deployment has 10 Pod replicas
- Rollout every 30 sec
Memory utilization delta ~50 MB …
=> [vertical-pod-autoscaler] recommender memory-save

.github/CODEOWNERS
Setting @apolovov as kube-proxy module codeowner.
```changes
type: chore
summary: @apolovov is set as module codeowner.
```
=> [kube-proxy] CODEOWNERS update

.github/workflow_templates/deploy-channel.multi.yml, .github/workflows/deploy-alpha.yml, .github/workflows/deploy-beta.yml, .github/workflows/deploy-early-access.yml, .github/workflows/deploy-rock-solid.yml, .github/workflows/deploy-stable.yml
- Implemented validation to ensure the workflow runs only for release tags in the format `vX.Y.Z` (e.g., `v1.67.9`).
- The workflow now verifies that the `github.ref` matches `refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$` before proceeding.
- If the tag does not match the required format, the workflow exits with an error.
- To prevent accidental workflow execution on incorrect tags.
- Ensures that only proper release tags trigger the deployment process.
```changes
section: ci
type: chore
summary: updated flow deploy release
```
=> [CI] update flow deploy release

candi/bashible/bashbooster/56_detect_bundle.sh, candi/bashible/detect_bundle.sh, ee/be/candi/bashible/detect_bundle.sh
Add Oracle Linux as centos
Oracle Linux is the same distro like as RockyLinux, AlmaLinux, CentOS, RHEL
```
[root@kovalkov-oracle ~]# cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="9.5"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="9.5"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Oracle Linux Server 9.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:9:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://github.com/oracle/oracle-linux"
ORACLE_BUGZILLA_PRODUCT="Oracle Linux 9"
ORACLE_BUGZILLA_PRODUCT_VERSION=9.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=9.5
```
But we not detect it and detect bundle works too slow
```
┌ ⛵ ~ Bootstrap: Detect Bashible Bundle
│ Detected bundle: centos
└ ⛵ ~ Bootstrap: Detect …
```
=> [candi] Add Oracle Linux as centos

modules/160-multitenancy-manager/crds/doc-ru-projects.yaml, modules/160-multitenancy-manager/crds/projects.yaml, modules/160-multitenancy-manager/images/multitenancy-manager/src/apis/deckhouse.io/v1alpha2/project.go, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/client.go, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/renderer.go, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/testdata/default_case/project.yaml, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/testdata/default_case/resources.yaml, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/testdata/without_ns_case/project.yaml, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/testdata/without_ns_case/resources.yaml, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/testdata/without_ns_case/template.yaml
It adds resource labels and annotations.
It allows to set labels/annotations to all resource that will be created for the project, and also a good hack to trigger project resources to rerender.
Project:
```
apiVersion: deckhouse.io/v1alpha2
kind: Project
metadata:
name: test1
spec:
resourceLabels:
"my": "val"
resourceAnnotations:
"my": "val"
description: This is example.
parameters:
administrators:
- name: user@gmail.com
subject: User
resourceQuota:
limits:
memory: 20Gi
requests:
cpu: 2
memory: 10Gi
projectTemplateName: default
```
Rendered resource:
```
apiVersion: v1
kind: Namespace
metadata:
annotations:
meta.helm.sh/release-name: test1
meta.helm.sh/release-namespace: ""
my: val
creationTimestamp: "2025-02-06T21:00:12Z"
labels:
app.kubernetes.io/managed-by: Helm …
```
=> [multitenancy-manager] add resource labels/annotations

.github/scripts/js/ci.js, .github/scripts/js/constants.js, .github/scripts/js/specs/constants.test.js, .github/workflow_templates/run-ci-tests-on-changes.yml, .github/workflows/run-ci-tests-on-changes.yml
Added a CI job to run tests when scripts are changed in .github/scripts/js
Fixed falling Jest tests for JS code
The addition of a CI job to run tests whenever scripts are changed in the .github/scripts/js directory ensures that any modifications to these scripts are automatically validated
```changes
section: ci
type: chore
summary: Added a CI job to run tests when scripts are changed in .github/scripts/js
---
section: ci
type: chore
summary: Fixed falling Jest tests for JS code
```
=> [chore] add tests for ci js scripts

modules/002-deckhouse/templates/webhook-handler/rbac-for-us.yaml
Fix wildcard resources mask in webhook-handler's RBAC for `network.deckhouse.io` apiGroup.
Eliminates excessive permissions, increasing security.
```changes
type: chore
summary: Fix webhook-handler's RBAC for network.deckhouse.io apiGroup.
```
=> [deckhouse] Fix webhook-handler's RBAC

deckhouse-controller/pkg/controller/module-controllers/config/controller.go, deckhouse-controller/pkg/controller/module-controllers/source/helpers.go
It triggers the module config when a module created.
A module config can be created before the module is discovered.
It can help people with CI/CD.
Delete the module to test and then check that the module does not exist:
```
root@dev-master-0:~# k get module commander
Error from server (NotFound): modules.deckhouse.io "commander" not found
```
Create the module config(its normal that it is ignored now):
```
root@dev-master-0:~# kubectl get mc
NAME                         ENABLED   VERSION   AGE     MESSAGE
commander                    true      1         3m23s   Ignored: unknown module name
```
Wait for 3 minutes to source resync:
```
root@dev-master-0:~# k get module commander -oyaml
kind: Module
metadata:
creationTimestamp: "2025-02-12T18:05:01Z" …
```
=> [deckhouse] trigger the module config when a module created

modules/150-user-authn/images/dex-authenticator/patches/0004-add-redis-retries.patch, modules/150-user-authn/images/dex-authenticator/patches/README.md, modules/150-user-authn/images/dex-authenticator/werf.inc.yaml
Patch to oauth2-proxy that adds a loop to `sendRedisConnectionTest` to retry these connection. 
fixes https://github.com/deckhouse/deckhouse/issues/4644
<details>
<summary>Patched function:</summary>
```go
func sendRedisConnectionTest(client redis.Client, key string, val string) []string {
msgs := []string{}
ctx := context.Background()
var err error
for i := 0; i < 10; i++ {
logger.Printf("testing connection to redis...")
err = client.Set(ctx, key, []byte(val), time.Duration(60)*time.Second)
if err == nil {
break
}
time.Sleep(2 * time.Second)
}
if err != nil {
msgs = append(msgs, fmt.Sprintf("unable to set a redis initialization key: %v", err))
} else {
gval, errGet := client.Get(ctx, key)
if errGet != nil {
msgs = append(msgs,
fmt.Sprintf("unable to retrieve redis initialization key: …
```
=> [user-authn] Dex-authenticator add redis connection retries

ee/se/modules/380-metallb/hooks/migration_adopt_old_fashioned_l2_lbs.go, ee/se/modules/380-metallb/hooks/migration_auto_generating_l2_mlbc.go
Multiple interdependent hooks are executed in parallel, causing a race condition. We have moved them to a single queue with sequential execution.
Sometimes, due to parallel work of hooks, not all the Services are being migrated to the new controller and old External IPs are assigned to the wrong Services.
Customers face this problem at the production stage.
```changes
type: fix
summary: Fixed race condition in migration hook.
```
=> [metallb] Fix race condition between hooks

ee/modules/110-istio/images/metadata-exporter/werf.inc.yaml, modules/110-istio/images/proxyv2-v1x21x6/werf.inc.yaml
Add own curl to istio images.
```changes
section: ci
type: chore
summary: add own curl to istio images
```
=> [ci] add own curl to istio images

docs/documentation/_data/deckhouse-alerts.yml, global-hooks/migrate/migrate_update_policy.go, modules/340-monitoring-deckhouse/monitoring/prometheus-rules/alerting.yaml
It enriches the deprecated update policy alert with commands to set the update policy to the module config
To help people migrating.
```
root@dev-master-0:~# kubectl get clusteralert 76f555d6c3d29c67 -oyaml
alert:
description: |
The 'test' module matched by the 'alpha-auto' deprecated module update policy, the policy`s v1alpha1 has selector that no longer works.
Specify the update policy in the module config by following command:
```
kubectl patch moduleconfig test --type='json' -p='[{"op": "add", "path": "/spec/updatePolicy", "value": "alpha-auto"}]'
```
After solving all alerts for the 'alpha-auto' update policy, use this command to clear selector:
```
kubectl patch moduleupdatepolicies.v1alpha1.deckhouse.io alpha-auto --type='json' -p='[{"op": "replace", "path": …
=> [deckhouse] enrich deprecated update policy alert

docs/site/_data/getting_started/dkp_data.yaml, docs/site/_includes/getting_started/global/partials/select_revision.html.liquid
Fixed generation of blured blocks on the step4 page of GS.
```changes
section: docs
type: fix
summary: Fixed generation of blured blocks on the step4 page of GS.
```
=> [docs][getting-started] Fix blured blocks on the step4 page

modules/002-deckhouse/hooks/disable_sa_token_automount.go, modules/002-deckhouse/hooks/disable_sa_token_automount_test.go
Add hook to disable default ServiceAccount token automount
According to CIS Benchmark 5.1.5, `automountServiceAccountToken` for default sa should be disabled
```changes
type: feature
summary: Add hook to disable default ServiceAccount token automount.
```
=> [deckhouse] Add hook to disable default service account token automount

docs/documentation/_data/rbac/rbac.yaml, ee/modules/030-cloud-provider-dynamix/module.yaml, ee/modules/030-cloud-provider-dynamix/templates/rbacv2/manage/edit.yaml, ee/modules/030-cloud-provider-dynamix/templates/rbacv2/manage/view.yaml, ee/modules/030-cloud-provider-huaweicloud/module.yaml, ee/modules/030-cloud-provider-huaweicloud/templates/rbacv2/manage/edit.yaml, ee/modules/030-cloud-provider-huaweicloud/templates/rbacv2/manage/view.yaml
It provides rbacv2 for new cloud providers
New providers should have rbacv2 roles
```changes
type: chore
summary: Add rbacv2 for dynamix and huaweicloud providers.
```
=> [user-authz] add rbacv2 for new providers

docs/documentation/pages/module-development/STRUCTURE.md, docs/documentation/pages/module-development/STRUCTURE_RU.md
Fix module lifecycle stage values in the documentation.
There is conflicting information in the documentation
```changes
section: docs
type: chore
summary: Fix module lifecycle stage values in the documentation.
```
=> [docs] Update module lifecycle stage values in the documentation

modules/015-admission-policy-engine/crds/operation-policy.yaml, modules/015-admission-policy-engine/hooks/internal/apis/v1alpha1.go, modules/150-user-authn/templates/dex-authenticator/deployment.yaml
FIx requiredResource OperationPolicy
We don't want to have defaults for requiredResource. It lead to an undefined behavior
```changes
type: fix 
summary: Change defaults for requiredRequests in OperationPolicy.
```
=> [admission-policy-engine] FIx requiredResource OperationPolicy

modules/042-kube-dns/openapi/config-values.yaml, modules/042-kube-dns/openapi/openapi-case-tests.yaml
Make validation pattern for stubZones more widely.
https://regex101.com/r/XZ2Q0X/1
https://regex101.com/r/khD908/1
Fix https://github.com/deckhouse/deckhouse/issues/390
For example, we can setting kube-dns like this:
```
metadata:
name: kube-dns
spec:
enabled: true
settings:
stubZones:
- upstreamNameservers:
- 8.8.8.8
zone: _acme-challenge.example.com
upstreamNameservers:
- 10.128.0.6
version: 1
```
```changes
type: feature
summary: Change pattern for stubZones to allow _. 
```
=> [kube-dns] Change pattern for stubZones to allow _

candi/control-plane-kubeadm/config.yaml.tpl
Reduce `request-timeout` in kubernetes-api to 60s.
If kubelet is restarted at a time when etcd is unavailable (e.g. when etcd is recreated by d8-control-plane-manager), the kubelet will make several attempts to communicate with the kubernetes-api. If the kubernetes-api is running but not working properly (e.g. it's single master), then the etcd container will be launched after more than 10 minutes due to `request-timeout`. This is often the case when bootstrapping a new cluster.
Current value (300s) may have been set as a recommendation from the CIS (1.9) 1.2.20, but the check itself only recommends explicitly setting the `request-timeout`  in kubernetes-api manifest. 
```
- id: 1.2.20
text: "Ensure that the --request-timeout argument is set as appropriate (Manual)"
type: manual …
```
=> [candi] reduce kubernetes api request-timeout to 60s

candi/bashible/common-steps/all/000_preflight_checks.sh, candi/bashible/common-steps/all/033_restart_containerd_if_needed.sh.tpl
We have some [issue](https://github.com/deckhouse/deckhouse/issues/5830) where two containerd services in single node. Since deckhouse only use `containerd-deckhouse.service` in actual version (since v1.50), we can turn off the other `containerd.service` before restarting this in step [033_restart_containerd_if_needed.sh
](https://github.com/deckhouse/deckhouse/blob/9228fea4b0083a84b83b813627dca8b53e940277/candi/bashible/common-steps/node-group/033_restart_containerd_if_needed.sh.tpl)
In the current situation, another running `containerd.service` breaks step `033_restart_containerd_if_needed` and the update freezes
```changes
type: fix
summary: Disable old or another containerd.service
```
=> [bashible] Disable old or another containerd.service

modules/015-admission-policy-engine/crds/operation-policy.yaml, modules/015-admission-policy-engine/hooks/internal/apis/v1alpha1.go, modules/015-admission-policy-engine/templates/policies/operation-policy/constraint.yaml
Fix empty field handling
Deckhouse fails if limits/requests are empty, because of `null` json value
```changes
type: fix 
summary: Fix resourceRequests limits handling in the OperationPolicy CR.
```
=> Empty limit handler

deckhouse-controller/pkg/controller/module-controllers/downloader/downloader.go, deckhouse-controller/pkg/controller/moduleloader/loader.go
It provides fix for module.yaml ignored when weight == 0
Fixes #12235
It avoids ignoring and also provides some fixes(close open files and deepEqual with wrong structure)
```changes
type: fix
summary: Fix module.yaml ignored when weight == 0.
```
=> [deckhouse] fix module.yaml ignored when weight == 0

.werf/werf-deckhouse-controller.yaml
When we build deckhouse controller we have incorrect version because `CI_COMMIT_TAG` did not get from envs
Proble with deckhouse controller updating logic
Affect release process
```changes
section: ci
type: fix
summary: CI_COMMIT_TAG does not found in deckhouse controller
```
=> [ci] CI_COMMIT_TAG does not found in deckhouse controller

docs/documentation/_plugins/custom_sidebar.rb, docs/site/_assets/css/docs.scss, docs/site/backends/docs-builder-template/layouts/partials/sidebar.html
Fix the transfer of badges.
```changes
section: docs
type: chore
```
=> [docs] Fix the transfer of badges

ee/fe/modules/500-okmeter/templates/daemonset.yaml, modules/500-okmeter/templates/daemonset.yaml
Admission controller interference voids changes made in the [commit](https://github.com/deckhouse/deckhouse/commit/401c6555bdc79caf4f582072ef3ff14be6c1bb98#diff-bfa24c7a2cdffe17fc43b99474f1b86f68352192e768acf9415b074eb0d3e1b7L48) which removes `serviceAccountName` field from the DaemonSet. As a result, okmeter pods still require the service account and thus don't start.
This PR explicitly sets both serviceAccount and serviceAccountName to null effectively solving the issue described above.
We do. Okmeter DaemonSet still has the serviceAccountName field set, but the service account is missing. This prevents pods from being updated.
```changes
type: fix
summary: drop service account fields from the okmeter daemonset manifest
impact: okmeter daemonset pods will be rollout …
```
=> [okmeter] Explicitly remove service account fields from DaemonSet

deckhouse-controller/pkg/controller/module-controllers/source/controller.go, deckhouse-controller/pkg/controller/module-controllers/source/helpers.go
It fixes stuck overridden status in ms.
Overridden status not cleared.
Stuck overridden status can confuse.
```changes
type: fix
summary: Fix stuck overridden status in ms.
```
=> [deckhouse] fix overridden status

candi/bashible/common-steps/all/098_update_node_labels.sh.tpl
Make update_node_labels.sh working with python2 as well as with python3
On old systems, where there's only python2 available, update_node_labels.sh is broken
Script is broken in 1.68
```changes
section: candi
type: fix
summary: Fix update_node_labels.sh to work on python2.
```
=> [candi] Fix update_node_labels.sh

dhctl/pkg/app/preflight.go, dhctl/pkg/preflight/cidr_intersection.go, dhctl/pkg/preflight/cidr_intersection_test.go, dhctl/pkg/preflight/preflight.go
Add new preflight check for dhctl: CIDRs intersection. Fail if podSubnetCIDR intersects with serviceSubnetCIRD
This check allows to fail faster, without try to bootstrap cluster. CIDRs should not intersects
```changes
section: dhctl
type: feature
summary: Add CIDR intersection preflight check to dhctl
```
=> [dhctl] Preflight check: CIDRs intersection

dhctl/cmd/dhctl/commands/terraform.go, modules/040-terraform-manager/templates/terraform-state-exporter/deployment.yaml
Allow `dhctl terraform check` command in terraform-state-exporter
```changes
type: feature
summary: Allow dhctl terraform check command in terraform-state-exporter.
```
```changes
section: dhctl
type: fix
summary: Allow dhctl terraform check run if --ssh-host not set, but --kube-client-from-cluster set.
```
=> [terraform-manager] Allow dhctl terraform check command in terraform-state-exporter

modules/040-node-manager/monitoring/prometheus-rules/early-oom.tpl, modules/110-istio/monitoring/prometheus-rules/versions.tpl, modules/340-monitoring-custom/monitoring/prometheus-rules/reserved-domain.tpl
Some alerts had incorrect link templates, and when the `documentation` module was enabled, the link followed the path of the documentation web page in deckhouse.io
If there is no Internet access and the `Documentation` module is enabled, this can create problems for users who turn to external resources for additional information and troubleshooting. For such environments, it is important to have complete offline documentation or an internal mirror of the necessary resources so that users can access important information without relying on an internet connection. This setting ensures that even in conditions of limited access, users will be able to effectively manage alerts and maintain the system.
```changes
section: prometheus-rules
type: fix 
summary: Changes the links in alert's …
```
=> [prometheus-rules] Change links in prometheus-rules when module documentation is enable.

docs/documentation/_data/deckhouse-alerts.yml, modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
This PR adds a new alert rule: **D8KubernetesStaleTokensDetected**.  
The alert fires when stale service account tokens are detected in the cluster.
Currently these tokens are not blocked because the `--service-account-extend-token-expiration` flag is enabled by default (Default: true). With this flag enabled, admission-injected tokens are extended up to 1 year during token generation to facilitate a safe transition from legacy tokens to the bound service account token feature, ignoring the value of `service-account-max-token-expiration`.
For security reasons, this should be fixed.
Stale tokens can cause security risks and authentication failures because some applications read the token only at startup and do not refresh it later.  
```changes
type: feature …
```
=> [control-plane-manager] Stale service account alert

modules/015-admission-policy-engine/charts/constraint-templates/templates/security/allowed-apparmor-profiles.yaml
Fixes `allowed-apparmor-profiles` to support matching wildcard localhost profiles with `localhost/*`.
Currently, this rego-policy checks if a profile name literally matches the defined constraints so the `localhost/*` constraint wouldn't allow `localhost/myprofile-name` profile.
It breaks security policy apparmor profile checks.
```changes
type: fix
summary: Fix wildcard apparmor profile.
```
=> [admission-policy-engine] fix wildcard apparmor profile

modules/460-log-shipper/crds/cluster-logging-config.yaml
Adds validation to `ClusterLoggingConfig` CRD fields `KubernetesPods.namespaceSelector.labelSelector.matchExpressions`.
Helps prevent panic when `values` is specified along with `Exists, DoesNotExist` operators.
```changes
type: fix 
summary: Minor improvements in clusterloggingconfigs CRD
```
=> [log-shipper] Add field validation to clusterloggingconfigs CRD

modules/300-prometheus/hooks/grafana_v8_cleanup.go, modules/300-prometheus/hooks/grafana_v8_deprecation.go
This hook cleanup old unused Grafana V8 resources. The following Kubernetes resources in the d8-monitoring namespace will be delete:
Deployments:
- grafana
- grafana-v8-dex-authenticator
Services:
- grafana
- grafana-v8-dex-authenticator
Ingresses:
- grafana
- grafana-v8-dex-authenticator
- grafana-v8-dex-authenticator-sign-out
This hook was tested manually, as unit tests are not functioning correctly due to FieldSelector/NameSelector adding incorrect resources to the snapshots (known bug), causing test failures.
Cleanup unused resources.
- 
```changes
type: chore
summary: Cleanup after grafana v8 deprecation
```
=> [prometheus] Grafana v8 deprecation hook

modules/800-deckhouse-tools/images/web/static/tools.json
Binaries are build into the `/bin` subfolder nowdays, but tools were still linking to the old location, fixed paths in tools.json to point to the right place.
This fixes 404 errors during downloads of d8 binaries from deckhouse tools
This is a fix for broken functionality that users generally require if they are in the air-gapped environment
```changes
type: fix
summary: Fix tools links pointing to wrong path
```
=> [deckhouse-tools] Fix tools links pointing to wrong path

docs/documentation/pages/DECKHOUSE-FAQ.md, docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Actualised USED_MODULES parameter in Deckhouse FAQ.
Removed  mention of CSE from FAQ english version.
```changes
section: docs
type: chore
summary: Actualised USED_MODULES parameter in Deckhouse FAQ and removed mention of cse from FAQ english version.
```
=> [docs] Actualised USED_MODULES parameter in Deckhouse FAQ

.golangci.yaml, deckhouse-controller/pkg/controller/deckhouse-release/check_release.go, deckhouse-controller/pkg/controller/module-controllers/downloader/downloader.go, ee/modules/110-istio/hooks/ee/common_test.go, modules/040-node-manager/hooks/handle_node_templates.go, modules/040-node-manager/hooks/machineclass_checksum_collect.go
Added musttag linter to golangci-lint
If we marshall/unmarshall structs - we need to check all struct fields for correct struct tags applied.
If not - we get unpredictable result.
It's easy linter to apply (not so much errors in a code), but have a powerful impact in the future.
```changes
type: chore
summary: added musttag linter to golangci-lint
```
=> [deckhouse-controller] chore: add mustttag linter to golangci-lint

ee/modules/610-service-with-healthchecks/crds/doc-ru-servicewithhealthchecks.yaml, ee/modules/610-service-with-healthchecks/crds/servicewithhealthchecks.yaml, ee/modules/610-service-with-healthchecks/images/artifact/cmd/agent/main.go, ee/modules/610-service-with-healthchecks/images/artifact/cmd/controller/main.go, ee/modules/610-service-with-healthchecks/images/artifact/internal/agent/agent.go, ee/modules/610-service-with-healthchecks/images/artifact/internal/agent/postgres_credentials_controller.go, ee/modules/610-service-with-healthchecks/images/artifact/internal/agent/postgresql.go, ee/modules/610-service-with-healthchecks/images/artifact/internal/controller/controller.go, ee/modules/610-service-with-healthchecks/templates/controller/deployment.yaml
Fix several issues:
- fix the creation of endpointslices.
- reduce verbosity of loggers in the controller and agent in the default mode (debug: false).
- create a separate type of Secrets "network.deck house.io/postgresql-credentials "and a separate controller for processing it to improve the experience with PostreSQL probes.
- endpoint slices were created with the wrong port.
- the probes for PostgreSQL did not have the flexibility to change the credentials part.
- the logs of the controller and agents were too verbose. This made it difficult to find problems.
The corrections affect the correct functioning of the module. It needs to be fixed as soon as possible.
```changes
type: fix
summary: Fixed several issues.
```
=> [service-with-healthcheck] Fixed the creation of endpointslices and performing PGSQL-probes

ee/modules/380-metallb/templates/controller/deployment.yaml, ee/modules/380-metallb/templates/speaker/daemonset.yaml, ee/se/modules/380-metallb/templates/l2lb/controller/deployment.yaml, ee/se/modules/380-metallb/templates/l2lb/speaker/daemonset.yaml, modules/500-upmeter/images/upmeter/src/pkg/probe/group_loadbalancing.go
- Add an additional labels to **metallb** module pods (`metallb-role: <value>`).
- Add these labels in the **upmeter** module settings.
After extending the capabilities of the **metallb** module, **upmeter** monitoring broke.
This PR solves that problem.
```changes
type: fix
summary: Fixed metallb module probe.
```
=> [upmeter] Fix metallb probe

ee/se/modules/380-metallb/hooks/discovery_l2_load_balancers.go, ee/se/modules/380-metallb/hooks/migration_adopt_old_fashioned_l2_lbs.go, ee/se/modules/380-metallb/hooks/migration_auto_generating_l2_mlbc.go, ee/se/modules/380-metallb/hooks/update_service_status.go
Add hook logging when migrating to a new version of the module with `MetalLoadBalancerClass`.
We need to know what actions the hook performs in the process.
```changes
type: chore
summary: Added logging for hooks.
```
=> [metallb] Add logging for hooks

docs/documentation/_plugins/custom_sidebar.rb, docs/site/backends/docs-builder-template/layouts/partials/sidebar.html
Use detailed tooltips for a module stage in the sidebar.
```changes
section: docs
type: chore
summary: Use detailed tooltips for a module stage in the sidebar.
```
=> [docs] Use detailed tooltips for a module stage in the sidebar

deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/deckhouse_release.go, deckhouse-controller/pkg/controller/deckhouse-release/check_release.go, deckhouse-controller/pkg/controller/deckhouse-release/check_release_test.go, deckhouse-controller/pkg/controller/deckhouse-release/next_version_test.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/deployed-release-suspended.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/existed-release-suspended.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/deployed-release-suspended.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/existed-release-suspended.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-canary-release-wave-0.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-canary-release-wave-4.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-new-deckhouse-image.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/image-hash-not-changed.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/inherit-release-cooldown.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/new-release-suspended.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/patch-release-has-own-cooldown.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-canary.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-cooldown.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-disruptions.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-requirements.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-with-changelog.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/restore-absent-releases-from-registry.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/resume-suspended-release.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/step-by-step-update-successfully.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/resume-suspended-release.yaml, deckhouse-controller/pkg/registry/deckhouse.go
Fix step by step logic
Add restored release in releases sequence
Add annotations for process noting [kubernetes-like](https://kubernetes.io/docs/reference/labels-annotations-taints/#change-cause)
Fix tests and golden files
```changes
type: fix
summary: fix deckhouse-release check loop
```
=> [deckhouse-controller] fix creating deckhouse release loop

deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/deckhouse_release.go, deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_release.go, deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/release.go, deckhouse-controller/pkg/controller/module-controllers/release/controller.go, deckhouse-controller/pkg/controller/module-controllers/release/controller_test.go, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/reinstall-annotation.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/reinstall-annotation.yaml, docs/site/backends/registry-modules-watcher/internal/backends/pkg/registry-scaner/cache/cache_test.go, docs/site/backends/registry-modules-watcher/internal/backends/pkg/registry-scaner/registry-scaner.go
Add reinstall annotation
Close issue
Sometime we have broken (by different reasons) module. We need an annotation to download it again and restart the D8.
After add this annotation to ModuleRelease resource, reconciler redownload module, recreate symlinks, e.t.c (make default deploy process). At last, we remove "modules.deckhouse.io/reinstall" annotation.
```changes
type: fix
summary: Add reinstall annotation to reinstall module
```
=> [deckhouse-controller] add reinstall annotation

docs/documentation/.helm/values.yaml, docs/site/.helm/values.yaml
Increase memory requests for documentation pods to 150M.
```changes
section: docs
type: chore
summary: Increase memory requests for documentation pods to 150M.
```
=> [docs][website] update memory requests for documentation pods

modules/030-cloud-provider-aws/hooks/aws_cluster_configuration.go
Set `cloudProviderAws.internal` values individually in the `provider_cluster_configuration` hook.
We can't set `cloudProviderAws.internal` values in other hooks.
```changes
type: fix
summary: Set `cloudProviderAws.internal` values individually in the `provider_cluster_configuration` hook.
```
=> [cloud-provider-aws] Fix values setting(`cloudProviderAws.internal`) in a golang hooks

global-hooks/migrate/delete-metallb-deprecated-crd.go, global-hooks/migrate/delete-metallb-deprecated-crd_test.go
Add a global hook that removes the deprecated CRD `addresspools.metallb.io` from the MetalLB module from the cluster.
Before:
```shell
Warning: metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
No resources found
addresspools.metallb.io                                           2024-09-17T16:46:54Z
ipaddresspools.metallb.io                                         2024-05-16T10:31:23Z
```
After:
```shell
Error from server (NotFound): Unable to list "metallb.io/v1beta1, Resource=addresspools": the server could not find the requested resource (get addresspools.metallb.io)
ipaddresspools.metallb.io                                         2024-05-16T10:31:23Z
```
In the cluster logs `/var/log/kube-audit/audit.log` there are messages that the CRD …
=> [metallb] Add hook for deleting a deprecated CRD

modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/client_test.go, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/renderer.go, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/testdata/default_case/resources.yaml, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/testdata/secure_case/resources.yaml, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/testdata/secure_with_dedicated_node_case/resources.yaml, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/manager/project/manager.go
It fixes namespace rendering.
Helm can try to render the resources before the namespace, we put the namespace before all resources via postrenderer.
```changes
type: fix
summary: Fix namespace rendering.
```
=> [multitenancy-manager] fix namespace rendering

dhctl/pkg/preflight/sudoers.go, dhctl/pkg/server/pkg/helper/ssh_client.go
Related old PR: https://github.com/deckhouse/deckhouse/pull/12099
Related PR to master: https://github.com/deckhouse/deckhouse/pull/12368
Fixes dhctl-server use-case and dhctl-cli and connection-config use-case when passing sudoPassword in a non-interactive way.
Allow sudoPassword field in the SSHConfig kind.
Fixes dhctl-server use-case of sudoPassword field.
Fixes dhctl-cli use-case of sudoPassword usage (previously sudoPassword field in the connection-config has no effect and not used actually, this PR fixes non-interactive way of passing password).
```changes
section: dhctl
type: fix
summary: sudoPassword from the connection-config not used in dhctl CLI and dhctl server
```
=> [dhctl] fix: sudoPassword is not passed for dhctl-server and cannot be used non-interactively (1.68)

dhctl/pkg/app/app.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go, dhctl/pkg/server/rpc/dhctl/abort.go, dhctl/pkg/server/rpc/dhctl/bootstrap.go, dhctl/pkg/server/rpc/dhctl/check.go, dhctl/pkg/server/rpc/dhctl/commander_attach.go, dhctl/pkg/server/rpc/dhctl/commander_detach.go, dhctl/pkg/server/rpc/dhctl/converge.go, dhctl/pkg/server/rpc/dhctl/destroy.go
Eliminated usage of the deprecated `--resources` parameter in dhctl server bootstrap. `--resources` replaced with multiple `--config`
```changes
section: dhctl
type: chore
summary: eliminated usage of the deprecated --resources parameter in dhctl server bootstrap
```
=> [dhctl] feat(dhctl-for-commander): use only ConfigPaths in dhctl server bootstrap

candi/bashible/common-steps/all/002_create_static_node_cleanup_script.sh.tpl, candi/bashible/preflight/check_deckhouse_user.sh.tpl, dhctl/pkg/app/preflight.go, dhctl/pkg/preflight/deckhouse_user.go, dhctl/pkg/preflight/preflight.go, dhctl/pkg/template/bundle.go, dhctl/pkg/template/preflight.go
Fixes https://github.com/deckhouse/deckhouse/issues/11928
By bootstrap, we should not use `deckhouse` user and group. By destroy, we should cleanup that user and group as well as it's home directory
```changes
section: candi
type: fix
summary: Delete /home/deckhouse and deckhouse user and group by cleanup.
```
```changes
section: dhctl
type: feature
summary: Add preflight check for existence of deckhouse user and group.
```
=> [dhctl] Add deckhouse user and group existence preflight check

candi/bashible/common-steps/all/041_configure_sysctl_tuner.sh.tpl
Delete unnecessary warnings at sysctl tuner.
```
Feb 25 14:17:49 master-usmanov sysctl-tuner[697725]: tee: /sys/block/loop0/queue/nr_requests: Invalid argument
Feb 25 14:17:49 master-usmanov sysctl-tuner[697725]: tee: /sys/block/loop1/queue/nr_requests: Invalid argument
Feb 25 14:17:49 master-usmanov sysctl-tuner[697725]: tee: /sys/block/loop2/queue/nr_requests: Invalid argument
Feb 25 14:17:49 master-usmanov sysctl-tuner[697725]: tee: /sys/block/loop3/queue/nr_requests: Invalid argument
Feb 25 14:17:49 master-usmanov sysctl-tuner[697725]: tee: /sys/block/loop4/queue/nr_requests: Invalid argument
Feb 25 14:17:49 master-usmanov sysctl-tuner[697725]: tee: /sys/block/loop5/queue/nr_requests: Invalid argument
Feb 25 14:17:49 master-usmanov sysctl-tuner[697725]: tee: …
```
=> [candi] Delete unnecessary warnings at sysctl tuner

candi/bashible/common-steps/all/069_start_kubelet.sh.tpl
Clarify error message what steps needed if we see, that `The file /var/lib/kubelet/pki/kubelet-client-current.pem was not generated in 5 minutes.`
Give the user a hint on what exactly to do next. Because the message that the certificate has not been generated is not obvious to the user and confuses the user.
```changes
section: candi
type: chore
summary: Clarify error message about kubelet certificates.
```
=> [candi] Clarify error message about kubelet certificates

helm_lib/Chart.lock, helm_lib/Chart.yaml, helm_lib/charts/deckhouse_lib_helm/Chart.yaml, helm_lib/charts/deckhouse_lib_helm/README.md, helm_lib/charts/deckhouse_lib_helm/templates/_csi_controller.tpl, helm_lib/charts/deckhouse_lib_helm/templates/_csi_node.tpl, helm_lib/charts/deckhouse_lib_helm/templates/_module_image.tpl, helm_lib/charts/deckhouse_lib_helm/templates/_module_name.tpl, helm_lib/charts/deckhouse_lib_helm/templates/_module_security_context.tpl, modules/150-user-authn/templates/dex-authenticator/deployment.yaml
fixed: #12070
Change seccomp profile to RuntimeDefault instead of Unlimited
```changes
type: fix
summary: add security context with RuntimeDefault seccomp profile to dex container
```
=> feat: add security context with RuntimeDefault seccomp profile to dex container

ee/modules/030-cloud-provider-vcd/openapi/config-values.yaml, ee/modules/030-cloud-provider-vcd/openapi/doc-ru-config-values.yaml
Fixed typos at VMware configuration parameters.
```changes
section: docs
type: fix 
summary: Fixed typos at VMware configuration parameters.
```
=> [docs] Fixed typos at VMware configuration parameters

docs/documentation/_plugins/custom_hooks.rb, docs/site/backends/docs-builder-template/layouts/_default/single.html
Fixed the block with availability in editions.
```changes
section: docs
type: fix 
summary: Fixed the block with availability in editions.
```
=> [docs]  Fixed the block with availability in editions

ee/modules/500-operator-trivy/images/node-collector/werf.inc.yaml
Updates the node-collector image building so that it's built from alt_p11 image (not artifact).
We need it to have the node-collector image's default user set.
```changes
type: chore
summary: Refactor node-collector image building.
```
=> [operator-trivy] refactor node-collector image building

deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/deckhouse_release.go, deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/release.go, deckhouse-controller/pkg/controller/deckhouse-release/check_release.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/inherit-release-cooldown.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/patch-release-has-own-cooldown.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-cooldown.yaml, deckhouse-controller/pkg/releaseupdater/deploy_time_checker.go, modules/002-deckhouse/docs/internal/RELEASE.md
Remove deckhouserelease cooldown annotation
We don't use it. But we have to respect this option in the code, which make it more complex.
```changes
type: feature
summary: deckhouserelease cooldown removed
```
=> [deckhouse-controller] remove release cooldown

dhctl/pkg/operations/converge/controller/cloud_permanent_node_group.go
We have bug when starting converging cloud permanent nodegroups try to delete all nodes in group, because we cannot set desired replicas only when creating additional nodes
Bug introduced in https://github.com/deckhouse/deckhouse/pull/11086
Converge was broken
```changes
section: dhctl
type: fix
summary: Fix converge for NodeGroups with CloudPermanent type.
```
=> [dhctl] Fix converge cloud permanent nodegroups

docs/documentation/_data/modules/editions-addition.json, docs/site/backends/docs-builder-template/data/editions.json
Fixed alert with SE+ edition at documentation.
```changes
section: docs
type: chore
summary:  Fixed alert with SE+ edition at documentation.
```
=> [docs] Fixed alert with SE+ edition at documentation 

deckhouse-controller/pkg/controller/deckhouse-release/check_release.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-canary-release-wave-0.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-canary-release-wave-4.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-new-deckhouse-image.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/inherit-release-cooldown.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/new-release-suspended.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/patch-release-has-own-cooldown.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-canary.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-cooldown.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-disruptions.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-requirements.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-with-changelog.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/restore-absent-releases-from-registry.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/step-by-step-update-successfully.yaml, modules/002-deckhouse/templates/validation.yaml
Remove heritage label from deckhouse release
Impossible to update DeckhouseRelease in Manual update mode.
```changes
type: fix
summary: Fix DeckhouseRelease approval in the Manual update mode.
```
=> [deckhouse-controller] Remove heritage label from deckhouse release

dhctl/pkg/preflight/sudoers.go
Add shellescape to sudo preflight check
If sudo password contains special shell characters like `$`, sudo preflight check will fail. To avoid issues like this, we should escape all special shell characters 
v1.68 is affected, so we need to fix it
```changes
section: dhctl
type: fix
summary: Escape special shell characters in sudo preflight check.
```
=> [dhctl] Add shellescape to sudo preflight

docs/documentation/_data/deckhouse-alerts.yml, modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
add upmeter server storage usage alerts
If it fixes an issue https://github.com/deckhouse/deckhouse/issues/11682
will help to avoid problems in the operation of the upmeter
- [*] Changes were tested in the Kubernetes cluster manually.
```changes
type: fix
summary: Add D8UpmeterDiskUsage alert.
```
=> [upmeter] add alert D8UpmeterDiskUsage

deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module.go, deckhouse-controller/pkg/controller/module-controllers/config/controller.go, deckhouse-controller/pkg/controller/module-controllers/config/status.go
It removes useless module` phases
These phases can confused and they are not needed.
```changes
type: chore
summary: Delete useless module`s phases.
```
=> [deckhouse] delete useless module phases

.golangci.yaml, deckhouse-controller/pkg/controller/deckhouse-release/check_release.go, deckhouse-controller/pkg/controller/module-controllers/source/controller.go, go_lib/dependency/helm/hash.go, go_lib/dependency/vsphere/vsphere.go, go_lib/hooks/tls_certificate/order_certificate.go, modules/030-cloud-provider-aws/hooks/storage_classes.go, modules/030-cloud-provider-azure/hooks/storage_classes.go, modules/031-local-path-provisioner/hooks/storage_classes.go, modules/040-control-plane-manager/hooks/effective_kubernetes_version.go, modules/040-node-manager/hooks/yc_delete_preemptible_instances.go, modules/040-node-manager/hooks/yc_delete_preemptible_instances_test.go, modules/040-node-manager/template_tests/module_test.go, modules/402-ingress-nginx/hooks/get_ingress_controllers.go, modules/460-log-shipper/hooks/generate_config.go, testing/helm/init.go, testing/openapi_cases/library.go
Added prealloc linter
When we can prealloc slice - we'll do it. Sometimes we forget to do it. This linter can help to check accidentally missed prealloc.
```changes
type: chore
summary: added prealloc linter
```
=> chore: add prealloc linter

candi/bashible/common-steps/all/002_disable_unattended_upgrades.sh.tpl
Fix `disable_unattended_upgrades` bashible step
Step not working
```
root@kovalkov-master-0:~# systemctl list-unit-files unattended-upgrades
UNIT FILE STATE PRESET
0 unit files listed.
root@kovalkov-master-0:~# systemctl list-unit-files unattended-upgrades.service
UNIT FILE                   STATE   PRESET
unattended-upgrades.service enabled enabled
1 unit files listed.
```
```changes
section: candi
type: fix
summary: Fix `disable_unattended_upgrades` bashible step
```
=> [candi] Fix disable_unattended_upgrades bashible step

dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go, dhctl/pkg/operations/converge/runner.go, dhctl/pkg/operations/nodebootstrap.go
```changes
section: dhctl
type: chore
summary: Add opportunity to bootstrap terranodes parallel with env DHCTL_PARALLEL_CLOUD_PERMANENT_NODES_BOOTSTRAP revert sequentially by default 
```
=> [dhctl] Add opportunity to bootstrap terranodes parallel with env DHCTL_PARALLEL_CLOUD_PERMANENT_NODES_BOOTSTRAP revert sequentially by default 

.github/ci_templates/build.yml, .github/workflow_templates/build-and-test_dev.yml, .github/workflow_templates/build-and-test_release.yml, .github/workflow_templates/cve-pr.yml, .github/workflow_templates/cve-weekly.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml, .github/workflows/cve-pr.yml, .github/workflows/cve-weekly.yml, .github/workflows/rootless-images-scan.yml
Switch CI runners.
```changes
section: ci
type: chore
summary: Switch CI runners.
```
=> [ci] Switch CI runners

docs/documentation/_data/deckhouse-alerts.yml, docs/documentation/_plugins/custom_filters.rb, modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
Fixes the grouping of alerts based on secret `namespace`/`name` metadata.
Before: uses 'namespace' label that is taken from exporter namespace.
After: uses 'secret_namespace'/'secret_name' that is taken from secret resources metadata.
Improves/fixes the grouping of series based on proper labels.
```changes
type: fix 
summary:  Minor certificate alerts improvements
```
=> [extended-monitoring] Fix certificate alert expressions/description

modules/300-prometheus/hooks/grafana_v8_cleanup.go
Add additional label `heritage: deckhouse`filter for grafana v8 resources cleanup hook.
```changes
type: chore
summary: Minor improvements
```
=> [prometheus] Grafana v8 cleanup hook add label filter

modules/150-user-authn/hooks/discover_apiserver_endpoints.go, modules/150-user-authn/hooks/discover_apiserver_endpoints_test.go
Fix hook internal error
Rarely, when no apiservers provided hook can generate an error:
```
ModuleHookRun:/modules/user-authn:kubernetes:150-user-authn/hooks/discover_apiserver_endpoints.go:endpoints:Kubernetes:failures 8:2 errors occurred:
* userAuthn.internal.kubernetesApiserverAddresses must be of type array: "null"
```
I don't think we have to block the whole queue while apiservers are not ready. When they become ready, hook will execute with the a new values.
```changes
type: fix
summary: Fix publishAPI hook error when apiservers are not ready.
```
=> Fix the hook error is no apiserver endpoints

docs/documentation/_plugins/custom_sidebar.rb
This pull request includes a minor update to the `sidebar_entry` method in the `docs/documentation/_plugins/custom_sidebar.rb` file. The change removes the `target='_blank'` attribute from internal links to improve user experience and consistency.
* [`docs/documentation/_plugins/custom_sidebar.rb`](diffhunk://#diff-9a72a7b1ff62aa6f5804ae3e0510e235f771412700830f2c3466898be4b796a2L119-R119): Removed the `target='_blank'` attribute from internal links within the `sidebar_entry` method.
```changes
section: docs
type: fix
summary: Fixed sidebar behaviour with links.
```
=> [docs] Fix sidebar behaviour with links

deckhouse-controller/crds/doc-ru-module-source.yaml, deckhouse-controller/crds/module-release.yaml, deckhouse-controller/crds/module-source.yaml, deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_release.go, deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_source.go, deckhouse-controller/pkg/controller/module-controllers/release/controller.go, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-mode.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-patch-minor-update.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-patch-mode-minor-release-approved.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-patch-mode.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/clean-up-outdated-module-releases-for-deployed.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/clean-up-outdated-module-releases-when-deploy.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/dVersion-suitable.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/dVersion-unsuitable.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/kVersion-suitable.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/kVersion-unsuitable.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/new-module-manual-mode.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/simple.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/with-annotation.yaml, deckhouse-controller/pkg/controller/module-controllers/source/controller.go, deckhouse-controller/pkg/controller/module-controllers/source/controller_test.go, deckhouse-controller/pkg/controller/module-controllers/source/helpers.go, deckhouse-controller/pkg/controller/module-controllers/source/testdata/golden/empty.yaml, deckhouse-controller/pkg/controller/module-controllers/source/testdata/golden/withmodulepullerror.yaml, deckhouse-controller/pkg/controller/module-controllers/source/testdata/golden/withmodules.yaml
It provides terminating status for ms and mr.
Fixes #12212
To explicitly show that module source/release is deleted.
```
root@dev-master-0:~# k get ms
NAME         COUNT   STATUS        SYNC   MSG
deckhouse    20      Active        5s     Some errors occurred. Inspect status for details
foxtrot      3       Active        5s     Ready
losev-test   1       Active        5s     Ready
test         1       Terminating   37m    The source contains at least 1 deployed release and cannot be deleted. Please delete target ModuleReleases manually to continue
```
```changes
type: feature
summary: Terminating status for module source and release.
```
=> [deckhouse] terminating for ms and mr

modules/values-default.yaml
Remove smoke-mini from module bundles.
```changes
section: docs
type: chore
summary: Remove smoke-mini from module bundles.
```
=> [docs] Remove smoke-mini from module bundles

.github/ci_templates/build.yml, .github/workflow_templates/build-and-test_dev.yml, .github/workflow_templates/build-and-test_release.yml, .github/workflow_templates/cve-pr.yml, .github/workflow_templates/cve-weekly.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml, .github/workflows/cve-pr.yml, .github/workflows/cve-weekly.yml, .github/workflows/rootless-images-scan.yml
Rename CI runners.
```changes
section: ci
type: chore
summary: Rename CI runners.
```
=> [ci] Rename runners

candi/cloud-providers/yandex/docs/ENVIRONMENT.md, candi/cloud-providers/yandex/docs/ENVIRONMENT_RU.md, docs/site/_includes/getting_started/yandex/STEP_ENV.md, docs/site/_includes/getting_started/yandex/STEP_ENV_RU.md
Updated information about service account roles at Yandex Cloud. Based on [11012 issue](https://github.com/deckhouse/deckhouse/issues/11012).
```changes
section: docs
type: chore
summary: Updated information about service account roles at Yandex Cloud.
```
=> [docs] Updated information about service account roles at Yandex Cloud

ee/modules/500-operator-trivy/docs/README.md, ee/modules/500-operator-trivy/docs/README_RU.md
This pull request includes updates to the documentation of the `operator-trivy` module to provide more detailed information about its functionality and the sources used for vulnerability scanning.
Documentation updates:
* [`ee/modules/500-operator-trivy/docs/README.md`](diffhunk://#diff-861c441a1cade7abc857133b0319a59e2eae93ad3fe1b33e845ce4f919f3d684L6-R6): Updated the description to specify that the module scans user images in runtime for known CVEs using public databases.
* [`ee/modules/500-operator-trivy/docs/README_RU.md`](diffhunk://#diff-2d38f2dffe10d09819c85884602d59abb2711bb54ea217a35c59fa336d522cddL6-R6): Enhanced the description to include details about scanning user images in runtime for known CVEs, including vulnerabilities specific to Astra Linux, Redos, and Altlinux, and the …
=> [docs][operator-trivy] Update info about databases with vulnerabilities

docs/documentation/_data/modules/modules-addition.json, docs/site/backends/docs-builder-template/data/editions.json, docs/site/backends/docs-builder-template/data/modules_all.json
Update revision of csi-yadro-tatlin-unified module.
```changes
section: docs
type: chore
summary: Update revision of csi-yadro-tatlin-unified module.
```
=> [docs] Update revision of csi-yadro-tatlin-unified module

deckhouse-controller/pkg/controller/module-controllers/source/controller.go
It clears module source message after successful reconcile.
Message is not cleared.
```changes
type: fix
summary: Clear source message
```
=> [deckhouse] clear source message

tools/cve/base-images.sh, tools/cve/d8-images.sh, tools/cve/trivy-wrapper.sh
Trivy will use all severity levels for CVE scan
currently only HIGH and CRITICAL levels are used
```changes
section: ci
type: chore
summary: Trivy will use all severity levels for CVE scan
```
=> Use all Trivy severity levels

docs/documentation/_data/modules/modules-addition.json, docs/site/.helm/templates/_rewrites.tpl, docs/site/backends/docs-builder-template/data/modules_all.json
Remove deprecated csi-yadro and sds-drbd modules. Add redirects.
```changes
section: docs
type: chore
summary: Remove deprecated csi-yadro and sds-drbd modules. Add redirects.
```
=> [docs] Remove deprecated csi-yadro and sds-drbd modules. Add redirects.

ee/modules/030-cloud-provider-vcd/images/cloud-controller-manager-legacy/patches/001_ignore_static_nodes.patch, ee/modules/030-cloud-provider-vcd/images/cloud-controller-manager/patches/001_ignore_static_nodes.patch
Ignore a node if `providerID` has `static://` prefix.
We need to ignore static nodes created by `CAPS`.
```changes
type: fix
summary: Add a patch to `cloud-controller-manager` that ignores a node if `providerID` has `static://` prefix.
```
=> [cloud-provider-vcd](ccm) Fix a patch that ignored static nodes

dhctl/pkg/kubernetes/actions/deckhouse/delete.go, dhctl/pkg/operations/destroy/deckhouse.go
Add pdbs deletion to DeckhouseDestroyer
Sometimes, if pdbs exists, destroy process stucks. So we need to delete it to avoid such stucks. 
```changes
section: dhctl
type: fix
summary: Add pdbs deletion to DeckhouseDestroyer.
```
=> [dhctl] Add pdbs deletion to DeckhouseDestroyer

ee/modules/650-runtime-audit-engine/rules/k8s_audit_rules.yaml, ee/modules/650-runtime-audit-engine/templates/falco-rules.yaml, modules/040-control-plane-manager/hooks/audit_policy.go, modules/040-control-plane-manager/hooks/audit_policy_test.go
Checked built-in `runtime-audit-engine` rules, made necessary corrections. Checked that all rules work and all fields have correct values (without `<NA>` in output)
Deleted unused macros. Changed order of rules for correct `runtime-audit-engine` operation
```
falco-rules.yaml | yq e '.spec.rules[] | select(.rule.source == "K8sAudit") | .rule.name' | sort -h
Attach to cluster-admin Role
Attach/Exec Pod
ClusterRole with Pod Exec created
ClusterRole with wildcard created
ClusterRole with write privileges created
Container tag is not @sha256
EphemeralContainers created
K8s Pod created
K8s Pod deleted
K8s Role/ClusterRole binding created
K8s Role/ClusterRole binding deleted
K8s Role/ClusterRole created
K8s Role/ClusterRole deleted
K8s ServiceAccount created
K8s ServiceAccount deleted …
```
=> [runtime-audit-engine] built-in rules fix

dhctl/pkg/operations/bootstrap/cluster-bootstrapper-abort.go, dhctl/pkg/operations/bootstrap/steps.go, dhctl/pkg/preflight/preflight.go, dhctl/pkg/system/node/ssh/frontend/command.go
Fix [#12439](https://github.com/deckhouse/deckhouse/issues/12439)
If sudo password is wrong, bootstrap-phase abort just exits with non-readable error. So we'll add preflight checks to ensure what provided password is correct.
```changes
section: dhctl
type: fix
summary: Add minimal preflight checks to bootstrap-phase abort.
```
=> [dhctl] Fix sudo and add preflight to bootstrap-phase abort

dhctl/cmd/dhctl/commands/edit.go, dhctl/cmd/dhctl/commands/ssh.go, dhctl/cmd/dhctl/commands/terraform.go, dhctl/pkg/kubernetes/actions/deckhouse/install.go, dhctl/pkg/kubernetes/kube.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper-deckhouse.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper-resources.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go, dhctl/pkg/operations/bootstrap/steps.go, dhctl/pkg/operations/check/checker.go, dhctl/pkg/operations/commander/attach/attacher.go, dhctl/pkg/operations/converge/context/client_switcher.go, dhctl/pkg/operations/converge/context/context.go, dhctl/pkg/operations/converge/converger.go, dhctl/pkg/operations/destroy/deckhouse.go, dhctl/pkg/system/node/ssh/frontend/waiting.go, dhctl/pkg/util/retry/retry.go, dhctl/pkg/util/retry/retry_test.go
Add new retry.Loop method RunContext which accepts context and breaks if context done.
Add context to ConnectToKubernetesAPI func (we also need it in Installer).
In the future, the use of the Run function will be replaced with RunContext in cases where it is possible for the user to cancel the operation. This includes long processes such as bootstrapping, destroying, and converging.
Such locations are marked with appropriate TODO comments (dhctl-for-commander-cancels).
```changes
section: dhctl
type: feature
summary: make retrier cancellable
```
=> [dhctl] feat(dhctl-for-commander-cancels): add ctx to retry

modules/021-cni-cilium/images/agent/werf.inc.yaml
- Remove duplicate files for the `iproute2` package.
- Keep only one locale in use (`C.UTF-8`):
```shell
224M    /usr/lib/locale
396K    /usr/lib/locale/C.utf8/
```
Optimize image size.
```changes
type: chore
summary:  Optimized locale and iproute2 package file size and composition.
```
=> [cni-cilium] Optimize locale and iproute2 package file size and composition

ee/modules/025-static-routing-manager/crds/routingtables.yaml
Fixed regular expression to allow empty string in `nodeSelector` field for `routingtables.network.deckhouse.io` resource.
Probably some clients may have nodes with empty `nodeSelector` field.
```changes
section: static-routing-manager
type: fix
summary: Fixed regular expression to allow empty string in `nodeSelector` field.
```
=> [static-routing-manager] fix regexp for allow empty label

modules/402-ingress-nginx/images/controller-1-10/werf.inc.yaml
The `owasp-modsecurity-crs` directory was deleted as a consequence of the CVE vulnerability discovery. Deckhouse don't support the option.
This directory is used when the ingress controller `enable-owasp-modsecurity-crs: “true” option is specified in ConfigMap.
One customer, during internal security testing, discovered that this directory contained bash scripts whose implementation exposed CVE vulnerabilities.
```changes
type: fix
summary: Fixed CVE vulnerability upon client request
```
=> [ingress-nginx] fix cve vulnarible

ee/se-plus/modules/030-cloud-provider-zvirt/hooks/get_cni_secret.go, modules/030-cloud-provider-aws/hooks/get_cni_secret.go, modules/030-cloud-provider-aws/openapi/values.yaml, modules/030-cloud-provider-aws/templates/cni.yaml, modules/030-cloud-provider-azure/hooks/get_cni_secret.go, modules/030-cloud-provider-azure/openapi/values.yaml, modules/030-cloud-provider-azure/templates/cni.yaml, modules/030-cloud-provider-gcp/hooks/get_cni_secret.go, modules/030-cloud-provider-gcp/openapi/values.yaml, modules/030-cloud-provider-gcp/templates/cni.yaml, modules/030-cloud-provider-yandex/hooks/ensure_crds.go, modules/030-cloud-provider-yandex/hooks/get_cni_secret.go, modules/030-cloud-provider-yandex/openapi/values.yaml, modules/030-cloud-provider-yandex/templates/cni.yaml
We have added a hook to the modules of all our cloud providers that helps to prevent overwriting the settings of selected CNI.
All the cloud-providers were refactored to use `go_lib/hooks/get_cni_secret/hook.go` by analogy with the `cloud-provider-openstack`.
Some customers want to use CNI `Cilium` in their cloud installations (in particular, in AWS and YC). However, in the current implementation, CNI automatically switches to `simple-brigade` after a certain period of time.
The general solution is coming soon.
```changes
type: chore
summary: Added the ability to switch to another CNI.
---
type: chore
summary: Added the ability to switch to another CNI.
--- …
```
=> [cni] Adding the ability to switch to another CNI in cloud installations.

modules/040-node-manager/hooks/get_crds.go, modules/040-node-manager/hooks/get_crds_test.go
The `get_crds` hook will fail with error if the node groups count in cluster is not equal to the calculated one.
We had an indecent with dropping all machinedeployments and cloud nodes and we decide to add error if count calculated nodegroups not equals node groups in the cluster 
```changes
type: chore
summary:  The `get_crds` hook will fail with error if the node groups count in cluster is not equal to the calculated one.
```
=> [node-manager] the `get_crds` hook will fail with error if the node groups count in cluster is not equal to the calculated one

ee/se/modules/380-metallb/hooks/alert_for_annotations_and_mc.go
Add metric group clearing in the new alert D8MetallbObsoleteLayer2PoolsAreUsed
In v1.68.0, a new alert `D8MetallbObsoleteLayer2PoolsAreUsed` was added.
https://github.com/deckhouse/deckhouse/pull/11728
A new metric [d8_metallb_obsolete_layer2_pools_are_used](https://github.com/deckhouse/deckhouse/blob/main/ee/se/modules/380-metallb/hooks/alert_for_annotations_and_mc.go#L81) and a new group for this metric [D8MetallbObsoleteLayer2PoolsAreUsed](https://github.com/deckhouse/deckhouse/blob/main/ee/se/modules/380-metallb/hooks/alert_for_annotations_and_mc.go#L83) were created for it, but clearing of metrics from this group was not added to the hook, so if (`d8_metallb_obsolete_layer2_pools_are_used == 1`) repeated triggering of the hook will not reset the metric.
This is needed in the patch …
=> [metallb] Add clearing of alert metric group D8MetallbObsoleteLayer2PoolsAreUsed

ee/candi/cloud-providers/vcd/terraform-modules/master-node/main.tf, ee/candi/cloud-providers/vcd/terraform-modules/static-node/main.tf
Increase `network_dhcp_wait_seconds` in the `vcd_vapp_vm` resource from 60 to 120 seconds.
`dhctl bootstrap` exited with an error:
```changes
section: candi
type: fix
summary: Increase `network_dhcp_wait_seconds` in the `vcd_vapp_vm` resource from 60 to 120 seconds.
```
=> [candi](vcd) Increase `network_dhcp_wait_seconds`

modules/140-user-authz/templates/rbacv2/global/use/roles/dict.yaml
Add DVP dicts for next resources:
- virtualmachineclasses
- clustervirtualimages
We need to get and list DVP resources too.
It extends this [PR](https://github.com/deckhouse/deckhouse/pull/11943)
```
root@dev-master-0:~# cat testrole.yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: developer
subjects:
- kind: User
name: developer
apiGroup: rbac.authorization.k8s.io
- kind: User
name: developer2
apiGroup: rbac.authorization.k8s.io
roleRef:
kind: ClusterRole
name: d8:use:role:viewer
apiGroup: rbac.authorization.k8s.io
```
```
root@dev-master-0:~# kubectl get clusterrolebindings.rbac.authorization.k8s.io d8:dict:
2h6xn  kk58q  
root@dev-master-0:~# kubectl get clusterrolebindings.rbac.authorization.k8s.io d8:dict:2h6xn -oyaml
apiVersion: …
```
=> [user-authz] use dvp dict

deckhouse-controller/pkg/controller/deckhouse-release/controller.go, deckhouse-controller/pkg/controller/deckhouse-release/controller_test.go, deckhouse-controller/pkg/controller/deckhouse-release/event.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/few-patch-releases.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/apply-now-deckhouse-previous-release-is-not-ready.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/deckhouse-previous-release-is-not-ready.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/few-minor-releases.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/few-patch-releases.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/minor-release-and-patch-release.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/minor-release-and-patch-release.yaml, deckhouse-controller/pkg/controller/module-controllers/release/controller.go, deckhouse-controller/pkg/releaseupdater/deploy_time_checker.go, deckhouse-controller/pkg/releaseupdater/task_calculator.go, modules/340-monitoring-deckhouse/monitoring/prometheus-rules/alerting.yaml
Provides multiples fixes to deckhouse/module release controllers regarding metrics and applying releases.
Closes #12352 
Closes #12353 
The following issues have been fixed:
1) missing/flapping `d8_is_updating` metric. The metrics is set to 1 when deckhouse controller detects that the deployed release has `IsUpdating` annotation set to true and the deckhouse pod isn't ready. As soon as the deckhouse pod becomes ready, the annotations is set to false from the deployed release and the metric is expired. This way, we say the deckhouse is updating only during the first run on a new deployed release. In order to make it work, the deckhouse-controller's `releasePhasePredicate` predicate has been updated to exclude objects at `v1alpha1.ModuleReleasePhaseDeployed` phase.
2) missing …
=> [deckhouse-controller] fix applying releases and their metrics

deckhouse-controller/pkg/controller/controller.go, deckhouse-controller/pkg/controller/module-controllers/config/controller.go, deckhouse-controller/pkg/controller/module-controllers/source/helpers.go
It provides fix for module condition race.
Both of controllers - the config and source change the EnabledByModuleConfig condition, it leads to race. 
```changes
type: fix
summary: Fix module condition race.
```
=> [deckhouse] fix module condition race

modules/340-monitoring-kubernetes/templates/kubelet/service-monitor.yaml
Remove cadvisor image|name label drop
```changes
type: chore
summary: Add `image`, `name` labels to cadvisor metrics 
```
=> [monitoring-kubernetes] Remove cadvisor image|name label drop

ee/se-plus/modules/030-cloud-provider-vsphere/hooks/discover_zones_and_datastores.go, ee/se-plus/modules/030-cloud-provider-vsphere/hooks/discover_zones_and_datastores_test.go
Fix [issue](https://github.com/deckhouse/deckhouse/issues/8090)
```changes
type: fix
summary: Fix null storageclasses vsphere on exclude storageclasses from discovery
```
=> [cloud-provider-vsphere] Fix null storageclasses vsphere

modules/460-log-shipper/hooks/internal/vector/transform/destination.go, modules/460-log-shipper/hooks/testdata/file-to-kafka-tls/result.json, modules/460-log-shipper/hooks/testdata/file-to-kafka/result.json
Add delete parsed_data to final kafka transform render
```changes
type: fix
summary: Add delete parsed_data to final kafka transform render
```
=> [log-shipper] fix kafka parsed-data

deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module.go, deckhouse-controller/pkg/controller/moduleloader/loader.go
It sets EnabledByModuleConfig condition by default for all modules.
Before 1.67, module releases were created by default, the process did not depend on a module enabling. After 1.67, module releases are created only if the module is enabled. And if a module is disabled(by config) more than 3 days - it`s deleted. But if a module was not enabled(there is no config) deckhouse does not consider the module as disabled and does not delete releases.  To fix it - module loader sets EnabledByModuleConfig condition if it is unset.
```changes
type: fix
summary: Set EnabledByModuleConfig condition by default for modules without this condition.
```
=> [deckhouse] set EnabledByModuleConfig condition for modules by default

go_lib/dependency/k8s/drain/default.go, go_lib/dependency/k8s/drain/drain.go, modules/040-node-manager/hooks/handle_draining.go
handleDraining hook does not consider timeout to be a critical error and continues working
test: https://github.com/deckhouse/deckhouse/pull/12542#issuecomment-2721351697
handleDraining hook does cordon and drain node, this hook has a timeout. In some cases drain cannot be executed at the right time for various reasons, such as an incorrectly configured PDB. This results in the hook never being executed
```changes
type: fix
summary: ignore timeout error in handleDraining hook
impact: 
```
=> [node-manager] ignore timeout error in handleDraining hook

modules/042-kube-dns/hooks/migration_deployment.go, modules/042-kube-dns/hooks/migration_deployment_test.go, modules/042-kube-dns/hooks/migration_service_with_many_ports.go
Fix problem with absent kube-dns port
Explicitly set ports in d8-kube-dns deployment, kubernetes uses StrategicMergePatch and the key for merge patch is the containerPort, but we need to have the same containerPort with only different protocols, so when we try to patch old deployment with only one port set kuberentes thinks that we already have that port and we don't need to patch anything.
We need this because in old clusters there are deployments with only one container port
```changes
type: fix
summary: Explicitly set ports in d8-kube-dns deployment.
```
=> [deckhouse] explicitly set ports for kube dns deployment

ee/modules/110-istio/templates/validations.yaml
Included `helm_lib_get_api_version_by_kind` library to dynamically render apiVersion  `ValidatingAdmissionPolicy` and `ValidatingAdmissionPolicyBinding` depending on `Capabilities.APIVersions`.
During e2e tests it was found out that api admissionregistration.k8s.io/v1beta1 is deprecated and since Kubernetes 1.30 version admissionregistration.k8s.io/v1 is used, helm chart validation condition is required.
```changes
section: istio
type: fix
summary: Added kubernetes version check in helm chart.
```
=> [istio] fix api version for validations serviceentry ports

deckhouse-controller/pkg/releaseupdater/requirements_checker.go
It fixes checking automatic kubernetes version in managed clusters.
In managed clusters there is no cluster configuration secret.
Deckhouse update failed.
```changes
type: fix
summary: Fix checking automatic kubernetes version in managed clusters.
```
=> [deckhouse] fix checking automatic kubernetes version in managed clusters

modules/030-cloud-provider-azure/images/cloud-controller-manager/patches/1.28/002-fix-disable-api-call-cache.patch, modules/030-cloud-provider-azure/images/cloud-controller-manager/patches/1.28/README.md, modules/030-cloud-provider-azure/images/cloud-controller-manager/patches/1.29/002-fix-disable-api-call-cache.patch, modules/030-cloud-provider-azure/images/cloud-controller-manager/patches/1.29/README.md, modules/030-cloud-provider-azure/images/cloud-controller-manager/patches/1.30/002-fix-disable-api-call-cache.patch, modules/030-cloud-provider-azure/images/cloud-controller-manager/patches/1.30/README.md, modules/030-cloud-provider-azure/images/cloud-controller-manager/patches/1.31/002-fix-disable-api-call-cache.patch, modules/030-cloud-provider-azure/images/cloud-controller-manager/patches/1.31/README.md, modules/030-cloud-provider-azure/images/cloud-controller-manager/patches/1.32/002-fix-disable-api-call-cache.patch, modules/030-cloud-provider-azure/images/cloud-controller-manager/patches/1.32/README.md, modules/030-cloud-provider-azure/templates/cloud-controller-manager/secret.yaml
To disable API call caching, the following changes have been made:  
- Added the `disableAPICallCache: true` option to the `cloud-controller-manager` configuration
- Removed the `useInstanceMetadata: true` option from the `cloud-controller-manager` configuration
- Applied a patch to fix issues in the disable API call cache feature
Deleting or recreating a virtual machine does not trigger the deletion of the `Node` resource if API call caching is enabled.
```changes
type: fix
summary: Disable API call caching in `cloud-controller-manager`.
```
=> [cloud-provider-azure] Disable caching of API calls in `CCM`

.github/ci_includes/werf_envs.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml, .werf/defines/modules.tmpl, .werf/werf-modules.yaml, Makefile, candi/version_map.yml, modules/007-registrypackages/images/d8/werf.inc.yaml, modules/800-deckhouse-tools/images/web/werf.inc.yaml, tools/images_tags/main.go, werf-giterminism.yaml, werf.yaml
Fixing d8-cli build, removing unnecessary secrets
! Can be merged only after https://github.com/deckhouse/deckhouse-cli/pull/94 and version bumping
Also don't forget to remove `# TODO test only` - needed for dev branch testing
```changes
type: fix
summary: [chore] d8-cli build fix
impact:
```
=> [deckhouse-tools] build fix

helm_lib/Chart.lock, helm_lib/Chart.yaml, helm_lib/charts/deckhouse_lib_helm/Chart.yaml, helm_lib/charts/deckhouse_lib_helm/README.md, helm_lib/charts/deckhouse_lib_helm/templates/_csi_node.tpl, helm_lib/charts/deckhouse_lib_helm/templates/_module_image.tpl, helm_lib/charts/deckhouse_lib_helm/templates/_priority_class.tpl
Update helm_lib to 1.44.5
Added new functions:
- helm_lib_module_image_digest
- helm_lib_module_image_digest_no_fail
```changes
section: tools
type: chore
summary: update lib_helm to 1.44.5
```
=> [tools] update helm_lib to 1.44.5

candi/version_map.yml
Updated Deckhouse CLI to latest
```changes
section: candi
type: chore
summary: Update Deckhouse CLI to 0.11.3
```
=> [candi] Update Deckhouse CLI to 0.11.3

ee/candi/cloud-providers/vcd/terraform-modules/master-node/main.tf
Added hack to migrate etcd data disk to vcd_independent_disk. Master servers are recreated for migration. In case there is only one master server, dhctl suggested to run automatic scaling mechanism to 3.
tested:
- migration from 1 master with internal disk tested
- changing vm template in a  3 master cluster without loss of etcd data
- bootstrap from scratch
```changes
type: fix
summary: migrate ETCD disk to VCD Independent Disk to prevent deletion of ETCD data
impact: To migrate you must perform a converge, this will cause the master server to be recreated. If you are using only 1 master server with manual address assignment via `mainNetworkIPAddresses` parameter, you need to add 2 more IP addresses for the migration process.
```
=> [cloud-provider-vcd] Change the etcd(kubernetes_data) storage disk type from vcd_vm_internal_disk to vcd_independent_disk 

docs/site/.werf/nginx.conf
this mr allow download d8 cli through trdl client from deckhouse.ru/downloads/deckhouse-cli-trdl
this allow download d8 bin artifacts through trdl from deckhouse.ru domain, not trrr.flant.dev.
```changes
section: chore
type: feature
summary: Add trdl Nginx configuration to the site.
```
=> [docs] Add trdl nginx configuration to deckhouse.ru

deckhouse-controller/pkg/controller/module-controllers/config/controller.go
It fixes the case when a module config ignored because the module is discovered after the config created.
Prev fix: https://github.com/deckhouse/deckhouse/pull/12039
If a module is discovered after the module config created, the config is ignored because the controller cannot find the module. When the module created - nothing triggers the config to reconcile(watcher mechanism doesn't always work) so we set interval in 3 minutes to trigger the config by it. 
Flaky error, it can appear when a cluster is setting up by commander. Only reboot or trigger config fixed it.
```changes
type: fix
summary: Fix module config ignored.
```
=> [deckhouse] module config ignored

.github/scripts/js/changelog-command-validate.js, .github/workflow_templates/dispatch-slash-command.yml, .github/workflows/dispatch-slash-command.yml
This update enhances the changelog generation action, allowing it to run for closed milestones as well. Previously, the action was restricted to open milestones, which limited the ability to retrospectively update changelogs for completed releases.  
By enabling changelog generation for closed milestones, this change improves visibility into past releases, ensuring that all changes are properly documented. This is particularly useful for auditing purposes and release management, where maintaining an accurate changelog is critical.
```changes
section: ci
type: fix
summary: This update enhances the changelog generation action
```
=> fix changelog generation

modules/021-cni-cilium/monitoring/grafana-dashboards/kubernetes-cluster/cilium-ping-nodes.json, modules/300-prometheus/images/grafana-v10/werf.inc.yaml
We have added a new dashboard to help quickly identify any connectivity issues between nodes in the cluster. 
This dashboard is similar to the periodic execution of the `cilium-health status` command on all the nodes in the cluster.
This dashboard is very useful, as it allows you to quickly identify connection issues between nodes. In addition, all the necessary metrics are already available in Prometheus.
```changes
type: feature 
summary: Added new dashboard "Cilium Nodes Connectivity Status&Latency"
---
type: feature 
summary: Added new grafana plugin `esnet-matrix-panel`.
```
=> [cilium] Adding a new dashboard for cilium.

docs/site/_includes/getting_started/global/partials/INSTALL_OTHER.liquid, docs/site/_includes/getting_started/global/partials/INSTALL_OTHER_RU.liquid, docs/site/_includes/getting_started/global/partials/select_revision.html.liquid
Fixed a problem with config duplication for zvirt and vSphere.
Added login step in registry for BE, CE, CE+, EE.
```changes
section: docs
type: fix
summary: Fixed a problem with config duplication for zVirt and vSphere.
```
=> [docs] Fix config duplication problem in Getting Started for zVirt and vSphere

.github/ci_templates/build.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml
Increase werf verbosity for build.
Increased verbosity allows to determine whether the local / remote cache are properly utilized.
```changes
section: ci
type: chore
summary: Increase werf verbosity for build.
```
=> [ci] Increase werf verbosity

dhctl/pkg/operations/converge/controller/cloud_permanent_node_group.go, dhctl/pkg/operations/converge/controller/cloud_permanent_node_group_hook.go, dhctl/pkg/operations/converge/controller/node_group_controller.go, dhctl/pkg/operations/converge/infra/hook/controlplane/hook_for_destroy_pipeline.go, dhctl/pkg/operations/converge/infra/utils/drain.go
Added before hook for Cloud Permanent Node removal pipeline. Hook executes Node drain before deletion (just like we do for control plane nodes)
Deleting a node without drain can cause CSI problems or service interruptions
```changes
section: dhctl
type: fix
summary: Cloud Permanent Node converge should drain node before removal
impact:
```
=> [dhctl] converge should drain node before removal

ee/candi/cloud-providers/openstack/layouts/simple/master-node/main.tf, ee/candi/cloud-providers/openstack/layouts/standard/base-infrastructure/main.tf, ee/candi/cloud-providers/openstack/terraform-modules/master/main.tf, ee/candi/cloud-providers/openstack/terraform-modules/static-node/main.tf
Added check for tags and if there are 0 of them set null for metadata.
Close https://github.com/deckhouse/deckhouse/issues/11881
```changes
type: fix 
summary: fixed set empty metadata
```
=> [cloud-provider-openstack] fixed set empty metadata

modules/040-node-manager/templates/rbac-for-us.yaml
This pr allow to list secrets in kube-system mcm role.
This allow permission list secrets to mcm role and resolve this [pr](https://fox.flant.com/deckhouse/3p/deckhouse/mcm/-/merge_requests/2) and partly [this](https://github.com/deckhouse/deckhouse/issues/12233) issue.
```changes
type: chore 
summary: allow to list secrets in kube-system mcm role
```
=> [node-manager] allow to list secrets in kube-system mcm role

docs/documentation/_data/modules/modules-addition.json
This pull request includes an update to the `docs/documentation/_data/modules/modules-addition.json` file. The change adds new editions to the list of editions with restrictions for the "istio" module.
Changes to module restrictions:
* [`docs/documentation/_data/modules/modules-addition.json`](diffhunk://#diff-22b3a9a2748222753363a5ea87810c660a94b32bd3ce8fb99164cf00285b3bb0L24-R26): Added "se" and "se-plus" to the list of editions with restrictions for the "istio" module.
```changes
section: docs
type: fix
summary: Added SE and SE+ restrictions for Istio.
```
=> [docs][istio] Add SE and SE+ restrictions for Istio

docs/documentation/_data/deckhouse-alerts.yml, modules/031-ceph-csi/monitoring/prometheus-rules/deprecated-module-alert.yaml, modules/031-ceph-csi/templates/monitoring.yaml
Add ceph-csi deprecation alert
Ceph-csi module is deprecated and user must migrate from it.
```changes
type: chore
summary: Add ceph-csi deprecation alert
```
=> Add ceph-csi deprecation alert

deckhouse-controller/pkg/controller/module-controllers/config/controller.go
It fixes the case when a module config ignored because the module is discovered after the config created.
Prev fix: https://github.com/deckhouse/deckhouse/pull/12039
If a module is discovered after the module config created, the config is ignored because the controller cannot find the module. When the module created - nothing triggers the config to reconcile(watcher mechanism doesn't always work) so we set interval in 3 minutes to trigger the config by it. 
Flaky error, it can appear when a cluster is setting up by commander. Only reboot or trigger config fixed it.
```changes
type: fix
summary: Fix module config ignored.
```
=> [deckhouse] 1.68 module config ignored

tools/dmt-lint.sh
Update DMT version to 0.1.9
Use new lint settings
```changes
section: tools
type: chore
summary: update DMT version to 0.1.9
```
=> [tools] update DMT version to 0.1.9 in dmt-lint.sh

deckhouse-controller/files/bashrc, werf.yaml
Additional fix for https://github.com/deckhouse/deckhouse/pull/11501.
Forget change kubectl version in bashrc.
```
[root@dev-master-0 ~]# kubectl  exec -it -n d8-system svc/deckhouse-leader -- /bin/bash
bash: kubectl-1.28: command not found
```
```changes
type: fix
summary: Change kubectl version in bashrc.
```
=> [deckhouse-controller] additional fix for kubectl in deckhouse image

modules/402-ingress-nginx/images/controller-1-10/patches/README.md, modules/402-ingress-nginx/images/controller-1-10/patches/fix-validating-webhook-cve.patch, modules/402-ingress-nginx/images/controller-1-10/werf.inc.yaml, modules/402-ingress-nginx/images/controller-1-9/Dockerfile, modules/402-ingress-nginx/images/controller-1-9/patches/README.md, modules/402-ingress-nginx/images/controller-1-9/patches/fix-validating-webhook-cve.patch
Backports several security fixes to release-1.68 by means of applying patches to v1.9 and v1.10 of ingress-nginx controller. 
The source of the patches can be found [here](https://github.com/kubernetes/ingress-nginx/pull/13068).
The following CVEs of ingress-nginx are concerned:
CVE-2025-1097
CVE-2025-1098
CVE-2025-1974
CVE-2025-24513
CVE-2025-24514
Regarding CVE-2025-1974, it was necessary to disable the validation of the generated NGINX configuration during the validation of Ingress resources.
The resulting NGINX configuration is still checked before the actual loading, so that there are no failures of the underlying NGINX. However, invalid Ingress resources can lead to the NGINX configuration no longer being able to be updated.
In case of doubt, nginx configuration issues can be …
=> [ingress-nginx] backport latest cve fixes to v1.9 and v1.10 to release-1.68

modules/402-ingress-nginx/images/controller-1-10/Dockerfile, modules/402-ingress-nginx/images/controller-1-10/patches/README.md, modules/402-ingress-nginx/images/controller-1-10/patches/fix-validating-webhook-cve.patch, modules/402-ingress-nginx/images/controller-1-9/Dockerfile, modules/402-ingress-nginx/images/controller-1-9/patches/README.md, modules/402-ingress-nginx/images/controller-1-9/patches/fix-validating-webhook-cve.patch
Backports several security fixes to release-1.67 by means of applying patches to v1.9 and v1.10 of ingress-nginx controller. 
The source of the patches can be found [here](https://github.com/kubernetes/ingress-nginx/pull/13068).
The following CVEs of ingress-nginx are concerned:
CVE-2025-1097
CVE-2025-1098
CVE-2025-1974
CVE-2025-24513
CVE-2025-24514
Regarding CVE-2025-1974, it was necessary to disable the validation of the generated NGINX configuration during the validation of Ingress resources.
The resulting NGINX configuration is still checked before the actual loading, so that there are no failures of the underlying NGINX. However, invalid Ingress resources can lead to the NGINX configuration no longer being able to be updated.
In case of doubt, nginx configuration issues can be …
=> [ingress-nginx] backport latest cve fixes to v1.9 and v1.10 to release-1.67

dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go, dhctl/pkg/operations/converge/runner.go, dhctl/pkg/operations/nodebootstrap.go
1. Disable parallel bootstrapping cloud permanent nodes for VCD.
2. Enable parallel bootstrapping cloud permanent nodes for other providers.
3. Keep the option to disable parallel bootstrap for cloud permanent nodes via env variable: `DHCTL_PARALLEL_CLOUD_PERMANENT_NODES_BOOTSTRAP=false` 
VCD doesn't support parallel VM creation in the same vapp.
Not necessary.
```changes
section: dhctl
type: fix
summary: Disable parallel bootstrapping cloud permanent nodes for VCD.
```
=> [dhctl] disable parallel bootstrapping cloud permanent nodes for vcd

modules/110-istio/crds/ingress-istio.yaml, modules/402-ingress-nginx/crds/ingress-nginx.yaml
This pull request includes changes to the `x-doc-examples` values in the `spec` sections of two YAML files to ensure they are correctly formatted as integers instead of strings. The changes affect multiple instances within the `ingress-istio.yaml` and `ingress-nginx.yaml` files.
Changes to `ingress-istio.yaml`:
* Updated `x-doc-examples` for `httpPort` to use integer values instead of string values.
* Updated `x-doc-examples` for `httpsPort` to use integer values instead of string values.
Changes to `ingress-nginx.yaml`:
* Updated `x-doc-examples` for `httpPort` to use integer values instead of string values. [[1]](diffhunk://#diff-d7ed7f1be5c3c140855d1432c6a4dcb28d1f607d8ff6000ae811c83d5b53dde8L238-R238) [[2]](diffhunk://#diff-d7ed7f1be5c3c140855d1432c6a4dcb28d1f607d8ff6000ae811c83d5b53dd …
=> [docs][istio][ingress-nginx] Fix the display of ports in the examples in the CRDs

docs/documentation/_includes/module-editions.liquid
The information label with the editions has been removed from the global settings page.
Changes include:
* Added a conditional statement to check if the `page.module-kebab-name` contains "/installing/configuration.html" before rendering the informational alert. [[1]](diffhunk://#diff-0aef491f0fc3be1c79963fef942c0d9933668428286c9bfce719a2b47e2e2f7fR8) [[2]](diffhunk://#diff-0aef491f0fc3be1c79963fef942c0d9933668428286c9bfce719a2b47e2e2f7fR77)
```changes
section: docs
type: fix
summary: The information label with the editions has been removed from the global settings page.
```
=> [docs] Remove the information label with the editions from the global settings page

modules/002-deckhouse/templates/webhook-handler/deployment.yaml
Fix for [PR](https://github.com/deckhouse/deckhouse/pull/11830)
```changes
type: fix
summary: fix template for managed k8s
```
=> [node-manager] fix template for managed k8s

modules/035-cni-simple-bridge/images/simple-bridge/werf.inc.yaml
`simple-bridge` crashed as `root` couldn’t access `python3.11` owned by `deckhouse`. This fixes it.
Fixed Python permissions for `simple-bridge` by setting `python3.11` owner to `root`.
```shell
[root@a14057133204-1-con-1-30-master-0 root]# ls -l usr/bin
total 45304
-rwxr-xr-x. 1 root root  5740368 Jan 29 20:43 curl
-rwxr-xr-x. 1 root root  2623744 Jan 29 20:54 jq
lrwxrwxrwx. 1 root root       10 Jan 29 20:35 python3 -> python3.11
lrwxrwxrwx. 1 root root       17 Jan 29 20:35 python3-config -> python3.11-config
-rwx------. 1 root root 37977920 Jan 29 20:35 python3.11
-rwxr-xr-x. 1 root root     3021 Jan 29 20:35 python3.11-config
-rwxr-xr-x. 1 root root    39328 Nov  6  2023 tee
[root@a14057133204-1-con-1-30-master-0 root]# ls -l usr/lib
total 4
drwxr-xr-x. 38 root root 4096 Jan 29 20:35 …
```
=> [simple-bridge] fix permissions

modules/402-ingress-nginx/docs/internal/validations_cve_fixup.sh
This pr updates modules/402-ingress-nginx/docs/internal/validations_cve_fixup.sh script to make it compatible with earlier versions of Deckhouse (v1.58 for example).
Current versions of the script doesn't work for v1.63- as the shell-operator images for these versions have no tini binary.
Also, the way of getting shell-operator image's name and hash has been streamlined.
```changes
type: chore
summary: Ingress validation CVE fixer script is updated to support earlier versions of Deckhouse.
```
=> [ingress-nginx] update ingress cve fixer script

deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_release.go, deckhouse-controller/pkg/controller/module-controllers/release/controller.go, deckhouse-controller/pkg/controller/moduleloader/sync.go, deckhouse-controller/pkg/controller/moduleloader/testdata/releases/release.yaml
Add list option to function [restoreAbsentModulesFromReleases](https://github.com/deckhouse/deckhouse/blob/e88df4aea92534c31db006eacc6edfee8c4eb9fc/deckhouse-controller/pkg/controller/moduleloader/sync.go#L167) to find only releases with label `status: deployed`
We already have labels on every deployed release.
This optimization can make our function faster and clearer.
```changes
type: feature
summary: added list option to restoreAbsentModulesFromReleases to find releases with label status deployed
```
=> [deckhouse-controller] module loader add list option to get releases with label status deployed

docs/documentation/_data/sidebars/main.yml, modules/015-admission-policy-engine/docs/FAQ.md, modules/015-admission-policy-engine/docs/FAQ_RU.md
Added SecurityPolicies examples that match our baseline and restricted lists from [Kubernetes PSS](https://kubernetes.io/docs/concepts/security/pod-security-standards/) with a deployment guide to FAQ
We need a way to allow some existing policies without just enabling `privileged` policy. Examples and the guide should help with that.
```changes
type: chore
summary: Added SecurityPolicies examples for baseline and restricted policy standards.
```
=> [admission-policy-engine][docs] Add SecurityPolicies examples that match PSS

modules/015-admission-policy-engine/templates/validatingwebhookconfiguration.yaml
Exclude the virtualization service accounts group from the validation of the admission policy engine.
Specific service accounts were provided to be excluded from the validation. The provided service accounts are insufficient. To avoid updating the sa list every time, it was decided to exclude by group "system:serviceaccounts:d8-virtualization".
Due to this, the core functionality of virtualization doesn't work: migration of virtual machines created in the project
```changes
type: fix
summary: exclude virtualization from the validation of the admission policy engine
```
=> fix: exclude virtualization from the validation of the admission policy engine

modules/015-admission-policy-engine/charts/constraint-templates/tests/allowed-selinux/constraint_pss_baseline.yaml, modules/015-admission-policy-engine/charts/constraint-templates/tests/allowed-sysctls/constraint_pss_baseline.yaml, modules/015-admission-policy-engine/templates/policies/pod-security-standards/baseline/constraint.yaml
New baseline policies were added in Pod Security Standards https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline
```
SELinux
- container_engine_t (since Kubernetes 1.31)
Sysctl
- net.ipv4.ip_local_reserved_ports (since Kubernetes 1.27)
- net.ipv4.tcp_keepalive_time (since Kubernetes 1.29)
- net.ipv4.tcp_fin_timeout (since Kubernetes 1.29)
- net.ipv4.tcp_keepalive_intvl (since Kubernetes 1.29)
- net.ipv4.tcp_keepalive_probes (since Kubernetes 1.29)
```
<br class="Apple-interchange-newline">
We should keep Pod Security Standards policies up to date
```changes
type: chore
summary: Added pod security standards policies that were added since 1.27
```
=> [admission-policy-engine] Add new baseline policies

deckhouse-controller/pkg/controller/chroot_object_desctiptors.go, deckhouse-controller/pkg/controller/chroot_object_desctiptors_linux.go, deckhouse-controller/pkg/controller/controller.go, deckhouse-controller/pkg/controller/deckhouse-release/check_release.go, go_lib/dependency/cr/cr.go, go_lib/dependency/dependency_test.go
Add more verbose errors to registry client
Add set metric d8_updating_is_failed to 0 if update was complete
Fix compilation on darwin
Fix dependency tests naming to resolve this testing errors
```
go_lib/dependency/dependency_test.go:38:1: ExampleMockedHTTPClient refers to unknown identifier: MockedHTTPClient
go_lib/dependency/dependency_test.go:54:1: ExampleK8sClient refers to unknown identifier: K8sClient
go_lib/dependency/dependency_test.go:70:1: ExampleVersionedK8sClient refers to unknown identifier: VersionedK8sClient
go_lib/dependency/dependency_test.go:88:1: ExampleEtcdClient refers to unknown identifier: EtcdClient
FAIL    github.com/deckhouse/deckhouse/go_lib/dependency [build failed]
```
```changes
type: fix
summary: add verbosity to registry client …
```
=> [deckhouse-controller] Add verbose to registry client, fix tests and darwin compile

modules/160-multitenancy-manager/crds/doc-ru-projects.yaml, modules/160-multitenancy-manager/crds/projects.yaml, modules/160-multitenancy-manager/images/multitenancy-manager/src/apis/deckhouse.io/v1alpha2/project.go, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/client.go, modules/160-multitenancy-manager/images/multitenancy-manager/src/internal/helm/renderer.go
It gets rid of resource labels/annotations
This mechanism will be replaced.
```changes
type: chore
summary: Get rid of resource labels/annotations.
```
=> [multitenancy-manager] get rid of resource labels/annotations

modules/101-cert-manager/crds/crd-certificaterequests.yaml, modules/101-cert-manager/crds/crd-certificates.yaml, modules/101-cert-manager/crds/crd-challenges.yaml, modules/101-cert-manager/crds/crd-clusterissuers.yaml, modules/101-cert-manager/crds/crd-issuers.yaml, modules/101-cert-manager/crds/crd-orders.yaml, modules/101-cert-manager/crds/pull_crds.sh, modules/101-cert-manager/docs/README.md, modules/101-cert-manager/docs/README_RU.md, modules/101-cert-manager/images/cert-manager-acme-solver/werf.inc.yaml, modules/101-cert-manager/images/cert-manager-cainjector/werf.inc.yaml, modules/101-cert-manager/images/cert-manager-controller/patches/001-certificate_owner_ref.patch, modules/101-cert-manager/images/cert-manager-controller/patches/README.md, modules/101-cert-manager/images/cert-manager-controller/werf.inc.yaml, modules/101-cert-manager/images/cert-manager-webhook/werf.inc.yaml
Bump version of cert-manager component up to `v1.17.1`.
Cert-manager has accumulated a lot of bug fixes that are recommended to be included in Deckhouse.
```changes
type: feature
summary: Bump cert-manager version up to 1.17.1. This fixes acme confirmation for cloudflare provider.
```
=> Backport: [cert-manager] Bump cert-manager components to 1.17.1

dhctl/pkg/operations/bootstrap/steps.go, go_lib/registry-packages-proxy/proxy/proxy.go
Added a call to proxy.Stop after the bootstrap context was canceled. 
This should fix the error: failed to start registry packages proxy: Failed to listen registry proxy socket: listen tcp 127.0.0.1:5444: bind: address already in use
The dhctl server must be able to correctly clean up all resources generated during its run, as its lifetime exceeds that of a single (bootstrap, destroy, etc) operation.
```changes
section: dhctl
type: fix 
summary: improve resources cleanup after bootstrap
```
=> [dhctl] fix(dhctl-for-commander-stop-registry-proxy): stop registry proxy after bootstrap

dhctl/cmd/dhctl/commands/session.go, dhctl/cmd/dhctl/main.go
This pr allow dhctl session bind tcp port proxy on local spot to ssh tunnel and generate kubeconfig ~/.kube/config.
When successful bootstrap just done this help use local kubectl without  connecting to a control-plane node via SSH.
resolv [issue](https://github.com/deckhouse/deckhouse/issues/2842)
```changes
section: dhctl
type: feature
summary: add local kubeconfig k8s proxy
impact_level:  default
```
=> [dhctl] Add local kubeconfig k8s proxy

modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/deprecated-resources.json
This PR allow to set multi check boxes and choose several k8s versions.
This allow to see deprecated APIs resources on several k8s versions check boxes.
resolve [3657](https://github.com/deckhouse/deckhouse/issues/3657) issue.
```changes
type: feature
summary: add multi set desired K8s version
```
=> [monitoring-kubernetes-control-plane] Add multi set desired K8s version

dhctl/pkg/operations/bootstrap/post-script.go, dhctl/pkg/operations/bootstrap/steps.go, dhctl/pkg/operations/destroy/destroy.go, dhctl/pkg/system/node/interface.go, dhctl/pkg/system/node/local/command.go, dhctl/pkg/system/node/local/script.go, dhctl/pkg/system/node/ssh/cmd/ssh.go, dhctl/pkg/system/node/ssh/frontend/command.go, dhctl/pkg/system/node/ssh/frontend/kube-proxy.go, dhctl/pkg/system/node/ssh/frontend/reverse-tunnel.go, dhctl/pkg/system/node/ssh/frontend/tunnel.go, dhctl/pkg/system/node/ssh/frontend/upload-script.go, dhctl/pkg/system/node/ssh/frontend/waiting.go, go_lib/registry-packages-proxy/proxy/proxy.go
Extended use of context in bashible operations (exec.Command -> exec.CommandContext
```changes
section: dhctl
type: fix
summary: Fix bashible cancellation, use context in commands
```
=> [dhctl] fix(dhctl-for-commander-cancels-bashible-2): fix bashible cancellation

modules/000-common/images/alpine/werf.inc.yaml, testing/library/images_tags_generated.go
Deleted alpine image.
Technical debt.
```changes
type: chore
summary: rm alpine image
impact:
```
=> [common] rm alpine image

docs/site/.helm/templates/20-ingress.yaml, docs/site/.werf/nginx-dev.conf
this mr allow ingress traffic in localtion /downloads/deckhouse-cli-trdl to proxy frontend with nginx configuration in this mr [mr12704](https://github.com/deckhouse/deckhouse/pull/12704)
this partly resolv issue to download d8 bin artifacts through trdl from deckhouse.ru domain, not trrr.flant.dev.
```changes
section: docs
type: feature
summary: add trdl nginx path deckhouse-cli-trdl to ingress docs deckhouse.ru
```
=> [docs] Add trdl nginx path deckhouse-cli-trdl to ingress docs deckhouse.ru

ee/modules/610-service-with-healthchecks/images/artifact/cmd/agent/main.go, ee/modules/610-service-with-healthchecks/images/artifact/patches/README.md
Fix README.md for image patches to solve linter issues.
Note: I had to make some fake code modifications to initiate the DMT Lint job and than revert it.
There are some new linter issues was added after the pr was registered.
```changes
type: fix
summary: Fixed README.md for image patches.
```
=> [service-with-healthchecks] fix README.md for image patches

modules/340-monitoring-custom/hooks/metrics.go
Currently, the deckhouse controller watches for the Prometheus Operator CRs without a `heritage: deckhouse` label in `d8-` prefixed namespaces. All such resources are treated as unsolicited, and the corresponding alert is fired if they exist.
The `observability` module resides in the `d8-observability` namespace and creates the resources during its normal workflow. However, it cannot set the `heritage: deckhouse` label to the created resources. Hence, we have to exclude the namespace from the checks.
This PR prevents the alert for the resources in `d8-observability` namespace from firing.
```changes
section: monitoring-custom
type: chore
summary: exclude d8-observability namespace from D8CustomPrometheusRuleFoundInCluster alert
```
=> [monitoring-custom] Exclude d8-observability namespace from collecting Prometheus Operator CRs

deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go, modules/402-ingress-nginx/hooks/migration/common_test.go, modules/402-ingress-nginx/hooks/migration/migrate_remove_ingress_validation_cve_fixer.go, modules/402-ingress-nginx/hooks/migration/migrate_remove_ingress_validation_cve_fixer_test.go
This pr adds a hook to clean up the resources created to implement the fix for CVE-2025-1974 described [here](https://github.com/deckhouse/deckhouse/blob/main/modules/402-ingress-nginx/docs/internal/VALIDATIONS_CVE_FIXUP_RU.md) from the cluster.
Also, an extra "containers" section is deleted from the deployment manifest of the fix.
The fixer was brought here:
https://github.com/deckhouse/deckhouse/pull/12779
https://github.com/deckhouse/deckhouse/pull/12785
https://github.com/deckhouse/deckhouse/pull/12795
This hook cleans up the resources that might have been created to mitigate CVE-2025-1974 in clusters running Deckhouse versions below v1.67. As Deckhouse isn't exposed to the CVE-2025-1974 since v1.67 and greater, these resources aren't longer needed.
```changes …
```
=> [ingress-nginx] add cve fixer cleanup hook

modules/300-prometheus/crds/customalertmanager.yaml, modules/300-prometheus/crds/doc-ru-customalertmanager.yaml
Add `required` setting for `spec.internal.route` in CustomAlertManager CRD
Root route is required by prometheus-operator:
```
level=error ts=2024-10-15T13:51:39.125341794Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="sync \"d8-monitoring/alerts-email\" failed: provision alertmanager configuration: failed to initialize from global AlertmangerConfig: root route must exist"
```
```changes
type: chore
summary: Added required parameter for `internal.route` spec in CustomAlertManager CRD.
```
=> [prometheus] Require route in internal spec of CustomAlertManager

modules/500-cilium-hubble/templates/relay/deployment.yaml
Fixed nesting of the debugLogging parameter in the helm chart of the ciliumHubble module
In the current version, the debugLogging option is ignored in the helm chart due to incorrect nesting of values
As a result, the debugLogging parameter in the cilium-hubble module settings will be included in helm chart render and enable debug logging mode for hubble
```
type: fix
summary: Fixed nesting of the debugLogging parameter in the helm chart of the ciliumHubble module
```
=> [cni-cilium] Fix nesting of the debugLogging parameter in the helm chart of the ciliumHubble module

modules/021-cni-cilium/images/bin-cilium/patches/006-add-pod-prioroty-managment.patch
Add restoring/hiding network access for cilium endpoint(cep) when higher/lower priority cep was removed/added.
In case VM migration if virtualization controller incorrectly managment priority labels for VM pods - new VM pod may have not network access in cluster. For this case cilium must restore network access for low priority VM pod when more priority VM pod was completed and its cep removed.
```changes
type: fix
summary: Added restoring/hiding network access to cilium endpoint (cep) when higher/lower priority cep was removed/added.
```
=> [cilium] restoring/hiding network access for cep when higher/lower priority cep was removed/added

Makefile, docs/site/.werf/nginx-dev.conf, docs/site/.werf/nginx.conf
This pull request includes a change to the `docs/site/.werf/nginx-dev.conf` file to improve caching configuration.
* [`docs/site/.werf/nginx-dev.conf`](diffhunk://#diff-782094ed4212f4e56e86e3119bdc6b2cec16c66914304440d2e927ea006b8bfcR12-R13): Added `proxy_cache_path` directive to set up caching with a specified location, size, and inactivity period.
```changes
```
=> [docs] FIx local docimentation build and run

.github/workflow_templates/deploy-channel.multi.yml, .github/workflows/deploy-alpha.yml, .github/workflows/deploy-beta.yml, .github/workflows/deploy-early-access.yml, .github/workflows/deploy-rock-solid.yml, .github/workflows/deploy-stable.yml
Merge different release date labels for different release channels into one.
```changes
section: ci
type: chore
summary: Merge release date labels.
```
=> [ci] Merge release date labels

dhctl/pkg/kubernetes/actions/deckhouse/pod.go, dhctl/pkg/kubernetes/actions/manifests/manifests.go
During the boot process, the server can perform a graceful reboot with shutdown -r -t 5. After the reboot, the deckhouse pod may be in Error state, which blocks further boot process.
This solves the cluster bootstrap problem, in particular the problem occurs if the `floppy` module has been loaded on the server
```changes
section: dhctl
type: fix
summary: cleanup failed/completed deckhouse pods due to bootstrap
impact: 
```
=> [dhctl] cleanup failed/completed deckhouse pods due to bootstrap

deckhouse-controller/pkg/controller/deckhouse-release/check_release.go, deckhouse-controller/pkg/controller/deckhouse-release/controller.go, deckhouse-controller/pkg/controller/deckhouse-release/controller_test.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/existed-release-suspended.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-canary-release-wave-0.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-canary-release-wave-4.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-new-deckhouse-image.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/image-hash-not-changed.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/inherit-release-cooldown.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/new-release-suspended.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/patch-release-has-own-cooldown.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-canary.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-cooldown.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-disruptions.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-requirements.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-with-changelog.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/resume-suspended-release.yaml, dhctl/pkg/kubernetes/actions/deckhouse/install.go, dhctl/pkg/operations/bootstrap/steps.go
Add patch restored release status with Deployed Phase
Remove old deckhouse-controller deploy when only one release in cluster (because of restored release by check-release)
Remove old dhctl deckhouse-release create method (because of restored release by check-release)
Remove useless test for deckhouse-controller
Move registry work inside check-release after restore release
Add utils tests (parsing deckhouse registry secret)
Backports #12858
Now we can restore deckhouse-release without dhctl. We have an check-release process which restore release automatically and makes it "Deployed" phase.
```
NAME      PHASE      TRANSITIONTIME   MESSAGE
v1.69.0   Pending   12m              Release object was restored
```
```
NAME      PHASE      TRANSITIONTIME   MESSAGE
v1.69.0   Deployed   12m …
```
=> [deckhouse-controller] 1.68 feature/restore release with dc only

modules/040-node-manager/hooks/handle_node_templates.go
Ignore label `l2-load-balancer.network.deckhouse.io/member` when executing the `handle_node_templates` hook.
Have race condition with set/delete labels between hooks `handle_node_template.go` and  `380-metallb/hooks/node_membership_handler.go`
Fix race condition between hooks.
```changes
type: fix
summary: handle_node_template hook ignore metallb label
```
=> [node-manager] handle_node_template hook ignore metallb label

candi/version_map.yml, modules/040-node-manager/images/cluster-autoscaler/patches/1.29/001-go-mod.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.29/README.md
pr caused regression so we roll back some of the changes.
https://github.com/deckhouse/deckhouse/pull/12024
1.68
1.69
```changes
type: fix 
summary: partial rollback of changes in images cluster-autoscaler
impact: 
```
=> [node-manager] partial rollback of changes in images cluster-autoscaler

ee/modules/030-cloud-provider-vcd/images/vcd-csi-plugin/patches/001-add-iops-calculation.patch, ee/modules/030-cloud-provider-vcd/images/vcd-csi-plugin/patches/002-go-mod.patch
Improvements to `CSI` plugin patches:
- Bumped `github.com/vmware/go-vcloud-director/v2` to version `v2.26.1`
- Enhanced error handling  
The patch uses the `GetStorageProfileByHref` function, which is incompatible with the latest version of the `VCD` API. To fix this, we need to upgrade the package `github.com/vmware/go-vcloud-director/v2` to a version that includes the updated implementation of this function.
```changes
type: fix
summary: Fix creation of `PersistentVolumeClaim`.
```
=> [vcd] Fix `CSI` plugin patches

docs/site/.helm/values.yaml, docs/site/backends/docs-builder-template/i18n/en.yaml, docs/site/backends/docs-builder-template/i18n/ru.yaml, docs/site/backends/docs-builder-template/layouts/partials/module-resources.html, docs/site/backends/docs-builder-template/layouts/partials/openapi/format-configuration.html, docs/site/backends/docs-builder/internal/docs/service.go, docs/site/backends/docs-builder/internal/docs/upload.go, docs/site/backends/registry-modules-watcher/internal/backends/pkg/registry-scanner/process.go
Add displaying conversions for external modules.
```changes
section: docs
type: chore
summary: Add displaying conversions for external modules.
```
=> [docs] Add displaying conversions for external modules

dhctl/pkg/kubernetes/actions/entity/node.go, dhctl/pkg/operations/bootstrap/checks.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
Waiting for become ready first master node
If we will add another cloud permanent nodes, we will have error for connection to bashible api server because first masteer node is not ready and bashible api server pod is in the Pending status
```changes
section: dhctl
type: feature
summary: Add waiting for become ready first master node
```
=> [dhctl] Add waiting for become ready first master node

.werf/defines/parse-base-images-map.tmpl, Makefile, candi/README.md, candi/base_images.yml, werf.yaml
This PR is the first step of the move from images_versions.yml to use external base images library.
This PR adds images from external base_images.yml file and adds artifacts for every base image.
Example of base_images.yml:
```yaml
REGISTRY_PATH: registry.deckhouse.io/base_images
base/distroless: "sha256:f2ac3320ce677484d7aef4608f99ddf0055d8907cc3509f8cccc8513f314c31a" # fromImage: builder/scratch
base/nginx-static: "sha256:28a844d4ff777dc704d3808bdd1240108315f4d1ed1668e762627b9c4ddc8d66" # fromImage: base/distroless
base/python: "sha256:432f19eaeb5035ea38e3fbc721576e6802c679fd0fb7a8e6d441fdb36944c180" # fromImage: base/distroless
builder/alpine: "sha256:92adb9e8a387c645ba4eeedb08f9a6de0583c5d1d496bf9c9b3a89fe963a6a06" # from: alpine:3.20.6
builder/alt: …
```
=> Add base images from external base images repo

candi/bashible/common-steps/all/002_create_static_node_cleanup_script.sh.tpl
Add step to cleanup_static_node.sh to remove all users created form NodeUser manifests
We should clean up all the artifacts created by deckhouse by cleaning up static node
```changes
section: candi
type: feature
summary: Deleting all users created by deckhouse from NodeUser manifests.
```
=> [candi] Static node cleanup: remove all users created from NodeUser manifests

candi/bashible/common-steps/all/064_configure_kubelet.sh.tpl
1. dynamic_memory_sizing function uses the global variable total_memory, calling the function may result in unexpected behavior.
2. LC_ALL can affect awk, it causes an error in calculations
```shell
apt -y install locales-all > /dev/null
total_memory=$(free -m|awk '/^Mem:/{print $2}')
echo $total_memory 0.02 | awk '{print $1 * $2}'
30
echo $total_memory 0.02 | LC_ALL=ru_RU.UTF-8 awk '{print $1 * $2}'
0 
```
In some rare cases, this will cause `memory.available` prop  to become “0” in the kubelet configuration. Because of this kubelet crashes.
```changes
section: candi
type: fix
summary: bashible configure-kubelet step fix
impact:
```
=> [candi] bashible configure-kubelet step fix

docs/documentation/_data/deckhouse-alerts.yml, modules/500-openvpn/hooks/renew_ca_cert.go, modules/500-openvpn/hooks/renew_ca_cert_test.go, modules/500-openvpn/monitoring/grafana-dashboards/ovpn-admin/ovpn-admin.json, modules/500-openvpn/monitoring/prometheus-rules/ovpn-admin.yaml, modules/500-openvpn/templates/monitoring.yaml, modules/500-openvpn/templates/openvpn/podmonitor.yaml, modules/500-openvpn/templates/openvpn/statefulset.yaml
Added alerts notifying about expiring server certificate and CA certificate validity period, as well as about expired client certificates. Added [dashboard](https://github.com/palark/ovpn-admin/blob/master/dashboard/ovpn-admin.json) for Grafana with more detailed information. Also hook tracking server certificate validity period, after which all server certificates will be reissued and client certificates will be removed.
<details>
<summary>📸 Screenshots (Click to expand)</summary>
1. ![Screenshot 1](https://github.com/user-attachments/assets/07d0100a-4fba-4743-9357-a75694931089)  
2. ![Screenshot 2](https://github.com/user-attachments/assets/837af514-2c22-49a3-bd03-196c2855c7ab)  
3. ![Screenshot 3](https://github.com/user-attachments/assets/893cda43-9a59-46ba-a435-c4fbf104da3b) …
=> [ovpn] renew ca

docs/site/.werf/nginx-dev.conf, docs/site/.werf/nginx.conf
This pull request includes changes to the Nginx configuration files to add a new redirect for the `deckhouse-cli-trdl` endpoint. The most important changes are as follows:
* [`docs/site/.werf/nginx-dev.conf`](diffhunk://#diff-782094ed4212f4e56e86e3119bdc6b2cec16c66914304440d2e927ea006b8bfcR88-R91): Added a new location block to redirect `/downloads/deckhouse-cli-trdl` to `/products/kubernetes-platform/documentation/v1/deckhouse-cli/`.
* [`docs/site/.werf/nginx.conf`](diffhunk://#diff-637da0fa421ec0ecce777fd22d8da392873e8dc1599c2c7527a54bec65fe834bR69-R72): Added a similar location block to redirect `/downloads/deckhouse-cli-trdl` to `/products/kubernetes-platform/documentation/v1/deckhouse-cli/`.
```changes
section: docs
type: fix
summary: Add redirect to d8-cli from tuf repo page. …
```
=> [docs] Add redirect to d8-cli from tuf repo page

.github/workflow_templates/build-and-test_dev.yml, .github/workflow_templates/build-and-test_pre-release.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml
Allow DMT lint to run on PRs that have only markdown changes.
As DMT linter checks README.md files, it is necessary to run it on commits changing only markdown.
```changes
section: ci
type: fix
summary: Allow DMT lint to run on only markdown changes.
```
=> [ci] Allow DMT lint to run on markdown changes

candi/bashible/common-steps/all/098_update_node_annotations.sh.tpl, modules/040-node-manager/images/capi-controller-manager/patches/002-search-node-by-provider-id-annotation.patch, modules/040-node-manager/images/capi-controller-manager/patches/README.md, modules/040-node-manager/images/caps-controller-manager/src/api/deckhouse.io/v1alpha1/staticinstance_annotations.go, modules/040-node-manager/images/caps-controller-manager/src/api/deckhouse.io/v1alpha1/staticinstance_webhook.go, modules/040-node-manager/images/caps-controller-manager/src/internal/client/adopt.go, modules/040-node-manager/images/caps-controller-manager/src/internal/client/bootstrap.go, modules/040-node-manager/images/caps-controller-manager/src/internal/client/client.go, modules/040-node-manager/images/caps-controller-manager/src/internal/controller/deckhouse.io/staticinstance_controller.go, modules/040-node-manager/images/caps-controller-manager/src/internal/controller/infrastructure/staticmachine_controller.go, testing/cloud_layouts/Static/resources.tpl.yaml, testing/cloud_layouts/script.sh
To fix static node adoption, the following changes have been made:  
- Added a `bashible` step that assigns the `node.deckhouse.io/provider-id` annotation to nodes with a `static://` provider ID
- Implemented special logic in the `CAPS` controller for adopting static nodes
- Applied a patch to the Cluster API Controller to enable node searches using the `node.deckhouse.io/provider-id` annotation
In the previous implementation, a `StaticInstance` with the `static.node.deckhouse.io/skip-bootstrap-phase` annotation was cleaned up and moved to a failed state.
```changes
section: candi
type: feature
summary: Added a `bashible` step that assigns the `node.deckhouse.io/provider-id` annotation to nodes with a `static://` provider ID
---
type: fix …
```
=> [caps] Rewrite `StaticInstance` adoption

ee/candi/cloud-providers/openstack/layouts/standard/base-infrastructure/main.tf
bastion's root_disk_size doesn't have a default value though it is not a required value
```changes
type: fix
summary: fix terraform bastion default root_disk_size
```
=> [cloud-provider-openstack] fix terraform bastion default root_disk_size

dhctl/pkg/config/base.go, dhctl/pkg/config/connection_test.go, dhctl/pkg/config/deckhouse_config_test.go, dhctl/pkg/config/load.go, dhctl/pkg/config/validation_rules_test.go, dhctl/pkg/config/validation_test.go, dhctl/pkg/operations/check/check_test.go, dhctl/pkg/operations/check/destructive_change_id_test.go, dhctl/pkg/operations/converge/controller/node_group_controller_test.go, dhctl/pkg/server/pkg/fsm/fsm_test.go, dhctl/pkg/server/pkg/logger/writer_test.go, dhctl/pkg/server/pkg/requests_counter/requests_counter_test.go, dhctl/pkg/util/input/yaml_test.go
Add deny additional properties for validation schema eg module config
Some module config was allowed with additional fields which not in the schema
```changes
section: dhctl
type: fix
summary: Add deny additional properties for validation schema eg module config
```
=> [dhctl] Add deny additional properties for validation schema eg module config

modules/040-node-manager/requirements/check.go, modules/040-node-manager/requirements/check_test.go, release.yaml
This PR adds new UnmetCloudConditions check, depends on requiement from https://github.com/deckhouse/deckhouse/pull/12530
new versions of AWS TF plugin require additional roles to be able to be executed. we should block the update until user adds this roles to SA. See https://github.com/deckhouse/deckhouse/pull/11546
```changes
type: feature
summary: enable UnmetCloudConditions check
```
=> [node-manager] UnmetCloudConditions check

ee/be/modules/350-node-local-dns/images/stale-dns-connections-cleaner/go.sum, ee/be/modules/350-node-local-dns/images/stale-dns-connections-cleaner/main.go, ee/be/modules/350-node-local-dns/images/stale-dns-connections-cleaner/werf.inc.yaml, ee/be/modules/350-node-local-dns/templates/stale-dns-connections-cleaner/daemonset.yaml
Previously, stale-dns-connections-cleaner was updated to run as non-root user and its binary was updated to use file capabilities. In result the capabilities weren't set in the final image because they get deleted when the file is copied from one image to another:
```
/tmp/1 cap_sys_chroot,cap_sys_admin,cap_mknod=ep
```
Thus, this pr reverts previous changes, making stale-dns-connections-cleaner run as root.
Also, the scan interval has been decreased from 30 to 10 seconds to make it react faster.
Without root permissions and file capabilities set, stale-dns-connections-cleaner doesn't have enough permissions for deleting stale dns sockets. It can affect ingress-nginx controllers running in the cluster when node-local-dns/kube-dns pods are created.
In latest 1.68.x patch release almost all …
=> [node-local-dns] fix dns-stale-connections-cleaner security context and file permissions

.github/ci_templates/build.yml, .github/ci_templates/tests.yml, .github/render-workflows.sh, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml, candi/base_images.yml
Update golang in workflows to 1.24. 
Use updated base_images.yml(v0.4.2) with updated golang to 1.24.
This is part of move build to use of external base images repo and use of more recent golang version.
```changes
section: ci
type: chore
summary: Update golang in workflows to 1.24. Use updated base_images.yml(v0.4.2) with updated golang to 1.24.
```
=> [ci] update golang in workflows to 1.24. Use base_images.yml.

deckhouse-controller/pkg/controller/module-controllers/config/controller.go
Fix handler for the global config
An error occurred [here](https://github.com/deckhouse/deckhouse/pull/12686/files#diff-c639744b3e8b463b84bbb742767ecad92145915d9d33dd028c02db1902359956R186-R188), missed, that config could be global
```changes
type: fix
summary: Fix runtime handling for the global config.
```
=> Fix global module config handling

candi/bashible/common-steps/all/002_add_system_proxy.sh.tpl
remove system-wide proxy from `/etc/systemd/system.conf.d/`
We use systemd to run `kubelet.service`. Kubelet usually does not require proxy, but in some cases it may be necessary, so we add proxy directly to `kubelet.service`
fix process of updating modules via proxy in some rare cases
```changes
type: fix
summary: remove system-wide proxy from `/etc/systemd/system.conf.d/`
```
=> [node-manager] delete cluster-wide proxy from systemd

release.yaml
Backport #12957 
This PR enables UnmetCloudConditions check (introduced in https://github.com/deckhouse/deckhouse/pull/12845 and https://github.com/deckhouse/deckhouse/pull/12530)
new versions of AWS TF plugin require additional roles to be able to be executed. we should block the update until user adds this roles to SA. See https://github.com/deckhouse/deckhouse/pull/11546
```changes
type: feature
summary: enable UnmetCloudConditions check
impact: release upgrade will be blocked on AWS-based clusters where SA doesn't have DescribeAddressesAttribute and DescribeInstanceTopology roles. They are required for new Terraform AWS Provider version. 
```
=> [node-manager] enable UnmetCloudConditions check

global-hooks/migrate/delete_deckhouse_epslices.go, modules/002-deckhouse/hooks/migrate/delete_deckhouse_epslices.go
It deletes useless deckhouse epslices.
Deckhouse epslices was created manually before 1.69, now it is created by kubernetes. So we need to delete the stale resource.
It can cause connectivity problem.
Before:
```
root@dev-master-0:~# k get endpointslices.discovery.k8s.io -n d8-system
NAME                                      ADDRESSTYPE   PORTS            ENDPOINTS         AGE
conversion-webhook-handler-7hsmn          IPv4          9681             10.111.0.201      411d
deckhouse                                 IPv4          4222,4223,9652   192.168.199.201   411d
deckhouse-leader-4ccfq                    IPv4          4222,4223        192.168.199.201   42d
deckhouse-tools-6gng5                     IPv4          8080             10.111.2.18       223d
```
After:
```
root@dev-master-0:~# …
```
=> [deckhouse] delete deckhouse epslices

dhctl/pkg/server/rpc/dhctl/abort.go, dhctl/pkg/server/rpc/dhctl/bootstrap.go
Fixed configuration preparation for bootstrap and bootstrap abort of a cluster. Now, empty config files are ignored. This bug was introduced here: https://github.com/deckhouse/deckhouse/pull/12400
Installation error log caused by the bug:
```
Config document validation failed: document must contain "kind" and "apiVersion" fields:
apiVersion:
kind:
data:
1 ---
```
Currently, bootstrap and abort of clusters in Commander do not work if they have an empty configuration: ClusterConfig, InitConfig, ProviderSpecificClusterConfig, InitResources.
To fix cluster bootstrap functionality.
```changes
section: dhctl
type: fix
summary: fix bootstrap and abort config preparation
```
=> [dhctl] fix(dhctl-for-commander): skip empty config files in bootstrap and abort

ee/be/modules/350-node-local-dns/images/stale-dns-connections-cleaner/main.go, ee/be/modules/350-node-local-dns/images/stale-dns-connections-cleaner/werf.inc.yaml, ee/be/modules/350-node-local-dns/templates/stale-dns-connections-cleaner/daemonset.yaml
Backports stale dns connection cleaner [fix](https://github.com/deckhouse/deckhouse/pull/12944) to the v1.68 release brach.
There are some conflicts between the fix and the 1.68 release branch there that have to be resolved manually.
```changes
type: chore
summary: Stale dns connection cleaner fix is backported to the v1.68 release branch.
```
=> [node-local-dns] backport dns connection cleaner fix to 1.68

.github/ci_templates/build.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml
In the v4 version actions/setup-go enable caching by default https://github.com/actions/setup-go?tab=readme-ov-file#v4
This activity try to download and extract all dependencies for go.mod in the single archive.
Slow running `go generate` job in build workflow
```changes
section: ci
type: fix 
summary: Disable cache saving for `actions/setup-go@v5` when running go generate
```
=> [ci] Disable cache saving for `actions/setup-go@v5` when running go generate

modules/300-prometheus/docs/FAQ.md, modules/300-prometheus/docs/FAQ_RU.md
The layout of the alert on the site has been corrected
```changes
section: docs
type: chore
summary: the layout of the alert on the site has been corrected
```
=> [docs] Fix a warning about using alerts in the dashboard

docs/documentation/pages/admin/configuration/access/AUTHENTICATION.md, docs/documentation/pages/admin/configuration/access/AUTHENTICATION_RU.md
New DKP documentation translate — authentication.
```changes
section: docs
type: chore
summary: New DKP documentation translate — authentication.
```
=> [docs] New DKP documentation translate — authentication

ee/modules/030-cloud-provider-vcd/hooks/legacy_mode.go, ee/modules/030-cloud-provider-vcd/openapi/values.yaml, ee/modules/030-cloud-provider-vcd/templates/capcd-controller-manager/deployment.yaml, ee/modules/030-cloud-provider-vcd/templates/cloud-controller-manager/deployment.yaml, ee/modules/030-cloud-provider-vcd/templates/cloud-data-discoverer/deployment.yaml, ee/modules/030-cloud-provider-vcd/templates/csi/controller.yaml, ee/modules/030-cloud-provider-vcd/templates/csi/storage-classes.yaml
Add a hook to set `legacyMode` based on the detected `VCD API` version:
- Add `.Values.cloudProviderVcd.internal.legacyMode` value to control the selection of container images based on either `legacy` or `latest` `VCD API` versions.
- Set `.Values.cloudProviderVcd.internal.legacyMode` to the value of `VCDClusterConfiguration.legacyMode` if the field is present.  
- If `VCDClusterConfiguration.legacyMode` is not set, assign `.Values.cloudProviderVcd.internal.legacyMode` to `true` when the `VCD API` version is below `37.2`.
Add support for setting `legacyMode` either statically (for new clusters) or dynamically (for existing clusters).
```changes
type: fix
summary: Add a hook to set `legacyMode` based on the detected `VCD API` version
```
=> [cloud-provider-vcd] Add a hook to set `legacyMode` based on the `VCD API` version

modules/015-admission-policy-engine/.dmtlint.yaml, modules/015-admission-policy-engine/module.yaml, modules/031-ceph-csi/.dmtlint.yaml, modules/040-node-manager/module.yaml, modules/045-snapshot-controller/module.yaml, modules/101-cert-manager/module.yaml, modules/110-istio/module.yaml, modules/140-user-authz/module.yaml, modules/150-user-authn/.dmtlint.yaml, modules/200-operator-prometheus/module.yaml, modules/300-prometheus/.dmtlint.yaml, modules/300-prometheus/module.yaml, modules/400-descheduler/.dmtlint.yaml, modules/400-descheduler/module.yaml, modules/402-ingress-nginx/.dmtlint.yaml, modules/460-log-shipper/.dmtlint.yaml, modules/460-log-shipper/module.yaml, modules/500-cilium-hubble/module.yaml, modules/810-documentation/module.yaml, tools/dmt-lint.sh
update dmt lint to 0.1.14
updating the linter functionality
```changes
section: tools
type: feature
summary: update DMT version to 0.1.14
```
=> [tools] update DMT version to 0.1.14

ee/be/modules/350-node-local-dns/images/stale-dns-connections-cleaner/go.sum, ee/be/modules/350-node-local-dns/images/stale-dns-connections-cleaner/main.go, ee/be/modules/350-node-local-dns/images/stale-dns-connections-cleaner/werf.inc.yaml, ee/be/modules/350-node-local-dns/templates/stale-dns-connections-cleaner/daemonset.yaml
Backports stale dns connection cleaner https://github.com/deckhouse/deckhouse/pull/12944 to the v1.68 release brach.
There are some conflicts between the fix and the 1.68 release branch there that have to be resolved manually.
```changes
type: chore
summary: Stale dns connection cleaner fix is backported to the v1.69 release branch.
```
=> [node-local-dns] backport stale dns connections cleaner fix to v1.69

modules/462-loki/hooks/calculate_storage_capacity.go, modules/462-loki/hooks/calculate_storage_capacity_test.go
When Loki uses emptyDir (no PVC found in the cluster) and the `diskSizeGigabytes` setting is not explicitly set in the ModuleConfig, the storage capacity hook enters error state and halts the Deckhouse controller modules reconciliation loop.
This PR fixes the bug described above.
Even though the emptyDir use is rear and there is a workaround available, It's good to have this bug fixed in the nearest patch release.
```changes
section: loki
type: fix
summary: fix storage capacity calculator hook for Loki
impact: fixes the bug introduced in v1.69.0
```
=> [loki] Fix storage capacity calculation hook

deckhouse-controller/pkg/controller/deckhouse-release/controller.go
It clears deployed releases`s message.
Message stuck, we should clear it.
```changes
type: fix
summary: Clear deployed release`s message.
```
=> [deckhouse] clear deployed message

ee/modules/500-operator-trivy/templates/trivy-server.yaml
It adds proxy env for operator-trivy to download db in env with configured proxy.
Closes #12983
Trivy cannot download db in env with configured proxy.
```changes
type: fix
summary: Add proxy env variables support to the trivy server.
```
=> [operator-trivy] add proxy env

candi/bashible/common-steps/all/092_set_cgroup_type.sh.tpl
this mr add step label node from cgroup version on current node 
```
stat -fc %T /sys/fs/cgroup/
For cgroup v2, the output is cgroup2fs.
For cgroup v1, the output is tmpfs.
kubectl describe no master | grep cgroup
node.deckhouse.io/cgroup=cgroup2fs
curl deckhouse.d8-system.svc.cluster.local:8080/metrics/hooks | grep cgroup
d8_telemetry_node_cgroup{hook="dev/hooks/cgroup_metrics.py",module="flant-integration",type="cgroup2fs"} 1
d8_telemetry_node_cgroup{hook="dev/hooks/cgroup_metrics.py",module="flant-integration",type="tmpfs"} 0
d8_telemetry_node_cgroup{hook="dev/hooks/cgroup_metrics.py",module="flant-integration",type="unknown"} 0
```
this partly resolve this [mr](https://fox.flant.com/deckhouse/flant-integration/-/merge_requests/31)
```changes
section: candi
type: feature
summary: add …
```
=> [bashible] Add cgroup version label on node step bashible

modules/300-prometheus/templates/grafana/deployment-v10.yaml
Grafana uses a SQLite database as a backend for storing data. There is only one database file, and it appears that  Grafana executes transactions from the different code parts concurrently, hence leading to high database access contention. If some part of the code cannot take an exclusive lock, it fails and retries. When there are a lot of dashboards, alerts, etc., this particular code may exhaust all retries and fail, leading to errors. 
There is a consistency mechanism better than exclusive locking - WAL.
It has been found that dashboards with alerts cannot be provisioned, or the alerts are never executed due to the issue described above.
We do, as several setups use alerts on the dashboards, and confirmed to have this issue.
```changes
type: fix
summary: enable WAL …
```
=> [prometheus] Fix grafana sqlite locking errors

modules/300-prometheus/templates/grafana/deployment-v10.yaml
Grafana uses a SQLite database as a backend for storing data. There is only one database file, and it appears that  Grafana executes transactions from the different code parts concurrently, hence leading to high database access contention. If some part of the code cannot take an exclusive lock, it fails and retries. When there are a lot of dashboards, alerts, etc., this particular code may exhaust all retries and fail, leading to errors. 
There is a consistency mechanism better than exclusive locking - WAL.
Backports #13063 
It has been found that dashboards with alerts cannot be provisioned, or the alerts are never executed due to the issue described above.
We do, as several setups use alerts on the dashboards, and confirmed to have this issue.
```changes
type: fix …
```
=> [prometheus] Fix grafana sqlite locking errors (#13063)

.golangci.yaml, deckhouse-controller/pkg/apis/ensure_crds.go, go_lib/hooks/ensure_crds/hook.go
It adds localmodule to linter.
```changes
type: fix
summary: Add localmodule to linter.
```
=> [deckhouse] add localmodule to linter

deckhouse-controller/pkg/controller/moduleloader/sync.go, deckhouse-controller/pkg/controller/moduleloader/sync_test.go
Fix deployed module release restoration on HA installations
HA deckhouse installation could have symlink to an old module version on standby masters.
We have to restore the relevant module version on startup.
```changes
type: fix 
summary: Gracefully restore deployed modules on HA installations.
```
=> [deckhouse] Fix deployed module release restoration on HA installations

ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/patches/002-fix-cluster-name-handling.patch, ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/patches/README.md, ee/modules/030-cloud-provider-huaweicloud/templates/cloud-controller-manager/deployment.yaml
- Add the `--cluster-name` CLI flag to the `cloud-controller-manager`
- Add a patch to `cloud-controller-manager` to fix the handling of the `--cluster-name` CLI flag
The `cloud-controller-manager` uses the `--cluster-name` CLI flag to generate load balancer names. If this flag is not set, separate clusters may generate identical load balancer names.
For each `Service`, two load balancers were provisioned: one with the correct cluster name and another with the default cluster name. It is incorrect to have two load balancers for the same service. The patch to `cloud-controller-manager` fixes the issue by ensuring that only one load balancer is created with the correct cluster name.
```changes
type: fix
summary: Add the `--cluster-name` CLI flag to the …
```
=> [cloud-provider-huaweicloud] Add the `--cluster-name` CLI flag to the `CCM`

tools/docs/spelling/check_diff.sh
Updated the message displayed when the documentation linter fails to clarify how to skip the linter by using the `skip/documentation-validation` label and re-running all jobs.
```changes
section: docs
type: chore
summary: Updated the message displayed when the documentation linter fails.
```
=> [ci] Update documentation linter message

modules/150-user-authn/templates/dex-authenticator/deployment.yaml
fixed: #12546
Get the ability to create a DexAuthenticator with numbers in the name.
```changes
type: fix
summary: DexAuthenticator with digit name fails
```
=> [user-authn] DexAuthenticator with digit name fails

candi/bashible/bashbooster/50_dnf.sh, docs/site/pages/virtualization-platform/documentation/admin/platform-management/node-management/ADVANCED.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/node-management/ADVANCED_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/node-management/OS.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/node-management/OS_RU.md, ee/fe/modules/040-node-manager/templates/ngc-ca-certificate.yaml, modules/040-node-manager/docs/FAQ.md, modules/040-node-manager/docs/FAQ_RU.md, modules/040-node-manager/templates/ngc-nfs-common.yaml
Added `bb-dnf` functions. In some distributions (e.g. Red OS) yum is definitively declared deprecated and is not included in the distro package. Now you should use `bb-dnf-install `instead of `bb-yum-install` by default.
`bb-dnf-install` first checks that `dnf` is installed, if `dnf` is missing then downgrade to `yum` is attempted.
Support for dnf package manager in bashible
```changes
section: candi
type: fix 
summary:  Support for dnf package manager
impact: 
```
=> [candi] Support for dnf package manager

modules/040-node-manager/images/machine-controller-manager/werf.inc.yaml
Update `mcm` version. New version includes nil-value handling for VM object's  `config` property.
Related mcm PR: https://github.com/deckhouse/mcm/pull/17
This PR fixes https://github.com/deckhouse/deckhouse/issues/10744.
```changes
type: fix
summary: Fix panic in vSphere provider during VM creation
```
=> [node-manager] update mcm version to v0.36.0-flant.20

candi/bashible/common-steps/all/000_add_node_users.sh.tpl
Find additional sudoers groups only in readable files.
Step hangs if sudoers_path contains pipe files.
Not necessary.
```changes
section: candi
type: chore
summary: fix infinity execution in add_node_users step
```
=> [candi] fix infinity execution in add_node_users step

docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA.md, docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA_RU.md, tools/kind-d8.sh
Fix getting started for kind.
Added an alert to disable rosetta for Apple with ARM processors.
```changes
section: docs
type: chore
summary: Fix getting started for kind.
```
=> [docs] Fix getting started for kind

modules/300-prometheus/docs/FAQ.md, modules/300-prometheus/docs/FAQ_RU.md
Add info about how to figure out if dashboard doesn't appear in Grafana.
```changes
section: docs
type: fix
summary: Add info about debug GrafanaDashboardDefenition
```
=> [docs] Add info about debug GrafanaDashboardDefinition

tools/dmt-lint.sh
bump DMT version to 0.1.15
bump DMT version to 0.1.15
```changes
section: tools
type: chore
summary: bump DMT version to 0.1.15
```
=> [tools] bump DMT version to 0.1.15

dhctl/pkg/app/preflight.go, dhctl/pkg/preflight/preflight.go, dhctl/pkg/preflight/staticinstances_ip_duplication.go, dhctl/pkg/preflight/staticinstances_ip_duplication_test.go
Add preflight check to avoid ip addresses duplication in StaticInstance
Close https://github.com/deckhouse/deckhouse/issues/12594
```changes
section: dhctl
type: feature
summary: Add preflight check to avoid ip addresses duplication in StaticInstances.
```
=> [dhctl] Add preflight check to avoid duplication of StaticInstance IP

dhctl/pkg/preflight/staticinstances_ip_duplication.go
Remove output from preflight check
We do not need to print part of config to dhctl output
```changes
section: dhctl
type: chore
summary: Remove output from preflight check.
```
=> [dhctl] Remove debug output for preflight check

modules/340-extended-monitoring/templates/x509-certificate-exporter/deployment.yaml
During the migration from `cert_exporter` to `x509_certificate_exporter`, the `resources` section in the deployment manifest was not updated.  
This PR fixes that by renaming the resource reference from `certificate_exporter_resources` to `x509_certificate_exporter_resources` in `deployment.yaml`.
Currently, if VPA (Vertical Pod Autoscaler) is not used, the deployment manifest includes a non-existent resource reference (certificate_exporter_resources).
As a result, the x509_certificate_exporter cannot be deployed.
This fix ensures the correct resource values are used, allowing the exporter to start properly.
```changes
type: fix 
summary: Fix x509_certificate_exporter_resources deployment
```
=> [extended-monitoring] Resolve missing resource config for x509_certificate_exporter

deckhouse-controller/pkg/controller/module-controllers/source/controller.go
It limits module name to avoid ensuring "bad" modules such as blobs.
To avoid ensuring "bad" modules such as blobs.
```changes
type: fix
summary: Limit module name.
```
=> [deckhouse] limit module name

deckhouse-controller/pkg/debug/module_enable.go
It fixes enabling helper, it forbids to enable a module that does not exist.
Closes #6198
The enabling helper enabled all modules even they don`t exist, now it returns error:
```
root@dev-master-0:~# dcme test2
deckhouse-controller: error: enable module: module not found, try --help
command terminated with exit code 1
```
```changes
type: fix
summary: Fix enabling helper.
```
=> [deckhouse] fix enabling helper

deckhouse-controller/pkg/controller/module-controllers/override/controller.go, deckhouse-controller/pkg/controller/module-controllers/source/controller.go
It fixes mpo/source requeue.
Fix mpo/source requeue, use more appropriate way
```changes
type: fix
summary: Fix mpo/source requeue.
```
=> [deckhouse] fix mpo/source requeue

modules/002-deckhouse/module.yaml, modules/002-deckhouse/templates/admission/secret.yaml, modules/002-deckhouse/templates/namespace.yaml, modules/002-deckhouse/templates/service.yaml, modules/002-deckhouse/templates/webhook-handler/deployment.yaml, modules/002-deckhouse/templates/webhook-handler/secret.yaml, modules/002-deckhouse/templates/webhook-handler/service.yaml
This pull request introduces a set of changes aimed at preventing the accidental deletion of the Deckhouse module. These protections are implemented using Helm annotations and adding delete options to module to preserve critical resources that are essential to the platform’s functionality.
Removing or disabling the deckhouse module can completely paralyze a cluster and render it unmanageable. To mitigate this risk, this PR adds multiple safety measures that ensure critical resources remain untouched unless explicitly overridden.
All important Kubernetes objects (e.g. services, secrets, deployments, namespaces) now have:
```yaml
annotations:
"helm.sh/resource-policy": keep
```
Resources with this protection include:
- Namespaces: d8-monitoring, d8-service-accounts, …
=> [deckhouse-controller]: prevent unconditional module delete

modules/402-ingress-nginx/images/controller-1-9/werf.inc.yaml
The build procedure of ingress-nginx 1.9 was wrongly refactored some time ago and now ingress-nginx containers are missing some key shared libraries like grpc, resulting in controllers` pods crashing with the following errors:
```
-------------------------------------------------------------------------------
Error: exit status 1
nginx: [emerg] dlopen() "/modules_mount/etc/nginx/modules/otel/otel_ngx_module.so" failed (libgrpc.so.16: cannot open shared object file: No such file or directory) in /tmp/nginx/nginx-cfg3397002933:15
nginx: configuration file /tmp/nginx/nginx-cfg3397002933 test failed
-------------------------------------------------------------------------------
E0421 14:08:07.026288       7 queue.go:131] "requeuing" err=<
```
It fixes ingress-nginx controller build by copying …
=> [ingress-nginx] fix missing libraries for ingress-nginx v1.9

modules/140-user-authz/webhooks/validating/role_binding
It excludes clusterrolebindings that created by deckhouse from rbacv2 validation webhook
This webhook should check bindings that only created by users.
```changes
type: fix
summary: Exclude deckhouse clusterrolebindings from webhook.
```
=> [user-authz] exclude deckhouse clusterrolebinding from webhook

ee/be/modules/040-node-manager/openapi/values.yaml, modules/040-node-manager/openapi/values.yaml, tools/dmt-lint.sh
bump DMT version to 0.1.18
bump DMT version to 0.1.18
```changes
section: tools
type: chore
summary: bump DMT version to 0.1.18
```
=> [tools] bump DMT version to 0.1.18

deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_kubernetes_version.go, global-hooks/discovery/cluster_configuration.go, global-hooks/discovery/cluster_configuration_test.go, global-hooks/migrate/migrate_k8s_upgrade.go
Fix work when kubernetesVersion = 'Automatic'.
in https://github.com/deckhouse/deckhouse/pull/12853 we autoset variable DefaultKubernetesVersion on the build stage. This PR fixes some cases which cannot work properly after that PR.
```changes
type: fix
summary: fix usage of DefaultKubernetesVersion var
```
=> [deckhouse-controller] fix usage of DefaultKubernetesVersion var

docs/site/_includes/getting_started/huaweicloud/partials/config.ru.yml.standard.other.inc, docs/site/_includes/getting_started/huaweicloud/partials/config.yml.standard.other.inc, docs/site/_includes/getting_started/vcd/partials/config.ru.yml.standard.other.inc, docs/site/_includes/getting_started/vcd/partials/config.yml.standard.other.inc
Fixed errors at Huawei Cloud Getting Started.
```changes
section: docs
type: chore
summary: Fixed errors at Huawei Cloud Getting Started.
```
=> [docs] Fixed errors at Huawei Cloud Getting Started

candi/bashible/common-steps/all/068_configure_kubelet_systemd_unit.sh.tpl
Return support `.cri.notManaged.criSocketPath`. 
Probably support for this functionality was limited to Kubernetes version <1.27 by mistake and removed with eol:
https://github.com/deckhouse/deckhouse/commit/8d52e086113ff41284200fddd88ec9cb01b0c98e#diff-f64efc9c61452b3eb9e3bf9220130c3666b96837a313e1105c8b7baa4ef94c20R94-R96
https://github.com/deckhouse/deckhouse/commit/b676c8841d1f130d0de45176d1172cc42f5b9939#diff-a3108429fddd29708f27c209c6f167f0efa34eea3fed2ec0b1f3f2c61a29f779L90-L91
Not neccary.
```changes
section: candi
type: fix
summary: Return support `.cri.notManaged.criSocketPath`. 
```
=> [candi] return support criSocketPath for notManaged cri

modules/300-prometheus/docs/README.md, modules/300-prometheus/docs/README_RU.md, modules/300-prometheus/openapi/config-values.yaml, modules/300-prometheus/openapi/doc-ru-config-values.yaml
Updated info about MaxDiskSizeGigabytes Prometheus parameters and automatic volume expansion.
```changes
section: docs
type: chore
summary: Updated info about MaxDiskSizeGigabytes Prometheus parameters and automatic volume expansion.
```
=> [docs] Removed info about MaxDiskSizeGigabytes Prometheus parameters and automatic volume expansion

dhctl/pkg/operations/bootstrap/steps.go
Fix checking bashible already run and move this check before all bashible operations
Incorect checking bashible service run. Retry after fail after running bashible start bashible one time yet
```changes
section: dhctl
type: fix
summary: Fix checking bashible already run.
```
=> [dhctl] Fix checking bashible already run

candi/bashible/preflight/check_localhost.sh.tpl
Make preflight check localhost more accurate.
Current localhost check can give false positives in some cases:
1. If `/etc/hosts` doesn't contain "127.0.0.1 localhost" and system dns resolve `localhost` to another IP.
2. If `localhost` resolve to only IPv6 addr.
For example:
```console
[root@dev-master-0 ~]# cat /etc/hosts
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
[root@dev-master-0 ~]# getent ahosts localhost; echo $?
::1             STREAM localhost
::1             DGRAM
::1             RAW
0
```
that will broke bootstrap:
```log
│ ┌ Waiting for Kubernetes API to become Ready
│ │ ️⛱️️ Attempt #1 of 45 |
│ │ 	Waiting for Kubernetes API to become Ready failed, next attempt will be in 5s"
│ │ 	Error: kubernetes API is not Ready: Get …
```
=> [dhctl] fix preflightcheck localhost

docs/documentation/pages/admin/configuration/update/UPDATE-CONFIGURATION_RU.md
This PR fixes incorrect disruptive update naming in the new structure, reflecting the earlier changes made in `main`.
Ref: #12828 
```changes
section: docs
type: chore
summary: Updated disruptive update naming.
```
=> [docs] Update disruptive update info

docs/site/backends/docs-builder-template/layouts/partials/openapi/format-attributes.html
Added support for the x-enum-descriptions parameter for Hugo.
This allows to render x-enum-descriptions for external modules.
```changes
section: docs
type: chore
summary: Supporting x-enum-descriptions for hugo added.
```
=> [docs] Supporting x-enum-descriptions for hugo added

deckhouse-controller/pkg/controller/deckhouse-release/controller.go, docs/documentation/_data/deckhouse-alerts.yml, modules/340-monitoring-deckhouse/monitoring/prometheus-rules/deckhouse.yaml
It enriches DeckhouseUpdating alert to show the deploying version.
It helps to learn which version is deploying.
```
❯ kubectl get clusteralert 1db478a4d9ee998e -o yaml
alert:
labels:
d8_component: deckhouse
d8_module: deckhouse
deployingRelease: v1.71.0
prometheus: deckhouse
tier: cluster
name: DeckhouseUpdating
severityLevel: "4"
summary: Deckhouse is being updated to v1.71.0.
kind: ClusterAlert
metadata:
creationTimestamp: "2025-04-24T11:16:34Z"
generation: 1
labels:
app: prometheus
heritage: deckhouse
name: 1db478a4d9ee998e
resourceVersion: "524443047"
uid: 667aaf6d-e805-4c52-9771-f500405f60ee
status:
alertStatus: firing
lastUpdateTime: "2025-04-24T11:16:29Z"
startsAt: "2025-04-24T11:16:29Z"
```
```changes
type: chore
summary: …
```
=> [deckhouse] enrich DeckhouseUpdating alert

modules/040-control-plane-manager/hooks/audit_policy_basic_targets_generated.go, modules/150-user-authn/templates/basic-auth-proxy/deployment.yaml, modules/150-user-authn/templates/basic-auth-proxy/rbac-for-us.yaml
Add separate ServiceAccount to `basic-auth-proxy` template
According to CIS 5.1.5, default service account should not be used for Kubernetes API access
In v1.69 basic-auth-proxy fails to start, this changes will fix it.
```changes
type: fix
summary: Add separate ServiceAccount to basic-auth-proxy.
```
=> [user-authn] Add ServiceAccount to templates

docs/documentation/pages/admin/configuration/backup/BACKUP_AND_RESTORE.md, docs/documentation/pages/admin/configuration/backup/BACKUP_AND_RESTORE_RU.md
Translate new DKP structure — Backup and restore.
```changes
section: docs
type: chore
summary: Translate new DKP structure — Backup and restore.
```
=> [docs] Translate new DKP structure — Backup and restore

dhctl/pkg/operations/converge/context/context.go, dhctl/pkg/operations/converge/converger.go, dhctl/pkg/operations/converge/runner.go, dhctl/pkg/operations/phases/phases.go, modules/040-terraform-manager/images/base-terraform-manager/werf.inc.yaml
Disable converge deckhouse configuration for terraform autoconverger and converge from CLI
Also fix panic with running terraform-auto-converger and terraform state exporter because terraform_versions.yaml did not copied to images
Deckhouse configuration converge should work with commander only.
```changes
section: dhctl
type: fix
summary: Disable converge deckhouse configuration for terraform autoconverger and converge from CLI
```
=> [dhctl] Disable converge deckhouse configuration for terraform autoconverger and converge from CLI

dhctl/pkg/operations/converge/context/context.go, dhctl/pkg/operations/converge/converger.go, dhctl/pkg/operations/converge/runner.go, dhctl/pkg/operations/phases/phases.go
Disable caching metaconfig during converge and disable converge deckhouse manifests.
Caching metaconfig during converge break autoconverger logic. Because we load metaconfig once autoconverge does not getting actual config during attempts.
Together with converge deckhouse manifests it can revert changes in provider and cluster configuration.
Also, converge deckhouse manifest should enabled only for commander.  
Autoconverger and converge operation can revert changes in cluster and provider cluster configuration. 
```changes
section: dhctl
type: fix
summary: <Disable caching metaconfig during converge and disable converge deckhouse manifests.
```
=> [dhctl] Disable caching metaconfig during converge and disable converge deckhouse manifests

modules/040-control-plane-manager/images/etcd-backup/entrypoint.sh, modules/040-control-plane-manager/images/etcd-backup/werf.inc.yaml, modules/040-control-plane-manager/openapi/config-values.yaml, modules/040-control-plane-manager/openapi/doc-ru-config-values.yaml, modules/040-control-plane-manager/openapi/openapi-case-tests.yaml, modules/040-control-plane-manager/templates/etcd-backup/cronjob.yaml
Improve etcd backup. Add option to customise backup job:
- enable/disable
- schedule time
- path for saving backup on host
Close https://github.com/deckhouse/deckhouse/issues/12984
```changes
type: feature
summary: Add settings for etcd backup.
```
=> [control-plane-manager]  improve etcd-backup

deckhouse-controller/pkg/controller/controller.go, deckhouse-controller/pkg/controller/module-controllers/docbuilder/controller.go, deckhouse-controller/pkg/controller/module-controllers/docbuilder/controller_test.go, docs/site/backends/registry-modules-watcher/internal/backends/pkg/registry-scanner/process.go
It excludes conversion tests from docs
Tests have go ext, it is not allowed for doc rendering.
```changes
type: fix
summary: Exclude conversions test from docs.
```
=> [deckhouse] exclude conversion test from docs

.github/ci_templates/e2e_tests.yml, .github/workflows/e2e-abort-gcp.yml, .github/workflows/e2e-daily.yml, .github/workflows/e2e-gcp.yml, testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/Azure/Standard/configuration.tpl.yaml, testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/GCP/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/GCP/WithoutNAT/resources.yaml, testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml, testing/cloud_layouts/Static/configuration.tpl.yaml, testing/cloud_layouts/VCD/Standard/configuration.tpl.yaml, testing/cloud_layouts/script.d/wait_cluster_ready/test_autoscaler.sh, testing/cloud_layouts/script.sh, testing/cloud_layouts/vSphere/Standard/configuration.tpl.yaml
Add e2e tests for autoscaler and enble it permanent for GCP.
We added placement policy for all e2e tests for adding tests for all clouds by github label.
In the GCP we added new node group with 0 min and 1 max nodes in the group for testing.
Also we added script which create deployment which will placed in autoscaler nodegroup, wait become deployment ready, scale down deployment to zero, and waiting that nodes and instances will be deleted for autoscaler node group.
Also we are waiting 2 minutes and collect error and warnings logs from autoscaler because autoscaler can contains warnings and errors after scaling 
https://github.com/deckhouse/deckhouse-test-2/actions/runs/14695712698/job/41237062043
Often we change and add new autoscaler for new kubernetes versions and we cannot testing new …
=> [testing] Add e2e tests for autoscaler and enable it permanent for GCP

modules/500-upmeter/images/upmeter/src/pkg/agent/agent.go, modules/500-upmeter/images/upmeter/src/pkg/agent/sender/client.go, modules/500-upmeter/images/upmeter/src/pkg/kubernetes/access.go, modules/500-upmeter/images/upmeter/src/pkg/kubernetes/types.go, modules/500-upmeter/images/upmeter/src/pkg/probe/checker/http.go, modules/500-upmeter/images/upmeter/src/pkg/probe/checker/smoke_mini_test.go
Now upmeter rereads the Kubernetes token if the token's warnafter timestamp is greater than the current time. In short, the token is reread every hour. This is done to avoid the stale-token issue
Now we read the token, store it and its warnafter value, and if the current time is greater than warnafter, we reread the token.
Currently, upmeter reads the token only at application startup and ignores its rotation
```changes
type: fix
summary: upmeter sa token rotation
impact: 
```
=> [upmeter] sa token rotation

ee/candi/cloud-providers/vcd/terraform-modules/providers.tf, ee/modules/030-cloud-provider-vcd/templates/cloud-controller-manager/secret.yaml, ee/modules/030-cloud-provider-vcd/templates/cloud-data-discoverer/secret.yaml, ee/modules/030-cloud-provider-vcd/templates/csi/secret.yaml, ee/modules/030-cloud-provider-vcd/templates/registration.yaml
Remove trailing `/` from the `VCDClusterConfiguration.provider.server` field to ensure consistent URL handling.
`cloud-data-discoverer` log an error when API URL contains a trailing `/`:
```
{"level":"error","msg":"Getting instance types error: failed to create vcd client: unable to authenticate: error finding LoginUrl: could not find valid version for login: could not retrieve supported versions: error fetching versions: 404 Not Found\n","time":"2025-04-24T10:01:15Z"}
```
```changes
type: fix
summary: Trim trailing slash from `VCDClusterConfiguration.provider.server`.
```
=> [cloud-provider-vcd] trim trailing `/` from `VCDClusterConfiguration.provider.server`

.github/ci_templates/e2e_tests.yml, .github/workflows/e2e-abort-gcp.yml, .github/workflows/e2e-daily.yml, .github/workflows/e2e-gcp.yml, testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/Azure/Standard/configuration.tpl.yaml, testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/GCP/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/GCP/WithoutNAT/resources.yaml, testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml, testing/cloud_layouts/Static/configuration.tpl.yaml, testing/cloud_layouts/VCD/Standard/configuration.tpl.yaml, testing/cloud_layouts/script.d/wait_cluster_ready/test_autoscaler.sh, testing/cloud_layouts/script.sh, testing/cloud_layouts/vSphere/Standard/configuration.tpl.yaml
Backport
(cherry picked from commit 69023fa9addfda18a40e76504a8f1f87030b20ee)
```changes
type: feature
summary: Add e2e tests for autoscaler and enable it permanent for GCP.
```
=> [testing] Add e2e tests for autoscaler and enable it permanent for GCP (#13232)

.github/ci_templates/cve_tests.yaml, .github/workflows/cve-pr.yml, .github/workflows/cve-weekly.yml, Makefile, tools/cve/d8-images.sh, tools/cve/trivy-wrapper.sh
This PR improves error handling when scanning images using Trivy.  
A retry mechanism was added: the first attempt uses `--quiet`, subsequent retries switch to `--debug` mode if the initial scan fails.
Previously, transient Trivy failures (network issues, registry errors) caused immediate job failures.  
With retries (5 attempts, 5-second delay), the process becomes more stable and resilient to temporary problems.
```changes
section: ci
type: fix
summary: Trivy error handling improvements
```
=> Trivy error handling improvements

ee/modules/650-runtime-audit-engine/docs/FAQ.md, ee/modules/650-runtime-audit-engine/docs/FAQ_RU.md, ee/modules/650-runtime-audit-engine/monitoring/prometheus-rules/runtime-audit-engine.yaml
Remove deprecated `falco_events` metric.
`falcosidekick` since version 2.30 and above renamed the `falco_events` metric to `falcosecurity_falcosidekick_falco_events_total`. 
Since release 1.68 we supported both metric for backward compatibility, but since release 1.70 use only original metric.
```changes
type: chore
summary: Remove deprecated `falco_events` metric.
impact: Dashboards and alerts based on the `falco_events` metric might be broken.
```
=> [runtime-audit-engine] del deprecated falco_events metric

modules/110-istio/templates/rbac-to-us.yaml
Add `RBAC` rules to grant the HuaweiCloud `cloud-controller-manager` permission to view pods in the `d8-istio` namespace.
`cloud-controller-manager` does not create an external IP:
```
81s         Warning   SyncLoadBalancerFailed   service/ingressgateway                          Error syncing load balancer: failed to ensure load balancer: pods is forbidden: User "system:serviceaccount:d8-cloud-provider-huaweicloud:cloud-controller-manager" cannot list resource "pods" in API group "" in the namespace "d8-istio"
```
```changes
section: istio
type: fix
summary: Add `RBAC` rules to grant the HuaweiCloud `cloud-controller-manager` permission to view pods in the `d8-istio` namespace.
```
=> [istio] Add RBAC rules for the HuaweiCloud `CCM`

.github/ci_templates/e2e_tests.yml, .github/workflow_templates/e2e-daily.yml, .github/workflows/e2e-daily.yml
Disable Madison notification on failed daily e2e.
Due to changes in notification system, old notifications are unnecessary.
```changes
section: ci
type: chore
summary: Disable notification on failed daily e2e.
```
=> [ci] Disable notification on failed daily e2e

.github/workflow_templates/e2e-daily.yml, .github/workflows/e2e-daily.yml
Reverts deckhouse/deckhouse#13030
Should work for now, #12937 is still necessary for future usage.
```changes
section: ci
type: chore
summary: Revert disable Azure for daily e2e.
```
=> [ci] Revert disable Azure for daily e2e

.github/ci_templates/e2e_tests.yml, .github/workflows/e2e-abort-aws.yml, .github/workflows/e2e-abort-azure.yml, .github/workflows/e2e-abort-gcp.yml, .github/workflows/e2e-abort-openstack.yml, .github/workflows/e2e-abort-static.yml, .github/workflows/e2e-abort-vcd.yml, .github/workflows/e2e-abort-vsphere.yml, .github/workflows/e2e-aws.yml, .github/workflows/e2e-azure.yml, .github/workflows/e2e-daily.yml, .github/workflows/e2e-eks.yml, .github/workflows/e2e-gcp.yml, .github/workflows/e2e-openstack.yml, .github/workflows/e2e-static.yml, .github/workflows/e2e-vcd.yml, .github/workflows/e2e-vsphere.yml
Fix https://github.com/deckhouse/deckhouse/pull/13233
Pass to e2e container SLEEP_BEFORE_TESTING_CLUSTER_ALERTS not only eks
Daily e2e tests pause before cluster alerts work with Yandex.Cloud only
```changes
type: fix
summary: Fix pause before e2e cluster alerts
```
=> [testing] Fix pause before e2e cluster alerts

.github/workflows/e2e-daily.yml
Rerender daily e2e workflow.
```changes
section: ci
type: chore
summary: Rerender daily e2e workflow.
```
=> [ci] Rerender daily e2e workflow

modules/110-istio/templates/rbac-to-us.yaml
If the `cloud-provider-huaweicloud` module is enabled, define `RBAC` permissions granting the `cloud-controller-manager` access to list pods in the `d8-istio` namespace.
An error occurred in the prior implementation:
```
{
"level": "error",
"logger": "addon-operator",
"msg": "ModuleRun failed. Requeue task to retry after delay.",
"binding": "ConvergeModules",
"count": 24,
"error": "run helm install: template: istio/templates/rbac-to-us.yaml:1:17: executing \"istio/templates/rbac-to-us.yaml\" at <.Values.global.clusterConfiguration.cloud.provider>: nil pointer evaluating interface {}.provider\n\nUse --debug flag to render out invalid YAML",
"event.type": "OperatorStartup",
"module": "istio",
"phase": "RunHelm",
"queue": "main",
"task.id": "e9d7d735-5f3e-452a-b462-e1f9fe52c569", …
```
=> [istio] fix RBAC rules for HuaweiCloud CCM

deckhouse-controller/pkg/controller/moduleloader/sync.go, deckhouse-controller/pkg/controller/moduleloader/testdata/overrides/mpo-with-old-deployed-on.yaml, deckhouse-controller/pkg/controller/moduleloader/testdata/overrides/mpo-without-weight.yaml, deckhouse-controller/pkg/controller/moduleloader/testdata/overrides/mpo.yaml
It restore only ready mpo.
Useless to restore unready mpo.
```changes
type: fix
summary: Restore only ready mpo.
```
=> [deckhouse] restore only ready mpo

ee/modules/650-runtime-audit-engine/images/rules-loader/hooks/lib/convert.py, ee/modules/650-runtime-audit-engine/templates/configmap.yaml, ee/modules/650-runtime-audit-engine/templates/falco-rules.yaml
It fixes the config.
Runtime audit engine was stuck in CrashLoopBack.
Now the validation is successful:
```
Tue Apr 29 10:51:21 2025: [info] [k8smeta] Start the process scan under: '/host/proc'
Tue Apr 29 10:51:21 2025: [info] [k8smeta] Process scan correctly completed. Found '911' threads inside pods.
Tue Apr 29 10:51:21 2025: Configured rules filenames:
Tue Apr 29 10:51:21 2025:    /etc/falco/rules.d
Tue Apr 29 10:51:21 2025:    /etc/falco/k8s_audit_rules.yaml
Tue Apr 29 10:51:21 2025: Loading rules from:
Tue Apr 29 10:51:21 2025:    /etc/falco/rules.d/fstec.yaml | schema validation: ok
Tue Apr 29 10:51:21 2025:    /etc/falco/k8s_audit_rules.yaml | schema validation: ok
Tue Apr 29 10:51:21 2025: Hostname value has been overridden via environment variable to: dev-master-0
Tue Apr 29 …
```
=> [runtime-audit-engine] fix crashLoopBack due to invalid config

deckhouse-controller/pkg/debug/debug.go, modules/002-deckhouse/docs/FAQ.md, modules/002-deckhouse/docs/FAQ_RU.md
- Added creation of list of unmanaged modules to debug archive.
- Removed entry `terraform-check` in debug archive, because in current versions it is impossible to execute terraform-check inside cluster.
- Updated documentation for debug archive.
After adding [unmanaged modules](https://github.com/deckhouse/deckhouse/pull/12686) (v1.69.0), it will be convenient to see in the debug archive a list of modules that were disconnected by the client from deckhouse management
```changes
type: chore
summary: updated the data collected in the debug container
```
=> [deckhouse-controller] Add list of unmanaged modules to debug archive

docs/documentation/_plugins/render-jsonschema.rb
Fix showing required parameter status of the ModuleConfig in the documentation.
```changes
section: docs
type: chore
summary: Fix showing required parameter status of the ModuleConfig in the documentation.
```
=> [docs] Fix showing required parameter status of the ModuleConfig in the documentation

.werf/defines/infrastructure-manager.tmpl, .werf/defines/terradform-manager.tmpl, candi/terraform_versions.yml, ee/modules/040-terraform-manager/images/terraform-manager-dynamix/werf.inc.yaml, ee/modules/040-terraform-manager/images/terraform-manager-huaweicloud/werf.inc.yaml, ee/modules/040-terraform-manager/images/terraform-manager-openstack/werf.inc.yaml, ee/modules/040-terraform-manager/images/terraform-manager-vcd/werf.inc.yaml, ee/se-plus/modules/040-terraform-manager/images/terraform-manager-vsphere/werf.inc.yaml, ee/se-plus/modules/040-terraform-manager/images/terraform-manager-zvirt/werf.inc.yaml, modules/040-terraform-manager/images/terraform-manager-aws/werf.inc.yaml, modules/040-terraform-manager/images/terraform-manager-azure/werf.inc.yaml, modules/040-terraform-manager/images/terraform-manager-gcp/werf.inc.yaml, modules/040-terraform-manager/images/terraform-manager-yandex/werf.inc.yaml
Add define for getting base image for terraform-manager image depends of terraform_versions.yaml file
Manage base image in terraform_versions.yaml file without remembering about changing base image in terraform-manager module when migrate module to opentofu
```changes
section: ci
type: chore
summary: Add define for getting base image for terraform-manager image depends of terraform_versions.yaml file.
```
=> [ci] Add define for getting base image for terraform-manager image depends of terraform_versions.yaml file

dhctl/pkg/kubernetes/actions/deckhouse/install.go, dhctl/pkg/kubernetes/actions/deckhouse/install_test.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper-deckhouse.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go, dhctl/pkg/operations/bootstrap/steps.go, dhctl/pkg/operations/bootstrap/steps_test.go, testing/cloud_layouts/AWS/WithoutNAT/resources.yaml
Create resources before deckhouse manifests resources will be selected by special secret (for only our use) annotation.
Add manifests for creation prometheus rules mutating webhook which replace 'for' for rules to 1m. (only aws in this pr)
This pr does not fix alerts in aws. We have problems with tags in static instances. For fix it we need additional discussion.
Show results here https://github.com/deckhouse/deckhouse/actions/runs/14824592925
We have many alerts that begin firing after some delay. We want get all events in he cluster during e2e tests without delay and additional sleep in the tests
```changes
section: dhctl
type: feature
summary: Create resources before deckhouse manifests resources will be selected by special secret (for only our use) annotation.
--- …
```
=> [dhctl][testing] create resources before deckhouse manifest and mutating webhook for prom rules for e2e tests

.github/scripts/trivy-db-update-vulnerability-references.sh, .github/scripts/trivy-db-update.sh, .github/workflow_templates/trivy-db-schedule.yml, .github/workflows/trivy-db-schedule.yml
This PR updates the `trivy-db-schedule` workflow to improve how custom changes are applied to the Trivy database.
- Changed the branch used to download the Trivy DB — now it pulls directly from the upstream repository instead of a pre-patched fork.
- Added a step to clone an additional repository containing our custom patch files.
- Applied those patches to the Trivy DB after downloading.
The old setup used a pre-patched fork, which was harder to maintain.  
Now we apply patches during the workflow, making updates and maintenance simpler and more transparent.
```changes
section: ci
type: fix
summary: Fix trivy db download
```
=> Fix trivy db download

modules/460-log-shipper/hooks/internal/vector/destination/socket.go
Add condition for enabling [tls.enable](https://vector.dev/docs/reference/configuration/sources/socket/#tls.enabled) in case if certificates provided for a socket sink.
In some cases, we were failing to achieve TLS handshake using socket sink with certificates, since the parameter was turned off by default.
```changes
type: fix
summary: Enable TLS for TCP socket if certificates provided.
```
=> [log-shipper] Socket sink enable TLS if certificates provided

tools/validation/grafana_dashboard_test.go
Fix grafana_dashboard_test for deprecated components. 
The test implies that it uses deprecated parameters, however, in PR I made a mistake and changed to relevant ones, which caused the GO tests to crash
```changes
section: tools
type: fix 
summary: Fix grafana_dashboard_test for deprecated components. 
```
=> [tools] Fix grafana_dashboard_test for deprecated components. 

docs/documentation/_data/deckhouse-alerts.yml, modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
fix https://github.com/deckhouse/deckhouse/pull/12163
added additional instructions for resolving the alert
Sometimes, resolving an alert requires configuring additional audit policies.
```changes
type: fix 
summary: Stale service account alert upd
impact: 
```
=> [control-plane-manager] Stale service account alert upd

modules/110-istio/hooks/purge_orphan_resources.go, modules/110-istio/hooks/purge_orphan_resources_test.go
Changes to the resource deletion hook when disabling the module for deleting resources `configmap.istio-ca-root-cert`, `IstioMulticluster`, `IstioFederation`
When the `Istio` module was turned off, `configmap.istio-ca-root-cert` remained in the user namespace, which carried outdated certificates, which could lead to the failure of mtls if the certificates were not updated. There are also outdated cluster-wide resources `IstioMulticluster`, `IstioFederation`.
```changes
section: istio
type: feature
summary: Added garbage collection of istio-ca-root-cert and IstioMulticluster/IstioFederation resources after module disabling.
```
=> [istio] garbage collecting CRs when module is disabled

modules/002-deckhouse/template_tests/module_test.go, modules/002-deckhouse/templates/deployment.yaml
Add conditions for using direct connection, API-proxy and Service.
Deckhouse stucks when cni is malfunctioned.
Also, if you switch CNIs in a cluster, the network becomes unavailable, including all services. Deckhouse works with API through the service, so it loses access to it.
```changes
type: fix
summary: Changed the method of connecting deckhouse-controller to API-server.
```
=> [deckhouse] change the method of connecting deckhouse-controller to API-server

docs/site/pages/stronghold/documentation/admin/platform-management/network/EGRESS.md, docs/site/pages/stronghold/documentation/admin/platform-management/network/EGRESS_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/network/EGRESS.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/network/EGRESS_RU.md, modules/021-cni-cilium/docs/EXAMPLES.md, modules/021-cni-cilium/docs/EXAMPLES_RU.md
In the examples from the `EgressGateway` documentation, the label that specifies which nodes should run `EgressGateway` components has been changed from `node-role.deckhouse.io/egress: ""` to `dedicated/egress: ""`. 
Labels `node-role.deckhouse.io` are reserved and keys can only contain `master`, `system` or `frontend`, or the names of specific D8 modules. As egress is part of the cni-cilium (and not an independent module), an alert is triggered when this label is used. This can lead to confusion. 
```changes
type: fix
summary: Fixed the examples in the `Egressgateway` documentation.
```
=> [cni-cilium] Fix the examples in the `Egressgateway` documentation.

modules/402-ingress-nginx/docs/FAQ.md, modules/402-ingress-nginx/docs/FAQ_RU.md
A description of the Web Application Firewall (WAF) has been added to the documentation for the ingress-nginx module. This includes information on how to enable and configure the WAF.
Our users often ask about the presence of a WAF (Web Application Firewall) in the Deckhouse and, if so, how it can be configured.
```changes
type: chore
summary: Adding a WAF description to the documentation.
```
=> [ingress-nginx] Add a WAF description to the documentation.

docs/documentation/_data/deckhouse-alerts.yml, tools/helm_generate/runners/alert_templates/alert_templates.go
Fix rendering of `sourceFile` value in deckhouse-alerts docs.
Files with the `.tpl` extension after being rendered showed the wrong path in the `sourceFile` value if they were located in a subdirectory.
```changes
section: docs, tools
type: chore
summary: Fix rendering of `sourceFile` value in deckhouse-alerts docs.
```
=> [docs][tools] Fix rendering of sourceFile value in deckhouse-alerts docs

deckhouse-controller/crds/doc-ru-module-source.yaml, deckhouse-controller/crds/module-source.yaml, deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module.go, deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_source.go, deckhouse-controller/pkg/controller/module-controllers/downloader/downloader.go, deckhouse-controller/pkg/controller/module-controllers/source/controller.go, deckhouse-controller/pkg/controller/module-controllers/source/controller_test.go, deckhouse-controller/pkg/controller/module-controllers/source/helpers.go, deckhouse-controller/pkg/controller/module-controllers/source/testdata/golden/withmodulepullerror.yaml, deckhouse-controller/pkg/controller/module-controllers/source/testdata/golden/withmodules.yaml, deckhouse-controller/pkg/controller/module-controllers/source/testdata/withmodulepullerror.yaml, deckhouse-controller/pkg/controller/module-controllers/source/testdata/withmodules.yaml
It provides module version for module source.
Help to learn module versions in modules sources.
```
root@dev-master-0:~# k get ms test -oyaml
kind: ModuleSource
metadata:
creationTimestamp: "2025-03-19T10:32:06Z"
finalizers:
- modules.deckhouse.io/module-exists
- modules.deckhouse.io/release-exists
generation: 1
name: test
...
status:
message: ""
modules:
- name: csi-yadro-tatlin-unified
version: unknown
- name: data-exporter
version: unknown
- checksum: sha256:e66cfcec0dec60a3f0a3d6dc59be7bc31090f8ad15d8fb961d5df9cc9c2eedf1
name: development-platform
version: v0.1.1
- name: managed-postgres
version: unknown
- name: observability
version: unknown
- checksum: sha256:f0678a62316dd5debd6d22601270ace0c3e9b617a2db413659dfd960a1cdb944
name: prompp
version: …
```
=> [deckhouse] add module version to module source

docs/documentation/_data/deckhouse-alerts.yml, modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/kube-dns.tpl, tools/helm_generate/runners/alert_templates/template_values/340-monitoring-kubernetes.yaml
Disable `KubernetesDnsTargetDown` alert if module `kube-dns` is not used.
This alert use metrics from the `kube-dns` module, which is not included in the `Managed` bundle by default.
```changes
type: chore
summary: Disable KubernetesDnsTargetDown alert if module `kube-dns` is not used.
```
=> [monitoring-kubernetes] disable dns target down alert if module kube-dns is not used

modules/040-node-manager/images/cluster-autoscaler/patches/1.30/004-delete-mcm-annotations-from-md.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.31/004-delete-mcm-annotations-from-md.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.32/004-delete-mcm-annotations-from-md.patch, modules/040-node-manager/images/cluster-autoscaler/patches/README.md
Remove additional cordon node by mcm provider.
Continue of https://github.com/deckhouse/deckhouse/pull/13180
MCM provider of cluster autoscaler can cordon nodes out of autoscaler flow.
```changes
type: fix
summary: Autoscaler - remove additional cordon node by mcm provider.
```
=> [node-manager][autoscaler] Remove additional cordon node by mcm provider

docs/documentation/_includes/d8-cli-install/content.liquid, docs/site/_includes/d8-cli-install/content.liquid
Added alert about latest version at Deckhouse CLI documentation.
```changes
section: docs
type: chore
summary: Added alert about latest version at Deckhouse CLI documentation.
```
=> [docs] Added alert about latest version at Deckhouse CLI documentation

candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf
https://github.com/deckhouse/deckhouse/pull/12301 converges clusters with two-interface NAT-instance incorrectly. This PR brings back previous NAT-instance resource terraform logic as a fallback so that converge should be done correctly. 
Without this fix two-interface NAT instances will be broken during converge. 
```changes
type: fix
summary: fix WithNATInstance clusters converge
```
=> [cloud-provider-yandex] fix converge on WithNATInstance clusters

modules/021-cni-cilium/images/bin-cilium/patches/006-add-pod-prioroty-managment.patch
Fixed race condition when deleting element from ipcache agent map during VM migration.
This bug causes cilium agent crashes.
Fixes https://github.com/deckhouse/deckhouse/issues/13249.
There are customers who faced the issue.
```changes
type: fix
summary: Fixed race condition when deleting element from ipcache map during VM migration.
```
=> [cilium] fixed race condition when deleting element from map

modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.28/005-fix-list-routes-method.patch, modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.28/README.md, modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.29/005-fix-list-routes-method.patch, modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.29/README.md, modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.30/005-fix-list-routes-method.patch, modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.30/README.md, modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.31/005-fix-list-routes-method.patch, modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.31/README.md, modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.32/005-fix-list-routes-method.patch, modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.32/README.md
Modify `ListRoutes` method to handle errors gracefully without blocking reconcile loop.
`cloud-controller-manager` can get stuck in an infinite loop and stop creating new routes in AWS if, for any reason, it fails to find a Node with the specified ID:
```
E0429 06:44:40.239875       1 route_controller.go:120] Couldn't reconcile node routes: error listing routes: node with instanceID "i-0c1d9d783896b27c2" not found
```
When a new Deckhouse release is applied to the cluster and system pods are restarted, the Kubernetes API server starts responding with delays. As a result, the `fencing-agent` on some nodes fails to renew the lease in time, and those nodes are removed from the cluster ([see source](https://github.com/deckhouse/deckhouse/blob/070629cd3265a2eafe10ee7e56c24b8198155de9/modules/04 …
=> [cloud-provider-aws] Fix ListRoutes implementation in CCM

.werf/defines/infrastructure-manager.tmpl, dhctl/pkg/operations/check/check.go, ee/modules/040-terraform-manager/images/terraform-manager-dynamix/werf.inc.yaml, ee/modules/040-terraform-manager/images/terraform-manager-huaweicloud/werf.inc.yaml, ee/modules/040-terraform-manager/images/terraform-manager-openstack/werf.inc.yaml, ee/modules/040-terraform-manager/images/terraform-manager-vcd/werf.inc.yaml, ee/se-plus/modules/040-terraform-manager/images/terraform-manager-vsphere/werf.inc.yaml, ee/se-plus/modules/040-terraform-manager/images/terraform-manager-zvirt/werf.inc.yaml, modules/040-terraform-manager/images/terraform-manager-aws/werf.inc.yaml, modules/040-terraform-manager/images/terraform-manager-azure/werf.inc.yaml, modules/040-terraform-manager/images/terraform-manager-gcp/werf.inc.yaml, modules/040-terraform-manager/images/terraform-manager-yandex/werf.inc.yaml
Fix panic during dhctl terraform check if terraform returns error.
Also, add additional define for werf.yaml which calculate plugins dir for state-exporter and autoconverger images.
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1aa4ffb]
goroutine 15 [running]:
github.com/deckhouse/deckhouse/dhctl/pkg/operations/check.CheckState({0x24d5750, 0xc000714730}, 0xc000710240, 0xc00080e000, 0xc000713ca0, {0xe0?, {0x0?, 0x0?}})
/dhctl/pkg/operations/check/check.go:319 +0x27b
github.com/deckhouse/deckhouse/dhctl/pkg/operations.(*ConvergeExporter).getStatistic(0xc00007eea0, {0x24d5750, 0xc000714730})
/dhctl/pkg/operations/exporter.go:261 +0x285
github.com/deckhouse/deckhouse/dhctl/pkg/operations.(*ConvergeExpo …
```
=> [dhctl] Fix panic in check operations

deckhouse-controller/pkg/debug/debug.go
Modification of the `deckhouse-controller collect-debug-info` command to collect debugging information about Istio. The following data was collected:
1. Configuration for all resources in namespace d8-into
2. Configuration for all custom resources with istio.io CRD
3. Istio logs
4. Sidecar logs in random user application
We will not need to clarify additional information from the client in case of problems in closed environments where we do not have access.
```changes
section: istio
type: feature
summary: Added Istio debugging resources to collect-debug-info
```
=> [istio] Collecting debugging resources in collect-debug-info

docs/documentation/pages/storage/README.md
Fix broken links in the Storage overview (English version).
```changes
section: docs
type: fix
summary: Fix broken links in the Storage overview.
```
=> [docs] Fix broken links in the Storage overview.

modules/500-openvpn/templates/openvpn/configmap.yaml, testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/Azure/Standard/configuration.tpl.yaml, testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/GCP/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml, testing/cloud_layouts/Static/configuration.tpl.yaml, testing/cloud_layouts/VCD/Standard/configuration.tpl.yaml, testing/cloud_layouts/script.d/wait_cluster_ready/test_openvpn_ready.sh, testing/cloud_layouts/script.sh, testing/cloud_layouts/vSphere/Standard/configuration.tpl.yaml
* Added E2E tests to validate OpenVPN Admin pod startup and initialization of required secrets.
* Fixed path to scripts test_nodeuser.sh, test_script.sh, test_alerts.sh
We verify that the openvpn server is initialized correctly to avoid a repeat of the case
#11280 
<details>
<summary>📸 Screens E2E </summary>
</details>
```changes
type: chore
summary: Added e2e test for openvpn
```
=> [openvpn] Added e2e test

deckhouse-controller/crds/module.yaml, modules/031-ceph-csi/module.yaml
It provides stage column for modules instead of weight.
This column shows module`s lifecycle stage.
```
root@dev-master-0:~# k get module
NAME                                  STAGE        SOURCE     PHASE        ENABLED   READY
admission-policy-engine                            Embedded   Ready        True      True
basic-auth                                         Embedded   Downloaded   False     False
ceph-csi                              Deprecated   Embedded   Downloaded   False     False
```
```changes
type: chore
summary: Add module stage column.
```
=> [deckhouse] module stage column

dhctl/pkg/operations/converge/controller/cloud_permanent_node_group_hook.go, dhctl/pkg/operations/converge/infrastructure/hook/controlplane/hook_for_destroy_pipeline.go, dhctl/pkg/operations/converge/infrastructure/utils/drain.go
Use --force flag to drain master nodes.
During the drain of a master node, an error like the following may occur:
```
failed to remove control plane role from node 'test-master-1': failed to drain node 'zykov-master-1': Timeout while  
"Drain node 'test-master-1'": last error: failed to drain node 'test-master-1': cannot delete Pods declare no controller (use --force  
to override): d8-upmeter/upmeter-probe-scheduler-9f149529
```
The error occurs because the pod `upmeter-probe-scheduler-9f149529` does not have a controller, which causes the drain operation to fail.
```changes
section: dhctl
type: fix
summary: use --force flag to drain master nodes.
impact: 
```
=> [dhctl] force drain master nodes

candi/cloud-providers/gcp/bashible/common-steps/all/000_discover_kubernetes_data_device_path.sh.tpl, testing/cloud_layouts/GCP/WithoutNAT/configuration.tpl.yaml
Use `bb-d8-node-name` instead `HOSTNAME` variable for getting current node name in bashible step for gcp. 
`HOSTNAME` env variable doesn't updated value without rerun login scripts or start a new shell. In some cases this will broke step for discovering kubernetes device.
```changes
section: candi
type: fix
summary: Use bb-d8-node-name instead HOSTNAME variable for getting current node name in bashible step for gcp. 
```
=> [candi] fix step for discovering kubernetes-device in gcp

ee/candi/cloud-providers/openstack/terraform-modules/static-node/main.tf, ee/modules/040-terraform-manager/images/terraform-manager-openstack/patches/003-empty-metadata-fix.patch, ee/modules/040-terraform-manager/images/terraform-manager-openstack/patches/README.md, testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml
Decrease cloud permanent in openstack e2e because prefix + ng name lenght > 42 symbols (44)
Fix `D8TerraformStateExporterNodeStateChanged` alert for cloud permanent nodes, create empty object for metadata field instead of null.
Patch terraform-provider-openstack for prevent get diff when metadata of compute instance is empty.
Tested converge with adding, removing tags, and checked that after creating and deleting tags terraform check did not have plan changes.
```
{"level":"info","msg":"cp: node template status is ok\n","time":"2025-05-13T23:41:05Z"}
{"level":"info","msg":"cp: node template clean status changed\n","time":"2025-05-13T23:41:05Z"}
{"level":"info","msg":"cp: node template clean status absent\n","time":"2025-05-13T23:41:05Z"}
```
```
│ │ │ ️⛱️️ Attempt #41 of 45 |
│ │ │ …
```
=> [testing] Fix openstack e2e tests with cloud permanent ng

candi/terraform_versions.yml, dhctl/pkg/infrastructureprovider/get_test.go, go_lib/cloud-data/apis/v1/zvirt_cloud_provider_discovery_data.go
Replacing Terraform with OpenTofu for Zvirt
An old version of Terraform is used, which has CVE vulnerabilities that cannot be fixed.
```changes
section: candi
type: fix
summary: Replacing Terraform with OpenTofu for Zvirt
```
=> [candi] add support opentofu to the zvirt

dhctl/pkg/kubernetes/actions/deckhouse/delete.go, dhctl/pkg/operations/destroy/deckhouse.go
This pr allow skip PV's provided manually or with reclaimPolicy other than delete to destroy dkp cluster continuously.
```
kubectl -nd8-stronghold get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                        STORAGECLASS    VOLUMEATTRIBUTESCLASS   REASON   AGE
d8-stronghold-data-0                       1Gi        RWO            Delete           Bound    d8-stronghold/data-stronghold-0                              local-storage   <unset>                          18m
pvc-1c1ac48c-c076-4edb-b535-50b599c11f0b   40Gi       RWO            Delete           Bound    d8-monitoring/prometheus-main-db-prometheus-main-0           network-hdd     <unset>                          28m …
```
=> [dhctl]  Skip  PV's provided manually or with reclaimPolicy other than delete.

testing/cloud_layouts/script.d/wait_cluster_ready/test_autoscaler.sh
Improve autoscaler e2e tests.
Now we save nodes names and nodes count of autoscaler in variables. We grep cordon and draining events for each node in nodes list and grep events by node name instead of nodegroup prefix. This allows you to more accurately collect events this allows restarting testing without side effects (when we have separate events for each nodes by test attempt and we wait 1 one event for test). Also, during testing, we found that k8s not always set cordon event, but autoscaler always. We begin to check k8s events and if we did not find them check autoscaler events as fallback.  
Restarting e2e tests not working correctly and we summarized tests for adding additional nodes in tests.
```changes
type: fix
summary: Improve autoscaler e2e tests. …
```
=> [testing] Improve autoscaler e2e tests

ee/se/modules/380-metallb/images/l2lb/patches/002-l2lb-service-custom-resource.patch
This PR fixes a bug where deleting an `SDNInternalL2LBService` left IP addresses allocated, blocking new services.
It prevents IP pool exhaustion, ensuring new services can get IPs after deletions, while keeping support for multiple IP addresses.
The bug disrupts service deployment in production, making this fix urgent to maintain cluster reliability.
```changes
type: fix
summary: Fixed IP pool exhaustion on LoadBalancer deletion.
```
=> [metallb] Fix IP pool exhaustion on SDNInternalL2LBService deletion

modules/400-descheduler/images/descheduler/patches/001-go-mod.patch
fix bug go mod tidy
```changes
type: fix
summary: descheduler fix go mod tidy
```
=> [descheduler] Descheduler hotfix go mod tidy

modules/040-node-manager/templates/node-group/_bootstrap.tpl
n PR [#10845](https://github.com/deckhouse/deckhouse/pull/10845), we changed the bootstrap.sh behavior to exit immediately with a human-readable exception when receiving a 401 error from the master node during bootstrapping.
Now we've added a retry mechanism for 401 errors, since they can occur not only due to an expired token.
In some rare cases, the bootstrap script fails even when the token is valid
```changes
section: candi
type: fix
summary: retry logic for 401 in bootstrap script
impact: 
```
=> [candi] bootstrap 401 retry

.github/workflow_templates/e2e-daily.yml, .github/workflows/e2e-daily.yml
Switch daily e2e to Automatic Kubernetes version.
Allows to regularly test automatic Kubernetes version selection without significantly changing tests.
```changes
section: ci
type: chore
summary: Switch daily e2e to Automatic Kubernetes version.
```
=> [ci] Switch daily e2e to Automatic Kubernetes version

docs/documentation/_data/deckhouse-alerts.yml, modules/031-ceph-csi/monitoring/prometheus-rules/deprecated-module-alert.yaml
This PR implements minor edits to the alert about the deprecated `ceph-csi` module.
```changes
section: docs
type:  chore
summary: Edited description for the ceph-csi alert.
```
=> [docs] Edit description for the ceph-csi alert

modules/042-kube-dns/templates/service.yaml
The d8-kube-dns-redirect service has been reverted.
The d8-kube-dns-redirect service was used as a forwarding server for node-local-dns. During an upgrade, this service is removed and old instances of local-dns continue to access the non-existent forward server. However, because the service was not responding, and due to the behavior of the cache plugin, specifically the serve_stale 1h verify setting, it waited up to 5 seconds for a response from the forwarding server. This delay can be critical for latency-sensitive applications such as web frontends.
On large clusters, updating node-local-dns pods can take 10-15 minutes, at which point local dns is left without forwarding servers, which can be undesirable.
```changes
type: fix
summary: Fixed release upgrade issue with …
```
=> [kube-dns] The d8-kube-dns-redirect service has been restored

docs/site/pages/code/documentation/admin/install/PLATFORM_INSTALLATION_RU.md
Fixed installations manifests at Deckhouse Code documentation.
```changes
section: docs
type: fix 
summary: Fixed installations manifests at Deckhouse Code documentation.
```
=> [docs] Fixed installations manifests at Deckhouse Code documentation

ee/be/modules/350-node-local-dns/monitoring/grafana-dashboards/kubernetes-cluster/dns-node-local.json, modules/042-kube-dns/monitoring/grafana-dashboards/kubernetes-cluster/dns/dns-coredns.json
This change removes outdated panels from the CoreDNS dashboard. These panels were consistently showing "No data" because certain metrics (`coredns_forward_*`) have been deprecated in recent versions of CoreDNS.  
Reference: [CoreDNS forward plugin - deprecated metrics](https://coredns.io/plugins/forward/#:~:text=The%20following%20metrics%20have%20recently%20been%20deprecated)
Not necessarily.  
```changes
type: fix
summary: Removed CoreDNS dashboard panels referencing deprecated metrics (`coredns_forward_*`).
=> [kube-dns] Update CoreDNS dashboards

modules/040-node-manager/images/machine-controller-manager/werf.inc.yaml
this mr allow to use v0.36.0-flant.23 version mcm which use node-manager bootstrap token node instead mcm
resolve [this](https://github.com/deckhouse/deckhouse/issues/12233) issue
```changes
type: fix
summary: change mcm version to use node manager token instead mcm
```
=> [node-manager] Change mcm version to use node manager token instead mcm

modules/040-node-manager/images/cluster-autoscaler/patches/1.30/004-set-priorities-for-to-de-deleted-machines-and-clean-annotation.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.30/README.md, modules/040-node-manager/images/cluster-autoscaler/patches/1.31/004-set-priorities-for-to-de-deleted-machines-and-clean-annotation.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.31/README.md, modules/040-node-manager/images/cluster-autoscaler/patches/1.32/004-set-priorities-for-to-de-deleted-machines-and-clean-annotation.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.32/README.md, modules/040-node-manager/images/cluster-autoscaler/patches/README.md, testing/cloud_layouts/script.d/wait_cluster_ready/test_autoscaler.sh
Patch autoscaler 1.30-1.32 to support our MCM.
New autoscaler works with new version MCM which select nodes for deleting from annotation `node.machine.sapcloud.io/trigger-deletion-by-mcm` This annotation does not support by our MCM, and we should set deleting priority with annotation `machinepriority.machine.sapcloud.io` for right deletion order.
We set priority for machines and keep `node.machine.sapcloud.io/trigger-deletion-by-mcm` annotation for calculation replicas, but we need to clean deleted machines from annotation in refresh function for keeping up to date annotation value to avoid drizzling replicas count in machine deployment.
After our previous patch https://github.com/deckhouse/deckhouse/pull/13391 cluster autoscaler periodically scale up and scale down machine deployments, …
=> [node-manager][autoscaler] Patch autoscaler 1.30-1.32 to support our MCM

.github/workflow_templates/k8s-autoupdate.yml, .github/workflows/k8s-autoupdate.yml
Now in automatic update k8s does not pass
Fix this
```changes
section: ci
type: fix
summary: DCO pass in K8s autoupdates.
```
=> [ci] Fix DCO on K8s autoupdates

dhctl/pkg/kubernetes/actions/converge/master_node_group_controller.go
Do not create a local-converger lock for commanderMode
When using commander dhctl should not create a local-converger lock it is intended for manual converge only
```changes
section: dhctl
type: fix
summary: Do not create a local-converger lock for commanderMode
impact: 
```
=> [dhctl] Do not create a local-converger lock for commanderMode

modules/040-node-manager/images/cluster-autoscaler/patches/1.28/001-go-mod.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.29/001-go-mod.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.30/001-go-mod.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.31/001-go-mod.patch, modules/040-node-manager/images/cluster-autoscaler/patches/1.32/001-go-mod.patch, modules/040-node-manager/images/cluster-autoscaler/werf.inc.yaml
this pr fix cluster-autoscaler CVE vulnerabilities
bump packages versions to fix CVE vulnerabilities.
clusterAutoscaler128 https://defectdojo.flant.com/test/19532
v1.28.3 cannot to be bumped and make build because fixed CVE already on minor version 1.29.13 or 1.29.14
```
go.mod (gomod)
Total: 6 (UNKNOWN: 0, LOW: 0, MEDIUM: 3, HIGH: 3, CRITICAL: 0)
┌──────────────────────────────────────────────────────────────┬────────────────┬──────────┬──────────┬───────────────────┬──────────────────────────────────┬─────────────────────────────────────────────────────────────┐
│                           Library                            │ Vulnerability  │ Severity │  Status  │ Installed Version │          Fixed Version           │                            Title                            │ …
```
=> [cluster-autoscaler] Cluster-autoscaler CVE vulnerabilities fixes

modules/002-deckhouse/template_tests/module_test.go, modules/002-deckhouse/templates/deployment.yaml
Add toleration to allow dh pod to be scheduled to nodes with `node.deckhouse.io/uninitialized` taint
Sometimes, when custom tolerations was set to dh deployment, and nodes have `node.deckhouse.io/uninitialized` taint, it couldn't be remover because of no deckhouse pod can be scheduled at the time. This toleration allows to schedule dh pods to such nodes, so it could remove taints later.
```changes
type: fix
summary: Add toleration to dh deployment.
```
=> [deckhouse] Update dh tolerations

docs/documentation/_data/conversions.yml, ee/se/modules/380-metallb/openapi/conversions/v2.yaml
Added conversion rule to guide users in removing `addressPool` elements with `layer2` protocol for the new version upgrade.
Informs users via documentation about the need to remove deprecated `layer2` `addressPool` elements, ensuring a smooth transition to the new version and preventing configuration issues.
```changes
type: chore
summary: Added a description of the conversions.
```
=> [metallb] Add a description of the conversions

docs/site/pages/stronghold/documentation/admin/platform-management/node-management/ADVANCED_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/node-management/ADVANCED.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/node-management/ADVANCED_RU.md, modules/007-registrypackages/images/containerd/scripts/install, modules/007-registrypackages/images/containerd/werf.inc.yaml, modules/040-node-manager/docs/FAQ.md, modules/040-node-manager/docs/FAQ_RU.md
Return `shim-runc-v1` for backward compatibility. 
Update docs for using `shim-runc-v2` in ngc for GPU.
Related to #13205 .
`shim-runc-v1` was specified in the NGC example for GPU nodes in our [documentation](https://github.com/deckhouse/deckhouse/blob/4ceec52c4f37b5e214cc726fe1c4ae417be138a2/docs/site/pages/virtualization-platform/documentation/admin/platform-management/node-management/ADVANCED.md?plain=1#L185).
Need to return `shim-runc-v1` to registrypackages for backward compatibility.
```changes
section: candi, docs
type: fix
summary: Return `shim-runc-v1` for backward compatibility. 
```
=> [registrypackages] return shim-runc-v1

ee/se-plus/modules/030-cloud-provider-zvirt/images/cloud-data-discoverer/src/discoverer.go, ee/se-plus/modules/030-cloud-provider-zvirt/images/cloud-data-discoverer/src/ovirt_logger.go
oVirt have own wrapper for `log` logger and in its constructor `log` is mentioned as optional, however wrapper's constructor panics if it is not provided here: https://github.com/oVirt/go-ovirt-client-log/blob/main/go_logger.go#L17
This PR adds our own oVirt logger wrapper and fixes panic. 
```changes
type: fix
summary: fix zvirt cloud-discoverer panic
```
=> [cloud-provider-zvirt] fix cloud data discoverer logger

.golangci.yaml, global-hooks/discovery/kubernetes_version.go
Add `usestdlibvars` linter and fix _magic values_.
The `usestdlibvars` linter identifies instances where hardcodes literals can be replaced with well-defined constants from Go's standard library (e.g "GET" -> http.MethodGet).
This practice enhances code clarity, reduces the risk of errors, and aligns with Go's idiomatic standards.
```changes
type: chore
summary: add usestdlibvars lint and fix errors
```
=> [linting] Add usestdlibvars lint and fix errors

.werf/werf-release-channel.yaml
Fix release-channel image build
```changes
section: ci
type: fix
summary: Fix release-channel build.
```
=> [ci] Fix release-channel build

candi/terraform_versions.yml, ee/se-plus/modules/030-cloud-provider-zvirt/hooks/to_tofu_migrate_metric.go, modules/040-terraform-manager/templates/terraform-auto-converger/deployment.yaml
In the previous pr https://github.com/deckhouse/deckhouse/pull/13386/files we forget to enable migrator to opentofu states from terraform and did not add hook for fire alert when cluster has terraform state.
Alse we added comment in `terraform_versions.yaml` for providers that using terraform with instruction to migrate to opentofu.
For cloud-provider-dynamics we did not add migrator because we do not have working installation with this provider.
We have Zvirt installation on terraform. We need to enable migrator for smooth migration from terraform to opentofu.
Also we added comment in `terraform_versions.yaml` to prevent forgetting enable migrator and metrics hook when we migrate from terraform to opentofu
```changes
type: chore
summary: Enable migrator from …
```
=> [cloud-provider-zvirt] Enable migrator from terraform state to opentofu

modules/810-documentation/templates/configmap.yaml, modules/810-documentation/templates/deployment.yaml, modules/810-documentation/templates/ingress.yaml, modules/810-documentation/templates/rbac-to-us.yaml, modules/810-documentation/templates/service.yaml, modules/810-documentation/templates/vertical-pod-autoscaler.yaml
Added TLS encryption via kube-rbac-proxy between ingress-nginx and documentation pod
To implement it, the following changes are made:
- Nginx in the documentation container listens only to 127.0.0.1:8080, external communication is done via kube-rbac-proxy on port :8443
- The service (clusterIP) "documentation-builder" has been deleted because it is not in use
Some customers may have had problems with security scanners due to the lack of TLS encryption at the pod with documentation
```changes
type: chore
summary: Added TLS between ingress-nginx controller and documentation.d8-system pod.
```
=> [ingress-nginx] Added TLS proxy-pass to documentation.d8-system pod

deckhouse-controller/pkg/controller/module-controllers/source/controller.go, deckhouse-controller/pkg/controller/module-controllers/source/controller_test.go
It is necessary to add validation according to `RFC 1123` for module names added to `ModuleSource`, as well as to cover with unit tests.
`RFC 1123` defines the rules for names used in _DNS_, including subdomain names. According to this standard, a name must:
- Consist of lowercase letters (a–z), digits (0–9), hyphens (-), and dots (.).
- Start and end with an alphanumeric character.
- Be no more than 253 characters in length.
If module names do not conform to these requirements, it can lead to errors when creating resources, issues with _DNS_ name resolution, and other unpredictable behaviors in the cluster.
Adding validation of module names according to `RFC 1123` allows:
- Preventing the creation of modules with invalid names.
- Ensuring compatibility with other Kubernetes components …
=> [deckhouse-controller] Add validation according to RFC 1123 for module names added to ModuleSource

docs/documentation/_includes/SUPPORTED_VERSIONS.liquid
This pull request updates the logic in the `SUPPORTED_VERSIONS.liquid` file to correctly identify the default Kubernetes version. The change replaces the comparison of the first element (`k8sItem[0]`) with the default version, using a more explicit check on the `default` property of the second element (`k8sItem[1]`).
* [`docs/documentation/_includes/SUPPORTED_VERSIONS.liquid`](diffhunk://#diff-e44f23e14a0796fdb27cc05a99f779755bfdfeaaab2ef1d82ba21e9512253405L233-R233): Updated the conditional logic to check the `default` property of `k8sItem[1]` instead of comparing `k8sItem[0]` with the default version, improving clarity and accuracy.
```changes
section: docs
type: fix
summary: Fixed generation of label about default Kubernetes version in the table with supported versions.
impact_level: …
```
=> [docs] Fix label about default Kubernetes version in the table with supported versions

dhctl/pkg/system/node/ssh/frontend/upload-script.go, dhctl/pkg/util/tar/tar.go, dhctl/pkg/util/tar/tar_test.go
Implement native tar instead of using binary `tar`
Reduce dependencies, needed for `dhctl` run
```changes
section: dhctl
type: feature
summary: Replace call of binary tar to native golang tar implementation in dhctl.
```
=> [dhctl] Implement native tar

candi/cloud-providers/aws/layouts/standard/base-infrastructure/main.tf, candi/cloud-providers/aws/layouts/with-nat/base-infrastructure/main.tf, candi/cloud-providers/aws/terraform-modules/master-node/main.tf, candi/cloud-providers/aws/terraform-modules/static-node/main.tf, candi/cloud-providers/aws/terraform-modules/versions.tf, candi/terraform_versions.yml, modules/040-terraform-manager/images/terraform-manager-aws/patches/001-go-mod.patch, testing/cloud_layouts/EKS/WithoutNAT/infra.tf.tpl
This PR bumps terraform-provider-aws to 5.83.1
To support new AWS Region `ap-southeast-7`
Region `ap-southeast-7` is available and valid for cluster bootstrap.  
```changes
type: fix
summary: bump terraform-provider-aws to 5.83.1
```
=> [cloud-provider-aws]: bump terraform-provider-aws to 5.83.1

modules/000-common/images/kube-rbac-proxy/patches/001-stale-cache.patch
We use `kube-rbac-proxy` to access prom exporters. ~~Earlier we added staleCache mechanism which caches authorization permission in case kuve-api is unavailable.
Now we added backoff mechanism that blocks access to kube-api with exponential timeout in case kube-api is unavailable. So, if kube-rbac-proxy fails to connect to kube-api, the next 5 seconds of attempts will be blocked and authorization permission will be taken from cache at once. If the attempt fails again, the timeout will be extended. Maximum timeout is 5 minutes~~
Previously there was a long timeout in kube-api client, which caused prom exporters to become unavailable if kube-api became unavailable. Now timeout is set to 3 seconds, after that stale cache will be used.
~~Before this change, kube-rbac-proxy tried to access …
=> [common][kube-rbac-proxy] stale cache request timeout

go_lib/hooks/storage_class_change/hook.go
Because of metrics collector inner logic we expire all groups in grouped metrics before add them
If we remove group in this hook - we can receive multiple metrics at the same time
Using group in this case - redundant
```changes
type: fix
summary: fix overwrite metrics in storage class change hook
```
=> [deckhouse-controller] Remove metric group from storage class change hook

docs/site/_includes/getting_started/global/partials/select_revision.html.liquid
This pull request includes a minor update to the `select_revision.html.liquid` file to refine the conditions for setting the `active` class.
* [`docs/site/_includes/getting_started/global/partials/select_revision.html.liquid`](diffhunk://#diff-357ad82a89b0d4877517cc8bed968343739b23ad3b33c8337bb83147bca30aacL113-R113): Updated the conditional logic to ensure that the `active` class is applied only when the revision is `ee` and both `page.ee_only` is `true` and `page.se_support` is not `true`.
```changes
section: docs
type: fix
summary: Removed unnecessary blocks with commands on the installation page of GS.
```
=> [docs] Remove unnecessary blocks with commands on the installation page of GS.

modules/400-descheduler/crds/deschedulers.yaml, modules/400-descheduler/crds/doc-ru-deschedulers.yaml, modules/400-descheduler/hooks/get_crds.go, modules/400-descheduler/hooks/get_crds_test.go, modules/400-descheduler/hooks/internal/v1alpha2/descheduler.go, modules/400-descheduler/openapi/openapi-case-tests.yaml, modules/400-descheduler/openapi/values.yaml, modules/400-descheduler/template_tests/module_test.go, modules/400-descheduler/templates/configmap.yaml
Closes #13172
This pr allow to add evictLocalStoragePods option as boolean parameters in descheduler cr, ex.
```
---
apiVersion: deckhouse.io/v1alpha2
kind: Descheduler
metadata:
name: low-node-utilization
spec:
evictLocalStoragePods: true
strategies:
lowNodeUtilization:
enabled: true
```
```
kubectl -nd8-descheduler get cm descheduler-policy -oyaml
apiVersion: v1
data:
policy.yaml: |
apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
- name: low-node-utilization
pluginConfig:
- name: "DefaultEvictor"
args:
evictLocalStoragePods: true
...
```
this pr allow edit global parameters in used strategies in descheduler cr
```changes
type: feature
summary: add crd descheduler global parameters
```
=> [descheduler] Add global parameters to Descheduler CRD

modules/300-prometheus/templates/aggregating-proxy/configmap.yaml
When a user requests a large metrics range, the query frontend splits the request into subrequests of a configured duration (24h by default), executes them in parallel, and caches the result. The cache, however, is useless because almost every query starts with the current timestamp; hence, splitting the entire time range into 24h has no positive outcome, as the subrequests always have different caching keys.
This can be fixed by enabling this option:
```
[align_queries_with_step: <boolean> | default = false]
```
making subrequests have a predictable range, thus reusable while caching.
This change drastically improves caching of the wide range requests.
The option, described above, was disabled explicitly for an unknown reason.
```changes
type: fix
summary: improve …
```
=> [prometheus] Improve prometheus response caching

ee/modules/450-network-gateway/images/dnsmasq/prepare-config.py, ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml, ee/modules/450-network-gateway/images/snat/iptables-loop.py
Fix python path in the network-gateway components.
dhcp server from network-gateway cannot start.
```
"reason": "StartError",
"message": "failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: \"/usr/bin/python3\": permission denied: unknown",
"labels": {
"io.kubernetes.container.name": "init",
"io.kubernetes.pod.name": "dhcp-0",
"io.kubernetes.pod.namespace": "d8-network-gateway",
"io.kubernetes.pod.uid": "0ad6859e-edc7-4a76-bab8-b7c5cb9d605c"
},
```
```changes
section: network-gateway
type: fix
summary: Fix python path
```
=> [network gateway] Fix python path

.werf/defines/version-map.tmpl, .werf/werf-version-map.yaml
Added additional logic to handle empty versions. This allows inheritance of CE settings but leaves the possibility to reduce the number of supported kube versions.
This will reduce the number of modified files in cse.
```changes
section: ci
type: chore
summary: moved filter from cse edition when rendering parse_version_map
```
=> [ci] moved filter from cse edition when rendering parse_version_map

ee/se/modules/380-metallb/hooks/delete-deprecated-crd.go, ee/se/modules/380-metallb/hooks/delete-deprecated-crd_test.go
Move the global hook to remove CRD `addresspools.metallb.io` to the `d8-metallb` module.
PR #12453 implements the removal of the `addresspools.metallb.io` CRD. But if the customer uses its own `metallb` module, the hook removes its CRD too. Now hook removes CRD only when `d8-metallb` module is enabled.
The problem affects CE edition users after upgrading to version 1.69.
```changes
type: fix
summary: Fixed deprecated CRD addresspools.metallb.io deletion.
```
=> [metallb] fix CRD addresspools.metallb.io deletion

testing/cloud_layouts/EKS/WithoutNAT/infra.tf.tpl
Update EKS cluster creation config for e2e testing configuration.
Tests do not work without it.
For pre-release testing.
```changes
section: ci
type: fix
summary: Update EKS test config.
```
=> [ci] Update EKS test config

modules/500-openvpn/templates/openvpn/configmap.yaml
Adding the `BF-CBC` cipher to the `data-ciphers-fallback` parameter.
Without this fix, the e2e test failed with an error: `OpenVPN versions before 2.5 defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.`
Broken e2e-tests can interfere with the development process.
```changes
type: fix
summary: Ciphers `BF-CBC` has been added to the options `data-ciphers-fallback`.
```
=> [openvpn] Fix e2e-tests

candi/version_map.yml
Updated d8 cli to latest stable
```changes
section: candi
type: chore
summary: Update Deckhouse CLI to 0.12.1
```
=> [candi] Update Deckhouse CLI to 0.12.1

deckhouse-controller/pkg/controller/module-controllers/source/controller.go, deckhouse-controller/pkg/controller/module-controllers/source/controller_test.go
[Backport of PR](https://github.com/deckhouse/deckhouse/pull/13543)
moduleName is limited to 64 characters and, it is necessary to add validation according to `RFC 1123` for module names added to `ModuleSource`, as well as to cover with unit tests.
`RFC 1123` defines the rules for names used in _DNS_, including subdomain names. According to this standard, a name must:
- Consist of lowercase letters (a–z), digits (0–9), hyphens (-), and dots (.).
- Start and end with an alphanumeric character.
- Be no more than 253 characters in length.
If module names do not conform to these requirements, it can lead to errors when creating resources, issues with _DNS_ name resolution, and other unpredictable behaviors in the cluster.
Adding validation of module names according to `RFC 1123` allows:
- …
=> [deckhouse-controller] Add validation according to RFC 1123 for module names added to ModuleSource (backport)

candi/version_map.yml
fix https://github.com/deckhouse/deckhouse/pull/13357
Fix double preview version in candi/version_map
There should only be one preview version
```changes
section: candi
type: fix
summary: fix double preview version in candi/version_map
impact: 
```
=> [chore] candi/version_map fix

modules/040-control-plane-manager/hooks/audit_policy.go
Fix incorrect group in audit rules for virtualization.
```changes
type: chore
summary: fix audit policy rules for virtualization
```
=> [control-plane-manager] fix audit policy for virtualization

tools/docs/run_external_modules.sh
This pull request introduces a new script, `run_external_modules.sh`, to streamline the management and documentation of external modules for the project. The script provides functionality for setting up module directories, preparing documentation and CRDs, managing OpenAPI specs, and running a local Hugo server for documentation previews.
```changes
section: tools
type: chore
summary: [tools][docs] Add script to run documentation of an external module.
```
=> [tools][docs] Add script to run documentation of an external module

docs/documentation/_data/deckhouse-ports.yml, modules/340-monitoring-ping/templates/daemonset.yaml
Changed the container port kube-rbac-proxy of DaemonSet monitoring-ping from 4229 to 4289
The port overlaps with the health check probe of the csi-nfs module.
The port overlaps with the health check probe of the csi-nfs module
```changes
type: fix
summary: Changed the container port kube-rbac-proxy of DaemonSet monitoring-ping from 4229 to 4289
```
=> [monitoring-ping] changed metrics port monitoring-ping 

deckhouse-controller/crds/module-update-policy.yaml
This action we are gradually getting rid of the deprecated version (`ModuleUpdatePolicy - v1alpha1`).
In this case the backup mechanism has been modified so that it retains the current resource versions.
The `v1alpha1` lifecycle is coming to an end, so the validation webhook prohibits these resources from being deployed to the cluster. Since the old resource is deprecated, we must backup the updated `v1alpha2` resource and keep data of actual version.
After successful data migration, we observe in the CRD:
```
storedVersions:
- v1alpha2
```
Also, I attach `d8 backup` logs before and after the change (only related to `ModuleUpdatePolicy`):
```
W0527 14:54:16 [warnings.go:70] ModuleUpdatePolicy v1alpha1 deprecated (repeated x30)
```
```
I0527 15:07:04 [request.go:729] Client throttling: GET …
```
=> [deckhouse-controller]  Convert MUP CRD v1alpha2 storage

ee/modules/015-admission-policy-engine/templates/ratify/rbac-for-us.yaml
The namespace field in RoleBinding for admission-policy-engine is superfluous
Bringing application templates to a working state
```changes
type: fix
summary: remove redundant namespace from RoleBinding
```
=> [admission-policy-engine] remove namespace from RoleBinding

docs/site/backends/docs-builder-template/i18n/en.yaml, docs/site/backends/docs-builder-template/i18n/ru.yaml, docs/site/backends/docs-builder-template/layouts/partials/openapi/format-configuration.html
Display “No additional parameters are available for this module” on configuration pages for external modules with no defined parameters.
When a docs/CONFIGURATION.md file exists but openapi/config-values.yaml properties list is empty, the configuration page would render completely blank, leaving users confused. This change adds a clear message so that empty-state pages give meaningful feedback.
```changes
section: docs
type: feature
summary: Display “No additional parameters are available for this module” on configuration pages for external modules with no defined parameters.
```
=> [docs] Add empty-state message to external module configuration pages

deckhouse-controller/crds/doc-ru-module-pull-override.yaml, deckhouse-controller/crds/module-pull-override.yaml
This action we are gradually getting rid of the deprecated version (`ModulePullOverride - v1alpha1`).
The `v1alpha1` lifecycle is coming to an end, so the validation webhook prohibits these resources from being deployed to the cluster. Since the old resource is deprecated, we must backup the updated `v1alpha2` resource and keep data of actual version.
After successful data migration, we observe in the CRD:
```
storedVersions:
- v1alpha2
```
Also, I attach `d8 backup` logs before and after the change (only related to `ModulePullOverride`):
```
W0527 14:54:16 [warnings.go:70] ModulePullOverride v1alpha1 deprecated (repeated x30)
```
```
I0527 15:07:04 [request.go:729] Client throttling: GET v1alpha2/modulepulloverrides (2.78s)
```
The problem:
- The cluster uses `ModulePullOverride` version …
=> [deckhouse] change storage for MUP CRD

docs/site/_includes/getting_started/global/partials/NOTICES.liquid
This pull request updates the `NOTICES.liquid` file to include a new informational alert specific to the "red" platform code. 
Documentation update:
* [`docs/site/_includes/getting_started/global/partials/NOTICES.liquid`](diffhunk://#diff-6c16be6010fc68740657eca2822d958961d1a89811301dcccdcbf12248d33051R7-R11): Added an informational alert advising users to pre-create virtual machines with required parameters before installing Deckhouse Kubernetes Platform in the "red" virtualization environment.
```changes
section: docs
type: fix
summary: Added notice about creating VMs in the RED virtualization.
```
=> [docs] Add notice about RED virtualization in GS

docs/site/_assets/css/docs.scss, docs/site/_assets/js/customscripts.js
Correct numbers and padding.
Fix https://github.com/deckhouse/deckhouse/pull/13161
```changes
section: docs
type: chore
summary: Correct numbers and padding. Fix #13161.
```
=> [docs] Correct numbers and padding

docs/documentation/_tools/modules_generate_configuration.sh, docs/documentation/pages/DECKHOUSE_CONFIGURE_GLOBAL.md, docs/documentation/pages/DECKHOUSE_CONFIGURE_GLOBAL_RU.md, docs/documentation/werf-git-section.inc.yaml
Added global module conversions at documentation.
```changes
section: docs
type: chore
summary: Added global module conversions at documentation.↓
```
=> [docs] Added global module conversions at documentation

ee/se/modules/380-metallb/.dmtlint.yaml, ee/se/modules/380-metallb/templates/monitoring.yaml
Fixed import logic of MetalLB dashboards
Now BGP dashboard will be added only when BGP balancing is enabled, otherwise L2 dashboard will be added
When the client does not enable BGP balancing in the MetalLB module, the module still imports the BGP dashboard
But there are no metrics (No Data) from BGP, this can be misleading for the client
```changes
type: fix
summary: BGP grafane dashboard is deployed only when BGP balancing is enabled 
```
=> [metallb] Fix of the logic of dashboard imports

.github/scripts/python/e2e-commander-clean/main.py, .github/workflow_templates/e2e-autoclean.yml, .github/workflows/e2e-autoclean.yml
Now when closing or merging a pull request, running clusters remain
Make E2E clusters delete when closing or merging a pull request
```changes
section: ci
type: feature
summary: Make E2E clusters delete when closing or merging a pull request.
```
=> feat: delete cluster on pr closed

dhctl/pkg/config/meta.go, dhctl/pkg/config/meta_test.go
Alert the user with an error about the CA certificate when the local registry is configured with the HTTP scheme on `dhctl bootstrap` phase
Fix [issue](https://github.com/deckhouse/deckhouse/issues/10834) 
When run `dhctl bootstrap` with the HTTP scheme and CA on InitConfiguration, an unobvious behavior occurs (containerd have different [configuration](https://github.com/deckhouse/deckhouse/blob/e38ab2ee95f102629f0c93145f4f74fbd05c7b83/candi/bashible/common-steps/node-group/032_configure_containerd.sh.tpl#L148-L155) for both params)
```changes
section: dhctl
type: fix
summary: Add Local Registry Configuration Check to Installation Process
```
=> [dhctl] Add Local Registry Configuration Check to Installation Process

dhctl/pkg/server/rpc/dhctl/abort.go, dhctl/pkg/server/rpc/dhctl/bootstrap.go, dhctl/pkg/server/rpc/dhctl/check.go, dhctl/pkg/server/rpc/dhctl/commander_attach.go, dhctl/pkg/server/rpc/dhctl/commander_detach.go, dhctl/pkg/server/rpc/dhctl/converge.go, dhctl/pkg/server/rpc/dhctl/destroy.go, dhctl/pkg/server/rpc/dhctl/service.go
When encountering panic or errors, always read the last state directly from the cache (currently implemented on disk). Do not rely on phasedExecutionContext and its internal state. This is particularly important with the introduction of cancellations when a task can be interrupted between phases.
```changes
section: dhctl
type: chore
summary: read dchtl server state from disk on errors
```
=> [dhctl] chore(dhctl-for-commander): make dhctl server state extractor more reliable

testing/cloud_layouts/script.sh
Fix incorrect update image in e2e Static test script.
```changes
section: ci
type: fix
summary: Fix incorrect update image in e2e Static test script.
```
=> [ci] Fix incorrect update image in e2e script

docs/site/backends/registry-modules-watcher/internal/backends/pkg/registry-scanner/process.go
Improved Logging for Module Processing
We've added info-level logging to module processing functions to improve visibility. Previously, there was no way to track which modules were being processed in real-time, making debugging difficult. 
The new logs now provide:
- Real-time visibility into currently processing modules
- Clear tracking of module execution flow
- Immediate feedback during operations
Problems Solved:
- Eliminated blind spots in module processing
- Enabled real-time monitoring of operations
- Improved debugging capabilities
```changes
section: docs
type: feature
summary: Added info level logs
```
=> [docs] Add logs for modules processing

docs/site/.helm/templates/20-ingress.yaml
Update Ingress paths to use ImplementationSpecific pathType.
Update apiVersion for DexAuthenticator to deckhouse.io/v1
```changes
section: docs
type: chore
summary: Update Ingress paths to use ImplementationSpecific pathType and update apiVersion for DexAuthenticator
```
=> [docs] Update Ingress paths to use ImplementationSpecific pathType and update apiVersion for DexAuthenticator

.github/ci_templates/build.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml
Fix release images publish.
```changes
section: ci
type: fix
summary: Fix release images publish.
```
=> [ci] Fix release images publish

deckhouse-controller/pkg/controller/deckhouse-release/controller.go, deckhouse-controller/pkg/controller/deckhouse-release/controller_test.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/clear-data-after-deploy.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/clear-data-after-deploy.yaml
This change ensures that the `Message` field in `DeckhouseReleaseStatus` is cleared when a Deckhouse release transitions to the `Deployed` phase. This prevents outdated or misleading status messages from persisting in the `DeckhouseRelease` resource.
The issue arises because:
- The `Message` field is not automatically reset when the release moves to the `Deployed` phase.
- In cases where multiple reconciliation processes run concurrently, an outdated message might remain in the status, even after the release is successfully deployed.
**Changes**
- Clear the `Message` field in `DeckhouseReleaseStatus` when the release reaches the `Deployed` phase and `Message` is empty.
- Ensure the status reflects the actual deployment state consistently.
- Prevents user confusion caused by outdated …
=> [deckhouse-controller] Clean DeckhouseRelease message when release deployed

candi/bashible/bb_node_name.sh.tpl
fix [12996](https://github.com/deckhouse/deckhouse/pull/12996)
Use node name from kubelet certificate, if the node is bootstrapped and there is a certificate.
previous method was more complicated and did not work in kubernetes 1.32+
```changes
section: candi
type: fix
summary: bashible bb-discover-node-name use node name from kubelet certificate
impact: 
```
=> [candi]  Use node name from kubelet certificate

docs/documentation/_data/modules/modules-addition.json, docs/site/backends/docs-builder-template/data/modules_all.json
Add read-only mode comments for the console module editions.
```changes
section: docs
type: chore
summary: Add read-only mode comments for the console module editions
```
=> [docs] Add read-only mode comments for the console module editions

.werf/werf-release-channel.yaml
Fix kubernetes version info in the release file.
Now version.json in the release-channel image cannot have proper info about k8s versions (current and auto). That leads to problems with deckhouse update. This PR fixes it.
```changes
section: ci
type: fix
summary: fix kubernetes version info in the release file
```
=> [ci] fix kubernetes version info in the release file

candi/version_map.yml
update k8s patch versions
includes:
https://github.com/deckhouse/deckhouse/pull/13572
```changes
section: candi
type: chore
summary: update k8s patch versions
```
=> Update k8s patch version release 1.70

candi/bashible/common-steps/all/003_disable_swap.sh.tpl
I added a check to the bashible step for the presence of a previously created symlink and where it leads to.
Recreating this symlink every time it is present is unnecessary.
There are clients who have integrity control enabled by inode and the constant re-creation of this symlink triggers the integrity control mechanism.
```changes
section: candi
type: fix
summary: Added a check to the bashible step for the presence of a previously created symlink and where it leads to
```
=> [candi] Update step bashible 003_disable_swap

modules/040-control-plane-manager/monitoring/prometheus-rules/etcd-maintenance.yaml
Use last_over_time to fetch the last available etcd DB size metric if it's missing.
If deckhouse is down due to etcd issues, metrics for etcd DB size become unavailable, breaking our alerts. With last_over_time, we use the latest value from the past 6 hours, so alerts still work even if the metric temporarily disappears.
```changes
type: fix
summary: Use last_over_time to fetch the last available etcd DB size metric if it's missing.
impact: 
```
=> [control-plane-manager] etcd alert last_over_time

deckhouse-controller/pkg/controller/deckhouse-release/controller.go, deckhouse-controller/pkg/controller/deckhouse-release/controller_test.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/clear-data-after-deploy.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/clear-data-after-deploy.yaml
Backport of this [PR](https://github.com/deckhouse/deckhouse/pull/13761)
This change ensures that the `Message` field in `DeckhouseReleaseStatus` is cleared when a Deckhouse release transitions to the `Deployed` phase. This prevents outdated or misleading status messages from persisting in the `DeckhouseRelease` resource.
The issue arises because:
- The `Message` field is not automatically reset when the release moves to the `Deployed` phase.
- In cases where multiple reconciliation processes run concurrently, an outdated message might remain in the status, even after the release is successfully deployed.
**Changes**
- Clear the `Message` field in `DeckhouseReleaseStatus` when the release reaches the `Deployed` phase and `Message` is empty.
- Ensure the status reflects the actual …
=> [deckhouse-controller] Backport: Clean DeckhouseRelease message when release deployed

modules/160-multitenancy-manager/crds/projects.yaml, modules/160-multitenancy-manager/crds/projecttemplate.yaml
Fixed labels for Custom Resource Definitions (CRDs) in the `multitenancy-manager` module:
- `projects.deckhouse.io`
- `projecttemplates.deckhouse.io`
Previously, these resources were incorrectly labeled as belonging to the deckhouse module, although they are actually part of the `multitenancy-manager`.
Incorrect labels in CRDs can lead to:
- Maintenance confusion - it is more difficult to filter resources related to `multitenancy-manager`.
- Errors in automated processes - if scripts or monitoring tools rely on tags, they may not work correctly.
- Inconsistency with documentation - the documentation lists these CRDs as part of the `multitenancy-manager`, but they are labeled differently in the cluster.
```changes
type: fix
summary: fix incorrect labels.module …
```
=> [multitenancy-manager] fix incorrect labels.module value

ee/modules/500-operator-trivy/templates/trivy-server.yaml
Fix #13697
Added a startupProbe to extend the initialization window and allow sufficient time for database downloads:
```yaml
startupProbe:
httpGet:
scheme: HTTP
path: /healthz
port: trivy-http
initialDelaySeconds: 5     # Wait 5s before first check
periodSeconds: 10          # Check every 10s
successThreshold: 1        # 1 successful check = ready
failureThreshold: 60       # Allow up to 10 minutes (60 attempts × 10s)
```
When Trivy downloads security databases over a slow connection (taking more than 105 seconds), the container would repeatedly fail and restart, creating a crash loop. This prevented the pod from ever successfully initializing.
Why This Works:
- Extended Grace Period: The probe now allows 600 seconds (10 minutes) for downloads to complete before failing.
- Health-Checked …
=> [operator-trivy] Add startupProbe

ee/modules/500-operator-trivy/images/report-updater/src/internal/cache/cache.go, ee/modules/500-operator-trivy/images/report-updater/src/internal/web/hook/hook.go, ee/modules/500-operator-trivy/images/report-updater/src/internal/web/server.go
It adds support anon registry creds for bdu updater.
Fixes #13852
```
root@usmanovddd-master-0:~# kubectl logs -n d8-operator-trivy report-updater-6474b9bbf9-2lqw8
2025/06/06 15:22:21 auth config for the '158.160.34.44' registry is empty; using anonymous access
2025/06/06 15:22:21 initialize BDU dictionary
2025/06/06 15:22:21 download BDU image
2025/06/06 15:22:21 BDU dictionary dated 2025-06-06 12:26:19.686831909 +0000 UTC has been applied
2025/06/06 15:22:21 server is starting to listen on '0.0.0.0:40443' ...
```
```changes
type: fix
summary: Add support anon registry creds for bdu updater.
```
=> [operator-trivy] support anon registry creds for bdu updater

modules/500-dashboard/templates/api/deployment.yaml, modules/500-dashboard/templates/api/rbac-for-us.yaml, modules/500-dashboard/templates/metrics-scraper/service.yaml
After refactor for DMT Lint https://github.com/deckhouse/deckhouse/commit/c5777e4980e77029a78801ac45325b68ff0429e6#diff-67adf522866f2751b19b320f5a73171647f713b54b22faacd3345f44a6082729 add named port to svc metrics-scraper
Named port in metrics-scraper svc generate error in api-dashboard and metrics not display
```
E0509 17:09:48.742991       1 manager.go:96] Metric client health check failed: the server is currently unable to handle the request (get services metrics-scraper). Retrying in 30 seconds.
E0509 17:10:18.751070       1 manager.go:96] Metric client health check failed: the server is currently unable to handle the request (get services metrics-scraper). Retrying in 30 seconds.
E0509 17:10:48.756521       1 manager.go:96] Metric client health check failed: the server is currently …
```
=> [dashboard] Fix display workload metrics on ui kubernetes-dashboard

candi/bashible/common-steps/all/064_configure_kubelet.sh.tpl
Backward compatibility of the numfmt_to_bytes function for python2
step stopped working with python2
```changes
section: candi
type: fix
summary:  memory.available calculation python2 fix
impact:
```
=> [candi] memory.available calculation python2 fix

modules/021-cni-cilium/images/bin-cilium/patches/006-add-pod-prioroty-management.patch
Fixed cleanup logic in cilium 1.17 when removing cilium endpoint from an cilium operator priority filter.
Without correct cleanup cilium endpoint from operator priority filter may be situation where new cilium endpoint can't reuse IP4 address from previously removed cilium endpoint.
```changes
type: fix
summary: fixed bug in cilium 1.17 operator priority filter
```
=> [cilium] fix bug in cilium operator priority filter

modules/039-registry-packages-proxy/module.yaml, modules/040-control-plane-manager/module.yaml, modules/040-terraform-manager/module.yaml, modules/302-vertical-pod-autoscaler/module.yaml, modules/400-descheduler/module.yaml, modules/470-chrony/module.yaml, modules/800-deckhouse-tools/module.yaml
Describe module stage
Declaring explicit stage for core modules
Adds module stage visibility for users
```changes
section: chrony, control-plane-manager, deckhouse-tools, descheduler, node-manager, registry-packages-proxy, terraform-manager, vertical-pod-autoscaler
type: fix 
summary: Added module stage in module manifest
impact: 
```
=> [core] Describe module stage

modules/021-cni-cilium/docs/README.md, modules/021-cni-cilium/docs/README_RU.md
Change Using CiliumClusterwideNetworkPolicies section (cni-cilium).
```changes
section: docs
type: chore
summary: Change Using CiliumClusterwideNetworkPolicies section (cni-cilium).
```
=> [docs] Change Using CiliumClusterwideNetworkPolicies section

go_lib/hooks/to_tofu_migrate_metric/hook.go, modules/000-common/hooks/to_tofu_migrate_metric_test.go
to_tofu_migrate_metric hook does not respect hybrid clusters.
Deckhouse stuck in error in hybrid clusters.
Deckhouse stuck in error in hybrid clusters.
```changes
type: fix
summary: Handle hybrid clusters case in the to_tofu_migrate_metric hook
```
=> [go_lib] Handle hybrid clusters case in the to_tofu_migrate_metric hook

ee/modules/610-service-with-healthchecks/template_tests/module_test.go, ee/modules/610-service-with-healthchecks/templates/agent/daemonset.yaml
Changed port for kube-rbac-proxy  container in agent DaemonSet.
Conflict with the cni-nfs module needs to be resolved.
There is already a conflict in active clusters with the cni-nfs module.
```changes
type: fix
summary: change port kube-rbac-proxy in agent DaemonSet
```
=> [service-with-healthchecks] change port kube-rbac-proxy

modules/800-deckhouse-tools/templates/deployment.yaml
as described [here](https://github.com/kubernetes/kubernetes/issues/72519) there are some issues with removing `serviceAccountName` field from the deployment.
So I add an empty value, it will be removed in the next release
After updating release, the field did not disappear from the deployment
```
Warning  FailedCreate  42s (x16 over 3m17s)  replicaset-controller  Error creating: pods "deckhouse-tools-55c9768cfc-" is forbidden: error looking up service account d8-system/deckhouse-tools: serviceaccount "deckhouse-tools" not found
```
problem occurred after this [change](https://github.com/deckhouse/deckhouse/pull/11962/files#diff-91ff6ae8e9c32539ebbbbf177dc33d7b8972404d60c63133173b4c7e44b06f55):
```changes
type: fix
summary: deckhouse-tools fix deployment render …
```
=> [deckhouse-tools] fix render deployment

.werf/werf-deckhouse-controller.yaml
Change deckhouse version generation during the build phase
At now we are calculating the deckhouse version for the latest tag. It has 2 cases:
1. Next tag is not created yet but the release branch exists
2. `release-X.Y` branches generates `v1.<tag>.0-release-X.Y.` release version
We can change the logic:
1. Use latest branch, not tag for calculating the next prerelease version
2. Change logic for `release` branches to generate the desired deckhouse version `release-1.69` generate `v1.69.0`
```changes
section: ci
type: fix
summary: Change deckhouse version variable generation
```
=> [chore] deckhouse version generating in CI

docs/documentation/_data/i18n.yml, docs/site/backends/docs-builder-template/i18n/en.yaml, docs/site/backends/docs-builder-template/i18n/ru.yaml
This pull request updates the `conversion_action_message` in the `i18n.yml` file to provide a more detailed explanation of how module configuration versioning and transformations are handled. The new message clarifies the automatic and manual processes for updating the module configuration.
* [`docs/documentation/_data/i18n.yml`](diffhunk://#diff-26a2d3ec2aad6effdacc644931a6b5c9e7c3f7d1643f295f1731946c8193ca3fL114-R121): Enhanced the `conversion_action_message` for both English (`en`) and Russian (`ru`) to include details about automatic transformations during version changes and instructions for manual updates to the `ModuleConfig` resource.
```changes
section: docs
type: fix
summary: Updated conversions message.
```
=> [docs] Update conversions message

ee/modules/500-operator-trivy/.dmtlint.yaml, ee/modules/500-operator-trivy/templates/deployment.yaml, modules/015-admission-policy-engine/.dmtlint.yaml, modules/015-admission-policy-engine/templates/audit-deployment.yaml, modules/015-admission-policy-engine/templates/gatekeeper-deployment.yaml, modules/101-cert-manager/.dmtlint.yaml, modules/101-cert-manager/templates/cert-manager/deployment.yaml
Addendum Liveness and Readiness probes for kube-rbac-proxy
Bringing containers to a single standard of operation
```changes
type: chore
summary: Liveness and Readiness probes for kube-rbac-proxy
```
=> [deckhouse] Liveness and Readiness probes for kube-rbac-proxy

ee/se-plus/candi/cloud-providers/zvirt/openapi/cluster_configuration.yaml, ee/se-plus/modules/030-cloud-provider-zvirt/openapi/values.yaml
This PR relaxes UUID validation. In current implementation it allows only UUID v4.  
zVirt 4.3 uses UUID v1, which are not compatible with our UUID validation regex. 
```changes
type: fix
summary: fix UUID validation regex
```
=> [cloud-provider-zvirt] fix UUID validation regex

ee/be/modules/350-node-local-dns/.dmtlint.yaml, ee/be/modules/350-node-local-dns/templates/daemonset.yaml, ee/modules/610-service-with-healthchecks/.dmtlint.yaml, ee/modules/610-service-with-healthchecks/template_tests/module_test.go, ee/modules/610-service-with-healthchecks/templates/agent/daemonset.yaml, ee/modules/610-service-with-healthchecks/templates/controller/deployment.yaml, modules/021-cni-cilium/.dmtlint.yaml, modules/021-cni-cilium/templates/_agent-daemonset.tpl, modules/021-cni-cilium/templates/operator/deployment.yaml, modules/036-kube-proxy/.dmtlint.yaml, modules/036-kube-proxy/templates/daemonset.yaml, modules/042-kube-dns/.dmtlint.yaml, modules/042-kube-dns/templates/deployment.yaml, modules/110-istio/.dmtlint.yaml, modules/110-istio/templates/cni/daemonset.yaml, modules/110-istio/templates/kiali/deployment.yaml, modules/500-cilium-hubble/.dmtlint.yaml, modules/500-cilium-hubble/templates/ui/deployment.yaml, modules/500-openvpn/.dmtlint.yaml, modules/500-openvpn/templates/openvpn/statefulset.yaml
Added missing probes for kube-rbac-proxy in all network modules.
* node-local-dns
* kube-dns
* istio
* openvpn
* cilium-hubble
* kube-proxy
* cni-cilium
* service-with-healthchecks
This PR is part of solution for https://github.com/deckhouse/deckhouse/issues/11295.
```changes
type: fix
summary: Added probes for `kube-rbac-proxy`.
---
type: fix
summary: Added probes for `kube-rbac-proxy`.
---
section: istio
type: fix
summary: Added probes for `kube-rbac-proxy`.
---
type: fix
summary: Added probes for `kube-rbac-proxy`.
---
type: fix
summary: Added probes for `kube-rbac-proxy`.
---
type: fix
summary: Added probes for `kube-rbac-proxy`.
---
type: fix …
```
=> [network] Enabled liveness-probe and readiness-probe probe for network modules.

modules/040-node-manager/requirements/check_config.go
Fixed update for static clusters if secrets “d8-static-cluster-configuration” does not exist
If there is no secret, cluster update is blocked permanently.
```changes
type: fix 
summary: fixed update for static clusters
impact: 
```
=> [node-manager] fixed update for static clusters

candi/version_map.yml
Updated Deckhouse CLI to the latest stable
```changes
section: candi
type: chore
summary: Update Deckhouse CLI to 0.13.1
```
=> [candi] Update Deckhouse CLI to 0.13.1

modules/300-prometheus/templates/grafana/certificate.yaml
Remove Grafana v8 name from Certificate
To remove an old grafana-v8 name from Certificate and keep dnsNames in fresh state
```changes
type: fix 
summary: Remove Grafana v8 name from Certificate
```
=> [prometheus] Remove Grafana v8 name from Certificate

.github/ci_templates/e2e_tests.yml, .github/workflows/e2e-daily.yml, .github/workflows/e2e-eks.yml, .github/workflows/e2e-openstack.yml, .github/workflows/e2e-static.yml, .github/workflows/e2e-vcd.yml, .github/workflows/e2e-vsphere.yml
Enable saving e2e state on cancelled workflow.
This change allows to delete e2e cluster via usual delete workflow if the e2e workflow was cancelled.
```changes
section: ci
type: fix
summary: Enable saving e2e state on cancel.
```
=> [ci] Enable saving e2e state on cancel

modules/402-ingress-nginx/templates/validator/deployment.yml
This patch adds mounting of the ingress-nginx-{{ $crd.name }}-auth-tls secret into the validator Deployment in the 402-ingress-nginx module. The mounted secret contains TLS certificates required for secure communication and authentication by NGINX components.
Without this secret, the validator component cannot correctly execute `nginx -t`, which is used to validate the NGINX configuration.
Yes, we need this in a patch release because the absence of the auth-tls secret causes a runtime error in the validator during configuration validation (`nginx -t`). All d8 Ingress-resources has references to this secret.
```changes
type: fix
summary: fix missing proxy client cert in validator deployment
```
=> [ingress-nginx] fix bug with proxy client cert in validator

modules/140-user-authz/templates/rbacv2/global/use/capabilities/manage_security.yaml
It adds patch verb for sa.
Use manager can not patch service accounts.
Use manager can not patch service accounts.
```changes
type: fix
summary: Add patch verb for service accounts
```
=> [user-authz] add patch verb for service accounts for use managers

.github/ci_templates/build.yml, .github/scripts/python/compare_external_modules.py, .github/scripts/python/compare_internal_modules.py, .github/scripts/python/obtain_edition_list.py, .github/workflow_templates/build-and-test_release.yml, .github/workflow_templates/compare-external-modules.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml, .github/workflows/compare-external-modules.yml
Add jobs for comparing external and internal modules between editions.
Closes #10553
Example of external module comparison:
Example of internal module comparison:
Differences in modules that should be same causes problems when switching between editions on same installation. This check allows to find out problems earlier.
```changes
section: ci
type: feature
summary: Add jobs for comparing external and internal modules between editions.
```
=> [ci] Add module comparison

ee/be/modules/350-node-local-dns/templates/configmap.yaml
Increased the value of the `health_check' parameter for the dynamicforward plugin from 100 ms to 300ms.
We are improving the reliability of node-local-dns in clusters with slow or unstable inter-node connections, and in particular as an example for geo-distributed clusters.
In one of our geo-distributed clusters, several nodes located at a sufficient distance from the controle-plane and could not perform a health check of the remote kube-dns service due to the low timeout threshold.
```changes
type: fix
summary: Improved stability for clusters with poor node-to-node connection quality by increasing node-local-dns to kube-dns healthcheck timeouts.
```
=> [node-local-dns] increase healthcheck timeout for dynamicforward plugin

candi/control-plane-kubeadm/v1beta4/config.yaml.tpl
After upgrading to v1beta4 in https://github.com/deckhouse/deckhouse/pull/13153 I lost a few fields
fix kubeadm v1beta4 config
```changes
type: fix
summary: fix kubeadm v1beta4 config
impact:
```
=> [control-plane-manager] Kubeadm v1beta4 fix

deckhouse-controller/pkg/debug/debug.go
Fixing errors when collecting debugging resources in collect-debug-info about Istio.
When called collect-debug-info command in cluster without enabled Istio modules or deployed components, user see errors, but archive create correct.
After this fix command collect-debug-info worked without errors.
```changes
section: istio
type: fix
summary:  Fix for collecting debugging resources in collect-debug-info about Istio
impact: When called collect-debug-info command in cluster without Istio, user see errors, but archive create correct
```
=> [istio] Fix for collecting debugging resources in collect-debug-info about Istio

.github/scripts/python/compare_version_modules.py, .github/workflow_templates/build-and-test_pre-release.yml, .github/workflows/build-and-test_pre-release.yml
Add listing of changed modules for release branch changes.
Example:
This change allows to detect potentially destructive image changes for minor release.
```changes
section: ci
type: feature
summary: Add listing of changed modules for release branch changes.
```
=> [ci] Add listing of changed modules for release branch changes

.github/ci_templates/cve_tests.yaml, .github/scripts/js/ci.js, .github/scripts/js/constants.js, .github/workflow_templates/cve-pr.yml, .github/workflows/cve-pr.yml, .github/workflows/cve-weekly.yml
This PR updates the trigger conditions for the **Trivy CVE scan on PR** workflow.  
Previously, the workflow was executed on every pull request unconditionally.  
Now, it runs **only if the pull request contains the `security/cve` label**, ensuring targeted scanning only where required.
Running the Trivy CVE scan on every PR was redundant and resource-consuming for changes unrelated to security.  
This change optimizes CI resource usage by limiting CVE scanning to PRs explicitly marked with the `security/cve` label.
This prevents unnecessary scan jobs, reduces noise in PR checks, and ensures that security scanning is performed only where relevant.
```changes
section: ci
type: fix
summary: This PR updates the trigger conditions for the **Trivy CVE scan on PR** workflow.  
impact_level: …
```
=> Run Trivy CVE scan only when security/cve label is present

modules/300-prometheus/images/trickster/patches/001-go-mod.patch
Fixed CVEs
```changes
type: fix
summary: Fix CVEs vulnerabilities trickster
```
=> [prometheus] Fix CVEs vulnerabilities trickster

modules/040-control-plane-manager/template_tests/template_test.go, modules/040-control-plane-manager/templates/etcd-backup/cronjob.yaml
Since v1.70 we add custom properties for etcd backup and unintentionally changed default behaviour for backup job.
Related to: #13193
Etcd backup should be enable by default.
Etcd backup should be enable by default.
```changes
type: fix
summary: Fix default behaviour for etcd backup.
```
=> [control-plane-manager] fix default  behaviour for etcd backup

ee/modules/650-runtime-audit-engine/images/falco/werf.inc.yaml
this pr add werf fixes for build image falco artifacts fro CSE release.
this resolve falco build artifacts for cse release.
```changes
type: fix
summary: falco build fixes for CSE
```
=> [runtime-audit-engine] Falco build werf fixes for CSE release.

modules/150-user-authn/crds/dex-client.yaml, modules/150-user-authn/crds/doc-ru-dex-client.yaml, modules/150-user-authn/hooks/get_dex_client_crds.go, modules/150-user-authn/hooks/get_dex_client_crds_test.go
Now we keep secret only those labels and annotations that we explicitly specify in the DexClient  resource.
Fix implicit behavior when using argocd labels added in [PR](https://github.com/deckhouse/deckhouse/pull/10883)
Argocd labels may be different and we can't determine whether to pass it on to the secret or not automatically.
```changes
type: fix
summary: The logic of label transfer and annotation to secret has been changed for DexClient
```
=> [user-authn] Fix logic for transfer labels and annotations to secret from dexclient

modules/300-prometheus/templates/aggregating-proxy/servicemonitor.yaml
This PR increases the number of samples limit for the aggregation-proxy component from 1500 to a higher value to better handle large clusters with significant metrics volume.
In large clusters with huge amount of metrics, the previous limit of 1500 samples proved insufficient, causing metrics collection issues. The new higher limit will:
- Prevent metrics loss in large environments
```changes
type: fix
summary: Increased target samples limit for aggregation-proxy
```
=> [Prometheus]  Increase target samples limit for aggregation-proxy

dhctl/pkg/operations/bootstrap/cluster-bootstrapper-abort.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper-base-infra.go
Fix config.ParseConfig error handling. It will prevent panics
```
2025-06-25T21:39:32Z - [DEBUG] - Job execution failed: panic: meta config must be provided, goroutine 69 [running]:
runtime/debug.Stack()
/usr/lib/golang/src/runtime/debug/stack.go:26 +0x5e
github.com/deckhouse/deckhouse/dhctl/pkg/server/rpc/dhctl.panicMessage({0x26f84b0, 0xc0007e32c0}, {0x1eca260, 0x26d3a50})
/dhctl/pkg/server/rpc/dhctl/service.go:224 +0x3f
github.com/deckhouse/deckhouse/dhctl/pkg/server/rpc/dhctl.(*Service).abortSafe.func1()
/dhctl/pkg/server/rpc/dhctl/abort.go:139 +0x51
panic({0x1eca260?, 0x26d3a50?})
/usr/lib/golang/src/runtime/panic.go:791 +0x132
github.com/deckhouse/deckhouse/dhctl/pkg/infrastructureprovider.ExecutorProvider(0xc00038b240?)
/dhctl/pkg/infrastructureprovider/get.go:37 +0x5e …
```
=> [dhctl] fix(dhctl-for-commander): fix config.ParseConfig error handling

.werf/defines/installer.tmpl, testing/cloud_layouts/script-commander.sh, testing/cloud_layouts/script.sh, testing/cloud_layouts/script_eks.sh
Add envsubst bash replacement to the install image.
Envsubst is used in the e2e tests.
```changes
section: ci
type: fix
summary: add envsubst bash replacement to the install image
```
=> [ci] add envsubst bash replacement to the install image

ee/modules/500-operator-trivy/images/operator/patches/011-support-new-jobs.patch, ee/modules/500-operator-trivy/images/operator/patches/README.md
It fixes operator-trivy does not respect kubernetes 1.31+
Operator-trivy 0.22 does not support kubernetes 1.31+
Upstream [issue](https://github.com/aquasecurity/trivy-operator/pull/2292)
Upstream [fix](https://github.com/aquasecurity/trivy-operator/pull/2292)
This problem probably affects all versions of deckhouse.
Symptoms:
Logs with errors
```
{"level":"error","ts":"2025-06-25T12:52:42Z","msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"scan-vulnerabilityreport-56d7ddd967","namespace":"d8-operator-trivy"},"namespace":"d8-operator-trivy","name":"scan-vulnerabilityreport-56d7ddd967","reconcileID":"9c7ab8bb-8380-4d39-ace7-5ff225a46485","error":"unrecognized scan job condition: …
```
=> [operator-trivy] operator-trivy respects k8s 1.31+

.werf/defines/base.tmpl, .werf/defines/dev-prebuild.tmpl, deckhouse-controller/go-build.sh
Move deckhouse-controller to static build
```changes
section: ci
type: chore
summary: move deckhouse-controller to static build
```
=> [ci] move deckhouse-controller to static build

modules/015-admission-policy-engine/charts/constraint-templates/tests/allowed-capabilities/constraint_pss_restricted.yaml, modules/015-admission-policy-engine/charts/constraint-templates/tests/allowed-capabilities/test_samples/pss_restricted/allowed_with_skip_pss.yaml, modules/015-admission-policy-engine/charts/constraint-templates/tests/allowed-capabilities/test_suite.yaml, modules/015-admission-policy-engine/templates/_helpers.tpl, modules/015-admission-policy-engine/templates/admission.yaml
Add label to skip PodSecurityStandard check for pods
Add policy to allow such pods only from the virtualization module
Virtualization pods couldn't correspond the standards.
Deny other pods to create:
```
The pods "demo" is invalid: : ValidatingAdmissionPolicy 'deny-pods-with-skip-pss-label' with binding 'deny-skip-pss-label-binding' denied request: Pods with label 'security.deckhouse.io/skip-pss-check=true' are not allowed
```
```changes
type: feature
summary: Add label to skip PodSecurityStandards for some pods.
```
=> [admission-policy-engine] Add skip-pss label

docs/documentation/_data/deckhouse-alerts.yml, modules/340-monitoring-deckhouse/monitoring/prometheus-rules/alerting.yaml
Follow-up https://github.com/deckhouse/deckhouse/pull/14189
We need to the last 60 seconds usage but the whole heap footprint
```changes
```
=> [deckhouse] Use in-place memory footprint instead of range usage

modules/040-control-plane-manager/images/etcd/patches/002-etcdctl-snapshot-pipe.patch, modules/040-control-plane-manager/images/etcd/werf.inc.yaml
this pr add support etcd version 3.6.1 and add etcdutl for support snapshot options because of https://github.com/etcd-io/etcd/pull/13809.
single-master bootstrap
```
/opt/deckhouse/bin/kubectl -nkube-system exec -it etcd-standalone-master-0 -- etcd --version
etcd Version: 3.6.1
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.24.3
Go OS/Arch: linux/amd64
/opt/deckhouse/bin/kubectl -nkube-system exec -it etcd-standalone-master-0 -- etcdctl version
etcdctl version: 3.6.1
API version: 3.6
/opt/deckhouse/bin/kubectl -nkube-system exec -it etcd-standalone-master-0 -- etcdutl version
etcdutl version: 3.6.1
API version: 3.6
```
multi-master bootstrap and migrate from v3.5.21 to v3.6.1.
```
+--------------------------+------------------+---------+-----------------+--------- …
```
=> [etcd] etcd update to v3.6.1

modules/040-node-manager/hooks/migration/migrate_remove_old_caps_lease.go, modules/040-node-manager/hooks/migration/migrate_remove_old_caps_lease_test.go, modules/040-node-manager/images/caps-controller-manager/src/cmd/main.go
Rename caps-controller-manager lease from `faf94607.cluster.x-k8s.io` to `controller-leader-election-caps`
Fix https://github.com/deckhouse/deckhouse/issues/8952
Before:
```
~ $ kubectl -n d8-cloud-instance-manager get leases
NAME                              HOLDER                                                                          AGE
controller-leader-election-capi   kovalkov-master-2_737cd5cb-0b2d-4ed8-8965-b30219bec756                          4m15s
faf94607.cluster.x-k8s.io         caps-controller-manager-76d5586866-555l8_7fab1154-54c9-4946-be69-d3623e523c53   4m10s
```
After:
```
~ $ kubectl -n d8-cloud-instance-manager get leases.coordination.k8s.io
NAME                              HOLDER                                                                          AGE …
```
=> [node-manager] Rename lease name for caps-controller-manager

modules/002-deckhouse/templates/deployment.yaml
Always set resource requests for deckhouse
Without that on bootstrap deckhouse will set request == limit and will wait for 6Gi of memory. We can set the initial requests to the container and then VPA will change them if required
```changes
type: fix
summary: Set resource requests even if VPA is enabled.
```
=> [deckhouse] Always set resource requests

ee/se-plus/modules/030-cloud-provider-vsphere/templates/csi-legacy/controller.yaml
Add /tmp emptyDir for csi-node-legacy for the `node` container of `csi-node-legacy`.
This PR is analog for https://github.com/deckhouse/deckhouse/pull/14197 
`csi-node-legacy` needs to write files in /tmp
```
log: exiting because of error: log: cannot create log: open /tmp/vsphere-csi.s-apimng-ks-node-tekton-pipelines-d601158f-75b58-hxt6l.root.log.WARNING.20250626-153509.1: read-only file system
```
```changes
type: fix
summary: Add /tmp emptyDir for csi-node-legacy
```
=> [cloud-provider-vsphere] add /tmp emptyDir for csi-node-legacy

candi/bashible/common-steps/all/000_add_node_users.sh.tpl, modules/040-node-manager/crds/nodeuser.yaml, modules/040-node-manager/hooks/internal/v1/node_user.go, modules/040-node-manager/webhooks/validating/node_user
The PR allows creating NodeUser CR without passwordHash field.
this allow to create node user without password to avoid auth issues from pam, ldap, etc.
ex.
```
---
kind: NodeUser
metadata:
name: user
spec:
uid: 20029
sshPublicKey: "ssh-rsa  ..."
isSudoer: true
nodeGroups:
- master
kubectl apply -f nodeuser.yaml
Warning: Password hash is empty. The user might not be able to log in.
nodeuser.deckhouse.io/user created
cat /etc/shadow | grep user
...
user:!:20235:0:99999:7:::
```
```changes
type:  chore
summary: passwordHash in nodeuser cr is not required
```
=> [node-manager] Make NodeUser passwordHash parameter optional

modules/021-cni-cilium/images/bin-cilium/patches/010-fix-cilium-local-redirect-policy.patch, modules/021-cni-cilium/images/bin-cilium/patches/README.md
If the `bpf-lb-algorithm-annotation` parameter is enabled in Cilium settings, `CiliumLocalRedirectPolicy` stops working. This affects the DNS service because `CiliumLocalRedirectPolicy` is used for redirecting DNS traffic to `node-local-dns` pods.
Enabling the `bpf-lb-algorithm-annotation` parameter is required for PR #13867, where we introduce a custom "Least Connections" algorithm and enable per-service load balancing algorithm selection.
```changes
type: fix
summary: Fixed CiliumLocalRedirectPolicy working if bpf-lb-algorithm-annotation parameter is enabled.
```
=> [cni-cilium] fix CiliumLocalRedirectPolicy

testing/cloud_layouts/script.sh
Fix legacy E2E test script.
This is necessary for E2E tests to run.
```changes
section: ci
type: fix
summary: Fix legacy E2E test script.
```
=> [ci] Fix Static E2E test

modules/300-prometheus/images/mimir/patches/001-go-mod.patch, modules/300-prometheus/images/mimir/patches/README.md, modules/300-prometheus/images/mimir/werf.inc.yaml
Fix of image vulnerabilities and rollback version
To improve the security of Deckhouse and to fix the bug, when we updated Mimir to a version higher than 2.14.3 version the variables in grafana are not working.
Fixed CVEs and working variables in Grafana
```changes
type: fix
summary: Fix CVEs vulnerabilities mimir
```
=> [prometheus] Fix CVEs vulnerabilities mimir and rollback version

.github/CODEOWNERS
Add @z9r5 to CODEOWNERS.
Reverts deckhouse/deckhouse#14040
```changes
section: ci
type: chore
summary: Update CODEOWNERS.
```
=> Revert "[ci][chore] Update CODEOWNERS"

modules/402-ingress-nginx/docs/EXAMPLES.md, modules/402-ingress-nginx/docs/EXAMPLES_RU.md
Add selector/tolerations to ingressnginxcontroller manifest to clarify that speakers and ingress-controllers must be scheduled on the same node.
Previous example was misleading for copy and paste deployment.
```changes
type: chore
summary: Fix ingress-nginx L2 MetalLB example
```
=> [docs][ingress-nginx] Fix selectors in L2 MetalLB example

modules/040-control-plane-manager/docs/FAQ.md, modules/040-control-plane-manager/docs/FAQ_RU.md
This pull request includes updates to the etcd backup restoration process. It addresses issues related to inconsistencies when expanding the master nodes from 1 to 3 after a restoration. Specific flags have been added to the restoration command to resolve these floating problems, and the recovery steps have been updated to ensure a smoother process.
The main purpose of this change is to eliminate problems encountered during the restoration of etcd backups which previously resulted in difficulties when scaling up master nodes in a Kubernetes cluster. By adding specific flags and expanding the recovery steps, this update ensures that users can reliably restore from backups and adequately scale their cluster without encountering unexpected issues.
```changes
section: …
```
=> [docs][control-plane-manager] Correct way to restore etcd backup

deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_kubernetes_version.go, deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_module.go, deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_module_config.go, deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_update_policy.go, deckhouse-controller/pkg/debug/module_enable.go
Add user notification about multiple sources when enable module.
```
deckhouse-controller module enable console
Module console enabled
```
```
deckhouse-controller module enable console
Warning: module 'console' is enabled but didn’t run because multiple sources were found (deckhouse, deckhouse-prod), please specify a source in ModuleConfig resource
Module console enabled
```
```
kubectl edit mc console                       
moduleconfig.deckhouse.io/console edited
```
```
kubectl edit mc console                       
Warning: module 'console' is enabled but didn’t run because multiple sources were found (deckhouse, deckhouse-prod), please specify a source in ModuleConfig resource 
moduleconfig.deckhouse.io/console edited
```
```changes
type: feature …
```
=> [deckhouse-controller] Add synh notify user

docs/site/pages/stronghold/documentation/user/ACCESS.md, docs/site/pages/stronghold/documentation/user/ACCESS_RU.md
Fixed title at Stronghold documentation.
```changes
section: docs
type: chore
summary: Fixed title at Stronghold documentation.
```
=> [docs] Fixed title at Stronghold documentation

modules/110-istio/docs/EXAMPLES.md, modules/110-istio/docs/EXAMPLES_RU.md
This change adds documentation on how to redefine Istio sidecar limit/request for applications. The guidance is intended for users who need to add more resources for Istio sidecar, when is used high load application.
Some environments require more limits and requests for Istio Sidecar in applications than are globally specified. However, instructions on how to do this were previously missing from the documentation.
```changes
section: istio
type: chore
summary: Examples for redefine limit/request on sidecars in pod/deployment
```
=> [istio] Examples for redefine limit/request on sidecars in pod/deployment

deckhouse-controller/pkg/controller/deckhouse-release/controller.go, deckhouse-controller/pkg/controller/module-controllers/release/controller.go
This PR optimizes the DeckhouseRelease update mechanism by replacing Update operations with Patch for Deckhouse deployments.
Changes made:
- Replaced Update with Patch for modifying the deckhouse Deployment
- Added some debug-level logging
Performance Optimization:
- Patch operations are more efficient than Update calls
- Reduces network payload and API server load
```changes
type: feature
summary: Deckhouse deployment upgrades now use Patch instead of Update
```
=> [deckhouse-controller] Replace Update to Patch in DeckhouseRelease update

go_lib/hooks/storage_class_change/hook.go, modules/300-prometheus/hooks/prometheus_longterm_storage_class_change.go
It fixes fake longterm emptydir alert.
The alert is fire even if longterm is disabled, it fixes this.
1.70 is also affected.
```changes
type: fix
summary: Fix fake longterm emptydir alert.
```
=> [prometheus] fix fake longterm emptydir alert

docs/site/_data/footer.json, docs/site/_includes/header.html
Update the link to the documentation in the header and the footer.
Ref: https://github.com/deckhouse/deckhouse/pull/14329
```changes
section: docs
type: chore
summary: Update the link to the documentation in the header and the footer.
```
=> [docs] Update the link to the documentation in the header and the footer

docs/documentation/_plugins/reference_generator.rb
Fix markup for rendering reference for d8 CLI in the documentation.
```changes
section: docs
type: chore
summary: Fix markup for rendering reference for d8 CLI in the documentation.
```
=> [docs] Update d8 CLI tool reference generator

ee/modules/040-node-manager/templates/nvidia-gpu/nvidia-mig-config.yml
Remove `update.node.deckhouse.io/disruption-approved` annotation after mig-manager has finished reconfiguring the node
For now, after mig-manager has finished reconfiguring the node, annotation `update.node.deckhouse.io/disruption-approved` keeps on the node. It should be removed.
```changes
type: fix
summary: Fix mig-manager behavior related to update.node.deckhouse.io/disruption-approved annotation.
```
=> [node-manager] Disruption approved annotation removal

modules/300-prometheus/hooks/enable_prompp.go, modules/300-prometheus/hooks/enable_prompp_test.go
Prompp is a drop-in replacement for the Prometheus which drastically reduces resource consumption by the monitoring stack. This PR enables the Deckhouse Prom++ module by default effectively replacing Prometheus with  Deckhouse Prom++.
If there are significant reasons for sticking with the Prometheus, the following `ModuleConfig` has to be created prior to the platform upgrade: 
```yaml
metadata:
name: prompp
spec:
enabled: false
```
The Deckhouse Prom++ is known to be much more efficient compared to the Prometheus, thus reducing cluster running costs. The Deckhouse Prom++ is considered mature enough to be the default metrics store in the Deckhouse Kubernetes Platform.
```changes
type: feature
summary: Deckhouse …
```
=> [prometheus] Switch from Prometheus to Deckhouse Prom++ by default

candi/bashible/bashbooster/50_deckhouse_registrypackages.sh, candi/bashible/bashible.sh.tpl
The registry module, in managed mode, configures mirrors using the `hosts.toml` mechanism.  
Because of this, direct access to the registry API at `registry.d8-system.svc` is unavailable.
This PR resolves the issue with downloading packages for external modules.
How it works:
- If the request goes to `registry.d8-system.svc:5001`, `ctr` is used to fetch the packages;
- Otherwise, curl is used (default behavior);
The changes affect the following functions:
- `bb-rp-fetch`;  
- `bb-rp-install` (which uses `bb-rp-fetch`);  
- `bb-rp-module-install` (which uses `bb-rp-install`);
`bb-rp-module-install` usage example:
- ~[module sds-replicated-volum](https://github.com/deckhouse/sds-replicated-volume/blob/main/templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml#L37)~. [When …
=> [registry] Use ctr for bb-rp-fetch when registry module is used

modules/402-ingress-nginx/hooks/get_ingress_controllers.go, modules/402-ingress-nginx/hooks/get_ingress_controllers_test.go
This PR ensures that `validationEnabled` is always set to `false`.
This change is necessary to reduce high resource consumption caused by additional validation `pods` in ingress-nginx. Enabling validation can lead to significant CPU and memory consumption in large clusters with many `IngressNginxController` resources.
High resource utilization is a blocking factor for future Deckhouse updates.
```changes
type: fix
summary: Validation is switched off temporarily.
```
=> [ingress−nginx] Ensure that validationEnabled is always set to false

ee/se-plus/modules/021-cni-cilium/hooks/ee/egressgateways_discovery.go
This PR reduces the deckhouse hook execution queue for the egressgateway by hook filter. 
The Deckhouse queue overflows and starts consuming a lot of RAM, which negatively affects the performance of the cluster node.
```changes
type: fix
summary: EgressGateway controller optimized for large setups with lot's of EgressGateways.
```
=> [cni-cilium] Fixing the egressgateway controller for large setups

candi/cloud-providers/yandex/openapi/cluster_configuration.yaml, candi/cloud-providers/yandex/openapi/doc-ru-cluster_configuration.yaml
Add warning to `natInstanceResources` description that auto-converger would restart after it's interval NAT instance by default.
NAT instance is considered base-infra, therefore non-desctructive changes are applied automatically.
```changes
type: chore
summary: Add warning NAT-instance restarts if resources changed
```
=> [docs][cloud-provider-yandex] Add warning NAT-instance restarts if resources changed

modules/340-monitoring-ping/images/monitoring-ping/src/main.go, modules/340-monitoring-ping/images/monitoring-ping/werf.inc.yaml, modules/340-monitoring-ping/templates/daemonset.yaml
* Added init container for clearing obsolete mertrics passed through the file. The cleanup logic was migrated from agent to init-container.
In the previous implementation of monitoring-ping (python version) a file was created to transfer metrics to node-exporter in the directory /var/run/node-exporter-textfile named in the following pattern “monitoring-ping*.prom, after switching to exporting metrics using http server, the file remains, and as a consequence the hung metrics are displayed in monitoring prometheus and grafana. The cleanup function is already implemented, but the best solution would be to run it in a separate init container, since deleting files requires root privileges, it is reasonable to perform the deletion in the init container, and leave the execution of the …
=> [monitoring-ping] added init container for cleanup deprecated exporter

candi/bashible/common-steps/all/001_check_kubernetes_version.sh.tpl
Add bashible step to check for upgrade k8s to 1.31 and ask for approval
Due upgrade from 1.30 to 1.31, all pods on the node will be restarted, what causes downtime. So we should check if it's upgrade to 1.31 and ask for approval.
We should backport it to all releases, when 1.31 is available.
```changes
section: candi
type: feature
summary: Add bashible step to check for upgrade k8s to 1.31 and ask for approval.
impact: Upgrade process on the node will be stopped  until it's not approved.
```
=> [candi] Add bashible step to check for upgrade k8s to 1.31

modules/302-vertical-pod-autoscaler/templates/admission.yaml
Fix apiVersion for ValidatingAdmissionPolicy
apiVersion is based on the kubernetes version
```changes
type: fix 
summary: Fix apiVersion detection for ValidatingAdmissionPolicy.
```
=> [vertical-pod-autoscaler] Fix VPA admission resources

modules/110-istio/docs/EXAMPLES.md, modules/110-istio/docs/EXAMPLES_RU.md
Fixed rendering for Customizing istio-proxy sidecar resource management article.
Before:
After:
```changes
section: docs
type: chore
summary: Fixed rendering for Customizing istio-proxy sidecar resource management article.
```
=> [docs] Fixed rendering for Customizing istio-proxy sidecar resource management article

modules/101-cert-manager/openapi/config-values.yaml, modules/101-cert-manager/openapi/doc-ru-config-values.yaml, modules/101-cert-manager/templates/cert-manager/clusterissuer-letsencrypt-staging.yaml, modules/101-cert-manager/templates/cert-manager/clusterissuer-letsencrypt.yaml
Introduces a new parameter to the cert-manager module. 
The parameter allows users to specify which ingress-class to use for domain ownership verification via the `http01` method.
By allowing the selection of an ingress-class, users can better control traffic routing when verifying domain ownership. This update addresses issues where the default ingress controller might not be suitable for certain application setups.
Resolve #13923 issue
```changes
type: feature 
summary: Added ingressClass selection for ACME HTTP-01 challenge method.
```
=> [cert-manager] Add support for ACME HTTP-01 challenges method in ingressClass

ee/se-plus/candi/cloud-providers/vsphere/docs/ENVIRONMENT.md, ee/se-plus/candi/cloud-providers/vsphere/docs/ENVIRONMENT_RU.md
Fixed links at vSphere documentation.
```changes
section: docs
type: chore
summary: Fixed links at vSphere documentation.
```
=> [docs] Fixed links at vSphere documentation

docs/documentation/pages/architecture/security/RUNTIME-AUDIT.md
This PR adds translation of the security event audit page in the Architecture section of the new docs structure.
=> [docs][new structure] Translate event audit architecture page

.github/scripts/js/constants.js, .github/workflow_templates/e2e.multi.yml, .github/workflows/e2e-aws.yml, .github/workflows/e2e-azure.yml, .github/workflows/e2e-eks.yml, .github/workflows/e2e-gcp.yml, .github/workflows/e2e-openstack.yml, .github/workflows/e2e-static.yml, .github/workflows/e2e-vcd.yml, .github/workflows/e2e-vsphere.yml, .github/workflows/e2e-yandex-cloud.yml
This pr adds ContainerdV2 for e2e tests.
We need to test bootstrapping clusters on ContainerdV2.
```changes
section: ci
type: chore
summary: ContainerdV2 for e2e tests
```
=> [Tests] ContainerdV2 for e2e tests

testing/cloud_layouts/script-commander.sh, testing/cloud_layouts/script.d/wait_cluster_ready/test_alerts.sh
This fix adds allow alert ModuleConfigObsoleteVersion for e2e tests.
Firing this informational alert blocks e2e upgrade test case.
```changes
section: ci
type: chore
summary: Allow alert ModuleConfigObsoleteVersion for e2e tests.
```
=> [tests] Allow module config obsolete version alert

modules/007-registrypackages/images/containerd/patches/containerd/2.1.3/003-hosts-auth.patch, modules/007-registrypackages/images/containerd/werf.inc.yaml
For implement integrity check in container v2 we need to download manifest with signature. For it we will use additional function to get it. We need to get credentials from containerd config files. Function `ConfigureHosts` is source of truth for getting information about hosts for connecting. But this function returns callback which returns list of `RegistryHost` struct which contains only  `Authorizer` interface without credentials. We added field `Credentials`. It is callback which returns credentials and its callback can be used in another places for getting auth settings. Also we small rewrite logic for creating docker authorizer options in `ConfigureHosts` function. Now, for creating  authorizer options (for options we need to get credentials) will use same function which saved to …
=> [node-manager] Containerd v2 rewrite host auth patch

modules/040-node-manager/templates/node-group/_capi_machine_deployment.tpl
added placeholder for required field in `MachineDeployment` template
`spec.selector` is a required field, it is usually filled in via `mutatingwebhookconfigurations.admissionregistration.k8s.io/capi-mutating-webhook-configuration`
If the webhook is not running or has not yet been created, MachineDeployment creation error will occured (`spec.selector: Required value`)
```changes
type: fix
summary: added placeholder for required field in `MachineDeployment` template
impact: 
```
=> [node-manager] added placeholder for required field

modules/040-node-manager/images/bashible-apiserver/src/pkg/cmd/server/start.go
Add profiling for bashible-apiserver.
How to profile:
```
curl -s -k --header "Authorization: Bearer $(kubectl -n d8-system create token --duration=10m deckhouse)" "https://$(kubectl -n d8-cloud-instance-manager get pod -lapp=bashible-apiserver -o jsonpath='{.items[0].status.hostIP}'):4221/debug/pprof/heap" > /tmp/heap
```
Sometimes bashible-apiserver uses many resources and we need to profile them.
```changes
type: chore
summary: Add profiling for bashible-apiserver
```
=> [node-manager] Add profiling for bashible-apiserver

candi/bashible/common-steps/all/005_check_gpu.sh.tpl, candi/bashible/common-steps/all/032_configure_containerd.sh.tpl, candi/bashible/common-steps/all/041_configure_sysctl_tuner.sh.tpl, modules/040-node-manager/images/bashible-apiserver/src/pkg/template/context_builder.go
Remove duplicate fields from bashible context
Reduce bashible-apiserver cognitive complexity 
```changes
type: chore
summary: Remove duplicate fields from bashible context.
```
=> [node-manager] Remove duplicate fields from bashible context

modules/040-terraform-manager/.dmtlint.yaml, modules/040-terraform-manager/templates/terraform-auto-converger/deployment.yaml, modules/040-terraform-manager/templates/terraform-state-exporter/deployment.yaml
Added missing probes for kube-rbac-proxy in all cloud-providers. This primarily relates to cloud-data-discoverer.
This PR partly resolves https://github.com/deckhouse/deckhouse/issues/11295
```changes
type: fix
summary: Added probes for `kube-rbac-proxy`
```
=> [terraform-manager] probes for kube-rbac-proxy

modules/021-cni-cilium/images/bin-cilium/patches/011-add-least-conn-lb-algorithm.patch
Fixed extra least-conn logs when feature is disabled.
When least-conn load-balancing algorithm is disabled, there should be no corresponding logs in cilium agent.
The least-conn was released in 1.71, so the logs will confuse customers in case of network issues.
```changes
type: fix
summary: Fixed least-conn logs when feature is disabled
```
=> [cilium] Fixed least-conn logs when feature is disabled

modules/300-prometheus/hooks/enable_prompp.go
If there are several ModuleSources with the module it's mandatory to specify the correct one in the ModuleConfig, otherwise module will end up in the "Conflict" state and a corresponding alert is emitted. This PR sets the `.spec.source` field of the prompp `ModuleConfig` to "deckhouse" by default avoiding the conflict state.
There are handful of clusters which have several ModuleSources, e.g. for the production and dev modules. The Deckhouse e2e-tests cluster is known to be the one. If there are active alerts in this cluster, e2e tests considered failed.
Yes, to fix e2e tests
```changes
type: fix
summary: use the "deckhouse" ModuleSource as the default for the prompp ModuleConfig
impact: if there are several ModuleSources with the prompp module available, the …
```
=> [prometheus] Add .spec.source = deckhouse to prompp ModuleConfig

ee/se/modules/380-metallb/templates/monitoring.yaml
`helm_lib_single_dashboard` helper adds the `d8-` to the resource names, so we should avoid using extra prefix while arranging the template
#13478 has the dashboard rename side effect, leading the `ClusterObservabilityDashboard` deploy stuck on the unique dashboard uid constraint.
Yes, it's better to fix the issue now, until it reaches the stable channels where metallb module is used extensively.
```changes
type: fix
summary: avoid double prefixes in the dashboard names.
```
=> [metallb] Avoid double prefixing in dashboard resources

modules/015-admission-policy-engine/templates/admission.yaml
Exclude pods check if skip-pss-check is not changed. These pods were not allowed to even change an annotations
Before
pod with pss-check label exists
```shell
❯ kubectl -n default get pods nginx-deployment-b67576676-f8pzn -o jsonpath='{.metadata.labels}' | jq .
{
"app": "nginx",
"pod-template-hash": "b67576676",
"security.deckhouse.io/skip-pss-check": "true"
}
```
try to annotate the pod:
```shell
❯ kubectl -n default annotate pods nginx-deployment-b67576676-f8pzn a=b
The pods "nginx-deployment-b67576676-f8pzn" is invalid: : ValidatingAdmissionPolicy 'deny-pods-with-skip-pss-label' with binding 'deny-skip-pss-label-binding' denied request: Pods with label 'security.deckhouse.io/skip-pss-check=true' are not allowed
```
After:
```shell
❯ kubectl -n default annotate pods …
```
=> [admission-policy-engine] Fix ValidatingAdmissionPolicy with skip-pss-label

docs/site/pages/stronghold/documentation/user/auth/mfa/multifactor.ru.md
Updates Stronghold and Multifactor integration image.
We should use internal registry for our images
```changes
section: docs
type: chore
summary: Updates Stronghold and Multifactor integration image on the site.
```
=> [docs] Updates Stronghold and Multifactor integration image

ee/fe/modules/340-monitoring-applications/applications/redis/grafana-dashboards/propagated-redis.json
Change stacking mode to none for "Total Memory Usage" graph in redis dashboard.
Solving the problem of incorrect visualization of memory consumption graph.
```changes
type: fix
summary: redis dash turn off stacking for mem graph
```
=> [observability] redis dash turn off stacking for mem graph

.github/scripts/python/compare_internal_modules.py, .github/workflow_templates/build-and-test_pre-release.yml, .github/workflows/build-and-test_pre-release.yml
This pr extends list of the internal modules, which can be assembled different based on edition. Also, internal module comparison validation will be performed for release branches, to warn about the issue in advance before tag build.
We need it to fix the validation failure on release builds and to improve this check by performing it in advance on release branches.
```changes
section: ci
type: chore
summary: Improve internal modules comparison
```
=> Backport: [chore] Improve internal modules comparison #14618

deckhouse-controller/cmd/deckhouse-controller/start.go
Currently, Deckhouse controller only enables leader election when running in High Availability (HA) mode. However, this creates a potential issue in single-master clusters:
When multiple Deckhouse controller instances operate concurrently, they can:
- Apply conflicting configuration changes
- Create race conditions in cluster state management  
- Generate inconsistent module configurations
- Cause unpredictable cluster behavior
The current implementation assumes that single-master mode means only one pod will ever exist. However, in practice:
- **Rolling updates**: New pod starts before old pod terminates
- **Pod migrations**: Node evictions causing pod restarts
- **Manual scaling**: Operators accidentally scale replicas > 1
- **Stuck deployments**: Old ReplicaSet pods fail to terminate …
=> [deckhouse-controller] add leader election mechanism for non ha clusters

docs/documentation/_data/supported_versions.yml, docs/documentation/_includes/SUPPORTED_VERSIONS.liquid, docs/documentation/_includes/partials/supported-table-line.liquid
This pull request refactors the supported versions documentation by introducing a new partial template to simplify the rendering logic and adding support for Community Edition (CE) versions. 
* **Introduction of `partials/supported-table-line.liquid`**: Created a new partial template to consolidate and simplify the logic for rendering supported OS versions in tabular format. This includes preparing separate lists for CE, CSE, and other versions, as well as handling multilingual support (Russian and English).
* **Replacement of inline logic in `SUPPORTED_VERSIONS.liquid`**: Removed extensive inline logic for rendering supported versions and replaced it with the new partial template, significantly reducing code duplication and improving readability.
* **Update to `supported_versions.yml`**: …
=> [docs] Refactor table of supported OS versions

modules/038-registry/enabled
Enable the module only if all of the following conditions are met:
1. global.clusterConfiguration exists — this indicates that the cluster is managed by Deckhouse.
2. global.clusterConfiguration.defaultCRI is set and is in the allowed list of container runtimes the module supports.
Without `moduleConfig`:
With `moduleConfig`:
if try to change `moduleConfig/deckhouse`:
```ayml
```
Without `moduleConfig`:
With `moduleConfig`:
if try to change `moduleConfig/deckhouse`:
```yaml
```
```changes
type: fix
summary: fixed enable script for registry module
impact: 
```
=> [Registry] Fixed enable script

.github/ci_templates/helper_jobs.yml, .github/scripts/js/ci.js, .github/workflow_templates/build-and-test_dev.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/on-pull-request-labeled.yml, .github/workflows/validation.yml
Fix rerun workflow with multiple editions labels.
This fix removes edition labels deletion and change build condition for PR's based on pr info collected by the job it depends on.
It fixes rerun PR's build workflow, which was labeled by multiple editions.
```changes
section: ci
type: chore
summary: Fix rerun workflow with multiple editions labels.
```
=> Fix rerun workflow with multiple editions labels

docs/documentation/_data/deckhouse-alerts.yml, ee/be/modules/350-node-local-dns/monitoring/prometheus-rules/cache-plugin.yaml, ee/be/modules/350-node-local-dns/templates/configmap.yaml, ee/be/modules/350-node-local-dns/templates/monitoring.yaml, modules/042-kube-dns/templates/configmap.yaml
We set explicit max and min TTL values for the success and denial parameters of the CoreDNS cache plugin. Additionally, we reduce the denial max TTL to 5 seconds to minimize the delay in propagating new or recreated DNS records (e.g., after a pod or service rollout).
To improve DNS responsiveness and avoid double caching, we also disable the cache in the upstream kube-dns only if the node-local-dns module is enabled. In such cases, DNS caching is handled exclusively at the node level (in node-local-dns), which ensures faster propagation and more accurate resolution of changes in the cluster's DNS records.
<details>
<summary>Screenshots</summary>
</details>
use case: if the service resource was instantly recreated or became unavailable for a while, the erroneous response from the DNS …
=> [node-local-dns] Updated plugin cache settings for node-local-dns

modules/500-cilium-hubble/module.yaml
Added the `stage` field to the `module.yaml` of 500-cilium-hubble module.
This metadata field explicitly declares the [lifecycle stage](https://deckhouse.io/products/kubernetes-platform/documentation/v1/module-development/versioning/#how-do-i-figure-out-how-stable-a-module-is) of each network module. It improves clarity and helps consumers of the module (both internal tools and users) make informed decisions regarding stability, risk, and expected support level.
Currently, there is no consistent way to determine the maturity or readiness level of a module from its metadata. This creates ambiguity for both users and automated tooling when evaluating which modules are safe to use in production environments.
✅ This change introduces no runtime behavior modifications and is fully backward …
=> [500-cilium-hubble] Define stage to module.yaml

modules/002-deckhouse/templates/deployment.yaml
Fixed an issue when the KUBERNETES_SERVICE_HOST var in Deckhouse deployment is being changed.
Due to merge patch problems, the array element:
```yaml
- name: KUBERNETES_SERVICE_HOST
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: status.hostIP
```
Had to be changed to:
```yaml
- name: KUBERNETES_SERVICE_HOST
value: 127.0.0.1
```
But in fact was changed to:
```yaml
- name: KUBERNETES_SERVICE_HOST
value: 127.0.0.1
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: status.hostIP
```
Which is illegal.
The fix is setting valueFrom to null.
Sometimes helm can't handle array modifications properly.
```changes
type: fix
summary: Fixed a helm issue with patching arrays in deckhouse deployment.
```
=> [deckhouse] Fix merge patch issues in deployment template

.github/ci_templates/build.yml, .github/workflow_templates/build-and-test_release.yml, .github/workflows/build-and-test_release.yml
Added the `check-changelog` job that always runs, but performs a changelog file check **only on tag pushes**.  
If the current ref is a tag, the job looks for the file `./CHANGELOG/CHANGELOG-${TAG_VERSION}.yml` and fails if it is missing.  
On non-tag pushes, the job exits successfully without doing anything.
This ensures that every release tag is accompanied by a changelog, without affecting regular CI flows.
-  [Tag push, changelog exists — job succeeds](https://github.com/deckhouse/deckhouse-test-2/actions/runs/16452624195/job/46501551158)
- [Tag push, changelog missing — job fails](https://github.com/deckhouse/deckhouse-test-2/actions/runs/16452651743/job/46501647539)
- [Non-tag push — job skips check, exits 0; `build_fe` not triggered due to `git_info` …
=> Backport #14352: Run changelog check only on tag pushes to enforce release documentation

modules/101-cert-manager/openapi/config-values.yaml, modules/101-cert-manager/openapi/doc-ru-config-values.yaml, modules/101-cert-manager/templates/cert-manager/deployment.yaml
It provides recursive settings for cert-manager.
You can specify recursive nameservers via module config:
```
metadata:
name: cert-manager
spec:
enabled: true
settings:
recursiveSettings:
nameservers:
- 8.8.8.8:53
- https://1.1.1.1
version: 1
```
It adds ```--dns01-recursive-nameservers``` flag to the cert-manager deployment:
```
...
- --acme-http01-solver-resource-request-cpu=0
- --dns01-recursive-nameservers=8.8.8.8:53,https://1.1.1.1
...
```
If you want use only recusrive without fallback, you can specify use only recursive:
```
metadata:
name: cert-manager
spec:
enabled: true
settings:
recursiveSettings:
useOnlyRecursive: true
nameservers:
- 8.8.8.8:53
- https://1.1.1.1:443 …
```
=> [cert-manager] recursive settings

ee/modules/650-runtime-audit-engine/images/falco/werf.inc.yaml
Compile falco without jemalloc (with stdlib allocator)
jemalloc does not return memory if there is plenty on the host, which leads to the memory growth and looks like a memory leak (which is not but it doesn't metter)
By compiling falco with the USE_JEMALLOC=Off we can improve the memory profile
This is a user-facing problem that leads to higher resource consumption and looks like a bug
```changes
type: fix
summary: Improve memory footprint by switching to the stdlib memory allocator instead of jemalloc
```
=> Backport: [runtime-audit-engine] No JEMALLOC

.werf/werf-modules.yaml, ee/se-plus/modules/030-cloud-provider-zvirt/images/cloud-data-discoverer/werf.inc.yaml, ee/se-plus/modules/030-cloud-provider-zvirt/images/zvirt-csi-driver/werf.inc.yaml, modules/040-terraform-manager/images/base-terraform-manager/werf.inc.yaml
this mr allow to bootstrap CSE release on cloud provider zvirt.
```changes
type: feature
summary: zvirt cloud provider to cse. 
```
=> [cloud-provider-zvirt] Add zvirt cloud provider support to CSE release.

ee/se-plus/modules/030-cloud-provider-zvirt/hooks/discover.go
Fix for [New Snapshot logic](https://github.com/deckhouse/deckhouse/pull/12513)
We must use non pointer generics for snapshots
```changes
type: fix
summary: fix new snapshot logic bag
```
=> [deckhouse] Fix new snapshot logic bag

.github/ci_templates/e2e_tests.yml, .github/workflows/e2e-abort-aws.yml, .github/workflows/e2e-abort-azure.yml, .github/workflows/e2e-abort-eks.yml, .github/workflows/e2e-abort-gcp.yml, .github/workflows/e2e-abort-openstack.yml, .github/workflows/e2e-abort-static.yml, .github/workflows/e2e-abort-vcd.yml, .github/workflows/e2e-abort-vsphere.yml, .github/workflows/e2e-abort-yandex-cloud.yml, .github/workflows/e2e-aws.yml, .github/workflows/e2e-azure.yml, .github/workflows/e2e-daily.yml, .github/workflows/e2e-eks.yml, .github/workflows/e2e-gcp.yml, .github/workflows/e2e-openstack.yml, .github/workflows/e2e-static.yml, .github/workflows/e2e-vcd.yml, .github/workflows/e2e-vsphere.yml, .github/workflows/e2e-yandex-cloud.yml, testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml, testing/cloud_layouts/Static/configuration.tpl.yaml, testing/cloud_layouts/VCD/Standard/configuration.tpl.yaml, testing/cloud_layouts/script-commander.sh, testing/cloud_layouts/script.sh, testing/cloud_layouts/script_eks.sh, testing/cloud_layouts/vSphere/Standard/configuration.tpl.yaml
Removes leaked credentials used in the E2E test flow to access the container registry.  
Secrets have been revoked and replaced with a secure authentication method.
Tests: https://github.com/deckhouse/deckhouse/actions/runs/16554517266
Fixes a security issue: the exposed creds could allow unauthorized registry access.  
This update prevents misuse by rotating secrets and updating the test flow.
```changes
section: ci
type: fix 
summary: fix e2e creds
```
=> fix e2e creds

docs/documentation/_plugins/custom_sidebar.rb
Add support for displaying a "Preview" badge status in the custom sidebar plugin for documentation.
```changes
section: docs
type: chore
summary: Add preview badge status to sidebar plugin.
```
=> [docs] Add preview badge status to sidebar plugin

docs/site/backends/docs-builder-template/layouts/_partials/openapi/format-configuration.html, docs/site/backends/docs-builder-template/layouts/_partials/openapi/format-schema.html
Added settings. for external modules parameters rendering.
Before:
After:
```changes
section: docs
type: chore
summary: Added settings. for external modules parameters rendering.
```
=> [docs] Added settings. for external modules parameters rendering

testing/cloud_layouts/OpenStack/Standard/resources.yaml
For `inlet: HostWithFailover` no need `hostPort`
delete this
```changes
section: ci
type: fix
summary: For `inlet.HostWithFailover` no need `hostPort`.
```
=> fix: openstack e2e

dhctl/pkg/preflight/staticinstances_ip_duplication.go
Fix the issue that check can fail if somewhere in `resources.yaml` three minus signs in a row are used not for split yaml
Fix false-positive preflight fails
```changes
section: dhctl
type: fix
summary: Fix false-positive staticinstance ip duplication preflight checks fails.
```
=> [dhctl] Fix staticinstance ip duplication preflight check

.github/ci_templates/e2e_tests.yml, .github/workflows/e2e-abort-aws.yml, .github/workflows/e2e-abort-azure.yml, .github/workflows/e2e-abort-eks.yml, .github/workflows/e2e-abort-gcp.yml, .github/workflows/e2e-abort-openstack.yml, .github/workflows/e2e-abort-static.yml, .github/workflows/e2e-abort-vcd.yml, .github/workflows/e2e-abort-vsphere.yml, .github/workflows/e2e-abort-yandex-cloud.yml, .github/workflows/e2e-aws.yml, .github/workflows/e2e-azure.yml, .github/workflows/e2e-daily.yml, .github/workflows/e2e-eks.yml, .github/workflows/e2e-gcp.yml, .github/workflows/e2e-openstack.yml, .github/workflows/e2e-static.yml, .github/workflows/e2e-vcd.yml, .github/workflows/e2e-vsphere.yml, .github/workflows/e2e-yandex-cloud.yml, testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml, testing/cloud_layouts/Static/configuration.tpl.yaml, testing/cloud_layouts/VCD/Standard/configuration.tpl.yaml, testing/cloud_layouts/script-commander.sh, testing/cloud_layouts/script.sh, testing/cloud_layouts/script_eks.sh, testing/cloud_layouts/vSphere/Standard/configuration.tpl.yaml
Backport pr #14691
Removes leaked credentials used in the E2E test flow to access the container registry.  
Secrets have been revoked and replaced with a secure authentication method.
Tests: https://github.com/deckhouse/deckhouse/actions/runs/16554517266
Fixes a security issue: the exposed creds could allow unauthorized registry access.  
This update prevents misuse by rotating secrets and updating the test flow.
```changes
section: ci
type: fix 
summary: fix e2e creds
```
=> Backport fix e2e creds

ee/modules/040-node-manager/images/d8-shutdown-inhibitor/src/pkg/app/nodecondition/graceful_shutdown_postpone.go, ee/modules/040-node-manager/images/d8-shutdown-inhibitor/src/pkg/kubernetes/condition.go, ee/modules/040-node-manager/images/d8-shutdown-inhibitor/src/pkg/kubernetes/kubectl.go
Single quotes in arguments are dropped in bash, but are passed as-is in Go. Unmarshal in  ConditionFromJSON can't parse quoted JSON objects.
In some scenarios, condition GracefulShutdownPostpone may still present during Node startup. This PR fixes parsing problem in this situation.
Error from logs:
```
Jul 28 08:53:58 node-03 systemd[1]: Started Shutdown inhibitor to allow manual Pod eviction.
...
Jul 28 08:53:58 node-03 d8-shutdown-inhibitor[98271]: Stop all tasks...
...
Jul 28 08:53:59 node-03 d8-shutdown-inhibitor[98271]: Stop app...
Jul 28 08:53:59 node-03 d8-shutdown-inhibitor[98271]: Application stopped
Jul 28 08:53:59 node-03 d8-shutdown-inhibitor[98271]: ERROR: nodeConditionSetter patch Node to set condition: condition json unmarshal: invalid character '\'' looking for beginning …
```
=> [node-manager] fix reset of GracefulShutdownPostpone condition at start

ee/se/modules/380-metallb/hooks/discovery_l2_load_balancers.go, ee/se/modules/380-metallb/hooks/discovery_l2_load_balancers_test.go, ee/se/modules/380-metallb/hooks/types.go, ee/se/modules/380-metallb/hooks/update_service_status.go, ee/se/modules/380-metallb/hooks/update_service_status_test.go
There are many hooks in the module, two of which modify the `status` field in services. But each time they overwrite this field with new values. This PR allows them to add new values and update previously set `status` values.
The problem occurs if in a properly working cluster with MetalLB all `MetalLoadBalancerClass` are set to `isDefault: false` and no `loadBalancerClass` is specified, and then perform a pod Deckhouse reload. The module will stop announcing ARP and serving load-balancer IP addresses.
The problem affects customers who are using the MetalLB module now.
```changes
type: fix
summary: Fixed overwriting of Service `status` field by module components.
```
=> [metallb] fix overwriting of Service `status` field by module components

global-hooks/openapi/conversions/v2.yaml
Fix description in global ModuleConfig conversion (add info about removing deprecated properties from ModuleConfig).
Relevant to #13573
```changes
section: docs
type: chore
summary: Update `global` ModuleConfig conversion from v1 to v2.
```
=> [docs] Fix description in global-hooks/conversions/v2

docs/documentation/pages/admin/configuration/access/authentication/EXTERNAL_AUTHENTICATION_PROVIDERS.md, docs/documentation/pages/admin/configuration/access/authentication/EXTERNAL_AUTHENTICATION_PROVIDERS_RU.md
This PR adds Keycloak configuration details, mirroring contents of [another PR](https://github.com/deckhouse/deckhouse/pull/14755) pulled to the `main` earlier.
=> [docs][new structure] Add Keycloak details

modules/150-user-authn/docs/USAGE.md, modules/150-user-authn/docs/USAGE_RU.md
Information about KeyCloak settings has been added in case email verification is not used.
Some users cannot change KeyCloak settings and delete the `email_verified` mapping. To bypass email verification, a method was proposed with the configuration of `client scopes` `email`.
Added information about configuring KeyCloak, which does not use email verification.
```changes
section: docs
type: fix
summary: Correction of KeyCloak documentation in d8-user-authn
impact: Users will know how to configure KeyCloak and dexProvider to get user rights in dashboard and console.
```
=> [docs][user-authn] Correction of KeyCloak documentation in d8-user-authn

docs/site/assets/js/filter.js, docs/site/assets/js/tile.js
Fix pagination in guides filter.
```changes
section: docs
type: chore
summary: Fix pagination in guides.
```
=> [docs] Fix pagination in guides filter

modules/038-registry/module.yaml, modules/200-operator-prometheus/module.yaml, modules/300-prometheus/module.yaml, modules/301-prometheus-metrics-adapter/module.yaml, modules/303-prometheus-pushgateway/module.yaml, modules/340-extended-monitoring/module.yaml, modules/340-monitoring-custom/module.yaml, modules/340-monitoring-deckhouse/module.yaml, modules/340-monitoring-kubernetes-control-plane/module.yaml, modules/340-monitoring-kubernetes/module.yaml, modules/340-monitoring-ping/module.yaml, modules/460-log-shipper/module.yaml, modules/462-loki/module.yaml, modules/500-cilium-hubble/module.yaml, modules/500-okmeter/module.yaml
Modules should use requirements with deckhouse version when used stage properties
fix lint on deckhouse build
```changes
section: tools
type: fix
summary: add Deckhouse version requirements to multiple module configurations
```
=> [tools] add Deckhouse version requirements to multiple module configurations

docs/documentation/pages/admin/configuration/access/authentication/EXTERNAL_AUTHENTICATION_PROVIDERS.md, docs/documentation/pages/admin/configuration/access/authentication/EXTERNAL_AUTHENTICATION_PROVIDERS_RU.md, docs/documentation/pages/admin/configuration/storage/external/NFS.md, docs/documentation/pages/admin/configuration/storage/external/NFS_RU.md, docs/documentation/pages/admin/configuration/storage/external/YADRO.md, docs/documentation/pages/admin/configuration/storage/external/YADRO_RU.md, docs/documentation/pages/admin/configuration/storage/sds/lvm-local/LVM_LOCAL.md, docs/documentation/pages/admin/configuration/storage/sds/lvm-local/LVM_LOCAL_RU.md, docs/documentation/pages/admin/configuration/storage/sds/lvm-replicated/LVM_REPLICATED.md, docs/documentation/pages/admin/configuration/storage/sds/lvm-replicated/LVM_REPLICATED_RU.md
Replace WEITH to STAGE in information about module.
```changes
section: docs
type: chore
summary: Replace WEITH to STAGE in information about module.
```
=> [docs] Replace WEITH to STAGE in information about module

docs/documentation/pages/DECKHOUSE-CLI.md, docs/documentation/pages/DECKHOUSE-CLI_RU.md, docs/site/pages/stronghold/reference/console-utilities/D8.md, docs/site/pages/stronghold/reference/console-utilities/D8_RU.md, docs/site/pages/virtualization-platform/reference/console-utilities/D8.md, docs/site/pages/virtualization-platform/reference/console-utilities/D8_RU.md
Replace `d8 d` command with `d8 dk` in the documentation.
```changes
section: docs
type: chore
summary: Replace `d8 d` command with `d8 dk` in the documentation.
```
=> [docs] Change d8 d command to d8 dk in the documentation

deckhouse-controller/pkg/controller/module-controllers/config/controller_test.go, deckhouse-controller/pkg/controller/module-controllers/config/status.go, deckhouse-controller/pkg/controller/module-controllers/config/testdata/change-source.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/disable-module.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/disable-with-releases.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/embedded-module.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/enable-module.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/global-config.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/golden/change-source.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/golden/disable-module.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/golden/disable-with-releases.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/golden/embedded-module.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/golden/enable-module.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/golden/global-config.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/golden/multiple-sources.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/golden/unknown-module.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/multiple-sources.yaml, deckhouse-controller/pkg/controller/module-controllers/config/testdata/unknown-module.yaml
Added tests for the internal config module using the same approach as I found in adjacent modules (source module) to cover config internal module's reconciler logic
To have a little bit more coverage in unit tests
Actually it seems that we do not need to patch release with this PR, this is just a unit test
The logic is the same with no edits, changed only test code
```changes
type: chore
summary: just a test for the config module
impact: no impact on production code
```
=> [deckhouse] tests for the internal config module

ee/modules/040-node-manager/templates/monitoring.yaml
Hide Nvidia GPU dashboards if there is no GPU nodes in a cluster
These dashboards only required if there are Nvidia GPU nodes in the cluster. They should be hided otherwise.
Dashboards comes to 1.71, so we need to hide them
```changes
type: fix
summary: Hide Nvidia GPU dashboards if there is no GPU nodes in a cluster.
```
=> [node-manager] Update monitoring template: hide GPU dashboards

.github/ci_templates/web.yml, .github/scripts/js/ci.js, .github/scripts/js/comments.js, .github/scripts/js/constants.js, .github/workflow_templates/deploy-web.multi.yml, .github/workflows/deploy-web-stage.yml, .github/workflows/deploy-web-test2.yml, .github/workflows/deploy-web-test3.yml, .github/workflows/deploy-web-test4.yml
Add new environments: test2, test3, and test4 for deployment deployment.
Update corresponding workflow files and constants to reflect changes.
Use corresponding label: deploy/web/test[234]
```changes
section: ci
type: chore
summary: Add new environments for documentation deployment.
```
=> [ci][docs] Add more environments for deployment documentation

docs/site/backends/docs-builder/internal/docs/build.go, docs/site/backends/docs-builder/internal/docs/build_test.go, docs/site/backends/docs-builder/pkg/hugo/commandeer.go, docs/site/backends/docs-builder/pkg/hugo/commandeer_test.go
This PR fixes issue during calling HugFromConfig causing the panic. To get the panic it was enough to:
1) [docs/site/backends/docs-builder-template/layouts/baseof.html](https://github.com/deckhouse/deckhouse/blob/main/docs/site/backends/docs-builder-template/layouts/baseof.html) - edit this file and broke something (syntax or invalid variable name)
2) run server locally:
```
mkdir -p ~/test-docs-builder/{src,dst}
cp -r docs/site/backends/docs-builder-template/* ~/test-docs-builder/src/
go run main.go --src ~/test-docs-builder/src --dst ~/test-docs-builder/dst --address :8081
```
3) generate the docs:
```
curl -X POST http://localhost:8081/api/v1/build \
-H "Content-Type: application/json" \
-d '{}'
```
4) Ensure that there is no panic in logs after fix(previously it was)
With this fix I …
=> [docs-builder] Hugo config error handling

ee/modules/500-operator-trivy/hooks/storage_class_change.go, ee/modules/500-operator-trivy/hooks/storage_class_change_test.go, go_lib/hooks/storage_class_change/hook.go, modules/000-common/hooks/storage_class_change_test.go
Added ability to allow emptyDir usage for specific modules without generating `DeckhouseModuleUseEmptyDir` alert.
**Problem:** operator-trivy sends `DeckhouseModuleUseEmptyDir` alert when using emptyDir, even though emptyDir usage is correct and safe for this module.
**Solution:** Added `AllowEmptyDir` flag that allows modules to explicitly permit emptyDir usage without generating false positive alerts.
```changes
type: feature
summary: Fix false positive DeckhouseModuleUseEmptyDir alert for operator-trivy
```
=> [deckhouse] operator-trivy hook new param AllowEmptyDir

ee/modules/110-istio/templates/alliance/metadata-exporter/deployment.yaml
There is a typo in the metadata exporter's template - the metadata_exporter_resources macro must be used instead of metadata_discovery_resources.
If the vertical-pod-autoscaler module is disabled, the istio module fails to render with the error:
```
1. ConvergeModules:main:::Operator-Startup
Queue 'parallel_queue_10': length 1, status: 'sleep after fail for 32s (24s left of 32s delay)'
1. ModuleRun:parallel_queue_10:istio:doStartup:OperatorStartup:failures 18:run helm install: template: istio/templates/alliance/metadata-exporter/deployment.yaml:103:16: executing "istio/templates/alliance/metadata-exporter/deployment.yaml" at <include "metadata_discovery_resources" .>: error calling include: template: no template "metadata_discovery_resources" associated with template "gotpl"
Use --debug …
```
=> [istio] fixed metadata exporter template

candi/bashible/common-steps/all/032_configure_containerd.sh.tpl, candi/bashible/common-steps/all/076_install_d8_shutdown_inhibitor.sh.tpl, ee/modules/040-node-manager/images/d8-shutdown-inhibitor/scripts/d8-shutdown-inhibitor.service, ee/modules/040-node-manager/images/d8-shutdown-inhibitor/src/pkg/app/app.go, ee/modules/040-node-manager/images/d8-shutdown-inhibitor/src/pkg/app/nodecondition/graceful_shutdown_postpone.go, ee/modules/040-node-manager/images/d8-shutdown-inhibitor/src/pkg/app/tasks/node_cordoner.go, ee/modules/040-node-manager/images/d8-shutdown-inhibitor/src/pkg/app/tasks/pod_observer.go, modules/040-node-manager/hooks/update_approval.go
fixed containerd migration v1 <> v2
Related to:  https://github.com/deckhouse/deckhouse/pull/12674 https://github.com/deckhouse/deckhouse/pull/14370
- Added forced stopping and deleting of all containers. Stopping containerd-deckhouse.service is not guaranteed to stop containers. Especially relevant for single-master installations
- Minor fix in `modules/040-node-manager/hooks/update_approval.go` -  skip draining node if the annotation `update.node.deckhouse.io/disruption-approved=` is set
- Minor fix in the inhibitor - now it only launches nodeCordon if pods with the label `pod.deckhouse.io/inhibit-node-shutdown` are detected on the node.
- Minor fix in the  Inhibitor (candi) - it now restarts after update
```changes
section: candi, node-manager
type: fix
summary: containerd migration …
```
=> [candi] containerd migration fix

modules/040-node-manager/hooks/discover_standby_ng.go, modules/040-node-manager/hooks/discover_standby_ng_test.go
Fixed RAM size calculation in discover_standby_ng_test.go hook
There seems to be some mistake between MI (^2) and MB (^10).
4126652008 bytes /2 (50%) / 1024 / 1024 must be 1967 Mi
but now we have 2064Mi (looks like 4126652008/2/1000/1000)
```changes
type: fix 
summary: fix calculation of memory for standby holder
impact:
```
=> [node-manager] fix standby-ng calculation

Makefile, modules/040-node-manager/hooks/update_approval.go, modules/040-node-manager/hooks/update_approval_test.go
We redesigned it to use new node abstractions in clouds.
Using outdated node abstractions in clouds
```changes
type: chore
summary: usage Instance in update_approval
impact: 
```
=> [node-manager] usage Instance in update_approval

ee/modules/030-cloud-provider-huaweicloud/images/cloud-data-discoverer/werf.inc.yaml
Adds discovery logic so Cluster Autoscaler can create nodes starts with zero replicas
Huawei clusters can not autoscale from zero.
```changes
type: feature
summary: discovery logic so Cluster Autoscaler can create nodes starts with zero replicas
```
=> [cloud-provider-huaweicloud] Make huawei autoscaler "scale from zero" 

ee/be/modules/350-node-local-dns/templates/configmap.yaml
The "servfail 0" option of the CoreDNS cache plugin is introduced in order to disable caching SERVFAIL responses as it can cause cache poisoning.
It was tested and proven that CoreDNS cache plugin with "serve_stale 1h immediate" option is subjected to poisoning when an upstream server returns a SERVFAIL response. Such a response would be staying in the cache and used in subsequent responses to clients for an hour due to an unknown CoreDNS issue related to updating cached negative responses.
Despite the fact that "serve_stale 1h verify" mode, for some reason, seems to be unaffected by the issue, it was decided to disable caching SERVFAIL responses at all.
```changes
type: chore
summary: Caching SERVFAIL responses is disabled.
```
=> [node-local-dns] disable caching servfail

modules/101-cert-manager/hooks/create_registry_secret_for_solver.go
Sometimes cert-manager secrets and service accounts get stuck during deletion
The hook responsible for cleaning up completed ACME challenge dependencies deletes the related secret and service account synchronously, so when it gets stuck, it causes a bunch of problems
```changes
type: fix
summary: clean up ACME challenge with `background` propagation policy
```
=> [cert-manager] delete challenges and secrets with `background` propagation policy

docs/site/_includes/getting_started/bm/STEP_FINALIZE.md, docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md, docs/site/_includes/getting_started/dvp/global/STEP_USER.md, docs/site/_includes/getting_started/dvp/global/STEP_USER_RU.md, docs/site/_includes/getting_started/stronghold/bm/STEP_FINALIZE.md, docs/site/_includes/getting_started/stronghold/bm/STEP_FINALIZE_RU.md
This pull request updates the documentation to clarify file paths when applying Kubernetes manifests, ensuring that commands explicitly reference files in the current working directory. This change is applied consistently across both English and Russian documentation for multiple deployment scenarios.
```changes
section: docs
type: fix
summary: |
Fixed `sudo -i` command in GS pages.
```
=> [docs][getting-started] Fix sudo -i command in GS pages

docs/documentation/_data/storage/crds/doc-ru-nfsstorageclass.yaml, docs/documentation/_data/storage/crds/nfsstorageclass.yaml
Added info about nfsstorageclass in documentation.
```changes
section: docs
type: chore
summary: Added info about nfsstorageclass in documentation.
```
=> [docs] Minor updates in nfsstorageclass documentation

dhctl/pkg/app/app.go, dhctl/pkg/preflight/common.go, dhctl/pkg/system/node/gossh/file.go
Fix tunnel string in preflight checks
Preflight check `Checking if Cloud API is accessible through proxy` fails in case of wrong tunnel string. We should fix it.
```changes
section: dhctl
type: fix
summary: Fix tunnel string in preflight checks.
```
=> [dhctl] Fix tunnel string in preflight checks

candi/control-plane-kubeadm/v1beta3/config.yaml.tpl, modules/040-control-plane-manager/template_tests/template_test.go, modules/040-control-plane-manager/templates/_authentication_configuration.tpl
When adding `AuthenticationConfiguration` in #14788, it was not taken into account that depending on the version of kubernetes, different versions of the api `apiserver.config.k8s.io` should be used.
This revision eliminates this problem
Improving code quality
```changes
type: fix 
summary: Add different api version for "apiserver.config.k8s.io" depends kube version
```
=> [control-plane-manager] Add different api version for `apiserver.config.k8s.io` depends kube version

candi/cloud-providers/aws/layouts/standard/base-infrastructure/main.tf, candi/cloud-providers/aws/layouts/standard/base-infrastructure/variables.tf, candi/cloud-providers/aws/layouts/standard/master-node/main.tf, candi/cloud-providers/aws/layouts/standard/master-node/variables.tf, candi/cloud-providers/aws/layouts/standard/static-node/main.tf, candi/cloud-providers/aws/layouts/standard/static-node/variables.tf, candi/cloud-providers/aws/layouts/with-nat/base-infrastructure/main.tf, candi/cloud-providers/aws/layouts/with-nat/base-infrastructure/variables.tf, candi/cloud-providers/aws/layouts/with-nat/master-node/main.tf, candi/cloud-providers/aws/layouts/with-nat/master-node/variables.tf, candi/cloud-providers/aws/layouts/with-nat/static-node/main.tf, candi/cloud-providers/aws/layouts/with-nat/static-node/variables.tf, candi/cloud-providers/aws/layouts/without-nat/base-infrastructure/main.tf, candi/cloud-providers/aws/layouts/without-nat/base-infrastructure/variables.tf, candi/cloud-providers/aws/layouts/without-nat/master-node/main.tf, candi/cloud-providers/aws/layouts/without-nat/master-node/variables.tf, candi/cloud-providers/aws/layouts/without-nat/static-node/main.tf, candi/cloud-providers/aws/layouts/without-nat/static-node/variables.tf, candi/cloud-providers/aws/openapi/cloud_discovery_data.yaml, candi/cloud-providers/aws/openapi/cluster_configuration.yaml, candi/cloud-providers/aws/openapi/doc-ru-cluster_configuration.yaml, candi/cloud-providers/aws/terraform-modules/master-node/main.tf, candi/cloud-providers/aws/terraform-modules/master-node/variables.tf, candi/cloud-providers/aws/terraform-modules/security-groups/main.tf, candi/cloud-providers/aws/terraform-modules/security-groups/outputs.tf, candi/cloud-providers/aws/terraform-modules/security-groups/variables.tf, candi/cloud-providers/aws/terraform-modules/static-node/main.tf, candi/cloud-providers/aws/terraform-modules/static-node/variables.tf, testing/cloud_layouts/script-commander.sh
Make the creation of default security groups optional.
https://github.com/deckhouse/deckhouse/issues/9919
```changes
type: feature
summary: Make the creation of default security groups optional.
```
=> [cloud-providers-aws] Make creation of default security groups optional

candi/cloud-providers/dvp/openapi/cluster_configuration.yaml, candi/cloud-providers/dvp/openapi/doc-ru-cluster_configuration.yaml
Fixed broken links at DVP cloud provider documentation.
```changes
section: docs
type: chore
summary: Fixed broken links at DVP cloud provider documentation.
```
=> [docs] Fix broken links at DVP cloud provider documentation

modules/000-common/images/crane/werf.inc.yaml, modules/007-registrypackages/images/kubernetes-api-proxy/werf.inc.yaml, modules/007-registrypackages/images/pause/werf.inc.yaml
this pr allow disable crane issue with tag "i-was-a-digest" with dev-registry.deckhouse.io when pull image artifact.
ex.
```
werf.yaml
dependencies:
- image: control-plane-manager/kubernetes-api-proxy
before: setup
imports:
- type: ImageDigest
targetEnv: IMAGE_DIGEST
- type: ImageRepo
targetEnv: IMAGE_REPO
...
shell:
setup:
- /crane pull $IMAGE_REPO@$IMAGE_DIGEST $param /kubernetes-api-proxy.tar
...
/kubernetes-api-proxy # cat manifest.json
..."RepoTags":["dev-registry.deckhouse.io/sys/deckhouse-oss:i-was-a-digest"],"Layers":...
```
this pr resolve issues when images pulled from private repos have tag "i-was-a-digest" with "dev-registry.deckhouse.io"
```
kubectl get no -oyaml
...
before
images:
- names:
- deckhouse.local/images:kubernetes-api-proxy
- …
```
=> [common] Disable tag "i-was-a-digest" when crane pull image by digest.

dhctl/pkg/system/node/session/session.go
Fix SSH connection string shown by bootstraping process
If any SSH port set, connection string shows not correctly and user cannot just copy and paste it to connect to first master host
```changes
section: dhctl
type: fix
summary: Fix SSH connection string.
```
=> [dhctl] Fix connection string

modules/402-ingress-nginx/images/controller-1-10/werf.inc.yaml, modules/402-ingress-nginx/images/controller-1-12/werf.inc.yaml
The following changes are introduced:
- The size of the ingress-nginx controller image is reduced by deleting extra locale data from the /chroot/usr/lib64/locale directory (it took approximately 1GB of disk space);
- The missing library
```
nginx: [emerg] dlopen() "/etc/nginx/modules/otel_ngx_module.so" failed (libupb_wire_lib.so.45: cannot open shared object file: No such file or directory)
``` 
issue was fixed.
It fixes the missing opentelemetry library issue.
```changes
type: fix
summary: The missing opentelemetry libraries issue is fixed.
impact: The pods of Ingress Nginx controllers of 1.10 and 1.12 versions will be restated.
```
=> [ingress-nginx] fix opentelemetry missing library and shrink ingress-nginx controller image

docs/site/_sass/components/_filter.scss
Fix asset file paths in _filter.scss to use absolute paths for background images.
```changes
section: docs
type: chore
summary: Fix asset file paths in _filter.scss to use absolute paths for background images.
```
=> [docs] Fix asset file paths

deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_module_source.go
We tried to check the old source, but it does not exist when its a creating operation. 
It fixes source creating.
Before:
```
root@paksashvili-master-0:~# k apply -f modules/losevsource.yaml
Error from server (InternalError): error when creating "modules/losevsource.yaml": Internal error occurred: failed calling webhook "module-sources.deckhouse-webhook.deckhouse.io": failed to call webhook: an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1\",\"response\":{\"uid\":\"2abc12f2-3c5a-4ab1-8a72-7746e671e50f\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"validator error: parse old source: EOF\"}}}") has prevented the request from succeeding
```
After:
```
root@paksashvili-master-0:~# k apply -f …
```
=> [deckhouse] fix validate creating module config

ee/modules/030-cloud-provider-vcd/images/capcd-controller-manager-legacy/patches/002-go-mod.patch, ee/modules/030-cloud-provider-vcd/images/cloud-controller-manager-legacy/patches/005-add-vapptemplate-search-by-org.patch, ee/modules/030-cloud-provider-vcd/images/cloud-controller-manager-legacy/patches/README.md
`getCatalog()` failed to retrieve VM templates from organization catalogs lacking direct permissions.
Implemented indirect catalog access path
```changes
type: fix
summary: Fix fetching VM templates from organization catalogs without direct access to organizastion
```
=> [cloud-provider-vcd] Fix Template Org catalog querying

ee/modules/650-runtime-audit-engine/template_tests/module_test.go, ee/modules/650-runtime-audit-engine/templates/daemonset.yaml, ee/modules/650-runtime-audit-engine/templates/falco-leak-limit-range.yaml
Temporarily set `updateMode` for falco VPA to `Off` so that it does not try to go over 1Gi limit and interfere with memory limiting introduced in https://github.com/deckhouse/deckhouse/pull/14818
This fixes falco daemonsets not being able to schedule due to VPA going crazy and constantly raising memory limits over the ceiling set with the LimitRange from https://github.com/deckhouse/deckhouse/pull/14818
See above ^
```changes
type: chore
summary: Disable VPA for Falco until it's memory leak is fixed
```
=> [runtime-audit-engine] Disable falco VPA until memory leak is fixed

modules/002-deckhouse/templates/default-module-source.yaml
Make ModuleSource installed in cluster without bootstrap check
```changes
type: fix
summary: ModuleSource will be installed in cluster without bootstap check
```
=> [deckhouse] ModuleSource must install without cluster bootstrapped

.github/ci_templates/helper_jobs.yml, .github/workflows/cve-pr.yml, .github/workflows/e2e-aws.yml, .github/workflows/e2e-azure.yml, .github/workflows/e2e-eks.yml, .github/workflows/e2e-gcp.yml, .github/workflows/e2e-openstack.yml, .github/workflows/e2e-static.yml, .github/workflows/e2e-vcd.yml, .github/workflows/e2e-vsphere.yml, .github/workflows/e2e-yandex-cloud.yml
Disable e2e blocking for non-PR jobs.
Blocking for release branch tests if incorrect and should be disabled.
Blocks pre-release tests.
```changes
section: ci
type: chore
summary: Disable e2e blocking for non-PR jobs.
```
=> [ci] Disable e2e blocking for non-PR jobs

deckhouse-controller/crds/module.yaml
It removes bundle enum
We put bundles from a module definition - invalid bundle there causes crash module creating.
Invalid bundle can crash module`s creating and deckhouse.
```changes
type: fix
summary: Remove bundle enum
```
=> [deckhouse] remove bundle enum

modules/300-prometheus/templates/prometheus/_helpers.tpl, modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml, modules/300-prometheus/templates/prometheus/prometheus.yaml
This PR fixes a misindentation in the securityContext of the initContainer, which resulted in an invalid resource manifest. Because of this, Prometheus configuration changes might not have been applied.
Yes. This issue affects virtually all clusters
```changes
type: fix
summary: fix securityContext indentation in the Prometheus main and longterm resources
impact: main and longterm Prometheuses will be rollout-restarted
```
=> [prometheus] Fix initContainer securityContext indent

modules/040-control-plane-manager/docs/FAQ.md, modules/040-control-plane-manager/docs/FAQ_RU.md
Edit steps to restore objects from an etcd backup.
```changes
section: docs
type: chore
summary: Edited steps to restore objects from an etcd backup.
```
=> [docs] Edit info about restore etcd objects

tools/dmt-lint.sh
update dmt to v0.1.33
added new linters
```changes
section: tools
type: chore
summary: update dmt to v0.1.33
```
=> [tools] update dmt to v0.1.33

ee/modules/040-node-manager/images/d8-shutdown-inhibitor/scripts/d8-shutdown-inhibitor.service
follow https://github.com/deckhouse/deckhouse/pull/14622
Changed ExecStartPre in d8-shutdown-inhibitor.service
In some operating systems, echo >/dev/tcp/127.0.0.1/6445 does not work.
```changes
section: candi
type: fix
summary: Changed ExecStartPre in d8-shutdown-inhibitor.service
impact:
```
=> [candi] fix ExecStartPre in d8-shutdown-inhibitor.service

ee/be/modules/140-user-authz/images/webhook/src/go.mod, ee/be/modules/140-user-authz/images/webhook/src/go.sum
Bump golang.org/x/oauth2 to include fixes for CVE-2025-22868
Audit prerequisite
```changes
type: chore
summary: Fix CVE-2025-22868
```
=> [user-authz] Fix CVE-2025-22868

docs/documentation/pages/DECKHOUSE-FAQ.md, docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Added steps how to patch secret before `deckhouse-controller helper change-registry`.
It solves problem with incorrect `.dockerconfigjson` after `deckhouse-controller helper change-registry`.
```changes
section: docs
type: fix
summary: Added steps that patch secret and prevented the image pull fail.
```
=> [docs] Add steps that patch secret and prevent the image pull fail

Makefile
This pull request updates the way the `docs` and `docs-dev` Makefile targets invoke the `werf` binary for building documentation containers. The main change is adjusting the path to the `werf` executable to ensure it is correctly referenced from the documentation directories.
The problem arose after [this PR](https://github.com/deckhouse/deckhouse/pull/15077):
```
$ make docs
mkdir -p bin
docker network inspect deckhouse 2>/dev/null 1>/dev/null || docker network create deckhouse
cd docs/documentation/; bin/werf compose up --docker-compose-command-options='-d' --env local --repo ":local" --skip-image-spec-stage=true
/bin/sh: bin/werf: No such file or directory
make: *** [docs] Error 127
```
Documentation build process improvements:
* Updated the commands in the `docs` and `docs-dev` …
=> [docs] Fix the local launch of documentation

deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module.go, deckhouse-controller/pkg/controller/controller.go, deckhouse-controller/pkg/controller/module-controllers/config/controller.go, deckhouse-controller/pkg/controller/module-controllers/override/controller.go, deckhouse-controller/pkg/controller/module-controllers/source/controller.go, deckhouse-controller/pkg/controller/module-controllers/source/helpers.go, deckhouse-controller/pkg/controller/module-controllers/source/testdata/proceed-enabled-modules-without-default.yaml, deckhouse-controller/pkg/controller/module-controllers/source/testdata/proceed-enabled-modules.yaml, deckhouse-controller/pkg/controller/moduleloader/sync.go
It fixes ensuring mr process.
If a user disabled a module via its config, we should not ensure mr.
Without it deckhouse may stuck in restarting loop 
```changes
type: fix
summary: Dont ensure releases of disabled modules.
```
=> [deckhouse] dont ensure mrs of disabled modules

modules/160-multitenancy-manager/docs/README.md, modules/160-multitenancy-manager/docs/README_RU.md
Fix relative links in the multitenancy-manager module documentation.
```changes
section: docs
type: fix
summary: Fix relative links in the multitenancy-manager module documentation.
```
=> [docs] Fix relative links in multitenancy-manager module

deckhouse-controller/pkg/controller/module-controllers/config/controller.go, deckhouse-controller/pkg/controller/module-controllers/downloader/downloader.go
Fixed fallback module definition downloading.
Fixed behavior when module config is disabled - module receives DisabledModuleConfig status
```yaml
kind: Module
metadata:
name: s-p-test
status:
conditions:
- lastProbeTime: "2025-08-26T14:06:24Z"
lastTransitionTime: "2025-08-26T14:06:24Z"
status: "False"
type: EnabledByModuleManager
- lastProbeTime: "2025-08-26T14:06:25Z"
lastTransitionTime: "2025-08-26T14:06:24Z"
message: downloading
reason: Downloading
status: "False"
type: IsReady
phase: Downloading
```
```yaml
kind: Module
metadata:
name: s-p-test
status:
conditions:
- lastProbeTime: "2025-08-26T16:15:14Z"
lastTransitionTime: "2025-08-26T16:15:14Z"
status: "False"
type: EnabledByModuleConfig
- lastProbeTime: …
```
=> [deckhouse-controller] Fix module config condition setting, fix module definition downloading

modules/500-dashboard/enabled, modules/500-dashboard/module.yaml
It adds ```user-authz``` requirement for the module ```dashboard```.
After removing weight, all non critical modules have the 'same' weight, which may cause the script to be unaware of whether ```user-authz``` has been enabled.
For example:
```
root@paksashvili-master-0:~# k get module dashboard -owide
NAME        WEIGHT   STAGE        RELEASE CHANNEL   SOURCE     VERSION                PHASE        ENABLED   DISABLED MESSAGE                                                         READY
dashboard   900      Deprecated   Stable            Embedded   v1.73.0-main+9bde9c9   Downloaded   False     turned off by enabled script: 'user-authz' module needs to be enabled.   False
root@paksashvili-master-0:~# k get module user-authz
NAME         STAGE                  SOURCE     PHASE   ENABLED …
```
=> [dashboard] add user-authz requirement

deckhouse-controller/pkg/controller/moduleloader/types/definition.go
It remove weight constraints for modules
Critical modules have weight less than 900
```changes
type: chore
summary: Remove module weight constraints.
```
=> [deckhouse] remove module weight constraint

dhctl/pkg/preflight/common.go
Fix legacy SSH tunnel preflight check panic
If flag `--ssh-legacy-mode` is used with `--ask-become-pass`, it causes panic in preflight check
This preflight was changed in v1.72, so we need to fix it.
```changes
section: dhctl
type: fix
summary: Fix legacy SSH tunnel preflight check panic.
```
=> [dhctl] Fix legacy SSH tunnel preflight check

modules/150-user-authn/hooks/get_dex_user_crds.go, modules/150-user-authn/webhooks/validating/group.py, modules/150-user-authn/webhooks/validating/group_cycle_test.py, modules/150-user-authn/webhooks/validating/group_test.py
Add `Group` validation webhook which detects recursive loops in nested group's hierarchy.
Users can create `Groups` with  potentially cycled nested subgroups relations, resulting in infinite loops when resolving dependent subgroups. Example stack trace is shown below.
```
{"level":"info","msg":"Binding contexts from tasks. Tasks are dropped from queue","count":2,"filteredCount":1,"queueName":"/modules/user-authn","tasks":"are combined and compacted to 1 contexts","time":"2025-08-19T12:52:17Z"}
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc029790340 stack=[0xc029790000, 0xc049790000]
fatal error: stack overflow
runtime stack:
runtime.throw({0x3b60fb9?, 0x200000008?})
/usr/local/go/src/runtime/panic.go:1101 +0x48 fp=0xc001815e90 sp=0xc001815e60 pc=0x479dc8 …
```
=> [user-authn] add groups cycle validation

modules/015-admission-policy-engine/docs/GATEKEEPER-CR.md, modules/015-admission-policy-engine/docs/GATEKEEPER-CR_RU.md
Added example at admission-policy-engine documentation.
```changes
section: docs
type: chore
summary: Added example at admission-policy-engine documentation.
```
=> [docs] Add example at admission-policy-engine documentation

.github/workflow_templates/e2e.abort.multi.yml, .github/workflows/e2e-abort-aws.yml, .github/workflows/e2e-abort-azure.yml, .github/workflows/e2e-abort-eks.yml, .github/workflows/e2e-abort-gcp.yml, .github/workflows/e2e-abort-openstack.yml, .github/workflows/e2e-abort-static.yml, .github/workflows/e2e-abort-vcd.yml, .github/workflows/e2e-abort-vsphere.yml, .github/workflows/e2e-abort-yandex-cloud.yml
Add containerdv2 to e2e-abort workflows.
Fixes absence of e2e-abort containerdv2 jobs.
```changes
section: ci
type: chore
summary: Add containerdv2 to e2e-abort workflows.
```
=> [chore] ContainerdV2 destroy cluster

modules/150-user-authn/templates/validation.yaml
Fix the `ValidatingAdmissionPolicy` for the `User` CR by updating the validation expression.  
Now the rule checks:  
```rego
oldObject == null || object.spec.password == oldObject.spec.password
```  
This ensures that validation passes on `CREATE` (where `oldObject` is `null`) and still enforces password immutability on `UPDATE`.  
Previously, the policy tried to compare `object.spec.password` with `oldObject.spec.password` even during `CREATE` operations, where `oldObject` does not exist.  
As a result, creating new `User` resources failed.  
With this fix, user creation works correctly, while password immutability is still enforced for updates.  
Yes, because the bug directly prevents creating `User` resources in clusters with password policy enabled.  
This is a functional regression …
=> [user-authn] Hotfix USER CR ValidatingAdmissionPolicy oldObject == null

.werf/werf-modules.yaml, candi/bashible/common-steps/all/034_ctr_import_local_images.sh.tpl, candi/bashible/common-steps/all/051_pull_and_configure_kubernetes_api_proxy.sh.tpl, modules/007-registrypackages/images/kubernetes-api-proxy/werf.inc.yaml, modules/007-registrypackages/images/pause/werf.inc.yaml, werf-giterminism.yaml, werf.yaml
Import local images(k8s-api-proxy and pause) without oci.image.index manifest.
1. Import without `application/vnd.oci.image.index.v1+json ` 
2. Set image name and tag at the stage of creating the tar archive.
```changes
section: candi
type: chore
summary: Import local images without oci.image.index manifest. 
```
=> [candi] Import local images without oci.image.index manifest.

.github/scripts/cve_scan.sh
Upload DKP cve results per modules into DD
Currently DKP modules goes into the same product in DD
```changes
section: ci
type: chore
summary: Upload DKP cve results per modules into DD
impact: none
```
=> Upload DKP cve results per modules into DD

dhctl/pkg/operations/converge/controller/node_group_controller.go, dhctl/pkg/system/node/gossh/client.go
Minor improvements in SSH behavior (client and converge)
If node is down/unreachable, connect by SSH may fails many time in a row. We should choose a new host(fallback) any time it fails.
We should improve go ssh behavior, introduced in 1.72.0
```changes
section: dhctl
type: fix
summary: Improve SSH client start logic.
```
=> [dhctl] SSH client improvements

dhctl/cmd/dhctl/commands/bootstrap/phase.go, dhctl/cmd/dhctl/commands/destroy.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go, dhctl/pkg/operations/converge/infrastructure/hook/controlplane/kube-proxy.go, dhctl/pkg/system/node/gossh/default.go, dhctl/pkg/system/node/ssh/privatekeys.go
Add logic for re-prompt ssh key passphrase and handle error.
If user put a wrong ssh key passphrase, operations continues as usual, but ssh client fails to start. We should re-ask passphrase if it's wrong and don't start operation if ssh key cannot be parsed.
Version since 1.72 affected
```changes
section: dhctl
type: fix
summary: Add logic for re-prompt ssh key passphrase and handle error.
```
=> [dhctl] Improve wrong ssh key passphrase handling

deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_deckhouse_release.go, deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_deckhouse_release_test.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/migrated-module-not-enabled.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/migrated-modules-empty-migrated-modules.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/migrated-modules-mc-disabled-not-in-source.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/migrated-modules-mc-enabled-in-source.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/migrated-modules-mc-enabled-not-in-source.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/migrated-modules-module-missing.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/migrated-modules-module-pull-error.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/migrated-modules-modules-available.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/migrated-modules-no-migrated-modules.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/migrated-module-not-enabled.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/migrated-modules-empty-migrated-modules.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/migrated-modules-mc-disabled-not-in-source.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/migrated-modules-mc-enabled-in-source.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/migrated-modules-mc-enabled-not-in-source.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/migrated-modules-module-missing.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/migrated-modules-module-pull-error.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/migrated-modules-modules-available.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/migrated-modules-no-migrated-modules.yaml, deckhouse-controller/pkg/releaseupdater/requirements_checker.go
Backport: https://github.com/deckhouse/deckhouse/pull/15145
This PR modifies the DeckhouseRelease controller to properly handle migrated modules validation. Previously, the system would ignore disabled migrated modules during release validation. Now, the system explicitly rejects DeckhouseRelease objects that specify disabled modules in their `migratedModules` requirement, as migration cannot occur for disabled modules.
The changes include:
- Updated `MigratedModulesCheck` logic in `requirements_checker.go` to skip checks if we have module, but it's disabled.
- Added comprehensive test coverage for both validation and controller packages
- Renamed test cases to follow consistent naming convention (matching YAML file names without extension)
- Fix for manual aprove in …
=> [deckhouse-controller] ignore migrate module if disabled

modules/402-ingress-nginx/images/controller-1-10/patches/018-disable-error-logs.patch, modules/402-ingress-nginx/images/controller-1-10/patches/README.md, modules/402-ingress-nginx/images/controller-1-10/werf.inc.yaml, modules/402-ingress-nginx/images/controller-1-12/patches/016-disable-error-logs.patch, modules/402-ingress-nginx/images/controller-1-12/patches/README.md, modules/402-ingress-nginx/images/controller-1-9/patches/ingress-nginx/015-disable-error-logs.patch, modules/402-ingress-nginx/images/controller-1-9/patches/ingress-nginx/README.md, modules/402-ingress-nginx/images/controller-1-9/werf.inc.yaml
Disable log messages like:
```log
W0828 11:09:05.372106       7 controller.go:1116] Error obtaining Endpoints for Service "d8-monitoring/grafana": no object matching key "d8-monitoring/grafana" in local store
W0828 11:09:05.372284       7 controller.go:1116] Error obtaining Endpoints for Service "d8-ingress-nginx/fakeservice": no object matching key "d8-ingress-nginx/fakeservice" in local store
```
How to verify:
```shell
kubectl -n d8-ingress-nginx logs controller-main-wvvh6 | grep "Error obtaining"
```
- These messages are of the Warning type, but they contain the word "Error", which many users perceive as an error that needs to be fixed.
- These messages are generated very frequently and clutter the log with unnecessary information.
```changes
type: fix
summary: …
```
=> [ingress-nginx] Disable some log messages

ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/patches/004-fix_providerid_and_exclude_loopback_in_node_IP_selection.patch, ee/modules/030-cloud-provider-huaweicloud/images/cloud-controller-manager/patches/README.md
Fix providerID format and exclude 127.0.0.0/8 in node IP selection
Currently, only `127.0.0.1` is excluded from IP selection and host IP lookup fails if its `/etc/hosts` contains `127.0.1.1` entry
```changes
type: fix
summary: fix providerID format and exclude 127.0.0.0/8 in node IP selection
```
=> [cloud-provider-huaweicloud] Fix providerID format and exclude 127.0.0.0/8 in node IP selection

modules/110-istio/templates/operator/deployment.yaml, modules/110-istio/templates/operator/podmonitor.yaml
Added https 8443 metrics port to podmonitor deployment and istio operator 1.25 and newer deployment.
Certificate issue still persists, hence `insecureSkipVerify: true` https://github.com/deckhouse/deckhouse/issues/1487
We were getting `TargetDown` alert on Istio operator 1.25. It's happened because the port has changed.
Metrics about Istio Operator 1.25 will be collected correctly and the `TargetDown` error will disappear.
```changes
section: istio
type: fix
summary: Fixed metrics port for operator 1.25 and newer
```
=> [istio] Fixed metrics port for operator 1.25>=

.werf/defines/base.tmpl
Restore `diff` and `ps` binaries to the deckhouse
These binaries are used by deckhouse.
```changes
type: fix
summary: Restore binaries.
```
=> Restore diff and ps to the deckhouse-controller

testing/cloud_layouts/script-commander.sh
Fix commander e2e test script.
```changes
section: ci
type: fix
summary: Fix commander e2e test script.
```
=> [ci] Fix e2e test script

docs/site/_includes/getting_started/global/buttons.html
* Fixed the link to the step back in the second step of the DVP
* The back button on the first step of DVP has been removed
```changes
section: docs
type: fix
summary: Fixed back button on the second step of DVP GS.
```
=> [docs][getting-started] Fix back button on the second step of DVP GS

modules/040-node-manager/images/capi-controller-manager/werf.inc.yaml, modules/040-node-manager/images/caps-controller-manager/src/cmd/main.go, modules/040-node-manager/templates/capi-controller-manager/deployment.yaml, modules/040-node-manager/templates/caps-controller-manager/deployment.yaml
Upgrade patch version of CAPI manager due to logic fixes and fix cve's.
Increase leader elect leases timeout in CAPI manager.
Add leader elect leases timeout in CAPS manager.
We have some incorrect logical solution when caps crashes due bootstrap node.
We will fix it in 1.73 version.
Probably from version 1.71 (where we upgrade etcd to 3.6) etcd increase restart timeout and we have multiple restarts of CAPI and CAPS controllers when renew lease due to bootstrap cluster and we do not continue of bootstrap static nodes.
As temporary solution we add lease duration timeouts to CAPS and set and increase lease duration for CAPI.
Probably from version 1.71 (where we upgrade etcd to 3.6) etcd increase restart timeout and we have multiple restarts of CAPI and CAPS controllers when renew lease due …
=> [node-manager] Upgrade CAPI manager. Increase and add leader elect timeouts

docs/site/.helm/templates/15-modules-watcher.yaml
This PR fixes alert `TargetSampleLimitExceeded` on registry-modules-watcher app.
```changes
section: docs
type: fix
summary: fix alert
```
=> [docs-watcher] fix TargetSampleLimitExceeded

modules/500-upmeter/hooks/smokemini/internal/snapshot/gen_parse.go, modules/500-upmeter/hooks/smokemini/internal/snapshot/parse.generated.go
An error occurred, which is why the deckhouse does not start
```
{"level":"info","logger":"addon-operator","msg":"ModuleHookRun task for 'main' group binding, trigger is Schedule","binding":"schedule","binding.name":"reschedule","event.id":"03c78233-554b-4e7f-84d5-20be886e6802","hook":"500-upmeter/hooks/smokemini/reschedule.go","hook.type":"module","module":"upmeter","queue":"/modules/upmeter/update_selector","task.flow":"start","task.id":"b682eff9-6e87-4ed1-8558-f42a050244f9","time":"2025-09-05T10:12:00Z"}
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2ce4b8c]
goroutine 6511 [running]:
github.com/deckhouse/deckhouse/modules/500-upmeter/hooks/smokemini/internal/scheduler.(*filterByMinSts).selectNodes( …
```
=> [deckhouse-controller] Fix null pointer error

docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA.liquid, docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA_RU.liquid
This PR adds a note about enabling Rosetta option on macOS 26 when installing DKP.
```changes
section: docs
type: chore
summary: Added a note about enabling Rosetta option on macOS 26 when installing DKP.
```
=> [docs] Add a note about enabling Rosetta on macOS 26 when installing DKP

candi/base_images.yml
Add base_images missing in 1.72.
```changes
section: ci
type: chore
summary: Add missing base_images.
```
=> [ci] Add missing base_images

modules/021-cni-cilium/templates/ngc-disruptive-update.yaml
- changed the startup order of NGC,
- added the maximum number of attempts to prevent an infinite loop,
- added a forced update of the `safe-agent-updater` pod on the nodes where the disruptive-update was starting.
- this NGC will wait indefinitely for the user to approve the update, blocking other "bashible" steps in the process.
- if a disruptive update was starting on a node where the `safe-agent-updater` pod was not already updated, the upgrade process would be stuck.
This fix will improve the stability and reliability of bashible steps.
```changes
type: fix
summary: Fixed the infinite loop in the "cilium migration" bashible step and improved synchronization between bashible and safe-agent-updater.
```
=> [cni-cilium] some fixes to the process of upgrading cilium to version 1.17

docs/site/backends/docs-builder/go.mod, docs/site/backends/docs-builder/go.sum
Update oauth package version to fix CVE [CVE-2025-22868 golang.org/x/oauth2 v0.26.0]
```changes
section: docs
type: chore
summary: bump oauth on docs-builder
```
=> [docs][registry-modules-watcher] Update Oauth package

modules/500-upmeter/hooks/remove_old_sts.go
Fixed filter func, which return several types (string and custom struct).
Error occurred:
```
panic: reflect.Set: value of type string is not assignable to type hooks.StatefulSetStorage
goroutine 5754 [running]:
reflect.Value.assignTo({0x3375340?, 0x4512860?, 0xc000382240?}, {0x3d4a7c8, 0xb}, 0x3a55320, 0x0)
/usr/local/go/src/reflect/value.go:3072 +0x28b
reflect.Value.Set({0x3a55320?, 0xc004acfea0?, 0x8080808080808057?}, {0x3375340?, 0x4512860?, 0x6994280?})
/usr/local/go/src/reflect/value.go:2057 +0xe6
github.com/flant/addon-operator/pkg/module_manager/go_hook.(*Wrapped).UnmarshalTo(0x160?, {0x3269f40?, 0xc004acfea0?})
/go/pkg/mod/github.com/flant/addon-operator@v1.11.4/pkg/module_manager/go_hook/filter_result.go:41 +0x405
github.com/deckhouse/deckhouse/modules/500-upmeter/hooks.removeSts …
```
=> [deckhouse-controller] Fix panic on snapshotIter

deckhouse-controller/pkg/helpers/change_registry/change_registry.go, deckhouse-controller/pkg/helpers/register.go, docs/documentation/pages/DECKHOUSE-FAQ.md, docs/documentation/pages/DECKHOUSE-FAQ_RU.md
When using the registry change functionality, errors sometimes occur due to incorrect schema input. Bringing the schema to lowercase will solve this problem.
We also made changes to the documentation and flag description by enclosing the protocol enums in quotation marks.
For correct use of schema values in the registry address
```changes
type: chore
summary: check lowercased scheme in ChangeRegistry function
```
=> [deckhouse-controller] check lowercased scheme in ChangeRegistry function

modules/002-deckhouse/hooks/check_deckhouse_edition.go
Fix alert `DeckhouseEditionNotFound` for edition, that not included in editions list.
```changes
type: fix
summary: fix editions list in check deckhouse edition hook
```
=> [deckhouse] Fix edition list in hook check_deckhouse_edition.go

modules/030-cloud-provider-dvp/images/capdvp-controller-manager/src/go.mod, modules/030-cloud-provider-dvp/images/capdvp-controller-manager/src/go.sum, modules/030-cloud-provider-dvp/images/cloud-controller-manager/src/go.mod, modules/030-cloud-provider-dvp/images/cloud-controller-manager/src/go.sum, modules/030-cloud-provider-dvp/images/cloud-data-discoverer/src/go.mod, modules/030-cloud-provider-dvp/images/cloud-data-discoverer/src/go.sum, modules/030-cloud-provider-dvp/images/dvp-common/go.mod, modules/030-cloud-provider-dvp/images/dvp-common/go.sum, modules/030-cloud-provider-dvp/images/dvp-csi-driver/src/go.mod, modules/030-cloud-provider-dvp/images/dvp-csi-driver/src/go.sum
Bump golang.org/x/oauth2 module version to fix CVE-2025-22868
Fix CVE-2025-22868
```changes
section: cloud-provider-dvp
type: fix
summary: fix CVE-2025-22868
```
=> [cloud-provider-dvp] fix CVE-2025-22868

ee/be/modules/140-user-authz/images/webhook/werf.inc.yaml, ee/modules/500-operator-trivy/images/node-collector/werf.inc.yaml, ee/modules/500-operator-trivy/images/operator/werf.inc.yaml, ee/modules/500-operator-trivy/images/report-updater/werf.inc.yaml, ee/modules/500-operator-trivy/images/trivy/werf.inc.yaml, modules/015-admission-policy-engine/images/gatekeeper/werf.inc.yaml, modules/300-prometheus/images/prometheus/werf.inc.yaml, modules/462-loki/images/loki/werf.inc.yaml
add new modules for svace analyze
- `userAuthz/webhook`
- `operatorTrivy/node-collector`
- `operatorTrivy/operator`
- `operatorTrivy/report-updater`
- `operatorTrivy/trivy`
- `prometheus/prometheus`
- `admissionPolicyEngine/gatekeeper`
- `loki`
```changes
section: ci
type: chore
summary: add new modules to svace analyze
```
=> [chore] add to svace analyze new modules

modules/500-dashboard/enabled
Return add check for user-authn in enabled script
Add commentaries
If user-authn is enabled
```
kind: Module
metadata:
name: dashboard
status:
conditions:
- lastProbeTime: "2025-09-10T09:26:13Z"
lastTransitionTime: "2025-09-10T09:26:13Z"
status: "True"
type: EnabledByModuleManager
- lastProbeTime: "2025-09-10T09:26:13Z"
lastTransitionTime: "2025-09-10T09:21:41Z"
message: reconciling
reason: Reconciling
status: "False"
type: IsReady
```
If user-authn is disabled
```
kind: Module
metadata:
name: dashboard
status:
conditions:
- lastProbeTime: "2025-09-10T09:24:29Z"
lastTransitionTime: "2025-09-10T09:24:29Z"
message: 'turned off by enabled script: required values settings.auth.externalAuthentication.authSignInURL
and settings …
```
=> [dashboard] add check for user-authn in enabled script

docs/site/backends/docs-builder-template/layouts/single.html
Fix alert level from warning to info for modules with General Availability status.
```changes
section: docs
type: chore
summary: Fix alert level from warning to info for modules with General Availability status.
```
=> [docs] Fix alert level for modules with General Availability status

ee/se-plus/modules/021-cni-cilium/hooks/ee/egressgateway_stale_node_label_cleaner_test.go, ee/se-plus/modules/021-cni-cilium/hooks/ee/egressgateways_discovery.go, ee/se-plus/modules/021-cni-cilium/hooks/ee/egressgateways_discovery_test.go, modules/021-cni-cilium/images/bin-cilium/patches/013-ignore-egress-gateway-inactual-warning.patch, modules/021-cni-cilium/images/bin-cilium/patches/README.md
Fixed egress gateway reselection for case node hard reset.
In the event of a hard reboot of a node in the cluster, a new egress gateway is not elected by cilium agents on other nodes. To fix this issue, we need to manually remove the labels from the ciliumnodes CR too in the hook.
1. Deploy debug app.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: debug-pod-right
namespace: right
labels:
app: debug-pod
spec:
replicas: 1
selector:
matchLabels:
app: debug-pod
template:
metadata:
labels:
app: debug-pod
spec:
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: node-role.kubernetes.io/master
operator: Exists
- matchExpressions:
- key: node-role.kubernetes.io/control-plane
operator: Exists
tolerations:
- key: …
```
=> [cni-cilium]  fixed egress gateway reselection for case node hard reset

modules/000-common/images/coredns/mount-points.yaml, modules/000-common/images/coredns/werf.inc.yaml, modules/042-kube-dns/images/sts-pods-hosts-appender-webhook/src/main.go, modules/042-kube-dns/templates/sts-pods-hosts-appender-webhook/deployment.yaml
All containers of the kube-dns module have the readOnlyRootFilesystem setting set to true.
We need it to meet security concerns and overall hardening of the DKP platform.
```changes
type: chore
summary: The readOnlyRootFilesystem security option is set to true for all containers.
impact: The kube-dns webhook pod will be restarted.
```
=> [kube-dns] enable readOnlyRootFilesystem

docs/documentation/_plugins/render-jsonschema.rb, docs/site/_plugins/render-jsonschema.rb
Delete quotation for default values in OpenAPI schemas.
Before:
After:
```changes
section: docs
type: chore
summary: Deleted quotation for default values in OpenAPI schemas.
```
=> [docs] Delete quotation for default values in OpenAPI schemas

modules/402-ingress-nginx/images/controller-1-10/patches/010-nginx-build.patch, modules/402-ingress-nginx/images/controller-1-10/werf.inc.yaml, modules/402-ingress-nginx/images/controller-1-9/patches/ingress-nginx/011-nginx-build.patch, modules/402-ingress-nginx/images/controller-1-9/werf.inc.yaml, modules/402-ingress-nginx/template_tests/controller_test.go, modules/402-ingress-nginx/template_tests/testdata/golden/host-port-with-pp/controller/controller.yaml, modules/402-ingress-nginx/template_tests/testdata/golden/host-with-failover/controller/controller.yaml, modules/402-ingress-nginx/template_tests/testdata/golden/lb-with-hide-headers-and-envoy-header-added-and-with-istio/controller/controller.yaml, modules/402-ingress-nginx/template_tests/testdata/golden/lb-with-hide-headers-and-envoy-header-added/controller/controller.yaml, modules/402-ingress-nginx/template_tests/testdata/golden/lb-with-hide-headers-and-with-istio/controller/controller.yaml, modules/402-ingress-nginx/template_tests/testdata/golden/lb-with-hide-headers/controller/controller.yaml, modules/402-ingress-nginx/template_tests/testdata/golden/lb-with-istio/controller/controller.yaml, modules/402-ingress-nginx/template_tests/testdata/golden/lb-with-pp/controller/controller.yaml, modules/402-ingress-nginx/template_tests/testdata/golden/lb-with-terminating/controller/controller.yaml, modules/402-ingress-nginx/template_tests/testdata/golden/lb-without-hpa/controller/controller.yaml, modules/402-ingress-nginx/template_tests/testdata/golden/lb/controller/controller.yaml
Fixed patches customizing the script build.sh to build nginx images for the ingress controller.
The build is broken due to incomplete modification of the nginx image build script.
The problem is caused by [PR](https://github.com/deckhouse/deckhouse/pull/14245).
```changes
section:  ingress-nginx
type: fix
summary: Fixed nginx image build for ingress controller and template tests.
```
=> [ingress-controller] Fixing the build and template tests of ingress controllers versions 1.10 and 1.9.

docs/documentation/_data/deckhouse-alerts.yml, modules/402-ingress-nginx/hooks/set_annotation_validation_suspended.go, modules/402-ingress-nginx/hooks/set_annotation_validation_suspended_test.go, modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
This patch updates the `set_annotation_validation_suspended.go hook`. Previously, the hook only set the `ingress_nginx_validation_suspended` metric but did not remove it when it was no longer needed. This change adds logic to remove the `ingress_nginx_validation_suspended` metric if there are no `ingressNginxControllers` resources in the cluster with the annotation `network.deckhouse.io/ingress-nginx-validation-suspended`.
Without this fix, the `ingress_nginx_validation_suspended` metric can remain set even when all controllers have removed the suspension annotation. This leads to inaccurate monitoring data and potential confusion in alerts or dashboards that rely on this metric.
Without this fix, the `NginxIngressValidationIsDisabled` alert remains active at all times, regardless of …
=> fix: Fixed set_annotation_validation_suspended.go hook

modules/002-deckhouse/openapi/config-values.yaml, modules/002-deckhouse/openapi/doc-ru-config-values.yaml
Remove editions enum from config-values.
We should not validate the revision via openapi spec.
- This is necessary so that we can create a new revision at any time and place it even in old releases.
- We will validate it later via the license token, the available editions will be indicated there and we will compare them.
Add incorrect license edition "DD" to deckhouse ModuleConfig
Main branch:
```bash
>> k edit mc deckhouse
spec.settings are not valid (version 1):  1 error occurred: * deckhouse.license.edition should be one of [CE BE EE SE SE-plus]
```
This PR:
```bash
>> k edit mc deckhouse
moduleconfig.deckhouse.io/deckhouse edited
```
```changes
type: feature
summary: Remove editions enum from config-values
```
=> [deckhouse] Remove editions enum from config-values

deckhouse-controller/pkg/controller/module-controllers/release/controller_test.go, go_lib/dependency/dependency.go
Fix race condition in concurrent tests with fakeCloak testing
```changes
type: fix
summary: fix concurrent tests with fake cloak
```
=> [deckhouse-controller] fix: race condition in concurrent tests with fakeCloak

dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
Change warning message about necessity of additional actions after master node bootstrap
```changes
section: dhctl
type: chore
summary: Change warning message about necessity of additional actions after master node bootstrap
```
=> [dhctl] Update cluster-bootstrapper.go message

dhctl/pkg/operations/commander/attach/attacher.go, dhctl/pkg/server/rpc/dhctl/commander_attach.go, dhctl/pkg/server/rpc/dhctl/commander_detach.go
Fixed the behaviour of the attach operation when there are no keys in SSHConfig, only a password
Fixed logging in the gRPC server for the attach and detach operations.
This fix is critical for Commander users who rely on password-based authentication. Without it, they cannot attach their clusters.
```changes
section: dhctl
type: fix
summary: Fixed the behaviour of the attach operation when there are no keys in SSHConfig, only a password
```
=> [dhctl] fix(dhctl-for-commander): make ssh keys optional in attach operation

docs/documentation/_data/deckhouse-alerts.yml, docs/site/_includes/getting_started/openstack_vk/partials/config.ru.yml.standard.other.inc, docs/site/_includes/getting_started/openstack_vk/partials/config.yml.standard.other.inc, modules/021-cni-cilium/hooks/check_cni_configuration.go, modules/021-cni-cilium/hooks/check_cni_configuration_test.go, modules/021-cni-cilium/hooks/set_cilium_mode.go, modules/021-cni-cilium/hooks/set_cilium_mode_test.go, modules/035-cni-flannel/hooks/check_cni_configuration.go, modules/035-cni-flannel/hooks/check_cni_configuration_test.go, modules/035-cni-flannel/hooks/set_pod_network_mode.go, modules/035-cni-flannel/hooks/set_pod_network_mode_test.go, modules/035-cni-simple-bridge/hooks/check_cni_configuration.go, modules/035-cni-simple-bridge/hooks/check_cni_configuration_test.go, modules/340-monitoring-deckhouse/monitoring/prometheus-rules/cni-checks.yaml
The following changes have been implemented:
- Cloud provider controllers will continue to generate the Secret d8-cni configuration. 
- However, its purpose has slightly changed. These are now the recommended CNI settings for this provider by default.
- Parameters described in the ModuleConfig CNI take priority over those specified in the Secret d8-cni-configuration. 
- Any parameter can now be redefined.
- A migration mechanism has been added to allow for a safe switch to the new logic.
There are two sources of parameters for configuring CNI in a cluster:
- the CNI ModuleConfig, which can be configured by the user,
- the d8-cni-configuration secret, which is created by a cloud provider controller.
The d8-cni-configuration secret always has priority over the ModuleConfig CNI parameters. …
=> [cni] Add new logic to merge the parameters from the moduleConfig CNI and d8-cni-configuration secret.

pkg/metrics-storage/metric_storage.go, pkg/metrics-storage/metric_storage_test.go
```changes
section: tools
type: fix
summary: metrics storage prefix is optional
```
=> [metrics-storage] Make prefix optional

dhctl/pkg/kubernetes/actions/resources/resouce_ready.go, dhctl/pkg/kubernetes/actions/resources/resources.go, dhctl/pkg/kubernetes/client/client.go
Refactor resources processing in dhctl: reduce APIResources/APIResourcesList api calls
By single resource creation, we calls APIResources/APIResourcesList up to 4 time for the same data.
```changes
section: dhctl
type: chore
summary: Refactoring of resources creation in dhctl.
```
=> [dhctl] Refactor resources: reduce APIResources calls

candi/control-plane-kubeadm/v1beta4/config.yaml.tpl
Fix arg `encryption-provider-config ` for kubeadm configuration.
Restore encryption-provider-config in kubeadm v1beta4.
Fix problem during the upgrade to 1.71.
```changes
section: candi
type: fix
summary: Fix arg `encryption-provider-config ` for kubeadm configuration.
```
=> [candi] fix secretEncryptionKey for kubeadm v1beta4

ee/modules/030-cloud-provider-huaweicloud/hooks/get_cni_secret.go, ee/modules/030-cloud-provider-huaweicloud/templates/cni.yaml
Add default CNI for huawei cloud provider
If no MC CNI specified run cni module by default
```changes
type: feature
summary: If no MC CNI specified run cni module by default
```
=> [cloud-provider-huaweicloud] Add default CNI for huawei cloud provider

modules/040-node-manager/images/machine-controller-manager/werf.inc.yaml
This PR changes machine drain logic and keeps it in LB before drain. 
See https://github.com/deckhouse/deckhouse/issues/13594
https://github.com/deckhouse/mcm/pull/20
```changes
type: fix
summary: don't remove machine from LB before drain
```
=> [cloud-provider-yandex] don't remove machine from LB before drain

.dmtlint.yaml, tools/dmt-lint.sh
- Feature flags as warn rules and a new configuration architecture have been added to DMT - now you can control the severity level of both entire linters and individual rules at the global level.
- A documentation linter has been added: it checks for the presence of `README.md`, bilingualism (English/Russian), and the absence of Cyrillic characters in English `.md` files.
- Includes a new documentation linter and immediately sets its severity level to *warn* via `.dmtlint.yaml` 
- We can change impact of linter.
- This improves the basic hygiene of Deckhouse modules. 
```changes
section: tools
type: feature
summary: update dmt version to 0.1.37
```
=> [dmt] update dmt version to 0.1.37

docs/documentation/_data/sidebars/main.yml, modules/462-loki/module.yaml
Change stage to Preview
When rolling out a new version, users encounter that the Loki module is in the experimental stage
```changes
section: loki
type: fix
summary: Change stage to Preview
```
=> [loki] Change stage to Preview

modules/150-user-authn/templates/dex/ingress.yaml, modules/150-user-authn/templates/dex/resource-quota.yaml
Increase flexibility of Dex authentication requests for clients behind a single IP by adjusting Ingress rate limits and adding a global AuthRequest quota.
This prevents user requests from being blocked unnecessarily while still protecting the cluster from excessive AuthRequest objects.
- Raised per-IP request limits using a token-bucket approach in the Dex Ingress.
- Added a ResourceQuota for the total number of AuthRequest objects to protect the database.
Current limit of 20 AuthRequest/min per IP is insufficient for clients where many users share a single IP (e.g., corporate NAT).
Increasing the burst in rate-limiting allows multiple concurrent users without triggering 429 errors.
The ResourceQuota ensures that the total number of AuthRequest objects stays within safe limits, preventing …
=> [user-authn] Refactor DEX rate limit setup

modules/150-user-authn/docs/FAQ.md, modules/150-user-authn/docs/FAQ_RU.md, modules/150-user-authn/hooks/get_dex_authenticator_crds.go, modules/150-user-authn/hooks/get_dex_authenticator_crds_test.go, modules/150-user-authn/openapi/values.yaml, modules/150-user-authn/template_tests/authenticator_test.go, modules/150-user-authn/template_tests/authenticator_truncation_test.go, modules/150-user-authn/template_tests/kubernetes_oauth2client_test.go, modules/150-user-authn/templates/dex-authenticator/deployment.yaml, modules/150-user-authn/templates/dex-authenticator/ingress.yaml, modules/150-user-authn/templates/dex-authenticator/secret.yaml, modules/150-user-authn/templates/dex-authenticator/service.yaml
Ensure validity of resource names for DexAuthenticator by centralizing and lazily truncating long names.
- Introduce `SafeDNS1123Name` and move name generation logic from Helm templates into the Go hook `get_dex_authenticator_crds.go`.
- If a computed resource name exceeds 63 characters, normalize and truncate it to 57 characters and append `-<hash5>`, where `<hash5>` is the first 5 hex characters of the SHA256 of the original full name.
- Precompute safe names and expose them via `.Values.userAuthn.internal.dexAuthenticatorNames` for templates to consume (Service, Deployment, Secret, Ingress, etc.).
- Add diagnostic labels to resources whose names were truncated to simplify identification and debugging:
- `deckhouse.io/name-truncated: "true"`
- `deckhouse.io/name-hash: "<hash5>"`
- …
=> [user-authn] Truncate long DexAuthenticator resource names

modules/035-cni-flannel/images/flanneld/mount-points.yaml, modules/035-cni-flannel/images/flanneld/werf.inc.yaml, modules/035-cni-flannel/images/iptables-wrapper-init/mount-points.yaml, modules/035-cni-flannel/images/iptables-wrapper-init/werf.inc.yaml, modules/035-cni-flannel/templates/daemonset.yaml, testing/library/images_tags_generated.go
All containers of the cni-flannel module have the readOnlyRootFilesystem setting set to true.
We need it to meet security concerns and for overall hardening of the DKP platform.
```changes
type: chore
summary: The readOnlyRootFilesystem security option is set to true for all containers.
impact: Pods of the cni-flannel module will be restarted.
```
=> [cni-flannel] enable readOnlyRootFilesystem

ee/modules/450-network-gateway/images/dnsmasq/mount-points.yaml, ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml, ee/modules/450-network-gateway/images/iptables-wrapper-init/mount-points.yaml, ee/modules/450-network-gateway/images/iptables-wrapper-init/werf.inc.yaml, ee/modules/450-network-gateway/images/snat/mount-points.yaml, ee/modules/450-network-gateway/images/snat/werf.inc.yaml, ee/modules/450-network-gateway/templates/snat-daemonset.yaml, testing/library/images_tags_generated.go
All containers of the network-gateway module have the readOnlyRootFilesystem setting set to true.
We need it to meet security concerns and for overall hardening of the DKP platform.
```changes
section: network-gateway
type: chore
summary: The readOnlyRootFilesystem security option is set to true for all containers.
impact: Pods of the network-gateway module will be restarted.
```
=> [network-gateway] enable readOnlyRootFilesystem

docs/documentation/_data/deckhouse-alerts.yml, modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
This PR lowers the severity level of the IngressNginxController alert from 3 to 4 to better reflect its actual impact on cluster operations
The current severity level of 3 is too high for this alert. Reducing it to level 4 will ensure proper prioritization of responses and reduce noise in engineer notifications, without diminishing awareness of potential issues
This change affects an existing alert and influences its handling priority. Including it in the patch release allows us to quickly align the alert’s behavior with current requirements and prevent false alarms in the production cluster
```changes
type: fix
summary: lowers the severity level of the IngressNginxController alert from 3 to 4
```
=> [ingress-nginx] Fix severity for NginxIngressValidationIsDisabled alert

tools/dmt-lint.sh
- Check deckhouse version for optional modules.
- Skip test deckhouse repos in registry.
- Fix documentation linter.
Added a new validation rule to DMT that checks if optional modules are used with a compatible Deckhouse version:
Automatically detects the !optional flag in module requirements
Ensures Deckhouse version is >= 1.73.0 when optional modules are used
Uses the existing RequirementsRegistry architecture for consistency
Also done some fixes
```changes
section: tools
type: feature
summary: update dmt version to 0.1.38
```
=> [dmt] Update dmt version to 0.1.38

modules/021-cni-cilium/images/safe-agent-updater/src/main.go
Fixed 1.14 -> 1.17 migration mechanism (bugs in pr https://github.com/deckhouse/deckhouse/pull/15602).
In some cases, the main upgrading logic doesn't work, so agent DaemonSets aren't upgrading.
It is the fix for patch, that is in patch release.
```changes
type: fix
summary: Fixed 1.14 -> 1.17 migration mechanism
```
=> [cni-cilium] Fixed 1.14 -> 1.17 migration mechanism

modules/040-control-plane-manager/hooks/audit_policy.go, modules/040-control-plane-manager/hooks/audit_policy_test.go
Change order of applying virtualization policies and custom policies to prevent breaking virtualization audit configuration.
**Before:**
AuditPolicy manifest is a sum of policies:
```
Basic policies
+
Custom policies from Secret/audit-policy
+
Policies for virtualization module
```
It is a good practice to add audit for all resources with level "Metadata" in some closed environments. For example with this "catch all" additional Policy:
```
apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
omitStages:
- "RequestReceived"
rules:
- level: Metadata
omitStages:
- "RequestReceived"
```
The order of applying policies in audit-policy hooks makes this rule appear before virtualization rules and all events about VirtualMachineOperations recorded with Metadata level. This breaks VMOP …
=> [control-plane-manager] apply custom audit policies after embedded policies

modules/150-user-authn/images/dex/patches/006-fix-render-error.patch, modules/150-user-authn/images/dex/patches/README.md
This patch improves the login error message for local users. Instead of showing a generic `Internal Error` when access is restricted by allowed group or email, users now see a clear 'Access Denied' message.
Previously, when a local user tried to log in but was restricted due to group/email rules, the system displayed an `Internal Error`, which was confusing. This fix provides a user-friendly message, improving UX and reducing support requests.
```changes
type: fix
summary: Show 'Access Denied' instead of 'Internal Error' for restricted local users
impact: Users will see a clear error message when their login is restricted by allowed group or email, instead of a confusing internal error.
```
=> [user-authn] Fix DEX login denied render

docs/site/.helm/templates/20-ingress.yaml, docs/site/.werf/nginx-dev.conf, docs/site/.werf/nginx.conf, docs/site/_includes/getting_started/global/partials/installer/installer_block_ru.html
Fixed URL for downloading installer.
```changes
section: docs
type: chore
summary: Fixed URL for downloading installer.
```
=> [site] Fix URL for downloading installer

dhctl/pkg/config/registry.go, dhctl/pkg/log/log_sanitizer.go, dhctl/pkg/log/logger.go
Sanitize sensitive data in debug log(klog).
Hide sensitive data in debug log.
behaviour:
- <details>
<summary>Before</summary>
```
2025-09-26 14:48:57 - klog: I0926 14:48:57.477831      21 round_trippers.go:553] GET http://localhost:22322/api/v1/namespaces/kube-system/secrets/d8-provider-cluster-configuration 200 OK in 46 milliseconds
2025-09-26 14:48:57 - klog: I0926 14:48:57.477944      21 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 46 ms Duration 46 ms
2025-09-26 14:48:57 - klog: I0926 14:48:57.477959      21 round_trippers.go:577] Response Headers:
2025-09-26 14:48:57 - klog: I0926 14:48:57.477976      21 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 2dd73ca9-53a2-4a4b-ad6b-cf0fdeba5d51
2025-09-26 14:48:57 - klog: I0926 14:48:57.477987 …
```
=> [dhctl] sanitize klog

dhctl/pkg/app/ssh.go, dhctl/pkg/operations/destroy/destroy.go, dhctl/pkg/system/node/gossh/client.go, dhctl/pkg/system/node/gossh/kube-proxy.go
Fixes to a gossh-related dhctl behavior:
- Fix start and keep-alive behavior, do not change host if any kube-proxies has been started
- Restart kubeProxy fully after 3 retries to restart tunnel
- Exit with error, if there is no SSH key on file system, put with `--ssh-agent-private-keys` flag
- Add ssh client stop to cloud destroy before infra destroy step, to avoid keep-alive related problems
- Adjust ssh client connection timeouts
Sometimes kube-proxy through bastion cannot be restarted or cannot restart tunnel.
Affected since v1.72
```changes
section: dhctl
type: fix
summary: Fix start and keep-alive behavior, do not change host if any kube-proxies has been started.
```
=> [dhctl] gossh client and kubeproxy fixes

modules/040-node-manager/hooks/get_crds.go, modules/040-node-manager/hooks/get_crds_test.go
Group get_crd errors and make them more readable
Group get_crd errors and make them more readable
```changes
type: chore
summary: Group get_crd errors and make them more readable
```
=> [node-manager] group get_crd errors and make them more readable

ee/modules/500-operator-trivy/images/node-collector/patches/002-go-mod.patch
Bumped golang.org/x/oauth2 to v0.31.0 to fix CVE-2025-22868
```changes
type: chore
summary: Fixed CVE-2025-22868 in trivy node-collector image
```
=> [operator-trivy] bump golang.org/x/oauth2 to v0.31.0

ee/modules/650-runtime-audit-engine/template_tests/module_test.go, ee/modules/650-runtime-audit-engine/templates/daemonset.yaml, ee/modules/650-runtime-audit-engine/templates/falco-leak-limit-range.yaml, ee/modules/650-runtime-audit-engine/templates/k8s-metacollector/deployment.yaml
Following  #14984, VPA has been disabled for the k8s-metacollector module.
Fixes issues related to VPA and limitrange conflicts
Problem actual on releases `1.70`, `1.71`, `1.72`
```changes
section:  runtime-audit-engine
type: fix
summary: Disable vpa for k8s-metacollector
```
=> Backport: [runtime-audit-engine] Disable vpa for k8s-metacollector

docs/site/.helm/templates/10-cm-frontend.yaml
Fix lost redirect configuration for installer downloads.
Ref: #15662, #15661, #15660, #12192
```changes
section: docs
type: chore
summary: Fix lost redirect configuration for installer downloads.
```
=> [docs][gs] Add redirect configuration for installer downloads

dhctl/pkg/operations/bootstrap/steps.go, dhctl/pkg/system/node/gossh/upload-script.go
Fixed https://github.com/deckhouse/deckhouse/issues/15623
The execution of bashible steps goes on endlessly
```changes
section: dhctl
type: fix
summary: Fixing bashible steps when it does not respond to the limit on the number of attempts
```
=> [dhctl] Fix exit on retry limit for bashible run from dhctl backport to 1.72

go.mod, go.sum
Move disabling of module hook monitors to after `afterDeleteHelm` execution. This preserves Kubernetes snapshots for module hooks bound to `afterDeleteHelm`, aligning runtime behavior with the documentation. Previously, monitors were stopped before running `afterDeleteHelm`, resulting in empty snapshots.
- Stop calling `DisableModuleHooks` before deletion.
- Run Helm delete.
- Run module hooks with `afterDeleteHelm`.
- Then call `DisableModuleHooks` to stop monitors and schedules.
No changes to the behavior of `beforeHelm`/`afterHelm`.
Hooks with `afterDeleteHelm` are expected to receive snapshots of their Kubernetes bindings. In practice they were empty because monitors were stopped right before executing the binding. This fix ensures `afterDeleteHelm` receives the last known snapshots …
=> fix: remove monitors after afterDelete hook run

docs/site/backends/docs-builder-template/layouts/_partials/module-resources.html, docs/site/backends/docs-builder-template/layouts/_partials/openapi/format-configuration.html
Fix show conversion for modules configuration schema.
Fix: https://github.com/deckhouse/deckhouse/pull/15733
```changes
section: docs
type: chore
summary: Fix show conversion for modules configuration schema
```
=> [docs] Fix show conversion for modules configuration schema

docs/site/_includes/getting_started/global/partials/installer/installer_block_ru.html, docs/site/pages/getting_started/getting_started_ru.html
This pull request adds logic to the Russian "Getting Started" documentation page to automatically switch to the GUI installation tab when the URL hash is set to `#gui-install`. This improves the user experience by allowing direct linking to the GUI installation instructions.
Enhancements to tab navigation:
* Added a script that checks the URL hash on page load and, if it matches `gui-install`, switches the active tab and button to display the GUI installation instructions.
Other changes:
* Minor formatting adjustment in the installer block partial for Russian documentation.
```changes
section: docs
type: feature
summary: Added an anchor to the GUI installer.
```
=> [docs][getting-started] Add link for GUI installer in GS

docs/site/pages/virtualization-platform/documentation/user/resource-managment/IMAGES.md, docs/site/pages/virtualization-platform/documentation/user/resource-managment/IMAGES_RU.md
Fixed an invalid link on the Images page of the virtualization docs.
The link to the VirtualImage CR reference was leading to a 404 page. Updated it to the correct reference location.
```changes
section: docs
type: fix
summary: Fixed an invalid link on the Images page of the virtualization docs.
```
=> [docs] Fix broken VirtualImage link

modules/040-node-manager/images/caps-controller-manager/src/internal/client/bootstrap.go, modules/040-node-manager/images/caps-controller-manager/src/internal/scope/instance_scope.go
Enable SSHLegacyMode if SSHPrivateKey is not empty and fix gossh panic
gossh implementation can be unstable and have connection issues. To avoid it we will use clissh implementation if we don't need password auth. Additionally, if credential was wrong, gossh causes panic, so we should fix it.
```changes
type: fix
summary: Enable SSHLegacyMode if SSHPrivateKey is not empty and fix gossh panic.
```
=> [node-manager] CAPS: add condition to enable SSHLegacyMode

candi/bashible/common-steps/all/000_check_containerd_v2_support.sh.tpl
Add exit 1 for check_containerd_v2_support step if set_labels() func failure
The step might not stop after 10 unsuccessful attempts and output a large number of logs with errors.
```changes
section: candi
type: fix
summary: Add exit 1 for check_containerd_v2_support step if set_labels() func failure
```
=> [candi] Add exit 1 for check_containerd_v2_support step

tools/dmt-lint.sh
Fix bug (skip empty license files)
We should not check license files if they are empty.
```changes
section: tools
type: fix
summary: update dmt version to 0.1.44
```
=> [dmt] Change version to 0.1.44

candi/openapi/dhctl/doc-ru-ssh_configuration.yaml, candi/openapi/dhctl/ssh_configuration.yaml, dhctl/cmd/dhctl/commands/bootstrap/phase.go, dhctl/cmd/dhctl/commands/control-plane.go, dhctl/cmd/dhctl/commands/converge.go, dhctl/cmd/dhctl/commands/deckhouse.go, dhctl/cmd/dhctl/commands/destroy.go, dhctl/cmd/dhctl/commands/edit.go, dhctl/cmd/dhctl/commands/kube.go, dhctl/cmd/dhctl/commands/lock.go, dhctl/cmd/dhctl/commands/session.go, dhctl/cmd/dhctl/commands/ssh.go, dhctl/cmd/dhctl/commands/terraform.go, dhctl/pkg/app/ssh.go, dhctl/pkg/config/connection.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go, dhctl/pkg/operations/converge/context/client_switcher.go, dhctl/pkg/operations/converge/converger.go, dhctl/pkg/operations/converge/infrastructure/hook/controlplane/kube-proxy.go, dhctl/pkg/operations/destroy/destroy.go, dhctl/pkg/operations/exporter.go, dhctl/pkg/preflight/common.go, dhctl/pkg/preflight/registry_test.go, dhctl/pkg/server/pkg/helper/ssh_client.go, dhctl/pkg/system/node/clissh/frontend/reverse-tunnel.go, dhctl/pkg/system/sshclient/init.go, dhctl/pkg/terminal/ask-password.go
Manual backport https://github.com/deckhouse/deckhouse/pull/15773 to release-1.72 .
```changes
section: dhctl
type: fix
summary: Change default ssh mode.
```
=> [dhctl][backport] manual backport - change default ssh mode (#15773)

Makefile, docs/documentation/_data/modules/modules-addition.json, docs/site/.helm/templates/20-ingress.yaml, docs/site/.helm/values.yaml, docs/site/.werf/nginx-local.conf, docs/site/Makefile, docs/site/backends/docs-builder-template/data/modules_all.json
- Removed the `managed-memcached` and `managed-postgres` modules from the comparison table.
- Use EE modules registry for the prod and test envs
- Use FE modules registry for stage and test2 envs
- Fixed local run of the documentation site (Makefiles and Nginx config)
```changes
section: docs
type: chore
summary: Updated the comparison table and modules set on the site. Fixed local run of the documentation site.
```
=> [docs] Update the comparison table and modules set on the site

docs/site/backends/docs-builder-template/config/_default/hugo.yaml, docs/site/backends/docs-builder-template/data/dkp/embedded_modules.json, docs/site/backends/docs-builder-template/i18n/en.yaml, docs/site/backends/docs-builder-template/i18n/ru.yaml, docs/site/backends/docs-builder-template/layouts/modules/modules-list.html
* Updated logic in modules list to ensure embedded modules are skipped if an external module with the same name exists, preventing duplication and improving warning messages.
* Added new translation keys for "Advanced usage"
* Enabled Hugo's `printI18nWarnings` option to help catch missing or incorrect translations.
* Update embedded modules list
```changes
section: docs
type: chore
summary: Update modules list generation logic.
```
=> [docs] Update modules list generation logic

ee/modules/015-admission-policy-engine/images/trivy-provider/mount-points.yaml, ee/modules/015-admission-policy-engine/images/trivy-provider/werf.inc.yaml, ee/modules/015-admission-policy-engine/templates/trivy-provider/statefulset.yaml
```changes
type: chore
summary: trivy-provider set readOnlyRootFilesystem
impact: 
```
=> [admission-policy-engine] trivy-provider set readOnlyRootFilesystem

modules/030-cloud-provider-dvp/templates/registration.yaml, modules/040-node-manager/templates/node-group/_cloud_init_cloud_config.tpl
Add forget sshPublicKey field for cloud-provider-dvp registration secret. Without it we cannot login via ssh on nodes were creating with CAPI dvp infrastructure provider.
Also disable running `apt/yum/dns update` during first boot via cloud-init of cloud-ephemeral nodes.
We can do it with next reasons:
- if we install package with bb-*-install functions, before install we run `apt/yum/dnf update`
- we do not install packages during bashible bootstrap. If we forget about some packages, see first reason.
- user (or module developer) should use our bb-*-install functions in NGC. otherwise it's your own fault. 
We cannot login via ssh on nodes were creating with CAPI dvp infrastructure provider.
Increase bootstrap cloud-ephemeral nodes. `apt/yum/dnf update` can took long time for downloading …
=> [cloud-provider-dvp][node-manager] Add sshPublicKey to registration secret and disable update system packages index during boot cloud ephemeral nodes

modules/101-cert-manager/templates/webhook/mutatingwebhookconfiguration.yaml, modules/101-cert-manager/templates/webhook/validatingwebhookconfiguration.yaml
Increased cert-manager's time budget for receiving certificates from ACME, as default of 10 seconds per webhook is not always enough.
User request, fixes flaky certificate issue.
```changes
type: chore
summary: Increase timeout for admission webhooks to 30 seconds
```
=> [cert-manager] Increase timeout for admission webhooks to 30 seconds
