- modules/402-ingress-nginx/monitoring/grafana-dashboards/kubernetes-cluster/controller-detail.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/kubernetes-cluster/controllers.json
- modules/402-ingress-nginx/templates/failover/podmonitor.yaml
Fix `Kubernetes / Ingress Nginx Controllers` and `Kubernetes / Ingress Nginx Controller Details` Grafana dashboards.
Multiple panels seems broken in `Kubernetes / Ingress Nginx Controllers Grafana` dashboard.
On `Kubernetes / Ingress Nginx Controllers` following rows are fixed:
* Container Resources
* Direct Fallback
* Controller (`Requests` graphs was already working)
On `Kubernetes / Ingress Nginx Controller Details` following rows are fixed:
* Container Resources
```changes
type: fix
summary: Kubernetes / Ingress Nginx Controllers Grafana dashboard fixed
```
> [grafana][ingress-nginx] Fix Ingress Nginx dashboard

- testing/cloud_layouts/Static/configuration.tpl.yaml
- testing/cloud_layouts/script.sh
This PR enables helm test for linstor module.
This is temporary solution before implementing https://github.com/deckhouse/deckhouse/issues/2380
Execute e2e tests for linstor
```changes
type: chore
summary: Enable automatic integration tests for linstor module
```
> [testing] Enable automatic integration tests for linstor module

- modules/460-log-shipper/hooks/validate_test.go
- modules/460-log-shipper/images/vector/Dockerfile
Fix https://vector.dev/releases/0.24.2/
The key point to update
> The expire_metrics_secs setting is now correctly applied to expire timeseries not seen in the configured number of seconds.
```changes
type: chore
summary: Bump Vector to 0.24.2
```
> [log-shipper] Vector 0.24.2

- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/doc-ru-cluster_configuration.yaml
Update docs about the `existingZoneToSubnetIDMap` and `exporterAPIKey` parameters.
Ref: #2563
```changes
type: fix
summary: Update docs about the `existingZoneToSubnetIDMap` and `exporterAPIKey` parameters.
```
> [docs][cloud-provider-yandex] Update docs about parameters

- modules/021-cni-cilium/monitoring/prometheus-rules/agent.yaml
Fixed alert templating.
Alerts were incorrectly escaped.
Alert labels are templated properly now.
```changes
type: fix
summary: Fixed alert templating.
```
> [cni-cilium] Fixed alert templating

- modules/040-node-manager/monitoring/prometheus-rules/early-oom.tpl
Alert summary is not clear. It doesn't show all actions that can be done to resolve the alert.
We have feedback from users that they don't know what to do with this alert. Fix UX.
```changes
type: chore
summary: Clarify further actions for EarlyOOMPodIsNotReady alert
```
> [node-manager] Clarify further actions for EarlyOOMPodIsNotReady alert

- modules/042-kube-dns/templates/configmap.yaml
Forgot about "prefer_udp" in stub zones in https://github.com/deckhouse/deckhouse/pull/2413
Same as in previous issue.
CoreDNS with enabled stub zones are no longer affected by the aforementioned issue.
```changes
type: fix
summary: Added "prefer_udp" to stub zones
```
> [kube-dns] "prefer_udp" in stub zones

- candi/bashible/common-steps/all/083_disable_rsyslog_for_docker_and_kubelet.sh.tpl
This PR updates rsyslog modification step to work on systems without rsyslog by default.
Closes #2756
Allows installation on systems without rsyslog.
Install on minimal ubuntu 22.04 without any problems.
> Add rsyslog unit check

- global-hooks/openapi/config-values.yaml
This PR speeds up matrix test by moving "kube-%s.company.my" `publicDomainTemplate` example from `x-examples` to `x-doc-examples`.
Change was tested locally using `time make tests-matrix`:
- before:
- after:
Matrix testing time has greatly increased since #2415 was merged.
This PR fixes this effect, still leaving proposed `publicDomainTemplate` example in docs.
```changes
type: fix
summary: Fix matrix tests duplication in global_hooks/openapi/config_values.yaml
```
> [global_hooks][testing] Fix matrix tests duplication in global_hooks/openapi/config_values.yaml

- modules/021-cni-cilium/images/cilium/patches/003-fix-bwmap-delete-errors.patch
https://github.com/cilium/cilium/commit/125591a72328659237bcde4c81868df655b9a3a8
An unexpected error forces the container to exit.
cilium-agents will be restarted.
```changes
type: fix
summary: Fix panic in the cilium-agent code.
impact: Cilium Agent pods will be restarted.
```
> [cni-cilium] Avoid panic

- .github/workflow_templates/on-pull-request-backport.yml
- .github/workflows/on-pull-request-backport.yml
Add source PR to the backport action
If backport is run from the comment it does not have payload with the PR data. We can fetch it explicitly.
```changes
section: ci
type: fix 
summary: Fix PR title and body generation when backport runs from comment.
```
> [ci] fix backport PR title from comment

- modules/460-log-shipper/templates/configmap.yaml
Reduce interval of metrics expirations checks
In frequently auto-scaling environments, expiring metrics once, e.g., in ten minutes, can cause memory shakes that look like a saw.
Since vector has a smart expiration mechanism that only expires stale metrics, we do not need to care much about the frequency.
Log shipper pods will be restarted.
```changes
type: fix
impact: Expire metrics more frequently
```
> [log-shipper] Expire metrics more frequently

- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/kubernetes/actions/converge/node.go
- dhctl/pkg/system/ssh/checks.go
Add control-plane-manager pod check after creating control-plane nodes.
Creating 2 additional control-plane nodes (doing multimaster) and change first control-plane node both can break a cluster because we cannot check control-plane readiness before recreate first node.
```changes
section: dhctl
type: fix
summary: Wait readiness control plane manager pod while creating new control-plane node. Fix no control new nodes in internal state.
```
> [dhctl] Wait readiness control plane manager pod while creating new control-plane node. Fix no control new nodes in internal state.

- modules/300-prometheus/hooks/calculate_storage_capacity.go
- modules/300-prometheus/hooks/calculate_storage_capacity_test.go
- Fixed disk retention size calculation for small disks.
- Added tests for disks smaller than the default size.
This fixes a bug.
```changes
type: fix
summary: Fixed disk retention size calculation for small disks.
```
> [prometheus] fix disk retention size calc

- docs/site/pages/community.html
Fix broken site link to the blog.
```changes
section: docs
type: fix
summary: Fix broken site link to the blog.
```
> [docs] Fix broken link to the blog

- modules/460-log-shipper/hooks/internal/composer/testdata/config_3.json
- modules/460-log-shipper/hooks/internal/vector/destination/elasticsearch.go
- modules/460-log-shipper/hooks/testdata/es-5x/result.json
- modules/460-log-shipper/hooks/testdata/file-to-elastic/result.json
- modules/460-log-shipper/hooks/testdata/multiline/result.json
- modules/460-log-shipper/hooks/testdata/multiple-dest/result.json
- modules/460-log-shipper/hooks/testdata/namespaced-source/result.json
- modules/460-log-shipper/hooks/testdata/one-dest/result.json
- modules/460-log-shipper/hooks/testdata/pair-datastream/result.json
- modules/460-log-shipper/hooks/testdata/simple-pair/result.json
- modules/460-log-shipper/hooks/testdata/throttle/result.json
https://vector.dev/docs/reference/configuration/sinks/elasticsearch/#suppress_type_name
Fixes https://github.com/deckhouse/deckhouse/issues/2737
```changes
type: fix
summary: Fix Elasticsearch 8.X and Opensearch
```
> [log-shipper] Fix Elasticsearch 8.X

- modules/040-node-manager/hooks/handle_node_templates.go
- modules/040-node-manager/hooks/handle_node_templates_test.go
Fix node taints when NG master has `"node-role.kubernetes.io/master"` set explicitly
We have made fix for single node installations with taint removal but it can affect old cluster with only `"node-role.kubernetes.io/master"` taint set in the `master` NG
```changes
section: node-group
type: fix
summary: Avoid "node-role.kubernetes.io/master" taint removal when it is explicitly set in the master NG
```
> [node-group] Fix master node taint

- modules/460-log-shipper/hooks/internal/vector/transform/destination.go
- modules/460-log-shipper/hooks/testdata/multiple-dest/result.json
- modules/460-log-shipper/hooks/testdata/namespaced-source/result.json
Loki extra labels depends on `parsed_data`
There is a bug with the extraLabels option for Loki when users want to dynamically add labels.
```changes
type: fix
summary: Loki fix extra labels.
```
> [log-shipper] Loki fix extra labels

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
Run chown for /deckhouse repository after executing werf.
There is regression after merging https://github.com/deckhouse/deckhouse/pull/2512. Werf is using Git to managing subtrees and creates new objects under root user inside the docker. These objects can't be managed by unprivileged runner due to incorrect permissions:
```
Error: error: insufficient permission for adding an object to repository database .git/objects
Error: fatal: failed to write object
Error: fatal: unpack-objects failed
Error: The process '/usr/bin/git' failed with exit code 128
```
No above errors 
```changes
type: chore
summary: Fix permissions after running werf
```
> [testing] Fix permissions after running werf

- ee/modules/110-istio/templates/control-plane/iop.yaml
Exclude d8-upmeter ns from istio discovery
Periodically created resources in ns d8-upmeter create unnecessary load on istiod service
Endpoints from ns d8-upmeter no longer appear in updates from istiod for istio-proxy
```changes
section: istio
type: fix
summary: Exclude the `d8-upmeter` namespace from the istio discovery process.
```
> [istio] exclude d8-upmeter ns from istio discovery

- go.mod
- go.sum
shell-operator updates:
- factory to deduplicate informers to reduce memory usage
- remove kube_snapshot* metrics to reduce memory usage
- fix testing/generator to work with factory
addon-operator updates:
- fix: enable 'map merge' YAML feature in OpenAPI schemas
- fix: ignore KubeConfig events before first converge
This update is a part of #1729 scheduled to 1.39 but deps can be updated in release 1.38 to reduce mem usage and possibly return PR #2504 .
```changes
type: fix
summary: update shell-operator and addon-operator dependencies, reduce memory usage
```
> [deckhouse-controller] update shell-operator and addon-operator

- candi/openapi/cluster_configuration.yaml
- candi/openapi/doc-ru-cluster_configuration.yaml
- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Fixed command parameters for editing configuration (added `-ti` to the `kubectl exec` command).
```changes
section: docs
type: fix
summary: Fixed command parameters for editing configuration (added `-ti` to the kubectl exec command).
```
> [doc] Fix command parameters for editing configuration

- Makefile
This PR fixes a bug introduced in #2426 that causes `make` to complain about missing `go` binary when running in workflows without golang installed, e.g. [this test run](https://github.com/deckhouse/deckhouse-test-2/actions/runs/3327302190/jobs/5501973788#step:9:22).
Changes were tested localy.
- Prior that changes:
- After that changes:
This PR makes filling `GOHOSTARCH` and `GOHOSTOS` optional depending upon `go` binary installed.
- Targets not requiring `GOHOSTARCH` and `GOHOSTOS` are executed without makefile complaining about missing `go` executable whether system has that executable.
- Targets that actually use `GOHOSTARCH` and `GOHOSTOS` will fail if executed on a system without `go` binary due to empty variables.
```changes …
```
> [testing] Fix complains about missing go binary during some workflows

- modules/460-log-shipper/apis/v1alpha1/cluster_log_destination.go
- modules/460-log-shipper/apis/v1alpha1/types.go
- modules/460-log-shipper/crds/cluster-log-destination.yaml
- modules/460-log-shipper/crds/doc-ru-cluster-log-destination.yaml
- modules/460-log-shipper/hooks/generate_config_test.go
- modules/460-log-shipper/hooks/internal/composer/composer.go
- modules/460-log-shipper/hooks/internal/composer/testdata/config_1.json
- modules/460-log-shipper/hooks/internal/vector/destination/common.go
- modules/460-log-shipper/hooks/internal/vector/destination/elasticsearch.go
- modules/460-log-shipper/hooks/internal/vector/destination/kafka.go
- modules/460-log-shipper/hooks/internal/vector/destination/loki.go
- modules/460-log-shipper/hooks/internal/vector/transform/destination.go
- modules/460-log-shipper/hooks/testdata/file-to-kafka/manifests.yaml
- modules/460-log-shipper/hooks/testdata/file-to-kafka/result.json
- modules/460-log-shipper/hooks/testdata/multiple-dest/result.json
- modules/460-log-shipper/hooks/testdata/namespaced-source/result.json
- modules/460-log-shipper/images/vector/Dockerfile
* Add new destination - [Kafka](https://vector.dev/docs/reference/configuration/sinks/kafka)
* Use a common struct for encoding - `Encoding`.
Closes https://github.com/deckhouse/deckhouse/issues/560
```changes
type: feature
summary: Add Kafka destination.
```
> [log-shipper] Add Kafka destination

- modules/300-prometheus/hooks/metrics_storage_retention.go
- modules/300-prometheus/hooks/metrics_storage_retention_test.go
- modules/300-prometheus/monitoring/prometheus-rules/prometheus-storage.yaml
Prometheus Retain alerts now respect the retentionDays parameters.
Ignoring the retentionDays parameters leads to false alerts.
```changes
type: fix
summary: Improve Prometheus Retain alerts.
```
> [prometheus] Improove Prometheus Retain alerts

- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/script.sh
Run e2e tests on Redos 7.3 in Yandex Cloud for Containerd. We continue to use ubuntu for docker.
We need to test Redos in e2e
```changes
type: chore
summary: Run e2e tests on Redos 7.3 in Yandex Cloud for Containerd
```
> [testing] Run e2e tests on Redos 7.3 in Yandex Cloud for Containerd

- modules/500-dashboard/openapi/config-values.yaml
- modules/500-dashboard/openapi/doc-ru-config-values.yaml
Add 'highAvailability' field to the OpenAPI schema of config values.
Fix regression: #2133 forbids highAvailability while switching module to use the OpenAPI schema for config values.
- dashboard use high availability while global.highAvailability option is not specified.
```changes
type: fix
summary: "Fix regression - add per-module `highAvailability` field to the OpenAPI schema."
```
> [dashboard] add per-module highAvailability field to the OpenAPI schema

- candi/openapi/doc-ru-node_group.yaml
- candi/openapi/node_group.yaml
`minPerZone` and `maxPerZone` relations clarification in NodeGroup CR documentation.
Some users had false expectations, they wanted to set `minPerZone` = 0 and `maxPerZone` > 0 but this case was [restricted](https://github.com/deckhouse/deckhouse/pull/1249).
The doc describes the case.
```changes
type: fix
summary: `minPerZone` and `maxPerZone` relations clarification in NodeGroup CR documentation.
```
> [node-manager][doc] minPerZone and maxPerZone relations clarification

- modules/021-kube-proxy/templates/daemonset.yaml
Disable readonly filesystem for kube-proxy init-container
https://github.com/deckhouse/deckhouse/pull/2512 introduced regression, kube-proxy can't run with readonly file system:
```
/nodeport-bind-address.sh: line 20: cannot create temp file for here-document: Read-only file system
```
Kube-proxy able to start
```changes
type: fix
summary: Fix insufficient privileges for the init container.
impact: The `kube-proxy` DaemonSet will be restarted.
```
> [kube-proxy] fix insufficient privileges for init container

- modules/300-prometheus/hooks/calculate_storage_capacity.go
- modules/300-prometheus/hooks/calculate_storage_capacity_test.go
Fixed calculation of pvc size and retention size.
In pr #1446, the `app` label was renamed, causing pvc size and retention to be calculated using the default values.
```changes
type: fix
summary: Fixed calculation of pvc size and retention size.
```
> [prometheus] Fix calculation of pvc size and retention size

- modules/002-deckhouse/crds/deckhouse-release.yaml
- modules/002-deckhouse/crds/doc-ru-deckhouse-release.yaml
Remove .status.approved printer field
It doesn't make sense for a user but only confuses him. We left this flag for internal logic (state) but hide it from the output
```changes
type: fix
summary: Removed the `Approved` column from the status columns.
```
> [deckhouse] remove approved status from printer columns

- candi/cloud-providers/aws/docs/LAYOUTS.md
- candi/cloud-providers/aws/docs/LAYOUTS_RU.md
- docs/site/_includes/getting_started/aws/partials/config.yml.standard.ce.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.standard.ee.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.with_nat.ce.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.with_nat.ee.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.without_nat.ce.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.without_nat.ee.inc
- docs/site/js/getting-started.js
AWS AMI in the Getting Started was updated to Ubuntu Server 22.04 LTS.
Clarified description in the AWS config files in the Getting Started.
```changes
section: docs
type: fix
summary: Updated AWS AMI in the Getting Started to Ubuntu Server 22.04 LTS.
```
> Fix AMI in Get Started guide

- modules/041-linstor/docs/CONFIGURATION.md
- modules/041-linstor/docs/CONFIGURATION_RU.md
Automatically allocate 100% free space while creating lvmthin pool
Don't force user to think about space allocation
Docs updated
```changes
type: chore
summary: document how to automatically allocate 100% free space while creating lvmthin pool
```
> Automatically allocate 100% free space while creating lvmthin pool

- modules/300-prometheus/monitoring/grafana-dashboards/kubernetes-cluster/prometheus-self.json
* Add tables to the bottom of panels to be able to sort and filter
* Increase size
```changes
type: feature 
summary: Update Prometheus-(Self) dashboard
```
> [prometheus] Update Prometheus-(Self) dashboard

- modules/300-prometheus/monitoring/grafana-dashboards/kubernetes-cluster/prometheus-benchmark.json
To make Prometheus debugging easier.
```changes
type: feature
summary:  Add Prometheus benchmark dashboard
```
> [prometheus] Add Prometheus benchmark dashboard

- modules/021-cni-cilium/templates/agent/podmonitor.yaml
- modules/021-cni-cilium/templates/operator/podmonitor.yaml
Naming and apply them only if operator-prometheus-crd is enabled.
PodMonitors were not appropriately named. This resulted in non-transparent understanding of metrics labels and their source.
Metrics are now appropriately named.
```changes
type: fix
summary: Improved PodMonitors. Naming and apply them only if operator-prometheus-crd is enabled.
```
> [cni-cilium] Improved PodMonitors

- modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml
Signed-off-by: Maksim Nabokikh <maksim.nabokikh@flant.com>
Fixes https://github.com/deckhouse/deckhouse/issues/2904
```changes
type: fix
summary: Fix a typo in CertificateSecretExpiredSoon alert's description
```
> [extended-monitoring] Typos in CertificateSecretExpiredSoon

- modules/041-linstor/images/spaas/Dockerfile
DRBD kernel module can't be built on Ubuntu 22.04
fixes https://github.com/LINBIT/saas/issues/2
Linstor module is working on Ubuntu 22.04
```changes
type: fix
summary: fix spaas python dependencies
```
> [linstor] spaas: fix python and gcc dependencies 

- docs/documentation/_data/supported_versions.yml
- docs/documentation/_data/version_map_addition.yml
Add Rocky Linux 8 and 9 to the list of supported OS.
```changes
section: docs
type: chore
summary: Add Rocky Linux 8 and 9 to the list of supported OS.
```
> [docs] Add Rocky Linux to the list of supported OS

- candi/openapi/node_group.yaml
- ee/modules/110-istio/openapi/config-values.yaml
- ee/modules/110-istio/openapi/openapi-case-tests.yaml
- global-hooks/openapi/config-values.yaml
- global-hooks/openapi/openapi-case-tests.yaml
- modules/021-cni-cilium/openapi/config-values.yaml
- modules/021-cni-cilium/openapi/openapi-case-tests.yaml
- modules/300-prometheus/openapi/config-values.yaml
- modules/300-prometheus/openapi/openapi-case-tests.yaml
- modules/300-prometheus/openapi/values.yaml
- modules/340-monitoring-kubernetes/openapi/config-values.yaml
- modules/340-monitoring-kubernetes/openapi/openapi-case-tests.yaml
- modules/460-log-shipper/openapi/config-values.yaml
- modules/460-log-shipper/openapi/openapi-case-tests.yaml
memory validation fix — float support for dimensioned digits like 3.5Gi.
We couldn't use the dot in values with units.
Closes issue #2233
Memory validation allows using notations like '5.0Gi'
```changes
section: openapi
type: chore
summary: Memory validation allows to use notation like '5.0Gi'
impact: no impact expected
```
> [global] memory validation fix — float support for dimensioned digits

- ee/modules/450-network-gateway/openapi/openapi-case-tests.yaml
- modules/002-deckhouse/openapi/openapi-case-tests.yaml
- modules/301-prometheus-metrics-adapter/openapi/openapi-case-tests.yaml
- testing/openapi_cases/openapi_cases_test.go
- copy iterator variable for proper carrying
- fix some non-working tests
Commit e66033a2 brings regression: only global OpenAPI schema was tested.
- OpenAPI cases test should fail on invalid values for modules.
```changes
type: fix
summary: fix openapi cases tests
```
> [testing] fix openapi cases test

- Makefile
Allow specifying FOCUS for tests-modules, eg.:
```
make tests-modules FOCUS=cloud-provider-yandex
```
Better DX
Ability to test specific module via makefile
```changes
type: chore
summary: support FOCUS for tests-modules target
```
> [testing] support FOCUS for tests-modules target

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/generic/kubelet.tpl
PR #2942 reverting.
It was accidentally merged (it was a draft but with ready-to-review status).
```changes
type: fix
summary: Reverting of "removed unschedulable nodes from K8SNodeNotReady alert"
```
> Revert "[monitoring-kubernetes] removed unschedulable nodes from K8SNodeNotReady and K8SManyNodesNotReady alerts (#2942)"

- ee/modules/380-metallb/monitoring/prometheus-rules/metallb.yaml
Removed the D8MetalLBAddressPoolUsage80Percent alert.
Practice has shown, that there are plenty of legitimate cases when the fool pool isn't an issue.
No false positive alerts about MetalLB pool usage. Problem with stucked service of loadbalancer type will be solved in #2981 
```changes
type: chore
summary: Removed alert about 80% MetalLB pool usage.
```
> [metallb] removed the D8MetalLBAddressPoolUsage80Percent alert

- modules/340-extended-monitoring/images/extended-monitoring-exporter/src/extended-monitoring.py
Sometimes extended monitoring exporter can stop sending metrics because of Kubernetes API server connection loss of something.  This PR adds the check that new metrics are collected. Otherwise, kubelet will restart the pod because of the failed liveness probe.
```changes
section: extended-monitroing
type: fix
summary: Restart if metrics were last collected more than 15 minutes
```
> [extended-monitoring] Restart if metrics were last collected more than 15 minutes

- ee/modules/350-node-local-dns/templates/daemonset.yaml
Disable node-local-dns for cilium installations on nodes with kernel < 5.7 due to problems with ebpf-socket and resolved endpoints.
```changes
type: fix
summary: Disable `node-local-dns` for cilium installations on nodes with kernel < 5.7 due to problems with `ebpf-socket` and resolved endpoints.
impact: The node-local-dns module stops working for cilium installations on nodes with kernels < 5.7.
```
> [node-local-dns] disable node-local-dns for cilium installations on nodes with kernel < 5.7

- ee/modules/040-node-manager/openapi/openapi-case-tests.yaml
- modules/040-node-manager/openapi/openapi-case-tests.yaml
- remove values cases from EE version
- add negative case in CE with EE bundles
Fix openapi tests after split in #2946
OpenAPI tests works.
```changes
type: fix
summary: Fix OpenAPI tests after the split in #2946.
```
> [node-manager] fix openapi tests for node-manager after #2946

- modules/340-monitoring-kubernetes-control-plane/templates/control-plane-proxy/daemonset.yaml
Changed listen port because it is already used by ingress-nginx module.
There is a conflict when ingress-nginx and control-plane-proxy are running on the same nodes.
```changes
type: fix
summary: Port to listen changed to 8008 because it is already used by the ingress-nginx module.
```
> [monitoring-kubernetes-control-plane] control-plane-proxy change listen port

- candi/openapi/node_group.yaml
- modules/040-node-manager/webhooks/validating/node_group
Additional NodeGroup name validation
One of labels assigned by the cloud instance manager contains full node name.
Kubernetes label can't be longer than 63 characters. 
Also, in Amazon cloud AWSMachineClass name can't contain dots.
We limit node names to 63 characters and restrict dots usage.
Fix #2726
It is forbidden to use dots in the NodeGroup name. Length of clusterPrefix and NodeGroup name sum limited to 42 characters.
```changes
type: chore
summary: Added pattern and limit of 42 characters in NodeGroup name check in CRD.
```
> [node-manager] added pattern and length limit for NodeGroup name check

- ee/fe/modules/340-monitoring-applications/hooks/discovery.go
Fix error in discovery hook for monitoring-aplications module.
Discovery does not work properly.
```
monitoringApplications:
enabledApplications: []
internal:
allowedApplications: []
enabledApplicationsSummary: []
```
```
monitoringApplications:
enabledApplications: []
internal:
allowedApplications:
- consul
- elasticsearch
- etcd3
- fluentd
- grafana
- memcached
- minio
- mongodb
- nats
- nginx
- php-fpm
- prometheus
- rabbitmq
- redis
- sidekiq
- trickster
- uwsgi
enabledApplicationsSummary:
- prometheus
```
```changes
type: fix
summary: Fix discovery hook for monitoring applications module.
```
> [monitoring] fix discovery hook for monitoring applications module

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- tools/images_tags/main.go
Using werf insude the docker container brings additional problems:
- Werf creates new git objects with wrong permissions, which must be fixed every time after running docker
- Werf wants to control git worktrees, which are persistent and can be broken insude/outside container
It seems the [previous fix](https://github.com/deckhouse/deckhouse/pull/2848) does not working properly
This is another attempt to fix it.
No more werf inside the docker, let it on a host only
```changes
type: fix
summary: avoid using werf inside the docker
impact: low
```
> [testing] avoid using werf inside the docker

- modules/340-monitoring-kubernetes/templates/kube-state-metrics/additional-scrape-config.yaml
kube-state-metrics scrape timeout was extended.
I've decided to pick it as a patch to v1.40.2 for two reasons:
* there is possible unpleasant impact to Madison (hundreds of alerts like D8IstioActualVersionIsNotInstalled).
* there is a hand-fixed customer cluster under v1.36 🙄 .
* there are approved fixes in v1.40.2.
In some setups (Pods count > 3k), kube-state-metrics couldn't fit the standard timeout (10s).
kube-state-metrics exports their metrics and prometheus scrapes them well.
```changes
type: fix
summary: kube-state-metrics scrape timeout was extended.
```
> [monitoring-kubernetes] kube-state-metrics extended scrape_timeout

- global-hooks/discovery/kubernetes_version.go
- modules/002-deckhouse/hooks/metrics.go
- modules/002-deckhouse/hooks/set_module_image_value.go
- modules/300-prometheus/images/grafana/grafana_home_dashboard.json
- modules/340-monitoring-deckhouse/monitoring/prometheus-rules/alerting.yaml
* Added `Release Channel` stat.
* Added `Update Mode` stat and `Update Windows` table.
* Table with enabled modules is sorted by the module order. Each module name contains the link to its documentation.
* Added table with an interval between the last metric in Prometheus tsdb and the current time. In the previous picture, Prometheus longterms stores metrics for 4 month, and regular Prometheus stores metrics for 15 days.
* Pies instead of panels for:
* Pods quantity by status (Running and others)
* Nodes quantity by node group name
* Controllers quantity by type (DaemonSet, Deployment, etc.)
* Services quantity by type (NodePort, ClusterIP)
```changes
type: fix
summary: Update Grafana Home dashboard.
impact_level: …
```
> [prometheus] Update Grafana Home dashboard

- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
run render-workflows.sh (fix for https://github.com/deckhouse/deckhouse/pull/2984)
fix regression when https://github.com/deckhouse/deckhouse/pull/2984 was merged without rendering github workflows
No more werf inside the docker, let it on a host only
```changes
type: fix
summary: run render-workflows.sh (fix for 2984)
impact: low
```
> [testing] re-render github workflows (fix)

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/generic/kubelet.tpl
Excluded unschedulable nodes from K8SNodeNotReady and K8SManyNodesNotReady alerts.
When a node is about to be removed by cluster-autoscaler, alerts can start firing despite the node is cordoned.
Fix #2829
Alerts K8SNodeNotReady and K8SManyNodesNotReady ignore cordoned nodes.
```changes
type: chore
summary: Excluded unschedulable nodes from K8SNodeNotReady and K8SManyNodesNotReady alerts.
```
> [monitoring-kubernetes] excluded unschedulable nodes from K8SNodeNotReady and K8SManyNodesNotReady alerts

- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/pkg/config/load.go
- dhctl/pkg/kubernetes/client/lease-lock.go
- dhctl/pkg/log/process_test.go
- dhctl/pkg/operations/bootstrap.go
- dhctl/pkg/template/engine.go
Minor edits of log messages in dhctl.
Some messages of dhctl confuse.
—
```changes
section: dhctl
type: fix
summary: Minor edits of log messages in dhctl.
```
> [dhctl] minor edits of log messages

- modules/340-extended-monitoring/templates/image-availability-exporter/deployment.yaml
Pass HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables into image-availability-exporter.
Setting Deckhouse [proxy parameters](https://deckhouse.io/en/documentation/v1/deckhouse-configure-global.html#parameters-modules-proxy) required to actually pass said variables.
<details>
<summary>Changes were tested on local cluster.</summary>
* Before:
* After:
</details>
Currently image-availability-exporter is unaware of [proxy parameters](https://deckhouse.io/en/documentation/v1/deckhouse-configure-global.html#parameters-modules-proxy), which may lead to false alerts from `modules/340-extended-monitoring/monitoring/prometheus-rules/image-availability/image-checks.tpl` if proxy is used for registry access.
httpProxy, httpsProxy and …
> [extended-monitoring] Pass HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables into image-availability-exporter

- modules/101-cert-manager/openapi/config-values.yaml
- modules/101-cert-manager/openapi/doc-ru-config-values.yaml
- modules/101-cert-manager/template_tests/module_test.go
- modules/101-cert-manager/templates/cert-manager/clusterissuer-letsencrypt-staging.yaml
- modules/101-cert-manager/templates/cert-manager/clusterissuer-letsencrypt.yaml
Implementation of the feature to control ClusterIssuers objects in case of its disabling.
It is feauture request, required by client, to avoid the ClusterIssuer objects creation due to unsage of letsencrypt of cert-manager.
It refers to this issue: #2711
In case of specifying 'false' or non-specified - the backward compatibility will be used, so nothing would be changed.
In case of specifying 'true' - there wouldn't be any creation regarding to ClusterIssuer objects at all.
```changes
type: feature
summary: Ability to disable the `letsencrypt` ClusterIssuers creation in case of needs.
```
> Add ability to control default list of ClusterIssuers

- tools/change-registry.sh
Added additional checks to the registry migration script. The script will exit with an error, in case of:
- There is no path in registry URL.
- Domain doesn't match RFC 1123 regex.
- It's impossible to get a Bearer token from the new registry.
In some cases, there can be problems after Deckhouse migration to other registry.
Script will exit with error, in case of:
- There is no path in registry URL.
- Domain doesn't match RFC 1123 regex.
- It's impossible to get a Bearer token from the new registry.
```changes
section: tools
type: fix
summary: Added additional checks to registry migration script.
```
> [tools] fix in registry migration script

- ee/modules/110-istio/hooks/discovery_application_namespaces.go
- ee/modules/110-istio/hooks/discovery_application_namespaces_test.go
Ignore `Namespace` in terminating phase during istio driven `Namespace` discovery in `discovery_application_namespaces.go`
Closes https://github.com/deckhouse/deckhouse/issues/3052
No errors in synchronization of the istio module during the existence of the istio driven namespace in termination state
```changes
section: istio
type: fix
summary: Exclude terminating application namespaces from discovery
```
> [istio] fix namespace discovery

- modules/040-node-manager/template_tests/module_test.go
- modules/040-node-manager/templates/cluster-autoscaler/expander-cm.yaml
Fix generating expander configmap for cluster-autoscaler if Deckhouse has a few node groups with the same priority
Same priority on a few node groups generates wrong yaml:
```
apiVersion: v1
data:
priorities: |-
50:
- ^xxx-staging-[0-9a-zA-Z]+$
70:
- ^xxx-staging-spot-m5a-2xlarge-[0-9a-zA-Z]+$
90:
- ^xxx-staging-spot-[0-9a-zA-Z]+$
- ^xxx-staging-spot-m5a.8xlarge-[0-9a-zA-Z]+$
- ^xxx-staging-spot-c5.16xlarge-[0-9a-zA-Z]+$
kind: ConfigMap
metadata:
labels:
app: cluster-autoscaler
heritage: deckhouse
workload-resource-policy.deckhouse.io: master
name: cluster-autoscaler-priority-expander
namespace: d8-cloud-instance-manager
```
After this fix cm will look like:
```
apiVersion: v1
data:
priorities: |-
50:
- …
```
> [node-manager] Fix ng expander cm

- modules/040-node-manager/hooks/handle_node_templates.go
- modules/040-node-manager/hooks/handle_node_templates_test.go
- modules/040-node-manager/monitoring/prometheus-rules/node-group.tpl
Add an alert about missing taints
Some old-created node groups are missing desired control-plane taint and it could lead to the problems in 1.24+ k8s clusters
```changes
type: feature 
summary: Add an alert about missing control-plane taints on the `master` node group
```
> [node-manager] add alert on master ng absent taint

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/controller.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/namespace/namespace.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/pod.json
Fix network-related columns and graphs in Main/Namespace, Main/Namespace/Controller, and  Main/Namespace/Controller/Pod dashboards
- Fix Receive and Transmit panels in the Network section:
- Fix queries
- Fix title for "Receive" panels.
- Special handling of Pods with hostNetwork: true.
- Add query to produce -1 value for such Pods
- Use timeseries plugin and add value mappings to display warning about Pods with hostNetwork: true
- Fix TX Network and RX Network column in the summary table.
- Add value mapping, display "hostNet" for Pods with hostNetwork: true.
- Add comments to queries.
- Known issues:
- The 'Total' row in the legend is now at the bottom. May be fixed in Grafana 9.1.
- Clicking on the 'Total' row in legend shows nothing.
- Warning duplication feels weird (see …
> [monitoring-kubernetes] fix kube_pod_info{host_network=true} expression

- docs/site/.helm/templates/20-ingress.yaml
- docs/site/_includes/channel-menu.html
- docs/site/werf-debug.yaml
- docs/site/werf.yaml
- Fix the menu of versions on the site.
- Add redirects for documentation from a patch version to a Maj.Min version.
- Use a stable web-router tag.
```changes
section: docs
type: fix
summary: Fix the menu of versions on the site.
```
> [site] Fix the menu of versions on the site

- docs/site/.helm/templates/20-ingress.yaml
Add redirects for documentation versions lower than 1.38.
```changes
section: docs
type: chore
summary: Add redirects for documentation versions lower than 1.38.
```
> [site] Add redirects for documentation versions lower than 1.38

- modules/500-upmeter/images/upmeter/Makefile
- modules/500-upmeter/images/upmeter/pkg/db/context/context.go
- modules/500-upmeter/images/upmeter/pkg/db/context/pool.go
- modules/500-upmeter/images/upmeter/pkg/db/dao/episode30s.go
- modules/500-upmeter/images/upmeter/pkg/db/dao/episode5m.go
- modules/500-upmeter/images/upmeter/pkg/db/dao/exporting.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/dex.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_daemonset.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_nodegroup.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/prometheus.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/prometheus_metrics_adapter.go
- modules/500-upmeter/images/upmeter/pkg/server/api/episode_test.go
- modules/500-upmeter/images/upmeter/pkg/server/api/parse_test.go
- modules/500-upmeter/images/upmeter/pkg/server/api/public_status.go
- modules/500-upmeter/images/upmeter/pkg/server/api/public_status_test.go
- modules/500-upmeter/images/upmeter/pkg/server/api/status.go
- modules/500-upmeter/images/upmeter/pkg/server/entity/episode_test.go
- modules/500-upmeter/images/upmeter/pkg/server/entity/status.go
- modules/500-upmeter/images/upmeter/pkg/server/entity/status_test.go
- modules/500-upmeter/images/upmeter/pkg/server/ranges/steprange.go
- modules/500-upmeter/images/upmeter/pkg/server/ranges/steprange_test.go
- modules/500-upmeter/images/upmeter/pkg/server/server.go
- testing/cloud_layouts/script.sh
In public status route on the server, we add uptime value per probe.
It can help us track the availablility of more cluster components in e2e tests than smoke-mini can
provide.
e2e tests request the uptime information from upmeter server and fail is the uptime is not satisfactory.
```changes
type: feature
summary: Added probe uptime in public status API to use in e2e tests
```
> [upmeter,e2e] Smoke test with upmeter server, using per-probe public uptime

- modules/030-cloud-provider-yandex/hooks/yandex_cluster_configuration_test.go
Remove duplicated keys from YAML in test.
All PRs have failed tests because of this test. It seems we've updated yaml library or something like that.
<details><summary>Log example</summary>
<pre>
Modules :: cloud-provider-yandex :: hooks :: yandex_cluster_configuration :: /deckhouse/modules/030-cloud-provider-yandex/hooks/yandex_cluster_configuration_test.go:29
Provider data is successfully discovered
/deckhouse/modules/030-cloud-provider-yandex/hooks/yandex_cluster_configuration_test.go:162
All values should be gathered from discovered data [It]
/deckhouse/modules/030-cloud-provider-yandex/hooks/yandex_cluster_configuration_test.go:168
Expected '
existingNetworkID: enpma5uvcfbkuac1i1jb
kind: YandexClusterConfiguration
layout: WithNATInstance
masterNodeGroup: …
> [cloud-provider-yandex] fix: test fails on unmarshaling YAML with duplicated keys

- candi/control-plane-kubeadm/config.yaml.tpl
- ee/modules/030-cloud-provider-vsphere/hooks/discover_zones_and_datastores.go
- modules/015-admission-policy-engine/hooks/detect_validation_resources.go
- modules/015-admission-policy-engine/hooks/detect_validation_resources_test.go
- modules/015-admission-policy-engine/images/constraint-exporter/go.mod
- modules/015-admission-policy-engine/images/constraint-exporter/go.sum
- modules/015-admission-policy-engine/images/constraint-exporter/main.go
- modules/015-admission-policy-engine/images/constraint-exporter/pkg/gatekeeper/constraints.go
- modules/015-admission-policy-engine/images/constraint-exporter/pkg/kinds/kinds.go
- modules/015-admission-policy-engine/images/constraint-exporter/pkg/kinds/kinds_test.go
- modules/015-admission-policy-engine/openapi/values.yaml
- modules/015-admission-policy-engine/template_tests/module_test.go
- modules/015-admission-policy-engine/template_tests/policies_test.go
- modules/015-admission-policy-engine/templates/audit-deployment.yaml
- modules/015-admission-policy-engine/templates/rbac-for-us.yaml
- modules/015-admission-policy-engine/templates/service.yaml
- modules/015-admission-policy-engine/templates/validatingwebhookconfiguration.yaml
- modules/021-kube-proxy/templates/configmap.yaml
Get resources from tracked constraints to watch only them in the validation webhook
By default validation webhook is too open. It validates all type of the resources. We can calculate only desired resources and follow them. Deckhouse will automatically filter unsupported resources (like `extensions/Ingress` for the 1.24 k8s).
Also enable [Topology Aware Hints](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/) for webhook service to save traffic in the multi-zone clusters
We have the next match in the constraint:
```
spec:
enforcementAction: deny
match:
kinds:
- apiGroups:
- ""
kinds:
- Pod
```
then validation webhook will have:
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
name: d8-admission-policy-engine-config …
```
> [admission-policy-engine] admission policy validation webhook include only tracked resources

- candi/bashible/bashbooster/50_deckhouse_registrypackages.sh
- candi/bashible/bundles/centos/all/000_install_ca_certificates.sh.tpl
- candi/bashible/bundles/centos/bootstrap.sh.tpl
- candi/bashible/bundles/debian/all/000_install_ca_certificates.sh.tpl
- candi/bashible/bundles/ubuntu-lts/all/000_install_ca_certificates.sh.tpl
- candi/bashible/common-steps/all/001_set_system_proxy.sh.tpl
- candi/bashible/common-steps/all/001_set_system_proxy.tpl
- candi/bashible/common-steps/node-group/050_configure_and_start_containerd.sh.tpl
- ee/candi/bashible/bundles/alteros/all/000_install_ca_certificates.sh.tpl
- ee/candi/bashible/bundles/astra/all/000_install_ca_certificates.sh.tpl
- ee/candi/bashible/bundles/redos/all/000_install_ca_certificates.sh.tpl
- modules/040-node-manager/images/bashible-apiserver/pkg/template/context_builder.go
- modules/040-node-manager/templates/bashible-apiserver/deployment.yaml
1. Added fail with error if docker registry cannot support bearer token auth.
2. Added bashible unit to setup system-wide proxy from deckhouse config (for closed environments).
3. Fixed registry custom ca certificate step.
1. If docker registry cannot suport bearer token auth, bashible fails with curl error, which is not informative.
2. global proxy is needed for containerd in closed environments to pull images from registry.
3. When registry ca certificate changes, we need to restart containerd. 
```changes
section: candi
type: chore
summary: |
Added fail with error if docker registry cannot support bearer token auth.
Added bashible unit to setup system-wide proxy from deckhouse config (for closed environments).
Fixed registry custom ca certificate step.
```
> [candi] various bashible fixes and improvements

- ee/modules/030-cloud-provider-vsphere/images/vsphere-csi-plugin/Dockerfile
Bump csi driver to [v2.5.4](https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.5.4).
Closes https://github.com/deckhouse/deckhouse/issues/2985
```changes
type: fix
summary: Bump csi driver to v2.5.3
```
> [cloud-provider-vsphere] Bump csi driver to v2.5.4

- dhctl/pkg/kubernetes/actions/manifests/manifests_test.go
Fix struct_vs_unmarshal test
Test was unstable and was not passed. [Example](https://github.com/deckhouse/deckhouse/actions/runs/3523321321/jobs/5907568953)
Test always should pass
```changes
section: dhctl
type: fix
summary: Fix struct_vs_unmarshal test
```
> [dhctl] Fix struct_vs_unmarshal test

- modules/402-ingress-nginx/templates/controller/admission.yaml
Added different ValidatingWebhookConfiguration webhooks for system and application ingresses, with different failurePolicy, to avoid Deckhouse stuck during update.
Fix #2950 
Deckhouse won't stuck during upgrade if ingress controller exists without available replicas.
```changes
type: fix
summary: Added different ValidatingWebhookConfiguration webhooks for service and application ingresses, with different failurePolicy, to avoid Deckhouse stuck during update.
```
> [ingress-nginx] less stringent rules for validating Deckhouse service ingresses

- modules/099-ceph-csi/images/cephcsi/Dockerfile
Updated cephcsi to version 3.7.2
An update is required to support new versions of kubernetes.
```changes
type: chore
summary: Updated cephcsi to version 3.7.2
impact: Pods in d8-ceph-csi namespace will be restarted
```
> [ceph-csi] update to 3.72

- modules/003-deckhouse-config/images/deckhouse-config-webhook/werf.inc.yaml
Add stageDependencies to not fail on gitLatestPatch.
Fix build error:
All PR builds are successful.
```changes
type: chore
summary: fix deckhouse-config webhook build
```
> [deckhouse-config] fix deckhouse-config webhook build

- docs/documentation/_data/version_map_addition.yml
Fix supported os list
```changes
section: docs
type: chore
summary: Fix supported os list.
```
> [docs]  Fix supported os list

- modules/500-upmeter/hooks/dynamic_probe/hook.go
- modules/500-upmeter/hooks/dynamic_probe/hook_test.go
- modules/500-upmeter/hooks/dynamic_probe/names.go
- modules/500-upmeter/images/upmeter/cmd/upmeter/parse_args.go
- modules/500-upmeter/images/upmeter/pkg/agent/agent.go
- modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_nodegroup.go
- modules/500-upmeter/images/upmeter/pkg/probe/group_nodegroups.go
- modules/500-upmeter/images/upmeter/pkg/probe/load.go
- modules/500-upmeter/openapi/values.yaml
- modules/500-upmeter/templates/upmeter-agent/daemonset.yaml
Fix nodegroup probe for clusters in Azure Cloud
In Azure, we have mismatch between VM zones ("1", "2", "3") used in upmeter zone discovery. But nodes have topology.kubernetes.io/zone label in the form '$region-1', '$region-2', etc. We have to add a workaround for that.
In future, deckhouse-wise zone notation can be chosen separately from what Azure tooling accepts on input. 
e2e tests in Azure pass
```changes
type: fix
summary: Fixed nodegroup probe for clusters in Azure by fixing zone name discovery.
```
> [e2e tests, azure] Fix zone discovery and matching

- deckhouse-controller/register/main.go
- testing/helm/init.go
- tools/audit_policy/main.go
- tools/build.go
- tools/register/main.go
Code generation should work when deckhouse repo root is symlinked at /deckhouse. This PR attempts
for fix go's `filepath.Walk` for this case.
Enhances DX for those who use /deckhouse symnlink for development
The code generation tha depends on modules should work, e.g. statically generated serviceaccount
list in audit policy.
```changes
section: tools
type: chore
summary: Fixed the generation of go files in /deckhouse
```
> [DX] Fix code generation when /deckhouse is symlinked

- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Increasing failureThreshold of startupProbes for main and longterm prometheus objects.
It is fix, relates to poor performance of used resources.
It refers to this issue: #2884 
The prometheus objects as main and longterm would have the following for startupProbe:
**failureThreshold: 300**
```changes
type: fix
summary: Setting up failureThreshold of startupProbes for main and longterm prometheus objects from 60 to 300.
```
> Increasing failureThreshold of startupProbes for main and longterm prometheus objects

- go_lib/deckhouse-config/status.go
- modules/003-deckhouse-config/hooks/update_status.go
Update version for configs with empty spec.settings.
Should display version for empty settings:
```
spec:
enabled: false
settings: {}
version: 1
```
```
NAME                       STATE      VERSION   STATUS   AGE
log-shipper                Enabled    1                  73m
node-local-dns             Disabled                      39m
prometheus                 Enabled    2                  73m
```
```changes
type: fix
summary: Update version for configs with empty spec.settings.
```
> [deckhouse-config] update version for configs with empty spec.settings

- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Increasing query.maxSamples for main and longterm prometheus objects.
It is fix, relates to dashboard issues with showing a data.
It refers to this issue: #2846 
The prometheus objects as main and longterm would have the following for query:
maxSamples: 100000000
```changes
type: fix
summary: setting up maxSamples of query for main and longterm prometheus objects from 50000000 to 100000000.
impact: the `prometheus` module will be restarted.
```
> Increasing query.maxSamples value for Prometheus

- candi/cloud-providers/aws/openapi/cluster_configuration.yaml
- candi/cloud-providers/aws/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/gcp/openapi/cluster_configuration.yaml
- candi/cloud-providers/gcp/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/doc-ru-cluster_configuration.yaml
- candi/openapi/cluster_configuration.yaml
- candi/openapi/doc-ru-cluster_configuration.yaml
- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
- ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/openapi/doc-ru-cluster_configuration.yaml
- ee/candi/cloud-providers/vsphere/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/vsphere/openapi/doc-ru-cluster_configuration.yaml
Clarify using the ClusterConfiguration and the <provider>ClusterConfiguration parameters.
Close: #2957
```changes
section: doc
type: fix
summary: Clarify using the ClusterConfiguration and the <provider>ClusterConfiguration parameters.
```
> [docs] Clarify using the ClusterConfiguration and the <provider>ClusterConfiguration parameters

- modules/040-node-manager/images/bashible-apiserver/pkg/template/node_group_configuration.go
- modules/040-node-manager/images/bashible-apiserver/pkg/template/steps_storage.go
Fix script name generation
Names for adding and removing scripts are different. And we can't remove a script with a double digits name
```changes
type: fix
summary: Fix script name generation and the bashible-apiserver
```
> [node-manager] Fix script name generation in the bashible-apiserver

- global-hooks/deckhouse-config/startup_sync.go
- global-hooks/deckhouse-config/startup_sync_test.go
- go_lib/deckhouse-config/initial_config_loader.go
- testing/cloud_layouts/script.sh
- Fix initial config loader to skip listing ModuleConfig resources if the ConfigMap/deckhouse-generated... has migration annotation.
- Fix "deckhouse readiness" false-positive in e2e script when Pod is in Terminating phase but is still is ready.
e2e test fails when switch releases from 1.40 to 1.41: deckhouse-controller somehow starts with empty configuration despite  existing configuration in ConfigMap/deckhouse-generated-config-do-not-edit.
'Switching e2e' tests not fail.
```changes
type: fix
summary: Ignore listing ModuleConfig at start when migration in progress.
```
> [deckhouse-config] fix: do not list ModuleConfig if migration in progress

- ee/modules/600-flant-integration/hooks/pricing/envs_from_nodes.go
Filter master nodes based on `node.deckhouse.io/group` in pricing and consider both `node-role.kubernetes.io/master` and `node-role.kubernetes.io/control-plane` taints for dedicated master.
<details>
<summary>
This PR was tested manually on dev-cluster with `node-role.kubernetes.io/control-plane` taint replaced with `node-role.kubernetes.io/master` in `master` NodeGroup.
</summary>
* Corresponding metric on main:
* Corresponding metric on this PR:
</details>
The Kubernetes project is [moving away](https://github.com/kubernetes/kubeadm/issues/2200) from wording that is considered offensive, so `node-role.kubernetes.io/master` label/taint being replaced with `node-role.kubernetes.io/control-plane`.
Relying on `node.deckhouse.io/group` …
> [flant-integration] Filter master nodes based on "node.deckhouse.io/group" and consider "node-role.kubernetes.io/master" taint for dedicated master

- candi/bashible/bashible.sh.tpl
Add `-x` parameter for bash source step command if step fail 3 times.
Close #2158
```changes
type: feature
summary: Show bash debug output for failed sources steps when bootstrap cluster.
```
> [bashible] Show bash debug output for failed sources steps when bootstrap cluster.

- modules/340-monitoring-ping/hooks/discover_targets.go
- modules/340-monitoring-ping/hooks/discover_targets_test.go
Skip unschedulabe nodes in `monitoring-ping`.
Changes were tested in local cluster.
After cordoning one of the workers corresponding metrics won't be captured anymore: 
Currently unschedulable nodes are still pinged in monitoring-ping module.
This causes false positive alerts when unschedulable node is no longer accessible, but isn't removed from k8s yet.
`monitoring-ping` no longer tries to ping unschedulable nodes.
```changes
type: chore
summary: Skip unschedulabe nodes in `monitoring-ping`
```
> [monitoring-ping] Skip unschedulable nodes

- modules/003-deckhouse-config/images/deckhouse-config-webhook/register.go
- modules/003-deckhouse-config/images/deckhouse-config-webhook/werf.inc.yaml
Fix werf.inc.yaml to work with CE sources:
- add go run to re-generate conversion imports
- cleanup: put binary to /
CE build fails https://github.com/deckhouse/deckhouse/actions/runs/3580644295/jobs/6022949324
Release build  justworks.
```changes
type: fix
summary: Fix the CE revision build of the `deckhouse-config-webhook`.
```
> [deckhouse-config] fix CE build of the deckhouse-config-webhook

- dhctl/pkg/kubernetes/actions/deckhouse/install.go
Do not create/update `deckhouse` configmap if exists.
Prevent error:
```
deckhouse create manifests: create resource: admission webhook "[validate-cm.deckhouse-config-webhook.deckhouse.io](http://validate-cm.deckhouse-config-webhook.deckhouse.io/)" denied the request:     ↵
changing ConfigMap/deckhouse is not allowed for kubernetes-admin. Use ModuleConfig resources to configure Deckhouse.
```
during restart bootstrap cluster
```changes
section: dhctl
type: fix
summary: Fix restart bootstrap cluster.
```
> [dhctl] Fix restart bootstrap cluster

- docs/documentation/_includes/module-enable-snippet.liquid
Change the incorrect `deckhouse.io/v1` ModuleConfig version to the correct `deckhouse.io/v1alpha1`.
```changes
section: docs
type: fix
summary: Fix ModuleConfig APIVersion in the documentation.
```
> [docs] Fix ModuleConfig APIVersion in the documentation

- modules/021-cni-cilium/monitoring/prometheus-rules/agent.yaml
Removed CiliumAgentUnreachableNodes alert.
This alert based on metric cilium_unreachable_nodes which is do not work properly on large amount of preemptible instances.
```changes
type: fix
summary: Removed CiliumAgentUnreachableNodes alert
```
> [cni-cilium] removed CiliumAgentUnreachableNodes alert

- modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring/application-controllers.yaml
Fixing the typo
Allows to copy and paste command example flawlessly
The exprience is smoother
```changes
type: chore
summary: Fixed typo in alert templatessibly MULTI-LINE>, required if impact_level is high ↓
```
> [extended-monitoring] Fix alert typo

- deckhouse-controller/go-build.sh
- go.mod
- go.sum
- werf.yaml
Remove libjq-go from build.
Supporting PR: https://github.com/flant/shell-operator/pull/440
libjq is not needed for Go hooks.
```changes
type: chore
summary: Remove libjq-go from build
```
> [deckhouse-controller] libjq is not needed for Go hooks, remove it

- modules/402-ingress-nginx/hooks/manual_daemonset_update.go
- modules/402-ingress-nginx/hooks/manual_daemonset_update_test.go
Fix manual rollout for HostPort inlet
Close #3107 
We have to use `numberAvailable` field value not `currentNumberScheduled`. Because `numberAvailable` increments when pod is ready and available for at least minReadySeconds time, meanwhile `currentNumberScheduled` increments when pod is binded to a node
```
controller-main-2lc9z   3/3     Running       0          5m7s
controller-main-4ppbn   2/3     Terminating   0          6m42s
```
```
controller-main-2lc9z   3/3     Running       0          5m7s
controller-main-vbqv5   0/3     ContainerCreating   0          0s
```
```
controller-main-2lc9z   3/3     Running       0          5m7s
controller-main-vbqv5   2/3     Running   0          8s
```
```
controller-main-vbqv5   3/3     Running   0 …
```
> [ingress-nginx] fix manual pod rollout

- modules/460-log-shipper/hooks/internal/composer/composer.go
Collect data of log-shipper custom resources.
To be aware of various cluster configurations and the number of clusters where the module is really used by applications.
```changes
type: chore
summary: Add telemetry.
```
> [log-shipper] Add telemetry

- modules/040-node-manager/hooks/get_crds.go
- modules/040-node-manager/hooks/get_crds_test.go
- modules/040-node-manager/hooks/internal/autoscaler/capacity/capacity.go
Fix node capacity value generation
In some cases wrong/missing capacity spec can lead to broken ng spec. I think we can set `nodeCapacity` value only if it's valid.  We have a protection inside the templates `{{- if $ng.nodeCapacity }}` so we will have an error and unscalable from zero node group but it would have a change to break a whole node-group spec and remove all nodes (because of `cloudInstances` is not set)
```changes
type: fix
summary: Fix node-group template generation when `minPerZone==0` and capacity is not set.
```
> [node-manager] fix ng capacity handling

- docs/site/_includes/getting_started/existing/partials/TROUBLESHOOT.liquid
- docs/site/_includes/getting_started/existing/partials/TROUBLESHOOT_RU.liquid
- docs/site/_includes/getting_started/global/partials/NOTICES.liquid
- docs/site/_includes/getting_started/global/partials/NOTICES_ENVIRONMENT.liquid
Added a note in the Getting started that EKS is not supported.
```changes
section: docs
type: fix
summary: Added a note in the Getting started that EKS is not supported.
```
> [docs] Note that EKS is not supported

- global-hooks/deckhouse-config/startup_sync.go
- global-hooks/deckhouse-config/startup_sync_test.go
- global-hooks/deckhouse-config/testdata/test-startup-sync/global-hooks/openapi/config-values.yaml
- global-hooks/deckhouse-config/testdata/test-startup-sync/modules/001-cert-manager/openapi/config-values.yaml
- go.mod
- go.sum
- go_lib/deckhouse-config/initial_config_loader.go
- go_lib/deckhouse-config/initial_config_loader_test.go
- go_lib/deckhouse-config/module-manager/test/mock/mock.go
- go_lib/deckhouse-config/status.go
- go_lib/deckhouse-config/testdata/validator/global/openapi/config-values.yaml
- go_lib/deckhouse-config/validator.go
- go_lib/deckhouse-config/validator_test.go
- modules/003-deckhouse-config/hooks/update_status_test.go
- testing/cloud_layouts/script.sh
- testing/conversion/init.go
Validate raw spec.settings is not compatible with addon-operator behaviour. Addon-operator applies defaults before validating "config values" (see [module_manager.go](https://github.com/flant/addon-operator/blob/main/pkg/module_manager/module_manager.go#L979-L981)).
deckhouse-config module treats valid spec.settings as invalid and disables previously enabled module.
Should not disable modules on update v1.40 -> v1.41.
```changes
type: fix
summary: Apply defaults before spec.settings validation.
```
> [deckhouse-config] fix: apply defaults before spec.settings validation

- release.yaml
Turn on canary deploy for the Beta release channel.
```changes
section: ci
type: chore
summary: Turn on canary deploy for the Beta release channel.
```
> [ci] Turn on canary deploy for the Beta release channel

- go.mod
- go.sum
Switch from feat_build_tag_to_enable_libjq_go to main branch (regression in pr #3098).
Branch for PR may dissapear.
```changes
type: chore
summary: Use main branch for shell-operator.
```
> [deckhouse-controller] chore: use main branch for shell-operator

- modules/150-user-authn/images/dex/patches/oidc-ca-insecure.patch
Read content directly, not from paths. It is pointless to try to read certificates from files because users cannot mount them.
This is a bug, the previously added feature does not work.
The reason of hotfixing — there is a customer with pilot project and hardly-closed infrastructure. Need to hurry the process up.
```changes
summary: Read CA for OIDC provider from encoded PEM string.
```
> [user-authn] Read CA from encoded PEM string

- modules/402-ingress-nginx/hooks/order_certificates.go
Change hook order
This hook is based on values `ingressControllers` array but has lower order. That's why on bootstrap it can has no controllers and will skip certificates generation.
```changes
type: fix
summary: Fix auth tls certificates bug which leads to absent certificates on ingress controller bootstrap
```
> [ingress-nginx] change order_certificates hook order

- ee/modules/600-flant-integration/monitoring/prometheus-rules/sending-alerts.yaml
Changed expression for D8PrometheusMadisonErrorSendingAlertsToBackend alert (it ignored the possibility of two Prometheus instances in cluster)
Fix #2271 
There will be alerts in cluster if any of main Prometheus fails to send events.
```changes
type: fix
summary: Changed expression for D8PrometheusMadisonErrorSendingAlertsToBackend alert
```
> [flant-integration] changed expression for D8PrometheusMadisonErrorSendingAlertsToBackend alert

- candi/cloud-providers/aws/openapi/doc-ru-instance_class.yaml
- candi/cloud-providers/aws/openapi/instance_class.yaml
Clarify the use of the ami parameter in the AWSInstanceClass.
```changes
section: docs
type: chore
summary: Clarify the use of the ami parameter in the AWSInstanceClass.
```
> [docs] Clarify the use of the ami parameter in the AWSInstanceClass

- modules/003-deckhouse-config/templates/deckhouse-config-webhook/webhook-configuration.yaml
- Webhook has stuck in Pending status because it requires initialized cluster
- Deckhouse has stuck on global hook trying to update ConfigMap
deckhouse-config-webhook seems redundant during cluster bootstrap.
Fix race condition "Global hook can't update the ConfigMap because node-manager can't remove the taint "uninitialized" because global hook holds the 'main' queue."
- Sometimes NodeManager does not have time to remove the taint "uninitialized" and Deckhouse Pod is restarted.
- During startup Deckhouse has stuck on global hook trying to update ConfigMap.
- deckhouse-config-webhook can't tolerate "unintialized" and has stuck in Pending status.
It was observed in real installations (not e2e tests) of Static cluster and in Azure.
```changes
type: fix
summary: …
```
> [deckhouse-config] disable deckhouse-config webhook for uninitialized cluster

- modules/600-namespace-configurator/hooks/handler.go
- modules/600-namespace-configurator/hooks/handler_test.go
Bugfix — every configuration patched every namespace matched the filter.
There could be many configurations simultaneously and we must support it.
Why hotfix — there is a customer who eager to use the module.
```changes
section: namespace-configurator
type: fix
summary: Apply configuration only for namespaces matched the filter in this configuration.
```
> [namespace-configurator] multiple configurations together fix

- ee/modules/600-flant-integration/images/flant-pricing/hooks/prometheus_metrics.sh
Changes in flant-integration for Rocky, RedOS, AlterOS, Alma and Astra Linux support
We need correct parsing of OS image param in flant-integration module for correct OS name discover from client nodes.
Correct data about nodes with Rocky, RedOS, AlterOS, Alma and Astra Linux
```changes
type: chore
summary: Changes in flant-integration for Rocky, RedOS, AlterOS, Alma and Astra Linux support
```
> [flant-integration] Added regex to parse os image for rocky, alteros, redos, alma and astra linux

- modules/030-cloud-provider-yandex/images/yandex-csi-plugin/Dockerfile
Updated Yandex CSI to v0.9.12 (with [fsck check while mounting PV](https://github.com/deckhouse/yandex-csi-driver/pull/12))
Fix #2887 
Fsck check will now be performed while mounting PV.
```changes
type: chore
summary: Added fsck check while mounting PV in Yandex Cloud.
```
> [cloud-provider-yandex] updated Yandex CSI to v0.9.12 (with fsck check while mounting PV)

- modules/150-user-authn/templates/dex-authenticator/deployment.yaml
Dex now serves TLS with self signed certificates
```changes
type: fix
summary: Fix dex authenticator probe to tolerate self signed certificates.
```
> [user-authn] Fix dex authenticator probe

- candi/cloud-providers/yandex/layouts/standard/base-infrastructure/main.tf
- candi/cloud-providers/yandex/layouts/standard/variables.tf
- candi/cloud-providers/yandex/layouts/with-nat-instance/base-infrastructure/main.tf
- candi/cloud-providers/yandex/layouts/with-nat-instance/variables.tf
- candi/cloud-providers/yandex/layouts/without-nat/base-infrastructure/main.tf
- candi/cloud-providers/yandex/layouts/without-nat/variables.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/main.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/outputs.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/variables.tf
- candi/terraform_versions.yml
- Update terraform yandex provider to [v0.83.0](https://github.com/yandex-cloud/terraform-provider-yandex/releases/tag/v0.83.0)
- Use NAT gateway instead of deprecated feature "[NAT to the internet](https://cloud.yandex.com/en-ru/docs/vpc/operations/enable-nat)"
"NAT to the internet" is deprecated. New clusters can't be created using layout Standard.
If you have layout Standard, follow the [migration guide](https://docs.google.com/document/d/1ssFEfX1jL7YiGD0_ZyJc1awofjQRJeRlABFmXk3E3ws) to start using the new ["NAT gateway"](https://cloud.yandex.com/en-ru/docs/vpc/operations/create-nat-gateway) feature after Deckhouse release 1.42 is installed in an existing cluster.
```changes
section: candi
type: feature
summary: Migrate …
```
> [candi] Migrate to NAT gateway in yandex cloud Standard layout

- ee/modules/030-cloud-provider-openstack/images/cinder-csi-plugin/werf.inc.yaml
- ee/modules/030-cloud-provider-openstack/openapi/config-values.yaml
- ee/modules/030-cloud-provider-openstack/openapi/doc-ru-config-values.yaml
- ee/modules/030-cloud-provider-openstack/openapi/values.yaml
- ee/modules/030-cloud-provider-openstack/template_tests/module_test.go
- ee/modules/030-cloud-provider-openstack/templates/cloud-controller-manager/secret.yaml
Backported fix for OpenStack with version older than 3.34, in some clouds (like VK cloud) persistent volume provisioning didn't worked.
Fix #3129 
Provisioning works in OpenStack with API versions lower then 3.34.
```changes
type: fix
summary: Backported fix for OpenStack with version older than 3.34, for compatibility with some clouds (e.g. VK cloud).
```
> [cloud-provider-openstack] Added patch for old OpenStack versions support

- ee/modules/110-istio/templates/kiali/configmap.yaml
exclude `upmeter-probe-namespace-.*` from kiali
get rid of upmeter noise
`upmeter-probe-namespace-.*` namespace is no longer displayed in the kiali dashboard
```changes
section: istio
type: fix
summary: exclude `upmeter-probe-namespace-.*` from kiali
```
> [istio] exclude upmeter-probe-namespace-.* from kiali

- modules/140-user-authz/docs/USAGE.md
- modules/140-user-authz/docs/USAGE_RU.md
Fix the Usage page in the user-authz module (incorrect secret name in examples).
```changes
type: fix
summary: Fix the Usage page in the documentation.
```
> [docs][user-authz] Fix the Usage page

- modules/150-user-authn/hooks/generate_crowd_basic_auth_proxy_cert.go
Fixed generate_crowd_basic_auth_proxy_cert.go hook
In a situation where the deckhouse was unable to rotate the certificate, previously it was necessary to restart the deckhouse, now it is enough to remove the expired certificate
```changes
type: fix
summary: Fixed generate_crowd_basic_auth_proxy_cert.go hook
```
> [user-authn] fix crowd proxy cert generator

- modules/099-ceph-csi/templates/cephfs/secret.yaml
- modules/099-ceph-csi/templates/cephfs/storage-classes.yaml
- modules/099-ceph-csi/templates/rbd/secret.yaml
- modules/099-ceph-csi/templates/rbd/storage-classes.yaml
Allow non-admin ceph account for cephfs.
It was necessary to use an account named "admin" for cephfs.
```changes
section: ceph-fs
type: fix
summary: Allow non-admin ceph account for cephfs
```
> [ceph-csi] Allow non-admin ceph account for cephfs

- ee/modules/110-istio/templates/ingress-gateway-controller/namespace.yaml
added kube-rbac-proxy CA certificate to d8-ingress-istio
To fix matrix tests
Matrix tests should not fail
```changes
section: istio
type: fix
summary:  added kube-rbac-proxy CA certificate to d8-ingress-istio
```
> [istio] add kube-rbac-proxy CA certificate to d8-ingress-istio

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
Added docs: 
- How to turn a multi-master cluster into a single-master cluster and vice verse.
- How to change the multi-master cluster OS image.
Users have to know how to do it!
```changes
type: chore
summary: Added docs about how to turn a multi-master cluster into a single-master cluster and vice versa, and about how to change OS image in a multi-master cluster.
```
> [control-plane-manager] Docs about how to migrate from multi-master to single-master

- modules/015-admission-policy-engine/hooks/ensure_native_crds.go
For native crds
Native crds were moved to the internal dir. They are not installed by default
```changes
type: fix
summary: Add ensure_crds hook for native gatekeeper CRDs.
```
> [admission-policy-engine] Create one more ensure_crds hook

- modules/340-monitoring-deckhouse/monitoring/prometheus-rules/deckhouse.yaml
Add alert for the `deckhouse_kubernetes_client_watch_errors_total` metric.
This alert is our attempt to detect the correlation between the faulty snapshot invalidation and apiserver connection errors, especially for the handle-node-template hook in the node-manager module.
```changes
section: deckhouse-monitoring
type: fix
summary: Add alert for the `deckhouse_kubernetes_client_watch_errors_total` metric.
```
> [deckhouse-monitoring] alert for watch errors

- modules/040-node-manager/monitoring/prometheus-rules/early-oom.tpl
- modules/300-prometheus/monitoring/prometheus-rules/emptydir.yaml
It's not allowed in madison to group alerts with themselves (causes CouldNotCreateEvent errors in the alert manager), so we need to use different group name.
> It's not allowed to group alerts with themselves

- modules/150-user-authn/hooks/generate_crowd_basic_auth_proxy_cert.go
Hardcode paths for client ca and key in the script for cfssl
If the kube-apiserver has many arguments, the `ps aux` command may cut some of them and produce an invalid argument on the script input.
We could replace it with `ps auxww', but since this crowd proxy only works on deckhouse clusters, we can hardcode the paths
```changes
type: fix
summary: Fix crowd proxy certificate generation.
```
> [user-authn] Fix crowd proxy cert generation

- modules/002-deckhouse/hooks/check_deckhouse_release_test.go
- werf.yaml
Make backquotes in the changelog YAML render in DeckhouseRelease resource.
How it looks now:
```yaml
upmeter:
- pull_request: https://github.com/deckhouse/deckhouse/pull/1729
summary: The  and  options are deprecated. Consider using the  module.
```
It only fixes unrendered backquotes in the DeckhouseRelease resource. So the text will be generally readable.
In new DeckhouseRelease resource, the changelog will be rendered as with backquotes.
```yaml
upmeter:
- pull_request: https://github.com/deckhouse/deckhouse/pull/1729
summary: The `auth.username` and `auth.password` options are deprecated.
Consider using the `user-authn` module.
```
```changes
type: fix
summary: Fixed unrendered backquotes in the …
```
> [deckhouse] Fix backquotes rendering in DeckhouseRelease changelog

- modules/302-vertical-pod-autoscaler/templates/admission-controller/mutatingwebhookconfiguration.yaml
Setting admissionReviewVersions to v1 in mutating webhook.
v1beta1 isn't supported by the new vpa controller.
Mututating webhook work in any k8s setup.
```changes
section: vpa
type: fix
summary: Setting admissionReviewVersions to v1 in mutating webhook.
```
> [vpa] Setting admissionReviewVersions to v1 in mutating webhook

- ee/modules/110-istio/images/api-proxy/main.go
- ee/modules/110-istio/templates/kiali/rbac-for-us.yaml
- ee/modules/110-istio/templates/multicluster/api-proxy/deployment.yaml
Replace CA for ingress validation for api-proxy, fix kiali `ClusterRole`
CA changed in this pr: https://github.com/deckhouse/deckhouse/pull/3288, we need to use it, otherwise it can broke istio multicluster.
Istio api-proxy will use valid CA for validation
```changes
section: istio
type: fix
summary: Replace CA for ingress validation for api-proxy, fix kiali `ClusterRole`
impact: low
```
> [istio] fix api-proxy ca

- global-hooks/migrate/migrate_cluster_configuration.go
- global-hooks/migrate/migrate_cluster_configuration_test.go
- helm_lib/templates/_envs_for_proxy.tpl
Fixes in cluster configuration migration process and proxy template (if installed in EKS cluster, the absence of proxy settings will be ignored)
Installation in EKS cluster fails due to the lack of a secret with proxy settings. This fix will allow Deckhouse to ignore secret's absence.
Deckhouse installation in Amazon EKS now will complete successfully.
```changes
type: fix
summary: Fixes in cluster configuration migration process and proxy template for EKS cluster installation.
```
> [global] fixes in cluster configuration migration process and proxy template for EKS cluster installation

- modules/013-helm/hooks/metrics.go
Set flag explicitly
Avoid reading the docs every time when we met this hook. This does not change hook behavior
```changes
section: helm
type: chore
summary: Set resourceVersionMatch flag for secret listing explicitly
```
> [helm] set resource version match explicitly

- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/pkg/operations/bootstrap.go
- Remove unnecessary process wrap in deckhouse install step on `dhctl bootstrap-phase install-deckhouse` command.
- Rename `Waiting for additional Nodes` -> `Waiting for Node Groups are ready`
- Rename `Create master NodeGroup` -> `Bootstrap additional master nodes`
UI bug fixes 
```changes
section: dhctl
type: chore
summary: Fix some small user interface bugs
```
> [dhctl] Fix some small user interface bugs

- modules/150-user-authn/images/dex/patches/oidc-ca-insecure.patch
It fixes the problem with an invalid x509 certificate error that occurred on exchanging a code
```changes
type: fix
summary:  Fix insecure OIDC Ca patch.
```
> [user-authn] Fix insecure oidc ca patch

- candi/control-plane-kubeadm/patches/kube-controller-manager.yaml.tpl
Explicitly set seccompProfile type to Unconfined
Kubeadm sets seccomp to [RuntimeDefault](https://kubernetes.io/docs/tutorials/security/seccomp/#enable-the-use-of-runtimedefault-as-the-default-seccomp-profile-for-all-workloads) for kube-controller-manager in Kubernetes clusters > 1.21:
```
securityContext:
seccompProfile:
type: RuntimeDefault
```
We still have Docker with different runc versions. And we have problem with ceph rbd in-tree using runc version <= `1.0.0-rc92`:
```
Thread::try_create(): pthread_create failed with error 1./src/common/Thread.cc: In function 'void Thread::create(const char*, size_t)' thread 7f07ccea9340 time 2022-12-27T18:42:01.846784+0000
./src/common/Thread.cc: 165: FAILED ceph_assert(ret == 0) …
```
> [candi] Temporary disable seccomp for kube-controller-manager

- modules/402-ingress-nginx/hooks/order_certificates.go
- modules/402-ingress-nginx/hooks/order_certificates_test.go
Change certificate expiry time to 1 year
We have to reload an ingress when certificate is change. And we have CA certificate is valid for 10 years. 
We can recreate certificate 1 year before expiration to be sure that certificate will be reloaded inside the pod
```changes
type: fix 
summary: Change certificate expiry time
```
> [ingress-nginx] change certificate expiry date

- modules/041-linstor/templates/linstor-csi/linstorcsidriver.yaml
Fix regression introduced by https://github.com/deckhouse/deckhouse/pull/3193
Now the `{{ .registry }}` expands to map instead of string. The template wasn't updated for linstor-csi custom resource. This PR fixes that.
Linstor CSI plugin can't be deployed
Linstor CSI deployed
```changes
type: fix
summary: fix deckhouse registry regression
```
> [linstor] fix deckhouse registry regression

- testing/cloud_layouts/script.sh
Fix incorrect user set for Yandex.Cloud run.
E2e tests for Yandex.Cloud do not work.
```changes
type: fix
summary: Fix e2e tests for Yandex Cloud
```
> [testing] Fix e2e tests for Yandex Cloud

- modules/040-terraform-manager/images/base-terraform-manager/werf.inc.yaml
Rebuild base-terraform-manager image only after changes in `candi/openapi` folder.
Speed up Deckhouse builds and development.
```changes
type: chore
summary: Rebuild image only if openapi spec is changed
```
> [terraform-manager] Rebuild images only if openapi spec is changed

- docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA.md
- docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA_RU.md
Added note about using Deckhouse with kind on Windows.
When using kind on Windows, Kubernetes Service with `sessionAffinity: ClientIP`  will not be accessible. This feature may cause Prometheus/Grafana to be unavailable.
```changes
section: docs
type: fix
summary: Added note about using Deckhouse with kind on Windows.
```
> [docs][gs][kind] Add note about using d8 with kind on Windows

- .github/stale.yml
There is a special label to reconsider the issue. Let's use it for 
```changes
section: ci
type: feature
summary: Make stale bot to put issues to the triage queue.
```
> Make stale bot to put issues to the triage queue

- docs/documentation/_includes/revision_comparison_detail_table.liquid
- docs/site/css/docs.scss
Fix module status label in the comparison table.
Fix #3478
```changes
section: docs
type: fix
summary: Fix module status label in the comparison table.
```
> [docs] Fix module status label in the comparison table

- ee/modules/140-user-authz/images/webhook/web/server.go
- ee/modules/140-user-authz/templates/webhook/configmap-control-plane-configurator.yaml
- ee/modules/140-user-authz/templates/webhook/daemonset.yaml
- ee/modules/140-user-authz/templates/webhook/secret.yaml
- go_lib/hooks/tls_certificate/internal_tls.go
- modules/140-user-authz/hooks/generate_webhook_certs.go
- modules/140-user-authz/hooks/generate_webhook_certs_test.go
- modules/140-user-authz/openapi/values.yaml
- modules/140-user-authz/template_tests/module_test.go
Switch to the library wrapper for TLS certificate handling.
Ensures that the certificate is always valid.
- The certificate is always valid in the authn webhook
- The certificate fields migrate to common schema.
```changes
type: fix
summary: Enabled TLS certificate rotation for the authn webhook
```
> [user-authz]: Re-generate certificate automatically

- modules/402-ingress-nginx/docs/EXAMPLES_RU.md
Signed-off-by: krakazyabra <pronin.egor@gmail.com>
Documentation's typo was fixed in "Example for Bare metal" label (RU)
Because it is typo mistake :)
Typo was fixed in "Example for Bare metal" label
```changes
section: docs
type: fix
summary: Fixed typo on the site.
```
> [docs] Fixed typo in the "Example for Bare metal" page

- ee/modules/350-node-local-dns/templates/configmap.yaml
Switched from "immediate" to "verified" stale_cache mode.
Some programs resolve a Service name only once and then attempt to connect to it without retrying DNS resolution. stale_cache's `immediate` mode results in node-local-dns sending a response (granted, with TTL 0) to the client, and only then attempting to refresh the cache. In `verified` mode, node-local-dns will attempt to first get a fresh response and only send the stale one to the client if the refresh fails.
https://coredns.io/plugins/cache/
https://github.com/coredns/coredns/blob/66f2ac7568ccb0178cc9ce6dbd7320bcd3428d64/plugin/cache/handler.go#L43-L66
`stale_cache` always attempts to send a fresh Resource Record to the client.
```changes
type: fix
summary: Switched stale cache behavior from `immediate` …
```
> [node-local-dns] Switch to "verified" mode

- modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
Fixing D8UpmeterProbeGarbageNamespaces alert from upmeter module.
There shouldn't be false alerts.
There aren't false alert.
```changes
type: fix
summary: Fixing D8UpmeterProbeGarbageNamespaces alert from upmeter module.
```
> [upmeter] Fixing D8UpmeterProbeGarbageNamespaces alert

- docs/site/_data/getting_started/data.yaml
- docs/site/_includes/getting_started/global/partials/NOTICES.liquid
Added note about working through proxy.
The settings for working through a proxy server have [changed](https://github.com/deckhouse/deckhouse/pull/3185) in Deckhouse 1.42, but the getting start guide currently supports Deckhouse 1.41.
Ref: #3185 
```changes
section: docs
type: chore
summary: Added note about working through proxy.
```
> [docs][getting-started] Add note about working through proxy.

- ee/modules/007-registrypackages/images/containerd-alteros/scripts/install
- ee/modules/007-registrypackages/images/containerd-redos/scripts/install
- ee/modules/007-registrypackages/images/docker-alteros/scripts/install
- ee/modules/007-registrypackages/images/docker-redos/scripts/install
- ee/modules/007-registrypackages/images/kubeadm-alteros/scripts/install
- ee/modules/007-registrypackages/images/kubeadm-redos/scripts/install
- ee/modules/007-registrypackages/images/kubectl-alteros/scripts/install
- ee/modules/007-registrypackages/images/kubectl-redos/scripts/install
- ee/modules/007-registrypackages/images/kubelet-alteros/scripts/install
- ee/modules/007-registrypackages/images/kubelet-redos/scripts/install
- ee/modules/007-registrypackages/images/kubernetes-cni-alteros/scripts/install
- ee/modules/007-registrypackages/images/kubernetes-cni-redos/scripts/install
Allow downgrading rpms from registrypackages in any rpm-distro.
Extending https://github.com/deckhouse/deckhouse/pull/3353.
```changes
type: fix
summary: Allow downgrading rpms from registrypackages in any rpm-distro.
```
> [registrypackages] Allowing RPM downgrades for any distro

- modules/300-prometheus/templates/trickster/configmap.yaml
Fixed token-based authentication between trickster and prometheus.
The trickster didn't set Authorization header properly and couldn't set it if the original connection had no the header.
It is possible to make request to trickster without a token but with client cert.
```changes
section: protmetheus
type: fix
summary: Fixed token-based authentication between trickster and prometheus.
```
> [prometheus] Fix trickster authentication

- modules/300-prometheus/template_tests/prometheus_cr_test.go
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Fix indent in Prometheus CR template.
Deckhouse gets stuck on ValidationError
```
remoteWrite:
- url: https://victoriametrics-test.domain.com/api/v1/write
tlsConfig:
insecureSkipVerify: true
1. ModuleRun:main:prometheus:Kubernetes-Change-ModuleValues:failures 221:helm upgrade failed: error validating "": error validating data: ValidationError(Prometheus.spec.remoteWrite[0]): unknown field "insecureSkipVerify" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite
```
```changes
type: fix
summary: Fix remoteWrite tlsConfig render
```
> [prometheus] Fix remoteWrite tlsConfig render

- .github/workflow_templates/dispatch-slash-command.yml
- .github/workflows/dispatch-slash-command.yml
The right way is to give slash commands to the collabrator instead of the contributor. Why? 
During the experiments it turned out that 
Member is a member of the github organization and the organization is public (here https://github.com/orgs/deckhouse/people)
A Collaborator is a member of github and the organization is private (here https://github.com/orgs/deckhouse/people)
Contributor is a person who is not a member of github, but has contributed to the repository.
Members with private membership in organization can not run abortion of failed e2e.
```changes
section: ci
type: fix
summary: Allow to exec slash command for collaborator instead contributor
```
> [ci] Allow to exec slash command for collaborator instead contributor

- modules/021-cni-cilium/templates/agent/flowschema.yaml
Add flowschema to queue list requests from agent pods
Restarting the Kubernetes API results in recreating the cilium agent api watches and massive list requests.
```changes
type: chore
summary: add flowschema to queue list requests from agent pods
```
> [cni-cilium] add flowschema to queue list requests from agent pods

- modules/007-registrypackages/images/kubernetes-cni-centos/scripts/install
- modules/007-registrypackages/images/kubernetes-cni-centos/scripts/uninstall
- modules/007-registrypackages/images/kubernetes-cni-centos/werf.inc.yaml
Install `flannel` 0.8.7 binary to CentOS due to flannel binary missing in `kubernetes-cni` 1.1.1.
Flannel was moved to sepatate repo in https://github.com/containernetworking/plugins/pull/633, so this PR is intended as temporary fix.
Changes were tested manually in paused e2e cluster.
Update to K8s 1.23 broken on CentOS-based systems due to this issue.
Update to K8s 1.23 works on CentOS-based systems.
```changes
type: fix
summary: Install flannel 0.8.7 binary to CentOS due to flannel binary missing in kubernetes-cni 1.1.1
```
> [registrypackages] Install flannel 0.8.7 binary to CentOS due to flannel binary missing in kubernetes-cni 1.1.1

- docs/documentation/_plugins/openapi.rb
Show the deprecated status of the OpenAPI parameter if the `deprecated` option is set.
Currently, the deprecated status of a parameter on the site is only shown if the `x-doc-deprecated` option of the parameter is true. But there are parameters with the `deprecated` option also. 
```changes
section: docs
type: fix
summary: Show the deprecated status of the OpenAPI parameter if the `deprecated` option is set.
```
> [docs] Show deprecated status in the `deprecated` option is set

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/ebpf-exporter.yaml
- Add one more recording rule `oom_kills:normalized` with label_replace for cgroupfs
It works for ebpf_exporter_oom_kills metrics from regular pods ooms
```
ebpf_exporter_oom_kills{cgroup_path="/sys/fs/cgroup/memory/kubepods/burstable/pod50b98f22-1095-48bf-804d-c21da2013bb6", container="kube-rbac-proxy", global_oom="0", instance="192.168.199.70:9434", job="ebpf-exporter", node="k-aksenov-master-0", tier="cluster"}
kube_pod_container_info{container="stress-ng", container_id="containerd://d48ea9823470abbf4b68e846fd4d20837abab32db09984c5fae67669d4af7737", image="docker.io/alexeiled/stress-ng:latest", image_id="docker.io/alexeiled/stress-ng@sha256:91f1313a67e3c8c23f3c75855019d01c4a43e2f872b099f720047f03309d8ad4", image_spec="alexeiled/stress-ng", instance="kube-state-metrics.d8-monitoring.svc. …
```
> [monitoring-kubernetes] Attempt to fix oom_kills:normalized for cgroupfs driver

- modules/150-user-authn/images/dex/patches/oidc-ca-insecure.patch
https://github.com/dexidp/dex/pull/2781
```changes
type: fix
summary: OIDC insecure userInfo endpoint.
```
> [user-authn] OIDC insecure userInfo endpoint

- docs/documentation/Gemfile.lock
- docs/site/Gemfile.lock
Jekyll 3.9.2 builds 5 times slower than 3.9.1.
```changes
section: ci
type: chore
summary: Use jekyll 3.9.1
```
> [ci] Use jekyll 3.9.1

- modules/460-log-shipper/docs/EXAMPLES.md
- modules/460-log-shipper/docs/EXAMPLES_RU.md
- modules/460-log-shipper/hooks/internal/vector/destination/splunk.go
- modules/460-log-shipper/hooks/testdata/file-to-splunk/manifests.yaml
- modules/460-log-shipper/hooks/testdata/file-to-splunk/result.json
* Automatically add indexed fields 
* Do not encode them in original message
* Always set TLS settings
Without this changes, users only see messages in Splunk without Kubernetes metadata attached
```changes
type: feature
summary: Add indexes fields for Splunk destination.
```
> [log-shipper] Add indexes fields for Splunk destination

- helm_lib/templates/_module_image.tpl
We have global values which describes registry:
```yaml
global:
modulesImages:
registry:
base:
path:
address:
CA:
scheme:
dockercfg:
```
In this PR we add ability to use module registry settings which have same structure as global. This ability is needed for external modules (#3465).
```changes
section: helm-lib
type: feature
summary: added support of module registry settings
```
> [helm-lib] added support of module registry settings

- modules/460-log-shipper/hooks/internal/composer/composer.go
The type field can hint at how many sources and destinations of each type are used and find the most popular combinations.
```changes
type: feature
summary: Add type field for telemetry metrics
```
> [log-shipper] Add type field for telemetry metrics

- candi/version_map.yml
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.21/001-lock-route-table-operations.patch
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.21/README.md
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.22/001-lock-route-table-operations.patch
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.22/README.md
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.23/001-lock-route-table-operations.patch
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.23/README.md
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.24/001-lock-route-table-operations.patch
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.24/README.md
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/werf.inc.yaml
1. Introduced locking to Route Table operations, so that only one operation on a route table can run simultaneously.
2. Disabled useless Route Table updates on ListRoutes().
Yandex.Cloud introduced harsher API call-limits earlier this year.
Route Table operations are no longer locked on each other. Also, they do not hit the API call limit.
```changes
type: fix
summary: |
Changes to CCM:
1. Introduced locking to Route Table operations, so that only one operation on a route table can run simultaneously.
2. Disabled useless Route Table updates on ListRoutes().
```
> [cloud-provier-yandex] Lock route table operations

- dhctl/pkg/kubernetes/actions/converge/converge.go
Immediately stop converge if node converge was failed
We should stop converge nodes if one node converge was failed for prevent break all nodes on nodegroup.
N/A
```changes
section: dhctl
type: chore
summary: Add comment about returning errors during converge
```
> [dhctl] Add comment about returning errors during converge

- modules/470-chrony/docs/CONFIGURATION.md
- modules/470-chrony/docs/CONFIGURATION_RU.md
- modules/470-chrony/images/chrony/start.sh
- modules/470-chrony/template_tests/module_test.go
- modules/470-chrony/templates/daemonset.yaml
Adding a dot to the end of each NTP server address to avoid resolve problems. Allowing correction of large time difference.
Incorrect DNS resolve is possible in case of wildcard domains in search. In case of a large difference in local time with the world time correction may not work. This PR corrects both situations.
Chrony correct work.
```changes
type: fix
summary: Adding a dot to the end of each NTP server address to avoid resolve problems. Allowing correction of large time difference.
```
> [chrony] Adding a dot to the end of each NTP server address to avoid resolve problems. Allowing correction of large time difference

- helm_lib/templates/_node_affinity.tpl
- modules/041-linstor/templates/linstor-affinity-controller/deployment.yaml
- modules/041-linstor/templates/linstor-controller/linstorcontroller.yaml
- modules/041-linstor/templates/linstor-csi/linstorcsidriver.yaml
- modules/041-linstor/templates/linstor-scheduler/deployment.yaml
- modules/041-linstor/templates/piraeus-operator/deployment.yaml
- modules/041-linstor/templates/spaas/deployment.yaml
Add additional system tolerations to LINSTOR pods
When DRBD has problems linstor ha-controller adds taint to the nodes, that prevents linstor pods get scheduled on this node.
The piraeus linstor pods will be deployed with additional tolerations:
```diff
tolerations:
- key: dedicated.deckhouse.io
operator: Equal
value: "linstor"
- key: dedicated.deckhouse.io
operator: Equal
value: "system"
+       - key: drbd.linbit.com/lost-quorum
+       - key: drbd.linbit.com/force-io-error
+       - key: drbd.linbit.com/ignore-fail-over
```
```changes
type: fix
summary: Tolerate DRBD problems.
```
> [linstor] tolerate drbd problems

- modules/041-linstor/templates/linstor-controller/linstorcontroller.yaml
- modules/041-linstor/templates/linstor-node/linstorsatelliteset.yaml
Specify the default container for `kubectl exec`
When user executes linstor command it shows that command executed in first container.
No warning when executing linstor command
```changes
type: chore
summary: Specify the default container for kubectl.
```
> [linstor] specify default container for kubectl

- dhctl/cmd/dhctl/main.go
- dhctl/pkg/app/app.go
- werf.yaml
Add version file to install image and dhctl command.
New users want's to have easy method to determine installer version.
File with version in image and built-in version string for dhctl
```changes
section: dhctl
type: feature
summary: Add version in dhctl image
```
> [dhctl] Add version in dhctl image

- docs/site/_includes/getting_started/bm-private/partials/config.yml.ce.inc
- docs/site/_includes/getting_started/bm-private/partials/ingress-nginx-controller.yml.inc
- docs/site/_includes/getting_started/bm-private/partials/user.yml.inc
- docs/site/_includes/getting_started/global/partials/NOTICES.liquid
- docs/site/_includes/getting_started/global/partials/getting-started-setup.js.liquid
- docs/site/_includes/getting_started/global/partials/select_revision.html.liquid
- docs/site/_includes/getting_started/global/step_cluster_setup.html
- docs/site/_includes/getting_started/global/step_cluster_setup_ru.html
- docs/site/js/getting-started-private.js
**Have to be merged after v 1.42 becomes a stable version.**
Update the guide for installing in a private environment according to [changes](https://github.com/deckhouse/deckhouse/pull/3185) in `v1.42`.
The settings for working through a proxy server have changed in Deckhouse 1.42 ([issue](https://github.com/deckhouse/deckhouse/pull/3185)).
```changes
section: docs
type: chore
summary: Update the guide for installing in a private environment according to [changes](https://github.com/deckhouse/deckhouse/pull/3185) in `v1.42`.
```
> [docs][getting started] Update guide for installing in a private environment

- modules/021-cni-cilium/openapi/config-values.yaml
- modules/021-cni-cilium/openapi/doc-ru-config-values.yaml
- modules/021-cni-cilium/openapi/openapi-case-tests.yaml
- modules/021-cni-cilium/templates/configmap.yaml
Add labels config value.
https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/#limiting-identity-relevant-labels
This PR adds config parameter to limit the set of identity-relevant labels to avoid frequent creation of new security identities in large environments.
```changes
type: feature
summary: Added Deckouse config value for cilium entity labels
impact: Cilium pods should be restarted.
```
> [cni-cilium] add labels config value

- dhctl/pkg/kubernetes/client/lease-lock.go
Fixing some cli messages.
There was misunderstanding.
```changes
section: dhctl
type: fix
summary: Fixing some cli messages.
```
> [dhctl] Fixing some cli messages

- ee/modules/110-istio/template_tests/module_test.go
- ee/modules/110-istio/templates/control-plane/iop.yaml
Added control of an environment variable for obtaining cloud provider metadata for istio proxy
Automatic cloud provider detection must be disabled to avoid unwanted network interaction
For istio-proxy, getting cloud provider metadata is available for: azure, aws, gcp for other cases - disabled.
```changes
section: istio
type: fix
summary: Added control of an environment variable for obtaining cloud provider metadata for istio proxy
```
> [istio] add CLOUD_PROVIDER env var for istio proxy

- global-hooks/deckhouse-config/startup_sync.go
- go_lib/deckhouse-config/config_map_section.go
- go_lib/deckhouse-config/conversion/chain.go
- go_lib/deckhouse-config/conversion/chain_test.go
- go_lib/deckhouse-config/initial_config_loader.go
- go_lib/deckhouse-config/initial_config_loader_test.go
- go_lib/deckhouse-config/validator.go
- modules/003-deckhouse-config/hooks/sync_configmap.go
- Run JSON marshal-unmarshal for latest settings to cast types as in converted settings.
This PR fixes panic in MultiplyOfInt during settings validation. It was impossible to configure float parameters.
Should not panic with "runtime error: integer divide by zero" when set integer number for field with float multipleOf.
OpenAPI example:
```
sampling:
type: number
minimum: 0.01
maximum: 100.0
multipleOf: 0.01
```
And creating this ModuleConfig:
```
metadata:
name: istio
spec:
enabled: true
settings:
...
tracing:
...
sampling: 100.0
```
```changes
type: fix
summary: Support integer numbers for settings constrained with the float number in `multipleOf`.
```
> [deckhouse-config] fix: Support integer number for settings constrained with the float number in multipleOf

- modules/300-prometheus/monitoring/prometheus-rules/prometheus-storage.yaml
There is an issue with PrometheusLongtermRotatingEarlierThanConfiguredRetentionDays alert caused by incorrect `d8_prometheus_longterm_storage_retention_days` metric name.
Issue is probably a typo because above there is a correct implementation for `main` Prometheus, and correct metric name [is found](https://github.com/deckhouse/deckhouse/commit/57dce3ca06406e2d240db7cb491a84defb8b7236#diff-e4f26acbfd220e1b5552809e349adc065510c04197ea7051d4354477a7d9c349R46) in the same commit.
This issue causes `longterm` Prometheus to not alert about rotating earlier than configured retention.
Prometheus will alert about described condition.
```changes
type: chore
summary: [prometheus] Fix typo in metrics name for …
```
> [prometheus] Fix typo in metrics name for PrometheusLongtermRotatingEarlierThanConfiguredRetentionDays

- modules/013-helm/hooks/metrics.go
- modules/013-helm/hooks/metrics_test.go
- modules/013-helm/monitoring/prometheus-rules/deprecated-versions.yaml
Change timing and batch size for deprecated resources checks
Spread the load to the api-server. Run this check once per hour and make a 3 second pause between secret fetches. Also change batch size to 10 secrets at once. This will make the load more smooth and we will avoid huge load peaks.
```changes
section: helm
type: fix 
summary: Change deprecated resources check parameters. Make the load more uniform.
```
> [helm] change intervals and batch size

- modules/002-deckhouse/hooks/internal/updater/notification.go
- modules/002-deckhouse/hooks/internal/updater/updater.go
- modules/002-deckhouse/hooks/update_deckhouse_image.go
- modules/002-deckhouse/hooks/update_deckhouse_image_test.go
- modules/002-deckhouse/openapi/config-values.yaml
- modules/002-deckhouse/openapi/doc-ru-config-values.yaml
- modules/002-deckhouse/openapi/openapi-case-tests.yaml
Add authentication settings to the update notification hook.
For the inner Flant infrastructure, we need to be able to send update notifications to the clients
from their clusters.
The update notification hook can be configured to send  authenticated notifications requests.
```changes
type: feature
summary: Added authentication settings to the update notification hook
```
> [deckhouse]: Add auth to update notification

- docs/documentation/_plugins/openapi.rb
- docs/site/css/components/_resources.scss
Use the full parameter path in an OpenAPI spec instead of only name.
E.g. `storageClass.provision.iops` instead of `iops`. It will help to better understand the scope of a parameter and help to avoid stupid mistakes.
```changes
section: docs
type: feature
summary: Display the full parameter path in OpenAPI spec.
```
> [docs] Use the full parameter path in OpenAPI spec

- modules/600-secret-copier/hooks/handler.go
Add annotation to a copied secret
It's useful for debug purposes to have an annotation when secret was created/update by secret-copier
```changes
type: chore
summary: Add annotation with create/update timestamp to copied secrets
```
> [secret-copier] Add annotations with timestamp

- modules/041-linstor/hooks/metrics.go
- modules/041-linstor/hooks/metrics_test.go
Collect general statistics
We need to understand current usage of linstor module
A new metrics appear in cluster: 
```
d8_telemetry_linstor_enabled
d8_telemetry_linstor_satellites
d8_telemetry_linstor_storage_pools
d8_telemetry_linstor_resource_definitions
d8_telemetry_linstor_snapshot_definitions
d8_telemetry_linstor_resources
```
```changes
section:  linstor
type: feature
summary: Collect general statistics
```
> [linstor] Collect general statistics

- candi/bashible/bashible.sh.tpl
- candi/bashible/common-steps/node-group/050_configure_and_start_containerd.sh.tpl
- modules/040-node-manager/templates/bashible/rbac-for-us.yaml
- testing/matrix/linter/rules/roles/placement.go
Fix error in bb-event-error-create bashible function.
1. When bashible tries to create an event, we get an error because we do not have access from system:nodes group to events.k8s.io api.
2. If cluster in bootstrapping state, we cannot have working API to send events, so we simply suppress event creating errors to prevent bashible fail. 
```changes
section: candi
type: fix
summary: Fix error in bb-event-error-create bashible function.
```
> [bashible] fix bb-event-error-create

- ee/modules/110-istio/images/proxyv2-v1x12x6/Dockerfile
- ee/modules/110-istio/images/proxyv2-v1x12x6/iptables-wrapper-installer.sh
- ee/modules/110-istio/images/proxyv2-v1x13x7/Dockerfile
- ee/modules/110-istio/images/proxyv2-v1x13x7/iptables-wrapper-installer.sh
Using iptables-wrapper-installer.sh in Istio proxy images to solve iptables-nft vs iptables-legacy issue.
On the centos-powered nodes init-container couldn't set up iptables rules. There was an error:
```
2023-01-18T17:17:47.706257Z	info	Running command: iptables-restore --noflush /tmp/iptables-rules-1674062267706031953.txt694377717
2023-01-18T17:17:47.728011Z	error	Command error output: xtables resource problem: line 24: TABLE_ADD failed (No such file or directory): table nat
line 24: TABLE_ADD failed (No such file or directory): table nat
line 24: TABLE_ADD failed (No such file or directory): table nat
line 24: TABLE_ADD failed (No such file or directory): table nat
line 24: TABLE_ADD failed (No such file or directory): table nat
line 24: TABLE_ADD failed (No such file or directory): …
```
> [istio] using iptables-wrapper-installer.sh in proxy images

- modules/021-cni-cilium/monitoring/prometheus-rules/agent.yaml
Removed useless CiliumAgentControllersRunsFailing.
The Prometheus gauge is not returned to zero once an error condition clears. Perhaps, we'll take a look at this bug once we update to a fresher version of Cilium
Alert no longer triggers.
```changes
type: fix
summary: Removed CiliumAgentControllersRunsFailing alert
```
> [cni-cilium] Removed useless alert

- ee/modules/350-node-local-dns/templates/daemonset.yaml
Add label for node-local-dns daemonset to fix cilium connectivity tests
Cilium connectivity tests must work properly
Cilium connectivity tests work properly
```changes
type: fix 
summary: Add label for node-local-dns daemonset to fix cilium connectivity tests
```
> [node-local-dns] add labels to fix cilium connectivity tests

- candi/bashible/common-steps/all/091_set_virtualization_type.sh.tpl
- candi/bashible/common-steps/node-group/069_start_kubelet.sh.tpl
Refactor start_kubelet step to avoid 60 sec pause on cloud node bootstrap.
When we bootstrap cloud nodes, on the first bashible run we got 60 sec pause on kubelet restart.
```changes
section: candi
type: fix
summary: refactor start_kubelet step
```
> [bashible] refactor start_kubelet step

- modules/041-linstor/crds/piraeus.linbit.com_linstorcsidrivers.yaml
- modules/041-linstor/images/piraeus-operator/patches/README.md
- modules/041-linstor/images/piraeus-operator/patches/csi-controller-strategy.patch
- modules/041-linstor/templates/linstor-affinity-controller/deployment.yaml
- modules/041-linstor/templates/linstor-csi/linstorcsidriver.yaml
- modules/041-linstor/templates/linstor-scheduler/deployment.yaml
- modules/041-linstor/templates/piraeus-operator/deployment.yaml
- modules/041-linstor/templates/spaas/deployment.yaml
This PR specifies deployment strategy for linstor components 
Includes upstream fix:
-   https://github.com/piraeusdatastore/piraeus-operator/pull/395
fixes https://github.com/deckhouse/deckhouse/issues/3074
```changes
type: fix
summary: fix rollingUpdate with two system nodes
```
> [linstor] fix rollingUpdate with two system nodes

- modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/control-plane-status.json
Replaced `$__interval` with `$__range` variable so that the table properly displays results over the whole time period.
Interval calculation displayed inaccurate results since table does not display continuous change.
Tables have proper results.
```changes
type: fix
summary: Replaced `$__interval` with `$__range` variable so that the table properly displays results over the whole time period
```
> [monitoring-kubernetes-control-plane] Fixed "Control Plane Status" dashboard

- modules/460-log-shipper/hooks/internal/vector/destination/kafka.go
- modules/460-log-shipper/hooks/internal/vector/destination/vector.go
- modules/460-log-shipper/hooks/internal/vector/transform/extra_fields.go
- modules/460-log-shipper/hooks/internal/vrl/elasticsearch.go
- modules/460-log-shipper/hooks/testdata/file-to-kafka-tls/result.json
- modules/460-log-shipper/hooks/testdata/file-to-kafka/result.json
* Make log-shipper sending whole json message with metadata to Kafka destination
* Fix some TODO messages
Closes https://github.com/deckhouse/deckhouse/issues/3623
```changes
type: fix
summary: Make log-shipper-agents sending whole JSON message with metadata to Kafka destination.
```
> [log-shipper] Send metadata to Kafka

- deckhouse-controller/entrypoint.sh
- werf.yaml
Added bash wrapper, allowing processing of USR1, USR2 signals, which is used to restart the deckhouse child process.
This supervisor is required for the use of 3rd party modules.
By receiving USR1, USR2 the deckhouse child process will receive a TERM signal and be restarted.
```changes
type: feature
summary: Added bash wrapper for handling USR signals.
```
> [deckhouse] add bash wrapper for handling USR signals

- go_lib/deckhouse-config/service.go
- go_lib/deckhouse-config/status.go
- go_lib/deckhouse-config/v1alpha1/module_config.go
- modules/003-deckhouse-config/crds/module-config.yaml
- modules/003-deckhouse-config/hooks/update_status.go
- modules/003-deckhouse-config/hooks/update_status_test.go
Support module type (embedded or external) in module config statuses.
We need differ external modules when request modules list via `kubectl get mc` command
`kubectl get mc` command should show `Type` column
```changes
type: feature
summary: Support statuses for external modules
```
> [deckhouse-config] Support statuses for external modules

- candi/cloud-providers/aws/docs/LAYOUTS.md
- candi/cloud-providers/aws/docs/LAYOUTS_RU.md
- candi/cloud-providers/aws/openapi/cluster_configuration.yaml
- candi/cloud-providers/aws/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/gcp/openapi/cluster_configuration.yaml
- candi/cloud-providers/gcp/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/yandex/docs/LAYOUTS_RU.md
- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/doc-ru-cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/openapi/doc-ru-cluster_configuration.yaml
- ee/candi/cloud-providers/vsphere/docs/LAYOUTS.md
- ee/candi/cloud-providers/vsphere/docs/LAYOUTS_RU.md
- ee/candi/cloud-providers/vsphere/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/vsphere/openapi/doc-ru-cluster_configuration.yaml
Added description and examples to <PROVIDER>ClusterConfiguration OpenAPI specs.
```changes
section: docs
type: chore
summary: Added description and examples to <PROVIDER>ClusterConfiguration OpenAPI specs.
```
> [cloud-providers][docs] Add description and examples to OpenAPI specs

- global-hooks/discovery/modules_images_tags.go
- global-hooks/discovery/modules_images_tags_test.go
- global-hooks/discovery/testdata/modules-images-tags/external-modules-source/999-test-test/images_tags.json
- global-hooks/discovery/testdata/modules-images-tags/external-modules/997-test-local/images_tags.json
- global-hooks/discovery/testdata/modules-images-tags/external-modules/998-test-empty
- global-hooks/discovery/testdata/modules-images-tags/external-modules/999-test-test
- werf.yaml
Modify modules_images_tags global hook to support external modules.
This is the part of #3465.
```changes
type: feature
summary: modify modules_images_tags to support external modules
```
> [global] modify modules_images_tags to support external modules

- ee/modules/030-cloud-provider-vsphere/templates/csi/cm.yaml
Stop depending on CCM to uniquely identify instance ID. Fixes a couple of bugs.
Feature: https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/1321
Bug: https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/2135
Volume detach does not work sometimes.
Volume detach works every time.
```changes
type: fix
summary: Stop depending on CCM to uniquely identify instance ID. Fixes a couple of bugs.
```
> [cloud-provider-vsphere] Set "use-csinode-id" feature flag

- modules/500-okmeter/openapi/config-values.yaml
- modules/500-okmeter/openapi/doc-ru-config-values.yaml
- modules/500-okmeter/templates/daemonset.yaml
This PR brings an opportunity to disable auto-discovery in okagent deployed by deckhouse module
Okagent is deployed as a DaemonSet and runs on each host of a cluster. It continuously watches host process list and discovers services it can monitor, e.g: postgresql, redis, etc. The dynamic nature of Kubernetes is still not well tolerated by the Okmeter. For example, simple rollout of the newer version of redis deployment will cause alerts to fire due to redis pod name change. Okagent has feature to disable plugins auto-discovery leaving only basic monitoring, so we can support it on the Deckhouse side.
Solves https://github.com/deckhouse/deckhouse/issues/2429
> Add disableAutoDiscovery option to okmeter module

- modules/340-extended-monitoring/images/image-availability-exporter/Dockerfile
Fixed panic upstream. Still needs some work to streamline Keychain interface usage, but it should suffice for now.
https://github.com/deckhouse/k8s-image-availability-exporter/releases/tag/v0.3.4
It panicked on some specific pullSecrets compositions.
It does not panic anymore.
```changes
type: fix
summary: Fixed keychain access panic in image-availability-exporter
```
> [extended-monitoring] Fixed keychain panic in IAE

- modules/460-log-shipper/docs/EXAMPLES.md
- modules/460-log-shipper/docs/EXAMPLES_RU.md
Add an example to log-shipper docs
1. The feature itself is great because it helps to create indexes dynamically.
2. extraLabels integration is not apparent.
```changes
type: chore
summary: Index template example for Elasticsearch.
```
> [log-shipper] Index template example for Elasticsearch

- .github/scripts/js/constants.js
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
For further 1.26 e2e test we have to update CI before
```changes
section: ci
type: feature
summary: Add 1.26 kubernetes e2e tests
```
> [ci] Add 1.26 e2e pipelines

- ee/modules/110-istio/images/proxyv2-v1x12x6/iptables-wrapper-installer.sh
- ee/modules/110-istio/images/proxyv2-v1x13x7/Dockerfile
- ee/modules/110-istio/images/proxyv2-v1x13x7/iptables-wrapper-installer.sh
iptables-wrapper fix for istio sidecar.
Previous one didn't detect the legacy mode.
Pods with istio sidecar start without problems.
```changes
section: istio
type: fix
summary: iptables-wrapper fix for istio sidecar.
```
> [istio] iptables-wrapper fix

- go_lib/set/set.go
- modules/040-node-manager/hooks/yc_delete_preemptible_instances.go
- modules/040-node-manager/hooks/yc_delete_preemptible_instances_test.go
1. Stop deleting Yandex.Cloud preemptible instances if percent of Ready Machines in a NodeGroup dips below 90%.
2. Try to delete 10% of all Machines older than 24h, while respecting the aforementioned NG readiness, on each hook iteration (every 15 minutes).
Deletion of preemptible instances continues even if new Machines cannot be provisioned.
No Machines are deleted if more than 10% of Machines in a NodeGroup are not Ready. Algorithm is simplified.
```changes
type: fix
summary: |
1. Stop deleting Yandex.Cloud preemptible instances if percent of Ready Machines in a NodeGroup dips below 90%.
2. Algorithm is simplified.
```
> [node-manager] Fixed Yandex preemptible hook

- ee/modules/502-delivery/templates/argocd/repo-server/argocd-repo-server-deployment.yaml
Add tmp dir to werf-argocd-cmp-sidecar container in argocd-repo-server Deployment.
Fixes werf bundle render error.
```
rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `sh -ec export WERF_RELEASE="${WERF_RELEASE:-$ARGOCD_APP_NAME}" export WERF_NAMESPACE="${WERF_NAMESPACE:-$ARGOCD_APP_NAMESPACE}" export WERF_BUNDLE_DIR="." werf bundle render ` failed exit status 1: time="2023-02-06T12:09:00Z" level=warning msg="Reading allowed ID mappings: Reading subuid mappings for user \"nobody\" and subgid mappings for group \"nobody\": No subuid ranges found for user \"nobody\" in /etc/subuid" …
```
> [delivery] Add tmp dir for werf in argocd-repo-server sidecar

- .github/ci_templates/e2e_tests.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Do not try to save e2e test results (dhctl, deckhouse logs) if dhctl log path variable does not set
If e2e test was failed before finish setup step then `save test result` step tried to load all directory in artifacts (because we use specified regexp)
```changes
section: ci
type: fix 
summary: Fix save test results step
```
> [ci] Fix save test results step

- candi/bashible/common-steps/all/001_disable_swap.sh.tpl
First disable units, then disable swapping on all devices.
If we disable swapping on devices before disabling units, it prevents units from disabling. This happens because `systemctl list-units --no-legend --plain --no-pager --type swap | cut -f1 -d" " ` returns empty list. And on reboot swap is enabled again.
```changes
section: candi
type: fix
summary: Reorder swap disabling steps
```
> [candi] Reorder swap disabling steps

- modules/500-upmeter/openapi/openapi-case-tests.yaml
- modules/500-upmeter/templates/smoke-mini/statefulsets.yaml
Fixing rendering error.
Smoke mini statefulsets cannot render when nodes are named as numbers. Unquoted numbers in
annotations are interpreted as numbers when unmarshalling in kube client.
Nodes with names like "12345" don't cause rendering problems.
```changes
type: fix
summary: Fixed rendering error when nodes are named as numbers.
```
> [upmeter] Fix smoke-mini StatefulSet rendering when nodes are named as numbers

- candi/openapi/init_configuration.yaml
Remove the deprecated `global.modules.proxy` parameter from the example.
```changes
section: docs
type: chore
summary: [docs] Update example in the InitConfigration OpenAPI spec.
```
> [docs] Update example in the InitConfigration OpenAPI spec

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/generic/cri-version.tpl
Switching on the DeprecatedDockerContainerRuntime alert.
It was switched off earlier and now we are ready to migrate.
The alert fires if there are nodes with Docker cri.
```changes
type: chore
summary: DeprecatedDockerContainerRuntime alert is switched on — it is time to use containerd now.
```
> [monitoring-kubernetes] Switching on the DeprecatedDockerContainerRuntime alert

- ee/modules/110-istio/templates/control-plane/mutatingwebhook-global.yaml
- ee/modules/110-istio/templates/control-plane/validatingwebhook-global.yaml
- modules/003-deckhouse-config/templates/deckhouse-config-webhook/webhook-configuration.yaml
- modules/015-admission-policy-engine/templates/validatingwebhookconfiguration.yaml
- modules/042-kube-dns/templates/sts-pods-hosts-appender-webhook/webhook-configuration.yaml
- modules/045-snapshot-controller/templates/snapshot-validation-webhook/webhook.yaml
- modules/101-cert-manager/templates/webhook/mutatingwebhookconfiguration.yaml
- modules/101-cert-manager/templates/webhook/validatingwebhookconfiguration.yaml
- modules/402-ingress-nginx/templates/controller/admission.yaml
Removed obsolete v1beta1 admissionReviewVersions from modules:
- Istio
- deckhouse-config
- admission-policy-engine
- kube-dns
- snapshot-controller
- cert-manager
- ingress-nginx
This is done to reduce the load on the apiserver and codebase simplification.
Reduce apiserver load and codebase simplification.
```changes
type: chore
summary: Removed obsolete v1beta1 admissionReviewVersions from multiple modules.
```
> [global] remove obsolete v1beta1 admissionReviewVersions from different modules

- ee/modules/450-network-gateway/openapi/config-values.yaml
- ee/modules/450-network-gateway/openapi/doc-ru-config-values.yaml
- ee/modules/502-delivery/openapi/config-values.yaml
- ee/modules/502-delivery/openapi/doc-ru-config-values.yaml
- modules/300-prometheus/openapi/config-values.yaml
- modules/300-prometheus/openapi/doc-ru-config-values.yaml
- modules/500-upmeter/openapi/config-values.yaml
- modules/500-upmeter/openapi/doc-ru-config-values.yaml
Add the link to the global storageClass.
```changes
section: docs
type: chore
summary: Add the link to the global `storageClass`.
```
> [docs] Add the link to the global storageClass

- modules/490-virtualization/hooks/disk_handler.go
- modules/490-virtualization/hooks/disk_handler_test.go
Some fixes regarding queue and panic when creating empty disks
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x369b120]
goroutine 78218 [running]:
github.com/deckhouse/deckhouse/modules/490-virtualization/hooks.handleVirtualMachineDisks(0xc003fed700)
/deckhouse/modules/490-virtualization/hooks/disk_handler.go:242 +0x520
github.com/flant/addon-operator/sdk.(*commonGoHook).Run(0xc004d14038?, 0xc00588cde0?)
/go/pkg/mod/github.com/flant/addon-operator@v1.1.2/sdk/sdk.go:27 +0x22
github.com/flant/addon-operator/pkg/module_manager.(*HookExecutor).RunGoHook(0xc004d14908)
/go/pkg/mod/github.com/flant/addon-operator@v1.1.2/pkg/module_manager/hook_executor.go:183 …
```
> [virtualization] Fix panic when creating empty disks

- .gitignore
- modules/002-deckhouse/images/webhook-handler/werf.inc.yaml
- python_lib/sitecustomize.py
- werf.yaml
Add support for module hooks written in Python
Allows external modules (WIP) with Python hooks to be used. Also, Deckhouse hooks can be written in
Python instead of Bash.
Deckhouse Python hooks can be run and tested.
```changes
type: feature
summary: Added Python environment to support Python hooks
```
> Python runtime

- python_lib/sitecustomize.py
Fix failing discovery of external module hooks, that are not in modules/
Make python hooks in external modules work
External module hooks work
```changes
section: python_lib
type: fix
summary: Fixed the discovery of external module hooks
```
> [python_lib] Fix external module path discovery: rely on Chart.yaml

- modules/045-snapshot-controller/enabled
- modules/491-containerized-data-importer/enabled
Fix trace output in enabled scripts
```
│ │ Running pod found! Checking logs...
│ │ 	containerized-data-importer/: Traceback (most recent call last):
│ │ 	containerized-data-importer/:   File "/deckhouse/modules/491-containerized-data-importer/enabled", line 37, in main
│ │ 	containerized-data-importer/:     enabled::run "$@"
│ │ 	containerized-data-importer/:   File "/deckhouse/shell_lib/enabled.sh", line 18, in enabled::run
│ │ 	containerized-data-importer/:     __main__
│ │ 	containerized-data-importer/:   File "/deckhouse/modules/491-containerized-data-importer/enabled", line 27, in __main__
│ │ 	containerized-data-importer/:     case "$(kubectl get moduleconfig containerized-data-importer -o jsonpath={.spec.enabled}            ↵
│ │ …
```
> [snapshot-controller][containerized-data-importer] fix trace output in enabled scripts

- modules/021-cni-cilium/images/cilium/Dockerfile
- modules/021-cni-cilium/images/cilium/patches/003-mtu.patch
- modules/021-cni-cilium/images/cilium/patches/README.md
Here is an upstream issue https://github.com/cilium/cilium/issues/23711
By default cilium inherits MTU values from phiscal dev, this is not working for tunneled mode. 
While containers are not affected, the virtual machines are very sensitive for provided MTU value. 
Setting correct number will fix problems with communication between VMs in tunneled mode.
If cilium tunnel mode enabled, then all veth-interfaces will be created with correct MTU settings
```changes
section: cilium-cni
type: fix
summary: set correct mtu values in tunnel mode
```
> [cni-cilium] reuse route mtu for interfaces

- modules/402-ingress-nginx/images/proxy-failover-iptables/Dockerfile
- modules/402-ingress-nginx/images/proxy-failover-iptables/iptables-wrapper-installer.sh
- modules/402-ingress-nginx/images/proxy-failover-iptables/rootfs/usr/bin/iptables-loop
- modules/402-ingress-nginx/images/proxy-failover/rootfs/etc/nginx/nginx.conf.tpl
Fix `HostWithFailover` inlet to work with cilium CNI.
`HostWithFailover` inlet doesn't work with cilium CNI.
`HostWithFailover` inlet works as expected.
```changes
section: nginx-ingress
type: fix
summary: Fix HostWithFailover inlet to work with cilium CNI.
impact: All proxy-<ingress-name>-failover daemonsets will be restarted
```
> [nginx-ingress] fix failover inlet

- modules/041-linstor/monitoring/prometheus-rules/linstor-controller.yaml
Linstor runs two controllers, but only one is active and serves metrics.
This PR fixes the alert for `if any target down` to `if all targets down`.
Fixes https://github.com/deckhouse/deckhouse/issues/2614
```changes
type: fix
summary: Fix D8LinstorControllerTargetDown alert.
```
> [linstor] Fix D8LinstorControllerTargetDown alert

- modules/301-prometheus-metrics-adapter/templates/config-map.yaml
* Switch from the hardcoded 5m interval to the x4 scrape interval
Otherwise, users can experience problems with CPU metrics with the following error for all pods (this is important because, for a small number of pods, this error can happen for different reasons).
```
E0213 15:05:01.429761       1 provider.go:191] unable to fetch CPU metrics for pod d8-cni-flannel/flannel-jd692, skipping
E0213 15:05:01.429765       1 provider.go:191] unable to fetch CPU metrics for pod d8-cni-flannel/flannel-jfv86, skipping
E0213 15:05:01.429769       1 provider.go:191] unable to fetch CPU metrics for pod d8-cni-flannel/flannel-jkpvx, skipping
E0213 15:05:01.429774       1 provider.go:191] unable to fetch CPU metrics for pod …
```
> [prometheus-metrics-adapter] Relative CPU metrics query interval

- modules/021-cni-cilium/images/cilium/Dockerfile
- modules/021-cni-cilium/images/operator/Dockerfile
Bump cilium to v1.11.13.
Cilium bug fixes and security patches.
Update cilium agents and operator are deployed.
```changes
type: chore
summary: Bump cilium to v1.11.14
impact: All cilium Pods will be restarted.
```
> [cni-cilium] bump cilium version to v1.11.14

- modules/000-common/oss.yaml
The previous Alpine Logo URL is no longer available, so it has been updated to the new one.
```changes
section: docs
type: chore
summary: Update Alpine Linux logo URL
```
> [docs] Update Alpine Linux logo URL

- docs/site/_data/getting_started/data.yaml
- docs/site/_includes/getting_started/yandex/layouts/STANDARD.md
- docs/site/_includes/getting_started/yandex/layouts/STANDARD_RU.md
- docs/site/_includes/getting_started/yandex/layouts/WITHOUT_NAT.md
- docs/site/_includes/getting_started/yandex/layouts/WITHOUT_NAT_RU.md
- docs/site/_includes/getting_started/yandex/partials/config.yml.standard.ce.inc
- docs/site/_includes/getting_started/yandex/partials/config.yml.standard.ee.inc
Use the Standard layout in the Yandex Cloud provider.
Ref: https://github.com/deckhouse/deckhouse/pull/3411
```changes
section: docs
type: chore
summary: Use the Standard layout in the Yandex Cloud provider.
```
> [docs][gs] Use the Standard layout in the Yandex Cloud provider

- modules/490-virtualization/images/vmi-router/main.go
vmi-router: disable metrics by default
VMI-router runs in host-network and binding on `:8080` and `:8081` ports, which are conflicting with nginx-ingress
We're not collecting metrics and do not run probes for vmi-router right now, so it's better to disable them by default
vmi-router stops listening on tcp ports
```changes
type: fix
summary: vmi-router: disable metrics by default
```
> [virtualization] vmi-router: disable metrics by default

- modules/500-openvpn/openapi/config-values.yaml
- modules/500-openvpn/openapi/doc-ru-config-values.yaml
- modules/500-openvpn/templates/openvpn/statefulset.yaml
Signed-off-by: Konstantin Maltsev <konstantin.maltsev@flant.com>
There is a configuration of **highAvailability** flag for openvpn module.
There is horizontal scaling of openvpn server for high availability.
It refers to this issue: #1622 
In case of specifying 'false' or non-specified - there would be only 1 replica of server.
In case of specifying 'true' - there would be 2 replicas of server.
Also it controls by global **highAvailability** parameter.
```changes
type: feature
summary: configuration HA for openvpn server
```
> [openvpn] Setup HA for openvpn module

- modules/021-kube-proxy/images/init-container/nodeport-bind-address.sh
- modules/021-kube-proxy/templates/daemonset.yaml
- modules/030-cloud-provider-gcp/docs/README.md
- modules/030-cloud-provider-gcp/docs/README_RU.md
Update kube-proxy configuration to set listen address to 0.0.0.0/0 when using GCP cloud provider.
Closes (https://github.com/deckhouse/deckhouse/issues/3734)
For GCP cloud provider, kube-proxy will handle connections on 0.0.0.0/0.
```changes
type: fix
summary: update kube-proxy configuration to set listen address to 0.0.0.0/0 when using GCP cloud provider.
impact: "`kube-proxy` Pods will be recreated."
```
> [cloud-provider-gcp] update kube-proxy configuration to set listen address to 0.0.0.0/0 when using GCP cloud provider

- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
In case of installation on bare metal, in the getting started steps, you have to run kubectl with sudo, as kubectl is automatically configured in the root user.
```changes
section: docs
type: chore
summary: Minor updates for the bare-metal installation.
```
> [getting-started] Minor updates for the bare-metal installation

- modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
Add alert with higher severity level to notice about EOL of the 1.21 kubernetes version
1.21 kubernetes will be unsupported in the next release (1.45)
```changes
type: chore
summary: Kubernetes version 1.21 support will be remove in the next (1.45) Deckhouse release. An alert have been added to keep you from forgetting about it.
```
> [control-plane-manager] kubernetes version EOL

- docs/documentation/_data/version_map_addition.yml
It's already included in e2e, so there are no reasons to omit it from the list of the supported versions of the OS.
```changes
section: docs
type: chore
summary: Add support of Astra 1.7.3 on the site.
```
> [site] Add support of Astra 1.7.3

- modules/015-admission-policy-engine/docs/README.md
- modules/015-admission-policy-engine/docs/README_RU.md
- modules/015-admission-policy-engine/templates/operation-policy/constraint.yaml
1. Change recommended imagePullPolicy to Always.
2. Fix template rendering
1. `Always` is the recommended policy. More information [here](https://www.fairwinds.com/blog/kubernetes-devops-tip-5-why-setting-imagepullpolicy-to-always-is-more-necessary-than-you-think). Kubernetes has admission plugin [AlwaysPullImages](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages) to force this policy.
2. Fix error
```
spec:
enforcementAction: "deny"
match:
kinds:
- apiGroups: [""]
kinds: ["Pod"]
namespaceSelector: map[matchLabels:map[operation-policy.deckhouse.io/enabled:true]]
spec:
enforcementAction: "deny"
match:
kinds:
- apiGroups: [""]
kinds: ["Pod"]
namespaces:
- foxtrot-demo
labelSelector: map[matchLabels:map[operation-policy.deckhouse.io/enabled:true] …
```
> [admission-policy-engine] Change recommended imagePullPolicy to Always

- modules/150-user-authn/images/dex/Dockerfile
- modules/150-user-authn/images/dex/patches/README.md
- modules/150-user-authn/images/dex/patches/robots-txt.patch
To avoid Dex being accidentally scraped by robots.
```changes
type: feature
summary: Add robots.txt for Dex
```
> [user-authn] Robots.txt

- release.yaml
This reverts commit e0b86ed58c4635380f6ea6f9bc07bb83e3ca7718.
(PR returns requirement for minimal Ubuntu node version)
We need minimum Ubuntu 18.04 for containerd 1.6
Correct containerd 1.6 installation.
```changes
type: fix
summary: Revert "temporarily removed requirement for minimal ubuntu node version (#3714)".
```
> [deckhouse] revert "temporarily removed requirement for minimal ubuntu node version (#3714)"

- candi/bashible/bundles/centos/all/001_install_mandatory_packages.sh.tpl
- candi/bashible/bundles/debian/all/001_install_mandatory_packages.sh.tpl
- candi/bashible/bundles/ubuntu-lts/all/001_install_mandatory_packages.sh.tpl
- ee/candi/bashible/bundles/redos/all/001_install_mandatory_packages.sh.tpl
- modules/007-registrypackages/images/containerd-centos/scripts/install
- modules/007-registrypackages/images/containerd-centos/werf.inc.yaml
Fixes in CentOS and Ubuntu based distros for normal node bootstrap.
There is 3 problems:
- Centos 9 based distributives wants selinux-policy 38.1.2-1 or higher, but in base last version is 34.1.2-1.
- With Ubuntu, there is possibility of missed apparmor package.
- Centos based distributives wants to install conntrack, which is replaced with conntrack-tools. In case of AWS AMI thereis is version lock on conntrack-tools, and bashible can't proceed mandatory packages installation
All cases can lead to node bootstrap failure
Successful node bootstrap
```changes
section: candi
type: fix
summary: Fixes in CentOS and Ubuntu based distros for normal node bootstrap.
```
> [candi] Fixes for centos 9 based bundles and force apparmor install in ubuntu

- deckhouse-controller/entrypoint.sh
Sleep for 10 seconds if Deckhouse in the ConvergeModules phase
We need this to prevent Deckhouse restart. Helm release could stuck in the `pending-upgrade` state and it's hard fix it
```changes
type: fix
summary: Prevent restart during the ConvergeModule phase
```
> [deckhouse] add sleep to prevent deckhouse abnormal termination

- modules/021-cni-cilium/templates/configmap.yaml
Specify `--tunnel-port=8472` for direct routing mode too.
This fix extends solution from https://github.com/deckhouse/deckhouse/pull/3887 also for direct routing mode.
I found out that cilium continues blocking 8472/udp port even when it is not using tunnel.
Cilium in direct routing mode not blocking 8472/udp port the same way in tunneled mode.
```changes
type: fix
summary: Preserve default tunnel port `8472` for virtualization workloads (direct routing mode).
```
> [cni-cilium] Preserve default tunnel port 8472 for virtualization workloads (direct routing mode)

- go.sum
- modules/402-ingress-nginx/hooks/safe_daemonset_update.go
- modules/402-ingress-nginx/hooks/safe_daemonset_update_test.go
Improve rollout hook:
- wait for all pods to be ready before delete a next one
- sort slice of pods to have an equal one in the each iteration
In a multi-master cloud the list of pods could be sorted in the different order. This way we can have a few pods to be deleted at once
```changes
type: fix 
summary: Improve rollout hook to avoid concurrent controller pod deletion
```
> [ingress-nginx] improve daemonset failover rollout hook

- ee/modules/007-registrypackages/images/kubernetes-cni-alteros/scripts/install
- ee/modules/007-registrypackages/images/kubernetes-cni-alteros/scripts/uninstall
- ee/modules/007-registrypackages/images/kubernetes-cni-alteros/werf.inc.yaml
- ee/modules/007-registrypackages/images/kubernetes-cni-redos/scripts/install
- ee/modules/007-registrypackages/images/kubernetes-cni-redos/scripts/uninstall
- ee/modules/007-registrypackages/images/kubernetes-cni-redos/werf.inc.yaml
Fixes https://github.com/deckhouse/deckhouse/issues/3625.
Install flannel 1.1.2 binary to CentOS-based distros for kubernetes-cni newer than 0.9.1 due to missing flannel binary.
Flannel was moved to sepatate repo in https://github.com/containernetworking/plugins/pull/633.
This is additional part of https://github.com/deckhouse/deckhouse/pull/3534 for centos-based distros supported by Deckhouse.
Cni flannel binary is absent in kubernetes-cni package > 0.9.1.
```changes
section: network
type: fix
summary:  fix install flannel binary in centos-based distros.
```
> [network] fix install flannel binary in centos-based distros

- modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring/application-controllers.yaml
- modules/340-monitoring-ping/templates/daemon-set.yaml
Added a tip about how to find problem nodes unscheduled DaemonSet replicas
In big clusters, unscheduled DaemonSet replicas usually mean there is a problem with a node. This
tip helps to find the problem node.
The alert renders useful shell command.
```changes
type: feature
summary: Added a tip about how to find problem nodes for unscheduled DaemonSet replicas.
```
> [extended-monitoring] Add tip to figure out problematic nodes in KubernetesDaemonSetReplicasUnavailable alert

- docs/site/_includes/getting_started/existing/partials/TROUBLESHOOT.liquid
- docs/site/_includes/getting_started/existing/partials/TROUBLESHOOT_RU.liquid
- docs/site/_includes/getting_started/global/partials/NOTICES.liquid
- docs/site/_includes/getting_started/global/partials/NOTICES_ENVIRONMENT.liquid
Deckhouse supports installing in an existing EKS cluster.
```changes
section: docs
type: chore
summary: Deckhouse supports installing in an existing EKS cluster.
```
> [gs] Remove notice about installing in EKS

- .github/ci_templates/e2e_tests.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Fix e2e upgrade test.
Changes were [tested](https://github.com/deckhouse/deckhouse-test-1/actions/runs/4305464067/) on test-1 repo.
Currently e2e upgrade tests are failing due to incorrect install image being used.
* e2e upgrade tests will now use initial ref slug to determine which install image and layout versions should be used;
* e2e upgrade tests are passing on release branches.
```changes
section: ci
type: fix
summary: Fix e2e upgrade test.
```
> [ci][testing][e2e] Fix e2e upgrade test

- modules/490-virtualization/templates/kubevirt.yaml
This PR enables feature gate for online-resizing disks for virtual machines
When user changes size of virtual machine disk it also resizes it for virtual machine
```changes
type: feature
summary: Enable the `ExpandDisks` feature gate.
```
> [virtualization] Enable ExpandDisks feature gate

- deckhouse-controller/entrypoint.sh
- modules/002-deckhouse/hooks/handle_pending_upgrade.go
- modules/002-deckhouse/hooks/handle_pending_upgrade_test.go
Fix deckhouse release stuck in the pending state
Deckhouse could restart in the middle of upgrade process and helm release will stuck in the pending-upgrade state.
Entrypoint sleep breaks module-configs logic, so we have to repair releases in the Deckhouse module
```changes
type: fix
summary: remove pending releases before Deckhouse upgrade
```
> [deckhouse] Handle pending release

- modules/021-cni-cilium/monitoring/grafana-dashboards/kubernetes-cluster/cilium-agent.json
- modules/021-cni-cilium/templates/monitoring.yaml
Added official cilium agent dahboard.
```changes
type: chore
summary: Added cilium agent dashboard
```
> [cni-cilium] add agent dashboard

- modules/140-user-authz/crds/crd.yaml
- modules/140-user-authz/crds/doc-ru-crd.yaml
- modules/140-user-authz/docs/USAGE.md
- modules/140-user-authz/docs/USAGE_RU.md
Add links to the `enableMultiTenancy` module parameter.
```changes
type: chore
summary: Add links to the `enableMultiTenancy` module parameter.
```
> [docs][user-authz] Add links to the enableMultiTenancy module parameter

- modules/150-user-authn/hooks/discover_dex_ca.go
- modules/150-user-authn/hooks/discover_dex_ca_test.go
Signed-off-by: Konstantin Maltsev <konstantin.maltsev@flant.com>
There is a fix for **discover_dex_ca** hook for proper secrets loop.
It must loops over the list of secrets instead of catching first one.
It refers to this issue: #2173
Depending on mode (_CertManager_ or _CustomCertificate_) it subcribes to the secret (_ingress-tls_ or _ingress-tls-customcertificate_) accordingly.
```changes
type: fix
summary: 'The `discover_dex_ca` hook subscribes secret according to the used mode.'
```
> [user-authn] discover_dex_ca loops the list of secrets

- modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
Remove D8 prefix for `KubernetesVersionEndOfLife` alert.
Alerts with D8 prefix are automatically redirected to the foxtrot. We don't want this.
```changes
type: fix
summary: Fix `KubernetesVersionEndOfLife` alert auto redirection.
```
> [control-plane-manager] Remove D8 prefix for KubernetesVersionEndOfLife alert

- modules/402-ingress-nginx/hooks/order_certificates.go
- modules/402-ingress-nginx/hooks/order_certificates_test.go
Fix order_certificates hook logic
This PR solves issue, when secret `ingress-nginx-<controller name>-auth-tls` is not present (certificate is not generated). Now, when it isn't present - it fails with error `module hook '402-ingress-nginx/hooks/order_certificates.go' failed: there is no Secret with name 'ingress-nginx-<controller-name>-auth-tls' in namespace 'd8-ingress-nginx'`. 
Fix improper hook logic and new tests
```changes
type: chore
summary: fix order_certificates hook logic
```
> [ingress-nginx] Fix order certificates hook

- modules/003-deckhouse-config/templates/deckhouse-config-webhook/deployment.yaml
- modules/003-deckhouse-config/templates/deckhouse-config-webhook/pdb.yaml
Disable HA mode
Set podAffinity
Deckhouse-config have to be on the same node as Deckhouse to have access to the external-modules directory and also, actual external-modules
```changes
type: fix
summary: Place deckhouse-config-webhook on the same node as Deckhouse
```
> [deckhouse-config] disable webhook ha mode

- modules/490-virtualization/images/artifact/patches/007-tolerations-for-strategy-dumper-job.patch
- modules/490-virtualization/images/artifact/patches/README.md
Backport from upstream https://github.com/kubevirt/kubevirt/pull/9360
This PR specifies:
```yaml
tolerations:
- operator: "Exists"
affinity:
podAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchExpressions:
- key: kubevirt.io
operator: In
values:
- virt-operator
topologyKey: "kubernetes.io/hostname"
```
for virt-operator-strategy-dumper job spawned by virt-operator
There is a problem when all nodes in cluster have taints, KubeVirt can't run virt-operator-strategy-dumper job.
The provided fix will always run the job in same place where `virt-operator` runs
```changes
type: fix
summary: Fix tolerations for virt-operator-strategy-dumper job
```
> [virtualization] Fix tolerations for virt-operator-strategy-dumper job

- modules/500-upmeter/hooks/smokemini/internal/snapshot/node.go
- modules/500-upmeter/hooks/smokemini/internal/snapshot/node_test.go
- modules/500-upmeter/hooks/smokemini/reschedule_test.go
Rename deprecated annotations
https://kubernetes.io/docs/reference/labels-annotations-taints/#failure-domainbetakubernetesiozone
Fix #2850 
```changes
type: chore
summary: rename deprecated annotations
```
> [upmeter][smoke-mini] Rename deprecated annotations for upmeter

- docs/site/.helm/templates/20-ingress.yaml
Fix ingress to allow redirection from the www.deckhouse on the site.
```changes
section: docs
type: chore
summary: Fix ingress to allow redirection from the www.deckhouse on the site.
```
> [chore] Add www. redirect on the site

- modules/300-prometheus/templates/prometheus/servicemonitor.yaml
Metrics quantity can grow with the number of rulegroups increasing
Since we know that the maximum numbers of prometheuses is three, we can safely bump the limit
```changes
type: fix
summary:  Increase prometheus self sample limit
```
> [prometheus] Increase prometheus self sample limit

- candi/cloud-providers/aws/openapi/instance_class.yaml
- candi/cloud-providers/azure/openapi/instance_class.yaml
- candi/cloud-providers/gcp/openapi/instance_class.yaml
- candi/cloud-providers/yandex/openapi/instance_class.yaml
- ee/candi/cloud-providers/openstack/openapi/instance_class.yaml
- ee/candi/cloud-providers/vsphere/openapi/instance_class.yaml
- modules/040-node-manager/hooks/get_crds.go
- modules/040-node-manager/hooks/set_instance_class_ng_usage.go
- modules/040-node-manager/hooks/set_instance_class_ng_usage_test.go
- testing/hooks/validation/exported_struct_test.go
Extend InstanceClass status field to show node groups which use it
Improve user experience. Easy to figure out which instance classes is not used
```yaml
kind: OpenStackInstanceClass
metadata:
name: worker
spec:
flavorName: m1.large
imageName: ubuntu-22-04-cloud-amd64
mainNetwork: ndev
status:
nodeGroupConsumers:
- testme
- worker
```
or via the IC list:
```bash
NAME     NODE GROUPS           AGE
test     []                    3d3h
worker   ["testme","worker"]   75d
```
```changes
type: feature 
summary: Show used NodeGroups in the InstanceClass status field
```
> [node-manager] show instance class link to NG

- docs/documentation/werf-git-section.inc.yaml
- modules/040-node-manager/crds/doc-ru-nodegroupconfiguration.yaml
- modules/040-node-manager/crds/nodegroupconfiguration.yaml
For the node-manager module the openapi spec from the CE revision is used on the site, but the spec from the FE version is needed. The PR fix this bug.
The allowBundles parameter of the node-manager module use the allowed values list of more than 3 items (FE revision spec).
```changes
section: docs
type: chore
summary: Fix bug in generating OpenAPI values for the module.
```
> [docs][node-manager] Fix bug in generating OpenAPI values for the module

- deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go
- modules/490-virtualization/images/artifact/patches/007-tolerations-for-strategy-dumper-job.patch
- modules/491-containerized-data-importer/hooks/https/copy_custom_certificate.go
- modules/491-containerized-data-importer/openapi/config-values.yaml
- modules/491-containerized-data-importer/openapi/doc-ru-config-values.yaml
- modules/491-containerized-data-importer/openapi/openapi-case-tests.yaml
- modules/491-containerized-data-importer/openapi/values.yaml
Make CDI working with customCertificate
If cluster configured to use customCertificate method, cdi module can't be installed
CDI able to work with customCertificate
```changes
section: containerized-data-importer
type: fix
summary: Make CDI working with `customCertificate`.
```
> [containerized-data-importer] fix customCertificate

- helm_lib/Chart.lock
- helm_lib/Chart.yaml
- helm_lib/README.md
- helm_lib/charts/deckhouse_lib_helm/Chart.yaml
Upgrade lib-helm to 1.0.1 and update readme.
Broken link in readme.
Release 1.0 for lib-helm (without any changes)
```changes
section: Upgrade lib-helm to 1.0.1 and update readme 
type: chore
summary: Upgrade lib-helm to 1.0.1 and update readme
```
> [helm_lib] Upgrade lib-helm to 1.0.1 and update readme

- .github/workflow_templates/e2e-daily.yml
- .github/workflows/e2e-daily.yml
Run daily e2e tests at 1 am UTC, as 3 am UTC is too late.
```changes
section: ci
type: chore
summary: Run daily e2e tests at 1 am UTC.
```
> [ci] Schedule e2e-daily test on 1:00 UTC (was 3:00 UTC)

- modules/041-linstor/monitoring/prometheus-rules/drbd-devices.yaml
Update alerts and labels.
Simplify label selectors and update course of action in case of failures
```changes
type: chore
summary: Update alerts and labels.
```
> [linstor] Update alerts and labels

- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
Small changes in module FAQ
There is incorrect information about cri.type changing in module FAQ.
Correct information in FAQ.
```changes
type: chore
summary: Changes in FAQ about changing CRI type for node groups.
```
> [node-manager] changes in FAQ about changing CRI type for node groups.

- modules/021-cni-cilium/docs/internal/CONNECTIVITY_TESTS.md
Internal documents on problems with running cilium connectivity tests
Information on potential problems and solutions should be accumulated
```changes
type: chore
summary: Internal documents on problems with running cilium connectivity tests.
```
> [cni-cilium] cilium connectivity test doc

- .github/workflow_templates/build-and-test_pre-release.yml
- .github/workflow_templates/cve-daily.yml
- .github/workflow_templates/e2e-daily.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/cve-daily.yml
- .github/workflows/e2e-daily.yml
This PR fixes incorrect name rendering for following workflows:
* `build-and-test_pre-release.yml`
* `cve-daily.yml`
* `e2e-daily.yml`
Workflow names mentioned above don't render correctly:
Workflow names render correctly now (tested on `deckhouse-test-1` repo):
```changes
section: ci
type: fix
summary: Fix build-and-test_pre-release.yml, cve-daily.yml and e2e-daily.yml workflow name rendering
```
> [ci] Fix build-and-test_pre-release.yml, cve-daily.yml and e2e-daily.yml workflow name rendering

- ee/modules/650-runtime-audit-engine/hack/far-converter/main.go
- ee/modules/650-runtime-audit-engine/images/rules-loader/hooks/rules/hook.py
- ee/modules/650-runtime-audit-engine/images/rules-loader/hooks/rules/test.py
- ee/modules/650-runtime-audit-engine/images/rules-loader/requirements.txt
Add the stringcase library to convert camel case to string case.
The plugin's name is `k8saudit`, but the source's name is `k8s_audit`. Without it, `K8sAudit` source type rules are ignored now.
```changes
type: fix
summary: Fix `K8sAudit` -> `k8s_audit` source convert action.
```
> [runtime-audit-engine] Fix K8sAudit -> k8s_audit source convert action

- modules/021-cni-cilium/images/virt-cilium/patches/004-fib.patch
- modules/021-cni-cilium/images/virt-cilium/patches/README.md
Perform routing lookup for custom tables
Upstream fix: https://github.com/cilium/cilium/pull/24271
Pod-to-pod communication is not working in case when routes are located in different routing tables.
See https://github.com/cilium/cilium/issues/24252 for more details.
That makes our virtualization workloads not working because per-vm routes are adding into additional routing table.
That will fix communication between VMs when cilium runs in direct-node-routing mode.
```changes
type: fix
summary: Perform routing lookup for custom tables.
```
> [cni-cilium] Perform routing lookup for custom tables

- modules/021-cni-cilium/images/virt-cilium/patches/002-stable-mac.patch
- modules/021-cni-cilium/images/virt-cilium/patches/README.md
- modules/021-cni-cilium/templates/configmap.yaml
This PR changes non-working mac-address generator with static values, which are used only for virtualization-enabled clusters.
There is a regression after https://github.com/deckhouse/deckhouse/pull/3889:
All the interfaces get the same MAC-address. This is not actually bad, because in most cases VMs (eg. ubuntu with its cloud-init) are depending on stable MAC-address even after changing IP-address. But we don't know about possible drawbacks of such solution.
Thus it would be better to apply this configuration only for virtualization clusters.
All the veth-interfaces will have explicitly specified MAC-address:
- From container side: `f6:e1:74:94:b8:1a`
- From host side: `f6:e1:74:94:b8:1b`
```changes
type: fix
summary: Use predefined MAC-addresses for virtualization …
```
> [cni-cilium] Use predefined MAC-addresses for virtualization workloads

- modules/300-prometheus/template_tests/secret_datasources_list_test.go
- modules/300-prometheus/templates/grafana/secret-datasources-list.yaml
Fix timeInterval for longterm Prometheus
Without this, all interval variables in Grafana are lower than 5 minutes, which leads to empty panels
```changes
type: fix
summary: Fix the time interval for Prometheus longterm.
```
> [prometheus] Fix time interval for prometheus longterm

- modules/003-deckhouse-config/templates/deckhouse-config-webhook/deployment.yaml
Temporary Recreate strategy for deckhouse-config-webhook Deployment.
The new affinity in 1.44:
```
affinity:
podAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchLabels:
app: deckhouse
topologyKey: kubernetes.io/hostname
```
The old one:
```
affinity:
podAntiAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchLabels:
app: deckhouse-config-webhook
topologyKey: kubernetes.io/hostname
```
So, the new Deployment version can't make it through RollingUpdate:
```
0/31 nodes are available: 1 node(s) didn't satisfy existing pods anti-affinity rules, 2 node(s) didn't match pod affinity rules
```
deckhouse-config-webhook is being upgraded without problems.
```changes
section: deckhouse-config-webhook
type: fix
summary: Temporary Recreate …
```
> [deckhouse-config-webhook] temporary Recreate strategy for webhook

- modules/003-deckhouse-config/templates/deckhouse-config-webhook/deployment.yaml
Remove nodeSelector for deckhouse-config-webhook deployment
Deckhouse config webhook have to be on the same node as Deckhouse controller because of external modules. We can handle it with pod affinity, but webhook should not have his own node selector
```changes
section: deckhouse-config-webhook
type: fix
summary: Remove node-selector for deckhouse-config-webhook
```
> [deckhouse-module-config] Remove nodeSelector for deckhouse-config-webhook

- modules/491-containerized-data-importer/crds/cdi.yaml
- modules/491-containerized-data-importer/images/artifact/patches/004-replicas.patch
- modules/491-containerized-data-importer/images/artifact/patches/README.md
- modules/491-containerized-data-importer/templates/cdi.yaml
Added option to specify replicas for CDI
Includes upstream fix:
- https://github.com/kubevirt/containerized-data-importer/pull/2563
```changes
section: containerized-data-importer
type: fix
summary: Enable high availability
```
> [containerized-data-importer] Enable HA

- candi/bashible/common-steps/cluster-bootstrap/070_install_control_plane.sh.tpl
Remove from first control-plane node `node-role.kubernetes.io/master` taint during bootstrap.
Deprecated taint `node-role.kubernetes.io/master` keeps on first control-plane node.
```changes
section: candi
type: fix
summary: Remove from first control-plane node `node-role.kubernetes.io/master` taint during bootstrap.
```
> [candi] Remove from first control-plane node `node-role.kubernetes.io/master` taint during bootstrap.

- ee/candi/cloud-providers/vsphere/layouts/standard/base-infrastructure/outputs.tf
- ee/candi/cloud-providers/vsphere/openapi/cloud_discovery_data.yaml
- ee/modules/030-cloud-provider-vsphere/hooks/internal/v1/cloud_discovery_data.go
- ee/modules/030-cloud-provider-vsphere/hooks/vsphere_cluster_configuration_test.go
- ee/modules/030-cloud-provider-vsphere/openapi/values.yaml
Add zones to vsphere provider cloud discovery data for uniformity with another cloud providers
Fix #4109 
Added zones to vsphere provider cloud discovery data
```changes
type: feature
summary: Add zones list to cloud discovery data
```
> [cloud-provider-vsphere] Add zones to provider cloud discovery data

- candi/bashible/bashible.sh.tpl
- dhctl/pkg/template/bootstrap.go
- modules/040-node-manager/templates/node-group/_bootstrap_script.tpl
Nodes bootstrap in air-gapped envs should work properly.
In air-gapped envs bootstrap script depends on `curl` binary which used to download bashible bundle from bashible apiserver. But in some distros `curl` binary is relatively old and does not properly deals with proxy environment variables, 
especially with `no_proxy`.  In that case api request from new node to apiserver goes to proxy, and, if this type of traffic is denied, node cannot give bashible bundle and stay unbootstrapped.
```changes
section: candi
type: fix
summary: fix bootstrap in air-gapped envs
```
> [candi] fix bootstrap in air-gapped envs

- modules/460-log-shipper/monitoring/prometheus-rules/log-shipper-agent.yaml
Add a component type label to the throttling alert
To prevent alerting if events are dropped because of filters or other transforms (when drops are intended)
```changes
type: fix
summary: Fix throttling alert labels.
```
> [log-shipper] Fix throttling alert labels

- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
Fix shell binary using by ansible in FAQ example. Ansible shell module use /bin/sh by default, but the script is written on bash.
Correct example in documentation without syntax error in shell during execution.
Try to add node, using ansible script in documentation without syntax errors.
```changes
section: docs
type: fix
summary: Fix the Ansible script example for adding a node.
impact: documentation
```
> fix shell executable

- tools/change-registry.sh
When using change-registry.sh script now, it doesn't change image for init container for deckhouse deployment. THis PR fixes this
fix #4056
```changes
section: tools
type: fix
summary: change-registry.sh script changes deckhouse initContainer image 
```
> [tools] Change image for init container for deckhouse deployment with change-registry.sh 

- candi/version_map.yml
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.23/001-lock-route-table-operations.patch
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.23/002-use-real-internal-ip-for-routes.patch
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.23/README.md
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.24/001-lock-route-table-operations.patch
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.24/002-use-real-internal-ip-for-routes.patch
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.24/README.md
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.25/001-use-real-internal-ip-for-routes.patch
- modules/030-cloud-provider-yandex/images/cloud-controller-manager/patches/1.25/README.md
Use real InternalIP to avoid problematic routes in the route table.
https://github.com/deckhouse/yandex-cloud-controller-manager/pull/53
Currently, CCM relies on InternalIP provided by the Node object in the Kubernetes API. This creates a race, since kubelet sets the IP earlier than CCM. This results in the wrong internalIP in the routing table.
Proper InternalIP is added to the routing table.
```changes
type: fix
summary: Proper InternalIPs are not added to the routing table. Those that are physically present on a VM in the cloud.
```
> [cloud-provider-yandex] Use real InternalIPs for routes

- modules/140-user-authz/templates/cluster-roles.yaml
Disabled NetworkPolicy editing for Editors.
Editor can't edit native NetworkPolicy. This is important for security reasons. All egress traffic have to be denied by default. And only cluster admin decides where application can route egress traffic outside of namespace.
Only ClusterAdmins can edit NetworkPolicy.
```changes
type: fix
summary: Disabled NetworkPolicy editing for Editors.
```
> [user-authz] Disable NetworkPolicy editing for Editor role

- modules/460-log-shipper/hooks/internal/composer/testdata/config_1.json
- modules/460-log-shipper/hooks/internal/composer/testdata/config_2.json
- modules/460-log-shipper/hooks/internal/vector/destination/common.go
- modules/460-log-shipper/hooks/testdata/multiple-dest/result.json
Fix typo from #4095 
```changes
type: chore
summary: fix buffer settings typo
```
> [log-shipper] fix typo for buffer settings

- modules/021-cni-cilium/templates/agent/daemonset.yaml
- modules/021-cni-cilium/templates/configmap.yaml
Run CNI cilium in a non-privileged environment with the maximum permissions restriction.
Reduce the attack surface
Closes (https://github.com/deckhouse/deckhouse/issues/2961)
The cilium agent runs in an unprivileged environment
```changes
type: chore
summary: Run CNI cilium in a non-privileged environment with the maximum permissions restriction.
impact: All cilium pods will be restarted
```
> [cni-cilium] unprivileged mode

- modules/015-admission-policy-engine/hooks/handle_operation_policies_test.go
- modules/015-admission-policy-engine/hooks/internal/apis/v1alpha1.go
- modules/015-admission-policy-engine/template_tests/operation_policies_test.go
Fix struct for `requiredLabels` OperationPolicy
Wrong manual struct generation lead to the error:
```
filterFn: cannot restore slice from map
```
Unmarshal correctly
```changes
type: fix
summary: Fix `requiredLabels` OperationPolicy
impact: `requiredLabel` unmarshalling lead to an error
```
> [admission-policy-engine] Fix requiredLabels operation policy

- dhctl/pkg/kubernetes/actions/manifests/manifests.go
- modules/002-deckhouse/templates/deployment.yaml
This PR removes external module directory volume mount and init container if external module manager disabled. Also it adds init container in dhctl manifest to fix installation in managed clusters
In case of disabled external module manager we have Deckhouse stucked because of non-existent external modules directory. Also, we have problem with installation in managed clusters.
Correct work of Deckhouse pod, and successful installation in managed clusters
```changes
type: chore
summary: Changes in deckhouse module manifest and dhctl to fix installation in managed clusters (and also in minimal bundle).
```
> [deckhouse] changes in deckhouse module manifest and dhctl to fix installation in managed clusters

- modules/040-node-manager/hooks/util.go
- modules/040-node-manager/webhooks/validating/node_group
Restrict changing `nodeType` for node groups by validating webhook and fix stale status fields
Fix #4236 
Users can't change `nodeType` in the node group spec and removed stale status fields from static NGs
```changes
type: fix
summary: restrict changing nodeType for node groups and remove stale status fields from static node groups
```
> [node-manager] Restrict changing `nodeType` for node groups and fix stale status fields

- modules/500-upmeter/hooks/smokemini/reschedule.go
- modules/500-upmeter/hooks/smokemini/reschedule_test.go
Fix smoke-mini image generation.
After moving to pull images via sha256 digest there is a problem with smoke-mini image path generation
Correct image
```changes
type: fix
summary: Fix smoke-mini image generation.
```
> [upmeter] Fix smoke-mini image generation.

- modules/460-log-shipper/images/vector/Dockerfile
- modules/460-log-shipper/images/vector/patches/README.md
- modules/460-log-shipper/images/vector/patches/kubernetes-backoff.patch
Add a patch
```
2023-03-29T17:28:32.024522Z  WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(Service(Closed))
2023-03-29T17:28:32.024537Z  WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(Service(Closed))
2023-03-29T17:28:32.024551Z  WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(Service(Closed))
2023-03-29T17:28:32.024569Z  WARN vector::kubernetes::reflector: Watcher Stream received an error. Retrying. error=InitialListFailed(Service(Closed))
```
If there is a problem with API, vector immediately reties to requests.
```changes
type: fix
summary: Make vector retrying request on startup with backoff …
```
> [log-shipper] Add vector backoff patch

- modules/300-prometheus/docs/FAQ.md
- modules/300-prometheus/docs/FAQ_RU.md
Add kube-rbac-proxy usage example
```changes
section: docs
type: chore
summary: Add `kube-rbac-proxy` usage example.
```
> [docs] add kube-rbac-proxy usage example

- modules/040-node-manager/hooks/internal/conditions/calculate.go
- modules/040-node-manager/hooks/update_node_group_status_test.go
If node has `update.node.deckhouse.io/disruption-approved` clear WaitingForDisruptiveApproval ng status.
Fix bug.
```changes
type: fix
summary: Fix WaitingForDisruptiveApproval status calculating.
```
> [node-manager] Fix WaitingForDisruptiveApproval status calculating

- modules/041-linstor/images/linstor-server/Dockerfile
- modules/041-linstor/images/linstor-server/liveness.sh
- modules/041-linstor/templates/linstor-controller/linstorcontroller.yaml
Add liveness container to check linstor nodes connectivity status
fixes https://github.com/deckhouse/deckhouse/issues/4121
```changes
type: fix
summary: Add liveness container to check linstor nodes connectivity status.
```
> [linstor] add liveness container to check linstor nodes connectivity status

- modules/340-extended-monitoring/images/extended-monitoring-exporter/src/extended-monitoring.py
- modules/340-extended-monitoring/images/extended-monitoring-exporter/src/requirements.txt
In k8s version 1.25 there is no batch/v1beta1 version, so cronjob listing fails in extended monitoring
Non-working extended-monitoring in k8s 1.25
Proper working extended monitoring in all supported versions
```changes
type: fix
summary: Fix in extended monitoring module
```
> [extended-monitoring] fix cronjob listing

- ee/modules/110-istio/monitoring/prometheus-rules/versions.yaml
Remove pod and instance labels from D8IstioDeprecatedIstioVersionInstalled alert.
Each alert contains pod and instance labels, which are generated by the deckhouse itself. When the deckhouse rolls, a new alert fires.
```changes
section: istio
type: fix 
summary: Got rid of pod, instance and group excess labels in D8IstioDeprecatedIstioVersionInstalled alert.
```
> [monitoring][istio] remove pod and instance labels from D8IstioDeprecatedIstioVersionInstalled alert

- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
Add warning during bootstrap: `Some resources require at least one non-master node to be added to the cluster`
Some users do not understand why they cannot create resources after bootstrap.
```changes
section: dhctl
type: chore
summary: Add warning during bootstrap: `Some resources require at least one non-master node to be added to the cluster`
```
> [dhctl] Add warning during bootstrap: `Some resources require at least one non-master node to be added to the cluster`

- modules/040-node-manager/monitoring/prometheus-rules/node-update.yaml
Add in NodeRequiresDisruptionApprovalForUpdate rules prometheus 'No need to drain the master'.
```changes
section:  node-manager
type: fix 
summary: Add in NodeRequiresDisruptionApprovalForUpdate rules prometheus 'No need to drain the master'.
```
> [node-manager] Add in rules prometheus 'No need to drain the master'

- modules/040-node-manager/images/bashible-apiserver/go.mod
- modules/040-node-manager/images/bashible-apiserver/go.sum
- modules/040-node-manager/images/bashible-apiserver/pkg/template/context_builder.go
- modules/040-node-manager/images/bashible-apiserver/pkg/template/context_builder_test.go
Prevent changing bashible checksum if scale/downscale nodegroup.
When we scale/downscale node group all nodes in nodegroup start updating.
Need for Deckhouse UI. 
```changes
type: fix
summary: Prevent changing bashible checksum if scale/downscale nodegroup.
```
> [bashible-api-server] Prevent changing bashible checksum if scale/downscale nodegroup

- modules/490-virtualization/hooks/internal/v1alpha1/virtualmachine_types.go
- modules/490-virtualization/hooks/vm_handler.go
- Set default bus to `virtio` for diskAttachments
- Unset `virtio` bus for cloud-init drive
Virtio is faster by default. Let's use it by default for all drives.
While cloud-init does not require to be virtio due to better compatibility with various OSes 
All VMs will use virtio by default for disk attachments and use no virtio for cloud init drive
```changes
type: fix
summary: Set default bus to `virtio` for diskAttachments
---
type: fix
summary: Unset `virtio` bus for cloud-init drive
```
> [virtualization] Set bus for diskAttachments

- modules/490-virtualization/images/artifact/patches/008-fix-admissionreview.patch
- modules/490-virtualization/images/artifact/patches/README.md
This PR adds patch to fix AdmissionReview for KubeVirt
When VM pods are created they does not pass admission review due to KubeVirt bug.
Thus linstor-scheduler-admission can't assign correct `schedulerName: linstor` for the VM pods
All the VM pods on linstor will have `schedulerName: linstor` specified
```changes
type: fix
summary: Fix AdmissionReview for KubeVirt virtual machines
```
> [virtualization] Fix AdmissionReview

- modules/340-monitoring-custom/docs/README.md
- modules/340-monitoring-custom/docs/README_RU.md
- modules/340-monitoring-custom/templates/pod-monitor.yaml
- modules/340-monitoring-custom/templates/service-monitor.yaml
Set a new default value for services and Pods.
The current value is too low and permanently causes application metrics to be unavailable.
```changes
section: monitoring-custom
type:  chore
summary: Set a new default value for services and Pods.
```
> [monitoring-custom] Set by default limit 5000

- modules/340-extended-monitoring/images/image-availability-exporter/Dockerfile
Get a new `image-availability-exporter` docker image with `batchv1/CronJob` support.
Upstream PR: https://github.com/deckhouse/k8s-image-availability-exporter/pull/68
Kubernetes 1.25+ does not support `batch/v1beta1` anymore. So, `image-availability-exporter` is not able to start.
```changes
type: fix
summary: Fix `image-availability-exporter` for Kubernetes 1.25+.
```
> [monitoring] Fix image availability exporter

- modules/340-extended-monitoring/templates/image-availability-exporter/rbac-for-us.yaml
Fix RBAC ClusterRole for exporter
We have an error:
```
W0410 08:03:53.965246       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:d8-monitoring:image-availability-exporter" cannot list resource "serviceaccounts" in API group "" at the cluster scope
E0410 08:03:53.965289       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169: Failed to watch *v1.ServiceAccount: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:d8-monitoring:image-availability-exporter" cannot list resource "serviceaccounts" in API group "" at the cluster scope
W0410 08:04:22.904852       1 reflector.go:424] …
```
> [monitoring] Fix rbac rules for image-availability-exporter

- modules/030-cloud-provider-gcp/templates/cloud-controller-manager/deployment.yaml
Disable `PodCIDR` assignment in the CCM.
There is an IPAM controller enabled by default in GCP CCM. It races with kube-controller-manager that produces same `PodCIDR` for two Nodes.
Only one Node IPAM controller runs in the cluster. The one in the kube-controller-manager.
```changes
type: fix
summary: Disabled Node IPAM in GCP CCM that conflicted with kube-controller-manager's IPAM controller
```
> [cloud-provider-gcp] Disable nodeipam in GCP CCM

- modules/402-ingress-nginx/hooks/migrate_daemonset_and_pods.go
- modules/402-ingress-nginx/hooks/migrate_daemonset_and_pods_test.go
Migrate only old pods, without OpenKruise labels
Hook can act many times and set unneeded labels during the rollout process
We can avoid it with more strict labels selector
```changes
type: fix
summary: Improve controller migration hook.
```
> [ingress-nginx] Improve migration hook

- modules/402-ingress-nginx/templates/kruise/manager.yaml
Set `imagePullSecrets` for `kruise-controller`.
Image-availability-exporter requires this link to the secret for work
It doesn't respect containerd requirements
```changes
type: fix
summary: Set `imagePullSecrets` for `kruise-controller`.
```
> [ingress-nginx] set imagePullSecrets for kruise-controller

- modules/040-node-manager/hooks/internal/conditions/calculate.go
- modules/040-node-manager/hooks/update_node_group_status.go
- modules/040-node-manager/hooks/update_node_group_status_test.go
Stabilize node group error condition.
Often we see `Started Machine creation process` or we do not see error when node group is in error.
See [this](https://github.com/deckhouse/deckhouse/pull/4367/files#diff-9e81af91baf05718041369f0cbc3133f589d2664f2ab94e0567a37a18044d2ceR161) comment for more information 
```changes
type: fix
summary: Fix error node group condition
```
> [node-manager] Fix error node group condition

- modules/002-deckhouse/images/webhook-handler/werf.inc.yaml
- modules/300-prometheus/images/prometheus/Dockerfile
- modules/300-prometheus/images/prometheus/sample_limit_annotation.patch
- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Bump Prometheus
Better performance, less bugs.
Prometheus will be restarted.
```changes
section: promtheus
type: fix
summary: Update Prometheus to 2.43.0 (bug and security fixes, performance improvements)
```
> [prometheus] Update to 2.43.0

- modules/150-user-authn/hooks/generate_crowd_basic_auth_proxy_cert.go
- modules/150-user-authn/hooks/generate_crowd_basic_auth_proxy_cert_test.go
Fix job image path in user-authn
After switch to sha256 we have problem with job container image generation in user-authn
Correct job creation in user-authn
Some clusters got stuck due to hook error:
failed: object is being deleted: jobs.batch "crowd-proxy-cert-generate-job" already exists
Job pods couldn't be created.
```changes
type: fix
summary: Fix job image path in user-authn
```
> [user-authn] fix in job image

- werf.yaml
This PR removes Helm binary from Deckhouse image.
Having Helm binary in Deckhouse image carries only debugging purpose.
But keeping it in sync with Helm lib in go.mod requires addition effort, and sometimes it'll get out of sync, causing inability to use Helm for debugging.
Deckhouse pod doesn't force read-only, so it's easy to download it manually.
This PR closes #4277.
Well, as a bonus, we will save 40MB.
Helm binary is removed from Deckhouse image:
```changes
type: chore
summary: Remove Helm binary from Deckhouse image
```
> [deckhouse] Remove Helm binary from Deckhouse image

- modules/040-node-manager/hooks/handle_draining.go
- modules/040-node-manager/hooks/handle_draining_test.go
- modules/040-node-manager/hooks/update_approval.go
- modules/040-node-manager/hooks/update_approval_test.go
- modules/040-node-manager/hooks/update_node_group_status_test.go
Add annotation for user-initiated node drain
We need to separate 2 draining sources:
- bashible
- user
Bashible drain is fully handled by deckhouse, so we don't need any manual operations here.
User drain is initiated via the annotation and then user have to uncordon node manually
```changes
type: feature
summary: Add annotation `update.node.deckhouse.io/draining=user` for starting node drain process
```
> [node-manager] User draining

- modules/021-cni-cilium/templates/configmap.yaml
Enable external access to ClusterIP services.
Need in cases when clients want to have access to services inside cluster(thru vpn for example).
```changes
type: feature
summary: Enable external access to ClusterIP services
impact: cilium pods should be restarted
```
> [cni-cilium] Enable external access to ClusterIP services

- modules/340-extended-monitoring/hooks/alert_old_annotation.go
- modules/340-extended-monitoring/hooks/alert_old_annotation_test.go
Replaced batch/v1beta1 with batch/v1.
batch/v1beta1 is not supported anymore.
Everything works in newer Kubernetes versions.
```changes
type: fix
summary: Use the `batch/v1` API version instead of the `batch/v1beta1`.
```
> [extended-monitoring] batch/v1beta1 -> batch/v1

- .github/ci_templates/e2e_tests.yml
- .github/scripts/js/e2e/cleanup.js
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- testing/cloud_layouts/script.sh
- testing/cloud_layouts/wait-master-ssh-and-update-comment.sh
Fix output only grey IP in e2e tests.
Close #3992
e2e should output bastion `user@ip` in e2e tests (static).
Tested [here](https://github.com/deckhouse/deckhouse-test-2/pull/299).
```changes
section: ci
type: fix
summary: Fix output only grey IP in e2e tests.
```
> [ci] Fix output only grey IP in e2e tests 

- modules/140-user-authz/webhooks/validating/cluster_authorization_rule
Fixed string splitting in bash `for` loop.
Incorrectly splits JSON documents that have whitespaces in its elements.
It blocks creating ClusterAuthorizationRules with fields with whitespaces in it.
Whitespaces in ClusterAuthorization do not crash the script anymore.
```changes
type: fix
summary: Fixed cluster_authorization_rule webhook so that it doesn't crash on fields with whitespaces anymore
```
> [user-authz] Fixed bash in cluster_authorization_rule webhook

- modules/300-prometheus/hooks/alertmanager_crd_discovery_test.go
- modules/300-prometheus/template_tests/multiple_custom_alert_managers_test.go
- modules/300-prometheus/templates/alertmanager/internal/alertmanagerconfig.yaml
Add three dashes `---` to separate resources in alertmanagerconfig.yaml Helm template. Add tests.
In Helm templates you MUST separate resources with three dashes `---`.
Close #3369 
Fixed creation of multiple CustomAlertmanager resources.
```changes
type: fix
summary: Fixed creation of multiple CustomAlertmanager resources.
```
> [prometheus] Fix AlertmanagerConfig Heml template

- modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
This PR adds following note in `D8TerraformStateExporterClusterStateError` and `D8TerraformStateExporterNodeStateError` if  `cloud-provider-aws` is enabled:
```
Also, it can occur because of missing permissions for the following actions in configured AWS IAM policy that were first used in Deckhouse v1.45:
1. `ec2:DescribeInstanceTypes`,
2. `ec2:DescribeSecurityGroupRules`.
```
This PR was tested manually on AWS cluster with corresponding permissions missing:
Since https://github.com/deckhouse/deckhouse/pull/4256 the permissions above are essential for AWS Terraform Provider to function correctly, but there is a common case when this permission are missing on existing cluster.
We need to inform CE users of existing AWS clusters of the newly required permissions.
Information about …
> [cloud-provider-aws][monitoring] Document missing IAM permissions in corresponding alerts for Deckhouse >= 1.45

- ee/modules/500-operator-trivy/images/operator/patches/003-support-legacy-dockercfg.patch
- ee/modules/500-operator-trivy/images/operator/patches/README.md
Add support for `kubernetes.io/dockercfg` (legacy) secrets in `imagePullSecrets` pods field for scan jobs.
Some of the clusters have secrets with type `kubernetes.io/dockercfg` (legacy) that are used in `imagePullSecrets` field, so we should treat them in the operator to avoid 401 error in scan jobs
Scan jobs for pods with secrets with type `kubernetes.io/dockercfg` in `imagePullSecrets` field are not failing
```changes
type: fix
summary: Add support for kubernetes.io/dockercfg secrets in imagePullSecrets pods field for scan jobs.
```
> [operator-trivy] Add support for `kubernetes.io/dockercfg` secrets in `imagePullSecrets` pods field for scan jobs

- .github/CODEOWNERS
Change owner for `deckhouse-controller/` directory
Yuriy should be codeowner of `deckhouse-controller/`.
```changes
section: ci
type: chore
summary: Change owner for deckhouse-controller/ directory
```
> [ci] Change owner for deckhouse-controller/ directory

- modules/021-cni-cilium/monitoring/grafana-dashboards/kubernetes-cluster/cilium-agent.json
Update Grafana dashboard for Cilium v1.12 agent.
Grafana dashboard version should match Cilium version.
Close #4393 
```changes
type: fix
summary: Update Grafana dashboard for Cilium agent
```
> [cni-cilium] Update Grafana dashboard for Cilium agent

- tools/release/d8-pull-tarball.sh
- tools/release/d8-pull.sh
- tools/release/d8-push.sh
Fix d8-push.sh and d8-pull.sh scripts to proper evaluate digests. Save previous d8-pull.sh to d8-pull-tarball.sh for trivy scanning. 
After move from tags to digests d8-pull.sh script can't be used, because it saves images in taballs with different digests. This PR is fixing this.
Proper pushing images to registry
```changes
section: tools
type: fix
summary: Fix d8-push.sh and d8-pull.sh scripts
```
> [tools] Fix `d8-push.sh` and `d8-pull.sh` scripts

- candi/bashible/bundles/centos/node-group/031_install_containerd.sh.tpl
- candi/bashible/bundles/debian/node-group/031_install_containerd.sh.tpl
- candi/bashible/bundles/ubuntu-lts/node-group/031_install_containerd.sh.tpl
- ee/candi/bashible/bundles/alteros/node-group/031_install_containerd.sh.tpl
- ee/candi/bashible/bundles/astra/node-group/031_install_containerd.sh.tpl
- ee/candi/bashible/bundles/redos/node-group/031_install_containerd.sh.tpl
Remove /var/lib/cni/networks/cbr0/* on docker->containerd migration.
Flannel has dir to store used pod ip addresses (/var/lib/cni/networks/cbr0). If node has many pods, after migration to containerd pods are restarted and flannel tries to assign new ip addresses to pods. But almost all of pod ip addresses marked as used, because we cannot clean /var/lib/cni/networks/cbr0 directory on docker->containerd migration.
Pods fail to start with message 
```
Warning  FailedCreatePodSandBox  9m55s (x475 over 117m)  kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "27160a7396731fab0b66773efde66e8b570f33d3aeb64967bdc12b0726d40cee": plugin type="flannel" failed (add): failed to delegate add: failed to allocate …
```
> [bashible] fix cleanup flannel used ips on migration from docker to containerd

- ee/modules/040-node-manager/openapi/config-values.yaml
Add `altlinux` to the default values list of the [`allowedBundles`](https://deckhouse.io/documentation/latest/modules/040-node-manager/configuration.html#parameters-allowedbundles) parameter (EE edition).
Alt Linux support was added in Deckhouse EE 1.45. The `allowedBundles` parameters should include all possible bundles by default.
It is a minor change and can be skipped in the patch.
```changes
type: chore
summary: Add `altlinux` to the default values list of the [`allowedBundles`](https://deckhouse.io/documentation/latest/modules/040-node-manager/configuration.html#parameters-allowedbundles) parameter (EE edition).
```
> [chore][node-manager] Update the default value of the allowedBundles parameter

- docs/documentation/modules_menu_skip
- modules/010-cloud-data-crd/docs/README.md
- modules/010-cloud-data-crd/docs/README_RU.md
Remove the `cloud-data-crd` module from the site.
> [cloud-data-crd] Minor doc fixes

- modules/041-linstor/images/linstor-csi/Dockerfile
- modules/041-linstor/images/linstor-csi/patches/README.md
- modules/041-linstor/images/linstor-csi/patches/requisites.patch
Sometimes Kubernetes may request multiple requisites in topology in CreateVolume request.
This patch considers just the first one as the requested node.
upstream: https://github.com/piraeusdatastore/linstor-csi/pull/196
fixes https://github.com/piraeusdatastore/linstor-csi/issues/195
Some of our clients already using this feature
Some scheduling errors will gone
```changes
type: fix
summary: Fix multiple requisites in volume placement request
```
> [linstor] Fix multiple requisites

- modules/490-virtualization/hooks/disk_handler.go
- modules/490-virtualization/hooks/disk_handler_test.go
- modules/490-virtualization/hooks/vm_handler.go
- modules/490-virtualization/hooks/vm_handler_test.go
This PR fixes some cases of processing VirtualMachineDisks
- Releasing disk lease when VM is not removed but disk is not attached
- Copying VirtualMachineDisk from VirtualMachineDisk
Fix already existing cases, I checked cherry-pick works fine
The above problems fixed
```changes
type: fix
summary: fix releasing disk lease when VM is not removed but disk is not attached
impact: low
---
type: fix
summary: fix copying VirtualMachineDisk from VirtualMachineDisk
impact: low
```
> [virtualization] fix disks processing

- global-hooks/migrate/migrate_descheduler.go
Restored descheduler config-to-CR migration hook.
Has been deleted in https://github.com/deckhouse/deckhouse/pull/4016/files#diff-86dc37896afb6eceaa9b1da3da51da09170dee0531cb2e3b89473b98c20f7ac1L17
Current releases are silently disable descheduler configuration.
Descheduler config is correctly migrated.
```changes
type: fix
summary: Restored descheduler migration hook
```
> [descheduler] Restored migration hook

- modules/000-common/images/kubernetes/werf.inc.yaml
- modules/007-registrypackages/images/kubeadm/werf.inc.yaml
- modules/007-registrypackages/images/kubectl/werf.inc.yaml
- modules/007-registrypackages/images/kubelet/werf.inc.yaml
- modules/021-kube-proxy/images/kube-proxy/werf.inc.yaml
- modules/040-control-plane-manager/images/control-plane-manager/werf.inc.yaml
- modules/040-control-plane-manager/images/kube-apiserver/werf.inc.yaml
- modules/040-control-plane-manager/images/kube-controller-manager/werf.inc.yaml
- modules/040-control-plane-manager/images/kube-scheduler/werf.inc.yaml
Include patch version in common kubernetes image artifact name.
Before this PR common kubernetes artifact name was something like`common/kubernetes-artifact-1-24`.
Now it is include patch version of kubernetes, so name is `common/kubernetes-artifact-1-24-3`.
It allows us to avoid permanent rebuild via branches during the kubernetes patch version bump
```changes
section: candi
type: chore
summary: include patch version in common kubernetes image artifact name
```
> [candi] include patch version in common kubernetes image artifact name

- modules/000-common/images/kubernetes/werf.inc.yaml
Added env variable GO_VERSION.
Kubernetes build expects GO_VERSION env variable to be set to current go version. If this variable is not set, kubernetes build tries to autodetect go version with gimme tool and downloads go sources, slowing down the build.
```changes
section: candi
type: chore
summary: speed up kubernetes build 
```
> [candi] speed up kubernetes build

- candi/bashible/bundles/altlinux/node-group/031_install_docker.sh.tpl
- modules/040-node-manager/images/bashible-apiserver/README.md
Without this fix, bashible-apiserver in kubernetes clusters with docker does not work
bashible apiserver log
```
I0503 06:57:23.560006       1 trace.go:205] Trace[734617307]: "Get" url:/apis/bashible.deckhouse.io/v1alpha1/bashibles/ubuntu-lts.master,user-agent:kubectl/v1.23.17 (linux/amd64) kubernetes/953be89,client:192.168.199.112 (03-May-2023 06:57:21.883) (total time: 1676ms):
Trace[734617307]: [1.676145184s] [1.676145184s] END
I0503 06:57:23.562712       1 context.go:350] Running context update. (Source: 'NodeUserConfiguration')
I0503 06:57:23.573584       1 trace.go:205] Trace[1809769494]: "Get" url:/apis/bashible.deckhouse.io/v1alpha1/bashibles/ubuntu-lts.system,user-agent:kubectl/v1.23.17 (linux/amd64) kubernetes/953be89,client:192.168.199.105 (03-May-2023 06:57:21.766) (total …
```
> [node-manager] Fix bashible altlinux docker containerd version

- modules/150-user-authn/webhooks/validating/user
Added validating webhook to check for unique userID and email in User object
userID and email must be unique for all static users
```changes
type: feature
summary: Added validating webhook to check for unique userID and email in User object
```
> [user-authn] Add check for unique of userID and email in User object

- modules/040-node-manager/hooks/handle_draining.go
- modules/040-node-manager/hooks/handle_draining_test.go
Create event when node drain was failed
This event will bind to a Node object and we will be able to find drain failure reason easily
It's hard to figure out drain failure reason from deckhouse logs
Event will be created in the `default` namespace:
```bash
apiVersion: v1
items:
- action: Binding
apiVersion: v1
eventTime: "2023-05-03T19:22:20.036930Z"
firstTimestamp: null
involvedObject:
kind: Node
name: ndev-worker-5e11c78a-5f688-zmmjb
resourceVersion: "106354301"
uid: 5dbe53d3-3d6d-4074-a807-5faa130fee45
kind: Event
lastTimestamp: null
message: "drain failure reason"
metadata:
creationTimestamp: "2023-05-03T19:23:52Z"
generateName: node-ndev-worker-5e11c78a-
name: ndev-worker-5e11c78a-5f688-zmmjb
namespace: default
resourceVersion: "106354767"
uid: …
```
> [node-manager] Create event if node drain failed

- modules/462-loki/templates/logshipper-log-destination.yaml
ClusterLogDestination CR uses d8-loki namespace instead of d8-monitoring
At the moment the current configuration with the specified service in d8-loki namespace does not work
This fix may be in the patch release
```changes
section: loki
type: fix
summary: Fix ClusterLogDestination loki endpoint
```
> fix ClusterLogDestination loki endpoint

- deckhouse-controller/cmd/deckhouse-controller/main.go
- go.mod
- go.sum
Use a library to automatically set gomaxprocs env variable according to the deckhouse container limits. By default, it equals to the number of cores of the node.
https://github.com/uber-go/automaxprocs
Should improve performance on the servers with many cores, e.g., baremetal installations
```changes
type: feature
summary: Automatically set GOMAXPROCS according to container limits
```
> [deckhouse-controller] Add autogomaxprocs

- modules/002-deckhouse/docs/USAGE.md
- modules/002-deckhouse/docs/USAGE_RU.md
- modules/002-deckhouse/hooks/check_deckhouse_release.go
- modules/002-deckhouse/hooks/check_deckhouse_release_test.go
- modules/002-deckhouse/hooks/cleanup_deckhouse_releases_test.go
- modules/002-deckhouse/hooks/update_deckhouse_image_test.go
Remove Deckhouse release naming transformation
```changes
type: fix
summary: Remove Deckhouse release naming transformation.
```
> [deckhouse] Remove Deckhouse release naming transformation

- modules/150-user-authn/docs/README.md
- modules/150-user-authn/docs/README_RU.md
Remove the "Integration with Kubernetes and Deckhouse" section from the documentation of the `user-authn` module.
```changes
type: chore
summary: 'Remove the "Integration with Kubernetes and Deckhouse" section from the documentation.'
```
> [user-authn][docs] Remove the "Integration with Kubernetes and Deckhouse" section

- candi/bashible/detect_bundle.sh
- candi/version_map.yml
- testing/library/images_tags_generated.go
Added ALT Linux 10.1 support
```changes
section: candi
type: feature
summary: Added ALT Linux 10.1 support
```
> [candi] Add ALT Linux 10.1 support

- modules/041-linstor/hooks/read_passphrase.go
Fix on-live update passphrase hook
When user adds passphrase for linstor, deckhouse will reconcile it only after restart
User can add passphrase for linstor without restarting deckhouse pod
```changes
type: fix
summary: Fix passphrase reconcilation
```
> [linstor] Fix passphrase reconcilation

- modules/200-operator-prometheus/templates/operator.yaml
Added secret-field-selector
Eliminates unnecessary secrets from surveillance
```changes
type: fix
summary: Added secret-field-selector in args.
```
> [operator-prometheus] added secret-field-selector

- candi/bashible/bundles/centos/bootstrap.sh.tpl
- candi/bashible/detect_bundle.sh
- ee/candi/bashible/bundles/alteros/bootstrap.sh.tpl
- ee/candi/bashible/bundles/redos/bootstrap.sh.tpl
- ee/candi/bashible/detect_bundle.sh
Refactor bootstrap scripts to fit 16kb limit of cloud-data. Backport of https://github.com/deckhouse/deckhouse/pull/4580.
In AWS cloud provider size of bootstrap scripts is limited to 16kb. We need to precisely write the bash bootstrap code to avoid exceeding the limit.
```changes
section: candi
type: fix
summary: Refactor bootstrap scripts to fit 16kb limit of cloud-data.
```
> [candi] refactor bootstrap scripts to fit 16kb limit of cloud-data

- modules/491-containerized-data-importer/templates/cdi.yaml
Enable HonorWaitForFirstConsumer for CDI
This solves problem of correct provisioning PVs for virtual machines using WaitForFirstConsumer storage-class
We already have clients using this feature
CDI will wait until VM pod appears before scheduling importer pod
```changes
section: containerized-data-importer
type: fix
summary: Enable `HonorWaitForFirstConsumer`.
```
> [containerized-data-importer] Enable HonorWaitForFirstConsumer

- global-hooks/migrate/migrate_descheduler.go
- modules/400-descheduler/hooks/migrate_from_cm.go
- modules/400-descheduler/hooks/migrate_from_cm_test.go
Create a default Descheduler instance even if no config is present.
Descheduler instance was configured automatically if `descheduler` module is enabled. Continue this fine tradition.
Deschedulers are disabled by default. This is a breaking change.
Default descheduler instance is created with the following config:
```yaml
"removePodsViolatingInterPodAntiAffinity": true,
"removePodsViolatingNodeAffinity": true
```
```changes
type: fix
summary: Create a default Descheduler instance.
```
> [descheduler] Provided a proper migration

- global-hooks/discovery/cluster_dns_address.go
- global-hooks/discovery/cluster_dns_address_test.go
Take cluster dns address from service with `kube-dns` name if there are multiply clusterIp services labeled `k8s-app: kube-dns` in cluster.
E.g.:  enable node-local-dns plugin in GKE, to deploy two services with same labels `k8s-app: kube-dns` and selectors  named `kube-dns` and `kube-dns-upstream`,
after that cluster dns address fails with error `"ERROR: can't find a single kube-dns service`
```changes
type: fix
summary:  Fix cluster dns address discovery
```
> [global-hooks] Fix cluster dns address discovery

- candi/bashible/common-steps/all/001_disable_swap.sh.tpl
Remove swap entries from /etc/fstab after checking for such an entry
The /etc/fstab file was modified every time bashible was started
```changes
section: candi
type: fix
summary: Remove swap entries from /etc/fstab after checking for such an entry
```
> [candi] Disable swap entry in /etc/fstab

- modules/402-ingress-nginx/images/controller-1-1/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-1-6/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/protobuf-exporter/rootfs/etc/protobuf_exporter/mappings.yaml
- modules/402-ingress-nginx/monitoring/grafana-dashboards/ingress-nginx/namespace/namespace_detail.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/ingress-nginx/namespace/namespaces.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/kubernetes-cluster/controller-detail.json
- modules/402-ingress-nginx/monitoring/grafana-dashboards/kubernetes-cluster/controllers.json
Add labels to the default backend request metric: ingress, service, location.
The default backend can handle requests to different locations. We need to split metric for different locations. 
ingress_nginx_default_backend_requests_total metric MUST contain 3 new labels - ingress, service, location
```changes
type: feature
summary: The default backend request metric contain ingress, service, and location labels
```
> [ingress-nginx] Add detailed default backend metrics

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
Add `-w table` parameters for `member list` and `endpoint status`.
Now, commands output table with header.
Many clients are confused with `false` in last column.
```changes
type: chore
summary: Add `-w table` parameters for `member list` and `endpoint status`.
```
> [control-plane-manager] Add `-w table` parameters for `member list` and `endpoint status`

- docs/documentation/_data/sidebars/main.yml
- docs/site/_config.yml
Add the experimental badge to the `runtime-audit-engine` and `operator-trivi` modules documentation.
The experimental badge in the `runtime-audit-engine` and `operator-trivi` modules documentation.
```changes
section: docs
type: chore
summary: Add the experimental badge to the `runtime-audit-engine` and `operator-trivi` modules documentation.
```
> [docs]  Add the experimental badge onto the runtime-audit-engine and  `operator-trivi` modules.

- candi/cloud-providers/aws/bashible/common-steps/bootstrap-networks.sh.tpl
Bashible script for network bootstrap in AWS has been updated to use the new version of [ec2_describe_tags](https://github.com/flant/go-ec2-describe-tags/releases/tag/v0.0.1-flant.2) binary, supporting AWS IMDSv2. 
Current implementation of bashible networking bootstrap in AWS cloud uses AWS IMDSv1 that fails to bootstrap a node in case IMDSv1 is disabled (by policies or/and there is IMDSv2=required setting in the AMI that is used for VM creation).
Switching to the new version of the binary overcomes the bootstrapping issue for the IMDSv2-required nodes and doesn't affect the nodes where IMDSv2 isn't mandatory as IMDSv2 is also available on such nodes.
Close #4583
An AWS node bootstrap process should be successfully regardless of the version of IMDS set for the node.
```changes
section: …
```
> [bashible] update ec2_describe_tags binary version to support IMDSv2

- candi/cloud-providers/aws/openapi/cluster_configuration.yaml
Change default etcd disk type from gp2 to gp3 and  disk size from 150GB to 20GB.
This is necessary to reduce costs.
```changes
type: chore
summary: Change default etcd disk type from gp2 to gp3 and  disk size from 150GB to 20GB.
```
> [cloud-provider-aws] Change default etcd disk size and type

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Sometimes users encounter questions about strange errors when using the `d8-push.sh` script (for example, [question in telegram](https://t.me/deckhouse_ru/19356) and [solution](https://t.me/deckhouse_ru/19523)). So we can add note about specifying registry path for `d8-push.sh` script
```changes
section: docs
type: chore
summary: Add note about specifying registry path for `d8-push.sh` script.
```
> [docs] Add note about specifying registry path for `d8-push.sh` script

- modules/002-deckhouse/images/webhook-handler/werf.inc.yaml
- modules/300-prometheus/images/prometheus/Dockerfile
Move from the stringlabels tagged version to the stable version.
Related https://github.com/deckhouse/deckhouse/pull/4269
Bugfixes to new prometheus storage format.
```changes
section: promtheus
type: chore
summary: Bump Prometheus 2.44.0
```
> [prometheus] Bump 2.44.0

- modules/300-prometheus/images/grafana-dashboard-provisioner/hooks/dashboard_provisioner.py
Add error handler for dasboard definition json unmarshalling
If we have a malformed dashboard hook will fail and stuck. No other dashboards would be rendered.
Hook blocks dashboard provisioning and we can have a situation when all dashboards in the Grafana are absent.
New hook handles error, reports about malformed dashboard and skip it:
```
{"binding":"dashboard_resources","event":"kubernetes","hook":"dashboard_provisioner.py","level":"info","msg":"Execute hook","queue":"main","task":"HookRun","time":"2023-05-19T08:48:42Z"}
{"binding":"dashboard_resources","event":"kubernetes","hook":"dashboard_provisioner.py","level":"info","msg":"ERROR: Dashboard 'foobar' contains errors: Expecting property name enclosed in double quotes: line 2 column 3 (char …
```
> [prometheus] Handle grafana dashboard's json unmarshaller error

- docs/documentation/_includes/search.liquid
- docs/documentation/_plugins/custom_hooks.rb
Updated search index to make available search module by the `<module>Enabled` or `<module>Disabled` word.
Users could not find anything by the `<module>Enabled` or `<module>Disabled`, which is used in the InitConfigration resource.
When you search in the documentation by cniCiliumDisabled or cniCiliumEnabled you should get at least a page to the cni-cilium module.
```changes
section: docs
type: chore
summary: Add ability to search module documentation by the `<module>Enabled` or `<module>Disabled` word.
```
> [docs] Update search index to search by the <Module>[Enabled|Disabled] parameter

- modules/002-deckhouse/hooks/enable_extended_monitoring_test.go
- modules/400-descheduler/templates/namespace.yaml
- modules/402-ingress-nginx/templates/namespace.yaml
Deckhouse objects are erroneously alerted on. 
A user of a cluster has no way of acting upon such alert.
Deckhouse-managed objects are not included in the alert.
```changes
type: fix 
summary: Remove D8 objects from the `DeprecatatedAnnotation` alert.
```
> [extended-monitoring] Removed deprecated annotations from Deckhouse-managed objects

- ee/modules/350-node-local-dns/images/iptables-loop/iptables-loop.sh
Added logs if changed state iptables
It is not clear from the logs when and how often the state changed.
```changes
type: fix 
summary: Added logs if changed state iptables.
```
> [node-local-dns] added logs if changed state iptables

- dhctl/pkg/kubernetes/actions/deckhouse/pod.go
Add to debug log information about error got during getting deckhouse pod.
When we got error during getting deckhouse pod we get `No Deckhouse pod found.` error only, without root cased error.
We should output it to debug log
```changes
section: dhctl
type: chore
summary: Add to debug log information about error got during getting deckhouse pod
```
> [dhctl] Add to debug log information about error got during getting deckhouse pod

- modules/041-linstor/images/linstor-pools-importer/main.go
- modules/041-linstor/images/linstor-pools-importer/main_test.go
- modules/041-linstor/templates/linstor-affinity-controller/deployment.yaml
This PR enables WaitForFirstConsumer for all auto-generated storageclasses for linstor
This is approved part from https://github.com/deckhouse/deckhouse/pull/4500 to enhance data-locality but not totally enforce it.
```changes
type: fix
summary: Enable `WaitForFirstConsumer`.
impact: |
- all auto-generated linstor storageclasses will be recreated with WaitForFirstConsumer option.
- all existing Persistent Volumes do not require any update or modifications.
```
> [linstor] enable WaitForFirstConsumer

- modules/015-admission-policy-engine/crds/operation-policy.yaml
- modules/015-admission-policy-engine/monitoring/grafana-dashboards/security/admission-policy-engine.json
Admission-policy-engine security dashboard definition in Grafana has been updated:
* Previously disabled and incorrect query has been removed;
* The query type has been changed to instant (from vector) and grouping by time has been removed.
OperationPolicy CRD has been updated:
* spec.policies.requiredLabels.watchKinds pattern regex expression has been fixed (wasn't working as it was intended)
Previously, OPA Violations table showed multiple entries for the same violations with different timestamps (range vector), rendering the whole table pretty cumbersome. After the aforementioned changes the table includes only unique records for the violating objects for the selected period of time.
Close #4415 
OPA Violations table of Admission-policy-engine Dashboard in Grafana shows only unique …
> [admission-policy-engine] update grafana dashboard definition

- modules/490-virtualization/hooks/utils.go
- modules/490-virtualization/hooks/vm_handler.go
- modules/490-virtualization/hooks/vm_handler_test.go
This PR includes two fixes:
hooks failing and stop processing other VMs in case of error of `setVMfields` for single VM:
```
2023-04-11T09:11:35Z [error][virtualization] - Module hook failed, requeue task to retry after delay. Failed count is 25. Error: 1 error occurred:
* Filter object kubevirt.io/v1/VirtualMachine/infra/test-0: cloud-config variables can only be appended to userData section
```
nil pointer exception when creating VirtualMachineDisk not from registry source:
```
deckhouse-f84765c85-qfktk deckhouse {"binding":"onStartup","event.type":"OperatorStartup","hook":"490-virtualization/hooks/ensure_crds.go","hook.type":"module","level":"info","module":"virtualization","msg":"Module hook start …
```
> [virtualization] Minor fixes

- modules/041-linstor/images/linstor-pools-importer/main.go
This change fixes the case when linstor-pools-importer not reconciling seen pools which have tags updated
fixes https://github.com/deckhouse/deckhouse/issues/2728
and possible fixes https://github.com/deckhouse/deckhouse/issues/3142
linstor-pools-importer will start reconciling any changes in tags for the existing VGs
```changes
type: fix
summary: Reconcile LVM pool updates
```
> [linstor] Reconcile LVM pool updates

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/namespace/namespace.json
Removed duplicates.
`Main / Namespace` dashboard had two duplicates of memory graphs in `Usage by controller` and `Over-requested by controller`. It is brought into line with `Main / Namespaces` and `Main / Namespaces / Controller dashboard`.
Before:
After:
And now it matches other dashboards:
```changes
type: fix
summary: Remove duplicates of memory graphs on namespace dashboard
```
> [monitoring-kubernetes] Remove duplicates of memory graphs on namespace dashboard

- modules/041-linstor/templates/linstor-controller/linstorcontroller.yaml
Disable the `auto-resync-after` option on the cluster level.
It seems this is a new and currently unstable feature. At the moment, it's doing us more harm than good.
The devices will not wait for each other to start syncing.
```changes
type: fix
summary: Disable the `auto-resync-after` option.
```
> [linstor] Disable auto-resync-after

- candi/bashible/common-steps/all/098_remove_old_binaries.sh.tpl
Force deletion of directories.
bashible gets stuck while trying to delete directory `/usr/local/bin/crictl`.
bashible gets stuck while trying to delete directory `/usr/local/bin/crictl`.
bashible is no longer stuck.
```changes
section: candi
type: fix
summary: Force deletion of the `/usr/local/bin/crictl` directory.
```
> [candi] Fixed old bashible deletion

- modules/402-ingress-nginx/hooks/migrate_daemonset_and_pods.go
- modules/402-ingress-nginx/hooks/migrate_daemonset_and_pods_test.go
Add helm `keep resource` annotation
We can have a race when DaemonSet is not deleted by hook and helm tries to delete it with all siblings (pods).
We can set the annotation and prevent helm from deleting this pod
In some cases (I guess it's some kind of race) helm can delete DaemonSet with pods, according to this messages:
```
34m         Normal    SuccessfulDelete                  daemonset/controller-main-host-port               Deleted pod: controller-main-host-port-4pn66
```
Let's add one more protection for this case
```changes
type: fix
summary: Add protection for ingress-nginx-controller daemonset migration.
```
> [ingress-nginx] Add annotation for keeping helm objects

- modules/013-helm/hooks/metrics.go
Fix deprecated k8s resources metrics
There are some mistakes in deprecated resources config
There are some mistakes in deprecated resources config, that are in k8s version 1.25, which we start to support in deckhouse v1.42
```changes
section: helm
type: fix
summary: Fix deprecated k8s resources metrics.
```
> [helm] Fix deprecated k8s resources metrics

- modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/go.mod
- modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/go.sum
- modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/main.go
Provide a proper path for thresholds exporter.
It does not work with kubelet root dir.
It panics on division by zero.
No panics are observed.
```changes
type: fix
summary: Fixed path to hostPath in thresholds-exporter
```
> [monitoring-kubernetes] Fixed thresholds-exporter path

- modules/002-deckhouse/hooks/enable_extended_monitoring.go
- modules/002-deckhouse/hooks/enable_extended_monitoring_test.go
Add prometheus.deckhouse.io/rules-watcher-enabled on d8-system namespace.
We should set label to all namespaces with prometheus rules (see related [pr](https://github.com/deckhouse/deckhouse/pull/4407)). 
But we forget to add label to `d8-system` namespace because we do not have manifest for it. d8-system ns was created by dhctl.
Prometheus rules from d8-system can not be found.
Prometheus rules from d8-system can not be found.
```changes
type: fix
summary: Add prometheus.deckhouse.io/rules-watcher-enabled on d8-system namespace
```
> [deckhouse] Add `prometheus.deckhouse.io/rules-watcher-enabled` on d8-system namespace

- candi/bashible/bashible.sh.tpl
- candi/bashible/common-steps/all/098_remove_old_binaries.sh.tpl
- candi/bashible/common-steps/node-group/000_migrate_containerd_to_cgroupfs.sh.tpl
Fixed a migration that did not include /opt/deckhouse/bin creation. Also save PATH to a previous jq location to avoid breaking the bashible.sh update process.
bashible step failed mid-process due to a previous issue that was addressed in v1.46.1. Here we protect from losing path to a jq binary even more.
More proofing against bashible exploding due to missing jq binary.
jq is always available to bashible.sh main script.
```changes
section: candi
type: fix
summary: Fixed a migration that did not include /opt/deckhouse/bin creation. Also save PATH to a previous jq location to avoid breaking the bashible.sh update process.
```
> [candi] Old binary deletion fixes

- modules/021-cni-cilium/monitoring/prometheus-rules/agent.yaml
Added missing severity levels for Cilium alerts.
All alerts should have a severity_level.
severity_level is present on all alerts.
```changes
type: fix
summary: Added severity_levels to all alerts
```
> [cni-cilium] Added severity_levels for alerts

- modules/402-ingress-nginx/templates/kruise/manager.yaml
Fixed incorrect indentation of `resources` block in `kube-rbac-proxy` container of `kruise-controller-manager` deployment. The issue occurs if module `vertical-pod-autoscaler-crd` is not enabled.
The issue blocks `ingress-nginx` module deployment. Here are logs from deckhouse pod:
```
{"binding":"ConvergeModules","event.type":"OperatorStartup","level":"error","module":"ingress-nginx","msg":"ModuleRun failed in phase 'CanRunHelm'. Requeue task to retry after delay. Failed count is 2. Error: helm upgrade failed: error validating \"\": error validating data: [ValidationError(Deployment.spec.template.spec.containers[1].resources): unknown field \"cpu\" in io.k8s.api.core.v1.ResourceRequirements, ValidationError(Deployment.spec.template.spec.containers[1].resources): unknown field \"memory\" …
```
> [ingress-nginx] Fix kube-rbac-proxy resources indentation

- modules/041-linstor/templates/nodegroupconfiguration-install-kernel-headers.yaml
This PR updates regex for finding orphan kenel-header packages on debian-like distros
Currently it might trigger removing of meta-packages, which will remove the currently installed kernel headers by the dependency:
```
linux-headers-generic-hwe-22.04
linux-headers-virtual-hwe-22.04
```
UPD debian 11 also includes common pachage which should not be deleted:
```
linux-headers-*-common
```
fixes #4801 
Do not remove kernel-headers installed by meta package
We have community users with such issue
If user installed kernel-headers manually they will not be removed
```changes
type: fix
summary: fix kernel-headers cleanup script
```
> [linstor] fix kernel-headers cleanup script

- modules/041-linstor/images/drbd-driver-loader/Dockerfile
- modules/041-linstor/images/drbd-driver-loader/patches/README.md
- modules/041-linstor/images/drbd-driver-loader/patches/chcon.patch
- modules/041-linstor/images/piraeus-operator/patches/README.md
- modules/041-linstor/images/piraeus-operator/patches/add-selinux-params.patch
Added params for enabled SELinux support
In case of enabled SELinux, in linstor module there is a problems with lack of permissions.
Working linstor module on nodes with enabled SELinux
```changes
type: feature
summary: Added params for enabled SELinux support
impact: linstor satellite pods will be restarted
```
> [deckhouse] added selinux security options

- modules/040-control-plane-manager/images/control-plane-manager/controller/converge.go
- modules/040-control-plane-manager/images/control-plane-manager/controller/kubeconfig.go
Fix errors.
Control-plane-manager cannot join new master due to errors in backuping non-existent files.
```changes
section: candi
type: fix
summary: fix errors in control-plane-manager working
impact: control-plane-manager should be restarted
```
> [control-plane-manager] fix errors in control-plane-manager working

- modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring/deprecated-annotation.yaml
Change group in expression for ExtendedMonitoringDeprecatatedAnnotation.
Reduce number of alerts from cluster.
Clients get a lot of disturbing alerts that not critical.
```changes
type: fix
summary: Send one `ExtendedMonitoringDeprecatatedAnnotation` alert per cluster.
```
> [extended-monitoring] Send one ExtendedMonitoringDeprecatatedAnnotation alert per cluster

- modules/035-cni-flannel/images/flanneld/main.go
Fixed argument passing to flannel exec. 
flannel args are not properly passed by entrypoint and therefore ignored.
Due to `--ip-masq` argument not being correctly parsed, flannel forced `bridge` CNI plugin to set masquerade iptables rules by itself resulting in tons of blocking iptables processes. That impacted one of our resource-constrained clusters.
Arguments are passed and parsed correctly.
```changes
type: fix
summary: flannel's entrypoint now correctly passes arguments to the flannel itself.
```
> [cni-flannel] Fixed cmdline passing in entrypoint

- docs/documentation/_data/sidebars/main.yml
- docs/documentation/_plugins/custom_hooks.rb
Fix the module comparison table in the documentation: the experimental badge did show if a module had a special title.
```changes
section: docs
type: fix
summary: Fix the module comparison table in the documentation.
```
> [docs] Fix the module comparison table in the documentation

- go.mod
- go.sum
- modules/003-deckhouse-config/images/deckhouse-config-webhook/go.mod
- modules/003-deckhouse-config/images/deckhouse-config-webhook/go.sum
- tools/go.sum
Revert library update in attempt to fix a panic
Uncontrolled panic of the deckhouse cluster controller
```changes
type: fix
summary: Revert mergo library update.
impact: Deckhouse may panic on concurrent map access.
```
> [deckhouse-controller] Revert mergo

- dhctl/pkg/terraform/executor.go
- dhctl/pkg/terraform/runner.go
Fix `dhctl terraform check` race condition.
Potential race condition in the code 
```changes
section: dhctl
type: fix
summary: Fix cut off terraform output.
```
> [dhctl] Fix cut off terraform output 

- modules/340-monitoring-deckhouse/monitoring/prometheus-rules/node-os-requirements.yaml
These versions of os have reached eol
https://wiki.debian.org/DebianReleases
https://ubuntu.com/blog/ubuntu-18-04-eol-for-devices
```changes
type: feature
summary: added Debian 9 and Ubuntu 18.04 in D8NodeHasDeprecatedOSVersion
```
> [monitoring] added Debian 9 and Ubuntu 18.04 in D8NodeHasDeprecatedOSVersion

- modules/402-ingress-nginx/templates/controller/controller.yaml
Increase `minReadySeconds` for kruise `DaemonSet` for all inlets to 60 sec. Controller won't be restarted if there is only this change.
Avoid fast ingress controller rollout
We want to avoid fast ingress-nginx controllers rollout before going with 1.46 to stable
More smooth ingress-nginx controller rollout
```changes
type: fix
summary: Increase minReadySeconds for all inlets.
```
> [ingress-nginx] Increase minReadySeconds for all inlets

- docs/documentation/_data/sidebars/main.yml
- docs/site/_config.yml
Add the experimental badge to the delivery module documentation.
```changes
section: docs
type: chore
summary: Add the experimental badge to the delivery module documentation.
```
> [docs] Add the experimental badge to the delivery module

- deckhouse-controller/pkg/helpers/change_registry/change_registry.go
- deckhouse-controller/pkg/helpers/register.go
- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
- go.mod
Move `tools/change-registry.sh` to `deckhouse-controller`.
Fix #4328
Fix #4326
```changes
type: feature
summary: Move `tools/change-registry.sh` to `deckhouse-controller`.
```
> [deckhouse-controller] Move `tools/change-registry.sh` to `deckhouse-controller`

- modules/140-user-authz/webhooks/validating/cluster_authorization_rule
Added a check for the ".spec.subjects" field to the cluster_authorization_rule validation webhook to prevent it from being left empty.
The main Deckhouse queue stops when a ClusterAuthorizationRule exists with an empty "subjects" field.
```changes
type: fix
summary: Forbid empty .spec.subject field in ClusterAuthorizationRule
```
> [user-authz] Forbid empty .spec.subject field in ClusterAuthorizationRule

- modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/main.go
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/node-disk-usage.yaml
- Fix eviction threshold percent extraction for the case when they are specified in the kubelet configuration as bytes.
- Fix conditions in `node-disk-usage` prometheus rules
After refactoring of `kubelet-eviction-thresholds-exporter` metric `kubelet_eviction_nodefs_bytes` started returning eviction threshold percent `as-is` (before refactoring it was 100%-eviction threshold).
Conditions in prometheus rules must satisfy the changes that have been made with the metric values.
Some conditions were initially incorrect (the multiplication operation by 100 to calculate percentages was performed in the wrong place).
Another problem is that the metric uses `root-dir` kubelet as the `mountpoint`, and not the mountpoint of this folder.
If the cluster node has only one mountpoint, then in all …
> [monitoring-kubernetes] Fix kubelet-eviction-thresholds-exporter

- deckhouse-controller/pkg/debug/debug.go
- modules/002-deckhouse/docs/FAQ.md
- modules/002-deckhouse/docs/FAQ_RU.md
Add cluster-autoscaler logs into debug logs collector.
Client applications can experience problems if cluster-autoscaler doesn't work properly. It's better to collect its logs in cloud clusters.
```changes
type: chore
summary: Add cluster-autoscaler logs into debug logs collector.
impact_level:  default
```
> [deckhouse] Add cluster-autoscaler logs into debug logs collector

- global-hooks/openapi/config-values.yaml
- modules/010-user-authn-crd/crds/dex-authenticator.yaml
- modules/150-user-authn/openapi/config-values.yaml
- modules/300-prometheus/openapi/config-values.yaml
- modules/402-ingress-nginx/openapi/values.yaml
- modules/500-dashboard/openapi/config-values.yaml
- modules/500-openvpn/openapi/config-values.yaml
- modules/500-upmeter/openapi/config-values.yaml
- modules/810-documentation/openapi/config-values.yaml
Add validation pattern for the ingressClass and IngressCertificateSecretName fields.
We need it to sanitize what values can be passed as names, so that deckhouse reconcile loop wouldn't break in attempts to install objects with invalid names.
Close #4697 
If one attempts to set something similar:
```
metadata:
name: documentation
spec:
enabled: true
version: 1
settings:
ingressClas: nginX
```    
then there is an error 
```
error: moduleconfigs.deckhouse.io "documentation" could not be patched: admission webhook "validate.deckhouse-config-webhook.deckhouse.io" denied the request: spec.settings are not valid (version 1 converted to 2):  1 error occurred: * documentation.ingressClass should match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
``` …
> [global] add ingressClass validation to global hooks and dex

- modules/500-cilium-hubble/templates/ui/authenticator.yaml
Add Ingress TLS enabled condition for secret name rendering.
Fix the bug when clients could not install the `cilium-hubble` module  if the [modules.https.mode](https://deckhouse.io/documentation/v1/deckhouse-configure-global.html#parameters-modules-https-mode) global parameter set to `OnlyInURI`.
```changes
type: fix
summary: Fix the error with the install if the [modules.https.mode](https://deckhouse.io/documentation/v1/deckhouse-configure-global.html#parameters-modules-https-mode) global parameter is `OnlyInURI`.
```
> [cilium-hubble] Fix error with install if global https OnlyInURI

- modules/402-ingress-nginx/images/proxy-failover-iptables/main.go
Proxy-failover-iptables app crashes and duplicates iptables rules on start up.
Close #4943 
The app isn't panicking if http://127.0.0.1:10254/healthz isn't available.
No duplicates in the ingress-failover iptables chain.
```changes
section: nginx-ingress
type: fix
summary: Fix proxy-failover-iptables panicking and iptables rules duplicating.
```
> [nginx-ignress] fix proxy-failover-iptables

- docs/documentation/_data/sidebars/main.yml
- ee/modules/650-runtime-audit-engine/docs/ADVANCED_USAGE.md
- ee/modules/650-runtime-audit-engine/docs/ADVANCED_USAGE_RU.md
- ee/modules/650-runtime-audit-engine/docs/EXAMPLES.md
- ee/modules/650-runtime-audit-engine/docs/EXAMPLES_RU.md
- ee/modules/650-runtime-audit-engine/docs/FAQ.md
- ee/modules/650-runtime-audit-engine/docs/FAQ_RU.md
- ee/modules/650-runtime-audit-engine/docs/README.md
- ee/modules/650-runtime-audit-engine/docs/README_RU.md
- modules/460-log-shipper/docs/ADVANCED_USAGE_RU.md
Add more details to documentation and add advanced usage documentation.
We need to understand how to debug things in Falco.
Close #4031.
```changes
type: feature
summary: Improve documentation and add advanced usage documentation.
```
> [runtime-audit-engine] improve docs

- modules/402-ingress-nginx/crds/ingress-nginx.yaml
Having required to specify the .spec.ingressClass when defining an ingress nginx controller might seem daunting for some users. We can provide default value "nginx" if the field is left blank.
It makes it a bit easier to define an ingress nginx controller.
Close #4799 
In case the .ingressClass isn't provided on create/update, we set it to 'nginx' via crd default field.
```changes
type: feature
summary: Set ingressClass to 'nginx' if not explicitly set.
```
> [nginx-ingress] set default ingress class to nginx

- global-hooks/migrate/migrate_deckhouse-web_mc.go
- global-hooks/migrate/migrate_deckhouse-web_mc_test.go
- modules/810-documentation/hooks/deprecated_mc.go
- modules/810-documentation/monitoring/prometheus-rules/deprecated-mc.yaml
Automatilcally remove `ModuleConfig/deckhouse-web` on migration.
Remove garbage without user actions.
ref: #4982
```changes
type: fix
summary: Remove deckhouse-web mc on migration.
```
> [decumentation] remove deckhouse-web module config on migration

- ee/modules/600-flant-integration/hooks/madison/registration.go
In case there is an empty snapshot for `prometheus-https-mode` secret, use default value "http" instead of "".
Close #4723 
Url schema part for Grafana URL field isn't empty in madison.
```changes
type: chore
summary: Set default schema for Grafana URL to 'http' in case there is problem to fetch data from the cluster.
```
> [flant-integration] set grafana/prometheus scheme to http if snapshot is empty

- modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
Rename D8KruiseControllerPodIsRestartingTooOften alert to D8NginxIngressKruiseControllerPodIsRestartingTooOften so that it's obvious which kruise controller it relates to.
Close #4976 
It easy to tell the difference between the KruiseController alerts from d8-ingress-nginx namespace and other namespaces.
```changes
section: nginx-ingress
type: chore
summary: Rename the alert about malfunctioning kruise controller in d8-ingress-nginx namespace.
```
> [nginx-ingress] rename alert so that it clearly states which kruise controller is affected

- modules/402-ingress-nginx/templates/controller/hpa.yaml
Update HPA version for module `ingress-nginx`. Related to #2759.
Without this change I get helm error.
```
1. ModuleRun:main:ingress-nginx:doStartup:OperatorStartup:failures 111:unable to build kubernetes objects from release manifest: resource mapping not found for name: "hpa-scaler-main" namespace: "d8-ingress-nginx" from "": no matches for kind "HorizontalPodAutoscaler" in version "
autoscaling/v2beta2"
ensure CRDs are installed first
```
Running deckhouse on Managed K8S with version 1.26
This is very minor update.
Using managed 1.26 without errors.
```changes
type: fix
summary: Update apiVersion of HPA
```
> [ingress-nginx] Update HPA apiVersion to support 1.26.

- modules/300-prometheus/openapi/config-values.yaml
- modules/300-prometheus/openapi/doc-ru-config-values.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Adds the way to set custom external labels for the main Prometheus. According to the description: "The labels to add to any time series or alerts when communicating with external systems (federation, remote storage, Alertmanager)". The value of `prometheus` label is set to `deckhouse` by default and can't be changed. It's possible to set label values through resolving the environment variables of the `config-relloader` container( some meaningful examples: `SHARD`, `POD_NAME`, `HOSTNAME`). This env substitution functionality is provided by the `prometheus-config-reloader` binary, so no restart is required.
It allows a user to set custom external labels depending on their needs. 
Close #4673
It is possible to set external labels through the Prometheus module configuration.
```changes …
```
> [prometheus] add external labels knob

- modules/150-user-authn/hooks/get_dex_authenticator_crds.go
- modules/150-user-authn/hooks/get_dex_authenticator_crds_test.go
- modules/150-user-authn/template_tests/authenticator_test.go
* Ease restriction of using tokens received by DexAuthenticators to access the Kubernetes API
This is not possible to deploy web interfaces, that can reuse token to access the Kubernetes API.
```changes
type: feature
summary: Allow users to deploy DexAuthenticator trusted by Kubernetes.
```
> [user-authn] Allow users to deploy DexAuthenticator trusted by Kubernetes

- ee/modules/600-flant-integration/hooks/madison/registration.go
- ee/modules/600-flant-integration/hooks/madison/registration_test.go
- modules/300-prometheus/templates/prometheus-https-mode-secret.yaml
* Updated the Prometheus module's secret `prometheus-https-mode` to `prometheus-url-schema` so that its name corresponds to its function.
* Made some renaming in the Flant-integration Madison Registration hook in accordance with the new Prometheus secret and field names.
* Added tests for getPrometheusURLSchema function to make sure it returns expected values.
The aforementioned changes improve the readability and provide necessary testing.
```changes
type: chore
summary: Rename prometheus secret from prometheus-https-mode to prometheus-url-schema, update madison registration hook to use new secret and field, add some tests.
```
> [flant-integration] refactor madison registration hook and provide tests for getPrometheusURLSchema

- modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
Addition recommendation has been provided to follow in case thee is an issue with kruise controller manager.
Relates to https://github.com/deckhouse/deckhouse/issues/4976?utm=ford_dropdown-menu#issuecomment-1602135896,
helps users understand how to deal with kruise controller's restarts.
The alert contains some recommendations to follow.
```changes
section: nginx-ingress
type: chore
summary: provide some recommendations in D8NginxIngressKruiseControllerPodIsRestartingTooOften alert.
```
> [nginx-ingress] provide some recommendations in D8NginxIngressKruiseControllerPodIsRestartingTooOften alert

- modules/150-user-authn/images/dex-authenticator/Dockerfile
- modules/150-user-authn/images/dex-authenticator/patches/README.md
- modules/150-user-authn/images/dex-authenticator/patches/remove-groups.patch
The Group header size can grow without control, which can cause requests to fail because of the body size
This is a regression after upgrading oauth2-proxy 
```changes
type: fix
summary: Do not send groups header from DexAuthenticator
```
> [user-authn] Do not send groups header from DexAuthenticator

- candi/bashible/bashible.sh.tpl
- modules/040-node-manager/templates/node-group/_bootstrap_script.tpl
Add visibility of query errors to curl execution
issues #4439 Additional information about the error has occurred will help in investigating the causes.
detailed information about the issues encountered in the request
```changes
type: feature
summary: Add visibility of query errors to curl execution
```
> [bashible] add visibility of query errors to curl execution (#4439)

- global-hooks/migrate/migrate_reomove_old_d8_validating_webhook_configuration.go
- global-hooks/migrate/migrate_reomove_old_d8_validating_webhook_configuration_test.go
This PR removes old `d8-deckhouse-validating-webhook-handler` validating webhook configuration.
`shell-operator` >= 1.2 adds suffix `-hooks` for validating webhook configuration.
https://github.com/flant/shell-operator/pull/439/files#diff-c93f73840012ea2edf0f924aab72794a77de0132bf1351776df8dd9b494002f9R14
After updating shell-operator we have two webhook configuration: old `d8-deckhouse-validating-webhook-handler` and new `d8-deckhouse-validating-webhook-handler-hooks`. We shold remove old configuration.
Before switching to branch: have 2 validating webhook configurations:
After switching, Deckhouse is ready and old validation webhook configuration has deleted:
After it, restart Deckhouse and waiting for readiness Dechouse pod. Here we check that deckhouse correctly handle absence old …
> [global-hooks] Delete `d8-deckhouse-validating-webhook-handler` validating webhook configurations

- modules/040-node-manager/monitoring/prometheus-rules/node-unmanaged.tpl
Fix links to docs in node-unmanaged rule for Prometheus
The links to the documents in the node-unmanaged rule for Prometheus were pointing to different sources, one to the official site and the other to the internal Deckhouse site.  This may caused confusion for the users, so we fixed the links to point to the official site.
```changes
type: fix
summary: Fix links in node-unmanaged rule for Prometheus.
```
> [node-manager] Fix links in node-unmanaged rule for Prometheus

- modules/340-monitoring-custom/monitoring/prometheus-rules/reserved-domain.tpl
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/storage-class.tpl
Fix incorrect links to documentation in alerts.
```changes
section: docs
type: chore
summary: Fix incorrect links to documentation in alerts.
```
> [monitoring] Fix links in alerts

- dhctl/pkg/config/meta.go
- dhctl/pkg/infrastructure/nodes.go
- dhctl/pkg/kubernetes/actions/converge/check.go
- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/kubernetes/actions/converge/node.go
* Use a single function to parse node index
* Convert directly to `int`
From the description of the problems
> If a string is parsed into an int using strconv.Atoi, and subsequently that int is converted into another integer type of a smaller size, the result can produce unexpected values.
> This also applies to the results of strconv.ParseInt and strconv.ParseUint when the specified size is larger than the size of the type that number is converted to.
```changes
section: dhctl
summary: Fix parsing node index (CWE-190, CWE-681).
```
> [dhctl] Fix parsing node index (CWE-190, CWE-681)

- candi/bashible/common-steps/node-group/090_node_users.sh.tpl
- modules/040-node-manager/crds/nodeuser.yaml
NodeUser fixed the ability to use parameters in sshPublicKeys
Comma delimiter is bad because it is a valid character which would split key string into two lines.
```changes
type: fix 
summary: NodeUser fixed the ability to use parameters in sshPublicKeys
```
> [node-manager] NodeUser fixed the ability to use parameters in sshPublicKeys

- modules/005-external-module-manager/hooks/handle_sources.go
Prevent arbitrary file write during zip extraction ("zip slip")
Extracting files from a malicious zip archive without validating that the destination file path is within the destination directory can cause files outside the destination directory to be overwritten, due to the possible presence of directory traversal elements (..) in archive paths.
Zip archives contain archive entries representing each file in the archive. These entries include a file path for the entry, but these file paths are not restricted and may contain unexpected special elements such as the directory traversal element (..). If these file paths are used to determine which output file the contents of an archive item should be written to, then the file may be written to an unexpected location. This can result in …
> [external-module-manager] Prevent path traversal

- modules/041-linstor/templates/nodegroupconfiguration-check-drbd-version.yaml
- testing/cloud_layouts/Static/astra-instance-bootstrap.sh
Disable Astra Linux hardened kernel for static tests and add workaround for drbd version check in some cases
Fix broken static tests
No problem while drbd version check in some cases, and working e2e static tests
```changes
type: fix
summary: Disable astra hardened kernel for static tests and add workaround for drbd version check.
```
> [linstor] Fix drbd check on ALT linux and static tests on Astra linux

- modules/021-cni-cilium/images/cilium/werf.inc.yaml
hubble, correct socket address
> hubble observe
```log
failed to connect to 'unix:///var/run/cilium/hubble:sock': connection error: desc = "transport: error while dialing: dial unix /var/run/cilium/hubble:sock: connect: no such file or directory"
```
run `hubble observe` in pod cilium-agent
```changes
type: fix 
summary: cli hubble, incorrect socket address
```
> cli hubble, incorrect socket address

- dhctl/cmd/dhctl/commands/converge.go
- dhctl/pkg/state/cache/init.go
- dhctl/pkg/state/cache/init_test.go
Add cache identity for a kubeconfig parameter in the converge command
issues #4948 
Converge should start with a kubeconfig parameter
```changes
section: dhctl
type: fix
summary: Add cache identity for a kubeconfig parameter in the converge command
```
> [dhctl] add cache identity for kubeconfig (#4948)

- modules/010-user-authn-crd/crds/dex-authenticator.yaml
Update the applicationIngressCertificateSecretName field's pattern to accept an empty string.
It appears that some clusters still have `dex authenticators` with the `applicationIngressCertificateSecretName` field set to an empty string `""` (since the times when the field was `required` by openapi definition). Such fields are artifacts and it's hard to get rid of them without manual reapplying `dexauthenticator` resources (helm doesn't do it's job, leaving the field in place). In v1.47 a validation pattern was introduced to check that `applicationIngressCertificateSecretName` conforms to k8s standards and it doesn't allow an empty string, failing a few modules when updating.
It affects an update process of a cluster
It's possible to set an empty string for …
> [user-authn-crd] loosen the applicationIngressCertificateSecretName pattern

- modules/402-ingress-nginx/openapi/config-values.yaml
- modules/402-ingress-nginx/openapi/doc-ru-config-values.yaml
Provides a parameter for enabling High Availability mode in the module config.
Some users might want to have HA disabled globally, but enabled for Ingress-Nginx control plane components (openkruise controller).
Close #5036
It's possible to turn on HA mode for Ingress-Nginx module regardless global HA settings.
```changes
type: feature
summary: Provide High Availability setting for Ingress-Nginx module's control-plane components.
```
> [ingress-nginx] add module-level highavailability parameter

- modules/460-log-shipper/monitoring/prometheus-rules/log-shipper-agent.yaml
Add host label (pod name) to description and ignore annotaion_failed errors.
`annotation_failed` errors are the expected behavior of vector when frequently changing states of pods in cluster (restarts, states Error, Completed). There is nothing we can do about it and we don't need to react to these errors.
Adding a pod name to the description allows you to skip the step of finding a pod, knowing only the node on which it is running.
> [log-shipper] Ignore annotation_failed errors. Refactor description

- modules/150-user-authn/docs/CONFIGURATION.md
- modules/150-user-authn/docs/CONFIGURATION_RU.md
- modules/150-user-authn/docs/FAQ.md
- modules/150-user-authn/docs/FAQ_RU.md
- modules/150-user-authn/docs/README.md
- modules/150-user-authn/docs/README_RU.md
- modules/150-user-authn/templates/dex/deployment.yaml
LDAP bindPW with dollar character causes Invalid credentials
https://github.com/dexidp/dex/issues/1876
https://github.com/dexidp/dex/issues/1051
```changes
type: fix
summary: Disable env expansion to support dollar character in bindPW for ldap connector
```
> [user-authn] disable env expansion to support dollar character in bindPW for ldap connector

- candi/cloud-providers/aws/openapi/cluster_configuration.yaml
- candi/cloud-providers/aws/openapi/doc-ru-cluster_configuration.yaml
Remove anchor inheritance in the `AWSClusterConfiguration` OpenAPI specification. 
We need to remove the property `etcdDisk` in `nodeGroups`. This property is inherited from `masterNodeGroup` by mistake.  We can fix this if we avoid anchor inheritance.
Close #4956
```changes
section: candi
type: fix
summary: Remove the property `etcdDisk` in `nodeGroups` and remove anchor inheritance in the 'AWSClusterConfiguration' OpenAPI specification.
```
> [candi] Fix AWSClusterConfiguration OpenAPI spec

- modules/030-cloud-provider-azure/cloud-instance-manager/machine-class.yaml
- modules/040-node-manager/template_tests/module_test.go
Fixed helm to render correctly booleans.
Closes https://github.com/deckhouse/deckhouse/issues/4988
```changes
type: fix
summary:  fixed the behavior of the acceleratedNetworking variable 
```
> [cloud-provider-azure] fixed the behavior of the acceleratedNetworking variable

- ee/modules/110-istio/templates/multicluster/api-proxy/ingress.yaml
- ee/modules/502-delivery/templates/argocd/server/d8-ingress.yaml
- helm_lib/Chart.lock
- helm_lib/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/README.md
- helm_lib/charts/deckhouse_lib_helm/templates/_module_public_domain.tpl
- helm_lib/charts/deckhouse_lib_helm/templates/_module_security_context.tpl
- modules/110-istio/templates/certificate.yaml
- modules/150-user-authn/templates/dex/certificate.yaml
- modules/150-user-authn/templates/kubeconfig-generator/certificate.yaml
- modules/150-user-authn/templates/kubeconfig-generator/ingress.yaml
- modules/150-user-authn/templates/kubernetes-api/certificate.yaml
- modules/300-prometheus/templates/grafana/ingress.yaml
- modules/491-containerized-data-importer/templates/ingress.yaml
- modules/500-cilium-hubble/templates/ui/ingress.yaml
- modules/500-dashboard/templates/dashboard/ingress.yaml
- modules/500-openvpn/templates/openvpn/ingress.yaml
- modules/500-upmeter/templates/status/ingress.yaml
- modules/500-upmeter/templates/webui/ingress.yaml
- modules/810-documentation/templates/ingress.yaml
Add commonName field to Deckhouse X.509 certificates.
Close #4926.
```changes
type: fix
summary: Add commonName field to Deckhouse X.509 certificates.
```
> [common] Add commonName field to Deckhouse X.509 certificates

- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
Separate the name of the node group from the command
The divided command is more than comprehensible.
```changes
type: chore
summary: Separate the name of the node group from the command in the FAQ.
```
> [node-manager] Separate the name of the node group from the command

- ee/modules/650-runtime-audit-engine/hack/far-converter/main.go
- ee/modules/650-runtime-audit-engine/images/rules-loader/hooks/lib/test.py
- ee/modules/650-runtime-audit-engine/images/rules-loader/hooks/webhook/webhook.py
- ee/modules/650-runtime-audit-engine/rules/k8s_audit_rules.yaml
- ee/modules/650-runtime-audit-engine/templates/configmap.yaml
- ee/modules/650-runtime-audit-engine/templates/daemonset.yaml
* Mount docker and containerd sockets to fetch metadata.
* Mount falco config to rules-loader to enable plugins for validating webhook. Otherwise, webhook returns an error for valid rules.
* Output webhook validation error. Without this change, users have to search it in logs among all running falco pods.
* Fix converter `apiVersion` header, it was `apiversion`, which is not valid.
* Fix falcoauditrules resource name in rules. 
Various fixes of problems found while developing rules.
Falco pods will be restarted.
```changes
type: fix
summary:  Mount docker and containerd sockets to fetch metadata.
---
type: fix
summary: Mount falco config to rules-loader to enable plugins for validating webhook. Otherwise, webhook returns an error …
```
> [runtime-audit-engine] Mount sockets and fix webhook output

- modules/002-deckhouse/hooks/cleanup_deckhouse_releases.go
- modules/002-deckhouse/hooks/cleanup_deckhouse_releases_test.go
Fix cleanup hook
If the releases were not followed one by one, then the wrong index selection resulted in cleaning up the wrong releases
In some cases we can break the release order
```changes
type: fix 
summary: Fix DeckhouseRelease cleanup hook. Mark superseded releases in the right order.
```
> [deckhouse] Fix DeckhouseRelease cleanup hook

- .github/ci_templates/e2e_tests.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- testing/cloud_layouts/script.sh
Adds Deckhouse logs if Pod hasn't changed to ready status.
We cannot get deckhouse logs when e2e test was failed.
Negative (e2e tests was failed) tested [here](https://github.com/deckhouse/deckhouse-test-2/pull/326)
Positive (e2e tests was passed) [here](https://github.com/deckhouse/deckhouse-test-2/pull/327)
```changes
section: ci
type: fix 
summary: Added deckhouse logs if the Pod hasn't changed to ready status.
```
> [testing] [ci]  add deckhouse logs if not READY pod

- modules/402-ingress-nginx/templates/kruise/manager.yaml
By default, `kruise controller` uses `configmapLeasese` leader-election-resource-lock type. The leader election timers are also a bit aggressive (lease duration - 15s, retry period - 2s). 
We change resource-lock type to use only leases, decreasing the amount of API requests, and readjust leader election timers to:
* lease retry - 10s
* lease duration - 35s
* lease renew deadline - 30s.
Tests show that kruise controller is able to elect its leader and start converging after a full restart in 50-60 seconds.
Also, the verbosity level of `kruise controller` was raised from 2 to 5 so that system administrators and cluster operators could perform preliminary diagnosis and troubleshooting of what was going on.
We update timers and resource lock type to decrease "the noise" of `kruise …
> [ingress-nginx] tune kruise leader election and verbosity

- modules/015-admission-policy-engine/charts/constraint-templates/templates/operation-policy/required-annotations.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/templates/operation-policy/test_samples/required-annotations/allowed_dep.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/templates/operation-policy/test_samples/required-annotations/allowed_pod.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/templates/operation-policy/test_samples/required-annotations/constraint.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/templates/operation-policy/test_samples/required-annotations/disallowed_dep.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/templates/operation-policy/test_samples/required-annotations/disallowed_pod.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/templates/operation-policy/test_samples/required-annotations/suite.yaml
- modules/015-admission-policy-engine/crds/doc-ru-operation-policy.yaml
- modules/015-admission-policy-engine/crds/operation-policy.yaml
- modules/015-admission-policy-engine/hooks/handle_operation_policies_test.go
- modules/015-admission-policy-engine/hooks/internal/apis/v1alpha1.go
- modules/015-admission-policy-engine/template_tests/operation_policies_test.go
- modules/015-admission-policy-engine/templates/operation-policy/constraint.yaml
Add `RequiredAnnotations` policy to the `OperationPolicy` Deckhouse CRD
We have `RequiredLabels` policy but sometimes we want to check annotations also.
Create `OperationPolicy`
```yaml
kind: OperationPolicy
metadata:
name: defaultns
spec:
enforcementAction: Deny
match:
namespaceSelector:
labelSelector:
matchLabels:
operation-policy.deckhouse.io/enabled: "true"
policies:
requiredAnnotations:
annotations:
- allowedRegex: ^P\d{4}$
key: foo
watchKinds:
- /Pod
```
try to create pod:
```bash
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
name: busybox-sleep
spec:
containers:
- name: busybox
image: busybox:1.28
args:
- sleep
- "1000000"
EOF
```
result:
```bash
Error from server (Forbidden): error when creating "STDIN": admission webhook …
```
> [admission-policy-engine] Add required-annotations OPA policy

- modules/402-ingress-nginx/images/kruise/patches/README.md
- modules/402-ingress-nginx/images/kruise/patches/stick-to-maxunavailable.patch
It transpired that conditional
`		if max := len(candidatePodsToDelete); remainingUnavailable > max {
remainingUnavailable = max
` may result in an inability to revert a `daemonset` to the previous version (similar to `kubectl rollout undo` comman).
The `candiatePodsToDelete` variable contains pods of the former version and in case we update a `daemonset` and a new pod doesn't get ready and running (for any reason, e.g. wrong container's image), breaking the update process, if we revert changes (to deal with the new broken pod), there is the situation when there is no new revision (we're reverting), thus, `candidatePodsToDelete` has length of 0, preventing the update from progressing.
It's rather a rare situation and it's possible to recover
* through deleting a failed new pod after …
> [ingress-nginx] update stick-to-maxunavailable.patch

- modules/041-linstor/monitoring/grafana-dashboards/storage/linstor_drbd.json
- modules/041-linstor/monitoring/prometheus-rules/linstor-storage-pools.yaml
- modules/041-linstor/templates/linstor-controller/servicemonitor.yaml
- modules/041-linstor/templates/linstor-node/podmonitor.yaml
Rename `exported_node` to `node` in PrometheusRule.
Alert is not rendered correctly commands do not work in it without correction
Alert is not rendered correctly commands do not work in it without correction
```changes
type: fix
summary: Rename `exported_node` to `node` in PrometheusRule.
```
> [linstor] fixed prometheus-rules renamed exported_node to node

- modules/040-node-manager/templates/nodegroupconfiguration-prune-containerd-content.yaml
Do not render template by Helm at deploy stage. We need this Go template at runtime stage.
Fixes deckhouse/deckhouse#4843 cleanup feature
The following template is rendered by Helm at deploy stage, which causes the script to come up empty in kubernetes cluster
```go
{{- if eq .cri "Containerd" }}
...
{{- end }}
```
This is not an urgent fix because the feature it fixes is not critical. But I would like to bring it to the next release, as this fix will clean up unnecessary artifacts on the disk and free up space.
```changes
section: candi
type: fix
summary: Fixed ngc step rendering
```
> [node-manager] do not render template by helm

- modules/500-dashboard/images/dashboard/logout_button.js
Show username and groups on click to the user icon instead of just "Logged in with an auth header".
This feature was requested a couple of times with complaints that users do not know who they are.
```changes
type: feature
summary: Show username and groups.
```
> [dashboard] Show username and groups

- go_lib/dependency/k8s/drain/README.md
- go_lib/dependency/k8s/drain/filters.go
- modules/402-ingress-nginx/templates/controller/controller.yaml
- modules/402-ingress-nginx/templates/failover/daemonset.yaml
Fix drain helper to ignore kruise controller AdvancedDaemonSets also.
PDB for ingress daemonset is also removed, because they don' work and only invoke some problems.
Ingress controller pods could not be evicted and block a node drain. We have to ignore that pods such as normal DaemonSets
Node updates can stuck.
```changes
type: fix
summary: Fix kruise DaemonSet handling on node drain.
```
> [ingress-nginx] Fix drain for AdvancedDaemonSet

- modules/010-user-authn-crd/crds/group.yaml
- modules/150-user-authn/hooks/migration_groups_from_user_to_group_object.go
- modules/150-user-authn/hooks/migration_groups_from_user_to_group_object_test.go
* Run migration only once
* Slugify names
* Add the group name field to the output table
The previous version of the migration can fail or overwrite manual changes.
```changes
type: fix
summary: Improve the groups migration (run only once and slugify group names)
```
> [user-authn] Improve groups migration

- .github/ci_templates/e2e_tests.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- testing/cloud_layouts/script.sh
Add `--resources-timeout=30m` argument for `dhctl bootstrap` command in e2e test.
Increase job timeout in e2e workflows, because we added `resources-timeout` argument.
Close #5075
Tested [here](https://github.com/deckhouse/deckhouse-test-2/pull/328)
```changes
type: chore
summary: Increase resources creation timeout in e2e tests.
```
> [testing] Increase resources creation timeout in e2e tests

- docs/documentation/_includes/search.liquid
- docs/documentation/_plugins/openapi.rb
- docs/documentation/js/search.js
To add search keywords to a parameter in the OpenAPI specification, use the `x-doc-search` key.
E.g. the search does not give a result for the `ProviderClusterConfiguiration`. We need to add the ability to specify search keywords for OpenAPI spec parameters.
```changes
section: docs
type: chore
summary: Use `x-doc-search` key for OpenAPI spec parameters to add search keywords. 
```
> [docs] Add ability to add search keywords for parameters in OpenAPI spec

- go_lib/dependency/k8s/drain/filters.go
Fix drain daemonset pod without controller ref
Function can panic
Avoid panics
```changes
type: chore
summary: Fix DaemonSet panic on draining.
```
> [chore] fix daemonset filter for draining

- candi/cloud-providers/aws/openapi/cluster_configuration.yaml
- candi/cloud-providers/aws/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/gcp/openapi/cluster_configuration.yaml
- candi/cloud-providers/gcp/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/doc-ru-cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/openapi/doc-ru-cluster_configuration.yaml
- ee/candi/cloud-providers/vsphere/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/vsphere/openapi/doc-ru-cluster_configuration.yaml
Add search keywords for searching `*ClusterConfiguration` resources by the `ProviderClusterConfiguration` keyword.
Based on the #5155 
Allows to find `*ClusterConfiguration` resources by the `ProviderClusterConfiguration` search keyword (as specified in the documentation)
If you search by the `ProviderClusterConfiguration` keywords, you get `[AWS|GCP|...]ProviderConfigurationResources`.
```changes
section: docs
type: chore
summary: Add search keywords for searching *ClusterConfiguration resources by the ProviderClusterConfiguration keyword.
```
> [docs] Better search for <Provider>ClusterConfiguration resources

- modules/040-node-manager/monitoring/prometheus-rules/node-update.yaml
Add command to the alert - "how to get more info about non-drained node"
It's hard to figure out - what to do next, when you have this alert
```changes
type: chore
summary: Add info command to the drain alert.
```
> Add more info about drained node failure

- modules/041-linstor/templates/nodegroupconfiguration-check-drbd-version.yaml
Fix in bashible step in case of installed drbd-utils
We can have looped reboot if drbd-utils installed on host.
Problem can affect nodes
Fixed problem
```changes
type: fix
summary: Fix in bashible step in case of installed drbd-utils
```
> [linstor] fix check drbd version step

- candi/bashible/common-steps/node-group/089_manually_unmount_old_csi_mounts_after_kubernetes_1_24.sh.tpl
Cleanup of old CSI mounts that follow pre Kubernetes 1.24 naming convention. Get deployed only on Kubernetes >=1.24 and only if there are any 
Closes https://github.com/deckhouse/deckhouse/issues/5132
It enabled successful Pod volume unmounts when upgrading Kubernetes on the go (without draining a Node).
Closes upstream issue: https://github.com/kubernetes/kubernetes/pull/107065
When a kubelet reports that it cannot delete a Pod because there is a mount (with path adhering to an old format), parse a log statement an `umount` manually. 
```changes
section: candi
type: fix
summary: Create a system unit that manually unmounts pre-1.24 CSI mounts. That should stop stuck Pods while upgrading kubelet without draining the Node.
```
> [candi] CSI old mount cleaner

- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
- docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS.md
- docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS_RU.md
- docs/site/_includes/getting_started/global/partials/FINISH_CARDS.md
- docs/site/_includes/getting_started/global/partials/FINISH_CARDS_RU.md
- docs/site/_includes/getting_started/global/partials/GET_BALANCER_ADDR.liquid
- docs/site/_includes/getting_started/global/partials/INSTALL_OTHER.liquid
- docs/site/_includes/getting_started/global/partials/INSTALL_OTHER_RU.liquid
- Update getting started:  bare metal installation.
- Actualize example of finishing installation
- Notes to wait for Ingress controller readiness
- Replace `sudo kubectl` to `sudo /opt/deckhouse/bin/kubectl` in other getting started
```changes
section: docs
type: chore
summary: Update getting started.
```
> [getting-started] Update install on bare metal

- modules/110-istio/openapi/config-values.yaml
- modules/110-istio/openapi/doc-ru-config-values.yaml
- modules/110-istio/template_tests/module_test.go
- modules/110-istio/templates/control-plane/iop.yaml
Added a way to globally override resources for `istio-proxy`.
Ref: #4710
In large clusters, 1Gi of memory is not enough. it is too time consuming and impractical to set each Pods.
```changes
section: istio
type: feature
summary: Added a way to globally override resources for `istio-proxy`.
```
> [istio] added a way to globally override resources for istio-proxy

- candi/version_map.yml
Set Kubernetes 1.27 version status as a preview.
Mark Kubernetes 1.27 as a preview version, which is not suitable for production environments yet.
```changes
section: candi
type: chore
summary: Set Kubernetes 1.27 version status as a preview.
```
> [chore] Set Kubernetes 1.27 version status as a preview

- modules/041-linstor/openapi/config-values.yaml
- modules/041-linstor/openapi/doc-ru-config-values.yaml
- modules/041-linstor/templates/linstor-csi/linstorcsidriver.yaml
- modules/041-linstor/templates/linstor-ha-controller/daemonset.yaml
- modules/041-linstor/templates/linstor-node/linstorsatelliteset.yaml
- modules/041-linstor/templates/linstor-pools-importer/daemonset.yaml
Now we have redundant tolerations for linstor satellites. Also, we have no opportunity to set affinity for them.  This PR fix both of this situations.
Now satellites places over all nodes in cluster, if linstor mode enabeld.
We have clients that want it ASAP.
Correct tolerations and ability to add node selector for linstor satellites.
```changes
type: feature
summary: Added node selector and fix tolerations for satellites.
```
> [linstor] Added node selector and fix tolerations for satellites

- deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go
- ee/candi/cloud-providers/openstack/docs/LAYOUTS.md
- ee/candi/cloud-providers/openstack/docs/LAYOUTS_RU.md
- ee/candi/cloud-providers/openstack/layouts/simple-with-internal-network/master-node/main.tf
- ee/candi/cloud-providers/openstack/layouts/simple/master-node/main.tf
- ee/candi/cloud-providers/openstack/layouts/standard-with-no-router/master-node/main.tf
- ee/candi/cloud-providers/openstack/layouts/standard/base-infrastructure/main.tf
- ee/candi/cloud-providers/openstack/layouts/standard/master-node/main.tf
- ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/openapi/doc-ru-cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/terraform-modules/kubernetes-data/main.tf
- ee/candi/cloud-providers/openstack/terraform-modules/kubernetes-data/variables.tf
- ee/candi/cloud-providers/openstack/terraform-modules/master/main.tf
- ee/candi/cloud-providers/openstack/terraform-modules/master/outputs.tf
- ee/candi/cloud-providers/openstack/terraform-modules/master/variables.tf
- ee/candi/cloud-providers/openstack/terraform-modules/static-node/main.tf
- ee/candi/cloud-providers/openstack/terraform-modules/static-node/variables.tf
- ee/modules/030-cloud-provider-openstack/hooks/migrate/common_test.go
- ee/modules/030-cloud-provider-openstack/hooks/migrate/migrate_terraform_state.go
- ee/modules/030-cloud-provider-openstack/hooks/migrate/migrate_terraform_state_test.go
Added the `etcdDiskSizeGb` parameter for OpenStack and migration from `openstack_blockstorage_volume_v2` to `openstack_blockstorage_volume_v3`.
Yandex Cloud, GCP, and Azure `ClusterConfiguration` added in https://github.com/deckhouse/deckhouse/pull/4720
The `etcdDiskSizeGb` was not added to vSphere because there is no ability to resize `vsphere_virtual_disk` in `terraform-provider-vsphere`. See https://github.com/hashicorp/terraform-provider-vsphere/issues/851
The etcd disk size is now hardcoded. We've added a parameter to allow the user to choose the disk size, which solves the problem of the inflexible disk size in the previous version.
Partially closes issue https://github.com/deckhouse/deckhouse/issues/3348
We also migrated from `openstack_blockstorage_volume_v2` resource to …
> [cloud-provider-openstack] Add param etcdDiskSizeGb and migrate from openstack_blockstorage_volume_v2 to openstack_blockstorage_volume_v3

- docs/documentation/pages/DECKHOUSE_CONFIGURE_GLOBAL.md
- docs/documentation/pages/DECKHOUSE_CONFIGURE_GLOBAL_RU.md
Add an example of the global ModuleConfig.
```changes
section: docs
type: chore
summary: Add an example of the global ModuleConfig.
```
> [docs] Add an example of the global ModuleConfig

- ee/modules/030-cloud-provider-openstack/hooks/discover.go
- ee/modules/030-cloud-provider-openstack/hooks/discover_test.go
Fix discover volume types hooks wrong fallback to storage classes in another modules. Hook should fallback for `cloud-provider` openstack only.
Deckhouse fail with error
```
{"binding":"ConvergeModules","event.type":"OperatorStartup","level":"error","module":"cloud-provider-openstack","msg":"ModuleRun failed in phase 'CanRunHelm'. Requeue task to retry after delay. Failed count is 80. Error: helm upgrade failed: rendered manifests contain a resource that already exists. Unable to continue with update: StorageClass \"localpath-system\" in namespace \"\" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key \"meta.helm.sh/release-name\" must equal \"cloud-provider-openstack\": current value is …
```
> [cloud-provider-openstack] Fix discover volume types hooks incorrect fallback to storage classes in another modules.

- modules/015-admission-policy-engine/images/constraint-exporter/go.mod
- modules/015-admission-policy-engine/images/constraint-exporter/go.sum
- modules/015-admission-policy-engine/images/constraint-exporter/pkg/kinds/kinds.go
- modules/015-admission-policy-engine/images/constraint-exporter/pkg/kinds/kinds_test.go
Fix constraint exporter deduplications
Deduplicate resources with wildcard, like "*/Pods" and "/Pods"
Gracefully handle invalid resources like "apps/v1/Deployment"
Invalid resources could break the current installation
```changes
type: fix 
summary: Fix constraint exporter - avoid duplications and invalid resource handling.
```
> [admission-policy-engine] Deduplicate exported resources

- ee/modules/030-cloud-provider-openstack/images/cloud-data-discoverer/discoverer.go
- ee/modules/030-cloud-provider-openstack/images/cloud-data-discoverer/discoverer_test.go
Remove duplicates from images list in cloud-data-discoverer.
```
{"binding":"kubernetes","binding.name":"cloud_provider_discovery_data","event.id":"795674ad-eebe-4ab9-a523-1b18490930a3","hook":"030-cloud-provider-openstack/hooks/discover.go","hook.type":"module","level":"error","module":"cloud-provider-openstack","msg":"Module hook failed, requeue task to retry after delay. Failed count is 41. Error: module hook '030-cloud-provider-openstack/hooks/discover.go' failed: failed to validate 'discovery-data.json' from 'd8-cloud-provider-discovery-data' secret: Loading schema file: Document validation failed:\n---\n{\"apiVersion\":\"deckhouse.io/v1alpha1\",\"kind\":\"OpenStackCloudProviderDiscoveryData\",\"flavors\":[\"Standard-4-12\",\"Advanced-12-24\",\"Basic-1-2-40 …
```
> [cloud-provider-openstack] Remove duplicates from images list in cloud-data-discoverer

- modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
Restoring D8KubernetesVersionIsDeprecated alert from 1.23 to 1.22.
We haven't change the default `kubernetesVersion` but increased the alert. It is confusing for users and pushes them to change `kubernetesVersion` from `Automatic` to something specific.
Users are confused, we don't need to multiply them.
```changes
type: fix
summary: Restoring D8KubernetesVersionIsDeprecated alert from 1.23 to 1.22.
```
> [control-plane-manager] Restoring D8KubernetesVersionIsDeprecated alert from 1.23 to 1.22

- dhctl/pkg/operations/bootstrap.go
Removed double sudo call for reboot command
In ALT Linux, calling the sudo command twice leads to an error
<details>
```shell
│ │ Nodes Ready 1 of 1
│ │ * test-master-0 | Ready
│ │ 
│ │ 🎉 Succeeded!
│ └ Waiting for NodeGroup master to become Ready (121.14 seconds)
└ ⛵ ~ Bootstrap: Waiting for Node Groups are ready (121.14 seconds)
❗ ~ Some resources require at least one non-master node to be added to the cluster.
┌ ⛵ ~ Bootstrap: Clear cache
│ ❗ ~ Next run of "dhctl bootstrap" will create a new Kubernetes cluster.
└ ⛵ ~ Bootstrap: Clear cache (0.00 seconds)
┌ 🎈 ~ Common: Kubernetes Master Node addresses for SSH
│ test-master-0 | ssh altlinux@1.2.3.4
└ 🎈 ~ Common: Kubernetes Master Node addresses for SSH (0.00 seconds)
[deckhouse] root@f705fa597dd9 / #
```
</details>
```changes
section: …
```
> [candi] Fix Reboot master node over ssh

- ee/modules/030-cloud-provider-openstack/hooks/migrate/migrate_terraform_state.go
- ee/modules/030-cloud-provider-openstack/hooks/migrate/migrate_terraform_state_test.go
Fix migration from openstack_blockstorage_volume_v2 to openstack_blockstorage_volume_v3 for Bastion hosts by adding d8-cluster-terraform-state migration.
Now, migration from openstack_blockstorage_volume_v2 to openstack_blockstorage_volume_v3 does not work for bastion hosts whose state is located at d8-cluster-terraform-state. This PR fixed it.
Migration from openstack_blockstorage_volume_v2 to openstack_blockstorage_volume_v3 did not work properly now.
Migration from openstack_blockstorage_volume_v2 to openstack_blockstorage_volume_v3 worked for all resources.
```changes
type: fix
summary: Fix migration from `openstack_blockstorage_volume_v2` to `openstack_blockstorage_volume_v3` for bastion hosts.
```
> [cloud-provider-openstack] Fix migration from openstack_blockstorage_volume_v2 to openstack_blockstorage_volume_v3 for bastion hosts

- ee/modules/030-cloud-provider-openstack/images/cloud-data-discoverer/discoverer.go
- ee/modules/030-cloud-provider-openstack/images/cloud-data-discoverer/discoverer_test.go
Remove duplicates from additional security groups in cloud-data-discoverer.
```
{"binding":"kubernetes","binding.name":"cloud_provider_discovery_data","event.id":"24e0e923-aead-460e-a7e5-5741351f676a","hook":"030-cloud-provider-openstack/hooks/discover.go","hook.type":"module","level":"error","module":"cloud-provider-openstack","msg":"Module hook failed, requeue task to retry after delay. Failed count is 238. Error: module hook '030-cloud-provider-openstack/hooks/discover.go' failed: failed to validate 'discovery-data.json' from 'd8-cloud-provider-discovery-data' secret: Loading schema file: Document validation failed:\n---\n{\"apiVersion\":\"deckhouse.io/v1alpha1\",\"kind\":\"OpenStackCloudProviderDiscoveryData\",\"flavors\":[\"Standard-4-12\",\"Advanced-12-24\ …
```
> [cloud-provider-openstack] Remove duplicates from additional security groups

- go_lib/hooks/tls_certificate/internal_tls.go
- go_lib/hooks/tls_certificate/internal_tls_test.go
Fix the bug when certificates stay the same even after a domain change
Fixes https://github.com/deckhouse/deckhouse/issues/4881
```changes
type: fix
summary: Add test that original sans are not mutated
```
> [go_lib] Add test that original sans are not mutated

- modules/030-cloud-provider-aws/templates/cloud-data-discoverer/rbac-for-us.yaml
- modules/030-cloud-provider-azure/templates/cloud-data-discoverer/rbac-for-us.yaml
- modules/030-cloud-provider-gcp/templates/cloud-data-discoverer/rbac-for-us.yaml
Add rbac Role to access `d8-provider-cluster-configuration` and `d8-cloud-provider-discovery-data` secrets.
```
{"level":"error","msg":"Failed to get 'd8-provider-cluster-configuration' secret: secrets \"d8-provider-cluster-configuration\" is forbidden: User \"system:serviceaccount:d8-cloud-provider-aws:cloud-data-discoverer\" cannot get resource \"secrets\" in API group \"\" in the namespace \"kube-system\"\n","time":"2023-07-20T10:11:11Z"}
```
Deckhouse fails with error (see above).
```changes
type: fix
summary: Add rbac Role to access d8-provider-cluster-configuration and d8-cloud-provider-discovery-data secrets.
---
type: fix
summary: Add rbac Role to access …
```
> [cloud-provider-*] Add rbac Role to access `d8-provider-cluster-configuration` and `d8-cloud-provider-discovery-data` secrets

- deckhouse-controller/pkg/helpers/change_registry/change_registry.go
- deckhouse-controller/pkg/helpers/change_registry/change_registry_test.go
- deckhouse-controller/pkg/helpers/register.go
Fix handling CA for change registry command in deckhouse-controller
Fix custom CA using while connecting to registry with change-registry command
This bug may affect UX
change-registry works with custom CA
```changes
type: fix
summary:  Fix change-registry CA handling for connecting to registry.
```
> [deckhouse-controller] Fix change-registry CA handling for connecting to registry

- candi/cloud-providers/yandex/bashible/bundles/ubuntu-lts/bootstrap-networks.sh.tpl
Fix #5229.
Close: https://github.com/deckhouse/deckhouse/issues/5229
The PR [fixes](https://github.com/deckhouse/deckhouse/issues/5229) Ubuntu 22.04 bootstrap.
```changes
section: candi
type: fix 
summary: Fix router metric if the `additionalNetworks` parameter is specified.
```
> [candi][cloud-provider-yandex] fixed router metric if have additionalNetworks

- candi/control-plane-kubeadm/config.yaml.tpl
- modules/021-kube-proxy/images/init-container/entrypoint/main.go
Add x-kuberenetes-validation for CRDs.
This feature gate is disabled before 1.25, we can enable and use it from 1.23
Much easier then validating webhooks - https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules
You can add to a CRD:
```
x-kubernetes-validations:
- messageExpression: '"CRI forbidden: " + self'
rule: self != 'Docker'
```
result:
```
kubectl apply -f /tmp/testng
The NodeGroup "worker-test" is invalid: spec.cri.type: Invalid value: "string": CRI forbidden:: Docker
```
```changes
type: feature
summary: Add feature-gate CustomResourceValidationExpressions.
```
> [control-plane-manager] Add CustomResourceValidationExpressions feature gate

- .github/CODEOWNERS
Changing codeowner for linstor module to @AleksZimin.
Alexandr is a D8 storage TL.
```changes
type: chore
summary: Changing codeowner for linstor module to @AleksZimin.
```
> [linstor] Changing codeowner

- modules/002-deckhouse/hooks/pkg/apis/v1alpha1/module.go
- modules/005-external-module-manager/hooks/cleanup_releases.go
- modules/005-external-module-manager/hooks/cleanup_releases_test.go
Delete ExternalModuleReleases for absent modules
If an external module was deleted - we have to cleanup all it's releases
```changes
type: feature
summary: Cleanup ExternalModuleReleases for deleted external modules.
```
> [external-modules-manager] Cleanup deleted modules

- tools/release/d8-pull.sh
If a user has registry.deckhouse.io in .docker/config.json with a non-valid key, the script stumbles on line 183.
```changes
section: d8-pull
type: fix
summary: fixed docker pull under certain conditions
```
> [d8-pull] fixed docker pull under certain conditions

- deckhouse-controller/pkg/helpers/change_registry/change_registry.go
After changing registry from registry with custom CA to registry without CA - old ca is retained in the `deckhouse-registry` secret.
This PR fixes retaining old CA from `deckhouse-registry` secret
Old CA doesn't retain in the cluster
```changes
type: fix
summary: Fix CA retaining after change-registry command.
```
> [deckhouse-controller] Fix CA retaining after change-registry command

- ee/modules/650-runtime-audit-engine/monitoring/prometheus-rules/runtime-audit-engine.yaml
- modules/460-log-shipper/monitoring/prometheus-rules/log-shipper-agent.yaml
Change alert condition
If pods are in CrashLoopBackOff state, there is no alert
```changes
type: fix
summary: Alert if replicas are not available
---
type: fix
summary: Alert if replicas are not available
```
> [runtime-audit-engine] Alert if replicas are not available

- candi/bashible/common-steps/all/004_check_hostname.sh.tpl
Checking the server hostname for compliance with Kubernetes and Deckhouse requirements
issue #5072 
Preventing failures before bootstrap execution
```changes
section: candi
type: feature
summary: Checking the server hostname for compliance with Kubernetes and Deckhouse requirements
```
> [preflight-check] Checking the server hostname (#5072)

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
Pass the `--secondary-repo` argument to the `werf build` command only for main and release branches.
It takes too long to send requests to both registries on werf building because the registry.deckhouse.io has many tags and, as a result, is much slower.
Close #4993
```changes
section: ci
type: feature
summary: Enable secondary repo only for main and release branches (werf).
```
> [ci](werf) Enable secondary repo only for main and release branches

- modules/101-cert-manager/openapi/config-values.yaml
- modules/101-cert-manager/openapi/doc-ru-config-values.yaml
- modules/101-cert-manager/templates/cert-manager/deployment.yaml
Add max concurrent challenges parameter for cert-manager-controller
The simultaneous update of a large number of certificates with HTTP challenges can generate a high load on ingress controllers
```changes
type: feature
summary: Added max concurrent challenges parameter for cert-manager-controller.
```
> [cert-manager] Added max concurrent challenges parameter

- docs/site/_includes/getting_started/openstack/partials/config.yml.standard.ee.inc
- ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/openapi/doc-ru-cluster_configuration.yaml
Documentation improvement. Added commands to help filling `domainName` and `volumeTypeMap`
```changes
section: cloud-providers-openstack
type: fix 
summary: Add commands to help filling `domainName` and `volumeTypeMap`.
```
> [cloud-providers-openstack] documentation improvement. 

- ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/openapi/doc-ru-cluster_configuration.yaml
Added reference on how to look up volume types and availability zones in Openstack CLI
To add a place to start when configuring volume types.
```changes
section: cloud-providers-openstack
type: chore 
summary: Update description of the `volumeTypeMap` parameter.
```
> [docs][openstack] Expand volumeTypeMap description

- ee/modules/650-runtime-audit-engine/images/rules-loader/Dockerfile
Reduce size of the runtime-audit-engine rules-loader container.
Previous rules-loader image builds leads to 1.2G container size.
```changes
section: security
type: chore
summary: reduce size of rules-reloader container
impact: runtime-audit-engine pods should be restarted
```
> [runtime-audit-engine] reduce size of rules-reloader container

- docs/site/docker-compose.yml
Fix the following error, when running `make docs`:
```
WARN[0000] a network with name deckhouse exists but was not created by compose.
Set `external: true` to use an existing network 
network deckhouse was found but has incorrect label com.docker.compose.network set to ""
```
Fix Makefile for running documentation.
```changes
section: docs
type: chore
summary: Fix docker-compose.yml file for running documentation.
```
> [chore] Fix docker compose file for running documentation

- modules/500-okmeter/templates/daemonset.yaml
Mount containerd socket into okmeter daemonset pods
There is containerd support in the recent version of okagent software. To okagent be capable of collecting container information from the containerd, we need to provide it with the containerd socket the same way as it was done for docker.
```changes
type: feature
summary: Mount containerd socket into okmeter daemonset pods to meet the requirement for containerd monitoring feature
impact: Rolling upgrade of the okmeter daemonset. This will cause a short disruption in node monitoring.
```
> Mount containerd socket into okmeter pods

- modules/040-node-manager/templates/nodegroupconfiguration-cleanup-after-prune-containerd-content.yaml
Cleanup oneshot job. Remove flag file.
Just housekeeping
We don't
```changes
section: candi
type: chore
summary: Remove `prune-containerd-content` ngc.
```
> [candi] Remove prune-containerd-content ngc

- ee/modules/030-cloud-provider-openstack/hooks/migrate/migrate_terraform_state.go
- ee/modules/030-cloud-provider-openstack/hooks/migrate/migrate_terraform_state_test.go
- go.mod
Reduce backup state secret length for openstack state migration. 
During migration backup secret can not be created for clusters with long prefix and Deckhouse queue will be stuck.
During migration backup secret can not be created for clusters with long prefix and Deckhouse queue will be stuck.
```changes
type: fix
summary: Fix creating long name of backup secret in state.
```
> [cloud-provider-openstack] Fix creating long name of backup secret in state migration

- modules/600-secret-copier/hooks/handler.go
Add additional conditions for final step with create a copied secrets to the new namespaces
Closes #5280 
```changes
type: fix 
summary: fix create secret in terminating or errored namespace
```
> [secret-copier] fix create secret in terminating or errored namespace

- modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring/node.yaml
Added reference for ncdu usage and a command to find pods with most disk usage to the alert description
Adds a place to start when investigating high disk usage. Adds a command to easily find pods with most disk usage on a node.
```changes
type: chore
summary: Add description for the `NodeDiskBytesUsage` alert.
```
> [extended-monitoring] Add description for the NodeDiskBytesUsage alert

- modules/041-linstor/crds/piraeus.linbit.com_linstorcontrollers.yaml
- modules/041-linstor/crds/piraeus.linbit.com_linstorcsidrivers.yaml
- modules/041-linstor/crds/piraeus.linbit.com_linstorsatellitesets.yaml
Update piraeus-operator crds after upgrading piraeus-operator to version 1.10.5 in https://github.com/deckhouse/deckhouse/pull/5301
To ensure compatibility with the new features and improvements introduced in piraeus-operator version 1.10.5, it's necessary to update the custom resource definitions (crds).
Actual piraeus-operator crds
```changes
type: fix
summary: Update piraeus-operator crds to be compatible with version 1.10.5
```
> [linstor] update piraeus-operator crds

- release.yaml
Enable `containerdOnAllNodes` release requirement.
We need requirement to prevent release apply if docker nodes are present in the cluster.
```changes
section: core
type: feature
summary: Enable release requirement to prevent release approvement if cluster has docker nodes.
```
> [core] Enable `containerdOnAllNodes` release requirement

- candi/bashible/preflight/check_localhost.sh
- dhctl/pkg/app/preflight.go
- dhctl/pkg/preflight/domain.go
- dhctl/pkg/preflight/preflight.go
- dhctl/pkg/template/preflight.go
Checking the availability of the localhost domain
issue #5207 
Preventing failures before bootstrap execution
```changes
section: dhctl
type: feature
summary: Checking the availability of the localhost domain
```
> [preflight-check] Checking the availability of the localhost domain (#5207)

- ee/modules/110-istio/templates/multicluster/api-proxy/ingress.yaml
- ee/modules/502-delivery/templates/argocd/server/d8-ingress.yaml
- helm_lib/Chart.lock
- helm_lib/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/README.md
- helm_lib/charts/deckhouse_lib_helm/templates/_module_documentation_uri.tpl
- helm_lib/charts/deckhouse_lib_helm/templates/_module_generate_common_name.tpl
- helm_lib/charts/deckhouse_lib_helm/templates/_module_public_domain.tpl
- modules/110-istio/templates/certificate.yaml
- modules/150-user-authn/templates/dex/certificate.yaml
- modules/150-user-authn/templates/kubeconfig-generator/certificate.yaml
- modules/150-user-authn/templates/kubernetes-api/certificate.yaml
- modules/300-prometheus/templates/grafana/ingress.yaml
- modules/491-containerized-data-importer/templates/ingress.yaml
- modules/500-cilium-hubble/templates/ui/ingress.yaml
- modules/500-dashboard/templates/dashboard/ingress.yaml
- modules/500-openvpn/templates/openvpn/ingress.yaml
- modules/500-upmeter/templates/status/ingress.yaml
- modules/500-upmeter/templates/webui/ingress.yaml
- modules/810-documentation/templates/ingress.yaml
Fix `helm_lib_module_public_domain` and add `helm_lib_module_generate_common_name`.
```
ModuleRun:main:node-manager:doStartup:OperatorStartup:failures 1392:template: node-manager/templates/monitoring.yaml:1:4: executing "node-manager/templates/monitoring.yaml" at <include "helm_lib_prometheus_rules" (list . "d8-cloud-instance-manager")>: error calling include: template: node-manager/charts/deckhouse_lib_helm/templates/_monitoring_prometheus_rules.tpl:81:4: executing "helm_lib_prometheus_rules" at <include "helm_lib_prometheus_rules_recursion" (list $context $namespace "monitoring/prometheus-rules")>: error calling include: template: node-manager/charts/deckhouse_lib_helm/templates/_monitoring_prometheus_rules.tpl:18:24: executing …
```
> [helm-lib] Fix X.509 certificate common name generation

- ee/modules/030-cloud-provider-openstack/images/cloud-data-discoverer/discoverer.go
- ee/modules/030-cloud-provider-openstack/templates/cloud-data-discoverer/deployment.yaml
- ee/modules/030-cloud-provider-openstack/templates/cloud-data-discoverer/secret.yaml
- go_lib/cloud-data/apis/v1alpha1/openstack_cloud_provider_discovery_data.go
- go_lib/cloud-data/reconciler.go
Handle 404 error for security groups. Some clouds don't have security groups.
Getting settings from openstack module settings if d8-provider-cluster config secret does not exist. It would be in hybrid clusters.
Have errors
```
{"level":"error","msg":"Failed to get 'd8-provider-cluster-configuration' secret: secrets \"d8-provider-cluster-configuration\" not found\n","time":"2023-07-26T11:01:48Z"}
```
```
{"level":"error","msg":"Getting discovery data error: failed to get additional security groups: failed to list security groups: Resource not found: [GET https://api-3.uu/network/v2.0/security-groups], error message: {\"NeutronError\": {\"type\": \"HTTPNotFound\", \"message\": \"The resource could not be found.\", \"detail\": \"\"}}\n","time":"2023-07-26T09:37:49Z"}
```
Have errors
``` …
```
> [cloud-provider-openstack] Fix descovery security groups and error in hybrib clusters

- modules/340-monitoring-kubernetes/images/kube-state-metrics/Dockerfile
- modules/340-monitoring-kubernetes/images/node-exporter/Dockerfile
kube-state-metrics, node-exporter are now based on minimal image.
```changes
type: feature
summary: Images are based on a distroless image.
```
> [distroless] monitoring-kubernetes

- ee/modules/502-delivery/images/argocd-image-updater/Dockerfile
Just change registry, images stays the same.
Pull from ghcr.io regularly fails.
```
Error: phase build on image delivery/argocd-image-updater stage dockerfile handler failed: unable to fetch dependencies for stage delivery/argocd-image-updater/dockerfile: get repo image "ghcr.io/werf/argocd-image-updater@sha256:2037ecef459e1f41010a0ceee95335b5a9d84e5de2d1a29f1b1fdcfa840da9b1" config file failed: getting ghcr.io/werf/argocd-image-updater@sha256:2037ecef459e1f41010a0ceee95335b5a9d84e5de2d1a29f1b1fdcfa840da9b1: Get "https://ghcr.io/v2/": dial tcp 140.82.121.33:443: i/o timeout
```
```changes
type: chore
summary: Pull argocd-image-updater image from registry.werf.io instead of ghcr
impact: low
```
> [delivery] Pull argocd-image-updater image from registry.werf.io instead of ghcr

- ee/modules/500-operator-trivy/templates/configmap.yaml
When upmeter and operator-trivy modules are enabled - trivy trying to scan upmeter probes image, [which doesn't exist](https://github.com/deckhouse/deckhouse/blob/main/modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_statefulset.go#L164).
Scanning of upmeter probes generates errors in operator-trivy:
```
2023-07-22T07:39:47.908Z	FATAL	image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
* unable to inspect the image (registry.k8s.io/upmeter-nonexistent:3.1415): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
* containerd socket not found: /run/containerd/containerd.sock
* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such …
```
> [operator-trivy] Remove upmeter probes from trivy scanning

- docs/documentation/.helm/templates/10-app.yaml
- docs/documentation/.helm/values.yaml
- docs/site/.helm/templates/12-backend.yaml
- docs/site/.helm/templates/14-frontend.yaml
- docs/site/.helm/values.yaml
Fix the use of values for resources in helm templates. Change VPA mode to Auto for the site deployments.
Resources were too low. Where was the bug in the helm template.
```changes
section: docs
type: chore
summary: Update VPA mode and deployment resources for the site deployments.
```
> [site][docs] Update VPA mode and deployment resources.

- .github/workflow_templates/deploy-web.multi.yml
- .github/workflows/deploy-web-preproduction.yml
Fix CI to build site before deploying to pre-prod in case of label `deploy/web/preprod` was used.
```changes
section: ci
type: chore
summary: Update CI for deploying to preprod by a label.
```
> [ci] Update CI for deploying site to preprod

- ee/modules/030-cloud-provider-openstack/openapi/values.yaml
Remove `minLength: 1` requirement from `mainNetwork` and `defaultImageName` properties.
```
2023-07-31T08:51:55Z [error][cloud-provider-openstack] - Module hook failed, requeue task to retry after delay. Failed count is 8049. Error: module hook '030-cloud-provider-openstack/hooks/discover.go' failed: failed to validate 'discovery-data.json' from 'd8-cloud-provider-discovery-data' secret: Loading schema file: Document validation failed:
---
{"apiVersion":"deckhouse.io/v1alpha1","kind":"OpenStackCloudProviderDiscoveryData","flavors":["m1.tiny","BL1.1-512","BL1.1-1024","BL1.1-2048","BL1.2-4096","BL1.2-8192","BL1.4-16384","BL1.6-32768","BL1.8-49152","BL1.10-65536","SL1.1-1024","SL1.1-2048","SL1.2-4096","SL1.2-8192","SL1.4-16384","SL1.6-32768","SL1.8-32768","SL1.12-4 …
```
> [cloud-provider-openstack] Fix OpenAPI spec

- .github/ci_templates/web.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- .github/workflows/deploy-web-preproduction.yml
- .github/workflows/deploy-web-stage.yml
- .github/workflows/deploy-web-test.yml
Pass a datacenter name (code) to the doc deploy environment, which can be used in templates to change some data center-dependent parameters.
```changes
section: ci
type: chore
summary: Pass a datacenter name to the doc deploy environment.
```
> [ci][docs] Pass a datacenter name to doc deploy environment

- modules/300-prometheus/monitoring/prometheus-rules/longterm-target-down.yaml
Longterm prometheus cannot scrape main prometheus with timeout error (we have very large prometheus).
But we don't recieve D8PrometheusLongtermFederationTargetDown alert.
It fixes an issue https://github.com/deckhouse/deckhouse/issues/4972
In the case where the long-term prometheus cannot scrape the main-prometheus for whatever reason, we will get alert.
```changes
type: fix
summary: Fix alert expression when a longterm-prometheus fails to scrape the main-prometheus for whatever reason.
```
> [prometheus] D8PrometheusLongtermFederationTargetDown alert not working properly

- ee/fe/modules/340-monitoring-applications/applications/loki/grafana-dashboards/loki.json
- ee/fe/modules/340-monitoring-applications/docs/CONFIGURATION.md
- ee/fe/modules/340-monitoring-applications/docs/CONFIGURATION_RU.md
- modules/462-loki/templates/servicemonitor.yaml
Add Grafana dashboards for Loki.
Add ServiceMonitor for loki module.
It's useful to view main Loki metrics over time.
It's also useful for d8 loki module and should work with it.
Not necessary.
- The "Loki" dashboard should appear in "Applications" Grafana folder.
- Metrics from d8 loki should be presented on this dashboard.
```changes
type: feature
summary: Add Grafana dashboard for Loki.
```
> [monitoring-applications] Add grafana loki dashboard

- modules/460-log-shipper/apis/v1alpha1/cluster_log_destination.go
- modules/460-log-shipper/crds/cluster-log-destination.yaml
- modules/460-log-shipper/crds/doc-ru-cluster-log-destination.yaml
- modules/460-log-shipper/hooks/generate_config_test.go
- modules/460-log-shipper/hooks/internal/vector/destination/loki.go
- modules/460-log-shipper/hooks/testdata/file-to-loki/manifests.yaml
- modules/460-log-shipper/hooks/testdata/file-to-loki/result.json
Add tenantID option
Closes  https://github.com/deckhouse/deckhouse/issues/5248
```changes
type: feature
summary:  Add tenantID option for Loki (may be required for Grafana Cloud)
```
> [log-shipper] Add tenantID option for Loki

- candi/bashible/common-steps/node-group/068_configure_kubelet_systemd_unit.sh.tpl
Revert CRI socket path configuration for docker.
If nodeGroup.cri.type == "NotManaged" we try to configure kubelet cri
https://github.com/deckhouse/deckhouse/blob/main/candi/bashible/common-steps/node-group/068_configure_kubelet_systemd_unit.sh.tpl#L26C1-L37C5
And if notManaged node group contains docker nodes then kubeblet can not run in threse  nodes.
And if cri.type == notManaged node group contains docker nodes then kubeblet can not start in threse  nodes.
```changes
section: candi
type: fix
summary: Revert kubelet CRI socket path configuration for docker.
```
> [bashible] Revert kublet cri socket path configuration for docker

- ee/candi/cloud-providers/openstack/openapi/cloud_provider_discovery_data.yaml
Fix OpenAPI scheme for `d8-cloud-provider-discovery-data` secret. The `mainNetwork` and `defaultImageName` parameters can be empty.
In hybrid clusters, Deckhouse can get stuck in error.
In hybrid clusters, Deckhouse can get stuck in error.
```changes
type: fix
summary: Fix OpenAPI scheme for `d8-cloud-provider-discovery-data` secret.
```
> [cloud-provider-openstack] Fix openapi scheme for d8-cloud-provider-discovery-data secret

- modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/exporter/main.go
I made a mistake in PR #4888. If the mount point for the requested folder is `/` then `getMountpoint()` function returns an empty string. In this case, the `mountpoint` label will be missing in the metric.
I fixed the problem and now the mountpoint is determined correctly.
I added a temporary debug output to the console into the `getMountpoint()` function on one of the worker hosts in the kubernetes cluster. And here is the result after the changes:
```shell
Path:  /host/boot/efi/EFI/ubuntu
Mountpoint:  /boot/efi
Path:  /host/var/lib/kubelet
Mountpoint: /
Path:  /host/var/lib/containerd
Mountpoint: /
```
Closes #5430
Currently, the alert rules `KubeletNodeFSBytesUsage`, `KubeletNodeFSInodesUsage` are invalid. Since there is no `mountpoint` label in the metric …
> [monitoring-kubernetes] Fix mountpoint label in kubelet-eviction-thresholds-exporter

- modules/402-ingress-nginx/images/controller-1-1/Dockerfile
- modules/402-ingress-nginx/images/controller-1-1/patches/README.md
- modules/402-ingress-nginx/images/controller-1-1/patches/metrics-SetSSLExpireTime.patch
- modules/402-ingress-nginx/images/controller-1-6/Dockerfile
- modules/402-ingress-nginx/images/controller-1-6/patches/README.md
- modules/402-ingress-nginx/images/controller-1-6/patches/metrics-SetSSLExpireTime.patch
added namespase in SetSSLExpireTime
now the metric in the namespace label gives the value of where the controller is located but not the ingress itself, which is misleading for an engineer who studies the NGINXCertificateExpiry alert created on the basis of the nginx_ingress_controller_ssl_expire_time_seconds metric.
```changes
type: fix 
summary: fixed nginx_ingress_controller_ssl_expire_time_seconds
```
> [ingress-nginx] added namespase in SetSSLExpireTime

- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
Update the node-exporter daemonset to include the unconfined AppArmor security profile. This change is necessary to allow the node_exporter to access all necessary system resources on the node without being restricted by the default AppArmor profile.
To get rid of messages in journalctl like this:
```
virtlab-pt-0 audit[2275]: AVC apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=2275 comm="node_exporter" requested_mask="read" denied_mask="read" peer="unconfined"
```
There are no corresponding error messages in the logs.
```changes
type: fix
summary: fix node_exporter apparmor premissions issue
impact: all node_exporter pods will be restarted
```
> [monitoring-kubernetes] fix node_exporter apparmor premissions issue

- dhctl/pkg/config/base.go
- global-hooks/discovery/cluster_configuration.go
- global-hooks/discovery/cluster_configuration_test.go
- modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
Bump `Automatic` kubernetes version to the 1.25
Keep kubernetes up-to-date
```changes
type: feature
summary: Bump `Automatic` kubernetes version to the 1.25
impact: Cluster with `Automatic` kubernetes version value in the ClusterConfiguration will be updated to the kubernetes 1.25.
```
> [global] Bump Automatic kubernetes version

- modules/040-node-manager/hooks/update_approval.go
- modules/040-node-manager/monitoring/prometheus-rules/node-update.yaml
A new `D8ProblematicNodeGroupConfiguration` alert is sent when a Node without proper `node.deckhouse.io/configuration-checksum` annotation is detected during update approval process in `node-manager` module.
See #3300
```changes
type: feature
summary: alert fired if Node has no config checksum annotation during NodeGroup update
```
> [node-manager] create alert if node has no config checksum annotation

- candi/openapi/doc-ru-node_group.yaml
- candi/openapi/node_group.yaml
Fix NodeGroup OpenAPI spec:
- Fix `spec.kubelet.resourceReservation` description.
- Get rid of YAML anchors.
```changes
section: docs
type: chore
summary: Fix NodeGroup OpenAPI spec.
```
> [docs][candi] Fix NodeGroup OpenAPI spec

- modules/150-user-authn/template_tests/kubeconfig_generator_config_test.go
- modules/150-user-authn/templates/kubeconfig-generator/config.yaml
Fix bug when discovered CA is not added to kubconfigs
Without it, users cannot connect to kube-apiserver with the publish API feature when selfsigned certificates are used.
```changes
type: fix
summary: Use global discovered publishAPI cert by default for generated kubeconfigs
```
> [user-authn] Use global discovered publishAPI cert by default

- modules/041-linstor/hack/update.sh
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-centos-like.yaml
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-debian-like.yaml
We have some conditions in nodegroupconfigurations that not matches our code style. 
Potentially there can be problems with load dm-thin-pool module, that needed for lwm thin pool support.
Also, we need some additions in linstor components update script
This PR will fix conditions in nodegroupconfigurations that not matches our code style, force dm-thin-pool kernel module load and fix linstor components update script
Some changes for unified code base, confidence about lvm-thin support and updated script for linstor components update.
```changes
type: fix
summary: Fixes in nodegroupconfigurations for DRBD install and linstor components update script.
```
> [linstor] fixes in nodegroupconfigurations for DRBD install and linstor components update script

- modules/005-external-module-manager/crds/doc-ru-external-module-source.yaml
- modules/005-external-module-manager/crds/external-module-source.yaml
- modules/005-external-module-manager/hooks/handle_sources.go
- modules/005-external-module-manager/hooks/internal/apis/v1alpha1/source.go
Add custom CA certificate handling on external modules pulling.
Without CA registry with self-signed certificate will return an error, like `x509: certificate signed by unknown authority`
```changes
type: feature
summary: Support custom CA for ExternalModuleSource.
```
> [external-module-manager] Add CA certificate option to an ExternalModuleSource

- candi/bashible/common-steps/node-group/002_migrate_containerd_to_cgroupfs.sh.tpl
- candi/bashible/common-steps/node-group/050_configure_and_start_containerd.sh.tpl
- candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
Revert migration to cgroupfs driver for containerd cri.
We must migrate containerd to cgroupfs. This migration was deleted by mistake after removing Docker CRI support (#4960).
```changes
section: candi
type: fix
summary: Revert migration to cgroupfs driver for containerd cri.
```
> [candi](bashible) Revert migration to cgroupfs driver for containerd cri

- modules/013-helm/hooks/metrics.go
- modules/013-helm/hooks/metrics_test.go
- modules/013-helm/monitoring/prometheus-rules/deprecated-versions.yaml
Find deprecated apis for the current kubernetes version + 2
It was + 1 before
We want to know about deprecated helm releases before the Deckhouse release, because usually we jump over version (1.23 -> 1.25)
We are using 1.25 kubernetes as default version now but some clients don't know about a problems with releases
```changes
section: helm
type: fix
summary: Find and notify deprecated helm releases for the current Kubernetes version + 2.
```
> [helm] Fix depcreated helm apis calculation

- modules/002-deckhouse/hooks/internal/updater/notification.go
- modules/002-deckhouse/hooks/internal/updater/updater.go
- modules/002-deckhouse/hooks/update_deckhouse_image_test.go
Deckhouse has feature to control notifications about updates. There is parameter [minimalNotificationTime](https://deckhouse.io/documentation/v1/modules/002-deckhouse/configuration.html#parameters-update-notification-minimalnotificationtime). But some users use pull model to get information about releases. They can't be sure that they get information about release and this information will be in their internal system for required period of time.
If it fixes an issue https://github.com/deckhouse/deckhouse/issues/5147
We made it possible to configure minimalNotificationTime without configuring the notification webhook.
```changes
type: fix
summary: Made it possible to configure minimalNotificationTime without configuring the notification webhook.
```
> [deckhouse] Update release delay without configuring notification.

- candi/bashible/common-steps/node-group/089_manually_unmount_old_csi_mounts_after_kubernetes_1_24.sh.tpl
1. Removed `mount` call from the pipeline to avoid capturing the non-zero exit code of a mount command in an `if` expression. 
2. Added non-conditional start and enable of a systemd service and a systemd timer.
Fixes to https://github.com/deckhouse/deckhouse/pull/5153
The feature introduced in https://github.com/deckhouse/deckhouse/pull/5153 is not working properly.
Mount deletion service is correctly created and enabled.
```changes
section: candi
type: fix
summary: Fix old csi mount cleaner
```
> Fixed old csi mount cleaner

- candi/bashible/bashbooster/50_apt.sh
- candi/bashible/bundles/debian/bootstrap.sh.tpl
- candi/bashible/bundles/ubuntu-lts/bootstrap.sh.tpl
- candi/bashible/common-steps/all/080_setup_timer_to_run_bashible.sh.tpl
- ee/candi/bashible/bashbooster/50_apt_rpm.sh
- ee/candi/bashible/bundles/altlinux/bootstrap.sh.tpl
- ee/candi/bashible/bundles/astra/bootstrap.sh.tpl
- testing/cloud_layouts/script.sh
This reverts #5314 (commit 2e061f8961103ea6febcc798dbb36932bf32ffb6).
E2e tests in AWS fails with the following error:
```
InvalidParameterValue: User data is limited to 16384 bytes
```
e2e tests in AWS pass.
```changes
summary: Reverts #5314
```
> Revert "[bashible] fixed wait apt update (#5314)"

- docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA.md
- docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA_RU.md
- tools/kind-d8.sh
Fix script for installing Deckhouse on kind.
The script for installing Deckhouse on kind didn't work.
Deckhnouse installs on kind at least in Linux and MacOS.
```changes
section: tools
type: chore
summary: Fix script for installing Deckhouse on kind.
```
> [getting started] Fix kind installation script

- modules/402-ingress-nginx/template_tests/controller_test.go
- modules/402-ingress-nginx/templates/controller/controller.yaml
Add a lifecycle preStop hook with a `while` loop checking `controller's healthz 10254 port availability` to the `kube-rbac-proxy` container of an Ingress nginx's pod, preventing it from getting instantly not ready on termination.
Also, a minor change - a possibility to set `spec.waitLoadBalancerOnTerminating` to `0` value (previously, it would render to nil and wouldn't be accounted).
In case we use non-null value of the `--shutdown-grace-period` flag (`loadBalancer` and `hostPort` inlets) for ingress-nginx-controller, kube-rbac-proxy should continue running for the same time before exiting on shutdown. Otherwise we end up with a terminating and `not` ready pod as `kube-rbac-proxy` exits immediately and prevents liveness/readiness probes of the ingress-controller container from …
> [ingress-nginx] add prestop lifecycle hook for rbac-proxy

- ee/modules/650-runtime-audit-engine/docs/FAQ.md
- ee/modules/650-runtime-audit-engine/docs/FAQ_RU.md
Fix spec.labelFilter field for ClusterLoggingConfig (instead wrong lablesFilter) in docs
```changes
section: docs
type: fix
summary: Fix spec.labelFilter field in doc
impact: 
```
> Fix spec.labelFilter field in doc

- modules/005-external-module-manager/hooks/apply_release.go
- modules/005-external-module-manager/hooks/apply_release_test.go
- modules/005-external-module-manager/hooks/handle_sources.go
Execute `apply_releases` only before helm and on Kubernetes events. Skip synchronization.
Now the `handle_sources.go` will always be executed before the `apply_release.go` hook on the Deckhouse startup.
There are two hooks:
* [apply_release.go](https://github.com/deckhouse/deckhouse/blob/main/modules/005-external-module-manager/hooks/apply_release.go)
* [handle_sources.go](https://github.com/deckhouse/deckhouse/blob/main/modules/005-external-module-manager/hooks/handle_sources.go)
Both hooks have the Kubernetes binding and are executed on Synchronization. If it were `shell-operator`, everything would work well because there was only a single queue, and all synchronization tasks were executed [one after another](https://github.com/flant/shell-operator/blob/1d4c4d9320a89fbe348409750631b37267 …
> [external-module-manager] Fix race condition while handling source on Deckhouse startup

- modules/810-documentation/images/web/nginx.conf
Remove the unnecessary user directive from the `nginx.conf`, as the container works in unprivileged mode.
Remove the warning:
```
2023/08/18 15:30:22 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
```
```changes
type: chore
summary: Remove the unnecessary user directive from the `nginx.conf`, as the container works in unprivileged mode.
```
> [documentation] Remove the unnecessary user directive from the nginx.conf

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/node.json
In the expression we used rate for gauge metrics, I changed it to a standard expression to see in bytes how much virtual memory is being processed now.
Fixes the dashboard in Grafana.
we can see process virtual memory
```changes
type: fix 
summary: Change expression to `process_virtual_memory`.
```
> [monitoring-applications]change expression to process_virtual_memory

- modules/007-registrypackages/images/drbd/werf.inc.yaml
For build CSE version we need to use .ModulePath in werf.inc.yaml files instead off full path to files from git.
Debian virt-what pacjkage updated to v1.19.1 becuse old version does not exist in the repo
CSE support
```changes
type: chore
summary: Add .ModulePath to werf.inc.yaml
```
> [registrypackages] Add .ModulePath to werf.inc.yaml

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/node.json
Dashboard: Kubernetes Cluster / Node / Network Netstat / Netstat IP Forwarding
The expression contains "rate" for metric which can be only "1" or "2".
RFC2011 https://datatracker.ietf.org/doc/html/rfc2011
says that:
ipForwarding OBJECT-TYPE
SYNTAX      INTEGER {
forwarding(1),    -- acting as a router
notForwarding(2)  -- NOT acting as a router
}
Also we can find indication of that in the source of netstat: https://sourceforge.net/p/net-tools/code/ci/master/tree/statistics.c
So we shouldn't use "rate" for this value.
It fixes the issue for Grafana dashboard
It's not urgent.
We will see a correct value on the dashboard. 
```changes
type: fix 
summary: change expression for ip_forwarding
```
> Change expression in Grafana dashboard for Ip_Forwarding

- modules/002-deckhouse/hooks/check_deckhouse_release.go
- modules/002-deckhouse/hooks/check_deckhouse_release_test.go
- modules/340-monitoring-deckhouse/monitoring/prometheus-rules/deckhouse.yaml
When we use d8-pull.sh/d8-push.sh or dhctl mirror - we can transfer not all images and deckhouse can create DeckhouseRelease with minor version diff more than one version, for example:
```
NAME      PHASE        TRANSITIONTIME   MESSAGE
v1.47.5   Superseded   12d
v1.49.0   Deployed     3d
```
Updating across multiple versions can have unintended consequences that can break deckhouse functionality, as deckhouse cannot skip minor version updates.
fix #5377
We proceed according to the following algorithm:
* a. take all tags.
* b. we choose a version one more than the current one (maximum patch).
* c. create a release with the selected version.
* d. apply the update.
* e. go back to point a until we reach the desired version.
```changes
type: fix
summary: Updating the …
```
> [deckhouse] Step by step update when deckhouse release version.

- modules/150-user-authn/hooks/discover_publish_api_cert.go
- modules/150-user-authn/hooks/discover_publish_api_cert_test.go
- modules/150-user-authn/template_tests/kubeconfig_generator_config_test.go
- modules/150-user-authn/templates/kubeconfig-generator/config.yaml
1. Move all complicated discovery logic to the hook
2. If the `publishAPI.https.global.kubeconfigGeneratorMasterCA` field equals to `""`, then the cert will not be added to kubeconfigs
Keeping logic in templates is not error-prone, and there is no way to tell the user-authn that certificates should not be added to generated kubeconfigs.
```changes
type: feature
summary: Move publishAPI CA discovery logic to the hook
```
> [user-authn] Move publishAPI CA discovery logic to the hook

- modules/150-user-authn/docs/USAGE.md
- modules/150-user-authn/docs/USAGE_RU.md
Added descriptions for crowd groups in DexProviders custom resource
Groups from CROWD are passed to Dex in lowcase format and matched with what is described in DexProvider.
For example, your CROWD group is MyGroup, it is passed to Dex as mygmoup, and if you write MyGroup in DexProvider they will not be equal.
It is important to write it the way groups are passed to Dex
```changes
type: Documentation updates.
```
> [user-authn] [Docks] Added descriptions for crowd groups

- docs/site/_includes/getting_started/global/partials/getting-started-setup.js.liquid
- docs/site/_includes/getting_started/global/step_cluster_setup.html
- docs/site/_includes/getting_started/global/step_cluster_setup_ru.html
Remove a protocol prefix from the imagesRepo in the Getting started for the private environment.
We need it to get rid of one of the common mistakes.
```changes
section: docs
type: chore
summary: The Getting started updates.
```
> [getting started] Remove a protocol prefix from the imagesRepo

- testing/cloud_layouts/script.sh
Disable Linstor tests in static environment.
Now tests for Linstor do not reflect the current situation and hinder normal testing of the static environment. So we temporary disable them, in future there will be dedicated Linstor tests.
No problem with e2e static tests
```changes
section: e2e
type: fix
summary: Disable Linstor tests in static e2e environment.
```
> [e2e] linstor tests in e2e static is temporary disabled

- ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/openapi/doc-ru-cluster_configuration.yaml
Added description about getting openstack network list.
```changes
type: chore 
summary: added description about getting openstack network list
```
> [cloud-provider-openstack] added a command to get the list of networks

- global-hooks/create_endpoints.go
- global-hooks/create_endpoints_test.go
- modules/002-deckhouse/hooks/clean_endpoint_slices.go
- modules/002-deckhouse/hooks/clean_endpoint_slices_test.go
Handle orphan Endpoint and EndpointSlices
In a multi-master cluster old, orphan Endpoints and EndpointSlices could cause the request timeout error to a validation webhook.
We will rewrite the Endpoint and delete orphan EndpointSlices
```changes
type: fix 
summary: Handle orphan deckhouse Endpoints and EndpointSlices
```
> [deckhouse]  Handle Endpoints and orphan EndpointSlices

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
- modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
Added info about check terraform state before changing the master node.
```changes
type: chore
summary: Add info about checking the terraform state before changing the master node.
```
> [control-plane-manager] added a state check before changing the master node

- ee/modules/650-runtime-audit-engine/images/falcosidekick/Dockerfile
- ee/modules/650-runtime-audit-engine/templates/daemonset.yaml
Move faclosidekick container to the distroless image.
This PR is a part of https://github.com/deckhouse/deckhouse/issues/2797
```changes
section: runtime-audt-engine
type: chore
summary: move falcosidekick to distroless
impact: runtime-audit-engine pod will be restarted
```
> [runtime-audit-engine] move falcosidekick to distroless

- global-hooks/create_endpoints.go
- global-hooks/deckhouse-config/ensure_crd.go
- global-hooks/deckhouse-config/startup_sync.go
Fix global hooks order
Endpoints should be created before all other hooks
```changes
type: fix 
summary: Fix global hooks order
```
> [global] Fix global hooks order

- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
Revert node-exporter kube-rbac-proxy liveness probe.
We have problem with this probe and we need to investigate time for better solution.
```changes
type: fix
summary: Revert node-exporter kube-rbac-proxy liveness probe
```
> [monitoring-kubernetes] Revert node-exporter kube-rbac-proxy liveness probe

- candi/bashible/bashbooster/50_yum.sh
changed the output of the command for 'yum versionlock delete' if it is dnf
https://github.com/deckhouse/deckhouse/issues/5456
this fixes the kernel update case with linstor installed
1.50
1.49
```changes
section: candi
type: fix 
summary: changed the output of the command for 'yum versionlock delete' if it is dnf
```
> [candi] changed the output of the command for 'yum versionlock delete' if it is dnf

- ee/modules/650-runtime-audit-engine/images/falco/Dockerfile
- ee/modules/650-runtime-audit-engine/images/falco/werf.inc.yaml
- ee/modules/650-runtime-audit-engine/templates/daemonset.yaml
Add read-only root for falco container
Read-only container fs is needed for security purposes.
```changes
section: security
type: fix
summary: add read-only root for falco container
impact: runtime-audit-engine pods should be restarted
```
> [runtime-audit-engine] add read-only root for falco container

- candi/cloud-providers/aws/terraform-modules/master-node/main.tf
- candi/cloud-providers/aws/terraform-modules/static-node/main.tf
Explicitly specified tags from `AWSClusterConfiguration` for `root_block_device` in `master-node` and `static-node` terraform configurations
Fixes #5120 
```changes
section: candi
type: fix
summary: "AWS node's root_block_device is now marked with tags from AWSClusterConfiguration"
```
> [cloud-provider-aws] Explicitly provide tags to root_block_device

- candi/bashible/common-steps/node-group/089_manually_unmount_old_csi_mounts_after_kubernetes_1_24.sh.tpl
Fixed missing negation from https://github.com/deckhouse/deckhouse/pull/5548/files#diff-13ff18bfb1e6b6302d0f5d327557b20bab73b8b29570c517cdcec53369d2ca04L42
Fixes forgotten negation.
The previous fix does not work and CSI mount cleaner won't work correctly on Kubernetes 1.25 (which is default now).
I've created a test mount:
```
/dev/vdb on /tmp/test/var/lib/kubelet/plugins/kubernetes.io/csi/pv/test type ext4 (rw,relatime,discard)
```
All systemd units got successfully enabled:
```
root@klimentyev-master-0:~# systemctl cat old-csi-mount-cleaner.timer
[Unit]
Description=Old CSI mount cleaner timer
[Timer]
OnBootSec=2min
OnUnitActiveSec=2min
[Install]
WantedBy=multi-user.target
root@klimentyev-master-0:~# systemctl cat old-csi-mount-cleaner.service
[Unit]
Description=Old CSI mount cleaner …
```
> [candi] Fixed CSI mount cleaner

- modules/002-deckhouse/templates/admission/validation.yaml
Add description to the validation webhook
Once upon a time it's hard to remember why we disable the validation webhook on a cluster bootstrap :)
```changes
type: chore
summary: Add memorize comments to the validation webhook.
```
> [deckhouse] Add description to the validation webhook

- ee/modules/600-flant-integration/templates/pricing/config.yaml
Proxy settings were moved to clusterConfiguration. Fix issue in 600-flant-integration with usage Values.global.modules instead
```changes
section: modules
type: fix 
summary: fix config take values from clusterConfiguration instead global module
```
> Fix that proxy settings moved to clusterConfiguration

- modules/030-cloud-provider-yandex/docs/CONFIGURATION.md
- modules/030-cloud-provider-yandex/docs/CONFIGURATION_RU.md
- modules/030-cloud-provider-yandex/hooks/storage_classes.go
- modules/030-cloud-provider-yandex/hooks/storage_classes_test.go
Yandex cloud presented new disk type `network-ssd-io-m3`. See more information [here](https://cloud.yandex.com/en-ru/docs/compute/concepts/disk)
In this pr we add storage class for new disk type.
Deckhouse should support all disk types for cloud.
Before update we have 3 storage classes
Storage class edded and deckhouse reaady
PVC created successfully
```changes
type: feature
summary: Add storage class for new disk type network-ssd-io-m3
```
> [cloud-provider-yandex] Add storage class for new disk type network-ssd-io-m3

- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
Fix misstakes docks 040-node-manager install-cuda.sh for Centos
it fix nodegroupconfiguration install-cuda.sh
install-cuda.sh will work
```changes
type: fix 
```
> [Docks] fix misstakes "yam" to "yum"

- modules/007-registrypackages/images/drbd/werf.inc.yaml
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-centos-like.yaml
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-debian-like.yaml
We are currently using an external SPAAS service instead of a cluster in any case.
It is necessary to use an internal SPAAS service to save traffic especially in closed environments.
This affects our customers.
Using an internal SPAAS service when building DRBD.
```changes
type: fix
summary: Using an internal SPAAS service instead of the external one when building DRBD.
```
> [linstor] fixes in SPAAS usage

- go_lib/deckhouse-config/service.go
- go_lib/deckhouse-config/status.go
- modules/002-deckhouse/crds/doc-ru-module.yaml
- modules/002-deckhouse/crds/module.yaml
- modules/002-deckhouse/hooks/dconfig_update_status.go
- modules/002-deckhouse/hooks/dconfig_update_status_test.go
- modules/002-deckhouse/hooks/pkg/apis/v1alpha1/module.go
- modules/005-external-module-manager/hooks/apply_release.go
- modules/005-external-module-manager/hooks/cleanup_releases.go
- modules/005-external-module-manager/hooks/cleanup_releases_test.go
* Set status for modules in their normal state
* Migrate the source field from `Embedded / External: %s` to `<empty>/%s`.
It is not clear wether a module is ready or not.
Best effort alarm!
Actually, the condition for a module stage is not correct because the `CanRunHelm` status appears right before the first run.
The right approach is to check the queue for the module run task. However, there are too many addon-operator internals involved. We should consider moving these statuses to the `Module` resource, which is directly controlled by addon-operator.
```changes
type: feature 
summary: Set ready and converging status for module configs.
```
> [deckhouse] Set ready and converging status for module configs

- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
- dhctl/pkg/kubernetes/actions/deckhouse/install.go
Add information about deckhouse pod is ready and deckhouse cluster created successfully
1. Sometimes deckhouse controller show unnecessary errors, but controller  will be ready.
We should mark the moment when the fetus becomes ready. For better user experiences.
2. Also we do not show that cluster is bootstrapped. This is especially noticeable on static clusters.
```changes
section: dhctl
type: chore
summary: Add information about deckhouse pod is ready and deckhouse cluster created successfully
```
> [dhctl] Add information about deckhouse pod is ready and deckhouse cluster created successfully

- go.mod
- go.sum
- tools/go.sum
Prevent panic if a developer made a mistake in the schema.
https://github.com/flant/addon-operator/releases/tag/v1.2.1
The problem is related to modules downloaded from module sources (when there is no guarantees that the schema is well-tested).
```changes
type: fix
summary: Skip defaulting an array without items schema to prevent panic
```
> [deckhouse-controller] Fix panic on defaulting an array without items schema

- ee/modules/600-flant-integration/hooks/pricing/envs_from_deckhouse_secret.go
- ee/modules/600-flant-integration/hooks/pricing/envs_from_deckhouse_secret_test.go
- modules/002-deckhouse/templates/registration.yaml
- modules/005-external-module-manager/hooks/create_deckhouse_modules_source.go
- modules/005-external-module-manager/hooks/create_deckhouse_modules_source_test.go
- modules/005-external-module-manager/hooks/handle_sources.go
- modules/005-external-module-manager/hooks/internal/apis/v1alpha1/source.go
For Deckhouse EE and FE deploy a module source for modules distributed for Deckhouse.
There are modules developed by the Deckhouse team separately from the main Deckhouse repository.
By deploying the default module source, it will be more convenient to see other modules that can be deployed and enable them.
```changes
type: feature
summary: |
Deploy the `deckhouse` modules source. It will make it possible to enable modules developed by the Deckhouse team but distributed separately.
The most awaited module that can be enabled now is the `deckhouse-admin` module - a convenient web-interface to administer deckhouse clusters.
```
> [external-module-manager] Deckhouse module source

- go_lib/hooks/generate_password/hook.go
- go_lib/hooks/generate_password/hook_test.go
- modules/110-istio/hooks/generate_password.go
- modules/110-istio/hooks/generate_password_test.go
- modules/300-prometheus/hooks/generate_password.go
- modules/300-prometheus/hooks/generate_password_test.go
- modules/300-prometheus/templates/alertmanager/internal/ingress.yaml
- modules/500-cilium-hubble/hooks/generate_password.go
- modules/500-cilium-hubble/hooks/generate_password_test.go
- modules/500-dashboard/hooks/generate_password.go
- modules/500-dashboard/hooks/generate_password_test.go
- modules/500-openvpn/hooks/generate_password.go
- modules/500-openvpn/hooks/generate_password_test.go
- modules/810-documentation/hooks/generate_password.go
- modules/810-documentation/hooks/generate_password_test.go
We need a flag to control basic-auth password deletion if external authentication is enabled
Prometheus alertmanager always use basic-auth event is external auth is set.
We want to keep this password forever
Alertmanager should have the `nil` password even the external auth is set
```changes
type:  chore
summary: Add ability to keep basic-auth password via the flag
```
```changes
type:  fix
summary: Keep basic-auth password for alertmanager event is external authentication is set.
```
> [go_lib] Change generate password hook

- ee/modules/650-runtime-audit-engine/images/rules-loader/hooks/webhook/webhook.py
- ee/modules/650-runtime-audit-engine/images/rules-loader/requirements.txt
Do webhook code compatibility with python 3.8
For CSE compatibility OS contains only 3.8 python. We do not have build python 3.10 itself.
```changes
type: chore
summary: Support 3.8 python webhook 
```
> [runtime-audit-engine] Support 3.8 python webhook

- deckhouse-controller/files/kubectl_wrapper.sh
- global-hooks/migrate/migrate_modules.go
- global-hooks/migrate/migrate_modules_crds.go
- modules/005-external-module-manager/crds/external-module-source.yaml
- modules/005-external-module-manager/crds/module-source.yaml
Create CRD before modules migration
EnsureCRDs works via PatchCollector and applies changes only in the end of the script. So, we don't have new CRD when creating the Modules.
1.51 is broken atm. It will fail if you have existed resources in the cluster
```changes
type: fix 
summary: Fix modules migration webhook.
```
> [external-module-manager] Fix modules migration hook

- global-hooks/create_endpoints.go
- global-hooks/create_endpoints_test.go
Remove hostname from endpoints
Hostname is not needed for single-instance installations but generates some problems and errors in the managed clusters, like EKS
```changes
type: fix
summary: Remove hostname from the deckhouse endpoints/endpointslices to avoid managed cluster problems.
```
> [global] Fix hostname for endpointslices

- helm_lib/charts/deckhouse_lib_helm/templates/_module_security_context.tpl
- modules/340-monitoring-kubernetes/images/kube-state-metrics/Dockerfile
- modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/Dockerfile
- modules/340-monitoring-kubernetes/images/node-exporter/Dockerfile
- modules/340-monitoring-kubernetes/templates/kube-state-metrics/deployment.yaml
- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
kube-state-metrics, node-exporter are now based on minimal image. Bumped a version node-exporter to 1.6.1
```changes
type: feature
summary: Images are based on a distroless image. Bumped a version node-exporter to 1.6.1
```
> [distroless] monitoring kubernetes

- ee/modules/500-operator-trivy/images/node-collector/Dockerfile
- ee/modules/500-operator-trivy/images/operator/Dockerfile
- ee/modules/500-operator-trivy/images/trivy/Dockerfile
- ee/modules/500-operator-trivy/templates/configmap.yaml
- ee/modules/500-operator-trivy/templates/deployment.yaml
Changed all images to use distroless image by default.
Using images with nothing inside them except statically linked program improves security.
operator-trivy runs without errors and all Jobs created by it succeed and create appropriate CRs.
```
root@klimentyev-master-0:~# kubectl -n d8-operator-trivy get pod
NAME                                        READY   STATUS      RESTARTS   AGE
operator-66c658fbb5-dg4fb                   2/2     Running     0          39m
root@klimentyev-master-0:~# kubectl -n d8-operator-trivy get vulnerabilityreports.aquasecurity.github.io -A
NAMESPACE              NAME                                                       REPOSITORY          TAG   SCANNER   AGE
d8-cni-simple-bridge   daemonset-simple-bridge-simple-bridge                      sys/deckhouse-oss …
```
> [operator-trivy] Distroless

- modules/030-cloud-provider-yandex/images/yandex-csi-plugin/Dockerfile
Updated yandex-csi-driver. In the new version, the calculation of the limit of disks per node has been fixed.
In the new version of yandex-csi-driver, the calculation of the limit of disks per node has been fixed.
<details>
```
root@destroymeafter31aug-master-0:~# kubectl get po -o wide
NAME     READY   STATUS    RESTARTS   AGE     IP            NODE                                              NOMINATED NODE   READINESS GATES
asd-0    1/1     Running   0          50m     10.111.0.12   destroymeafter31aug-master-0                      <none>           <none>
asd-1    1/1     Running   0          12m     10.111.0.13   destroymeafter31aug-master-0                      <none>           <none>
asd-2    1/1     Running   0          12m     10.111.0.14   destroymeafter31aug-master-0 …
```
> [cloud-provider-yandex] Fix calculate disks limit in csi driver

- candi/bashible/common-steps/cluster-bootstrap/098_cleanup_after_cluster_bootstrap.sh.tpl
Candi's `098_cleanup.sh` will now also clean `/tmp` from remnants of the bootstrap bundle.
See [#5597](https://github.com/deckhouse/deckhouse/issues/5597#issuecomment-1695348015), point №2
```changes
section: candi
type: chore
summary: `/tmp` is now cleared before node is rebooted after bootstrap.
```
> [candi] Clean /tmp after bootstrap

- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-centos-like.yaml
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-debian-like.yaml
We added the `make clean` command to clean the directory from previous compilation results.
In rare cases, when switching kernels, 'make' would use previous compilation results, leading to the build of a broken DRBD module
No issues with building the DRBD module when changing the kernel.
```changes
type: fix
summary: Fix rare issues with building the DRBD module when changing the kernels.
```
> [linstor] Add the 'make clean' command

- candi/bashible/common-steps/node-group/002_add_system_proxy.sh.tpl
- candi/bashible/common-steps/node-group/031_install_containerd.sh.tpl
- candi/bashible/common-steps/node-group/050_configure_and_start_containerd.sh.tpl
- modules/007-registrypackages/images/containerd/scripts/install
- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
- tools/astra_integrity_check/main.go
- tools/astra_integrity_check/pre_run.go
- tools/astra_integrity_check/result_xml.go
- tools/astra_integrity_check/run_test.sh
Systemd's `containerd.service` shipped with deckhouse is now installed and used as `containerd-deckhouse.service` to avoid corruption of `containerd` packages in OS repos.
Also, a new testing tool is implemented to validate Astra Linux SE security compliance.
This is necessary to comply with Astra Linux SE security requirements.
```changes
section: candi
type: chore
summary: Containerd systemd unit that ships with Deckhouse renamed to `containerd-deckhouse.service`.
```
> [candi] Rename vendored containerd.service into containerd-deckhouse.service

- ee/modules/030-cloud-provider-openstack/template_tests/module_test.go
- ee/modules/030-cloud-provider-openstack/templates/cloud-controller-manager/secret.yaml
This PR fix error in openstack cloud-controller-manager config.
When the k8s cluster version > 1.24, the `ignore-volume-microversion` option does not appear in the cloud-controller-manager configuration regardless of the option value in the module configuration. This leads to problems with PV creating in some openstack clouds.
```
root@dev-master-0:~# kubectl -n d8-cloud-provider-openstack get secret cloud-controller-manager -o json | jq -r '.data."cloud-config"' | base64 -d
[Global]
...
[BlockStorage]
rescan-on-resize = true
```
```
root@dev-master-0:~# kubectl -n d8-cloud-provider-openstack get secret cloud-controller-manager -o json | jq -r '.data."cloud-config"' | base64 -d
[Global]
...
[BlockStorage]
ignore-volume-microversion = false
rescan-on-resize = true
```
```changes
section: …
```
> [cloud-provider-openstack] fix ignoreVolumeMicroversion parameter appliance for k8s>1.24

- global-hooks/migrate/migrate_modules.go
Add the check to prevent nil pointer dereference 
```
{"binding":"onStartup","event.type":"OperatorStartup","hook":"migrate/migrate_modules.go","hook.type":"global","level":"info","msg":"ExternalModuleSource resource is not in the cluster","output":"gohook","queue":"main","task.id":"12c91450-3aa8-4a61-bc8b-5c7f92091004","time":"2023-09-10T17:17:38Z"}
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x354932a]
goroutine 8 [running]:
github.com/deckhouse/deckhouse/global-hooks/migrate.modulesCRMigrate(0xc000e323c0, {0x4623bf0?, 0xc000206660?})
/deckhouse/global-hooks/migrate/migrate_modules.go:104 +0x66a
github.com/deckhouse/deckhouse/global-hooks/migrate.init.func3(0x3be9601?) …
```
> [external-module-manager] Fix panic if there are no resources for migration

- modules/300-prometheus/images/grafana/grafana_home_dashboard.json
* clarify the title and description for the panel that shows the difference between the oldest metric timestamp and the current time
* limit the query to a specific namespace 
Fixes https://github.com/deckhouse/deckhouse/issues/5691
```changes
type: fix
summary: Clarify description and formula for the oldest metrics panel on the starting page of Grafana
```
> [prometheus] Change description and formula for oldest metrics panel

- deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go
- ee/modules/502-delivery/hooks/https/copy_custom_certificate.go
- ee/modules/502-delivery/openapi/values.yaml
- ee/modules/502-delivery/template_tests/copy_custom_certificate_test.go
- ee/modules/502-delivery/templates/argocd/argocd-cm-configmap.yaml
Add CustomCertificate hook for delivery module.
Fix https://github.com/deckhouse/deckhouse/issues/5238. Delivery module fails when using CustomCertificate https mode.
This affects our customers.
Delivery module work with CustomCertificate https mode.
```changes
type: fix
summary: Fix delivery module work in customCertificate https mode.
```
> [delivery] Fix customCertificate

- modules/002-deckhouse/templates/deployment.yaml
- modules/002-deckhouse/templates/service.yaml
Change deckhouse kube-rbac-proxy port
Deckhouse pod lives in the hostNetwork. We have bound kube-rbac-proxy to the port 8080. It's a common used port that could be busy by client application.
We have to remove deckhouse to the another port
Deckhouse gets stuck with some customers
```changes
type: fix
summary: Move deckhouse `kube-rbac-proxy` port to `9889`, to avoid conflicts with user applications.
```
> [deckhouse] Fix deckhouse port

- modules/460-log-shipper/hooks/testdata/__default-config.json
- modules/460-log-shipper/templates/configmap.yaml
Toggle the option to suppress timestamps in the vector config
Metrics exposed by vector look like this
```
vector_uptime_seconds{host="log-shipper-agent-5hjmn"} 513828 1694687172697
```
Because of the last timestamp values, Prometheus can throw errors like the following
```
ts=2023-09-14T13:28:39.352Z caller=scrape.go:1690 level=warn component="scrape manager" scrape_pool=podMonitor/d8-monitoring/log-shipper-agent/0 target=https://10.111.23.184:9254/metrics msg="Error on ingesting out-of-order samples" num_dropped=8
```
However, a timestamp is not a necessity. For our use case, it is ok to let Prometheus handle timestamps on its own. 
```changes
type: feat
summary: Suppress metrics timestamp to avoid out-of-order ingestion error
```
> [log-shipper] Suppress metrics timestamp

- helm_lib/charts/deckhouse_lib_helm/templates/_module_security_context.tpl
- modules/300-prometheus/images/grafana/Dockerfile
- modules/300-prometheus/images/grafana/entrypoint/main.go
- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Static build grafana-cli for distroless. Fix issue with add custom grafana plugins.
We can run grafana-cli in distroless images. 
Fixed issue with add custom grafana plugins to the grafana.
Because clients can't add custom plugins to the grafana.
We can add custom plugins to the grafana.
```shell
2023/09/14 15:18:00 copy plugins: chmod /etc/grafana/plugins: operation not permitted
2023/09/14 20:40:24 convert env: fork/exec /usr/share/grafana/bin/grafana-cli: no such file or directory
$ ldd grafana-cli 
linux-vdso.so.1 (0x00007ffd3cb93000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7d772ec000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7d772e7000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7d77000000)
/lib64/ld-linux-x86-64.so.2 …
```
> [prometheus] fix issue with add custom grafana plugins

- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Fixed permissions for existing files after changing GID and UID.
Prometheus can't start
<details>
```shell
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8/meta.json' to 64535:64535
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8/index' to 64535:64535
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8/tombstones' to 64535:64535
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8/chunks/000001' to 64535:64535
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8/chunks' to 64535:64535
changed ownership of '/prometheus-db/01HAAYRKFEESRWBYSNZDG445S8' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PN8J7238BFGPER3SYFTP/meta.json' to 64535:64535
changed ownership of '/prometheus-db/01HAJ8PN8J7238BFGPER3SYFTP/index' to …
```
> [prometheus] Fix permissions for existing files

- modules/300-prometheus/images/grafana/grafana_home_dashboard.json
Fixing the etcd version in the home grafana dashboard.
The `etcd_cluster_version` metric disappeared, so we will use the `etcd_server_version`.
Also, the new `etcd_server_version` metric has a patch version, but `etcd_cluster_version` doesn't.
All the dashboards has empty etcd plate in dashboard. It is weird.
The etcd version is showed in home dashboards.
```changes
type: fix
summary: The etcd version in the home dashboard is fixed.
```
> [monitoring] Fixing the etcd version in the home dashboard

- candi/bashible/bashbooster/50_deckhouse_registrypackages.sh
- candi/bashible/bashible.sh.tpl
- candi/bashible/bundles/centos/bootstrap.sh.tpl
- candi/bashible/bundles/debian/bootstrap.sh.tpl
- candi/bashible/bundles/ubuntu-lts/bootstrap.sh.tpl
- candi/bashible/common-steps/cluster-bootstrap/060_bootstrap_kubernetes_pki.sh.tpl
- dhctl/pkg/app/app.go
- dhctl/pkg/operations/bootstrap.go
- dhctl/pkg/system/ssh/frontend/kube-proxy.go
- dhctl/pkg/system/ssh/frontend/upload-script.go
- ee/candi/bashible/bundles/alteros/bootstrap.sh.tpl
- ee/candi/bashible/bundles/altlinux/bootstrap.sh.tpl
- ee/candi/bashible/bundles/astra/bootstrap.sh.tpl
- ee/candi/bashible/bundles/redos/bootstrap.sh.tpl
Temporary files created by bashible steps during bootstrap will now be put into `/opt/deckhouse/tmp` instead of `/tmp`. `dhctl` will create this directory during master node bootstrap.
This solves points 1,3,4 and 5 of [#5597](https://github.com/deckhouse/deckhouse/issues/5597#issuecomment-1695348015)
```changes
section: candi
type: chore
summary: Point $TMPDIR to `/opt/deckhouse/tmp` during bashible bootstrap.
```
```changes
section: dhctl
type: chore
summary: Render bootstrap bundle into `/opt/deckhouse/tmp`.
```
```changes
section: candi
type: fix
summary: Delete registrypackage files if it failed to install before retrying installation.
```
> [candi] Use /opt/deckhouse/tmp instead of /tmp during bootstrap

- modules/040-node-manager/images/cluster-autoscaler/werf.inc.yaml
- modules/040-node-manager/templates/cluster-autoscaler/deployment.yaml
Fix liveness probe thru kube-rbac-proxy.
After moving to distroless cluster-autoscaler liveness probe does not work due to absent wget binary.
```changes
section: candi
type: fix
summary: Fix `cluster-autoscaler` liveness probe.
```
> [cluster-autoscaler] fix liveness probe

- .github/scripts/js/constants.js
- .github/workflow_templates/e2e.abort.multi.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
For further kubernetes 1.28 e2e test we have to update CI before
```changes
section: ci
type: feature
summary: Add Kubernetes 1.28 e2e tests.
```
> [ci] Add kubernetes 1.28 e2e pipelines

- dhctl/pkg/config/meta.go
- dhctl/pkg/config/meta_test.go
Added registryDockerCfg validation in MetaConfig.Prepare() 
Fix for https://github.com/deckhouse/deckhouse/issues/3814. 
In some cases we could have unexpected blank or invalid value at REGISTRY_AUTH in bootstrap.sh script. It is caused of incorrect "auths" field's value in docker credentials, which is got from registryDockerCfg field in InitConfiguration manifest. To prevent this issue the validation was added. 
InitConfiguration with invalid registryDockerCfg will fail dhctl bootstrap.
```changes
section: dhctl
type: fix
summary: Add registryDockerCfg validation
impact_level:  default
```
> [dhctl] Add registryDockerCfg validation

- ee/modules/600-flant-integration/template_tests/module_test.go
- ee/modules/600-flant-integration/templates/pricing/config.yaml
Fix error with template rendering for flant-pricing module in case of absence clusterConfiguration secret.
When we install deckhouse in managed environments, we do not have filled clusterConfiguration object and render config for the grafana-agent is failed.
```changes
section: flant-pricing
type: fix
summary: Fix rendering config in the case of the absence `clusterConfiguration`.
```
> [flant-pricing] fix proxy configuration

- dhctl/pkg/kubernetes/actions/deckhouse/install.go
In CreateDeckhouseManifests method we search `ConfigMap "Deckhouse"` by a new name.
We need that to prevent an error of editing `ConfigMap "Deckhouse"` while we try to create `ConfigMap "Deckhouse"` after cluster's restart.
After cluster restart we will not have an error that `ConfigMap "Deckhouse"` is cannot be edited.
```changes
section: dhctl
type: fix
summary: Fix restarting bootstrap process
```
> [dhctl] Fix restarting bootstrap process 

- docs/documentation/_data/deckhouse-used-directories.yml
- docs/documentation/_data/sidebars/main.yml
- docs/documentation/_includes/deckhouse-directories-csv.liquid
- docs/documentation/_includes/security_software_setup.liquid
- docs/documentation/pages/SECURITY_SOFTWARE_SETUP.md
- docs/documentation/pages/SECURITY_SOFTWARE_SETUP_RU.md
- docs/documentation/pages/deckhouse-directories.csv
- docs/documentation/pages/deckhouse-directories_ru.csv
Add a list of directories used by Deckhouse. It is needed to properly configure the security software (antivirus scanners, etc.).
Closes: https://github.com/deckhouse/deckhouse/issues/5226
Some security software gives false positive events when scanning a node. Deckhouse security administrator needs a list of exceptions to tune security scanners.
```changes
section: docs
type: chore
summary: Add a list of directories used by Deckhouse. It is needed to properly configure the security software.
```
> [doc]  Add a list of directories used by Deckhouse

- modules/462-loki/templates/statefulset.yaml
Fixed permissions for existing files after changing GID and UID.
Loki can't start
```changes
section: loki
type: fix
summary: Fixed permissions for existing files after changing GID and UID.
```
> [loki] fix permissions for existing files

- candi/version_map.yml
- helm_lib/Chart.lock
- helm_lib/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/templates/_csi_controller.tpl
- modules/000-common/images/csi-external-attacher/werf.inc.yaml
- modules/000-common/images/csi-external-provisioner/werf.inc.yaml
- modules/000-common/images/csi-external-resizer/werf.inc.yaml
- modules/000-common/images/csi-external-snapshotter/werf.inc.yaml
- modules/000-common/images/csi-livenessprobe/werf.inc.yaml
- modules/000-common/images/csi-node-driver-registrar/werf.inc.yaml
csi binaries use distroless images and built from our repos instead of using prebuilt images from google.
This PR is a part of moving Deckhouse to distroless.
```changes
section: candi
type: chore
summary: move csi-external-attacher to distroless.
---
section: candi
type: chore
summary: move csi-external-provisioner to distroless.
---
section: candi
type: chore
summary: move csi-external-resizer to distroless.
---
section: candi
type: chore
summary: move csi-external-snapshotter to distroless.
---
section: candi
type: chore
summary: move csi-livenessprobe to distroless.
---
section: candi
type: chore
summary: move csi-node-driver-registrar to distroless.
```
> [distroless] move csi binaries to distroless

- .github/ci_includes/werf_envs.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- tools/images_tags/main.go
- werf-giterminism.yaml
- werf.yaml
Added CI variable CRATESPROXY to set up proxy address for crates.io (rust cargo).
This proxy will be used to pull rust modules.
```changes
section: ci
type: chore
summary: add env var for crates proxy
```
> [ci] add env var for crates proxy

- candi/bashible/docs/README.md
- dhctl/pkg/operations/bootstrap.go
Added more command checks in CheckDHCTLDependencies method to prevent unexpected fails in bootstrap.sh script.
Fix https://github.com/deckhouse/deckhouse/issues/5066. It solves the problem of unexpected bootstrap.sh failure, if some of shell-commands are missing.
If some of shell-commands using in bootstrap.sh isn't installed, we'll get an error of a missing shell-command.
```changes
type: fix
summary: client will get an error of missing shell-command in bootstrap.sh 
```
> Added more command checks in CheckDHCTLDependencies method

- global-hooks/create_endpoints.go
- global-hooks/create_endpoints_test.go
Endpoints cleanup generate an error:
```
Delete object //d8-system/deckhouse-mfqfl: apiVersion '', kind '' is not supported by cluster
```
Objects, listed from cluster don't have apiVersion and Kind inside (don't know why). We have to set in constantly
Deckhouse can break on endpointslice deletion
```changes
type: fix
summary: Fix orphaned endpointslice deletion.
```
> [global] Fix endpoints cleanup

- helm_lib/charts/deckhouse_lib_helm/templates/_node_affinity.tpl
- modules/470-chrony/enabled
- modules/470-chrony/images/chrony/start.sh
- modules/470-chrony/template_tests/module_test.go
- modules/470-chrony/templates/daemonset.yaml
- modules/470-chrony/templates/deployment.yaml
- modules/470-chrony/templates/service.yaml
- testing/matrix/linter/rules/rules.go
`470-chrony` is now deployed to all nodes at once, but master nodes are configured run 2 chrony processes at once, one acts as an intermediate NTP server, pulling clock from some other NTP service if possible, other works as regular chrony NTP client. 
Chrony clients are configured to use master nodes as their primary NTP clock source (`stratum 5`) via a headless service acting as an NTP pool, and fall back to NTP servers from module config in case something bad happens with masters.
See #2949
```changes
type: feature
summary: Master nodes act as NTP servers for cluster.
```
> [chrony] Sync time on Nodes with control plane.

- go.mod
- go.sum
- tools/go.sum
Deckhouse deletes all helm releases from the d8-system namespace. It can be flaky in cases where clients has multi master cluster with modules downloaded from sources.
https://github.com/flant/addon-operator/pull/412
```changes
type: fix
summary: Do not purge unknown helm releases
```
> [deckhouse-controller] Do not purge unknown helm releases

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/capacity-planning/capacity-planning.json
Removes `".*"` regexp from `allValue` for nodes and namespaces.
This allows automatic filtering out namespaces not present on a node/nodes, when not all nodes are selected.
```changes
type: fix
summary: Improve filtering in the Capacity Planning dashboard.
```
> [monitoring-kubernetes] Remove allValue regexp from Capacity Planning

- candi/cloud-providers/yandex/openapi/instance_class.yaml
- modules/140-user-authz/docs/USAGE.md
- modules/140-user-authz/docs/USAGE_RU.md
Fix typos in user-authz module examples, and yandex cloud provider/instance_class documentation (fix based on https://github.com/deckhouse/deckhouse/blob/main/candi/cloud-providers/yandex/terraform-modules/master-node/variables.tf#L52 )
```changes
section: docs
type: chore
summary: Fix typos in user-authz module examples and ya/instance_class documentation.
```
> [docs] Fix typos in user-authz module examples and ya/instance_class documentation

- candi/bashible/common-steps/node-group/031_install_containerd.sh.tpl
- modules/007-registrypackages/images/containerd/werf.inc.yaml
- testing/library/images_tags_generated.go
Update containerd to 1.6.24
Update [runc](https://github.com/containerd/containerd/blob/v1.6.24/script/setup/runc-version) to 1.1.9
<details><summary>before</summary>
```shell
root@dev-master-0:~# kubectl get po -o wide -A
NAMESPACE                    NAME                                                                   READY   STATUS    RESTARTS       AGE     IP             NODE                                              NOMINATED NODE   READINESS GATES
d8-admission-policy-engine   gatekeeper-audit-f6f894c77-8n2vd                                       3/3     Running   0              23h     10.111.1.146   dev-worker-79d06ec4-5c6b6-5kp6w   <none>           <none>
d8-admission-policy-engine   gatekeeper-controller-manager-76497d74bf-lfmvz                         2/2     Running   0 …
```
> [registrypackages] Update containerd to 1.6.24

- .github/dependabot.yml
- modules/402-ingress-nginx/images/kube-rbac-proxy/src/controller-probe.go
- modules/402-ingress-nginx/images/kube-rbac-proxy/src/go.mod
- modules/402-ingress-nginx/images/kube-rbac-proxy/werf.inc.yaml
- modules/402-ingress-nginx/templates/controller/controller.yaml
- testing/library/images_tags_generated.go
Rewrite preStop probe to go.
After moving build to distroless, preStop probe does not work due to shell absense in kube-rbac-proxy pod. We create static Go probe to solve this problem.
```changes
section: ingress-controller
type: fix
summary: Fix controller preStop probe.
impact: Ingress controller will restart.
```
> [ingress-controller] fix controller preStop probe

- candi/bashible/bundles/centos/bootstrap.sh.tpl
- candi/bashible/bundles/debian/bootstrap.sh.tpl
- candi/bashible/bundles/ubuntu-lts/bootstrap.sh.tpl
- ee/candi/bashible/bundles/alteros/bootstrap.sh.tpl
- ee/candi/bashible/bundles/altlinux/bootstrap.sh.tpl
- ee/candi/bashible/bundles/astra/bootstrap.sh.tpl
- ee/candi/bashible/bundles/redos/bootstrap.sh.tpl
- modules/040-node-manager/templates/node-group/_bootstrap_script.tpl
The size of the cloud-init data has been reduced because we're limited to 16384 bytes
```changes
type: fix
summary: The size of the cloud-init data has been reduced
```
> [cloud-provider-aws] Reduce cloud-init data size

- modules/460-log-shipper/crds/cluster-log-destination.yaml
- modules/460-log-shipper/crds/cluster-logging-config.yaml
- modules/460-log-shipper/crds/pod-logging-config.yaml
Fix various reported bugs
- Fixes https://github.com/deckhouse/deckhouse/issues/5516
- Fixes https://github.com/deckhouse/deckhouse/issues/5382
- Make the type field mandatory for the buffer settings
```changes
type: fix
summary: Fix validation for the buffer ClusterLogDestination schema.
---
type: fix
summary: Add stricter validation for label selectors. Prevents the deckhouse pods from panicking.
---
type: fix
summary: Fix custom multiline parser validation for PodLoggingConfig (previously, it was not possible to use the Custom type due to a validation bug).
```
> [log-shipper] Fix CRD schema bugs

- modules/040-node-manager/monitoring/prometheus-rules/machine-controller-manager.tpl
Delete duplicated the expr field in the D8MachineControllerManagerPodIsNotRunning alert template.
```changes
type: chore
summary: Delete duplicated the expr field in the D8MachineControllerManagerPodIsNotRunning alert template.
```
> [node-manager] Fix D8MachineControllerManagerPodIsNotRunning alert

- modules/300-prometheus/images/grafana/Dockerfile
Switching grafana to ubuntu container.
The alexanderzobnin-zabbix-appliance plugin has dependencies on libraries that are not in the distroless container
An issue from customer
The alexanderzobnin-zabbix-appliance plugin working
```changes
type: fix
summary: Switch Grafana to using the Ubuntu container.
impact: Grafana will restart.
```
> [prometheus] switch grafana to ubuntu container

- modules/402-ingress-nginx/images/controller-1-6/Dockerfile
- modules/402-ingress-nginx/images/controller-1-6/patches/README.md
- modules/402-ingress-nginx/images/controller-1-6/patches/auth-cookie-always.patch
- modules/402-ingress-nginx/templates/controller/configmap.yaml
Set `add_header          Set-Cookie $auth_cookie always;` to avoid user logout on response codes >= 400
We have this patch in the controller 1.1 but it was missed in the controller 1.6
Users can have force logout randomly. It's a regression bug.
```changes
type: fix
summary: Fix bug with absent auth cookie, which leads to logout users sometimes from web pages with authorization.
impact: Ingress controller 1.6 will restart.
```
> [ingress-nginx] add auth cookie header always

- ee/fe/modules/340-monitoring-applications/applications/pgbouncer/grafana-dashboards/pgbouncer.json
- ee/fe/modules/340-monitoring-applications/docs/CONFIGURATION.md
- ee/fe/modules/340-monitoring-applications/docs/CONFIGURATION_RU.md
Add Grafana dashboard for pgbouncer.
```changes
type: feature
summary: Add Grafana dashboard for pgbouncer.
```
> Added pgbouncer grafana dashboard (also for yandex odyssey)

- modules/402-ingress-nginx/hooks/safe_daemonset_update.go
- modules/402-ingress-nginx/hooks/safe_daemonset_update_test.go
Add `ExecutionMinInterval: 5 * time.Second` and `ExecutionBurst:       1` settings to `safe_daemonset_update` hook so it doesn't trigger to often during updates.
Update `safe_daemonset_update` hook logic for `HostWithFailover` inlet by introducing postponed updates.
When an update of main controller is postponed (not more than once), failover controller gets some extra time for launching its updates so that the hook could take them into consideration. This way we get rid of the situation when the hook allows main controller to launch its update ahead of failover controller's updates, resulting in having both controllers updated simultaneously.
it fixes a noticeable and annoying issue.
HostWithFailover inlet doesn't have its main and failover controllers updated at the same time. …
> [ingress-nginx] apply postpone update to main controller of HostWithFailover inlet

- modules/005-external-module-manager/hooks/apply_release.go
- modules/005-external-module-manager/hooks/apply_release_test.go
Handle absent modules from sources
If we have `Deployed` release of a source module and absent symlink for this module, deckhouse will try to restore it. But if target module version does not exist, we will get infinite deckhouse restart.
This fix will will suspend broken release with the detailed message
```
some-module-v0.1.12   Suspended    6h34m            Desired version of module met problems: not found
```
```changes
type: fix
summary: Handle deployed source modules with absent version directory. Avoid infinite deckhouse restart on absent module.
```
> [external-module-manager] Handle absent versions of deployed modules

- modules/002-deckhouse/templates/admission/validation.yaml
Restrict the webhook to validate only d8 ConfigMaps.
The `kube-root-ca.crt` ConfigMap added to every namespace and mounted into every pod with service account token. We should not forward requests to update/delete this ConfigMap to the webhook.
In addition, this can cause problems in the cluster when Kubernetes tries to update the certificate, but deckhouse-controller (and consequently the webhook) is unavailable.
We don't.
The webhook validate only d8 ConfigMaps.
```changes
type: fix
summary: Restrics the webhook to validate only d8 configmaps.
```
> [deckhouse] Restrict the webhook to validate only d8 configmaps

- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
Add `-n default` into docs shell example
If user is switched in non-default context, default namespace must be specified.
```changes
type: chore
```
> [docs] [node-manager] Add namespace key for compatibility

- dhctl/pkg/config/base.go
- dhctl/pkg/config/errors.go
- dhctl/pkg/config/load.go
Moved cluster config validation from `commands` package to separated `configure` package.
This will allow to import validation functionality (`ParseClusterConfiguration`) into DeckhouseCommander (and probably into other projects as needed)
> [dhctl] fix(dhctl-for-commander): dhctl cluster config validation

- candi/bashible/bashible.sh.tpl
Added creation of TMPDIR directory in bashible.sh.
Bashible update does not work on some OS distributions.
```changes
section: candi
type: fix
summary: Add creation of the `TMPDIR` directory in the `bashible.sh` script.
```
> [candi] Add lost mkdir TMPDIR in bashible.sh

- modules/470-chrony/images/chrony/start.sh
- modules/470-chrony/template_tests/module_test.go
- modules/470-chrony/templates/daemonset.yaml
- modules/470-chrony/templates/deployment.yaml
Enabled `hostNetwork` for chrony pods
This is required for `node-manager`'s NTP collector to be able to access Node's NTP server.
This PR fixes node time alerts in `node-manager`
```changes
type: fix
summary: Run chrony pods in host network namespace.
```
> [chrony] Move chronyd back to host network namespace

- modules/041-linstor/images/linstor-server/Dockerfile
- modules/041-linstor/images/linstor-server/liveness.sh
- modules/041-linstor/images/piraeus-operator/patches/050-change-liveness-probe.patch
- modules/041-linstor/templates/linstor-controller/linstorcontroller.yaml
Workaround for several annoying issues in LINSTOR related to hanging controller.
The PR is a step to stable LINSTOR.
Our customers are eager to have this PR in their clusters.
Correctly working linstor controller liveness probe
```changes
type: fix
summary: Workaround for several annoying issues in LINSTOR related to hanging controller.
```
> [linstor] changed controller's liveness probe

- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/kubernetes/actions/deckhouse/converge.go
- dhctl/pkg/operations/converge/converger.go
Introduced **optional** commander-mode for converge operation. In this mode dhctl converge operation:
* uses ClusterConfiguration and ProviderClusterConfiguration which are externally provided, rather than in-cluster;
* overrides in-cluster ClusterConfiguration and ProviderClusterConfiguration with externally provided data using phase called "InstallDeckhousePhase". Which is exactly same phase used in the bootstrap operation to create in-cluster configuration. By analogy converge updates this configuration on the same phase (possibly InstallDeckhouse phase could be called just DeckhousePhase, like BaseInfraPhase rather than InstallBaseInfraPhase).
* we use externally initialized state-cache rather than dhctl state stored in-cluster, then write resulting dhctl state into the cluster;
In …
> [dhctl] feat(dhctl-for-commander): use given cluster-configuration data in commander mode in the converge operation

- modules/150-user-authn/images/self-signed-generator/src/main.go
Fix generation a self signed certificate for crowd-basic-auth-proxy
No certificate is generated for crowd-basic-auth-proxy
Cusromer issue
Certificate generated successfully
```changes
section: user-authen
type: fix
summary: Fix generation a self signed certificate for `crowd-basic-auth-proxy`.
```
> [user-authn] fix generation self signet certificate for crowd-basic-auth-proxy

- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Fix fix-permissions init-container to run under kesl security. In prometheus we use main prometheus image as init container which cause a problems with container start. We change init container image to alpine.
When kesl security scanner is enabled, prometheus pods do not start due to problem with init containers.
In logs:
```
Oct 06 10:47:44 dev-worker-2a6158ff-6764d-2grk2 containerd[622]: time="2023-10-06T10:47:44.263309413Z" level=info msg="CreateContainer within sandbox \"a0f03a15e7fb6026999dae88ca78bcd4b09a97d27cd3b5c8e690efc846b72f0c\" for container &ContainerMetadata{Name:permissions,Attempt:0,}"
Oct 06 10:47:44 dev-worker-2a6158ff-6764d-2grk2 containerd[622]: time="2023-10-06T10:47:44.264267653Z" level=error msg="CreateContainer within sandbox …
```
> [prometheus] fix fix-permissions init-container to run under kesl security

- modules/041-linstor/images/linstor-server/liveness.sh
Fixed error in linstor controller liveness probe logic.
Because of absent log file alive controller can be killed incorrectly
This is urgent situation that can affect our customers
Linstor controller liveness probe is working correctly now
```changes
type: fix
summary: Fixed error in LINSTOR controller liveness probe logic.
impact: Linstor controller will be restarted.
```
> [linstor] fix in linstor controller liveness probe

- ee/modules/140-user-authz/images/webhook/go.mod
- ee/modules/140-user-authz/images/webhook/web/hook/handler.go
The termination of the process when receiving invalid data has been removed. 
(Close https://github.com/deckhouse/deckhouse/issues/5644)
Now invalid data works the same as empty json
```changes
section:140-user-authz
type: fix
summary: webhook no longer crashes if called without data
```
> [user-authz] fix webhook crash on empty request data

- modules/150-user-authn/images/dex/Dockerfile
- modules/150-user-authn/images/dex/patches/401-password-auth.patch
- modules/150-user-authn/images/dex/patches/README.md
https://github.com/dexidp/dex/pull/2796
```changes
type: fix
summary: Return 401 instead of 200 if a password authentication attempt failed.
```
> [user-authn] Return 401 instead of 200 if a password authentication attempt failed

- ee/modules/030-cloud-provider-openstack/images/cloud-data-discoverer/werf.inc.yaml
- ee/modules/030-cloud-provider-openstack/templates/cloud-data-discoverer/deployment.yaml
- modules/030-cloud-provider-aws/images/cloud-data-discoverer/werf.inc.yaml
- modules/030-cloud-provider-aws/templates/cloud-data-discoverer/deployment.yaml
- modules/030-cloud-provider-azure/images/cloud-data-discoverer/werf.inc.yaml
- modules/030-cloud-provider-azure/templates/cloud-data-discoverer/deployment.yaml
- modules/030-cloud-provider-gcp/images/cloud-data-discoverer/werf.inc.yaml
- modules/030-cloud-provider-gcp/templates/cloud-data-discoverer/deployment.yaml
cloud-data-discoverer binaries use distroless images and built from our repos instead of using alpine:go images.
This PR is a part of moving Deckhouse to distroless.
```changes
type: chore
summary: "`cloud-data-discoverer` use distroless based image."
---
type: chore
summary: "`cloud-data-discoverer` use distroless based image."
---
type: chore
summary: "`cloud-data-discoverer` use distroless based image."
---
section: ee/cloud-provider-openstack
type: chore
summary: "`cloud-data-discoverer` use distroless based image."
```
> [distroless] move cloud-data-discoverer binaries to distroless

- helm_lib/Chart.lock
- helm_lib/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/templates/_node_affinity.tpl
- modules/030-cloud-provider-yandex/templates/cloud-controller-manager/deployment.yaml
- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/script.sh
Fix working in hybrid environments for cloud-provider-yandex.
In hybrid environment cloud-provider-yandex does not work properly.
```changes
type: fix
summary: fix working in hybrid environments for cloud-provider-yandex
```
> [cloud-provider-yandex] fix working in hybrid environments

- modules/040-node-manager/crds/nodeuser.yaml
Add warning about deprecated `sshPublicKey` parameter of the `nodeUser` resource.
```changes
section: docs
type: chore
summary: Add warning about deprecated `sshPublicKey` parameter of the `nodeUser` resource.
```
> [docs] Add warning about deprecated sshPublicKey parameter of the nodeUser

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
Changed example commands using `etcdctl` to list ectd members to not use `sh`. Solution for etcd backup is still in development
Since images are now distroless, old examples that used `sh` did not work
Not necessary.
```changes
type: chore
```
> [docs][control-plane-manager] Drop sh from etcdctl member list examples

- ee/modules/650-runtime-audit-engine/templates/daemonset.yaml
Fix events unbuffered output mode
Without unbuffered mode sometimes events take long time to appear in log.
```changes
type: fix
summary: fix events unbuffered output mode
```
> [runtime-audit-engine] fix events unbuffered output mode

- modules/041-linstor/templates/linstor-csi/linstorcsidriver.yaml
Hardcoded the number of parallel CSI workers (attacher, provisioner, snapshotter, resizer).
Now LINSTOR always get 10 concurrent processes of each CSI worker type. We hardcoded this value to 1, this will make LINSTOR more stable.
We have customers, who are experiencing issues due to too many parallel running processes.
More stable LINSTOR module work.
```changes
type: feature
summary: A setting has been added to specify the number of parallel CSI workers (attacher, provisioner, snapshotter, resizer).
```
> [linstor] number of parallel CSI workers hardcoded

- candi/control-plane-kubeadm/config.yaml.tpl
- modules/040-control-plane-manager/images/kube-controller-manager/werf.inc.yaml
Disable in-tree rbd plugin for k8s>=1.24.
Mainly, in-tree rbd plugin is deprecated in the [k8s 1.28](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features). But we experienced some problems with in-tree rbd plugin and containerd (https://github.com/deckhouse/deckhouse/issues/304). So, when docker CRI was deprecated in k8s 1.24, we need also to deprecate use of in-tree rbd plugin. 
```changes
section: candi
type: chore
summary: disable in-tree rbd plugin for k8s>=1.24
impact: control-plane pods should be restarted
```
> [candi] disable in-tree rbd plugin for k8s>=1.24

- modules/041-linstor/images/linstor-server/Dockerfile
- modules/041-linstor/images/linstor-server/patches/README.md
- modules/041-linstor/images/linstor-server/patches/fix-symlinks.patch
Automatically fix symlinks for devices
Upstream PR https://github.com/LINBIT/linstor-server/pull/370
This change is workaround for specific set of issues, often related to udev,
which lead to the disappearance of symlinks for LVM devices on a working system.
These issues commonly occur during device resizing and deactivation,
causing LINSTOR exceptions during accessing DRBD super-block of volume.
There is a customer who faces the problem quite often.
When symlink to device is not exists, linstor will try to make it first.
```changes
type: fix
summary: automatically fix symlinks for devices
```
> [linstor] automatically fix symlinks for devices

- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-centos-like.yaml
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Usermode helper has been disabled according to vendor recommendations. More information can be found here:
[Commit](https://github.com/LINBIT/drbd/commit/819285d065f1f81bad7b97e32a64017b5e15948d)
[Issue](https://github.com/LINBIT/linstor-server/issues/121)
[Issue](https://github.com/piraeusdatastore/piraeus-operator/issues/134)
Information from vendor:
```
This change is intended to help containerization of DRBD components.
Especially the ones that interact with the kernel.
The goal is to even load the kernel module from a container, but for now
assume we loaded the ko on the host. Then, in the container, we create
resources and therefore interact with the host kernel. One thing the
host kernel does is it calls various usermode helpers.
The mechanism is to call the usermode helper …
```
> [linstor] disable  usermode_helper

- candi/cloud-providers/azure/openapi/cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/doc-ru-cluster_configuration.yaml
vNetCIDR field description improved
https://github.com/deckhouse/deckhouse/issues/3944
```changes
section: cloud-providers-azure
type: chore
summary: Improve `vNetCIDR` field description.
```
> [cloud-providers-azure] vNetCIDR field description improved

- modules/300-prometheus/template_tests/alertmanager_ingress_test.go
- modules/300-prometheus/templates/alertmanager/internal/ingress.yaml
Fixed settings source for external auth
(Close https://github.com/deckhouse/deckhouse/issues/6058)
Alertmanager uses settings from prometheus.auth.externalAuthentication
```changes
section: 300-prometheus
type: fix
summary: Fix settings source for external auth.
```
> [prometheus] fix custom alertmanager external auth

- modules/402-ingress-nginx/images/controller-1-6/Dockerfile
- modules/402-ingress-nginx/images/controller-1-6/patches/README.md
- modules/402-ingress-nginx/images/controller-1-6/patches/endpointslice-missing-conditions.patch
Backport [fix](https://github.com/kubernetes/ingress-nginx/pull/9550) from ingress controller 1.7 
It fixes ingress controller panic [issue](https://github.com/kubernetes/ingress-nginx/pull/9550) when an endpointslice doesn't have valid conditions field.
Closes #5811
Ingress controller doesn't panic but rather skip invalid endpointslices.
```changes
type: fix
summary: Fix ingress controller panic when an endpointslice doesn't have .conditions field.
impact: All ingress controllers' pods will be recreated.
```
> [ingress-nginx] backport fix for endpointslices missing conditions

- modules/007-registrypackages/images/containerd/scripts/install
Fixed disabling the old containerd service in ubuntu 18.04.
<details>
```shell
root@node-f17788da-64c5f-fl257:~# systemctl status containerd.service 
● containerd.service - containerd container runtime
Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
Active: active (running) since Wed 2023-07-05 08:36:46 UTC; 3 months 7 days ago
Docs: https://containerd.io
Main PID: 1013752 (containerd)
Tasks: 235
CGroup: /system.slice/containerd.service
├─ 235402 /opt/deckhouse/bin/containerd-shim-runc-v2 -namespace k8s.io -id e2d69ba8974d6d92f0680ff46e99ee276c1952dd0cd003ff597422030be947b3 -address /run/containerd/containerd.sock
├─ 980040 /usr/bin/containerd-shim-runc-v2 -namespace k8s.io -id 5b49fbbf3c513d88c66a21557329fb82ea62fdd377fd251b7a45dede927a9b05 …
```
> [registrypackages] Fix disable old containerd for ubuntu 18.04

- ee/modules/650-runtime-audit-engine/templates/falco-rules.yaml
Add rules about pod start/stop.
```changes
type: chore
summary: add rules about pod start/stop
```
> [runtime-audit-engine] add rules about pod start/stop

- dhctl/pkg/infrastructure/cluster.go
- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/operations/converge/converger.go
- dhctl/pkg/operations/destroy/destroy.go
- dhctl/pkg/operations/phases/phases.go
Also refactored methods names of the PhasedExecutionContext.
> [dhctl] fix(dhctl-for-commander): fixed empty completedPhase param in the on-phase callback of phased-execution-context

- candi/openapi/cluster_configuration.yaml
Allow underscore in httpProxy and httpsProxy settings
If a user uses underscore to authenticate with a proxy, for example http://user_proxy:password@proxy:3128, then he receives a validation error
User can use username with underscore in httpProxy
> [candi] Allow underscore in httpProxy and httpsProxy

- modules/101-cert-manager/images/cert-manager-acme-solver/werf.inc.yaml
- modules/101-cert-manager/images/cert-manager-cainjector/werf.inc.yaml
- modules/101-cert-manager/images/cert-manager-controller/werf.inc.yaml
- modules/101-cert-manager/images/cert-manager-webhook/werf.inc.yaml
Switch cert-manager to use distroless image.
Unification of the approach to the development of module images
```changes
type: feature
summary: Switch cert-manager to use distroless image.
```
> [cert-manager] switch to distroless

- modules/041-linstor/images/linstor-server/patches/fix-symlinks.patch
Fix another set of issues with symlinks for devices. Related to https://github.com/deckhouse/deckhouse/pull/6026
Upstream PR https://github.com/LINBIT/linstor-server/pull/370
This PR builds upon the previous changes made in https://github.com/deckhouse/deckhouse/pull/6026 and addresses another set of issues related to symlinks for LVM devices. These issues are often associated with udev and can result in the disappearance of symlinks on a functioning system. These problems tend to occur during device resizing and deactivation, leading to LINSTOR exceptions when attempting to access the DRBD super-block of the volume or retrieve the size of the volume using `blockdev --getsize64`.
Our previous fix in https://github.com/deckhouse/deckhouse/pull/6026 partially addressed the problem, but it …
> [linstor] Improved symlink handling for devices.

- candi/bashible/bootstrap.sh.tpl
- candi/cloud-providers/yandex/bashible/bundles/ubuntu-lts/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/openstack/bashible/bundles/ubuntu-lts/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/vsphere/bashible/bundles/astra/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/vsphere/bashible/bundles/debian/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/vsphere/bashible/bundles/ubuntu-lts/bootstrap-networks.sh.tpl
- modules/040-node-manager/templates/node-group/_bootstrap.tpl
- modules/040-node-manager/templates/node-group/_cloud_init_cloud_config.tpl
- modules/040-node-manager/templates/node-group/_static_or_hybrid_script.tpl
- testing/cloud_layouts/vSphere/Standard/resources.yaml
Fix working of bootstrap cloud-networks setup scripts after #4907.
Changed vsphere cloud test to test two-interface nodes and cloud-network bootstrap scripts.
Cloud-networks setup scripts should run before we try to fetch second-phase bootstrap scripts from bashible apiserver. If we cannot run cloud network setup scripts at the first phase, we cannot give access to apiserver in the case of two or more interfaces on the node (cloud-init scripts setup only first interface by default and if first interface is external network we need to configure internal network interface by himself).
```changes
section: candi
type: fix
summary: fix working of bootstrap cloud-networks setup scripts
```
> [candi] fix working of bootstrap cloud-networks setup scripts

- dhctl/pkg/kubernetes/actions/deckhouse/install.go
- dhctl/pkg/kubernetes/actions/deckhouse/install_test.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- modules/002-deckhouse/hooks/change_host_ip.go
Secret with cluster uuid was not created.
Cluster uuid is required now.
And remove deprecated banner.
AWS cluster did not bootstrap
```changes
section: dhctl
type: fix
summary: FIX AWS install
```
> [dhctl] FIX AWS install

- ee/candi/bashible/bundles/redos/all/003_install_mandatory_packages.sh.tpl
- ee/candi/bashible/bundles/redos/bootstrap.sh.tpl
Revert curl version pinning for Red OS.
If we pin some version, we are at risk that this version is not available in package registry.
```changes
section: candi
type: fix
summary: Revert curl version pinning for Red OS
```
> [candi] Revert curl version pinning for Red OS
