deckhouse/deckhouse

candi/bashible/bundles/centos-7/all/000_add_yum_proxy_conf.sh.tpl
candi/bashible/bundles/ubuntu-lts/all/000_add_apt_proxy_conf.sh.tpl

specification: https://github.com/deckhouse/deckhouse/blob/main/candi/bashible/openapi.yaml#L28

[candi] Fix templating of proxy uri

---

.github/workflow_templates/on-pull-request-labeled.yml

```changes
module: <kebab-case>
type: fix | feature
description: <what effectively changes>
note: <what to expect>
```

CI for external PRs 

---

.github/actionlint.yaml
.github/render-workflows.sh

Add actionlint to render-workflows.sh
actionlint is a thorough linter for Github actions workflows.

[github] use actionlint if available

---

docs/site/_includes/getting_started/openstack/partials/config.yml.simple_with_internal_network.ee.inc
docs/site/_includes/getting_started/openstack/partials/config.yml.standard.ee.inc
docs/site/_includes/getting_started/openstack/partials/config.yml.standardwithnorouter.ee.inc

Update Deckhouse configuration for OpenStack.
Fix placeholder names and clarify some comments.
The OpenStack configuration is confusing, I spend a hour trying to use provided defaults.
This PR fixes placeholder names and adds additional comments.
```changes
module: docs
type: fix
description: "Fix OpenStack config"
note: |
Update Deckhouse configuration for OpenStack.
Fix placeholder names and adds additional comments.
```

[getting-started] Update config.yml for OpenStack

---

modules/402-ingress-nginx/docs/USAGE.md
modules/402-ingress-nginx/docs/USAGE_RU.md

[ingress-nginx::docs] Updated examples of creating loadbalancer in aws

[ingress-nginx] Update examples of creating loadbalancer in aws

---

modules/301-prometheus-metrics-adapter/docs/USAGE.md
modules/301-prometheus-metrics-adapter/docs/USAGE_RU.md

Scale up and down algorithm clarifications in USAGE.md. How to handle metrics fluctuation.

[prometheus-metrics-adapted] HPA scale algorhythm clarification

---

docs/site/LOCAL_DEV.md
docs/site/werf.yaml

Use images specified in environment variables when building site. There are special variables in a GitHub workflow, we can use.

[site] Use images specified in environment variables

---

docs/site/pages/index.html
docs/site/pages/index_ru.html

Minor changes. Added target blank to certificate link attribute.

[Site] Add `target blank` to certificate link attr

---

docs/site/_includes/getting_started/global/partials/INSTALL_OTHER.md
docs/site/_includes/getting_started/global/partials/INSTALL_OTHER_RU.md

Added `--pull=always` option to docker run command, to avoid running the installer of the old version.

[site][getting-started] Minor fixes

---

docs/documentation/_plugins/openapi.rb
docs/site/css/components/_resources.scss
docs/site/css/components/common/_mixins.scss
docs/site/css/components/common/_variables.scss
docs/site/css/site.scss

[site] Improve resource render. Update styles.

---

modules/300-prometheus/templates/prometheus/rbac-to-us.yaml
modules/300-prometheus/templates/trickster/rbac-to-us.yaml
modules/500-upmeter/images/upmeter/cmd/upmeter/main.go
modules/500-upmeter/images/upmeter/pkg/probe/checker/d8_clusterconfiguration.go
modules/500-upmeter/images/upmeter/pkg/probe/checker/http.go
modules/500-upmeter/templates/upmeter-agent/daemonset.yaml
modules/500-upmeter/templates/upmeter-agent/rbac-for-us.yaml
modules/500-upmeter/templates/upmeter/statefulset.yaml

Fixes all-mighty access rights 
Fixes #169
```changes
module: upmeter
type: fix
description: Assign limited access rights to agent serviceaccount
```

Limit agent serviceaccount to access only required resources

---

modules/140-user-authz/docs/FAQ_RU.md
modules/460-log-shipper/crds/cluster-log-destination.yaml
modules/460-log-shipper/crds/cluster-logging-config.yaml
modules/460-log-shipper/crds/doc-ru-cluster-log-destination.yaml
modules/460-log-shipper/crds/doc-ru-cluster-logging-config.yaml

Update the log-shipper modules' CRDs, correct misspellings.

[docs][log-shipper] Updates

---

docs/documentation/_data/i18n.yml
docs/site/css/components/_resources.scss

Fix styles. Remove dot after "required" value.
Ref: https://github.com/deckhouse/deckhouse/pull/371

[site] Resource render updates

---

docs/documentation/_layouts/default.html

[site] Fix resource render

---

global-hooks/discovery/deckhouse_registry.go
global-hooks/discovery/deckhouse_registry_test.go

Parse Deckhouse image the same way that containerd does
Closes https://github.com/deckhouse/deckhouse/issues/418
```changes
module: global
type: fix
description: Fix parsing deckhouse images repo if there is the sha256 sum in the image name
```

[global] Fix deckhouse image repo parsing

---

ee/fe/modules/340-extended-monitoring/docs/CONFIGURATION.md
ee/fe/modules/340-extended-monitoring/docs/CONFIGURATION_RU.md
ee/fe/modules/340-extended-monitoring/docs/README.md
ee/fe/modules/340-extended-monitoring/docs/README_RU.md

[extended-monitoring][docs] Minor updates

---

docs/site/css/components/_clients.scss

Scales client logo in client stories if the width is not enough

[site] Fix title in clients stories

---

modules/040-control-plane-manager/docs/FAQ.md
modules/040-control-plane-manager/docs/FAQ_RU.md

Added instruction to control-plane-manager FAQ on how to add master nodes in a cloud cluster
Ref: #333
```changes
type: fix
```

[docs][control-plane-manager] Add instruction on how to add master nodes in a cloud cluster

---

candi/version_map.yml

Update Kubernetes patch versions.
We want to keep Kubernetes up to date.
```changes
module: global
type: feature
description: |
Update Kubernetes patch versions.
```

[global] update kubernetes patch versions

---

ee/modules/110-istio/openapi/config-values.yaml
ee/modules/110-istio/openapi/doc-ru-config-values.yaml

`globalVersion` option clarification in documentation.
```changes
module: istio
type: fix
description: `globalVersion` option clarification in documentation.
```

[istio][doc] globalVersion clarification

---

docs/documentation/_plugins/openapi.rb

Don't render OpenAPI schema if it has no fields.

[site] Update resource generator

---

docs/site/.helm/templates/20-ingress.yaml
docs/site/.helm/templates/_helpers.tpl
docs/site/.helm/values.yaml
docs/site/_includes/channel-menu.html
docs/site/werf.yaml

- Bump web-router to v1.0.8 (fix menu of versions)
- Use OIDC provider for the test environment

[site] Fix menu of versions

---

candi/bashible/common-steps/all/001_disable_ntp_on_node.sh.tpl

[bashible] disable_ntp step refactoring

---

modules/020-deckhouse/docs/internal/IMAGE_COPIER.md
modules/020-deckhouse/images/images-copier/generate-copier-secret.sh

Fix images copier docs.
Add commands for patch deckhouse-registry secret and deployment
`How it works` section is confuse

[deckhouse][docs] Fix images copier docs

---

go.mod
go.sum

New commands from https://github.com/flant/addon-operator/pull/288 and https://github.com/flant/shell-operator/pull/345:
- queue main
- global snapshots
- module snapshots [module]
Snapshots are useful for diagnostics.

[deckhouse-controller] add more debug commands

---

modules/040-node-manager/hooks/discover_standby_ng.go
modules/040-node-manager/hooks/discover_standby_ng_test.go

When calculating maximum instanses for particular NodeGroup without zones defined — use global zones count from CloudProvider configuration.
There is a bug on calculation of standby instances desired amount. If NodeGroup has no zones defined, it's treated that it has only one zone.
```changes
type: fix
description: |
When calculating maximum instanses for particular NodeGroup without zones defined — use global zones count from CloudProvider configuration.
```

[node-manager] consider globally defined zones on standby calculations

---

modules/470-chrony/templates/bashible-step.yaml

Bashible step name fix.
```changes
module: chrony
type: fix
description: bashible step name fix
```

[chrony] bashible step name fix

---

modules/150-user-authn/openapi/values.yaml

Fix values scheme.
```changes
type: fix
description: "Fix values scheme."
note:
```

[user-authn] fix values scheme

---

docs/documentation/_plugins/openapi.rb
modules/460-log-shipper/crds/cluster-logging-config.yaml
modules/460-log-shipper/crds/pod-logging-config.yaml

Fix examples in ClusterLoggingConfig and PodLoggingConfig log-shipper CR.
Fix CR generator.
```changes
type: fix
description: Fix examples in `ClusterLoggingConfig` and `PodLoggingConfig` CR. Fix CR generator.
```

[docs][log-shipper] Fix CR example. Fix CR generator

---

docs/documentation/pages/DECKHOUSE_CONFIGURE.md
docs/documentation/pages/DECKHOUSE_CONFIGURE_RU.md

The "How to configure" article reviewing and fixing.
```changes
type: fix
description: "Review and fix the 'How to configure' article."
```

[docs] Update 'How to configure' article

---

candi/cloud-providers/azure/docs/ENVIRONMENT.md
candi/cloud-providers/azure/docs/ENVIRONMENT_RU.md
candi/cloud-providers/azure/docs/LAYOUTS.md
candi/cloud-providers/azure/docs/LAYOUTS_RU.md
candi/cloud-providers/azure/openapi/cluster_configuration.yaml
candi/cloud-providers/azure/openapi/doc-ru-cluster_configuration.yaml

Microsoft Azure documentation fixes and improvements.
```changes
module: cloud-provider-aws
type: fix
description: Documentation fixes.
```

[azure] docs fixes and improvements

---

candi/bashible/common-steps/node-group/052_configure_and_start_kubernetes_api_proxy.sh.tpl

Fix build of nginx package for Ubuntu 16.
Fix #719
```changes
module: registry-packages
type: fix
description: "Fix build of nginx package for Ubuntu 16 (Fix #719)"
```

[registry-packages] Fix build of nginx package for Ubuntu 16

---

candi/bashible/bundles/ubuntu-lts/node-group/051_install_kubernetes_api_proxy.sh.tpl

Fix kubeernetes-api-proxy nginx version for ubuntu 16.

[bashible] fix nginx version for ubuntu 16

---

docs/documentation/_data/supported_versions.yml
docs/documentation/_includes/SUPPORTED_VERSIONS.md

The "Supported Kubernetes and OS versions" article reviewing and fixing.
```changes
module: docs
type: fix
description: "Review and fix the 'Supported Kubernetes and OS versions' article."
```

[docs] Update 'Supported Kubernetes and OS versions' article

---

docs/documentation/_plugins/openapi.rb

Fix OpenAPI generator on the site.

[docs] Fix OpenAPI generator

---

docs/documentation/pages/RELEASES.md

Minor fix «Release channels» page

[docs] Minor fix «Release channels» page

---

.github/scripts/js/ci.js

Make variable bindling local
Reduce bug risk due to interference with globals in github actions
```changes
module: ci
type: fix
description: Make CI code little more accurate
```

CI: fix JS binding

---

docs/documentation/pages/DECKHOUSE-FAQ.md
docs/documentation/pages/DECKHOUSE-FAQ_RU.md

The "FAQ" article reviewing and fixing.
```changes
module: docs
type: fix
description: "Review and fix Deckhouse FAQ."
```

[docs] Fix Deckhouse FAQ

---

.github/actions/milestone-changelog/action.yml

Changelog: compact JSON with jq
Fix failing workflows

Changelog: fix JQ JSON parsing

---

.github/actions/milestone-changelog/action.yml

Fix changelog action by fixing bah quoting
Fixes changelog assembling

Changelog: fix JQ JSON quoting

---

docs/documentation/pages/REVISION_COMPARISON.md
docs/documentation/pages/REVISION_COMPARISON_RU.md

The "Deckhouse Platform editions comparison" article reviewing and fixing.
```changes
type: fix
description: "Review the 'Deckhouse Platform editions comparison' article."

[docs] Fix the «Deckhouse Platform editions comparison» article

---

docs/site/css/components/_product-intro.scss
docs/site/pages/index.html
docs/site/pages/index_ru.html

Fix CNCF certificate rendering on the site when viewing on mobile devices

[docs] Fix CNCF certificate rendering on mobile devices

---

docs/documentation/_layouts/default.html

[docs] Minor fixes

---

docs/documentation/.helm/templates/20-ingress.yaml
docs/site/.helm/templates/20-ingress.yaml

Update Ingress API version on the site

[docs] Update ingress API version on the site

---

modules/020-deckhouse/crds/deckhouse-release.yaml
modules/020-deckhouse/crds/doc-ru-deckhouse-release.yaml

The "The deckhouse module: Custom Resource" article reviewing and fixing.
```changes
module: docs
type: fix
description: "Review and fix the 'The deckhouse module: Custom Resource' article."
```

Fix article text in «The deckhouse module: Custom Resource» page

---

modules/402-ingress-nginx/monitoring/grafana-dashboards/kubernetes-cluster/controller-detail.json

Rude bug.
```changes
type: fix
description: Fix handled request query on a dashboard.
```

[ingress-nginx] Fix handled requests panel query

---

candi/cloud-providers/aws/docs/LAYOUTS.md
candi/cloud-providers/aws/docs/LAYOUTS_RU.md

The "Cloud provider — AWS: Layouts" article reviewing and fixing.
```changes
module: docs
type: fix
description: "Review and fix the 'Cloud provider — AWS: Layouts' article."
```

[docs] Fix article text in «Cloud provider — AWS: Layouts» page

---

docs/site/_includes/getting_started/existing/STEP_FINISH.md
docs/site/_includes/getting_started/existing/STEP_FINISH_RU.md
modules/301-prometheus-metrics-adapter/docs/USAGE.md
modules/301-prometheus-metrics-adapter/docs/USAGE_RU.md

[docs] Update prometheus-metrics-adapter the usage page and minor getting started changes

[docs] Update prometheus-metrics-adapter the usage page and minor getting started changes

---

.github/actions/milestone-changelog/action.yml

Validate changelog section
Avoid typos and reduce mis-using
```changes
section: ci
type: feature
summary: Added validation of changelogs sections
```

Changelog: validate sections

---

modules/810-deckhouse-web/openapi/config-values.yaml
modules/810-deckhouse-web/openapi/doc-ru-config-values.yaml

The "The deckhouse-web module: configuration" article reviewing and fixing.
```changes
module: docs
type: fix
description: "Review and fix the 'The deckhouse-web module: configuration' article."
```

[docs] Fix article text in «The deckhouse-web module: configuration» page

---

modules/810-deckhouse-web/docs/README.md
modules/810-deckhouse-web/docs/README_RU.md

The "The deckhouse-web module" article reviewing and fixing.
```changes
module: docs
type: fix
description: "Review and fix the 'The deckhouse-web module' article."

[docs] Fix article text in «The deckhouse-web module» page

---

docs/documentation/pages/internal/DEVELOPMENT.md
docs/site/LOCAL_DEV.md

Update information about the release process.

[docs] Update the release process

---

modules/810-deckhouse-web/docs/USAGE.md
modules/810-deckhouse-web/docs/USAGE_RU.md

The "The deckhouse-web module: usage" article reviewing and fixing.
```changes
module: docs
type: fix
description: "Review and fix the 'The deckhouse-web module: usage' article."
```

[docs] Fix article text in «The deckhouse-web module: usage» page

---

candi/cloud-providers/aws/openapi/doc-ru-instance_class.yaml

The "Cloud provider — AWS: Custom Resources" article reviewing and fixing.
```changes
module: docs
type: fix
description: "Review and fix the 'Cloud provider — AWS: Custom Resources' article."
```

[docs] Fix article text in «Cloud provider — AWS: Custom Resources» page

---

modules/030-cloud-provider-gcp/docs/README_RU.md

The "Cloud provider — GCP" article reviewing and fixing.
```changes
section: docs
type: fix
summary: "Review and fix the 'Cloud provider — GCP' article."
```

[docs] Fix article text in «Cloud provider — GCP» page

---

modules/460-log-shipper/crds/cluster-log-destination.yaml
modules/460-log-shipper/crds/doc-ru-cluster-log-destination.yaml

Fix description in the ClusterLogDestination CRD 
```changes
type: fix
summary: Fix description in the ClusterLogDestination CRD 
```

[docs][log-shipper] Fix CRD ClusterLogDestination description

---

modules/020-deckhouse/docs/README.md
modules/140-user-authz/crds/crd.yaml
modules/140-user-authz/crds/doc-ru-crd.yaml
modules/150-user-authn/docs/README.md
modules/150-user-authn/docs/USAGE.md
modules/150-user-authn/docs/USAGE_RU.md

[docs][user-authz] Minor documentation updates

---

candi/cloud-providers/gcp/docs/LAYOUTS.md
candi/cloud-providers/gcp/docs/LAYOUTS_RU.md

The "Cloud provider — GCP: Layouts" article reviewing and fixing.
```changes
section: docs
type: fix
description: "Review and fix the 'Cloud provider — GCP: Layouts' article."

[docs] Fix article text in «Cloud provider — GCP: Layouts» page

---

modules/040-node-manager/docs/FAQ.md
modules/040-node-manager/docs/FAQ_RU.md

[docs] Minor fix

---

modules/030-cloud-provider-gcp/docs/FAQ_RU.md

The "Сloud provider — GCP: FAQ" article reviewing and fixing.
```changes
module: docs
type: fix
description: "Review and fix the 'Сloud provider — GCP: FAQ' article."
```

Fix article text in «Сloud provider — GCP: FAQ» page

---

modules/400-descheduler/docs/README.md
modules/400-descheduler/docs/README_RU.md

Update descheduler module documentation.
```changes
section: docs
type: fix
summary: Update descheduler module documentation.
```

[docs][descheduler] Update documentation

---

candi/cloud-providers/azure/docs/ENVIRONMENT.md
candi/cloud-providers/azure/docs/ENVIRONMENT_RU.md
candi/cloud-providers/azure/docs/LAYOUTS.md
candi/cloud-providers/azure/docs/LAYOUTS_RU.md
candi/cloud-providers/azure/openapi/cluster_configuration.yaml
candi/cloud-providers/azure/openapi/doc-ru-cluster_configuration.yaml
candi/cloud-providers/azure/openapi/doc-ru-instance_class.yaml
candi/cloud-providers/azure/openapi/instance_class.yaml
modules/030-cloud-provider-azure/docs/CONFIGURATION.md
modules/030-cloud-provider-azure/docs/CONFIGURATION_RU.md
modules/030-cloud-provider-azure/docs/README_RU.md
modules/030-cloud-provider-azure/docs/USAGE.md
modules/030-cloud-provider-azure/docs/USAGE_RU.md

The "Microsoft Azure" section reviewing and fixing.
```changes
section: docs
type: fix
summary: "Microsoft Azure cloud provider documentation updates."
```

[docs] Fix Microsoft Azure cloud provider documentattion

---

candi/openapi/node_group.yaml
modules/010-user-authn-crd/crds/dex-authenticator.yaml
modules/040-node-manager/crds/nodeuser.yaml
modules/140-user-authz/crds/crd.yaml

OpenAPI specifications minor fixes
```changes
section: docs
type: fix
summary: Fix examples in some OpenAPI specifications.
```

[doc] Fix OpenAPI specifications

---

ee/modules/600-flant-integration/hooks/migrate_cluster_kubernetes_version.go
ee/modules/600-flant-integration/hooks/migrate_cluster_kubernetes_version_test.go

… migration
Validate kubernetes version migration is one-time migration
Adds special configmap to ensure we do kubernetes version migration from 1.19 to `Automatic` only one time.
```changes
section: flant-pricing
type: fix
summary: Validate kubernetes version migration is one-time migration
```

[flant-integration] validate kubernetes version migration is one-time migration

---

.github/workflows/changelog-by-milestone.yml

Detect pull request in changelog workflow.
Changelog workflow fails on milestoned issues.
```changes
section: ci
type: fix
summary: Detect pull requests in changelog milestones.
```

[ci] fix: changelog fail on new issue

---

werf.yaml

[ci] Fix build of release-channel-version image

---

.github/actions/milestone-changelog/action.yml

Fix quoting backticks in changelog files
Fix quoting backticks in changelog files
```changes
section: ci
type: fix 
summary: Fix quoting backticks in changelog files
```

[Changelog] fix quoting

---

docs/documentation/_includes/SUPPORTED_VERSIONS.md

Updated the  the Supported OS versions list format.
```changes
section: docs
type: fix
summary: Updated the Supported OS versions list format.
```

[docs] Update the Supported OS versions list format

---

.gitignore
candi/cloud-providers/azure/docs/LAYOUTS.md
candi/cloud-providers/azure/docs/LAYOUTS_RU.md
candi/cloud-providers/gcp/docs/LAYOUTS.md
candi/cloud-providers/gcp/docs/LAYOUTS_RU.md
ee/candi/cloud-providers/openstack/docs/LAYOUTS.md
ee/candi/cloud-providers/openstack/docs/LAYOUTS_RU.md

Fixing of the "Cloud Provider" pages comments in examples.
```changes
section: docs
type: fix
summary: "Minor fixes"
```

[docs] Comments of examples fix in Cloud Provider section

---

docs/site/pages/managed_ru.html

Updated prices for managed k8s

[docs] updated prices for managed k8s

---

candi/bashible/common-steps/node-group/090_node_users.sh.tpl

Fix update password hash for node user.
If hash exists for another user, we does not update hash 
```changes
section: candi
type: fix
summary: Fix update password hash for node user.
```

[candi] Fix update password hash for node user

---

docs/site/_data/footer.yaml
docs/site/_data/topnav.yml

Updated header & footer navigation
Better navigation makes everyone happy, right?

[docs] Update header and footer navigation on the site

---

.github/pull_request_template.md

```changes
section: ci
type: chore
summary: Update PR template  for chore change type and better sections discovery
```

[DX] Update PR template for chore change type and better sections discovery

---

candi/version_map.yml

New kubernetes patchversions
```changes
section: candi
type: feature
summary: New kubernetes patchversions.
```

[candi] new kubernetes patchversions

---

modules/031-linstor/docs/FAQ.md
modules/031-linstor/docs/FAQ_RU.md

This PR updates LINSTOR documentation to describe some frequent errors.
Better UX
```changes
type: chore
summary: document FailedMount errors
```

[linstor] document FailedMount errors

---

modules/810-deckhouse-web/images/web/werf.inc.yaml

Generate the cluster configuration in the in-cluster documentation.
```changes
section: docs
type: fix
summary: Generation of the cluster configuration in the in-cluster documentation.
```

[ci] Generate the cluster configuration in the in-cluster documentation

---

ee/fe/modules/500-openvpn/templates/openvpn/authenticator.yaml

Fixed DexAuthenticator applicationDomain.
This fixes a bug that makes it impossible to login to the web interface when the user-auth module is enabled
```changes
type: fix
summary: Fixed DexAuthenticator applicationDomain.
```

[openvpn] fix dex applicationDomain

---

ee/fe/modules/500-openvpn/openapi/config-values.yaml
ee/fe/modules/500-openvpn/openapi/doc-ru-config-values.yaml
ee/fe/modules/500-openvpn/openapi/values.yaml
ee/fe/modules/500-openvpn/template_tests/copy_custom_certificate_test.go
ee/fe/modules/500-openvpn/values.yaml
ee/fe/modules/500-openvpn/values_matrix_test.yaml

Fixed OpenAPI.
```changes
type: fix
summary: Fixed OpenAPI
```

[openvpn] fix openapi

---

docs/site/pages/enterprise_edition.html
docs/site/pages/enterprise_edition_ru.html

Added subscription plan title anchor for enterprise edition landing on the site

[docs] Add subscription plan title anchor for enterprise edition landing on the site

---

go_lib/hooks/storage_class_change/hook.go

Fixed a bug for the case when the storage class is set to "false"
Using false resulted in an error and didn't allow forcing emptyDir on modules.
```changes
type: fix
summary: Fixed a bug for the case when the storage class is set to "false"
```

[go_lib::storage_class_change] fix for storageClass=false

---

.github/CODEOWNERS

Add @zuzzas as a codeowner of the CCM.

add Andrey as an owner of CCM

---

modules/470-chrony/images/chrony/start.sh

Remove chronyd stale pid file on start.
If chronyd killed by probe, chronyd cannot restart due to stale pid file.
```changes
type: fix
summary:  Remove chronyd stale pid file on start
```

[chrony] remove chronyd stale pid file if chronyd crashes

---

docs/documentation/_data/sidebars/main.yml
modules/020-deckhouse/docs/FAQ.md
modules/020-deckhouse/docs/FAQ_RU.md

Add faq about kube-bench.
Users want to check if cluster setup follows best practices.
```changes
type: chore
summary: Add faq about kube-bench
```

[deckhouse] Add faq about kube-bench

---

ee/fe/modules/500-openvpn/openapi/config-values.yaml

Fixed spec to allow arbitrary annotations.
```changes
type: fix
summary: Fixed "loadBalancer" OpenAPI spec.
```

[openvpn] Fixed "loadBalancer" OpenAPI spec

---

ee/fe/modules/500-openvpn/openapi/config-values.yaml
ee/fe/modules/500-openvpn/openapi/doc-ru-config-values.yaml

Documentation and openAPI spec. minor changes.
```changes
type: fix
summary: Documentation and openAPI spec. minor changes.
```

[docs][openvpn] Documentation updates

---

docs/documentation/Makefile
docs/documentation/werf.yaml
docs/site/Makefile
docs/site/werf.yaml

Disable directory listing on the site.
Bump web-router to v1.0.10.

[docs] Disable directory listing on the site

---

docs/documentation/_data/sidebars/main.yml

Added link to CustomResources into the sidebar of the site.
```changes
type: fix
summary: Added link to CustomResources into the sidebar of the site.
```

[upmeter] Add link to CustomResources into the sidebar of the site

---

docs/site/.helm/templates/20-ingress.yaml

[docs] Ingress updates

---

modules/300-prometheus/hooks/prometheus_disk.go

Fixed PersistentVolumeClaim size calculation for local storage.
Incorrect calculation led to the need to perform manual actions when rolling out a release.
```changes
type: fix
summary: Fixed PersistentVolumeClaim size calculation for local storage.
```

[prometheus] fix calculating pvc size for local storage

---

docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
docs/site/_includes/getting_started/existing/STEP_FINALIZE.md
docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS.md
docs/site/_includes/getting_started/global/step_cluster_setup.html
docs/site/_includes/getting_started/vsphere/STEP_ENV.md

Fixed some misspellings.
```changes
section: docs
type: fix
summary: Fixed some misspellings.
```

[docs] Fix misspellings

---

candi/bashible/bashible.sh.tpl

Added filesystem sync on copy bashible-new.sh to bashible.sh
In centos releases with xfs file system, when node is cold-rebooted, bashible.sh truncated to zero size. This is xfs bug.
https://stackoverflow.com/questions/47077828/xfs-rhel7-3-cold-reboot-file-truncate
```changes
section: candi
type: fix
summary: added file sync on bashible.sh change
```

[candi] added file sync on bashible.sh change

---

ee/modules/600-flant-integration/docs/README.md

Translate 600-flant-integration readme.
This PR adds an EN readme file for the flant-integration module.

[docs] Translate the flant-integration module documentation

---

candi/cloud-providers/aws/openapi/cluster_configuration.yaml
ee/candi/cloud-providers/vsphere/openapi/cluster_configuration.yaml
ee/modules/030-cloud-provider-vsphere/openapi/values.yaml
modules/500-upmeter/crds/doc-ru-upmeterhookprobe.yaml
modules/500-upmeter/openapi/doc-ru-config-values.yaml

Fix OpenAPI specifications.
```changes
type: fix
summary: Fix OpenAPI specifications
---
type: fix
summary: Fix OpenAPI specifications
---
type: fix
summary: Fix OpenAPI specifications
```

Fix OpenAPI specifications

---

ee/fe/modules/500-openvpn/templates/openvpn/configmap.yaml

Fixed Values path in OpenVPN's CM.
Changed config values were not applied to OpenVPN's CM.
```changes
type: fix
summary: Fixed Values references in CM
```

[openvpn] Fix Values references in CM template

---

.github/ci_templates/helper_jobs.yml
.github/render-workflows.sh
.github/workflows/build-and-test_dev.yml
.github/workflows/on-pull-request-labeled.yml
.github/workflows/validation.yml

- Use 'FE' edition for push trigger
- Fix permissions of generated files in render script
It is useful to set push trigger to test some changes in build workflow.
```changes
section: ci
type: fix
summary: support push trigger, fix permissions in render script
```

[ci] fix: support push trigger for build-and-test_dev

---

helm_lib/templates/_csi_node.tpl
modules/099-ceph-csi/docs/USAGE.md
modules/099-ceph-csi/docs/USAGE_RU.md

Allow helm_lib_csi_node_manifests to be used for all cluster types for ceph-csi.
This is required to use ceph-csi in bare-metal clusters.
```changes
type: fix
summary: Allow helm_lib_csi_node_manifests to be used for all cluster types for ceph-csi.
```

[ceph-csi] allow helm_lib_csi_node_manifests to be used for all cluster types for ceph-csi

---

docs/site/css/components/_resources.scss
docs/site/css/docs.scss

[site] Fix offset for list

---

helm_lib/templates/_csi_controller.tpl

Update CSI controller without creating a new one.
Since controller is not a StatefulSet anymore, there can be unfortunate complications while trying to update it. Such as:
```
2022/04/27 12:39:33 failed to listen: listen tcp 192.168.176.29:12302: bind: address already in use
```
```changes
type: fix
summary: Update CSI controller without creating a new one.
```

[helm_lib] Properly update CSI controller Deployment

---

docs/site/pages/SECURITY.md
docs/site/pages/SECURITY_RU.md

[docs] Update security page

---

modules/340-monitoring-kubernetes/monitoring/prometheus-rules/coreos/cri-version.tpl

Fix alert UnsupportedContainerRuntimeVersion to support newest versions of containerd - 1.5.* and 1.6.* and docker 20.*.
Alert is fired after updating containerd and docker versions in use.
```changes
type: fix
summary: Fix alert UnsupportedContainerRuntimeVersion to support newest versions of containerd - 1.5.* and 1.6.* and docker 20.*.
```

[monitoring] UnsupportedContainerRuntimeVersion Docker 20.* Containerd 1.[5-6].*

---

modules/030-cloud-provider-azure/images/azuredisk-csi/Dockerfile

Update CSI to the latest version.
Fixes a problem with missing CSI GetVolumeStats calls, which result in missing PV metrics.
```changes
type: fix
summary: Updated CSI to v1.17.0. Fixes a problem with missing CSI GetVolumeStats calls, which result in missing PV metrics.
```

[cloud-provider-azure] Update CSI to v1.17.0

---

helm_lib/templates/_csi_node.tpl

Fixed nodeSelector for csi-node DaemonSet in helm_lib.
This is necessary for csi-node pods to run on all types of nodes.
```changes
type: fix
summary: Fixed nodeSelector for csi-node pods in helm_lib
```

[ceph-csi] Fix nodeSelector for csi-node pods in helm_lib

---

docs/site/pages/enterprise_edition.html

Added regulations link for EE on the site

[docs] Add EE regulations link

---

ee/modules/110-istio/docs/README.md

Update README.md to reflect changes in RU version
Adds up-to-date English Istio documentation.

[docs] Istio documentation refactoring

---

ee/fe/modules/500-openvpn/images/ovpn-admin/Dockerfile
ee/fe/modules/500-openvpn/openapi/config-values.yaml
ee/fe/modules/500-openvpn/openapi/doc-ru-config-values.yaml
ee/fe/modules/500-openvpn/templates/openvpn/configmap.yaml
ee/fe/modules/500-openvpn/templates/openvpn/service-external.yaml
ee/fe/modules/500-openvpn/templates/openvpn/statefullset.yaml

- Added support for UDP protocol.
- Added `tcpEnabled` and `udpEnabled` parameters to enable or disable the openvpn server with the corresponding protocol. It is not allowed to set both options to false at the same time.
- For openvpn server running on UDP protocol, added `udpTunnelNetwork` parameter to change tunnel network.
UDP allows us to get lower latency and higher speed through the VPN tunnel.
```changes
type: feature
summary: Added support for UDP protocol.
```

[openvpn] UDP

---

ee/fe/modules/340-extended-monitoring/images/extended-monitoring-exporter/src/extended-monitoring.py

Do not hit etcd on listing in extended-monitoring-exporter
It aimed to make continuous listing less painful for the Kubernetes control plane.
```changes
type: feature
summary: List objects from the kube-apiserver cache, avoid hitting etcd on each list. It should decrease control plane resource consumption.
```

[extended-monitoring] List kube-apiserver cached objects

---

.github/CODEOWNERS

Added codeowner for the documentation.
```changes
section: docs
type: feature
summary: Add codeowner for the documentation
```

[chore] Add codeowner for documentation

---

docs/site/_includes/getting_started/bm-private/partials/config.yml.default.ce.inc
docs/site/_includes/getting_started/global/partials/getting-started-setup.js.liquid
docs/site/_includes/getting_started/global/step_cluster_setup.html
docs/site/_includes/getting_started/global/step_cluster_setup_ru.html
docs/site/js/getting-started-private.js
docs/site/js/getting-started.js

Added the proxy parameter support to the getting started in a private environment.
```changes
section: docs
type: feature
summary: "Getting started in a private environment: the proxy parameter support."
```

[docs] Add the proxy parameter support to the getting started (private environment)

---

candi/cloud-providers/aws/layouts/with-nat/base-infrastructure/variables.tf
candi/cloud-providers/aws/layouts/with-nat/master-node/variables.tf

Fix errors in withNAT layout.
```changes
section: candi
type: fix
summary: Fix errors in withNAT layout
```

[cloud-provider-aws] fix withNAT layout

---

modules/010-priority-class/docs/CONFIGURATION.md
modules/010-priority-class/docs/CONFIGURATION_RU.md

Documentation fix.
```changes
section: priority-class
type: fix
impact: Documentation fix.
Impact_level: low
---
```

PriorityClass system-node-critical instead of node-cluster-critical

---

modules/007-registrypackages/images/kubeadm-centos/werf.inc.yaml
modules/007-registrypackages/images/kubeadm-debian/werf.inc.yaml
modules/007-registrypackages/images/kubeadm-ubuntu/werf.inc.yaml

Fix kubeadm registrypackages build
```changes
section: candi
type: fix
summary: fix kubeadm registrypackages build
```

[candi] fix kubeadm registrypackages build

---

.github/workflow_templates/schedule-cleanup.yml
.github/workflows/schedule-cleanup.yml

```changes
section: ci
type:  chore
summary: Enable cleanup for Deckhouse dev container registry
```

[ci] Disable WERF_DRY_RUN for cleanup jobs

---

modules/500-upmeter/images/smoke-mini/smoke-mini.go

Revert back smoke-mini handlers for e2e tests
We need e2e test to pass. Deleted handlers are involved in the tests.
```changes
type:  chore
summary: Revert the deletion of HTTP handlers for e2e tests
```

[upmeter] Revert the deletion of smoke-mini handlers for e2e tests

---

modules/030-cloud-provider-azure/templates/csi/storage-classes.yaml

Fix disk type parameter name.
In the latest (which is an all releases now) azuredisk-csi driver these fields are validated and no new PV can get provisioned due to incorrect value being present. It previously defaulted to `StandardSSD_LRS` and did not throw errors.
```changes
type: fix
summary: Fix parameter name `type` -> `skuName`
```

[cloud-provider-azure] type -> skuName

---

modules/402-ingress-nginx/images/protobuf-exporter/README.md

Updated README of the protobuf-exporter.
```changes
type: fix
summary: Updated README of the protobuf-exporter.
```

[ingress-nginx][docs] Update README of the protobuf-exporter

---

docs/site/css/docs.scss

Fixed styles of the ordered list on the site
```changes
section: docs
type: fix
summary: Fixed styles of the ordered list on the site
```

[site] Fix styles of the ordered list on the site

---

modules/101-cert-manager/images/cert-manager-acme-solver/werf.inc.yaml

Fix broken cert-manager-acme-solver image.
In  https://github.com/deckhouse/deckhouse/pull/1601 acme-solver was broken due to incorrect user in container.
```changes
type: fix
summary: fix broken cert-manager-acme-solver image
```

[cert-manager] fix broken cert-manager-acme-solver image

---

.github/ci_includes/terraform_versions.yml
.github/workflows/build-and-test_dev.yml
.github/workflows/build-and-test_release.yml
.github/workflows/deploy-web-stage.yml
.github/workflows/deploy-web-test.yml
.github/workflows/e2e-aws.yml
.github/workflows/e2e-azure.yml
.github/workflows/e2e-gcp.yml
.github/workflows/e2e-openstack.yml
.github/workflows/e2e-static.yml
.github/workflows/e2e-vsphere.yml
.github/workflows/e2e-yandex-cloud.yml
.github/workflows/schedule-cleanup.yml

Update terraform-provider-aws to version 4.16
Required to support new regions.
```changes
type: chore
summary: Update terraform-provider-aws to version 4.16
```

[cloud-provider-aws] update terraform-provider-aws

---

docs/documentation/pages/DECKHOUSE-FAQ.md
docs/documentation/pages/DECKHOUSE-FAQ_RU.md

Adds info about how to change the cluster configuration and Kubernetes version to the Deckhouse FAQ.
Closes: https://github.com/deckhouse/deckhouse/issues/246
```changes
section: docs
type: feature
summary: Add info about how to change the cluster configuration and Kubernetes version to the Deckhouse FAQ.
```

[docs] Update the Deckhouse FAQ

---

docs/documentation/pages/DECKHOUSE-FAQ.md
docs/documentation/pages/DECKHOUSE-FAQ_RU.md

[docs] Minor updates

---

docs/site/_includes/getting_started/aws/partials/resources.yml.ha.inc
docs/site/_includes/getting_started/aws/partials/resources.yml.minimal.inc
docs/site/_includes/getting_started/aws/partials/resources.yml.production.inc
docs/site/_includes/getting_started/azure/partials/resources.yml.ha.inc
docs/site/_includes/getting_started/azure/partials/resources.yml.minimal.inc
docs/site/_includes/getting_started/azure/partials/resources.yml.production.inc
docs/site/_includes/getting_started/gcp/partials/resources.yml.production.inc
docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS.md
docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS_RU.md
docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA.liquid
docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA_RU.liquid
docs/site/_includes/getting_started/openstack/partials/resources.yml.production.inc
docs/site/_includes/getting_started/vsphere/partials/config.yml.standard.ee.inc
docs/site/_includes/getting_started/vsphere/partials/resources.yml.ha.inc
docs/site/_includes/getting_started/vsphere/partials/resources.yml.production.inc

The getting started updates on the site.
```changes
section: docs
type: fix
summary: Getting started updates.
```

[docs] Getting started updates

---

docs/site/_includes/getting_started/vsphere/STEP_ENV.md
docs/site/_includes/getting_started/vsphere/STEP_ENV_RU.md
docs/site/_includes/getting_started/vsphere/partials/resources.yml.ha.inc

Fixed issues with descriptions in vSphere's getting started.
```changes
section: docs
type: fix
summary: Fixed issues with descriptions in vSphere's getting started
```

[docs] vSphere Getting Started improvements

---

modules/021-cni-cilium/openapi/config-values.yaml
modules/021-cni-cilium/openapi/doc-ru-config-values.yaml
modules/021-cni-cilium/template_tests/module_test.go
modules/021-cni-cilium/templates/agent/daemonset.yaml
modules/021-cni-cilium/templates/configmap.yaml
testing/matrix/linter/rules/resources/vpa.go

1. Added proper VPA configuration to cni-cilium module.
2. Added ability of use `vxlan` mode.
```changes
type: feature 
summary: clium improvements
```

[cilium] improvements

---

global-hooks/openapi/config-values.yaml
global-hooks/openapi/doc-ru-config-values.yaml

fix proxy doc
```changes
type: fix
summary: fix proxy parameter doc
```

[global] fix proxy doc

---

candi/cloud-providers/aws/terraform-modules/master-node/main.tf

Add `user_data_replace_on_change` to lifecycle ignore_changes list.
After #1656 terraform scheme was changed.
```
Terraform will perform the following actions:
│ │ 
│ │   # module.master-node.aws_instance.master will be updated in-place
│ │   ~ resource "aws_instance" "master" {
...
...
...
│ │         tenancy                              = "default"
│ │         user_data                            = "de654ea41c34ef1c62f4e"
│ │       + user_data_replace_on_change          = false
│ │         vpc_security_group_ids               = [
│ │             "sg-0123123123123",
│ │             "sg-0444444444444",
│ │             "sg-5555555555555",
│ │         ]
...
...
...
```
We added parameter to scheme to avoid manual converge of …

[cloud-provider-aws] fix terraform scheme

---

modules/007-registrypackages/images/conntrack-debian/werf.inc.yaml
modules/007-registrypackages/images/containerd-debian/werf.inc.yaml
modules/007-registrypackages/images/containerd-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/crictl/werf.inc.yaml
modules/007-registrypackages/images/d8-curl/werf.inc.yaml
modules/007-registrypackages/images/docker-centos/werf.inc.yaml
modules/007-registrypackages/images/docker-debian/werf.inc.yaml
modules/007-registrypackages/images/docker-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/inotify-tools-centos/werf.inc.yaml
modules/007-registrypackages/images/jq/werf.inc.yaml
modules/007-registrypackages/images/kubeadm-centos/werf.inc.yaml
modules/007-registrypackages/images/kubeadm-debian/werf.inc.yaml
modules/007-registrypackages/images/kubeadm-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/kubectl-centos/werf.inc.yaml
modules/007-registrypackages/images/kubectl-debian/werf.inc.yaml
modules/007-registrypackages/images/kubectl-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/kubelet-centos/werf.inc.yaml
modules/007-registrypackages/images/kubelet-debian/werf.inc.yaml
modules/007-registrypackages/images/kubelet-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/kubernetes-cni-centos/werf.inc.yaml
modules/007-registrypackages/images/kubernetes-cni-debian/werf.inc.yaml
modules/007-registrypackages/images/kubernetes-cni-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/virt-what-debian/werf.inc.yaml

Update curl options. Added `-f` flag to improve build process.
#1693 
```changes
section: candi
type: fix
summary: fix build of registry packages
```

[candi] fix build of registry packages

---

.github/actions/milestone-changelog/action.yml

Fix full link changelog placement

---

candi/version_map.yml

New kuberenetes patchversions.
```changes
section: candi
type: feature
summary: new kuberenetes patchversions
impact: control-plane-components should restart ↓
```

[candi] new kuberenetes patchversions

---

modules/040-node-manager/docs/internal/CLUSTER_AUTOSCALER.md

Minor updates of the CLUSTER_AUTOSCALER.md
```changes
section: docs
type: fix
summary: Minor updates of the node-manager/CLUSTER_AUTOSCALER.md .
```

[docs][node-manager] Minor updates of the CLUSTER_AUTOSCALER.md

---

modules/140-user-authz/docs/USAGE.md
modules/140-user-authz/docs/USAGE_RU.md

Documentation updates.
```changes
type: fix
summary: Documentation updates
```

[docs][user-authz] Documentation updates

---

docs/documentation/_includes/revision_comparison_detail_table.liquid
docs/site/_data/revision_comparison.yml

Minor site updates
```changes
section: docs
type: fix
summary: Minor site updates.
```

[docs] The site updates

---

candi/control-plane-kubeadm/config.yaml.tpl
modules/040-control-plane-manager/openapi/config-values.yaml
modules/040-control-plane-manager/openapi/doc-ru-config-values.yaml
modules/040-control-plane-manager/templates/daemonset.yaml

Added authentication-token-webhook-cache-ttl parameter to apiserver.
This parameter controls how long to cache authentication decisions and is used to reduce the load on the webhook at high request frequencies.
```changes
type: feature
summary: Added authentication-token-webhook-cache-ttl parameter to apiserver.
```

[control-plane-manager] added authentication-token-webhook-cache-ttl

---

.github/ci_templates/web.yml
.github/workflows/build-and-test_dev.yml
.github/workflows/build-and-test_release.yml
modules/010-vertical-pod-autoscaler-crd/crds/doc-ru-verticalpodautoscaler.yaml
modules/010-vertical-pod-autoscaler-crd/crds/verticalpodautoscaler.yaml
modules/101-cert-manager/docs/USAGE.md
modules/101-cert-manager/docs/USAGE_RU.md
modules/300-prometheus/docs/FAQ.md
modules/300-prometheus/docs/FAQ_RU.md
modules/302-vertical-pod-autoscaler/docs/README.md
modules/302-vertical-pod-autoscaler/docs/README_RU.md

Minor site fixes.
Fix links test in CI

Site minor fixes

---

modules/040-node-manager/docs/FAQ.md

[docs] Fix doc markup

---

README.md

```changes
section: docs
type: chore
summary: Add flow link
```

[chore] Add flow link

---

modules/007-registrypackages/images/conntrack-debian/werf.inc.yaml
modules/007-registrypackages/images/containerd-centos/werf.inc.yaml
modules/007-registrypackages/images/containerd-debian/werf.inc.yaml
modules/007-registrypackages/images/containerd-fe/werf.inc.yaml
modules/007-registrypackages/images/containerd-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/crictl/werf.inc.yaml
modules/007-registrypackages/images/d8-curl/werf.inc.yaml
modules/007-registrypackages/images/docker-centos/werf.inc.yaml
modules/007-registrypackages/images/docker-debian/werf.inc.yaml
modules/007-registrypackages/images/docker-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/inotify-tools-centos/werf.inc.yaml
modules/007-registrypackages/images/jq/werf.inc.yaml
modules/007-registrypackages/images/kubeadm-centos/werf.inc.yaml
modules/007-registrypackages/images/kubeadm-debian/werf.inc.yaml
modules/007-registrypackages/images/kubeadm-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/kubectl-centos/werf.inc.yaml
modules/007-registrypackages/images/kubectl-debian/werf.inc.yaml
modules/007-registrypackages/images/kubectl-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/kubelet-centos/werf.inc.yaml
modules/007-registrypackages/images/kubelet-debian/werf.inc.yaml
modules/007-registrypackages/images/kubelet-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/kubernetes-cni-centos/werf.inc.yaml
modules/007-registrypackages/images/kubernetes-cni-debian/werf.inc.yaml
modules/007-registrypackages/images/kubernetes-cni-ubuntu/werf.inc.yaml
modules/007-registrypackages/images/virt-what-debian/werf.inc.yaml

Added labels to registry package images.
We need additional labels on registry packages docker images to get additional info about distro, packages versions etc.
```changes
section: registry-packages
type: chore
summary: Added labels to registry package images
impact: some of the registry packages will be reinstalled
```

[registry-packages] Added labels to registry package images

---

candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl

Configured graceful node shutdown to 2 minutes by default. This value may be overriden in some cloud providers.
There doesn't seem to be any downsides.
```changes
section: candi
type: feature
summary: Configured graceful node shutdown to 2 minutes by default. This value may be overriden in some cloud providers.
```

[candi] Configure shutdownGracePeriod to 2m by default

---

modules/402-ingress-nginx/hooks/migrate_ingress_class.go

Fix pointer lib method
```changes
type: fix 
summary: Fix pointer
```

[ingress-nginx] fix pointer function call

---

.github/pull_request_template.md

Add a checkbox about unit tests and how one can check the changes in the PR template.
The updates will help not forget the need to check the code and write tests.
```changes
section: ci
type: feature
summary: Add a checkbox about unit tests and how one can check the changes.
```

[CI] Update the PR template

---

modules/020-deckhouse/monitoring/prometheus-rules/deckhouse.yaml

Change severity for alert rule
Alert is deferred and teams don't see it in time and then alert is closed natively
```changes
type: fix 
summary: Change DeckhouseUpdating Prometheus rule severity_level to avoid alert deferring
```

[deckhouse] change severity_level for DeckhouseUpdating rule

---

docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA.md
docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA_RU.md
tools/kind-d8.sh

Script for installing Deckhouse in kind on macOs or Debian based distros.
```changes
section: docs
type: feature
summary: Script for installing Deckhouse in kind on macOs or Debian based distros.
```

[docs] Script for installing Deckhouse in kind

---

docs/site/_includes/getting_started/global/partials/INSTALL_OTHER.liquid
docs/site/_includes/getting_started/global/partials/INSTALL_OTHER_RU.liquid

Remove `dont-use-public-control-plane-images` flag from getting started
Close #1548 
`dont-use-public-control-plane-images` must remove from getting started page for private envs.
```changes
section: docs
type: chore
summary: Remove dont-use-public-control-plane-images flag from getting started
```

[docs][getting-started] Remove dont-use-public-control-plane-images flag from getting started

---

modules/README.md

`modules/README.md` is among the most popular links to visit.
```changes
section: docs
type: chore
summary: Add README.md to the modules folder
```

[modules] Add README.md

---

modules/402-ingress-nginx/images/controller-0-49/Dockerfile

Upgrade 0.49.1 controller version to 0.49.3
In the 0.49.3 version lua-resty-balancer was upgraded and a couple of problems was fixed:
- should force convert weight to a number since it may cause dead loop
when weight is a string type "0".
- out-of-bounds memory writing may happen in chash_point_sort.
we have met this out-of-bounds problem before
```changes
type: fix
summary: Upgrade 0.49 ingress controller to fix out-of-bounds temporary error
impact: IngressNginxController of the version 0.49 will be restarted
```

[ingress-nginx] upgrade 0.49 controller

---

modules/470-chrony/docs/FAQ.md
modules/470-chrony/docs/FAQ_RU.md

fix doc in chrony module
```changes
type: fix
summary: doc fix
```

[chrony] fix doc

---

modules/150-user-authn/images/kubeconfig-generator/already_logged.patch

Fix an error for the previously added feature
https://github.com/deckhouse/deckhouse/pull/1827

[user-authn] Fix kubelogin tab

---

modules/030-cloud-provider-azure/docs/CONFIGURATION.md
modules/030-cloud-provider-azure/docs/CONFIGURATION_RU.md
modules/030-cloud-provider-azure/hooks/storage_classes
modules/030-cloud-provider-azure/hooks/storage_classes_test.go
modules/030-cloud-provider-azure/templates/csi/storage-classes.yaml

Provide StorageClasses for disks large than 4 TiB.
These SCs require cachingMode to be `None`.
```changes
type: feature
summary: Provide new default StorageClasses for disks large than 4 TiB.
```

[cloud-provider-azure] StorageClasses for disks > 4 TiB

---

modules/030-cloud-provider-azure/hooks/storage_classes_test.go

Fixed tests for a commit in main branch.
```changes
type: fix
summary: tests fix
```

[cloud-provider-azure] Fixed tests for a commit that wrongfully made its way directly into the main branch

---

docs/documentation/_data/i18n.yml
docs/documentation/_plugins/openapi.rb
docs/site/css/docs.scss

This reverts commit 41d94d93b7179aa0d8cbe900da395d381d5c1a45.
#1939

Revert "[docs] Highlight outdated fields (#1939)"

---

modules/300-prometheus/docs/internal/demo/README.md
modules/300-prometheus/docs/internal/demo/alertmanager.yaml
modules/300-prometheus/docs/internal/demo/clean_up.sh
modules/300-prometheus/docs/internal/demo/custom-prometheus-rule.yaml
modules/300-prometheus/docs/internal/demo/grafana-additional-datasource.yaml
modules/300-prometheus/docs/internal/demo/grafana-dashboard-definition.yaml
modules/300-prometheus/docs/internal/demo/prometheus-remote-write.yaml
modules/300-prometheus/docs/internal/demo/victoria-metrics.txt

Add an instruction on how to test the prometheus module customization features 
```changes
type: chore
summary: Add files for a Prometheus demo
```

[prometheus] Add files for a demo

---

.github/pull_request_template.md

Tests do pass, not passed by someone. I suggest reflecting this.
```changes
section: ci
type: chore
summary: Improved wording in PR template
```

[ci] Fix wording

---

modules/021-cni-cilium/docs/README.md
modules/021-cni-cilium/docs/README_RU.md

Document cilium kernel requirements.
We've tested and are actively using a specific set of Cilium features. Some of them are only tested and available on newer kernels.
```changes
type: chore
summary: Documented kernel requirements
```

[cni-cilium] Document kernel requirements

---

docs/site/_includes/request_access_form.html

License form updates.
```changes
section: docs
type: feature
summary: License form updates on the site.
```

[site] Fix license request language

---

candi/bashible/common-steps/node-group/050_configure_and_start_docker.sh.tpl

Fix of  https://github.com/deckhouse/deckhouse/pull/1975.
```
daemon_json="$(cat << "EOF"
{
"log-driver": "json-file",
"log-opts": {
"max-file": "5",
"max-size": "10m"
},
"max-concurrent-downloads": 3
}
EOF
)"
```
Wrong:
```
echo ${daemon_json}
{ "log-driver": "json-file", "log-opts": { "max-file": "5", "max-size": "10m" }, "max-concurrent-downloads": 3 }
```
Right:
```
echo "${daemon_json}"
{
"log-driver": "json-file",
"log-opts": {
"max-file": "5",
"max-size": "10m"
},
"max-concurrent-downloads": 3
}
```
```changes
section: candi
type: fix
summary: Fix docker config creation.
```

[candi] fix docker config creation

---

modules/300-prometheus/images/grafana/Dockerfile

Signed-off-by: Maksim Nabokikh <maksim.nabokikh@flant.com>
https://grafana.com/blog/2022/07/14/grafana-v9-0-3-8-5-9-8-4-10-and-8-3-10-released-with-high-severity-security-fix/
Grafana pod will be restarted.
```changes
type: fix
summary: Update Grafana to 8.5.9 to fix various CVE
```

[prometheus]  Grafana 8.5.9 to fix various CVE

---

modules/500-upmeter/templates/webui/authenticator.yaml

All ingres resources for the same domain must link the same certificate, otherwise ingress-nginx-controller can accidently respond to users with the fake certificate from time to time.
```changes
type: fix
summary: Fix certificate name for DexAuthenticator
```

[upmeter] Fix certificate name

---

modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/loop

Fix eviction inodes imagefs and node fs if containerd and kublet directory is symlink in `kubelet-eviction-thresholds-exporter`
If dir is symlink we read symlink target and return symlink target dir.
Incorrect value for `kubelet_eviction_imagefs_inodes` and `kubelet_eviction_nodefs_inodes` metrics.
Receiving false positive alerts.
```changes
type: fix
summary: Fix eviction inodes imagefs and node fs if containerd and kublet directory is symlink
```

[monitoring-kubernetes] Fix eviction inodes imagefs and node fs if containerd and kublet directory is symlink

---

modules/300-prometheus/images/grafana-dashboard-provisioner/hooks/dashboard_provisioner.sh

Write names of malformed dashboard definitions to logs
Makes it easier to localize errors
```changes
type: chore
summary: Added names of malformed dashboard definitions to the log of dashboard_provisioner container
```

[Grafana Dashboard Provisioner] Report names of malformed definitions

---

candi/cloud-providers/aws/terraform-modules/static-node/main.tf

In https://github.com/deckhouse/deckhouse/pull/1710 we change terraform scheme for master nodes, but forgot to change for static nodes.
Added lifecycle ignore_changes user_data_replace_on_change.
```changes
section: candi
type: fix
summary: fix aws terraform for static nodes
```

[candi] fix aws terraform for static nodes

---

modules/500-upmeter/templates/upmeter/statefulset.yaml

Add envs for proxy to upmeter statefulset.
For closed installations we should use proxy envs to send traffic from pod.
```changes
type: chore
summary: add envs for proxy to statefulset
impact: upmeter pods will be restarted
```

[upmeter] add envs for proxy to statefulset

---

candi/bashible/bundles/centos/all/034_install_kubelet_and_his_friends.sh.tpl
candi/bashible/bundles/debian/all/034_install_kubelet_and_his_friends.sh.tpl
candi/bashible/bundles/ubuntu-lts/all/034_install_kubelet_and_his_friends.sh.tpl
modules/007-registrypackages/images/kubelet-debian/werf.inc.yaml
modules/007-registrypackages/images/kubelet-ubuntu/werf.inc.yaml

[candi] Fix kubelet double restart

---

modules/301-prometheus-metrics-adapter/docs/CR.md
modules/301-prometheus-metrics-adapter/docs/CR_RU.md

Fix description of custom resources.
```changes
section: prometheus-metrics-adapter
type: fix
summary: Fix description of custom resources.
```

[docs][prometheus-metrics-adapter] Fix custom resource description

---

modules/150-user-authn/docs/internal/demo/README.md
modules/150-user-authn/docs/internal/demo/clean_up.sh
modules/150-user-authn/docs/internal/demo/dex-authenticator.yaml
modules/150-user-authn/docs/internal/demo/dex-provider.yaml
modules/150-user-authn/docs/internal/demo/dex-user.yaml
modules/150-user-authn/docs/internal/demo/echo-service.yaml
modules/150-user-authn/docs/internal/demo/ldap.yaml

Add an instruction on how to test the user-authn module customization features
```changes
type: chore
summary: Add files for user-authn demo
```

[user-authn] Add demo files

---

docs/site/_includes/getting_started/vsphere/partials/resources.yml.production.inc
docs/site/_includes/getting_started/yandex/partials/resources.yml.production.inc

Fix VSphere and Yandex.Cloud resources
VSphere production env does not bootstrap.  `ru-central1-c` zone is deprecated.  
Should render correct `resources.yml` file on Getting started page. 
```changes
section: docs
type: fix
summary: Fix VSphere and Yandex.Cloud resources
```

[docs][getting-started] Fix vsphere and yandex resources

---

docs/documentation/_includes/search.html
docs/documentation/js/search.js

Fix search result rendering.
```changes
section: docs
type: fix
summary: Fix search result rendering.
```

[docs] Fix search result rendering

---

modules/021-cni-cilium/oss.yaml
modules/500-cilium-hubble/oss.yaml

Fix description in used software related to the cilium.
```changes
type: fix
summary: Fix description in used software.
---
type: fix
summary: Fix description in used software.
```

[cilium] Update used software description

---

modules/040-control-plane-manager/monitoring/prometheus-rules/etcd-maintenance.yaml

Rename `D8EtcdCannotDecreaseQuotaBackendBytes` alerts and fix description.
Add table with values for set.
Add getting db size for all etcd instances command.
Alert name does not display content.
Alert content does not help get etcd current db size
N/A
```changes
type: chore
summary: Rename D8EtcdCannotDecreaseQuotaBackendBytes alerts and fix description
```

[control-plane-manager] Rename D8EtcdCannotDecreaseQuotaBackendBytes alerts and fix description

---

modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/node.yaml

Add alert NodeSUnreclaimBytesUsageHigh.
This alert helps to inform Deckhouse users about a [potential problem of kernel memory leakage](https://github.com/deckhouse/deckhouse/issues/2152) on a cluster node.
```changes
type: fix
summary: Add alert NodeSUnreclaimBytesUsageHigh
```

[monitoring-kubernetes] Add alert NodeSUnreclaimBytesUsageHigh

---

dhctl/pkg/kubernetes/actions/deckhouse/log.go

I forgot to add `InsecureSkipTLSVerifyBackend` to `logOptions` which rewrite initial log options.
Also, I added to debug-log all getting Deckhouse logs errors.
Close #2148 
In general, you should see `Request failed. Probably pod was restarted during installation` one ore two times only. 
```changes
section: dhctl
type: fix
summary: Fix output `Request failed. Probably pod was restarted during installation` multiple times during bootstrap cluster
```

[dhctl] Fix output `Request failed. Probably pod was restarted during installation` multiple times during bootstrap cluster

---

modules/values-managed.yaml

Removed "chrony" and "priority-class" from managed bundle.
These modules do not work properly in managed Kubernetes environments.
There are no errors with these modules on managed cluster install.
```changes
---
type: chore
summary: Removed from managed bundle
---
section: priority-class
type: chore
summary: Removed from managed bundle
```

Removed "chrony" and "priority-class" from managed bundle

---

docs/site/pages/license_request_expired.html
docs/site/pages/license_request_expired_ru.html

Added license expiration page on the site.

[site] Add license request expired page

---

docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS.md
docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS_RU.md

Update instruction for accessing vSphere cluster after bootstrap.
```changes
section: docs
type: fix
summary: Update instruction for accessing vSphere cluster.
```

[docs][getting started] Update instruction for accessing vSphere cluster

---

deckhouse-controller/files/vimrc.local

Fix vimrc.local
Fixes error
```
Error detected while processing /etc/vim/vimrc[18]../etc/vim/vimrc.local:
line    1:
E492: Not an editor command: [source $VIMRUNTIME/defaults.vim
line    2:
E481: No range allowed: +let g:skip_defaults_vim = 1
Press ENTER or type command to continue
```
```changes
type: chore
summary: Fix vimrc.local
```

[deckhouse-controller] Fix vimrc.local

---

modules/465-pod-reloader/images/pod-reloader/Dockerfile

Update pod reloader to the latest version.
Almost sure that this pr closes https://github.com/deckhouse/deckhouse/issues/1995.
```changes
section: pod-reloader
type: chore
summary: Update to v0.0.118
```

[pod-reloader] Update to v0.0.118

---

modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.19/README.md
modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.20/README.md
modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.21/README.md
modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.22/README.md
modules/030-cloud-provider-aws/images/cloud-controller-manager/patches/1.23/README.md

PR about `none` type LB was added to upstream. Add info about it to the patch README
Keep history about patch
```changes
type: chore
summary: Add PR to upstream into README
```

[cloud-provider-aws] Add upstream PR to README

---

.github/workflow_templates/on-pull-request-backport.yml
.github/workflows/on-pull-request-backport.yml

Improve CI
Avoid mistakes on comment format, support all types:
- /backport 1.34
- /backport v1.34
- /backport 1.34.14
- /backport v1.34.14
```changes
section: ci
type: fix
summary: Improve backport comment format
```

[c] improve backport on comment

---

ee/modules/600-flant-integration/images/madison-proxy/madison-proxy.go

Do not use HTTP2 for madison to avoid the following error:
```
http: proxy error: http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error
```
```changes
type: fix
summary: Disable HTTP2 for madison-proxy
```

[flant-integration] Disable HTTP2 for madison-proxy

---

modules/500-okmeter/openapi/config-values.yaml

Fix okmeter docs
Field required for image looks weird
```changes
type: fix
summary: fix docs for image field
```

[okmeter] docs: remove required field

---

ee/modules/600-flant-integration/images/madison-proxy/madison-proxy.go

(cherry picked from commit 57225e47b052808dd7d53ad4f9e0d99d1d33c3bd)
Ref: #2242
Do not use HTTP2 for madison to avoid the following error:
```
http: proxy error: http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error
```
Verify that there is no missing dms after release.
```changes
type: fix
summary: Disable HTTP2 for madison-proxy.
```

[flant-integration] Disable HTTP2 for madison-proxy (#2265)

---

docs/site/_includes/getting_started/global/partials/NOTICES_ENVIRONMENT.liquid

Minor fix of markup in the GCP getting started steps.
```changes
section: docs
type: fix
summary: Minor fix of markup in the GCP getting started steps.
```

[docs][getting-started] Minor fix

---

modules/040-node-manager/templates/cluster-autoscaler/deployment.yaml

Change Cluster autoscaler timeouts
2 minutes is too small timeout for unneeded node. If you are redeploying some chart, you can get out of this time limit and node will be removed. To avoid node flapping we can increase timeouts.
```changes
type: fix
summary: Change cluster autoscaler timeouts to avoid node flapping
```

[node-manager] Change Cluster autoscaler timeouts

---

modules/402-ingress-nginx/openapi/config-values.yaml
modules/402-ingress-nginx/webhooks/validating/ingressnginxcontroller

Change default ingress controller version
0.33 version is deprecated. We want to update to the actual 1.1. Everything is prepared for the upgrade and we can do it in background
```changes
type: feature
summary: Change default ingress nginx controller version to 1.1
impact: All ingress nginx controllers with not-specified version (0.33) will restart and upgrade to 1.1
```

[ingress-nginx] change default version

---

ee/modules/600-flant-integration/docs/README.md

Minor doc fixes in the flant-integration module.
```changes
type: fix
summary: Minor doc fixes in the flant-integration module.
```

[docs][flant-integration] Minor fixes

---

go_lib/module/module.go

Fixed priority of `https.mode` value getter.
It prioritized global https.mode. Which is obviously wrong,
Module's `https` values are prioritized before global ones.
```changes
type: fix
summary: Fixed copy_custom_certificate value priority
```

[go_lib] Fixed copy_custom_certificate value priority

---

modules/402-ingress-nginx/images/controller-0-33/rootfs/etc/nginx/lua/pbmetrics.lua
modules/402-ingress-nginx/images/controller-0-46/rootfs/etc/nginx/lua/pbmetrics.lua
modules/402-ingress-nginx/images/controller-0-48/rootfs/etc/nginx/lua/pbmetrics.lua
modules/402-ingress-nginx/images/controller-0-49/rootfs/etc/nginx/lua/pbmetrics.lua
modules/402-ingress-nginx/images/controller-1-1/rootfs/etc/nginx/lua/pbmetrics.lua

Fix lua script
Missed annotations arguments in 1 function, it leads to an error
```changes
type: fix 
summary: Fix pbmetrics collector
impact: Ingress nginx controller will restart
```

[ingress-nginx] fix lua pbmetrics 

---

helm_lib/templates/_module_image.tpl
modules/021-kube-proxy/templates/daemonset.yaml

fix error in daemonset image tag.
```changes
type: fix
summary:  fix daemonset image tag
```

[kube-proxy] fix daemonset image tag

---

modules/340-monitoring-kubernetes/monitoring/prometheus-rules/generic/kubelet.tpl

Fix K8SKubeletTooManyPods alert
```changes
type: fix
summary: fix K8SKubeletTooManyPods alert
```

[prometheus] fix K8SKubeletTooManyPods alert

---

modules/020-deckhouse/openapi/config-values.yaml
modules/020-deckhouse/openapi/doc-ru-config-values.yaml

Fix typos and formatting
```changes
section: docs
type: fix
summary: Fix typos and formatting
```

[docs][deckhouse] Fix typos and formatting

---

docs/site/_data/footer.yaml
docs/site/_data/topnav.yml
docs/site/_includes/header.html

[site] Added new items in top and footer nav menu

---

go_lib/module/module.go

Fixed GetValuesFirstDefined value priority
Global values are erroneously prioritized in some hooks.
Module values are properly prioritized in all hooks.
```changes
type: fix
summary: Fixed `GetValuesFirstDefined` value priority.
```

[go_lib] Fixed GetValuesFirstDefined value priority

---

modules/150-user-authn/docs/USAGE.md
modules/150-user-authn/docs/USAGE_RU.md

Add links to Okta, Keycloak and Gluu documentation.
Improve OIDC example searchability.
OIDC example is more clearer.
```changes
section: dex
type: fix
summary: Add links on how to register OIDC client in Okta, Keycloak, Gluu.
impact: low
```

[dex] fix: add links on how to register OIDC client in Okta, Keycloak, Gluu

---

modules/041-linstor/images/drbd-driver-loader/Dockerfile
modules/041-linstor/images/spaas/Dockerfile

```changes
type: fix
summary: Bump DRBD version to `9.21.4`.
```

[linstor] bump DRBD version v9.1.9

---

docs/documentation/pages/DECKHOUSE-OVERVIEW.md
docs/documentation/pages/DECKHOUSE-OVERVIEW_RU.md
docs/site/_config.yml
docs/site/_includes/header.html
docs/site/pages/community.html
docs/site/pages/community_ru.html
docs/site/pages/license_request_success.html
docs/site/pages/license_request_success_ru.html

Actualize social network links.
```changes
section: docs
type: chore
summary: Actualized social network links.
```

[site] Fix links in the header of the site

---

candi/bashible/detect_bundle.sh

This PR is fixing regression introduced by https://github.com/deckhouse/deckhouse/pull/2232
```changes
section: candi
type: fix
summary: fix detecting bundle
```

[candi] fix detecting bundle

---

docs/site/pages/license_ru.html

Signed-off-by: Evgeny Samoylov <EvgenySamoylov@users.noreply.github.com>
Update EULA doc link to the latest version.

Update the EULA to the latest version

---

modules/041-linstor/templates/linstor-node/linstorsatelliteset.yaml

This PR fixes incorrect label assigned for linstor-node daemonset
In HA mode linstor-node can't be scheduled with piraeus-operator pods
```changes
type: fix
summary: Fix `linstor-node` label and `podAntiAffinity` in HA mode.
```

[linstor] fix linstor-node label

---

go.mod
go.sum
modules/301-prometheus-metrics-adapter/hooks/custom_metrics_events.go

Bump addon-operator version
This version of addon-operator prevents usage OnStartup and Kubernetes bindings in go-hooks together
```changes
type: chore
summary: Bump addon-operator version
```

[core] bump addon-operator version

---

ee/modules/110-istio/templates/control-plane/iop.yaml

Signed-off-by: Andrey Polovov <andrey.polovov@flant.com>
Co-authored-by: aenoralanar <aenoralanar@users.noreply.github.com>
maxUnavailable strategy for istiod Deployment instead of default one 25%.
Solves https://github.com/deckhouse/deckhouse/issues/2295.
```changes
section: istio
type: fix
summary: maxUnavailable strategy for istiod Deployment instead of default one 25%.
```

[istio] maxUnavailable strategy for istiod

---

docs/documentation/pages/DECKHOUSE-FAQ.md
docs/documentation/pages/DECKHOUSE-FAQ_RU.md
tools/change-registry.sh

Added change registry script to simplify change of registry for devops.
```changes
section: tools
type: chore
summary: Added script to change container registry, which makes it easier for DevOps engineers.
```

[tools] added change registry script

---

modules/150-user-authn/templates/crowd-basic-auth-proxy/deployment.yaml

fix in crowd-basic-auth-proxy deployment
```changes
type: fix
summary: Fixed `crowd-basic-auth-proxy` deployment.
```

[user-authn] fix in crowd-basic-auth-proxy deployment

---

modules/002-deckhouse/hooks/internal/updater/updater.go

Check predicted release exists before fill the CM. Fallback to the deployed release
Avoid panic
```changes
type: fix 
summary: Fix panic in a release tracking during the deckhouse update process.
```

[deckhouse] check predicted release on observing release data

---

modules/040-node-manager/docs/README.md
modules/040-node-manager/docs/README_RU.md

We've got the bug report from the community: #2482
Need to figure it out and then we will return EKS support to the doc.

remove EKS from the node manager doc since it doesn't work

---

docs/documentation/pages/installing/README.md

Signed-off-by: Kirill Kononovich <41591254+kirkonru@users.noreply.github.com>

Translate installing/README.md

---

docs/site/_includes/header.html
modules/810-deckhouse-web/images/web/site/_data/topnav.yml

Added link to the license page.
```changes
section: deckhouse-web
type: fix
summary: Added link to the license page.
```

[deckhouse-web] Add link to the EULA

---

candi/image_versions.yml

The comment is outdated
```changes
section: docs
type: chore
summary: Delete crane comment
```

[docs] Delete crane comment

---

modules/300-prometheus/templates/prometheus/servicemonitor.yaml

Increase maximum scrape limit to 10000 for prometheus service monitor.
If there is a lot of service monitors in the cluster, count of metrics from prometheus itself will be more than 5000 and prometheus scrape will fail.
```changes
type: chore
summary: increase sample rate for prometheus-module service-monitor to 10000
```

[prometheus] increase sample rate for prometheus-module service-monitor to 10000

---

ee/fe/modules/340-monitoring-applications/docs/CONFIGURATION.md
ee/fe/modules/340-monitoring-applications/docs/CONFIGURATION_RU.md
ee/fe/modules/340-monitoring-applications/hooks/discovery.go
ee/fe/modules/340-monitoring-applications/hooks/discovery_test.go
ee/fe/modules/340-monitoring-applications/templates/service-monitors/_helpers.tpl
ee/fe/modules/340-monitoring-applications/templates/service-monitors/base-service-monitor.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/consul.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/elasticsearch.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/etcd3.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/fluentd.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/grafana.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/memcahced.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/minio.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/mongodb.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/nats.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/nginx.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/php-fpm.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/prometheus.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/rabbitmq.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/redis.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/sidekiq.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/trickster.yaml
ee/fe/modules/340-monitoring-applications/templates/service-monitors/uwsgi.yaml
go_lib/set/set.go
modules/303-prometheus-pushgateway/templates/service-monitor.yaml
modules/303-prometheus-pushgateway/templates/service.yaml
modules/340-monitoring-kubernetes/templates/kube-state-metrics/service.yaml

Reduce number of generated service monitors
It also reduces CPU consumption in clusters with many applications enabled.
```changes
type: feature
impact: Reduce number of generated service monitors
```

[monitoring-applications] Reduce number of generated service monitors

---

candi/version_map.yml

Bump version
This minor patches fixes some problems, for example with [target group](https://github.com/kubernetes/cloud-provider-aws/commit/d5582fffde1aae8e43f49df473f5ff95f37172cf) creation
```changes
type: fix
summary: Bump cloud provider version to fix LB target group creation.
```

[cloud-provider-aws] bump version

---

docs/site/_includes/getting_started/vsphere/STEP_ENV.md
docs/site/_includes/getting_started/vsphere/STEP_ENV_RU.md
ee/candi/cloud-providers/vsphere/docs/ENVIRONMENT.md
ee/candi/cloud-providers/vsphere/docs/ENVIRONMENT_RU.md

Fixed docs to properly support set of permissions required in vSphere 7.0U3.
Deckhouse failed to install without them.
Deckhouse installs correctly.
```changes
section: docs
type: chore
summary: Fixed docs to properly support set of permissions required in vSphere 7.0U3.
```

[docs] Fixed vSphere permissions

---

candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
candi/cloud-providers/yandex/openapi/doc-ru-cluster_configuration.yaml
candi/cloud-providers/yandex/terraform-modules/vpc-components/main.tf

Updated clusterConfiguraiton doc for cloud provider yandex.
Added doc warning about manual binding route table to predefined subnets.
```changes
type: chore
summary: Added doc warning about manual binding route table to predefined subnets.
```

[cloud-provider-yandex] assign route table to existing subnets

---

candi/openapi/node_group.yaml

Add the example about using disruptions.
```changes
section: docs
type: fix
summary: Add the example about using disruptions.
```

[docs][nodegroup] Add the example about disruption

---

candi/openapi/doc-ru-init_configuration.yaml
candi/openapi/init_configuration.yaml
modules/010-prometheus-crd/crds/customalertmanager.yaml
modules/010-prometheus-crd/crds/doc-ru-customalertmanager.yaml

Fix typos and broken links.
```changes
section: docs
type: fix
summary: Fix typos and broken links.
```

[docs] Fix typos and broken links

---

candi/image_versions.yml

Fixes HIGH and CRITICAL CVE: 
- [CVE-2022-30065](https://nvd.nist.gov/vuln/detail/CVE-2022-30065)
- CVE-2022-37434
```changes
section: candi
type: chore
summary: Bump alpine base image to `3.16.2`.
impact:  The majority of pods owned by Deckhouse will be restarted.
```

Bump alpine to 3.16.2

---

candi/openapi/doc-ru-node_group.yaml
candi/openapi/node_group.yaml
modules/002-deckhouse/openapi/config-values.yaml
modules/002-deckhouse/openapi/doc-ru-config-values.yaml

OpenaAPI schemas minor fixes.
Added examples and descriptions.
```changes
type: fix
summary: OpenaAPI schemas minor fixes.
---
section: candi
type: fix
summary: OpenaAPI schemas minor fixes.
```

[deckhouse][candi] OpenaAPI schemas minor fixes

---

docs/site/_includes/getting_started/aws/partials/resources.yml.production.inc
docs/site/_includes/getting_started/global/STEP_FINISH.md
docs/site/_includes/getting_started/global/STEP_FINISH_RU.md
docs/site/_includes/getting_started/kind/STEP_FINISH.md
docs/site/_includes/getting_started/yandex/partials/resources.yml.production.inc
modules/402-ingress-nginx/docs/FAQ.md
modules/402-ingress-nginx/docs/FAQ_RU.md

Fix doc about hpa mode.
```changes
type: chore
summary: Fix doc about HPA mode.
```

[ingress-nginx-controller] fix doc about hpa

---

.github/workflow_templates/validation.yml
.github/workflows/validation.yml

Check if PR has milestone.
CI fails if PR has no milestone.
```changes
section: ci
type: chore
summary: Check if PR has a milestone.
```

[ci][validation] Check if PR has milestone

---

modules/340-monitoring-kubernetes/templates/kube-state-metrics/deployment.yaml

Add deployments to kube-state-metrics's allowlist.
Kube-state-metrics couldn't export deployment labels.
```changes
type: fix
summary: Add deployments to kube-state-metrics's allowlist.
```

[monitoring-kubernetes] add deployments to kube-state-metrics's allowlist

---

docs/site/_includes/footer.html

Fix contact us phone number on the footer.

[site] Fix contact us phone number on the footer

---

docs/documentation/_includes/sidebar.html
docs/site/css/docs.scss
docs/site/js/customscripts.js

Stick sidebar to the top of the page in the documentation.
```changes
section: docs
type: fix
summary: Stick sidebar to the top of the page in the documentation.
```

[docs] Fix sidebar in documentation

---

docs/documentation/_data/supported_versions.yml

[doc] Fix misspellings

---

docs/site/_data/footer.yaml
docs/site/_data/topnav.yml
docs/site/css/components/_substitution.scss
docs/site/css/site.scss
docs/site/pages/substitution_ru.html
docs/site/pages/substitution_ru.md

[site] Site updates

---

docs/documentation/.werf/nginx.conf

Add site redirects according to modules reordering.
```changes
section: docs
type: fix
summary: Add site redirects according to modules reordering.
```

[docs] Add redirects to the documentation

---

docs/site/pages/substitution_ru.html

[docs] Site minor fix

---

modules/500-openvpn/docs/CONFIGURATION.md
modules/500-openvpn/docs/CONFIGURATION_RU.md
modules/500-openvpn/openapi/config-values.yaml

Minor fixes in the openvpn module documentation and OpenAPI spec (added examples).
```changes
type: fix
summary: Minor fixer in the openvpn module documentation.
```

[docs][openvpn] Update documentation

---

modules/040-node-manager/monitoring/prometheus-rules/early-oom.tpl

Rename D8EarlyOOMPodIsNotReady alert to EarlyOOMPodIsNotReady
For internal purposes.
N/A
```changes
type: chore
summary: Rename the `D8EarlyOOMPodIsNotReady` alert to the `EarlyOOMPodIsNotReady` alert.
```

[node-manager] Rename D8EarlyOOMPodIsNotReady alert to EarlyOOMPodIsNotReady

---

docs/site/_includes/clients.html

[site] Remove flags from our clients slider

---

modules/041-linstor/monitoring/prometheus-rules/linstor-node.yaml

Change `node` to `exported_node`.
```changes
type: chore
summary: Fix description for D8LinstorNodeIsNotOnline alert
```

[linstor] Fix description for D8LinstorNodeIsNotOnline alert

---

Makefile

We have an error in main makefile, which prevents to download gator binary.
```changes
section: tests
type: fix
summary: fix makefile gator error.
```

[tests] fix makefile gator error

---

modules/402-ingress-nginx/templates/controller/admission.yaml

Increase validation webhook timeout.
If we have a lot of Ingresses hook can fail with a deadline. Let's increase the timeout.
```changes
type: fix
summary: Increase Ingress validation webhook timeout.
```

[ingress-nginx] Increase validation webhook timeout

---

docs/documentation/_data/search.yml
docs/documentation/_includes/search.html
docs/documentation/_plugins/custom_filters.rb
docs/documentation/_plugins/openapi.rb
docs/documentation/js/search.js

Updated search indexing for the ability to search by OpenAPI spec parameters.
Close: #1773 
Ability to find a parameter by its name on the site.
```changes
section: docs
type: feature
summary: Updated search indexing for the ability to search by OpenAPI spec parameters.
```

[docs] Update search index data

---

docs/site/_data/topnav.yml
docs/site/pages/license_rules_ru.html

[site] Minor updates

---

modules/040-control-plane-manager/images/control-plane-manager/control-plane-manager
modules/040-control-plane-manager/images/control-plane-manager/werf.inc.yaml

Save 5 latest backups instead of deleting them all on success.
If a configuration was applied and control-plane-components have become ready, but there is something wrong with this config, it isn't possible to debug or diff with the previous configuration.
5 latest backups are saved instead of being deleted.
```changes
type: feature
summary: Save latest 5 backups of control-plane configs
```

[control-plane-manager] Save 5 latest backups

---

docs/documentation/_data/supported_versions.yml
docs/documentation/_includes/SUPPORTED_VERSIONS.liquid

Added links to supported OS versions on the site.
```changes
section: docs
type: fix
summary: Added links to supported OS versions on the site.
```

[docs] Add links to supported OS versions

---

candi/openapi/doc-ru-node_group.yaml
candi/openapi/node_group.yaml

Review the description of `minPerZone` and `maxPerZone` relations in the NodeGroup CR documentation.
Update the documentation to make it more user-friendly.
The documentation becomes easier to understand.
```changes
type: fix
summary: "Update the description of `minPerZone` and `maxPerZone` in the NodeGroup CR documentation."
```

[node-manager][doc] review the description of minPerZone and maxPerZone

---

docs/site/_data/revision_comparison.yml
docs/site/_includes/head-site.html
docs/site/_includes/revision_comparison_table.liquid
docs/site/pages/enterprise_edition_ru.html

Updates subscription plans table on the site.
```changes
section: docs
type: fix
summary: Site updates
```

[site] Update EE page on the site

---

docs/documentation/.helm/templates/20-ingress.yaml
docs/site/.helm/templates/20-ingress.yaml

Delete sticky sessions Ingress annotations.

[chore] Delete ingress old annotations

---

docs/documentation/_data/sidebars/main.yml
ee/modules/380-metallb/docs/USAGE.md
ee/modules/380-metallb/docs/USAGE_RU.md
modules/402-ingress-nginx/docs/USAGE.md
modules/402-ingress-nginx/docs/USAGE_RU.md

- Add metallb module usage example
- Small ingress usage refactoring. Renamed general example
This isn't clear what does `general example` means for ingress controller. And we have nice metallb module, but no examples. It's a shame.
```changes
type: chore
summary: Add metallb module usage example
```

[metallb] Add metallb module usage example

---

ee/modules/110-istio/openapi/openapi-case-tests.yaml
modules/021-cni-cilium/openapi/openapi-case-tests.yaml

Fix openapi cases for istio and cni-cilium modules after merging #2986 
Tests fail for PR based on main.
Openapi tests work good.
```changes
type: fix
summary: fix openapi cases for istio and cni-cilium modules
```

[testing] fix openapi tests after #2986

---

ee/modules/030-cloud-provider-vsphere/templates/registration.yaml

Fix value encoding in the template
Bootstrap fails
```changes
type: fix
summary: Fix helm template.
```

[cloud-provider-vsphere] fix template encoding

---

candi/version_map.yml

Changed desired kernel version to 5.11 for ubuntu 20.04.
For the correct operation of the openvpn and node-local-dns modules in clusters with the cilium module enabled, kernel version 5.7 or higher is required.
```changes
section: candi
type: fix
summary: Changed desired kernel version to 5.11.0-46-generic for ubuntu 20.04.
```

[candi] change desired kernel version for ubuntu 20.04

---

docs/site/pages/enterprise_edition.html
docs/site/pages/enterprise_edition_ru.html

Update info about subscription plans
```changes
section: docs
type: chore
summary: Update info about subscription plans.
```

[site] Update info about subscription plans

---

ee/fe/modules/500-basic-auth/hooks/generate_passwords.go

Enhanced the error message when there are unexpected number of fields in credentials secret.
Better describes user error in Deckhouse logs
The error should be more consistent with what the secret state
```changes
section: basic-auth
type: chore
summary: Improved error message on unexpected number of fields in the credentials secret
```

[basic-auth] Better error in secret validation

---

docs/site/css/components/_footer.scss

[site] Fix footer nav

---

modules/402-ingress-nginx/templates/controller/controller.yaml

Set minReadySeconds for an ingress controller DaemonSet
LoadBalancers sometimes don't have time to add a new controller to the endpoints and DaemonSet controller immediately terminates an old pod when a new is ready. We can put a delay between there two actions and give a LB some time to rebuild the endpoints.
```changes
type: fix 
summary: Add minReadySeconds for LB inlet controllers. This will give some time for LB to rebuild the endpoints.
```

[ingress-nginx] Min ready seconds

---

modules/140-user-authz/docs/USAGE.md
modules/140-user-authz/docs/USAGE_RU.md

Add fixes to make instructions valid for Kubernetes v1.24
```changes
type: fix
summary: Fix kubeconfig doc for Kubernetes `1.24`.
```

[user-authz] Fix kubeconfig doc for Kubernetes 1.24

---

docs/site/_includes/request_access_form.html
docs/site/_includes/request_callback_form.html
docs/site/_includes/request_education_form.html
docs/site/js/popup-form.js

[site] Added honeypot in forms

---

docs/site/_data/footer.yaml
docs/site/_data/topnav.yml

[site] Added Deckhouse vacancy link

---

modules/460-log-shipper/apis/v1alpha1/cluster_log_destination.go
modules/460-log-shipper/apis/v1alpha1/types.go
modules/460-log-shipper/crds/cluster-log-destination.yaml
modules/460-log-shipper/crds/doc-ru-cluster-log-destination.yaml
modules/460-log-shipper/hooks/generate_config_test.go
modules/460-log-shipper/hooks/internal/composer/composer.go
modules/460-log-shipper/hooks/internal/vector/destination/splunk.go
modules/460-log-shipper/hooks/testdata/file-to-splunk/manifests.yaml
modules/460-log-shipper/hooks/testdata/file-to-splunk/result.json
modules/460-log-shipper/images/vector/Dockerfile

Closes https://github.com/deckhouse/deckhouse/issues/3092
```changes
type: feature
summary: Add Splunk destination.
```

[log-shipper] Add Splunk destination

---

modules/140-user-authz/docs/USAGE.md

N/A
Markdown linter check was not pass
```changes
type: fix
summary: Fix markdown lint errors.
```

[user-authz] Fix markdown lint errors

---

modules/500-openvpn/openapi/config-values.yaml
modules/500-openvpn/openapi/doc-ru-config-values.yaml
modules/500-openvpn/templates/openvpn/configmap.yaml

Added pushDefaultGatewayToClient parameter.
This will allow clients to route all traffic through the VPN server by default.
```changes
type: feature
summary: Added pushDefaultGatewayToClient parameter.
impact: The openvpn pod will be restarted
```

[openvpn] Add pushDefaultGatewayToClient option

---

docs/site/_config.yml

Update the default page description.
```changes
section: docs
type: chore
summary: Update the default page description.
```

[site] Update the default description

---

modules/010-user-authn-crd/crds/dex-authenticator.yaml
modules/010-user-authn-crd/crds/dex-provider.yaml
modules/010-user-authn-crd/crds/doc-ru-dex-provider.yaml
modules/150-user-authn/openapi/values.yaml
modules/150-user-authn/templates/dex/config.yaml

Add the claim mappings option for OIDC providers to be able to deal with custom claims.
Some providers return non-standard claims (eg. mail). Dex cannot map mail to email by default, so it needs some hints from the user side.
https://dexidp.io/docs/connectors/oidc/
Nothing.
```changes
type: feature
summary: Add claim mappings for OIDC providers.
```

[user-authn] Add claim mappings for OIDC providers

---

.github/ci_templates/web.yml
.github/workflows/build-and-test_dev.yml
.github/workflows/build-and-test_pre-release.yml
.github/workflows/build-and-test_release.yml

Fix broken links checker.
The broken links checker doesn't since the new site structure has been implemented.
```changes
type: chore
summary: The broken links checker doesn't since the new site structure has been implemented.
```

[testing]  Fix broken links checker

---

docs/site/_includes/getting_started/vsphere/STEP_ENV.md
docs/site/_includes/getting_started/vsphere/STEP_ENV_RU.md
ee/candi/cloud-providers/vsphere/docs/ENVIRONMENT.md
ee/candi/cloud-providers/vsphere/docs/ENVIRONMENT_RU.md

Update documentation of setting up environment.
```changes
section: docs
type: chore
summary: Update documentation of setting up environment.
```

[docs][cloud-provider-vsphere] Update documentation of setting up environment

---

.github/scripts/js/constants.js
.github/workflow_templates/e2e.multi.yml
.github/workflows/e2e-aws.yml
.github/workflows/e2e-azure.yml
.github/workflows/e2e-gcp.yml
.github/workflows/e2e-openstack.yml
.github/workflows/e2e-static.yml
.github/workflows/e2e-vsphere.yml
.github/workflows/e2e-yandex-cloud.yml

Add 1.25 e2e tests
We have to have ci workflow in the main branch to run tests
```changes
section: ci
type: chore
summary: Add 1.25 e2e label test
```

[ci] add 1.25 e2e

---

modules/140-user-authz/templates/cluster-roles.yaml

Allowing pods manipulation for user-authz:admin clusterrole.
It is fix, relates to allow **create patch update** rights for **pods** by user-authz:admin clusterrole.
It fixes this issue: #2782
user-authz:admin clusterrole must have the following rights for pods resources:
`get list watch delete deletecollection create patch update`
```changes
type: fix
summary: create patch update rights for user-authz:admin clusterrole
```

Setting pods manipulation for authz Admin role

---

ee/modules/350-node-local-dns/enabled
ee/modules/values-managed.yaml

* Disable node-local-dns if kube-dns is not deployed
* Remove node-local-dns from Managed bundle
The node-local-dns module simply does not work without kube-dns.
https://github.com/deckhouse/deckhouse/blob/d287a2ee382b66d1d3489719a70ac471a0b751bf/ee/modules/350-node-local-dns/hooks/cluster_dns_address.go#L57-L59
```changes
type: fix
summary: Remove from Managed bundle.
```

[node-local-dns] Remove from Managed bundle

---

modules/140-user-authz/docs/USAGE.md
modules/140-user-authz/docs/USAGE_RU.md

Minor doc fixes (ref: #3237)
```changes
type: chore
summary: Minor doc fixes.
```

[docs][user-authz] Minor fixes

---

modules/015-admission-policy-engine/templates/registry-secret.yaml

Add registry secret which is used by deployments
Forgot
```changes
type: fix
summary: Add secret with credentials for a registry
```

[admission-policy-engine] Add registry secret

---

testing/cloud_layouts/script.sh

Remove additional logs catching method.
Additional log file makes bigger artifact. ~1Mb for regular artifact and ~40Mb for artifact with the additional log.
```changes
section: test
type: chore
summary: Remove catching additional logs during e2e tests.
```

[testing] chore: remove catching additional logs during e2e tests

---

.github/scripts/js/ci.js
.github/scripts/js/constants.js
.github/workflow_templates/e2e-daily.yml
.github/workflows/e2e-daily.yml
dhctl/pkg/config/base.go
global-hooks/discovery/cluster_configuration_test.go

Changed default kubernetes version to 1.23.
```changes
type: chore
summary: Changed the default Kubernetes version to `1.23`.
impact: Clusters with the `kubernetesVersion` parameter set to `Automatic` will be upgraded to Kubernetes `1.23`.
```

[deckhouse] change default kubernetes version to 1.23

---

docs/documentation/search-index.json
docs/site/search-index.json

Fix search index.
```changes
section: docs
type: chore
summary: Fix search index.
```

[site] Fix search index

---

modules/007-registrypackages/images/containerd-centos/scripts/install
modules/007-registrypackages/images/docker-centos/scripts/install
modules/007-registrypackages/images/inotify-tools-centos/scripts/install
modules/007-registrypackages/images/kubeadm-centos/scripts/install
modules/007-registrypackages/images/kubectl-centos/scripts/install
modules/007-registrypackages/images/kubelet-centos/scripts/install
modules/007-registrypackages/images/kubernetes-cni-centos/scripts/install

Allow downgrading RPMs in registrypackages for centos.
It is impossible to downgrade to previous release if there were packages upgraded in current release.
registrypackages install the rpms despite the version.
```changes
type: fix
summary: Allow downgrading RPMs in registrypackages for CentOS.
```

[registrypackages] Allow downgrading RPMs in centos

---

ee/modules/600-flant-integration/monitoring/prometheus-rules/sending-alerts.yaml

D8PrometheusMadisonErrorSendingAlertsToBackend many-to-many fix.
It doesn't work in HA-clusters. Related to https://github.com/deckhouse/deckhouse/pull/3113.
```changes
type: fix
summary: D8PrometheusMadisonErrorSendingAlertsToBackend many-to-many fix
```

[flant-integration] D8PrometheusMadisonErrorSendingAlertsToBackend many-to-many fix

---

modules/340-extended-monitoring/monitoring/prometheus-rules/image-availability/image-availability-exporter-health.yaml

Fix another alert with wrong group

---

modules/099-ceph-csi/hooks/get_crds.go
modules/099-ceph-csi/hooks/get_crds_test.go
modules/099-ceph-csi/templates/cephfs/storage-classes.yaml
modules/099-ceph-csi/templates/rbd/storage-classes.yaml

Delete storage classes after changing immutable fields.
In #3212 the immutable parameters of storageclasses were changed. Therefore, they need to be recreated.
```changes
type: fix
summary: Delete storage classes after changing immutable fields.
```

[ceph-csi] Delete storage classes after changing immutable fields

---

modules/402-ingress-nginx/hooks/order_certificates.go
modules/402-ingress-nginx/hooks/order_certificates_test.go
modules/402-ingress-nginx/templates/controller/secret.yaml

Update client certificate for ingress
Migrate from old client certificate from kube-rbac-proxy to the new one
```changes
type: fix
summary: Fix client certificate update.
```

[ingress-nginx] update client certificate

---

docs/site/pages/index_ru.html
docs/site/pages/substitution_ru.html

[site] Update site content

---

modules/340-monitoring-deckhouse/monitoring/prometheus-rules/kernel-requirements.yaml
modules/340-monitoring-deckhouse/monitoring/prometheus-rules/node-os-requirements.yaml

In deckhouse release 1.43 we plan to remove Ubuntu 16.04 support.
This PR adds alerting about Ubuntu 16.04 deprecation.
```changes
type: chore
summary: Add an alert about deprecated OS versions.
```

[monitoring] add an alert about deprecated OS versions

---

modules/040-node-manager/docs/FAQ.md
modules/040-node-manager/docs/FAQ_RU.md

Clarify using NodeGroup parameters.
```changes
section: docs
type: chore
summary: Clarify using NodeGroup parameters.
```

[node-manager] Clarify using NodeGroup parameters

---

docs/site/_includes/getting_started/vsphere/partials/resources.yml.ha.inc
docs/site/_includes/getting_started/vsphere/partials/resources.yml.minimal.inc
docs/site/_includes/getting_started/vsphere/partials/resources.yml.production.inc

Vsphere getting started fix — added mandatory mainNetwork field to NGs.
```changes
section: site
type: fix
summary:Vsphere getting started fix — added mandatory mainNetwork field to NGs.
```

[doc][getting started] fixed vsphere resources.yml

---

docs/site/_includes/getting_started/yandex/STEP_ENV.md
docs/site/_includes/getting_started/yandex/STEP_ENV_RU.md
ee/modules/110-istio/openapi/values.yaml
ee/modules/502-delivery/docs/USAGE.md
ee/modules/502-delivery/docs/USAGE_RU.md
ee/modules/502-delivery/openapi/config-values.yaml
ee/modules/502-delivery/openapi/doc-ru-config-values.yaml
modules/460-log-shipper/docs/internal/demo/audit-policy.yaml

Fix broken links.
```changes
section: docs
type: chore
summary: Fix broken links.
```

Fix broken links

---

docs/documentation/pages/DECKHOUSE-FAQ.md
docs/documentation/pages/DECKHOUSE-FAQ_RU.md
modules/031-local-path-provisioner/docs/FAQ.md
modules/031-local-path-provisioner/docs/FAQ_RU.md
modules/040-control-plane-manager/docs/EXAMPLES.md
modules/040-control-plane-manager/docs/EXAMPLES_RU.md
modules/040-control-plane-manager/docs/FAQ.md
modules/040-control-plane-manager/docs/FAQ_RU.md

```changes
section: docs
type: chore
```

[docs][control-plane-manager][local-path-provisioner] Minor documentation updates

---

deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go
modules/040-node-manager/hooks/minimal_node_os_version.go
modules/040-node-manager/hooks/minimal_node_os_version_test.go
modules/040-node-manager/requirements/check.go
modules/040-node-manager/requirements/check_test.go

This is part of https://github.com/deckhouse/deckhouse/pull/3388, which be implemented before main part.
```changes
type: chore
summary: Add requirements for nodes
```

[node-manager] add requirements for nodes

---

docs/documentation/_includes/revision_comparison_detail_table.liquid
docs/documentation/_plugins/custom_hooks.rb
docs/site/css/docs.scss

Added label with module status in the comparison table (revision-comparison.html).
```changes
section: docs
type: chore
summary: Added label with module status in the comparison table.
```

[docs] Add module status label in the comparison table

---

modules/101-cert-manager/docs/USAGE_RU.md

[docs] Fix typo

---

ee/modules/350-node-local-dns/templates/configmap.yaml

Changed "verified" to "verify".
The documentation on a coredns.io has a bug. The "main" branch is fixed upstream, but the website is not updated that often.
node-local-dns starts correctly.
```changes
type: fix
summary: Changed "verified" to "verify"
```

[node-local-dns] Fixed serve_stale syntax

---

docs/site/pages/policies/cookie_policy.html
docs/site/pages/policies/privacy_policy.html
docs/site/pages/policies/terms_of_service.html

[docs] Minor updates of the site

---

ee/fe/modules/340-monitoring-applications/applications/redis/grafana-dashboards/redis.json

Added new metrics like redis version, eviction policy, master/slave role, total and average commands duration
```changes
type: feature
summary: Redis dashboard improvements

Grafana: Redis dashboard improvements

---

Makefile
docs/site/Makefile

Update Makefile to stop documentation containers on macOS (they have different names on Linux and macOS).
```changes
section: ci
type: chore
summary: Update Makefile to stop documentation containers on macOS.
```

[ci] Update Makefile

---

modules/015-admission-policy-engine/crds/native/assign-customresourcedefinition.yaml
modules/015-admission-policy-engine/crds/native/assignmetadata-customresourcedefinition.yaml
modules/015-admission-policy-engine/crds/native/expansiontemplate-customresourcedefinition.yaml
modules/015-admission-policy-engine/crds/native/modifyset-customresourcedefinition.yaml
modules/015-admission-policy-engine/images/gatekeeper/Dockerfile
modules/015-admission-policy-engine/templates/README.md

Bump version
Close CVE
Migrate to stable version of CRDs
```changes
type: feature
summary: Bump gatekeeper version. Close CVE
```

[admission-policy-engine] bump version

---

docs/documentation/pages/DECKHOUSE-FAQ.md
docs/documentation/pages/DECKHOUSE-FAQ_RU.md

Instruction about how to switch Deckhouse revision EE <-> CE
```changes
section: docs
type: chore
summary: 'Instruction about how to switch Deckhouse revision EE <-> CE'
```

[docs] Add instruction about how to switch Deckhouse revision

---

docs/documentation/_data/sidebars/main.yml
docs/site/_config.yml
docs/site/css/docs.scss

Updated sidebar to show EE statues for the delivery module.
Updated site config to show EE status on the page of the istio and delivery modules.
```changes
section: docs
type: chore
summary: Update the labels of EE modules.
```

[site] Update the labels of EE modules

---

modules/040-control-plane-manager/templates/_authn_webhook_config.tpl
modules/040-control-plane-manager/templates/daemonset.yaml

CA should not be mandatory because of certificates signed by publicly available CAs and HTTP webhooks
```changes
type: fix
summary: Make authn webhook CA optional.
```

[control-plane-manager] Make auth webhook CA optional

---

candi/docs/README.md
docs/site/_includes/getting_started/bm-private/partials/config.yml.ce.inc
docs/site/_includes/getting_started/bm/partials/config.yml.ce.inc
docs/site/_includes/getting_started/bm/partials/config.yml.ee.inc

Added note about StaticClusterConfiguration.
```changes
section: getting-started
type: chore
summary: Added note about `StaticClusterConfiguration`.
```

[doc] added note about StaticClusterConfiguration

---

ee/modules/110-istio/images/proxyv2-v1x12x6/Dockerfile
ee/modules/110-istio/images/proxyv2-v1x13x7/Dockerfile

switching default iptables in proxyv2 to iptables-legacy (after switching debian to ubuntu).
```changes
section: istio
type: fix
summary: switching default iptables in proxyv2 to iptables-legacy (after switching debian to ubuntu).
```

[istio][fix] switching default iptables in proxyv2 to iptables-legacy

---

modules/300-prometheus/templates/trickster/servicemonitor.yaml

Trickster sample limit changed to 1500
In some cases, trickster can have more than 1000 metrics, so we have TargetDown problem.
Trickster metrics are collected normally.
```changes
type: fix
summary: Trickster sample limit changed to 1500.
```

[prometheus] Trickster sample limit changed to 1500

---

modules/007-registrypackages/images/containerd-centos/werf.inc.yaml

Fix containerd centos build.
Fix error with disappeared container-selinux-2.189 package from centos repository.
```changes
section: build
type: fix
summary: fix containerd centos build
```

[build] fix containerd centos build

---

docs/site/pages/regulations_ru.html

Technical support regulations updates.

[docs] Technical support regulations updates

---

modules/041-linstor/docs/FAQ_RU.md

Signed-off-by: Evgeny Samoylov <EvgenySamoylov@users.noreply.github.com>
Fix typos in the listor module documentation.
```changes
type: chore
summary: Fix typos in the documentation.
```

Fix some typos

---

modules/041-linstor/docs/USAGE.md

```changes
type: chore
summary: Update docs.
```

[linstor] Update docs

---

tools/change-registry.sh

Added support for port in registry address in change-registry.sh script
Now it unsupported
```changes
section: tools
type: fix
summary: Added support for port in registry address in change-registry.sh script.
```

[tools] Added support for port in registry address in change-registry.sh script

---

modules/040-node-manager/templates/node-group/_static_or_hybrid_script.tpl

Signed-off-by: Konstantin Maltsev <konstantin.maltsev@flant.com>
There is a fix for bashible service checking regarding to node bootstrap.
It's a hot-fix regarding possible **"Unknown"** output string during bashible checking on other distros.
If service is **active** - there is no needs to perform bootstrap. Other outputs should calls script execution.
```changes
type: fix
summary: fix bashible service checking
```

[bashible] Fix bashible service checking

---

modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml

Signed-off-by: Evgeny Samoylov <EvgenySamoylov@users.noreply.github.com>
Added link to "how to update the Kubernetes version in a cluster" doc in the D8KubernetesVersionIsDeprecated alert.
Teams are always asking for that when receiving the alert.
Fewer interruptions for the duty engineer.
```changes
```

Add link to the doc in the alert description

---

modules/101-cert-manager/docs/FAQ.md
modules/101-cert-manager/docs/FAQ_RU.md
modules/460-log-shipper/docs/EXAMPLES.md
modules/460-log-shipper/docs/EXAMPLES_RU.md

Apply MD linter suggestions.
```changes
section: docs
type: chore
summary: Apply MD linter suggestions
```

[chore] Apply MD linter suggestions

---

ee/modules/502-delivery/templates/argocd/application-controller/argocd-application-controller-statefulset.yaml
ee/modules/502-delivery/templates/argocd/applicationset-controller/argocd-applicationset-controller-deployment.yaml
ee/modules/502-delivery/templates/argocd/image-updater/argocd-image-updater-deployment.yaml
ee/modules/502-delivery/templates/argocd/notifications-controller/argocd-notifications-controller-deployment.yaml
ee/modules/502-delivery/templates/argocd/redis/argocd-redis-deployment.yaml
ee/modules/502-delivery/templates/argocd/repo-server/argocd-repo-server-deployment.yaml
ee/modules/502-delivery/templates/argocd/server/argocd-server-deployment.yaml
modules/041-linstor/templates/linstor-scheduler-admission/deployment.yaml
modules/490-virtualization/templates/virt-operator/deployment.yaml
modules/491-containerized-data-importer/templates/cdi-operator/deployment.yaml

Fix deprecated PDB APIs
Kubernetes v1.25+ support
```changes
type: fix
summary: Fix deprecated PDB APIs for Kubernetes v1.25+
---
type: fix
summary: Fix deprecated PDB APIs for Kubernetes v1.25+
---
type: fix
summary: Fix deprecated PDB APIs for Kubernetes v1.25+
```

[delivery][linstor][virtualization] Fix deprecated PDB APIs

---

docs/site/js/getting-started.js

Fix incorrect blurring in the getting started when change to EE.
```changes
section: docs
type: chore
summary: Fix incorrect blurring in the getting started.
```

[docs][getting-started] Fix incorrect blurring

---

candi/bashible/bashbooster/50_deckhouse_registrypackages.sh

Fix registry packages tmpdir cleanup.
Related to https://github.com/deckhouse/deckhouse/issues/2954.
If registry package fails to install, temporary dir for package is not removed.
```changes
section: candi
type: fix
summary: fix registry packages tmpdir cleanup
```

[candi] fix registry packages tmpdir cleanup

---

.github/CODEOWNERS

Add kvaps to codeowners of virtualization, containerized-data-importer and cdi modules
```changes
section: ci
type: chore
summary: Update codeowners of `virtualization`, `containerized-data-importer` and `cdi` modules.
```

[github] Add kvaps to codeowners virtualization, containerized-data-importer and cdi

---

release.yaml

Temporarily removed requirement for minimal ubuntu node version
Fix for release 1.43
Proper cluster update to 1.43 release
```changes
type: fix
summary: Temporarily removed the requirement for minimal ubuntu node version.
```

[global] Temporarily removed requirement for minimal ubuntu node version.

---

modules/300-prometheus/templates/alertmanager/internal/alertmanager.yaml

This one was lost during refactoring.
```changes
summary: Fix Alertmanager CA file (caused Unauthorized error).
```

[prometheus] Fix Alertmanager CA file

---

global-hooks/discovery/modules_images_tags.go

If os env EXTERNAL_MODULES_DIR is not set, hook writes wrong values for images in node-manager module (due to symlink to main images_tags.json file)
```changes
section: candi
type: fix
summary: fix modules_images_tags hook
```

[global-hooks] fix modules_images_tags hook

---

modules/099-ceph-csi/docs/internal/INTREE_MIGRATION.md

Added a small clarification to the migration docs.
This is necessary to eliminate misunderstandings.
```changes
type: chore
summary: Added a small clarification to the migration docs
```

[ceph-csi] Added a small clarification to the migration docs

---

modules/340-extended-monitoring/images/events-exporter/Dockerfile
modules/460-log-shipper/docs/EXAMPLES.md
modules/460-log-shipper/docs/EXAMPLES_RU.md

[log-shipper] Collect events doc
* Bump events_exporter https://github.com/nabokihms/events_exporter/releases/tag/v0.0.4
* Add instructions about collecting events with log-shipper
```changes
type: chore
summary: Bump events exporter.
---
type: chore
summary: Add instruction about collecting and sending Kubernetes events using log-shipper.
```

[extended-monitoring] Bump events exporter

---

docs/site/css/components/_resources.scss

Update style of resource parameters.
```changes
section: docs
type: chore
summary: Update the style of resource parameters.
```

[site] Update the style of resource parameters

---

Makefile

Bump golangci-lint to v1.48.0 (the same as werf.yaml file)
Align golangci-lint version in Makefile with version in werf.yaml to have the same behavior on local machine (`make lint`) and CI
```changes
section: ci
type: chore
summary: Bump golangci-lint to v1.48.0 (the same as werf.yaml file)
```

[ci] Bump golangci-lint to v1.48.0 (the same as werf.yaml file)

---

.github/workflows/e2e-aws.yml
.github/workflows/e2e-azure.yml
.github/workflows/e2e-gcp.yml
.github/workflows/e2e-openstack.yml
.github/workflows/e2e-static.yml
.github/workflows/e2e-vsphere.yml
.github/workflows/e2e-yandex-cloud.yml

Add not commit files
Main branch broken
```changes
section: ci
type: fix
summary: Add not commit files
```

[ci] Add not commit files

---

.github/workflow_templates/e2e.abort.multi.yml
.github/workflows/e2e-abort-aws.yml
.github/workflows/e2e-abort-azure.yml
.github/workflows/e2e-abort-gcp.yml
.github/workflows/e2e-abort-openstack.yml
.github/workflows/e2e-abort-static.yml
.github/workflows/e2e-abort-vsphere.yml
.github/workflows/e2e-abort-yandex-cloud.yml

Add versions 1.25 and 1.26
```changes
section: ci
type: chore
summary: Add 1.25 and 1.26 versions
```

[ci] abort for e2e clusters

---

docs/documentation/_data/sidebars/main.yml
docs/documentation/_includes/sidebar_entry.html

Update the sidebar generator to fix tooltip.
```changes
section: docs
type: chore
summary: Update the sidebar generator to fix tooltip.
```

[site] Update the sidebar generator to fix tooltip

---

docs/site/pages/substitution_ru.html

Add button on the substitution page on the site.

[site] Add button on the substitution page

---

modules/021-cni-cilium/images/cilium/patches/README.md

Fix link on upstream patch with MTU
```changes
type: chore
summary: Fix link on upstream patch.
```

[cni-cilium] Fix link on upstream patch

---

modules/490-virtualization/images/vmi-router/controllers/vmirouter_controller.go

Fix: routes-controller can't work with cilium running in host-gw mode
vmi-router always overrides interface to `cilium_host`, but it not works in `host-gw` mode when routes should be constructed via physical interfaces.
Thus we should override interface only for local routes
```changes
type: fix
summary: Fix routes in host-gw mode
```

[virtualization] Fix routes in host-gw mode

---

modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
modules/402-ingress-nginx/crds/ingress-nginx.yaml

Documentation fixes.
Indicated a link where to look for the `controllerVersion` version.
```changes
section: docs
type: chore
summary: Improved documentation.
```

[ingress-nginx][docs] Add link to the controllerVersion parameter

---

modules/015-admission-policy-engine/templates/audit-deployment.yaml
modules/015-admission-policy-engine/templates/gatekeeper-deployment.yaml

Fix PDBs
Fix pdb for controller (minAvailable depends on HA mode)
Remove minAvailable pdb for audit-controller (pause inside this component is not important)
These controllers could not be evicted atm
```changes
type: fix
summary: fix PDBs for controllers
```

[admission-policy-engine] fix pdb

---

docs/documentation/_includes/search.liquid
docs/documentation/_plugins/custom_hooks.rb
docs/documentation/js/search.js

Improve search by module name
```changes
section: docs
type: chore
summary: Improve search by module name.
```

[docs] Improve search by module name.

---

modules/011-flow-schema/docs/FAQ.md
modules/011-flow-schema/docs/FAQ_RU.md
modules/011-flow-schema/docs/README.md
modules/011-flow-schema/docs/README_RU.md

```changes
section: flow-schema
type: chore
```

[flow-schema] Minor documentation updates

---

docs/site/_includes/getting_started/yandex/partials/config.yml.standard.ce.inc
docs/site/_includes/getting_started/yandex/partials/config.yml.standard.ee.inc

Fix the EE Layout in the Getting Started.
```changes
section: docs
type: chore
summary: Fix the EE Layout in the Getting Started.
```

[cloud-provider-yandex] Fix the EE Layout in the Getting Started

---

modules/460-log-shipper/templates/daemonset.yaml
testing/matrix/linter/rules/resources/vpa.go
testing/matrix/linter/rules/rules.go

Fix matrix vpa tests.
We do not test couple of modules due to wrong test logic.
```changes
type: fix
summary: fix matrix vpa tests
```

[testing] fix matrix vpa tests

---

modules/490-virtualization/docs/EXAMPLES.md
modules/490-virtualization/docs/EXAMPLES_RU.md
modules/490-virtualization/hooks/vm_handler_test.go

Use small but real ssh-key in virtualization documentation.
More real-world example
```changes
type: chore
summary: Specify real ssh-key.
```

[virtualization] docs: specify real ssh-key

---

modules/021-kube-proxy/templates/daemonset.yaml

Fix in kube-proxy DS template for static clusters.
After PR #3914 kube-proxy DS can't be rendered for static clusters, because there is no cloud section in cluster configuration.
Kube-proxy DS template renders properly for static clusters.
```changes
section: Fix in kube-proxy DS template for static clusters.
type: fix
summary: Fix `kube-proxy` DaemonSet rendering for static cluster.
```

[kube-proxy] fix in kube-proxy DS template for static clusters

---

candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
candi/cloud-providers/yandex/openapi/instance_class.yaml

It is impossible to set `coreFraction` field to `0` in yandex console, but `YandexClusterConfiguration` accepts it. PR fixes this behaviour.
Fix #3551 
Users can't set `0` value for `coreFraction` field in `YandexClusterConfiguration`
```changes
type: fix
summary: Forbid zero value for coreFraction field in YandexClusterConfiguration
```

[cloud-provider-yandex] Forbid zero value for coreFraction field in YandexClusterConfiguration

---

modules/490-virtualization/templates/kubevirt.yaml

Set evictionStrategy: LiveMigrate by default
kubectl drain node should gracefully live-migrate the virtual machine
```changes
type: fix
summary: Set evictionStrategy: LiveMigrate by default
```

[virtualization] Set evictionStrategy: LiveMigrate by default

---

modules/011-flow-schema/docs/FAQ.md
modules/011-flow-schema/docs/FAQ_RU.md

Minor markup updates.
```changes
section: flow-schema
type: chore
summary: Minor markup updates.
```

[docs][flow-schema] Update markup

---

docs/documentation/_data/sidebars/main.yml

Fix the sidebar menu.
```changes
section: docs
type: chore
summary: Fix the sidebar menu.
```

[docs] Fix the sidebar menu

---

modules/040-control-plane-manager/docs/FAQ.md
modules/040-control-plane-manager/docs/FAQ_RU.md

Fix instruction about how to add master nodes to a cloud cluster.
```changes
section: docs
type: fix
summary: Fix instruction about how to add master nodes to a cloud cluster.
```

[docs] fix DH_EDITION set lowercase

---

modules/402-ingress-nginx/hooks/order_certificates.go

Fix golang-ci lint
fix for github actions
golang-ci lint success
```changes
type: chore
summary: fix linting
```

[ingress-nginx] fix lint

---

modules/460-log-shipper/monitoring/prometheus-rules/log-shipper-agent.yaml

Fix alert clause
```changes
type: fix
summary: Fix the exclude clause for unschedulable nodes in the RateLimit alert.
```

[log-shipper] Fix ratelimit alert

---

candi/cloud-providers/yandex/docs/LAYOUTS.md
candi/cloud-providers/yandex/docs/LAYOUTS_RU.md

A little more details - how to create NATInstance with a dynamic IP address
```changes
section: docs
type: chore
summary: Add docs about the dynamic IP address for the `withNATInstance` Yandex layout.
```

[docs] Yandex withNATInstance

---

ee/modules/110-istio/monitoring/prometheus-rules/versions.yaml

D8IstioDeprecatedIstioVersionInstalled alert description clarification.
It is convenient to have instructions in alert.
```changes
section: istio
type: fix
summary: D8IstioDeprecatedIstioVersionInstalled alert description clarification.
```

[istio] D8IstioDeprecatedIstioVersionInstalled alert description fix

---

candi/openapi/doc-ru-node_group.yaml
candi/openapi/node_group.yaml

```changes
type: fix
summary: Fixed documentation for the case if minPerZone is 0.
```

[docs] fixed node group if minPerZone = 0

---

modules/500-dashboard/images/dashboard/Dockerfile

Update of dashboard module to 2.7.0
Fix #3440 
Updated module
```changes
type: chore
summary: Update of dashboard module to 2.7.0
```

[dashboard] update to 2.7.0

---

modules/460-log-shipper/monitoring/prometheus-rules/log-shipper-agent.yaml

Do not fire alerts for standalone vector instances (that are not part of the log-shipper module).
```changes
type: fix
summary: Add job label selector to alerts query.
```

[log-shipper] Add job label selector to alerts query

---

candi/bashible/bundles/centos/all/001_install_mandatory_selinux_policies.sh.tpl
ee/candi/bashible/bundles/alteros/all/001_install_mandatory_selinux_policies.sh.tpl
ee/candi/bashible/bundles/redos/all/001_install_mandatory_selinux_policies.sh.tpl

Added selinux policies for cilium.
In redhat-based distros selinux policies disable running of cilium bpftool.
```changes
section: candi
type: fix
summary: add selinux policies for cilium
```

[candi] add selinux policies for cilium

---

modules/005-external-module-manager/hooks/handle_sources.go

Fix error decode if file with checksums is empty
Also skip checksum file reading if we have no ExternalModuleSource configured
Hook can fail with `EOF` error if checksum file is empty
```changes
type: fix 
summary: Fix decoding empty file with module checksums
```

[external-module-manager] Fix EOF json.Decode error

---

helm_lib/README.md

Update `helm_lib` readme
Add information about backport fixes.
```changes
section: lib_helm
type: chore
summary: Update readme.
```

[helm_lib] Update readme

---

ee/modules/502-delivery/docs/FAQ.md
ee/modules/502-delivery/docs/FAQ_RU.md

Add FAQ section with admin password reset instruction.
We need to add instruction about reset admin password.
```changes
type: chore
summary: Add FAQ section with the admin password reset instruction.
```

[delivery] Add FAQ section with admin password reset instruction

---

modules/041-linstor/docs/FAQ.md
modules/041-linstor/docs/FAQ_RU.md
modules/041-linstor/monitoring/prometheus-rules/drbd-devices.yaml
modules/041-linstor/monitoring/prometheus-rules/linstor-controller.yaml
modules/041-linstor/monitoring/prometheus-rules/linstor-csi-controller.yaml
modules/041-linstor/monitoring/prometheus-rules/linstor-csi-node.yaml
modules/041-linstor/monitoring/prometheus-rules/linstor-node.yaml

Update alerts and labels
Simplify label selectors and update course of action in case of failures
```changes
type: chore
summary: Update alerts and labels.
```

[linstor] Update alerts and labels

---

.github/CODEOWNERS

Add @name212 to helm_lib/* codeowners
```changes
section: ci
type: chore
summary: Add @name212 to helm_lib/* codeowners
```

[ci] Add @name212 to helm_lib/* codeowners

---

ee/modules/502-delivery/docs/FAQ.md
ee/modules/502-delivery/docs/FAQ_RU.md

Fix `How to reset admin password instruction`.
Need to add replacing namespace.
```changes
type: fix 
summary: Fix How to reset admin password instruction
```

[delivery] Fix How to reset admin password instruction

---

ee/candi/cloud-providers/vsphere/openapi/cluster_configuration.yaml
ee/candi/cloud-providers/vsphere/openapi/doc-ru-cluster_configuration.yaml
ee/candi/cloud-providers/vsphere/openapi/doc-ru-instance_class.yaml
ee/candi/cloud-providers/vsphere/openapi/instance_class.yaml

Clarifying implicit behavior of VsphereInstanceClass parameters.
Clarifies the doc.
```changes
type: chore
summary: Clarified implicit defaults in VsphereInstanceClass documentation
```

[cloud-provider-vsphere] Clarify instance class doc

---

werf_cleanup.yaml

Sets 3 days for keeping branches other than release branches.
```changes
section: chore
type: chore
summary: Update cleanup policy.
```

[ci] Update cleanup policy

---

modules/460-log-shipper/monitoring/grafana-dashboards/applications/vector.json

* Add status codes
* Add errors
* select only log-shipper metrics
```changes
type: feature
summary: Add status codes and errors to the dashboard.
```

[log-shipper] Add status codes and errors to dashboard

---

ee/modules/110-istio/docs/EXAMPLES_RU.md

```changes
section: istio
type: chore
summary: Documentation fixes.
```

[docs][istio] Documentation fix crd version ru 

---

modules/500-operator-trivy/templates/deployment.yaml

Disabled infra assessment, since it has bugs that spawn ~1000 Jobs when something is wrong with a Node.
operator-trivy may sometimes spawn lots of Jobs for an infra report.
Lots of Jobs are not spawned.
```changes
type: fix
summary: Disabled infra assessment jobs.
```

[operator-trivy] Disable infra assessment

---

docs/documentation/_data/sidebars/main.yml
modules/031-ceph-csi/docs/FAQ.md
modules/031-ceph-csi/docs/FAQ_RU.md

```changes
type: fix 
summary: Added info about how to show mapped RBD volume into a FAQ.
```

[ceph-csi] docs added rbd showmapped in FAQ

---

ee/modules/650-runtime-audit-engine/docs/EXAMPLES.md
ee/modules/650-runtime-audit-engine/docs/EXAMPLES_RU.md
ee/modules/650-runtime-audit-engine/docs/FAQ.md
ee/modules/650-runtime-audit-engine/docs/FAQ_RU.md
ee/modules/650-runtime-audit-engine/docs/README.md
ee/modules/650-runtime-audit-engine/docs/README_RU.md

Just small fixes in faq, examples and readme docs.
To improve user experience. Some examples don't work at all.
```
Error: /etc/falco/rules.d/ownership-permissions.yaml: Invalid
1 Errors:
In rules content: (/etc/falco/rules.d/ownership-permissions.yaml:0:0)
rule 'Detect Ownership Change': (/etc/falco/rules.d/ownership-permissions.yaml:0:2)
------
- condition: 'spawned_process and proc.name in (chmod, chown) and proc.args cont...
^
------
LOAD_ERR_VALIDATE (Error validating rule/macro/list/exception objects): Undefined macro 'spawned_process' used in filter.
```
```changes
type: fix
summary: Docs improvements.
```

[runtime-audit-engine] Docs improvements

---

modules/500-openvpn/openapi/config-values.yaml
modules/500-openvpn/openapi/values.yaml

Reduce matrix test cases from 32768 to 1024.
```changes
type: chore
summary: reduce test cases for openvpn module
```

[openvpn] reduce test cases

---

modules/007-registrypackages/images/containerd-centos/werf.inc.yaml

Update of selinux-policy and selinux-policy-targeted packages for Centos 9
Now we have problems with packages 38.1.4-1.el9, it's not matches to cockpit-ws packages requirements
Version 38.1.8-el9 will work fine
```changes
section: candi
type: fix
summary: Update of selinux-policy and selinux-policy-targeted packages for Centos 9.
```

[candi] fixes in centos 9 bootstrap

---

docs/documentation/pages/DECKHOUSE-FAQ.md
docs/documentation/pages/DECKHOUSE-FAQ_RU.md

Added some info about using proxy server.
```changes
section: docs
type: chore
summary: Added some info about using proxy server.
```

[docs] Using proxy

---

ee/modules/110-istio/templates/ingress-gateway-controller/registry-secret.yaml

Add registry secret for d8-ingress-istio namespace
Image availability exporter reports about unavailable `ingress-gateway-controller` image.
```changes
section: istio
type: fix
summary: Add registry secret for d8-ingress-istio namespace
```

[istio] Add registry secret for d8-ingress-istio namespace

---

modules/600-namespace-configurator/docs/EXAMPLES.md
modules/600-namespace-configurator/docs/EXAMPLES_RU.md

Change examples "includeNames" in namespace-configurator
```changes
section: docs
type: chore
summary: Change examples "includeNames" in namespace-configurator.
```

[docks] change examples in namespace-configurator

---

ee/modules/650-runtime-audit-engine/docs/FAQ.md
ee/modules/650-runtime-audit-engine/docs/FAQ_RU.md

Add absent escape backslash in manifest.
```changes
type: chore
summary: Fix typo in documentation.
```

[docs][runtime-audit-engine] Fix typo

---

tools/cve/release.sh

Fix in daily CVE tests, that was broken after move to sha256 images pull
Daily CVE tests was broken since move to sha256
CVE daily tests works fine
```changes
section: e2e
type: fix
summary: Fix in CVE daily tests
```

[e2e] Fix in daily CVE tests

---

modules/040-control-plane-manager/templates/_authn_webhook_config.tpl

revert wrong removing certificate b64 encoding
```changes
section: candi
type: fix
summary: fix auhtn webhook config generation
```

[control-plane-manager] Update _authn_webhook_config.tpl

---

modules/002-deckhouse/openapi/doc-ru-config-values.yaml

Fxi doc translation into Russian
```changes
type: fix
summary: Fixed translation in authentication settings of update notification webhook.
```

[deckhouse] Doc: fix module settings translation

---

modules/490-virtualization/hooks/vm_handler.go

Support other cloud-init sources
In VirtualMachineSpec user can specify `secretRef`, `userDataBase64`, `networkDataSecretRef`, `networkDataBase64` and `networkData`.
Currently it wasn't working.
```changes
type: fix
summary: Support other cloud-init sources
```

[virtualization] Support other cloud-init sources

---

modules/460-log-shipper/crds/cluster-log-destination.yaml
modules/460-log-shipper/crds/doc-ru-cluster-log-destination.yaml

Fixed a typo in the buffer parameter.
Ref: https://github.com/deckhouse/deckhouse/pull/4095/
```changes
type: chore
summary: Fixed a typo in the buffer parameter.
```

[log-shipper] Fix typo in spec

---

candi/bashible/bashible.sh.tpl

Fix in bashible template.
In bash v5.2 logic changed and $(<file) directive cause error if file not exists. (looks like it was changed [here](https://github.com/bminor/bash/blob/master/CHANGES#L299))
Working bashible even if file with node checksum ($CONFIGURATION_CHECKSUM_FILE) do not exist.
```changes
section: candi
type: fix
summary: Fix in bashible template.
```

[candi] fix in bashible.sh.tpl

---

ee/fe/modules/340-monitoring-applications/applications/rabbitmq/grafana-dashboards/rabbitmq.json

fixes rabbitmq dashboard using job rabbitmq
fixes dashboard when using custom label
```changes
type: chore
summary: Fixes rabbitmq dashboard using job rabbitmq.
```

[monitoring-applications] fixes rabbitmq dashboard using job rabbitmq

---

candi/bashible/bundles/altlinux/all/034_install_kubelet_and_his_friends.sh.tpl

Fix altlinux bundle after apply PR #3318
Deploy nodes with altlinux not working
```changes
section: candi
type: fix
summary: Fix altlinux bundle after apply PR #3318
```

[candi] Fix altlinux bundle

---

modules/015-admission-policy-engine/docs/README.md

Fix documentation
YAML example is broken
```changes
type: chore
summary: Fix documentation example.
```

[admission-policy-engine] fix mutation documentation

---

modules/031-ceph-csi/hooks/get_crds.go
modules/031-ceph-csi/templates/cephfs/storage-classes.yaml
modules/031-ceph-csi/templates/rbd/storage-classes.yaml

volumeBindingMode changed from default to WaitForFirstConsumer
```changes
type: chore
summary: volumeBindingMode changed from default to WaitForFirstConsumer
```

[ceph-csi] change default volumeBindingMode

---

.github/CODEOWNERS

We've desided to add teamleads to review modules api.
```changes
```

add teamleads to review modules api

---

.github/ci_templates/build.yml
.github/ci_templates/e2e_tests.yml
.github/scripts/js/constants.js
.github/workflow_templates/e2e.abort.multi.yml
.github/workflow_templates/e2e.multi.yml
.github/workflows/build-and-test_dev.yml
.github/workflows/build-and-test_pre-release.yml
.github/workflows/build-and-test_release.yml
.github/workflows/e2e-abort-eks.yml
.github/workflows/e2e-eks.yml
testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml
testing/cloud_layouts/EKS/WithoutNAT/infra.tf.tpl
testing/cloud_layouts/EKS/WithoutNAT/resources.yaml
testing/cloud_layouts/script.d/wait_cluster_ready/info_script_eks.sh
testing/cloud_layouts/script.d/wait_cluster_ready/test_script_eks.sh
testing/cloud_layouts/script_eks.sh
werf.yaml

Added EKS daily and manual tests
We haven't get check for managed cluster installation
Fix #3323 
Working E2E EKS tests
```changes
section: e2e
type: feature
summary: Added E2E EKS tests
```

[e2e] EKS tests

---

docs/site/_includes/getting_started/global/partials/DNS_OPTIONS.liquid
docs/site/_includes/getting_started/global/partials/INSTALL_CONFIG.liquid
modules/460-log-shipper/docs/README.md

Delete non-ASCII symbols from the English docs.

[docs] Delete non-ASCII symbols from the English docs

---

modules/490-virtualization/templates/kubevirt.yaml

Enable snapshot feature in virtualization module.
Without this, the VM snapshot feature doesn't work.
It isn't necessary for release but is important for virtualization RND.
Enabled snapshot support in virtualization module
```changes
type: feature
summary: Enable snapshot feature in the `virtualization` module.
```

[virtualization] enable snapshot feature

---

.github/CODEOWNERS

[chore] Update the CODEOWNERS file

---

.github/workflows/e2e-eks.yml

[ci]  Regenerate workflow

---

docs/documentation/_data/supported_versions.yml

Update the OS support list.
Minor fix that can be skipped in the patch release.
```changes
section: docs
type: chore
summary: Update the OS support list.
```

[doc] Update OS support list

---

go.mod
go.sum
modules/003-deckhouse-config/images/deckhouse-config-webhook/go.mod
modules/003-deckhouse-config/images/deckhouse-config-webhook/go.sum

Update gophercloud dependency.
The `discover_volume_types.go` hook failed with the `Resource not found` error.
The `discover_volume_types.go` hook failed with the `Resource not found` error.
```changes
type: chore
summary: Update gophercloud dependency.
```

[global] Update gophercloud dependency

---

modules/041-linstor/templates/linstor-controller/linstorcontroller.yaml

Adjust timers and timeouts for more stability in non-stable networks
In case of network problems, low timers can cause volumes out of sync
More stable linstor work
```changes
type: chore
summary: Adjust timers and timeouts for more stability in non-stable networks
```

[linstor] Adjust timers and timeouts for more stability work in non-stable networks

---

.github/workflow_templates/check_pr_milestone.yml
.github/workflow_templates/validation.yml
.github/workflows/check_pr_milestone.yml
.github/workflows/validation.yml

This PR fixes behaviour in CI for milestone/demilestone actions
Now we need to manually restart milestone job if it fails. This PR automates the behavior to restart the workflow if the milestone section is changed.
After this PR merge - in new PRs we won't need to re-run the milestone check job if it fails.
```changes
section: ci
type: chore
summary: Update milestone check job if milestone changes in PR.
```

[CI] Update milestone check job if milestone changes in PR

---

deckhouse-controller/cmd/deckhouse-controller/main.go
go.mod
go.sum
go_lib/deckhouse-config/module-manager/basic.go
modules/003-deckhouse-config/images/deckhouse-config-webhook/go.mod
modules/003-deckhouse-config/images/deckhouse-config-webhook/go.sum

Bump addon-operator's version with new improvements and optimizations
```changes
type: chore
summary: Bump addon-operator version
```

[chore] Update addon-operator

---

testing/cloud_layouts/script.sh

Removed some debug in e2e tests
It solves problem with static e2e test
Working e2e static tests
```changes
section: e2e
type: fix
summary: Removed some debug in e2e tests
```

[e2e] fix for e2e static tests

---

docs/site/pages/guides/PRODUCTION_RU.md

[chore] Fix markup

---

global-hooks/discovery/kubernetes_version.go
global-hooks/discovery/kubernetes_version_test.go

Fix Kubernetes version hook for DigitalOcean.
We need it to support deployment for managed DigitalOcean Kubernetes clusters.
```changes
section: discovery
type: fix
summary: Fix Kubernetes version hook for DigitalOcean
```

[discovery] Fix Kubernetes version hook for DigitalOcean

---

docs/documentation/pages/DECKHOUSE-FAQ.md
docs/documentation/pages/DECKHOUSE-FAQ_RU.md

Change tools downloading links from main branch to placeholder
Sometimes from version to version tool scripts are changing, so scripts from main branch are not suitable for older versions of deckhouse
```changes
section: docs
type: fix
summary: Change tools downloading links from main branch to placeholder.
```

[docs] Change tools downloading links from main branch to placeholder

---

candi/bashible/common-steps/all/000_add_system_proxy.sh.tpl

PR configures `/etc/systemd/system/containerd.service.d/proxy-environment.conf` with proxy config for installations with containerd CRI.
When we set proxy settings, bashible configure systemd to use it, by setting `/etc/systemd/system.conf.d/proxy-default-environment.conf` file, which sets `DefaultEnvironment` variables for systemd units. But sometimes, on older distros like Centos 7, this settings does not work and we should override service `Environment` in systemd unit. 
```changes
section: candi
type: fix
summary: override proxy settings for containerd unit.
```

[candi] override proxy settings for containerd unit

---

modules/500-openvpn/images/ovpn-admin/Dockerfile
modules/500-openvpn/templates/openvpn/statefulset.yaml

Fix update user list in HA mode.
```changes
type: fix
summary: Fix update user list in HA mode.
impact: openvpn will be restarted and connections will be terminated
```

[openvpn] fix update user list in HA mode

---

.github/workflow_templates/build-and-test_release.yml
.github/workflows/build-and-test_release.yml

Fix site workflow.
```changes
section: ci
type: chore
summary: Fix site workflow.
```

[ci] Fix site workflow

---

.github/ci_templates/web.yml
.github/workflow_templates/build-and-test_dev.yml
.github/workflow_templates/build-and-test_pre-release.yml
.github/workflow_templates/build-and-test_release.yml
.github/workflows/build-and-test_dev.yml
.github/workflows/build-and-test_pre-release.yml
.github/workflows/build-and-test_release.yml

Fix site links test workflow.
```changes
section: ci
type: chore
summary: Fix site links test workflow.
```

[ci] Fix links test workflow

---

docs/documentation/_data/supported_versions.yml
docs/documentation/_data/version_map_addition.yml
docs/documentation/_includes/SUPPORTED_VERSIONS.liquid

Update the supported OS list on the site.
```changes
section: docs
type: chore
summary: Update the supported OS list on the site.
```

[docs] Update the supported OS list on the site

---

candi/bashible/bashible.sh.tpl

Code cleanup in `bashible.sh.tpl`.
```changes
section: candi
type:chore
summary:  code cleanup in bashible.sh.tpl
```

[candi] code cleanup in bashible.sh.tpl

---

deckhouse-controller/cmd/deckhouse-controller/main.go
go.mod
go.sum

Reverts deckhouse/deckhouse#4595

Revert "[deckhouse-controller] Add autogomaxprocs"

---

.github/scripts/js/constants.js
.github/workflow_templates/e2e.abort.multi.yml
.github/workflow_templates/e2e.multi.yml
.github/workflows/e2e-abort-aws.yml
.github/workflows/e2e-abort-azure.yml
.github/workflows/e2e-abort-eks.yml
.github/workflows/e2e-abort-gcp.yml
.github/workflows/e2e-abort-openstack.yml
.github/workflows/e2e-abort-static.yml
.github/workflows/e2e-abort-vsphere.yml
.github/workflows/e2e-abort-yandex-cloud.yml
.github/workflows/e2e-aws.yml
.github/workflows/e2e-azure.yml
.github/workflows/e2e-eks.yml
.github/workflows/e2e-gcp.yml
.github/workflows/e2e-openstack.yml
.github/workflows/e2e-static.yml
.github/workflows/e2e-vsphere.yml
.github/workflows/e2e-yandex-cloud.yml

For further 1.27 e2e test we have to update CI before
```changes
section: ci
type: feature
summary: Add 1.27 kubernetes e2e tests
```

[ci] Add 1.27 e2e pipelines

---

dhctl/pkg/operations/bootstrap.go

Before bootstrap dhctl checks whether some relevant binaries/utils are present in the system.
Needed for providing a more transparent bootstrap process.
Related to https://github.com/deckhouse/deckhouse/issues/4576
Dhctl should abort the bootstrap process in case some dependencies are missing
```changes
section: dhctl
type: feature
summary: Introduces dependency verification on bootstrap.
```

[dhctl] add checks for bootstrap dependencies

---

candi/bashible/detect_bundle.sh

Fix a error in script rendering.
Nodes are not bootstrapped in CE release.
```changes
section: candi
type: fix
summary: fix error in detect_bundle.sh
impact: In CE release new nodes are not bootstrapped.
```

[candi] fix error in detect_bundle.sh

---

candi/bashible/bashible.sh.tpl

Bashible script template has been updated in terms of creating node events. An event manifest uses the node hostname for both .name and .uid fields.
Close #4609
If .uid field in the event manifest is set to a real node uid instead of the node hostname, such an event doesn't appear in `kubectl describe node` listing for kubectl versions 1.23.x.
The events created by bashible are correctly listed in the "Events" section of `kubectl describe node` output.
```changes
type: fix
summary: Events create by bashible get connected to the relevant node objects
```

[bashible] Error events from bashible are not connected to node object

---

docs/documentation/_data/sidebars/main.yml
ee/modules/500-operator-trivy/docs/FAQ.md
ee/modules/500-operator-trivy/docs/FAQ_RU.md

This PR adds a FAQ for the trivy operator module
It is not clear from the CIS grafana dashboard how to view resources that have not passed CIS compliance checks
Added FAQ to doc
```changes
type: chore
summary: Add a FAQ.
```

[operator-trivy] Add FAQ for module doc

---

modules/340-extended-monitoring/images/extended-monitoring-exporter/src/extended-monitoring.py

Monitoring enabled for all controllers by default if not disabled explicitly 
Fix after refctoring
https://github.com/deckhouse/deckhouse/pull/4356
```changes
type: fix
summary: Fix enabled condition for controllers after refactoring.
```

[extended-monitoring] Fix enabled condition for controllers after refactoring

---

modules/140-user-authz/crds/authorizationrule.yaml
modules/140-user-authz/crds/clusterauthorizationrule.yaml
modules/140-user-authz/crds/doc-ru-authorizationrule.yaml
modules/140-user-authz/crds/doc-ru-clusterauthorizationrule.yaml

Clarify the `AuthorizationRule` description and the `ClusterAuthorizationRule` description.
```changes
type: chore
summary: Clarify the `AuthorizationRule` description and the `ClusterAuthorizationRule` description.
```

[user-authz] Clarify AuthorizationRule and ClusterAuthorizationRule.

---

docs/documentation/_includes/module-bundle.liquid
docs/documentation/_includes/module-enable-snippet.liquid
docs/documentation/_includes/module-enable.liquid
docs/documentation/_includes/module-settings.liquid
docs/documentation/_includes/search.liquid
docs/documentation/_plugins/custom_hooks.rb
docs/documentation/search-index.json

Update info about enabling a module during the D8 installing
```changes
section: docs
type: chore
summary: Update search index. Update info about enabling a module.
```

[docs][search] Update info about enabling a module during the D8 installing

---

modules/040-node-manager/docs/FAQ.md
modules/040-node-manager/docs/FAQ_RU.md

Clarified debugging the `bashible` service on nodes.
```changes
section: docs
type: chore
summary: Clarified debugging the `bashible` service on nodes.
```

[node-manager] Doc updates

---

docs/documentation/search-index.json

Fix the search index.
```changes
section: docs
type: chore
summary: Fix the search index.
```

[docs] Fix search index

---

.github/workflow_templates/trivy-db-schedule.yml
.github/workflows/trivy-db-schedule.yml
ee/modules/500-operator-trivy/templates/configmap.yaml
tools/release/d8-pull.sh

Changed trivy-db path reference so that we won't have to check every possible path combination.
It is quite hard to manage trivy-db path in private repositories. Let's streamline usage in d8-pull/d8-push and reference to db image in Helm.
trivy-db relative path is used everywhere.
```changes
type: fix
summary: Streamline reference to trivy-db image
```

[operator-trivy] Changed trivy-db path to streamline registry path references

---

modules/300-prometheus/hooks/disk_metrics.go

Fixed d8_prometheus_fs metrics
```changes
type: fix
summary: Fixed d8_prometheus_fs metrics
```

[prometheus] Fix d8_prometheus_fs metrics

---

testing/cloud_layouts/script.sh

The script for bootstrapping  has been updated so that the nodes stay isolated across reboots.
Before these changes nodes would get access to the Internet after a reboot (due to the mix of wrong directives and using DHCP)
The nodes stay air-gapped after a reboot.
```changes
type: chore
summary: Update the script so that the nodes stay isolated from the Internet across reboots
```

[e2e] Test if redos worker has selinux enabled

---

docs/documentation/_data/i18n.yml
docs/documentation/_includes/module-settings.liquid
docs/documentation/_includes/revision_comparison_detail_table.liquid
docs/documentation/_plugins/openapi.rb
docs/documentation/generate_cluster_configuration.sh
docs/documentation/modules_generate_cr.sh
docs/documentation/modules_list.sh
docs/documentation/pages/DECKHOUSE_CONFIGURE_GLOBAL.md
docs/documentation/pages/DECKHOUSE_CONFIGURE_GLOBAL_RU.md
docs/documentation/werf.yaml
docs/site/css/components/common/_tooltip.scss

Update the [Deckhouse Platform editions comparison](https://deckhouse.io/documentation/v1/revision-comparison.html) table - 
automatically mark parameters that are not available in a revision (e.g. limitNamespaces).
```changes
section: docs
type: chore
summary: Automatically mark parameters that are not available in a revision in the the [Deckhouse Platform editions comparison](https://deckhouse.io/documentation/v1/revision-comparison.html) table. 
```

[docs] Update comparison table

---

.github/CODEOWNERS

[chore] Update CODEOWNERS

---

modules/040-control-plane-manager/requirements/check.go

```changes
type: fix 
summary: typo in the error text corrected
```

[docs] typo in the error text corrected

---

docs/documentation/_data/i18n.yml
modules/140-user-authz/docs/README.md
modules/140-user-authz/docs/README_RU.md
tools/authz_generate_rules_for_roles/readme-placeholder.tpl

Update the readme markup.
```changes
type: chore
summary: Update the module readme markup.
```

[user-authz] Update the readme markup

---

ee/modules/500-operator-trivy/monitoring/grafana-dashboards/security/trivy.json

Update Trivy dashboard
Improvement of Trivy dashboard
```changes
type: feature
summary: improvement of Trivy dashboard
```

[operator-trivy] Update Trivy dashboard

---

modules/140-user-authz/docs/README.md
modules/140-user-authz/docs/README_RU.md
modules/140-user-authz/templates/cluster-roles.yaml

User can't delete pods from `Lens` because of the error:
```text
pods "pod-name" is forbidden: User "user-name" cannot create resource "pods/eviction" in API group "" in the namespace "namespace-name"
```
this PR fixes this error
Allow users to delete pods from Lens
```changes
type: fix
summary: Fix access for `PrivilegedUser` role.
```

[user-authz] Fix access for `PrivilegedUser` role

---

candi/bashible/common-steps/node-group/069_start_kubelet.sh.tpl

Waiting till the file /var/lib/kubelet/pki/kubelet-client-current.pem generated
Before using kubectl, we need to wait for the generation of the kubelet client certificate.
Close #4854
```changes
section: candi
type: fix
summary: Add waiting for kubelet client certificate generation when a node bootstrap.
impact: low
```

[candi] add waiting for kubelet client certificate generation when a node bootstrap

---

modules/002-deckhouse/crds/doc-ru-module.yaml
modules/002-deckhouse/crds/module.yaml

Update the Module CRD.
```changes
section: docs
type: chore
summary: Update the Module CRD.
```

[deckhouse] Update the Module CRD

---

modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/main.go

Resolve symbolic links before getting file system statistics from the `kubelet` root directory and the container runtime root directory in `kubelet-eviction-thresholds-exporter`.
We need it for the correct generation of metrics.
```changes
type: fix
summary: Resolve symbolic links before getting file system statistics in kubelet-eviction-thresholds-exporter.
```

[monitoring-kubernetes] resolve symbolic links

---

modules/300-prometheus/docs/FAQ.md
modules/300-prometheus/docs/FAQ_RU.md

fix example in alertmanager doc
Incorrect example in the documentation. #4851  
```changes
section: alertmanager
type: fix
summary: Fix the example in the alertmanager doc.
```

 [alertmanager] fix example in alertmanager doc (#4851)

---

docs/documentation/_plugins/openapi.rb

Fix data generation for the comparison table in the documentation.
```changes
section: docs
type: chore
summary: Fix data generation for the comparison table in the documentation.
```

[doc] Fix data generation for the comparison table

---

deckhouse-controller/pkg/helpers/change_registry/change_registry.go
deckhouse-controller/pkg/helpers/change_registry/change_registry_test.go
go.mod

Add unit tests and some minor changes from comments after #4925 merge
```changes
type: fix
summary: Add unit tests for change-registry.
```

[deckhouse-controller] Add unit tests for change-registry

---

tools/release/d8-pull.sh

Adding config with auth for docker run command
```changes
section: tools
type: fix
summary: Fix auth for docker run in `d8-pull.sh`
```

[tools] Fix auth for docker run in `d8-pull.sh`

---

candi/bashible/bashible.sh.tpl

Add debug info to the bashible steps for all run type
Additional information about the error has occurred will help in investigating the causes.
detailed information about the issues
```changes
type: feature
summary: Add debug info to the bashible steps for all run type
```

[bashible] add debug info (#4128)

---

tools/release/d8-pull.sh
tools/release/d8-push.sh

Add images tagging for digest images (it is necessary for quay registry) and fix docker save command (add docker pull) 
```changes
section: tools
type: chore
summary: [tools] Add images tagging and fix docker save command.
```

[tools] Add images tagging and fix docker save command

---

docs/documentation/_includes/SUPPORTED_VERSIONS.liquid

Update the supported container registry list.
```changes
section: docs
type: chore
summary: Update the supported container registry list.
```

[docs] Update supported container registry list

---

.github/dependabot.yml
.github/workflow_templates/update-dependabot-pr.yml
.github/workflows/update-dependabot-pr.yml

```changes
section: ci
type: fix
summary: Fix condition for dependabot PRs
```

[ci] Fix condition for dependabot PRs

---

.github/workflow_templates/update-dependabot-pr.yml
.github/workflows/update-dependabot-pr.yml

```changes
section: ci
type: fix
impact: Update dependabot changelog comment
```

[ci] Update dependabot changelog comment

---

.github/actions/milestone-changelog/action.yml

```changes
section: ci
type: feature
summary: Add dependabot section to changelogs
```

[ci] Add dependabot changelog section

---

docs/site/_data/modal.yml

[site] Update the request license form.

[site] Update the request license form

---

docs/documentation/_data/supported_versions.yml
docs/documentation/_includes/SUPPORTED_VERSIONS.liquid

Add info about quay container registry support
```changes
section: docs
type: chore
summary: Add info about quay container registry support.
```

[docs] Add info about quay support

---

modules/040-control-plane-manager/docs/FAQ.md
modules/040-control-plane-manager/docs/FAQ_RU.md

Add an example of an object restoration from the etcd snapshot.
```changes
section: docs
type: chore
summary: Add an example of an object restoration from the etcd snapshot.
```

[docs] Add an example of an object restoration from the etcd snapshot

---

docs/site/_includes/getting_started/bm/partials/config.yml.ce.inc
docs/site/_includes/getting_started/bm/partials/config.yml.ee.inc

Use the [cni-cillium](https://deckhouse.io/documentation/v1/modules/021-cni-cilium/) module and enable the [publishAPI](https://deckhouse.io/documentation/v1/modules/150-user-authn/configuration.html#parameters-publishapi) parameter in the [getting started for a bare metal cluster](https://deckhouse.io/gs/bm/step2.html).
```changes
section: docs
type: chore
summary: Use the [cni-cillium](https://deckhouse.io/documentation/v1/modules/021-cni-cilium/) module and enable the [publishAPI](https://deckhouse.io/documentation/v1/modules/150-user-authn/configuration.html#parameters-publishapi) parameter in the [getting started for a bare metal cluster](https://deckhouse.io/gs/bm/step2.html).
```

[docs] Getting started bare metal updates

---

docs/site/_includes/getting_started/openstack/partials/config.yml.standard.ee.inc

Add reference to [tenantName](https://deckhouse.io/documentation/v1/modules/030-cloud-provider-openstack/cluster_configuration.html#openstackclusterconfiguration-provider-tenantname) in the Getting Started.

[getting-started][openstack] Add tenantName reference

---

docs/site/_data/modal.yml
docs/site/_includes/getting_started/global/EE_ACCESS.md
docs/site/_includes/getting_started/global/EE_ACCESS_RU.md
docs/site/css/docs.scss
docs/site/pages/enterprise_edition.html
docs/site/pages/enterprise_edition_ru.html

[site] Fix content in the license form

---

helm_lib/Chart.lock
helm_lib/Chart.yaml
helm_lib/charts/deckhouse_lib_helm/Chart.yaml
helm_lib/charts/deckhouse_lib_helm/README.md
helm_lib/charts/deckhouse_lib_helm/templates/_module_documentation_uri.tpl

Update lib_helm to the latest version.
Adds a new helm definition helm_lib_module_documentation_uri
```changes
section: lib_heml
type: chore
summary: update lib_helm chart
```

[lib_helm] update chart to 1.5.1

---

docs/documentation/pages/DECKHOUSE-FAQ.md
docs/documentation/pages/DECKHOUSE-FAQ_RU.md

Error in the example of using `deckhouse-controller helper change-registry`.
```changes
section: docs
type: fix 
summary: Fix example of uisind `deckhouse-controller helper helper change-registry`.
```

[documentation] fixed example helper change-registry

---

docs/site/_data/revision_comparison.yml
docs/site/_includes/getting_started/global/partials/NOTICES.liquid

Add info about air-gapped environment: the feature is available in Deckhouse EE only.
```changes
section: docs
type: chore
summary: Add info about air-gapped environment.
```

[site] Add info about air-gapped environment

---

modules/040-node-manager/templates/node-group/_bootstrap_script.tpl

Fixes the missing part of https://github.com/deckhouse/deckhouse/pull/4188
```changes
section: candi
type: fix
summary: fixes install in air-gapped envs
```

[candi] fixed bootstrap in air-gapped envs

---

modules/150-user-authn/templates/kubeconfig-generator/certificate.yaml

Fix kubeconfig certificate generation.
There is a warning about the HTTPS certificate when using the Kubeconfig generator.
```changes
type: fix
summary: Fix kubeconfig certificate generation.
```

[user-authn] Fix kubeconfig certificate generation

---

ee/modules/650-runtime-audit-engine/images/falco/Dockerfile
ee/modules/650-runtime-audit-engine/images/rules-loader/Dockerfile

Bump the version
Fix the bug https://github.com/falcosecurity/falco/pull/2653
It does not affect current installations, but affects adding new sources.
```changes
type: chore
summary: Update falco to 0.35.1 to fix an issue with multiple active event sources
```

[runtime-audit-engine] Update falco to 0.35.1

---

docs/site/pages/regulations_ru.html

Update link to the regulation rules on the site.

[docs] Update link to the regulation rules

---

docs/site/_includes/request_access_form.html
docs/site/css/docs.scss
docs/site/js/customscripts.js

Add preferred contact method field in license request form

---

.github/ci_templates/web.yml
.github/workflow_templates/build-and-test_pre-release.yml
.github/workflow_templates/build-and-test_release.yml
.github/workflows/build-and-test_pre-release.yml
.github/workflows/build-and-test_release.yml

Deploy documentation for the release branch and the main branch also on the new hosting.

[ci] Add deploy documentation to the new DC

---

.github/ci_templates/web.yml
.github/scripts/js/constants.js
.github/workflow_templates/deploy-web.multi.yml
.github/workflows/deploy-web-preproduction.yml

Add GitHub workflow for deploying the site to the new DC by the label 'deploy/web/preprod'.

[ci] Add WF for deploying site to the new DC

---

.github/labeler.yml

Update rules for autolabeler.
Ref: #5368
```changes
section: ci
type: chore
summary: Update rules for autolabeler.
```

[ci] Update rules for autolabeler

---

docs/documentation/.helm/templates/20-ingress.yaml
docs/documentation/.helm/values.yaml
docs/site/.helm/templates/20-ingress.yaml
docs/site/.helm/values.yaml

Update deploy templates for the site.
Need: #5393

[site] Update deploy templates

---

.github/workflow_templates/deploy-web.multi.yml
.github/workflows/deploy-web-preproduction.yml
.github/workflows/deploy-web-stage.yml
.github/workflows/deploy-web-test.yml

Fix workflows for deploying site by labels.

[ci] Fix WF for deploying site by labels

---

modules/462-loki/templates/statefulset.yaml

Mount `/tmp` to emptyDir
Closes https://github.com/deckhouse/deckhouse/issues/5183
```changes
section: loki
type: fix
summary: Mount `/tmp` to emptyDir to fix retention
```

[loki] Fix tmp mount for retention

---

.github/ci_templates/web.yml
.github/scripts/js/constants.js
.github/workflow_templates/build-and-test_pre-release.yml
.github/workflow_templates/build-and-test_release.yml
.github/workflow_templates/deploy-web.multi.yml
.github/workflows/build-and-test_pre-release.yml
.github/workflows/build-and-test_release.yml
.github/workflows/deploy-web-stage.yml
.github/workflows/deploy-web-test.yml
docs/site/.helm/templates/20-ingress.yaml

Update workflows and site templates.
- Deploy site Ingress according to different rules for different envs.
- Remove deployed by the `deploy/web/preprod` label (technical issues).
- Deploy doc and site in parallel jobs.
```changes
section: ci
type: chore
summary: Update workflows and site templates.
```

[ci][site] Update workflows and site templates

---

docs/site/.helm/templates/20-ingress.yaml

[ci][site] Update site Ingress

---

modules/150-user-authn/templates/kubeconfig-generator/custom-certificate.yaml

Add custom certificate for kubeconfig generator.
We need to create custom certificates for kubeconfig generator.
See above.
```changes
type: fix
summary: Add custom certificate for kubeconfig generator.
```

[user-authn] Add custom certificate for kubeconfig generator

---

docs/site/.helm/templates/20-ingress.yaml
docs/site/.werf/nginx-dev.conf
docs/site/.werf/nginx.conf
docs/site/sitemap-site.xml
docs/site/sitemap-site_ru.xml

Add the sitemap for non-versioned documentation.
Fix config for a local run.
```changes
section: docs
type: chore
summary: Site updates.
```

[site] Fix sitemap location

---

go.mod

Remove unnecessary libraries from go.mod
Remove unnecessary libraries from go.mod
```changes
type: chore
summary: Go mod tidy
```

[global] Go mod tidy

---

modules/402-ingress-nginx/openapi/config-values.yaml

Bump default ingress controller to the 1.6
Use EndpointSlices instead of Endpoints. More details [here](https://github.com/deckhouse/deckhouse/issues/5435)
```changes
type: feature 
summary: Bump default ingress controller version to the 1.6.
impact: If controller version in not pinned in the IngressNginxController CRD, ingress controller will be updated to the 1.6 version and will restart.
```

[ingress-nginx] Bump ingress controller default version to the 1.6

---

tools/images_tags/main.go

Added SOURCE_REPO to tests generation
To solve `make generate` local run failures
```changes
section: tools
type: chore
summary: add SOURCE_REPO to tests generation
```

[chore] add SOURCE_REPO to tests generation

---

docs/documentation/_data/sidebars/main.yml
ee/modules/450-keepalived/docs/FAQ.md
ee/modules/450-keepalived/docs/FAQ_RU.md

Add info about how to do manual IP switching.
```changes
section: keepalived
type: fix
summary: Adds info about how to do manual IP switching.
```

[keepalived][FAQ] How to manually switch keepalived

---

helm_lib/Chart.lock
helm_lib/Chart.yaml
helm_lib/charts/deckhouse_lib_helm/Chart.yaml
helm_lib/charts/deckhouse_lib_helm/README.md
helm_lib/charts/deckhouse_lib_helm/templates/_module_image.tpl
helm_lib/charts/deckhouse_lib_helm/templates/_module_security_context.tpl

1. Added Helm template helper to run images through a dedicated "deckhouse" user
2. Added deckhouse user and group to "distroless" container
We'd like to run every process inside deckhouse-borne containers through a single UID/GID to ease mapping.
```changes
type: feature
summary: Added "deckhouse" user to distroless image.
```

Updated helm_lib and distroless image to include new "deckhouse" user

---

modules/340-extended-monitoring/images/cert-exporter/Dockerfile

k8s-image-availability-exporter, events_exporter, cert-exporter are now based on minimal image.
```changes
type: feature
summary: Images are based on a distroless image.
```

[distroless] extended-monitoring

---

docs/documentation/_plugins/openapi.rb

Remove duplicates from the comparison table tooltip (e.g istio).
```changes
section: docs
type: chore
summary: Remove duplicates from the comparison table tooltip.
```

[docs] Remove duplicates from the comparison table

---

deckhouse-controller/pkg/debug/debug.go
modules/002-deckhouse/docs/FAQ.md
modules/002-deckhouse/docs/FAQ_RU.md

Improved readability of raw debugging information
not all json files are now in a format that is comfortable for manual reading. the added cost of spaces is insignificant due to compression. 
```changes
section: deckhouse-controller]
type: fix
summary: Improved readability of raw debugging information.
```

[deckhouse-controller] Improved readability of raw debugging information

---

docs/site/_plugins/alert.rb

Fix icon path on the alert block on the site.

[docs] Fix icon path on the alert block

---

candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl

Revert changes for `064_configure_kubelet.sh.tpl` file that was made in this pr(https://github.com/deckhouse/deckhouse/pull/5514)
After reverting(https://github.com/deckhouse/deckhouse/pull/5514) containerd migration to cgroupfs we have not considered the situation in which a node can have `NotManaged` Docker.
```changes
section: candi
type: fix
summary: Fix configure kubelet step.
```

[candi](bashible) Fix configure kubelet step

---

docs/documentation/_data/modal.yml
docs/documentation/_includes/become_a_partner_form.html
docs/documentation/_includes/form_in_modal.html
docs/documentation/_includes/get_a_report_form.html
docs/documentation/_includes/request_access_form.html
docs/documentation/_includes/request_callback_form.html
docs/documentation/_includes/request_demo_form.html
docs/documentation/_includes/request_education_form.html
docs/documentation/_layouts/default.html
docs/site/_includes/get_a_report_form.html
docs/site/_includes/request_access_form.html
docs/site/_includes/request_callback_form.html
docs/site/_includes/request_education_form.html
docs/site/_layouts/default.html

Fix forms in the documentation on the site.

[docs] Fix forms on the site

---

docs/documentation/_includes/toc.html
docs/site/_includes/toc.html

Fix TOC generation in the documentation.
Fix: https://github.com/deckhouse/deckhouse/pull/5556
```changes
section: docs
type: chore
summary: Fix TOC generation in the documentation.
```

[docs] Fix TOC generation

---

docs/site/_includes/getting_started/global/partials/FINISH_CARDS.md
docs/site/_includes/getting_started/global/partials/FINISH_CARDS_RU.md
docs/site/css/components/_cards.scss

Add info about the Going to production guide to the final step of the Getting started.
```changes
section: docs
type: chore
summary: Add info about the Going to production guide to the final step of the Getting started.
```

[docs][getting started] Add info about the Going to production guide

---

.github/ci_includes/werf_envs.yml
.github/workflows/build-and-test_dev.yml
.github/workflows/build-and-test_pre-release.yml
.github/workflows/build-and-test_release.yml
modules/462-loki/images/loki/Dockerfile
tools/images_tags/main.go
werf-giterminism.yaml
werf.yaml

We need do add go proxy for getting go modules for building CSE edition. For CSE edition proxy will be installed to our infrastructure. For another editions we set http://proxy.golang.org/
CSE build.
```changes
section: ci
type: chore
summary: Add GOPROXY env variable
```

[ci] Add GOPROXY env variable

---

modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml

fix issue #5312
fix node-exporter freezes
node-exporter has freezes
fix node-exporter freezes
node-exporter has livenessprobe and restart by himself
```changes
type: fix
summary: fix freezes for node-exporter
```

[monitoring] add livenessProbe for node-exporter

---

README.md

Update D8 certification information in the README.md

[readme] Update D8 certification information in the README.md

---

ee/modules/600-flant-integration/images/flant-pricing/hooks/controller_metrics.py
ee/modules/600-flant-integration/images/flant-pricing/hooks/controller_metrics_test.py
ee/modules/600-flant-integration/images/flant-pricing/hooks/utils.py

Change `sum` to `avg` in `controller_metrics` hook and refactor utils.
We don't want to use `sum` func because it result depends on replicas count.
```changes
type: fix
summary: Change `sum` to `avg` in `controller_metrics` hook and refactor utils.
```

[flant-integration] Change `sum` to `avg` in `controller_metrics` hook and refactor utils

---

docs/documentation/_data/sidebars/main.yml

Updates the monitoring section of the documentation sidebar.
Remove the Targets section and move items from the Target section to the upper level.
```changes
section: docs
type: chore
summary: Updates the monitoring section of the documentation sidebar.
```

[docs] Updates the monitoring section of the documentation sidebar

---

modules/021-cni-cilium/docs/README.md
modules/021-cni-cilium/docs/README_RU.md

Update kernel requirements for the `cni-cilium` module in the documentation.
```changes
section: docs
type: chore
summary: Update kernel requirements for the `cni-cilium` module in the documentation.
```

[docs][cni-cilium] Update kernel requirements

---

CHANGELOG/CHANGELOG-v1.50.md

Fix changelog fo the 1.50 release...

[chore] Fix CHANGELOG v1.50

---

docs/documentation/_data/supported_versions.yml

Clarify information about support for quay registry
Current documentation incomplete
```changes
section: docs
type: chore
summary: Clarify info about quay container registry support.
```

[docs] Add info about FEATURE_GENERAL_OCI_SUPPORT for quay support

---

ee/modules/450-keepalived/docs/README.md
ee/modules/450-keepalived/docs/README_RU.md
modules/040-node-manager/docs/FAQ.md
modules/040-node-manager/docs/FAQ_RU.md

```changes
section: docs
type: chore
```

[docs][keepalived] Minor documentation updates

---

modules/340-extended-monitoring/images/cert-exporter/Dockerfile
modules/340-extended-monitoring/images/events-exporter/Dockerfile
modules/340-extended-monitoring/images/image-availability-exporter/Dockerfile
modules/460-log-shipper/images/vector/Dockerfile
modules/462-loki/images/loki/Dockerfile

Add GOPROXY to cert_exporter, events_exporter, image_availability_exporter, log_shipper, loki
```changes
section: candi
type: feature
summary: Images are based on a distroless image.
```

[distroless] add goproxy

---

candi/openapi/doc-ru-static_cluster_configuration.yaml
candi/openapi/static_cluster_configuration.yaml

added how to edit StaticClusterConfiguration
```changes
section: docs
type: fix 
summary: Add info about how to edit `StaticClusterConfiguration`.
```

[docs] added how to edit StaticClusterConfiguration

---

modules/460-log-shipper/docs/EXAMPLES.md
modules/460-log-shipper/docs/EXAMPLES_RU.md

Added Collect logs without strings
```changes
type: fix 
summary: Add an example about collecting logs without strings.
```

[log-shipper] Added example Collect logs without strings

---

CHANGELOG/CHANGELOG-v1.50.md

Fix changelog for v1.50

---

deckhouse-controller/pkg/debug/debug.go
modules/002-deckhouse/docs/FAQ.md
modules/002-deckhouse/docs/FAQ_RU.md

additional information about monitoring status
```changes
type: fix 
summary: Add Prometeus logs to the debugging information.
```

[deckhouse-controller] added prometeus logs to the debugging information

---

modules/040-terraform-manager/docs/CONFIGURATION.md
modules/040-terraform-manager/docs/CONFIGURATION_RU.md
modules/040-terraform-manager/docs/README.md
modules/040-terraform-manager/docs/README_RU.md
modules/040-terraform-manager/openapi/config-values.yaml
modules/040-terraform-manager/openapi/doc-ru-config-values.yaml

```changes
section: docs
type: chore
```

[docs][terraform-manager] Minor documentation updates

---

modules/140-user-authz/crds/clusterauthorizationrule.yaml
modules/140-user-authz/crds/doc-ru-clusterauthorizationrule.yaml

[docs][user-authz] Update clusterAuthorizationRule spec

---

modules/000-common/images/kubernetes/werf.inc.yaml
modules/000-common/images/pause/werf.inc.yaml

This PR is a part of building all images from own repos and use distroless image.
```changes
section: candi
type: chore
summary: kubernetes add build from own repo
impact: control-plane components should restart
```

[common] kubernetes add build from own repo

---

modules/300-prometheus/images/grafana-dashboard-provisioner/Dockerfile
modules/300-prometheus/images/grafana-dashboard-provisioner/hooks/dashboard_provisioner.py
modules/300-prometheus/images/grafana-dashboard-provisioner/requirements.txt
modules/300-prometheus/images/grafana-dashboard-provisioner/werf.inc.yaml

Change build dashboard-loader from docker file to werf .
Update python dependency from shel-operator to deckhouse.
Need for CSE
Dashboard created
library updated
Have dashboard
Delete dashboard
```changes
type: chore
summary: Change build dashboard-loader from docker file to werf
```

[prometheus] Change build dashboard-loader from docker file to werf

---

ee/modules/600-flant-integration/hooks/madison/registration.go
ee/modules/600-flant-integration/hooks/madison/registration_test.go

Handle `connect.deckhouse.io` response basing on the status code instead of error message
Connect could return 401 response with `{"message": "Unauthorized"}` if no project is set in a license (for example) and hook will finish successfully but no registration will be done.
We could use status code instead of error message to requeue the hook
```changes
type: fix 
summary: Fix `connect` response handling with respect of status code instead of error message.
```

[flant-integration] Fix connect madison registration

---

modules/140-user-authz/crds/clusterauthorizationrule.yaml
modules/140-user-authz/crds/doc-ru-clusterauthorizationrule.yaml

Update the description of the namespaceSelector parameter.
```changes
section: docs
type: chore
summary: Update the description of the namespaceSelector parameter.
```

[user-authn][docs] Update description of the namespaceSelector parameter

---

modules/460-log-shipper/images/vector/Dockerfile

Remove libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb from a final image after install
```changes
type: fix
summary: Remove libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb from a final image after install
```

[log-shipper] fix Dockerfile

---

testing/openapi_validation/library.go
testing/openapi_validation/validators/enum.go
testing/openapi_validation/validators/ha_and_https.go

Some values and checks were missed somehow.
We have to add excludes for them
We can't run these tests localy
```changes
type: fix
summary: Fix openapi validation rules
```

[testing] Fix openapi validation

---

candi/openapi/doc-ru-init_configuration.yaml

[docs] Proofreading

---

testing/cloud_layouts/vSphere/Standard/configuration.tpl.yaml

Update configuration for running e2e tests in vSphere.
```changes
type: chore
summary: Update configuration for running e2e tests in vSphere.
```

[testing] Fix template for vSphere

---

ee/modules/600-flant-integration/monitoring/prometheus-rules/sending-alerts.yaml

```changes
type: fix
summary: Fixed a typo Pometheus
```

[modules] [600] fixed a typo

---

tools/build_includes/modules-with-dependencies-EE.yaml
tools/build_includes/modules-with-dependencies-FE.yaml

Run code generators.
```changes
type: chore
summary: Run code generators.
```

[chore] Regeneration

---

modules/150-user-authn/docs/USAGE.md
modules/150-user-authn/docs/USAGE_RU.md

Fixed a bug in the example Group object
```changes
type: fix
summary: Fixed a bug in the example Group object.
```

[user-authn] Fix apiVersion Group object in doc

---

modules/150-user-authn/docs/USAGE_RU.md

Not necessary.
```changes
section: docs
type: chore
```

[docs] Minor documentation updates

---

modules/462-loki/templates/statefulset.yaml

Fixed a volume mount init container
Loki can't start
```changes
section: loki
type: fix
summary: Fixed a volume mount init container.
```

[loki] fix init container

---

candi/cloud-providers/yandex/openapi/doc-ru-instance_class.yaml
candi/cloud-providers/yandex/openapi/instance_class.yaml

Update parameters description of the YandexInstanceClass resource.
```changes
section: docs
type: chore
summary: Update parameters description of the YandexInstanceClass resource.
```

[docs] Update description of the yandexinstanceclasses parameters

---

.github/workflow_templates/build-and-test_release.yml
.github/workflows/build-and-test_release.yml

Build custom tags to EE edition.
Most of our clients use EE version, not FE. Now custom tags builds only to FE edition.
```changes
section: ci
type: chore
summary: Build custom tags to EE edition.
```

[ci] Build custom tags to ee

---

ee/fe/modules/340-monitoring-applications/applications/elasticsearch/grafana-dashboards/elasticsearch.json
ee/fe/modules/340-monitoring-applications/applications/elasticsearch/prometheus-rules/elasticsearch.yaml

Updated elasticsearch dashboad. Added minimal alert rules for prometheus
Old
New

Added new verison of elasicsearch dashboard and alert rules

---

ee/fe/modules/340-monitoring-applications/applications/php-fpm/grafana-dashboards/php-fpm.json

Added queue status and slow requests pct on PHP-FPM dashboard

Added queue status and slow requests pct for PHP-FPM dashboard

---

docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md

[getting-started][docs] Minor fixes

---

.github/workflow_templates/build-and-test_pre-release.yml
.github/workflow_templates/build-and-test_release.yml
.github/workflows/build-and-test_pre-release.yml
.github/workflows/build-and-test_release.yml

Update deploy rules for the site.
```changes
section: ci
type: chore
summary: Update deploy rules for the site.
```

[ci] Update CI for site

---

.github/ci_templates/web.yml
.github/workflows/build-and-test_dev.yml
.github/workflows/build-and-test_pre-release.yml
.github/workflows/build-and-test_release.yml
.github/workflows/deploy-web-stage.yml
.github/workflows/deploy-web-test.yml

[ci] Update site workflow

---

docs/documentation/pages/DECKHOUSE-FAQ.md
docs/documentation/pages/DECKHOUSE-FAQ_RU.md

Update info about using d8-pull/d8-push scripts.
```changes
section: docs
type: chore
summary: Update info about using d8-pull/d8-push scripts.
```

[docs] Update info about using d8-pull/d8-push scripts

---

.github/CODEOWNERS

Codeowners were out of date
```changes
type: chore
summary: Change CODEOWNERS
```

[chore] Change CODEOWNERS

---

modules/340-extended-monitoring/docs/CONFIGURATION.md
modules/340-extended-monitoring/docs/CONFIGURATION_RU.md

Update documentation a bit about using extended monitoring.
```changes
section: docs
type: chore
summary: Update documentation a bit about using extended monitoring.
```

[docs][extended-monitoring] Documentation updates

---

modules/460-log-shipper/apis/v1alpha1/cluster_log_destination.go
modules/460-log-shipper/crds/cluster-log-destination.yaml
modules/460-log-shipper/crds/doc-ru-cluster-log-destination.yaml
modules/460-log-shipper/hooks/internal/vector/destination/kafka.go
modules/460-log-shipper/hooks/testdata/file-to-kafka/manifests.yaml
modules/460-log-shipper/hooks/testdata/file-to-kafka/result.json

Add more auth methods for Kafka
As of today, the only supported authentication method is tls, but for test environments, it is not convenient.
```changes
type: feature
summary: Add Kafka SASL auth settings to configure
```

[log-shipper] Add Kafka SASL auth settings

---

testing/cloud_layouts/script.sh

Fix e2e
```changes
type: fix
summary: Fix e2e
```

[testing] Fix e2e

---

candi/openapi/doc-ru-init_configuration.yaml
candi/openapi/init_configuration.yaml

Added missing description for InitConfiguration.deckhouse.devBranch parameter.
```changes
section: docs
type: chore
summary: Add description for InitConfiguration.deckhouse.devBranch parameter.
```

Add description for InitConfiguration.deckhouse.devBranch parameter

---

.github/ci_templates/web.yml
.github/workflows/build-and-test_dev.yml
.github/workflows/build-and-test_pre-release.yml
.github/workflows/build-and-test_release.yml
docs/site/_includes/header.html

[ci][docs] Fix footer and CI

---

modules/300-prometheus/monitoring/prometheus-rules/nodes.yaml

Fixed errors in template for correct rendering.
```changes
type: chore
summary: Fix template for K8STooManyNodes alert description
```

Fix template for K8STooManyNodes alert description

---

global-hooks/enable_cni.go
global-hooks/enable_cni_test.go

CNI hooks change

---

docs/site/css/docs.scss

Fix styles of the search element in the documentation.

[docs] Reverted styles for search field

---

global-hooks/migrate/migrate_modules_crds.go
go_lib/hooks/ensure_crds/hook.go
go_lib/hooks/ensure_crds/hook_test.go
go_lib/hooks/ensure_crds/test_data/double.crd
go_lib/hooks/ensure_crds/test_data/huge.crd
go_lib/hooks/ensure_crds/test_data/single.crd

Optimize EnsureCRD hook
Reduce memory and CPU usage
```
BenchmarkEnsureCRDs/old-12              1000000000               0.09505 ns/op  
BenchmarkEnsureCRDs/new-12              1000000000               0.03931 ns/op 
```
unfortunately we can't measure the memory allocations. Because Benchmem measures only the heap allocations, ignoring the stack
```changes
type: chore
summary: Optimize EnsureCRDs hook memory and CPU usage.
```

[go_lib] Optimize EnsureCRDs hook

---

modules/465-pod-reloader/templates/deployment.yaml

added the forgotten node selector
pod runs on non-system nodes. 
```changes
section: pod-reloader
type: fix
summary: added the forgotten node selector
```

[pod-reloader] added the forgotten node selector

---

tools/cve/d8-images.sh
tools/cve/html/body-part.tpl

Fix weekly CVE tests
Trivy image excluded from Weekly CVE tests
Weekly CVE tests passes successfully
```changes
section: tools | cve 
type: fix
summary: To successfully run CVE tests, the Trivy image was excluded from the scan
```

[cve] Fix weekly CVE tests

---

candi/openapi/doc-ru-init_configuration.yaml
candi/openapi/init_configuration.yaml
docs/site/_includes/getting_started/global/step_cluster_setup.html
docs/site/_includes/getting_started/global/step_cluster_setup_ru.html

Update info about `registryDockerCfg` parameter.
```changes
section: docs
type: chore
summary: Update info about registryDockerCfg parameter.
```

[docs] Update info about registryDockerCfg parameter

---

.github/workflow_templates/cve-weekly.yml
.github/workflows/cve-weekly.yml

Temporary remove "Send report" job
```changes
section: workflows | cve-weekly
type: fix
summary: Temporary remove "Send report" job
section: workflows_templates | cve-weekly
type: fix
summary: Temporary remove "Send report" job
```

[cve] fix: temporary comment Send report job

---

docs/documentation/_data/i18n.yml
docs/documentation/_data/sidebars/main.yml
docs/documentation/_plugins/openapi.rb
docs/site/_config.yml
docs/site/_data/i18n.yaml
docs/site/css/docs.scss

Add the "temporary deprecated" badge to the virtualization module.

[docs] Add temporary deprecated badge and popup

---

modules/460-log-shipper/images/vector/reloader/main.go

Sometimes locks are left in the folders preventing loading the config 
```
2023-10-12T15:56:16.714921Z ERROR vector::topology: Configuration error. error=Sink "destination/cluster/loki-ebapp": error occurred when building buffer: failed to build individual stage 0: failed to load/create ledger: failed to lock buffer.lock; is another Vector process running and using this buffer?
```
Locks are not required in Kubernetes because the daemonset controller can handle running two vector processes at the same time.
More context
https://github.com/vectordotdev/vector/issues/18831
```changes
type: fix
summary:  Remove buffer locks on startup
```

[log-shipper] Remove buffer locks on startup

---

docs/site/.gitignore
docs/site/.helm/templates/20-ingress.yaml
docs/site/.werf/nginx-dev.conf
docs/site/.werf/nginx.conf
docs/site/backends/docs-builder-template/config/_default/hugo.yaml
docs/site/backends/docs-builder-template/data/channels.yaml
docs/site/backends/docs-builder-template/data/helpers.yaml
docs/site/backends/docs-builder-template/data/modules.yaml
docs/site/backends/docs-builder-template/i18n/en.yaml
docs/site/backends/docs-builder-template/i18n/ru.yaml
docs/site/backends/docs-builder-template/layouts/_default/baseof.html
docs/site/backends/docs-builder-template/layouts/_default/list.html
docs/site/backends/docs-builder-template/layouts/_default/single.html
docs/site/backends/docs-builder-template/layouts/partials/breadcrumbs.html
docs/site/backends/docs-builder-template/layouts/partials/module-version-menu.html
docs/site/backends/docs-builder-template/layouts/partials/sidebar.html
docs/site/backends/docs-builder-template/layouts/partials/toc.html
docs/site/docker-compose.yml
docs/site/werf.yaml

Add HuGo templates.
Ref: https://github.com/deckhouse/deckhouse/issues/6145

[module] Documentation. Add templates

---

go.mod
go.sum
modules/340-monitoring-deckhouse/templates/podmonitor.yaml
tools/go.sum

Fix PodMonitor
Hook metrics were removed. Make PodMonitor synchronized
```changes
section: monitoring-deckhouse
type: fix 
summary: Fix deckhouse metrics fetch.
```

[monitoring-deckhouse] update pod monitor

---

docs/documentation/.helm/templates/20-ingress.yaml
docs/documentation/.helm/values.yaml
docs/site/.helm/templates/20-ingress.yaml
docs/site/.helm/values.yaml

- Change the name of the Secret with TLS certificate.
- Delete Certificate for production.

[docs] Update site deploy

---

modules/300-prometheus/images/prometheus/Dockerfile

Fix Prometheus image size.
```changes
type: fix
summary: Fix Prometheus image size.
```

[prometheus] fix prometheus image size

---

go.mod
go.sum
tools/go.sum
werf.yaml

- [CVE-2022-4450](https://access.redhat.com/errata/RHSA-2023:2165)
- [CVE-2023-0215](https://access.redhat.com/errata/RHSA-2023:2165)
- [CVE-2023-0286](https://access.redhat.com/errata/RHSA-2023:2165)
- [CVE-2023-0464](https://access.redhat.com/errata/RHSA-2023:3722)
- [CVE-2022-4450](https://access.redhat.com/errata/RHSA-2023:2165)
- [CVE-2023-0215](https://access.redhat.com/errata/RHSA-2023:2165)
- [CVE-2023-0286](https://access.redhat.com/errata/RHSA-2023:2165)
- [CVE-2023-0464](https://access.redhat.com/errata/RHSA-2023:3722)
- [GHSA-m425-mq94-257g](https://github.com/grpc/grpc-go)
```changes
type: fix
summary: fix cve issues in deckhouse-controller image
```

[deckhouse-controller] fix cve issues in deckhouse-controller image

---

modules/040-node-manager/docs/README.md
modules/040-node-manager/docs/README_RU.md

Fix https://github.com/deckhouse/deckhouse/pull/6514

[docs] Minor documentation fix

---

candi/version_map.yml

Azure cloud-controller-manager has been updated to the latest versions for all supported kubernetes versions.
<details><summary>Look here</summary>
```shell
[root@candi-6926419106-1-con-1-25-master-0 ~]# kubectl get no -o wide
NAME                                                      STATUS     ROLES                  AGE   VERSION    INTERNAL-IP   EXTERNAL-IP       OS-IMAGE         KERNEL-VERSION                 CONTAINER-RUNTIME
candi-6926419106-1-con-1-25-master-0                      Ready      control-plane,master   11m   v1.25.15   10.50.0.4     172.205.129.247   CentOS Linux 8   4.18.0-240.10.1.el8_3.x86_64   containerd://1.6.24
candi-6926419106-1-con-1-25-worker-30985b0d-589f6-kbkgc   Ready      worker                 26s   v1.25.15   10.50.0.5     <none>            CentOS Linux 8 …
```

[cloud-provider-azure] Update cloud-controller-manager

---

modules/040-node-manager/docs/EXAMPLES.md
modules/040-node-manager/docs/EXAMPLES_RU.md

Minor documentation fix.
```changes
type: chore
summary: Minor documentation fix.
```

[node-manager] Minor documentation fix.

---

docs/site/backends/docs-builder-template/data/helpers.yaml
docs/site/backends/docs-builder-template/i18n/en.yaml
docs/site/backends/docs-builder-template/i18n/ru.yaml
docs/site/backends/docs-builder-template/layouts/_default/single.html
docs/site/backends/docs-builder-template/layouts/partials/module-resources.html
docs/site/backends/docs-builder-template/layouts/partials/openapi/format-attributes.html
docs/site/backends/docs-builder-template/layouts/partials/openapi/format-crd.html
docs/site/backends/docs-builder-template/layouts/partials/openapi/format-schema.html
docs/site/backends/docs-builder-template/layouts/partials/openapi/format-type.html

Render CRDs
ref: https://github.com/deckhouse/deckhouse/pull/6317

[site] Render OpenAPI specs of the modules

---

testing/cloud_layouts/script.d/wait_cluster_ready/test_script.sh

Fix upmeter tests, after migration to distroless.
Ref #6176
```changes
type: chore
summary: Fix upmeter tests, after migration to distroless.
```

[testing] Fix upmeter probe test

---

candi/bashible/bootstrap.sh.tpl
modules/040-node-manager/images/caps-controller-manager/src/internal/client/bootstrap.go
modules/040-node-manager/images/caps-controller-manager/src/internal/client/cleanup.go
modules/040-node-manager/images/caps-controller-manager/src/internal/client/client.go
modules/040-node-manager/images/caps-controller-manager/src/internal/client/task_manager.go
modules/040-node-manager/images/caps-controller-manager/src/internal/controller/infrastructure/staticmachine_controller.go
modules/040-node-manager/images/caps-controller-manager/src/internal/providerid/provider_id.go
modules/040-node-manager/images/caps-controller-manager/src/internal/scope/instance_scope.go
modules/040-node-manager/templates/caps-controller-manager/static-cluster.yaml

Add MachineHealthCheck.
```changes
type: fix
summary: Add MachineHealthCheck for CAPS.
```

[node-manager](caps) add MachineHealthCheck

---

ee/modules/600-flant-integration/templates/pricing/config.yaml

Fix grafana agent config.
Metrics are not sent.
```changes
type: fix
summary: Fix grafana agent config.
```

[flant-integration] Fix grafana agent configuration

---

candi/cloud-providers/aws/terraform-modules/versions.tf
candi/cloud-providers/azure/terraform-modules/versions.tf
candi/cloud-providers/gcp/terraform-modules/versions.tf
candi/cloud-providers/yandex/terraform-modules/versions.tf
candi/terraform_versions.yml
ee/candi/cloud-providers/openstack/terraform-modules/versions.tf
ee/candi/cloud-providers/vsphere/terraform-modules/versions.tf
ee/modules/040-terraform-manager/images/terraform-manager-openstack/werf.inc.yaml
ee/modules/040-terraform-manager/images/terraform-manager-vsphere/werf.inc.yaml
modules/040-terraform-manager/images/base-terraform-manager/werf.inc.yaml
modules/040-terraform-manager/images/terraform-manager-aws/werf.inc.yaml
modules/040-terraform-manager/images/terraform-manager-azure/werf.inc.yaml
modules/040-terraform-manager/images/terraform-manager-gcp/werf.inc.yaml
modules/040-terraform-manager/images/terraform-manager-yandex/werf.inc.yaml

`base-terraform-manager` and everything based on it is now built from `common/distroless`.
We want our components to use distroless base image.
https://github.com/deckhouse/deckhouse/pull/6639#issuecomment-1833868409
```changes
type: chore
summary: Build distroless-based terraform-manager images.
```

[terraform-manager] Distroless build

---

docs/site/.helm/values.yaml

[docs] Fix configuration for the site.

[docs] Fix configuration for the site.

---

docs/site/backends/docs-builder-template/data/helpers.yaml
docs/site/backends/docs-builder-template/i18n/en.yaml
docs/site/backends/docs-builder-template/i18n/ru.yaml
docs/site/backends/docs-builder-template/layouts/_default/single.html

Use CR.md or CR.<lang>.md for customResource files.

[site][modules-docs] Fix using CR files

---

docs/site/backends/docs-builder-template/layouts/partials/openapi/format-crd.html

[modules-docs] Fix openapi generator.

---

docs/site/werf.yaml

Force rebuild of artifacts for the site

[chore] Force rebuild of artifacts

---

docs/site/backends/docs-builder-template/layouts/_default/baseof.html

Fix the language switcher to switch language on the module's documentation sections.
```changes
section: docs
type: chore
summary: Fix the language switcher to switch language on the module's documentation sections.
```

[chore] Fix language switcher

---

docs/site/backends/docs-builder-template/i18n/en.yaml
docs/site/backends/docs-builder-template/i18n/ru.yaml
docs/site/backends/docs-builder-template/layouts/_default/single.html
docs/site/backends/docs-builder-template/layouts/partials/alert.html
docs/site/backends/docs-builder-template/layouts/partials/sidebar.html
docs/site/backends/docs-builder-template/layouts/shortcodes/alert.html

Show module edition badge and use stable channel as default.
```changes
section: docs
type: chore
summary: Show module edition badge and use stable channel as default.
```

[modules-docs] Show module edition badge and use stable channel as default

---

modules/041-linstor/docs/FAQ.md
modules/041-linstor/docs/FAQ_RU.md

Ref: https://github.com/deckhouse/deckhouse/pull/6737
```changes
section: docs
type: chore
```

[docs][linstor] Minor documentation updates

---

.github/ci_templates/web.yml
.github/workflows/build-and-test_dev.yml
.github/workflows/build-and-test_pre-release.yml
.github/workflows/build-and-test_release.yml
Makefile
tools/doc_check_links.sh

Fix documentation links checker.
```changes
section: ci
type: chore
summary: Fix documentation links checker.
```

[ci] Fix documentation links checker

---

docs/site/.helm/values.yaml

Load modules from dev-registry
We want to watch for modules docs before pushing to production. We can take modules from dev-registry and render documentation for them
```changes
type: chore
summary: Change registry for test deckhouse.io site.
```

[documentation] Change registry for test deckhouse.io

---

modules/031-ceph-csi/openapi/config-values.yaml
modules/031-ceph-csi/openapi/values.yaml

Create empty config-values.yaml
With config-values module will not fill values for module. Both files required
```changes
type: fix 
summary: Create openapi config spec file.
```

[ceph-csi] Fix openapi spec

---

modules/040-node-manager/crds/doc-ru-sshcredentials.yaml
modules/040-node-manager/crds/doc-ru-staticinstance.yaml
modules/040-node-manager/crds/sshcredentials.yaml

Refine docs.
It's not clear why `SSHCredentials` resource is needed.
If we want these improvements to become available to users sooner.
```changes
type: chore
summary: Docs improvements for CAPS.
```

[docs] Refine SSHCredentials docs

---

ee/modules/350-node-local-dns/templates/cilium-local-redirect-policy.yaml

Fix for CiliumLocalRedirectPolicy for node-local-redirect (wrong protocol for dns-tcp rule).
node-local-dns actually did work for TCP requests, but it was confusing to have the wrong resource in cluster.
node-local-dns resolves TCP DNS requests (as it did).
```changes
type: fix
summary: Fix for CiliumLocalRedirectPolicy for node-local-redirect (wrong protocol for dns-tcp rule).
```

[node-local-dns] fixing CiliumLocalRedirectPolicy

---

docs/site/_includes/getting_started/azure/partials/config.yml.standard.ce.inc
docs/site/_includes/getting_started/azure/partials/config.yml.standard.ee.inc
docs/site/_includes/getting_started/gcp/partials/config.yml.without_nat.ce.inc
docs/site/_includes/getting_started/gcp/partials/config.yml.without_nat.ee.inc

Fix links in the Getting Started.
Corrected links to documentation in comments of config files of Microsoft Azure and Google Cloud Platform
```changes
section: docs
type: chore
summary: Fix links in the Getting Started.
```

Config comment link

---

docs/site/.helm/templates/14-frontend.yaml
docs/site/.werf/nginx-dev.conf
docs/site/.werf/nginx.conf
docs/site/backends/docs-builder/build.go
docs/site/docker-compose.yml

Change mounts for the modules docs.
```changes
section: docs
type: chore
summary: Change mounts for the modules docs.
```

Fix site paths

---

modules/040-node-manager/hooks/generate_capi_static_kubeconfig.go

fix creating ns

---

modules/040-node-manager/templates/cluster-autoscaler/rbac-for-us.yaml
modules/040-node-manager/templates/node-group/_capi_machine_deployment.tpl

add cluster autoscaller

---

modules/040-node-manager/templates/node-group/_capi_machine_deployment.tpl

fix add rolling update

---

docs/site/.helm/values.yaml

Change log levels for registry watcher
We need debug level for test and info level for prod
```changes
section: docs
type: fix
summary: Change registry watcher log level
```

[docs] Fix log level for registry watcher

---

docs/documentation/pages/DECKHOUSE-FAQ.md
docs/documentation/pages/DECKHOUSE-FAQ_RU.md

Provide a working and clear example on how to switch to a registry with self-signed HTTPS certificates
Older example with anonymous file insert wasn't working in most cases.
Guide with manual CA file insertion into pod was confusing as well, because root partition is RO in the deckhouse pod.
```changes
type: chore
summary: Minor docs fix.
```

[documentation] Change registry example with CA cert fix

---

docs/documentation/_includes/sidebar_entry.html
docs/site/backends/docs-builder-template/layouts/partials/sidebar.html
docs/site/css/docs.scss

Refactor the style of bages in the documentation sidebar.
```changes
section: docs
type: chore
summary: Refactor the style of bages in the documentation sidebar.
```

[site] Refactor badges in the sidebar

---

docs/site/_includes/getting_started/aws/partials/config.ru.yml.without_nat.ce.inc
docs/site/_includes/getting_started/aws/partials/config.yml.without_nat.ce.inc
docs/site/_includes/getting_started/azure/partials/config.ru.yml.standard.ce.inc
docs/site/_includes/getting_started/azure/partials/config.yml.standard.ce.inc
docs/site/_includes/getting_started/bm/partials/config.ru.yml.ce.inc
docs/site/_includes/getting_started/bm/partials/config.yml.ce.inc
docs/site/_includes/getting_started/existing/partials/config.ru.yml.ce.inc
docs/site/_includes/getting_started/existing/partials/config.yml.ce.inc
docs/site/_includes/getting_started/gcp/partials/config.ru.yml.without_nat.ce.inc
docs/site/_includes/getting_started/gcp/partials/config.yml.without_nat.ce.inc
docs/site/_includes/getting_started/yandex/partials/config.ru.yml.standard.ce.inc
docs/site/_includes/getting_started/yandex/partials/config.yml.standard.ce.inc

Update documentation regarding the Deckhouse release channels.
```changes
section: docs
type: chore
summary: Update documentation regarding the Deckhouse release channels.
```

[docs] Update documentation regarding the Deckhouse release channels

---

docs/site/backends/docs-builder-template/layouts/partials/openapi/format-attributes.html
docs/site/backends/docs-builder-template/layouts/partials/openapi/format-crd.html

Refactor markdown rendering in descriptions in the modules documentation

[docs] Refactor markdown rendering in descriptions

---

docs/site/backends/docs-builder-template/i18n/en.yaml
docs/site/backends/docs-builder-template/i18n/ru.yaml
docs/site/backends/docs-builder-template/layouts/_default/baseof.html
docs/site/backends/docs-builder-template/layouts/partials/breadcrumbs.html
docs/site/backends/docs-builder-template/layouts/partials/sidebar.html

Refactor breadcrumbs in a module documentation.

[module docs] Refactor breadcrumbs

---

CHANGELOG/CHANGELOG-v1.55.md

Fix changelog for the 1.55 release.
```changes
section: docs
type: chore
summary: Fix changelog for the 1.55 release.
```

[chore] Fix changelog

---

ee/modules/500-operator-trivy/monitoring/grafana-dashboards/security/trivy.json

Backport: [trivy] dashboard - added "Package name" column

---

release.yaml

Fix release requirements.
Fix critical bug.
```changes
section: candi
type: chore
summary: Fix release requirements.
```

[candi] Fix release requirements

---

dhctl/pkg/operations/mirror.go
dhctl/pkg/operations/mirror/errors.go
dhctl/pkg/operations/mirror/layouts.go
dhctl/pkg/operations/mirror/modules.go
dhctl/pkg/operations/mirror_module.go

Added some patches to allow mirroring of CSE repo.
CSE pretty much says it all.
We need it ASAP.
```changes
section: dhctl
type: feature
summary: support for mirroring CSE.
```

[dhctl] mirror: support cse mirroring

---

modules/402-ingress-nginx/images/controller-1-6/patches/README.md
modules/402-ingress-nginx/images/controller-1-9/patches/README.md

Fix README notes
```changes
type: fix
summary: Fix readme notes.
```

[ingress-nginx] fix readme for patches

---

dhctl/pkg/operations/mirror.go
dhctl/pkg/operations/mirror/pull.go

`dhctl mirror` will now retry pulls and pushes of images if they fail for some reason.
User-requested feature.
```changes
section: dhctl
type: feature
summary: retry failed pull/push operations during mirroring
```

[dhctl] mirror: retry failed pull/push operations

---

modules/300-prometheus/docs/FAQ.md
modules/300-prometheus/docs/FAQ_RU.md

Fix markup in the prometheus FAQ.
```changes
section: docs
type: chore
summary: Fix markup in the prometheus FAQ.
```

[docs] Minor markup fix

---

candi/bashible/bashible.sh.tpl

Add a bash function that waits for a node to be added to the cluster before annotating the node.
Fix #6057.
```changes
section: candi
type: fix
summary: Wait for a node to be added to the cluster before annotating the node.
```

[candi] wait node before annotate node

---

.github/CODEOWNERS

[docs] Update CODEOWNERS

---

docs/site/.helm/templates/20-ingress.yaml
docs/site/.werf/nginx-dev.conf
docs/site/.werf/nginx.conf

[docs][chore] Minor config changes

---

modules/110-istio/docs/EXAMPLES.md

Fix typo in docs
```changes
section: istio
type: chore
summary: Fix typo in docs.
```

[istio] Fix typo in docs

---

modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/node-ro-fs.yaml

Update the `NodeFilesystemIsRO` alert description.
```changes
type: chore
summary: Update the `NodeFilesystemIsRO` alert description.
```

[monitoring-kubernetes] Update NodeFilesystemIsRO alert

---

modules/460-log-shipper/docs/README.md
modules/460-log-shipper/docs/README_RU.md

Minor documentation updates in the log-shipper module.
```changes
type: chore
```

[log-shipper][docs] Minor documentation updates

---

docs/documentation/werf.yaml

Build site according to module bundles for EE. Fix: #7210
```changes
section: docs
type: chore
summary: Fix site build.
```

[ci][docs] Update site building instructions

---

modules/400-descheduler/hooks/populate_values_and_set_cr_status.go
modules/400-descheduler/hooks/populate_values_and_set_cr_status_test.go

Do not deploy the descheduler if nodeSelector selects less then 2 nodes.
Close #4703
```changes
type: fix
summary: Set the number of replicas to 0 if we have only one node.
```

[descheduler] Do not deploy the descheduler if nodeSelector selects less then 2 nodes

---

ee/modules/450-network-gateway/images/dnsmasq/prepare-config.py
ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
ee/modules/450-network-gateway/templates/dhcp-statefulset.yaml

Change the path to the `dnsmasq` configuration files directory from `/etc/dnsmasq.d` to `/etc/dnsmasq.conf.d`.
On `ALT Linux`, the default directory for configuration files for `dnsmasq` is `/etc/dnsmasq.conf.d`.
```changes
section: network-gateway
type: fix
summary: Fix distroless build.
```

[network-gateway] fix distroless build

---

modules/010-prometheus-crd/crds/customalertmanager.yaml
modules/010-prometheus-crd/crds/doc-ru-customalertmanager.yaml

Delete unnecessary information about interaction Go and SMTP 
```changes
section: prometheus-customalertmanager
type: chore
summary: Delete unnecessary information about interaction Go and SMTP 
```

Config delete comment prometheus

---

candi/version_map.yml
ee/candi/bashible/detect_bundle.sh

add altlinux 10
```changes
section: candi
type: fix
summary: Add AltLinux 10.
```

[candi] add altlinux 10

---

dhctl/pkg/app/bootstrap.go

Increased deckhouse install timeout from 10 minutes to 15 minutes
Fixes https://github.com/deckhouse/deckhouse/issues/7072
```changes
section: dhctl
type: fix
summary: Increase deckhouse install timeout
```

[dhctl] Increase deckhouse install timeout

---

.github/ci_includes/werf_envs.yml
.github/workflows/build-and-test_dev.yml
.github/workflows/build-and-test_pre-release.yml
.github/workflows/build-and-test_release.yml
tools/images_tags/main.go
werf-giterminism.yaml
werf.yaml

Add env PIPPROXY for python modules.
```changes
section: chore
type: chore
summary: Add env PIPPROXY for python modules.
```

[chore] Add env PIPPROXY

---

modules/030-cloud-provider-yandex/docs/README.md
modules/030-cloud-provider-yandex/docs/README_RU.md

Fix typo in the documentation.
```changes
section: docs
type: chore
summary: Fix typo.
```

[docs][cloud-provider-yandex] Fix typo

---

docs/site/.helm/templates/20-ingress.yaml

Updates https://github.com/deckhouse/deckhouse/pull/7343

[docs] Add redirect for the virtualization module

---

deckhouse-controller/crds/module-source.yaml
global-hooks/openapi/config-values.yaml
global-hooks/openapi/doc-ru-config-values.yaml

Minor documentation changes.
Update `moduleSource` and the `storageClass` field of the global-hook.
```changes
section: docs
type: chore
summary: Minor documentation changes.
```

[docs] Update moduleSource and the storageClass field

---

deckhouse-controller/pkg/controller/module-controllers/release/override-controller.go

Return detailed failure message
Impossible to understand why the module is not validated on override
```changes
type: fix 
summary: Fix failure message detailed output on pull override.
```

[deckhouse-controller] fix error message on module validation

---

modules/040-control-plane-manager/hooks/audit_policy_basic_targets_generated.go

Update Go-generated code.
```changes
type: chore
summary: Update Go-generated code.
```

[testing] Codegeneration

---

candi/bashible/bashbooster/50_deckhouse_registrypackages.sh
candi/bashible/bundles/centos/bootstrap.sh.tpl

Fix bash word splitting.
Closes #7387 
Yes, we do. This affects the client.
```changes
section: candi
type: fix
summary: Fix bash word splitting.
```

[candi] Fix bash word splitting

---

ee/candi/cloud-providers/zvirt/layouts/standard/master-node/main.tf
ee/candi/cloud-providers/zvirt/layouts/standard/master-node/outputs.tf
ee/candi/cloud-providers/zvirt/layouts/standard/master-node/providers.tf
ee/candi/cloud-providers/zvirt/layouts/standard/master-node/variables.tf
ee/candi/cloud-providers/zvirt/layouts/standard/master-node/versions.tf
ee/candi/cloud-providers/zvirt/layouts/standard/variables.tf
ee/candi/cloud-providers/zvirt/terraform-modules/variables.tf
ee/candi/cloud-providers/zvirt/terraform-modules/versions.tf

Added `standard` terraform layout for zvirt provider.

zvirt standard layout

---

candi/bashible/bashible.sh.tpl

fix bashible message about node annotation.
If bashible cannot annotate a node for some time user see annoying error like
```
Error from server (NotFound): nodes "dev-master-0-1" not found
Failed to annotate node dev-master-0 with annotation node.deckhouse.io/configuration-checksum=2ad0f3b52a889d40c91b32455dc7b41604cec7c8c934c728cc80e242624d1880 ... retry in 10 seconds.
```
And if on the next attempt annotation is succesful, user cannot see any messages about it.
This gives the wrong impression that the bashible ended with errors.
```changes
section: candi
type: chore
summary:  fix bashible message about node annotation
```

[candi] fix bashible message about node annotation

---

.github/CODEOWNERS

[ci] Update CODEOWNERS

---

dhctl/pkg/kubernetes/actions/converge/destructive_change_id.go
dhctl/pkg/kubernetes/actions/converge/destructive_change_id_test.go
dhctl/pkg/operations/check/checker.go

Add a function for consistent Destructive Change identification
```changes
section: dhctl
type: feature
summary: Add a new function to calculate the ID of cluster Destructive Change.
```

[dhctl] feat(dhctl-for-commander) Add DestructiveChangeID func

---

dhctl/pkg/config/base.go
dhctl/pkg/config/load.go
dhctl/pkg/config/validation_test.go

* Fix validation errors wrapping
```changes
section: dhctl
type: fix
summary: Fix error wrapping.
```

[dhctl] fix(dhctl-for-commander): fix validation error handling

---

modules/340-monitoring-kubernetes/openapi/config-values.yaml
modules/340-monitoring-kubernetes/openapi/doc-ru-config-values.yaml

Minor documentation updates on the monitoring-kubernetes.
```changes
type: fix 
```

[monitoring-kubernetes] Minor documentation updates
