- modules/010-user-authn-crd/crds/doc-ru-user.yaml
- modules/010-user-authn-crd/crds/user.yaml
- modules/150-user-authn/docs/USAGE.md
- modules/150-user-authn/docs/USAGE_RU.md
- modules/150-user-authn/hooks/get_dex_user_crds.go
- modules/150-user-authn/hooks/get_dex_user_crds_test.go
- modules/150-user-authn/template_tests/dex_config_test.go
- modules/150-user-authn/template_tests/user_test.go
- modules/150-user-authn/templates/dex/passwords.yaml
- modules/150-user-authn/webhooks/validating/user
Make the spec.userID parameter of the User resource as deprecated and update relevant documentation.
Remove unneeded field and or related functionality.
Closes #5995
There would be no userID field and any related functionality.
```changes
type: chore
summary: Make the spec.userID parameter of the User resource as deprecated.
```
> [user-authn] Make the spec.userID parameter of the User resource as deprecated

- ee/candi/bashible/detect_bundle.sh
Change the pattern
Both versions work fine (even if the 10.2 is still in the development stage), but Deckhouse returns an error that the version is not supported
```changes
type: fix
summary: Add Altlinux 10.0, 10.2 support
```
> [bashible] Add Altlinux 10.0, 10.2 support

- modules/041-linstor/images/linstor-server/liveness.sh
- modules/041-linstor/images/piraeus-operator/patches/050-change-liveness-probe.patch
Changes in controller liveness probe
Currently, the controller may lose connection with the satellite and not attempt to restore it. However, when viewing the list of satellites, they all appear online.
Restarting the controller when the connection with the satellites is lost with the above-mentioned symptoms.
```changes
type: fix
summary: Changes in controller liveness probe
```
> [linstor] changes in controller liveness probe

- candi/version_map.yml
Add ALT Linux 10.0, 10.2 to the version_map.yml.
Ref: https://github.com/deckhouse/deckhouse/pull/6215
```changes
section: candi
type: chore
summary: Add ALT Linux 10.0, 10.2 to the version_map.yml.
```
> [candi] Update version_map.yml

- modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring/node.yaml
To update extended monitoring node disk usage rules so that the kubelet_eviction_threshold metrics aren't taken into consideration when calculating whether warning/critical disk usage thresholds are reached.
Closes #6209 
At the moment, node disk usage rules of the extended monitoring aren't working because there is faulty `unless` math there. It hadn't worked before (label sets between two `unless` parts couldn't match technically) some recent changes to extended-monitoring introduced `mountpoint` label to `kubelet_eviction metrics` rendering them eligible for `unless` to proceed.
After removing `unless` condition, node disk usage rules should work fine.
Such extended-monitoring alerts like `NodeDiskBytesUsage` should work correctly and trigger on warning/critical thresholds for root …
> [extended-monitoring] remove unless kube-eviction from node-usage rules

- deckhouse-controller/files/bashrc
Fix bash completion.
bash completion doesn't work in deckhouse pod after removing support for kubernetes 1.23
```changes
type: fix
summary: Fix bash completion
```
> [deckhouse] Fix bash completion

- dhctl/pkg/app/preflight.go
- dhctl/pkg/config/meta.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/preflight/preflight.go
- dhctl/pkg/preflight/registry.go
- dhctl/pkg/preflight/registry_test.go
- dhctl/pkg/preflight/ssh.go
- dhctl/pkg/preflight/suite_test.go
Added a preflight check that tries to reach registry api using a proxy if one is given and registry address is not blacklisted for proxying.
```changes
section: dhctl
type: feature
summary: Dhctl will check if container registry can be reached with provided HTTP\HTTPS proxy
```
> [dhctl] Check if registry can be reached through proxy

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/capacity-planning/capacity-planning.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/namespace/namespaces.json
Filter non-Running pods from calculating requested and unrequested CPU and memory statistics in Capacity Planning dashboard by adding `* on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"}`
Non-running pods were used in calculation which lead to values different from `describe node`, request values over 100% and negative unrequested values
previous issue https://github.com/deckhouse/deckhouse/issues/2657
```changes
type: fix
```
> [monitoring-kubernetes] Remove non-running pods from requested and unrequested resources calculation in dashboard

- ee/modules/650-runtime-audit-engine/templates/falco-rules.yaml
Set Notice priority for rules requiring notification of security officer
Increased priority allows clarifying alerts [creation](https://deckhouse.io/documentation/v1/modules/650-runtime-audit-engine/faq.html#how-to-create-an-alert).
```changes
type: fix
summary: Set Notice priority for rules requiring notification of security officer
```
> [runtime-audit-engine] Set Notice priority for rules requiring notification of security officer

- modules/465-pod-reloader/images/pod-reloader/Dockerfile
- modules/465-pod-reloader/images/pod-reloader/werf.inc.yaml
The podreloader docker image is now distroless.
<details>
```shell
v.snurnitsin@thinkpad:/tmp/tmp$ docker save dev-registry.deckhouse.io/sys/deckhouse-oss@sha256:bfe3f35dd56fcc08334fffcb54294af96549fe53d4279b2eba0e03b3d1cc32c1 > 1.tar
v.snurnitsin@thinkpad:/tmp/tmp$ tar xvf 1.tar 
30526b51275d9a1659f5348b7aa34b0c228d15edfd91ab97560cd73cfeced9ac/
30526b51275d9a1659f5348b7aa34b0c228d15edfd91ab97560cd73cfeced9ac/VERSION
30526b51275d9a1659f5348b7aa34b0c228d15edfd91ab97560cd73cfeced9ac/json
30526b51275d9a1659f5348b7aa34b0c228d15edfd91ab97560cd73cfeced9ac/layer.tar
5b6d519671356c1db31c2b33fd2ddda7d0e6233cf4a4c8aa498d804e8778f396/
5b6d519671356c1db31c2b33fd2ddda7d0e6233cf4a4c8aa498d804e8778f396/VERSION
5b6d519671356c1db31c2b33fd2ddda7d0e6233cf4a4c8aa498d804e8778f396/json …
```
> [podreloader] distroless

- candi/openapi/doc-ru-node_group.yaml
- docs/documentation/werf-git-section.inc.yaml
- modules/040-node-manager/crds/doc-ru-nodegroupconfiguration.yaml
Ref: b5cb17b87e9ff0e870438e69aedb18e1f58993fe
Ref: https://github.com/deckhouse/deckhouse/pull/5432
Remove internal CRDs from the documentation.
```changes
section: docs
type: chore
summary: Remove internal CRDs from the documentation.
```
> [docs][capi] Documentation updates

- candi/bashible/preflight/check_localhost.sh
- candi/bashible/preflight/check_ports.sh
- dhctl/go.mod
- dhctl/pkg/app/preflight.go
- dhctl/pkg/kubernetes/actions/deckhouse/delete.go
- dhctl/pkg/kubernetes/actions/deckhouse/install.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/preflight/dhctl_obsolescence.go
- dhctl/pkg/preflight/dhctl_obsolescence_test.go
- dhctl/pkg/preflight/domain.go
- dhctl/pkg/preflight/ports.go
- dhctl/pkg/preflight/preflight.go
- dhctl/pkg/preflight/registry.go
- dhctl/pkg/preflight/ssh.go
- dhctl/pkg/preflight/suite_test.go
- dhctl/pkg/util/retry/retry.go
Adjusted image tag selection logic to allow usage of deckhouse version tag from `/deckhouse/version` for installation. Deckhouse is now bootstrapped using this tag.
Also preflight checks code was refactored.
And refactored preflight check error messages.
Fixes #3251 
```changes
section: dhctl
type: feature
summary: Allow installing Deckhouse from tag. Refactor preflight checks code.
```
> [dhctl] Bootstrap deckhouse with a version tag instead of release channel tag and refactor preflight checks messages

- modules/002-deckhouse/hooks/check_deckhouse_release_test.go
- modules/002-deckhouse/hooks/internal/updater/updater.go
- modules/002-deckhouse/hooks/update_deckhouse_image_test.go
Don't respect DeckhouseRelease applyAfter on manual updates
https://github.com/deckhouse/deckhouse/issues/6188
In manual mode, deckhouse is updated regardless of the presence of the applyAfter release field
```changes
type: fix
summary: Canary release disabled for manual update mode
```
> [deckhouse] don't respect DeckhouseRelease applyAfter on manual updates

- modules/465-pod-reloader/templates/deployment.yaml
- modules/465-pod-reloader/templates/rbac-for-us.yaml
* Run pod-reloader from deckhouse user.
* Added access to `cronjobs` and `jobs`.
* Running from the d8 user fixes error `access /reloader: permission denied`.
* Extending access rights eliminates warnings.
<details>
```shell
root@kube-master-0:~# kubectl -n d8-pod-reloader get po
NAME                            READY   STATUS    RESTARTS   AGE
pod-reloader-7654f7dd7d-p9k8f   2/2     Running   0          5m22s
root@kube-master-0:~# kubectl -n d8-pod-reloader logs pod-reloader-7654f7dd7d-p9k8f 
Defaulted container "manager" out of: manager, kube-rbac-proxy
time="2023-10-20T08:26:50Z" level=info msg="Environment: Kubernetes"
{"level":"info","msg":"Starting Reloader","time":"2023-10-20T08:26:50Z"}
{"level":"warning","msg":"KUBERNETES_NAMESPACE is unset, will detect changes in all …
```
> [pod-reloader] Run as deckhouse user

- dhctl/pkg/kubernetes/actions/deckhouse/install.go
- dhctl/pkg/kubernetes/actions/deckhouse/install_test.go
- dhctl/pkg/preflight/ssh.go
- dhctl/pkg/system/ssh/cmd/scp.go
- dhctl/pkg/system/ssh/cmd/ssh.go
Add SSH debug options if dhctl debug is enabled and increase ssh timeouts
ssh debug  flags did not work.
```changes
section: dhctl
type: chore
summary: Add SSH debug options if dhctl debug is enabled and increase ssh timeouts.
```
> [dhctl] Add SSH debug options if dhctl debug is enabled and increase ssh timeouts

- docs/documentation/werf-git-section.inc.yaml
Hide staticcluster CRD on the site.
```changes
section: docs
type: chore
summary: Hide staticcluster CRD on the site.
```
> [docs][node-manager] Hide staticcluster CRD on the site

- modules/030-cloud-provider-yandex/docs/FAQ.md
- modules/030-cloud-provider-yandex/docs/FAQ_RU.md
Add FAQ paragraph on how to set custom StorageClass as default
Original issue https://github.com/deckhouse/deckhouse/issues/6213
```changes
type: chore
```
> [cloud-provider-yandex][docs] Setting custom storageclass as default FAQ

- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-altlinux-like.yaml
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-centos-like.yaml
- modules/041-linstor/templates/nodegroupconfiguration-drbd-install-debian-like.yaml
Changed the method of loading DRBD kernel module on the nodes with active LINSTOR satellites.
On some recent versions of CentOS-based distributions, the old method of loading DRBD has stopped working.
Some of our clients occasionally experience issues due to DRBD's module not loaded in CentOS-based distros. 
Correctly loaded DRBD module on any OS version.
```changes
type: fix
summary: Changed the method of loading DRBD kernel module on the nodes with active LINSTOR satellites.
```
> [linstor] fixed DRBD kernel module load

- go_lib/dependency/vsphere/vsphere.go
Datastores containing `-` in their name did not match the regexp and their names were not converted to lowercase.
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
```changes
type: fix
summary: Fix slugify datastore name containing "-"
```
> [cloud-provider-vsphere] Fix slugify datastore name containing "-"

- modules/000-common/images/python-static/Setup.local
- modules/000-common/images/python-static/werf.inc.yaml
- modules/340-monitoring-ping/images/monitoring-ping/Dockerfile
- modules/340-monitoring-ping/images/monitoring-ping/werf.inc.yaml
- modules/340-monitoring-ping/templates/daemon-set.yaml
- testing/library/images_tags_generated.go
Switch monitoring-ping to use distroless image and static build a python
Unification of the approach to the development of module images
```changes
type: feature
summary: Switch monitoring-ping to use distroless image and static build a python
```
> [monitoring-ping] switch to distroless

- modules/300-prometheus/images/alertmanager/Dockerfile
[CVE-2022-41723](https://access.redhat.com/security/cve/CVE-2022-41723)
```changes
type: fix
summary: Fixed HIGH CVE issues in alertmanager image
impact: Check that the alerts come after the update
```
> alertmanager cve issues

- candi/bashible/bootstrap.sh.tpl
- modules/040-node-manager/crds/cluster.yaml
- modules/040-node-manager/crds/extension-config.yaml
- modules/040-node-manager/crds/machine-deployment.yaml
- modules/040-node-manager/crds/machine-health-check.yaml
- modules/040-node-manager/crds/machine-pools.yaml
- modules/040-node-manager/crds/machine-sets.yaml
- modules/040-node-manager/crds/machine.yaml
- modules/040-node-manager/hooks/generate_capi_static_kubeconfig_secret.go
- modules/040-node-manager/images/caps-controller-manager/src/internal/client/bootstrap.go
- modules/040-node-manager/templates/node-group/_bootstrap.tpl
- modules/040-node-manager/templates/node-group/_cloud_init_cloud_config.tpl
1. Fix CAPI kubeconfig hook, which cannot work on fresh installations. Running this hook after helm deployment.
2. Send name of capi machine to the bootstrapped node to properly patch corresponding instance status field.
3. Instance for cluster-api static instance now enriched with logs info same as for cloud instances.
```
bootstrapStatus:
description: Use 'nc x.x.x.x 8000' to get bootstrap logs.
logsEndpoint: x.x.x.x:8000
```
To see the logs from instance run command from master node:
`nc x.x.x.x 8000` now tails logs.
Bootstrap logs now saved to `/opt/deckhouse/tmp/bootstrap.log`.
4. Removed shortNames from CAPI crds.
1. On the fresh install if we try to deploy NG with staticInstances field, we've got an error from deckhouse controller, due to improper order of running …
> [candi] cluster-api static controller various improvements

- modules/000-common/images/kube-rbac-proxy/werf.inc.yaml
- [CVE-2021-3121](https://access.redhat.com/security/cve/CVE-2021-3121)
- [CVE-2022-21698](https://access.redhat.com/errata/RHSA-2022:8057)
- [CVE-2020-29652](https://access.redhat.com/security/cve/CVE-2020-29652)
- [CVE-2021-43565](https://access.redhat.com/security/cve/CVE-2021-43565)
- [CVE-2022-27191](https://access.redhat.com/errata/RHSA-2022:8008)
- [CVE-2021-33194](https://access.redhat.com/security/cve/CVE-2021-33194)
- [CVE-2022-27664](https://access.redhat.com/errata/RHSA-2023:2357)
- [CVE-2021-38561](https://access.redhat.com/security/cve/CVE-2021-38561)
- [CVE-2022-32149](https://access.redhat.com/security/cve/CVE-2022-32149)
```changes
type: fix …
```
> [common] fix cve issues in kube-rbac-proxy image

- go_lib/hooks/ensure_crds/hook.go
- go_lib/hooks/ensure_crds/hook_test.go
- go_lib/hooks/ensure_crds/test_data/huge.crd
- go_lib/hooks/ensure_crds/test_data/invalid.crd
Fix hook logic
If yaml document has only comment it was rendered as CRD and through an error. We can ignore such situations
```changes
type: fix 
summary: Fix EnsureCRDs hook - reading an empty yaml document should't trigger an error.
```
> [go_lib] Fix EnsureCRDs hook

- dhctl/cmd/dhctl/commands/mirror.go
- dhctl/cmd/dhctl/main.go
- dhctl/go.mod
- dhctl/pkg/app/mirror.go
- dhctl/pkg/log/logger.go
- dhctl/pkg/log/options.go
- dhctl/pkg/operations/mirror.go
- dhctl/pkg/operations/mirror/context.go
- dhctl/pkg/operations/mirror/digests.go
- dhctl/pkg/operations/mirror/index.go
- dhctl/pkg/operations/mirror/layouts.go
- dhctl/pkg/operations/mirror/modules.go
- dhctl/pkg/operations/mirror/pull.go
- dhctl/pkg/operations/mirror/util.go
- dhctl/pkg/operations/mirror/validate.go
- dhctl/pkg/operations/mirror/versions.go
- dhctl/pkg/util/maputil/maputil.go
- dhctl/pkg/util/maputil/maputil_test.go
Added `mirror` subcommand for dhctl, that allows to copy a particular set of Deckhouse releases to a local filesystem and then push that copy to some third-party registry. 
This subcommand does not support copying of Community Edition images.
Example of copying current Deckhouse-release channels images to local filesystem mounted into `/d8-images`:
```bash
dhctl mirror -l "license-token" -i /d8-images
```
Or, to copy Deckhouse images starting from release 1.49 to local filesystem mounted into `/d8-images`.
```bash
dhctl mirror --license="license-token" --min-version="1.49" --images=/d8-images
```
To copy downloaded images into third-party registry:
```bash
dhctl mirror --images="/d8-images" --registry="registry.infra.int:5000" --registry-login="user" --registry-password="pass" 
```
Or in …
> [dhctl] Deckhouse registry mirroring

- modules/402-ingress-nginx/images/kruise/werf.inc.yaml
- [CVE-2023-2253](https://access.redhat.com/security/cve/CVE-2023-2253)
- [CVE-2023-28840](https://access.redhat.com/security/cve/CVE-2023-28840)
- [CVE-2023-27561](https://access.redhat.com/security/cve/CVE-2023-27561)
- [CVE-2022-28948](https://access.redhat.com/security/cve/CVE-2022-28948)
```changes
type: fix
summary: fix cve issues in kruise image
```
> [ingress-nginx] fix cve issues in kruise image

- modules/005-external-module-manager/hooks/handle_sources.go
Adds support for unpacking images with modules containing links.
Currently, when unpacking an image containing a module, only files and directories are unpacked.
If your module has other types of files, you will see a "unknown tar type" error.
It will create links if they exist.
```changes
type: fix
summary: add support for hardlinks and symlinks to the module
```
> [external-module-manager] add support for hardlinks and symlinks to the module

- modules/040-node-manager/templates/fix-containerd-start.yaml
Fix containerd deckhouse start after install new containerd-deckhouse package (now new containerd-deckhouse starts later, in 050_ step, which leads to possibly problems with node notReady for large amount of time)
When we updates from release 1.51 to 1.52, we've got a problem:
Containerd package is replaced with containerd-deckhouse package in 031_ step.
After that kubeletpackage downloads and install.
After that containerd config updated and containerd-deckhouse is started.
When downloading of kubelet takes significant amount of time, we get node notReady due to all this time containerd does not work.
```changes
section: candi
type: fix
summary: Fix deckhouse containerd start after installing new containerd-deckhouse package.
```
> [candi] Fix containerd deckhouse start

- modules/005-external-module-manager/crds/doc-ru-module-source.yaml
- modules/005-external-module-manager/crds/module-source.yaml
- modules/005-external-module-manager/hooks/handle_sources.go
- modules/005-external-module-manager/hooks/internal/apis/v1alpha1/source.go
- testing/openapi_validation/validators/enum.go
Support `http` scheme for registry with source modules
Some users can have insecure registry
```changes
type: feature
summary: Add support for module pull from insecure (http) registry.
```
> [external-module-manager] Support http scheme for a source registry

- modules/402-ingress-nginx/images/protobuf-exporter/go.mod
- modules/402-ingress-nginx/images/protobuf-exporter/go.sum
- [CVE-2022-28948](https://access.redhat.com/security/cve/CVE-2022-28948)
```changes
type: fix
summary: fix cve issues in protobuf-exporter image
```
> [ingress-nginx] fix cve issues it protobuf-exporter image

- modules/402-ingress-nginx/images/nginx-exporter/werf.inc.yaml
- [CVE-2022-21698](https://access.redhat.com/errata/RHSA-2022:8057)
```changes
type: fix
summary: fix cve issues in nginx-exporter image
```
> [ingress-nginx] fix cve issues in nginx-exporter image

- candi/bashible/bashbooster/50_deckhouse_registrypackages.sh
- modules/040-node-manager/templates/node-group/_bootstrap.tpl
- testing/cloud_layouts/Static/configuration.tpl.yaml
- testing/cloud_layouts/script.sh
1. Send bootstrap logs to console in case of manual bootstrap insead of sending to /opt/deckhouse/tmp/bootstrap.log.
2. Change tinyproxy image in static e2e tests.
3. Change TMP* variables in bashbooster to TMP_*.
1. When we manually bootstraps the node, we need to see any possible problems. It's inconvenient to look logs at the file. 
2. Sometimes e2e static tests fail due to improper work of tinyproxy image (container started, but not work).
3. Bashbootser uses TMPDIR variable which intersects with system TMPDIR variable.
```changes
section: candi
type: fix
summary: send bootstrap logs to console in case of manual bootstrap
```
> [candi] send bootstrap logs to console in case of manual bootstrap

- deckhouse-controller/cmd/deckhouse-controller/main.go
- dhctl/pkg/kubernetes/actions/manifests/manifests.go
- go.mod
- go.sum
- modules/002-deckhouse/templates/deployment.yaml
- tools/go.sum
Update addon-operator and explicitly set run flags
Starts with JSON logs:
```
{"msg": "-- Starting Deckhouse using bundle Default --"}
{"level":"info", "msg": "New deckhouse PID 14"}
{"level":"info","msg":"Create metric histogram deckhouse_kubernetes_client_request_latency_seconds","operator.component":"metricsStorage","time":"2023-10-30T10:38:35Z"}
{"level":"info","msg":"Create metric counter deckhouse_kubernetes_client_request_result_total","operator.component":"metricStorage","time":"2023-10-30T10:38:35Z"}
{"level":"info","msg":"Kubernetes client is configured successfully with 'out-of-cluster' config","operator.component":"KubernetesAPIClient","time":"2023-10-30T10:38:35Z"}
{"level":"info","msg":"Kubernetes client is configured successfully with 'out-of-cluster' …
```
> [deckhouse-controller] Fix flags for logging and kube-client qps

- modules/340-monitoring-kubernetes/images/kube-state-metrics/Dockerfile
- [CVE-2022-1996](https://access.redhat.com/security/cve/CVE-2022-1996)
- [CVE-2022-27664](https://access.redhat.com/errata/RHSA-2023:2357)
- [CVE-2022-32149](https://access.redhat.com/security/cve/CVE-2022-32149)
Fixed CRITICAL and HIGH CVE issues
```changes
type: fix
summary: fix cve issues in kube-state-metrics image
```
> [monitoring-kubernetes] fix cve issues in kube-state-metrics image

- modules/402-ingress-nginx/crds/kruise/crd_daemonsets.yaml
- modules/402-ingress-nginx/templates/controller/controller.yaml
- modules/402-ingress-nginx/templates/failover/daemonset.yaml
Add default value of `1` to  the .`spec.replicas` field of the kruise daemonset CRD.
Add some extra labels to ingress-nginx PDBs to make them recalculate their state.
It fixes a migration problem when we update kruise controller to the revision where PDB support is enabled, but `.spec.replicas` isn't set yet so the controller can't get it with `GetScale` method.
Advanced daemonsets get initial value of `.spec.replicas` set to 1 and further updates are performed by open kruise controller according to its logic.
To check: `kubectl get ads -n d8-ingress-nginx -o yaml | grep relicas`
```changes
section: Ingress-nginx
type: chore
summary: Update kruise daemonsets' specs with default .spec.replicas value.
```
> [ingress-nginx] add default .spec.replicas value

- modules/402-ingress-nginx/images/kruise-state-metrics/werf.inc.yaml
- [CVE-2022-21698](https://access.redhat.com/errata/RHSA-2022:8057)
- [CVE-2021-43565](https://access.redhat.com/security/cve/CVE-2021-43565)
- [CVE-2022-27191](https://access.redhat.com/errata/RHSA-2022:8008)
- [CVE-2022-27664](https://access.redhat.com/errata/RHSA-2023:2357)
- [CVE-2022-32149](https://access.redhat.com/security/cve/CVE-2022-32149)
- [CVE-2022-28948](https://access.redhat.com/security/cve/CVE-2022-28948)
```changes
type: fix
summary: fix cve issues in kruise-state-metrics image
```
> [ingress-nginx] fix cve issues in kruise-state-metrics image

- modules/340-extended-monitoring/docs/CONFIGURATION.md
- modules/340-extended-monitoring/docs/CONFIGURATION_RU.md
- modules/340-extended-monitoring/images/extended-monitoring-exporter/src/extended-monitoring.py
The NodeDiskInodesUsage alert had a value lower than the corresponding eviction threshold parameter from kubelet, which led to premature alerts (without the ability to fix the problem directly - releasing inodes in the kubelet occurs automatically when the soft eviction threshold is reached).
The solution is to set the default threshold values corresponding to the system ones, so that the alert notifies when a problem really exists.
Kubelet soft eviction values hardcoded here: https://github.com/deckhouse/deckhouse/blob/2af949365a368dabe2e09d7936f6827fa1bef6dd/candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl#L94
```changes
type: chore
summary: Fix `NodeDiskInodesUsage` alert threshold values.
```
> [extended-monitoring] Fix NodeDiskInodesUsage alert threshold values according to kubelet default

- modules/000-common/images/csi-external-attacher/werf.inc.yaml
- modules/000-common/images/csi-external-provisioner/werf.inc.yaml
- modules/000-common/images/csi-external-resizer/werf.inc.yaml
- modules/000-common/images/csi-external-snapshotter/werf.inc.yaml
Fixed build csi-external-* images
<details>
before
```shell
Status: Image is up to date for registry.deckhouse.io/deckhouse/fe/install:stable
[deckhouse] root@04f534d56612 / # cat /deckhouse/candi/images_digests.json | grep csiE | sort -V
"csiExternalAttacher123": "sha256:635e7eb58d71d692f29c5dfa832631adb60c4b546bbca3deb8eb21627b6d7c5a",
"csiExternalAttacher124": "sha256:635e7eb58d71d692f29c5dfa832631adb60c4b546bbca3deb8eb21627b6d7c5a",
"csiExternalAttacher125": "sha256:635e7eb58d71d692f29c5dfa832631adb60c4b546bbca3deb8eb21627b6d7c5a",
"csiExternalAttacher126": "sha256:635e7eb58d71d692f29c5dfa832631adb60c4b546bbca3deb8eb21627b6d7c5a",
"csiExternalAttacher127": "sha256:635e7eb58d71d692f29c5dfa832631adb60c4b546bbca3deb8eb21627b6d7c5a",
"csiExternalProvisioner123": …
```
> [common] Fix build csi-external-* images

- modules/040-node-manager/images/bashible-apiserver/go.mod
- modules/040-node-manager/images/bashible-apiserver/go.sum
Bumped versions of `github.com/Masterminds/goutils` to 1.1.1 and `google.golang.org/grpc` to 1.56.3
```changes
type: fix
summary: Fix CVE-2021-4238 and  GHSA-m425-mq94-257g in bashible-apiserver
```
> [node-manager] Fix CVE-2021-4238 and  GHSA-m425-mq94-257g in bashible-apiserver

- modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring/application-controllers.yaml
- modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
Improves the command for finding nodes on which pods do not work
```changes
type: fix 
summary: changed the node search command for ds
```
> [monitoring] changed the node search command for ds pods

- candi/bashible/bashible.sh.tpl
Force bashible start after node reboot.
We consider a node to be ready after a bashible successful run.
```changes
section: candi
type: chore
summary: force bashible start after node reboot
```
> [candi] force bashible start after node reboot

- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
Fix incorrect StorageClass for the Longterm Prometheus in the Getting Started for bare metal.
```changes
section: docs
type: chore
summary: Fix incorrect StorageClass for the Longterm Prometheus in the Getting Started for bare metal.
```
> [docs][getting-started] Fix incorrect StorageClass for the Longterm Prometheus

- modules/031-local-path-provisioner/images/local-path-provisioner/werf.inc.yaml
- [CVE-2022-21698](https://avd.aquasec.com/nvd/cve-2022-21698)
- [CVE-2021-43565](https://avd.aquasec.com/nvd/cve-2021-43565)
- [CVE-2022-27191](https://avd.aquasec.com/nvd/cve-2022-27191)
- [CVE-2021-33194](https://avd.aquasec.com/nvd/cve-2021-33194)
- [CVE-2022-27664](https://avd.aquasec.com/nvd/cve-2022-27664)
- [CVE-2022-41723](https://avd.aquasec.com/nvd/cve-2022-41723)
- [CVE-2021-38561](https://avd.aquasec.com/nvd/cve-2021-38561)
- [CVE-2022-32149](https://avd.aquasec.com/nvd/cve-2022-32149)
```changes
type: fix
summary: fix cve issues in local-path-provisioner image
```
> [local-path-provisioner] fix cve issues in local-path-provisioner image

- modules/030-cloud-provider-yandex/images/cloud-metrics-exporter/werf.inc.yaml
- modules/030-cloud-provider-yandex/templates/cloud-metrics-exporter/deployment.yaml
This PR is a part of moving Deckhouse to distroless.
```changes
section: cloud-provider-yandex | cloud-metrics-exporter
type: chore
summary:"`cloud-metrics-exporter` use distroless based image."
```
> [distroless] chore: yandex-cloud-metrics-exporter to distroless

- go_lib/dependency/cr/cr.go
- modules/002-deckhouse/hooks/check_deckhouse_release.go
Send clusterUUID when checking for deckhouse release
We want to know cluster uuid when registry is accessed.
Before
```
http.request.useragent="go-containerregistry/v0.5.1"
```
After
```
http.request.useragent="bb6781c1-b38c-4ba8-9f8a-ff0feac51a66 go-containerregistry/v0.5.1"
```
```changes
type: chore
summary: Send clusterUUID when checking for deckhouse release
```
> [deckhouse] Send clusterUUID when checking for deckhouse release

- docs/site/_includes/getting_started/bm-private/partials/config.yml.ce.inc
- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
- docs/site/_includes/getting_started/bm/partials/config.yml.ce.inc
- docs/site/_includes/getting_started/global/step_cluster_setup.html
- docs/site/_includes/getting_started/global/step_cluster_setup_ru.html
1. Updated the config for the private environment in GS.
Added parameters:
```
global: modules.https.certManager.clusterIssuerName: selfsigned
cert-manager: disableLetsencrypt
contol-plane-manager: controlPlaneConfigurator.dexCAMode: FromIngressSecret
```
2. Removed the creation of a separate Storage Class for Prometheus.
3. Added a global Storage Class for system components.
4. Fixed the text at the 3rd step of installation in a private environment.
This will help to improve the installation of the platform in a private environment.
```changes
section: docs
type: chore
summary: Make the Getting Started more consistent.
```
> [getting-started][docs] Fix main config in private envinronment

- modules/460-log-shipper/apis/v1alpha1/cluster_log_destination.go
- modules/460-log-shipper/crds/cluster-log-destination.yaml
- modules/460-log-shipper/crds/doc-ru-cluster-log-destination.yaml
- modules/460-log-shipper/hooks/internal/vector/destination/common.go
- modules/460-log-shipper/hooks/internal/vector/destination/kafka.go
- modules/460-log-shipper/hooks/internal/vector/transform/cef.go
- modules/460-log-shipper/hooks/internal/vector/transform/destination.go
- modules/460-log-shipper/hooks/internal/vrl/cef.go
- modules/460-log-shipper/hooks/testdata/file-to-kafka-tls/manifests.yaml
- modules/460-log-shipper/hooks/testdata/file-to-kafka-tls/result.json
- modules/460-log-shipper/images/vector/Dockerfile
- modules/460-log-shipper/images/vector/patches/README.md
- modules/460-log-shipper/images/vector/patches/cef-encoder.patch
This PR adds an option to encode messages to CEF format (often accepted by SIEM systems, such as KUMA (Kaspersky Unified Monitoring and Analysis Platform).
> The Common Event Format (CEF) is a standardized logging format developed by ArcSight (now part of Micro Focus), a security information and event management (SIEM) solution provider. CEF is designed to simplify the process of logging security-related events and making it easier to integrate logs from different sources into a single system. CEF is based on the syslog format, which is a standard for message logging that is supported by most network devices and operating systems.
As of today, only Kafka is supported, but the feature is generic enough and can be exposed to other destinations in the future.
Deckhouse has security events …
> [log-shipper] Add CEF encoder

- ee/modules/380-metallb/images/artifact/werf.inc.yaml
- ee/modules/380-metallb/templates/controller/deployment.yaml
Fix error with preserving controller internal state after reboot.
There is an LB service with a specific IP (annotated) assigned to it.
Also there are other LB services in the cluster on "pending".
MetalLB's controller resets and when it goes back up again,
it loops over the services, sees first the "pending" LB service,
and assigns it the IP that was assigned to the annotated service.
Upstream PR - https://github.com/metallb/metallb/pull/2004
<details><summary>before</summary>
```shell
main-load-balancer-01   LoadBalancer   10.222.13.26     10.220.212.17   80:30829/TCP   2m5s
main-load-balancer-02   LoadBalancer   10.222.215.6     10.220.212.18   80:30959/TCP   53s
main-load-balancer-03   LoadBalancer   10.222.178.136   10.220.212.19   80:31481/TCP   53s
main-load-balancer-04 …
```
> [metallb] fix error with preserving controller internal state after reboot

- dhctl/Makefile
- dhctl/pkg/operations/mirror/layouts.go
Static build of dhctl
We want to be able to use dhctl outside of installer container for mirroring, so we need to bundle all of it's dependencies
```changes
section: dhctl
type: chore
summary: Build dhctl as static binary
```
> [dhctl] Static build

- modules/005-external-module-manager/hooks/create_deckhouse_modules_source.go
- modules/005-external-module-manager/hooks/internal/apis/v1alpha1/source.go
Fix ModuleSource recreation.
Every time patching a ModuleSource can stuck the queue. Because it tries to purge schema
```changes
type: fix 
summary: Fix deckhouse ModuleSource recreation on startup.
```
> [external-module-manager] fix deckhouse ModuleSource recreation

- modules/200-operator-prometheus/templates/rbac-for-us.yaml
Fix RBAC for updating alertmanager status.
Without this we can see in logs:
```
level=error ts=2023-11-08T10:09:33.267498071Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"d8-monitoring/sre\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"sre\" is forbidden: User \"system:serviceaccount:d8-operator-prometheus:operator-prometheus\" cannot update resource \"alertmanagers/status\" in API group \"monitoring.coreos.com\" in the namespace \"d8-monitoring\""
```
```changes
type: fix
summary: Fix RBAC for updating alertmanager status.
```
> [operator-prometheus] Fix rbac for alertmanager

- modules/200-operator-prometheus/images/prometheus-operator/werf.inc.yaml
- [CVE-2023-39325](https://github.com/deckhouse/deckhouse/pull/golang.org/x/net)
```changes
type: fix
summary: Fix CVE issues in `operator-prometheus` image.
```
> [operator-prometheus] fix cve in prometheus-operator image

- dhctl/cmd/dhctl/commands/mirror.go
- dhctl/pkg/app/mirror.go
- dhctl/pkg/operations/mirror.go
- dhctl/pkg/operations/mirror/context.go
- dhctl/pkg/operations/mirror/digests.go
- dhctl/pkg/operations/mirror/layouts.go
- dhctl/pkg/operations/mirror/modules.go
- dhctl/pkg/operations/mirror/versions.go
`dhctl mirror` subcommand's `--registry` flag now supports use of full paths of registry repository to specify where to upload Deckhouse images. 
If only the FQDN or `host:port` is provided, it falls back to default of `/deckhouse/ee` or `/deckhouse/fe` paths for EE and FE respectfully
```changes
section: dhctl
type: feature
summary: dhctl now supports uploading mirrored Deckhouse images to custom repo paths
```
> [dhctl] Support for uploading mirrored Deckhouse images to custom repo path

- modules/040-node-manager/templates/node-group/_bootstrap.tpl
Do not use cloud network setup scripts for static nodegroups
When we try to bootstrap static node in cloud environment, we've got a problem with cloud-network-init bashible scripts, due to nodes created manually and doesn't have appropriate metadata entries (for example, node-cidr in yandex cloud). 
We assume such nodes network should be configured manually.
```changes
section: candi
type: fix
summary: do not use cloud network setup scripts for static nodegroups
```
> [candi] do not use cloud network setup scripts for static nodegroups

- modules/040-control-plane-manager/hooks/effective_kubernetes_version.go
- modules/040-control-plane-manager/hooks/effective_kubernetes_version_test.go
- modules/040-control-plane-manager/openapi/values.yaml
- modules/040-control-plane-manager/requirements/check.go
- modules/040-control-plane-manager/requirements/check_test.go
Previously we used a minimal version of control-plane to restrict Deckhouse updates. Now we take the minimum version in the whole cluster.
We need to wait until the cluster is fully upgraded to the target version of k8s before upgrading Deckhouse. This will reduce the number of possible problems when updating k8s and Deckhouse at the same time
Running without requirements is ok
Add release with requirements is blocking release
Upgrade 1.25 -> 1.26 is ok, with requirements exist
block updating one node group for checking blocking update
One node was updated one was not. Requirements still exist and its target behavior.
Second node was updated. All cluster was updated to desired version and requirements was gone
```changes
type: fix
summary: Use minimal …
```
> [control-plane-manager] Use minimal kubernetes version for minimal support k8s version Deckhouse requirement

- modules/040-node-manager/images/caps-controller-manager/werf.inc.yaml
Move caps-controller image to distroless.
Unification of the approach to the development of module images
```changes
section: candi
type: chore
summary: Move caps-controller image to distroless.
impact: caps-controller should be restarted
```
> [candi] move caps-controller image to distroless

- candi/version_map.yml
- modules/000-common/images/csi-external-attacher/werf.inc.yaml
- modules/000-common/images/csi-external-provisioner/werf.inc.yaml
- modules/000-common/images/csi-external-resizer/werf.inc.yaml
- modules/000-common/images/csi-external-snapshotter/werf.inc.yaml
Fixed vulnerabilities: CVE-2023-44487, CVE-2022-41723, GHSA-m425-mq94-257g
<details><summary>trivy report</summary>
```shell
[deckhouse] root@b948a088bb62 / # cat /deckhouse/candi/images_digests.json | grep csiE | sort -V
"csiExternalAttacher124": "sha256:793ad7a88134fb4a847eacf055ed0ef376cdca1efcae3039e70547ef3f11f3c7",
"csiExternalAttacher125": "sha256:793ad7a88134fb4a847eacf055ed0ef376cdca1efcae3039e70547ef3f11f3c7",
"csiExternalAttacher126": "sha256:793ad7a88134fb4a847eacf055ed0ef376cdca1efcae3039e70547ef3f11f3c7",
"csiExternalAttacher127": "sha256:6b6f2cc3ce4d175208c51f03499f87df7d74c9e2153b7978df043c34bcce9a6a",
"csiExternalAttacher128": "sha256:8ff8cc34f5e31dc13c09e60021ff7d5b663914b017ff527ceeda31d46e01d71b",
"csiExternalProvisioner124": …
```
> [common] Fix CVEs in csi-external-* images

- docs/site/_includes/getting_started/aws/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/azure/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/bm-private/partials/user.yml.inc
- docs/site/_includes/getting_started/bm/partials/user.yml.inc
- docs/site/_includes/getting_started/gcp/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/openstack/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/openstack_ovh/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/openstack_selectel/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/openstack_vk/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/vsphere/partials/resources.yml.minimal.inc
- docs/site/_includes/getting_started/yandex/partials/resources.yml.minimal.inc
- docs/site/js/getting-started.js
In the listings on GS pages, password generation with base64 has been added in accordance with #6030
Close https://github.com/deckhouse/deckhouse/issues/5587 – update Getting Started.
It will help to avoid problems when copying the password hash sum and executing the `sudo /opt/deckhouse/bin/kubectl create -f - << EOF...` command during GS execution.
GS improvement .
```changes
section: docs
type: chore
summary: Make the Getting Started more consistent.
```
> [getting-started][docs] Add base64 encoding to GS pages and JS-scripts

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Clarified that minimal installer version for using dhctl mirror is 1.54.2
Mirroring feature was backported from 1.55 to 1.54.2, doc needs an update
```changes
section: docs
type: chore
summary: Update minimal dhctl installer version for mirroring registry.
```
> [docs] Update minimal dhctl installer version for mirroring registry

- modules/150-user-authn/template_tests/user_test.go
- modules/150-user-authn/templates/dex/passwords.yaml
Adds userID field to dex Password manifest.
userID field was removed from dex password definition, but it's value is taken into account during JWT generation and not having userID set results in all JWT's having the same SUB field, breaking auth process.
It fixes JWT-based authentication.
dex password custom resources are created with userID field set to userName. It should fix the aforementioned JWT generation problem.
```changes
type: fix
summary: Provide userID field for correct JWT generation.
```
> [user-authn] revert deletion of userID from dex.password template

- dhctl/cmd/dhctl/commands/edit.go
- dhctl/cmd/dhctl/main.go
Fix edit `provider-cluster-configuration` command. Update only one field expect replace whole secret
Also fix not creating terraform auto-converger and terraform exporter pods
`edit provider-cluster-configuration` command remove discovery-data.json from `kube-system/d8-provider-cluster-configuration` secret
`edit provider-cluster-configuration` command remove discovery-data.json from kube-system/d8-provider-cluster-configuration secret
Terrafrm autoconverger  and terraform-exporter are running now.
Cluster configuration was edited
Provider cluster configuration
discovery data json kept
DHCTL work in container and static cluster config edited
```changes
section: dhctl
type: fix 
summary:Fix edit provider-cluster-configuration command remove discovery-data.json from …
```
> [dhctl] Fix `edit provider-cluster-configuration` command remove discovery-data.json from `kube-system/d8-provider-cluster-configuration` secret

- modules/150-user-authn/templates/dex/passwords.yaml
Add missing quotes.
It's better to have all properties as strings.
Add missing quotes.
Have no missing quotes.
```changes
type: fix
summary: Add missing quotes.
```
> [user-authn] add missing quotes

- modules/462-loki/images/loki/Dockerfile
- tools/cve/trivy-wrapper.sh
[CVE-2023-39325](https://github.com/deckhouse/deckhouse/pull/golang.org/x/net)
```changes
section: loki
type: fix
summary: fix cve issues in loki image
```
> [loki] fix cve in loki image

- go.mod
- go.sum
- go_lib/dependency/dependency.go
- tools/go.sum
Bump addon-operator
We have some races. More details [here](https://flant.slack.com/archives/C78AQG5EY/p1699533458369469)
Have to rollback some changes to avoid them
```changes
type: chore
summary: Bump `addon-operator` to avoid race panics.
```
> [global] avoid races

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
Update the documentation on backing up etcd.
The current option in the documentation does not work.
1.54 already uses an distroless image for etcd so this fix should be included in that version.
```changes
type: fix
summary: Update the documentation on backing up etcd.
```
> [control-plane-manager] updated the documentation on backing up etcd

- modules/340-monitoring-kubernetes/images/kube-state-metrics/Dockerfile
- modules/340-monitoring-kubernetes/templates/kube-state-metrics/deployment.yaml
https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.7.0 
Interesting features from this release are:
- exit code metrics
- asterisk for the allowed list's keys
```changes
type: chore
summary: Bump kube-state-metrics 2.7.0
```
> [monitoring-kubernetes] Bump kube-state-metrics 2.7.0

- candi/bashible/preflight/check_localhost.sh
- candi/bashible/preflight/check_ports.sh
- dhctl/pkg/preflight/dhctl_obsolescence.go
- dhctl/pkg/preflight/domain.go
- dhctl/pkg/preflight/ports.go
- dhctl/pkg/preflight/preflight.go
- dhctl/pkg/preflight/registry.go
- dhctl/pkg/preflight/ssh.go
Edited error texts for preflight checks.
We want to make sure it's clear what is wrong with the node and how to fix it.
```changes
section: dhctl
type: chore
summary: Clarified dhctl's preflight checks error messages
```
> [dhctl] Overhaul preflight checks error messages

- dhctl/cmd/dhctl/main.go
- dhctl/pkg/config/base.go
- dhctl/pkg/config/deckhouse_config.go
- dhctl/pkg/config/meta.go
- dhctl/pkg/kubernetes/actions/deckhouse/install.go
Create d8-system/install-data config map with Deckhouse version at install time.
We need to enable some features only new cluster with needed version.
```changes
section:dhctl
type: feature
impact: Add config map with install version
```
> [dhctl] Add config map with install version

- dhctl/cmd/dhctl/main.go
- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Fix mirror command is not available in container
Command is not available
Out of container mirror only available
All work in container
```changes
section: dhctl
type: fix
summary: Fix mirror command is not available in container
```
> [dhctl] Fix mirror command is not available in container

- modules/040-node-manager/hooks/update_node_group_status.go
Removes `ResourceVersion` field from `statusNodeGroup` struct and snapshot of the `040-node-manager/hooks/update_node_group_status.go` go hook.
There's a bug in `040-node-manager/hooks/update_node_group_status.go` go hook causing a looped process of updating node groups' statuses. The hook creates nodegroup snapshot including `metadata.ResourceVersion` field and that field's value is getting incremented each time any field of a nodegroup is updated (including `.status`). Also, the hook updates node groups's status fields `observed`/`processed` which results in incrementing `metatada.ResourceVersion` field, forming a loop.
Node groups' status updates aren't getting looped and node groups' events are still getting attached (referenced) in the `kubectl describe ng` output (was tested in …
> [node-manager] fix ng update loop

- ee/modules/140-user-authz/images/webhook/Dockerfile
- ee/modules/140-user-authz/images/webhook/cmd/healthcheck/main.go
- ee/modules/140-user-authz/images/webhook/web/client.go
- ee/modules/140-user-authz/images/webhook/web/server.go
- ee/modules/140-user-authz/templates/webhook/daemonset.yaml
An additional binary has been added to the image to replace the curl request with a client certificate
https://github.com/deckhouse/deckhouse/issues/6368
Health check passes successfully
```changes
type: fix
summary: Fixed liveness probe for user-authz-webhook
```
> [user-authz] user-authz-webhook livenessProbe

- modules/015-admission-policy-engine/templates/gatekeeper-deployment.yaml
fixed labels in anti-affinity for gatekeeper-controller
a component may end up on one node in ha mod
```changes
type: fix 
summary: fixed labels in anti-affinity for gatekeeper-controller 
```
> [admission-policy-engine] fixed labels in anti-affinity for gatekeeper-controller

- go.mod
- go.sum
Fixed panic when validating module config. 
More details: https://github.com/flant/go-openapi-validate/commit/232e994bd2a62215b9638d58671971e731835314
https://github.com/deckhouse/deckhouse/issues/6548
Deckhouse should not panic
```changes
type: fix
summary: Fixed panic when validating int in number field in module configuration
```
> [deckhouse] panic with istio module config

- modules/021-cni-cilium/templates/agent/daemonset.yaml
Fixing resourceManagement in Static mode
It was impossible to configure Static resource management for agents.
Fixes https://github.com/deckhouse/deckhouse/issues/6559.
There is a customer who can't configure resource management now.
Resorce management works both in Static and VPA mode.
```changes
type: fix
summary:  Fixed `resourceManagement` in the Static mode.
```
> [cni-cilium][agent] Fixing resourceManagement for Static mode

- dhctl/pkg/preflight/preflight.go
Delete unnecessary obsolescence image preflight check.
Now we always use version from file in image.
Cluster bootstrap fails with panic.
```
unknown - [info] - panic: You are probably using a development image. please use devBranch
unknown - [info] - goroutine 9 [running]:
unknown - [info] - github.com/deckhouse/deckhouse/dhctl/pkg/config.(*DeckhouseInstaller).GetImage(0xc000cad080, 0x40?)
unknown - [info] - 	/dhctl/pkg/config/deckhouse_config.go:116 +0x118
unknown - [info] - github.com/deckhouse/deckhouse/dhctl/pkg/preflight.(*Checker).fetchAndValidateDeckhouseImageHashFromReleaseChannel(0xc0002f04c0, {0x1f06b28?, 0xc000dc6540})
unknown - [info] - 	/dhctl/pkg/preflight/dhctl_obsolescence.go:125 +0xc8
```
```changes
section: dhctl
type: fix 
summary: Delete unnecessary obsolescence image …
```
> [dhctl] Fix delete unnecessary obsolescence image preflight check

- dhctl/pkg/kubernetes/actions/deckhouse/delete.go
- dhctl/pkg/kubernetes/actions/deckhouse/delete_test.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-abort.go
- dhctl/pkg/operations/destroy/deckhouse.go
- dhctl/pkg/operations/destroy/destroy.go
Add destroy for static cluster with cleanup CAPS machines and clean up control-plane nodes passed with `ssh-host`.
We need to add it for support static clusters in Deckhouse commander.
Needs for pilots.
Also tested re bootstrap after clean up.
```changes
section: dhctl
type: feature
summary: Support destroy command for static clusters
```
> [dhctl] Support destroy command for static clusters

- dhctl/pkg/config/deckhouse_config.go
Fix no parse version from version file as semantic version.
Panic during bootstrap
```
unknown - [info] - panic: You are probably using a development image. please use devBranch
unknown - [info] - goroutine 21 [running]:
unknown - [info] - github.com/deckhouse/deckhouse/dhctl/pkg/config.(*DeckhouseInstaller).GetImage(0xc0003fe000, 0x0?)
unknown - [info] - 	/dhctl/pkg/config/deckhouse_config.go:116 +0x118
unknown - [info] - github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes/actions/deckhouse.deckhouseDeploymentParamsFromCfg(0xc0003fe000)
unknown - [info] - 	/dhctl/pkg/kubernetes/actions/deckhouse/install.go:453 +0x45
unknown - [info] - github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes/actions/deckhouse.CreateDeckhouseDeploymentManifest(0x1c0c501?)
```
Cannot bootstrap clusters …
> [dhctl] Fix panic on getting tag during bootstrap

- candi/bashible/bootstrap.sh.tpl
Do not wait `Instance` status patch indefinitely during bootstrap. This step puts information "how to get bootstrap logs" into Instance resource. It's not critical, and waiting for it indefinitely, breaking bootstrap, is not reasonable.
If an `Instance` cannot be patched, which may be due to another problem and is not a reason to break bootstrap process, that very process breaks.
After finite number of failures, bootstrap continues.
```changes
section: candi
type: fix
summary: Do not wait Instance status patch indefinitely during bootstrap.
```
> [candi] Do not wait Instance status patch indefinitely during bootstrap

- modules/040-node-manager/webhooks/validating/node_group
- testing/cloud_layouts/GCP/WithoutNAT/configuration.tpl.yaml
Add guard for nodegroup validation  webhook in case when global module config is not exists.
Add test configuration for GCP cluster. 
Editing node group fail with message:
```
Execute hook"
"Traceback (most recent call last):"
"  File \"/hooks/040-node-manager/webhooks/validating/node_group\", line 191, in main"
"    hook::run \"$@\""
"  File \"/frameworks/shell/hook.sh\", line 17, in hook::run"
"    hook::_run_first_available_handler \"${HANDLERS}\""
"  File \"/frameworks/shell/hook.sh\", line 73, in hook::_run_first_available_handler"
"    ($handler) # brackets are to run handler as a subprocess"
"  File \"/hooks/040-node-manager/webhooks/validating/node_group\", line 134, in __main__"
"    customTolerationKeys=$(context::jq -e -r '.snapshots.deckhouse_config[0].filterResult' | yq  e …
```
> [node-manager] Fix node group validation webhook if global mc does not exists

- go_lib/dependency/cr/cr.go
- go_lib/dependency/cr/cr_test.go
We can ignore path for registry credentials
User can set auths like:
```
{
"auths": {
"registry.example.com:8032/modules": {
"auth": "YTpiCg=="
}
}
}
```
and out auth check will fail with `no auth data` if you check auth for `registry.example.com:8032/modules` source
We can avoid this
```changes
section: dependency
type: feature
summary: Ignore `/path` when checking registry credentials.
```
> [dependency] Ignore path for docker registry auths

- dhctl/pkg/kubernetes/actions/deckhouse/delete.go
- dhctl/pkg/operations/bootstrap/checks.go
Skip deleting master machine deployment and skip from waiting master machines.
Retry checking uuid in the cluster.
Destroy static cluster cannot finish successfully if master nodes was bootstrapped with CAPS.
Need for pilots,
```changes
section: Fix static cluster destroy
type: fix
summary: Fix static cluster destroy
```
> [dhctl] Fix static cluster destroy

- modules/150-user-authn/images/dex-authenticator/Dockerfile
- modules/150-user-authn/images/dex/Dockerfile
- modules/150-user-authn/images/kubeconfig-generator/Dockerfile
Fix vulnerabilities: 
- CVE-2022-41721
- CVE-2022-41723
- CVE-2023-39325
- CVE-2022-32149
- GHSA-m425-mq94-257g
- CVE-2021-33194
- CVE-2022-27664
- CVE-2022-21698
- CVE-2021-43565
- CVE-2022-27191
- CVE-2021-38561
- CVE-2020-29652
- CVE-2020-7919
- CVE-2020-9283
- CVE-2019-9512
- CVE-2019-9514
- CVE-2022-3064.
<details><summary>in cluster</summary>
```shell
root@dev-master-0:~# kubectl -n d8-user-authn get po
NAME                                    READY   STATUS    RESTARTS   AGE
dex-d9f9cb54b-sk5xn                     2/2     Running   0          23m
kubeconfig-generator-55c88d5fd9-5xrjd   1/1     Running   0          4m30s
root@dev-master-0:~# kubectl -n d8-user-authn logs dex-d9f9cb54b-sk5xn -c dex | head -n3
{"level":"info","msg":"Dex Version: DEV, Go Version: go1.20.5, Go OS/ARCH: …
```
> [user-authn] Fix CVEs

- candi/bashible/common-steps/all/005_disable_manage_iprules.sh.tpl
Fix disabling managing foreign IP rules by systemd-networkd.
If the systemd-networkd module did not exist in the operating system, the step would terminate with an error and the node installation could not proceed.
If the systemd-networkd module did not exist in the operating system (e.g. CentOS 8+), the bashible step completes correctly and does not crash with an error
```changes
section: candi
type: fix
summary: Fix disabling managing foreign IP rules by systemd-networkd.
```
> [candi] Fixing disabling managing foreign ip rules by systemd-networkd

- modules/005-external-module-manager/hooks/create_deckhouse_modules_source.go
- modules/005-external-module-manager/hooks/create_deckhouse_modules_source_test.go
- modules/005-external-module-manager/hooks/handle_sources.go
- modules/005-external-module-manager/openapi/values.yaml
* Reconcile all modules sources on startup. This affects client's registry load, but is more error pron.
* Always deploy the module source for deckhouse modules (since as of today dhctl mirror command copies the module source to private registries by default).
In the module values, checksum map looks like
```
externalModuleManager:
internal:
modulesChecksums:
inspektor-gadget:
inspektor-gadget: sha256:155628253a07fd119c179ec175658b7ce5012c5bfa9512b28323e2f24d9228b8
```
an it is dropped on restarts.
The first fix is applied to survive the situation when dechkouse the problem that module was downloaded but there is no module release in the cluster. The assumption is that the situation occurs when deckhouse is restarted in the middle of downloading the module, or hook simply fails.  With the …
> [external-module-manager] Store checksums in memory

- candi/openapi/init_configuration.yaml
Remove debBranch or releaseChannel requirements from InitConfiguration.
In release 1.54 we deprecated releaseChannel parameter, but forgot delete field from required fields.
Why we did deprecate releaseChannel param? 
1. From 1.54 version we install Deckhouse controller same version as installer.
2. We implemented  Deckhouse init configuration with module config and client can set release channel with `deckhouse` module config.
```changes
section: dhctl
type: fix
summary: Remove debBranch or releaseChannel requirements from InitConfiguration
```
> [dhctl] Remove debBranch or releaseChannel requirements from InitConfiguration

- modules/030-cloud-provider-yandex/hooks/alert_on_deprecated_availability_zone.go
- modules/030-cloud-provider-yandex/hooks/alert_on_deprecated_availability_zone_test.go
- modules/030-cloud-provider-yandex/monitoring/prometheus-rules/deprecated_availability_zone.yaml
If cluster has nodes on Yandex.Cloud availability zone `ru-central1-c`, alert will be fired asking user to migrate to zone `ru-centra1-d`
Yandex.Cloud [deprecated](https://cloud.yandex.com/en-ru/docs/overview/concepts/ru-central1-c-deprecation) `ru-central1-c` availability zone, users are encouraged to migrate to `ru-central1-d`
```changes
type: feature
summary: Alert about yandex ru-central-c zone deprecation
```
> [node-manager] Alert about yandex ru-central-c zone deprecation

- modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring/persistent-volume-claim.yaml
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/generic/kubelet.tpl
Added a job to sift metrics from custom exporters
if custom exporter gives metrics from alerts but with different labels it breaks alerts
```changes
type: fix
summary: added a job to sift metrics from custom exporters in persistent-volume-claim and coreos.kubelet
```
> [monitoring] added a job to sift metrics from custom exporters

- modules/300-prometheus/docs/FAQ.md
- modules/300-prometheus/docs/FAQ_RU.md
Updated FAQ entry by adding two tested examples.
The current example wasn't entirely valid, as the root route had a valid receiver set instead of a blackhole. Because of that, the explicit child route was redundant and misleading.
```changes
type: chore
summary: Minor documentation change.
```
> [prometheus][alertmanager] Ignore unnecessary alerts in Alertmanager examples update

- modules/301-prometheus-metrics-adapter/images/k8s-prometheus-adapter/Dockerfile
- [CVE-2022-1996](https://access.redhat.com/security/cve/CVE-2022-1996)
- [CVE-2022-21698](https://access.redhat.com/errata/RHSA-2022:7529)
- [CVE-2021-43565](https://access.redhat.com/security/cve/CVE-2021-43565)
- [CVE-2022-27191](https://access.redhat.com/errata/RHSA-2022:7469)
- [CVE-2022-27664](https://access.redhat.com/errata/RHSA-2023:2802)
- [CVE-2023-39325](https://github.com/deckhouse/deckhouse/pull/golang.org/x/net)
- [CVE-2021-38561](https://access.redhat.com/security/cve/CVE-2021-38561)
- [CVE-2022-32149](https://access.redhat.com/security/cve/CVE-2022-32149)
- [CVE-2022-28948](https://access.redhat.com/security/cve/CVE-2022-28948)
```changes
section: …
```
> [prometheus-metrics-adapter] fix cve in k8sPrometheusAdapter image

- modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/Dockerfile
- modules/340-monitoring-kubernetes/images/node-exporter/Dockerfile
[CVE-2023-39325](https://github.com/deckhouse/deckhouse/compare/golang.org/x/net)
```changes
type: fix
summary: fix cve issues in fix cve in node-exporter, kubelet-eviction-tresholds-exporter image
```
> [monitoring-kubernetes] fix cve in node-exporter, kubelet-eviction-tresholds-exporter image

- modules/150-user-authn/docs/USAGE.md
- modules/150-user-authn/docs/USAGE_RU.md
A new option has been added to the GitLab integration setup in version 16; users are faced with difficulties during authorization if it is not configured. The documentation has been updated with a method for enabling this option.
```changes
section: docs
type: chore
summary: Update documentation for integration user-authn with Gitlab ver16+.
```
> [docs] update documentation for integration user-authn with Gitlab ver16+

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/capacity-planning/capacity-planning.json
Change formula used to calculate `% Pods Usage` in Capacity Planning dashboard
https://github.com/deckhouse/deckhouse/issues/5933
Reported `% Pods Usage` matches the current usage in cluster/selected node(s).
```changes
type: fix
summary: Capacity Planning dashboard shows correct number of Pods usage
```
> fix Pods Usage graphic on Capacity Planning dashboard (#5933)

- testing/cloud_layouts/script.d/wait_cluster_ready/test_script_eks.sh
Fix e2e tests to test release updates.
E2e test for testing release updates doesn't work.
```changes
type: chore
summary: Fix e2e tests to test release updates.
```
> [testing] Fixes

- ee/modules/350-node-local-dns/hooks/cleanup_daemonset_hostports.go
- ee/modules/350-node-local-dns/hooks/cleanup_daemonset_hostports_test.go
Remove `hostPorts` from manifest when `hostNetwork=false`.
We don't use `hostNetwork` if `cni-cilium` is used and use it otherwise. If you migrate, e.g. from `cni-flannel` to `cni-cilium`, the `hostPorts` added by the controller when `hostNetwork` was true will remain in the DaemonSet manifest. In some cases, this can break resolving on nodes in the cluster because the `hostPort` bind port 53 on the host and then `systemd-resolved` (which works on port 53) stops working.
The problem described here https://github.com/kubernetes/kubernetes/issues/117689
We don't
Hook MUST remove `hostPorts` from the DaemonSet manifest if `hostNetwork=false`.
```changes
type: feature
summary: Remove `hostPorts` from manifest when `hostNetwork=false`.
```
> [node-local-dns] Remove hostPorts when hostNetwork=false

- dhctl/pkg/config/deckhouse_config.go
- dhctl/pkg/config/deckhouse_config_test.go
- dhctl/pkg/kubernetes/actions/deckhouse/install.go
- dhctl/pkg/kubernetes/actions/deckhouse/install_test.go
- dhctl/pkg/kubernetes/client/client.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-abort.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/operations/destroy/destroy.go
Fix release channel does not get from InitConfiguration.
Dhctl cannot create module config resources during bootstrap fixed. We now invalidate kube-client cache.
Abort did not work with static clusters fixed
Old set release channel mechanism not work.
Instructions from getting started don't work
```changes
section: dhctl
type: fix
summary: Fix release channel does not get from InitConfiguration
```
> [dhctl] Fix release channel does not get from InitConfiguration

- candi/cloud-providers/aws/docs/LAYOUTS.md
- candi/cloud-providers/aws/docs/LAYOUTS_RU.md
Minor docs fix
```changes
section: candi
type: chore
summary: Minor docs fix.
```
> [candi] Minor docs fix

- dhctl/pkg/config/base.go
- dhctl/pkg/config/base_test.go
Add fake InitConfiguretion for getting default from openapi spec if InitConfiguration was skipped
Init configuration is unnecessary and can be skipped. But without InitConfiguration cluster does not bootstrap.
New getting started does not work.
```changes
section: dhctl
type: fix
summary: Fix Deckhouse CE registry setting do not set if InitConfiguration was skipped.
```
> [dhctl] Fix Deckhouse CE registry setting do not set if InitConfiguration was skipped

- modules/021-cni-cilium/crds/ciliumclusterwideenvoyconfigs.yaml
- modules/021-cni-cilium/crds/ciliumenvoyconfigs.yaml
Restoring removed api versions in cilium's CRDs.
In some clusters the CRDs have `status.storedVersions` with old version, but there aren't any resources. So, there is an error during deckhouse update:
```
Error: module hook '021-cni-cilium/hooks/ensure_crds.go' failed: 2 errors occurred:
* CustomResourceDefinition.apiextensions.k8s.io "ciliumclusterwideenvoyconfigs.cilium.io" is invalid: status.storedVersions[0]: Invalid value: "v2alpha1": must appear in spec.versions
* CustomResourceDefinition.apiextensions.k8s.io "ciliumenvoyconfigs.cilium.io" is invalid: status.storedVersions[0]: Invalid value: "v2alpha1": must appear in spec.versions
```
Some clusters can't complete D8 update to version 1.55.
D8 update to version 1.55 completed without errors.
```changes
type: fix …
```
> [cni-cilium][fix] restoring removed api versions in CRDs

- modules/402-ingress-nginx/crds/ingress-nginx.yaml
Add ingressnginxcontrollers crd validation for httpsPort field. Forbid to use 6443 port for inlet HostPort mode.
Fix issue #3961
inlet HostPort with 6443 port may break k8s controlplane if ingress controller scheduled to control-plane nodes. Validation rule prevents that issue.
The issue can be reproduced in all previous releases, so it's better to check a port there too.
<pre>
#
#
kind: IngressNginxController
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"deckhouse.io/v1","kind":"IngressNginxController","metadata":{"annotations":{},"name":"main"},"spec":{"hostPort":{"httpPort":80,"httpsPort":443},"ingressClass":"nginx","inlet":"HostPort","nodeSelector":{"node-role.kubernetes.io/master":""},"tolerations":[{"effect":"NoS …
> [ingress-nginx] Add validation rule for httpsPort parameter

- modules/300-prometheus/hooks/update_alertmanager_status.go
- modules/300-prometheus/hooks/update_alertmanager_status_test.go
PR updates `update_alertmanager_status.go` hook to skip `customalertmanagers` created via labeled services (deprecated functionality).
We need it because otherwise `update_alertmanager_status.go` hook fails to converge due to missing CRs for `CustomAlertManagers` created via `labeled services` (by design). Such customalertmanagers have `ResourceName` field set to empty string in internal values.
It fixes deckhouse converge issue when there is a customalertmanager-labeled service in a cluster.
`update_alertmanager_status.go` hook successfully executes even if there is a customalertmanager-labeled service in the cluster.
```changes
type: fix
summary: Fixes update_alertmanager_status hook when there is an alertmanager via a labeled service in the cluster.
```
> [prometheus-operator] fix update alertmanagers hook for customalertmanagers via labeled services

- go_lib/dependency/cr/cr.go
Add default 30 seconds timeout to registry client operations
With `REGISTRY_TIMEOUT` env variable we can hack this timeout in a cluster (just for emergency situation resolve)
example:
```
REGISTRY_TIMEOUT=5m
```
Registry call could be endless on a huge amount of tags or huge image. We have to limit this kind of operation
```changes
type: fix 
summary: Limit registry client operations with 30 seconds timeout.
```
> [global] Add default timeout to registry client

- testing/cloud_layouts/script.sh
Temporary disable e2e alerts test
e2e alerts tests failed. we need investigation for  fix it
```changes
type:chore
summary: Temporary disable e2e alerts test
```
> [testing] Temporary disable e2e alerts test

- docs/site/_includes/getting_started/aws/partials/config.yml.without_nat.ce.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.without_nat.ee.inc
- docs/site/_includes/getting_started/azure/partials/config.yml.standard.ce.inc
- docs/site/_includes/getting_started/azure/partials/config.yml.standard.ee.inc
- docs/site/_includes/getting_started/bm-private/partials/config.yml.ce.inc
- docs/site/_includes/getting_started/bm/partials/config.yml.ce.inc
- docs/site/_includes/getting_started/bm/partials/config.yml.ee.inc
- docs/site/_includes/getting_started/existing/partials/config.yml.ce.inc
- docs/site/_includes/getting_started/existing/partials/config.yml.ee.inc
- docs/site/_includes/getting_started/gcp/partials/config.yml.without_nat.ce.inc
- docs/site/_includes/getting_started/gcp/partials/config.yml.without_nat.ee.inc
- docs/site/_includes/getting_started/kind/partials/config.yml.ce.inc
- docs/site/_includes/getting_started/kind/partials/config.yml.ee.inc
- docs/site/_includes/getting_started/openstack/partials/config.yml.standard.ee.inc
- docs/site/_includes/getting_started/openstack_ovh/partials/config.yml.standard.ee.inc
- docs/site/_includes/getting_started/openstack_selectel/partials/config.yml.standard.ee.inc
- docs/site/_includes/getting_started/openstack_vk/partials/config.yml.standard.ee.inc
- docs/site/_includes/getting_started/vsphere/partials/config.yml.standard.ee.inc
- docs/site/_includes/getting_started/yandex/partials/config.yml.standard.ce.inc
- docs/site/_includes/getting_started/yandex/partials/config.yml.standard.ee.inc
The configuration files for installing Deckhouse have been changed in accordance with the deprecation of the configOverrides section.
Solves the problems of installing new clusters according to the manual from GS.
GS will become relevant.
```changes
section: docs
type: chore
summary: Make the Getting Started more consistent.
```
> [getting-started][docs] Changing configs after the deprecation of configOverrides

- go_lib/hooks/tls_certificate/order_certificate.go
- modules/040-node-manager/hooks/generate_capi_static_kubeconfig_secret.go
- modules/040-node-manager/hooks/internal/kubeconfig/kubeconfig.go
- modules/040-node-manager/images/caps-controller-manager/src/cmd/main.go
- modules/040-node-manager/templates/capi-controller-manager/rbac-for-us.yaml
Generate a `static-kubeconfig` with X.509 certificates for the Cluster API controller.
When we generate kubeconfig, we need to avoid using a token that never expires.
```changes
type: fix
summary: Generate a `static-kubeconfig` with X.509 certificates for the Cluster API controller.
```
> [node-manager](caps) fix static-kubeconfig generation

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
Remove the use of `crictl` when backing up etcd.
`crictl` output is not stable enough to rely on it.
```changes
type: fix 
summary: Remove the use of crictl when backing up etcd.
```
> [control-plane-manager] removed the use of crictl when backing up etcd

- tools/kind-d8.sh
A new configuration file has been added to the kind installation script, which takes into account the deprecation of configOverrides.
Solves the problems of installing new clusters according to the manual from GS.
GS will become relevant.
```changes
section: docs
type: chore
summary: Make the Getting Started more consistent.
```
> [getting-started][docs] Updating the config in the kind installation script

- candi/openapi/cluster_configuration.yaml
- docs/documentation/_plugins/openapi.rb
Set a badge for the proxy parameters of the ClusterConfiguration resource that the parameters are for Deckhouse EE only.
```changes
section: docs
type: chore
summary: Set a badge for the proxy parameters of the _ClusterConfiguration_ resource.
```
> [candi] Set badge for ClusterConfiguration proxy parameters

- dhctl/cmd/dhctl/commands/mirror.go
- dhctl/pkg/operations/mirror.go
- dhctl/pkg/operations/mirror/auth.go
- dhctl/pkg/operations/mirror/layouts.go
- dhctl/pkg/operations/mirror/modules.go
- dhctl/pkg/operations/mirror/pull.go
- dhctl/pkg/operations/mirror/versions.go
`dhctl mirror` will now validate passed credentials such as Deckhouse license tokens and registry logins/passwords prior to mirroring
We got a feedback about dhctl taking long time to signal about bad registry credentials after push to the third-party registry is started due to the tar bundle unpack procedure taking a few minutes. Only after dhctl is done with it and started pushing, it will find out about bad creds and fail.
https://github.com/deckhouse/deckhouse/pull/6629#issuecomment-1822893839
```changes
section: dhctl
type: fix
summary: Validate passed credentials against registry prior to mirroring
```
> [dhctl] Validate passed credentials against registry prior to mirroring

- modules/015-admission-policy-engine/openapi/config-values.yaml
- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
* Inaccuracies in the comparison table of CE and EE versions have been eliminated.
* Several typos have been eliminated.
This will make the documentation more accurate and relevant.
```changes
section: docs
type: chore
summary: Make the documentation more consistent.
```
> [admission-policy-engine][docs] Fix table with CE and EE comparison and make some text typos

- testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/script.d/wait_cluster_ready/test_alerts.sh
- testing/cloud_layouts/script.sh
Tests can failed on AWS and on static because of incorrect alert checking.
Should to ignore alerts CertmanagerCertificateExpired.*, Deckhouse ModuleEmpty.
Disable earlyOOM killer for AWS tests, cause AWS use Centos with kernel version below 4
Without fixes tests failed every time
All test pass (primary AWS and static). All alerts that need to be ignored are ignored.
```changes
type: chore
summary: Fix some errors on e2e tests in AWS and static
```
> [testing] Correct mistake with alerts in e2e test

- modules/340-extended-monitoring/images/image-availability-exporter/Dockerfile
Fix wrong permissions for k8s-image-availability-exporter
#6752 
k8s-image-availability-exporter have correct UID and GID 64535
```changes
type: fix
summary: Fix wrong permissions for k8s-image-availability-exporter
```
> [extended-monitoring] fix permissions

- candi/bashible/common-steps/node-group/032_configure_and_start_containerd.sh.tpl
Restart kubelet after containerd restart to fix containerd.sock loss.
When containerd restarts kubelet can lose containerd.sock connection.
```changes
section: candi
type: fix
summary: Restart kubelet after containerd restart to fix containerd.sock loose.
```
> [candi] restart kubelet after containerd restart to fix containerd.sock loss

- ee/modules/600-flant-integration/hooks/pricing/envs_from_nodes.go
Run hook envs_from_nodes OnBeforeHelm
Closes https://github.com/deckhouse/deckhouse/issues/6645
```changes
type: fix
summary: Run hook envs_from_nodes OnBeforeHelm to prevent main queue stuck
```
> [flant-integration] Run hook envs_from_nodes OnBeforeHelm

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Added documentation for https://github.com/deckhouse/deckhouse/pull/6651
Close https://github.com/deckhouse/deckhouse/issues/5772
```changes
type: feature
impact: Update documentation about how to add an annotation to apply DeckhouseRelease immediately.
```
> [deckhouse] Add annotation to apply DeckhouseRelease immediately

- dhctl/pkg/operations/mirror.go
- dhctl/pkg/operations/mirror_module.go
Added module-named tags at modules repo root after all of module images were pushed
This fixes module discovery in Deckhouse, which is listing module subrepo tags to find modules instead of looking in the repo catalog
This fixes a bug in modules mirroring, which was reported by a user
```changes
section: dhctl
type: fix
summary: Fix mirror not adding module-named tags at modules repo root.
```
> [dhctl] Fix mirror not adding module-named tags at modules repo root

- modules/460-log-shipper/hooks/internal/vector/transform/filter.go
- modules/460-log-shipper/hooks/internal/vector/transform/testdata/filters.json
- modules/460-log-shipper/hooks/internal/vector/transform/transforms_test.go
If in the `logFilter` the empty field is specified, vector was throwing an error because of the `.parsed_data.` selector with the trailing dot symbol. This PR fixes the error by making the deckhouse rendering only the `.parsed_data` key without the trailing dot.
Closes https://github.com/deckhouse/deckhouse/issues/6611
```changes
type: fix
summary: Fix empty field trailing dots in filters
```
> [log-shipper] Fix empty field trailing dot in filters

- modules/490-virtualization/docs/FAQ.md
- modules/490-virtualization/docs/FAQ_RU.md
- modules/490-virtualization/hack/remove-module.sh
Add information on how to disable the module correctly.
Before enabling the new virtualization module, you must correctly clean up all old configurations of the embedded module.
We need to inform users on how to correctly disable an embedded module before the module is removed.
Nothing.
```changes
type: chore
summary: Add a module removal script.
```
> [virtualization] add remove module script

- modules/040-node-manager/templates/node-group/_bootstrap.tpl
Use dependency-free cross-version python script for second phase bootstrap loading.
- No longer need to support multiple versions of python
- No third-party packages (`requests`) are used that are not included in python by default
We don't
We can bootstrap node without cloud-init package (which brings `requests` python package).
```changes
type: feature
summary: Use dependency-free cross-version python script for second phase bootstrap loading.
```
> [node-manager] Use dependency-free cross-version python script for second phase bootstrap loading

- modules/005-external-module-manager/hooks/create_deckhouse_modules_source.go
- modules/005-external-module-manager/hooks/create_deckhouse_modules_source_test.go
- modules/005-external-module-manager/hooks/migration_create_update_policies.go
- modules/005-external-module-manager/hooks/migration_create_update_policies_test.go
We don't want to create default update policy, only to migrate the old one
A lot of modules will be pulled by default, we want just to observe them, not load
```changes
type: fix
summary: Remove default ModuleUpdatePolicy for the `deckhouse` ModuleSource.
```
> [external-module-manager] remove default ModuleUpdatePolicy

- modules/041-linstor/enabled
Enabling the Linstor module is prohibited when the SDS-DRBD module is enabled.
Simultaneously enabling the Linstor and SDS-DRBD modules is not possible, as it can lead to data corruption.
Simultaneously enabling the Linstor and SDS-DRBD modules is prohibited.
```changes
type: chore
summary: Simultaneously enabling the Linstor and SDS-DRBD modules is prohibited.
```
> [linstor] Enabling the Linstor module is prohibited when the SDS-DRBD module is enabled

- docs/site/.helm/templates/20-ingress.yaml
Add redirect to the stable channel for modules documentation by default.
```changes
section: docs
type: chore
summary: Add redirect to the stable channel for modules documentation by default.
```
> [modules-docs] Rewrite to stable channel

- docs/site/backends/docs-builder-template/config/_default/hugo.yaml
- docs/site/backends/docs-builder-template/layouts/_default/baseof.html
- docs/site/backends/docs-builder-template/layouts/partials/head.html
Add page metadata to the layout of module documentation.
```changes
section: docs
type: chore
summary: Add page metadata to the layout of module documentation.
```
> [modules-docs] Add page metadata to the layout of module documentation.

- modules/300-prometheus/images/prometheus/werf.inc.yaml
Add df utility to an image
There is a error in the prometheus hook.
command should be work `kubectl -n <namespace> exec -ti <pod_name> -c prometheus -- df -PBG /prometheus`
```changes
type: fix
summary: Add df utility to an image.
```
> [prometheus] distroless prometheus fix

- dhctl/pkg/app/mirror.go
Clarified the help text of `--images-bundle-path` flag, saying that it should point to a .tar file. Added validation of that.
There were some complaints about the subject beign unclear to users.
```changes
section: dhctl
type: feature
summary: Clarify tar bundle flag usage and validate it more strictly.
```
> [dhctl] Clarify tar bundle flag usage and validate it more strictly

- ee/modules/650-runtime-audit-engine/images/falco/werf.inc.yaml
- ee/modules/650-runtime-audit-engine/images/falcosidekick/Dockerfile
- ee/modules/650-runtime-audit-engine/images/rules-loader/werf.inc.yaml
Fixed vulnerabilities: GHSA-62mh-w5cv-p88c, CVE-2021-3127, GHSA-j756-f273-xhp4, CVE-2022-21698, CVE-2020-29652, CVE-2021-43565, CVE-2022-27191, CVE-2021-33194, CVE-2022-27664, CVE-2022-41723, CVE-2023-39325, CVE-2021-38561, CVE-2022-32149, GHSA-m425-mq94-257g, CVE-2022-28948
<details><summary>before</summary>
```shell
[deckhouse] root@2794dff5146e / # cat /deckhouse/candi/images_digests.json | grep runtimeAuditEngine -A4
"runtimeAuditEngine": {
"falcosidekick": "sha256:c0f4f9202ee991f9d47dea491efc70b36bd739fe804d14a9aa4c30c899c78cd9",
"rulesLoader": "sha256:014252666b89a056778b820eab24dbce4beb1cb2a8c1c0b24935c70287237ffc",
"falco": "sha256:296b85a3cdd42248f7b827cacc7ccea054b3d5f61ac8735c2a9ae0586216ed8c"
},
dev-registry.deckhouse.io/sys/deckhouse-oss@sha256:c0f4f9202ee991f9d47dea491efc70b3 …
```
> [runtime-audit-engine] Fix CVEs

- docs/site/backends/registry-modules-watcher/go.mod
- docs/site/backends/registry-modules-watcher/go.sum
- docs/site/backends/registry-modules-watcher/internal/backends/pkg/registry-scaner/process.go
- docs/site/backends/registry-modules-watcher/internal/backends/pkg/sender/sender.go
We used the "go-retryablehttp" library from "hashicorp" to implement the repetitive request functionality. 
This led to the appearance of a second logger in the module, which is not convenient to manage and difficult to replace with klog.
We switched to a new library cenkalti/backoff with similar functionality. This allowed us to remove the second logger.
It fix log output and logging level management in documentation module.
Unified log output and management of logging levels
```changes
section: docs
type: fix
summary: Fix log output and logging level management in the documentation module.
```
> Fix registry watcher logs. Change retry lib.

- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/terraform-modules/master-node/main.tf
- candi/cloud-providers/yandex/terraform-modules/static-node/main.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/main.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/outputs.tf
Add support for ru-central1-d availability zone in Yandex Cloud
Closes #6513
Closes #6546
We don't
- New clusters successfully bootstrapped in new zone
- Existing clusters does not broken after converge
- It is possible to successfully change a zone of nodes in an existing `NodeGroup`
```changes
section: candi
type: feature
summary: Add support for the `ru-central1-d` zone in Yandex Cloud.
```
> [cloud-provider-yandex] Add support for ru-central1-d zone in Yandex Cloud

- .github/workflow_templates/e2e.abort.multi.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
Current name of action 'e2e destroy failed' is misleading
It is necessary to change the name to a more correct one
Name of action changed
```changes
section: ci
summary: Change name of action 'e2e destroy faled'.
```
> [ci] Change name of action 'e2e destroy faled'

- ee/modules/160-multitenancy-manager/templates/user-resources/user-resources-templates.yaml
- go_lib/dependency/helm/hash.go
- go_lib/dependency/helm/helm.go
What we've got:
When we make changes to any project or projectTemplate, we make a call to Helm.Update for all projects. This leads to unnecessary increase of Helm release version.
What we're getting at:
We compute an md5 hash based on templates and template values and store this hash in the release custom label.   When changes are made, we compare the hash and prevent helm.Update from being called.
It prevents the creation of a new "helm" release when no changes are made to it.
When changes are made to a project or project template helm.update will only be called for projects that have changes or for new projects.
```changes
type: fix
summary: Prevents the creation of a new "helm" release when no changes are made to it
```
> Preventing the creation of a new "helm" release when no changes are made

- dhctl/pkg/operations/mirror/layouts.go
- dhctl/pkg/operations/mirror/pull.go
- dhctl/pkg/operations/mirror_module.go
When `dhctl mirror` pulls module release channel images, it will no longer report missing images as a critical error and abort pulling. Instead it will log this as a warning and continue.
Fixes https://github.com/deckhouse/deckhouse/issues/6809
This is a fix for a top priority bug.
```changes
section: dhctl
type: fix
summary: Allow missing module release channels.
```
> [dhctl] mirror: Allow missing module release channels

- candi/bashible/common-steps/node-group/002_create_static_node_cleanup_script.sh.tpl
Fixes in cleanup script
1. Migrate from `killall` to `pkill`. With `killall` we have error `bash: killall: command not found`, because package `psmisc` not installed by default. `pkill` exists in package `procps` on debian-like systems and in package `procps-ng` on centos-like systems and looks like this packages installed by default
2. Disable our services and timers lets systemd remove symlinks
3. `systemctl daemon-reload` must be executed after remove services and timers
After cleanup node with command `bash /var/lib/bashible/cleanup_static_node.sh --yes-i-am-sane-and-i-understand-what-i-am-doing` and bootstrap again we have strange problems like
```
=== Step: /var/lib/bashible/bundle_steps/032_configure_and_start_containerd.sh
===
bash [WARNING] 'containerd-need-restart' flag was set. …
```
> [candi][bashible] Fix cleanup script

- modules/015-admission-policy-engine/charts/constraint-templates/templates/operation/replica-limits.yaml
- modules/015-admission-policy-engine/crds/doc-ru-operation-policy.yaml
- modules/015-admission-policy-engine/crds/operation-policy.yaml
- modules/015-admission-policy-engine/hooks/handle_operation_policies_test.go
- modules/015-admission-policy-engine/hooks/internal/apis/v1alpha1.go
- modules/015-admission-policy-engine/template_tests/operation_policies_test.go
- modules/015-admission-policy-engine/templates/policies/operation-policy/constraint.yaml
New operation policy for checking replica values for Deployments, ReplicaSets and StatefulSets
We would need to control low and high ranges of replicas to prevent zero replicas or check too high values.
If replica value is not in range we'll get an error
New operation policy for replica value checking
```yaml
kind: OperationPolicy
metadata:
name: foo
spec:
policies:
replicaLimits:
minReplicas: 1
maxReplicas: 3
match:
namespaceSelector:
matchNames: ["default"]
```
```sh
$ kubectl -n default patch deployment echo-server  --type='merge' -p '{"spec":{"replicas":5}}'
Error from server (Forbidden): admission webhook "admission-policy-engine.deckhouse.io" denied the request: [foo] The provided number of replicas is not allowed for Deployment: echo-server. …
```
> [admission-policy-engine] add policy for replicas limits

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/loadbalancer.yaml
On some cloud providers deckhouse can't order vm for LoadBalancer. So we need to know when it is happened. 
Need to know when LoadBalancer not started
When LoadBalancer was created with Kubernetes by not starts al alert _LoadBalancerServiceWithoutExternalIP_ should appear 
```changes
type: feature
summary: Add alert when LoadBalancer has not been created.
```
> [monitoring-kubernetes] Add alert when LoadBalancer have not been created

- candi/openapi/node_group.yaml
Fix the wrong field name in the NodeGroup schema.
```changes
section: doc
type: fix
summary: Fix the wrong field name in the NodeGroup schema.
```
> Fix the wrong field name in the NodeGroup schema

- candi/bashible/bashbooster/50_deckhouse_registrypackages.sh
Handle registry packages fetch errors.
`curl` writes file as it is loading. If the download fails, we will get corrupted file. Since we don't currently have the ability to validate packages checksum (and we don't do it), we will get an error at the unpacking stage:
```
bashible.sh[1088426]: bb-rp [INFO] Unpacking package 'kubectl'
bashible.sh[1088426]: gzip: stdin: unexpected end of file
bashible.sh[1088426]: tar: Unexpected EOF in archive
bashible.sh[1088426]: tar: Unexpected EOF in archive
bashible.sh[1088426]: tar: Error is not recoverable: exiting now
bashible.sh[1086700]: Failed to execute step ...
```
Since we don't handle this error, it will start to fill up disk space 'cause the original corrupted blob will not be refetched (there is no such logic) and the temp directory is not …
> [candi][bb] Handle registry packages fetch errors

- modules/021-cni-cilium/templates/configmap.yaml
Enabling pprof interface for agents.
In case of cpu leaks it is convenient to profile the agent code with pprof.
The pprof gathering works inside cilium-agent pod:
```
cilium-bugtool --get-pprof --pprof-trace-seconds 30
```
```changes
type: chore
summary: Enabled pprof interface in cilium-agent.
impact: cillium-agent pods will restart.
```
> [cni-cilium] Enabling pprof interface for agents

- modules/021-cni-cilium/images/builder/werf.inc.yaml
- modules/021-cni-cilium/images/cilium/werf.inc.yaml
- modules/021-cni-cilium/images/operator/werf.inc.yaml
Bump cni-cilium to 1.14.5.
There is [regression](https://github.com/cilium/cilium/issues/29175) in 1.14 which causes high cpu usage.
There is a customer who faced the high cpu usage by agents.
CPU usage is moderate.
```changes
type: fix
summary: Cilium version bumped to 1.14.5
impact: Cilium agents will restart, during restart some policies won't work.
```
> [cni-cilium] Bump cilium to 1.14.5

- modules/040-node-manager/webhooks/validating/node_group
Add `NodeGroup` name validation only for `CREATE` operation.
```changes
type: fix
summary: add NodeGroup name validation only for 'CREATE' operation.
```
> [node-manager] fix NodeGroup validating webhook

- testing/cloud_layouts/Azure/Standard/configuration.tpl.yaml
- testing/cloud_layouts/Azure/Standard/resources.yaml
- testing/cloud_layouts/Static/configuration.tpl.yaml
Disable early-oom for centos based e2e tests
Centos based images contains old kernel and early oom pods do not start
```changes
type: fix
summary: Disable early-oom for centos based e2e tests
```
> [testing] Disable early-oom for centos based e2e tests

- candi/bashible/bashbooster/50_deckhouse_registrypackages.sh
Resolve names to IPv4 addresses with `d8-curl`.
https://github.com/deckhouse/deckhouse/issues/6862
The problem is only observed with our version of curl (`d8-curl`). Other versions of curl also send IPv6 requests, but try IPv4 after timeout. Maybe the problem is in the musl implementation in the static build (need investigation).
```changes
section: candi
type: fix
summary: Resolve names to IPv4 addresses with d8-curl.
```
> [candi] Resolve names to IPv4 addresses with d8-curl

- candi/cloud-providers/yandex/bashible/common-steps/all/000_set_cloud_variables.sh.tpl
Decrease `shutdownGracePeriod` for Yandex Cloud.
`shutdownGracePeriod: 30s` is too large and nodes will be forcibly terminated before graceful shutdown timeout expires (information from Yandex Cloud Support).
We don't.
```changes
section: candi
type: fix
summary: Decrease shutdownGracePeriod for YandexCloud.
```
> [candi][yc] Decrease shutdownGracePeriod

- modules/110-istio/hooks/compatibility_version_istio_k8s_monitoring.go
- modules/110-istio/hooks/compatibility_version_istio_k8s_monitoring_test.go
- modules/110-istio/hooks/deprecated_versions_monitoring.go
- modules/110-istio/monitoring/prometheus-rules/versions.tpl
Add a metric showing istio and k8s compatibility, and an alert for it
If the istio version and the k8s version are not officially compatible or supported, they may not function correctly together.
We removed this check previously to revise it (https://github.com/deckhouse/deckhouse/pull/6914).
If k8s and istio versions aren't compatible, we get alert of that
```changes
section: istio
type: fix
summary: Adding alert about istio and k8s versions incompatibility
```
> [istio] Add a metric showing istio and k8s compatibility, and an alert for it

- docs/documentation/_plugins/openapi.rb
- docs/site/backends/docs-builder-template/layouts/partials/openapi/format-attributes.html
- docs/site/css/components/_resources.scss
Fix the rendering of OpenAPi specs to avoid overlapping with the TOC in the documentation on the site.
> [modules docs] Fix rendering of resources to avoid overlapping with the TOC

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/node-ro-fs.yaml
Close https://github.com/deckhouse/deckhouse/issues/3893 
```changes
type: feature
summary: Add alert NodeFilesystemIsRO
```
> [monitoring-kubernetes] Add alert NodeFilesystemIsRO

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/generic/kube-state-metrics.yaml
In the new version of Prometheus only the values of the first query were given. the other queries did not overwrite the metrics values, which broke the logic. 
Close https://github.com/deckhouse/deckhouse/issues/6238
```changes
type: fix
summary: fixed generation of metrics kube_persistentvolume_is_local
```
> [monitoring-kubernetes]  merged kube_persistentvolume_is_local into one query 

- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
fixes a limitation when using apparmor on nodes
This removes errors from container logs and node logs generated due to lack of permissions.
```changes
type: fix
summary: fixed AppArmor rule in kubelet-eviction-thresholds-exporter
```
> [monitoring-kubernetes] fixed AppArmor rule in kubelet-eviction-thresholds-exporter

- dhctl/pkg/app/mirror.go
- dhctl/pkg/operations/mirror/digests.go
- dhctl/pkg/operations/mirror/util.go
This PR adds support for using images_tags.json as source of Deckhouse images to mirror. Also fixes a bug where go-containerregistry would not handle some gzipped layer streams correctly, which broke pulls of v1.45.
This is a bugfix.
This fixes mirroring of older DH releases.
```changes
section: dhctl
type: fix
summary: Fix for pulling older Deckhouse versions with tags instead of digests in installers.
```
> [dhctl] mirror: fix for pulling older Deckhouse versions with tags instead of digests in installers

- modules/150-user-authn/templates/dex-authenticator/deployment.yaml
Fix #6696 
It is currently not possible to configure oauth-proxy with --insecure-oidc-allow-unverified-email.
As a result, you cannot log into Deckhouse modules such as grafana or dashboard if your user has unverified email.
So you have to manually path the deployment, but this will probably work only until the next module update.
We have clients who are forced to use such users in OIDC.
A user whose email has not been verified can log into grafana.
OIDC allow unverified email
```changes
type: fix
summary: OIDC allow unverified email
impact_level: defaut
```
> [user-authn] OIDC allow unverified email

- tools/build.go
- tools/build_includes/modules-with-exclude-EE.yaml
- tools/build_includes/modules-with-exclude-FE.yaml
Exclude go files from deckhouse-controller image
Deckhouse image should not contain *.go files
```changes
section: ci
type: chore
summary: Exclude go files from deckhouse-controller image
impact_level: ow
```
> [ci] Exclude go files from deckhouse-controller image

- dhctl/pkg/app/mirror.go
Mirror will now validate if the directories in the images bundle path exist.
This is a bug reported by a user.
```changes
section: dhctl
type: fix
summary: mirror will validate tar bundle path more strictly.
```
> [dhctl] mirror: validate tar bundle path more strictly

- modules/402-ingress-nginx/images/controller-1-6/Dockerfile
- modules/402-ingress-nginx/images/controller-1-6/patches/README.md
- modules/402-ingress-nginx/images/controller-1-6/patches/fix-cleanup.patch
- modules/402-ingress-nginx/images/controller-1-9/Dockerfile
- modules/402-ingress-nginx/images/controller-1-9/patches/README.md
- modules/402-ingress-nginx/images/controller-1-9/patches/fix-cleanup.patch
Fix tempDir path for the cleanup routine.
https://github.com/kubernetes/ingress-nginx/pull/10797
The cleanup routine searches tmp files in a wrong place, so temp configs don't get deleted at all.
Close #6868 
Temp files older than 5min get deleted every 5 minutes.
```changes
type: fix
summary: Fix ingress controller clean up routine.
impact: All pods of ingress nginx controllers of versions 1.6 and 1.9 will be recreated.
```
> [ingress-nginx] fix cleanup temp dir path

- modules/402-ingress-nginx/images/controller-1-6/patches/fix-cleanup.patch
- modules/402-ingress-nginx/images/controller-1-9/patches/fix-cleanup.patch
A quick fix on the heels of [the previous update](https://github.com/deckhouse/deckhouse/pull/6985).
Without slash path.Walk doesn't unwrap a symlink directory (in case of a chrooted image) preventing temp files from being deleted.
Cleanup also works in a chrooted environment.
```changes
type: fix
summary: Fix cleanup for a chrooted environment
impact: All pods of ingress nginx controllers of versions 1.6 and 1.9 will be recreated.
```
> [ingress-nginx] fix clean up for chroot images

- docs/site/backends/docs-builder/build.go
- docs/site/backends/docs-builder/build_test.go
- docs/site/backends/docs-builder/channel_mapping.go
- docs/site/backends/docs-builder/handler.go
- docs/site/backends/docs-builder/upload.go
- docs/site/backends/docs-builder/upload_test.go
Added removal of invalid documentation during build
```changes
type: fix
summary: Improved stability of the documentation site
```
> [documentation] add docs-builder build error handling

- modules/021-cni-cilium/templates/configmap.yaml
Fixing pprof listen address for cilium-agents.
Cilium uses "localhost" address to bind the pprof interface. So, it have to resolve the address using DNS, but dns doesn't work without network.
There are clusters faced the problem.
agents start without problems.
```changes
type: fix
summary: Fixed pprof listen address for cilium-agents.
impact: cilium-agents will restart. Some fqdn-basic network policies will blink awile.
```
> [cni-cilium] Fixing pprof listen address

- ee/modules/500-operator-trivy/images/operator/Dockerfile
- ee/modules/500-operator-trivy/images/operator/patches/005-cis-benchmark-on-startup.patch
- ee/modules/500-operator-trivy/images/operator/patches/README.md
The first check begins instantly when the operator starts
https://github.com/deckhouse/deckhouse/issues/5174
```changes
type: fix
summary: CIS compliance checks are now available immediately after activating the module
```
> [operator-trivy] cis benchmark job startup

- deckhouse-controller/pkg/controller/module-controllers/release/override-controller.go
Drop error message from ModulePullOverride status
If ModulePullOverride had a problem with registry, we can reset the error message  after reconnecting, in case the image digest was not updated
```changes
type: fix
summary: Drop error message on registry reconnection.
```
> [deckhouse-controller] Drop error message for ModulePullOverride

- dhctl/cmd/dhctl/commands/mirror.go
- dhctl/pkg/operations/mirror.go
- dhctl/pkg/operations/mirror/layouts.go
- dhctl/pkg/operations/mirror/versions.go
Release channel images of deckhouse controller and installer will now be pushed into the registry with both release channel and version tags.
This fixes installation from mirrored registries where release channel was not of latest patch in release.
```changes
section: dhctl
type: fix
summary: dhctl mirror will tag release channels images with their versions as well.
```
> [dhctl] mirror: tag release channels images with their versions

- ee/modules/500-operator-trivy/images/trivy/Dockerfile
PR updates the image sources list Trivy tries to use to get a image for a remote scan (client/server). Originally, this lists consists of several values: "docker", "podman", "containerd" and "remote". Trivy cycles over the list trying each source at a time and if there is some error during the scan, the error message gets bloated with extra errors from failed image sources, resulting in bloated and counterintuitive logs. As we use only remote scan, the image sources list has been updated to include only "remote" source for client/server mode.
Standalone mode shouldn't be affected by the changes and it is acknowledged by the logs below.
It removes some unnecessary logs like "trivy couldn't connect to podman/docker/etc".
In case of an error when scanning remotely, trivy operator scan logs …
> [operator-trivy] disable non-remote image sources for remote scans

- modules/110-istio/hooks/purge_orphan_resources.go
- modules/110-istio/hooks/purge_orphan_resources_test.go
Add a hook to check for orphaned resources and remove them when the module is shut down
If an operator's pod fails to start or was deleted before its resources, they remain in the cluster as orphaned and cannot be deleted because of `finalizers`.
To avoid this, we add a check for orphaned resources and delete them when the module is disabled.
Fixes https://github.com/deckhouse/deckhouse/issues/5285.
After disabling the module, there are no remaining Istio system-components in the cluster.
```changes
section: istio
type: fix
summary: After disabling the module, clean up any orphaned Istio components.
```
> [istio] Delete orphan istio resources after disable module

- modules/110-istio/hooks/deprecated_versions_monitoring.go
- modules/110-istio/hooks/deprecated_versions_monitoring_test.go
Improved checking for currently running deprecated versions of Istio in the cluster.
Previously, if a deprecated version was used in a cluster, but was not explicitly described in the moduleconfig, no alert would be generated. For example, the control-plane was setupped from custom IstioOperator CR.
Fixes https://github.com/deckhouse/deckhouse/issues/6374.
The alert D8IstioDeprecatedIstioVersionInstalled will be generated if a deprecated version of istio is described in the moduleconfig or running in the cluster (being setupped from custom IstioOperator CR).
```changes
section: istio
type: fix
summary: Improved checking for currently running deprecated versions of Istio in the cluster.
```
> [istio] Check deprecated versions based on mc and iop in cluster

- modules/110-istio/templates/control-plane/mutatingwebhook-revisions.yaml
- modules/110-istio/templates/control-plane/validatingwebhook-revisions.yaml
Generate only requested mutating and validating webhooks.
Previously, `MutatingWebhookConfigurations` and `ValidatingWebhookConfigurations` were created for all supported versions of Istio.
It could be confusing.
`MutatingWebhookConfigurations` and `ValidatingWebhookConfigurations` will only be created for the versions used in the cluster (globalVersion and additionalVersions).
```changes
section: istio
type: chore
summary: Generate only requested mutating and validating webhooks.
```
> [istio] Generate only requested mutating and validating webhooks

- modules/300-prometheus/crds/doc-ru-prometheusremotewrite.yaml
- modules/300-prometheus/crds/prometheusremotewrite.yaml
- modules/300-prometheus/openapi/values.yaml
- modules/300-prometheus/template_tests/prometheus_cr_test.go
- modules/300-prometheus/templates/prometheus/prometheus.yaml
- modules/300-prometheus/templates/prometheus/remote-write-secrets.yaml
Implement CA property in D8's PrometheusRemoteWrite CRD.
Close https://github.com/deckhouse/deckhouse/issues/3572
```changes
type: feat
summary: Implement CA property in D8's PrometheusRemoteWrite.
```
> [prometheus] Support setting custom CA for remote_write

- modules/300-prometheus/docs/USAGE.md
- modules/300-prometheus/docs/USAGE_RU.md
Add examples of CustomAlertmanager for Slack and Opsgenie.
```changes
type: chore
summary: Add examples of CustomAlertmanager for Slack and Opsgenie.
```
> [prometheus]  Add examples for CustomAlertmanager

- modules/300-prometheus/docs/USAGE.md
- modules/300-prometheus/docs/USAGE_RU.md
This returns https://github.com/deckhouse/deckhouse/pull/7030 (was reverted in https://github.com/deckhouse/deckhouse/pull/7050).
The return of values became possible after https://github.com/deckhouse/deckhouse/pull/7052.
```changes
section: docs
type: chore
summary: Return https://github.com/deckhouse/deckhouse/pull/7030 (was reverted in https://github.com/deckhouse/deckhouse/pull/7050).
```
> return "[prometheus]  Add examples for CustomAlertmanager (#7030)"

- modules/002-deckhouse/templates/namespace.yaml
- modules/300-prometheus/docs/FAQ.md
- modules/300-prometheus/docs/FAQ_RU.md
- modules/300-prometheus/hooks/additional_configs_render.go
- modules/300-prometheus/monitoring/prometheus-rules/deprecation.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
- modules/340-monitoring-kubernetes/templates/kube-state-metrics/additional-scrape-config.yaml
The old way to add custom endpoints to additional scrape config for Prometheus in secrets will be deprecated soon.
The new way is to use ScrapeConfig custom resourse.
This change solves issue #6787 and allows scrape endpoint addition after deprecation.
Metrics still be available, but the describing method was changed.
Additional scrape config format was changed from secret to custom resource.
```changes
type: chore
summary: The additional scrape config format was changed from secret to custom resource.
```
> [prometheus] add metrics and alert for deprecated scrape config method

- candi/bashible/bashbooster/50_deckhouse_registrypackages.sh
- candi/bashible/bundles/centos/bootstrap.sh.tpl
Set curl overall timeout to 300 seconds explicitly and connect timeout to 10s.
[Default curl timeout](https://github.com/curl/curl/blob/26f002e02ef1142a432c8dc087bd27de71ce38bf/lib/connect.h#L40) is 5 minutes. We want to set it explicitly. curl also doesn't have a default connect timeout. This can lead to hang-ups and slow bashible operation.
We don't
```changes
section: candi
type: feature
summary: Set curl connect timeout to 10s and explicitly set overall timeout to 300s.
```
> [candi] Set curl timeouts

- modules/300-prometheus/templates/alertmanager/internal/alertmanager.yaml
When a public domain is configured the `.spec.externalURL` parameter must be set in the `Alertmanager` manifest [similar](https://github.com/deckhouse/deckhouse/blob/fdc2a2bc3072f5acae424b85eeacd053ec5eb81e/modules/300-prometheus/templates/prometheus/prometheus.yaml#L271-L273) to the Prometheus manifest
This PR fix part of problem with internal alertmanager in #7041 issue
Currently the `.spec.externalURL` parameter is absent, and as a result, in notifications where `externalURL` is used in templates, the link contains the URL of the internal k8s service
This is a minor fix, so there's no need to wait for a minor release
When a public domain is specified the `.spec.externalURL` parameter in the Alertmanager manifest should appear with the corresponding value
```changes …
```
> [prometheus] Set .spec.externalURL in alermanager manifest

- go_lib/deckhouse-config/validator.go
This pr fixes `ModuleConfig` validation in case a module config has empty settings field but there are some required parameters in its OpenApi schema.
As of now, if a module config has empty settings field, the validation process doesn't actually validate any module values and if there are some required parameters in the module's OpenApi schema it entails a deferred error when deckhouse is trying to enable the module. Such ModuleConfigs have to be filtered at creation step.
Closes #6973
ModuleConfigs are get validated even if they don't have .spec.version/.spec.settings fields specified.
```changes
type: fix
summary: Fix ModuleConfig validation for configs with empty settings.
```
> [deckhouse-controller] module config validator

- ee/modules/450-keepalived/images/keepalived/Dockerfile
- ee/modules/450-keepalived/images/keepalived/werf.inc.yaml
- ee/modules/450-keepalived/templates/statefulset.yaml
Keepalived is now built from source and runs on a distroless image.
We want our images to be distroless-based.
```changes
section: keepalived
type: chore
summary: keepalived is now based on a distroless image.
impact: keepalived pods will restart during the update.
```
> [keepalived] Distroless build

- release.yaml
Disable the requirement that blocks Deckhouse updates when the built-in embedded virtualization module is enabled
The embedded virtualization module has been removed. Therefore, this requirement is no longer needed.
```changes
type: chore
summary: Disable the requirement that blocks Deckhouse updates when the built-in embedded virtualization module is enabled.
```
> [virtualization] remove requirement

- ee/modules/650-runtime-audit-engine/images/falco/werf.inc.yaml
- ee/modules/650-runtime-audit-engine/images/rules-loader/requirements.txt
- ee/modules/650-runtime-audit-engine/images/rules-loader/werf.inc.yaml
`runtime-audit-engine` images are now based on a distroless image.
```changes
type: feature
summary: Docker images are based on a distroless image.
```
> [runtime-audit-engine] migrate runtime-audit-engine module to distroless

- dhctl/cmd/dhctl/commands/mirror.go
- dhctl/cmd/dhctl/commands/mirror_modules.go
- dhctl/pkg/app/mirror.go
- dhctl/pkg/app/mirror_modules.go
- dhctl/pkg/operations/mirror/auth.go
- dhctl/pkg/operations/mirror/context.go
- dhctl/pkg/operations/mirror/layouts.go
- dhctl/pkg/operations/mirror/modules.go
- dhctl/pkg/operations/mirror/pull.go
- dhctl/pkg/operations/mirror_module.go
Added `--tls-skip-verify` that forces mirror to accept non-trusted registry certificates.
Users requested this.
```changes
section: dhctl
type: feature
summary: Added a flag that forces mirror to accept non-trusted registry certificates.
```
> [dhctl] mirror: skip registry tls certificate validation flag

- modules/031-ceph-csi/images/cephcsi/Dockerfile
- modules/031-ceph-csi/images/cephcsi/werf.inc.yaml
`cesh-csi` module is based now on a distroless image.
```changes
type: feature
summary: ceph-csi module is based on a distroless image.
```
> [ceph-csi] migrate cesh-csi to distroless

- modules/040-node-manager/templates/capi-controller-manager/rbac-for-us.yaml
- modules/040-node-manager/templates/capi-controller-manager/rbac-to-us.yaml
Add RBAC rules for kube-rbac-proxy.
Fix #6821.
```changes
type: fix
summary: Add RBAC rules for kube-rbac-proxy in capi-controller-manager.
```
> [node-manager](capi) add RBAC rules for `kube-rbac-proxy`

- modules/042-kube-dns/monitoring/prometheus-rules/kubernetes/dns.yaml
Change alert name to send alert directly to cluster owner instead of d8 support
Alert should send to cluster support command. D8 support can't resolve this alert
Alert send to cluster support team
```changes
type: fix
summary: Change D8KubeDnsServiceWithDeprecatedAnnotation alert name
```
> [kube-dns] Change D8KubeDnsServiceWithDeprecatedAnnotation alert name

- dhctl/pkg/preflight/registry.go
Add trailing slash for registryURL in CheckRegistryAccessThroughProxy
This change allows to avoid unnecessary redirects by testing registry (also avoid bug in harbor registry like https://github.com/goharbor/harbor/issues/19773)
Fixes #7049
```changes
section: dhctl
type: fix
summary: Avoid unnecessary redirects by testing registry through proxy
```
> [dhctl] Add trailing slash for registryURL in CheckRegistryAccessThroughProxy

- modules/005-external-module-manager/hooks/create_deckhouse_modules_source.go
- modules/005-external-module-manager/hooks/create_deckhouse_modules_source_test.go
Get scheme from default `deckhouse` ModuleSource from values
If user has changed scheme in ModuleSource and then change some other registry field, scheme will be resetted. It can lead to non-obvious errors and error messages, like [here](https://flant.slack.com/archives/CML93AWG2/p1704962889578619)
```changes
type: fix
summary: Get scheme for `deckhouse` ModuleSource from the deckhouse values
```
> [external-module-manager] Fix default overrite

- dhctl/pkg/kubernetes/actions/deckhouse/install.go
Update the `manifest.resourceVersion` field in the `ModuleConfig` manifest if the `ModuleConfig` manifest already exists in the cluster when the cluster is bootstrapping.
If the cluster bootstrap process is interrupted after generating some `ModuleConfig` manifests and the bootstrap process is started again, messages similar to the following will appear in the bootstrap log:
```
moduleconfigs.deckhouse.io "deckhouse" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```
```changes
section: dhctl
type: fix
summary: fix ModuleConfig update error: 'Invalid value: 0x0: must be specified for an update'
```
> [dhctl](bootstrap) update the `metadata.resourceVersion` field in the `ModuleConfig` manifest

- candi/version_map.yml
- modules/000-common/images/csi-livenessprobe/werf.inc.yaml
- modules/000-common/images/csi-node-driver-registrar/werf.inc.yaml
Fixed vulnerabilities:
- CVE-2022-41723
- CVE-2023-39325
- GHSA-m425-mq94-257g
<details><summary>before</summary>
```shell
csi-node-driver-registrar (gobinary)
Total: 2 (HIGH: 2, CRITICAL: 0)
┌────────────────────────┬─────────────────────┬──────────┬───────────────────┬────────────────────────┬──────────────────────────────────────────────────────────────┐
│        Library         │    Vulnerability    │ Severity │ Installed Version │     Fixed Version      │                            Title                             │
├────────────────────────┼─────────────────────┼──────────┼───────────────────┼────────────────────────┼──────────────────────────────────────────────────────────────┤
│ golang.org/x/net       │ CVE-2023-39325      │ HIGH     │ v0.8.0            │ 0.17.0 …
```
> [common] Fix CVEs in csi livenessprobe and node-driver-registrar

- modules/005-external-module-manager/hooks/cleanup_releases.go
- modules/005-external-module-manager/hooks/cleanup_releases_test.go
Do not consider the Module resource when clearing ModuleRelease
Deckhouse can remove all module releases, because of modules snapshot.
```changes
type: fix 
summary: Fix ModuleRelease nightly cleanup.
```
> [external-module-manager] Fix module release cleanup

- modules/110-istio/hooks/hack_iop_reconciling.go
- modules/110-istio/hooks/hack_iop_reconciling_test.go
Improved `hack_iop_reconciling` hook
Previously, this hook didn't trigger on errors contain `rev.validation.istio.io`.
This hook should be triggered for errors that contain `validation.istio.io` or `*.validation.istio.io`.
```changes
section: istio
type: chore
summary: Improved hack_iop_reconciling hook to prevent istio-operator stucking
```
> [istio] Improved `hack_iop_reconciling` hook

- modules/110-istio/requirements/check.go
- modules/110-istio/requirements/check_test.go
- release.yaml
Add a minimum version of istio to the D8 update requirements.
If the istio version and versions of other component are not compatible, they may not function correctly together.
D8 can't upgrade to next version If istio installed in cluster and it version lower then 1.16 
```changes
section: istio
type: chore
summary: Add a minimum version of istio to the D8 update requirements.
impact: D8 can't upgrade to next version If istio installed in cluster and it version lower then 1.16 
```
> [istio] Add a minimum version of istio to the D8 update requirements.

- deckhouse-controller/pkg/controller/controller.go
Fix modules registration
Modules are not created if they don't have any labels
```changes
summary: Fix modules registration on startup.
```
> [deckhouse-controller] Fix modules registration

- modules/005-external-module-manager/hooks/cleanup_releases.go
- modules/005-external-module-manager/hooks/cleanup_releases_test.go
Reverts deckhouse/deckhouse#7108
Wrong solution was made. Problem in Module resources not in the cleanup script.
ModuleConfigs are get validated even if they don't have .spec.version/.spec.settings fields specified.
```changes
section:  external-module-manager
type: chore
summary: Revert module release cleanup.
```
> Revert "[external-module-manager] Fix module release cleanup"

- docs/site/backends/docs-builder-template/i18n/en.yaml
- docs/site/backends/docs-builder-template/i18n/ru.yaml
- docs/site/backends/docs-builder-template/layouts/partials/openapi/format-schema.html
Show that a parameter is required according to the OpenAPI spec in the modules documentation.
```changes
section: docs
type: chore
summary: Show that a parameter is required according to the OpenAPI spec in the modules documentation.
```
> [docs][modules-docs] Show that a parameter is required according to the OpenAPI spec.

- modules/035-cni-flannel/docs/CONFIGURATION.md
- modules/035-cni-flannel/docs/CONFIGURATION_RU.md
Fix documentation of the cni-flannel module. cni-flannel is NOT enabled automatically in OpenStack and Vsphere.
```changes
type: chore
summary: Update documentation.
```
> [cni-flannel][docs] Update documentation

- docs/documentation/_data/sidebars/main.yml
Rename the item for the admission-policy-engine module in the sidebar.
```changes
section: docs
type: chore
summary: Rename the item for the admission-policy-engine module in the sidebar.
```
> [docs] Rename the item for the admission-policy-engine module in the sidebar

- modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring/cronjob.yaml
added the CronJobFailed alert group
Closes #2106
```changes
type: feature
summary: added the CronJobFailed alert group
```
> [extended-monitoring] added the CronJobFailed alert group

- testing/cloud_layouts/Static/resources.tpl.yaml
- testing/cloud_layouts/script.sh
In current static e2e tests, all static nodes bootstrapped manually, sending bash script to the node. Recently, we added Cluster API Provider Static (CAPS) for managing static nodes. We need to add this kind of node to e2e Static tests.
It is needed to bootstrap nodes with Cluster API Provider Static (CAPS) in e2e static tests. 
Worker node bootstraps using CAPS.
```changes
type: feature
summary: Change worker node bootstrap from manual to CAPS.
```
> [testing] Change worker node bootstrap from manual to CAPS

- candi/bashible/common-steps/all/006_fetch_registry_packages.sh.tpl
- candi/bashible/common-steps/all/062_install_kubelet_and_his_friends.sh.tpl
- candi/bashible/common-steps/all/064_fix_permission_on_cni_files.sh.tpl
- candi/bashible/common-steps/all/066_fix_permission_on_cni_files.sh.tpl
- candi/bashible/common-steps/cluster-bootstrap/035_install_kubeadm.sh.tpl
- modules/007-registrypackages/images/kubernetes-cni/scripts/install
- modules/007-registrypackages/images/kubernetes-cni/scripts/uninstall
- modules/007-registrypackages/images/kubernetes-cni/werf.inc.yaml
- testing/library/images_tags_generated.go
Updating cni-plugins to version 1.4.0
Using the most recent stable version.
Partial solution of issue https://github.com/deckhouse/deckhouse/issues/6454
The version of cni-plugins (located in /opt/cni/bin/) is 1.4.0
New ipam host-local files (located in /var/lib/cni/networks) are created with a permission 600
```changes
section: candi
type: chore
summary: Update `cni-plugins` to version `1.4.0`.
impact: "cni-plugins will be recreated during the upgrade."
```
> [candi] bump cni-plugins version to 1.4.0

- modules/002-deckhouse/webhooks/validating/disable_virtualization_module
Add a validating webhook to prevent the linstor module from being enabled.
The linstor module should not be allowed to be enabled because we are moving to sds-drbd module.
It will not be possible to enable the module if it has not been enabled before, alas to change module config.
```changes
type: chore
summary: Add a validating webhook to prevent the linstor module from being enabled.
impact: The `linstor` module is deprecated. Please switch to [sds-drbd](https://deckhouse.io/modules/sds-drbd/stable/) module ASAP. The `linstor` module cannot be enabled but will continue to work if it was already enabled before.
```
> [linstor] add validating webhook to disable module

- deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go
- modules/041-linstor/hooks/requirement_release_on_module_delete.go
- modules/041-linstor/hooks/requirement_set_if_module_is_enabled.go
- modules/041-linstor/requirements/check.go
- modules/041-linstor/requirements/check_test.go
Disable Deckhouse update while linstor module is enabled.
Ref: https://github.com/deckhouse/deckhouse/pull/7086
You must disable the legacy linstor module before it can be completely removed from the deckhouse.
Deckhouse will not update until the linstor module is disabled.
```changes
type: chore
summary: Disable Deckhouse update while `legacy` linstor module is enabled.
impact: Deckhouse will not be able to perform an upgrade if `linstor` module is enabled.
```
> [linstor] prevent Deckhouse update while Linstor module is enabled

- .github/ci_templates/tests.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- Makefile
- deckhouse-controller/pkg/helpers/change_registry/change_registry.go
- deckhouse-controller/pkg/helpers/change_registry/change_registry_test.go
Fixed a bug where helper would not properly marshal provided credentials for registry into the secret. Unit tests of `deckhouse-controller` are now enabled as part of CI pipeline.
This fixes a reported bug introduced with a `go-containerregistry` update.
```changes
type: fix
summary: fix for `change-registry` helper's handling of registry credentials.
```
> [deckhouse-controller] Fix auth data handling in change-registry helper

- .github/scripts/js/ci.js
- .github/scripts/js/constants.js
- .github/workflow_templates/validation.yml
- .github/workflows/validation.yml
- testing/validate_grafana_dashboard.sh
- tools/validation/grafana_dashboard.go
- tools/validation/grafana_dashboard_test.go
- tools/validation/main.go
- tools/validation/messages.go
Grafana dashboard linter
Closes #7081
Related to #7018 and #7027
CI fail when:
- Dashboard contains a deprecated query interval (deprecated intervals: `$__interval_rv`, `$__interval_sx3` and `$__interval_sx4`)
- Dashboard contains a legacy alert rule (alert rule that is configured on dashboard table and uses Grafana < 9.x internal alerting)
- Dashboard contains a hard-coded datasource uid (uid is copied as-is, without using Grafana variable of `Datasource` type)
```changes
section: tools | testing
type: chore
summary: Grafana dashboard linter
```
> [grafana] Dashboard linter

- README.md
- candi/cloud-providers/gcp/terraform-modules/versions.tf
- modules/040-terraform-manager/images/terraform-manager-gcp/werf.inc.yaml
rename plugin terraform-provider-gcp to terraform-provider-google in terraform-state-exporter
Solved an issue with error "Validating provider hashicorp/google v3.48.0 failed: provider binary not
found: could not find executable file starting with terraform-provider-google"
```changes
type: fix
summary: rename plugin terraform-provider-gcp to terraform-provider-google in terraform-state-exporter
```
> [terraform-manager] fix a binary name for terraform-provider-google plugin

- modules/340-extended-monitoring/images/extended-monitoring-exporter/Dockerfile
- modules/340-extended-monitoring/images/extended-monitoring-exporter/src/requirements.txt
- modules/340-extended-monitoring/images/extended-monitoring-exporter/werf.inc.yaml
`extended-monitoring-exporter` image is based on a distroless image.
```changes
type: feature
summary: |
`extended-monitoring-exporter` image is based on a distroless image.
```
> [extended-monitoring] migrate exporter image to distroless

- dhctl/pkg/preflight/registry.go
- dhctl/pkg/preflight/registry_test.go
Fix skipping preflight check about registry-through-proxy.
Close #7045
```changes
section: dhctl
type: fix
summary: fix skipping preflight check about registry-through-proxy
```
> [dhctl](install) fix skipping preflight check about registry-through-proxy

- ee/modules/450-network-gateway/images/dnsmasq/Dockerfile
- ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
- ee/modules/450-network-gateway/images/snat/Dockerfile
- ee/modules/450-network-gateway/images/snat/werf.inc.yaml
- ee/modules/450-network-gateway/templates/dhcp-statefulset.yaml
- ee/modules/450-network-gateway/templates/snat-daemonset.yaml
`network-gateway` module is based on a distroless image.
```changes
section: network-gateway
type: feature
summary: network-gateway module is based on a distroless image.
```
> [network-gateway] migrate network-gateway module to distroless

- modules/500-upmeter/images/upmeter/cmd/upmeter/parse_args.go
- modules/500-upmeter/images/upmeter/pkg/db/dao/episode5m.go
- modules/500-upmeter/images/upmeter/pkg/server/server.go
- modules/500-upmeter/templates/upmeter/statefulset.yaml
Add retention ability for upmeter database. 
It is not configurable and equal 548 days.
Retention started once per day.
Close https://github.com/deckhouse/deckhouse/issues/6285
```changes
type: feature 
summary:  database retention
impact: The upmeter database will only store data for the last 548 days
```
> [upmeter] database retention

- modules/402-ingress-nginx/crds/ingress-nginx.yaml
- modules/402-ingress-nginx/hooks/generate_admission_webhook_cert_test.go
- modules/402-ingress-nginx/hooks/get_ingress_controllers_test.go
- modules/402-ingress-nginx/hooks/migrate_daemonset_and_pods_test.go
- modules/402-ingress-nginx/hooks/minimal_ingress_nginx_version_test.go
- modules/402-ingress-nginx/hooks/safe_daemonset_update_test.go
- modules/402-ingress-nginx/openapi/config-values.yaml
- modules/402-ingress-nginx/template_tests/controller_test.go
- release.yaml
This reverts  https://github.com/deckhouse/deckhouse/pull/6795 (commit ecbec6b4e560496826cf45f9f7452b19f36e017b). 
```changes
type: chore
summary: Revert  https://github.com/deckhouse/deckhouse/pull/6795.
```
> Revert "[ingress-nginx] remove ingress-nginx version 1.1 (#6795)"

- docs/site/_includes/getting_started/bm-private/partials/config.ru.yml.ce.inc
- docs/site/_includes/getting_started/bm-private/partials/config.yml.ce.inc
- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
- docs/site/_includes/getting_started/bm/partials/config.ru.yml.ce.inc
- docs/site/_includes/getting_started/bm/partials/config.ru.yml.ee.inc
- docs/site/_includes/getting_started/bm/partials/config.yml.ce.inc
- docs/site/_includes/getting_started/bm/partials/config.yml.ee.inc
- Remove `storageClass` from `global` `moduleConfig`
- Move creation of `LocalPathProvisioner` `StorageClass` step before bootstrapping a worker node. 
- Setting `storageClass` in `global` `moduleConfig` isn't needed, as this parameter [should only be used in exceptional circumstances.](https://deckhouse.io/documentation/v1/deckhouse-configure-global.html#parameters-storageclass)
- Creation of `StorageClass` before bootstrapping first worker node ensures that `d8` components won't get created using `emptyDir`
- The 'Use master without taints' variant will still use `EmptyDirs`. Before there was no way to start StatefulSets correctly.
```changes
section: docs
type: chore
summary: Minor changes to getting started docs.
```
> [docs] Fix storageClass in bare metal GS

- docs/documentation/_plugins/openapi.rb
Render examples from the .spec.[]versrions.schema.openAPIV3Schema.[x-doc-examples|x-doc-example|x-examples|example] field. It is a good place for examples of the whole CRD.
At now, the site generator renders only examples from the field of an OpenAPI spec.
```changes
section: docs
type: chore
summary: Render examples of the whole CRD from the spec.
```
> [docs][openapi] Render general CRD examples

- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
- deckhouse-controller/pkg/controller/module-controllers/release/override-controller.go
- deckhouse-controller/pkg/controller/module-controllers/utils/utils.go
- go_lib/deckhouse-config/service.go
Adds checks to module release/override controllers to check if deckhouse-config service was initialized before creating controllers' workers.
As of now, Deckhouse panics on restart if there are Pending module releases or module pull overrides in the cluster because deckhouse-config service gets initialized a bit after module release/override controllers. It should be checked before starting module controllers if deckhouse-config service was initialized.
Closes #7139
Deckhouse doesn't panic on restart if there are Pending module releases or module pull overrides in the cluster.
```changes
section: deckhouse-module-controller
type: chore
summary: Add deckhouse-service initialization check.
```
> [external-module-manager] add deckhouse-service init heck for release/override controllers

- modules/402-ingress-nginx/templates/failover/configmap.yaml
Updates `proxy-failover` configmap template so that if `.spec.acceptRequestsFrom` isn't set, no filters are applied by `proxy-failover` nginx.
Pr fixes a nasty bug in `HostWithFailover` ingress-nginx inlet when there is no `.spec.acceptRequestFrom` setting in an ingress-nginx and `proxy-failover` just denies all requests, resulting in an outage when upgrading `ingress-nginx`.
It's a bug in ingress-nginx module and it's better to fix it in the current release.
if `.spec.acceptRequestsFrom` isn't set, `proxy-failover` configmap should be empty and has no filters set.
```changes
type: fix
summary: Fix HostWithFailover inlet proxy filter.
```
> [ingress-nginx] fix hostwithfailover proxy filter

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/loadbalancer.yaml
When the alert is active, it makes an error, because of `incorrect plk_group param`.
Alert appears with error.
Not necessary but has a medium impact.
Alert appears correctly.
```changes
type: chore
summary: Correct the `LoadBalancerServiceWithoutExternalIP` alert.
```
> [monitoring-kubernetes] Correct LoadBalancerServiceWithoutExternalIP alert

- candi/openapi/node_group.yaml
Temporary fix.
Markup breaks if there is more than one example on the root level of the CRD spec.
```changes
section: docs
type: chore
summary: Fix nodeGroup examples.
```
> [docs][openapi] Update nodeGroup examples to fix markup

- docs/documentation/werf-git-section.inc.yaml
Remove DeckhouseControlPlane CR from the documentation.
```changes
section: docs
type: chore
summary: Remove DeckhouseControlPlane CR from the documentation.
```
> [docs][openapi][node-manager] Remove DeckhouseControlPlane CR from the documentation

- modules/021-cni-cilium/templates/user-authz-cluster-roles.yaml
Grant users access to view and edit `ciliumnetworkpolicies` based on `user-authz` roles
Currently, users created and configured with `user-authz` and `user-authn` do not have access to view and edit `ciliumnetworkpolicies`.
Users created and configured with `user-authz` and `user-authn` will have access to view and edit `ciliumnetworkpolicies`.
```changes
type: chore
summary: Add user-authz RBACs for `ciliumnetworkpolicies`.
```
> [cni-cilium] add RBAC for ciliumnetworkpolicies

- modules/021-cni-cilium/monitoring/grafana-dashboards/kubernetes-cluster/cilium-agent.json
Refresh dashboard for cni-cilium
We want to have an up-to-date dashboard.
The dashboard is fresh (i.e. the title is Cilium Metrics, not Cilium 1.12 Metrics).
```changes
type: chore
summary: Refresh dashboard for cni-cilium
```
> [cni-cilium] change cilium dashboard 

- testing/cloud_layouts/script.d/wait_cluster_ready/test_alerts.sh
In e2e tests with OS on older cores (AWS, Azure), ebpf_exporter does not run. Because of it e2e test crushes.
Need to ignore alert if it is appear in e2e tests to pass e2e test. We need to check how dechouse works on old OS now.
KubernetesDaemonSetReplicasUnavailable alert will be marked as ignored in e2e test log. 
```changes
type: chore
summary: Ignore KubernetesDaemonSetReplicasUnavailable alert in e2e tests
```
> [testing] Ignore KubernetesDaemonSetReplicasUnavailable alert in e2e tests

- ee/modules/600-flant-integration/templates/pricing/config.yaml
Shell operator hooks metrics path was changed from `metrics` to `metrics/hooks`. This PR sets correct path.
No metrics from flant pricing
```changes
type: fix
summary: Correct `metrics_path`.
```
> [flant-integration] Correct metrics_path for flant-pricing container

- ee/modules/110-istio/monitoring/prometheus-rules/federation.yaml
- ee/modules/110-istio/monitoring/prometheus-rules/multicluster.yaml
Fix diagnostic instructions in istio federation/multicluster alerts.
deckhouse-commander args have been changed, but the alert's wern't actualized.
There are alerts with wrong instructions.
```changes
section: istio
type: fix
summary: Fix diagnostic instructions in istio federation/multicluster alerts.
```
> [istio] Fix depricated instructions for  Reproducing request in alerts

- modules/002-deckhouse/images/webhook-handler/werf.inc.yaml
- modules/300-prometheus/images/prometheus/werf.inc.yaml
- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Update version of prometheus from v2.44.0 to v2.45.2 (LTS version)
Update used build image for using Go 1.21
Remove downloads of unnecessary dependencies (because they updated in prometheus)
Fixes https://github.com/deckhouse/deckhouse/issues/7193
```changes
type: fix
summary: Update version of `prometheus` from `v2.44.0` to `v2.45.2`.
```
> [prometheus] Update version of prometheus from v2.44.0 to v2.45.2

- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
Update restoreAbsentSourceModules so that it also checks that there is up to date version of a module is used by deckhouse.
It should fix the problem with multi-master clusters when masters have different version of modules on their file systems. Only latest deployed version should be used by masters.
It fixes a bug.
If there is a symlink leading to an old superseded version of a module, this symlink should be updated to the latest module version directory.
```changes
type: fix
summary: Fix outdated module versions in multi-master environment.
```
> [external-module-manager] fix restore absent module for multi master

- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
* Before restoring a module symlink we check if there is another symlink for the module in the folder and delete it if it's the case.
* fixes message formats
Fixes a situation when module controller restores a missing symlink for current version of a module, ending up having several symlinks for the module if the module's weight was changed in the newer release.
It fixes current issue for sds-drbd module.
Module controller deletes old symlink if it exists before restoring a module from its source.
```changes
type: fix
summary: Fix multiple symlinks for a single module in the symlink folder.
```
> [external-module-manager] delete old symlinks on restore

- candi/openapi/node_group.yaml
- modules/040-node-manager/templates/node-group/_bootstrap.tpl
Allow specifying the `staticInstance` field in a NodeGroup with type CloudStatic.
Close #6970
```changes
type: feature
summary: Allow specifying the 'staticInstance' field in a NodeGroup with type CloudStatic.
```
> [node-manager] allow specifying the staticInstance field in a NodeGroup with type CloudStatic

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/pod-status.yaml
Correct a grammatical error in alert PodStatusIsIncorrect annotations
```changes
type: fix
summary: Fix a grammatical error in alert PodStatusIsIncorrect annotations
```
> [monitoring-kubernetes] Fix grammatical error in alert's annotations

- candi/bashible/bashbooster/50_deckhouse_registrypackages.sh
The ability to install packages from images inside an external module has been added
We need to be independent of Deckhouse releases in order to add new images with software packages.
We need this change to be implemented in production within a reasonable timeframe.
We can add images with software packages outside the Deckhouse release cycle.
```changes
type: feature
summary: The ability to install packages from images inside an external module has been added
```
> Ability to install packages from images inside an external module has been added

- candi/openapi/node_group.yaml
- modules/040-node-manager/hooks/migration/migrate_system_reserve.go
Fix setting the default value for the `kubelet.resourceReservation` parameter in `NodeGroup`.
```changes
section: candi
type: fix
summary: Fix setting the default value for the `kubelet.resourceReservation` parameter in `NodeGroup`.
```
> [candi] Fixed setting default value for kubelet resourceReservation

- modules/300-prometheus/images/alerts-receiver/src/main.go
Add RLock/RUnlock while reading memStore alert map on periodic reconcile.
This map is also accessed by the webserver handler (evokes insertAlert() which uses Lock/Unlick).
Alerts-receiver periodically throws `fatal error: concurrent map iteration and map write` errors.
```
goroutine 35 [running]:
main.reconcile({0xc7ce58, 0xc000223480}, 0xc00021fdd0)
/app/main.go:96 +0x1e6
main.reconcileLoop({0xc7ce58, 0xc000223480}, 0x0?)
/app/main.go:80 +0x59
created by main.main
/app/main.go:63 +0x31f
goroutine 1 [chan receive, 301 minutes]:
main.main()
/app/main.go:65 +0x339
goroutine 8 [syscall, 301 minutes]:
os/signal.signal_recv()
/usr/local/go/src/runtime/sigqueue.go:152 +0x2f
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1 …
```
> [prometheus] alerts-receiver: fix concurrent map access

- candi/openapi/init_configuration.yaml
Add validation pattern for the `imagesRepo` parameter.
Fixes https://github.com/deckhouse/deckhouse/issues/7046
```changes
section: candi
type: fix
summary: Add validation pattern for the `imagesRepo` parameter.
```
> [candi] Add validation pattern for imagesRepo value

- ee/modules/650-runtime-audit-engine/templates/falco-rules.yaml
Remove the `trusted_sa` macros in Falco rules.
Close #6961. Replace #7001.
```changes
type: fix
summary: Remove the `trusted_sa` macros in Falco rules.
```
> [runtime-audit-engine] remove `trusted_sa` macro

- .github/CODEOWNERS
cni-cilium codeowner is apolovov.
```changes
section: ci
type: chore
summary: cni-cilium codeowner is apolovov
```
> [ci] cni-cilium codeowner is apolovov

- dhctl/pkg/operations/mirror/auth_test.go
- dhctl/pkg/operations/mirror/bundle_test.go
- dhctl/pkg/operations/mirror/digests_test.go
- dhctl/pkg/operations/mirror/versions.go
- dhctl/pkg/operations/mirror_test.go
Added some tests for mirroring.
Why not?
```changes
section: dhctl
type: chore
summary: Added tests for dhctl mirror.
```
> [dhctl] mirror tests

- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
- deckhouse-controller/pkg/controller/module-controllers/release/override-controller.go
This pr introduces additional logic for restoring module releases which can be described in the following steps:
1) on bootstrap we cycle over deployed module releases;
2) if there is a `ModulPullOverride` for a deployed release in the cluster, we skip restoring of this module release;
3) if there is no `ModulPullOverride` for the deployed release there, we check for the symlink pointing to up-to-date version of the module and restore it if necessary;
4) after cycling over deployed releases, we cycle over `ModulPullOverride` objects;
5) if there is a `ModuleSource` for a `ModulPullOverride`, we try to download relevant module dev image from the source;
6) we check for the symlink pointing to dev version of the module and restore it if necessary;
Apart from restoring correct versions of …
> [external-module-manager] restore mpo

- modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
Kubernetes version 1.24 support will be removed in the next Deckhouse release (1.58).
```changes
type: feature
summary: Kubernetes version 1.24 support will be removed in the next Deckhouse release (1.58).
```
> [control-plane-manager] End-of-life alert for kubernetes 1.24

- candi/version_map.yml
Mark K8s 1.24 as EOL on the site.
Ref: https://github.com/deckhouse/deckhouse/pull/7268
```changes
section: docs
type: chore
summary: Mark K8s 1.24 as EOL on the site.
```
> [docs] Mark K8s 1.24 as EOL on the site

- .github/ci_includes/werf_envs.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- tools/images_tags/main.go
- werf-giterminism.yaml
- werf.yaml
This reverts #7304.
```changes
section: ci
type: chore
summary: This reverts #7304.
```
> Revert "[chore] Add env PIPPROXY (#7304)"

- modules/002-deckhouse/hooks/update_deckhouse_image.go
- modules/002-deckhouse/hooks/update_deckhouse_image_test.go
Close #7133 
Cluster bootstrap action was changed and first release is stuck in pending state. We have to change first release apply logic also.
```changes
type: fix
summary: Fix release apply on the cluster bootstrap.
```
> [deckhouse] Change cluster bootstrap logic

- modules/300-prometheus/images/alerts-receiver/src/main.go
- modules/300-prometheus/images/alerts-receiver/src/memstore.go
Instead of deleting resolved alerts one by one, we accumulate them in a list, take a Lock over memStore and delete all of them at once.
There is a bug in the code: It takes RLock for the whole loop over memstore map while inside the loop there is another Lock to delete some elemets from the map. It prevents alerts-receiver from deleting stale alerts from memStore.
It fixes a bug introduced by another fix.
Clusteralerts are get deleted properly.
```changes
section: prometheus-operator
type: fix
summary: Fix alerts-receiver reconcile loop issue.
impact: Alerts-receiver pod will be recreated.
```
> [prometheus] fix alerts-receiver lock issue

- dhctl/pkg/kubernetes/actions/converge/converge.go
Now if user deny converge base infra then dhctl returns error.
W've fixed it.
User cannot converge cloud permanent node if base infra has changes.
It is bug.
```changes
section: dhctl
type: fix
summary: Skip converge base infra if user does not want converge base infra
```
> [dhctl] Skip converge base infra if user does not want converge base infra

- docs/site/_includes/copyright.html
Set the date in the documentation footer automatically.
```changes
section: docs
type: chore
summary: Set the date in the documentation footer automatically.
```
> Fixed copyright date in footer

- .github/workflow_templates/build-and-test_release.yml
- .github/workflows/build-and-test_release.yml
Add if for ee and be edition when build main branch
Random tag main image
```changes
section: ci
type: fix 
summary: Fix build main branch
```
> [ci] Fix build main branch

- candi/cloud-providers/aws/openapi/cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/cluster_configuration.yaml
- candi/cloud-providers/gcp/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/doc-ru-cluster_configuration.yaml
- dhctl/pkg/config/base.go
- dhctl/pkg/config/validation.go
- dhctl/pkg/config/validation_rules.go
- dhctl/pkg/config/validation_test.go
- dhctl/pkg/template/resources.go
- dhctl/pkg/util/input/yaml.go
- ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/vsphere/openapi/cluster_configuration.yaml
Add ClusterConfiguration openapi extensions. Support new extensions in ValidateClusterSettingsChanges function. 
Better ClusterConfiguration validation in Commander. Prevent potentially dangerous field changes when updating configuration.
> [dhctl] feat(dhctl-for-commander) Add more ClusterConfiguration validations

- modules/021-cni-cilium/images/operator/werf.inc.yaml
- modules/021-cni-cilium/templates/operator/deployment.yaml
cilium-operator is based on a distroless images.
```changes
type: chore
summary: cilium-operator is now based on a distroless images
impact: cilium-operator pods will restart.
```
> [cni-cilium] migrate cilium-operator image to distroless

- docs/site/.helm/templates/20-ingress.yaml
Add a redirect for the virtualization module, as the internal virtualization module was substituted by [the new module](https://deckhouse.io/modules/virtualization/stable/).
```changes
section: docs
type: chore
summary: Add a redirect for the virtualization module.
```
> Add redirect for the virtualization module.

- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/cmd/dhctl/commands/destroy.go
- dhctl/pkg/infrastructure/base.go
- dhctl/pkg/infrastructure/cluster.go
- dhctl/pkg/infrastructure/nodes.go
- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/kubernetes/actions/converge/nodebootstrap.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-abort.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-base-infra.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/operations/bootstrap/steps.go
- dhctl/pkg/operations/destroy/destroy.go
- dhctl/pkg/terraform/pipeline.go
- dhctl/pkg/terraform/terraform_context.go
Prepare terraform runner creation code to reuse terraform runners between check and actual converge inside check+converge operation. This is part 1/2 PR to achieve this task.
Plan should be generated only once, because we approve first plan generated by the terraform check. It should not be changed after this approval. Otherwise we will converge unapproved changes.
> [dhctl] fix(dhctl-for-commander): create all terraform runners using TerraformContext

- candi/openapi/dhctl/ssh_configuration.yaml
- candi/openapi/dhctl/ssh_host_configuration.yaml
- dhctl/pkg/config/dhctl.go
- dhctl/pkg/config/dhctl_test.go
- dhctl/pkg/config/load.go
- dhctl/pkg/config/load_test.go
- dhctl/pkg/config/validation_test.go
Add ssh connection config parsing/validating with openapi specs.
In commander we use dhctl as a library. Therefore, obtaining configuration for ssh connection from cli arguments is not suitable for us. Added the ability to parse the configuration from a string and openapi spec
> [dhctl] feat(dhctl-for-commander) Add ssh openapi specs

- dhctl/pkg/app/mirror.go
- dhctl/pkg/operations/mirror.go
- dhctl/pkg/operations/mirror/layouts.go
- dhctl/pkg/operations/mirror/layouts_test.go
- dhctl/pkg/operations/mirror/trivy-db.go
- dhctl/pkg/operations/mirror/trivy-db_test.go
- dhctl/pkg/operations/mirror_test.go
Added Trivy vulnerability database image to mirror dumps.
This fixes `operator-trivy` scanning in isolated environments.
It's a bugfix.
```changes
section: dhctl
type: fix
summary: Mirroring will now include Trivy vulnerability database image.
```
> [dhctl] Mirror Trivy vulnerability database image

- testing/cloud_layouts/script.d/wait_cluster_ready/test_alerts.sh
- testing/cloud_layouts/script.sh
On kernels <5.08, the ebpf exporter cannot start. Fix the validation warning in the e2e tests that are displayed on older kernels.
In some clouds, we run vm's with a kernel lower than 5.08. e2e tests with this vm's fail due to an incorrect kernel. We have to ignore it.
The e2e test runs on virtual machines running on old kernels. On a newer kernel, we should not ignore the alerts "D8NodeHasUnmetKernelRequirements" and "KubernetesDaemonSetReplicasUnavailable".
```changes
type: fix
summary: Ignore alerts generated by not init ebpf exporter only for older kernels in e2e tests.
```
> [testing] Ignore alerts generated by not init ebpf exporter only for older kernels in e2e tests

- docs/site/backends/docs-builder-template/config/_default/hugo.yaml
Update Hugo config. Allow inline HTML rendering.
Want to render inline HTML like complicated tables e. g., that can't be properly rendered using markdown 
```changes
section: docs
type: chore
summary: Update Hugo config.
```
> [docs][module documentation] Update renderer config

- ee/modules/500-operator-trivy/images/node-collector/patches/001-change-node-collector-config.patch
The node-collector patch was remastered so that node-collector would be able to test different settings set via flags or in a config file. Some tests were updated to check settings relevant in deckhouse environment.
The CIS benchmark provided by trivy wasn't reliable as it had some results hard-coded no matter what was really configured on a tested kubernetes node.
Trivy CIS benchmark provides consistent results according to what is configured on a tested kubernetes node.
```changes
type: chore
summary: Remaster trivy node-collector audit settings.
```
> [operator-trivy] update node-collector audit

- modules/150-user-authn/templates/dex-authenticator/deployment.yaml
[user-authn] Bring dex-auth to complience with restricted admission-control policy
When `restricted` policy of admission-control module is active for namespace, dex-authentificator pods cannot to start in it.
To comply the requirements of admission-control module, some "capabilities drop" must be injected to deployment manifest
Some clients encountered with this issue, and asked for solution.
When this patch applied, during enabled admission-policy module is enabled, dex-authentificator pods is able to start and work as expected in namespaces with label `security.deckhouse.io/pod-policy: restricted`.
```changes
type: fix
summary: dex-authentificator is able to run in namespaces with restricted admission-policy
```
> [user-authn] Bring dex-auth manifest to complience with restricted admission-control policy

- modules/042-kube-dns/monitoring/prometheus-rules/kubernetes/dns.yaml
Change the description field for the `KubeDnsServiceWithDeprecatedAnnotation` alert.
Description is displayed like ```kubectl -n  get svc  -o yaml``` instead ```kubectl -n prod get svc mongo -o yaml```
```changes
type: fix
summary: Change the description field for the `KubeDnsServiceWithDeprecatedAnnotation` alert.
```
> [kube-dns] Fix description for KubeDnsServiceWithDeprecatedAnnotation

- modules/460-log-shipper/docs/README.md
- modules/460-log-shipper/docs/README_RU.md
- modules/460-log-shipper/hooks/internal/composer/testdata/config_1.json
- modules/460-log-shipper/hooks/internal/composer/testdata/config_2.json
- modules/460-log-shipper/hooks/internal/composer/testdata/config_4.json
- modules/460-log-shipper/hooks/internal/vector/destination/loki.go
- modules/460-log-shipper/hooks/internal/vector/source/kubernetes.go
- modules/460-log-shipper/hooks/internal/vrl/cleanup.go
- modules/460-log-shipper/hooks/testdata/es-5x/result.json
- modules/460-log-shipper/hooks/testdata/file-to-elastic/result.json
- modules/460-log-shipper/hooks/testdata/file-to-kafka-tls/result.json
- modules/460-log-shipper/hooks/testdata/file-to-kafka/result.json
- modules/460-log-shipper/hooks/testdata/file-to-loki/result.json
- modules/460-log-shipper/hooks/testdata/file-to-splunk/result.json
- modules/460-log-shipper/hooks/testdata/file-to-vector/result.json
- modules/460-log-shipper/hooks/testdata/many-to-one/result.json
- modules/460-log-shipper/hooks/testdata/multiline-custom-pods/result.json
- modules/460-log-shipper/hooks/testdata/multiline-custom/result.json
- modules/460-log-shipper/hooks/testdata/multiline/result.json
- modules/460-log-shipper/hooks/testdata/multiple-dest/result.json
- modules/460-log-shipper/hooks/testdata/namespaced-source/result.json
- modules/460-log-shipper/hooks/testdata/one-dest/result.json
- modules/460-log-shipper/hooks/testdata/pair-datastream/result.json
- modules/460-log-shipper/hooks/testdata/simple-pair/result.json
- modules/460-log-shipper/hooks/testdata/throttle-with-filter/result.json
- modules/460-log-shipper/hooks/testdata/throttle/result.json
Add node labels to vector log metadata. 
Now it's possible to filter logs also by a node group name. We can choose different log destinations depending on a node group name for example.
Log shipper collects node labels
```changes
type: feature
summary: New labels for log filtering.
```
> [log-shipper] add node group name to logs metadata

- ee/modules/500-operator-trivy/images/node-collector/Dockerfile
- werf.yaml
Update the base image for the operator-trivy module.
Ref: https://github.com/deckhouse/deckhouse/pull/7329
The build of the 1.57 release fails.
```changes
type: chore
summary: Update the base image for the operator-trivy module.
```
> [operator-trivy] Update base image

- dhctl/pkg/config/base.go
- dhctl/pkg/config/connection.go
- dhctl/pkg/config/connection_test.go
- dhctl/pkg/config/load.go
- dhctl/pkg/config/validation.go
- dhctl/pkg/config/validation_test.go
Add new validate functions which support `Strict` unmarshal.
To return an error in Commander to the user as quickly as possible and prevent errors with fields being overwritten
> [dhctl] feat(dhctl-for-commander) Add strict unmarshal mode

- candi/openapi/dhctl/ssh_configuration.yaml
- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/cmd/dhctl/commands/control-plane.go
- dhctl/cmd/dhctl/commands/converge.go
- dhctl/cmd/dhctl/commands/deckhouse.go
- dhctl/cmd/dhctl/commands/destroy.go
- dhctl/cmd/dhctl/commands/edit.go
- dhctl/cmd/dhctl/commands/kube.go
- dhctl/cmd/dhctl/commands/lock.go
- dhctl/cmd/dhctl/commands/ssh.go
- dhctl/cmd/dhctl/commands/terraform.go
- dhctl/pkg/app/ssh.go
- dhctl/pkg/config/base.go
- dhctl/pkg/config/connection.go
- dhctl/pkg/config/connection_test.go
- dhctl/pkg/config/load.go
- dhctl/pkg/config/load_test.go
- dhctl/pkg/config/validation.go
- dhctl/pkg/config/validation_test.go
- dhctl/pkg/terraform/pipeline_test.go
- dhctl/pkg/terraform/runner_test.go
Added the ability to specify ssh settings using a configuration file. Thus, the same code will be used in the cli and in the commander for parsing and validating connection configuration.
A uniform approach to obtaining configuration for connecting via ssh.
The main problem was that the `app` package with global variables was imported everywhere in the project. Importing the `config` package from the `app` package resulted in cyclic imports. Because of this, I was not able to parse the ssh configuration file in the `DefineSSHFlags` function.
I had to slightly change the calls to the `app.DefineSSHFlags` function and add another parameter with the config parser.
> [dhctl] feat(dhctl-for-commander) Add ssh -connection-config flag

- ee/modules/380-metallb/templates/speaker/daemonset.yaml
Adding livenessProbe and readinessProbe in metallb speaker spec.
Goals:
Reducing the number of errors when launching the pod.
Making updating smoother and seamless.
This patch will significantly improve stability of metallb in certain prod-clusters.
If the Metallb speaker pods are not working properly, they will be restarted.
The update process will be smoother and more seamless.
```changes
type: fix
summary: Adding livenessProbe and readinessProbe in metallb speaker spec.
impact: The metallb-speaker pods will be restarted.
```
> [metallb] Add livenessProbe and readinessProbe to speaker

- modules/042-kube-dns/templates/sts-pods-hosts-appender-webhook/webhook-configuration.yaml
increased the waiting timeout for the sts-pods-hosts-appender-webhook so that there would be no waiting errors for StatefulSets with large manifests.
If the StatefulSet manifest is large, the webhook takes a long time to work out.
```changes
type: fix 
summary: Increased sts-pods-hosts-appender-webhook wait timeout
```
> [kube-dns] fixed sts-pods-hosts-appender-webhook wait timeout

- modules/402-ingress-nginx/template_tests/controller_test.go
Adds missing tests for proxy-failover configmap of HostWithFailover inlet.
New configmap template for proxy-failover was introduced but it wasn't covered with tests.
Related tests are in place and they pass.
```changes
section: Ingress-nginx
type: chore
summary: Add missing tests.
```
> [ingress-nginx] add missing tests for proxy-failover configmap

- modules/040-node-manager/webhooks/validating/node_group
Forbid to change NodeGroup if it contains unknown zone.
Now, if a NodeGroup contains an unknown zone (e.g. a typo), node-manager will remove it from internal values and all nodes in that NodeGroup will be removed.
We added new zone support to YandexCloud in release 1.56 (https://github.com/deckhouse/deckhouse/pull/6652) and users can start actively changing zones in NodeGroup manifests and can break their cluster through configuration errors or typos.
```changes
type: fix
summary: Forbid to change NodeGroup if it contains unknown zone.
```
> [node-manager] Forbid to change NodeGroup if it contains unknown zone

- modules/040-node-manager/crds/nodeuser.yaml
If we create a NodeUser following the examples from the instructions (uid: '1100'), we get an error 'apply resource "NodeUser/arch": failed to create typed patch object (/arch; deckhouse.io/v1, Kind=NodeUser): .spec.uid: expected numeric (int or float), got string'
```changes
section: docs
type: fix
summary: Change NodeUser uid example type (from string to number).
```
> [docs][node-manager] Fix NodeUser uid example type (from string to number)

- candi/cloud-providers/yandex/openapi/instance_class.yaml
Fix misleading default value about [diskType](https://deckhouse.ru/documentation/v1/modules/030-cloud-provider-yandex/cr.html#yandexinstanceclass-v1-spec-disktype) of YandexInstanceClass in documentation
Close https://github.com/deckhouse/deckhouse/issues/7344
```changes
section: candi
type: chore
summary: Fix misleading default value about diskType of YandexInstanceClass in documentation.
```
> [candi] Fix misleading default value about diskType in documentation

- ee/modules/380-metallb/templates/speaker/daemonset.yaml
To prevent frequent restarts of the speaker pods (in some cases), it was decided to switch the VPA to its original mode.
Due to high ARP and NDP packets activity on the network, speaker pods may consume more memory.
Additionally, changes in event intensity can also affect pod memory consumption.
In addition, when the intensity of events in the network changes, the memory consumption of the pod changes accordingly.
Frequent changes in network event intensity cause the VPA operating in Auto mode to periodically restart the pods.
This patch will significantly improve stability of metallb in certain prod-clusters.
The VPA will stop constantly rebooting pods. 
Resource changes will only be applied when the pods are reloaded organically
```changes
type: fix
summary: Changing …
```
> [metallb] Change updateMode to Initial

- modules/040-node-manager/images/machine-controller-manager/werf.inc.yaml
Previous version does not check all errors except NotFound error/ 
Fix panic in mcm
Panic in mcm
```changes
type: fix
summary: Fix panic when vsphere driver create disk
```
> [node-manager][mcm] Fix panic when vsphere driver create disk

- ee/be/candi/bashible/bundles/altlinux/all/003_install_mandatory_packages.sh.tpl
Add the `tzdata` package to the bootstrap script on AltLinux `10.0`.
```changes
section: candi
type: fix
summary: Add the `tzdata` package to the bootstrap script on AltLinux `10.0`.
```
> [candi] Add the tzdata package to the bootstrap script on AltLinux

- candi/cloud-providers/yandex/layouts/with-nat-instance/base-infrastructure/main.tf
- candi/cloud-providers/yandex/layouts/with-nat-instance/variables.tf
- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/variables.tf
- modules/030-cloud-provider-yandex/hooks/yandex_cluster_configuration_test.go
Allow to customize NAT instance resources, instead of hardcoded values (2 CPUs/2048MiB).
In highly loaded environments, the resources provided by default are not enough.
We don't.
```changes
section: candi
type: feature
summary: Allow to customize Yandex Cloud NAT instance resources.
```
> [candi][cloud-provider-yandex] Allow to customize NAT instance resources

- modules/040-node-manager/webhooks/validating/static_instance
- modules/040-node-manager/webhooks/validating/statis_instance
Validate StaticInstance address is unique.
Each StaticInstance leads to physical machine with unique ip address.
```changes
section: candi
type: chore
summary: Validate StaticInstance address is unique
```
> [node-manager] Validate StaticInstance address is unique

- docs/documentation/modules_list.sh
- docs/documentation/werf-git-section.inc.yaml
- docs/documentation/werf.yaml
- modules/810-documentation/images/web/werf.inc.yaml
Show documentation for the `node-local-dns` and `flant-integration` modules.
`node-local-dns` and `flant-integration` modules were moved to the BE and disappeared from the site.
We have to return the module documentation to the site.
```changes
section: docs
type: chore
summary: Show documentation for the node-local-dns and flant-integration modules.
```
> [docs] Show BE modules on the site

- modules/402-ingress-nginx/images/controller-1-6/Dockerfile
Added chmod 1777 /tmp to ingress-nginx controller-1.6 final image.
Fix /tmp access rights in the controller image to avoid errors like
```
E0214 10:39:01.651045       7 queue.go:130] "requeuing" err="open /tmp/new-nginx-cfg1568789429: permission denied" key="d8-monitoring/prometheus-longterm-b89nt"
```
```changes
section: ingress
type: fix
summary: Fix `/tmp` access rights for controller v1.6.
```
> [ingress-nginx] fix /tmp rights

- werf.yaml
Fix e2e tests
After merging #7101 envsubst binary is missing in install image. This leads to cloud-tests fail.
```changes
section: ci
type: fix
summary: fix e2e tests
```
> [ci] fix e2e tests

- candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
- candi/control-plane-kubeadm/config.yaml.tpl
- ee/modules/160-multitenancy-manager/hooks/project.go
- ee/modules/160-multitenancy-manager/hooks/project_test.go
- ee/modules/160-multitenancy-manager/templates/validating.yaml
Reject manual change for resources inside the namespace which are managed by Projects
Prevent manual modifications of resources. Manage them only via the ProjectTemplate
```yaml
apiVersion: v1
data:
a: b
fhff: gg
z: x
kind: ConfigMap
metadata:
annotations:
meta.helm.sh/release-name: test-project-1
meta.helm.sh/release-namespace: test-project-1
creationTimestamp: "2024-02-13T21:18:14Z"
labels:
app.kubernetes.io/managed-by: Helm
name: tututu
namespace: test-project-1
resourceVersion: "76800907"
uid: 46fb7f19-b5c1-41fc-842f-699c1632f9fa
```
tries to patch:
```yaml
The configmaps "tututu" is invalid: : ValidatingAdmissionPolicy 'multitenancy-manager' with binding 'multitenancy-manager-binding' denied request: This resource is managed by test-project-1 Project. Manual modification is …
```
> [multitenancy-manager] resource validation

- modules/470-chrony/monitoring/prometheus-rules/chrony.yaml
After migrate chrony to distroless, binary path moved
Correct help message.
```changes
type: fix
summary: chrony, fixed incorrect path in alert 
```
> chrony, incorrect path

- candi/openapi/cluster_configuration.yaml
Improve strict for validation pattern of proxy.
A more strict pattern is better than unexpected behavior during the installation process.
```changes
section: candi
type: fix
summary: Improve strict for validation pattern of proxy.
```
> [candi] Improve strict for validation pattern of proxy

- candi/control-plane-kubeadm/config.yaml.tpl
Fix runtime config
It doesn't work for 1.25 kubernetes version
```changes
type: fix 
summary: Fix runtime config for kube-apiserver
```
> [control-plane-manager] fix runtime config

- ee/modules/502-delivery/openapi/config-values.yaml
- ee/modules/502-delivery/openapi/doc-ru-config-values.yaml
- global-hooks/openapi/config-values.yaml
- global-hooks/openapi/doc-ru-config-values.yaml
- modules/110-istio/openapi/config-values.yaml
- modules/110-istio/openapi/doc-ru-config-values.yaml
- modules/150-user-authn/openapi/config-values.yaml
- modules/150-user-authn/openapi/doc-ru-config-values.yaml
- modules/300-prometheus/openapi/config-values.yaml
- modules/300-prometheus/openapi/doc-ru-config-values.yaml
- modules/500-cilium-hubble/openapi/config-values.yaml
- modules/500-cilium-hubble/openapi/doc-ru-config-values.yaml
- modules/500-dashboard/openapi/config-values.yaml
- modules/500-dashboard/openapi/doc-ru-config-values.yaml
- modules/500-openvpn/openapi/config-values.yaml
- modules/500-openvpn/openapi/doc-ru-config-values.yaml
- modules/500-upmeter/openapi/config-values.yaml
- modules/500-upmeter/openapi/doc-ru-config-values.yaml
- modules/810-documentation/openapi/config-values.yaml
- modules/810-documentation/openapi/doc-ru-config-values.yaml
Add HTTP to HTTPS redirect requirement for external load balancer in case of `https.mode` `OnlyInURI`
fixes #7444
```changes
section: docs
type: chore
```
> [docs] Add redirect requirement for LB in case of OnlyInURI

- modules/021-cni-cilium/templates/safe-agent-updater/daemonset.yaml
Removing deprecated annotation from safe-agent-updater.
The `scheduler.alpha.kubernetes.io/critical-pod` annotation has been non-functional since Kubernetes version 1.16. Its use may cause confusion.
We don't use deprecated annotations in manifests and don't see warnings that they are in the cluster.
```changes
type: chore
summary: Removing deprecated annotation from safe-agent-updater.
impact: The `safe-agent-updater` pods will be restarted
```
> [cilium] Remove deprecated annotation from safe-agent-updater

- docs/site/werf-docs-builder.inc.yaml
- testing/library/images_tags_generated.go
Use werf artifact for the `docs-builder-artifact` image.
```changes
type: chore
summary: Use werf artifact for the `docs-builder-artifact` image.
```
> [documentation]  Use werf artifact for the `docs-builder-artifact` image

- ee/be/modules/600-flant-integration/templates/pricing/daemonset.yaml
- ee/modules/380-metallb/templates/controller/deployment.yaml
- ee/modules/380-metallb/templates/speaker/daemonset.yaml
- ee/modules/500-operator-trivy/templates/deployment.yaml
- modules/002-deckhouse/templates/deployment.yaml
- modules/040-terraform-manager/templates/terraform-auto-converger/deployment.yaml
- modules/040-terraform-manager/templates/terraform-state-exporter/deployment.yaml
- modules/042-kube-dns/templates/deployment.yaml
- modules/101-cert-manager/templates/cert-manager/deployment.yaml
- modules/200-operator-prometheus/templates/operator.yaml
- modules/300-prometheus/templates/grafana/deployment.yaml
- modules/300-prometheus/templates/trickster/deployment.yaml
- modules/340-extended-monitoring/templates/extended-monitoring-exporter/deployment.yaml
- modules/340-monitoring-kubernetes-control-plane/templates/control-plane-proxy/daemonset.yaml
- modules/340-monitoring-kubernetes/templates/kube-state-metrics/deployment.yaml
- modules/500-dashboard/templates/dashboard/deployment-dashboard.yaml
- modules/500-openvpn/templates/openvpn/statefulset.yaml
- modules/500-upmeter/templates/upmeter/statefulset.yaml
Set `KUBE_RBAC_PROXY_LISTEN_ADDRESS` environment variable to pod IP.
We need to avoid listening on all addresses.
```changes
section: kube-rbac-proxy
type: fix
summary: kube-rbac-proxy sidecar listening on the pod IP address.
```
> [kube-rbac-proxy] listen on pod IP

- helm_lib/charts/deckhouse_lib_helm/templates/_module_init_container.tpl
Running check-kernel-version init-container as deckhouse user
During migration to distroless we missed it. Now pods with the init-container can't pass admission-policy-engine check:
```
Error: container has runAsNonRoot and image will run as root (pod: "xxxxxx(8be44c16-456e-4a1f-9042-e00d4301b2f1)", container: check-linux-kernel).
```
```changes
type: fix
summary: Running check-kernel-version init-container as deckhouse user
impact: All related Pods will be restarted — cilium-agent, node-local-dns, openvpn.
```
> [helm_lib] Running check-linux-kernel init-container as deckhouse user

- modules/470-chrony/images/chrony/main.go
- modules/470-chrony/template_tests/module_test.go
- modules/470-chrony/templates/configmap.yaml
- modules/470-chrony/templates/daemonset.yaml
Set `bindaddress` to host IP.
We need to avoid listening on all addresses.
```changes
type: fix
summary: Avoid listening on all addresses and listen on the host IP address.
```
> [chrony] listen on host IP only

- dhctl/pkg/system/ssh/cmd/ssh.go
Disable `known_hosts` file checking for SSH client.
When a master node is recreated, the master node's SSH fingerprint changes and the SSH client returns an error.
```changes
section: dhctl
type: fix
summary: Ignore a master node SSH fingerprint.
```
> [dhctl] disable `known_hosts` file checking for SSH client

- ee/modules/380-metallb/monitoring/grafana-dashboards/kubernetes-cluster/metallb-pool.json
- ee/modules/380-metallb/monitoring/grafana-dashboards/kubernetes-cluster/metallb.json
- ee/modules/380-metallb/monitoring/prometheus-rules/metallb.yaml
- ee/modules/380-metallb/templates/monitoring.yaml
Add MetalLB and MetalLB/pools dashboards to Grafana: 
* The table to discover from which node the virtual ip is being announced. 
* Pools usage.
* L2 & BGP -specific metrics.
Also, added an alert D8MetalLBConfigStale which is firing if MetalLB running on a stale configuration, because the latest config failed to load.
The screenshots [are bellow](https://github.com/deckhouse/deckhouse/pull/7459#issuecomment-1951945806).
We had no ability to discover which speaker announces the ip. At the same time we developed the dashboard with other metrics. 
The MetalLB dashboard exists in Grafana.
```changes
type: feature
summary: MetalLB dashboard for Grafana
```
> [metallb] Add MetalLB grafana dashboard

- ee/modules/450-network-gateway/images/dnsmasq/werf.inc.yaml
- shell_lib/hook.sh
- shell_lib/tools.sh
Fix an error with password generation in shell hooks.
Previously shell lib uses pwgen to generate passwords. Now we use python to do it.
```changes
section: core
type: fix
summary: Fix an error with password generation in shell hooks
```
> [shell_lib] Fix an error with password generation in shell hooks

- modules/050-network-policy-engine/templates/daemonset.yaml
Add /run/xtables.lock mount.
After migration to distroless, we lost `/run` directory in container filesystem.
```
F0216 14:42:03.836030       1 network_policy_controller.go:430] failed to run iptables command to create KUBE-ROUTER-OUTPUT chain due to running [/sbin/iptables -t filter -S KUBE-ROUTER-OUTPUT 1 --wait]: exit status 4: Fatal: can't open lock file /run/xtables.lock: No such file or directory
```
This affects clients.
```changes
section: network-policy-engine
type: fix
summary: Add /run/xtables.lock mount.
```
> [network-policy-engine] Fix /run mount

- modules/340-monitoring-kubernetes/hooks/auto_k8s_version_test.go
Autotest has a high probability of false positives when running in the test pipeline because the cluster configuration is not set in time.
Eliminates the need to repeatedly restart the testing pipeline.
Significantly reduces the chances of false positive tests.
In testing, 3 out of 3 launches were successful.
```changes
type: fix
summary: Reduces the chances of false positive tests.
```
> Fix false test triggering when cluster configuration secret is unavailable

- helm_lib/Chart.lock
- helm_lib/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/templates/_csi_controller.tpl
Set `http-endpoint` address for `livenessprobe` to host IP address.
We need to avoid listening on all addresses.
```changes
type: fix
summary: Avoid listening on all addresses and listen on the host IP address.
```
> [ceph-csi] set livenessprobe address to host IP

- docs/documentation/werf-git-section.inc.yaml
Don't render the ProjectType resource in the documentation as it has been deprecated.
```changes
type: chore
summary: Don't render the ProjectType resource in the documentation as it has been deprecated.
```
> [docs][multitenancy-manager] Don't render the ProjectType resource in the documentation.

- docs/documentation/_data/i18n.yml
- docs/documentation/_plugins/openapi.rb
- ee/modules/160-multitenancy-manager/crds/projecttypes.yaml
- Mark the `ProjectType` resource fields as deprecated.
- Fix the OpenAPI generator to show the deprecation status of a resource if `spec.versions[].deprecated` resource field is set to `true`.
```changes
section: multitenancy-maanger
type: chore
summary: Mark the `ProjectType` resource as deprecated.
```
> [docs][multitenancy-manager] Mark the ProjectType resource fields as deprecated

- modules/021-cni-cilium/images/safe-agent-updater/README.md
Add a code description for the safe-agent-updater
The reason for creating the application `safe-agent-updater` and the logic behind its operation were obscure.
```changes
type: chore
summary: Add a code description for the safe-agent-updater
```
> [cilium] Add a code description for the safe-agent-updater

- modules/302-vertical-pod-autoscaler/images/vertical-pod-autoscaler/patches/openkruise-daemonset-apiversion.patch
- modules/402-ingress-nginx/crds/kruise/crd_daemonsets.yaml
- modules/402-ingress-nginx/images/kruise/patches/README.md
- modules/402-ingress-nginx/images/kruise/patches/add-label-selector-to-scale.patch
- modules/402-ingress-nginx/templates/controller/controller.yaml
- modules/402-ingress-nginx/templates/failover/daemonset.yaml
PR includes the following changes:
* `Vertical pod autoscaler` is patched so that it could tell the difference between original `apps/v1 daemonsets` and `openkruise apps.kruise.io/v1alpha1 advanved daemonsets`. With the proposed changes VPA is able to discover necessary pods of an advanced daemonetset via the daemonset's `scale subresource` (`labelSelectorPath` option);
* OpenKruise controller is patched to set a proper value to `.status.labelSelecor` field of an advanved daemonset. This values is used as `labelSelectorPath` option of a `scale subresource` and `labelSelectorPath` value is used by VPA to discover relevant pods of a controller;
* OpenKruise AdvancedDaemonetSet CR is updated with `.status.labelSelector` and `.subresources.scale.labelSelectorPath` fields so that advanced …
> [ingress-nginx] add .status.labelSelector to ADS and patch VPA

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/generic/cri-version.tpl
Fixes alert UnsupportedContainerRuntimeVersion to support the newest versions of containerd - 1.7.*.
```changes
type: fix
summary: Fix `UnsupportedContainerRuntimeVersion` alert to support the newest containerd versions (`1.7.*`).
```
> [monitoring] Fix UnsupportedContainerRuntimeVersion alert (add containerd 1.7.*)

- werf.yaml
Add ca certificates to standard path /etc/ssl instead of /etc/pki/ca-cert.
Some binaries search ca certificates under /etc/ssl.
```changes
type: fix
summary: Add CA certificates to the standard `/etc/ssl/` path.
```
> [deckhouse-controller] add ca-certificates

- modules/040-control-plane-manager/requirements/check.go
Hotfixed race reading between  deckhouse pod status and "minUsedControlPlaneKubernetesVersion" variable.
```changes
type: fix
summary: Fix race reading between the deckhouse pod status and the `minUsedControlPlaneKubernetesVersion` variable.
impact: Prevents the Deckhouse version update error from being skipped.
```
> [control-plane-manager] Hotfixed race reading between  deckhouse pod status and "minUsedControlPlaneKubernetesVersion" variable.

- modules/002-deckhouse/templates/webhook-handler/deployment.yaml
- modules/300-prometheus/images/prometheus/sample_limit_annotation.patch
- modules/300-prometheus/images/prometheus/werf.inc.yaml
- modules/300-prometheus/webhooks/validating/customprometheusrules
1. Fix validating webhook build for promtool work.
2. Fix prometheus build to return sample limit patch.
```changes
type: fix
summary: Fix validating webhook build for promtool work.
---
type: Fix Prometheus build to return sample limit patch.
summary: impact_level: default
```
> [prometheus] fix build errors

- go_lib/deckhouse-config/status.go
Provides an additional check if the module manager has the required module before calculating the module's status.
A panic may be observed at a d8s module status update if the module manager doesn't have a basic module with such a name.
It fixes a panic condition.
If a module isn't presented in the module manager moduleset, its status should be set to Error.
```changes
type: fix
summary: Fix panic at a module status update.
```
> [external-module-manager] fix panic at a module status update

- dhctl/pkg/kubernetes/actions/converge/check.go
- dhctl/pkg/terraform/pipeline.go
- dhctl/pkg/terraform/pipeline_test.go
Add terraform plan to CheckResult
To give the commander user more information about the changes being applied
> [dhctl] feat(dhctl-for-commander): Add raw terraform plan to check result

- modules/040-node-manager/webhooks/validating/node_group
Added NodeGroup validation to prevent adding more than one taint with the same key and effect.
<details><summary>Details</summary>
```shell
root@dev2-master-0:~# kubectl edit ng redos 
error: nodegroups.deckhouse.io "redos" could not be patched: admission webhook "nodegroup-policy.deckhouse.io" denied the request: .spec.nodeTemplate.taints must contains only one taint with the same key and effect
You can run `kubectl replace -f /tmp/kubectl-edit-3126790586.yaml` to try this update again.
```
</details>
```changes
type: fix
summary: Added NodeGroup validation to prevent adding more than one taint with the same key and effect.
```
> [node-manager] Don't allow more than one taint with the same key and effect

- modules/040-node-manager/images/caps-controller-manager/src/internal/ssh/ssh.go
Add the `PasswordAuthentication=no` option to the OpenSSH client if public key authentication is used.
If we specify an incorrect private key in `SSHCredentials`, the server may prompt for a password and the SSH session will freeze.
```changes
type: fix
summary: Add the `PasswordAuthentication=no` option to the OpenSSH client if public key authentication is used.
```
> [node-manager](caps) Fix public key authentication

- modules/040-node-manager/hooks/instance_controller.go
Do not return an error if NodeGroup has been deleted.
We have a race in instance controller if we delete `NodeGroup`.
```changes
type: fix
summary: Fix a race in instance controller if NodeGroup has been deleted.
```
> [node-manager] do not return an error in the instance controller if `NodeGroup` has been deleted

- modules/040-node-manager/images/caps-controller-manager/src/internal/client/cleanup.go
Remove `/var/lib/bashible` and reboot the host if the cleanup script does not exist.
If a `StaticMachine` is deleted during bootstrap and the cleanup script has not yet been created, then the `StaticInstance` may go into the `Pending` status.
```changes
type: fix
summary: Fix the cleanup phase in the 'caps-controller-manager' if the cleanup script does not exist.
```
> [node-manager](caps) fix the cleanup phase

- modules/040-node-manager/webhooks/validating/static_instance
Check for `SSHCredentials` in the `StaticInstance` webhook.
We need to check if `SSHCredentials` exists before reconciling it in the `StaticInstance` controller.
```changes
type: fix
summary: Check for `SSHCredentials` in the `StaticInstance` webhook.
```
> [node-manager](caps) Check for `SSHCredentials` in the `StaticInstance` webhook

- modules/040-node-manager/hooks/handle_draining.go
- modules/040-node-manager/hooks/handle_draining_test.go
- modules/040-node-manager/hooks/update_approval.go
- modules/040-node-manager/monitoring/prometheus-rules/node-update.yaml
added NodeStuckInDraining alert 
Closes https://github.com/deckhouse/deckhouse/issues/5173
```changes
type: fix
summary: added alert on impossible node drain
```
> [node-manager] added alert on impossible node drain

- dhctl/pkg/config/meta.go
- dhctl/pkg/config/meta_test.go
```
panic: runtime error: index out of range [2] with length 1
goroutine 303 [running]:
github.com/deckhouse/deckhouse/dhctl/pkg/config.(*MetaConfig).FindTerraNodeGroup(0xc000367180, {0xc000f555c6, 0x6})
/go/pkg/mod/github.com/deckhouse/deckhouse/dhctl@v0.0.0-20240229021302-d736890b4b64/pkg/config/meta.go:201 +0x1b4
```
> [dhctl] fix FindTerraNodeGroup

- dhctl/pkg/kubernetes/actions/deckhouse/log.go
- dhctl/pkg/kubernetes/client/client.go
- dhctl/pkg/log/logger.go
Reduce log level for deckhouse converging error
Often we have one-shot errors which they do not govern for bootstrap process and it confuses users.
```changes
section: dhctl
type: chore
summary: Reduce log level for deckhouse converging error
```
> [dhctl] Reduce log level for deckhouse converging error

- candi/cloud-providers/azure/docs/ENVIRONMENT.md
- candi/cloud-providers/azure/docs/ENVIRONMENT_RU.md
- candi/cloud-providers/azure/openapi/cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/doc-ru-cluster_configuration.yaml
- docs/site/_includes/getting_started/azure/STEP_ENV.md
- docs/site/_includes/getting_started/azure/STEP_ENV_RU.md
Adding information about clientSecret issued for 1 year to Azure layout.
```changes
section: docs
summary: Add info about using client secrets in Azure.
type: fix
```
> [docs] added info for clientSecret Azure layout

- modules/402-ingress-nginx/docs/testing/README.md
- modules/402-ingress-nginx/images/controller-1-9/Dockerfile
- werf.yaml
Add needed libraries to the final image.
When we refactored the build to use distroless images we lost some necessary libraries.
There is a bug in the Ingress controller.
```changes
type: fix
summary: Add libraries to the final image.
impact: ingress nginx controller will restart.
```
> [ingress-nginx] add needed libraries to final image

- modules/460-log-shipper/images/vector/werf.inc.yaml
- modules/500-openvpn/images/ovpn-admin/werf.inc.yaml
- werf.yaml
Added missing ca-certs to images based on alt:p10 to prevent errors with HTTPS connections.
Bug fix.
Before this PR:
LogShipper:
```
2024-03-01T09:46:09.439636Z  WARN sink{component_kind="sink" component_id=destination/cluster/dop-flant-com component_type=loki component_name=destination/cluster/dop-flant-com}:request{request_id=1}:http: vector::internal_events::http_client: HTTP error. error=error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1919:: unable to get local issuer certificate error_type="request_failed" stage="processing" internal_log_rate_limit=true
2024-03-01T09:46:09.439728Z  WARN sink{component_kind="sink" component_id=destination/cluster/dop-flant-com component_type=loki …
```
> [core] add ca-certificates to alt-based images

- modules/015-admission-policy-engine/charts/constraint-templates/templates/security/allowed-cluster-roles.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/allowed-cluster-roles/constraint-allowed-admin.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/allowed-cluster-roles/samples/allowed.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/allowed-cluster-roles/samples/allowed2.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/allowed-cluster-roles/samples/disallowed.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/allowed-cluster-roles/suite.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/common/test_samples/ns.yaml
- modules/015-admission-policy-engine/crds/doc-ru-security-policy.yaml
- modules/015-admission-policy-engine/crds/security-policy.yaml
- modules/015-admission-policy-engine/hooks/handle_security_policies.go
- modules/015-admission-policy-engine/hooks/handle_security_policies_test.go
- modules/015-admission-policy-engine/hooks/internal/apis/v1alpha1.go
- modules/015-admission-policy-engine/template_tests/security_policies_test.go
- modules/015-admission-policy-engine/templates/policies/security-policy/constraint.yaml
Added the ability to specify restrictions on applying cluster roles to users.
In CRD "security-policy" added new parameter: "allowedClusterRoles". A list of cluster roles that are allowed to be bound to users.
Attempting to bind unresolved cluster roles will result in an error:
```
kubectl apply -f disallowed-rolebinding.yaml
Error from server (Forbidden): error when creating "disallowed-rolebinding.yaml": admission webhook "admission-policy-engine.deckhouse.io" denied the request: [mypolicy] ClusterRole secret-reader is not in list of allowed roles ["admin"]
```
close issue #7375 
Attempting to bind unresolved cluster roles will result in an error.
```changes
type: fix
summary: Added the ability to specify restrictions on applying cluster roles to users. …
```
> [admission-policy-engine] security policy: AllowedClusterRoles

- modules/030-cloud-provider-yandex/monitoring/prometheus-rules/deprecated_availability_zone.yaml
Move step converge from cluster to local machine
Our master node can also have connection to internet through NAT-instance and when converge delete NAT instance we lost connection to `api.cloud.yandex.net`
Not necessary.
```changes
type: chore
summary: Improve alert about migration NAT instance.
```
> [cloud-provider-yandex] Improve alert about migration NAT instance

- modules/015-admission-policy-engine/templates/podmonitor.yaml
- modules/030-cloud-provider-aws/templates/cloud-data-discoverer/pod-monitor.yaml
- modules/030-cloud-provider-azure/templates/cloud-data-discoverer/pod-monitor.yaml
- modules/030-cloud-provider-gcp/templates/cloud-data-discoverer/pod-monitor.yaml
- modules/030-cloud-provider-yandex/templates/cloud-metrics-exporter/pod-monitor.yaml
- modules/040-node-manager/templates/early-oom/pod-monitor.yaml
- modules/200-operator-prometheus/templates/podmonitor.yaml
- modules/402-ingress-nginx/template_tests/controller_test.go
- modules/402-ingress-nginx/templates/controller/hpa.yaml
- modules/402-ingress-nginx/templates/kruise/podmonitor.yaml
Provides an additional check to prevent rendering of components that require CRDs from operator-prometheus-crd module, if this module is disabled.
Closes https://github.com/deckhouse/deckhouse/issues/7433
Some modules use CRDs from operator-prometheus-crd module in their components(PodMonitor, PrometheusRules). But if operator-prometheus-crd is disabled, the modules cannot be deployed because they are trying to deploy unavailable resources. Adding an additional condition will fix the problem, modules will be deployed without unavailable components. 
It allows to use the modules whose components use CRDs from operator-prometheus-crd module without it.
Using some modules (for example ingress-nginx) without the operator-prometheus-crd module. The modules will be deployed without PodMonitors …
> [global] preventing rendering of unavailable components

- candi/cloud-providers/aws/openapi/cluster_configuration.yaml
Fix additionalRolePolicies regex.
Regex was wrong and cannot accept valid roles like `kafka-cluster:*Topic*`.
```changes
section: candi
type: fix
summary: Fix additionalRolePolicies regex.
```
> [cloud-provider-aws] fix additionalRolePolicies regex

- modules/021-cni-cilium/monitoring/prometheus-rules/agent.yaml
Removing CiliumAgentMapOperationFailures alert
There are many spamming alerts in different clusters with maps which are not described in official docs. We are not reaping any real benefits from using this alert.
```changes
type: chore
summary: remove CiliumAgentMapOperationFailures alert
```
> [cilium] Remove CiliumAgentMapOperationFailures alert.

- modules/050-network-policy-engine/enabled
Disable network-policy-engine module if cni-cilium module is enabled.
When the CNI-Cilium module is enabled, its own Network Policies are in place. If the Network Policy Engine module is also activated concurrently, conflicts and ambiguity can occur. To prevent this, a verification check will be added to the module activation script to ensure if the CNI-Cilium module is already enabled.
```changes
section: network-policy-engine
type: chore
summary: Deny module setup if the cni-cilium module is enabled
```
> [network-policy-engine] Deny module setup if the cni-cilium module is enabled

- ee/modules/500-operator-trivy/images/operator/Dockerfile
- ee/modules/650-runtime-audit-engine/images/falcosidekick/Dockerfile
- modules/000-common/images/csi-external-attacher/werf.inc.yaml
- modules/000-common/images/csi-external-provisioner/werf.inc.yaml
- modules/000-common/images/csi-external-resizer/werf.inc.yaml
- modules/000-common/images/csi-external-snapshotter/werf.inc.yaml
- modules/000-common/images/csi-livenessprobe/werf.inc.yaml
- modules/000-common/images/csi-node-driver-registrar/werf.inc.yaml
- modules/000-common/images/kube-rbac-proxy/werf.inc.yaml
- modules/031-local-path-provisioner/images/local-path-provisioner/werf.inc.yaml
- modules/042-kube-dns/images/coredns/patches/README.md
- modules/150-user-authn/images/dex-authenticator/Dockerfile
- modules/150-user-authn/images/dex/Dockerfile
- modules/150-user-authn/images/kubeconfig-generator/Dockerfile
- modules/200-operator-prometheus/images/prometheus-operator/werf.inc.yaml
- modules/300-prometheus/images/alertmanager/Dockerfile
- modules/300-prometheus/images/trickster/Dockerfile
- modules/301-prometheus-metrics-adapter/images/k8s-prometheus-adapter/Dockerfile
- modules/340-monitoring-kubernetes/images/kube-state-metrics/Dockerfile
- modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/Dockerfile
- modules/402-ingress-nginx/images/kruise-state-metrics/patches/README.md
- modules/402-ingress-nginx/images/kruise/patches/README.md
- modules/402-ingress-nginx/images/nginx-exporter/werf.inc.yaml
- modules/462-loki/images/loki/Dockerfile
Change `go get -u` to `go get` + `go mod tidy` for build immutability.
When we use `go get -u`, we are updating dependencies to the latest version, not the preferred version.
This causes problems with resolv of go packages.
```changes
section: core
type: fix
summary: change go get -u to go get for build immutability
```
> [core] change go get -u to go get for build immutability

- candi/openapi/node_group.yaml
Fixed kubelet resource reservation for Static nodes
kubelet resource reservation doesn't work with nodeType Static
```shell
kind: NodeGroup
metadata:
name: test-ng
spec:
disruptions:
approvalMode: Automatic
kubelet:
containerLogMaxFiles: 4
containerLogMaxSize: 50Mi
maxPods: 150
resourceReservation:
mode: "Static"
static:
cpu: 500m
memory: 1G
nodeType: Static
operatingSystem:
manageKernel: false
The NodeGroup "test-ng" is invalid: <nil>: Invalid value: "": "spec.kubelet.resourceReservation.static" must validate one and only one schema (oneOf). Found 2 valid alternatives
```
```shell
root@dev2-master-0:~# kubectl get crd nodegroups.deckhouse.io -o json | jq '.spec.versions[2].schema.openAPIV3Schema.properties.spec.properties.kubelet.properties.resourceReservation. …
```
> [node-manager] kubelet resource reservation fix

- dhctl/pkg/operations/mirror/versions.go
Implemented a check that prevents mirroring of versions newer than version of `alpha` release channel
This fixes incorrect versions selection resulting in mirroring of unreleased artifacts.
This is a bugfix.
```changes
section: dhctl
type: fix
summary: "mirror will avoid mirroring versions that were not yet released."
```
> [dhctl] mirror: avoid mirroring versions that were not yet released

- modules/301-prometheus-metrics-adapter/images/k8s-prometheus-adapter/Dockerfile
- modules/340-monitoring-kubernetes/images/kube-state-metrics/Dockerfile
Change go get for modules.
It fixes the bug.
```changes
section: core
type: fix
summary: Change go get.
```
> [core] change go get

- dhctl/cmd/dhctl/commands/mirror.go
Added debug output for `dhctl mirror` when `DHCTL_DEBUG` is set.
We cannot debug registry problems without debug output. 
```changes
section: core
type: feature
summary: Added debug output for `dhctl mirror` when `DHCTL_DEBUG` is set.
```
> [dhctl] added mirror debug

- README.md
- testing/matrix/linter/rules/modules/images.go
Distroless image linter
We want to verify that Deckhouse images are Distroless images.
Matrix tests is PASS
```changes
section: matrix-tests
type: feature
summary: Distroless image linter
```
> [matrix-tests] distroless image linter

- modules/021-cni-cilium/templates/safe-agent-updater/daemonset.yaml
Making fixes:
1) Launching pods of `safe_agent_updater` in the `hostNetwork`
2) When connecting to the k8s api-server, use the `kubernetes-api-proxy`.
If there are pods of `cilium-agent` in the cluster that aren't functioning correctly, we may encounter the following issue. 
The `safe_agent_updater` application may not be able to connect to the Kubernetes API server to determine if the pods of `cilium-agent` need to be restarted. 
By default, connections to the Kubernetes API server are made using the svc with type `Cluster IP` which is processed entirely by the `cilium-agents` pods. 
To prevent this situation, we can launch the `safe_agent_updater` pods with `hostNetwork` and configure it to communicate with Kubernetes API server through the `kubernetes-api-proxy`.
Now, this issue occurs …
> [cilium] Fixup safe_agent_updater

- modules/011-flow-schema/template_tests/module_test.go
- modules/011-flow-schema/templates/flowschema.yaml
- modules/011-flow-schema/templates/prioritylevelconfiguration.yaml
apiVersion for FlowSchema and PriorityLevelConfiguration changed to the minimum available
In rare cases, when rolling back a k8s version, a situation arises that makes it impossible to apply the new flow-schema release
```shell
root@dev-master-0:~# kubectl version -o json | jq '.serverVersion.gitVersion'
"v1.26.14"
root@dev-master-0:~# kubectl -n d8-system get secret sh.helm.release.v1.flow-schema.v3 -o json | jq -r '.data.release' | base64 -d | base64 -d | gzip -d | jq -r '.manifest' | grep "^apiVersion: f" -A1
apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: FlowSchema
--
apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: PriorityLevelConfiguration
root@dev-master-0:~# kubectl version -o json | jq '.serverVersion.gitVersion'
"v1.27.11"
root@dev-master-0:~# kubectl -n d8-system …
```
> [flow-schema] apiVersion for FlowSchema and PriorityLevelConfiguration changed to the minimum available

- modules/500-dashboard/templates/namespace.yaml
Closes https://github.com/deckhouse/deckhouse/issues/7730.
Fixes CM kube-rbac-proxy-ca.crt is missing in namespace d8-dashboard.
```changes
type: fix
summary: Add cm kube-rbac-proxy-ca.crt in namespace d8-dashboard.
```
> [dashboard] Fix 7730 issue

- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
This PR disables converge-lock when running bootstrap operation in commander-mode.
It is totally safe to remove this lock in commander mode because:
* terraform-manager (auto-converge) is disabled in commander;
* converge runs outside of target cluster and commander ensures no parallel converges are running;
* it is supposed that user never runs dhctl-converge from cli manually, user always uses commander ui to change configuration.
So we don't need this lock in commander mode at all.
If bootstrap has been terminated at InstallAdditionalMastersAndStaticNodes for example, then converge-lock lease remains to exist in the target cluster. On the next bootstrap retry, which is automatic in commander, bootstrap will hang in deadlock.
> fix(dhctl-for-commander): disable local-bootstraper converge-lock in commander-mode

- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
- modules/040-node-manager/images/caps-controller-manager/src/api/deckhouse.io/v1alpha1/staticinstance_webhook.go
- modules/040-node-manager/images/caps-controller-manager/src/go.mod
- modules/040-node-manager/images/caps-controller-manager/src/go.sum
- modules/040-node-manager/images/caps-controller-manager/src/internal/scope/machine_scope.go
- modules/040-node-manager/images/caps-controller-manager/src/internal/scope/machine_scope_test.go
Add the `"node.deckhouse.io/allow-bootstrap": "false"` label requirement to the `StaticInstance` label selector. Add a detailed description of `StaticInstance` deletion to the documentation.
Close #7370.
```changes
type: fix
summary: Add the ability to disable StaticInstance bootstrapping by adding the '"node.deckhouse.io/allow-bootstrap": "false"' label.
```
> [node-manager](caps) Add the ability to disable StaticInstance bootstrapping

- modules/045-snapshot-controller/docs/README.md
- modules/045-snapshot-controller/docs/README_RU.md
- modules/045-snapshot-controller/docs/USAGE.md
- modules/045-snapshot-controller/docs/USAGE_RU.md
- modules/045-snapshot-controller/enabled
- modules/045-snapshot-controller/template_tests/module_test.go
This PR fixes the documentation and scripts in the snapshot-controller module by adding support for `sds-replicated-volume` and removing support for linstor.
Now snapshot controller have no support for `sds-replicated-volume` module.
Snapshot controller module supports for sds-replicated-volume module
```changes
type: chore
summary: Fix the documentation. Fix the enabled script to add support for `sds-replicated-volume` module instead of the deprecated `linstor` module.
```
> Added sds-replicated-volume support in volume snapshot controller, and removed linstor support

- dhctl/pkg/operations/check/checker.go
Abandoned nodes will be destroyed in the converge, so give DestructiveOutOfSync status in such case.
This fixes current behaviour where abandoned nodes treated as a regular out-of-sync.
> [dhctl] fix(dhctl-for-commander): abandoned node should be treated as destructive check status

- .github/ci_templates/e2e_tests.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- candi/terraform_versions.yml
- dhctl/pkg/terraform/mocks/checkplan/destructively_changed.json
- dhctl/pkg/terraform/mocks/checkplan/empty.json
- dhctl/pkg/terraform/mocks/pipeline/base_infra_ok_plan.json
- dhctl/pkg/terraform/mocks/pipeline/empty_state.json
- dhctl/pkg/terraform/mocks/pipeline/master_node_destructively_changed_plan.json
- dhctl/pkg/terraform/mocks/pipeline/not_empty_state.json
- modules/040-terraform-manager/templates/terraform-auto-converger/deployment.yaml
- modules/040-terraform-manager/templates/terraform-state-exporter/deployment.yaml
- testing/cloud_layouts/script.sh
- testing/cloud_layouts/script_eks.sh
- testing/cloud_layouts/wait-master-ssh-and-update-comment.sh
Change terraform version from 0.13.8 to 0.14.8
This is required for the virtualization module so that virtual environments can be deployed using terraform-provider-kubernetes. This module can work with custom resources (vm, vmd, vmip, etc.) only with terraform starting from 0.14.8 version.
All cloud environments must work as expected and cluster deployments across clouds must also work as expected.
```changes
section: candi 
type: chore
summary: change terraform version to 0.14.8
impact: all cloud envirinment(clusters in AWS,GCP,Azure,Yandex-Cloud,OpenStack,VSphere)
```
> [candi] change terraform version to 0.14.8

- ee/modules/500-operator-trivy/images/trivy/Dockerfile
- ee/modules/500-operator-trivy/templates/configmap.yaml
Contains an update for trivy. This update adds scanning support for new os.
It allows trivy to scan new os.
Trivy can scan more os.
```changes
type: feature
summary: Adding new os to trivy
```
> [operator-trivy] update trivy tag

- dhctl/pkg/kubernetes/actions/converge/check.go
- dhctl/pkg/terraform/pipeline.go
- dhctl/pkg/terraform/runner.go
Added detalization about abandoned node which will be deleted during next converge.
Currently check result destructive detalization lacks info about abandoned nodes.
> [dhctl] fix(dhctl-for-commander): add destructive detalization  for abandoned node and terraform plans into check result

- modules/030-cloud-provider-aws/images/ebs-csi-plugin/werf.inc.yaml
Update `aws-ebs-csi-driver` version to `v1.28.0`
Used driver too old (released at September 2021), new driver have many improvements and bugfixes
```changes
type: fix
summary: Update `aws-ebs-csi-driver` version to `v1.28.0`.
```
> [cloud-provider-aws] Update ebs-csi-plugin to v1.28.0

- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-abort.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/server/rpc/dhctl/check.go
- dhctl/pkg/system/ssh/client.go
- dhctl/pkg/system/ssh/default.go
- dhctl/pkg/system/ssh/frontend/agent.go
- dhctl/pkg/system/ssh/session/session.go
- dhctl/pkg/terminal/ask-password.go
ClusterBootstrapper: eliminate usage of app.SSH* and add SSHClient to Params.
Add support for passphrase in Params.
Support of multiple ssh keys and passphrases in Commander.
> [dhctl] feat(dhctl-for-commander): support multiple ssh keys and passphrase

- tools/kind-d8.sh
Fixed the error of getting a password after installing Deckhouse in Kind.
Fixes a problem with installing Deckhouse in Kind by GS.
It was:
```
Provide following credentials to access Grafana at http://grafana.127.0.0.1.sslip.io/ :
Username: admin
Password: null
The information above is saved to /Users/zhbert/.kind-d8/info.txt file.
```
Become:
```
Provide following credentials to access Grafana at http://grafana.127.0.0.1.sslip.io/ :
Username: admin
Password: VhZYVlVRmhCS1yljJ9yC
The information above is saved to /Users/zhbert/.kind-d8/info.txt file.
```
```changes
section: docs
type: chore
summary: Update the Deckhouse installation script for Kind.
```
> [docs][getting-started] Fix script for kind

- candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
- modules/040-node-manager/hooks/internal/v1/nodegroup.go
- modules/040-node-manager/hooks/migration/migrate_system_reserve.go
- Fixed migration. NodeGroup's that have the `.spec.resourceReservation.mode` parameter set will be ignored.
- Fixed an issue resulting in the kubelet being unable to start if only one of the `cpu`, `memory` or `ephemeral-storage` parameters is specified in `NodeGroup.spec.resourceReservation.static`.
* Verified that migration ignores nodegroups with `.spec.resourceReservation.mode`.
* Verified that `.spec.resourceReservation.static` can be set for all `cpu`, `memory` and `ephemeral-storage` or only some.
part of NodeGroup spec 
```
kubelet:
resourceReservation:
mode: Auto
```
result
```
d8 logs
"040-node-manager/hooks/migration/migrate_system_reserve.go NodeGroupName: worker, KubeletResourceReservationMode: Static, skipMigration: true"
```
part of NodeGroup spec 
```
kubelet: …
```
> [node-manager] kubelet resource reservation fixes

- modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
- modules/402-ingress-nginx/crds/ingress-nginx.yaml
- modules/402-ingress-nginx/hooks/update_ingress_address.go
- modules/402-ingress-nginx/hooks/update_ingress_address_test.go
- modules/402-ingress-nginx/templates/controller/service.yaml
Provides an additional fields for ingress-nginx-controller status. These fields represent assigned ip and hostname of the external loadBalancer.
Closes #7718
The ip and hostname are displayed when getting ingress-nginx-controller with LoadBalancer inlet. 
```changes
type: feature
summary: add ip and hostname to ingress-nginx-controller status
```
> [ingress-nginx] add ip and hostname to ingress-nginx-controller status

- release.yaml
Getting rid of istioMinimalVersion requirement in release.yaml
Users can't upgrade their deckhouses:
```
% k get deckhousereleases.deckhouse.io                
NAME      PHASE      TRANSITIONTIME   MESSAGE
v1.57.5   Deployed   3h42m            
v1.58.4   Pending    10m              "istioMinimalVersion" requirement is not registered
```
```changes
section: istio
type: fix
summary: Got rid of istioMinimalVersion requirement in release.yaml to fix upgrading issue.
```
> [istio] Getting rid of istioMinimalVersion requirement in release.yaml

- modules/402-ingress-nginx/crds/ingress-nginx.yaml
Provides https port validation fix.
Closes #7657
You can use httpPort field without httpsPort field. You can remove httpsPort field for hostPort. 
```changes
type: fix
summary: Fix HTTPS port validation for HostPort inlet.
```
> [ingress-nginx] fix-https-port-validation

- modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
Add information of instance and pod to labels of the NginxIngressDaemonSetReplicasUnavailable alert.
This is for so that the number alerts does not equal the number of  kruise-controller replicas, but only 1, as for example for upmeter.
Reducing the number of alerts in monitoring system.
```changes
summary: Add information of instance and pod to labels of the NginxIngressDaemonSetReplicasUnavailable alert.
type: fix 
```
> [monitoring] hide labels instance/pod alerts

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Move passwords to env for dhctl mirror examples.
The new variant uses passwords more securely and does not shine them in ps on the system where they are run.
Optional.
```changes
section: dhctl
type: fix
summary: Moved passwords to env for dhctl mirror examples.
```
> [docs] moved passwords to env for dhctl mirror examples

- modules/000-common/images/shell-operator/werf.inc.yaml
- modules/002-deckhouse/docs/FAQ.md
Added repeated queries to get crd and apply conversation strategies.
The processing of conversation strategies occurs at the start of deckhouse and when a particular module is enabled.
In this case, processing may be started before crd is installed. This situation leads to an error.
The problem described above occurs in the 1.58 update and users may encounter it.
A good example to check is the multitenancy module.
It is necessary to turn off the module. Then remove the crd of this module such as (projects.deckhouse.io, projecttemplates.deckhouse.io) and enable the module again. The first attempt to apply conversation strategies will fail, but after a few attempts it will succeed.
```changes
section: shell-operator
type: fix
summary: Repeat queries to get CRD and apply conversation …
```
> Fix taking a crd that is not yet installed

- ee/candi/cloud-providers/vcd/openapi/cluster_configuration.yaml
- ee/modules/030-cloud-provider-vcd/capi/cluster.yaml
- ee/modules/030-cloud-provider-vcd/hooks/vcd_cluster_configuration_test.go
- ee/modules/030-cloud-provider-vcd/template_tests/module_test.go
- ee/modules/030-cloud-provider-vcd/templates/registration.yaml
- modules/040-node-manager/hooks/deployment_required.go
- modules/040-node-manager/hooks/deployment_required_test.go
- modules/040-node-manager/template_tests/module_test.go
- modules/040-node-manager/templates/node-group/_capi_bootstrap_secret.tpl
Cluster API provider VCD creates virtual application (if not found) equal VCDCluster resource name. Thus, we should validate virtual application name in OpenAPI spec.
Also, in this PR we disable MachineControllerManager for cloud providers which support ClusterAPI only (today it is VCD only).
Validate unsupported virtual apllication names.
Disable MCM where it is unneeded.
VCD provided in this relese, we need add restriction in same release.
MCM disabled when vcd cluster-api deployed
VCD cluster bootstrapped, cloud nodes work fine
openstack with caps and mcm working in parallel
```changes
type: fix 
summary: Add validation for virtual application name
---
type: fix
summary: Disable MCM for unsupported cloud providers …
```
> [cloud-provider-vcd] Add validation for virtual application name

- testing/cloud_layouts/wait-master-ssh-and-update-comment.sh
wait-master-ssh-and-update-comment.sh script contains curl execution with `-v` flag. We removed it.
Verbosity logs is unneeded
```changes
section: ci
type: chore
summary: Decrease log level in curl execution.
```
> [ci] Decrease log level in curl execution

- .github/workflows/codeql.yml
Add rules for scanning code by CodeQL.
```changes
section: ci
type: chore
summary: Add rules for scanning code by CodeQL.
```
> [ci] Create rules for CodeQL

- modules/002-deckhouse/hooks/check_deckhouse_release_test.go
- modules/002-deckhouse/hooks/update_deckhouse_image.go
- modules/002-deckhouse/hooks/update_deckhouse_image_test.go
The mechanism for checking if the pods are ready has been replaced. Now used the pod readiness probe via http.
get http://{{deckhouse pod ip addr}}:9650/readyz
close #7644
```changes
type: fix
summary: pod readiness probe during the release minor update
```
> [deckhouse] Deckhouse pod readiness probe during the release minor update

- dhctl/cmd/dhctl/commands/terraform.go
- dhctl/pkg/config/meta.go
- dhctl/pkg/infrastructure/cluster.go
- dhctl/pkg/kubernetes/actions/converge/check.go
- dhctl/pkg/kubernetes/actions/converge/commander.go
- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/kubernetes/actions/converge/nodegroup.go
- dhctl/pkg/kubernetes/actions/converge/state.go
- dhctl/pkg/operations/check/checker.go
- dhctl/pkg/operations/commander/meta_config.go
- dhctl/pkg/operations/exporter.go
- dhctl/pkg/state/state.go
- dhctl/pkg/state/terraform/cached.go
- dhctl/pkg/state/terraform/cluster_cached.go
- dhctl/pkg/state/terraform/lazy.go
- dhctl/pkg/state/terraform/state.go
- dhctl/pkg/terraform/pipeline.go
- dhctl/pkg/terraform/runner.go
- dhctl/pkg/terraform/runner_interface.go
- dhctl/pkg/terraform/single_shot_runner.go
- dhctl/pkg/terraform/terraform_context.go
* generate abandoned node terraform plan correctlly for check & converge;
* load state for check and converge using dhctl state given from parameters in commander mode, instead of using in-cluster state;
* fix panic due to typo in the Config::DeepCopy method.
> [dhctl] fix(dhctl-for-commander): working abandoned nodes converge case with destructive change approval; rework check+converge tf state loading

- dhctl/pkg/config/meta.go
This PR fixes MetaConfig::DeepCopy method, which should create a copy object and return it.
There is a typo: deep copy never creates a copy, it returns old object itself.
As a side effect of non-copy behavior we've experienced a panic in the converge op when scaling down some node-group, panic occured after abandoned nodes deletion.
> [dhctl] fix(dhctl): meta config deep copy method does not return copy

- modules/340-monitoring-kubernetes/hooks/auto_k8s_version.go
- modules/340-monitoring-kubernetes/hooks/auto_k8s_version_test.go
Skip error when "d8-cluster-configuration" secret is missing.
In the case of a managed cluster, this is a perfectly acceptable situation.
```
[error][monitoring-kubernetes] - Module hook failed, requeue task to retry after delay. Failed count is 71. Error: module hook '340-monitoring-kubernetes/hooks/auto_k8s_version.go' failed: cluster configuration kubernetesVersion is empty or invalid
```
```changes
type: fix
summary: Fix error when `d8-cluster-configuration` secret is missing.
```
> Fix error on empty cluster-configuration.yaml config

- release.yaml
Wiping istioVer requirement from release.yaml
We [solved](https://github.com/deckhouse/deckhouse/pull/7815) upgrading issue from 1.57 to 1.58 by wiping istioMinimalVersion. But now we cant update 1.58.4 -> 1.58.5.
There are patch update locks.
```changes
section: istio
type: fix
summary: Wiped `istioVer` requirement from `release.yaml`.
```
> [istio] Wiping istioVer requirement from release.yaml

- ee/modules/160-multitenancy-manager/hooks/project.go
- ee/modules/160-multitenancy-manager/hooks/project_test.go
- ee/modules/160-multitenancy-manager/templates/user-resources/default-project-template.yaml
- ee/modules/160-multitenancy-manager/templates/user-resources/secure-project-template.yaml
- ee/modules/160-multitenancy-manager/templates/user-resources/secure-with-dedicated-nodes-project-template.yaml
A few fixes:
- remove empty manifests generation for embedded templates
- add empty manifests handler for PostRenderer (skip garbage generation)
- add logger for PostRenderer
In some cases embedded templates can generate empty manifests which would create invalid resources in the post renderer. We can avoid this behavior.
Also, add a logger to print generated manifests in the Debug deckhouse mode
We can't create some projects without this fix
```changes
type: fix 
summary: Fix Project rendering in some cases for embedded templates.
```
> [multitenancy-manager] Fix Project templates rendering

- ee/modules/030-cloud-provider-vcd/images/capcd-controller-manager/patches/001_our_machinery.patch
In some cases, a new VM (or VM template) could not contain connections (in cloud director terms), a new connection will be created with Static Pool mode instead of DHCP, and the virtual machine will not bootstrap.
Add additional logs for network reconciliation.
CAPI machines for vCloud director could not bootstrapped.
CAPI machines for vCloud director could not bootstrapped.
cluster was bootstrapped
Node was bootstrapped
```changes
type: fix
summary: Change the default network mode for new VMs.
```
> [cloud-provider-vcd] Change default network mode for new vms

- modules/300-prometheus/templates/prometheus/servicemonitor.yaml
If the samplelimit threshold is exceeded, then prometheuse metrics are lost
there are more than 50,000 metrics in the cluster, because of this "Kubernetes Cluster metrics/Prometheus Benchmark" missing
curl https://10.244.12.67:9090/metrics -H "Authorization: Bearer _token" -k | grep -v ^# | wc -l
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 15.4M    0 15.4M    0     0  30.1M      0 --:--:-- --:--:-- --:--:-- 30.2M
50741
```changes
type: fix 
summary: increasing the sapmleLimit threshold to 100000
```
> [prometheuse] edit samplelimit in service-monitor-prometheus-module

- go_lib/dependency/requirements/requirements.go
Close https://github.com/deckhouse/deckhouse/issues/7883
Multiply functions could be used with one requirements key
```changes
section: core
type: fix 
summary: Use a few requirement functions for one key
```
> [deckhouse] Multiply function for requirements

- dhctl/pkg/system/ssh/cmd/scp.go
This PR disables known_hosts file checking when uploading bundle-related files using scp.
There was related change https://github.com/deckhouse/deckhouse/pull/7360 – which disables strict host checking for ssh client related operations. But seems it lacks just same settings for scp.
We can't connect to the target host anymore from cluster manager worker when target host changes its fingerprint. It may result in following error:
```
2024-03-21T17:57:03Z - [ERROR] - Error happened during task execution: timeout while "Get bundle": last error: detect_bundle.sh: upload: upload file '/tmp/3539489677-detect_bundle.sh': exit status 1
stderr: ssh: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
ssh: @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
ssh: …
```
> [dhctl] fix(dhctl-for-commander): disable known_hosts file checking for scp

- modules/040-node-manager/hooks/internal/autoscaler/capacity/capacity.go
- modules/040-node-manager/templates/cluster-autoscaler/rbac-for-us.yaml
Add permission for machinepoll clusterapi resource
Add support for scale from zero for vcd. But it works partially (see pr https://github.com/kubernetes/autoscaler/pull/4840)
Cluster autoscaller for clusterapi does not work with k8s 1.27+
Cluster autoscaller for clusterapi does not work with k8s 1.27+
```changes
type: fix
summary: Add permission for cluster api resources for cluster
```
> [node-manager] Add permission for cluster api resources for cluster autoscaler and support scale from zero for vcd

- candi/openapi/init_configuration.yaml
- release.yaml
Remove LINSTOR module leftovers
LINSTOR module migrated to sds-replicated-volume external module
No LINSTOR leftover in Deckhouse
```changes
type: fix
summary: Remove LINSTOR module leftovers
```
> [linstor] Remove LINSTOR module leftovers

- deckhouse-controller/crds/doc-ru-module.yaml
- deckhouse-controller/crds/module.yaml
- deckhouse-controller/hack/update-codegen.sh
- deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module.go
- deckhouse-controller/pkg/controller/loader.go
- deckhouse-controller/pkg/controller/models/definition.go
- deckhouse-controller/pkg/controller/models/module.go
Added ability to set and display the current life cycle stage for modules. In addition, the "description" field has been fixed.
Makes it more transparent to work with the life cycle stages of modules.
```changes
type: feature
summary:  Ability to set and display the current life cycle stage for modules.
```
> [deckhouse-controller] Module life cycle stage

- modules/040-node-manager/images/caps-controller-manager/src/internal/client/bootstrap.go
- modules/040-node-manager/images/caps-controller-manager/src/internal/client/cleanup.go
- modules/040-node-manager/images/caps-controller-manager/src/internal/client/client.go
- modules/040-node-manager/images/caps-controller-manager/src/internal/client/task_manager.go
- modules/040-node-manager/images/caps-controller-manager/src/internal/controller/infrastructure/staticmachine_controller.go
Check the `StaticInstance` address by establishing a TCP connection before setting the `StaticInstance` phase to `Bootstrapping`.
If we specify the wrong address for `StaticInstance`, then we need to wait for the bootstrap timeout(20 minutes) and cleanup timeout(10 minutes) to expire before we can delete the `StaticInstance`.
```changes
type: feature
summary: Check the `StaticInstance` address by establishing a TCP connection.
```
> [node-manager](caps) Check the `StaticInstance` address by establishing a TCP connection

- candi/bashible/bashbooster/50_apt.sh
- candi/bashible/bashbooster/50_yum.sh
- candi/bashible/bundles/centos/all/003_install_mandatory_packages.sh.tpl
- ee/be/candi/bashible/bundles/redos/all/003_install_mandatory_packages.sh.tpl
Remove `yum versionlock` and `apt-mark hold`.
Close #6242.
```changes
section: candi
type: fix
summary: Remove 'yum versionlock' and 'apt-mark hold'.
```
> [candi] remove `yum versionlock` and `apt-mark hold`

- modules/400-descheduler/templates/configmap.yaml
Remove incorrect inclusions of the `removeDuplicates` field in the descheduler policy ConfigMap.
Close #5844
```changes
type: fix
summary: Remove incorrect inclusions of the 'removeDuplicates' field.
```
> [descheduler] fix removeDuplicates

- candi/control-plane-kubeadm/config.yaml.tpl
- modules/040-control-plane-manager/openapi/config-values.yaml
- modules/040-control-plane-manager/openapi/doc-ru-config-values.yaml
This option changes the issuer claim `iss` of service account JWT tokens. In addition, it changes what is returned by requesting the `/.well-known/openid-configuration` endpoint.
The feature is required to provide access to external systems and make them able to validate service account tokens. For example, service account token validation may happen as a part of the token exchange between kubernetes and AWS to create resources in AWS using Kubernetes tokens.
Deep dive about how connection between Kubernetes Service Account tokens work
https://mjarosie.github.io/dev/2021/09/15/iam-roles-for-kubernetes-service-accounts-deep-dive.html
```changes
type: feature
summary: Option to change service account tokens issuer
```
> [control-plane-manager] Option to change service account tokens issuer

- modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
Improved description of NginxIngressSslWillExpire and NginxIngressSslExpired
```changes
type: fix 
summary: Improved description of NginxIngressSslWillExpire and NginxIngressSslExpired
```
> [ingress-nginx] Improved description of NginxIngressSslWillExpire and NginxIngressSslExpired

- candi/bashible/bashbooster/60_deckhouse.sh
- candi/bashible/bashible.sh.tpl
- candi/bashible/bootstrap.sh.tpl
- candi/bashible/common-steps/all/003_set_short_hostname.sh.tpl
- candi/bashible/common-steps/all/004_check_hostname.sh.tpl
- candi/bashible/common-steps/all/091_set_virtualization_type.sh.tpl
- candi/bashible/common-steps/all/099_reboot.sh.tpl
- candi/bashible/common-steps/cluster-bootstrap/050_reset_control_plane_on_configuration_change.sh.tpl
- candi/bashible/common-steps/node-group/001_waiting_approval_annotations.sh.tpl
Issue #5594 
Node with short name works well. Node with fqdn names works well, also on centos-based distros. 
```changes
section: candi
type: feature
summary: Node named with fqdn
impact: New nodes have fqdn
```
> [candi] Change node name to fqdn

- modules/040-node-manager/hooks/set_ng_priorities.go
- modules/040-node-manager/hooks/set_ng_priorities_test.go
Add "catch-all" regex (`.*`) with low priority (`1`) to priority list.
Closes #7605.
We don't.
```changes
type: feature
summary: Scale all NodeGroups (with low priority) if any of them have a priority.
```
> [node-manager] Scale all NodeGroups (with low priority) if any of them have a priority.

- ee/be/candi/bashible/bundles/redos/all/003_install_mandatory_packages.sh.tpl
Add flag `--allowerasing ` for dnf/yum update in redos bundle.
For solve problem with conflicting packages:
```
Problem: problem with installed package python3-dnf-plugin-versionlock-4.0.18-4.el7.noarch
- package python3-dnf-plugin-versionlock-4.0.18-4.el7.noarch requires python3-dnf-plugins-core = 4.0.18-4.el7, but none of the providers can be installed
- cannot install both python3-dnf-plugins-core-4.4.2-1.el7.noarch and python3-dnf-plugins-core-4.0.18-4.el7.noarch
```
Execute `003_install_mandatory_packages.sh` without error.
```changes
section: candi
type: fix
summary: fix problem with conflicting packages in bashible step. 
```
> [candi] Add allowerasing flag for redos bundle

- candi/bashible/bundles/debian/all/003_iptables_legacy.sh.tpl
- candi/bashible/detect_bundle.sh
- candi/version_map.yml
- dhctl/README.md
- ee/be/candi/bashible/detect_bundle.sh
- ee/be/modules/600-flant-integration/images/flant-pricing/hooks/prometheus_metrics.sh
- modules/040-node-manager/hooks/minimal_node_os_version.go
- modules/040-node-manager/hooks/minimal_node_os_version_test.go
- modules/040-node-manager/requirements/check.go
- modules/040-node-manager/requirements/check_test.go
- release.yaml
- testing/cloud_layouts/OpenStack/Standard/resources.yaml
add support debian 12 and remove debian 9
Closes #5446 
```changes
section: candi
type: feature 
summary: Add support for Debian 12, remove support for Debian 9.
---
type: feature
summary: Add check for minimal Debian version.
---
type: chore
summary: Change the default image for OpenStack `cloud_layouts` on Debian 12.
```
> [candi] add support debian 12 and remove support debian 9

- modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
Fix misleading summary in alert `NginxIngressDeprecatedVersion`
Just fix misleading summary in alert
Closes #7921
We need it for both actual `1.58` and `1.57` deckhouse releases to fix misleading summary in alert
```changes
type: chore
summary: Fix misleading summary in alert `NginxIngressDeprecatedVersion`.
```
> [ingress-nginx] Fix misleading summary in alert NginxIngressDeprecatedVersion

- testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml
- testing/cloud_layouts/OpenStack/Standard/resources.yaml
- testing/cloud_layouts/Static/infra.tpl.tf
- testing/cloud_layouts/Static/redos-instance-bootstrap.sh
- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/script.sh
Redos image update in e2e.
For using actual redos version in e2e.
e2e with redos 7.3.4 was passed:
openstack:
https://github.com/deckhouse/deckhouse/actions/runs/8392076004
static:
https://github.com/deckhouse/deckhouse/actions/runs/8417452675
yandex-cloud:
https://github.com/deckhouse/deckhouse/actions/runs/8418482812
```changes
type: chore
summary: redos version image update in e2e.
```
> [e2e] update redos ver for e2e

- ee/se/modules/380-metallb/docs/EXAMPLES.md
- ee/se/modules/380-metallb/docs/EXAMPLES_RU.md
Add example of binding specific IP address from MetalLB pool to ingress-controller
```changes
section: doc
type: chore
summary: Add the example of binding IP to Ingress controller.
```
> [doc] add example of binding IP to ingress controller

- dhctl/pkg/operations/destroy/deckhouse.go
- dhctl/pkg/operations/destroy/destroy.go
No converge or destroy locks needed in commander mode, so it is safe to disable it.
This PR have the same purpose as:
* https://github.com/deckhouse/deckhouse/pull/7763
* https://github.com/deckhouse/deckhouse/pull/7791
> [dhctl] fix(dhctl-for-commander): disable local-destroyer lock for commander mode

- modules/040-control-plane-manager/hooks/audit_policy_basic_targets_generated.go
- modules/460-log-shipper/crds/cluster-log-destination.yaml
- modules/460-log-shipper/crds/doc-ru-cluster-log-destination.yaml
- modules/460-log-shipper/docs/FAQ.md
- modules/460-log-shipper/hooks/generate_config.go
- modules/460-log-shipper/hooks/handle_cluster_log_destination_d8_loki.go
- modules/460-log-shipper/hooks/internal/composer/composer.go
- modules/460-log-shipper/hooks/internal/vector/destination/kafka.go
- modules/460-log-shipper/hooks/internal/vector/destination/logstash.go
- modules/460-log-shipper/hooks/internal/vector/destination/loki.go
- modules/460-log-shipper/hooks/internal/vector/destination/vector.go
- modules/460-log-shipper/hooks/testdata/file-to-vector/result.json
- modules/460-log-shipper/hooks/testdata/many-to-one/result.json
- modules/460-log-shipper/monitoring/prometheus-rules/warnings.yaml
- modules/460-log-shipper/templates/log-shipper-token.yaml
- modules/462-loki/hooks/tokens.go
- modules/462-loki/openapi/values.yaml
- modules/462-loki/templates/configmap.yaml
- modules/462-loki/templates/grafana-datasource.yaml
- modules/462-loki/templates/logshipper-log-destination.yaml
- modules/462-loki/templates/rbac-for-us.yaml
- modules/462-loki/templates/rbac-to-us.yaml
- modules/462-loki/templates/servicemonitor.yaml
- modules/462-loki/templates/statefulset.yaml
- testing/matrix/linter/rules/roles/binding-subject.go
Add `kube-rbac-proxy` to prevent access to `Loki` from unauthorized clients.
We need to limit access to `Loki`.
```changes
type: feature
summary: Add kube-rbac-proxy to prevent access to Loki from unauthorized clients.
impact: Loki and Grafana will restart.
```
> [loki] add kube-rbac-proxy

- modules/402-ingress-nginx/images/controller-1-9/Dockerfile
- modules/402-ingress-nginx/images/controller-1-9/curl-chroot-wrapper.sh
Fix maxmind db download for controller 1.9.
Now if we set maxmind db parameters to ingressNginxController resource, nothing is download.
```changes
type: fix
summary: fix maxmind db download for controller 1.9
impact: ingress-nginx 1.9 controller should be restarted
```
> [ingress-nginx] fix maxmind db download for controller 1.9

- modules/015-admission-policy-engine/monitoring/grafana-dashboards/security/admission-policy-engine.json
Provides new columns to grafana representing policy name and policy type to grafana
Closes #7351
Grafana contains new columns marking if an event is triggered by OP or SP.
```changes
type: feature
summary: add new columns to grafana representing policy name and policy type
```
> [admission-policy-engine] add new columns to grafana

- go_lib/hooks/storage_class_change/hook.go
- modules/015-admission-policy-engine/hooks/storage_class_change.go
- modules/015-admission-policy-engine/hooks/storage_class_change_test.go
- modules/015-admission-policy-engine/openapi/config-values.yaml
- modules/015-admission-policy-engine/openapi/doc-ru-config-values.yaml
Provides storageClass field for admission-policy-engine and fix storage class fake alert. 
Add storageClass field to admission-policy-engine and Closes #7671
You can choose a storage class for trivy-provider and no `DeckhouseModuleUseEmptyDir` alert as the module's StatefulSet trivy-provider that uses storage is not deployed.
```changes
type: fix
summary: Fix storageFlass fake alert.
```
> [admission-policy-engine] fix storage class fake alert

- go_lib/dependency/requirements/requirements.go
- go_lib/dependency/requirements/requirements_test.go
- modules/002-deckhouse/hooks/internal/updater/updater.go
Run release requirements checks only for enabled modules
Closes #7923
If module is disabled it's weird to run the requirements check. Requirement values are empty because hook has not been run.
```bash
NAME    WEIGHT   STATE      SOURCE     STAGE   STATUS
istio   110      Disabled   Embedded           Info: disabled by Default bundle
```
Before:
```bash
NAME      PHASE     TRANSITIONTIME   MESSAGE
v1.58.6   Pending   60m              "k8s" requirement for DeckhouseRelease "1.58.6" not met: istio:minimalVersion key is not registred
```
After:
```bash
NAME      PHASE      TRANSITIONTIME   MESSAGE
v1.58.6   Deployed   27s
```
Enabled modules work:
```bash
NAME      PHASE     TRANSITIONTIME   MESSAGE
v1.58.6   Pending   5m54s            "k8s" requirement for DeckhouseRelease "1.58.6" not met: …
```
> [deckhouse] Requirements with module state

- ee/modules/381-l2-load-balancer/crds/l2-load-balncer.yaml
- ee/modules/381-l2-load-balancer/hooks/load_balancers_status_update.go
- ee/modules/381-l2-load-balancer/hooks/load_balancers_status_update_test.go
- ee/modules/381-l2-load-balancer/templates/rbac-to-us.yaml
- ee/modules/381-l2-load-balancer/templates/user-services/service.yaml
Updater for L2 Load Balancers Status.
We can see External IP from Services in L2LoadBalancer Status field. It is convenient.
```changes
type: feature
summary:  Show public IP in the status of a CustomResource.
```
> [l2-load-balancer] Updater for L2 Load Balancers Status

- ee/modules/030-cloud-provider-openstack/images/cloud-data-discoverer/discoverer.go
- ee/modules/030-cloud-provider-openstack/templates/cloud-controller-manager/deployment.yaml
- ee/modules/030-cloud-provider-openstack/templates/cloud-data-discoverer/deployment.yaml
- ee/modules/030-cloud-provider-openstack/templates/csi/controller.yaml
- Add helm_lib_envs_for_proxy to cloud-controller-manager, cloud-data-discoverer and csi components
- Set custom HTTPClient for discoverer if env `OS_CACERT` is provided
We support setups when components use http proxy to access public networks and internet.
Nothing will change for existing clusters.
```changes
type: feature
summary: Allow to install clusters with http proxy in OpenStack
```
> [cloud-provider-openstack] Allow to install clusters with http proxy

- dhctl/pkg/config/validation.go
- dhctl/pkg/config/validation_rules.go
- dhctl/pkg/config/validation_rules_test.go
- dhctl/pkg/config/validation_test.go
Add more config valdiations:
* return clusterConfig from ValidateClusterConfiguration even if there are validation errors 
* hide errors with empty string kind from ValidateClusterConfiguration
* make errors from ValidateClusterSettingsChanges more readable
* add tests
> [dhctl] fix(dhct-for-commander): improve validation error messages

- modules/402-ingress-nginx/templates/controller/admission.yaml
- modules/402-ingress-nginx/templates/kruise/webhook.yaml
Reduce timeoutSeconds parameter to 28 seconds in 402-ingress-nginx/templates/controller/admission.yaml and 402-ingress-nginx/templates/kruise/webhook.yaml
Can't update k8s in digital ocean. Error:
```
Errors preventing us from upgrading this cluster safely
Validating webhook with a TimeoutSeconds value smaller than 1 second or greater than 29 seconds will block upgrades.
Validating webhook with a TimeoutSeconds value smaller than 1 second or greater than 29 seconds will block upgrades.
Mutating webhook with a TimeoutSeconds value smaller than 1 second or greater than 29 seconds will block upgrades.
Validating webhook is configured in such a way that it may be problematic during upgrades.
```
Need to update before the end of the month
```changes
type: fix 
summary: …
```
> [ingress-nginx] digital ocean k8s upgrade, update timeoutSeconds

- tools/release/d8-pull.sh
- tools/release/d8-push.sh
Added deprecation notice for d8-pull and d8-push scripts
We want to notify users that they have to stop using these scripts.
```
bash tools/release/d8-push.sh --help
DEPRECATION NOTICE: d8-pull and d8-push scripts are deprecated. Please use dhctl mirror command instead for Deckhouse releases starting from version 1.45.
See the documentation for additional information https://deckhouse.io/documentation/v1/deckhouse-faq.html#manually-uploading-images-to-an-air-gapped-registry
Usage: tools/release/d8-push.sh
....
```
```changes
section: tools
type: chore
summary: d8-pull and d8-push scripts are deprecated
```
> [tools] d8-pull and d8-push scripts are deprecated

- modules/002-deckhouse/hooks/internal/updater/updater.go
- modules/002-deckhouse/hooks/update_deckhouse_image.go
Inherit behavior for releases with the `release.deckhouse.io/apply-now="true"` annotation from the main release logic.
`release.deckhouse.io/apply-now="true"` releases had their own logic and they were incorrect in some cases:
```yaml
v1.58.6   Deployed     7d
v1.58.7   Pending      19m              "k8s" requirement for DeckhouseRelease "1.58.7" not met: istio:minimalVersion key is not registred
```
Patch release should not check the release requirements, but apply-now release had to check it.
We can use standard rules from minor and patch releases but take into account the release annotation.
```changes
type: fix
summary: Use the same logic as minor/patch for `apply-now` release, except the time settings.
```
> [deckhouse] relevant behavior of releases with `apply-now` annotation

- testing/validate_release_requirements.sh
- tools/validation/main.go
- tools/validation/release_requirements.go
- tools/validation/release_requirements_test.go
- tools/validation/test_data/release_requirements/correct/example.go
- tools/validation/test_data/release_requirements/faulty/example.go
- tools/validation/test_data/release_requirements/faulty/extra-check.go
- tools/validation/test_data/release_requirements/faulty/function-assignment.go
- tools/validation/test_data/release_requirements/release.yaml
The pr introduces yet another validator to the validation CI that inspects current release requirements and makes sure that related checks and requirements don't get introduced by the same PR.
Release requirements validator checks two conditions:
- If there are any release requirements set in the `release.yaml` file which aren't concerned by any d8s module (orphaned requirements);
- If there are some checks and requirements introduced simultaneously by the same PR there (a faulty situation that may affect upcoming d8s releases).
The validation can be skipped if the `skip/release-requirements label` is applied to a PR.
Release requirements validation is run against subsequent changes in the repo.
```changes
section: cicd
type: feature
summary: Add release requirements validation. …
```
> [cicd] add release requirements validation

- dhctl/pkg/kubernetes/actions/converge/node.go
- dhctl/pkg/kubernetes/actions/deckhouse/install.go
- dhctl/pkg/kubernetes/actions/deckhouse/log.go
- dhctl/pkg/kubernetes/actions/deckhouse/pod.go
- dhctl/pkg/kubernetes/actions/manifests/manifests.go
- dhctl/pkg/operations/converge/infra/hook/controlplane/hook.go
- modules/002-deckhouse/templates/deployment.yaml
Dhctl will now corretcly handle multiple deckhouse pods in HA mode during bootstrap and detect which one to check via `d8-system/deckhouse-leader-election` lease object.
This is required as a HA mode for deckhouse deployment is the new default now
```changes
section: dhctl
type: chore
summary: Support Deckhouse controller high availability mode during bootstrap.
```
> [dhctl] Support Deckhouse controller high availability mode during bootstrap

- .github/scripts/js/ci.js
- .github/scripts/js/constants.js
- .github/scripts/js/specs/constants.test.js
Remove deprecated `e2e/use/cri/*` labels for CI.
Currently we only use cri containerd, which is used by default. There are changes to remove deprecated labels:
```
/e2e/use/cri/docker
/e2e/use/cri/containerd
```
https://github.com/deckhouse/deckhouse-test-1/actions/runs/8523761744/job/23346768733
```changes
section: ci
type: chore
summary: Remove deprecated labels in ci
impact: low
```
> [ci] remove deprecated cri labels

- candi/bashible/bashbooster/20_event.sh
- candi/bashible/bashbooster/30_flag.sh
- candi/bashible/common-steps/node-group/031_install_containerd.sh.tpl
- candi/bashible/common-steps/node-group/032_configure_containerd.sh.tpl
- candi/bashible/common-steps/node-group/033_restart_containerd_if_needed.sh.tpl
Change containerd restart flow to avoid unwanted restarts. Add some logging to make future debugging easier.
Handlers declared via `bb-event-on` are executed after the step is completed. Thus `_on_containerd_config_changed` is called after the `containerd-need-restart` flag is checked and unset at the end of step 032, and sets this flag again, resulting in an unwanted restart of containerd on the next bashible run.
Double containerd restarts  can have unwanted consequences.
```changes
section: candi
type: fix
summary: Change containerd restart flow to avoid unwanted restarts.
```
> [candi] Change containerd restart flow to avoid unwanted restarts

- dhctl/pkg/infrastructure/cluster.go
- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/operations/converge/converger.go
- dhctl/pkg/operations/destroy/destroy.go
- dhctl/pkg/operations/import/import_result.go
- dhctl/pkg/operations/import/importer.go
- dhctl/pkg/operations/import/phases.go
- dhctl/pkg/operations/phases/phased_execution_context.go
- dhctl/pkg/operations/phases/phases.go
New import operation which works only in commander-mode. Import task allows any deckhouse cluster become commander's cluster. This implies running commander-agent, disabling auto-converger and other possible in-cluster changes.
This operation needed only for commander mode to implement user-story where user puts already existing deckhouse cluster into control of commander.
> [dhctl] feat(dhctl-for-commander): add import operation skeleton without real implementation, rework on-phase hook

- ee/modules/500-operator-trivy/images/operator/Dockerfile
- ee/modules/500-operator-trivy/images/operator/patches/006-new-metrics.patch
- ee/modules/500-operator-trivy/images/operator/patches/README.md
- ee/modules/500-operator-trivy/monitoring/grafana-dashboards/security/trivy.json
Provides fix for incorrect links in trivy-operator grafana dashboad.
When the vuln does not match our mapping there are incorrect links. To fix this, we have added primaryLink metric for collector and are now using a more "native" way to get these links.
Correct links for vulns in grafana.
```changes
summary: fix incorrect reports links
```
> [operator-trivy] fix incorrect reports links

- modules/040-node-manager/hooks/minimal_node_os_version.go
Fix panic error in discoverMinimalNodesOSVersion hook.
Fix panic error.
```changes
type: fix
summary: Fix panic error in `discoverMinimalNodesOSVersion` hook.
```
> [node-manager]  fix panic error in node-manager hook

- modules/300-prometheus/templates/memcached/sts.yaml
- testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/script_eks.sh
Add imagePullSecrets for memcached template and update configuration.tpl.yaml for EKS e2e.
For successful e2e test execution in EKS.
```changes
type: chore
summary: Add imagePullSecrets for memcached template.
impact: low
```
```changes
type: chore
summary: Added necessary modules for successful e2e test execution.
impact: low
```
> [e2e] fix eks e2e 1.59

- modules/015-admission-policy-engine/crds/doc-ru-security-policy.yaml
- modules/015-admission-policy-engine/crds/security-policy.yaml
Fix allowedClusterRoles field in SecurityPolicy CRD (was accidentally deleted in #7643).
```changes
type: chore
summary: Fix allowedClusterRoles field in SecurityPolicy CRD.
```
> [admission-policy-engine] Fix allowedClusterRoles field in SecurityPolicy CRD

- modules/015-admission-policy-engine/hooks/bootstrap_handler.go
Provides adding a separate queue and throttling for bootstrap hook.
Closes #6591
Bootstrap hook works in separate queue.
```changes
type: feature
summary: add a separate queue and throttling for bootstrap hook
```
> [admission-policy-engine] add a separate queue and throttling for bootstrap hook

- deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_pull_override.go
- deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_release.go
- deckhouse-controller/pkg/controller/controller.go
- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
- deckhouse-controller/pkg/controller/module-controllers/release/override-controller.go
- deckhouse-controller/pkg/docs/updater.go
- go_lib/module/docs.go
This pr introduces the following changes:
- Deckhouse documentation-related lease informer is moved from release controller to a dedicated structure of the main controller where it is available both for release and override controllers (and whatsoever in the future);
- MPO-enabled modules have their documentation published and updated the same way it works for module releases;
- In case of rebuilding a modules' documentation, the documentation archive is formed from the files in the local module's directory. If the directory is unavailable for some reason, the documentation is pulled from the image in the repository.
Modules releases and MPO follow the same way of updating their documentation and most of the time the documentation is built from local files instead of pulling from the …
> [deckhouse-controller] add documentation updater

- modules/300-prometheus/templates/aggregating-proxy/configmap.yaml
Currently, when using a `promxy-backed` data source, both main and long-term Prometheus are queried.
Long-term Prometheus metrics may have extra labels, e.g. `prometheus="deckhouse"` thus, when combining the response some unsolicited series emerge and break most of the queries in Grafana dashboards.
This PR strips the only currently known label from the long-term Prometheus responses.
```changes
type: fix 
summary: Fix aggregation with longterm Prometheus
```
> [monitoring] Fix aggregation with longterm prometheus

- modules/300-prometheus/images/grafana-v10/grafana_home_dashboard.json
- modules/300-prometheus/images/grafana/grafana_home_dashboard.json
- modules/340-monitoring-deckhouse/monitoring/grafana-dashboards/main/deckhouse.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/controller.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/namespace/namespace.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/main/pod.json
Switch from `statusmap` plugin to `statushistory`.
```changes
type: fix 
summary: Switch from `statusmap` plugin to `statushistory`.
```
> [monitoring] Migrate from statusmap and status-history to state-timeline plugin

- .github/ci_templates/e2e_tests.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Add chown temp directories owner in `Cleanup temp directory` job.
If e2e was stuck:
https://github.com/deckhouse/deckhouse/actions/runs/8626464723/job/23644672318
we get orphaned tmp directories with root owner, which will break the next e2e test:
https://github.com/deckhouse/deckhouse/actions/runs/8627080527/job/23649875067
Success start e2e test.
```changes
section: ci
type: fix 
summary: Add chown temp directories owner in Cleanup temp directory job.
impact: low
```
> [ci] fix e2e temp directories owner

- modules/300-prometheus/images/grafana-v10/entrypoint/main.go
Grafana v10 lacks `grafana-cli` binary. `grafana cli` should be used instead.
Missed in the original PR, grafana-v10 pods fail to start if additional plugin installation requested.
> Fix grafana-v10 plugin installation command in entrypoint

- ee/modules/110-istio/monitoring/prometheus-rules/dataplane.yaml
fix PromQL expression for alert `D8IstioDataPlaneVersionMismatch`
The expression in alert `max by (namespace, dataplane_pod) (d8_istio_dataplane_metadata{version="1.19.4"})`
doesn't work
Not necessary
```changes
section: istio
type: fix
summary: fix PromQL expression for alert `D8IstioDataPlaneVersionMismatch`.
```
> [istio] fix PromQL expression for alert D8IstioDataPlaneVersionMismatch

- modules/040-node-manager/monitoring/prometheus-rules/cloud-data-discovery.yaml
Fix ClusterHasOrphanedDisks polk group.
You can't use the same name for a trigger (alert) and for a group.
Polk alerts don't work.
```changes
type: fix
summary: Fix ClusterHasOrphanedDisks polk group.
```
> [node-manager] Fix ClusterHasOrphanedDisks polk group

- modules/460-log-shipper/crds/cluster-log-destination.yaml
Provides extraLabels validation.
Closes #7740
There is a problem related to the fact that you can use reserved keys for extraLabels, and this causes redefinition and unexpected behavior. Adding validation prevents this.
parsed_data cannot be used as a key in extraLabels.
```changes
type: feature 
summary: Add extraLabels validation.
```
> [log-shipper] add extraLabels validation

- modules/110-istio/hooks/discovery_operator_versions_to_install.go
- modules/110-istio/hooks/discovery_operator_versions_to_install_test.go
- modules/110-istio/requirements/check.go
Fixing istio-to-k8s requirement.
Fix bug with release version check.
```changes
section: istio
type: fix
summary: Fix `istio-to-k8s` requirement checker.
```
> [istio] Fixing istio-to-k8s requirement

- modules/000-common/images/shell-operator/werf.inc.yaml
- modules/002-deckhouse/templates/webhook-handler/rbac-for-us.yaml
Add repeated queries to get CRD and apply conversion strategies.
The processing of conversion strategies occurs at the deckhouse start and when a particular module enables.
In this case, processing may be started before CRD is installed. This situation leads to an error.
The problem described above occurs in Deckhouse v1.58, and users may encounter it.
A good example to check is the multitenancy module.
It is necessary to turn off the module. Then remove the CRD of this module (such as projects.deckhouse.io, projecttemplates.deckhouse.io) and enable the module again. The first attempt to apply conversion strategies will fail, but after a few attempts, it will succeed.
```changes
type: fix
summary: Repeated queries with a limited number of attempts to get CRDs …
```
> Watch crd to set webhook

- deckhouse-controller/pkg/helpers/change_registry/change_registry.go
- deckhouse-controller/pkg/helpers/change_registry/change_registry_test.go
- deckhouse-controller/pkg/helpers/register.go
Provides replacement of insecure flag with scheme flag.
Closes #8026
The schema can be defined explicitly, rather than being calculated by path.
```changes
type: feature 
summary: replace insecure flag with scheme flag
```
> [deckhouse-controller] replace insecure flag with scheme flag

- ee/be/candi/bashible/detect_bundle.sh
Allow astra 1.8 in bashible bundle.
For testing opportunities.
```changes
section: candi
type: chore
summary: allow recent astra version in bashible bundle.
```
> [candi] allow astra 18 in bashible bundle

- modules/110-istio/requirements/check.go
- modules/110-istio/requirements/check_test.go
Deckhouse release requirements checker fix.
Deckhouse can't perform upgrade:
```
v1.59.1   Pending      102s             "k8s" requirement for DeckhouseRelease "1.59.1" not met: in coming release the default kubernetes version '1.25.0' will be incompatible with Istio version '1.19'
```
Deckhouse can't perform upgrade.
```changes
section: istio
type: fix
summary: Deckhouse release requirements checker fix.
```
> [istio] Deckhouse release requirements checker fix

- modules/300-prometheus/docs/CONFIGURATION.md
- modules/300-prometheus/docs/CONFIGURATION_RU.md
Add mention of default prometheus PVC size ([defaultDiskSizeGiB 40GiB](https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/hooks/calculate_storage_capacity.go#L31)) in documentation.
We had multiple questions regarding how default size of prometheus PVC is determined. 
Not necessary.
```changes
type: chore
summary: Minor documentation addition.
```
> [prometheus] Mention defaultDiskSizeGiB in docs

- candi/openapi/cluster_configuration.yaml
Allow [reserved](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) characters in http[s]Proxy
Not very important.
```changes
section: candi
type: fix
summary: Fix regex pattern for `httpProxy` to allow using reserved characters.
```
> [candi] Fix httpProxy regex pattern 

- dhctl/pkg/log/logger.go
- dhctl/pkg/log/options.go
- dhctl/pkg/operations/check/checker.go
- dhctl/pkg/operations/import/importer.go
- improve import operation logs, add new process to logger
- reuse single k8s client in sequential import and check operations
> [dhctl] feat(cliuster-import): Improve import logs

- ee/be/modules/600-flant-integration/templates/logs/logdestination.yaml
add buffers with deletion to sending logs to endpoint
We cannot guarantee 100% sla for endpoint, and in case of problems with it we get disk space problem on nodes in all clusters at once.
It is better to lose some logs than to jeopardize client clusters.
```changes
type: chore
summary: added buffer in ClusterLogDestination
```
> [flant-integration] added buffer in ClusterLogDestination

- modules/300-prometheus/hooks/deprecate_outdated_grafana_dashboard_crd.go
- modules/300-prometheus/monitoring/prometheus-rules/deprecation.yaml
- tools/validation/grafana_dashboard.go
- tools/validation/grafana_dashboard_test.go
Additional validations are added:
- Check if datasource uid specified correctly
(legacy, before Grafana 8.3: `"datasource": "$datasource_uid"`, after `"datasource": {"uid": "$datasource_uid"}`)
- Check if panel type is not deprecated
(recommend to migrate from `graph (old)` to `timeseries` and from `flant-statusmap-panel` to `state-timeline`)
Recommendations changed:
- Changed existing `flant-statusmap-panel` deprecation recommendation from `status-history` to `state-timeline`
Validations logic fixed:
- Along with `rows` and `panels` fields, some of the panels can also be of `row` type containing panels inside
Closes #8038 
CI must fail for new pull requests that contain dashboards with deprecated forms of datasource UIDs and panel types 
```changes
section: prometheus, tools
type: chore …
```
> [grafana] Dashboards content validations improvements

- ee/modules/160-multitenancy-manager/templates/user-resources/default-project-template.yaml
- ee/modules/160-multitenancy-manager/templates/user-resources/secure-project-template.yaml
- ee/modules/160-multitenancy-manager/templates/user-resources/secure-with-dedicated-nodes-project-template.yaml
- ee/modules/160-multitenancy-manager/webhooks/validating/projectTemplate
Provides an additional label for system project templates to identify that these are our templates.
Closes #8066
System project templates are marked with the label  `heritage:deckhouse`, and users cannot create project templates with this label.
```changes
type: feature 
summary: Set `heritage: deckhouse` label to embedded ProjectTemplates. Deny ProjectTemplates copying with this label.
```
> [multitenancy-manager] mark system project templates

- global-hooks/migrate/migrate_k8s_upgrade.go
Skip migration if `kubernetesVersion` is set to `Automatic` and the `deckhouseDefaultKubernetesVersion` field is not present in the `d8-cluster-configuration` secret.
This is necessary because The `deckhouseDefaultKubernetesVersion` field also appeared in this release and we rely on it if the `Automatic` version is set.
Important. Fixes a bug.
```changes
type: fix
summary: Fix K8s upgrade migration.
```
> [global-hooks] Fix k8s upgrade migration

- docs/site/_includes/getting_started/yandex/partials/resources.yml.minimal.inc
Remove unnecessary `nodeTemplate` setting for worker in Yandex.Cloud GS, because this label setting by deckhouse automatically
Improve documentation
```changes
section: docs
type: chore
summary: Remove unnecessary `nodeTemplate` set in Getting Started for Yandex.Cloud.
```
> [docs][getting_started] Remove unnecessary nodeTemplate set

- modules/300-prometheus/templates/alertmanager/internal/alertmanager.yaml
Switch Alertmanager configuration selector from alertmanagerConfiguration to alertmanagerConfigSelector
When we using alertmanagerConfiguration prometheus-operator does not add TLS certificate to special secret which mount to alertmanager. Switch  to alertmanagerConfigSelector resolve this problem 
Needs for clients.
TLS secret before 
TLS secret after
Container contains pem 
Switching from old method to new working without problem
```changes
type: fix
summary: Switch Alertmanager configuration selector from alertmanagerConfiguration to alertmanagerConfigSelector
```
> [prometheus] Switch Alertmanager configuration selector from alertmanagerConfiguration to alertmanagerConfigSelector

- modules/300-prometheus/templates/grafana/deployment-v10.yaml
This PR fixes antiAffinity labels and GF_SERVER_ROOT_URL for Grafana v10.
Currently, old and new Grafana share the same label selectors in podAntiAffinity. This results in pod scheduling issues in clusters with HA mode enabled. Also GF_SERVER_ROOT_URL environment variable in Grafana v10 pods has an invalid value.
This patch will prevent Grafana pods from getting stuck in a pending state due to unresolved antiAffinity conditions.
Proper scheduling of the old version and new version of Grafana pods.
```changes
type: fix
summary: Fix grafana-v10 podAntiAffinity and environment variables.
impact: grafana-v10 deployment rolling restart.
```
> Fix antiAffinity and GF_SERVER_ROOT_URL env for grafana-v10

- modules/040-control-plane-manager/images/control-plane-manager/controller/config.go
- modules/040-control-plane-manager/images/control-plane-manager/controller/converge.go
- modules/040-control-plane-manager/images/control-plane-manager/controller/node.go
Fix infinite loop of checksum verification.
Closes #7134
In cases where the static manifest get changes while the kube-apiserver  is unavaliable, we may are stuck in an infinite loop. This behavior looks like a issue:
https://github.com/kubernetes/kubernetes/issues/109596#issuecomment-1219172244
After 120 tries/seconds, we try to recreate static pod:
```
{"level":"warning","msg":"kubernetes pod kube-apiserver-dev-master-0 checksum  does not match expected checksum 079bac0150a77fbe9e1f1937fff87c941b91e2d469fd8c74a3d684fc506ebdbf","time":"2024-04-09T13:48:05Z"}
{"level":"warning","msg":"kubernetes pod kube-apiserver-dev-master-0 checksum  does not match expected checksum 079bac0150a77fbe9e1f1937fff87c941b91e2d469fd8c74a3d684fc506ebdbf","time":"2024-04-09T13:48:06Z"} …
```
> [control-plane-manager] fix checksum loop

- modules/002-deckhouse/hooks/migrate/adopt_node_manager_resources.go
- modules/002-deckhouse/hooks/migrate/adopt_node_manager_resources_test.go
fix annotantions on ns d8-cloud-intance-manager to move to the another module.
When moving ns to another module and helm release we need to set up helm `keep` annotation to prevent namespace deletion.
```changes
section: core
type: fix
summary: fix annotantions on ns d8-cloud-intance-manager to move to the another module
```
> [deckhouse] fix annotantions on ns d8-cloud-intance-manager to move to the another module

- deckhouse-controller/cmd/deckhouse-controller/start.go
- modules/002-deckhouse/templates/deployment.yaml
FQDN k8s pod name is used as the holder identity for the deckhouse-leader-election lease.
It should help in case there is an http proxy implemented in the cluster and NO_PROXY already has `cluster.local` entry or similiar.
It should solve a communication problem between deckhouse pods if there is an http proxy enforced in the cluster.
We have a couple of affected clients with HA mode enabled.
All deckhouse pods should be in ready 2/2 state as soon as the leader starts reporting converged state.
```changes
type: fix
summary: Use fqdn k8s pod name for the lease leader.
```
> [deckhouse-controller] use fqdn k8s pod name for the lease leader

- dhctl/pkg/operations/mirror.go
- dhctl/pkg/operations/mirror/layouts.go
- dhctl/pkg/operations/mirror/pull.go
- dhctl/pkg/operations/mirror/tag_resolver.go
- dhctl/pkg/operations/mirror/tag_resolver_test.go
- dhctl/pkg/operations/mirror/trivy-db.go
- dhctl/pkg/operations/mirror_module.go
`dhctl mirror` will now resolve all tagged image references to their digests and pull images by that digests instead of tags. This reduces the probability of races between mirror pull and images tags being updated during release processes.
This fixes a bug where the mirror was creating an inconsistent package with component versions that didn't match what it was supposed to contain and what was reported at an execution time.
```changes
section: dhctl
type: fix
summary: fix `dhctl mirror` producing bundles with unexpected components versions
```
> [dhctl] mirror: fix producing bundles with unexpected components versions

- modules/460-log-shipper/apis/v1alpha1/cluster_log_destination.go
- modules/460-log-shipper/crds/cluster-log-destination.yaml
- modules/460-log-shipper/crds/doc-ru-cluster-log-destination.yaml
- modules/460-log-shipper/hooks/internal/vector/destination/kafka.go
- modules/460-log-shipper/hooks/testdata/file-to-kafka/manifests.yaml
- modules/460-log-shipper/hooks/testdata/file-to-kafka/result.json
Added the ability to set key_field for kafka
Close https://github.com/deckhouse/deckhouse/issues/8115
Not important.
```changes
type: feature
summary: Add the ability to set key_field for Kafka.
```
> [log-shipper] Add key_field in destination kafka

- modules/030-cloud-provider-yandex/images/cloud-data-discoverer/discoverer.go
Temporarily disable discovery orphan disks in yandex cloud, until CSI starts placing cluster labels that solve the problem of discovery from different clusters in one folder.
Currently alert `ClusterHasOrphanedDisks` gives incorrect information for different clusters in the same yandex folder.
Temporary disable orphan disks discovery for yandex cloud.
```changes
type: fix
summary: Temporary disable orphan disks discovery for yandex cloud.
```
> [cloud-provider-yandex] disable orphan disks discovery

- modules/300-prometheus/templates/aggregating-proxy/configmap.yaml
Long-term Prometheus uses a federation endpoint to scrape metrics from the main Prometheus. This results in the label set discrepancy in the main and long-term series. Thus, it is not always possible for promxy to return unique series while querying these data sources. This can break queries in Grafana dashboards in certain cases, making them unusable.
This PR drops long-term Prometheus querying in aggregating-proxy. This approach turns out to be unreliable.
Multiple known configurations exist when querying long-term in aggregating-proxy breaks queries in Grafana dashboards.
Such as using `externalLabels` configuration option in the Prometheus `ModuleConfig`
```changes
type: fix
summary: Don't query longterm Prometheus in the aggregating-proxy.
```
> aggregating-proxy: don't query longterm prometheus

- deckhouse-controller/cmd/deckhouse-controller/start.go
Add a fallback if deckhouse is in HA mode and KUBERNETES_CLUSTER_DOMAIN env isn't set (it happens if deckhouse had already been in HA mode when 1.59.5 version was applied). In that case, the identity value for the leader election ignores KUBERNETES_CLUSTER_DOMAIN value.
If the deckhouse deployment is in HA mode and version 1.59.5 is applied, deckhouse won't start as the KUBERNETES_CLUSTER_DOMAIN isn't set, but it is mandatory to have it set.
It fixes a nasty bug in HA mode.
If the KUBERNETES_CLUSTER_DOMAIN env isn't set, the identity value for the leader election is successfully set without the env.
```changes
type: fix
summary: Drop cluster-domain part of the leader identity if KUBERNETES_CLUSTER_DOMAIN isn't set.
```
> [deckhouse-controller] add a fallback if KUBERNETES_CLUSTER_DOMAIN isn't set

- modules/300-prometheus/templates/memcached/sts.yaml
Memcached doesn't use `imagePullSecrets` because of incorrect Statefulset. And if registry needs auth, image can't be pulled.
`imagePullSecrets` appear in Statefulset `-o yaml`
> [prometheus] add imagePullSecrets to memcached

- release.yaml
set minimum supported debian 10 
Closes #7350
forbid to use Debian 9
```changes
section: candi
type: feature 
summary: forbid to use Debian 9.
```
> [candi] set minimum supported version debian 10 

- modules/002-deckhouse/templates/registry-secret.yaml
- modules/002-deckhouse/webhooks/validating/registry-secret-address
Added a webhook to validate that registry address in `deckhouse-registry` secret is always present
Closes https://github.com/deckhouse/deckhouse/issues/7173
```changes
type: fix
summary: Validate that registry address is always present in deckhouse configuration.
```
> [deckhouse] Validate that registry address is always present

- global-hooks/migrate/migrate_k8s_upgrade.go
Trigger k8s_upgrade migration when k8s version changes.
```changes
type: fix
summary: Trigger k8s_upgrade migration when k8s version changes
```
> [global-hooks] Trigger k8s_upgrade migration when k8s version changes

- .github/ci_templates/e2e_tests.yml
- .github/scripts/js/ci.js
- .github/scripts/js/constants.js
- .github/workflow_templates/e2e.abort.multi.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/EKS/WithoutNAT/infra.tf.tpl
Add support label `e2e/use/k8s/automatic` for using `kubernetesVersion: Automatic`
[eks with automatic label](https://github.com/deckhouse/deckhouse-test-2/actions/runs/8834413918)
[openstack with automatic label](https://github.com/deckhouse/deckhouse-test-2/actions/runs/8832245576)
[openstack without version labels](https://github.com/deckhouse/deckhouse-test-2/actions/runs/8833639046)
```changes
section: ci
type: feature
summary: Add support label e2e/use/k8s/automatic.
```
```changes
type: chore
summary: Change instance type for e2e eks.
```
> [ci] add support label for k8s version automatic

- modules/040-node-manager/monitoring/prometheus-rules/cloud-data-discovery.tpl
Fix temporary disable alert orphan disks for yandex cloud.
Related to: #8224 
In static clusters `.Values.global.clusterConfiguration` doesn't have cloud.provider specs, that return `nil pointer evaluating interface {}.provider` error.
Сorrect disabling of orphan disks alert for yandex cloud.
```changes
type: fix
summary: Fix temporary disable alert alert orphan disks for yandex.
```
> [node-manager]  fix disable alert orphan disks for yandex cloud

- dhctl/pkg/kubernetes/actions/deckhouse/log.go
- dhctl/pkg/log/logger.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-abort.go
- dhctl/pkg/operations/bootstrap/steps.go
- dhctl/pkg/system/ssh/frontend/upload-script.go
Output bashible scripts log wen error occurred only.
Suppress klog logs for none debug output 
Improve the user experience. 
```changes
section: dhctl
type: chore
summary: Reduce bootstrap logs
```
> [dhctl] Reduce bootstrap logs

- ee/be/modules/600-flant-integration/images/flant-pricing/hooks/node_group_resources_metrics.py
- ee/be/modules/600-flant-integration/images/flant-pricing/hooks/node_group_resources_metrics_test.py
Fix count resources for the different nodegroup roles.
Added tests.
Wrong counting of the worker nodegroups resources.
```changes
type: fix
summary: fix resources counting
```
> [flant-integration] fix resources counting and add tests

- modules/031-ceph-csi/docs/FAQ.md
- modules/031-ceph-csi/docs/FAQ_RU.md
Changed the command to display a list of RBD volumes divided by nodes.
The current command sometimes displays incorrect information due to the display of the time of the last restart of the pod.
```changes
type: chore
summary: Update FAQ.
```
> [ceph-csi] Update FAQ

- ee/modules/030-cloud-provider-vsphere/images/cloud-data-discoverer/go.mod
- ee/modules/030-cloud-provider-vsphere/images/cloud-data-discoverer/go.sum
Update govmomi lib to let discoverer work with vSphere 8.0.2.
With vCenter Server 8.0.2 and govmomi 0.35.0 (current version) we get the following error:
```json
{
"level": "error",
"msg": "Attempt 3 of 3. Getting disks meta error: failed to get disks: failed to list disks: ServerFaultCode: Unable to resolve WSDL method name CnsQueryVolume in vim.version.v8_0_2_0 (vim25/8.0.2.0)\n\nwhile parsing SOAP body\nat line 2, column 202\n\nwhile parsing SOAP envelope\nat line 2, column 0\n\nwhile parsing HTTP request before method was determined\nat line 1, column 0",
"time": "2024-04-18T16:12:26Z"
}
```
Since govmomi version 0.37.0 everything works in both 7.0.3 and 8.0.2 vCenter Server. I believe [this change](https://github.com/vmware/govmomi/commit/095f926b5840f960fa9c452c5a727369f0dc0a8e) that …
> [cloud-provider-vsphere][discovery] Update govmomi lib to fix discoverer for vSphere 8.0.2

- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
- deckhouse-controller/pkg/controller/module-controllers/release/updater.go
- deckhouse-controller/pkg/docs/updater.go
Fixed updates to module loading statistics and an error related to concurrent requests for documentation building.
```changes
type: fix
summary: Fix updates to module loading statistics and an error related to concurrent requests for module documentation building.
```
> [deckhouse-controller] hotfix

- modules/002-deckhouse/templates/deployment.yaml
This PR introduces an additional condition for the `deckhouse` module high availability mode: `.Values.global.clusterIsBootstrapped` values has to be true.
This measure should prevent deckhouse operator from switching to high availability mode when the cluster hasn't got bootstrapped yet, minimizing the impact on the whole bootstrapping process.
It may come in handy as soon as possible.
If a cluster hasn't bootstrapped yet, `deckhouse` operator shouldn't be run in high availability mode.
```changes
type: chore
summary: Deckhouse high availability mode can be enabled only after the bootstrap process completes.
```
> [deckhouse] enable ha only if clusterIsBootstrapped

- candi/bashible/common-steps/node-group/032_configure_containerd.sh.tpl
- candi/bashible/common-steps/node-group/033_restart_containerd_if_needed.sh.tpl
Add `containerd config dump` check, before restart containerd in bashible step.
Allow restart `containerd` in bashible step only with valid configuration files.
```changes
section: candi
type: feature
summary: Add preflight check containerd restart.
```
> [candi] add preflight check containerd restart

- modules/402-ingress-nginx/templates/controller/configmap.yaml
`IngressNginxController.spec.underscoresInHeaders` should change `enable-underscores-in-headers` parameter in  `nginx-config` configmap. It looks like we forgot to add this parameter to the template
https://deckhouse.io/documentation/v1/modules/402-ingress-nginx/cr.html#ingressnginxcontroller-v1-spec-underscoresinheaders
https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/configmap.md#enable-underscores-in-headers
`IngressNginxController.spec.underscoresInHeaders` will change `enable-underscores-in-headers`
```
type: fix
summary: Ability to change enable-underscores-in-headers
impact: Ability to change enable-underscores-in-headers
```
> Nginx ingress underscores in headers fix

- ee/candi/cloud-providers/openstack/docs/LAYOUTS.md
- ee/candi/cloud-providers/openstack/docs/LAYOUTS_RU.md
- ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
Set the default `standard.bastion.instanceClass.rootDiskSize` property to 50 gigabytes in the `OpenStackClusterConfiguration` schema.
Close #6867.
```changes
section: candi
type: fix
summary: 'Set the default `standard.bastion.instanceClass.rootDiskSize` property to 50 gigabytes in the `OpenStackClusterConfiguration` schema.'
```
> [candi](openstack) Set the default bastion rootDiskSize to 50 gigabytes

- dhctl/pkg/app/preflight.go
- dhctl/pkg/preflight/domain.go
- dhctl/pkg/preflight/preflight.go
- modules/002-deckhouse/webhooks/validating/public-domain-template
- modules/042-kube-dns/webhooks/validating/cluster-domain-alias
Add extra `publicDomainTemplate` and `clusterDomainAliases` checks.
Closes #7796
It is changes that add preflight check for dhctl and validation webhook that forbid using same domain in `clusterDomain` and `publicDomainTemplate`.
```changes
section: dhctl
type: feature
summary: Add preflight check for `publicDomainTemplate`.
```
```changes
type: feature
summary: Add validation webhook for `publicDomainTemplate`.
```
```changes
type: feature
summary: Add validation webhook for `clusterDomainAliases`.
```
> [dhctl][kube-dns][deckhouse] add extra publicdomaintemplate check

- ee/fe/modules/500-okmeter/templates/daemonset.yaml
- modules/500-okmeter/templates/daemonset.yaml
Restart okagent pods on API token change.
Closes #8319 
Okagent pods restarts on API token change
```changes
type: fix
summary: Restart okagent pods on API token change.
```
> [okmeter] Restart okagent pods on API token change

- dhctl/pkg/operations/mirror/layouts.go
This is a backport of a fix for pulling of additional modules images from d8-cli, that was broken in 1.59.5.
This is a bugfix for a bug that users are facing in the wild
```changes
section: dhctl
type: fix
summary: Backport fix for pulling of additional modules images from d8-cli into `dhctl mirror`.
```
> [dhctl] mirror: backport fix for pulling of additional modules images from d8-cli

- modules/110-istio/openapi/values.yaml
Optimizing matrix tests for istio module.
There are too many configuration options for the module and tests can't made it during 15m timeout.
Can't publish the 1.59.11 release.
```changes
section: istio
type: fix
summary: Optimize matrix tests.
```
> [istio] Optimizing matrix tests

- modules/040-control-plane-manager/docs/internal/ETCD_RECOVERY.md
- modules/040-control-plane-manager/monitoring/prometheus-rules/etcd-maintenance.yaml
Fix etcdctl command from pods to distroless syntax - remove /bin/sh
```changes
section: docs
type: chore
summary: Fix etcdctl command from pods to distroless syntax.
```
> [docs] Fix etcdctl command from pods

- .github/workflow_templates/build-and-test_dev.yml
- .github/workflow_templates/build-and-test_pre-release.yml
- .github/workflow_templates/build-and-test_release.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
Update CI to skip building documentation on some cases.
```changes
section: ci
type: chore
summary: Update CI to skip building documentation on some cases.
```
> [ci][docs] Skip building documentation on some cases

- deckhouse-controller/pkg/controller/module-controllers/downloader/module_downloader.go
- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
- deckhouse-controller/pkg/controller/module-controllers/release/override-controller.go
This PR fixes the situation described below, in the `Why do we need it section`.
Also, there are several minor changes/fixes/improvements related to the deckhouse-controller:
- release and override controllers' got separate PreflightChecks and corresponding methods of restoring absent modules on start up;
- a minor bug in override controller, related to restoring MPO modules, was fixed;
- a minor bug in release and override controllers, related to filtering out some update events, was fixed;
- some other small improvements.
A Deckhouse installation running in HA mode is susceptible to the situation when the modules, deployed by ModulePullOverrides, get out of sync with the registry due to the fact that we keep current module image's hash in the MPO object, but there might be a drift …
> [deckhouse-controller] fix mpo sync in HA mode

- ee/modules/500-operator-trivy/hooks/storage_class_change.go
- ee/modules/500-operator-trivy/hooks/storage_class_change_test.go
- ee/modules/500-operator-trivy/openapi/config-values.yaml
- ee/modules/500-operator-trivy/openapi/doc-ru-config-values.yaml
It provides the storageClass field for trivy.
Solves #8337
We could not explicitly set the storage class for trivy, now we can.
The storage class can be set explicitly.
```
root@dev-master-0:~# cat trivy.yaml 
metadata:
name: operator-trivy
spec:
version: 1
enabled: true
settings:
storageClass: ceph-ssd 
```
```
root@dev-master-0:~# dcm values operator-trivy
internal:
effectiveStorageClass: ceph-ssd
enabledNamespaces: []
reportUpdater: {}
```
```changes
type: feature 
summary: add ability to explicitly set storageClass.
```
> [operator-trivy] add storageClass field

- ee/fe/modules/500-okmeter/templates/daemonset.yaml
- modules/500-okmeter/templates/daemonset.yaml
Respect `nodeSelector` and `tolerations` configuration options from the ModuleConfig
Fixes #7886 
```changes
```
> [okmeter] Use nodeSelector and tolerations from ModuleConfig

- modules/110-istio/openapi/config-values.yaml
Setting `trafficRedirectionSetupMode` to `InitContainer` by default.
It is too dangerous to have `CNIPlugin` mode as default.
It is too dangerous to have `CNIPlugin` mode as default.
```changes
section: istio
type: fix
summary: "Set `trafficRedirectionSetupMode` option to `InitContainer` by default".
```
> [istio] Setting trafficRedirectionSetupMode to InitContainer by default

- candi/cloud-providers/yandex/openapi/doc-ru-instance_class.yaml
- candi/cloud-providers/yandex/openapi/instance_class.yaml
Add `network-ssd-io-m3` disk type to `YandexInstanceClass`.
Closes https://github.com/deckhouse/deckhouse/issues/7349
Ref https://github.com/deckhouse/deckhouse/pull/8384
Support for SSD IO StorageClass was added a while ago https://github.com/deckhouse/deckhouse/pull/5684
This PR adds `network-ssd-io-m3` to the CRD.
Was tested manually in a cluster by creating CloudEphemeral nodegroup.
High-performance redundant storage SSD IO is available for node root disks. 
```changes
type: feature
summary: Added option to create nodes with SSD IO root disks.
```
> [cloud-provider-yandex] Add SSD IO DiskType to YIC

- docs/site/_includes/getting_started/vcd/partials/config.ru.yml.standard.ee.inc
- docs/site/_includes/getting_started/vcd/partials/config.yml.standard.ee.inc
- docs/site/_includes/getting_started/vcd/partials/resources.yml.minimal.inc
Fix getting started configs for VCD provider
```changes
section: docs
type: chore
summary: Fix getting started configs for VCD provider.
```
> [docs][vcd] Fix getting started configs

- modules/002-deckhouse/templates/deployment.yaml
- modules/470-chrony/template_tests/module_test.go
- modules/470-chrony/templates/daemonset.yaml
This pr updates a couple of charts (chrony daemonset and deckhouse deployment respectively) to use `globa.discovery.clusterDomain` instead of `global.clusterConfiguration.clusterDomain` because of the possibility of missing `kube-system/d8-cluster-configuration` secret in the cluster (highly likely, such a cluster may have something to do with being previously run in a managed k8s service like EKS).
A couple of customers clusters, missing `kube-system/d8-cluster-configuration` secrets, were found. Without the secret the deckhouse deployment manifests can't be rendered if HA mode is enabled, missing `global.clusterConfiguration.clusterDomain` value.
clusterDomain value must be successfully fetched from `.global.discovery.clusterDomain` path, preventing related rendering issue in a cluster …
> [deckhouse] use global.discovery where possible

- modules/300-prometheus/images/grafana-v10/grafana_home_dashboard.json
Fix URL in Grafana home panel to use local documentation.
```changes
type: chore
summary: Fix URLs to the documentation in the Grafana home panel.
```
> [prometheus] Fix URLs to the documentation in the Grafana home panel

- modules/402-ingress-nginx/images/controller-1-6/patches/README.md
- modules/402-ingress-nginx/images/controller-1-6/patches/nginx-tmpl.patch
- modules/402-ingress-nginx/images/controller-1-6/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-1-9/patches/README.md
- modules/402-ingress-nginx/images/controller-1-9/patches/nginx-tmpl.patch
- modules/402-ingress-nginx/images/controller-1-9/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/templates/controller/configmap.yaml
It provides fix for ingress-nginx logs format.
In come cases, nginx may have 009 response status, but our log format expects a valid number, so to solve it, we replace the standard status field with a new one, which is explicitly converted to number by lua.
The status field is always a valid number.
```changes
type: fix 
summary: Replace status with formatted status in logs.
```
> [ingress-nginx] replace status with formatted status in logs

- modules/402-ingress-nginx/templates/kruise/webhook.yaml
Addition to PR [7933](https://github.com/deckhouse/deckhouse/pull/7933)
Reduce timeoutSeconds parameter to 28 seconds in 402-ingress-nginx/templates/kruise/webhook.yaml#L20
Can't update k8s in digital ocean. Error:
```
Errors preventing us from upgrading this cluster safely
Validating webhook with a TimeoutSeconds value smaller than 1 second or greater than 29 seconds will block upgrades.
Validating webhook with a TimeoutSeconds value smaller than 1 second or greater than 29 seconds will block upgrades.
Mutating webhook with a TimeoutSeconds value smaller than 1 second or greater than 29 seconds will block upgrades.
Validating webhook is configured in such a way that it may be problematic during upgrades.
```
```changes
type: fix 
summary: Digital ocean Kubernetes …
```
> [ingress-nginx] digital ocean k8s upgrade, update timeoutSeconds 

- ee/se/modules/380-metallb/monitoring/grafana-dashboards/kubernetes-cluster/metallb.json
Switch to state-timeline plugin in MetalLB  Grafana dashboard
flant-statusmap will be abandoned shortly
No
```changes
type: fix
summary: Switched to state-timeline plugin in MetalLB  Grafana dashboard.
```
> Fix metallb dashboard

- .github/CODEOWNERS
Add new people to CODEOWNERS for okmeter module.
Add:
- Andrey Kolashtov
- Vadim Lazovskiy
- Vladimir Guryanov
```changes
section: ci
type: chore
summary: Update owners for okmeter module.
```
> [monitoring] Update owners for okmeter module

- modules/300-prometheus/templates/aggregating-proxy/configmap.yaml
… if Prometheus is unavailable or on connection timeout.
Change ignore_error value from true to false in the aggregation proxy config.
When ignore_error is set to true and the aggregation proxy does not receive a response from all Prometheus instances (due to reasons such as large queries causing connection timeouts, or all Prometheus instances being unavailable), an empty result is cached. Consequently, users see empty graphs in Grafana.
This PR changes ignore_error from true to false to prevent caching empty results in these scenarios and returne to Graphana error.
```changes
type: fix 
summary: Change ignore_error value from true to false in the aggregation proxy config to prevent caching empty results.
```
> [monitoring] Fix caching of empty results with aggregation proxy

- tools/spelling/clean-files.py
Linter fails when tries unmarshall YAML structure from the PR diff. Just add try-except block to handle potential YAML parsing errors and fix it later.
```changes
type: chore
summary: Fix linter for spellchecking documentation.
```
> [testing] Fix linter for spellchecking documentation

- deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_source.go
- deckhouse-controller/pkg/controller/module-controllers/source/controller.go
- deckhouse-controller/pkg/controller/module-controllers/source/controller_test.go
- deckhouse-controller/pkg/controller/module-controllers/source/testdata/golden/with-error.yaml
- deckhouse-controller/pkg/controller/module-controllers/source/testdata/golden/with-stale-error.yaml
- deckhouse-controller/pkg/controller/module-controllers/source/testdata/with-error.yaml
- deckhouse-controller/pkg/controller/module-controllers/source/testdata/with-stale-error.yaml
Remove stale errors from ModuleSource status
```
status:
message: Some errors occurred. Inspect status for details
moduleErrors:
- error: 'fetch image error: GET https://registry.deckhouse.io/v2/deckhouse/ee/modules/operator-redisfailover/release/manifests/alpha:
MANIFEST_UNKNOWN: manifest unknown; map[Tag:alpha]'
name: operator-redisfailover
```
If a wrong module is deleted from registry, ModuleSource will have a stale error in the status. We can remove it gracefully
To avoid errors in a client's clusters
```changes
type: fix
summary: Remove stale errors in a ModuleSource status.
```
> [deckhouse] Fix stale errors for ModuleSource

- deckhouse-controller/pkg/controller/controller.go
- deckhouse-controller/pkg/controller/loader.go
- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
- deckhouse-controller/pkg/controller/module-controllers/release/override-controller.go
If we have doubled module (Embedded and External one), deckhouse will use the embedded one but print an external source in modules list output
Also ignore deleted resource on startup module restoration
When we are rewriting a module, we can have doubled modules for some period of time. We want to use and show the embedded one, until it is deleted
Before:
```yaml
NAME                  WEIGHT   STATE       SOURCE           STAGE        STATUS
flant-integration    600       Disabled    flint-registry
```
After:
```yaml
NAME                WEIGHT   STATE      SOURCE     STAGE   STATUS
flant-integration   600      Disabled   Embedded
```
```changes
type: fix
summary: Print the right source for doubled (Embedded + External) modules.
```
> [deckhouse] Source for doubled module

- modules/002-deckhouse/docs/FAQ.md
- modules/002-deckhouse/docs/FAQ_RU.md
Updated the documentation for running kube-bench to remove dependency on yq, which is not available in the container. The new instructions use kubectl and jq only.
The change resolves the issue where yq is not available in the container, allowing users to run kube-bench using available tools only.
Users should be able to run kube-bench on specific nodes without the need for yq. The command provided in the documentation should work correctly.
```changes
section: docs
type: fix
summary: Update kube-bench documentation to use `kubectl` and `jq` instead of `yq`.
> [docs] kube-bench apply without yq

- modules/045-snapshot-controller/docs/README.md
- modules/045-snapshot-controller/docs/README_RU.md
- modules/045-snapshot-controller/enabled
This PR fixes the documentation and scripts in the snapshot-controller module by adding support for `csi-nfs`.
Now snapshot controller have no support for `csi-nfs` module.
Snapshot controller module supports for csi-nfs module
```changes
type: chore
summary: Fix the documentation. Fix the enabled script to add support for `csi-nfs` module.
```
> [snapshot-controller] Added csi-nfs support in volume snapshot controller,

- docs/documentation/.werf/nginx.conf
Added permanent rewrite rules to redirect `021-kube-proxy` to `036-kube-proxy` in the nginx configuration for the documentation. This ensures that the URLs for kube-proxy documentation are correctly mapped to their new locations.
```changes
section: docs
type: chore
summary: Add rewrite rules for kube-proxy module documentation.
```
> [chore][docs] Add rewrite rules for kube-proxy module documentation

- dhctl/pkg/config/base.go
- global-hooks/discovery/cluster_configuration_test.go
- modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
- release.yaml
Set the Default K8s version to '1.27'  (when using `Automatic` in the [kubernetesVersion](https://deckhouse.io/documentation/v1/installing/configuration.html#clusterconfiguration-kubernetesversion) parameter).
Deckhouse Life Cycle.
```changes
type: chore
summary: Change the default Kubernetes version to '1.27'.
impact: Cluster will upgrade if the [kubernetesVersion](https://deckhouse.io/documentation/v1/installing/configuration.html#clusterconfiguration-kubernetesversion) parameter is set to `Automatic`) .
```
> [deckhouse] Set default k8s version to '1.27'

- candi/bashible/bashible.sh.tpl
- candi/bashible/bootstrap.sh.tpl
- candi/bashible/common-steps/node-group/003_set_short_hostname.sh.tpl
In the previous PR we have multiple errors with detecting host name. For static nodes we have incorrect condition in template for discovery nodegroup type
For static instances hostname was short (`hostname -s`)
Cloud cluster
Static
```changes
type: fix
summary: Fix incorrect condition for hostname discovery
```
> [bashible] Fix incorrect condition for hostname discovery

- ee/modules/650-runtime-audit-engine/docs/FAQ.md
- ee/modules/650-runtime-audit-engine/docs/FAQ_RU.md
- ee/modules/650-runtime-audit-engine/hack/far-converter/README.md
Fix path to FalcoAuditRules converter.
Fix missing macro in example.
Improve documentation.
```changes
type: chore
summary: Fix path to FalcoAuditRules converter.
```
> [runtime-audit-engine] Fix path to FalcoAuditRules converter

- candi/bashible/bashible.sh.tpl
- candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
Set LC_NUMERIC before using awk so that the output format of numbers will be dotted.
If the system default locale ru is comma delimiter.
```changes
section: candi
type: fix
summary: set LC_NUMERIC in configure kubelet
```
> [candi] set LC_NUMERIC in configure kubelet

- dhctl/pkg/system/ssh/frontend/agent.go
- modules/040-node-manager/images/caps-controller-manager/src/internal/ssh/ssh.go
Trim all leading and trailing white space and add a newline to the SSH private key before passing the key to the OpenSSH client.
OpenSSH client has strict requirements for private key files. The private key file must not have any leading or trailing white space. The private key file must also end with a newline character. If the private key file does not meet these requirements, the OpenSSH client will not be able to use the private key file to authenticate with the remote server.
```changes
section: dhctl
type: fix
summary: Try to fix an incorrectly formatted SSH private key before using it.
section: caps
type: fix
summary: Try to fix an incorrectly formatted SSH private key before using it.
```
> Try to fix an incorrectly formatted SSH private key before using it

- modules/340-monitoring-ping/hooks/discover_targets.go
- modules/340-monitoring-ping/hooks/discover_targets_test.go
Skip nodes without addresses.
The hook can catch the moment when the Node object has already appeared, but the address has not yet appeared in the status, which leads to the appearance of a node without an address in the targets for the `monitoring-ping.py` script and causes the following error:
```
Traceback (most recent call last):
File "/src/monitoring-ping.py", line 184, in <module>
result = computed[dimension["ip"]]
~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: ''
```
```changes
type: fix
summary: Skip nodes without IP address.
```
> [monitoring-ping] Skip nodes without addresses

- docs/documentation/_data/deckhouse-ports.yml
Add sds-node-configurator metric port to documentation
We need actual port number list in documentation
It's can be important for our clients security teams
Actual port number list in documentation
```changes
section: docs
type: chore
summary: Add sds-node-configurator metric port to documentation.
```
> [docs] Add sds-node-configurator metric port

- dhctl/pkg/app/preflight.go
- dhctl/pkg/preflight/preflight.go
- dhctl/pkg/preflight/registry.go
Preflight check registry credentials before start instalations
Before performing bootstrap, checks the possibility of autorize in registry
Preventing failures before bootstrap execution
```changes
section: dhctl
type: feature
summary: Preflight check registry credentials before start instalations
```
> [dhctl] Preflight check registry credentials

- ee/candi/cloud-providers/vcd/layouts/standard/base-infrastructure/outputs.tf
- ee/candi/cloud-providers/vcd/openapi/cloud_discovery_data.yaml
- ee/modules/030-cloud-provider-vcd/candi
- ee/modules/030-cloud-provider-vcd/hooks/discover.go
- ee/modules/030-cloud-provider-vcd/images/cloud-data-discoverer/discoverer.go
- ee/modules/030-cloud-provider-vcd/images/vcd-csi-plugin-legacy/patches/01-add-iops-calculation.patch
- ee/modules/030-cloud-provider-vcd/images/vcd-csi-plugin-legacy/patches/README.md
- ee/modules/030-cloud-provider-vcd/images/vcd-csi-plugin-legacy/werf.inc.yaml
- ee/modules/030-cloud-provider-vcd/images/vcd-csi-plugin/werf.inc.yaml
- ee/modules/030-cloud-provider-vcd/openapi/values.yaml
- ee/modules/030-cloud-provider-vcd/template_tests/module_test.go
- ee/modules/030-cloud-provider-vcd/templates/csi/controller.yaml
- ee/modules/030-cloud-provider-vcd/templates/csi/storage-classes.yaml
- go_lib/cloud-data/apis/v1alpha1/vcd_cloud_provider_discovery_data.go
- testing/library/images_tags_generated.go
- testing/openapi_validation/validators/enum.go
Support multiple VCD API versions.
We want to support the online volume expansion, which is available since vcd-csi-driver version 1.6.0, but we need to support an older version of the VCD API (< 37.2), which is not compliant with 1.6.0 vcd-csi-driver.
Compatibility matrix: https://github.com/vmware/cloud-director-named-disk-csi-driver/blob/15142e09f9ac1dfcb4860e3f307d28f092b947de/README.md
```changes
type: feature
summary: Support multiple VCD API versions.
```
> [cloud-provider-vcd][discovery] Support multiple VCD API versions

- modules/042-kube-dns/webhooks/validating/cluster-domain-alias
Fix empty array jq error in domain alias validation webhook.
Fixes #8484 
Restores the ability to edit mc of kube-dns module.
```
root@dev2-master-0:~# kubectl  get mc kube-dns  -o yaml
metadata:
creationTimestamp: "2024-05-27T14:07:06Z"
generation: 5
name: kube-dns
resourceVersion: "4260293"
uid: 6ed0d9de-fd1a-4807-8285-8ba51d98e08e
spec:
enabled: true
status:
message: ""
version: "1"
root@dev2-master-0:~# kubectl patch --type=merge -p '{"metadata": {"annotations": {"meta.helm.sh/release-name": "cluster-resources", "meta.helm.sh/release-namespace": "cluster-resources"}}}' ModuleConfig/kube-dns
moduleconfig.deckhouse.io/kube-dns patched
root@dev2-master-0:~#
```
```changes
type: fix
summary: Fix empty array error in …
```
> [kube-dns] fix cluster-domain-alias webhook

- candi/bashible/bashbooster/50_registrypackages.sh
- go_lib/registry-packages-proxy/registry/default_client.go
- Don't replace the system CA certificates if a custom CA is used.
- Print response body in case of http error (instead of default `urllib.error.HTTPError: HTTP Error 500: Internal Server Error`)
We want to add CAs to the system ones, not replace them completely.
```changes
section: registry-packages-proxy
type: fix
summary: Don't replace the system CA certificates if a custom CA is used.
---
section: registry-packages-proxy
type: chore
summary: Print response body in case of http error.
```
> [registry-packages-proxy] Don't replace the system CA certificates if a custom CA is used

- ee/modules/030-cloud-provider-vcd/openapi/values.yaml
Remove required from discoveryData property.
These fields are not populated by Terraform (unlike in providerDiscoveryData property).
```
1. ModuleHookRun:main:kubernetes:030-cloud-provider-vcd/hooks/generate_capcd_webhook_certs.go:secret:OperatorStartup:failures 45:3 errors occurred:
* cloudProviderVcd.internal.discoveryData.apiVersion is required
* cloudProviderVcd.internal.discoveryData.kind is required
```
It is not working for now.
```changes
type: fix
summary: Remove required from discoveryData property.
```
> [cloud-provider-vcd] Remove required from discoveryData property

- modules/040-node-manager/images/caps-controller-manager/src/internal/ssh/ssh.go
Write the SSH private key to a temporary file and delete the file after use.
Multiple goroutines overwrite the same SSH private key file.
```changes
section: caps
type: fix
summary: Write the SSH private key to a temporary file and delete the file after use.
```
> [caps] Write the SSH private key to a temporary file

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Add info about `deckhouse-controller helper change-registry` command into docs.
It will help the documentation to be more friendly to beginners.
The documentation will become more complete.
```changes
section: docs
type: chore
summary: Add description of `deckhouse-controller helper change-registry` command into documentation.
```
> [docs] Add description of deckhouse-controller helper change-registry command

- dhctl/pkg/config/deckhouse_config.go
- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/kubernetes/actions/deckhouse/converge.go
- dhctl/pkg/kubernetes/actions/deckhouse/install.go
- dhctl/pkg/kubernetes/actions/manifests/manifests.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/operations/check/checker.go
- dhctl/pkg/operations/commander/attach/attacher.go
- dhctl/pkg/operations/commander/helpers.go
- dhctl/pkg/operations/converge/converger.go
- dhctl/pkg/operations/destroy/deckhouse.go
- dhctl/pkg/operations/destroy/destroy.go
Internal PR aimed only for commander-specific branch for current EA+EE version (1.60.2 at the moment).
> feat(dhctl-for-commander): add commander-uuid consistency checks and commander-uuid storing in the dh cluster

- dhctl/pkg/config/validation_rules.go
- dhctl/pkg/config/validation_rules_test.go
- make image id change prohibited
- enrich validation errors with links to docs
Improving user experience. Better validation of cluster configurations.
```changes
section: dhctl
type: feature
summary: Improve config validation error messages
```
> [dhctl] feat(dhctl-for-commander): prohibited master ng image updating, improve error texts

- modules/002-deckhouse/hooks/set-deckhouse-ready-nodes.go
- modules/002-deckhouse/hooks/set_deckhouse_ready_nodes.go
- modules/002-deckhouse/hooks/set_deckhouse_ready_nodes_test.go
- modules/002-deckhouse/templates/deployment.yaml
- Throws in a conditional for the replicas number of the Deckhouse deployment to set it to 1 if the cluster isn't bootstrapped yet.
- Adds a hook to to check if a master node has a kube-apiserver pod running and ready and label the node with `node.deckhouse.io/deckhouse-ready: true/false` label.
- Adds nodeAfinity of preferredDuringScheduling type to the deckhouse deployment so that it would prefer to be scheduled on the masters with the `node.deckhouse.io/deckhouse-ready: true` labels. 
Without checking whether the cluster is bootstrapped or not it's not safe to set the Deckhouse deployment replicas to something bigger than 1 as it may end up having multiple Deckhouse instances, running simulateneously, in the cluster.
Also, extra labels on master nodes and the dechkouse deployment's …
> [deckhouse] fix the number of replicas if cluster isn't bootstrapped and add extra labels

- modules/340-extended-monitoring/images/image-availability-exporter/Dockerfile
- modules/340-extended-monitoring/openapi/config-values.yaml
- modules/340-extended-monitoring/openapi/doc-ru-config-values.yaml
- modules/340-extended-monitoring/templates/image-availability-exporter/deployment.yaml
Added mirror support for `image_availability_exporter`.
In some cases we use mirrors in the containerd configuration, so we need to check the availability of the image through the mirrors.
```changes
type: fix
summary: Add support of mirrors for container registries for `image_availability_exporter`.
```
> Added mirror support for image_availability_exporter

- modules/002-deckhouse/templates/default-module-source.yaml
This pr fixes default module source template in terms of CA field.
Currently, CA value is rendered incorrectly in default module source.
It blocks use of private registries for storing modules.
CA values is rendered correctly, as a multi-line value (See examples below).
```changes
type: fix
summary: Fix default module source template.
```
> [deckhouse] fix default ms ca template

- docs/documentation/_data/sidebars/main.yml
- docs/documentation/modules_generate_configuration.sh
- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
- docs/documentation/pages/DECKHOUSE_CR.md
- docs/documentation/pages/DECKHOUSE_CR_RU.md
- modules/002-deckhouse/docs/CR.md
- modules/002-deckhouse/docs/CR_RU.md
The DeckhouseRelease CRD was moved in https://github.com/deckhouse/deckhouse/pull/8301 and the `deckhouse` module now has no CRDs.
Update sidebar structure and add DeckhouseRelease CRD from the `deckhouse-controller/crds` folder.
We need to fix the documentation.
`DeckhouseRelease` CRD appears on the [page](https://deckhouse.io/documentation/latest/cr.html).
```changes
section: docs
type: chore
summary: Return DeckhouseRelease CRD on the site.
```
> [docs] Return DeckhouseRelease CRD on the site

- docs/documentation/_data/deckhouse-ports.yml
Update `Configuring network policies for Deckhouse` with `registry-packages-proxy` port 5443 TCP
Added in 1.60 https://github.com/deckhouse/deckhouse/pull/7751
We need to keep this information up to date.
It is not necessary.
```changes
section: docs
type: chore
summary: Update network policies documentation.
```
> [docs] Add registry-packages-proxy port in network policies

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Added clarification about the immediate update annotation in the Deckhouse FAQ.
The documentation in its current form did not reflect the nuances of updating with this annotation.
The documentation will become more understandable for the user.
```changes
section: docs
type: chore
summary: Added clarification about the immediate update annotation in the Deckhouse FAQ.
```
> [docs] Add information about immediately updates to the Deckhouse FAQ

- docs/site/_includes/getting_started/global/partials/select_revision.html.liquid
- docs/site/js/getting-started.js
Trim license key to get valid registryDockerCfg value in the Getting Started.
If there are spaces in license token on the Installation step of the Getting Started, the registryDockerCfg value is incorrect,
```changes
section: docs
type: chore
summary: Trim license key to get valid registryDockerCfg value in the Getting Started.
```
> [docs][gs] Trim license key to get valid registryDockerCfg value

- docs/documentation/_data/supported_versions.yml
- docs/documentation/_data/version_map_addition.yml
- ee/be/candi/bashible/bundles/redos/all/003_install_mandatory_packages.sh.tpl
- ee/be/candi/bashible/detect_bundle.sh
- ee/be/candi/version_map.yml
- testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml
- testing/cloud_layouts/OpenStack/Standard/resources.yaml
- testing/cloud_layouts/Static/infra.tpl.tf
- testing/cloud_layouts/Static/redos-instance-bootstrap.sh
- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/resources.yaml
Added support for Red OS 8.0
This update ensures compatibility with the latest version of Red OS
The system should now correctly detect and install necessary packages for Red OS 8.0. 
```changes
section: candi
type: feature
summary: Added support for Red OS 8.0.
impact: Support for Red OS 8.0 ensures compatibility with the latest OS version, providing updated packages and configurations.
```
> [candi] redos 8.0 support

- .github/scripts/js/constants.js
- .github/workflow_templates/e2e.abort.multi.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
CI update to enable e2e testing with kubernetes version 1.30.
Make it possible to run e2e with kubernetes 1.30, for further testing.
```changes
section: ci
type: feature
summary: Add Kubernetes 1.30 e2e tests.
```
> [ci] add k8s 1.30 e2e pipelines

- modules/110-istio/openapi/config-values.yaml
Add the globalVersion and additionalVersions ModuleConfig options validations.
It's easy to make a mistake in ModuleConfig, and it's hard to figure out if there is a problem.
```changes
section: istio
type:  chore
summary: Added the globalVersion and additionalVersions ModuleConfig options validations.
```
> [istio] Add globalVersion and additionalVersions mc options validations

- ee/fe/modules/340-monitoring-applications/applications/rabbitmq/prometheus-rules/rabbitmq.yaml
Change severity of RabbitMQ alerts from 3 to 4.
```changes
type: chore
summary: Change severity of RabbitMQ alerts from 3 to 4.
```
> [monitoring-applications] Update rabbitmq alerts severity

- deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go
- modules/030-cloud-provider-yandex/hooks/alert_on_deprecated_availability_zone.go
- modules/030-cloud-provider-yandex/hooks/alert_on_deprecated_availability_zone_test.go
- modules/030-cloud-provider-yandex/hooks/deprecated_zone_in_cluster_configuration.go
- modules/030-cloud-provider-yandex/hooks/deprecated_zone_in_cluster_configuration_test.go
- modules/030-cloud-provider-yandex/requirements/check.go
- modules/030-cloud-provider-yandex/requirements/check_test.go
Add requirements for deprecated zone removal in the next release.
We want to remove deprecated zone from candi (terraform) and configs in the next release. We need to check if cluster is ready for this.
#7781 
We don't.
```changes
type: feature
summary: Add requirements for deprecated zone removal in the next release. 
```
> [cloud-provider-yandex] Add requirements for deprecated zone removal in the next release

- modules/000-common/images/kubernetes/patches/kube-scheduler/1.27/01-kube-scheduler-fix-int-divide-by-zero.patch
- modules/000-common/images/kubernetes/patches/kube-scheduler/README.md
Fixed a bug in the scheduler (version 1.27.14) where it would crash when prefilter returns a non-existent node.
Cherry pick of https://github.com/kubernetes/kubernetes/pull/124933
Scheduler fix for the current default version of k8s(1.27.14).
```changes
type: fix
summary: Fixed a bug in the scheduler (version 1.27.14) where it would crash when prefilter returns a non-existent node.
```
> [common] add patch for kube-scheduller 1.27.14

- docs/documentation/_data/i18n.yml
- docs/site/_data/i18n.yaml
- docs/site/backends/docs-builder-template/i18n/en.yaml
- docs/site/backends/docs-builder-template/i18n/ru.yaml
- docs/site/backends/docs-builder-template/layouts/_default/single.html
- docs/site/backends/docs-builder-template/layouts/partials/alert.html
- docs/site/backends/docs-builder-template/layouts/partials/sidebar.html
Updates for module status:
- Updated i18n strings for module statuses.
- Changed or added messages for 'experimental', 'preview' (new), and 'deprecated' (new) statuses.
- Enhanced alerts to support dynamic module status messages.
- Modified sidebar to display status badges with tooltips for better user experience.
- Improved HTML templates to handle different module statuses more efficiently.
To set a status to a module use the `moduleStatus` parameter in the front matter of the README file.
An example (set the preview status to the docs-example module):
```
---
title: "Module docs-example"
description: Module for testing docs render
summary: This is a summary of the docs-example module.
moduleStatus: preview
---
```
```changes
section: docs
type: chore
summary: Updates for module status. …
```
> [docs][modules] Updates for module status

- candi/cloud-providers/yandex/terraform-modules/master-node/variables.tf
- candi/cloud-providers/yandex/terraform-modules/static-node/variables.tf
- modules/030-cloud-provider-yandex/hooks/migrate_disk_gb_size_before_changing_default.go
- modules/030-cloud-provider-yandex/hooks/migrate_disk_gb_size_before_changing_default_test.go
- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
Change defaults in terraform.
Add migration for adding old default disk size (20 GB) to provider cluster configuration to prevent terraform state changing.
Remove diskSizeGB from e2e tests.
Difference between documentation and real value in cluster.
```changes
type: fix
summary: Change default root disk size for master and cloud permanent nodes to 50 GB
```
> [cloud-provider-yandex]  Change default root disk size for master and cloud permanent nodes to 50 GB

- testing/cloud_layouts/script.sh
Change the tinyproxy image in e2e-static.
Sometimes the proxy stops responding to requests, causing errors when running e2e tests. The latest version fixes many bugs, which should increase the stability of passing tests.
Successful completion of e2e static.
```changes
type: chore
summary: Changing the tinyproxy image to e2e-static.
```
> [testing] change tinyproxy image for e2e static

- dhctl/cmd/dhctl/commands/ssh.go
- dhctl/pkg/operations/bootstrap/steps.go
- dhctl/pkg/preflight/domain.go
- dhctl/pkg/preflight/ports.go
- dhctl/pkg/system/ssh/frontend/upload-script.go
- dhctl/pkg/terraform/pipeline.go
- dhctl/pkg/terraform/runner.go
- dhctl/pkg/util/tomb/tomb_test.go
Use the `errors.As` function to handle errors.
An error can be wrapped in another error, and we need to unwrap it to get the original error. The `errors.As` function helps us to do that. It unwraps the error and checks if it is of the specified type.
Close #8356.
```changes
section: dhctl
type: fix
summary: Fix incorrect error handling.
```
> [dhctl] Use the `errors.As` function to handle errors

- dhctl/cmd/dhctl/main.go
- dhctl/pkg/log/logger.go
Debug tee logger needs WriteCloser interface instead of path name.
Need for implement debug logs in deckhouse-commander.
```changes
section: dhctl
type: chore
summary: Change interface for tee debug logger
```
> [dhctl] Change interface for tee debug logger

- dhctl/cmd/dhctl/commands/terraform.go
- dhctl/go.mod
- dhctl/pkg/kubernetes/actions/converge/check.go
- dhctl/pkg/kubernetes/actions/converge/check_test.go
Hide raw terraform plan and destructive changes from check result in CLI. It was added by mistake.
Improved user experience, more readable Check operation output.
```changes
section: dhctl
type: fix
summary: Hide raw terraform plan and destructive changes from check result
```
> [dhctl] Remove terraform plan and destructive changes from check output

- dhctl/pkg/operations/bootstrap/steps.go
Fixed bootstrap on systems with umask 027/077
```changes
section: dhctl
type: fix
summary: Fixed bootstrap on systems with umask 027/077
```
> [dhctl] Fix bootstrap on systems with umask 027/077

- modules/340-monitoring-kubernetes/templates/kube-state-metrics/deployment.yaml
Add configmap labels assembly
We need to get configmaps labels for alerting
We need it for proper alerting
Configmaps labels assembly
```changes
type: feature
summary: Add configmap labels assembly
```
> [monitoring] Add configmap labels assembly

- modules/402-ingress-nginx/images/kruise/patches/add-pdb.patch
The step of the logic where kruise controller checks if a pod should continue running on the node has been slightly updated so that the controller adds [default daemonset tolerations](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations) (two of which have "NoExecute" effect) when calculating the resulting set of the pod's tolerations.
Currently, kruise controller deschedules ingress nginx pods from a node that becomes not-ready because of "NoExecute" taints. It happens because kruise's logic of checking if a pod should run on a particular node doesn't take into account default daemonset tolerations. While it could make sense in some other environments, having ingress nginx pods descheduled even from not-ready nodes is highly undesirable.
Closes …
> [ingress-nginx] fix pod descheduling from a not-ready node

- modules/402-ingress-nginx/images/controller-1-10/patches/nginx-tmpl.patch
- modules/402-ingress-nginx/images/controller-1-10/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-1-6/patches/nginx-tmpl.patch
- modules/402-ingress-nginx/images/controller-1-6/rootfs/etc/nginx/lua/pbmetrics.lua
- modules/402-ingress-nginx/images/controller-1-9/patches/nginx-tmpl.patch
- modules/402-ingress-nginx/images/controller-1-9/rootfs/etc/nginx/lua/pbmetrics.lua
It provides fix for ingress-nginx to avoid crashes when using custom logs formats without our fields(e.g. formatted_status).
When a client uses custom logs formats without our fields, they cause error in lua code.
No crashes when using custom logs formats without our fields.
```changes
type: fix
summary: fix usage custom logs formats without our fields
```
> [ingress-nginx] fix usage custom logs formats without our fields

- candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
- modules/040-node-manager/hooks/clear_nodeuser_errors.go
- modules/040-node-manager/templates/bashible/rbac-for-us.yaml
Fix RBAC permissions and startup schedule cleanup of NodeUser creation errors.
Fixing errors at bootstrap node for fast up a node
Affected customer
```changes
type: fix
summary: Fix RBAC permissions and startup schedule cleanup of NodeUser creation errors.
```
> [node-manager] fix add nodeuser

- testing/matrix/linter/rules/rules.go
> [testing] A linter for checking the hostNetwork ports range

- ee/se/modules/380-metallb/monitoring/prometheus-rules/metallb.yaml
Metallb alert group naming fix.
Fix error like:
`ERROR: #<EventsSeries::AnnotationsService::BadAnnotations: Usage of current alert's trigger (D8MetalLBConfigStale) is forbidden in grouping to prevent circular dependencies!>`
```changes
section: 380-metallb
type: chore
summary: Metallb alert group naming fix
```
> [metallb] Metallb alert group naming fix

- .github/workflow_templates/trivy-db-schedule.yml
- .github/workflows/trivy-db-schedule.yml
Not only do we copy java-db image from ghcr to our registries but we also slightly update its manifest so that it fits in Yandex Container Registry.
YandexCR has some OCI-compliance issues and original java-db image can't be uploaded due to some dets of its manifest.
There is no issues uploading java-db image from our registries to any other registry, including YandexCR.
```changes
section: operator-trivt
type: chore
summary: Update Java-db image manifest.
```
> [operator-trivy] update javadb mediaType

- dhctl/cmd/dhctl/commands/mirror.go
- dhctl/cmd/dhctl/commands/mirror_modules.go
Added a message to inform dhctl mirror users of it's deprecation
We moved all mirroring functions to d8-cli, `dhctl mirror` this is no longer supported
```changes
section: dhctl
type: chore
summary: dhctl mirror is deprecated in favour of Deckhouse CLI.
impact: dhctl mirror is deprecated. All mirroring-related functionality has been moved into the Deckhouse CLI and will be completely removed from dhctl in Deckhouse Kubernetes Platform v1.64.
```
> [dhctl] add mirror deprecation notice

- modules/110-istio/requirements/check.go
Fixing istio module release requirements checker.
Even though the module is turned off, the checker runs and throw the error:
```
"k8s" requirement for DeckhouseRelease "1.61.0" not met: istio:minimalVersion key is not registred.
```
It blocks deckhouse upgrades.
```changes
section: istio
type: fix
summary: Fixed istio module release requirements checker.
```
> [istio] release requirements checker fix

- modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
We miss `severity_level` for this rule, there may be errors in clients alertmanagers.
All rules should have `severity_level`.
```changes
type: fix
summary: Add missing `severity_level` for NginxIngressConfigTestFailed rule
```
> [ingress-nginx] Add missing severity_level for rule

- docs/documentation/_data/sidebars/main.yml
Mark the descheduler module as experimental
```changes
section: docs
type: chore
summary: Mark the descheduler module as experimental.
```
> [docs] Mark the descheduler module as experimental

- candi/cloud-providers/yandex/bashible/bundles/ubuntu-lts/bootstrap-networks.sh.tpl
- modules/007-registrypackages/images/iptables/scripts/install
Fix bootstrap steps with static binaries.
1.  Replacing d8-curl on python, because `bootstrap-networks.sh.tpl` step is running before d8-binaries are available on the node.
2. We should use xtables-legacy-multi for OS with kernel version older then 3.14.
Succesful bootstrap.
```changes
section: candi
type: fix
summary: Fix bootstrap steps with static binaries.
impact: low
```
```changes
type: fix
summary: Fix install binary iptables for OS with kernel older then 3.14.
impact: low
```
> [candi] fix bootstrap with static binaries

- candi/control-plane-kubeadm/config.yaml.tpl
Added specification for the --service-account-jwks-uri flag in kubernetes-apiserver when a public domain is available. This flag is crucial as it allows the API server to validate JWT tokens authentically issued by the service account token issuer, using the public keys hosted at the provided URI.
It makes it possible for external systems, e.g., cloud auth systems to validate kubernetes tokens signatures
Execute `kubectl get --raw /.well-known/openid-configuration | jq` in the cluster. Without changes from the PR, the response will be:
```json
{
"issuer": "https://kubernetes.default.svc.cluster.local",
"jwks_uri": "https://192.168.199.22:6443/openid/v1/jwks",
"response_types_supported": [
"id_token"
],
"subject_types_supported": [
"public"
],
"id_token_signing_alg_values_supported": [ …
```
> [control-plane-manager] Specify service-account-jwks-uri

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
Change secondary-repo flag to cache repo.
After discussion with the werf developers, came to the conclusion that this is the more appropriate option to use.
```changes
section: ci
type: feature
summary: Change secondary repo flag to cache repo (werf).
```
> [ci] Change secondary-repo flag to cache repo

- modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/deprecated-resources.json
A variable was missing in the Kubernetes Cluster/Deprecated APIs dashboard.
Without the variable the dashboard wasn't working. This commit fixes that
```changes
type: fix
summary: Add missing datasource variable to deprecated-apis dashboard
```
> Add missing variable to deprecated-apis dashboard

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- testing/matrix/linter/controller.go
Run build tasks closer to the registry. Reduce matrix test cpu usage.
```changes
section: ci
type: feature
summary: Run build tasks closer to the registry. Reduce matrix test cpu usage
```
> [ci] Run build tasks closer to the registry. Reduce matrix test cpu usage

- modules/040-node-manager/monitoring/prometheus-rules/cloud-data-discovery.tpl
Re-enable ClusterHasOrphanedDisks alert for yandex.
Related to #8224.
```changes
type: feature
summary: Re-enable ClusterHasOrphanedDisks alert for yandex.
```
> [node-manager] Re-enable ClusterHasOrphanedDisks alert for yandex

- candi/bashible/common-steps/all/003_disable_swap.sh.tpl
Disable `systemd-gpt-auto-generator`, which automatically detects swap partition in GPT  and activates it.
If system has a swap partition in the GUID Partition Table, systemd-gpt-auto-generator will automatically enable swap after finishing `003_disable_swap.sh.tpl` and rebooting. 
Closes #8644 
Successful bootstrap cluster.
```changes
section: candi
type: fix
summary: Disable `systemd-gpt-auto-generator`, which automatically detects swap partition in GPT and activates it.
```
> [candi] Disable systemd-gpt-auto-generator 

- modules/460-log-shipper/images/vector/reloader/main.go
Delete lock files before sending a signal to vector to update the configuration
At startup sometimes there is an error that the lock file already exists
```
2024-06-19T13:58:12.622408Z ERROR vector::topology: Configuration error. error=Sink "destination/cluster/xxxx": error occurred when building buffer: failed to build individual stage 0: failed to load/create ledger: failed to lock buffer.lock; is another Vector process running and using this buffer?
```
```changes
type: fix
summary: Delete lock files before sending a signal to vector to update the configuration
```
> [log-shipper]  Delete lock files before sending a signal to vector to update the configuration

- candi/bashible/common-steps/node-group/002_create_static_node_cleanup_script.sh.tpl
Clean up units created by registry packages install scripts.
We forgot to delete them.
```changes
section: candi
type: fix
summary: Clean up units created by registry packages install scripts.
```
> [candi] Clean up rp units

- ee/modules/160-multitenancy-manager/templates/user-resources/_helpers.tpl
- ee/modules/160-multitenancy-manager/templates/user-resources/default-project-template.yaml
- ee/modules/160-multitenancy-manager/templates/user-resources/secure-project-template.yaml
- ee/modules/160-multitenancy-manager/templates/user-resources/secure-with-dedicated-nodes-project-template.yaml
- ee/modules/160-multitenancy-manager/templates/user-resources/templates/_helpers.tpl
- ee/modules/160-multitenancy-manager/templates/user-resources/templates/user-resources-templates.yaml
When describing the project, we fill in the block of authorisation rules.
In the authorisation rules template, the variable user.name used twice:
- in the name of the rule
- in the user name
Email can and often is used in the username. But we cannot use the special characters in the rule name due to restrictions on the part of k8s.
Now, when using a template, if the user's email is used in the username, we get a template generation error.
As a result, the necessary users are not created.
We are replacing the special characters with `-` in the rule name. And as a result, the template is generated and the necessary users are created.
```changes
type: fix
summary: replace special characters in a AuthorizationRule metadata.name
```
> [multitenancy-manager] fix: replace special characters in metadata.name

- dhctl/pkg/operations/bootstrap/steps.go
- dhctl/pkg/operations/bootstrap/steps_test.go
- modules/039-registry-packages-proxy/images/registry-packages-proxy/src/internal/credentials/secret.go
- modules/039-registry-packages-proxy/images/registry-packages-proxy/src/internal/credentials/secret_test.go
Fix working with registries on non-standard ports.
Due to wrong calculate a path to registry with non-standard port in url, registry-packages-proxy cannot work with this registries, affecting new installs and upgrade.
Symthoms:
```
bashible.sh[164163]: Failed to execute step /var/lib/bashible/bundle_steps/062_install_kubelet_and_his_friends.sh ... retry in 10 seconds.
bashible.sh[164163]: ===
bashible.sh[164163]: === Step: /var/lib/bashible/bundle_steps/062_install_kubelet_and_his_friends.sh
bashible.sh[164163]: ===
bashible.sh[164163]: error: error parsing STDIN: error converting YAML to JSON: yaml: line 9: did not find expected key
...
bashible.sh[164163]: bb-package [INFO] Fetching packages: d8
bashible.sh[164163]: ++ trap 'bb-log-error "Failed to fetch packages"' ERR …
```
> [core] fix working with registries on non-standard ports

- modules/402-ingress-nginx/templates/controller/controller.yaml
Restore hostPort for https port in HostPortWithProxyProtocol inlet
We have missed this values during the http/3 implementation
HostPortWithProxyProtocol inlet is broken
```changes
type: fix 
summary: Fix HostPortWithProxyProtocol inlet.
```
> [ingress-nginx] Fix hostPortWithProxyProtocol inlet

- modules/150-user-authn/hooks/delete_crowd_basic_auth_proxy.go
- modules/150-user-authn/hooks/delete_crowd_basic_auth_proxy_test.go
It provides fix for crowd-basic-auth-proxy to avoid ingress problems during migration to basic-auth-proxy
It helps to avoid migration problems. We have renamed the crowd-basic-auth-proxy ingress, and it causes conflicts during migration from crowd-basic-auth-proxy to basic-auth-proxy.
```
Queue 'main': length 43, status: 'run first task'
1. ModuleRun:main:user-authn:doStartup:OperatorStartup:failures 3:helm upgrade failed: failed to create resource: admission webhook "main.validate.d8-ingress-nginx-deckhouse" denied the request: host "api.dev.hf.flant.com" and path "/basic-auth(\/?)(.*)" is already defined in ingress d8-user-authn/crowd-basic-auth-proxy
```
To avoid migration problems.
Succeful migration from crowd-auth-basic-proxy(v1.60) to basic-auth-proxy(v1.61)
```changes
section: …
```
> [user-authn] fix crowd basic auth proxy migration

- modules/402-ingress-nginx/images/controller-1-10/patches/add-http3.patch
- modules/402-ingress-nginx/images/controller-1-10/patches/nginx-build.patch
It provides updates for ingress-nginx, it bumps version of nginx to 1.25.5.
Ingress-controller 1.10 has nginx 1.25.5
```
bash-4.4$ nginx -v
nginx version: nginx/1.25.5
```
```changes
type: feature 
summary: bump nginx to 1.25.5
```
> [ingress-nginx] bump nginx to 1.25.5

- global-hooks/discovery/modules_images_tags.go
- global-hooks/discovery/modules_images_tags_test.go
- global-hooks/discovery/testdata/modules-images-tags/external-modules-source/998-double/images_digests.json
- global-hooks/discovery/testdata/modules-images-tags/external-modules/998-double
This PR updates `modules_images_tags` discovery hook's logic so that if there are two modules in the cluster with the same name, images tags of first one (supposedly, an embedded module) will make their way into resulting images_digests.json file.
Closes #8480 
We need it because in opposite case images digests of an embedded module get overwritten with values of its namesake sourced module.
Embedded modules have priority in terms of charts and images digests over source modules.
```changes
type: chore
summary: Fix overwriting embedded modules' images tags.
```
> [deckhouse] fix overwriting embedded modules' images tags

- global-hooks/discovery/cluster_domain.go
- global-hooks/discovery/cluster_domain_test.go
If the domain field is filled in in the cluster configuration, we need to use it in the work of the hook to determine the domain name.
Sometimes it can be quite difficult to determine a domain name based on dynamic variables. And if the cluster configuration is defined, we just use it.
If the domain name is defined in the cluster configuration, it will be used in the `global.discovery.clusterDomain` field.
```changes
type: feature
summary: set clusterDomain from global.clusterConfiguration.clusterDomain
```
> [deckhouse] feat: set clusterDomain from global.clusterConfiguration.clusterDomain

- modules/002-deckhouse/template_tests/module_test.go
- modules/002-deckhouse/templates/validation.yaml
We need to prohibit the creation of namespaces with names that begin with `kube-` and `d8-`
Only the deckhouse system user should be able to do this
Regular users, including the administrator, should not be able to create system namespaces so as not to affect important settings.
Any user, with the exception of deckhouse, should receive an error for such an attempt when trying to create a namespace whose name begins with `d8-` or `kube-`.
```changes
type: feature
summary: restrict creating system namespaces
```
> [deckhouse] feat: restrict creating system namespaces

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/ebpf-exporter.yaml
Precomputed `oom_kills:normalized` contains more results than the original `ebpf_exporter_oom_kills`
You can see it in the screenshots:
There were 2 problems:
1. metric `ebpf_exporter_oom_kills` was filtered using the wrong regexp `.*slice.*` in cgroup_path label (probably copied from previous prometheus rule). Then cgroup_path was parsed to get `raw_container_id` but since it's not in the expected format parsing has always given `raw_container_id=""`.
2. `kube_pod_container_info` sometimes doesn't have `container_id` label. The label is sometimes not there briefly after container creation (for 1 probe).
As a result, 2 metrics were merged by an empty raw_container_id label giving false-positive results. Basically, for every `kube_pod_container_info` metric without the `container_id` label …
> Fix oom_kills:normalized metric for cgroup_path with cri-containerd in name

- testing/cloud_layouts/script_eks.sh
During e2e tests, AWS secrets are displayed in our logs. We are making a correction as part of this request.
It is enough to look at the logs of running e2e tests to see the user’s credentials in aws. This data can be used for your own purposes. Including the evil ones.
A data leak entails both financial losses and can lead to loss of reputation.
Credentials are no longer present in e2e test launch logs.
```changes
type: fix
summary: do not reveal aws secrets in logs
```
> [deckhouse-controller][e2e] do not reveal secrets in logs

- ee/candi/cloud-providers/vsphere/bashible/bundles/altlinux/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/vsphere/bashible/bundles/astra/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/vsphere/bashible/bundles/debian/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/vsphere/bashible/bundles/ubuntu-lts/bootstrap-networks.sh.tpl
Updated `bootstrap-network` script to determine the primary network interface from the `50-cloud-init.yaml` file. If the file does not contain a MAC address, the script will extract the interface name using a regular expression.
`50-cloud-init.yaml` file sometimes does not contain a MAC address
The primary network interface will be correctly identified and configured even if the `50-cloud-init.yaml` file does not contain a MAC address. 
```changes
section: candi
type: fix
summary: Updated  `bootstrap-network` script to determine the primary network interface from the `50-cloud-init.yaml` file, with fallback to regex matching if MAC address is missing.
impact: Ensures correct network interface identification and configuration in all scenarios. …
```
> [cloud-provider-vsphere] net-bootstap fix

- modules/030-cloud-provider-yandex/images/yandex-csi-plugin/werf.inc.yaml
Update csi driver to disable root reservation.
More info in https://github.com/deckhouse/yandex-csi-driver/pull/20.
We don't
```changes
type: feature
summary: Update csi driver to disable root reservation.
```
> [cloud-provider-yandex] Update csi driver to disable root reservation

- .github/CODEOWNERS
Add the observability team to CODEOWNERS for monitoring modules
```changes
section: ci
type: chore
summary: 
impact: Update owners for  monitoring modules
```
> Add the observability team to CODEOWNERS for monitoring modules

- modules/300-prometheus/templates/grafana/authenticator-v10.yaml
- modules/300-prometheus/templates/grafana/certificate.yaml
- modules/300-prometheus/templates/grafana/ingress-v10.yaml
- modules/300-prometheus/templates/grafana/ingress.yaml
Fix copying of Grafana v10 custom certificate
Closes #8756 
Custom certificate is added for Grafana v10 ingress when https global module mode is CustomCertificate
```changes
type: fix
summary: Fix copying of Grafana v10 custom certificate
```
> [prometheus] Fix copying of Grafana v10 custom certificate

- ee/candi/cloud-providers/vsphere/terraform-modules/master-node/main.tf
- ee/candi/cloud-providers/vsphere/terraform-modules/master-node/variables.tf
- ee/candi/cloud-providers/vsphere/terraform-modules/static-node/main.tf
- ee/candi/cloud-providers/vsphere/terraform-modules/static-node/variables.tf
This pull request changes the default behavior of the vSphere provider by setting `wait_for_guest_net_routable` to `false`. This means that Terraform will no longer wait for the VM's network to become routable by default.
In some scenarios, virtual machines (VMs) may be launched in environments without a default gateway. This situation, although rare, can occur in isolated environments where a default route is not provided, and access to repositories and other resources is either within the network or through a proxy. Our current Terraform configuration does the following:
1. Launches the VM.
2. Waits for the VM to have the "guest.net" and "guest.ipStack" properties.
3. Waits for a default route to appear in "guest.IpRouteConfig".
If a default …
> Disable wait for guest network routable by default in vSphere Provider

- dhctl/pkg/preflight/registry.go
Change GetImage flag to true in registry availability preflight check to true for getting correct dhctl version
Cluster cannot be bootstrapped.
Cluster cannot be bootstrapped.
```changes
section: dhctl
type: fix
summary: Fix bootstrap cluster.
```
> [dhctl] Fix bootstrap cluster

- modules/300-prometheus/images/grafana-v10/grafana_home_dashboard.json
- modules/300-prometheus/templates/grafana/servicemonitor-v10.yaml
Grafana v10 metrics should be exposed
Currently it takes at least to have `grafana_build_info` exposed to show the actual version of Grafana on home dashboard
Closes #8724 
Grafana v10 metrics are exposed and home dashboard for Grafana v10 contains the actual value for installed version
```changes
type: fix
summary: Expose Grafana v10 metrics
```
> [prometheus] Expose Grafana v10 metrics

- deckhouse-controller/pkg/debug/debug.go
Hide cloud-providers/registry credentials and client certificates in debug output.
We don't want to expose sensitive data in debug output.
We don't.
```changes
type: feature
summary: Hide some sensitive data in debug output.
```
> [deckhouse-controller] Hide some sensitive data in debug output

- modules/030-cloud-provider-yandex/images/cloud-data-discoverer/discoverer.go
Fix typo in label key in discoverer.
Also remove the disk description filter, because that was a workaround until the `cluster_uuid` label came up.
We set label in snake_case, not in camelCase:
https://github.com/deckhouse/yandex-csi-driver/pull/19/files#diff-7b46685eeb2e24ed466c2d8f7c64f093cafa2b24e858407b1431c4d9e1576b47R176
Now it doesn't work.
```changes
type: fix
summary: Fix typo in label key in discoverer.
```
> [cloud-provider-yandex] Fix typo in label key in discoverer

- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/terraform-modules/master-node/main.tf
- candi/cloud-providers/yandex/terraform-modules/static-node/main.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/main.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf
- candi/cloud-providers/yandex/terraform-modules/vpc-components/outputs.tf
- release.yaml
Remove deprecated `ru-central1-c` zone from terraform.
Closes #7781.
```changes
section: candi
type: feature
summary: Remove deprecated `ru-central1-c` zone from terraform.
impact: Yandex.Cloud `ru-central1-c` zone has been removed from terraform. If you use `ru-central1-c` zone in Yandex.Cloud, you need to manually run converge to remove subnets from the cloud.
```
> [candi][cloud-provider-yandex] Remove ru-central1-c zone from terraform

- candi/bashible/common-steps/node-group/004_integrate_kubernetes_data_device.sh.tpl
- ee/candi/cloud-providers/openstack/layouts/simple-with-internal-network/master-node/main.tf
- ee/candi/cloud-providers/openstack/layouts/simple-with-internal-network/variables.tf
- ee/candi/cloud-providers/openstack/openapi/cloud_discovery_data.yaml
- ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/openapi/doc-ru-cluster_configuration.yaml
- ee/modules/030-cloud-provider-openstack/cloud-instance-manager/machine-class.yaml
- ee/modules/030-cloud-provider-openstack/hooks/internal/v1/provider_cluster_configuration.go
- ee/modules/030-cloud-provider-openstack/hooks/openstack_cluster_configuration.go
- ee/modules/030-cloud-provider-openstack/hooks/openstack_cluster_configuration_test.go
- ee/modules/030-cloud-provider-openstack/openapi/values.yaml
- ee/modules/030-cloud-provider-openstack/templates/registration.yaml
Add ConfigDrive support for mcm and SimpleWithInternalNetwork layout
Closes #3060.
```changes
type: feature
summary: Add support for the `ConfigDrive` parameter in mcm and `SimpleWithInternalNetwork` layout.
```
> [cloud-provider-openstack] Add ConfigDrive support for mcm and SimpleWithInternalNetwork layout

- ee/modules/160-multitenancy-manager/templates/validating.yaml
- modules/002-deckhouse/template_tests/module_test.go
- modules/002-deckhouse/templates/validation.yaml
Ignore kubernetes system accounts for changing/creating objects with `heritage: deckhouse` label
This Policy can block kube-controller-manager or kubelet requests
```changes
type: fix
summary: Fix ValidatingAdmissionPolicy for objects with the label `heritage: deckhouse`.
```
> [deckhouse] patch ValidatingAdmissionPolicy to ignore kubernetes system changes

- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
It contains a fix for the correct caps-controller-manager log in.
Changing the owner of the caps user's home directory so that the caps-controller-manager can log in without errors
When adding a key with the command echo `$KEY >> /home/caps/.ssh/authorized_keys` without changing the owner of the caps home directory, caps-controller-manager shows a failure in the logs:
```
.x-k8s.io" controllerKind="StaticMachine" StaticMachine="d8-cloud-instance-manager/worker-vv8qc" namespace="d8-cloud-instance-manager" name="worker-vv8qc" reconcileID="ccf86311-ae9e-4993-b802-f97da13b6eff" line=38 output="ssh: caps@158.160.121.206: Permission denied (publickey)."
E0514 11:03:58.349054       1 bootstrap.go:144] "Failed to bootstrap StaticInstance: failed to exec ssh command" err="failed to run ssh …
```
> [docs][gs] Change the owner of the home directory in bare metal installation

- docs/documentation/_data/sidebars/main.yml
Add the FAQ section to the side menu for the _chrony_ module.
```changes
section: docs
type: fix
summary: Add the FAQ section to the side menu for the chrony module.
```
> [docs] Add FAQ to chrony section in sidebar

- modules/002-deckhouse/templates/validation.yaml
Fix ValidatingAdmissionPolicy
kubernetes scheduler didn't have permission to interact with pvc with deckhouse labels
```changes
type: fix
summary: Clarify ValidatingAdmissionPolicy for objects with label `heritage: deckhouse`.
```
> [deckhouse] Fix heritage deckhouse Admission policy

- modules/300-prometheus/docs/FAQ.md
- modules/300-prometheus/docs/FAQ_RU.md
- modules/300-prometheus/templates/prometheus/prometheus.yaml
System-independent Probes
Closes #8777 
Probes must be system-independent and searched by applying label value:
```yaml
prometheus.deckhouse.io/probe-watcher-enabled: "true"
```
to the namespace containing required probes
```changes
type: feature
summary: System-independent Probes.
```
> [prometheus] System-independent Probes 

- ee/modules/450-network-gateway/openapi/config-values.yaml
- ee/modules/450-network-gateway/openapi/doc-ru-config-values.yaml
- ee/se/modules/502-delivery/openapi/config-values.yaml
- ee/se/modules/502-delivery/openapi/doc-ru-config-values.yaml
- modules/300-prometheus/openapi/config-values.yaml
- modules/300-prometheus/openapi/doc-ru-config-values.yaml
- modules/462-loki/openapi/config-values.yaml
- modules/462-loki/openapi/doc-ru-config-values.yaml
- modules/500-upmeter/openapi/config-values.yaml
- modules/500-upmeter/openapi/doc-ru-config-values.yaml
Added notes in modules' configuration docs that reflect that changing default storageclass in cluster won't affect current volumes until re-enabling a module.
We should reflect in the docs how modules behave when the cluster default storageClass is changed.
```changes
section: docs
type: chore
summary: Minor documentation update.
```
> [docs] Reflect module behaviour when changing default SC

- ee/candi/cloud-providers/openstack/openapi/instance_class.yaml
Fixed examples of filling objects for the "OpenStack: Custom Resources" page.  
The arrays were displayed as multiple single lines:  
- [additionalnetworks](https://deckhouse.io/documentation/v1/modules/030-cloud-provider-openstack/cr.html#openstackinstanceclass-v1-spec-additionalnetworks)
- [additionalsecuritygroups](https://deckhouse.io/documentation/v1/modules/030-cloud-provider-openstack/cr.html#openstackinstanceclass-v1-spec-additionalsecuritygroups)
The improvement will help clients fill in the module parameters correctly
Improve the quality of documentation
```changes
section: docs
type: fix 
summary: Fixed objects examples on page "Cloud provider — OpenStack"
```
> [docs] Improvements in Cloud provider — OpenStack. Fixed objects examples

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
This PR will add information and command to access Deckhouse controller in HA mode.
```changes
section: docs
type: fix
summary: Add information and command to access Deckhouse controller in HA mode.
> [docs] Add information and command to access Deckhouse controller in HA mode 

- docs/site/_includes/getting_started/openstack_vk/partials/config.ru.yml.standard.ee.inc
- docs/site/_includes/getting_started/openstack_vk/partials/config.yml.standard.ee.inc
- docs/site/_includes/getting_started/openstack_vk/partials/resources.yml.minimal.inc
Fix default image, because `Ubuntu-22.04-202208` was removed.
Add mc to fix problem that PVC does not create with error
```
Warning  ProvisioningFailed    9m24s (x15 over 37m)  cinder.csi.openstack.org_test-metallb-master-0_12a4fb37-e11d-4405-910d-c70659134e9f  failed to provision volume with StorageClass "ceph-hdd": rpc error: code = Internal desc = Failed to get volumes: Expected HTTP response code [200 204 300] when accessing [GET https://public.infra.mail.ru:8776/v3/bbf506e3ece54e21b2acf1bf9db4f62c/volumes/detail?name=pvc-c3374e05-ac6b-4d76-8874-e79999e0ec7d], but got 406 instead
{"computeFault": {"message": "Version 3.34 is not supported by the API. Minimum is 3.0 and maximum is 3.27.", "code": 406}}
```
Improve Getting Started
```changes
section: docs
type: chore …
```
> [docs] Improvements in Getting Started for install in VK Cloud

- ee/candi/cloud-providers/vsphere/layouts/standard/base-infrastructure/main.tf
- ee/candi/cloud-providers/vsphere/openapi/cluster_configuration.yaml
Fixed bootstrap to existing folder.
Tested in l* and selectel.
```changes
type: fix
summary: Fix bootstrap to existing folder.
```
> [cloud-provider-vsphere] Fix bootstrap to existing folder

- testing/matrix/linter/rules/roles/wildcards.go
- testing/matrix/linter/rules/rules.go
It is necessary to check for the presence of wildcards in Roles and ClusterRoles in the rbac-for-us.yaml files.
Kubernetes CIS [we recommend not using wildcard rights in Role/ClusterRole](https://github.com/aquasecurity/kube-bench/blob/0f8dfaf1156652b556c913aa8e78fccbb1dfd186/cfg/rke-cis-1.24/policies.yaml#L29-L35).
With each commit, template files are checked for the presence of wildcards. If no exception rule has been added, a validation error is generated.
```changes
type: feature
summary: matrix tests to check roles for wildcards
```
Closed #8517
> [testing] feat: matrix tests to check roles for wildcards

- modules/002-deckhouse/templates/webhook-handler/rbac-for-us.yaml
- modules/015-admission-policy-engine/templates/rbac-for-us.yaml
- testing/matrix/linter/rules/roles/wildcards.go
Add comments for wildcard rbac permissions
Setting a wildcard for Role/ClusterRole is potentially dangerous. We have to review them and 
```changes
type: chore
summary: Add comments for wildcard rbac permissions.
```
```changes
type: chore
summary: Add comments for wildcard rbac permissions.
```
> [global] rbac fix

- deckhouse-controller/files/kubectl_wrapper.sh
Fixed wrong kubectl version hardcoded into kubectl_wrapper.sh
This fixes kubectl executions within spare deckhouse pods
```changes
type: fix
summary: fix kubectl version detection in kubectl_wrapper.sh
```
> [deckhouse-controller] fix kubectl version detection in kubectl_wrapper.sh

- modules/021-cni-cilium/monitoring/prometheus-rules/agent.yaml
Fix typo in the CiliumAgentUnreachableHealthEndpoints alert.
```changes
section: 021-cni-cilium
type: chore
summary: Fix typo in the CiliumAgentUnreachableHealthEndpoints alert.
```
> [cni-cilium] Orthographic mistake in alert

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_release.yml
- werf-giterminism.yaml
- werf.yaml
When we build final images to prod registry we do not need werf git cleanup meta tags in registry.
This PR disables pushing of the werf meta tags to prod registry.
```changes
section: ci
type: chore 
summary: do not push meta tags to prod registry on build phase
```
> [build] do not push meta tags to prod registry on build phase

- candi/cloud-providers/aws/bashible/common-steps/node-group/001_create_nvme_ebs_aliases.sh.tpl
- modules/040-terraform-manager/images/base-terraform-manager/werf.inc.yaml
- testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/script.sh
Use centos 9 stream image in aws e2e because centos 7 end of life is June 30. 
Centos 7 end of life is June 30. 
```changes
type: fix
summary: Use centos 9 stream image in aws e2e. 
```
```changes
type: fix
summary: Rebuild with dev base-image. 
```
```changes
section: candi
type: fix
summary: Fix 001_create_nvme_ebs_aliases.sh step for cases without requirements symlinks.
```
> [testing] set centos 9 stream for aws

- dhctl/pkg/app/preflight.go
- dhctl/pkg/preflight/preflight.go
- dhctl/pkg/preflight/python.go
- dhctl/pkg/system/ssh/frontend/command.go
Added a preflight check to validate that required python modules are installed on the node
Installer will not begin bootstrapping nodes without required python modules
```changes
section: dhctl
type: feature
summary: dhctl will now check if required python modules are installed on the node before bootstrapping it
```
> [dhctl] add preflight check for python and his friends

- dhctl/pkg/server/server/proxy.go
Fix dhctl server sockets dir: use tmp dir.
Dhctl server creates unix sockets during its operation to communicate with its subprocesses. Use common tmp dhctl directory to store such files, rather than separate /var/run/dhctl directory, which was used before.
Otherwise we need to prepare dhctl image so that /var/run/dhctl directory exists in built image with correct permissions.
This fix is requred for dhctl server to operate normally in vanilla installer image, so it is preferred to include this fix into the patch release.
It is not expected to change any dhctl cli behaviour, only dhctl-server.
> [dhctl] fix(dhctl-for-commander): store dhctl-server sockets in dhctl tmp dir

- docs/documentation/_includes/d8-cli-install/content.liquid
- docs/documentation/_includes/d8-cli-install/main.liquid
- docs/documentation/pages/DECKHOUSE-CLI.md
- docs/documentation/pages/DECKHOUSE-CLI_RU.md
- docs/site/.werf/nginx.conf
- modules/007-registrypackages/images/d8/werf.inc.yaml
- Update the Deckhouse CLI version from `0.1.2` to `0.2.0`.
- Refactor Deckhouse CLI installation documentation.
```changes
type: chore
summary: Bump Deckhnouse CLI to `0.2.0`. Refactor the Deckhouse CLI installation page.
```
> [docs][registrypackages] Bump Deckhouse CLI to 0.2.0. Refactor the Deckhouse CLI installation page.

- docs/documentation/_includes/d8-cli-install/content.liquid
- docs/documentation/_includes/d8-cli-install/main.liquid
Fix URLs on the Deckhouse CLI installation page.
```changes
section: docs
type: chore
summary: Fix URLs on the Deckhouse CLI installation page.
```
> [docs][deckhouse-cli] Fix URLs on the Deckhouse CLI installation page.

- candi/openapi/init_configuration.yaml
Removed x-unsafe for deckhouse settings in InitConfiguration crd.
Initially x-unsafe was added to InitConfiguration to prevent changes of InitConfiguration settings. This was wrong decision. So we remove any x-unsafe annotations from InitConfiguration CRD, thus allowing changes of InitConfiguration during changes validation. Changes validation now mainly used in the commander, it should allow changing of InitConfiguration for already created clusters without any affect on those clusters.
This change allows changing of InitConfiguration in created clusters in the commander. Thus it is preferred to include this change into patch release.
It is not expected to change dhctl cli behaviour in any way, only validate-changes procedure which is currently used only in the commander.
> [candi] fix(dhctl-for-commander): init configuration openapi spec: allow any init-configuration changes

- testing/cloud_layouts/script_eks.sh
Refactor EKS script to remove hardcoded terraform path
- Removed the hardcoded path `/terraform/terraform` for `terraform init` and `terraform apply`
- Updated the commands to use `terraform` directly, assuming it's available in the system's PATH
```changes
section: ci
type: chore
summary: Refactor EKS script to remove hardcoded terraform path.
```
> [ci] Fix EKS e2e test script

- testing/cloud_layouts/EKS/WithoutNAT/infra.tf.tpl
- testing/cloud_layouts/script_eks.sh
- werf.yaml
Fix path terraform binary for e2e eks.
Success run e2e eks.
```changes
section: e2e
type: fix
summary: Fix path for e2e eks.
```
> [e2e] fix path terraform binary for eks

- candi/bashible/common-steps/node-group/064_configure_kubelet.sh.tpl
- ee/modules/500-operator-trivy/templates/reports/cis-benchmark-1.23.yaml
- Remove fields `tlsCertFile` and `tlsPrivateKeyFile` from the kubelet configuration file
- Remove the `operator-trivy` compliance control with id `4.2.10`
The kubelet always uses the certificate and key from the `tlsCertFile` and `tlsPrivateKeyFile` files unless the client request contains the TLS server name. By default, in Deckhouse, all nodes communicate using IP addresses rather than hostnames.
Close #8245.
```changes
section: candi
type: fix
summary: Fixed kubelet server certificate rotation.
```
> [candi](kubelet) Fix server certificate rotation

- ee/modules/021-cni-cilium/hooks/ee/egressgatewaypolicies_discovery.go
- ee/modules/021-cni-cilium/hooks/ee/egressgatewaypolicies_discovery_test.go
- modules/021-cni-cilium/docs/EXAMPLES.md
- modules/021-cni-cilium/docs/EXAMPLES_RU.md
* Fix trouble with empty excludedCIDRs in EgressGatewayPolicy
* Fix EgressGatewayPolicy example in documentation
If the _EgressGatewayPolicy_ resource is created with an empty `excludedCIDRs` field, the DH logs will contain an error:
```
ModuleRun:main:cni-cilium:Kubernetes-Change-ModuleValues:failures 6:2 errors occurred:
* cniCilium.internal.egressGatewayPolicies.excludedCIDRs must be of type array: "null"
```
Fix as soon as posible
```changes
type: fix
summary: Fix trouble with empty `excludedCIDRs` field in `EgressGatewayPolicy`.
```
> [cilium] fix trouble with empty excludedCIDRs in EgressGatewayPolicy

- deckhouse-controller/pkg/addon-operator/kube-config/backend/module_config.go
Increase Deckhouse controller's  module event channel buffer size up to 350.
It proved to have positive effect on the operator's converge time as the operator doesn't have to wait for the receiving side when sending module events.
The operator's HandleConvergeModules tasks take several second instead of 10-15.
```changes
type: chore
summary: Increase module event channel buffer.
```
> [deckhouse-controller] increase module event channel buffer

- dhctl/pkg/preflight/registry.go
Fix registry preflight check for anonymous docker registries.
Private registries with anonymous access fail with preflight check.
Important fix.
```changes
section:  dhctl
type: fix
summary: Fix registry preflight check for anonymous docker registries.
```
> [dhctl] Fix registry preflight check for anonymous docker registries

- ee/modules/500-operator-trivy/templates/configmap.yaml
It provides fix for trivy service url to avoid unavailability of trivy-server in env where HTTP_PROXY/HTTPS_PROXY is set.
When the HTTP_PROXY or HTTPS_PROXY is set, the NO_PROXY must be configured to add the trivy service URL. Without this, the operator-trivy will not be able to access the trivy server. But using url with cluster domain fixes this problem, because the cluster domain exists in NO_RPOXY.
Trivy works in env where HTTP_PROXY/HTTPS_PROXY is set.
```changes
type: fix
summary: Fix service URL to work in env where HTTP_PROXY/HTTPS_PROXY is set.
```
> [operator-trivy] fix service url

- modules/031-local-path-provisioner/templates/rbac-for-us.yaml
- testing/matrix/linter/rules/roles/placement.go
- testing/matrix/linter/rules/roles/wildcards.go
Remove wildcard from module RBAC
We need to reduce the module's permissions to limit available resources.
This is necessary for some of our customers
More secure platform
```changes
type: chore
summary: Remove wildcard from module RBAC.
```
> [local-path-provisioner] remove wildcard from module RBAC

- modules/402-ingress-nginx/monitoring/prometheus-rules/ingress-nginx.yaml
Increase `kruise controller is restarting too often` alert's threshold from 5 to 10 in one hour.
Current alert's threshold is  five consecutive restarts of the kruise controller in one hour. This value seems to be too sensitive for a situation when the cluster is bootstrapping (for e2e tests, for example).
The alert doesn't fire during e2e tests.
```changes
section: Ingress-nginx
type: chore
summary: Adjust kruise controller is restarting alert's threshold.
```
> [ingress-nginx] adjust kruise controller alert's threshold

- dhctl/pkg/app/preflight.go
- dhctl/pkg/preflight/preflight.go
- dhctl/pkg/preflight/sudoers.go
Added a preflight check to validate that bootstrapping user as able to run elevate priviliges using sudo
We hit a case where root was not in sudoers file some time ago and it was not obvious what is wrong nad how to fix the problem
No change in happy path, error message if user cannot use sudo due to lack of privileges or incorrect password
```changes
section: dhctl
type: feature
summary: added a preflight check for sudo permissions
```
> [dhctl] add preflight checks for sudo access

- ee/candi/cloud-providers/vcd/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/vcd/openapi/doc-ru-cluster_configuration.yaml
- ee/candi/cloud-providers/vcd/terraform-modules/providers.tf
- ee/modules/030-cloud-provider-vcd/capi/cluster.yaml
- ee/modules/030-cloud-provider-vcd/docs/EXAMPLES.md
- ee/modules/030-cloud-provider-vcd/docs/EXAMPLES_RU.md
- ee/modules/030-cloud-provider-vcd/images/cloud-data-discoverer/discoverer.go
- ee/modules/030-cloud-provider-vcd/openapi/values.yaml
- ee/modules/030-cloud-provider-vcd/templates/cloud-data-discoverer/deployment.yaml
- ee/modules/030-cloud-provider-vcd/templates/registration.yaml
- ee/modules/030-cloud-provider-vcd/templates/secret.yaml
- modules/040-node-manager/templates/node-group/_capi_bootstrap_secret.tpl
Add support for token-based authentication to the VCD cloud provider.
We need to add a more secure authentication type than password-based authentication.
```changes
type: feature
summary: Add support for token-based authentication.
```
> [cloud-provider-vcd] API token support

- candi/cloud-providers/aws/bashible/common-steps/node-group/001_create_nvme_ebs_aliases.sh.tpl
- modules/007-registrypackages/images/amazon-ec2-utils/scripts/install
- modules/007-registrypackages/images/amazon-ec2-utils/scripts/uninstall
- modules/007-registrypackages/images/amazon-ec2-utils/werf.inc.yaml
- testing/library/images_tags_generated.go
Fix aws identity ebs device in step `001_create_nvme_ebs_aliases.sh`.
Sometime (e.g. centos 9 stream), step 001_create_nvme_ebs_aliases.sh may fail to determine the EBS device name:
```
[root@9838403433-1-con-1-26-master-0 ~]# nvme id-ctrl -v /dev/nvme1n1 | grep ^0000:
[root@9838403433-1-con-1-26-master-0 ~]#
```
In such cases we can try to get ebs device name as follows:
```
[root@9838403433-1-con-1-26-master-0 ~]# /opt/deckhouse/bin/ebsnvme-id /dev/nvme1n1
Volume ID: vol-0e33e15c451c2c12d
/dev/xvdf
```
Correct identification of EBS device.
```changes
section: candi
type: fix
summary: Fix AWS identity EBS device.
impact: low
```
> [candi] fix aws identity ebs device

- modules/007-registrypackages/images/d8/werf.inc.yaml
Bump [Deckhouse CLI](https://deckhouse.io/documentation/v1.62/deckhouse-cli/) version from 0.2.0 to 0.2.1.
```changes
type: chore
summary: Bump [Deckhouse CLI](https://deckhouse.io/documentation/v1.62/deckhouse-cli/) version 0.2.1.
```
> [deckhouse-cli] Bump Deckhouse CLI version from 0.2.0 to 0.2.1

- ee/modules/021-cni-cilium/.build.yaml
- ee/modules/021-cni-cilium/hooks/ee/egressgatewaypolicies_discovery.go
- ee/modules/021-cni-cilium/monitoring/prometheus-rules/egressgatewaypolicies.yaml
- ee/modules/021-cni-cilium/templates/monitoring.yaml
- tools/build_includes/modules-EE.yaml
- tools/build_includes/modules-FE.yaml
- tools/build_includes/modules-with-dependencies-EE.yaml
- tools/build_includes/modules-with-dependencies-FE.yaml
- tools/build_includes/modules-with-exclude-EE.yaml
- tools/build_includes/modules-with-exclude-FE.yaml
Add alert for orphan EgressGatewayPolicy resources with irrelevant EgressGateway fields.
The alert will help the client quickly respond to a situation where the EgressGatewayPolicy is misconfigured.
This is an important patch that will help improve the client experience.
```changes
type: chore
summary: Alert for orphan EgressGatewayPolicy.
```
> [cilium] alert for orphan EgressGatewayPolicy

- modules/810-documentation/templates/rbac-for-us.yaml
- testing/matrix/linter/rules/roles/wildcards.go
Replace wildcards to specific resources in dex
Setting a wildcard for Role/ClusterRole is potentially dangerous. We have to review them and replace with specific resources.
```changes
type: chore
summary: Improve documentation rbac permissions.
```
> [global] improve documentation permissions

- modules/150-user-authn/templates/dex/rbac-for-us.yaml
- testing/matrix/linter/rules/roles/wildcards.go
Replace wildcards to specific resources in dex
Setting a wildcard for Role/ClusterRole is potentially dangerous. We have to review them and replace with specific resources.
```changes
type: chore
summary: improve dex rbac permissions
```
> [user-authn] improve dex permissions

- modules/021-cni-cilium/docs/internal/CONNECTIVITY_TESTS.md
Added description about clusterrole creation.
For internal cilium connectivity tests
Run cilium connectivity tests without error.
```changes
type: chore
summary: Add description about clusterrole creation.
```
> [cni-cilium] Update internal documentation about cilium connectivity tests

- docs/documentation/_data/sidebars/main.yml
Sort modules in the documentation sidebar.
Not necessary.
```changes
section: docs
type: chore
summary: Sort modules in the documentation sidebar.
```
> [site] Sort modules in the documentation sidebar

- go_lib/updater/updater.go
When using manual confirmation of module installation, an error occurred; the confirmation status was reset immediately before the check. As a result, after installing the annotation in Kubernetes on the module, the installation did not proceed.
It is necessary to restore the functionality of confirming the installation of modules in manual mode.
After installing the annotation on the module in Kubernetes, the installation is successful.
```changes
type: fix
summary: successful confirmation of module installation via annotations
```
> [go_lib] fix: successful confirmation of module installation via annotations

- candi/cloud-providers/aws/openapi/cluster_configuration.yaml
- candi/cloud-providers/aws/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/cluster_configuration.yaml
- candi/cloud-providers/azure/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/gcp/openapi/cluster_configuration.yaml
- candi/cloud-providers/gcp/openapi/doc-ru-cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/cluster_configuration.yaml
- candi/cloud-providers/yandex/openapi/doc-ru-cluster_configuration.yaml
- candi/openapi/cluster_configuration.yaml
- candi/openapi/doc-ru-cluster_configuration.yaml
- candi/openapi/doc-ru-static_cluster_configuration.yaml
- candi/openapi/static_cluster_configuration.yaml
- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
- ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/openstack/openapi/doc-ru-cluster_configuration.yaml
- ee/candi/cloud-providers/vcd/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/vcd/openapi/doc-ru-cluster_configuration.yaml
- ee/candi/cloud-providers/vsphere/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/vsphere/openapi/doc-ru-cluster_configuration.yaml
- ee/candi/cloud-providers/zvirt/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/zvirt/openapi/doc-ru-cluster_configuration.yaml
- ee/modules/030-cloud-provider-vcd/openapi/values.yaml
- ee/modules/030-cloud-provider-zvirt/openapi/values.yaml
- modules/002-deckhouse/docs/FAQ.md
- modules/002-deckhouse/docs/FAQ_RU.md
- modules/500-upmeter/scripts/fix_server_db/README.md
In the docs everywhere we have a command like:
```sh
kubectl -n d8-system exec -ti deploy/deckhouse -- deckhouse-controller edit provider-cluster-configuration
```
which could not work for HA installations
We should replace `kubectl -n d8-system exec -ti deploy/deckhouse` with `kubectl -n d8-system exec -ti svc/deckhouse-leader`
related #8994
Documentation is up to date
```changes
section: docs
type: chore
summary: Use `svc/deckhouse-leader` in kubectl exec command (more convenient, especially when Deckhouse works in HA mode).
```
> [docs] fix the docs about exec process

- modules/010-user-authn-crd/crds/dex-provider.yaml
- modules/010-user-authn-crd/crds/doc-ru-dex-provider.yaml
In the user authentication documentation, the link to the list of fields to include in the response when requesting a token in the `spec.oidc.scopes` parameter has been changed.
When clicking on the link, users will find the information they need.
```changes
section: docs
type: fix 
summary: Fix links in documentation.
```
> [docs] Link to documentation with lists of fields has been changed.

- candi/bashible/common-steps/all/003_create_deckhouse_user.sh.tpl
- candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
Don't create deckhouse user's home directory and check right permissions for NodeUser home dir.
Step `003_create_deckhouse_user.sh` creates `/home/deckhouse` with default permission 700, that denies access to the NodeUsers ssh key.
Without these changes NodeUser can't connect via ssh-key.
Repair ability to connect via ssh for NodeUser.
```changes
section: candi
type: fix
summary: Fix home directory permission for NodeUser.
```
> [candi] fix dir permission for NodeUser

- modules/110-istio/templates/kiali/rbac-for-us.yaml
- modules/110-istio/templates/operator/rbac-for-us.yaml
- modules/500-cilium-hubble/templates/ui/rbac-for-us.yaml
- testing/matrix/linter/rules/roles/wildcards.go
Remove wildcard from network modules RBAC
Setting a wildcard for Role/ClusterRole is potentially dangerous. We need to reduce the modules' permissions to to avoid security issues.
This is necessary for some of our customers
```changes
section: istio
type: chore
summary: Remove wildcard from network modules RBAC.
---
type: chore
summary: Remove wildcard from network modules RBAC.
```
> [istio][cilium-hubble] Remove wildcard from modules RBAC

- modules/340-monitoring-kubernetes/images/node-exporter/Dockerfile
- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
- modules/470-chrony/templates/configmap.yaml
Fix node exporter ntp address.
Node exporter awaits ntp server on localhost, bu our chrony listens on the node ip.
This PR fixes access from node-exporter to the chrony on the node.
```changes
type: fix
summary: Fix node exporter NTP address.
impact: node-exporter will restart.
```
> [monitoring] Fix node exporter NTP address

- candi/cloud-providers/aws/docs/ENVIRONMENT.md
- candi/cloud-providers/aws/docs/ENVIRONMENT_RU.md
- docs/site/_includes/getting_started/aws/STEP_ENV.md
- docs/site/_includes/getting_started/aws/STEP_ENV_RU.md
- docs/site/_includes/getting_started/aws/partials/config.ru.yml.without_nat.ce.inc
- docs/site/_includes/getting_started/aws/partials/config.ru.yml.without_nat.ee.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.without_nat.ce.inc
- docs/site/_includes/getting_started/aws/partials/config.yml.without_nat.ee.inc
The getting started section has been edited:
* Fixed typo in D8CloudProviderAWS policy name in examples
* Removed enabling the Cillium module for AWS cloud provider. The reason for deletion is that the module is not currently ready for production use in AWS.
Changes in allow you to more correctly deploy Deckhouse in AWS according to the instructions from the documentation.
```changes
section: docs
type: fix 
summary: Removed cillium module configuration, fixed typos in the getting started section for the AWS cloud.
```
> [docs] Added documentation improvements in getting started for AWS

- modules/007-registrypackages/images/iptables/werf.inc.yaml
- modules/050-network-policy-engine/images/kube-router/werf.inc.yaml
Using the same iptables from registrypackages as in the host.
There is a [conflict](https://github.com/cloudnativelabs/kube-router/issues/1370) between kubelet and kube-router which leads to DROPping all the input and output traffic. They both work with the KUBE-FIREWALL iptables chain and kubelet creates the rule:
```
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
```
Meanwhile, the kube-router uses iptables-save/iptables-restore flow to sync his own rules and during restore, the `-m mark --mark 0x8000/0x8000` part is being lost. The result is lost connectivity between Nodes!
Fix is using the same iptables versions both in kubelet (host) and kube-router (image).
Also, the only affected and supported by d8 …
> [network-policy-engine] Using the same iptables from registrypackages as in the host

- modules/460-log-shipper/monitoring/prometheus-rules/log-shipper-agent.yaml
Improve alert `D8LogShipperAgentNotScheduledInCluster`.
Command in alert is not give us full information (daemonset have different name)
```
kubectl -n d8-log-shipper get daemonset,pod --selector=app=log-shipper-agent
NAME                          READY   STATUS             RESTARTS          AGE
pod/log-shipper-agent-2g62s   3/3     Running            0                 9d
pod/log-shipper-agent-2rwp7   3/3     Running            0                 9d
pod/log-shipper-agent-65qcx   3/3     Running            0                 11h
pod/log-shipper-agent-6zhrm   3/3     Running            0                 9d
pod/log-shipper-agent-7vjjh   3/3     Running            0                 5d10h
pod/log-shipper-agent-965xs   3/3     Running            131 (3h34m ago)   8d
pod/log-shipper-agent-98fd4 …
```
> [log-shipper] Improve alert D8LogShipperAgentNotScheduledInCluster

- modules/039-registry-packages-proxy/templates/deployment.yaml
- modules/040-node-manager/hooks/discover_packages_proxy_addresses.go
- modules/040-node-manager/hooks/discover_packages_proxy_addresses_test.go
Fixed the behavior of the discover_packages_proxy_addresses hook that caused a static node to be created with an empty PACKAGES_PROXY_ADDRESSES variable, resulting in a bootstrap error.
This change resolves an issue where nodes would fail to bootstrap due to missing package proxy addresses
After applying these changes, nodes should bootstrap successfully without errors related to missing package proxy addresses.
```changes
section: node-manager, registry-packages-proxy
type: fix
summary: Fixed issue causing static nodes to be created with empty package proxy addresses, leading to bootstrap errors.
impact: Nodes will now bootstrap successfully without errors related to missing package proxy addresses.)
```
> [node-manager] discover_packages_proxy_addresses hook fix

- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-abort.go
Minor logging fixes related to commander-mode operation of dhctl.
This PR improves logging when uuid is not exists in the dhctl cache. And in the case when uuid does not exists in the cache there is a corresponding log message.
> chore(dhctl-for-commander): minor logging fixes

- dhctl/pkg/kubernetes/actions/manifests/manifests.go
Fix creation cloudPermanent nodes with valid length name ( no longer 42 symbols ).
CloudPermanent ng with correct length name  ( cluster prefix + node group name should be no longer then 42 symbols ) doesn't create.
In example used cluster prefix `dev-` and node group name `worker-permanent-to-looooooooooooooong`, that give valid name with 42 symbols. Try apply it:
```
nodeGroups:
- instanceClass:
configDrive: false
flavorName: m1.medium
imageName: redos-standard-7.3.4
mainNetwork: dev
name: worker-permanent-to-looooooooooooooong
replicas: 1
```
Behavior before:
```
...
│ │ │ State path: terraform.tfstate
│ │ │ Terraform runner "static-node" process exited.
│ │ │ Save intermediate state error: timeout while "Save intermediate Terraform state for Node …
```
> [dhctl] del name label on d8-node-terraform-state secret

- modules/021-cni-cilium/docs/internal/MAINTENANCE.md
Adding maintenance command to the documentation
Previously, a mechanism was added to safely update pods with cilium agents. Because of this, the simple `rollout restart ds agent` command no longer functions. 
A new command has been added to the documentation that, if necessary, allows for a sequential restart of all cilium agent pods.
```changes
type: chore
summary: Add maintenance command to the documentation.
```
> [cni-cilium] Adding maintenance command to the documentation

- docs/site/.helm/templates/20-ingress.yaml
Add temporary HTTP redirect for `/platform` location on the website to the stable documentation.
So, the _https://deckhouse.io/platform/modules/500-dashboard/examples.html_ will redirect to _https://deckhouse.io/documentation/v1/modules/500-dashboard/examples.html_.
There is a problem when creating links in modules. We agreed to create **relative** links to DKP documentation and other modules. But DKP documentation inside the cluster (in the documentation module) is located at the same nesting level relative to the modules. For example:
- /en/platform/URL (for DKP documentation and documentation of internal modules)
- /en/modules/URL (for DKP modules)
At the same time, the documentation on the public website has a different structure. For example:
- …
> [site] Add redirect for the /platform location

- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
Change weight from 49 to 31 for better behaviour then bashible doesn't see new script and wait 4 hours.
We use 31 weight for others containerd NGC, like docker mirror.
```changes
section: docs
type: chore
summary: Change weight for GPU runtime in NodeGroupConfiguration example.
```
> [docs] Change weight for GPU runtime NGC

- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/pkg/app/bootstrap.go
- dhctl/pkg/config/base.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-resources.go
- dhctl/pkg/template/resources.go
- dhctl/pkg/util/fs/path.go
Add --config flag and add deprecation warning abour --resources flag for bootstrap-phase create-resources command
`--resources` flag is deprecated. We need use `--config` in all places
```changes
section: dhctl
type: feature
summary: Add --config flag and add deprecation warning abour --resources flag for bootstrap-phase create-resources command
```
> [dhctl] Add --config flag and add deprecation warning abour --resources flag for `bootstrap-phase create-resources` command

- modules/010-user-authn-crd/crds/user.yaml
When creating a user, email and password checks are not performed. You can create a user with empty values ​​or with an incorrect email.
In this regard, a number of errors are possible. And we need to check that the password and email fields are filled in correctly.
The cluster must have users with a correctly specified email and non-empty password fields.
When creating a user, the email and password fields are checked for completion. In this case, the email field is checked for a specific format.
```changes
type: chore
summary: Validate email and password on user create.
```
> [user-authn] feat: validate email and password on user create

- go.mod
- go.sum
- modules/000-common/images/shell-operator/werf.inc.yaml
- werf.yaml
We need to change default ports for shell-operator.
We already have a new version of shell-operator with this functionality, and now we need to use it
Closed: #9056
This is necessary to be able to configure the standard ports that are used in the shell-operator.
After changing the version of shell-operator we are using, we have the opportunity to configure standard shell-operator ports through environment variables.
```changes
section: tools
type: chore
summary: update shell-operator version
```
> feat: update shell-operator version

- dhctl/pkg/server/rpc/dhctl/bootstrap.go
This PR enables standard preflight checks in dhctl server bootstrap operation, which are used in dhctl bootstrap cli command.
All preflight checks was disabled for dhtll server bootstrap operation just because these checks was initially disabled in dhctl bootstrap operation in the commander. Currently we aim to enable these checks just like in default dhctl cli bootstrap command.
> fix(dhctl-for-commander): enable default preflight checks for dhctl server bootstrap operation

- modules/007-registrypackages/images/iptables/scripts/install
Fix detection of iptables nft support in iptables registry-package during install.
Some servers with custom kernels don't have nft support. We can't rely on kernel version alone.
The correct way to detect iptables nft support.
```changes
type: fix
summary: Fix detection of iptables nft support in iptables registry-package during install.
```
> [registrypackages] Fix detection of iptables nft support in iptables registry-package during install.
