deckhouse/deckhouse

docs/site/werf.yaml
Sync the topnav menu once an hour.
=> [docs] Sync menu once an hour

dhctl/pkg/operations/bootstrap/cluster-bootstrapper-deckhouse.go
Set version field for ConfigMap `install-data`.
```changes
section: dhctl
type: fix
summary: Set version field for ConfigMap 'install-data' in 'dhctl bootstrap-phase install-deckhouse'.
```
=> [dhctl](bootstrap-phase) set version field for ConfigMap `install-data`

modules/030-cloud-provider-yandex/monitoring/prometheus-rules/deprecated_availability_zone.yaml
Add a link to the Yandex Migration Guide.
```changes
type: feature
summary: Add link to the Yandex Migration Guide.
```
=> [cloud-provider-yandex][docs] Add link to the Yandex Migration Guide

werf.yaml
Fix libs in deckhouse-controller.
```changes
section: ci
type: fix
summary: Fix libs in `deckhouse-controller`.
```
=> [ci] fix libs in deckhouse-controller

modules/030-cloud-provider-yandex/docs/FAQ.md, modules/030-cloud-provider-yandex/docs/FAQ_RU.md
Add the instruction about installing with a bastion host, that useful with [WithNATInstance](https://deckhouse.ru/documentation/v1/modules/030-cloud-provider-yandex/layouts.html#withnatinstance) layout
Just improve documentation
```changes
type: chore
summary: Add the instruction about installing with bastion.
```
=> [cloud-provider-yandex] Add the instruction about installing with bastion

modules/300-prometheus/openapi/config-values.yaml
Fix OpenAPI spec in the prometheus module.
Fix: #7523 
```changes
section: [prometheus]
type: chore
summary: Fix OpenAPI spec.
```
=> [prometheus] Fix OpenAPI spec

modules/040-node-manager/hooks/handle_node_templates.go, modules/040-node-manager/hooks/handle_node_templates_test.go
Prevent node (with CloudPermanent or Static type) deletion by autoscaler.
```changes
type: fix
summary: Prevent node (with `CloudPermanent` or `Static` type) deletion by autoscaler.
```
=> [node-manager] Prevent node deletion by autoscaler

modules/031-local-path-provisioner/crds/local_path_provisioner.yaml
Change string to array in [example](https://deckhouse.io/documentation/v1/modules/031-local-path-provisioner/cr.html#localpathprovisioner-v1alpha1-spec-nodegroups)
```
x-doc-examples:
- - master
- worker
```
```changes
type: fix 
```
=> [docs] Change string to array in example

.github/actions/milestone-changelog/action.yml
Update action.yml to include a new directory in the module path. Update template for release content.
```changes
section: ci
type: chore
summary: Update the changelog generator.
```
=> [ci] Update the changelog generator

docs/site/_includes/getting_started/openstack_selectel/partials/config.ru.yml.standard.ee.inc
Update the Getting Starte config for OpenStack.
Ref: https://github.com/deckhouse/deckhouse/pull/6871
```changes
section: docs
type: chore
summary: Minor documentation changes.
```
=> [docs] Actualise Selectel RU GS

dhctl/pkg/operations/converge/converger.go
Resolve todos about destructiveChangeID comparison in converger
=> [dhctl] feat(dhctl-for-commander): compare destructiveChangeID

modules/810-documentation/templates/deployment.yaml, testing/cloud_layouts/script.d/wait_cluster_ready/test_script_eks.sh, werf.yaml
Fixes for e2e tests for AWS: fixed panic when rendering templates and added curl to the deckhouse container.
```changes
type: fix
summary: Fix e2e tests for AWS. And curl to the deckhouse container.
```
=> [documentation] Fix EKS tests 

ee/modules/030-cloud-provider-vcd/hooks/ensure_crds_capi.go
Fix the path in the `ensure_crds` hook.
```changes
type: fix
summary: Fix the path in the `ensure_crds` hook.
```
=> [cloud-provider-vcd] Fix path in ensure crd hook

.github/CODEOWNERS
Update repository code owners list.
=> [chore] Update repository code owners

docs/site/_includes/footer.html
Update the footer in the documentation.
```changes
section: docs
type: chore
summary: Update the footer in the documentation.
```
=> [docs] Update the footer

candi/cloud-providers/azure/docs/LAYOUTS.md, docs/site/_includes/getting_started/azure/layouts/STANDARD.md, docs/site/_includes/getting_started/azure/layouts/STANDARD_RU.md, docs/site/_includes/getting_started/existing/STEP_FINALIZE.md
Fix typos in the documentation.
```changes
section: docs
type: chore
summary: Fix typos in the documentation.
```
=> [docs] Fix typos

modules/402-ingress-nginx/images/controller-1-9/Dockerfile, modules/402-ingress-nginx/images/controller-1-9/README.md
Fix missed libs.
The fix is necessary for a patch release, as it fixes important bugs.
```changes
section: core
type: fix
summary: Fix missed libs.
impact: Ingress controller will restart.
```
=> [ingress-nginx] fix libs and build

modules/402-ingress-nginx/images/controller-1-9/Dockerfile
Remove duplicate lines in controller image
Just clean duplicate lines
```changes
type: chore
summary: Remove duplicate lines in controller image.
```
=> [ingress-nginx] Remove duplicate lines in controller image

dhctl/pkg/kubernetes/actions/deckhouse/install.go
Does not create lock cm when deckhouse deployment already created.
Prevent dedlock after restart bootstrap process.
It is bug and it needs in LTS version.
Lock created with normal case
```changes
section: dhctl
type: fix
summary: Prevent deadlock when re-bootstrap cluster
```
=> [dhctl] Prevent deadlock when re-bootstrap cluster

modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
Fixed D8KubernetesVersionIsDeprecated alert
```changes
type: fix
summary: Fixed D8KubernetesVersionIsDeprecated alert
```
=> [control-plane-manager] Fix D8KubernetesVersionIsDeprecated alert

dhctl/pkg/kubernetes/actions/converge/converge.go, dhctl/pkg/operations/converge/converger.go
This PR have the same purpose as https://github.com/deckhouse/deckhouse/pull/7763
=> [dhctl] fix(dhctl-for-commander): disable converge-lock in commander-mode for converge operation as well as bootstrap

candi/bashible/bashbooster/50_deckhouse_registrypackages.sh
`if bb-error?` code doesn't work because of the "bash strict mode" (`set -e`) because an error causes an immediate exit and we can't process the return code. `trap` solves this problem.
Since the if block doesn't execute, we don't clean up temporary files or re-fetch registry packages in case of an error. This leads to bootstrap failure.
This affects clients, but it doesn't happen very often.
```changes
section: candi
type: fix
summary: Fix bootstrap by replace bb-error checks with trap.
```
=> [candi] Fix bootstrap by replace bb-error checks with trap

ee/candi/cloud-providers/zvirt/layouts/standard/base-infrastructure/outputs.tf, ee/candi/cloud-providers/zvirt/openapi/cloud_discovery_data.yaml, ee/modules/030-cloud-provider-zvirt/hooks/zvirt_cluster_configuration.go, ee/modules/030-cloud-provider-zvirt/openapi/values.yaml
=> [zvirt] provider-discovery-data

docs/site/css/docs.scss, docs/site/js/customscripts.js
Added wrapper for tables, added wrap for code blocks. CSS changes.
=> [docs][site] Added wrapper for tables, added wrap for code blocks

dhctl/pkg/server/rpc/dhctl/check.go
Fix ssh private keys handling, add bastion settings
=> [dhctl] feat(dhctl-for-commander): Update ssh client creation

candi/bashible/common-steps/node-group/002_create_static_node_cleanup_script.sh.tpl
Add remove /etc/containerd directory to cleanup script.
Just improve cleanup script.
We don't.
```changes
section: candi
type: chore
summary: Add remove /etc/containerd directory to cleanup script.
```
=> [candi] Add remove /etc/containerd directory to cleanup script

.github/CODEOWNERS
Update repository codeowners list.
=> [chore] Update repository codeowners

deckhouse-controller/pkg/controller/module-controllers/release/controller.go
Deckhouse will fail on module restoration error during the startup
Close https://github.com/deckhouse/deckhouse/issues/7914
```
NAME                         READY   STATUS   RESTARTS     AGE
deckhouse-579fb48fdc-m9md2   1/2     Error    1 (3s ago)   7s
```
```
{"level":"error","msg":"modules restoration failed: couldn't create module symlink: Download module hello-world with version v0.0.15 failed: GET https://dev-registry.deckhouse.io:5001/auth?scope=repository%3Adeckhouse%2Flosev%2Fexternal-modules%2Fhello-world%3Apull\u0026service=Docker+registry: unexpected status code 401 Unauthorized: Auth failed.\n. Skipping","time":"2024-03-26T15:47:00Z"}
```
```changes
type: feature
summary: Fail deckhouse controller if module restoration failed on startup.
```
=> [deckhouse] Fail controller on module restoration error

dhctl/pkg/server/fsm/fsm.go, dhctl/pkg/server/fsm/fsm_test.go, dhctl/pkg/server/rpc/dhctl/check.go, dhctl/pkg/server/rpc/dhctl/dhctl.go, dhctl/pkg/server/server.go, dhctl/pkg/terraform/pipeline_test.go
Add finite state machine to properly handle different grpc messages
=> [dhctl] feat(dhctl-for-commander) Add check service stop msg handling

modules/030-cloud-provider-yandex/cloud-instance-manager/machine-class.yaml
Changes label in YandexMachineClass to fit in Yandex Cloud limits.
Closes https://github.com/deckhouse/deckhouse/issues/6282
```changes
type: fix
summary: Fix a long node name.
```
=> [cloud-provider-yandex] fixing a long node name

testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/Azure/Standard/configuration.tpl.yaml
Disable ebpf exporter on CentOS based e2e
e2e test don't work
```changes
type: fix
summary: Disable `ebpf_exporter` on CentOS based e2e tests.
```
=> [testing] Disable ebpf exporter on CentOS based e2e

docs/documentation/_data/sidebars/main.yml, modules/460-log-shipper/docs/FAQ.md, modules/460-log-shipper/docs/FAQ_RU.md
[loki][log-shipper] Documentation updates
Ref: https://github.com/deckhouse/deckhouse/pull/6911
```changes
type: chore
summary: Documentation updates.
```
=> [loki][log-shipper] Documentation updates

docs/documentation/_data/sidebars/main.yml, ee/modules/381-l2-load-balancer/docs/README.md
Ref: #7752
Update documentation of the _l2-load-balancer_ module.
```changes
type: chore
summary: Update documentation of the _l2-load-balancer_ module.
```
=> [l2-load-balancer][docs] Documentation updates

testing/cloud_layouts/script.sh
Fix ssh_user for openstack testing e2e layout.
```changes
type: chore
summary: change user for openstack e2e testing layout.
```
=> [e2e] update user for e2e openstack

modules/300-prometheus/images/memcached/werf.inc.yaml, testing/matrix/linter/rules/modules/images.go
Move Prometheus/memcached to distroless.
```changes
type: chore
summary: Move Prometheus/memcached to distroless.
impact: Memcached (Prometheus) will restart.
```
=> [prometheus] move prometheus/memcached to distroless

dhctl/pkg/config/connection.go, dhctl/pkg/config/connection_test.go, dhctl/pkg/config/validation.go, dhctl/pkg/config/validation_rules_test.go, dhctl/pkg/config/validation_test.go, dhctl/pkg/terraform/pipeline_test.go
Add new type for validation error. 
In commander we need detailed and typed validation error.
=> feat(dhctl-for-commander): Add typed error for commander

dhctl/pkg/config/validation.go, dhctl/pkg/config/validation_rules_test.go, dhctl/pkg/config/validation_test.go
Add more config valdiations:
* improve cloud provider config validations 
* add tests
=> [dhctl] feat(dhctl-for-commander): more validations

docs/site/.helm/templates/13-rbac.yaml
Delete duplicated RoelBinding.
```changes
section: docs
type: chore
summary: Delete duplicated RoelBinding.
```
=> [site] Fixed RoleBinding

candi/bashible/preflight/check_ports.sh
Fix checking the possibility of opening ports 6443 2379 2380 on the server.
Close #7391.
If the master node does not have python3, the `check_ports.sh` script fails.
```changes
section: dhctl
type: fix
summary: Fix preflight ports checking when static cluster is bootstrapping.
```
=> [dhctl](preflight-check) Add python2 support for `check_ports.sh`

modules/040-node-manager/webhooks/validating/node_group
Simplify ng zones check expression.
Closes #7936.
One client had a problem.
```changes
type: fix
summary: Simplify ng zones check expression.
```
=> [node-manager] Simplify ng zones check expression

docs/documentation/_data/sidebars/main.yml, ee/modules/381-l2-load-balancer/docs/CR.md, ee/modules/381-l2-load-balancer/docs/CR_RU.md
Add rendering of CRDs of the l2-load-balancer module to the documentation.
```changes
type: chore
summary: Add rendering of CRDs to the documentation.
```
=> [docs][l2-load-balancer] Render CRDs

Makefile
increased execution time for matrix tests
Fixing a common timeout error
```changes
type: fix
summary: Increase execution time for matrix tests.
```
=> [testing][ci] Increased execution time for matrix tests

docs/documentation/pages/DECKHOUSE-CLI.md, docs/documentation/pages/DECKHOUSE-CLI_RU.md
Add alert about Community Edition.
```changes
section: docs
type: chore
summary: Add info about using `d8 d` commands.
```
=> Add alert to Deckhouse CLI page

ee/modules/381-l2-load-balancer/hooks/load_balancers_status_update.go, ee/modules/381-l2-load-balancer/templates/rbac-to-us.yaml, ee/modules/381-l2-load-balancer/templates/speaker/daemonset.yaml
1. Fixed ports conflict between metallb and l2lb speakers.
2. Fixed panic in `L2LoadBalancer` status handler hook.
Change the ports to avoid conflict with the metallb module. Speakers in both modules use hostNetwork.
It is impossible to run l2-load-balancer and metallb modules simultaneously.
```changes
type: fix
summary: Fixes for ports conflict and hook panic.
```
=> [l2-load-balancer] Fixes for ports conflict and hook panic

dhctl/pkg/config/validation.go, dhctl/pkg/config/validation_rules.go, dhctl/pkg/operations/import/import_result.go, dhctl/pkg/operations/import/importer.go
=> [dhctl] feat(cluster-import): Add ssh keys to ScanResult

dhctl/pkg/config/validation.go, dhctl/pkg/config/validation_rules.go
=> [dhctl] feat(dhctl-for-commander): add zvirt support

werf.yaml
Add go.mod and go.sum from everywhere in go_lib
Main branch is broken
```changes
section: ci
type: fix
summary: Add go.mod and go.sum from everywhere in go_lib
```
=> [ci] Add go.mod and go.sum from everywhere in go_lib

go_lib/registry-packages-proxy/registry/default_client.go
Fixed panic when using custom CA
```changes
section: registry-packages-proxy
type: fix
summary: Fixed panic when using custom CA
```
=> [registry-packages-proxy] Fix panic

dhctl/pkg/config/base.go
Print invalid YAML documents.
Close #7251.
```changes
section: dhctl
type: fix
summary: Print invalid YAML documents.
```
=> [dhctl] Print invalid YAML documents

docs/site/backends/docs-builder/upload.go
Clean old documentation files when updating.
```changes
section: documenation
type: fix
summary: Clean old documentation files when updating.
```
=> [documentation] Fixing an issue with renaming files

modules/030-cloud-provider-azure/hooks/storage_classes.go, modules/030-cloud-provider-azure/hooks/storage_classes_test.go, modules/030-cloud-provider-azure/openapi/config-values.yaml, modules/030-cloud-provider-azure/openapi/doc-ru-config-values.yaml, modules/030-cloud-provider-azure/templates/csi/storage-classes.yaml
Add tag support for additional StorageClasses and fix available values for `storageClass.provision.type`.
To be able to use tags in additional StorageClasses.
ModuleConfig
storageClass
pv
```changes
type: feature
summary: Add tags support for additional StorageClasses.
```
=> [cloud-provider-azure] add tags support for azure additional storageclasses

docs/documentation/pages/DECKHOUSE_CONFIGURE.md, docs/documentation/pages/DECKHOUSE_CONFIGURE_RU.md
Actual examples
some corrections for equal RU and EN docs
Improve documentation
```changes
section: docs
type: chore
summary: Actualize examples in the documentation.
```
=> [docs] Actual examples

modules/002-deckhouse/docs/FAQ.md, modules/002-deckhouse/docs/FAQ_RU.md, modules/150-user-authn/docs/FAQ.md, modules/150-user-authn/docs/FAQ_RU.md
```changes
section: docs
type: chore
```
=> [docs][user-authn][deckhouse] Update FAQ

deckhouse-controller/pkg/controller/module-controllers/release/controller.go, deckhouse-controller/pkg/controller/module-controllers/source/controller.go, modules/040-node-manager/hooks/handle_node_templates.go, modules/150-user-authn/hooks/generate_crowd_basic_auth_proxy_cert.go
Fix old loopvar copies
```changes
type: chore
summary: Fix linter cases.
```
=> [deckhouse] Fix linter loopvar

.github/workflow_templates/validation.yml, .github/workflows/validation.yml
We need golang 1.22
```changes
section: ci
type: chore
summary: Change validations runner to the ubuntu 24.04
```
=> Restore runner

modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/node.json
added 'Storage Filesystem' -> 'Filesystem size'
adds information about the size of fs
```changes
type: feature 
summary: Added 'Storage Filesystem' -> 'Filesystem size' in grafana-dashboard node.
```
=> [monitoring-kubernetes] grafana-dashboards edit node

MAINTAINERS.md
Update the core maintainers list.
```changes
section: docs
type: chore
summary: Update the core maintainers list.
```
=> [chore] Update the core maintainers list

.github/actions/milestone-changelog/action.yml
Added a module path for SE to milestone changelog action:
- Updated `.github/actions/milestone-changelog/action.yml` to include a new module path `ee/se/modules` in the list of included directories.
```changes
section: ci
type: chore
summary: Added a module path for SE to milestone changelog action.
```
=> [ci] Added new module path to milestone changelog action

deckhouse-controller/pkg/controller/controller.go, deckhouse-controller/pkg/controller/loader.go, go.mod, go.sum
Added context to the error message
```changes
type: fix
summary: Added context to the error message
```
=> [deckhouse-controller] fix error message

testing/cloud_layouts/EKS/WithoutNAT/infra.tf.tpl
Change instance type for e2e eks.
To successfully pass the e2e eks tests. 
```changes
type: chore
summary: Change instance type for e2e eks.
```
=> [testing] change instance_types e2e eks

tools/spelling/check_diff.sh
Minor spellchecking linter fix to properly check PRs.
```changes
type: chore
summary: Minor spellchecking linter fix to properly check PRs.
```
=> [testing] Minor spellchecking linter fix

dhctl/pkg/app/preflight.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go, dhctl/pkg/preflight/preflight.go, dhctl/pkg/preflight/ssh.go, dhctl/pkg/system/ssh/frontend/waiting.go
Preflight check ssh credentials before start instalations
Before performing bootstrap, checks the possibility of autorize by ssh
```changes
section: dhctl
type: feature
summary: Preflight check ssh credentials before start instalations
```
=> [dhctl] Preflight check ssh credentials before start instalations

deckhouse-controller/pkg/controller/module-controllers/release/controller.go
The PR provides an additional conditional for deployed ModuleReleases to check if their documentations must be skipped in favour of corresponding ModulePullOverrides.
If there is a deployed yet overridden module release, then relevant module's documentation is built from the ModuleRelease's directory, not from the ModulePullOverride's one.
If a deployed module release is overridden by the corresponding module pull override, its documentation has to be sourced from the module pull override.
`kubectl get moduledocumentation` must provide correct path to `dev` directory of the module.
```changes
type: chore
summary: Fix documentation updates for deployed yet overridden module releases.
```
=> [deckhouse-controller] fix doc updates for deployed realses

dhctl/pkg/operations/phases/phased_execution_context.go
Internal PR aimed only for commander-specific branch for current EA+EE version (1.59.12 at the moment).
=> fix(dhctl-for-commander): fix incorrect state passed to first on-phase call of bootstrap action

ee/modules/030-cloud-provider-vcd/capi/machine-template.yaml, modules/040-node-manager/template_tests/module_test.go
Add support catalog selection for vcd cluster-api instances
Client request
```changes
type: fix
summary: Support catalog in instance class template
```
=> [cloud-provider-vcd] Support catalog in instance class template

candi/cloud-providers/yandex/openapi/cluster_configuration.yaml, candi/cloud-providers/yandex/openapi/doc-ru-cluster_configuration.yaml, candi/cloud-providers/yandex/terraform-modules/master-node/main.tf, candi/cloud-providers/yandex/terraform-modules/master-node/variables.tf, testing/openapi_validation/validators/enum.go
Added `diskType` parameter for `masterNodeGroup` and `nodeGroups`.
```changes
type: feature
summary: Added diskType parameter for masterNodeGroup and nodeGroups in YandexClusterConfiguration.
```
=> [cloud-provider-yandex] Add diskType parameter for masterNodeGroup and nodeGroups

modules/007-registrypackages/images/d8/werf.inc.yaml
Update d8 version.
```changes
type: chore
summary: Update the `d8` registry package version.
```
=> [registry-packages] Update d8 version

candi/bashible/preflight/check_containerd.sh, dhctl/pkg/app/preflight.go, dhctl/pkg/preflight/containerd.go, dhctl/pkg/preflight/preflight.go, dhctl/pkg/system/ssh/client.go, dhctl/pkg/system/ssh/frontend/command.go, dhctl/pkg/system/ssh/frontend/file.go, dhctl/pkg/system/ssh/frontend/kube-proxy.go, dhctl/pkg/system/ssh/frontend/reverse-tunnel.go, dhctl/pkg/system/ssh/frontend/tunnel.go, dhctl/pkg/system/ssh/frontend/upload-script.go, dhctl/pkg/system/ssh/frontend/waiting.go, dhctl/pkg/template/preflight.go, testing/cloud_layouts/script.sh
Preflight check exist embedded containerd 
#7960
```changes
section: dhctl
type: feature
summary: Preflight check exist embedded containerd 
```
=> [dhctl] Preflight check exist embedded containerd 

dhctl/cmd/dhctl/main.go, dhctl/pkg/app/app.go, dhctl/pkg/config/base.go, dhctl/pkg/config/deckhouse_config.go, dhctl/pkg/config/load.go, dhctl/pkg/config/module_config.go, dhctl/pkg/kubernetes/actions/deckhouse/install.go, dhctl/pkg/kubernetes/client/state_cache.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go, dhctl/pkg/operations/bootstrap/steps.go, dhctl/pkg/state/cache.go, dhctl/pkg/state/cache/init.go, dhctl/pkg/template/bundle.go, dhctl/pkg/util/cache/cache.go, dhctl/pkg/util/cache/tmp.go, modules/030-cloud-provider-yandex/hooks/yandex_cluster_configuration_test.go
Add additional debug logs for dhctl bootstrap.
Sanitize exist logs and errors
Remove renaming debug log file into state dir and output debug log file.
Improve dhctl UX
```changes
section: dhctl
type: chore
summary: Add debug logs and sanitize errors
```
=> [dhctl] Add debug logs and sanitize errors

dhctl/pkg/preflight/preflight.go
Temporary disabled preflight check containerd exist
```changes
section: dhctl
type: fix
summary: Temporary disabled preflight check containerd exist
```
=> [dhctl] Disable preflight check containerd exist

docs/documentation/pages/installing/README.md, docs/documentation/pages/installing/README_RU.md
Update Deckhouse installation instruction.
```changes
section: docs
type: chore
summary: Update Deckhouse installation instruction.
```
=> [docs] Update Deckhouse installation instruction

dhctl/pkg/kubernetes/actions/resources/resources.go, dhctl/pkg/operations/check/checker.go, dhctl/pkg/operations/commander/detach/detacher.go, dhctl/pkg/operations/commander/helpers.go
Internal PR aimed only for commander-specific branch for current EA+EE version (1.60.3 at the moment).
=> feat(dhctl-for-commander): commander/detach operation implementation

docs/site/_includes/gdpr.html, docs/site/css/components/_gdpr.scss, docs/site/css/components/common/_button.scss, docs/site/js/customscripts.js
Update GDPR banner styling and logic.
- Changed `var` to `const` for variables in `customscripts.js`.
- Added new condition to check `cmplz_banner-status` cookie in `customscripts.js`.
- Updated GDPR banner to use flexbox for alignment and spacing.
- Commented out redundant GDPR title section in `gdpr.html`.
- Modified CSS for GDPR banner: adjusted positioning, display properties, and padding.
Improves user experience and ensures the banner is displayed correctly based on cookie status.
=> [docs] fix styles and add one more check cookie field in script

dhctl/pkg/app/preflight.go, dhctl/pkg/preflight/preflight.go
Fix spelling in preflight check
Spelling error correction
```changes
section: dhctl
type: fix
summary: Fix spelling in preflight check
```
=> [dhctl] Fix spelling in preflight check

deckhouse-controller/pkg/controller/module-controllers/utils/utils.go
Add user-agent for registry client
When debugging, it's hard to understand sometime, who generates requests for a registry. 
```changes
type: feature
summary: Add user-agent for the registry client.
```
=> [deckhouse-controller] Add user-agent for registry client

ee/candi/version_map.yml
Fix typo
```changes
section: candi
type: chore
summary: Fix typo in ee version map.
```
=> [candi] Fix typo

.github/workflow_templates/update-dependabot-pr.yml, .github/workflows/update-dependabot-pr.yml
Avoid error `bad credentials`
```changes
section: ci
type: chore
summary: Fix dependabot permissions.
```
=> [ci] Fix dependabot permissions

.github/workflow_templates/update-dependabot-pr.yml, .github/workflows/update-dependabot-pr.yml
Fix action version
```changes
section: ci
type: chore
summary: Fix dependabot action version
```
=> [ci] Fix ci action

modules/300-prometheus/hooks/alertmanager_crd_discovery.go
Add beforeHelm binding for `alertmanager_crds` hook.
Sometimes when we create a cluster, we get cr prometheus created without alertmanager. 
Correct render cr prometheus with alertmanager spec.
```changes
type: fix
summary: Add beforeHelm binding for `alertmanager_crds` hook.
```
=> [prometheus] add beforeHelm for alertmanager_crds hook

modules/030-cloud-provider-aws/docs/EXAMPLES.md, modules/030-cloud-provider-aws/docs/EXAMPLES_RU.md
Added a link to the service annotations
Absence of a link leads to searching for annotations in the wrong place.
```changes
type: feature
summary: Update documentation. Add a link to the service annotations.
```
=> [docs][cloud-provider-aws] Added a link to the service annotations

dhctl/pkg/terraform/executor.go, dhctl/pkg/terraform/runner.go, testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml, testing/cloud_layouts/script.sh
Set right path for terraform plugins.
Correct execution of `terrafrom init`.
```changes
section: dhctl
type: fix
summary: Set right path for terrafrom plugins.
```
```changes
type: fix
summary: Update AWS AMI for CentOS.
impact: low
```
=> [dhctl] fix terraform plugin dir

candi/openapi/cluster_configuration.yaml
Allow [reserved](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) characters in http[s]Proxy 
For the user, : and @ are excluded
This will allow us to use a user with a domain separator in user
https://serverfault.com/questions/371150/any-difference-between-domain-username-and-usernamedomain-local
https://github.com/deckhouse/deckhouse/issues/7976
```changes
section: candi
type: fix
summary: Fix regex pattern for `httpProxy` to allow using reserved characters.
```
=> [candi] httpProxy regex doesn't allow URL encoded characters

ee/be/candi/version_map.yml
fix for https://github.com/deckhouse/deckhouse/pull/8666
```changes
```
=> rosa version_map fix

testing/cloud_layouts/script.sh
Fix e2e cloud tests.
Fix typo in script path.
```changes
type: fix
summary: fix e2e cloud tests
```
=> [testing] fix e2e cloud tests

werf_cleanup.yaml
set the image cleanup time to 15 days
```changes
section: ci
type: chore
summary: set the image cleanup time to 15 days
```
=> [ci] set the image cleanup time to 15 days

modules/045-snapshot-controller/enabled, modules/045-snapshot-controller/images/snapshot-controller/Dockerfile, modules/045-snapshot-controller/images/snapshot-controller/werf.inc.yaml, modules/045-snapshot-controller/images/snapshot-validation-webhook/Dockerfile, modules/045-snapshot-controller/images/snapshot-validation-webhook/werf.inc.yaml, modules/045-snapshot-controller/templates/snapshot-validation-webhook/deployment.yaml
Switch snapshot-controller to distroless
We need to reduce the number of attack vectors
More secure snapshot-controller module
```changes
type: chore
summary: Switch _snapshot-controller_ module to distroless.
```
=> [snapshot-controller] Switch to distroless

Makefile
Added makefile task to build images locally.
To proper use you need to set env var `SOURCE_REPO`.
To build all deckhouse use command `make build`.
If you need to build only one module use `make build FOCUS=<module_name>`.
For proper work you should set two variables before run:
```
export CI_COMMIT_REF_SLUG="<your_pr_name>"
export SOURCE_REPO=https://oauth2:**************@fox.flant.com/deckhouse/3p                                        
```
```changes
section: ci
type: chore
summary: local building of deckhouse images
```
=> [ci] Local build

Makefile
Fix error in the Makefile.
```changes
section: ci
type: fix
summary: Fix error in the Makefile.
```
=> [ci] fix makefile error

.github/workflow_templates/validation.yml, .github/workflows/validation.yml
Add a login step for development registry to validation workflow for spellchecking.
=> [ci] Fix workflow for spellchecking

modules/500-openvpn/templates/openvpn/rbac-for-us.yaml, testing/matrix/linter/rules/roles/wildcards.go
Change wildcard verbs with explicit list
Security
```changes
type: chore
summary: Replace wildcard verbs with explicit list.
```
=> [openvpn] Fix wildcard rbac verbs

dhctl/pkg/preflight/preflight.go, dhctl/pkg/preflight/ssh.go
Fixed SSH tunneling preflight check
This preflight check in required for registry-packages-proxy built into the dhctl container to work properly.
Fixes #6959
If node's sshd is configured to prohibit TCP forwarding, preflight check should fail and notify user about the problem
```changes
section: dhctl
type: fix
summary: Fix ssh tunneling preflight check not triggering when TCP forwarding is disabled
```
=> [dhctl] fix ssh tunneling preflight check

go_lib/registry-packages-proxy/registry/default_client.go
Fix error in working with http registries from registry packages proxy.
We cannot set insecure opt for HTTP registries.
```changes
section: core
type: fix
summary: fix working registry packages proxy with insecure registries(http)_level is high ↓
```
=> [rpp] fix error in working with http registries

werf.yaml
Sometimes if we use cache-repo option we have image digests with registry address in the output.
Right example:
```
{
"common": {
"csiExternalSnapshotter128": "sha256:459da4045de4a3026be49c2df2d86cecdbfeb5b32d9a64311574f7a807f9cd70",
"csiExternalSnapshotter129": "sha256:d83e0305fb9c1c6b9d702a28c77a491a2eb98d578747983a61b8b7741879e339",
"alpine": "sha256:7d9b12f967fb69b5ee8a6371e2d93beba2595aa9c1ac42700e9d8e49b76293a8",
...
```
Wrong example:
```
{
"common": {
"csiExternalSnapshotter128": "registry-write.deckhouse.io/deckhouse/fe@sha256:459da4045de4a3026be49c2df2d86cecdbfeb5b32d9a64311574f7a807f9cd70",
"csiExternalSnapshotter129": "sha256:d83e0305fb9c1c6b9d702a28c77a491a2eb98d578747983a61b8b7741879e339",
"alpine": "sha256:7d9b12f967fb69b5ee8a6371e2d93beba2595aa9c1ac42700e9d8e49b76293a8", …
```
=> [ci] fix possible error in werf digest output

testing/cloud_layouts/script_eks.sh
Fix path in e2e test script for EKS.
```changes
section: ci
type: chore
summary: Fix path in e2e test script for EKS.
```
=> [ci] Fix path in e2e test script for EKS

helm_lib/Chart.lock, helm_lib/Chart.yaml, helm_lib/charts/deckhouse_lib_helm/Chart.yaml, helm_lib/charts/deckhouse_lib_helm/README.md, helm_lib/charts/deckhouse_lib_helm/templates/_csi_controller.tpl, helm_lib/charts/deckhouse_lib_helm/templates/_csi_node.tpl, helm_lib/charts/deckhouse_lib_helm/templates/_enable_ds_eviction.tpl, helm_lib/charts/deckhouse_lib_helm/templates/_module_security_context.tpl
Update helm-lib version.
```changes
type: chore
summary: bump version
```
=> [helm-lib] update version

modules/470-chrony/docs/CONFIGURATION.md, modules/470-chrony/docs/CONFIGURATION_RU.md
Fix chrony settings example
Improve documentation.
```changes
section: docs
type: chore
summary: Fix chrony example.
```
=> [docs] Fix chrony settings example

docs/site/_config.yml, docs/site/_includes/counters-and-chat.liquid, docs/site/_includes/head-site.html
- Update chat and analytics scripts and move them into file `counters-and-chat.liquid`.
- Ensured the scripts load conditionally based on the site's hostname (don't load on the test/stage env).
```changes
section: docs
type: chore
summary: Update chat and analytics scripts.
```
=> [site] Update chat and analytics scripts

docs/site/_config.yml
Fix chat script URLs.
```changes
section: docs
type: chore
summary: Fix chat script URLs.
```
=> [docs] Fix chat script URLs

deckhouse-controller/entrypoint.sh, modules/150-user-authn/templates/dex/rbac-for-us.yaml, modules/810-documentation/templates/rbac-for-us.yaml
Rbac verb `get` was missed
It doesn't work without
```changes
type: fix 
summary: Fix verbs for rbac permissions.
```
=> [global] Fix rbac verbs

candi/cloud-providers/aws/openapi/cluster_configuration.yaml, candi/cloud-providers/aws/openapi/doc-ru-cluster_configuration.yaml
Clarification of the documentation on the zones.
The documentation is now misleading in that it indicates that all cluster components are affected.
Not necessary.
```changes
section: cloud-providers-aws
type: fix 
summary: Clarification of the documentation on the zones.
```
=> [cloud-providers-aws] Clarification of the documentation on the zones

modules/150-user-authn/docs/USAGE.md, modules/150-user-authn/docs/USAGE_RU.md
Change version from 1 to [2](https://github.com/deckhouse/deckhouse/blob/072039a2dea3cea00080f93440694b955755ac7f/modules/150-user-authn/openapi/conversions/v2.yaml) in ModuleConfig [example](https://deckhouse.io/documentation/v1/modules/150-user-authn/usage.html#an-example-of-the-module-configuration) for user-authn
We have some message in case with version 1
```
status:
message: Update available, latest spec.settings schema version is 2
version: "1"
```
```changes
section: docs
type: chore
summary: Fix user-authn example.
```
=> [docs] update version to 2 in example moduleConfig user-authn

Makefile
Added gh binary to auto-detect pr number by branch name.
```changes
section: ci
type: chore
summary: add gh to the makefile
```
=> [ci] add gh to the makefile

dhctl/pkg/app/ssh.go
This pull request makes it so if you set the `--ssh-user` but don't set the `--ssh-bastion-user`, the system will automatically use `--ssh-user` for the bastion.
It makes setting up SSH easier and reduces the chance of mistakes. You don't have to set both options if you want to use the same user.
When you set `--ssh-user`, it will also be used for the bastion if you don't set `--ssh-bastion-user`. This simplifies the setup process.
```changes
section: dhctl
type: fix
summary: Automatically use `--ssh-user` as `--ssh-bastion-user` if not set by the user.
=> [dhctl] set SSHBastionUser same as SSHUser if not defined

candi/bashible/bashbooster/50_registrypackages.sh
Remove bb-package-module-install function dupicate
Now we have duplicated function in bb
Correct bb work
```changes
type: fix
summary: Remove bb-package-module-install function dupicate.
```
=> [bashible] Remove bb-package-module-install function dupicate

tools/check-release-images.sh
- Corrected the `set` command to remove `-e` option (to handle commands fail).
- Display the number of images to be checked.
- Added `--pull always` option to `docker create` command  (when creating installer container).
```changes
section: ci
type: chore
summary: Fix check-release-images.sh script to better trap errors, enhance logging.
```
=> [ci] Fix check-release-images.sh script to better trap errors, enhance logging

modules/302-vertical-pod-autoscaler/templates/rbac-for-us.yaml, testing/matrix/linter/rules/roles/wildcards.go
Add comments for wildcard rbac permissions.
Fixes #8517
Setting a wildcard for Role/ClusterRole is potentially dangerous. We need to reduce module permissions where possible to avoid security issues.
More secure platform.
```changes
type: chore
summary: Add comments for wildcard rbac permissions.
```
=> [vertical-pod-autoscaler] Review of RBAC permissions.

testing/cloud_layouts/AWS/WithoutNAT/resources.yaml, testing/cloud_layouts/Azure/Standard/resources.yaml, testing/cloud_layouts/EKS/WithoutNAT/resources.yaml, testing/cloud_layouts/GCP/WithoutNAT/resources.yaml, testing/cloud_layouts/OpenStack/Standard/resources.yaml, testing/cloud_layouts/Static/resources.tpl.yaml, testing/cloud_layouts/Yandex.Cloud/WithoutNAT/resources.yaml, testing/cloud_layouts/script.d/wait_cluster_ready/test_nodeuser.sh, testing/cloud_layouts/script.sh, testing/cloud_layouts/vCloudDirector/Standard/resources.tpl.yaml, testing/cloud_layouts/vSphere/Standard/resources.yaml
Add NodeUser check for e2e tests.
Improvement of e2e.
Example test result:
```changes
type: feature
summary: add nodeUser to e2e-test 
```
=> [e2e] add nodeUser to test

candi/bashible/common-steps/node-group/002_create_static_node_cleanup_script.sh.tpl
Add missing dirs to clean up that Deckhouse/Kubernetes may create on static node.
```
var/
├─ log
│  ├── kube-audit
│  ├── pods
│  └── containers
└── lib
├── deckhouse
└── upmeter
```
It completely delete remove tmp files for new clean install.
```changes
section: candi
type: fix
summary: Add new dirs to cleanup on cleanup_static_node.sh
```
=> [candi] Add new dirs to cleanup on cleanup_static_node.sh

docs/site/_includes/getting_started/bm/partials/ingress-nginx-controller.yml.inc
Updating tolerations of the ingress controller to prevent issues that may arise when inexperienced users change the nodeselector in the configuration, which could cause problems during node draining.
```changes
section: getting-started
type: chore
summary: Update tolerations of the Ingress controller. 
```
=> [getting-started] Update configuration ingress-nginx-controller.yml

testing/cloud_layouts/vCloudDirector/Standard/configuration.tpl.yaml
Update rootDiskSizeGb in vCloudDirector configuration.
```changes
type: chore
summary: Update rootDiskSizeGb in vCloudDirector configuration.
```
=> [testing][vcd] Update rootDiskSizeGb in vCloudDirector configuration

ee/candi/cloud-providers/dynamix/layouts/standard/base-infrastructure/main.tf, ee/candi/cloud-providers/dynamix/layouts/standard/base-infrastructure/variables.tf, ee/candi/cloud-providers/dynamix/openapi/cluster_configuration.yaml, ee/candi/cloud-providers/dynamix/terraform-modules/master-node/main.tf, ee/candi/cloud-providers/dynamix/terraform-modules/master-node/outputs.tf, ee/candi/cloud-providers/dynamix/terraform-modules/master-node/variables.tf, ee/modules/030-cloud-provider-dynamix/openapi/values.yaml
=> [cloud-providers] dynamix create vins

modules/007-registrypackages/images/d8/werf.inc.yaml
Updated d8-cli to v0.3.1
```changes
type: chore
summary: update d8-cli to 0.3.1
```
=> [registrypackages] Update d8-cli to 0.3.1

docs/site/js/pdf-slider.js
Fix width of presentations in the documentation.
=> [docs][site] Fix width of presentations in the documentation

ee/modules/160-multitenancy-manager/templates/user-resources/default-project-template.yaml, ee/modules/160-multitenancy-manager/templates/user-resources/secure-project-template.yaml, ee/modules/160-multitenancy-manager/templates/user-resources/secure-with-dedicated-nodes-project-template.yaml
It provides fixes for templates.
There are some bugs in project templates which do not allow you to use templates properly.
Templates can be used.
```changes
type: fix
summary: Fix templates bugs.
```
=> [multitenancy-manager] fix templates

modules/110-istio/openapi/config-values.yaml, modules/110-istio/openapi/doc-ru-config-values.yaml
Minor updates of description of resource management parameters section.
```changes
section: docs
type: chore
summary: Minor updates of description of resource management parameters section.
```
=> [docs][istio] Update description of resource management parameters section

ee/modules/030-cloud-provider-dynamix/hooks/get_cni_secret.go, ee/modules/030-cloud-provider-dynamix/images/dynamix-common/api/compute.go, ee/modules/030-cloud-provider-dynamix/openapi/values.yaml, ee/modules/030-cloud-provider-dynamix/templates/cni.yaml
=> [cloud-provider-dynamix] enable Cilium

modules/040-node-manager/images/bashible-apiserver/werf.inc.yaml
We forgot to add detect_bundle.sh to the CE images of bashible-apiserver In this [pr](https://github.com/deckhouse/deckhouse/pull/8640) . As a result, bootstrap of new nodes ends with an error
After this fix, bashibe will render second phase script correctly. As a result, node bootstrap  will be executed successfully.
```changes
section: candi
type: fix
summary: Fix for node bootstrap in CE edition
impact: 
```
=> [bashible-apiserver] detect_bundle.sh in CE edition

modules/010-vertical-pod-autoscaler-crd/crds/verticalpodautoscaler.yaml
Change [controlledresources](https://deckhouse.io/documentation/v1/modules/302-vertical-pod-autoscaler/cr.html#verticalpodautoscaler-v1-spec-resourcepolicy-containerpolicies-controlledresources) to correspond with to [crd](https://github.com/kubernetes/autoscaler/blob/aff50d773e42f95baaae300f27e3b2e9cba1ea1b/vertical-pod-autoscaler/deploy/vpa-v1-crd.yaml#L66-L70)
```changes
type: chore
summary: Fix controlledresources description of verticalpodautoscaler.
```
=> [vertical-pod-autoscaler] Fix description verticalpodautoscaler

docs/documentation/pages/DECKHOUSE-CLI.md, docs/documentation/pages/DECKHOUSE-CLI_RU.md
Added a description to the Deckhouse CLI pages.
This should improve the search results.
```changes
section: docs
type: fix
summary: Added a description to the Deckhouse CLI pages.
```
=> [docs] Add description for the Deckhouse CLI pages

docs/documentation/pages/DECKHOUSE-FAQ.md, docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Improvements in check images commands after change registry.
Improve documentation.
```changes
section: docs
type: chore
summary: Improvements in check images commands after change registry.
```
=> [docs] Improvements in check images commands after change registry

docs/documentation/_data/i18n.yml, docs/documentation/_plugins/openapi.rb, docs/site/backends/docs-builder-template/i18n/en.yaml, docs/site/backends/docs-builder-template/i18n/ru.yaml, docs/site/backends/docs-builder-template/layouts/partials/openapi/format-schema.html, docs/site/css/components/_resources.scss, docs/site/css/docs.scss
Minor markup fixes to properly show deprecated parameters and parameter type.
```changes
section: docs
type: chore
summary: Minor markup fixes to properly show deprecated parameters and parameter type.
```
=> [docs][site] Fix markup for deprecated parameters

docs/site/_includes/getting_started/bm/STEP_INSTALL_SCHEMA.md, docs/site/_includes/getting_started/bm/STEP_INSTALL_SCHEMA_RU.md, docs/site/_includes/getting_started/global/STEP_INSTALL_SCHEMA.md, docs/site/_includes/getting_started/global/STEP_INSTALL_SCHEMA_RU.md
Update URL for presentations in the getting started.
```changes
section: docs
type: chore
summary: Update URL for presentations in the getting started.
```
=> [docs] Update URL for presentations in the getting started

docs/site/css/syntax.css
[docs] Fix styles in the block of code syntax
```changes
section: docs
type: chore
summary: Fix styles in the block of code syntax.
```
=> [docs] Fix styles in the block of code syntax

docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA.md, docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA_RU.md, modules/300-prometheus/docs/CONFIGURATION.md, modules/300-prometheus/docs/CONFIGURATION_RU.md
Fix [issue](https://github.com/deckhouse/deckhouse/issues/8121)
```changes
section: docs
type: chore
summary: Minor doc fixes.
```
=> [docs] Fix getting grafana pass in kind setup

modules/015-admission-policy-engine/templates/validatingwebhookconfiguration.yaml
Adds one more service account of the virtualization module to the list of the service accounts bypassing PSS checks.
It's a temporary solution until the virtualization module starts to comply with PSS.
PSS checks don't interfere with the virtualization module's operations.
```changes
type: chore
summary:  Update the list of excluded sa.
```
=> [admission-policy-engine] update the list of excluded sa

modules/150-user-authn/images/dex/patches/client-groups.patch
Filter group claims earlier
Fix for the problem when the user is not allowed to access web interfaces if allowed groups option is specified in Dex authenticator.
```changes
type: fix
summary: Fix the problem when the user is not allowed to access web interfaces if the allowed groups option is specified in Dex authenticator.
```
=> Filter group claims earlier

docs/documentation/_data/rbac.yaml, ee/modules/160-multitenancy-manager/templates/rbacv2/manage/edit.yaml, ee/modules/160-multitenancy-manager/templates/rbacv2/manage/view.yaml
It regenerates RBAC for multitenancy-manager
It generates a new RBAC for multitenancy-manager
```changes
type: fix
summary: Regeneration RBAC for multitenancy-manager.
```
=> [deckhouse] regenerate rbac for multitenancy-manager

testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
optimizing the cost of master node in yc
Reducing the cost of one test run in yandex.
https://github.com/deckhouse/deckhouse/issues/5975
```changes
type: fix
summary: optimizing the cost of master node in yc
```
=> [testing] optimizing the cost of master node in yc

candi/terraform_versions.yml, dhctl/pkg/kubernetes/actions/converge/converge.go, ee/candi/cloud-providers/dynamix/terraform-modules/master-node/main.tf, ee/candi/cloud-providers/dynamix/terraform-modules/static-node/main.tf, ee/candi/cloud-providers/dynamix/terraform-modules/versions.tf, ee/modules/030-cloud-provider-dynamix/hooks/discover.go, ee/modules/030-cloud-provider-dynamix/images/cloud-controller-manager/src/go.mod, ee/modules/030-cloud-provider-dynamix/images/cloud-controller-manager/src/go.sum, ee/modules/030-cloud-provider-dynamix/images/cloud-data-discoverer/go.mod, ee/modules/030-cloud-provider-dynamix/images/cloud-data-discoverer/go.sum, ee/modules/030-cloud-provider-dynamix/images/dynamix-common/go.mod, ee/modules/030-cloud-provider-dynamix/images/dynamix-common/go.sum, ee/modules/030-cloud-provider-dynamix/images/dynamix-csi-driver/src/go.mod, ee/modules/030-cloud-provider-dynamix/images/dynamix-csi-driver/src/go.sum
=> Cloud provider dynamix terraform

ee/modules/030-cloud-provider-dynamix/hooks/discover.go, ee/modules/030-cloud-provider-dynamix/hooks/ensure_instance_class.go, ee/modules/030-cloud-provider-dynamix/hooks/wait_for_all_master_nodes_to_become_initialized.go, ee/modules/030-cloud-provider-dynamix/templates/cloud-controller-manager/secret.yaml, ee/modules/030-cloud-provider-dynamix/templates/cloud-data-discoverer/deployment.yaml, ee/modules/030-cloud-provider-dynamix/templates/csi/storage-classes.yaml, testing/matrix/linter/rules/modules/oss.go, testing/openapi_validation/validators/enum.go
=> [dynamix] fix linters and tests

deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/patch-release-notification.yaml
Re-generate golden files
```changes
type: fix
summary: Fix unit test.
```
=> [deckhouse-controller] Test hotfix

modules/040-node-manager/images/capi-controller-manager/werf.inc.yaml
Update capi controller manager version to 1.7.
Fix memory leak in capi-controller-manager.
```changes
type: feature
summary: Update `capi-controller-manager` to version `1.7`.
```
=> [node-manager] capi controller manager version update

deckhouse-controller/pkg/controller/deckhouse-release/controller.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/dev-have-new-deckhouse-image.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/dev-no-new-deckhouse-image.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/dev-have-new-deckhouse-image.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/dev-no-new-deckhouse-image.yaml, deckhouse-controller/pkg/controller/deckhouse-release/update_by_image_hash_test.go
Fixed artifacts remaining from previous versions where snapshots were used
Deckhouse controller could fail with panic if we have some Pending/Terminating deckhouse pod
Deckhouse controller could fail with panic if we have some Pending/Terminating deckhouse pod
```changes
type: fix
summary: Fixed panic when processing terminating deckhouse pod
```
=> [deckhouse-controller] Fixed tag update

modules/040-node-manager/hooks/instance_controller.go
Fix instance-controller hook.
Reduce fields in instance filter to prevent hook start on changing managed fields.
```changes
type: chore
summary: Fix instance controller hook.
```
=> [node-manager] fix instance controller hook

modules/002-deckhouse/templates/webhook-handler/deployment.yaml
Set tmpfs for webhooh-handler's /tmp dir
Tmp files are taking too much time for hooks execution
```changes
type: fix
summary: Use tmpfs for hooks execution dir.
```
=> [dckhouse] Update deployment.yaml for webhook-handler

deckhouse-controller/pkg/controller/deckhouse-release/controller.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/dev-have-new-deckhouse-image.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/dev-no-new-deckhouse-image.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/dev-have-new-deckhouse-image.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/dev-no-new-deckhouse-image.yaml, deckhouse-controller/pkg/controller/deckhouse-release/update_by_image_hash_test.go
Cherry pick for https://github.com/deckhouse/deckhouse/pull/9621
=> [deckhouse-controller] Fixed tag update backport to release1.63

dhctl/pkg/operations/bootstrap/cluster-bootstrapper-deckhouse.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper-resources.go, global-hooks/discovery/kubernetes_version.go, modules/002-deckhouse/templates/validation.yaml, modules/040-node-manager/templates/machine-controller-manager/validation.yaml, modules/150-user-authn/templates/validation.yaml, modules/402-ingress-nginx/templates/validation.yaml
Fixed SIGSEGV in dhctl during specific bootstrap conditions.
This fixes bootstrap in EKS and install-deckhouse phase in general.
```changes
section: dhctl
type: fix
summary: Fix SSH client startup in Deckhouse installation phase.
```
=> [dhctl] Fix ssh client startup in deckhouse installation phase

dhctl/pkg/kubernetes/actions/resources/resources.go
Revert  https://github.com/deckhouse/deckhouse/pull/9157
Affect DKP == 1.63
For DKP >= 1.64 fixed here https://github.com/deckhouse/deckhouse/pull/9714
Creating resources fail with timeout error in some cases.
Creating resources fail with timeout error in some cases.
```changes
section: dhctl
type: fix
summary: Revert ensure required namespaces while resources creation.
```
=> [dhctl] Revert ensure required namespaces while resources creation

ee/modules/030-cloud-provider-dynamix/hooks/discover.go, ee/modules/030-cloud-provider-dynamix/openapi/values.yaml, ee/modules/030-cloud-provider-dynamix/templates/csi/controller.yaml, ee/modules/030-cloud-provider-dynamix/templates/csi/storage-classes.yaml, go_lib/cloud-data/apis/v1/dynamix_cloud_provider_discovery_data.go
=> [dynamix] expansion csi

dhctl/pkg/operations/secretedit.go
Changed `dhctl edit *cluster-configuration` logic to create empty configuration secrets if they are missing from cluster instead of failing with error.
This improves UX of out tooling.
```changes
section: dhctl
type: feature
summary: Upon editing configuration secrets, create them if they are missing from cluster
```
=> [dhctl] Upon editing configuration secrets, create them if they are missing from cluster

ee/candi/cloud-providers/dynamix/openapi/instance_class.yaml, ee/modules/030-cloud-provider-dynamix/capi/instance-class.checksum, ee/modules/030-cloud-provider-dynamix/capi/machine-template.yaml, ee/modules/030-cloud-provider-dynamix/crds/external/dynamixclusters.yaml, ee/modules/030-cloud-provider-dynamix/crds/external/dynamixmachines.yaml, ee/modules/030-cloud-provider-dynamix/crds/external/dynamixmachinetemplates.yaml, ee/modules/030-cloud-provider-dynamix/images/capd-controller-manager/werf.inc.yaml
=> Dynamix add the external network name field to the DynamixInstanceClass

ee/candi/cloud-providers/dynamix/layouts/standard-with-internal-network/base-infrastructure/main.tf, ee/candi/cloud-providers/dynamix/layouts/standard-with-internal-network/base-infrastructure/outputs.tf, ee/candi/cloud-providers/dynamix/layouts/standard-with-internal-network/base-infrastructure/providers.tf, ee/candi/cloud-providers/dynamix/layouts/standard-with-internal-network/base-infrastructure/variables.tf, ee/candi/cloud-providers/dynamix/layouts/standard-with-internal-network/base-infrastructure/versions.tf, ee/candi/cloud-providers/dynamix/layouts/standard-with-internal-network/master-node, ee/candi/cloud-providers/dynamix/layouts/standard-with-internal-network/static-node, ee/candi/cloud-providers/dynamix/openapi/cluster_configuration.yaml, ee/candi/cloud-providers/dynamix/terraform-modules/master-node/main.tf, ee/candi/cloud-providers/dynamix/terraform-modules/master-node/outputs.tf, ee/candi/cloud-providers/dynamix/terraform-modules/static-node/main.tf, ee/modules/030-cloud-provider-dynamix/images/cloud-controller-manager/werf.inc.yaml, ee/modules/030-cloud-provider-dynamix/openapi/values.yaml
=> [dynamix] standard with internal network

dhctl/pkg/operations/bootstrap/steps.go
Break circle goroutines if get error on check dependencies, examp. not exist bin file or tcp interrupt connection
this allow to break 30 attempts check dependencies on error and log it to output
check dependencies finish on first error and output log in terminal
```changes
section: dhctl
type: fix
summary: Break circle and output error in log on check dependencies if get first error
```
=> [dhctl] Break circle and output error in log on check dependencies if get first error

testing/cloud_layouts/script.sh
Add retry for e2e test requirements.
Test can be failed multiple times  
```changes
type: chore
summary: Retry test requirements if it was failed
```
=> [testing] Retry test requirements if it was failed

docs/site/_includes/getting_started/global/partials/NOTICES.liquid
The alert on the private environment page has been changed.
```changes
section: docs
type: fix
summary: Update notes for bare metal in the Getting started.
```
=> [docs][gs] Update notes for bare metal

modules/800-deckhouse-tools/hooks/https/copy_custom_certificate.go
Fixed module name in values declaration for hook that handles certificates copying.
This fixes `deckhouse-tools` module in clusters with self-signed certs
```changes
type: fix
summary: Fix custom certs copying.
```
=> [deckhouse-tools] Fix custom certs copying

modules/460-log-shipper/images/vector/werf.inc.yaml
```changes
type: chore
summary: build adapted for cse edition
```
=> [log-shipper] build adapted for cse edition

modules/200-operator-prometheus/images/prometheus-config-reloader/werf.inc.yaml, modules/200-operator-prometheus/images/prometheus-operator/patches/004_go_mod.patch, modules/200-operator-prometheus/images/prometheus-operator/patches/README.md, modules/200-operator-prometheus/images/prometheus-operator/werf.inc.yaml
```changes
section: prometheus-operator
type: chore
summary: build adapted for cse edition
```
=> [prometheus-operator] build adapted for cse edition

modules/340-monitoring-kubernetes/images/kube-state-metrics/werf.inc.yaml, modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/werf.inc.yaml, modules/340-monitoring-kubernetes/images/node-exporter/werf.inc.yaml
```changes
type: chore
summary: build adapted for cse edition
```
=> [monitoring-kubernetes] build adapted for cse edition

modules/039-registry-packages-proxy/images/registry-packages-proxy/werf.inc.yaml
```changes
section: registry-packages-proxy
type: chore
summary: build adapted for cse edition
```
=> [registry-packages-proxy] build adapted for cse edition

modules/000-common/images/csi-external-snapshotter/werf.inc.yaml
```changes
type: chore
summary: fixed cve in snapshot-controller images
```
=> [snapshot-controller] fixed cve in snapshot-controller images

modules/150-user-authn/images/dex-authenticator/werf.inc.yaml, modules/150-user-authn/images/dex/werf.inc.yaml, modules/150-user-authn/images/kubeconfig-generator/patches/dep-upgrade.patch, modules/150-user-authn/images/kubeconfig-generator/werf.inc.yaml, modules/150-user-authn/images/self-signed-generator/src/go.mod, modules/150-user-authn/images/self-signed-generator/src/go.sum
=> [user-authn] fix cve and warnings

modules/402-ingress-nginx/images/controller-1-10/werf.inc.yaml
=> DO NOT MERGE! debug ingress nginx

docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA.liquid, docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA_RU.liquid
Fix broken links in the Getting Started
=> [gs][doc] Fix broken links

modules/035-cni-flannel/images/flanneld/werf.inc.yaml
=> [cni-flannel] permission denied fix

ee/be/modules/350-node-local-dns/images/coredns/werf.inc.yaml
=> [node-local-dns] cse path fix

candi/bashible/common-steps/node-group/002_create_static_node_cleanup_script.sh.tpl
Replaced the async reboot script with a delayed reboot command in static node cleanup scripts.
Closes https://github.com/deckhouse/deckhouse/issues/8509
```changes
section: candi
type: fix
summary: reboot static node with a delay on cleanup
```
=> [candi] reboot static node with a delay on cleanup

dhctl/pkg/system/node/ssh/frontend/kube-proxy.go, modules/002-deckhouse/templates/validation.yaml
Prohibit to change resources with the label `heritage: deckhouse` from the `kubernetes-admin` user
```changes
type: feature
summary: Prohibit to change resources with the label `heritage: deckhouse` even from the `kubernetes-admin` user.
```
=> [deckhouse] Prohibit to change deckhouse resources

docs/documentation/werf.yaml, docs/site/werf.yaml, modules/810-documentation/images/web/werf.inc.yaml
- Use prebuild base image for Jekyll
- Consolidated module copying commands into a single loop.
- Enhanced werf.yaml to use "Mode" and "Edition" settings.
- Added conditional logic for Jekyll image and environment modes.
- Updated shell commands to reflect new environment variable usage.
```changes
section: docs, documentation
type: chore
summary: Update build rules.
```
=> [docs][documentation] Update build rules

.github/ci_templates/e2e_tests.yml, .github/workflows/e2e-abort-aws.yml, .github/workflows/e2e-abort-azure.yml, .github/workflows/e2e-abort-eks.yml, .github/workflows/e2e-abort-gcp.yml, .github/workflows/e2e-abort-openstack.yml, .github/workflows/e2e-abort-static.yml, .github/workflows/e2e-abort-vcd.yml, .github/workflows/e2e-abort-vsphere.yml, .github/workflows/e2e-abort-yandex-cloud.yml
Fix whitespace in e2e-abort pipeline.
Incorrect whitespace breaks the pipeline
Working pipeline
```changes
section: ci
type: fix
summary: Fix whitespace in e2e-abort pipeline.
```
=> [ci] Fix whitespace in e2e-abort pipeline

docs/documentation/werf.yaml, docs/site/werf.yaml
=> [site] Fix topnav menu items

docs/site/werf.yaml
=> [docs] Fix site menu generation

modules/000-common/images/python-static/patches/README.md, modules/000-common/images/python-static/patches/setuptools.patch, modules/000-common/images/python-static/werf.inc.yaml
```changes
type: fix 
summary: cve fix in python-static
```
=> [common] cve fix in python-static

.github/ci_templates/web.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml, docs/documentation/werf-git-section.inc.yaml, docs/documentation/werf.yaml, docs/site/werf.yaml, modules/810-documentation/images/web/werf.inc.yaml
- Changed .Env to .Edition in werf-git-section.inc.yaml
- Set default .Env to "EE" in werf.inc.yaml and werf.yaml
- Added .Mode and .Edition variable handling in werf.inc.yaml
- Updated CI templates to include WERF_ENV as "EE"
```changes
section: ci, docs
type: chore
summary: Update site build rules.
```
=> [docs] Update site build rules

.github/ci_templates/loop-alerting.yaml, .github/workflows/e2e-daily.yml
Fix for sending messages
Set quotes :)
Message is send
```changes
section: ci
type: fix
summary: Fix for sending loop messages.
```
=> fix: loop alert

ee/modules/030-cloud-provider-dynamix/templates/cloud-data-discoverer/pod-monitor.yaml
=> [dynamix] pod monitor condition

docs/site/css/components/common/_variables.scss, docs/site/css/docs.scss, docs/site/css/syntax.css
Fix font size and color of texts and titles in main styles.
```changes
section: docs
type: chore
summary: Fix font size and color of texts and titles in main styles.
```
=> [site] Fix font size and color of texts and titles in main styles

modules/000-common/images/shell-operator/werf.inc.yaml
Bump shell-operator
Micro optimizations for the webhook-handlers conversion webhooks
```changes
type: chore
summary: Bump shell-operator to optimize conversion hooks in the webhook-handler.
```
=> [common] Bump shell-operator

modules/402-ingress-nginx/images/controller-1-10/patches/nginx-build.patch, modules/402-ingress-nginx/images/controller-1-10/patches/nginx-tmpl.patch
=> Cse release 1.64 ingress nginx closed env

docs/documentation/werf.yaml, docs/site/werf-debug.yaml, docs/site/werf-docs-builder.inc.yaml, docs/site/werf.yaml, modules/810-documentation/images/web/werf.inc.yaml, werf.yaml
migrate from ansible to shell in werf
```changes
section: ci
type: chore
summary: Migrate from ansible to Shell in werf.
```
=> [ci] migrate from ansible to shell in werf

docs/documentation/_includes/sidebar.html, docs/documentation/_includes/sitemap.liquid, docs/documentation/_plugins/openapi.rb, docs/documentation/generate_cluster_configuration.sh, docs/documentation/modules_generate_configuration.sh, docs/documentation/modules_generate_cr.sh
- Modify moduleconfig parameters structure to allow collapsing in the documentation.
- Don't generate sitemap and sidebar in the documentation 'development' mode to speed up the build.
```changes
section: docs
type: chore
summary: Update OpenAPI generator
```
=> [docs] Update OpenAPI generator

.github/ci_includes/werf_envs.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml, tools/images_tags/main.go, werf-giterminism.yaml, werf.yaml
Add OBSERVABILITY_SOURCE_REPO env
Need to build images from observability private repo
```changes
section: ci
type: chore
summary: add OBSERVABILITY_SOURCE_REPO for build observability projects
```
=> [ci] add OBSERVABILITY_SOURCE_REPO for build observability projects

modules/040-node-manager/crds/doc-ru-node_group.yaml
Correct an inaccuracy in the nodegroup documentation
```changes
section: docs
type: chore
summary: Fix documentation for fencing nodegroup parameter
```
=> [node-manager] fix nodegroup fencing docs

werf-giterminism.yaml, werf.yaml
OBSERVABILITY_SOURCE_REPO fix. Forget dot before it.
Pipeline failed
```changes
section:cci
type: fix
summary: OBSERVABILITY_SOURCE_REPO fix
```
=> [CI] OBSERVABILITY_SOURCE_REPO fix

Makefile
`make build-render` returns many errors
Fix generation errors
`make build-render` runs without errors
```changes
section: ci
type: fix
summary: Fix werf generation errors.
```
=> fix: werf files

modules/500-dashboard/openapi/config-values.yaml, modules/500-dashboard/templates/dashboard/authenticator.yaml
Add similar authorization mechanism as we have in other modules
Users always ask whether we have allowed groups for the dashboard module. To stop explaining, it is easier to add the option.
```changes
type: feature
summary: Add auth.allowedUserGroups option. Now it is possible to authorize user access based on their groups.
```
=> [dashboard] Add auth.allowedUserGroups option

.github/workflow_templates/check-pr-milestone.yml, .github/workflows/check-pr-milestone.yml
Milestone check doesn't always work now
Add additional launch rules to check the milestone.
Not related for release
Milestone check is triggered when a milestone is added.
```changes
section: ci
type: fix
summary: Add additional launch rules to check the milestone.
```
=> fix: check milestone run action

modules/030-cloud-provider-yandex/docs/CONFIGURATION_RU.md
Fix table in the cloud-provider-yandex documentation.
```changes
type: fix
summary: Fix table in the documentation.
```
=> [docs] Fixed table at yandex cloud settings.

docs/site/_data/copyright.json, docs/site/_data/footer.json, docs/site/_data/topnav-l2-products.json, docs/site/_data/topnav.json, docs/site/_includes/header.html, docs/site/werf.yaml
Add the second level menu in the header.
```changes
section: docs
type: chore
summary: Add the second level menu in the header.
```
=> [docs] Add second level menu in the header

docs/site/css/syntax.css
Update style for highlighting code blocks.
```changes
section: docs
type: chore
summary: Update style for highlighting code blocks.
```
=> [docs] Add new code theme

modules/000-common/images/csi-external-provisioner/patches/v5.1.0/001-go-mod.patch, modules/000-common/images/csi-external-provisioner/werf.inc.yaml, modules/000-common/images/redis-static/werf.inc.yaml, modules/000-common/images/shell-operator/werf.inc.yaml, werf.yaml
=> [common] fixed cve in src

modules/300-prometheus/images/grafana-v10/patches/001-go-mod.patch, modules/300-prometheus/images/grafana-v10/werf.inc.yaml, modules/300-prometheus/images/mimir/werf.inc.yaml, modules/300-prometheus/images/prometheus/werf.inc.yaml, modules/300-prometheus/images/trickster/werf.inc.yaml
=> [prometheus] fixed cve in src

ee/modules/030-cloud-provider-dynamix/hooks/get_cni_secret.go, ee/modules/030-cloud-provider-dynamix/templates/cni.yaml
=> Dynamix cni

docs/site/css/docs.scss
Fix styles in the documentation.
```changes
section: docs
type: chore
summary: Fix styles in the documentation.
```
=> [docs] Fix width columns of search answers

docs/documentation/pages/module-development/STRUCTURE.md, docs/documentation/pages/module-development/STRUCTURE_RU.md
Corrected mistakes in Python code and fix style using PIP8 specification.
Incorrect documentation.
Correct documentation.
```changes
section: docs
type: chore
summary: Fix Platform/v1/Module_structure hooks Python code example. 
```
=> [docs] Fix Platform/v1/Module_structure hooks Python code example

ee/candi/cloud-providers/dynamix/openapi/cluster_configuration.yaml, ee/candi/cloud-providers/dynamix/terraform-modules/master-node/main.tf, ee/candi/cloud-providers/dynamix/terraform-modules/static-node/main.tf, ee/modules/030-cloud-provider-dynamix/openapi/values.yaml, modules/040-node-manager/crds/instance.yaml
=> [dynamix] layout fix

modules/110-istio/docs/ISTIO-CR.md, modules/110-istio/docs/ISTIO-CR_RU.md
Add conditions reference, fix links on actual DKP istio version - v1.19
```changes
section: docs
type: fix
summary: Add conditions reference, fix links on actual DKP istio version - v1.19
```
=> [docs] Some improves istio docs - Custom Resources (by istio.io)

modules/040-control-plane-manager/openapi/config-values.yaml, modules/040-control-plane-manager/openapi/doc-ru-config-values.yaml
Fixed info at apiserver.certSANs spec.
```changes
section: docs
type: chore
summary: Fixed info at apiserver.certSANs spec.
```
=> [docs] Fixed info at apiserver.certSANs spec

deckhouse-controller/pkg/controller/controller.go, deckhouse-controller/pkg/controller/deckhouse-release/check_release.go, deckhouse-controller/pkg/controller/deckhouse-release/client_test.go, deckhouse-controller/pkg/controller/deckhouse-release/controller.go, deckhouse-controller/pkg/controller/deckhouse-release/controller_test.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/auto-patch-minor-update.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/auto-patch-patch-update.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/auto-patch-minor-update.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/auto-patch-patch-update.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/patch-release-with-apply-now-annotation-out-of-window.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-with-apply-now-annotation-disruption.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-with-apply-now-annotation-requirements.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/patch-release-with-apply-now-annotation-out-of-window.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/release-with-apply-now-annotation-disruption.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/release-with-apply-now-annotation-requirements.yaml, deckhouse-controller/pkg/controller/deckhouse-release/updater/updater.go, deckhouse-controller/pkg/controller/module-controllers/docbuilder/docs_controller.go, deckhouse-controller/pkg/controller/module-controllers/release/controller.go, deckhouse-controller/pkg/controller/module-controllers/release/override-controller.go, deckhouse-controller/pkg/controller/module-controllers/release/updater.go, deckhouse-controller/pkg/controller/module-controllers/source/controller.go, deckhouse-controller/pkg/controller/module-controllers/utils/utils.go, deckhouse-controller/pkg/registry/registry.go, go_lib/updater/notification.go, go_lib/updater/settings.go, go_lib/updater/updater.go, go_lib/updater/updater_test.go
Fixed update logic in various modes
Close https://github.com/deckhouse/deckhouse/issues/10000
```changes
type: fix
summary: Fixed update logic in various modes
```
=> [deckhouse-controller] Fixed update.windows for the new DeckhouseRelease update logic

ee/modules/010-metallb-crd/crds/bfdprofiles.yaml, ee/modules/010-metallb-crd/crds/bgpadvertisements.yaml, ee/modules/010-metallb-crd/crds/bgppeers.yaml, ee/modules/010-metallb-crd/crds/communities.yaml, ee/modules/010-metallb-crd/crds/ipaddresspools.yaml, ee/modules/010-metallb-crd/crds/l2advertisements.yaml, ee/modules/010-metallb-crd/crds/servicel2statuses.yaml, ee/se/modules/380-metallb/templates/speaker/daemonset.yaml, ee/se/modules/380-metallb/templates/speaker/rbac-for-us.yaml
=> [metallb] Some fixes after upgrade to 0.14.8

modules/150-user-authn/templates/kubeconfig-generator/oauth2client.yaml
Add the /device/callback url to be able to authorize with https://auth0.com/docs/get-started/authentication-and-authorization-flow/device-authorization-flow
This is required to use kubeconfig + kubelogin on servers without a browsed
```changes
type: feature
summary: Allow device flow for Kubernets API
```
=> [user-authn] Allow device flow for Kubernets API

modules/040-control-plane-manager/hooks/label_heritage_on_kube_system.go, modules/040-control-plane-manager/hooks/label_heritage_on_kube_system_test.go
set label "heritage: deckhouse" in namespace kube-system when hook on synchronization deckhouse
it solve issue https://github.com/deckhouse/deckhouse/issues/6157
namespace kube-system is hovered by label "heritage: deckhouse"
```changes
type: fix
summary: Label "heritage: deckhouse" in namespace kube-system
```
=> [control-plane-manager] Label "heritage: deckhouse" in namespace kube-system

docs/site/_includes/header.html, docs/site/css/docs.scss
=> [docs] Add shadow for header

modules/110-istio/docs/README.md
Improvement of the Istio Federation documentation to reduce the empty item.
```changes
section: istio
type: chore
summary: Removal an empty item in the Istio Federation configuration
```
=> [docs] Removal an empty item in the Istio Federation configuration

ee/modules/500-operator-trivy/openapi/config-values.yaml, ee/modules/500-operator-trivy/openapi/doc-ru-config-values.yaml, global-hooks/openapi/config-values.yaml, global-hooks/openapi/doc-ru-config-values.yaml
Update trivy documentation with wide description about storageClass.
```changes
section: trivy
type: fix
summary: Add wide description about trivy storageClass usage
```
=> [docs][trivy] Add wide description about trivy storageClass usage

.github/workflow_templates/check-pr-milestone.yml, .github/workflows/check-pr-milestone.yml
```changes
section: ci
type: fix
summary: Add more reactions for check milestone job: reopened and synchronize (to trigger job when it is needed).
```
=> [ci] Add more reactions for check milestone job

ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/helm/main_test.go
It provides fix for a multitenancy-manager test.
A new function did not call in tests.
Tests work fine.
```changes
type: fix
summary: Fix multitenancy-manager.
```
=> [mulitenancy-manager] fix test

modules/040-control-plane-manager/docs/FAQ.md, modules/040-control-plane-manager/docs/FAQ_RU.md
```changes
type: fix
summary: Minor documentation updates
```
=> [docs][control-plane-manager] Minor documentation updates

modules/140-user-authz/hooks/handle_manage_bindings.go
It provides a lint fix.
```changes
type: fix
summary: Lint fix.
```
=> [user-authz] fix lint

modules/040-control-plane-manager/docs/FAQ.md, modules/040-control-plane-manager/docs/FAQ_RU.md
Correcting the file name in backup control plan manager.
```changes
type: chore
summary: Minor documentation fixes.
```
=> [Docs] Correcting the file name in backup control plan manager

docs/site/_includes/header.html, docs/site/_layouts/default.html, docs/site/js/customscripts.js
Fixed blinking of the docs button on the gs page.
```changes
section: docs
type: fix
summary: Fix blinking of the docs button in the Getting started and the Guide.
```
=> [docs] Fixed blinking of the docs button on the gs page

.github/CODEOWNERS
```changes
section: ci
type: chore
summary: Fix CODOWNERS
```
=> [ci] Fix codeowners

candi/cloud-providers/aws/openapi/cluster_configuration.yaml, candi/cloud-providers/azure/openapi/cluster_configuration.yaml, candi/cloud-providers/gcp/openapi/cluster_configuration.yaml, candi/cloud-providers/yandex/openapi/cluster_configuration.yaml, ee/candi/cloud-providers/openstack/openapi/cluster_configuration.yaml, ee/candi/cloud-providers/vcd/openapi/cluster_configuration.yaml, ee/candi/cloud-providers/vsphere/openapi/cluster_configuration.yaml, ee/candi/cloud-providers/zvirt/openapi/cluster_configuration.yaml
This merge request updates the validation process to allow modifications on master nodeGroups.
```changes
section: dhctl
type: feature
summary: Remove validation rules to enable master nodegroup auto converge
```
=> [dhctl] feat(dhctl-for-commander): remove masterNodeGroup unsafe rules

modules/402-ingress-nginx/monitoring/grafana-dashboards/ingress-nginx/vhost/vhost_detail.json
- Update `VHost Detail` dashboard panel types.
- Improve heatmap panels readability
```changes
type: chore
summary: Minor VHost dashboard improvements
```
=> [ingress-nginx] Update VHost dashboards

docs/site/_config.yml
Fix Jekyll config.
Ref: https://github.com/deckhouse/deckhouse/pull/10595
```changes
section: docs
type: chore
summary: Fix Jekyll config.
```
=> Fix Jekyll config

docs/site/_includes/header.html
There is a bug in the top menu. Fix topnav in the documentation.
```changes
type: fix
summary: Fix topnav in the documentation
```
=> [documentation] Fix topnav in the documentation

docs/site/_includes/header.html
Return language switcher button
Ref: https://github.com/deckhouse/deckhouse/pull/10608
```changes
type: chore
summary: Return language switcher button.
```
=> [documentation] Return language switcher button

testing/cloud_layouts/script.sh
fixed $python_binary
```changes
type: fix 
summary: fixed $python_binary
```
=> [testing] fixed $python_binary

docs/documentation/.werf/nginx.conf
Fix incorrect redirect.
Ref: https://github.com/deckhouse/deckhouse/pull/10561
Some assets may not load.
```changes
section: docs
type: chore
summary: Fix assets loading
```
=> [docs][documentation] fix assets loading

docs/site/backends/docs-builder-template/layouts/partials/openapi/format-schema.html
Revert 6ba1977b28817c5b3bcb9b1862d85781ac0a6e9f
=> [docs] Revert changes from the 6ba1977b28817c5b3bcb9b1862d85781ac0a6e9f

ee/modules/030-cloud-provider-vsphere/docs/EXAMPLES.md, ee/modules/030-cloud-provider-vsphere/docs/EXAMPLES_RU.md
Fix unknown field in InstanceClass example
Fix unknown field that lead to misunderstanding
```changes
section: docs
type: fix
summary: Fix spec. network name for VSphere
```
=> [docs][cloud-provider-vsphere] Fix spec. network name for VSphere

docs/documentation/_data/editions-addition.json, docs/documentation/_data/modules/modules-addition.json
Update modules and editions data files.
```changes
section: docs
type: chore
summary: Update modules and editions data files.
```
=> [docs] Update modules and editions data files

dhctl/Makefile, dhctl/pkg/config/deckhouse_config.go, dhctl/pkg/kubernetes/actions/deckhouse/install_test.go, dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
Fix duplicate import.
Fix after merge #10688
Main cannot build
```changes
section: dhctl
type: fix
summary: Fix imports
```
=> [dhctl] Fix imports

modules/000-common/images/shell-operator/werf.inc.yaml
Bump shell-operator image
Logrus in the previous version has memory leak in the loaded environments
Avoid memory leak
```changes
type: fix
summary: Bump shell-operator image.
impact: Fix webhook-handler memory leak.
```
=> [common] Bump shell-operator version for common/shell-operator image

ee/candi/cloud-providers/huaweicloud/layouts/standard/base-infrastructure/main.tf, ee/candi/cloud-providers/huaweicloud/layouts/standard/base-infrastructure/outputs.tf, ee/candi/cloud-providers/huaweicloud/layouts/standard/static-node/main.tf, ee/candi/cloud-providers/huaweicloud/layouts/standard/static-node/providers.tf, ee/candi/cloud-providers/huaweicloud/layouts/standard/static-node/variables.tf, ee/candi/cloud-providers/huaweicloud/layouts/standard/static-node/versions.tf, ee/candi/cloud-providers/huaweicloud/openapi/cloud_discovery_data.yaml, ee/candi/cloud-providers/huaweicloud/openapi/cluster_configuration.yaml, ee/candi/cloud-providers/huaweicloud/terraform-modules/network-security/outputs.tf, ee/candi/cloud-providers/huaweicloud/terraform-modules/static-node/main.tf, ee/candi/cloud-providers/huaweicloud/terraform-modules/static-node/variables.tf, ee/candi/cloud-providers/huaweicloud/terraform-modules/static-node/versions.tf, ee/modules/030-cloud-provider-huaweicloud/openapi/values.yaml
=> [huaweicloud] static-node

modules/000-common/images/shell-operator/werf.inc.yaml
Bump shell-operator image
Logrus in the previous version has memory leak in the loaded environments
Avoid memory leak
```changes
type: fix
summary: Bump shell-operator image.
impact: Fix webhook-handler memory leak.
```
=> Bump shell-operator version for common/shell-operator image

modules/500-openvpn/images/ovpn-admin/werf.inc.yaml
Repository https://github.com/palark/ovpn-admin is no longer updated.
Switch module build to current repository
The module is built from a new repository
```changes
type: chore
summary: Switch module build to current repository.
```
=> chore: change ovpn-adm source

docs/documentation/_data/supported_versions.yml
The Quay note has added information about the version with which additional actions are needed.
```changes
section: docs
type: fix
summary: The Quay note has added information about the version with which additional actions are needed.
```
=> [docs] Improvement of the Quay note in supported versions

docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS.md, docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS_RU.md
Fixed the link to the `publicDomainTemplate` parameter in step 5 of the GS.
```changes
section: docs
type: fix
summary: |
Fixed the link to the `publicDomainTemplate` parameter in step 5 of the GS.
```
=> [docs][getting-started] Fix links on the step five page in getting started

modules/500-openvpn/images/ovpn-admin/werf.inc.yaml
Fixed double rm
```changes
type: fix 
summary: fixed double rm
```
=> [openvpn] fixed double rm

docs/site/css/docs.scss
Fix padding for the light large Tippy theme on the site
```changes
section: docs
type: chore
summary: Fix padding for the light large Tippy theme on the site
```
=> [docs] Fix padding for light large tippy theme

ee/modules/500-operator-trivy/images/report-updater/cache/cache.go, ee/modules/500-operator-trivy/images/report-updater/go.mod, ee/modules/500-operator-trivy/images/report-updater/main.go, ee/modules/500-operator-trivy/images/report-updater/web/hook/hook.go, ee/modules/500-operator-trivy/images/report-updater/web/server.go, ee/modules/500-operator-trivy/templates/report-updater/configmap.yaml, ee/modules/500-operator-trivy/templates/report-updater/deployment.yaml
Updates report-updater to support insecure/customCA registries and fixes the bug when the db registry is set with a custom port.
Closes #10711 
Report-updater is able to get its database from a wider range of registry configurations.
```changes
type: chore
summary: Update report-updater to support insecure/customCA registries.
```
=> [operator-trivy] update report-updater

docs/documentation/pages/SECURITY_SOFTWARE_SETUP.md, docs/documentation/pages/SECURITY_SOFTWARE_SETUP_RU.md
Added KESL documentation for Security software settings doc.
```changes
section: docs
type: chore
summary: Added KESL documentation for Security software settings doc.
```
=> [docs] Added KESL documentation for Security software settings doc

modules/015-admission-policy-engine/webhooks/validating/security_policy.py
=> Fix self check

.github/ci_includes/werf_envs.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml, .werf/werf-modules.yaml, candi/version_map.yml, modules/007-registrypackages/images/d8/werf.inc.yaml, modules/800-deckhouse-tools/images/web/werf.inc.yaml, tools/images_tags/main.go, werf-giterminism.yaml, werf.yaml
Updated Deckhouse CLI to v0.6.1 which brings new CLI for Stronghold and bug fixes
```changes
section: candi
type: chore
summary: Update Deckhouse CLI to v0.6.1
```
=> [ci][registrypackages] Update Deckhouse CLI to v0.6.1

docs/documentation/pages/SECURITY_SOFTWARE_SETUP.md, docs/documentation/pages/SECURITY_SOFTWARE_SETUP_RU.md
Minor documentation changes.
```changes
section: docs
type: fix 
summary: Minor documentation changes.
```
=> [docs] Updated text at KESL documentation

deckhouse-controller/crds/module.yaml
It provides fix
Some clusters can have old main with incorrect phases.
No error 
```changes
type: fix
summary: Fix module phases
```
=> [deckhouse] fix phases

docs/site/pages/virtualization-platform/documentation/admin/platform-management/network/INGRESS.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/network/INGRESS_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/network/NTP.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/network/NTP_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/network/ROUTING.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/network/ROUTING_RU.md
Translated incoming traffic and routing management articles in the section of DVP docs for admins to English.
```changes
section: docs
type: chore
summary: Update DVP documentation.
```
=> [docs] Update DVP documentation

helm_lib/Chart.lock, helm_lib/Chart.yaml, helm_lib/charts/deckhouse_lib_helm/Chart.yaml, helm_lib/charts/deckhouse_lib_helm/templates/_csi_controller.tpl, helm_lib/charts/deckhouse_lib_helm/templates/_csi_node.tpl, helm_lib/charts/deckhouse_lib_helm/templates/_node_affinity.tpl
Update helm lib to 1.37.1 which brings new tolerations for CSI components. Closes https://github.com/deckhouse/deckhouse/issues/10332
This allows CSI daemonset to keep it's pods on the drained nodes and unmount PV's properly
```changes
type: fix
summary: Updated helm_lib to 1.37.1, which should fix issue #10332
```
=> [helm_lib] Update to v1.37.1

docs/site/_data/sidebars/virtualization-platform.yml, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/external/CEPH.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/external/CEPH_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/external/NFS.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/external/NFS_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/external/YADRO.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/external/YADRO_RU.md
Update links in the documentation sidebar.
```changes
section: docs
type: chore
summary: Update links in the documentation sidebar.
```
=> [docs][dvp] update storage documentation links

docs/documentation/_data/sidebars/main.yml, docs/documentation/_includes/sidebar_entry.html, docs/site/_includes/sidebar_entry.html
Fix sidebar generation logic.
```changes
section: docs
type: chore
summary: Fix sidebar generation logic.
```
=> [docs] Fix sidebar generation logic

modules/150-user-authn/hooks/get_dex_client_crds.go, modules/150-user-authn/hooks/get_dex_client_crds_test.go
Extend list annotations helm.sh/ to delete from secret
Now annotation helm.sh/hook remove all meta.helm.sh from secret, PR fix this
```changes
type: fix 
summary: Extend list annotations helm.sh/ to delete from secret
```
=> [user-authn] Extend list annotations blacklist for transfer to dexclient secret

docs/site/_data/sidebars/virtualization-platform.yml
Fix sidebar for DVP.
```changes
section: docs
type: chore
summary: Fix sidebar for DVP.
```
=> [docs][dvp] Fix sidebar

ee/candi/cloud-providers/huaweicloud/openapi/cluster_configuration.yaml, ee/candi/cloud-providers/huaweicloud/openapi/doc-ru-cluster_configuration.yaml, ee/candi/cloud-providers/huaweicloud/openapi/doc-ru-instance_class.yaml, ee/modules/030-cloud-provider-huaweicloud/openapi/doc-ru-config-values.yaml, ee/modules/030-cloud-provider-huaweicloud/openapi/openapi-case-tests.yaml, ee/modules/030-cloud-provider-huaweicloud/openapi/values.yaml, testing/matrix/linter/rules/modules/oss.go, testing/matrix/matrix_test.go, testing/openapi_validation/validators/enum.go
=> [huaweicloud] matrix tests

docs/documentation/_data/sidebars/main.yml
Fix sidebar in the documentation.
```changes
section: docs
type: chore
summary: Fix sidebar in the documentation.
```
=> [docs] Fix sidebar

docs/documentation/_data/deckhouse-ports.yml
```changes
section: docs
type: chore
summary: Text revisions configuring network policies.
```
=> [docs] Text revisions configuring network policies

docs/documentation/_data/sidebars/main.yml
Fix sidebar for service-with-healthchecks module.
```changes
section: docs
type: chore
summary: Fix sidebar for service-with-healthchecks module
```
=> [docs] Fix sidebar for service-with-healthchecks module

docs/documentation/_data/sidebars/main.yml, docs/documentation/pages/security/KESL.md, docs/documentation/pages/security/KESL_RU.md, docs/documentation/pages/security/KUMA.md, docs/documentation/pages/security/KUMA_RU.md, docs/documentation/pages/security/SECURITY_SOFTWARE_SETUP.md, docs/documentation/pages/security/SECURITY_SOFTWARE_SETUP_RU.md, tools/spelling/dictionaries/dev_OPS.dic, tools/spelling/wordlist
The structure of the security pages in the cluster has been changed.
```changes
section: docs
type: fix
summary: The structure of the security pages in the cluster has been changed.
```
=> [docs] Improve pages about SIEM and KESL

testing/cloud_layouts/Yandex.Cloud/WithoutNAT/resources.yaml
Increase resources for e2e test on Yandex.
```changes
type: chore
summary: Increase resources for e2e test on Yandex.
```
=> [testing] Increase resources for e2e test on Yandex

docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
The command on the fifth step page has been fixed.
```changes
section: docs
type: fix
summary: The command on the fifth step page has been fixed.
```
=> [docs][getting-started] Small fix in step five of BM

modules/007-registrypackages/images/containerd/werf.inc.yaml
=> MERGE WITH ATTENTION move containerd to werf with source artifact

ee/modules/650-runtime-audit-engine/images/falco/werf.inc.yaml
=> MERGE WITH ATTENTION move runtime-audit-engine to src-artifact

ee/modules/650-runtime-audit-engine/images/falco/werf.inc.yaml, ee/modules/650-runtime-audit-engine/images/rules-loader/werf.inc.yaml, modules/000-common/images/alt-p11/werf.inc.yaml, modules/000-common/images/python-static/werf.inc.yaml, modules/000-common/images/shell-operator/werf.inc.yaml, modules/000-common/images/src-artifact/werf.inc.yaml, modules/002-deckhouse/images/webhook-handler/werf.inc.yaml, modules/007-registrypackages/images/nvme-cli/werf.inc.yaml, modules/021-cni-cilium/images/base-cilium-dev/werf.inc.yaml, modules/300-prometheus/images/grafana-dashboard-provisioner/werf.inc.yaml
=> add alt p11 as base layer

ee/modules/650-runtime-audit-engine/images/falco/werf.inc.yaml, ee/modules/650-runtime-audit-engine/images/rules-loader/werf.inc.yaml, modules/000-common/images/python-static/werf.inc.yaml, modules/000-common/images/shell-operator/werf.inc.yaml, modules/000-common/images/src-artifact/werf.inc.yaml, modules/002-deckhouse/images/webhook-handler/werf.inc.yaml, modules/007-registrypackages/images/nvme-cli/werf.inc.yaml, modules/021-cni-cilium/images/base-cilium-dev/werf.inc.yaml, modules/300-prometheus/images/grafana-dashboard-provisioner/werf.inc.yaml
=> MERGE WITH ATTENTION fix werf common alpt image from

modules/040-node-manager/templates/node-group/_bootstrap.tpl
…load_phase2_script
```changes
```
=> MERGE WITH ATTENTION bootstrap stderr in load phase2 script

docs/site/_data/footer.json, docs/site/_data/topnav-l2-products.json, docs/site/_includes/header.html
Update the top navigation menu on the site.
```changes
section: docs
type: chore
summary: Update the top navigation menu on the site.
```
=> [site] Update the top navigation menu

.dmtlint.yaml, .github/ci_templates/tests.yml, .github/workflow_templates/build-and-test_dev.yml, .github/workflow_templates/build-and-test_pre-release.yml, .github/workflow_templates/build-and-test_release.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml, .werf/werf-test.yaml, Makefile, tools/dmt-lint.sh, werf.yaml
Current matrix tests do not cover all needs
For matrix tests an alternative solution is used
An alternative solution is used for tests
```changes
section: ci
type: chore
summary: For matrix tests an alternative solution is used.
```
=> chore: add dmt lint

.dmtlint.yaml, ee/se-plus/modules/030-cloud-provider-vsphere/openapi/values.yaml, go_lib/dependency/extenders/deckhouseversion/extender.go, modules/150-user-authn/openapi/values.yaml, modules/150-user-authn/templates/kubeconfig-generator/service.yaml, modules/500-dashboard/templates/api/rbac-for-us.yaml, modules/500-dashboard/templates/auth/rbac-for-us.yaml, modules/500-dashboard/templates/metrics-scraper/rbac-for-us.yaml, modules/500-dashboard/templates/web/rbac-for-us.yaml, modules/500-openvpn/openapi/values.yaml, tools/dmt-lint.sh
Fix module linter
```changes
section: chore
type: chore
summary: Fix linter
```
=> Fix linter rules

modules/160-multitenancy-manager/images/multitenancy-manager/pkg/helm/client.go
It configures helm logs to the json format.
Every log in multitenancy has the json format, but helm uses klog instead.
Logs in the json format are more convenient for parsing tools.
Helm client logs have the json format
Before:
```
{"level":"info","ts":"2024-12-19T17:02:00Z","logger":"multitenancy-manager.template-manager","msg":"the template reconciled","template":"custom"}
I1219 17:02:01.117854       1 upgrade.go:166] performing update for test
I1219 17:02:02.309033       1 upgrade.go:364] creating upgraded release for test
I1219 17:02:02.697176       1 client.go:393] checking 6 resources for changes
I1219 17:02:02.780200       1 client.go:693] Patch AuthorizationRule "user-gmail-com" in namespace test
I1219 17:02:02.906725       1 client.go:693] Patch OperationPolicy …
```
=> [mulitenancy-manager] helm client json logs

deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_config.go, deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_module_config.go, docs/documentation/_data/deckhouse-alerts.yml, modules/340-monitoring-deckhouse/monitoring/prometheus-rules/alerting.yaml
Correct wording
```changes
type: fix
summary: Rename disabling annotation
```
=> [deckhouse[ Rename disabling annotation

deckhouse-controller/crds/module.yaml, dhctl/pkg/apis/v1alpha1/deckhouse_release.go, global-hooks/create_endpoints.go, global-hooks/create_endpoints_test.go
Remove old migrations and dead code
```changes
type: chore
summary: Remove dead code
```
=> Remove dead code

docs/site/_data/sidebars/virtualization-platform.yml
Refine sidebar titles in Deckhouse Virtualization Platform documentation for better clarity and consistency.
```changes
section: docs
type: chore
summary: Refine sidebar titles in Deckhouse Virtualization Platform documentation for better clarity and consistency.
```
=> [docs] Update sidebar for DVP

.werf/defines/base.tmpl, modules/000-common/images/alt-p11/werf.inc.yaml
=> MERGE WITH ATTENTION fix werf.yaml

.werf/defines/dev-prebuild.tmpl, .werf/defines/installer.tmpl, .werf/werf-test.yaml
=> MERGE WITH ATTENTION fixes in defines

modules/300-prometheus/images/mimir/werf.inc.yaml
=> MERGE WITH ATTENTION fix mimir

modules/300-prometheus/images/promxy/werf.inc.yaml, modules/462-loki/images/loki/werf.inc.yaml
Fix loki build.
Patches doesn't apply.
```changes
type: fix
summary: fix loki build
```
=> [loki] fix build

.github/ci_templates/web.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml
=> [ci] fix workflow

.github/ci_templates/web.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml
Fix documentation linter issues
- Correct werf stage image command
- Add missing environment variables for html-proofer steps
```changes
section: docs
type: chore
summary: Fix documentation linter issues.
```
=> [ci] fix documentation linter issues

docs/documentation/pages/DECKHOUSE-FAQ.md, docs/documentation/pages/DECKHOUSE-FAQ_RU.md
It adds possibility to switch EE revision to SE step by step following the instruction.
We have transition cases, but there is no documentation for these cases.
New case in FAQ 
```changes
section: docs
type: chore
summary: A new transition case has been added in the FAQ.
```
=> [docs][deckhouse] Add steps to switch EE to SE

.github/ci_templates/web.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml
Update workflows to continue on Check links linter errors.
```changes
section: ci
type: chore
summary: Update workflows to continue on Check links linter errors.
```
=> [ci] update workflows to continue on Check links linter errors

ee/modules/380-metallb/images/metallb/patches/001-update-go-libraries.patch, ee/modules/380-metallb/images/metallb/patches/README.md, ee/modules/380-metallb/images/metallb/werf.inc.yaml, ee/modules/380-metallb/templates/controller/deployment.yaml, ee/modules/380-metallb/templates/speaker/daemonset.yaml, ee/se/modules/380-metallb/images/l2lb/patches/004-update-go-libraries.patch, ee/se/modules/380-metallb/images/l2lb/patches/README.md, ee/se/modules/380-metallb/images/l2lb/werf.inc.yaml, testing/library/images_tags_generated.go
- Refactor build.
- Update dependencies to fix vulnerabilities: CVE-2024-45338.
- Vulnerability remediation.
- Unification of assembly using `werf`.
```changes
type: chore
summary: Refactored build and fixed vulnerabilities.
```
=> [metallb] Refactor build

docs/site/_data/i18n.yaml, docs/site/_includes/virtualization-platform/crds-index.liquid, docs/site/_plugins/dvp_resource_generator.rb, docs/site/_plugins/render-jsonschema.rb
=> [docs] Updates for rendering JSONSchemas

modules/470-chrony/images/chrony/werf.inc.yaml, modules/470-chrony/templates/daemonset.yaml
Added missing libcap library
```changes
type: fix
summary: fix build
```
=> [chrony] fix build

.werf/defines/packages-proxies.tmpl
Fix bookworm packages proxy.
```changes
section: ci
type: fix
summary: fix bookworm packages proxy
```
=> [ci] fix bookworm packages proxy

modules/300-prometheus/images/memcached/patches/001-fix-cve.patch, modules/300-prometheus/images/memcached/werf.inc.yaml
Fixed CVEs
```changes
type: fix
summary: Fix memcached CVEs
```
=>  [prometheus] Fix memcached CVEs

modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml, modules/402-ingress-nginx/crds/ingress-nginx.yaml
Update description for the legacySSL parameter of IngressNginxController CRD.
```changes
section: docs
type: chore
summary: Update description for the legacySSL parameter of IngressNginxController CRD
```
=> [docs][ingress-nginx] Update description for the legacySSL parameter of IngressNginxController CRD

docs/documentation/pages/DECKHOUSE-FAQ.md, docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Update commands in step for change redactions.
Due to the addition of validatingadmissionpolicy `heritage-label-objects.deckhouse.io` it is necessary to make changes to the commands for a successful switch between editions.
```changes
section: docs
type: chore
summary: Update commands in step for change redactions.
```
=> [docs] update steps for change redactions

docs/documentation/pages/DECKHOUSE-RELEASE-CHANNELS.md, docs/documentation/pages/DECKHOUSE-RELEASE-CHANNELS_RU.md
Fix a relative path for some assets in DKP <=1.66
=> [docs] Fix a relative path for some assets

modules/000-common/images/csi-external-snapshotter/werf.inc.yaml
Fix snapshot-controller user and group for https://github.com/deckhouse/deckhouse/pull/11361
Application run by user with UID/GID 65534, but binary is owned by UID/GID 65535
Module binary can be executed inside container
```changes
type: fix
summary: Fix snapshot-controller user and group.
```
=> [snapshot-controller] Fix user and group

modules/031-local-path-provisioner/images/helper/werf.inc.yaml, modules/031-local-path-provisioner/images/local-path-provisioner/patches/fix-go-mod.patch, modules/031-local-path-provisioner/images/local-path-provisioner/werf.inc.yaml
Switch build to CSE redaction based rules.
We need safe and simple images for the CSE version.
Safe and simple module images.
```changes
type: feature
summary: Switch build to CSE redaction based rules
```
=> [local-path-provisioner] Prepare to CSE 1.67 version

docs/documentation/_data/deckhouse-alerts.yml, modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificate.yaml, modules/340-extended-monitoring/monitoring/prometheus-rules/certificates/certificates-exporter-health.yaml
Fix doc/alert typo 
```changes
type: fix
summary: Fix doc/alert typo
```
=> [extended-monitoring] Fix doc/alert typo

docs/documentation/_data/sidebars/main.yml
Update naming in the sidebar.
```changes
section: docs
type: chore
summary: Update naming in the sidebar.
```
=> [docs] Update sidebar

docs/documentation/_includes/d8-cli-install/content.liquid, docs/documentation/pages/DECKHOUSE-CLI_RU.md, docs/site/_includes/d8-cli-install/content.liquid, docs/site/pages/virtualization-platform/reference/console-utilities/D8_RU.md
Corrected the deckhouse CLI page for DKP and DVP to reflect the deckhouse-tools module.
```changes
section: docs
type: feature
summary: Corrected the deckhouse CLI page for DKP and DVP to reflect the deckhouse-tools module.
```
=> [docs] Corrected the deckhouse CLI page for DKP and DVP

.werf/defines/base.tmpl, .werf/werf-dev-alt.yaml
=> [deckhouse-controller] Added pyOpenSSL to the image (#11424)

modules/000-common/images/kubernetes/patches/1.27/go-mod.patch, modules/000-common/images/kubernetes/werf.inc.yaml, modules/040-control-plane-manager/images/etcd/patches/001-go-mod.patch
=> [control-plane-manager] fixed CVE-2024-51744

ee/be/modules/350-node-local-dns/images/stale-dns-connections-cleaner/werf.inc.yaml
Set capabilities NET_ADMIN (via setcap) on the executable file so that there are no socket deletion errors.
```changes
type: fix
summary: Set capabilities (via setcap) on the executable file.
```
=> [node-local-dns] fix CAPs for stale-dns-connections-cleaner

docs/documentation/werf-web.inc.yaml, docs/site/werf-debug.yaml, docs/site/werf-docs-builder.inc.yaml, tools/docs/spelling/filesignore
Removed the werf warning about using artifacts.
```changes
section: docs
type: chore
summary: rm artifact in werf
```
=> [docs] rm artifact in werf

docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS.md, docs/site/_includes/getting_started/global/STEP_CLUSTER_ACCESS_RU.md
Adding a space to a command (Getting started).
```changes
section: docs
summary: Adding a space to a command (Getting started).
```
=> Adding a space to a command (Getting started)

docs/documentation/_data/deckhouse-alerts.yml, modules/015-admission-policy-engine/monitoring/prometheus-rules/audit.yaml, modules/015-admission-policy-engine/monitoring/prometheus-rules/bootstrap.yaml, modules/101-cert-manager/monitoring/prometheus-rules/certificate.yaml, modules/470-chrony/monitoring/prometheus-rules/chrony.yaml
Improve wording and formatting in alert descriptions for admission-policy-engine, cert-manager, and chrony.
```changes
section: docs
type: chore
summary: Improve wording and formatting in alert descriptions
```
=> [docs] Update alert descriptions

modules/040-node-manager/images/capi-controller-manager/patches/001-go-mod.patch, modules/040-node-manager/images/capi-controller-manager/patches/README.MD, modules/040-node-manager/images/capi-controller-manager/werf.inc.yaml
=> [node-manager] bump go mod deps versions

docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Add instructions in case of changing Deckhouse edition from EE 1.64 to CSE 1.64
```changes
section: docs
type: fix
summary: Update instructions to switch from EE to CSE 1.64
```
=> [docs] Update instructions to switch from EE to CSE 1.64

Makefile, docs/site/_data/copyright.json, docs/site/_data/footer.json, docs/site/_data/i18n.yaml, docs/site/_data/topnav-l2-products.json, docs/site/_data/topnav.json, docs/site/_includes/header.html, docs/site/werf.yaml
Add level 2 topnav for English.
```changes
section: docs
type: chore
summary: Update topnav on the site.
```
=> [docs] Update topnav on the site

modules/402-ingress-nginx/images/controller-1-10/patches/01-gomod.patch
Fix dependencies in go.mod for controller.
```changes
type: chore
summary: Refactored build and updated dependent libraries to fix vulnerables.
```
=> [ingress-nginx] refactor build (go deps)

modules/007-registrypackages/images/crictl/patches/1.27.1/go_mod.patch, modules/007-registrypackages/images/crictl/patches/1.28.0/go_mod.patch, modules/007-registrypackages/images/crictl/patches/1.29.0/go_mod.patch, modules/007-registrypackages/images/crictl/patches/1.30.1/go_mod.patch, modules/007-registrypackages/images/crictl/patches/1.31.1/go_mod.patch, modules/007-registrypackages/images/crictl/werf.inc.yaml
fixed cve in crictl
security
```changes
type: fix
summary: fixed cve in crictl
```
=> [registrypackages] fixed cve in crictl

modules/200-operator-prometheus/images/prometheus-config-reloader/werf.inc.yaml, modules/200-operator-prometheus/images/prometheus-operator/werf.inc.yaml
Update source artefact(put sources to the /src folder).
```changes
type: chore
summary: Update source artefact(put sources to the /src folder)
```
=> [operator-prometheus] update build

modules/150-user-authn/crds/dex-authenticator.yaml
Update example for whitelistSourceRanges in DexAuthenticator CRD.
```changes
section: docs
type: chore
summary: Update example for whitelistSourceRanges in DexAuthenticator CRD.
```
=> [docs][user-authn] Update DexAuthenticator CRD

modules/402-ingress-nginx/images/controller-1-10/werf.inc.yaml
Fix a bug with dynamic libraries in the ingress-nginx controller pod:
```
Error: exit status 1
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_brotli_filter_module.so" failed (libbrotlienc.so.1: cannot open shared object file: No such file or directory) in /tmp/nginx/nginx-cfgxxxxxxx:10
```
```changes
type: fix
summary: Fixed a bug with dynamic libraries in the ingress-nginx controller pod
```
=> [ingress-nginx] fix dynamic libraries issue

docs/site/_data/sidebars/virtualization-platform.yml
The DVP sidebar was missing the Administration -> Introduction section. Added the missing section to the sidebar.
```changes
section: docs
type: fix
summary:  Added the missing section to the sidebar for DVP documentation.
```
=> [docs][fix] Add Overview for DVP Administration section sidebar

ee/candi/cloud-providers/huaweicloud/docs/ENVIRONMENT.md, ee/candi/cloud-providers/huaweicloud/docs/ENVIRONMENT_RU.md
Add documentation for the `HuaweiCloud` provider.
```changes
section: docs
type: feature
summary: Add documentation for the `HuaweiCloud` provider.
```
=> [docs] Add documentation for the `HuaweiCloud` provider

docs/documentation/_includes/revision_comparison_detail_table.liquid, docs/site/_assets/css/docs.scss, docs/site/_assets/js/customscripts.js
Fix the visibility of the tooltip
Users of the site will be able to see the prompts correctly.
```changes
section: docs
type: chore
```
=> [docs] Fix the tooltip

docs/site/_assets/css/docs.scss, docs/site/_includes/header.html
Fix the header positioning.
For the convenience of using the menu.
```changes
section: docs
type: chore
summary: Fix the header positioning.
```
=> [docs] Fix the header positioning

docs/site/_assets/css/components/_header.scss
Fixed a bug in the drop-down menu
```changes
section: docs
type: chore
```
=> [docs] Fixed a bug in the drop-down menu

dhctl/pkg/kubernetes/actions/deckhouse/install.go, dhctl/pkg/kubernetes/actions/deckhouse/install_test.go
=> [dhctl] use check or setup cni mc only default bundle

ee/candi/cloud-providers/dynamix/openapi/doc-ru-instance_class.yaml
Fix localization for DynamixInstanceClass CRD
```changes
section: docs
type: chore
summary: Fix localization for DynamixInstanceClass CRD.
```
=> [docs][cloud-provider-dynamix] Fix localization for DynamixInstanceClass

modules/300-prometheus/templates/aggregating-proxy/deployment.yaml
Remove duplicate `kube-rbac-proxy` container spec in `aggregating-proxy` VPA.
Get rid of duplicate sample error logs in Prometheus logs.
```changes
type: fix
summary: Minor aggregating-proxy improvements
```
=> [prometheus] Remove duplicate aggregating-proxy VPA spec

go.mod, go.sum
```changes
section: dependencies
type: fix
summary: fixed hooks panic with nil pointers
```
=> [addon-operator] fix nil pointers in batch hooks

modules/160-multitenancy-manager/docs/CONFIGURATION.md, modules/160-multitenancy-manager/docs/CONFIGURATION_RU.md, modules/160-multitenancy-manager/docs/USAGE.md, modules/160-multitenancy-manager/docs/USAGE_RU.md
Fixed links and duplication of information about bundles.
```changes
type: fix
summary: Fixed links and duplication of information about bundles.
```
=> [docs][multitenancy-manager] Small docs fixes

modules/402-ingress-nginx/images/controller-1-10/patches/01-gomod.patch
=> [ingress-nginx] Fix CVEs

deckhouse-controller/pkg/registry/registry.go
Add CA to helpers registry requests
```changes
type: fix 
summary: add CA to registry requests in helper
```
=> [deckhouse-controller] registry helper support CA

modules/110-istio/images/proxyv2-v1x21x6/werf.inc.yaml
=> [istio] fix cves

docs/documentation/_includes/toc_in_sidebar.html, docs/site/_includes/toc_in_sidebar.html, docs/site/backends/docs-builder-template/layouts/partials/toc.html
setting up anchors by menu items.
```changes
section: docs
type: chore
```
=> [docs] Setting up anchors by menu items

ee/modules/610-service-with-healthchecks/docs/EXAMPLES.md, ee/modules/610-service-with-healthchecks/docs/EXAMPLES_RU.md
Fix example TCP.
Correct documentation.
```changes
type: chore
summary: Fix example TCP.
```
=> [service-with-healthchecks][docs] Fix example TCP

modules/300-prometheus/images/grafana-v10/werf.inc.yaml
=> [prometheus] grafana 10 cse refactor build

.werf/defines/packages-proxies.tmpl
=> Fix altlinux package proxy

docs/site/_assets/css/components/_header.scss, docs/site/_assets/css/components/common/_breakpoints.scss, docs/site/_assets/css/components/common/_button.scss, docs/site/_assets/css/components/common/_container.scss, docs/site/_data/i18n.yaml, docs/site/_includes/header.html
Changing the menu style.
```changes
section: docs
type: chore
```
=> [docs] Changing the menu style

candi/cloud-providers/aws/terraform-modules/master-node/main.tf, candi/cloud-providers/aws/terraform-modules/static-node/main.tf
network_border_group fixes
```changes
type: fix
summary: network_border_group fix
```
=> [cloud-provider-aws] network_border_group fixes

modules/000-common/images/shell-operator/werf.inc.yaml
Remove some apt leftovers from the /var directory.
Shrinks the shell-operator's image.
```changes
type: chore
impact: Remove apt cache after building.
```
=> [common] remove apt cache

docs/site/_assets/css/components/_header.scss, docs/site/_assets/css/components/common/_breakpoints.scss, docs/site/_includes/header.html
Fix the header size.
```changes
section: docs
type: chore
```
=> [docs] Fix the header for a wide screen

docs/site/_assets/css/docs.scss
Fixed the positioning of the copy button.
```changes
section: docs
type: chore
```
=> [docs] Fix copy button

modules/000-common/images/alt-p11/werf.inc.yaml
=> [common] fix common alt-p11 image

modules/042-kube-dns/docs/FAQ.md, modules/042-kube-dns/docs/FAQ_RU.md
Update example in kube-dns: FAQ.
```changes
section: docs
type: fix
summary: Update example in kube-dns: FAQ.
```
=> [docs] Update example in kube-dns: FAQ

go.mod, go.sum
Fix batch hook version bug (empty binding contexts)
Fix !BADKEY logger error
Fix config map update
```changes
section: dependencies
type: fix
summary: bump addon operator with minor fixes
```
=> [addon-operator] bump addon operator

modules/000-common/images/alt-p11/werf.inc.yaml
=> [common] base alt p11 with archive repos

modules/300-prometheus/images/grafana-v10/werf.inc.yaml
=> fix go install wire

modules/021-cni-cilium/images/base-cilium-dev/werf.inc.yaml, modules/110-istio/images/proxyv2-v1x21x6/werf.inc.yaml
Use clone repos from `{{ $.SOURCE_REPO }}` instead `go install` external dependencies:
- google.golang.org/grpc/cmd/protoc-gen-go-grpc@8ba23be9613c672d40ae261d2a1335d639bdd59b
- google.golang.org/protobuf/cmd/protoc-gen-go@v1.30.0
- github.com/mitchellh/protoc-gen-go-json@v1.1.0
- github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@v1.5.1
Fro build in an environment without Internet.
```changes
section: cni-cilium, istio
type: chore
summary: Fix go install external package.
```
=> [cni-cilium] fix go install package

modules/007-registrypackages/images/d8/werf.inc.yaml
=> fix go install task

docs/site/.helm/templates/20-ingress.yaml
Fix Ingress to work with the old URLs.
```changes
section: docs
type: chore
summary: Fix Ingress to work with the old URLs.
```
=> [docs][site] fix Ingress to work with the old URLs

docs/documentation/pages/module-development/EXAMPLE.md, docs/documentation/pages/module-development/EXAMPLE_RU.md
It provides docs fix.
```changes
section: docs
type: fix
summary: Fix update policy docs.
```
=> [docs] fix update policy docs

ee/modules/015-admission-policy-engine/images/ratify/patches/02-go-mod.patch
Updates vulnerable deps.
Updates vulnerable deps.
```changes
type: chore
summary: Update ratify deps.
```
=> [admission-policy-engine] bump ratify deps

docs/site/backends/registry-modules-watcher/cmd/main.go, docs/site/backends/registry-modules-watcher/internal/backends/pkg/registry-scaner/cache/cache.go, docs/site/backends/registry-modules-watcher/internal/backends/pkg/registry-scaner/cache/cache_test.go, docs/site/backends/registry-modules-watcher/internal/backends/pkg/registry-scaner/process.go, docs/site/backends/registry-modules-watcher/internal/backends/pkg/registry-scaner/registry-scaner.go, docs/site/backends/registry-modules-watcher/internal/backends/pkg/sender/sender.go, docs/site/backends/registry-modules-watcher/internal/watcher/watcher.go, docs/site/backends/registry-modules-watcher/pkg/registry-client/registry-client.go
fixed: #11490
Updating the documentation on the site when updating modules in the registry
```changes
section: docs
type: fix
summary: improve docs remove module
```
=> [docs] improve docs remove module

deckhouse-controller/files/kubectl_wrapper.sh
Fix kubectl wrapper script.
```changes
section: core
type: fix
summary: Fix kubectl wrapper script
```
=> [deckhouse-controller] fix kubectl wrapper script

modules/000-common/images/distroless/werf.inc.yaml
Add a template for using package-proxy.
Unification build.
```changes
type: chore
summary: Add a template for using package-proxy.
```
=> [common] add alpine apk proxy

modules/800-deckhouse-tools/images/web/werf.inc.yaml
```changes
type: chore
summary: reduced size of artifact images
```
=> [deckhouse-tools] reduced size of artifact images

modules/300-prometheus/images/memcached/werf.inc.yaml
=> [prometheus] fix promu

modules/000-common/images/yq4/werf.inc.yaml
update yq4
security
```changes
type: chore
summary: update yq4 to 3.45.1
```
=> [common] update yq4 to 3.45.1

werf.yaml
Add `.DistroPackagesProxy` to context for render  `ssh_static_artifact`.
```changes
section: ci
type: chore
summary: fix package proxy in ssh-static define.
```
=> [ci] fix package proxy in ssh-static

.dmtlint.yaml, docs/documentation/_data/conversions.yml, modules/150-user-authn/openapi/conversions/v2.yaml, tools/dmt-lint.sh
Add human readable conversion description
```changes
type: feature
summary: Add human-readable conversion description.
```
=> [user-authn] Add conversion description

modules/810-documentation/templates/configmap.yaml
Fix redirection issue for some assets in the documentation module.
```changes
type: chore
summary: Fix redirection issue for some assets in the documentation module
```
=> [documentation] Fix redirection issue for some assets.

.werf/defines/base.tmpl
Add `libpthread.so` to deckhouse image.
```
Traceback (most recent call last):
File "/deckhouse/downloaded/virtualization/dev/hooks/./generate_secret_for_dvcr.py", line 20, in <module>
from lib.password_generator import password_generator, htpasswd as hd
File "/deckhouse/downloaded/virtualization/dev/hooks/lib/password_generator/htpasswd.py", line 16, in <module>
import bcrypt
File "/deckhouse/downloaded/virtualization/dev/lib/python/dist/bcrypt/__init__.py", line 13, in <module>
from ._bcrypt import (
ImportError: libpthread.so.0: cannot open shared object file: No such file or directory
```
```changes
section: werf
type: fix
summary: Add `libpthread.so` to deckhouse image.
```
=> [werf] add libpthread.so to deckhouse image

modules/007-registrypackages/images/crictl/werf.inc.yaml
Use global context in include "alpine packages proxy".
Otherwise the packages proxy doesn't work.
```changes
type: chore
summary: fix package proxy in build crictl.
```
=> [registrypackages] fix package proxy in build crictl

modules/000-common/images/kubernetes/werf.inc.yaml
Optimize the use of space in the registry.
```changes
type: chore
summary: reduced size of kubernetes-artifact images
```
=> [common] reduced size of kubernetes-artifact images

candi/version_map.yml
Fix CVEs in Yandex Cloud provider
```changes
type: chore
summary: fix CVEs
```
=> [cloud-provider-yandex] fix CVEs

modules/340-monitoring-kubernetes/images/kube-state-metrics/werf.inc.yaml
fix cve in sources and update build.
```changes
type: fix
summary: fix cve in sources and update build
```
=> [monitoring-kubernetes] fix cve in sources and update build

modules/460-log-shipper/images/vector/werf.inc.yaml
Update vector to 0.44 version.
```changes
type: chore
summary: Update vector to 0.44 version
```
=> [log-shipper] update vector to 0.44

pkg/log/handler.go, pkg/log/output.go
Replace log keys with constant values
```changes
section: pkg
type: fix
summary: logger keys replaced with constant values
```
=> [pkg] fix/add logger const

docs/site/.helm/templates/15-modules-watcher.yaml, docs/site/.helm/values.yaml
Fix modules watcher template to use log level configuration for klog.
Ref: https://github.com/deckhouse/deckhouse/pull/11893/
```changes
section: docs
type: fix
summary: Fix modules watcher log level configuration.
```
=> [docs] Fix modules watcher log level configuration

ee/be/modules/350-node-local-dns/images/stale-dns-connections-cleaner/werf.inc.yaml
Add `GOPROXY` to install stages in stale-dns-connections-cleaner-build-artifact.
Not necessary.
```changes
type: chore
summary: Add `GOPROXY` to install stages in stale-dns-connections-cleaner-build-artifact.
```
=> [node-local-dns] add goproxy

.werf/defines/base.tmpl, .werf/werf-dev-alt.yaml
Add locale files to deckhouse image.
before:
```
root@dev-master-0:~# kubectl  exec -it -n d8-system svc/deckhouse-leader -- /bin/bash
bash: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8): No such file or directory
bash: warning: setlocale: LC_COLLATE: cannot change locale (C.UTF-8): No such file or directory
```
after:
```
[root@dev-master-0 ~]# kubectl  exec -it -n d8-system svc/deckhouse-leader -- /bin/bash
[deckhouse] deckhouse@dev-master-0 /deckhouse $
```
```changes
section: werf
type: chore
summary: Add locale files to deckhouse image.
```
=> [werf] return locale to base image

ee/modules/015-admission-policy-engine/images/ratify/werf.inc.yaml
Use `{{ $.SOURCE_REPO }}` instead `github.com` for cloning dependency in build.
```changes
type: chore
summary: Use variable for source repo in build.
```
=> [admission-policy-engine] Use variable for source repo in build.

ee/modules/500-operator-trivy/images/node-collector/werf.inc.yaml
Use alt-p11-artifact instead base image.
In artifact used package manager repos on specific date, which allows the build to be idempotent.
Not necessary.
```changes
type: chore
summary: Use alt-p11-artifact instead base image.
```
=> [operator-trivy] use alt-p11-artifact instead base image

deckhouse-controller/pkg/controller/deckhouse-release/controller.go, deckhouse-controller/pkg/controller/module-controllers/release/controller.go, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-mode.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-patch-minor-update.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-patch-mode-minor-release-approved.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-patch-mode.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/clean-up-outdated-module-releases-when-deploy.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/dVersion-suitable.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/kVersion-suitable.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/simple.yaml
Fix deckhouse-controller must restart
Add backoff to retry funtions
Add labels to release after deploy
Add finalizers to release after deploy
```changes
type: fix
summary: deckhouse controller restart after module loaded
```
=> [deckhouse-controller] fix/module release error

.github/workflows/e2e-aws.yml, .github/workflows/e2e-azure.yml, .github/workflows/e2e-eks.yml, .github/workflows/e2e-gcp.yml, .github/workflows/e2e-openstack.yml, .github/workflows/e2e-static.yml, .github/workflows/e2e-vcd.yml, .github/workflows/e2e-vsphere.yml, .github/workflows/e2e-yandex-cloud.yml
fix render-workflow
fix job render workflow
```changes
section: ci
type: chore
summary: fix render-workflow
```
=> chore: fix render-workflow

modules/800-deckhouse-tools/images/web/src/package-lock.json, modules/800-deckhouse-tools/images/web/src/package.json
Module deckhouse-tools has CVE
Upgrade deps
not related to release
```changes
type: chore
summary: Update deckhouse-tools deps.
```
=> chore: update deckhouse-tools deps

candi/cloud-providers/yandex/docs/LAYOUTS.md, candi/cloud-providers/yandex/docs/LAYOUTS_RU.md
Added a description of how the NAT gateway works, from which addresses the outgoing traffic comes.
section: docs
type: chore
summary: Added a more detailed description of how the nat gateway works.
=> [docs] Added a more detailed description of how the nat gateway works

modules/007-registrypackages/images/crictl/patches/1.27.1/go_mod.patch, modules/007-registrypackages/images/crictl/patches/1.28.0/go_mod.patch
=> fix crictl glog cve

docs/documentation/Makefile, docs/site/Makefile
The port of local registry for local docs build has been changed.
```changes
section: docs
type: fix
summary: Changed port of local registry for local docs build.
```
=> [docs] Change port of local registry for local docs build

modules/040-terraform-manager/images/base-terraform-manager/patches/001-go-mod.patch, modules/040-terraform-manager/images/base-terraform-manager/patches/readme.md, modules/040-terraform-manager/images/base-terraform-manager/werf.inc.yaml
```changes
section: terraform-mananger
type: fix
summary: Terraform fix CVE's
```
=> [terraform-manager] Terraform fix CVE's

docs/site/_data/getting_started/dkp_data.yaml, docs/site/_data/i18n.yaml, docs/site/_includes/getting_started/global/partials/INSTALL_CONFIG.liquid
Added tab with SE+ redaction on the page of the 4th step of GS.
```changes
section: docs
type: fix
summary: Added tab with SE+ redaction on the page of the 4th step of GS.
```
=> [docs][getting-started] Add SE+ to GS as individual tab

candi/version_map.yml
Update d8-cli
```changes
section: d8-cli
type: chore
summary: update d8-cli
```
=> [d8-cli] update d8-cli

modules/300-prometheus/images/mimir/werf.inc.yaml, modules/300-prometheus/images/promxy/werf.inc.yaml, modules/462-loki/images/loki/werf.inc.yaml
Remove src artifacts from final images
```changes
section: ci
type: fix
summary: remove src artifacts from final images
```
=> [ci] remove src artifacts from final images

candi/cloud-providers/aws/bashible/bootstrap-networks.sh.tpl, modules/007-registrypackages/images/ec2-describe-tags/werf.inc.yaml, testing/library/images_tags_generated.go
security
```changes
type: fix
summary: cve update ec2-describe-tags
```
=> [registrypackages] cve update ec2-describe-tags

modules/000-common/images/kubernetes/patches/1.30/005-gomod.patch, modules/000-common/images/kubernetes/patches/1.31/005-gomod.patch
Fix kubernetes build by updating patches
Kubernetes binaries are failed to build for now; fix this problem
Kubernetes binaries are failed to build for now; fix this problem
```changes
type: chore
summary: Fix kubernetes build by updating patches.
```
=> Update kubernetes patches

candi/cloud-providers/aws/bashible/bootstrap-networks.sh.tpl, modules/007-registrypackages/images/ec2-describe-tags/werf.inc.yaml, testing/library/images_tags_generated.go
cve update ec2-describe-tags 
```changes
section: ci
type: fix
summary: cve update ec2-describe-tags 
```
=> [registrypackages] cve update ec2-describe-tags (#12115)

candi/terraform_versions.yml, ee/candi/cloud-providers/dynamix/terraform-modules/master-node/variables.tf, ee/candi/cloud-providers/dynamix/terraform-modules/versions.tf, ee/modules/030-cloud-provider-dynamix/images/capd-controller-manager/werf.inc.yaml, ee/modules/030-cloud-provider-dynamix/images/cloud-controller-manager/werf.inc.yaml, ee/modules/030-cloud-provider-dynamix/images/cloud-data-discoverer/werf.inc.yaml, ee/modules/030-cloud-provider-dynamix/images/dynamix-csi-driver/werf.inc.yaml, ee/modules/040-terraform-manager/images/terraform-manager-dynamix/patches/readme.md, ee/modules/040-terraform-manager/images/terraform-manager-dynamix/patches/update_gomod.patch, ee/modules/040-terraform-manager/images/terraform-manager-dynamix/werf.inc.yaml
cve fix dynamix cloud provider and bump go version
cve fix
```changes
type: fix
summary: cve fix dynamix cloud provider and bump go version
```
=> [terraform-manager] cve fix terraform-manager-dynamix (#11952)

modules/402-ingress-nginx/images/kruise/patches/00-gomod.patch
CVE fixes.
```changes
type: chore
summary: CVE fixes
```
=> [ingress-nginx] CVE fixes

modules/300-prometheus/images/mimir/werf.inc.yaml, modules/300-prometheus/images/promxy/werf.inc.yaml
=> [prometheus] del tools from src mimir and promxy

modules/303-prometheus-pushgateway/images/pushgateway/patches/001_fix_cve.patch, modules/303-prometheus-pushgateway/images/pushgateway/patches/README.md, modules/303-prometheus-pushgateway/images/pushgateway/werf.inc.yaml
security
```changes
section: prometheus-pushgateway
type: fix 
summary: cve update
```
=> [prometheus-pushgateway] cve update

candi/bashible/common-steps/all/004_disable_firewalld.sh.tpl
Fix bashible step that disable firewalld
Fix https://github.com/deckhouse/deckhouse/issues/12138
```changes
section: candi
type: fix
summary: Fix bashible step that disable firewalld
```
=> [candi] Fix bashible step that disable firewalld

modules/150-user-authn/images/dex-authenticator/werf.inc.yaml, modules/150-user-authn/images/dex/werf.inc.yaml, modules/150-user-authn/images/kubeconfig-generator/werf.inc.yaml
Add missing `stageDependencies` for patches.
Cached images do not update without `stageDependencies`.
Not necessary. 
```changes
type: chore
summary: Add missing stage dependencies for patches.
```
=> [user-authn] fix stage dependencies for patches

.github/scripts/js/validators/pr-changes-validator.js, .github/scripts/js/validators/pr-changes-validator.test.js
impact and impact_level is not a required field
Correcting invalid rules for validation
```changes
section: ci
type: fix
summary: Correcting invalid rules for validation
impact: Correcting invalid rules for validation
```
=> fix: pr changes validator

modules/300-prometheus/images/mimir/werf.inc.yaml
fix mimir build
```changes
section: ci
type: chore
summary: fix mimir build
```
=> [ci] fix mimir build

docs/site/pages/virtualization-platform/documentation/admin/platform-management/virtualization/CLUSTER_IMAGES.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/virtualization/CLUSTER_IMAGES_RU.md, docs/site/pages/virtualization-platform/documentation/user/resource-managment/VM.md, docs/site/pages/virtualization-platform/documentation/user/resource-managment/VM_RU.md
```changes
section: docs
type: chore
summary: Transferring information from the module to the DVP documentation.
```
=> [docs] Transferring information from the module to the DVP documentation

modules/040-node-manager/templates/cluster-autoscaler/rbac-for-us.yaml
Fix autoscaler RBAC-for-us for zvirt and dynamix 
```changes
type: fix
summary: fix autoscaler RBAC for zvirt and dynamix
```
=> [node-manager] fix autoscaler rbac for zvirt and dynamix

docs/documentation/_includes/module-editions.liquid
Fix edition list rendering.
```changes
section: docs
type: chore
summary: Fix edition list rendering
impact: Fix edition list rendering
```
=> [docs] Fix edition list rendering block

modules/160-multitenancy-manager/crds/projects.yaml
It fixes resource annotations crd.
CRD is wrong.
```changes
type: fix
summary: Fix resource annotations.
```
=> [multitenancy-manager] fix resource annotations

docs/documentation/_includes/toc_in_sidebar.html, docs/site/_assets/css/docs.scss, docs/site/_includes/toc_in_sidebar.html, docs/site/backends/docs-builder-template/layouts/partials/toc.html
Fixed the indentation.
```changes
section: docs
type: chore
```
=> [docs] Fixed the indentation

modules/000-common/images/python-static/werf.inc.yaml
Python-static image contains extra files
Remove extra files in python-static image
```changes
section: ci
type: chore
summary: Remove extra files in python-static image.
```
=> chore: refactor python image

docs/documentation/_data/conversions.yml, modules/040-node-manager/openapi/conversions/v2.yaml
Add human readable conversion description
```changes
type: feature
summary: Add human-readable conversion description.
```
=> [node-manager] Add conversion description

docs/documentation/_data/conversions.yml, modules/400-descheduler/openapi/conversions/v2.yaml
Add human readable conversion description
```changes
type: feature
summary: Add human-readable conversion description.
```
=> [descheduler] Add conversion description

docs/documentation/_data/i18n.yml, docs/documentation/_includes/module-editions.liquid, docs/site/backends/docs-builder-template/i18n/en.yaml, docs/site/backends/docs-builder-template/i18n/ru.yaml, docs/site/backends/docs-builder-template/layouts/partials/module-editions.html
Simplify module status messages.
```changes
section: docs
type: chore
summary: Simplify module status messages.
```
=> [docs] Simplify module status messages

docs/documentation/_includes/module-editions.liquid, docs/site/backends/docs-builder-template/layouts/partials/module-editions.html
Minor markup updates.
```changes
section: docs
type: chore
summary: Minor markup updates.
```
=> [docs] Minor markup updates

docs/site/README.md
This PR is aimed to update several outdated items and improve overall wording and formatting of the README for Deckhouse docs site.
```changes
section: docs
type: chore
summary: Improved wording and formatting in the Deckhouse docs site's README.
```
=> [docs] Update Deckhouse docs README

docs/documentation/_data/i18n.yml, docs/documentation/_includes/warning-version.liquid, docs/site/backends/docs-builder-template/i18n/en.yaml, docs/site/backends/docs-builder-template/i18n/ru.yaml, docs/site/backends/docs-builder-template/layouts/_default/single.html
Update warning block content in the documentation.
```changes
section: docs
type: chore
summary: Update warning block content in the documentation.
```
=> [docs] Update warning block content

docs/site/_includes/getting_started/vcd/partials/config.ru.yml.standard.other.inc, docs/site/_includes/getting_started/vcd/partials/config.yml.standard.other.inc
Update `mc metallb` `spec.version` to `2` in vCloud GS. No other changes seem necessary.
We keep Getting Started docs updated
```changes
section: docs
type: chore
summary: Minor update to vCloud Getting Started example config.
```
=> [docs] Update mc metallb version in vCloud GS example

docs/documentation/_data/i18n.yml
Fix module stages description.
```changes
section: docs
type: chore
summary: Fix module stages description.
```
=> [docs] Fix module stages description

modules/110-istio/docs/EXAMPLES.md, modules/110-istio/docs/EXAMPLES_RU.md
Fixes in istio (clarification of versions).
```changes
section: docs
type: chore
summary: Fixes in istio (clarification of versions).
```
=> [docs] Fixes in istio (clarification of versions)

docs/documentation/_data/modal.yml, docs/documentation/_includes/form_in_modal.html, docs/documentation/_includes/request_callback_form.html, docs/site/_assets/css/components/_request-callback.scss, docs/site/_assets/css/components/common/_button.scss, docs/site/_assets/css/components/common/_form.scss, docs/site/_assets/css/components/common/_text.scss, docs/site/_assets/css/site.scss, docs/site/_assets/js/popup-form.js, docs/site/_data/modal.yml, docs/site/_includes/form_in_modal.html, docs/site/_includes/head-site.html, docs/site/_includes/header.html, docs/site/_includes/request_callback_form.html
Add a modal window to the contact button.
```changes
section: docs
type: chore
```
=> [docs] add a modal window to the contact button

docs/site/docker-compose.yml
Fix documentation local build.  Ref: https://github.com/deckhouse/deckhouse/pull/12182
```changes
section: docs
type: chore
summary: Fix documentation local build.
```
=> [docs] Fix documentation local build

modules/007-registrypackages/images/amazon-ec2-utils/werf.inc.yaml
Fix registrypackage amazon-ec2 build
```changes
section: ci
type: fix
summary: fix registrypackage amazon-ec2 build
```
=> fix registrypackage amazon-ec2 build

global-hooks/migrate/delete-metallb-deprecated-crd.go, global-hooks/migrate/delete-metallb-deprecated-crd_test.go
Refactor a global hook (https://github.com/deckhouse/deckhouse/pull/12378) that removes the deprecated CRD `addresspools.metallb.io` from the MetalLB module from the cluster.
Before:
```shell
Warning: metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
No resources found
addresspools.metallb.io                                           2025-03-06T14:16:26Z
ipaddresspools.metallb.io                                         2025-01-24T14:24:52Z
```
After:
```shell
Error from server (NotFound): Unable to list "metallb.io/v1beta1, Resource=addresspools": the server could not find the requested resource (get addresspools.metallb.io)
ipaddresspools.metallb.io                                         2025-01-24T14:24:52Z
```
Optimizing hook operation.
```changes
section: …
```
=> [metallb] Change the CRD removal method

modules/110-istio/images/proxyv2-v1x21x6/werf.inc.yaml, modules/402-ingress-nginx/images/controller-1-10/werf.inc.yaml, modules/402-ingress-nginx/images/kruise-state-metrics/werf.inc.yaml, modules/402-ingress-nginx/images/kruise/werf.inc.yaml, modules/402-ingress-nginx/images/nginx-exporter/werf.inc.yaml
Removed .git directories to reduce image size.
To optimize storage of images in registy and reduce the build cache.
```changes
section: ci
type: chore
summary: Reduce artifact size.
```
=> [ci] Optimize src artifacts build

docs/documentation/_plugins/custom_sidebar.rb, docs/site/_data/sidebars/virtualization-platform.yml
Add validation for sidebar items to ensure each
item has a valid data.
Fix sidebar for DVP.
```changes
section: docs
type: chore
summary: Add validation for sidebar items to ensure each item has a valid data.
```
=> [docs] Add sidebar validation. Fix DVP sidebar.

.github/workflow_templates/trivy-db-schedule.yml, .github/workflows/trivy-db-schedule.yml
Updated the runs-on parameter in the CI/CD job configuration.
This update ensures the job runs on specific runners by modifying the runs-on parameter. It improves control, stability, and consistency in CI/CD execution, preventing accidental runs on incorrect or overloaded runners.
```changes
section: ci
type: fix
summary: Updated the runs-on parameter in the CI/CD job configuration
```
=> fix trivy-db-shedule

.github/scripts/js/validators/pr-changes-validator.js, .github/scripts/js/validators/pr-changes-validator.test.js, .github/workflow_templates/validation.yml, .github/workflows/validation.yml
This PR enhances the validation and processing of changelog entries in Pull Requests
visually prominent error messages guide contributors to fix issues quickly
```changes
section: ci
type: chore
summary: Added processBlock function to automatically handle special characters ([, {) in summary and impact fields
---
section: ci
type: chore
summary: Added human-readable error message
```
=> [chore]: update pr changes validator

candi/bashible/bashible.sh.tpl
This pr allow to send bashible events about start update nodes and finish to default namespace.
```
kubectl get events -w --sort-by='.lastTimestamp'
warning: --watch or --watch-only requested, --sort-by will be ignored
LAST SEEN   TYPE      REASON                    OBJECT                                               MESSAGE
0s          Normal    BashibleNodeUpdate        node/devtest-master-0                      start steps update on devtest-master-0
0s          Normal    BashibleNodeUpdate        node/devtest-master-0                      finish  steps update on devtest-master-0
```
this resolve [3656](https://github.com/deckhouse/deckhouse/issues/3656) issue
```changes
section: candi
type: feature
summary: send bashible info events start and finish update nodes to default namespace …
```
=> [candi] Send bashible info events start and finish update nodes to default namespace

docs/documentation/_data/conversions.yml, modules/300-prometheus/openapi/conversions/v2.yaml, modules/340-extended-monitoring/openapi/conversions/v2.yaml
Adding description for prometheus/extended-monitoring CRD conversion hooks.
-
```changes
type:  chore
summary: Add conversion hook descriptions for prometheus/extended-monitoring module.
```
=> Add prometheus/extended-monitoring conversion hook descriptions

docs/documentation/_layouts/default.html, docs/site/_data/modal.yml, docs/site/_includes/footer.html, docs/site/_includes/request_callback_form.html, docs/site/_layouts/default.html
```changes
section: docs
type: chore
```
=> [docs] Fix contact button

modules/002-deckhouse/templates/deployment.yaml
Update Set VPA min to 100m
Set CPU request with VPA-disabled to 150m
Deckhouse request 500m for each pod with VPA-disabled, and minimum 500m with VPA-enabled
Actual long-term resource consumption, depending on the number of enabled modules, ranges from 100mcpu to 200mcpu
When it is necessary to place some components on master nodes (for example, nginx controller), high resource requests force the creation of cluster nodes of 8 cores, although the actual node load is no more than 1 core
```changes
type: fix
summary: updated deckhouse pod cpu requests to request 100mcpu with vpa enabled and 150 with vpa disabled
```
=> [deckhouse] update deckhouse pod resource requests

dhctl/pkg/preflight/check_time.go
just a little fix after [12519](https://github.com/deckhouse/deckhouse/pull/12232)
```changes
section: dhctl
type: fix
summary: small fix and trash removal 
impact: 
```
=> [chore] small fix and trash removal 

deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-mode.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-patch-minor-update.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-patch-mode-minor-release-approved.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/auto-patch-mode.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/clean-up-outdated-module-releases-for-deployed.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/clean-up-outdated-module-releases-when-deploy.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/dVersion-suitable.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/kVersion-suitable.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/new-module-manual-mode.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/reinstall-annotation.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/simple.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/with-annotation.yaml, deckhouse-controller/pkg/controller/module-controllers/source/testdata/golden/empty.yaml, deckhouse-controller/pkg/controller/module-controllers/source/testdata/golden/withmodulepullerror.yaml, deckhouse-controller/pkg/controller/module-controllers/source/testdata/golden/withmodules.yaml
Bump golden files for tests.
Fixed [this](https://github.com/deckhouse/deckhouse/pull/12317) 
```changes
type: chore
summary: bump golden files for tests
```
=> [deckhouse-controller] chore/bump golden files

docs/documentation/pages/DECKHOUSE-CLI.md, docs/documentation/pages/DECKHOUSE-CLI_RU.md
Updated Deckhouse CLI install instructions to reflect recent changes.
```changes
section: docs
type: fix
summary: Update Deckhouse CLI installation guide
```
=> [docs] Update Deckhouse CLI installation guide

docs/site/.helm/templates/20-ingress.yaml, docs/site/_assets/js/customscripts.js, docs/site/_includes/header.html, modules/810-documentation/images/web/site/_data/topnav.yml, modules/810-documentation/templates/configmap.yaml, modules/810-documentation/templates/ingress.yaml
This pull request includes several changes to improve language handling, update URL structures, and configure settings for the documentation module. The most important changes are grouped by theme below.
The documentation module updates:
* Set a language cookie based on the user's browser language.
* Use cookie and browser language for root redirects.
* Fix bug in the topnav menu generation for external URLs 
* Various URL rewrites and redirects for language-specific paths and modules.
* Add Ingress resource for serving favicon-like assets in the documentation without authentication.
* Refactor NGINX configuration for the documentation module.
Fix bugs:
- links from the console module are broken;
- errors that make it impossible to navigate the documentation.
```changes
section: …
```
=> [documentation] Fix bugs is navigation. Set language cookie

docs/site/_includes/getting_started/global/partials/INSTALL_OTHER.liquid, docs/site/_includes/getting_started/global/partials/INSTALL_OTHER_RU.liquid
Change quick start for Bare Metal, change info about SHH and access on master node, the current version may cause user confusion.
```changes
section: docs
type: chore
summary: Change quick start for Bare Metal, change info about SHH and access on master node, the current version may cause user confusion.
```
=> [docs] Fix quick start: change info about SHH and access on master node

ee/candi/cloud-providers/dynamix/terraform-modules/master-node/variables.tf
Change  cloudConfig`jsondecode` to `yamldecode`
```changes
section: cloud-provider-dynamix
type: fix
summary: fix terraform cloudConfig decoding
```
=> [cloud-provider-dynamix] fix terraform cloudConfig decoding

modules/040-node-manager/hooks/generate_capi_kubeconfig.go
Always generate `static-kubeconfig` if `CAPS` is running.
```changes
type: fix
summary: Fix `kubeconfig` generation for `CAPI`.
```
=> [node-manager] Fix `kubeconfig` generation for `CAPI`

modules/402-ingress-nginx/images/controller-1-10/werf.inc.yaml
Fixing the ingress-nginx module assembly
Correction of incorrect assembly
```changes
type: fix
summary: fix patch names in ingress-nginx
```
=> [ingress-nginx] fix patch names in ingress-nginx

deckhouse-controller/pkg/controller/deckhouse-release/controller.go, deckhouse-controller/pkg/controller/deckhouse-release/controller_test.go, deckhouse-controller/pkg/controller/deckhouse-release/event.go, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/apply-now-deckhouse-previous-release-is-not-ready.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/deckhouse-previous-release-is-not-ready.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/few-minor-releases.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/minor-release-and-patch-release.yaml, deckhouse-controller/pkg/controller/deckhouse-release/testdata/minor-release-and-patch-release.yaml, deckhouse-controller/pkg/controller/module-controllers/release/controller.go, deckhouse-controller/pkg/releaseupdater/deploy_time_checker.go, deckhouse-controller/pkg/releaseupdater/task_calculator.go, modules/340-monitoring-deckhouse/monitoring/prometheus-rules/alerting.yaml
Backports #12632 into 1.68 branch
```changes
section: Deckhouse-controller
type: fix
summary: Backport metrics fix.
```
=> [deckhouse-controller] Backport metrics fix to release 1.68

docs/site/_data/sidebars/code.yml
Fix sidebar for Deckhouse Code.
```changes
section: docs
type: chore
summary: Fix sidebar for Deckhouse Code
```
=> [docs] Fix sidebar for Deckhouse Code

docs/documentation/_data/i18n.yml, docs/documentation/_includes/module-configuration.liquid, docs/documentation/_includes/module-conversion.liquid, docs/documentation/_includes/module-settings.liquid, docs/documentation/_tools/modules_generate_configuration.sh, docs/documentation/werf-git-section.inc.yaml, ee/modules/030-cloud-provider-vcd/docs/CONFIGURATION.md, ee/modules/030-cloud-provider-vcd/docs/CONFIGURATION_RU.md, ee/se-plus/modules/030-cloud-provider-vsphere/docs/CONFIGURATION.md, ee/se-plus/modules/030-cloud-provider-vsphere/docs/CONFIGURATION_RU.md, modules/030-cloud-provider-aws/docs/CONFIGURATION.md, modules/030-cloud-provider-aws/docs/CONFIGURATION_RU.md, modules/030-cloud-provider-azure/docs/CONFIGURATION.md, modules/030-cloud-provider-azure/docs/CONFIGURATION_RU.md, modules/030-cloud-provider-gcp/docs/CONFIGURATION.md, modules/030-cloud-provider-gcp/docs/CONFIGURATION_RU.md, modules/030-cloud-provider-yandex/docs/CONFIGURATION.md, modules/030-cloud-provider-yandex/docs/CONFIGURATION_RU.md, modules/150-user-authn/openapi/conversions/v3.yaml, modules/150-user-authn/openapi/conversions/v4.yaml, modules/500-cilium-hubble/docs/CONFIGURATION.md, modules/500-cilium-hubble/docs/CONFIGURATION_RU.md
Add module conversion details to the internal module documentation.
```changes
section: docs
type: chore
summary: Add module conversion details to the internal module documentation.
```
=> [docs] Add module conversion details to the internal module documentation

modules/462-loki/templates/loki-api-from-d8-token.yaml, modules/462-loki/templates/rbac-to-us.yaml
This PR allow to access loki api RBAC policies from d8 bin.
D8 can get logs from loki api by service account loki token.
```changes
section: loki
type: feature
summary: add RBAC manifest loki api for d8.
```
=> [loki] Add RBAC manifests loki api for d8.

modules/030-cloud-provider-yandex/images/cloud-controller-manager/werf.inc.yaml
This PR fixes logic of creating LB services in yandex CCM, non-yandex nodes are ignored from LB sync. 
See https://github.com/deckhouse/yandex-cloud-controller-manager/commit/64cf7778a4a42cbe2b775d5683d89367061612a1 
See https://github.com/deckhouse/deckhouse/issues/12153
```changes
type: fix
summary: fix LB service creation in hybrid clusters
```
=> [cloud-provider-yandex] fix LB service creation in hybrid clusters

docs/site/pages/virtualization-platform/documentation/FAQ.md, docs/site/pages/virtualization-platform/documentation/FAQ_RU.md, docs/site/pages/virtualization-platform/documentation/admin/install/steps/BASE_CLUSTER_RU.md
DVP FAQ formatting edits.
```changes
section: docs
type: chore
summary: DVP FAQ formatting edits.
```
=> [docs] DVP FAQ formatting edits

.github/scripts/validation_bashible.sh, .github/workflow_templates/bashible_validation.yml, .github/workflows/bashible_validation.yml
This PR introduces a GitHub Actions workflow for validating `bashible` templates. The workflow triggers on `pull_request` events when changes are made to `.tpl` files within the following directories:
- `candi/bashible/**/*.tpl`
- `candi/cloud-providers/**/*.tpl`
- Ensures that Bashible templates remain valid before merging changes.
- Automates the validation process to prevent broken configurations.
- Improves CI/CD reliability by catching template issues early.
```changes
section: ci
type: chore
summary: This PR introduces a GitHub Actions workflow for validating `bashible` templates.
```
=> add bashible validation

modules/150-user-authn/docs/USAGE.md, modules/150-user-authn/docs/USAGE_RU.md
Add keycloak DexProvider example to docs.
Setting up keycloak requires notable settings regarding scopes.
```changes
type: chore
summary: Added DexProvider resource example for Keycloak.
```
=> [user-authn] Add keycloak dexprovider example

ee/modules/610-service-with-healthchecks/templates/agent/daemonset.yaml
Fix agent VPA min defaults
By default, agents request too many resources that they don't actually use
```changes
type: fix 
summary: Fix agent VPA min defaults
```
=> [service-with-healthchecks] Fix agent VPA min defaults

docs/documentation/_data/sidebars/main.yml, docs/documentation/pages/release-notes/1-68.md, docs/documentation/pages/release-notes/1-68_RU.md
This PR adds a new release notes section to DKP docs.
```changes
section: docs
type: chore
summary: Added the release notes section to DKP docs.
```
=> [docs] Add release notes

ee/candi/cloud-providers/vcd/terraform-modules/master-node/main.tf
Reverts deckhouse/deckhouse#12651
=> Revert "[cloud-provider-vcd] Change the etcd(kubernetes_data) storage disk type from vcd_vm_internal_disk to vcd_independent_disk "

dhctl/pkg/operations/check/check.go, dhctl/pkg/operations/converge/context/context.go, dhctl/pkg/operations/exporter.go, dhctl/pkg/state/infrastructure/state_version.go, dhctl/pkg/state/infrastructure/state_version_test.go, docs/documentation/_data/deckhouse-alerts.yml, modules/030-cloud-provider-yandex/images/cloud-migrator/werf.inc.yaml, modules/030-cloud-provider-yandex/templates/migration/job.yaml, modules/040-terraform-manager/images/base-terraform-manager/werf.inc.yaml, modules/040-terraform-manager/images/terraform-manager-yandex/werf.inc.yaml, modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl, testing/cloud_layouts/Static/configuration.tpl.yaml, testing/cloud_layouts/Static/infra.tpl.tf, testing/cloud_layouts/script.sh
=> yandex opentofu test: 1

candi/bashible/bashbooster/50_registrypackages.sh, candi/bashible/bb_package_install.sh.tpl
Additional correction for https://github.com/deckhouse/deckhouse/pull/11926
```changes
section: dhctl
type: fix 
summary: Fixed timeout value when downloading packets
impact: 
```
=> [dhctl] Fixed timeout value when downloading packets

.werf/defines/modules.tmpl, candi/image_versions.yml
Remove dev and obsolete images.
```changes
section: ci
type:  chore
summary: Remove dev and obsolete images
impact: 
```
=> [ci] remove obsolete dev-images

modules/300-prometheus/images/mimir/werf.inc.yaml, modules/300-prometheus/images/promxy/werf.inc.yaml
Clean build tools from src-artifacts mimir and promxy.
Reduce scanning area for vulnerabilities.
Not necessary.
```changes
type: chore
summary: Clean build tools from src-artifacts mimir and promxy.
```
=> [prometheus] clean build tools from src-artifacts

candi/control-plane-kubeadm/patches/kube-apiserver.yaml.tpl, candi/control-plane-kubeadm/patches/kube-controller-manager.yaml.tpl, candi/control-plane-kubeadm/patches/kube-scheduler.yaml.tpl, dhctl/pkg/kubernetes/actions/manifests/manifests.go, modules/002-deckhouse/templates/deployment.yaml
Change Go GC settings to improve memory consumption.
```changes
section: core
type: chore
summary: Change Go GC settings to improve memory consumption
impact: control-plane pods should restart
```
=> [deckhouse] Make GC run more frequently

modules/031-local-path-provisioner/images/helper/src/go.mod, modules/031-local-path-provisioner/images/local-path-provisioner/patches/001-go-mod.patch, modules/031-local-path-provisioner/images/local-path-provisioner/werf.inc.yaml
Update localpath-provisioner to actual version to fix CVE and get codebase up-to-date
Actual module version
```changes
type: chore
summary: update localpath-provisioner version
```
=> [local-path-provisioner] update version

candi/version_map.yml
pr caused regression so we roll back some of the changes.
https://github.com/deckhouse/deckhouse/pull/12024
yes 1.68
```changes
type: fix 
summary: partial rollback of changes in images cluster-autoscaler
impact: 
```
=> [node-manager] partial rollback of changes in images cluster-autoscaler

candi/cloud-providers/dvp/terraform-modules/master/variables.tf, candi/cloud-providers/dvp/terraform-modules/static-node/variables.tf, modules/030-cloud-provider-dvp/images/cloud-controller-manager/src/pkg/cloudprovider/dvp/cloud.go, modules/030-cloud-provider-dvp/images/cloud-controller-manager/src/pkg/cloudprovider/dvp/loadbalancer.go, modules/030-cloud-provider-dvp/images/dvp-common/api/api.go, modules/030-cloud-provider-dvp/images/dvp-common/api/loadbalancer.go, modules/030-cloud-provider-dvp/templates/cloud-controller-manager/deployment.yaml
=> Cloud provider dvp ccm lb

.github/CODEOWNERS
This reverts commit e51271ad398d990df16eb09f22c81550aae41930.
=> [chore] Revert "Update CODEOWNERS (#12695)"

.github/ci_includes/dmt_envs.yml, .github/ci_templates/tests.yml, .github/workflow_templates/build-and-test_dev.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml, Makefile, ee/fe/modules/340-monitoring-applications/applications/nats/prometheus-rules/nats.yaml, ee/fe/modules/500-basic-auth/module.yaml, ee/modules/610-service-with-healthchecks/module.yaml, modules/140-user-authz/module.yaml, modules/600-namespace-configurator/module.yaml, modules/600-secret-copier/module.yaml, modules/800-deckhouse-tools/module.yaml, modules/810-documentation/module.yaml, tools/dmt-lint.sh
DMT update to version 0.1.12
Adding new functionality, including telemetry activation.
```changes
section: tools
type: feature
summary: update DMT lint configuration and version to 0.1.12
```
=> [tools] feat: update DMT lint configuration and version to 0.1.12

modules/150-user-authn/docs/USAGE.md, modules/150-user-authn/docs/USAGE_RU.md
Made clarifications to the instructions for connecting the OIDC provider "Keycloak"
```changes
section: docs
type: chore
summary: made clarifications to the instructions for connecting the OIDC provider "Keycloak"
```
=> [docs] Update keycloak connection instructions

deckhouse-controller/pkg/controller/deckhouse-release/e2e/steps/10_notification.sh, deckhouse-controller/pkg/controller/deckhouse-release/e2e/steps/12_notification_with_autopatch.sh, deckhouse-controller/pkg/controller/deckhouse-release/e2e/steps/13_notification_with_canary.sh, deckhouse-controller/pkg/controller/deckhouse-release/e2e/steps/20_notification_with_error.sh
Update test scripts
```changes
type: chore
summary: update e2e test scripts.
```
=> Update releses tests

.github/ci_templates/build.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml, Makefile, tools/images_tags/main.go
when errors with go generate it is not clear on which part of the file it happens.
https://github.com/deckhouse/deckhouse/actions/runs/14355323433/job/40243334912?pr=12938
```changes
section: ci
type: chore
summary: added output of the file that is executed in go generate
impact: 
```
=> [ci] added output of the file that is executed in go generate

docs/documentation/_data/deckhouse-alerts.yml, modules/040-node-manager/monitoring/prometheus-rules/cloud-data-discovery.tpl
This PR includes edits for the description of the `UnmetCloudConditions` alert.
Ref: #12530 
```changes
section: docs
type: chore
summary: Edited the description of the `UnmetCloudConditions` alert.
```
=> [docs] Update alert description

.github/workflow_templates/deploy-channel.multi.yml, .github/workflows/deploy-alpha.yml, .github/workflows/deploy-beta.yml, .github/workflows/deploy-early-access.yml, .github/workflows/deploy-rock-solid.yml, .github/workflows/deploy-stable.yml
Fix pip install syntax in post deploy preparation.
This change fixes workflow job which updates release channel versions
```changes
section: ci
type: chore
summary: Fix CI job which updates release channel versions
```
=> [chore] fix pip install in post deploy preparation ci

docs/documentation/_data/supported_versions.yml, docs/documentation/_data/version_map_addition.json
Update the supported versions table for CSE.
```changes
section: docs
type: chore
summary: Update the supported versions table for CSE.
```
=> [docs] Update the supported versions table for CSE

tools/validation/no_cyrillic.go
Update linter for validating localization symbols in files.
```changes
section: docs
type: chore
summary: Update linter for validating localization symbols in files.
```
=> [ci][fix] Update files linter

modules/300-prometheus/docs/FAQ.md, modules/300-prometheus/docs/FAQ_RU.md
Added a warning about using the alert mechanism in the dashboard and its future removal in current versions of Grafana.
```changes
section: docs
type: chore
summary: added a warning about using the alert mechanism in the dashboard
```
=> [docs] Add a warning about using alerts in the dashboard

docs/site/_data/topnav-l2-products.json, docs/site/_includes/header.html
Add the icon and the "activity" section of the documentation.
```changes
section: docs
type: chore
summary: Fix the topnav for Deckhouse Code documentation on the site.
```
=> [docs][site] Fix the topnav for Deckhouse Code

ee/modules/650-runtime-audit-engine/docs/ADVANCED_USAGE.md, ee/modules/650-runtime-audit-engine/docs/ADVANCED_USAGE_RU.md
Change metric to actual name from `falco_events` to `falcosecurity_falcosidekick_falco_events_total`.
Change instruction about create debug event. `nsenter` looks like best choice, because:
1. We cant do something like
```
export TOKEN_SECRET=$(kubectl -n d8-monitoring get serviceaccount prometheus -o jsonpath='{.secrets[].name}')
export TOKEN=$(kubectl -n d8-monitoring get secret $TOKEN_SECRET -o jsonpath='{.data.token}' | base64 -d)
export POD_IP=$(kubectl -n d8-runtime-audit-engine get pods -l app=runtime-audit-engine -o jsonpath='{.items[0].status.podIP}')
curl --insecure -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -H "Accept: application/json" https://$POD_IP:4212/sidekick/test
```
or oneliner:
```
curl --insecure -X POST -H "Content-Type: …
```
=> [runtime-audit-engine] Update usage in docs

tools/build.go, tools/build_includes/candi-EE.yaml, tools/build_includes/candi-FE.yaml, tools/build_includes/candi-SE-plus.yaml, tools/build_includes/modules-BE.yaml, tools/build_includes/modules-EE.yaml, tools/build_includes/modules-FE.yaml, tools/build_includes/modules-SE-plus.yaml, tools/build_includes/modules-SE.yaml, tools/build_includes/modules-with-dependencies-BE.yaml, tools/build_includes/modules-with-dependencies-EE.yaml, tools/build_includes/modules-with-dependencies-FE.yaml, tools/build_includes/modules-with-dependencies-SE-plus.yaml, tools/build_includes/modules-with-dependencies-SE.yaml, tools/build_includes/modules-with-exclude-BE.yaml, tools/build_includes/modules-with-exclude-EE.yaml, tools/build_includes/modules-with-exclude-FE.yaml, tools/build_includes/modules-with-exclude-SE-plus.yaml, tools/build_includes/modules-with-exclude-SE.yaml
We use autogenerated imports in build process. We use it on the setup stage, but we modify git archive on the install stage. This PR fixes that issue.
```changes
section: ci
type: fix
summary: fix stageDependencies stage in included files
```
=> [ci] fix stageDependencies stage in included files

candi/cloud-providers/gcp/openapi/cloud_discovery_data.yaml, ee/candi/cloud-providers/huaweicloud/openapi/cloud_discovery_data.yaml
Fix some OpenAPI schemas for cloud discovery data. 
This change was made because OpenAPI validation has become stricter.
```changes
section: candi
type: fix
summary: Fix some OpenAPI schemas for cloud discovery data. 
```
=> [candi] Fix cloud discovery data schemas for gcp and huawei cloud

modules/040-control-plane-manager/docs/FAQ.md, modules/040-control-plane-manager/docs/FAQ_RU.md
[docs] updates docs about FAQ control-plane-manager
This supplement describes what to do when quota-backend-bytes in etcd is reached.
```changes
section: docs
type: chore
summary: Updates docs about FAQ control-plane-manager.
```
=> [docs] Updates docs about FAQ control-plane-manager

docs/documentation/_data/modules/modules-addition.json, docs/documentation/_includes/revision_comparison_detail_table.liquid, docs/documentation/_plugins/custom_hooks.rb, docs/site/backends/docs-builder-template/data/modules_all.json
Update DKP module editions.
```changes
section: docs
type: chore
summary: Update DKP module editions.
```
=> [docs] Update DKP module editions

.github/scripts/validation_run.sh
Improve validation skip instructions. 
```changes
section: ci
type: chore
summary: Improve validation skip instructions. 
```
=> [ci] Improve validation skip instructions

modules/110-istio/docs/EXAMPLES.md, modules/110-istio/docs/EXAMPLES_RU.md, modules/300-prometheus/docs/USAGE.md, modules/300-prometheus/docs/USAGE_RU.md, modules/302-vertical-pod-autoscaler/docs/EXAMPLES.md, modules/302-vertical-pod-autoscaler/docs/EXAMPLES_RU.md, modules/500-dashboard/docs/EXAMPLES.md, modules/500-dashboard/docs/EXAMPLES_RU.md, modules/810-documentation/docs/EXAMPLES.md, modules/810-documentation/docs/EXAMPLES_RU.md
Modified the `key: dedicated` label to `key: dedicated.deckhouse.io` in module examples to:
1. Provide clearer namespace separation
2. Avoid potential conflicts with user-defined applications
3. Maintain better alignment with Deckhouse naming conventions
```changes
section: docs
type: chore
summary:  Dedicated key fix in examples
```
=> [docs] Dedicated key fix in examples

modules/042-kube-dns/openapi/config-values.yaml
Make validation pattern for stubZones more widely.
Fix https://github.com/deckhouse/deckhouse/issues/390
Fix https://github.com/deckhouse/deckhouse/pull/12238
For example, we can setting kube-dns like this:
```
metadata:
name: kube-dns
spec:
enabled: true
settings:
stubZones:
- upstreamNameservers:
- 8.8.8.8
zone: _acme-challenge.example.com
upstreamNameservers:
- 10.128.0.6
version: 1
```
```changes
type: fix
summary: Expanded pattern for `stubZones` to allow underscores (`_`) in domain names.
```
=> [kube-dns] Change pattern for stubZones to allow _ 

modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
just a small fix for the alert implemented in this pr https://github.com/deckhouse/deckhouse/pull/12163
Alert rule fix
```changes
type: fix
summary:  Stale service account alert fix
impact: 
```
=> [control-plane-manager] Stale service account alert fix

docs/documentation/.werf/nginx.conf, docs/documentation/_includes/doclinks.liquid, docs/documentation/_plugins/custom_hooks.rb, docs/documentation/_plugins/render-jsonschema.rb, docs/documentation/_tools/modules_generate_cr.sh, docs/documentation/doclinks.json
Add JSON file with documentation links for modules and CRDs.
- File path - '/doclinks.json' 
- Example of the file structure:
```json
{
"modules": {
"admission-policy-engine": {
"overview": {
"internal": {
"en": "/en/platform/modules/admission-policy-engine/",
"ru": "/ru/platform/modules/admission-policy-engine/"
},
"external": {
"en": "/products/kubernetes-platform/documentation/v1/modules/admission-policy-engine/",
"ru": "/products/kubernetes-platform/documentation/v1/modules/admission-policy-engine/"
}
},
"crds": [
"operationpolicies.deckhouse.io",
"securitypolicies.deckhouse.io"
]
}
},
"crds": {
"operationpolicies.deckhouse.io": {
"internal": {
"en": "/en/platform/modules/admission-policy-engine/cr.html#operationpolicy",
"ru": …
```
=> [docs] Add JSON file with documentation links for modules and CRDs

.github/scripts/python/post-deploy-preparation.py, .github/workflow_templates/deploy-channel.multi.yml, .github/workflows/deploy-alpha.yml, .github/workflows/deploy-beta.yml, .github/workflows/deploy-early-access.yml, .github/workflows/deploy-rock-solid.yml, .github/workflows/deploy-stable.yml
* Bump werf action version for channels publishing job.
* Deploy to old production was removed. 
* Output error message from lib to highlight root cause of requests failure 
Fixes publishing release channels job failure.
Fixes deploy workflow.
```changes
section: ci
type: chore
summary: Fixes deckhouse deploy workflow
```
=> [chore] Fix and improve release channel publishing

docs/documentation/pages/admin/configuration/backup/BACKUP_AND_RESTORE_RU.md
New DKP structure — Deckhouse CLI backups.
=> [docs] New DKP structure — Deckhouse CLI backups

docs/documentation/_data/modules/editions-addition.json, docs/site/backends/docs-builder-template/data/editions.json, docs/site/backends/docs-builder-template/data/modules_all.json
Update DKP CSE editions.
Updates: https://github.com/deckhouse/deckhouse/pull/13159
```changes
section: docs
type: chore
summary: Update DKP CSE editions.
```
=> [docs] Update DKP CSE editions

modules/031-ceph-csi/module.yaml
Add "Deprecated" status to module
We need actual module status
```changes
type: chore
summary: Add "Deprecated" status to module
impact: low
```
=> [ceph-csi] add deprecated status

ee/modules/030-cloud-provider-openstack/images/cloud-data-discoverer/werf.inc.yaml, ee/modules/030-cloud-provider-vcd/images/cloud-data-discoverer-legacy/werf.inc.yaml, ee/modules/030-cloud-provider-vcd/images/cloud-data-discoverer/werf.inc.yaml, ee/se-plus/modules/030-cloud-provider-vsphere/images/cloud-data-discoverer/werf.inc.yaml, ee/se-plus/modules/030-cloud-provider-zvirt/images/cloud-data-discoverer/werf.inc.yaml, modules/030-cloud-provider-aws/images/cloud-data-discoverer/werf.inc.yaml, modules/030-cloud-provider-azure/images/cloud-data-discoverer/werf.inc.yaml, modules/030-cloud-provider-gcp/images/cloud-data-discoverer/werf.inc.yaml, modules/030-cloud-provider-yandex/images/cloud-data-discoverer/werf.inc.yaml
This PR adds `stageDependencies` where required
To fix images build.
```changes
section: cloud-data
type: fix
summary: add stageDependencies where required
```
=> [cloud-data] fix build - add stageDependencies where required

modules/040-control-plane-manager/hooks/audit_policy.go, modules/040-control-plane-manager/hooks/audit_policy_test.go
Add new AuditPolicy rules for virtualization module. Required for virtualization-audit controller.
At the moment, there is no way to add custom audit rules for modules. A temporary solution is to add the necessary rules to the controller-plane-manager.
```changes
type: chore
summary: add audit policy rules for virtualization
```
=> [control-plane-manager] add audit policy for virtualization

modules/040-node-manager/templates/capi-controller-manager/rbac-for-us.yaml
Extend capi-controller-manager permissions to the root path ('/')  of the Kubernetes API with RBAC.
This PR fixes the dramatic increase in 403 errors from the `capi-controllers-manager` on `GET /?timeout=5s` requests. It can be observed by the `rest_client_requests_total{code=~"4..", job="capi-controller-manager"}` request in Prometheus.
```changes
type: fix
summary: Fixed increased 403 errors from capi-controller-manager accessing the Kubernetes API server root path ('/').
```
=> [node-manager] extend capi-controller-manager permissions

docs/site/_includes/getting_started/zvirt/partials/config.ru.yml.standard.other.inc, docs/site/_includes/getting_started/zvirt/partials/config.yml.standard.other.inc
This PR updates several items in zVirt's getting started instructions.
```changes
section: docs
type: chore
summary: Updated getting started instructions for zVirt.
```
=> [docs] Update getting started instructions for zVirt

dhctl/pkg/preflight/sudoers.go
Fix sudoers preflight check: works correctly with passwords contains whitespaces
Fix https://github.com/deckhouse/deckhouse/issues/13130
Incorrect behavior is reproducible at least in 1.68, 1.69
```changes
section: dhctl
type: fix
summary: Fix incorrect behavior that fails sudoers preflight check if password contains whitespaces.
```
=> [dhctl] Fix sudoers preflight check

candi/terraform_versions.yml, modules/030-cloud-provider-dvp/images/cloud-data-discoverer/src/discoverer.go, modules/030-cloud-provider-dvp/images/cloud-data-discoverer/src/go.mod, modules/030-cloud-provider-dvp/images/cloud-data-discoverer/src/go.sum
=> use opentofu

docs/documentation/_data/i18n.yml, docs/documentation/_data/modules/modules-addition.json, docs/site/backends/docs-builder-template/data/modules_all.json, docs/site/backends/docs-builder-template/layouts/partials/sidebar.html
Fix DKP modules editions availability info.
```changes
section: docs
type: chore
summary: Fix DKP modules editions availability info.
```
=> [docs] Fix DKP modules editions availability info

modules/040-terraform-manager/images/base-terraform-manager/werf.inc.yaml
Add terraform_versions.yaml to tofu base terraform image
terraform autoconverger and state exporter do not work for yandex cloud 
```changes
type: fix
summary: Add terraform_versions.yaml to tofu base terraform image.
```
=> [terraform-manager] Add terraform_versions.yaml to tofu base terraform image

testing/cloud_layouts/script.d/wait_cluster_ready/test_autoscaler.sh
Added caching cordon node event.
It is important for us to know whether the node was cordoned before deletion or not. It is also important for us whether the node was successfully drained, but for now this functionality (creating an event about a successful drain) is only available in cluster-api (https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machine/machine_controller.go#L518) but not in mcm. Therefore, we will limit ourselves to cordon events only and assume that if the node was cordoned, then it was drained.
```changes
type: feature
summary: Add condition for cordon event during scaling
```
=> [testing][e2e][autoscaler] Add condition for cordon event during scaling

modules/021-cni-cilium/images/bin-cilium/patches/006-add-pod-prioroty-managment.patch
Update priority label patch for Cilium v1.17.
```changes
type: fix
summary: update priority label patch for Cilium v1.17
```
=> [cilium] update priority label patch

docs/documentation/_data/sidebars/main.yml, docs/documentation/pages/module-development/RUN.md, docs/documentation/pages/module-development/RUN_RU.md
Integrating Deckhouse Module Tools for Module Validation and Metrics Collection.
```changes
section: docs
type: chore
summary: Integrating Deckhouse Module Tools for Module Validation and Metrics Collection.
```
=> [docs] Deckhouse Module Tools user guide

docs/documentation/_data/modules/modules-addition.json, docs/site/backends/docs-builder-template/data/modules_all.json
Update editions for the console module.
```changes
section: docs
type: chore
summary: Update editions for the console module.
```
=> [docs] update editions for the console module

deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_release.go, deckhouse-controller/pkg/controller/module-controllers/release/controller_test.go, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/apply-force-release.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/apply-force-release.yaml
Module Release GetForce() function returns only false.
Must return true if force annotation `modules.deckhouse.io/force` set with "true"
```changes
type: fix
summary: fix module release force behaviour
```
=> [deckhouse-controller] fix module release force behaviour

.github/ci_templates/build.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml
Add vex ci vars to build envs.
```changes
section: ci
type: chore
summary: Add vex ci vars to build envs
```
=> [ci] add vex ci vars

deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_release.go, deckhouse-controller/pkg/controller/module-controllers/release/controller_test.go, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/apply-force-release.yaml, deckhouse-controller/pkg/controller/module-controllers/release/testdata/releases/golden/apply-force-release.yaml
Backport [PR](https://github.com/deckhouse/deckhouse/pull/13378)
```changes
type: fix
summary: fix module release force behaviour
```
=> [deckhouse-controller] 1.68 fix module release force behaviour

docs/documentation/_data/deckhouse-alerts.yml, modules/031-ceph-csi/monitoring/prometheus-rules/deprecated-module-alert.yaml
Add alert about future ceph-csi module remove
Users must be informed about future module removance
```changes
type: chore
summary: Add alert about future ceph-csi module remove
```
=> [ceph-csi] Add alert about future remove

docs/documentation/pages/security/KUMA.md, docs/documentation/pages/security/KUMA_RU.md, ee/modules/650-runtime-audit-engine/docs/FAQ.md, ee/modules/650-runtime-audit-engine/docs/FAQ_RU.md, modules/460-log-shipper/docs/EXAMPLES.md, modules/460-log-shipper/docs/EXAMPLES_RU.md, modules/462-loki/docs/EXAMPLES.md, modules/462-loki/docs/EXAMPLES_RU.md
Update version for ClusterLoggingConfig in examples from deckhouse.io/v1alpha1 to deckhouse.io/v1alpha2.
```changes
section: docs
type: chore
summary: Update version for ClusterLoggingConfig in examples.
```
=> [docs] Update version for ClusterLoggingConfig in examples

docs/site/_config.yml, docs/site/_includes/counters-and-chat.liquid
Adjust the metric.
```changes
section: docs
type: chore
summary: Added the division of metrics by domain.
```
=> [docs] Adjust the metric

candi/terraform_versions.yml, dhctl/pkg/infrastructureprovider/get_test.go, ee/candi/cloud-providers/dynamix/terraform-modules/master-node/variables.tf, ee/candi/cloud-providers/dynamix/terraform-modules/static-node/variables.tf, go_lib/cloud-data/apis/v1/dynamix_cloud_provider_discovery_data.go
Replacing Terraform with OpenTofu for Dynamix
An old version of Terraform is used, which has CVE vulnerabilities that cannot be fixed.
```changes
section: candi
type: fix
summary: Replacing Terraform with OpenTofu for Dynamix
```
=> [candi] Replacing Terraform with OpenTofu for Dynamix

modules/470-chrony/images/chrony-exporter/patches/001-go-mod.patch, modules/470-chrony/images/chrony-exporter/werf.inc.yaml
this pr fix chrony exporter CVE vulnerabilities
bump packages versions to fix CVE vulnerabilities
https://defectdojo.flant.com/test/18660
```changes
type: fix
summary: chrony exporter CVE vulnerabilities fixes
```
=> [chronyExporter] Chrony exporter CVE vulnerabilities fixes

modules/400-descheduler/images/descheduler/patches/001-go-mod.patch, modules/400-descheduler/images/descheduler/werf.inc.yaml
this pr fix descheduler CVE vulnerabilities
bump versions to fix CVE vulnerabilities
https://defectdojo.flant.com/test/17246
```changes
type: fix
summary: descheduler CVE vulnerabilities fixes
```
=> [descheduler] Descheduler CVE vulnerabilities fixes

.github/workflow_templates/e2e-autoclean.yml, .github/workflows/e2e-autoclean.yml
When updating the reporting mechanism, backward compatibility was not preserved
Fix the mechanism for sending reports
```changes
section: ci
type: fix
summary: Fix the mechanism for sending reports.
```
=> fix: report on e2e autoclean

modules/302-vertical-pod-autoscaler/images/vertical-pod-autoscaler/patches/001-go-mod.patch, modules/302-vertical-pod-autoscaler/images/vertical-pod-autoscaler/werf.inc.yaml
this pr fix vertical pod autoscaler CVE vulnerabilities
bump packages versions to fix CVE vulnerabilities
https://defectdojo.flant.com/test/19148 admissioncontroller
https://defectdojo.flant.com/test/19138 updater
https://defectdojo.flant.com/test/19128 recommender
```changes
type: fix
summary: vpa cve vulnerabilities fixes
```
=> [vpa] VPA CVE vulnerabilities fixes

.github/scripts/cve_scan.sh, .github/scripts/python/defectdojo_dev_tests_rotator.py
- Fix floating unauthorized error in registry during trivy DBs update
- Fix for DD tests rotator to not delete needed tests
- Random unauthorized error in registry during trivy DBs update fails pipeline
- DD tests rotator deletes needed tests because of wrong if condition
```changes
section: ci
type: fix
summary: Fix trivy registry login on DBs update
impact: none
```
=> Fix trivy registry login on DBs update and fix DD tests rotator

candi/cloud-providers/dvp/openapi/cluster_configuration.yaml, candi/cloud-providers/dvp/openapi/doc-ru-cluster_configuration.yaml, candi/cloud-providers/dvp/openapi/doc-ru-instance_class.yaml, candi/cloud-providers/dvp/openapi/instance_class.yaml
This PR updates the OpenAPI schema definitions for the DVP cloud provider.
```changes
section: docs
type: chore
summary: Edited OpenAPI schema descriptions for DVP cloud provider.
```
=> [docs] Update schema definitions for DVP cloud provider

deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_module_config.go
Fixes issues with remote modules that cannot be unabled unless found in moduleStorage
```changes
type: fix
summary: fixes issue where modules cannot be enabled unless already in module storage
```
=> [deckhouse-controller]: fix remote module enable

ee/modules/650-runtime-audit-engine/images/falco/patches/falcoctl/001-go-mod.patch, ee/modules/650-runtime-audit-engine/images/falco/werf.inc.yaml
this pr fix falco CVE vulnerabilities
bump packages versions to fix CVE vulnerabilities
https://defectdojo.flant.com/test/18725
```changes
type: fix
summary: falco CVE vulnerabilities fixes
```
=> [falco] Falcoctl CVE vulnerabilities fixes

testing/cloud_layouts/script-commander.sh
Error when updating comment is not displayed correctly
Fix error text display when updating comment
```changes
section: ci
type: fix
summary: Fix error text display when updating comment.
```
=> [testing] Change comment var name

modules/000-common/images/shell-operator/werf.inc.yaml
```changes
type: fix 
summary: fixed usage sh in shell-operator
```
=> [deckhouse] fixed usage sh in shell-operator

docs/documentation/_data/modules/modules-addition.json, docs/site/_assets/css/components/_table-supported.scss, docs/site/_assets/css/docs.scss, docs/site/_assets/js/table-sticky.js, docs/site/_includes/head-site.html
Adjusting the table header and tooltips.
```changes
section: docs
type: chore
summary: Adjusting the table header and tooltips.
```
=> [docs] Fix the table header and tooltips

.github/workflow_templates/deploy-channel.multi.yml, .github/workflows/deploy-alpha.yml, .github/workflows/deploy-beta.yml, .github/workflows/deploy-early-access.yml, .github/workflows/deploy-rock-solid.yml, .github/workflows/deploy-stable.yml
Notify with custom message on deploy failure
If deploy failed on some edition - it is easy to miss it
```changes
section: ci
type: chore
summary: Notification on Deploy failure
impact: none
```
=> Notification on Deploy failure

modules/200-operator-prometheus/docs/README.md, modules/200-operator-prometheus/docs/README_RU.md
Correct info about Prometheus pod
```changes
type: chore
summary: Update info about Prometheus pods in the documentation.
```
=> [docs][operator-prometheus] Update info about Prometheus pods

.github/ci_templates/build.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml
Prints message when "Go generate" CI job fails.
Example:
This message might help people to fix problems faster.
```changes
section: ci
type: chore
summary: Add informative message on go generate failure.
```
=> [ci] Add informative message on go generate failure

docs/site/backends/docs-builder-template/data/modules_all.json
Update editions for static-routing-manager module.
Ref: https://github.com/deckhouse/deckhouse/pull/13433
```changes
section: docs
type: chore
summary: Update editions for static-routing-manager module.
```
=> docs: update editions for static-routing-manager module

modules/040-node-manager/crds/nodeuser.yaml
Fix validation for nodeuser in CRD
This changes was checked in the test cluster: a test cluster was deployed, and on the test cluster, a nodeuser was created. The cluster was switched to this PR. After the switch, the configuration validation of nodeuser was checked. A new nodeuser was successfully created."
Closes https://github.com/deckhouse/deckhouse/issues/12630 in which the problem has been described.
```changes
type: fix
summary: Correct CRD for validation
```
=> [node-manager] Fix validation for nodeuser

docs/site/_data/dvp/comparison.yaml
Update restrictions for DVP.
```changes
section: docs
summary: Update restrictions for DVP.
```
=> [docs] Update restrictions for DVP

docs/site/_data/dvp/comparison.yaml
Fix restrictions for DVP.
```changes
section: docs
type: chore
summary: Fix restrictions for DVP.
```
=> [docs] Fix restrictions for DVP

.github/workflow_templates/k8s-autoupdate.yml, .github/workflows/k8s-autoupdate.yml
There are no vulnerability checks on automatic pull requests
Add automatic vulnerability checks to pull requests
```changes
section: ci
type: feature
summary: Add automatic vulnerability checks to pull requests.
```
=> feat: add security scan on k8s autoupdate

modules/110-istio/crds/ingress-istio.yaml
Fix example values for httpPort and httpPorts in IngressIstioController.
```changes
section: docs
type: chore
summary: Fix example values for httpPort and httpPorts in IngressIstioController.
```
=> [doc] Fix some example values in  IngressIstioController

docs/site/_data/i18n.yaml, docs/site/_data/kubernetes-platform/guides.yaml, docs/site/pages/guides/guides_main.html
This PR introduces a few wording edits for the guide landing page texts.
```changes
section: docs
type: chore
summary: Edited texts on the guide landing page.
```
=> [docs] Update texts on guide landing page

deckhouse-controller/crds/module.yaml
Remove harmful enum field
This enum breaks modules with a new `Preview` values inside the `stage` field. While the deckhouse-controller's logic is not based on this field at all, we can make it wildcard, same as is the later deckhouse versions (1.68+)
```changes
type: fix 
summary: Remove harmful enum limitation from the Module CRD.
```
=> [deckhouse] Remove harmful enum from module.yaml

docs/site/_assets/css/components/_tile.scss
Update tiles style.
```changes
section: docs
type: chore
summary: Update tiles style.
```
=> [docs] Update tiles style

docs/documentation/_data/modules/modules-addition.json, docs/site/backends/docs-builder-template/data/modules_all.json
Add editions info about observability module.
```changes
section: docs
type: chore
summary: Add editions info about observability module.
```
=> [docs] Add editions info about observability module

modules/810-documentation/templates/configmap.yaml
Update the nginx configuration in the documentation module to solve issues with HTTP redirects when self-signed certificates are used in a cluster.
```changes
type: chore
summary: Update the nginx configuration in the documentation module to solve issues with HTTP redirects when self-signed certificates are used in a cluster.
```
=> [documentation] Update nginx configuration

docs/documentation/_data/modules/modules-addition.json, docs/site/backends/docs-builder-template/data/modules_all.json
Update the console module editions and add restrictions. The Console module is now available in CE and BE with restrictions.
```changes
section: docs
type: chore
summary: Update console module editions and add restrictions
```
=> [docs] Update console editions and add restrictions

docs/site/_assets/js/popup-form.js
Spam from the form.
```changes
section: docs
type: chore
summary: Block spam from the form on the site.
```
=> [docs] Block spam from the form on the site

docs/documentation/pages/admin/configuration/access/authentication/EXTERNAL_AUTHENTICATION_PROVIDERS_RU.md, docs/documentation/pages/admin/configuration/access/authentication/OVERVIEW.md
Update info about using Keycloak into the new documentation structure
=> [docs] Update info about using Keycloak into the new documentation structure

modules/150-user-authn/docs/USAGE.md, modules/150-user-authn/docs/USAGE_RU.md
Add warning about usage Keycloak as Idenitity Provider
```changes
section: docs
type: fix
summary: Update docs about Keycloak configuration for IP
```
=> [docs] Add Keycloak Idenitiy Provider warning

.github/ci_templates/helper_jobs.yml, .github/workflows/cve-pr.yml, .github/workflows/e2e-aws.yml, .github/workflows/e2e-azure.yml, .github/workflows/e2e-eks.yml, .github/workflows/e2e-gcp.yml, .github/workflows/e2e-openstack.yml, .github/workflows/e2e-static.yml, .github/workflows/e2e-vcd.yml, .github/workflows/e2e-vsphere.yml, .github/workflows/e2e-yandex-cloud.yml
returned the condition when the branch was not found
```changes
section: ci
type: fix
summary: returned the condition when the branch was not found
```
=> fix: block until the docker image job

docs/documentation/_data/deckhouse-alerts.yml, modules/500-openvpn/monitoring/prometheus-rules/ovpn-admin.yaml
Fixed alerts for openvpn client certificates.
Invalid condition for client certificates to be triggered.
We need to turn off the wrong alerts from the current customers.
```changes
type: fix 
summary: Fixed condition of alert triggering for client certificate.
```
=> [openvpn] Fix client cert alerts alerting.

ee/modules/030-cloud-provider-dynamix/module.yaml, ee/modules/030-cloud-provider-huaweicloud/module.yaml, ee/modules/030-cloud-provider-openstack/module.yaml, ee/modules/030-cloud-provider-vcd/module.yaml, ee/se-plus/modules/030-cloud-provider-vsphere/module.yaml, ee/se-plus/modules/030-cloud-provider-zvirt/module.yaml, modules/030-cloud-provider-aws/module.yaml, modules/030-cloud-provider-azure/module.yaml, modules/030-cloud-provider-dvp/module.yaml, modules/030-cloud-provider-gcp/module.yaml, modules/030-cloud-provider-yandex/module.yaml
Add `stage` to the `module.yaml` of every cloud provider.
All modules of the DKP must have specified `stage`.
```changes
section: cloud-provider-aws, cloud-provider-azure, cloud-provider-gcp, cloud-provider-dvp, cloud-provider-yandex, cloud-provider-zvirt, cloud-provider-dynamix, cloud-provider-vcd, cloud-provider-vsphere, cloud-provider-huaweicloud, cloud-provider-openstack
type: chore
summary: Add `stage` to every cloud provider module
```
=> [cloud-provider-*] add stage to the module.yaml

docs/documentation/_includes/release-notes/RELEASE-NOTES.md, docs/documentation/_includes/release-notes/RELEASE-NOTES_RU.md
Added RN 1.70 for doc site.
```changes
section: docs
type: chore
summary: Added RN 1.70 for doc site.
```
=> [docs] Added RN 1.70 for doc site

global-hooks/openapi/values.yaml, modules/402-ingress-nginx/template_tests/controller_test.go
Resolve conflicts to successfully merge [ingress-nginx] Restore validation (https://github.com/deckhouse/deckhouse/pull/13648)
```changes
type: fix
summary: Resolve conflicts to successfully merge [ingress-nginx] Restore validation 
```
=> Release 1.70 fix files to "Restore validation" commit merge

deckhouse-controller/pkg/controller/module-controllers/docbuilder/controller.go, deckhouse-controller/pkg/controller/module-controllers/downloader/downloader.go
Fix documentation file walk logs with debug level
Fix controller logs empty message
```changes
type: fix
summary: fixes logs output
```
=> [deckhouse-controller] Fix supress logs, fixes logs message

.github/CODEOWNERS
Add @Zhbert to CODEOWNERS.
```changes
section: ci
type: chore
summary: Update CODEOWNERS.
```
=> [ci][chore] Update CODEOWNERS

candi/openapi/dhctl/doc-ru-ssh_configuration.yaml, candi/openapi/dhctl/doc-ru-ssh_host_configuration.yaml, candi/openapi/dhctl/ssh_configuration.yaml, candi/openapi/dhctl/ssh_host_configuration.yaml, docs/documentation/_tools/modules_generate_configuration.sh, docs/documentation/pages/installing/CONFIGURATION.md, docs/documentation/pages/installing/CONFIGURATION_RU.md, docs/documentation/werf-git-section.inc.yaml
Rendered SSHHost and SSHConfig specs.
```changes
section: docs
type: fix
summary: Rendered SSHHost and SSHConfig specs.
```
=> [docs] Render SSHHost and SSHConfig specs

docs/site/_assets/css/docs.scss, docs/site/_assets/js/customscripts.js
Fix bugs in code blocks.
```changes
section: docs
type: chore
summary: Fix bugs in code blocks.
```
=> [docs] Fix bugs in code blocks

.github/workflow_templates/trivy-db-schedule.yml, .github/workflows/trivy-db-schedule.yml
This pull request updates the dependency to a newer version that includes improved resilience when downloading data from the external BDU source (https://bdu.fstec.ru).
The updated version introduces:
- HTTP client timeouts
- Retry mechanism with exponential backoff
- Context-based overall request deadline
- Better logging of download errors
Previously, downloads from the BDU service could hang or fail due to service instability, causing downstream update jobs to become unreliable.
By upgrading to the fixed version, we ensure more stable behavior in case of network issues or temporary unavailability of the external service.
```changes
section: ci
type: fix
summary: Update trivy-db version to improve BDU download reliability
```
=> Update trivy-db version to improve BDU download reliability

.github/workflow_templates/k8s-autoupdate.yml, .github/workflows/k8s-autoupdate.yml, candi/tools/update_kubernetes_patchversions.sh, candi/version_map.yml
Currently, e2e tests do not cover all the required versions when automatically updating k8s
Ensure all required versions are tested when automatically updating k8s
```changes
section: ci
type: feature
summary: Ensure all required versions are tested when automatically updating k8s.
```
=> Feat/k8s autoupdate/k8s version testing

.werf/defines/installer.tmpl, .werf/werf-dev-install.yaml
Fix install image after #13442 
```changes
section: ci
type: fix
summary: fix install image
```
=> [install] fix install image

dhctl/pkg/preflight/check_cloud_api.go, dhctl/pkg/preflight/registry.go, dhctl/pkg/preflight/ssh.go
Addition to the preflight check error about the necessity of checking a specific parameter
```changes
section: dhctl
type: chore
summary: Addition to the preflight check error about the necessity of checking a specific parameter
```
=> update preflight error about ssh tunnel

deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_config.go, deckhouse-controller/pkg/controller/module-controllers/config/controller.go
Add new finalizer for module config
`modules.deckhouse.io/module-registered`
Old finalizer will be removed from every resource.
```changes
type: fix
summary: handle new module config finalizer
```
=> [deckhouse-controller] Handle new module config finalizer

docs/site/pages/stronghold/documentation/admin/platform-management/network/EGRESS.md, docs/site/pages/stronghold/documentation/admin/platform-management/network/EGRESS_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/network/EGRESS.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/network/EGRESS_RU.md
Fix one sentence in doc about EgressGatewayPolicy.
```changes
section: docs
type: chore
summary: Fix one sentence in doc about EgressGatewayPolicy.
```
=> [docs] fix one sentence in doc about EgressGatewayPolicy

docs/site/.helm/templates/14-frontend.yaml, docs/site/.helm/templates/_helpers.tpl
Add custom probes to docs site deployment.
Prevents premature failure of werf converge job.
```changes
section: ci
type: chore
summary: Prevents premature failure of werf converge job.
```
=> [docs][site] Add custom probes to deployment

docs/documentation/_data/sidebars/main.yml, docs/documentation/pages/admin/configuration/logging/DELIVERY_RU.md, docs/documentation/pages/admin/configuration/logging/STORAGE_RU.md, docs/documentation/pages/architecture/LOGGING_RU.md, docs/documentation/pages/user/LOGGING.md, docs/documentation/pages/user/LOGGING_RU.md
This PR introduces updates in the Logging sections of the new docs structure upon a review by the dev team.
=> [docs][new structure] Update Logging sections after review

docs/site/.helm/templates/_helpers.tpl
Fix docs deployment probes. (Recommended)
Fix docs deployment jobs failure. Werf calculation expression of pod readiness doesn't have enough time to wait for pod readiness.
```changes
section: ci
type: chore
summary: Fix docs deployment probes.
```
=> [chore] [ci] Docs deployment probes

docs/documentation/_data/deckhouse-alerts.yml, modules/340-monitoring-deckhouse/monitoring/prometheus-rules/alerting.yaml
Change command in the alert hint
Dump also the cpu profile
```changes
section: monitoring-deckhouse
type: fix
summary: Fix the alert description.
```
=> [monitoring-deckhouse] Change command for dump

docs/documentation/_includes/module-settings.liquid
Fix module configuration snippet.
```changes
section: docs
type: chore
summary: Fix module configuration snippet.
```
=> [docs] Fix module configuration snippet

modules/300-prometheus/docs/USAGE.md, modules/300-prometheus/docs/USAGE_RU.md
Fix formatting on the usage page in the `prometheus` module.
```changes
section: docs
type: chore
summary: Fix formatting on the usage page in the `prometheus` module.
```
=> [docs][prometheus] Fix formatting on the usage page

docs/documentation/_data/sidebars/main.yml, docs/documentation/pages/user/network/ISTIO_SIDECAR_RESOURCE_MANAGEMENT.md, docs/documentation/pages/user/network/ISTIO_SIDECAR_RESOURCE_MANAGEMENT_RU.md
Added info about istio sidecars resource limitations.
=> [docs][new-structure] Add info about istio sidecars resource limitations

docs/site/_assets/css/docs.scss
Margins in lists.
```changes
section: docs
type: chore
summary: Margins in lists.
```
=> [docs] Margins in lists

go_lib/hooks/storage_class_change/hook.go
It fixes storage class change issue.
It is a manual backport for https://github.com/deckhouse/deckhouse/pull/14286
Closes #14278
Prev versions affected too.
```changes
type: fix
summary: Filter deleted pvcs in storage class change hook.
```
=> [deckhouse] 1.70 fix storage class change hook

modules/340-monitoring-ping/images/monitoring-ping/src/pkg/fastping/sockets.go
We optimized the packet reading function by replacing the polling loop with an epoll-based event mechanism. As a result, CPU usage decreased significantly — from ~0.08 to ~0.008 core.
<details>
<summary>Screenshots</summary>
</details>
Previously, the packet reading logic used a tight loop with recvmsg and short time.Sleep delays to check for new packets. This "polling" approach constantly consumed CPU cycles — even when no packets were arriving.
There are clusters with deckhouse 1.70 who don't happy about high consumption, but can wait for 1.71, so we decided to release the fix in 1.71.
```changes
type: fix
summary: Reducing PROCESSOR time consumption by changing the method of waiting for incoming packets.
```
=> [monitoring-ping] optimize CPU consumption

docs/documentation/_data/sidebars/main.yml, docs/documentation/pages/user/LOGGING.md, docs/documentation/pages/user/LOGGING_RU.md, docs/documentation/pages/user/monitoring/OVERVIEW.md, docs/documentation/pages/user/monitoring/OVERVIEW_RU.md
Update sibebar and some page titles
=> [docs][new structure] Update sibebar and some page titles

modules/002-deckhouse/templates/registry/registry-config-secret.yaml, modules/002-deckhouse/templates/registry/validation.yaml
```changes
type: fix
summary: introduce a new validation hook
impact: 
```
=> Introduce a new validation hook

dhctl/go.mod, dhctl/go.sum, go.mod, go.sum, go_lib/registry/go.mod, go_lib/registry/go.sum, go_lib/registry/models/bashible/config.go, go_lib/registry/models/bashible/config_test.go, go_lib/registry/models/bashible/context.go, go_lib/registry/models/bashible/context_test.go, modules/038-registry/hooks/checker/models.go, modules/038-registry/hooks/checker/models_test.go, modules/038-registry/hooks/orchestrator/hook.go, modules/038-registry/hooks/orchestrator/incluster-proxy/models.go, modules/038-registry/hooks/orchestrator/incluster-proxy/user.go, modules/038-registry/hooks/orchestrator/incluster-proxy/user_test.go, modules/038-registry/hooks/orchestrator/models.go, modules/038-registry/hooks/orchestrator/models_test.go, modules/038-registry/openapi/values.yaml, modules/038-registry/templates/inclusterproxy/deployment.yaml, modules/038-registry/templates/inclusterproxy/secret.yaml, modules/040-node-manager/images/bashible-apiserver/src/go.mod, modules/040-node-manager/images/bashible-apiserver/src/go.sum, modules/040-node-manager/images/bashible-apiserver/src/pkg/template/registry/data_test.go, modules/040-node-manager/images/bashible-apiserver/src/pkg/template/registry/deckhouse_registry_test.go, modules/040-node-manager/images/bashible-apiserver/src/pkg/template/registry/registry_bashible_cfg_test.go
Anonymous authorization for Direct mode
```changes
type: fix
summary: anonymous authorization
impact:
```
=> [Registry] Anonymous authorization for Direct mode

docs/documentation/pages/module-development/EXAMPLE.md, docs/documentation/pages/module-development/EXAMPLE_RU.md, docs/documentation/pages/module-development/RUN.md, docs/documentation/pages/module-development/RUN_RU.md, docs/documentation/pages/storage/external/NFS.md, docs/documentation/pages/storage/external/NFS_RU.md, docs/documentation/pages/storage/external/YADRO.md, docs/documentation/pages/storage/external/YADRO_RU.md, docs/documentation/pages/storage/sds/LVM_LOCAL.md, docs/documentation/pages/storage/sds/LVM_LOCAL_RU.md, docs/documentation/pages/storage/sds/LVM_REPLICATED.md, docs/documentation/pages/storage/sds/LVM_REPLICATED_RU.md, docs/site/backends/docs-builder-template/content/modules/_index.md, docs/site/backends/docs-builder-template/content/modules/_index.ru.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/external/NFS.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/external/NFS_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/external/YADRO.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/external/YADRO_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/sds/LVM_LOCAL.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/sds/LVM_LOCAL_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/sds/LVM_REPLICATED.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/storage/sds/LVM_REPLICATED_RU.md
Changed examples in module info (get module).
```changes
section: docs
type: chore
summary: Changed examples in module info (get module).
```
=> [docs] Changed examples in module info (get module)

docs/documentation/_data/sidebars/main.yml, docs/documentation/pages/admin/configuration/access/authentication/RESOURCE_CONFIGURATION.md, docs/documentation/pages/admin/configuration/access/authentication/RESOURCE_CONFIGURATION_RU.md
Add documentation about limits to all DexAuthenticator containers in the new structure.
=> [docs] Added documentation about limits to all DexAuthenticator containers  at new structure

docs/documentation/pages/module-development/STRUCTURE.md, docs/documentation/pages/module-development/STRUCTURE_RU.md, docs/site/_assets/css/docs.scss, docs/site/_assets/js/codeblock.js
Fix a bug in the list's code block.
```changes
section: docs
type: chore
summary: Fix a bug in the list's code block.
```
=> [docs] Fix a bug in the list's code block

modules/002-deckhouse/templates/registry/validation.yaml
```changes
type: fix
summary: fixed validation webhook
impact: 
```
=> Fix validation webhook

modules/038-registry/hooks/orchestrator/bashible/models_test.go, modules/038-registry/hooks/orchestrator/pki/models_test.go, modules/038-registry/hooks/orchestrator/pki/state_test.go, modules/038-registry/hooks/orchestrator/registry-switcher/models_test.go, modules/038-registry/hooks/orchestrator/secrets/models_test.go, modules/038-registry/hooks/orchestrator/users/models_test.go
```changes
type: feature
summary: add tests for orchestrator
impact: 
```
=> Add tests for orchestrator

docs/documentation/pages/admin/configuration/access/authentication/EXTERNAL_AUTHENTICATION_PROVIDERS.md, docs/documentation/pages/admin/configuration/access/authentication/EXTERNAL_AUTHENTICATION_PROVIDERS_RU.md
Fix example in Bitbucket Cloud Integration section in the new documentation.
=> [docs][new structure] Fix example in Bitbucket Cloud Integration section

.github/CODEOWNERS
Added @skurbatov as istio codeowner.
```changes
section: tools
type: chore
summary: Added skurbatov as istio codeowner.
```
=> [istio] Added skurbatov as codeowner

docs/site/_assets/js/codeblock.js
Fix a bug in code blocks in the getting started.
```changes
section: docs
type: chore
summary: Fix a bug in code blocks in the getting started.
```
=> [docs] Fix a bug in code blocks in the getting started

docs/documentation/pages/user/TLS.md, docs/documentation/pages/user/TLS_RU.md
This PR adds translation for the TLS certificate usage page in the new docs structure.
=> [docs][new structure] Translate page about using TLS certificates

modules/300-prometheus/docs/USAGE.md, modules/300-prometheus/docs/USAGE_RU.md
Add email customAlertManager example.
Email setup is complicated and we need an example.
```changes
type: chore
summary: Add email customAlertManager example.
```
=> [docs][prometheus] Add email customAlertManager example

docs/documentation/_data/sidebars/main.yml
Update sidebar for the registry module.
```changes
section: docs
type: chore
summary: Update sidebar for the registry module
```
=> [docs] Update sidebar for the registry module

.github/ci_templates/build.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml
To debug a build, you often need the werf file used for the build. You need to remember that the file contains sensitive data.
Implement saving and encryption of werf file
```changes
section: ci
type: feature
summary: Implement saving and encryption of werf file.
```
=> Feat: save werf render

testing/cloud_layouts/script-commander.sh
The configuration_error error is currently not handled
Handle configuration_error in commander
```changes
section: ci
type: fix
summary: Handle the configuration_error in commander
```
=> fix: Handle configuration_error in commander

docs/documentation/pages/admin/configuration/integrations/public/amazon/CONFIGURATION_AND_LAYOUT.md, docs/documentation/pages/admin/configuration/integrations/public/amazon/CONFIGURATION_AND_LAYOUT_RU.md
Added info about aws security groups at new structure.
=> [docs][new structure] Add info about AWS security groups

docs/site/_data/footer.json, docs/site/_includes/header.html
Update header and footer on the site.
```changes
section: docs
type: chore
summary: Update header and footer on the site.
```
=> [docs] Update header and footer on the site

docs/documentation/pages/admin/configuration/integrations/hybrid/OVERVIEW.md, docs/documentation/pages/admin/configuration/integrations/hybrid/OVERVIEW_RU.md
Update info about hybrid cluster installation
=> [docs][new structure] Update info about hybrid cluster installation

modules/400-descheduler/docs/EXAMPLES.md, modules/400-descheduler/docs/EXAMPLES_RU.md
This PR updates the documentation examples section for the descheduler module to ensure all provided configurations are fully functional and reflect current best practices. The changes include:
1. Corrected example configurations for descheduler policies
2. Added missing fields required for proper operation
3. Aligned examples with current module capabilities
The changes are documentation-only and don't affect actual module functionality.
The current examples in the documentation:
1. Contain outdated configuration patterns
2. Missing required fields in some cases
3. Could lead users to create non-functional configurations
This update ensures users have correct, working examples when configuring the descheduler module, preventing configuration errors and reducing support requests.
Not …
=> [docs][descheduller] Correct example for descheduler module

ee/modules/040-node-manager/images/nvidia-dcgm/patches/001-clang.patch, ee/modules/040-node-manager/images/nvidia-dcgm/patches/README.md, ee/modules/040-node-manager/images/nvidia-dcgm/scripts/llvm.sh, ee/modules/040-node-manager/images/nvidia-dcgm/werf.inc.yaml, modules/040-node-manager/.dmtlint.yaml
Fix DCGM build
```changes
type: fix
summary: Fix DCGM build.
```
=> [node-manager] Fix DCGM build

.github/ci_templates/build.yml, .github/ci_templates/steps.yml, .github/workflow_templates/build-and-test_dev.yml, .github/workflow_templates/build-and-test_pre-release.yml, .github/workflow_templates/build-and-test_release.yml, .github/workflows/build-and-test_dev.yml, .github/workflows/build-and-test_pre-release.yml, .github/workflows/build-and-test_release.yml
Add secret key for use with cosign.
```changes
section: ci
type: chore
summary: Add secret key.
```
=> [ci] Add secret key

docs/documentation/pages/admin/configuration/app-scaling/pod-eviction/SCHEDULER.md, docs/documentation/pages/admin/configuration/app-scaling/pod-eviction/SCHEDULER_RU.md
Minor updates at descheduler examples in the new doumentation structure.
=> [docs] Minor updates at descheduler examples in new structure

modules/040-control-plane-manager/template_tests/template_test.go
Fixes the module's unit tests.
Fixes the module's unit tests.
```changes
type: chore
summary: The module's unit tests are fixed.
```
=> [control-plane-manager] fix unit tests

docs/site/_includes/getting_started/bm/STEP_FINALIZE.md, docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md, docs/site/_includes/getting_started/stronghold/bm/STEP_FINALIZE.md, docs/site/_includes/getting_started/stronghold/bm/STEP_FINALIZE_RU.md, docs/site/pages/stronghold/documentation/admin/install/steps/INSTALL_RU.md, docs/site/pages/stronghold/documentation/admin/platform-management/control-plane-settings/PLACEMENT_MANAGEMENT_RU.md, docs/site/pages/stronghold/documentation/admin/platform-management/node-management/ADDING_NODE_RU.md, docs/site/pages/virtualization-platform/documentation/admin/install/steps/NODES.md, docs/site/pages/virtualization-platform/documentation/admin/install/steps/NODES_RU.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/control-plane-settings/PLACEMENT_MANAGEMENT.md, docs/site/pages/virtualization-platform/documentation/admin/platform-management/control-plane-settings/PLACEMENT_MANAGEMENT_RU.md
Documentation changes related to https://github.com/deckhouse/deckhouse/pull/13346
```changes
section: docs
type: feature
summary: Documentation changes related to new API version of SSHCredentials.
```
=> [docs][getting started] Update CAPS resources API version

modules/040-node-manager/docs/EXAMPLES.md, modules/040-node-manager/docs/EXAMPLES_RU.md, tools/docs/spelling/dictionaries/dev_OPS.dic, tools/docs/spelling/wordlist
Edit examples for system nodes.
```changes
section: docs
type: chore
summary: Edited examples for system nodes.
```
=> [docs] Edit examples for system nodes

modules/040-node-manager/templates/capi-controller-manager/rbac-for-us.yaml
fix https://github.com/deckhouse/deckhouse/pull/14603
Added permissions for `volumeattachments`. Starting from version 1.9, this resource is important for the machine deletion process: [https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/tasks/automated-machine-management/machine\_deletions.md](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/tasks/automated-machine-management/machine_deletions.md)
```changes
type: fix
summary: capi rbac fix
impact: 
```
=> [node-manager] Upgrade CAPI version: rbac fix 1

candi/openapi/cluster_configuration.yaml, candi/openapi/doc-ru-cluster_configuration.yaml, docs/documentation/pages/DECKHOUSE-FAQ.md, docs/documentation/pages/DECKHOUSE-FAQ_RU.md, modules/040-node-manager/crds/doc-ru-node_group.yaml, modules/040-node-manager/crds/node_group.yaml
Add new requirement and commands to meet containerdv2 requirements
```changes
section: docs
type: fix
summary: Add new requirement and commands to meet containerdv2 requirements
```
=> [docs] Add new requirement and commands to meet containerdv2 requirements

candi/version_map.yml, docs/documentation/_data/reference/d8-cli.json
This PR updates Deckhouse CLI to 0.16.0 version in DKP.
```changes
section: candi
type: chore
summary: Update Deckhouse CLI (d8) version to 0.16.0.
```
=> [d8] Update Deckhouse CLI to 0.16.0 version

modules/040-control-plane-manager/images/kubernetes-api-proxy/mount-points.yaml, modules/040-control-plane-manager/images/kubernetes-api-proxy/werf.inc.yaml
Create mountpoints for kubernetes-api-proxy. 
Integrity requirements.
```changes
type: chore
summary: add mount-points to kubernes-api-proxy.
```
=> [control-plane-manager] fix kubernes-api-proxy mount-points

go_lib/dependency/http/http.go
Add tracing to Dependency Container http client
```changes
type: feature
summary: add tracing to dependency container http client
```
=> [go-lib] Add tracing to Dependency Container http client

candi/version_map.yml, docs/documentation/_data/reference/d8-cli.json
This PR updates Deckhouse CLI to 0.17.0 version in DKP.
```changes
section: candi
type:  chore
summary: Update Deckhouse CLI (d8) version to 0.17.0.
```
=> [d8] Update Deckhouse CLI to 0.17.0 version 

docs/documentation/pages/admin/configuration/registry/SWITCHING_EDITIONS.md, docs/documentation/pages/admin/configuration/registry/SWITCHING_EDITIONS_RU.md
Add instructions for switching edition to BE/SE/SE+/EE into the new documentation structure.
=> [docs][new structure] Add instructions for switching edition to BE/SE/SE+/EE

ee/modules/650-runtime-audit-engine/templates/falco-leak-limit-range.yaml
Reduced minimal memory for falco containers to play nice with default requests of 10Mi
This fixes falco deployment without VPA
```changes
type: fix
summary: reduced memory limit floor for falco containers
```
=> [runtime-audit-engine] Reduce memory limit floor

modules/030-cloud-provider-yandex/images/yandex-csi-plugin/werf.inc.yaml
Update yandex-csi-plugin:
- Fail if CreateVolume() request missing zone and region
- Set metadata querying timeout 
- Add some log messages during driver startup
Hybrid clusters with bare-metal masters fails csi-controller silently.
```changes
type: fix
summary: Set CSI driver metadata querying timeouts
```
=> [cloud-provider-yandex] Set CSI driver metadata querying timeouts

docs/site/_includes/getting_started/dvp/bm/partials/user.yml.inc, docs/site/_includes/getting_started/dvp/global/STEP_STORAGE.md, docs/site/_includes/getting_started/dvp/global/STEP_STORAGE_RU.md, docs/site/pages/virtualization-platform/documentation/admin/install/steps/STORAGE.md, docs/site/pages/virtualization-platform/documentation/admin/install/steps/STORAGE_RU.md
Fix the DVP getting started.
```changes
section: dvp
type: chore
summary: Fix the DVP getting started.
```
=> [dvp] fix getting started docs

modules/140-user-authz/docs/USAGE.md, modules/140-user-authz/docs/USAGE_RU.md
Fixed example in the user-authz module.
```changes
type: chore
summary: Fixed example in the user-authz module.
```
=> [docs][user-authz] Fix example

dhctl/pkg/system/node/gossh/client.go
Improve gossh client start logic: combine dial from bastion and NewClientConn in one retry loop
By connecting through bastion host, sometimes tcp connection breaks, so we get an error message like `handshake failed: EOF`. To fix it, we should retry Dial too.
SSH client start logic should be fixed in v1.72
```changes
section: dhctl
type: fix
summary: Fix ssh client start with bastion in dhctl.
```
=> [dhctl] Improve ssh client start logic

.github/scripts/js/constants.js, .github/workflow_templates/e2e.abort.multi.yml, .github/workflow_templates/e2e.multi.yml, .github/workflows/e2e-abort-aws.yml, .github/workflows/e2e-abort-azure.yml, .github/workflows/e2e-abort-eks.yml, .github/workflows/e2e-abort-gcp.yml, .github/workflows/e2e-abort-openstack.yml, .github/workflows/e2e-abort-static.yml, .github/workflows/e2e-abort-vcd.yml, .github/workflows/e2e-abort-vsphere.yml, .github/workflows/e2e-abort-yandex-cloud.yml, .github/workflows/e2e-aws.yml, .github/workflows/e2e-azure.yml, .github/workflows/e2e-eks.yml, .github/workflows/e2e-gcp.yml, .github/workflows/e2e-openstack.yml, .github/workflows/e2e-static.yml, .github/workflows/e2e-vcd.yml, .github/workflows/e2e-vsphere.yml, .github/workflows/e2e-yandex-cloud.yml
Add k8s 1.34 to CI
We'll be able to run e2e with k8s version 1.34
By setting label e2e/use/k8s/1.34 with e2e/run/anything will run e2e with version 1.34 of kubernetes
```changes
section: ci
type: feature
summary: Add k8s 1.34 to CI.
```
=> [CI] Add k8s 1.34

docs/documentation/_data/modules/modules-addition.json, docs/site/backends/docs-builder-template/data/modules_all.json
Updated info for the observability module in the comparison table in the documentation.
```changes
section: docs
type: chore
summary: Updated info for the observability module in the comparison table in the documentation.
```
=> [docs][chore] Update info for the observability module in the comparison table

modules/500-upmeter/crds/doc-ru-upmeterremotewrite.yaml, modules/500-upmeter/crds/upmeterremotewrite.yaml, modules/500-upmeter/images/upmeter/src/pkg/monitor/remotewrite/types.go, modules/500-upmeter/images/upmeter/src/pkg/server/remotewrite/syncer.go
Add the ability to pass headers in RW
There are some users who want to add custom headers with remote write requests. 
```changes
type: feature
summary: Add the ability to pass headers in RW
```
=> [upmeter] Add the ability to pass headers in RW

docs/site/_includes/header.html
Updated top navigation menu on the site.
```changes
section: docs
type: chore
summary: Updated top navigation menu on the site.
```
=> [docs][site] Update topnav

modules/040-node-manager/crds/cluster.yaml, modules/040-node-manager/crds/machine-deployment.yaml, modules/040-node-manager/crds/machine-health-check.yaml, modules/040-node-manager/crds/machine-pools.yaml, modules/040-node-manager/crds/machine-sets.yaml, modules/040-node-manager/crds/machine.yaml, modules/040-node-manager/templates/capi-controller-manager/deployment.yaml
follow https://github.com/deckhouse/deckhouse/pull/14603
crd served version fix, disabled v1beta2
necessary for correct operation of capi
```changes
type: fix
summary: capi crd served version fix
impact: 
```
=> [node-manager] CAPI CRD fix

docs/documentation/pages/404.md, docs/documentation/pages/404_RU.md
Updated the 404 page.
```changes
section: docs
type: chore
summary: "Updated the 404 page."
```
=> [docs] Update 404 page

modules/000-common/images/debug-container/werf.inc.yaml
Add etcdctl and etcdutl into debug-container
Add more tools for debugging
No need
```changes
section: tools
type: feature
summary: add etcdctl and etcdutl
impact: add etcdctl and etcdutl
```
=> [common]Add etcdctl debug container

docs/site/.helm/templates/_rewrites.tpl
Update rewrite rules for site to make old links work.
```changes
section: docs
type: chore
summary: Update rewrite rules for site to make old links work.
```
=> [site] Update rewrite rules

docs/site/_includes/head.html
Update metainfo on some DKP pages.
```changes
section: docs
type: chore
summary: Update metainfo on some DKP pages.
```
=> [site] Update DKP pages metainfo

docs/site/.helm/templates/_rewrites.tpl
Update site redirection rules.
```changes
section: docs
type: chore
summary: Update site redirection rules.
```
=> [docs] Update site redirection rules

docs/site/.helm/templates/10-cm.yaml
Fix documentation deploy. Add deploy of CM with the cert for working with S3.
Fix: https://github.com/deckhouse/deckhouse/pull/15743
```changes
section: docs
type: chore
summary: Fix documentation deploy. Add deploy of CM with the cert for working with S3.
```
=> [docs][ci] Fix documentation deploy

docs/site/assets/js/sidebar-scroll.js
Fix scroll errors inthe documentation.
```changes
section: docs
type: chore
summary: Fix scroll errors inthe documentation.
```
=> [docs] Fix scroll

docs/site/assets/js/search-v3.js, docs/site/backends/docs-builder-template/layouts/_partials/openapi/extract-crd-search-params.html, docs/site/backends/docs-builder-template/layouts/_partials/openapi/module-search-index.json
- Refactored CRD search parameter extraction (use kind instead of filename).
- Refactored frontend search result grouping and ranking to improve prioritization of API parameter results versus documentation. Updated search boosting.
```changes
section: docs
type: chore
summary: Enhance search logic and fix CRD search param extraction.
```
=> [docs][search] Enhance search logic and fix CRD search param extraction

docs/site/_sass/components/_feedback.scss, docs/site/assets/js/feedback.js
Add edits feedback.
```changes
section: docs
type: chore
summary: Add edits feedback.
```
=> [docs] Add edits feedback

dhctl/pkg/server/pkg/helper/ssh_client.go
Related to: https://github.com/deckhouse/deckhouse/pull/15773
```changes
section: dhctl
type: chore
summary: Add ssh mode with rpc client func
```
=> [dhctl]  add ssh mode with rpc client

docs/documentation/_data/supported_versions.yml, docs/site/_includes/getting_started/global/partials/FINISH_CARDS.md, docs/site/_includes/getting_started/global/partials/FINISH_CARDS_RU.md
Fix broken links.
```changes
section: docs
type: chore
summary: Fixed broken links.
```
=> [docs] Fix broken links

docs/documentation/_data/i18n.yml
Formatted module name in the related links list for clarity.
```changes
section: docs
type: chore
summary: Formatted module name in the related links list for clarity.
```
=> [docs] Format module name in the related links list for clarity

modules/007-registrypackages/images/containerd/werf.inc.yaml
Bump integrity patch version for containerdv2.
```changes
section: candi
type: chore
summary: Bump integrity patch version for containerdv2.
```
=> [candi] Bump integrity patch version for containerdv2.

docs/documentation/_assets/js/search.js, docs/site/_includes/guides_main_page.liquid, docs/site/assets/js/filter-pagination.js, docs/site/assets/js/search-v3.js, docs/site/backends/docs-builder-template/layouts/modules/modules-list.html
Hide the show more button.
```changes
section: docs
type: chore
summary: Hide the show more button.
```
=> [docs] Hide the show more button

candi/version_map.yml, docs/documentation/_data/reference/d8-cli.json
Update d8 to 0.20.3.
```changes
type: chore
summary: update d8 to 0.20.3
impact: 
```
=> [deckhouse] update d8 to 0.20.3

candi/version_map.yml, docs/documentation/_data/reference/d8-cli.json
Minor fixes in deckhouse-cli contract
```changes
section: tools
type: fix
summary: bump deckhouse-cli v0.20.5
```
=> [deckhouse] bump deckhouse-cli v0.20.5

tools/dmt-lint.sh
Add more features and fix bugs in dmt
- Fixing unnecessary license finds
- Add SPDX license
- Fix bugs
We must cover good codebase
```changes
section: tools
type: fix
summary: update DMT version to 0.1.45
```
=> [dmt] Change version to 0.1.45
