- modules/040-node-manager/images/bashible-apiserver/pkg/cmd/server/start.go
Adding /openapi/v2 endpoint for bashible-apiserver. 
There is a non-stop spam of logs in the kube-apiserver logs:
```
E0724 07:02:08.686694       1 controller.go:116] loading OpenAPI spec for "v1alpha1.bashible.deckhouse.io" failed with: OpenAPI spec does not exist
E0724 07:03:08.690288       1 controller.go:116] loading OpenAPI spec for "v1alpha1.bashible.deckhouse.io" failed with: OpenAPI spec does not exist
E0724 07:05:08.694440       1 controller.go:116] loading OpenAPI spec for "v1alpha1.bashible.deckhouse.io" failed with: OpenAPI spec does not exist
```
The issue arises because the kube-apiserver is unable to[fetch an OpenAPI spec](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/c …
> bashible-apiserver openapi v2 endpoint

- candi/bashible/bashbooster/50_registrypackages.sh
- candi/bashible/bb_package_install.sh.tpl
- go_lib/registry-packages-proxy/proxy/proxy.go
- go_lib/registry-packages-proxy/registry/client.go
- go_lib/registry-packages-proxy/registry/default_client.go
- modules/039-registry-packages-proxy/images/registry-packages-proxy/src/internal/cache/cache.go
- modules/039-registry-packages-proxy/images/registry-packages-proxy/src/internal/credentials/module_source.go
- modules/039-registry-packages-proxy/images/registry-packages-proxy/src/internal/credentials/secret.go
- modules/039-registry-packages-proxy/images/registry-packages-proxy/src/internal/credentials/watcher.go
Fix registry packages proxy to work with modules images.
Added additional logging info.
Currently registry packages proxy cannot work properly with registries from module sources.
```changes
section: core
type: fix
summary: fix work registry-packages-proxy with module sources
impact: registry-packages-proxy should be restarted
```
> [core] fix work registry-packages-proxy with module sources

- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
- docs/site/_includes/getting_started/global/partials/DNS_OPTIONS.liquid
- docs/site/_includes/getting_started/global/partials/DNS_OPTIONS_RU.liquid
An unused domain `cdi-uploadproxy` has been removed from Getting Started.
Getting Started will become more correct.
```changes
section: docs
type: fix
summary: |
An unused domain `cdi-uploadproxy` has been removed from Getting Started.
```
> [docs] Delete cdi-uploadproxy domain from GS

- dhctl/pkg/operations/bootstrap/steps.go
- dhctl/pkg/system/ssh/frontend/reverse-tunnel.go
Fix bashible bundles step did not break when retry attempts was exited
Add new line for registry packages proxy logger
Change reverse tunnel health monitor log from info to debug
Dhctl should break retries bashible step if bashible step retry loop receive exited attempts error.
Logs changes will improve UX
```changes
section: dhctl
type: fix
summary: Fix bashible bundles step did not break when retry attempts was exited
```
> [dhctl] Fix bashible bundles step did not break when retry attempts was exited

- modules/402-ingress-nginx/images/controller-1-10/Dockerfile
- modules/402-ingress-nginx/images/controller-1-10/patches/makefile.patch
- modules/402-ingress-nginx/images/controller-1-10/patches/nginx-build.patch
It bumps ingress-nginx to 1.10.3
This version contains our patches, security and performance improvements.
Ingress-nginx controller 1.10.3
```changes
type: feature
summary: Bump ingress-nginx to 1.10.3
impact: ingress-nginx controllers' pods will be recreated.
```
> [ingress-nginx] bump controller to 1.10.3

- modules/110-istio/hooks/generate_kiali_signing_key.go
- modules/110-istio/hooks/generate_kiali_signing_key_test.go
- modules/110-istio/openapi/values.yaml
- modules/110-istio/template_tests/module_test.go
- modules/110-istio/templates/kiali/configmap.yaml
- modules/110-istio/templates/kiali/deployment.yaml
- modules/110-istio/templates/kiali/ingress.yaml
- modules/110-istio/templates/kiali/rbac-for-us.yaml
- modules/110-istio/templates/kiali/secret.yaml
Inheriting cluster access rules from authenticated user to Kiali (impersonation). The logged in user will be authorized to do everything according to his RBAC.
Before the PR, Kiali used to identify any authenticated user as anonymous and gave him enormous privileges.
After logging in, the kiali shows your name in the UI and you can't do anything you wasn't allowed to.
```changes
section: istio
type: chore
summary: Kiali inherits cluster access rules from an authenticated user (impersonate him), not considering him as anonymous and not provides unwanted privileges.
```
> [istio] Inheriting cluster access rules from authenticated user to Kiali (impersonation)

- docs/documentation/_data/deckhouse-ports.yml
- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
- modules/470-chrony/images/chrony/main.go
- modules/470-chrony/images/chrony/werf.inc.yaml
- modules/470-chrony/templates/configmap.yaml
- modules/470-chrony/templates/daemonset.yaml
- modules/470-chrony/templates/service.yaml
- testing/matrix/linter/rules/rules.go
Optimize permissions and capabilities for chrony and chrony-master. Change NTP listen ports.
This will reduce security risks and satisfy our port range policy.
- Chrony listens on port 4234/udp.
- Chrony only run with the necessary permissions.
```changes
type: chore
summary: Optimized permissions and capabilities for chrony and chrony-master. NTP listen ports changed.
```
> [chrony] Optimize permissions and capabilities for chrony and chrony-master

- modules/460-log-shipper/hooks/generate_config_test.go
- modules/460-log-shipper/hooks/internal/vector/transform/destination.go
- modules/460-log-shipper/hooks/testdata/file-to-socket-cef/manifests.yaml
- modules/460-log-shipper/hooks/testdata/file-to-socket-cef/result.json
The extraLabels option is in the spec but does not work for the `Socket` dst. Also, without extraLabels, it is impossible to configure CEF encoding fields, and defaults for CEF encoding also do not work properly.
This PR changes the logic of the way both CEF and extra labels work correctly. The error was in the destination transformation clauses.
```changes
section:  log.shipper
type: fix
summary: Make extraLabels and CEF encoding work for Socket destination.
```
> [log-shipper] Make extraLabels and CEF encoding work for Socket dest

- modules/300-prometheus/templates/grafana/deployment-v10.yaml
Disable grafana-v10 unified alerting navigation
In last minor versions of Grafana v10 by default, home page navigation contains 2 links:  
- `Alerting (legacy)`
-  `Alerting` (even if `GF_UNIFIED_ALERTING_ENABLED` is set to false)
It is required to explicitly specify org id in `GF_UNIFIED_ALERTING_DISABLED_ORGS` to disable unified alerting navigation
Closes #9151 
Home page navigation contains only `Alerting (legacy)` link
```changes
type: chore
summary: Disable grafana-v10 unified alerting navigation
```
> [prometheus] Disable grafana-v10 unified alerting navigation

- testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/Azure/Standard/configuration.tpl.yaml
- testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/GCP/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml
- testing/cloud_layouts/Static/configuration.tpl.yaml
- testing/cloud_layouts/Static/resources.tpl.yaml
- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/script.d/wait_cluster_ready/test_script.sh
- testing/cloud_layouts/vCloudDirector/Standard/configuration.tpl.yaml
- testing/cloud_layouts/vSphere/Standard/configuration.tpl.yaml
Basic e2e-tests for modules:
* istio
* static-routing-manager
* cilium (EgressGateway and EgressGatewayPolicy)
Tests will help to detect modules deployment errors at an early stage.
```changes
type: chore
summary: basic e2e tests for network modules
```
> [testing][e2e] Add basic tests for network modules

- deckhouse-controller/pkg/controller/controller.go
- deckhouse-controller/pkg/controller/module-controllers/source/controller.go
Adds default releaseChannel value "Stable" for embedded deckhouse policy if releaseChannel isn't specified in the `deckhouse` module config.
In some clusters `deckhouse` may be running without .releaseChannel attribute set, yet its value is used for getting available module releases. Having an empty value when checking available module releases doesn't make sense, so a default value of "Stable" is applied.
If deckhouse isn't subscribed to any release channel, module sources are still able to fetch available module releases from the "Stable" channel.
```changes
type: chore
summary: Set default releaseChannel for ebedded deckhouse policy.
```
> [deckhouse-controller] set default release channel for embedded deckhouse policy

- docs/documentation/_data/deckhouse-ports.yml
- ee/modules/650-runtime-audit-engine/templates/daemonset.yaml
- testing/matrix/linter/rules/rules.go
Moving the webhook-handler port (9680/tcp) that listens on nodes to the range 4200-4299.
This will make it easier for administrators to create network policies on firewalls within the corporate infrastructure. They will be able to add a single range to the policy.
```changes
type: chore
summary: The webhook-handler port moved to the range 4200-4299.
impact: Note that you will need to change the access policies on the underlying firewalls before upgrading the cluster.
```
> [runtime-audit-engine] Move the webhook-handler port to the range 4200-4299

- modules/040-control-plane-manager/docs/README.md
- modules/040-control-plane-manager/docs/README_RU.md
Fixed the description in the scaling section.
```changes
type: fix
summary: Fixed the description in the scaling section.
```
> [docs][control-plane-manager] Improve the readme page

- testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml
OpenStack migration with configOverrides
Do not pass because of the complete abandonment of the old configuration format.
```changes
type: fix 
summary: OpenStack migration with configOverrides
```
> [testing] OpenStack migration with configOverrides

- testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml
Increased the root partition to 50.
`Error: Root disk capacity: expected at least 50, but 30 is configured`
```changes
type: fix
summary: OpenStack set root disk to 50
```
> [testing] OpenStack set root disk to 50

- testing/cloud_layouts/GCP/WithoutNAT/configuration.tpl.yaml
Fix test for GCP.
We fixed an e2e test for gcp where global ModuleConfig was not properly configured.
```changes
type: fix
summary: fix e2e test for GCP
```
> [testing][e2e] fix test for GCP

- deckhouse-controller/pkg/controller/deckhouse-release/check_release_test.go
- deckhouse-controller/pkg/controller/deckhouse-release/client_test.go
- deckhouse-controller/pkg/controller/deckhouse-release/controller_test.go
- deckhouse-controller/pkg/controller/deckhouse-release/next_version_test.go
At the current time, we have a suite that is configured strictly for certain behavior and that matches files. This makes it difficult to write tests that don't require this.
We have a number of functions that need to be tested, but which do not require matching with golden files to test.
In these tests we also need to initialize the controller with certain settings.
Once we have separated the controller initialization into separate functions, we can easily use them in new suites. And for each set of tests we can now create a separate suite.
```changes
type: chore
summary: Rewrite controller tests.
```
> [testing] rewrite controller tests

- docs/documentation/_data/deckhouse-alerts.yml
Satisfy `make generate` linter.
```changes
section: ci
type: chore
summary: Satisfy `make generate` linter.
```
> [chore] Satisfy `make generate` linter

- ee/candi/cloud-providers/openstack/terraform-modules/static-node/main.tf
This fix corrects configuration of [Allowed Address Pairs](https://docs.openstack.org/developer/dragonflow/specs/allowed_address_pairs.html) for static nodes created using Terraform. When using `podNetworkMode: DirectRoutingWithPortSecurityEnabled`, we add `allowed_address_pairs = ip_address='POD_NETWORK_CIDR'` to the ports of all servers.
This fix addresses an issue with the configuration of Allowed Address Pairs for static nodes, ensuring proper network functionality when using Direct Routing with Port Security enabled.
After applying these changes, the ports of all servers will correctly have `allowed_address_pairs = ip_address='POD_NETWORK_CIDR'` when `podNetworkMode: DirectRoutingWithPortSecurityEnabled` is used, ensuring correct network configuration and functionality.
```changes …
```
> [cloud-providers][openstack] Fix network configuration in OpenStack when using DirectRoutingWithPortSecurityEnabled.

- deckhouse-controller/pkg/controller/controller.go
- deckhouse-controller/pkg/controller/deckhouse-release/check_release.go
- deckhouse-controller/pkg/controller/deckhouse-release/client_test.go
- deckhouse-controller/pkg/controller/deckhouse-release/controller.go
- deckhouse-controller/pkg/controller/deckhouse-release/updater/metrics.go
- deckhouse-controller/pkg/controller/deckhouse-release/updater/updater.go
- docs/documentation/_data/deckhouse-alerts.yml
Deckhouse update metrics restored
```changes
type: fix
summary: Deckhouse update metrics restored.
```
> [deckhouse-controller] Deckhouse release controller metrics

- dhctl/pkg/kubernetes/actions/resources/resources.go
Added a retry for resource creation for cases where resources required for manifest creation is not there yet
We hit that case where a resource specified in `config.yml` during bootstrap was meant to be created in a module namespace. As modules are initialized only after bootstrap process is complete, it deadlocked the installer. This allows the installer to wait for such missing resources.
```changes
section: dhctl
type: fix
summary: Wait for resources required by manifest being created.
```
> [dhctl] Wait for resources required by manifest being created

- testing/cloud_layouts/vCloudDirector/Standard/configuration.tpl.yaml
- testing/cloud_layouts/vCloudDirector/Standard/resources.tpl.yaml
Fix vcd template debian 12 for e2e.
For success complete vcd e2e.
```changes
section: e2e
type: fix
summary: Fix vcd template debian 12 for e2e.
```
> [e2e] fix preserve_hostname and disk.EnableUUID in vcd template debian-12

- dhctl/pkg/terraform/runner.go
- dhctl/pkg/terraform/runner_test.go
We add `type` field to the terraform plan outputs.
We need `type` field to show destructive changes in commander. 
Remove line that saves terraform plan files for debug.
`type` field should exist in terraform plan outputs.
```changes
section: dhctl
type: chore
summary: Added resource type field to the terraform plan outputs
```
> [dhctl] add resource type to terraform plan output

- ee/modules/030-cloud-provider-openstack/docs/CONFIGURATION.md
- ee/modules/030-cloud-provider-openstack/docs/CONFIGURATION_RU.md
- ee/modules/030-cloud-provider-vsphere/docs/CONFIGURATION.md
- ee/modules/030-cloud-provider-vsphere/docs/CONFIGURATION_RU.md
- modules/030-cloud-provider-yandex/docs/CONFIGURATION.md
- modules/030-cloud-provider-yandex/docs/CONFIGURATION_RU.md
The parameter pages are aligned to a single element layout style.
```changes
type: fix
summary: The layout of the elements on the page has been changed.
---
type: fix
summary: The layout of the elements on the page has been changed.
---
type: fix
summary: The layout of the elements on the page has been changed.
```
> [docs] Refactoring sections in the documentation of cloud providers

- modules/021-cni-cilium/monitoring/prometheus-rules/agent.yaml
When pods start or restart in a cluster, cilium agents lose communication with each other and export the metric `cilium_unreachable_health_endpoints` to Prometheus. There are no settings in cilium to change this behavior (probe delay for just started agents, for example), and it is not possible to develop them due to internal API limitations.
It is necessary to change the conditions in the expression to avoid receiving false positive alarms from the monitoring system.
When pods are started or rebooted, the monitoring system will not register an alarm for 7 minutes after the changes. If there are no changes in the pod states, but the cilium agents have lost communication with each other, an alarm is sent through Prometheus Alarm Manager.
```changes
type: fix 
summary: …
```
> [cilium][monitoring] Modify the CiliumAgentUnreachableHealthEndpoints alarm expression

- candi/control-plane-kubeadm/config.yaml.tpl
Add API `admissionregistration.k8s.io/v1alpha1` support for K8s >= 1.28.
On helm update, we can stuck if we have `admissionregistration.k8s.io/v1alpha1` in the resource. We have to keep support of this API even in the 1.28+ Kubernetes version.
If fixes a bug.
```changes
section: candi
type: fix 
summary: Keep `admissionregistration.k8s.io/v1alpha1` API support for K8s 1.28+.
```
> [candi] Add admissionregistration API for K8s >= 1.28

- ee/modules/030-cloud-provider-vcd/images/vcd-csi-plugin-legacy/werf.inc.yaml
- ee/modules/030-cloud-provider-vcd/images/vcd-csi-plugin/patches/01-add-iops-calculation.patch
- ee/modules/030-cloud-provider-vcd/images/vcd-csi-plugin/werf.inc.yaml
Fix build csi-controller. Use right command for apply patch
CSI controller cannot work with storage policy using 0 as Max IOPS 
Affect new clients
```changes
type: fix
summary: Fix impossibility to use 0 as value of Max IOPS in storage policy
```
> [cloud-provider-vcd] Fix impossibility to use 0 as value of Max IOPS in storage policy

- deckhouse-controller/pkg/controller/module-controllers/downloader/downloader_test.go
- deckhouse-controller/pkg/controller/module-controllers/downloader/module_downloader.go
Fix panic on invalid module image
```changes
type: fix
summary: Fix panic on invalid module image
```
> [deckhouse-controller] Fix panic on invalid module image

- docs/documentation/_data/deckhouse-alerts.yml
- ee/modules/110-istio/monitoring/prometheus-rules/dataplane.yaml
Renaming the `D8IstioActualDataPlaneVersionNeDesired` alert to `D8IstioActualDataPlaneVersionNotEqualDesired`.
In `D8IstioActualDataPlaneVersionNeDesired` name isn't obvious what `Ne` is.
```changes
section: istio
type: chore
summary: The `D8IstioActualDataPlaneVersionNeDesired` alert renamed to `D8IstioActualDataPlaneVersionNotEqualDesired`.
```
> [istio][monitoring] Renaming the D8IstioActualDataPlaneVersionNeDesired alert

- ee/modules/021-cni-cilium/templates/monitoring.yaml
- modules/021-cni-cilium/monitoring/grafana-dashboards/kubernetes-cluster/cilium-agent.json
- tools/build_includes/modules-EE.yaml
- tools/build_includes/modules-FE.yaml
- tools/build_includes/modules-with-dependencies-EE.yaml
- tools/build_includes/modules-with-dependencies-FE.yaml
- tools/build_includes/modules-with-exclude-EE.yaml
- tools/build_includes/modules-with-exclude-FE.yaml
This PR addresses two main issues:
1. It adds a missing variable to define the datasource in the Grafana dashboard. This variable was lost in a previous PR.
2. It fixes the `cni-cilium` module by deleting the `monitoring.yaml` template for EE version, which was added by mistake. This issue was specific to the EE version, and this template was preventing the `cni-cilium` dashboard from appearing in the EE version entirely.
This PR is essential for ensuring that the Grafana dashboard functions correctly by defining the datasource. Moreover, it resolves the issue with the `cni-cilium` module in the EE version, ensuring that the dashboard is rendered correctly. This fix is critical as it reinstates the visibility of the `cni-cilium` dashboard in the EE version, which was completely missing …
> [monitoring] Fix cni cilium dashboard

- testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/script.d/wait_cluster_ready/test_script.sh
- testing/cloud_layouts/script.sh
Disabling the istio module and the istio availability test from EKS e2e layout.
The Istio module has a hook discovery_preflight_check.go, which checks the cluster's k8s version. But in EKS we don't control the control-plane and don't know the k8s version. So we decided not to test the module in this layout. Will handle it later.
Need to fix e2e tests as soon as possible.
EKS e2e layout is succeeding.
```changes
type: fix
summary: The istio module and istio availability test are disabled EKS e2e layout.
```
> [testing] Disabling the istio module and the istio availability test from EKS e2e layout.

- modules/002-deckhouse/templates/validation.yaml
Previously, rules were added to check whether changes can be made to objects with the `heritage=deckhouse` label.
It is necessary to additionally prohibit deletion of such objects for users who are not administrators or system users.
Fixed: #9108
An additional layer of system security needs to be provided to prevent users from deleting objects that have the `heritage=deckhouse` label.
Users who are not system or administrators cannot create, update, or delete objects that have the `heritage=deckhouse` label.
```changes
type: feature
summary: add DELETE verbs for restrict operations on deckhouse heritage
```
> feat: add DELETE verbs for restrict operations on deckhouse heritage

- deckhouse-controller/crds/module-release.yaml
- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
It provides missed skipped status for module release crd.
The module release controller can try to set status to Skipped, and it causes an error.
The module release controller can try to set status to Skipped, and it causes a error.
The Skipped status can be set.
```changes
summary: Add skipped status.
```
> [deckhouse] add skipped status

- modules/035-cni-flannel/images/flanneld/entrypoint/main.go
- modules/035-cni-flannel/templates/daemonset.yaml
When switching CNI from **cilium** to **flannel**, the **cilium** configuration file `/etc/cni/net.d/05-cilium.conflist` remains in the host file system.
Stale configuration file prevents CNI from working properly.
When starting **flannel**, the **cilium** configuration file `/etc/cni/net.d/05-cilium.conflist` will be deleted.
The file will not be deleted if both CNI **cilium** and **flannel** are enabled at the same time. 
```changes
section: flannel
type: chore
summary: Added deletion of stale cilium cni configuration file from the host file system when starting flannel.
```
> [flannel] Removing the cilium configuration file on flannel startup

- deckhouse-controller/pkg/controller/module-controllers/downloader/module_downloader.go
- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
- deckhouse-controller/pkg/controller/module-controllers/release/controller_test.go
- deckhouse-controller/pkg/controller/module-controllers/release/copy.go
- deckhouse-controller/pkg/controller/module-controllers/release/copy_test.go
- deckhouse-controller/pkg/controller/module-controllers/release/override-controller.go
- deckhouse-controller/pkg/controller/module-controllers/release/override-controller_test.go
- deckhouse-controller/pkg/controller/module-controllers/release/testdata/module-failed/openapi/config-values.yaml
- deckhouse-controller/pkg/controller/module-controllers/release/testdata/module-not-valid/openapi/values.yaml
- deckhouse-controller/pkg/controller/module-controllers/release/testdata/module-values-failed/openapi/config-values.yaml
- deckhouse-controller/pkg/controller/module-controllers/release/testdata/module-values-failed/openapi/values.yaml
- deckhouse-controller/pkg/controller/module-controllers/release/testdata/module/openapi/config-values.yaml
- deckhouse-controller/pkg/controller/module-controllers/release/testdata/module/openapi/values.yaml
- deckhouse-controller/pkg/controller/module-controllers/release/testdata/releaseController/golden/simple.yaml
- deckhouse-controller/pkg/controller/module-controllers/release/testdata/releaseController/golden/with-annotation.yaml
- deckhouse-controller/pkg/controller/module-controllers/release/updater.go
- testing/openapi_validation/library.go
Modules may have an invalid configuration, and their activation may lead to a problem with the release.
As part of these changes, we are improving the verification of module configuration files. And if errors are detected, the release will be transferred to pending status.
Fixed: #8799 
Modules with incorrect configuration should be suspended
```changes
type: fix
summary: Correct module validation.
```
> [deckhouse-controller] feat: improve module validation

- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
After removing the module release, we need to restart the controller to completely remove the module from the system.
Fixed: #9074
If a deployed module release gets deleted, corresponding module should also be deleted from the ModuleManager and DeckhouseController to reflect new state of the cluster.
```changes
type: feature
summary: Restart controller if a ModuleRelease is Deployed phase is deleted
```
> [deckhouse-controller] Restart controller if a ModuleRelease is Deployed phase is deleted

- modules/002-deckhouse/templates/validation.yaml
When upgrading the cluster, there was a problem where kubernetes-admin was unable to make changes to objects labeled heritage deckhouse.
You need to grant permission to modify such objects to the kubernetes-admin user
When conducting e2e testing, the deckhouse version is switched by directly changing the image version. In this case, kubectl can be run under a user with different groups. To solve the problem, we issue the necessary rights directly to the user.
When running e2e testing, image switching occurs without problems.
```changes
type: fix
summary: allow kubernetes-admin to make changes
```
> [e2e] fix: allow kubernetes-admin to make changes

- .github/ci_templates/e2e_tests.yml
- .github/scripts/js/constants.js
- .github/workflow_templates/e2e-daily.yml
- .github/workflow_templates/e2e.abort.multi.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-abort-vcd.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vcd.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- testing/cloud_layouts/script.sh
Renaming VCD e2e tests. Fixes the issue of running tests via comments, e.g., `/e2e/run/vcd release-123`
```changes
```
> [e2e] vcd e2e workflow renaming

- modules/110-istio/hooks/discovery_preflight_check.go
- modules/110-istio/templates/control-plane/iop.yaml
- testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/script.d/wait_cluster_ready/test_script.sh
- testing/cloud_layouts/script.d/wait_cluster_ready/test_script_eks.sh
Fixed istio module operability in managed k8s setups.
There is no way to run the istio module and its tests on managed clusters with minimal bundle (such EKS).
There is a customer who considers using istio in EKS.
```changes
section: istio
type: fix
summary: Fixed istio module operability in managed k8s setups.
```
> [istio] Fixed operability in managed k8s setups

- modules/810-documentation/docs/EXAMPLES.md
- modules/810-documentation/docs/EXAMPLES_RU.md
spec.version: 2 in module config has error
`documentation               true      2         2m33s   Error: invalid spec.version, use version 1`
We need change default to 1
```changes
section: docs
type: Fix spec.version in the example in the documentation module.
```
> [docs] Fix spec.version in mc for documentation module

- dhctl/pkg/kubernetes/actions/deckhouse/delete.go
- dhctl/pkg/operations/destroy/deckhouse.go
Deleting LocalStorageClass, ReplicatedStorageClass, NFSStorageClass and CephStorageClass during dhctl destroy
If we try to delete a storageClass that is associated with one of our storage modules we will get an error for example:
```
kubectl delete sc replicated-storage-class
Error from server: admission webhook "d8-sds-replicated-volume-sc-validation.storage.deckhouse.io" denied the request: Direct modifications to the StorageClass (other than annotations) with the provisioner linstor.csi.linbit.com are not allowed. Please use ReplicatedStorageClass for such operations.
```
So, the custom resource must be deleted first 
Successful execution of dhctl destroy for clusters where our sds modules are used for storageClass.
```changes
section: deleting storage.deckhouse.io/crs when dhctl …
```
> [dhctl] deleting storage.deckhouse.io/crs when dhctl destroy is executed

- dhctl/pkg/operations/bootstrap/steps.go
- dhctl/pkg/system/ssh/frontend/upload-script.go
SSH clients `UploadScript` will now try to delete uploaded scripts from remote server after execution attempt. This can be prevented for special cases such as first bashible execution.
Closes https://github.com/deckhouse/deckhouse/issues/9060
```changes
section: dhctl
type: chore
summary: remove uploaded SSH scripts after execution
```
> [dhctl] Remove uploaded SSH scripts after execution

- candi/bashible/common-steps/node-group/002_install_ms_ca_certificates.sh.tpl
- candi/bashible/common-steps/node-group/032_configure_containerd.sh.tpl
Don't create an empty ca cert-file if ModuleSource does not contain a custom ca.
Now bashible step create empty `"/usr/local/share/d8-ca-certificates/***registry-host***-ca.crt"` for  modulseSource without custom ca.
For order. It's not necessary, but will be good.
Create ModuleSource with empty (or without) `.spec.registry.ca`:
```bash
[root@dev-master-0 ~]# kubectl apply -f - <<EOF
kind: ModuleSource
metadata:
name: mysource
spec:
registry:
ca: ""
dockerCfg: $DOCKERCFG
repo: 192.168.199.92:5000/deckhouse-modules
scheme: HTTPS
releaseChannel: ""
EOF
modulesource.deckhouse.io/mysource created
[root@dev-master-0 ~]#
```
Behaviour before:
```bash
[root@dev-master-0 ~]# kubectl -n d8-cloud-instance-manager get nodegroupbundle common.master  -o json | jq -r …
```
> [candi] fix install empty ca module source

- modules/000-common/images/shell-operator/werf.inc.yaml
Configured version variable setting when building shell-operator image
Closed https://github.com/deckhouse/deckhouse/issues/9178 
```changes
type: fix
summary: fixed the displayed version of shell-operator
```
> [common] fixed the displayed version of shell-operator

- modules/110-istio/templates/kiali/configmap.yaml
- modules/110-istio/templates/kiali/deployment.yaml
- modules/110-istio/templates/kiali/ingress.yaml
- modules/110-istio/templates/kiali/rbac-for-us.yaml
- modules/110-istio/templates/kiali/rbac-to-us.yaml
- modules/110-istio/templates/kiali/service.yaml
- modules/500-cilium-hubble/templates/ui/deployment.yaml
- modules/500-cilium-hubble/templates/ui/ingress.yaml
- modules/500-cilium-hubble/templates/ui/rbac-for-us.yaml
- modules/500-cilium-hubble/templates/ui/rbac-to-us.yaml
- modules/500-cilium-hubble/templates/ui/service.yaml
Making hubble-ui and kiali services accessible only for the ingress controller.
Improving security of interactions between platform components.
```changes
type: chore
summary: Internal TLS authentication between ingress-controller and hubble-ui enabled.
---
section: istio
type: chore
summary:  Internal TLS authentication between ingress-controller and kiali enabled.
```
> [cilium][istio] Making hubble-ui and kiali accessible only for the to the ingress controller

- docs/site/_includes/getting_started/existing/STEP_FINISH.md
- docs/site/_includes/getting_started/existing/STEP_FINISH_RU.md
- modules/810-documentation/docs/CONFIGURATION.md
- modules/810-documentation/docs/CONFIGURATION_RU.md
Fixed command asking for basic-auth password of `documentation` module. Typo found by community members
Improves the quality of documentation
```changes
type: fix
summary: Fixed command for requesting basic-auth password for `documentation` module.
```
> [docs] Fixed command requesting basic-auth password for `documentation` module

- candi/bashible/common-steps/all/003_install_mandatory_packages.sh.tpl
- modules/007-registrypackages/images/iptables/werf.inc.yaml
- modules/050-network-policy-engine/images/kube-router/werf.inc.yaml
- testing/library/images_tags_generated.go
Downgrading iptables version from 1.8.10 to 1.8.9 in network-policy-engine (kube-router) and registrypackages (iptables binary on nodes).
With the current version of iptables there is a problem with kube-router endlessly adding a rule like 
```shell
-t filter -A KUBE-ROUTER-INPUT -p tcp -m comment --comment "allow LOCAL TCP traffic to node ports - <some-id>" -m addrtype --dst-type LOCAL -m multiport --dports 30000:32767 -j RETURN
```
It happens because kube-router perform check by executing the iptables command:
```shell 
iptables -t filter -C KUBE-ROUTER-INPUT -p tcp -m comment --comment "allow LOCAL TCP traffic to node ports - <some-id>" -m addrtype --dst-type LOCAL -m multiport --dports 30000:32767 -j RETURN
```
Which sometimes fails with EXIT_CODE 1. So, kube-router decides there …
> [network-policy-engine][registrypackages] Downgrading iptables version to 1.8.9

- candi/bashible/common-steps/all/003_install_mandatory_packages.sh.tpl
- modules/007-registrypackages/images/iptables/werf.inc.yaml
- modules/050-network-policy-engine/images/kube-router/werf.inc.yaml
- testing/library/images_tags_generated.go
Downgrading iptables version from 1.8.10 to 1.8.9 in network-policy-engine (kube-router) and registrypackages (iptables binary on nodes).
Backports: https://github.com/deckhouse/deckhouse/pull/9315
With the current version of iptables there is a problem with kube-router endlessly adding a rule like 
```shell
-t filter -A KUBE-ROUTER-INPUT -p tcp -m comment --comment "allow LOCAL TCP traffic to node ports - <some-id>" -m addrtype --dst-type LOCAL -m multiport --dports 30000:32767 -j RETURN
```
It happens because kube-router perform check by executing the iptables command:
```shell 
iptables -t filter -C KUBE-ROUTER-INPUT -p tcp -m comment --comment "allow LOCAL TCP traffic to node ports - <some-id>" -m addrtype --dst-type LOCAL -m multiport --dports 30000:32767 -j RETURN
```
Which …
> [network-policy-engine][registrypackages] Downgrading iptables version to 1.8.9 

- modules/470-chrony/docs/CONFIGURATION.md
- modules/470-chrony/docs/CONFIGURATION_RU.md
- modules/470-chrony/openapi/config-values.yaml
Fix example in docs to pass validation
```
module config validation: Enabled field for module config chrony shoud set to true or false
data:
1	apiVersion: deckhouse.io/v1alpha1
2	kind: ModuleConfig
3	metadata:
4	  name: chrony
5	spec:
6	  settings:
7	    ntpServers:
8	      - pool.ntp.org
9	      - ntp.ubuntu.com
10	  version: 1
```
Add third ntp-server to resolve problem "A man with a watch knows what time it is. A man with two watches is never sure."
Improve documentation
```changes
type: chore
summary: Fix example in docs.
```
> [chrony] docs: Fix example

- modules/110-istio/templates/control-plane/iop.yaml
Add an annotation `istio-mtls-ca-bundle-checksum: <sha256sum>` to the `istiod` pods to force restarting when ca changes.
When configuring custom CA and intermediate certificates for mTLS issuing, you must reload `istiod` pod for the settings to take effect.
After changing the `spec.settings.ca` settings of the **istio** module, an annotation is added and **helm** generates a new manifest for `istiod`. All newly created pods with **istio** side-cars will use custom certificates for mTLS operation.
```changes
section: istio
type: fix
summary: Fixed an issue with automatically applying new custom certificates for mTLS issuing.
```
> [istio] Forcing istiod to restart when mTLS ca configuration changes

- dhctl/pkg/kubernetes/actions/resources/cluster_is_bootstrap.go
- dhctl/pkg/kubernetes/actions/resources/resource_id.go
- dhctl/pkg/kubernetes/actions/resources/resource_is_ready.go
- dhctl/pkg/kubernetes/actions/resources/resource_is_ready_test.go
- dhctl/pkg/kubernetes/actions/resources/resources.go
- dhctl/pkg/kubernetes/actions/resources/waiter.go
- dhctl/pkg/kubernetes/actions/resources/waiter_test.go
- dhctl/pkg/kubernetes/actions/resources/watcher.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-resources.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/operations/commander/attach/attacher.go
- dhctl/pkg/operations/commander/detach/detacher.go
- dhctl/pkg/util/retry/retry.go
- modules/040-node-manager/images/caps-controller-manager/src/internal/scope/instance_scope.go
Add a Kubernetes resources checker to the `dhctl bootstrap` command.
We need to wait until the Kubernetes resources specified in the `dhctl bootstrap` `--config` option are in the `Ready` status.
```changes
section: dhctl
type: feature
summary: 'The `dhctl bootstrap` command will wait until the status of each resource in the `--config` option changes to `Ready`.'
```
> [dhctl] Add a resource readiness status check 

- docs/documentation/_data/deckhouse-alerts.yml
- modules/040-node-manager/monitoring/prometheus-rules/cluster-autoscaler.tpl
Fix container name in alert.
Correct command in alert to get logs.
Now we have not working command:
```
~ $ kubectl -n d8-cloud-instance-manager logs -f -l app=cluster-autoscaler -c controller
error: container controller is not valid for pod cluster-autoscaler-7cff9f865b-gjhwt
```
We need to use `cluster-autoscaler` container in pod
```
~ $ kubectl -n d8-cloud-instance-manager logs -f -l app=cluster-autoscaler -c cluster-autoscaler
I0813 22:48:09.545414       1 pre_filtering_processor.go:67] Skipping vk-dh-system-f2800271-5585f-npr7q - node group min size reached (current: 2, min: 2)
I0813 22:48:09.545420       1 pre_filtering_processor.go:67] Skipping vk-dh-worker-f2800271-68c7c-b7lfp - node group min size reached (current: 1, min: 1)
I0813 22:48:09.545449       1 …
```
> [node-manager] Fix cluster-autoscaler alert

- ee/modules/160-multitenancy-manager/templates/user-resources/default-project-template.yaml
- ee/modules/160-multitenancy-manager/templates/user-resources/secure-project-template.yaml
- ee/modules/160-multitenancy-manager/templates/user-resources/secure-with-dedicated-nodes-project-template.yaml
It provides fix for templates.
The PodSelector field is not in the right place.
This field may be ignored by helm.
The PodSelector field is in the right place.
```changes
type: fix
summary: Fix templates.
```
> [multitenancy-manager] fix templates

- ee/modules/030-cloud-provider-openstack/templates/cloud-controller-manager/rbac-for-us.yaml
- ee/modules/030-cloud-provider-vcd/templates/cloud-controller-manager/rbac-for-us.yaml
- ee/modules/030-cloud-provider-vsphere/templates/cloud-controller-manager/rbac-for-us.yaml
- ee/modules/030-cloud-provider-zvirt/templates/cloud-controller-manager/rbac-for-us.yaml
- modules/030-cloud-provider-aws/templates/cloud-controller-manager/rbac-for-us.yaml
- modules/030-cloud-provider-azure/templates/cloud-controller-manager/rbac-for-us.yaml
- modules/030-cloud-provider-gcp/templates/cloud-controller-manager/rbac-for-us.yaml
- modules/030-cloud-provider-yandex/templates/cloud-controller-manager/rbac-for-us.yaml
Minimize RBAC permissions by removing the wildcard("*") from ClusterRole rules.
Fixes #8517
```changes
type: fix
summary: Minimize RBAC permissions by removing the wildcard("*") from ClusterRole rules.
```
```changes
type: fix
summary: Minimize RBAC permissions by removing the wildcard("*") from ClusterRole rules.
```
```changes
type: fix
summary: Minimize RBAC permissions by removing the wildcard("*") from ClusterRole rules.
```
```changes
type: fix
summary: Minimize RBAC permissions by removing the wildcard("*") from ClusterRole rules.
```
```changes
type: …
```
> [cloud-provider-*] Minimize RBAC permissions in the ClusterRole

- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
- global-hooks/openapi/config-values.yaml
- global-hooks/openapi/doc-ru-config-values.yaml
Info about domain used in the template should not match the domain specified in the clusterDomain parameter and the internal service network zone. 
```changes
section: docs
type: chore
summary: Additional info for choosing DNS template name in the getting started.
```
> [getting-started] Additional info dns template

- candi/openapi/doc-ru-init_configuration.yaml
- candi/openapi/init_configuration.yaml
Remove deprecated parameters from examples in the InitConfiguration.
```changes
section: docs
type: chore
summary: Remove deprecated parameters from examples in the InitConfiguration
```
> [docs] Remove deprecated parameters from examples in the InitConfiguration

- modules/460-log-shipper/hooks/internal/vector/destination/socket.go
- modules/460-log-shipper/hooks/testdata/file-to-socket/manifests.yaml
- modules/460-log-shipper/hooks/testdata/file-to-socket/result.json
- Set codec field to JSON by default
- Add tests
JSON codec for Socket doesn't work (and this codec is the default one)
```changes
type: fix
summary:  Fix json codec for socket destination
```
> [log-shipper] Fix json codec socket

- docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA.md
- docs/site/_includes/getting_started/kind/STEP_INSTALL_SCHEMA_RU.md
- tools/kind-d8.sh
Upon testing KIND installs from Getting Started, various issues came up
1. `ValidatingAdmissionPolicy` resource is missing and is required by multitenancy-manager on setup (both EE and CE)
2. Instructions for EE install are not valid
Fixes:
1. Added featureGate in Kind config to enable `ValidatingAdmissionPolicy` https://github.com/kubernetes-sigs/kind/issues/3029 (I have tested `kindest/node:v1.30.3`, it's not enabled by default here either, that's why I didn't upgrade the image)
2. Fixed `InitConfiguration` rendering for EE installs
4. Added `docker login` to EE step, because `install` image is pulled from the host
We want our Getting Started experience to be smooth
If we want to fix Getting Started for 1.62
```changes
type: chore
summary: Fixed Kind flow in Getting …
```
> [deckhouse] Various KIND fixes

- go_lib/hooks/migrate_root_disk_size/hook.go
- modules/030-cloud-provider-yandex/hooks/migrate_disk_gb_size_before_changing_default.go
- modules/030-cloud-provider-yandex/hooks/migrate_disk_gb_size_before_changing_default_test.go
Skipping migration `diskSizeGB` for dev build.
After bootstrapping, `dhctl converge` attempts to resize the master boot disk from 50gb to 20gb. 
```changes
type: fix
summary: Skipping migration `diskSizeGB` for dev branch.
type: fix
summary: Skipping migration `diskSizeGB` for dev branch.
```
> [go_lib] Skipping migration `diskSizeGB` for dev build

- modules/002-deckhouse/templates/validation.yaml
After introducing restrictions on changing objects with heritage-deckhouse labels, administrators lost the ability to change objects with kind StorageClass
This situation needs to be corrected.
Administrators should be able to modify system objects that have kind StorageClass.
Administrators are given the ability to modify system kind StorageClass objects.
```changes
type: fix
summary: allow admins to change objects with kind=StorageClass
```
> [deckhouse] fix: allow admins to change objects with kind=StorageClass

- go_lib/hooks/ensure_crds/hook.go
- go_lib/hooks/ensure_crds/hook_test.go
- go_lib/hooks/ensure_crds/test_data/heritage.crd
Fixed: #9268
We have a protection to delete deckhouse installed CRDs. But some CRDs are not marked as deckhouse controlled.
All created crd must have the deckhouse label
```changes
type: feature
summary: add heritage label to all crds
```
> [go_lib] feat: add heritage label to all crds

- dhctl/pkg/kubernetes/actions/resources/resources.go
Fix panic while resources creation
```
│ ┌ Create deckhouse.io/v1alpha1, Kind=ModuleSource resources
│ │ Manifest for ModuleSource deckhouse
│ │ 🎉 Succeeded!
│ └ Create deckhouse.io/v1alpha1, Kind=ModuleSource resources (0.01 seconds)
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1a7693d]
goroutine 7 [running]:
github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes/actions/resources.(*clusterIsBootstrapCheck).outputNodeGroups(0x0?)
/dhctl/pkg/kubernetes/actions/resources/cluster_is_bootstrap.go:174 +0x1d
github.com/deckhouse/deckhouse/dhctl/pkg/kubernetes/actions/resources.(*clusterIsBootstrapCheck).outputProgressInfo(0x0)
/dhctl/pkg/kubernetes/actions/resources/cluster_is_bootstrap.go:168 +0x18 …
```
> [dhctl] Fix panic during resources creation

- modules/007-registrypackages/images/d8/werf.inc.yaml
Updated d8 to the latest release
```changes
type: chore
summary: Updated Deckhouse CLI to v0.3.2
```
> [dhctl] Update Deckhouse CLI to v0.3.2

- docs/documentation/_plugins/openapi.rb
- docs/site/backends/docs-builder-template/config/_default/hugo.yaml
- docs/site/backends/docs-builder-template/layouts/_default/modules.html
- docs/site/backends/docs-builder-template/layouts/_default/single.html
- docs/site/backends/docs-builder-template/layouts/partials/openapi/format-attributes.html
- docs/site/backends/docs-builder-template/layouts/partials/openapi/format-schema.html
- docs/site/css/components/_resources.scss
- docs/site/css/components/common/_variables.scss
- docs/site/css/docs.scss
- docs/site/css/syntax.css
- docs/site/js/customscripts.js
Refactor resource block styles in the documentation.
- Change styles of Open API specifications and code blocks.
- Add the ability to collapse a section of parameters in an Open API specification.
```changes
section: docs
type: chore
summary: Refactor resource block styles in the documentation.
```
> [docs] Refactor resource block styles in the documentation

- global-hooks/migration_service_with_many_ports.go
- global-hooks/migration_service_with_many_ports_test.go
Fixing the broken Services with multiple ports. Helm didn't handle Service resource modification well while deploying https://github.com/deckhouse/deckhouse/pull/8955.
In some clusters Services became broken. In some clusters it was kube-dns.
The release 1.63 is blocked.
All Services are correspond to their templates.
```changes
type: fix
summary: Fixed the Services with multiple ports broken by Helm.
```
> [global-hooks][migration] Fix multiport Services broken by Helm

- dhctl/pkg/preflight/specs_static.go
- dhctl/pkg/preflight/specs_static_test.go
Changed `/proc/cpuinfo` parsing to count logical CPUs instead of physical ones.
It seems we are ok with dual-core dual-thread CPUs on master nodes
```changes
section: dhctl
type: feature
summary: Count logical CPU cores instead of physical in system requirements preflight check.
```
> [dhctl] Count logical CPU cores instead of physical in system requirements preflight check

- .github/dependabot.yml
- modules/007-registrypackages/images/docker-registry/scripts/install
- modules/007-registrypackages/images/docker-registry/scripts/uninstall
- modules/007-registrypackages/images/docker-registry/werf.inc.yaml
- testing/library/images_tags_generated.go
Add standalone docker-registry package.
How to install it ?
```
kind: NodeGroupConfiguration
metadata:
labels:
heritage: deckhouse
name: install-docker-registry.sh
spec:
bundles:
- '*'
content: |
#
#
#
if [[ $HOSTNAME != "master-0" ]]; then
exit 1
fi
bb-package-install "docker-registry:{{- index $.images.registrypackages "dockerRegistry283" }}"
nodeGroups:
- 'master'
weight: 100
```
Take note about
```
if [[ $HOSTNAME != "master-0" ]]; then
exit 1
fi
```
This code set up registry binary only on one master if master hosts more than one.
Sometimes we need own in-cluster registry.
```changes
section: registry-packages
type: chore
summary: add standalone docker-registry package
```
> [registry-packages] add docker-registry package

- candi/bashible/bashible.sh.tpl
Before running `kubectl` check if it exists.
Error while node bootstrap
```changes
section: candi
type: fix
summary: Before running `kubectl` check if it exists.
```
> [candi] Before running `kubectl` check if it exists

- candi/cloud-providers/aws/bashible/bootstrap-networks.sh.tpl
- candi/cloud-providers/yandex/bashible/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/openstack/bashible/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/vcd/bashible/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/vsphere/bashible/bootstrap-networks.sh.tpl
Fix catch exit codes in bootstrap-network scripts.
Non-zero exit codes may be legal in bootstrap-network scripts.
Fix bootstrap new nodes in different cloud-providers.
```changes
section: candi
type: fix
summary: Fix catch exit codes in cloud-providers bootstrap-network scripts.
```
> [candi] fix exit codes in bootstrap-networks scripts

- dhctl/cmd/dhctl/main.go
- dhctl/pkg/system/process/executor.go
- dhctl/pkg/system/ssh/frontend/upload-script.go
Add cpu profiling while DHCTL_TRACE=yes env provided.
While bootstrap static cluster dhctl start consume all cpu cores.
This will begin to appear after adding additional prefly checks https://github.com/deckhouse/deckhouse/pull/8867/files.
It happens  because reader in executor returns error which not handled.
Error raised because we was check interfaced variable on nil itself only, but should check on interfaced typed value.
Also we had leaking goroutines because we did not close pipes.
DHCTL should not consume a lot of cpu during work.
DHCTL should not consume a lot of cpu during work.
Affecter >= 1.62 DKP version
```changes
section: dhctl
type: fix
summary: Fix static installation consume 100% of cpu
```
> [dhctl] Fix static installation consume 100% of cpu

- dhctl/pkg/config/meta.go
Fixed checking the length of the list of external IP addresses in the `YandexClusterConfiguration`.
It is impossible to create nodes without external IP addresses.
```changes
section: dhctl
type: fix
summary: Fixed checking the length of the list of external IP addresses in the `YandexClusterConfiguration`.
```
> [dhctl](cloud-provider-yandex) Fix externalIPAddresses validation

- modules/500-cilium-hubble/images/ui-frontend/patches/001-hubble-ui-vm-name-icon.patch
- modules/500-cilium-hubble/images/ui-frontend/patches/README.md
- modules/500-cilium-hubble/images/ui-frontend/werf.inc.yaml
Improved VM pod appearance in Hubble UI. Now it isn't an "Unknown App", but some VM with name and proper icon.
Hubble UI will:
- Use the label value `vm.kubevirt.internal.virtualization.deckhouse.io/name=<name>` as the name.
- Use the presence of the label `kubevirt.internal.virtualization.deckhouse.io=virt-launcher` to change the icon.
In the Hubble UI, the virtual machine have "Unknown App" instead of a name and have the standard Kubernetes pod icon.
In the Hubble UI, the virtual machine will have the correct name and icon.
```changes
type: chore
summary: Improved VM pod appearance in Hubble UI. Now it isn't an "Unknown App", but some VM with name and proper icon.
```
> [cilium-hubble] Add name to VM pod and change its icon

- candi/cloud-providers/yandex/terraform-modules/master-node/main.tf
When a situation arises when the `externalIP` of the master node is switched from `Auto` to a static one created outside of terraform, then terraform first tries to delete the `externalIP` object before it is disconnected from the VM and got error.
Adding the `lifecycle` resource to the `externalIP` object fixes the problem.
The solution was taken from [similar issue](https://github.com/hashicorp/terraform-provider-google/issues/12748#issuecomment-1273958412) in terraform-provider-google
**The error may be relevant for other cloud providers.**
The modification helps to replace `externalIP` in master nodes correctly
Replacing `externalIP` for master nodes without errors
```changes
section: candi
type: fix
summary:  Fix externalIP detaching before deleting for master node in Yandex cloud. …
```
> [candi](yandex)  Fix externalIP detaching before deleting 

- modules/007-registrypackages/images/iptables/scripts/install
- modules/007-registrypackages/images/iptables/werf.inc.yaml
- modules/035-cni-simple-bridge/images/simple-bridge/werf.inc.yaml
Add kernel version check for installing iptables. According to the documentation nftables is available upstream since Linux kernel 3.13. Also cni-simple-bridge use the same iptables binaries as on the host to prevent incompatibility.
On older kernels (e.g. centos7 with 3.10), there are problems with nftables, despite having the necessary kernel modules.
This issue may affect systems with kernel version < 3.14.
```changes
type: fix
summary: Add kernel version check for installing iptables.
```
```changes
section: cni-simple-bridge
type: fix
summary: cni-simple-bridge use the same iptables binaries as on the host to prevent incompatibility.
```
> [registrypackages][cni-simple-bridge] adding kernel version check for installing iptables and using this iptables bins in the simple-bridge image

- ee/modules/650-runtime-audit-engine/templates/daemonset.yaml
- ee/modules/650-runtime-audit-engine/templates/k8s-metacollector/deployment.yaml
- ee/modules/650-runtime-audit-engine/templates/k8s-metacollector/podmonitor.yaml
- ee/modules/650-runtime-audit-engine/templates/k8s-metacollector/rbac-for-us.yaml
- ee/modules/650-runtime-audit-engine/templates/k8s-metacollector/rbac-to-us.yaml
Fix monitoring rbac permissions.
```changes
type: fix
summary: fix monitoring rbac permissions
```
> [runtime-audin-engine] fix monitoring rbac permissions

- docs/documentation/pages/NETWORK_SECURITY_SETUP.md
- docs/documentation/pages/NETWORK_SECURITY_SETUP_RU.md
Clarifying network security infrastracture requirements in "Network security settings" section.
Some customers thaught that they have to turn VXLAN on to use NetworoPolicies.
```changes
section: docs
type: fix
summary: Clarified network security infrastracture requirements in "Network security settings" section.
```
> [docs] Clarifying network security infrastracture requirements

- candi/bashible/bb_package_install.sh.tpl
Increase number of retries and sleep timeout for `bb-package-install` in bootstrap phase.
Sometimes 3 retries (with 2 seconds timeout) not enough for installing package on node from rpp after execution `netplan apply` (network may not be ready yet).  As we increase the number of attempts and timeout, we will cover such cases.
More successful installations.
```changes
section: candi
type: fix
summary: Increase number of retries and sleep timeout for bb-package-install in bootstrap phase.
```
> [candi] Increase retries for bb-package-install in bootstrap phase

- modules/150-user-authn/images/dex/patches/client-groups.patch
Our patch for checking user groups in dex stopped working due to disabled transition to approve page
Checking for user groups in dex should be done before checking for the need to use the approve page.
Checking for user groups in dex works again.
```changes
type: fix
summary: Update `client-groups.patch` for dex.
```
> [user-authn] fix: update client-groups.patch for dex

- modules/015-admission-policy-engine/templates/validatingwebhookconfiguration.yaml
This pr updates the `namespaceSelector` clause of the admission-policy-engine module's validating web hook.
The problem arises when we set up a namespace to be checked by `trivy-provider` by applying 
the `security.deckhouse.io/trivy-provider` label. If `trivy-provider` is disabled globally, the namespace effectively bypasses all admission-policy-engine checks because current `namespaceSelector` for the admission-policy-web hook looks like this:
```
namespaceSelector:
matchExpressions:
- key: heritage
operator: NotIn
values:
- deckhouse
- key: security.deckhouse.io/trivy-provider
operator: DoesNotExist
```
Second `matchExpression` was introduced to make sure that, when `trivy-provider` is enabled, kube-api doesn't send two requests to the same web hook. But we forgot to apply this …
> [admission-policy-engine] fix validating webhook

- dhctl/pkg/preflight/preflight.go
Added a preflight check to validate that bootstrapping user is able to run elevate priviliges using sudo
Closes #5653
We hit a case where root was not in sudoers file some time ago and it was not obvious what is wrong and how to fix the problem
No change in happy path, error message if user cannot use sudo due to lack of privileges or incorrect password
```changes
section: dhctl
type: fix
summary: added back missing preflight check for sudo access
```
> [dhctl] fix missing static preflight check

- modules/040-node-manager/images/machine-controller-manager/werf.inc.yaml
This PR fixes situation when deleting several NodeGroups mcm crashes with the error "panic: runtime error: invalid memory address or nil pointer dereference"
#8240
machine-controller-manager pod works as usual.
```changes
type: fix
summary: Fix panic in mcm when deleting several NodeGroups
```
> [node-manager] fix panic in mcm

- modules/040-node-manager/hooks/kubelet_csr_approver.go
Validate `CertificateSigningRequest` only if `spec.signerName: "kubernetes.io/kubelet-serving"`.
We need to avoid warnings like this:
```
[warning][node-manager] - capi-controller-manager org does not match: [d8:node-manager:capi-controller-manager:manager-role]
```
```changes
type: fix
summary: Fix CertificateSigningRequest validation in the auto approve hook.
```
> [node-manager] Fix `CSR` validation in the auto approve hook

- docs/documentation/_data/deckhouse-alerts.yml
- modules/040-node-manager/hooks/machine_deployments_caps_metrics.go
- modules/040-node-manager/hooks/machine_deployments_caps_metrics_test.go
- modules/040-node-manager/monitoring/prometheus-rules/caps-nodes.tpl
- modules/040-node-manager/template_tests/module_test.go
- modules/040-node-manager/templates/node-group/_capi_machine_deployment.tpl
- modules/040-node-manager/templates/node-group/_static_or_hybrid_machine_deployment.tpl
Add alert about unavailable CAPS instances.
Closes #8649 .
1. Add new node-group for caps without  prepared StaticInstance:
```bash
[root@dev-master-0 ~]# kubectl apply -f - <<EOF
kind: NodeGroup
metadata:
name: caps-system
spec:
nodeType: Static
staticInstances:
count: 1
labelSelector:
matchLabels:
role: caps-system
EOF
nodegroup.deckhouse.io/caps-system created
[root@dev-master-0 ~]# kubectl get staticinstances.deckhouse.io  -l role=caps-system
No resources found
```
2.   Check instance in the cluster and the relevant alert about its state in prometheus:
```bash
[root@dev-master-0 ~]# kubectl get instance -l node.deckhouse.io/group=caps-system
NAME                      STATUS    AGE
caps-system-g9lc6-645tv   Pending   5m
```
```changes …
```
> [node-manager] Add alert about unavailable CAPS instances

- modules/110-istio/templates/kiali/rbac-for-us.yaml
Added permissions for Kiali to get metrics from Prothemeus (trickster).
When trying to open the traffic graph, error 403 is generated.
The traffic graph is displayed correctly.
```changes
section: istio
type: fix
summary: Fixed graph display issue in Kiali.
```
> [istio] Fixes graph display issue in Kiali

- modules/021-cni-cilium/hooks/set_vm_cidrs.go
- modules/021-cni-cilium/hooks/set_vm_cidrs_test.go
In one of the updates in mc `virtualization`, the parameter was renamed from `vmCIDRs` to `virtualMachineCIDRs`. 
Because of this, the mechanism responsible for setting up masquerading has stopped adding exceptions for DVP virtual machines.
Traffic between virtual machines is masqueraded, although this should not be the case.
This affects some applications
Traffic between virtual machines is not masqueraded.
```changes
type: fix
summary: Fixing masquerading between DVP virtual machines.
impact: This fix disables masquerading between virtual machines.
```
> [cni-cilium] Fixing masquerading between DVP virtual machines.

- docs/site/_includes/getting_started/global/partials/NOTICES.liquid
Remove outdated warnings about proxy settings in Deckhouse v1.42.
```changes
section: docs
type: chore
summary: Remove outdated warnings about proxy settings in Deckhouse v1.42.
```
> [docs] Remove outdated warnings about proxy settings in Deckhouse v1.42

- go_lib/dependency/extenders/deckhouseversion/extender.go
- go_lib/dependency/extenders/kubernetesversion/extender.go
- go_lib/dependency/extenders/kubernetesversion/watcher.go
It provides fix for parsing kubernetes version.
The file with kubernetes version might be empty.
An empty file will be skipped.
```changes
type: fix
summary: Fix parsing kubernetes version.
```
> [deckhouse] fix parsing kubernetes version

- docs/documentation/_data/deckhouse-alerts.yml
- ee/modules/110-istio/monitoring/prometheus-rules/multicluster.yaml
Alerts `D8IstioMulticlusterRemoteAPIHostDoesntWork` has incorrect command for getting token in the alert description.
```changes
section: istio
type: chore
summary: Alerts `D8IstioMulticlusterRemoteAPIHostDoesntWork` has incorrect command for getting token in the alert description.
```
> [istio] repair description in alerts

- ee/modules/160-multitenancy-manager/crds/doc-ru-projects.yaml
- ee/modules/160-multitenancy-manager/crds/projects.yaml
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/cmd/main.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/apis/deckhouse.io/v1alpha2/project.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/consts/main.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/controller/project/main.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/controller/template/main.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/manager/project/main.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/manager/project/utils.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/manager/template/main.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/manager/template/utils.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/webhook/project/main.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/webhook/template/main.go
It provides ```Deckhouse``` and ```Others``` virtual projects and the used namespaces field in a project status.
Fixes #9093
Fixes #9092
All ```kube-*``` and ```d8-*``` namespaces are collected into the ```deckhouse``` virtual project (to the ```.status.namespaces``` field).
All namespaces which are not used in any projects into the ```others``` virtual project.
```changes
type: feature
summary: Add virtual projects and used namespaces to status.
```
> [multitenancy-manager] add virtual projects and used namespaces to status

- dhctl/cmd/dhctl/commands/destroy.go
If key `--yes-i-am-sane-and-i-understand-what-i-am-doing` not used, all resources was deleted from cluster without confirmation, closed [issue](https://github.com/deckhouse/deckhouse/issues/8375)
```changes
section: dhctl
type: feature
summary: Add cleanup resources confirmation on destroy 
```
> [dhctl] Add cleanup resources confirmation on destroy

- modules/460-log-shipper/images/vector/werf.inc.yaml
Bump vector to 0.40.1.
```changes
section: logging
type: chore
summary: Bump vector to `0.40.1`.
```
> [monitoring] bump vector to 0.40.1

- candi/cloud-providers/aws/layouts/standard/base-infrastructure/main.tf
small fix for this [pr](https://github.com/deckhouse/deckhouse/pull/9063) 
Added forgotten “available_except_local_zone” block to layout standard for AWS Cloud Provider
Fix for bootstrap or upgrade an existing cluster  installed in AWS using the "Standard" layout 
Without this fix, bootstrap problems happen
Bootstrap or upgrade an existing cluster in AWS using the “Standard” layout runs successfully
```changes
section: candi
type: fix
summary: Fix for bootstrap or upgrade an existing cluster  installed in AWS using the "Standard" layout 
impact:
```
> [cloud-providers][aws] available_except_local_zone for aws standart layout

- ee/be/modules/350-node-local-dns/templates/configmap.yaml
Add prefer_udp to forward in forward plugin configuration of node-local-dns container coredns.
If application uses TCP to send request to node-local-dns than TCP is used to establish connection with kube-dns.
We previously solved the same problem for kube-dns https://github.com/deckhouse/deckhouse/pull/2413
TCP resolve is used quite rarely, but some clients are affected. It happened presumably because of service `d8-kube-dns-redirect` update in https://github.com/deckhouse/deckhouse/pull/8955
```changes
type: fix
summary: Use prefer_udp to connect with kube-dns
```
> [node-local-dns] Use prefer_udp to connect with kube-dns

- candi/bashible/common-steps/all/098_set_permissions.sh.tpl
- modules/040-control-plane-manager/images/control-plane-manager/controller/config.go
- modules/040-control-plane-manager/images/control-plane-manager/controller/converge.go
- modules/040-control-plane-manager/images/control-plane-manager/controller/kubeconfig.go
- modules/040-control-plane-manager/images/control-plane-manager/controller/pki.go
- modules/040-control-plane-manager/images/control-plane-manager/controller/util.go
Stricter permissions (0700 for directories, 0600 for files) to all kubelet config files and PKI files. This is done to improve security.
These changes are needed to make the Kubernetes cluster more secure. With these permissions, only the necessary services and the root user can access important configuration files, reducing the risk of unauthorized access.
After these changes, the permissions on kubelet directories and files will be stricter—0700 for directories and 0600 for files. 
```changes
section: control-plane-manager,candi
summary: Stricter permissions (0700/0600) applied to kubelet configuration and PKI files to improve security.
impact: 
```
> [candi] kubelet files strict permissions

- deckhouse-controller/pkg/helpers/change_registry/change_registry.go
- deckhouse-controller/pkg/helpers/change_registry/change_registry_test.go
Update validation of the response header from registry for change-registry helper. Previously there was strict validation for bearer token support now basic auth is allowed. 
Some legacy container registries only support basic auth.
change-registry helper runs successfully for repository with basic-auth
```changes
type: fix
summary: Adding basic-auth support for change-registry helper 
impact: 
```
> helper change-registry bearer or basic auth support

- modules/015-admission-policy-engine/charts/constraint-templates/templates/operation/ingress-class.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/templates/operation/storage-class.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/ingress-class/allowed.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/ingress-class/constraint.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/ingress-class/disallowed.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/ingress-class/suite.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/storage-class/allowed.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/storage-class/constraint.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/storage-class/disallowed.yaml
- modules/015-admission-policy-engine/charts/constraint-templates/tests/storage-class/suite.yaml
- modules/015-admission-policy-engine/crds/doc-ru-operation-policy.yaml
- modules/015-admission-policy-engine/crds/operation-policy.yaml
- modules/015-admission-policy-engine/hooks/handle_operation_policies_test.go
- modules/015-admission-policy-engine/hooks/internal/apis/v1alpha1.go
- modules/015-admission-policy-engine/template_tests/operation_policies_test.go
- modules/015-admission-policy-engine/templates/policies/operation-policy/constraint.yaml
Close https://github.com/deckhouse/deckhouse/issues/9087
```changes
type: feature
summary: Added ability to limit ingressClassName for Ingress and storageClassName for PersistentVolumeClaim for project / namespace / etc
```
> [admission-policy-engine] Added new checks for OperationPolicy 

- deckhouse-controller/pkg/helpers/change_registry/change_registry.go
Trim ending slash from registry.
For example, `registry.deckhouse.io/deckhouse/ee/` -> `registry.deckhouse.io/deckhouse/ee`
Like it done in dhctl https://github.com/deckhouse/deckhouse/blob/cf33d8655e04ed81d63e9725dc53f7b6c9d37239/dhctl/pkg/config/meta.go#L90
Users often type registry path with ending slash in command to change registry:
```
kubectl exec -ti -n d8-system deploy/deckhouse -c deckhouse -- deckhouse-controller helper change-registry  --user license-token --password PASSWORD registry.deckhouse.io/deckhouse/ee/
```
And command executes with no error:
```
~ $ kubectl exec -ti -n d8-system deploy/deckhouse -c deckhouse -- deckhouse-controller helper change-registry   --user license-token --password PASSWORD registry.deckhouse.io/deckhouse/ee/
INFO[0000] Kubernetes client is …
```
> [deckhouse-controller] Trim ending slash of registry in helper change-registry command

- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/operations/bootstrap/state.go
- dhctl/pkg/preflight/preflight.go
- dhctl/pkg/preflight/registry_test.go
- dhctl/pkg/preflight/suite_test.go
added dhctl preflight cache files, when boostraping is interrupt it restore data preflight from cache
this allow to not generate all bootstrap preflight checks again on bootstrap stage if bootstrap was interrupt
preflight check status save in cache
```changes
section: dhctl
type: fix
summary: Skip preflight checks after restarting bootstrap if checks were finished successfully 
```
> [dhctl] Skip preflight checks after restarting bootstrap if checks were finished successfully 

- candi/bashible/bootstrap/01-network-scripts.sh.tpl
This update removes the cloud metadata request from the bootstrap script (`http://169.254.169.254/`) when adding static nodes in hybrid clusters. This change is needed to support environments where nodes are in on-premise data centers without access to cloud metadata.
The change fixes an issue where static nodes in hybrid clusters failed to bootstrap correctly because the script tried to use cloud metadata, which isn't available in on-prem environments.
Static nodes in hybrid clusters should bootstrap without errors related to cloud metadata.
```changes
section: candi
type: fix
summary: Fix bootstrap script for static nodes in hybrid clusters to avoid using cloud metadata
impact:
```
> [bashible] Do not use cloud metadata server for static nodegroup

- ee/modules/030-cloud-provider-openstack/templates/csi/volume-snapshot-class.yaml
- ee/modules/030-cloud-provider-vsphere/templates/csi/volume-snapshot-class.yaml
- modules/030-cloud-provider-aws/templates/csi/volume-snapshot-class.yaml
- modules/030-cloud-provider-azure/templates/csi/volume-snapshot-class.yaml
- modules/030-cloud-provider-gcp/templates/csi/volume-snapshot-class.yaml
Update `VolumeSnapshotClass.apiVersion` from v1beta1 to v1.
`VolumeSnapshotClass.apiVersion` v1beta1 is deprecated.
```changes
type: fix
summary: Update `VolumeSnapshotClass.apiVersion` from v1beta1 to v1.
type: fix
summary: Update `VolumeSnapshotClass.apiVersion` from v1beta1 to v1.
type: fix
summary: Update `VolumeSnapshotClass.apiVersion` from v1beta1 to v1.
type: fix
summary: Update `VolumeSnapshotClass.apiVersion` from v1beta1 to v1.
type: fix
summary: Update `VolumeSnapshotClass.apiVersion` from v1beta1 to v1.
```
> [cloud-provider-*] Update VolumeSnapshotClass apiVersion

- modules/340-monitoring-ping/templates/daemon-set.yaml
- modules/460-log-shipper/template_tests/module_test.go
- modules/460-log-shipper/templates/daemonset.yaml
- modules/470-chrony/templates/daemonset.yaml
Reduce the memory request for daemonsets
In most clusters, we get a large over requests for some ds on each nodes. Unused memory can be used for client workload
Monitoring-ping:
Vector-reloader:
Chrony:
Over-requests reduce in large clusters without performance losses
```changes
type: fix
summary: Reduce over-requested memory.
```
> [monitoring][chrony] Reduce memory requests in ds

- ee/modules/030-cloud-provider-vcd/images/capcd-controller-manager/werf.inc.yaml
- ee/modules/030-cloud-provider-zvirt/images/cloud-controller-manager/werf.inc.yaml
Fixed missing -y flag for build in modules cloud-provider-vcd/capcd-controller-manager and cloud-provider-zvirt/cloud-controller-manager
Modules might not build if the flag is not present.
Successful build of modules.
```changes
section: ci
type: chore
summary: Fix missing -y flag for build in modules
```
> [ci] Fix missing -y flag for apt

- dhctl/pkg/operations/kube.go
Fixed editing of cluster configs via `deckhouse-controller edit *cluster-configuration` that broke with addition of local bootstrapping feature.
This fixes the standard recommended way of editing cluster configuration
```changes
section: dhctl
type: fix
summary: Fix editing of cluster configs via `deckhouse-controller edit`
```
> [dhctl] Fix editing of cluster configs

- ee/be/modules/600-flant-integration/images/flant-pricing/werf.inc.yaml
- modules/000-common/images/shell-operator/werf.inc.yaml
- modules/002-deckhouse/images/webhook-handler/werf.inc.yaml
- modules/110-istio/images/metadata-discovery/werf.inc.yaml
- modules/300-prometheus/images/grafana-dashboard-provisioner/werf.inc.yaml
The base image and Python version in dependent images have been updated.
```changes
---
type: chore
summary: Update base images in `common/shell-operator`.
---
type: chore
summary: Update Python in images `flant-pricing`.
---
type: chore
summary: Update Python in images `webhook-handler`.
---
type: chore
summary: Update Python in images `grafana-dashboard-provisioner`.
```
> [common] update common/shell-operator images

- ee/modules/030-cloud-provider-zvirt/images/cloud-controller-manager/src/pkg/cloudprovider/zvirt/instances.go
Added a condition to use external addresses if internal ones are missing
So that modules such as monitoring-ping work correctly. [Monitoring-ping pods will crash if there are no targets to ping](https://github.com/deckhouse/deckhouse/blob/main/modules/340-monitoring-ping/images/monitoring-ping/monitoring-ping.py#L116)
zvirt nodes have internal addresses. monitoring-ping pods work as expected without crashes
```changes
type: fix
summary: Fix monitoring-ping pods crashing
```
> [cloud-provider-zvirt] Fix empty private IP addresses

- candi/bashible/bundles/debian/all/002_disable_unattended_upgrades.sh.tpl
- candi/bashible/bundles/debian/all/010_disable_unattended_upgrades.sh.tpl
- candi/bashible/bundles/ubuntu-lts/all/002_disable_unattended_upgrades.sh.tpl
- ee/be/candi/bashible/bundles/astra/all/002_disable_unattended_upgrades.sh.tpl
- testing/cloud_layouts/VCD/Standard/configuration.tpl.yaml
Disable and remove unattended upgrades early for debian and ubuntu and astra
Remove cni-cilium from cluster configuration for vcd e2e
In some cases unattended upgrades block apt install
```changes
section: candi
type: fix
summary: Disable and remove unattended upgrades early for debian and ubuntu and astra.
```
> [candi] Disable and remove unattended upgrades early for debian and ubuntu and astra

- dhctl/pkg/terminal/ask-password.go
Use sudo become password from non-interactive stdin with flag --ask-become-sudo. ex.:
`echo "PASSWORD" | dhctl bootstrap`
this allow to use become sudo password for non-interactive usage, if need for example ansible automation
sudo become password get from non-interactive stdin
```changes
section: dhctl
type: feature
summary: Sudo become password from non-interactive stdin. 
```
> [dhctl] Sudo become password from non-interactive stdin

- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
- docs/documentation/_data/deckhouse-alerts.yml
- modules/002-deckhouse/templates/validation.yaml
- modules/340-monitoring-deckhouse/monitoring/prometheus-rules/deckhouse.yaml
If you create a _ModuleRelease_ resource with a _ModuleUpdatePolicy_ and then remove the _ModuleUpdatePolicy_, the module stops updating.
Instead of errors in the logs, a module should get update settings from the default _ModuleUpdatePolicy_.
Removing ModuleUpdatePolicy should not block module updates.
ModuleRelease should find new matching ModuleUpdatePolicy or fallback to the embedded one (the default _ModuleUpdatePolicy_)
```changes
type: fix
summary: Use the default _ModuleUpdatePolicy_ if the _ModuleUpdatePolicy_, referenced in _ModuleRelease_, has been deleted.
```
Fixed: #8988
> [deckhouse-controller] fix: ModuleRelease with absent ModuleReleasePolicy

- deckhouse-controller/pkg/controller/deckhouse-release/check_release.go
- deckhouse-controller/pkg/controller/deckhouse-release/check_release_test.go
- deckhouse-controller/pkg/controller/deckhouse-release/controller_test.go
- deckhouse-controller/pkg/controller/deckhouse-release/next_version_test.go
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/notification-basic-auth.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/notification-bearer-token-auth.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/notification-release-apply-after-time-is-after-notification-period.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/postponed-release.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/restore-absent-releases-from-registry.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/restore-absent-releases-from-registry.yaml
- go_lib/dependency/dependency.go
Restore absent releases from a registry
Close https://github.com/deckhouse/deckhouse/issues/8991
```changes
type: feature
summary: Restore absent releases from a registry
```
> [deckhouse-controller] Restore absent releases from a registry

- candi/cloud-providers/azure/openapi/cluster_configuration.yaml
https://github.com/deckhouse/deckhouse/issues/8933
In some cases may need to use Microsoft.CognitiveServices values for serviceEndpoints in AzureClusterConfiguration
expand values for serviceEndpoints in Azureclusterconfiguration
```changes
type: chore
summary: Add `Microsoft.CognitiveServices` to allowed values of serviceEndpoint module parameter.
```
> [azure] add values to serviceEndpoint

- modules/462-loki/images/loki/Dockerfile
- modules/462-loki/monitoring/grafana-dashboards/applications/loki-search.json
- modules/462-loki/monitoring/grafana-dashboards/applications/loki.json
- modules/462-loki/openapi/config-values.yaml
- modules/462-loki/openapi/doc-ru-config-values.yaml
- modules/462-loki/templates/configmap.yaml
- modules/462-loki/templates/monitoring.yaml
Currently, Loki runs with nearly default configuration, which is irrelevant to almost every real-world demand.
This PR introduces a limited amount of tunable parameters, yet can address most log delivery problems.
The default Loki configuration cannot ingest even a moderate amount of logs seen in most clusters. Lots of 4xx errors can be observed at a log send software due to rate limiting or other obstacles imposed by the Loki configuration. It's almost certain that the user will have to alter the default configuration to achieve smooth log delivery.
We don't
```changes
section: loki
type: feature
summary: Configurable Loki limits
impact: Loki pod will be restarted. Short disruption will occur.
```
> [loki] Add configuration tunables for Loki

- ee/se/modules/502-delivery/hooks/migration_service_with_many_ports.go
- ee/se/modules/502-delivery/hooks/migration_service_with_many_ports_test.go
- ee/se/modules/502-delivery/templates/argocd/repo-server/argocd-repo-server-service.yaml
- ee/se/modules/502-delivery/templates/argocd/server/argocd-server-service.yaml
- modules/002-deckhouse/hooks/migration_service_with_many_ports.go
- modules/002-deckhouse/hooks/migration_service_with_many_ports_test.go
- modules/002-deckhouse/templates/deckhouse-leader-service.yaml
- modules/002-deckhouse/templates/service.yaml
- modules/042-kube-dns/hooks/migration_service_with_many_ports.go
- modules/042-kube-dns/hooks/migration_service_with_many_ports_test.go
- modules/110-istio/hooks/migration_service_with_many_ports.go
- modules/110-istio/hooks/migration_service_with_many_ports_test.go
- modules/110-istio/templates/kiali/service.yaml
- modules/300-prometheus/hooks/migration_service_with_many_ports.go
- modules/300-prometheus/hooks/migration_service_with_many_ports_test.go
- modules/300-prometheus/templates/memcached/service.yaml
Fixing the broken Services with multiple ports. Helm didn't handle Service resource modification well while deploying https://github.com/deckhouse/deckhouse/pull/8955.
In some clusters, Services became broken. In some clusters it was kube-dns.
All Services are corresponded to their templates.
```changes
---
type: fix
summary: Fixed the d8-kube-dns and d8-kube-dns-redirect Services with multiple ports broken by Helm (pr #8955).
---
type: fix
summary: Fixed the argocd-repo-server and argocd-server Services with multiple ports broken by Helm (pr #8955).
---
type: fix
summary: Fixed the deckhouse-leader and deckhouse Services with multiple ports broken by Helm (pr #8955).
---
section: istio
type: fix
summary: Fixed the kiali Service with …
```
> [migration] Fix multiport Services broken by Helm

- docs/site/_includes/getting_started/bm-private/partials/config.yml.ce.inc
- docs/site/js/getting-started-private.js
Replaced the description of the `noProxy` parameter in `config.yml` in GS.
```changes
section: docs
type: fix
summary: Replaced the description of the `noProxy` parameter in `config.yml` in GS.
```
> [docs][getting started] Fix comment about noProxy parameter in GS

- .github/ci_templates/e2e_tests.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vcd.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
Delete e2e cluster after cancel e2e
Delete e2e cluster after cancel e2e
```changes
section: ci
type: fix
summary: Delete e2e cluster after cancel e2e.
```
> [CI] Delete e2e cluster after cancel e2e

- modules/150-user-authn/openapi/config-values.yaml
- modules/150-user-authn/openapi/doc-ru-config-values.yaml
Fix translation for `addKubeconfigGeneratorEntry` parameter.
```changes
type: chore
summary: |
Fix translation for `addKubeconfigGeneratorEntry` parameter.
```
> [user-authn] Fix translate to russian for option addKubeconfigGeneratorEntry

- .github/ci_includes/werf_envs.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- tools/images_tags/main.go
- werf-giterminism.yaml
- werf.yaml
Add CLOUD_PROVIDERS_SOURCE_REPO env
Need to build protected cloud providers.
```changes
section: ci
type: chore
summary: Add CLOUD_PROVIDERS_SOURCE_REPO env for build protected cloud providers
```
> [ci] Add CLOUD_PROVIDERS_SOURCE_REPO env for build protected cloud providers

- README.md
Update CNCF certification info in the repo README.
```changes
section: docs
type: chore
summary: Update CNCF certification info in the repo README.
```
> [docs] Update CNCF certification info

- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
Fix command with regexp for detect modules in deckhouse image.
Expected processing of the regular expression and return the result without empty lines.
```bash
[deckhouse] root@50cee49b4caa / # ls -l deckhouse/modules/ | awk {'print $9'}  |grep -oP "\d.*-\w*"
000-common
001-priority-class
002-deckhouse
005-external-module-manager
007-registrypackages
010-cloud-data-crd
010-metallb-crd
010-operator-prometheus-crd
010-prometheus-crd
010-snapshot-controller-crd
010-user-authn-crd
010-vertical-pod-autoscaler-crd
011-flow-schema
015-admission-policy-engine
021-cni-cilium
...
```
```changes
section: docs
type: chore
summary: Fix command with regexp for detect modules in deckhouse image.
```
> [docs] fix command with regexp for detect modules in deckhouse image

- dhctl/pkg/preflight/preflight.go
Fixed wrong skip flag in preflight check and added logic to detect such duplicates in the future
This improves bad user experience
```changes
section: dhctl
type: fix
summary: Fix wrong skip flag for CheckLocalhostDomain preflight check
```
> [dhctl] Fix wrong skip flag for CheckLocalhostDomain preflight check

- .github/workflow_templates/deploy-channel.multi.yml
- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-early-access.yml
- .github/workflows/deploy-rock-solid.yml
- .github/workflows/deploy-stable.yml
Add check cooldown for release action
Closes #5306 
```changes
section: ci
type: fix
summary: Add check cooldown for release.
```
> [CI] Add check cooldown for release

- dhctl/pkg/server/pkg/interceptors/interceptors.go
- dhctl/pkg/server/pkg/logger/logger.go
- dhctl/pkg/server/pkg/logger/writer.go
- dhctl/pkg/server/pkg/logger/writer_test.go
- dhctl/pkg/server/rpc/dhctl/abort.go
- dhctl/pkg/server/rpc/dhctl/bootstrap.go
- dhctl/pkg/server/rpc/dhctl/check.go
- dhctl/pkg/server/rpc/dhctl/commander_attach.go
- dhctl/pkg/server/rpc/dhctl/commander_detach.go
- dhctl/pkg/server/rpc/dhctl/converge.go
- dhctl/pkg/server/rpc/dhctl/destroy.go
- dhctl/pkg/server/rpc/dhctl/service.go
- dhctl/pkg/server/server/proxy.go
- dhctl/pkg/server/server/server.go
- dhctl/pkg/server/server/singlethreaded/server.go
- Reduced code duplication in the gRPC server message handler
- Reduced code duplication in the log sender
- Refactored the graceful shutdown mechanism
- Added support for proper log output for multiple parallel instances of the dhctl server
It is not expected to change behaviour of any dhctl operation not in commander-mode. 
```changes
section: dhctl
type: feature
summary: Reduces code duplication in the gRPC server message handler and log sender, refactors the graceful shutdown mechanism, and adds support for proper log output for multiple parallel instances of the dhctl server.
```
> [dhctl] feat(dhctl-for-commander): server refactoring

- modules/042-kube-dns/templates/configmap.yaml
Added lameduck Option to CoreDNS Health Plugin Configuration. lameduck option delays the shutdown of CoreDNS for a specified duration, allowing the `/health` endpoint to continue returning 200 OK during this period. This ensures that ongoing requests can complete before the server fully shuts down.
https://coredns.io/plugins/health/
https://github.com/coredns/coredns/blob/master/plugin/health/README.md
Currently, during the rollout of `d8-kube-dns` deployment, CoreDNS pod shuts down before it can process all incoming requests. The `lameduck` option ensures it remains in a terminating state for 15 seconds, allowing it to complete processing all requests and return responses before fully shutting down.
Graceful rollout of the kube-dns deployment without disrupting connections.
```changes …
```
> [kube-dns] rollout enhancement

- modules/040-node-manager/docs/FAQ.md
- modules/040-node-manager/docs/FAQ_RU.md
Adding a config edit command to our nvidia-container-toolkit installation example in docs to lower the log level:
```
nvidia-ctk config --set nvidia-container-runtime.log-level=error --in-place
```
Workaround for https://github.com/deckhouse/deckhouse/issues/6186
Basically, on default log-level `info` every exec into a container is logged in log.json, which leads to the log file growth when pods have exec probes. That's why we suggest to lower the log level
```changes
type: chore
summary: Update to nvidia GPU support FAQ.
```
> [node-manager] Setting nvidia-ctk log-level to error in docs

- dhctl/cmd/dhctl/main.go
- werf.yaml
Replaced `getwd` syscall with path of dhctl binary for building paths to resources such as candi, etc.
This fixes execution in cases where dhctl is called with working dir which differs from the actual dhctl binary location
```changes
section: dhctl
type: fix
summary: Use dhctl binary path instead of working dir when building paths to resources
```
> [dhctl] Use dhctl binary path instead of working dir when building paths to resources

- deckhouse-controller/pkg/controller/deckhouse-release/check_release.go
Fixed panic when processing release with nil applyAfter
Fixed panic when processing release with nil applyAfter
Fixed panic when processing release with nil applyAfter
```changes
type: fix
summary: Fixed panic when processing release with nil applyAfter
```
> [deckhouse-controller] Fixed panic when  processing release with nil applyAfter

- werf.yaml
Add forgotten CLOUD_PROVIDERS_SOURCE_REPO in werf.inc.yaml context
CLOUD_PROVIDERS_SOURCE_REPO does not work.
```changes
section: ci
type: chore
summary: Add forgotten CLOUD_PROVIDERS_SOURCE_REPO in werf.inc.yaml context
```
> [ci] Add forgotten CLOUD_PROVIDERS_SOURCE_REPO in werf.inc.yaml context

- modules/600-secret-copier/hooks/handler.go
- modules/600-secret-copier/hooks/handler_test.go
Delete labels that belong to ArgoCD on copied secrets
Now secrets copied by module does not belong to ArgoCD.
```changes
type: feature
summary: Delete ArgoCD labels on copied secrets
```
> [secret-copier] Delete argocd labels from copied secrets

- testing/cloud_layouts/script.sh
Added fallback to curl if wget is not available on e2e test machine.
In some cases, e2e testing can fail after running all tests as wget is not present on the current machine. It is possible to bypass that by using curl.
e2e test script uses curl.
```changes
type: fix
summary: Add fallback to curl if wget is not available on e2e test machine.
```
> [testing] Fallback to curl if wget is not available on e2e tests

- ee/modules/030-cloud-provider-zvirt/hooks/discover.go
- ee/modules/030-cloud-provider-zvirt/openapi/values.yaml
- ee/modules/030-cloud-provider-zvirt/templates/csi/controller.yaml
- ee/modules/030-cloud-provider-zvirt/templates/csi/storage-classes.yaml
This PR allows volume expansion in Zvirt clusters
To be able to expand volumes in Zvirt clusters
After a PVC spec resources requests storage has been increased, we expect the status capacity storage to be increased accordingly
```changes
type: feature
summary: Allow Zvirt volume expansion.
```
> [cloud-provider-zvirt] Allow volume expansion

- deckhouse-controller/pkg/debug/debug.go
Improved debugging information
Also сloses [issue](https://github.com/deckhouse/deckhouse/issues/5953)
I suggest add additional debugging information about:
- CAR
- AR
- pods
- mc
```changes
type: feature
summary: add additional debugging information
```
> [deckhouse-controller] Improved debugging information

- docs/documentation/_includes/d8-cli-install/content.liquid
- docs/documentation/werf-git-section.inc.yaml
- docs/documentation/werf.yaml
- modules/810-documentation/images/web/werf.inc.yaml
The source for the Deckhouse CLI version has been changed in the #9140. The PR fix the issue.
```changes
section: docs
type: chore
summary: Update source for the Deckhouse CLI version.
```
> [docs] Update source for the Deckhouse CLI version.

- modules/040-node-manager/images/caps-controller-manager/src/internal/client/cleanup.go
Don't use bash builtin functions ( `[[ ... ]]` ) in shell command.
```
I0912 09:17:52.005909       1 logger.go:62] "stderr: OpenSSH client output" controller="staticmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="StaticMachine" StaticMachine="d8-cloud-instance-manager/static-worker-st5km-fngml" namespace="d8-cloud-instance-manager" name="static-worker-st5km-fngml" reconcileID="b1ae2aae-568e-46ef-8550-52e0f1e2f7d1" line=59 output="debug1: Sending command: sudo sh -c \"if [[ ! -f /var/lib/bashible/cleanup_static_node.sh ]]; then rm -rf /var/lib/bashible; (sleep 5 && shutdown -r now) & else bash /var/lib/bashible/cleanup_static_node.sh --yes-i-am-sane-and-i-understand-what-i-am-doing; fi\""
I0912 09:17:52.015639       1 logger.go:62] "stderr: OpenSSH client output" …
```
> [node-manager] fix cleanup command for nodes managed by caps-сontroller.

- modules/040-node-manager/images/caps-controller-manager/src/internal/ssh/ssh.go
Fix error handling in the SSH client.
```changes
type: fix
summary: Fix error handling in the CAPS SSH client.
```
> [caps] Fix error handling in the SSH client

- modules/040-node-manager/images/caps-controller-manager/src/internal/client/bootstrap.go
- modules/040-node-manager/templates/node-group/_static_or_hybrid_script.tpl
1. Fix recreate bootstrap-token on already bootstraped nodes.
2. Fixes from PR : #9680 
- Remove checking for node.deckhouse.io/configuration-checksum annotation before change StaticInstance phase to Running.
-  Check if the node status is Ready before change StaticInstance phase to Running.
In cases with parallel bootstrap of multiple nodes:
- Caps-controller may run bootstrap second time on node, which already bootstraping.
- Caps-controller may slowly check and set `Running` status on staticinstances.
Fix errors when caps bootstrap multiple nodes.
```changes
section: node-manger
type: fix
summary: fix caps bootstrap multiple nodes.
```
> [node-manager] fix caps bootstrap multiple nodes  

- dhctl/pkg/config/base_test.go
- dhctl/pkg/config/meta.go
- dhctl/pkg/config/meta_test.go
- dhctl/pkg/config/mocks/1-InitConfiguration.yml
- dhctl/pkg/preflight/registry_test.go
Added repo check to validateRegistryDockerCfg
Close https://github.com/deckhouse/deckhouse/issues/3814
```changes
section: dhctl
type: fix
summary: Added repo check to validateRegistryDockerCfg
```
> [dhctl] Added repo check to validateRegistryDockerCfg

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- Makefile
There is a [warning](https://github.com/deckhouse/deckhouse/actions/runs/4646537433/jobs/8231552929#step:12:15360) on the build stage:
```
DEPRECATED: use --save-build-report ($WERF_SAVE_BUILD_REPORT) with optional --build-report-path ($WERF_BUILD_REPORT_PATH)        ↵
instead of --report-format ($WERF_REPORT_FORMAT)
```
Need to update werf launch syntax.
Not related to release.
Warning is not displayed.
Replace deprecated --report-path command with --build-report-path
```changes
section: ci
type: fix
summary: Replace deprecated --report-path command with --build-report-path.
```
> [fix] Replace deprecated --report-path command with --build-report-path

- ee/modules/650-runtime-audit-engine/templates/configmap.yaml
Allow falco to match multiple rules on same event.
Be default, if rule matches event, than event stopped to match against rules.
This leads to the fact that user-defined rules cannot fired if event is matched against build-in deckhouse rules.
https://github.com/falcosecurity/falco/pull/2705.
```changes
type: chore
summary: Allow falco to match multiple rules on same event.
```
> [runtime-audit-engine] allow falco to match multiple rules on same event

- .github/workflow_templates/check-pr-milestone.yml
- .github/workflows/check-pr-milestone.yml
Sometimes the milestone check does not start.
Change the rules for running a milestone check. Remove rules not supported in [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target)
Does not apply to the release
Milestone check is always triggered when the PR changes
```changes
section: ci
type: chore
summary: Change check milestone rules.
```
> [chore] Change check milestone rules

- testing/cloud_layouts/script.sh
Use d8-curl from Deckhouse package for downloading files in e2e test script
In some cases, e2e testing can fail after running all tests as neither curl nor wget are present on the current machine. It is possible to bypass that by using d8-curl.
e2e test script uses curl.
```changes
type: fix
summary: Switch to d8-curl for downloading files in e2e test script.
```
> [testing] Switch to d8-curl from Deckhouse package in e2e test script

- modules/040-control-plane-manager/monitoring/prometheus-rules/etcd-maintenance.yaml
- testing/cloud_layouts/script.d/wait_cluster_ready/test_alerts.sh
Small fix for this [pr](https://github.com/deckhouse/deckhouse/pull/9464#issue-2480896609)
The alert may trigger during a short-term sharp increase in the number of resources (e.g., during cluster bootstrap). The alert firing time has been increased to 30 minutes.
D8EtcdExcessiveDatabaseGrowth alert does not trigger during bootstrap.
```changes
type: fix 
summary: D8EtcdExcessiveDatabaseGrowth alert fix
impact:
```
> D8EtcdExcessiveDatabaseGrowth alert fix

- modules/340-extended-monitoring/images/image-availability-exporter/Dockerfile
Bumped image-availability-exporter version
To keep module in fresh state and to use new features
We don't
Latest image of image-availability-exporter in containers
```changes
type: chore
summary: newer version of image-availability-export with new features
```
> [extended-monitoring] bump image-availability-exporter version

- global-hooks/migrate/migrate_d8_cni_secret.go
- global-hooks/migrate/migrate_d8_cni_secret_test.go
Add default for cni-cilium default masquerade mode.
If module config cni-* exists and settings is empty (expect cni-simple-bridge) then do migration.  
Migration fail with error `Error: global hook 'migrate/migrate_d8_cni_secret.go' failed: unknown cilium masquerade mode `
```changes
type: fix 
summary: Fix cni secret migration.
```
> [global-hooks] Fix cni secret migration

- testing/cloud_layouts/script.sh
Add `-` for `su` command for pass envs (ex https_proxy that needs for curl) to new root env
Upgrade deckhouse version e2e test for static.
```changes
type: chore
summary: Fix static upgrade deckhouse e2e.
```
> [testing] Fix static upgrade deckhouse e2e

- modules/462-loki/openapi/config-values.yaml
- modules/462-loki/openapi/doc-ru-config-values.yaml
Changing code block with example in maxStreamsPerUser
```changes
section: loki
type: fix 
summary: Update `maxStreamsPerUser` parameter description.
```
> [docs] Changing code block with example in maxStreamsPerUser

- modules/021-cni-cilium/hooks/set_cilium_mode.go
Forcing cni-cilium module to apply ModuleConfig settings immediately without d8 restart. (`tunnelMode`, for example).
Some module settings are being handled in the `set_cilium_mode.go` hook which was configured to run only OnStartup (https://github.com/deckhouse/deckhouse/pull/9347). The PR fixes the problem by configuring the hook to run OnBeforeHelm.
To apply cni-cilium MC settings we have to restart deckhouse controller.
Settings are being applied immediately. `tunnelMode`, for example.
```changes
type: fix
summary: Forcing module to apply ModuleConfig settings immediately without d8 restart.
```
> [cni-cilium] Applying the ModuleConfig changes immediately

- docs/site/.werf/nginx.conf
Adjusted regular expressions in deckhouse website nginx configuration to allow downloading of d8-cli checksum files via `location` that is used to proxy the main `d8` binary.
Some users are either afraid or forbidden to download from github, but still wish to validate checksums of `d8` binaries they are installing
```changes
section: docs
type: chore
summary: Proxy d8-cli checksum files alongside main d8 binaries.
```
> [site] Proxy d8-cli checksum files

- global-hooks/migrate/migrate_d8_cni_secret.go
Fix migrate cni secret migration for updating existing secret
Fix error if mc already exists 
`failed: moduleconfigs.deckhouse.io \"cni-cilium\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update`
```changes
type: fix
summary: Fix CNI secret migration for updating existing secret.
```
> [global-hooks] Fix migrate cni secret migration for updating existing secret

- deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go
- docs/documentation/_data/deckhouse-alerts.yml
- ee/modules/381-l2-load-balancer/hooks/alert_module_deprecated.go
- ee/modules/381-l2-load-balancer/hooks/alert_module_deprecated_test.go
- ee/modules/381-l2-load-balancer/hooks/disable_requirements_flag.go
- ee/modules/381-l2-load-balancer/hooks/disable_requirements_flag_test.go
- ee/modules/381-l2-load-balancer/monitoring/prometheus-rules/services.yaml
- ee/modules/381-l2-load-balancer/requirements/check.go
- ee/modules/381-l2-load-balancer/requirements/check_test.go
- testing/cloud_layouts/Static/configuration.tpl.yaml
- testing/cloud_layouts/Static/resources.tpl.yaml
Module `l2LoadBalancer` is deprecated. Add an alert about it.
It is necessary to warn and prepare for the transfer of clients to use the MetalLB module.
- Users are warned that the module is deprecated.
- Not allowed to update cluster if the l2-load-balancer module is enabled.
```changes
type: feature
summary: Set the l2-load-balancer module to deprecated status.
impact: l2-load-balancer module is deprecated. To upgrade to the next DKP version, you must disable the l2-load-balancer module.
```
> [l2-load-balancer] Deprecating the module

- ee/candi/cloud-providers/vcd/terraform-modules/master-node/main.tf
- ee/candi/cloud-providers/vcd/terraform-modules/static-node/main.tf
Add PVC disks to ignore_changes lifecycle for CloudPermanent nodes at VMware Cloud Director.
We have cluster with CloudPermanent NodeGroup system what means, that Prometheus pods was scheduled and mount PVC to node. After this we have alert `D8TerraformStateExporterNodeStateChanged` and terraform show that we need to detach disks:
```
┌ 🌱 ~ Terraform: Check state static-node for cmdr-system-1
│ ┌ terraform init ...
│ │
│ │ Initializing the backend...
│ │
│ │ Initializing provider plugins...
│ │ - Reusing previous version of vmware/vcd from the dependency lock file
│ │ - Using previously-installed vmware/vcd v3.10.0
│ │
│ │
│ │ Warning: No-op -get-plugins flag used
│ │
│ │ As of Terraform 0.13+, the -get-plugins=false command is a no-op flag. If you
│ │ would like to customize provider …
```
> [candi][vcd] Add PVC disks to ignore_changes lifecycle

- modules/150-user-authn/templates/validation.yaml
We have system users who are registered with an email that has + symbols in it.
It is necessary that the validation of such users takes place correctly.
Without proper validation, there is no way to allow users to make changes to the cluster configuration.
Users with email containing a plus will be verified.
```changes
type: fix
summary: allow system-users with + symbol in email
```
> [user-authn] fix: allow system-users with + symbol in email

- docs/site/LOCAL_DEV.md
Changed manual on how to install the documentation locally.
Solves the problem of incorrect installation of documentation via the werf compose up method in /docs/site .
```changes
section: docs
type: chore
summary: Changed the manual on how to install the documentation locally.
```
> [docs] Changed manual on how to run docs locally

- docs/site/_includes/getting_started/global/partials/select_revision.html.liquid
Added a warning about choosing the subnet dimension in Yandex Cloud.
```changes
section: docs
type: fix
summary: Added a warning about choosing the subnet dimension in Yandex Cloud.
```
> [docs] Add a warning about dimension of subnets in Yandex Cloud

- ee/candi/cloud-providers/openstack/layouts/standard/base-infrastructure/main.tf
- ee/candi/cloud-providers/openstack/layouts/standard/master-node/main.tf
- ee/candi/cloud-providers/openstack/layouts/standard/variables.tf
- ee/candi/cloud-providers/openstack/terraform-modules/master/main.tf
- ee/modules/040-terraform-manager/images/terraform-manager-openstack/patches/implement_openstack_compute_servergroup_v2_data_source.patch
- ee/modules/040-terraform-manager/images/terraform-manager-openstack/werf.inc.yaml
- Add patch to `terraform-provider-openstack` with `openstack_compute_servergroup_v2` data source implementation.
- Move `ServerGroup` creation to `base-infrastructure` step.
We only need one server group for all masters. If we try to create a server group at the `master-node` step, we will have multiple server groups.
```changes
type: fix
summary: Create one server group for all masters.
```
> [cloud-provider-openstack] Fix ServerGroup creation

- ee/candi/cloud-providers/vcd/openapi/cluster_configuration.yaml
- ee/candi/cloud-providers/vcd/openapi/doc-ru-cluster_configuration.yaml
Fixed broken links to VCDInstanceClass on VMware Cloud Director page.
Fixed broken links to VCDInstanceClass on VMware Cloud Director page, it opens without 404 error.
```changes
section: docs
type: fix 
summary: Fixed broken links to VCDInstanceClass on VMware Cloud Director page.
```
> [docs ] Fixed broken links to VCDInstanceClass on VMware Cloud Director page

- modules/140-user-authz/hooks/handle_manage_bindings.go
It provides fix for the rbacv2 hook.
The hook does not work correctly.
The hook creates RoleBindings with a Role instead of a ClusterRole.
The hook creates RoleBindings with a ClusterRole.
```changes
type: fix
summary: Fix rbacv2 hook.
```
> [deckhouse] fix rbacv2 hook

- docs/documentation/pages/installing/CONFIGURATION.md
- docs/documentation/pages/installing/CONFIGURATION_RU.md
Added a warning that we do not recommend changing ClusterConfiguration settings in a running cluster.
This solves the problem where users make changes in the ClusterConfiguration settings and the cluster fails.
Added a warning that we do not recommend changing ClusterConfiguration settings in a running cluster.
```changes
section: docs
type: chore
summary: Added a warning that we do not recommend changing ClusterConfiguration settings in a running cluster.
```
> [docs] Added a warning about changing ClusterConfiguration 

- candi/bashible/common-steps/all/098_set_permissions.sh.tpl
fix for this [pr](https://github.com/deckhouse/deckhouse/pull/9494)  exluded plugins folder
Stricter permissions (0700 for directories, 0600 for files) to all kubelet config files and PKI files. This is done to improve security.
These changes are needed to make the Kubernetes cluster more secure. With these permissions, only the necessary services and the root user can access important configuration files, reducing the risk of unauthorized access.
After these changes, the permissions on kubelet directories and files will be stricter—0700 for directories and 0600 for files. 
```changes
type: feature
summary: Stricter permissions (0700/0600) applied to kubelet configuration and PKI files to improve security.
impact: 
---
section: candi …
```
>  [candi] kubelet files strict permissions fx

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
The instructions for switching from EE redaction to CE and from CE to EE for releases 1.64 and 1.63 have been refactored.
```changes
section: docs
type: fix
summary: The instructions for switching from EE redaction to CE and from CE to EE for releases 1.64 and 1.63 have been refactored.
```
> [docs] Refactor EE to CE and CE to EE instructions in the FAQ page for 1.64 and 1.63 releases

- modules/302-vertical-pod-autoscaler/images/admission-controller/werf.inc.yaml
- modules/302-vertical-pod-autoscaler/images/recommender/werf.inc.yaml
- modules/302-vertical-pod-autoscaler/images/updater/werf.inc.yaml
- modules/302-vertical-pod-autoscaler/images/vertical-pod-autoscaler/patches/dep-upgrade.patch
- modules/302-vertical-pod-autoscaler/images/vertical-pod-autoscaler/patches/recommender.patch
- modules/302-vertical-pod-autoscaler/images/vertical-pod-autoscaler/werf.inc.yaml
> [vertical-pod-autoscaler] fix cve and build for cse edition

- modules/021-cni-cilium/images/agent/werf.inc.yaml
We replace the iptables-wrapper in the agent with one that we have built ourselves and make sure it is correctly installed in the pod.
In the previous version, the iptables-wrapper was not installed correctly in the pod. As a result, the iptables-legacy version was always used.
The pods of `cilium` correctly detect the iptables version and insert the rules into the appropriate tables.
```changes
type: fix
summary: iptables-wrapper fix for cilium pods
impact: The cilium pods will be restarted.
```
> [cni-cilium] iptables-wrapper fix

- .github/scripts/js/constants.js
- .github/workflow_templates/e2e.abort.multi.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vcd.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vcd.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
CI update to enable e2e testing with kubernetes version 1.31.
Make it possible to run e2e with kubernetes 1.31 for further testing.
```changes
section: ci
type: feature
summary: add Kubernetes 1.31 e2e tests.
```
> [ci] add k8s 1.31 e2e pipelines 

- docs/site/_includes/getting_started/openstack_vk/partials/config.ru.yml.standard.ee.inc
- docs/site/_includes/getting_started/openstack_vk/partials/config.yml.standard.ee.inc
Added a default name for externalNetworkName based on the SDN used in the project.
These changes are necessary for the convenience of users, enabling them to quickly set the externalNetworkName without needing to determine the specific naming for their SDN. This increases productivity and reduces the risk of configuration errors.
After applying these changes, the documentation will automatically include the default name for externalNetworkName based on the SDN used. Users can verify the updated documentation to see the specified default name.
```changes
section: docs
type: chore
summary: Add default name for externalNetworkName based on the SDN used in the project.
```
> [docs][getting started] add an explanation of externalNetworkName in VK Cloud

- modules/460-log-shipper/docs/EXAMPLES.md
- modules/460-log-shipper/docs/EXAMPLES_RU.md
Add CEF format example in [docs](https://deckhouse.ru/products/kubernetes-platform/documentation/v1/modules/460-log-shipper/examples.html#syslog) log-shipper
```changes
section: docs
type: fix
summary: Add CEF format example in docs log-shipper
```
> [docs] Add CEF format example in docs

- candi/openapi/doc-ru-init_configuration.yaml
- candi/openapi/init_configuration.yaml
- dhctl/README.md
- dhctl/pkg/config/base_test.go
- dhctl/pkg/config/deckhouse_config.go
- dhctl/pkg/config/deckhouse_config_test.go
- dhctl/pkg/config/module_config.go
- dhctl/pkg/config/module_config_test.go
- dhctl/pkg/config/types.go
- docs/documentation/pages/installing/README.md
- docs/documentation/pages/installing/README_RU.md
Remove support for deprecated `InitConfiguration.configOverrides` parameter.
Parameter `configOverrides` was deprecated since v1.54.
Close #6354.
```changes
section: dhctl
type: chore
summary: Remove support for deprecated 'InitConfiguration.configOverrides' parameter.
```
> [dhctl] del deprecated configOverrides

- ee/candi/cloud-providers/vcd/terraform-modules/master-node/main.tf
- ee/modules/040-terraform-manager/images/terraform-manager-vcd/patches/fix_getting_vcd_catalog_vapp_template_data_source_by_org_and_catalog_id.patch
- ee/modules/040-terraform-manager/images/terraform-manager-vcd/werf.inc.yaml
- Add patch to `terraform-provider-vcd` with fixes to `vcd_catalog_vapp_template` data source.
- Add `org` argument to `vcd_catalog_vapp_template` data source.
See https://github.com/vmware/terraform-provider-vcd/issues/1331.
```changes
type: fix
summary: Fix vcd catalogs sharing.
```
> [cloud-provider-vcd] Fix getting `vcd_catalog_vapp_template` data source by `org` and `catalog_id`

- modules/150-user-authn/images/dex/patches/static-user-groups.patch
When we added groups to users, we did not add groups when refreshing the token. As a result, the groups were not updated if the token was refreshed.
Fixed: #6928
When updating a token, the user's groups are updated
```changes
type: feature
summary: refresh groups on updating tokens
```
> [user-authn] feat: refresh groups on updating tokens

- modules/021-cni-cilium/templates/_agent-daemonset.tpl
- modules/021-cni-cilium/templates/agent/daemonset.yaml
- modules/021-cni-cilium/templates/agent/rbac-for-us.yaml
The Cilium agent process (a.k.a. DaemonSet) supports setting configuration on a per-node basis. 
This allows overriding module config for a node or set of nodes. It is managed by `CiliumNodeConfig` objects.
Warning: Creating or modifying a `CiliumNodeConfig` will not cause changes to take effect until agent pods are deleted and re-created (or their node is restarted).
Note: Currently it is possible to customize only two parameters — `debug` and `single-cluster-route`.
Currently, we are unable to configure `cilium-agents` individually on each node. We need the feature to configure the d8-virtualization powered nodes joined to the same cluster in future.
We can selectively enable or configure features for specific nodes.
```changes
type: feature
summary: Adding support …
```
> [cni-cilium] Adding support for setting configuration on a per-node basis.

- modules/110-istio/openapi/config-values.yaml
- modules/110-istio/openapi/doc-ru-config-values.yaml
- modules/110-istio/openapi/openapi-case-tests.yaml
- modules/110-istio/template_tests/module_test.go
Improved validation of the `spec.sidecar.resourcesManagement.static` parameter in istio ModuleConfig.
Onder-the-hood resource `IstioOperator` doesn't support the numberic resource specifications, it can handle only the string's. We decided to handle it by forbidding the numbering notation in ModuleConfig.
The values that you enter in `moduleConfig` do not cause errors in the Istio operation. If you enter an invalid value, you will immediately know about it before it is applied.
The consequences of wrong configuration aren't obvious, istio-operator just stops working and the logs aren't obvious.
```changes
section: istio
type: fix
summary: Improved validation of the ModuleConfig
```
> [istio] Improved resourceManagement validation in the ModuleConfig

- ee/modules/160-multitenancy-manager/templates/validation.yaml
We have a special [message](https://github.com/deckhouse/deckhouse/blob/c883118690704fd8082917a1e3fb827b4570427c/ee/modules/160-multitenancy-manager/templates/validation.yaml#L22) in case of violation of the policy but this not work
```shell
Error from server (Forbidden): namespaces "my-project-test01" is forbidden: ValidatingAdmissionPolicy 'd8-multitenancy-manager' with binding 'd8-multitenancy-manager' denied request: failed expression: request.userInfo.username == "system:serviceaccount:d8-system:deckhouse"
``` 
This is because the `namespace` resource does not have `object.metadata.namespace`
Changes add verify this
```changes
type: fix
summary: Add verify namespace object for messageExpression in ValidatingAdmissionPolicy
```
> [multitenancy-manager] Add verify namespace object for messageExpression in ValidatingAdmissionPolicy

- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/helm/main.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/manager/project/main.go
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/manager/project/utils.go
It provides fix to avoid the ```namespace not found``` problems.
Helm can try to install resources before install their namespace(this is just a theory, the root cause may be different), it causes the ```namespace not found``` problem.
Adding retry helps to avoid flaky helm errors.
```changes
type: fix
summary: Fix 'namespace not found' problem.
```
> [multitenancy-manager] fix namespace not found

- modules/150-user-authn/images/dex/Dockerfile
- modules/150-user-authn/images/dex/patches/bytes-and-string-certificates.patch
Allow to load certificates from bytes and strings
In cloud environments, for publically available values it is easier to specify the content of a public certificate in the config than mounting it to the container.
We can use certificates as base64 strings
```changes
type: feature
summary: dex support base64 encoded and PEM encoded certs
```
> [user-authn] feat: dex support base64 encoded and PEM encoded certs

- .github/ci_templates/e2e_tests.yml
- .github/workflow_templates/e2e.abort.multi.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vcd.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
Mistaken edit in #9947 broke e2e-abort completely. Fixed.
Incorrect edit broke the abort pipeline.
Working pipeline
```changes
section: ci
type: fix
summary: Fix incorrect keys in e2e-abort.
```
> [ci] Fix incorrect keys in e2e-abort

- candi/bashible/common-steps/node-group/004_resize_partitions.sh.tpl
Fix resize partition bashible step.
Fix an error in determining the partition number.
In cases with extended partition, bashible resize step does not work correctly.
```changes
section: candi
type: fix
summary: fix resize partition step
```
> [candi] fix resize partition step

- ee/modules/030-cloud-provider-openstack/templates/cloud-data-discoverer/pod-monitor.yaml
- ee/modules/030-cloud-provider-vcd/templates/cloud-data-discoverer/pod-monitor.yaml
- ee/modules/030-cloud-provider-vsphere/templates/cloud-data-discoverer/pod-monitor.yaml
- ee/modules/030-cloud-provider-zvirt/templates/cloud-data-discoverer/pod-monitor.yaml
- ee/modules/110-istio/templates/alliance/ingressgateway/podmonitor.yaml
- modules/030-cloud-provider-yandex/templates/cloud-data-discoverer/pod-monitor.yaml
- modules/110-istio/templates/cni/podmonitor.yaml
- modules/110-istio/templates/ingress-gateway-controller/podmonitor.yaml
Protect PodMonitor CRD usage
it doesn't work during the cluster bootstrap
```changes
section: cloud-provider-openstack,cloud-provider-vcd,cloud-provider-yandex,cloud-provider-vsphere,cloud-provider-zvirt,istio
type: fix
summary: Protect PodMonitor CRD usage with module dependency.
```
> Secure PodMonitor CRD usage

- ee/modules/160-multitenancy-manager/images/multitenancy-manager/cmd/main.go
It provides json formatted logs.
With the dev mode logs seems to be panic and cannot be collected in json format.
It helps to analyze logs.
Logs are in json format.
```changes
type: fix
summary: Change logs format to json format.
```
> [multitenancy-manager] json logs format

- testing/cloud_layouts/script.sh
Fixed missing backslash in testing script.
Missing backslash breaks test script for vCD.
Working vCD e2e test.
```changes
type: fix
summary: Fixed missing backslash in testing script.
```
> [testing] Fixed missing backslash in testing script

- modules/150-user-authn/crds/dex-provider.yaml
- modules/150-user-authn/crds/doc-ru-dex-provider.yaml
- modules/150-user-authn/openapi/values.yaml
- modules/150-user-authn/templates/dex/config.yaml
Add the new `claimMappingOverride` option that configures Dex's behavior.
With this option enabled, dex will use claims from claimMapping even if the token has a standard claim.
By default (when the option is disabled), dex tries to get the value of the default claim, e.g., email, and only if the claim is not present, falls back to claim mapping.
This is the case of one of our clients. They have no emails in tokens, but the email claim is present in the token and equals the `(unverified)` value, which does not work.
https://dexidp.io/docs/connectors/oidc/
```changes
type: feature
summary: Add claimMappingOverride option for OIDC Dex provider
```
> [user-authn] Add claimMappingOverride option

- deckhouse-controller/go-build.sh
- werf.yaml
Add new environment variable D8_VERSION, which contains tag, or commit reference name. 
In error cases, it will be still "dev".
Users can check current release of deckhouse-controller without checking git branch
```
/deckhouse $ deckhouse-controller version
deckhouse v1.63.7 (addon-operator v1.4.2, shell-operator v1.4.10, Golang go1.22.2)
```
```
/deckhouse $ deckhouse-controller version
deckhouse pr9964 (addon-operator v1.4.2, shell-operator v1.4.10, Golang go1.22.2)
```
```
/deckhouse $ deckhouse-controller version
deckhouse dev (addon-operator v1.4.2, shell-operator v1.4.10, Golang go1.22.2)
```
```changes
type: fix
summary: Users can check current release of deckhouse-controller
```
> [deckhouse-controller] fix deckhouse version

- candi/openapi/dhctl/ssh_configuration.yaml
- dhctl/pkg/config/connection_test.go
This pull request addresses a YAML specification error by correcting the type of the sshBastionPort field from int (which is not a valid type) to integer within the SSHConfig. This change ensures that the sshBastionPort is parsed correctly without any issues.
This change resolves a bug where the incorrect type definition for sshBastionPort in the YAML specification could lead to parsing errors. 
```changes
section: dhctl
type: fix
summary: Fix sshBastionPort spec type
```
> [dhctl] fix(dhctl-for-commander): fix sshBastionPort spec (int -> integer)

- modules/040-node-manager/hooks/set_instance_class_ng_usage.go
Updates the `set_instance_class_ng_usage.go` hook's structures to comprise only exporting fields.
Currently, `deckhouse-controller module snapshots node-manager` command causes a panic with the following stracktrace:
```
{"http_method":"GET","level":"info","msg":"complete","operator.component":"debugEndpoint","panic":"reflect.Value.Interface: cannot return value obtained from unexported field or method","resp_bytes_length":79581,"resp_elapsed_ms":215900,"resp_status":200,"stack": ...
```
Closes #9640 
The aforementioned command doesn't cause a panic and a listing of  the `node-manager` module's snapshots is provided.
```changes
type: chore
summary: Fix the module's snapshots debugging.
```
> [node-manager] fix the module's snapshots debugging

- modules/021-cni-cilium/images/agent/check-n-cleaning-iptables.sh
- modules/021-cni-cilium/images/agent/werf.inc.yaml
- modules/021-cni-cilium/templates/_agent-daemonset.tpl
The init-container for cilium-agent pod checks iptables-legacy for any unwanted rules and deletes them if found.
Previously, due to a configuration error, cilium-agent was always creating its rules in the iptables-legacy. 
The configuration error has now been fixed, and cilium-agent is creating its own rules in the correct table. 
However, previously created rules remain in the iptables-legacy table, even if the system is using iptables-nft.
Such behavior does not have a negative impact.
But having the rules in the wrong table can be confusing.
The rules created by the cilium-agent are present only in those iptables tables (nft or lagacy) that are used by the entire node.
```changes
type: fix
summary: wiping unwanted iptables-legacy rules
impact: All cilium-agent pods …
```
> [cni-cilium] wiping unwanted iptables-legacy rules

- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
- deckhouse-controller/pkg/controller/module-controllers/release/updater.go
- docs/documentation/_data/deckhouse-alerts.yml
- modules/340-monitoring-deckhouse/monitoring/prometheus-rules/alerting.yaml
If the module is set to manual installation mode, we need to approve its installation when a new version appears.
In order to know that a new version has appeared and that we need to check and approve these changes, we need to add an alert to Prometheus.
If the cluster contains modules that require confirmation of installation, then when a new version appears, an alert will appear in Prometheus.
```changes
type: feature
summary: adding an alert that manual confirmation is required to install mr
```
> [deckhouse-controller] feat: adding an alert that manual confirmation is required to install mr

- docs/documentation/_data/sidebars/main.yml
- docs/site/_config.yml
Added deprecated alert at ceph-csi module.
```changes
type: feature
summary: Make ceph-csi module deprecated.
```
> [ceph-csi] Make ceph-csi module deprecated

- candi/bashible/common-steps/node-group/051_pull_and_configure_kubernetes_api_proxy.sh.tpl
Pull kubernetes-api-proxy image before apply static manifest to not timeout when registry for image was changed and pod was redeployed
this allow to not timeout and wait pull image when kubernetes-api-proxy pod was redeployed
kubernetes-api-proxy pod was redeployed and run immediately
```
section: dhctl
type: fix
summary: Add cache image kubernetes-api-proxy to not pull image when registry for image was changed
```
> [dhctl] Add cache image kubernetes-api-proxy to not pull image when registry for image was changed

- docs/site/_includes/getting_started/openstack_vk/partials/config.ru.yml.standard.ee.inc
- docs/site/_includes/getting_started/openstack_vk/partials/config.yml.standard.ee.inc
- docs/site/_includes/getting_started/openstack_vk/partials/resources.yml.minimal.inc
Actual flavor for VKCloud and adjust rootDiskSize.
Flavor `Standard-4-8-80` is legacy for VKCloud.
Also increase `rootDiskSize` to 50G, because with 40G we have error in dhctl like this:
```
Installation aborted: Timeout while "Checking cloud master node system requirements are met": last error: Root disk capacity: expected at  ↵
least 50, but 40 is configured
Please fix this problem or skip it if you're sure with preflight-skip-system-requirements-check flag
```
```changes
section: docs
type: chore
summary: Actual flavor for VKCloud and adjust rootDiskSize.
```
> [docs][getting_started] Actual flavor for VKCloud and adjust rootDiskSize

- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/auto-deploy-patch-release-in-manual-mode.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/auto-patch-mode-minor-release.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/manual-approval-mode-is-set.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/manual-approval-mode-with-canary-process.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/manual-mode.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/pending-manual-release-on-cluster-bootstrap.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/second-run-of-the-hook-in-a-manual-mode-should-not-change-state.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/unknown-mode-minor-release.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/pending-manual-release-on-cluster-bootstrap.yaml
- docs/documentation/pages/module-development/RUN.md
- docs/documentation/pages/module-development/RUN_RU.md
- go_lib/updater/updater.go
Change manual approve message
It would be printed even for AutoPatch release. So we have to change it.
```
v1.64.1    Pending      90s              Waiting for manual approval
```
```
v1.64.1    Pending      90s              Waiting for the 'release.deckhouse.io/approved: "true"' annotation
```
```changes
type: fix
summary: Change release approval message
```
> [deckhouse-controller] change release approval message

- modules/402-ingress-nginx/templates/controller/admission.yaml
Add matchConditions in validating webhook to filter requests by spec.ingressClassName according to controller ingressClass field
It should ease the load on ingress nginx controllers in a situation when there are multiple ingress nginx controllers of different ingress classes in the cluster.
When we create new Ingress resource in cluster with spec.insgressClassName field not equal to controller spec.ingressClass - controller did not receive this request.
```changes
type: fix
summary: minor speed up for ingress validating
```
> [ingress-nginx] Add matchConditions in validating webhook to filter requests by spec.ingressClassName

- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/kubernetes/actions/converge/lock.go
- dhctl/pkg/kubernetes/actions/converge/master_node_group_controller.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
Fix lease locking.
`dhctl` immediately locks and unlocks lease.
```changes
section: dhctl
type: fix
summary: Fix lease locking.
```
> [dhctl] Fix lease locker

- docs/documentation/werf.yaml
- modules/810-documentation/images/web/werf.inc.yaml
Fix documentation build.
```changes
section: docs
type: fix
summary: Fix documentation build.
```
> [docs] fixed build in shell

- candi/bashible/common-steps/all/098_set_permissions.sh.tpl
fix for this [pr](https://github.com/deckhouse/deckhouse/pull/9494)  exluded plugins folder
Stricter permissions (0700 for directories, 0600 for files) to all kubelet config files and PKI files. This is done to improve security.
These changes are needed to make the Kubernetes cluster more secure. With these permissions, only the necessary services and the root user can access important configuration files, reducing the risk of unauthorized access.
After these changes, the permissions on kubelet directories and files will be stricter—0700 for directories and 0600 for files. 
```changes
section: candi
type: feature
summary: Stricter permissions (0700/0600) applied to kubelet configuration and PKI files to improve security.
impact: 
```
> [candi] kubelet files strict permissions fix

- modules/800-deckhouse-tools/images/web/static/tools.json
Correct the link for d8-cli for windows in deckhouse-tools web, add extension of file in link
The d8-cli has a name d8.exe , but the extension was not specified in the incorrect link, so it was impossible to download the file.
We need a valid download link for d8-cli for windows.
We have correctly link for download d8-cli for windows. We don't get a 404 response.
```changes
section: deckhouse-tools 
type: fix 
summary: Corrected the link to d8-cli for windowsOS, add a extension of file to link&
```
> [deckhouse-tools] Correct the link for d8-cli for windows

- docs/documentation/pages/module-development/DEVELOPMENT.md
- docs/documentation/pages/module-development/DEVELOPMENT_RU.md
Fixed incorrect spelling of the command at ModulePullOverride.
```changes
section: docs
type: fix
summary: Fixed incorrect spelling of the command at ModulePullOverride.
```
> [docs] Fixed command at ModulePullOverride

- go_lib/cloud-data/reconciler.go
add probe to the cloud-data reconciler
Some clients have cloud-data-discoverer hangs.
When cloud-data-discoverer hangs, it should restart itself
```changes
type: fix
summary: add probe to the cloud-data reconciler
```
> [go_lib] add probe to the cloud-data reconciler

- modules/040-control-plane-manager/images/etcd/patches/000_etcdctl-snapshot-pipe.patch
- modules/040-control-plane-manager/images/etcd/werf.inc.yaml
Added a etcd patch based on https://github.com/etcd-io/etcd/pull/16243 to allow backups of etcd via Deckhouse CLI from our distroless-based etcd images.
Related PR's:
* https://github.com/deckhouse/deckhouse/pull/10014
* https://github.com/deckhouse/deckhouse-cli/pull/46
This allows to properly implement etcd backup in Deckhouse CLI.
```changes
type: feature
summary: patch etcd to support outputting of snapshots to stdout
```
> [control-plane-manager] patch etcd to support outputting of snapshots to stdout

- dhctl/pkg/system/node/local/command_test.go
- dhctl/pkg/system/node/local/script_test.go
Skipped some flaky tests of local cmd executor that randomly fail due to data race.
This code is the reason our pipelines randomly fail from time to time and it has become an obvious pain point. This PR will adress that until a proper fix is implemented.
No changes in behaviour of deckhouse, local executor is not used anywhere
```changes
section: dhctl
type: chore
summary: Skip flaky tests for unused code
```
> [dhctl] Skip flaky tests for unused code

- modules/150-user-authn/images/dex/web/templates/password.html
Trim space for username on the dex login form
User can copy email with spaces and it will lead to the error. Also, visually it's hard to find prefix/suffix space in the form.
Before:
After:
```changes
type: fix
summary: Trim spaces from email field on the login form.
```
> [user-authn] Trim user email on dex auth form

- go_lib/registry-packages-proxy/proxy/proxy.go
Edit log message for received params and add log with success message for sending package
Improve dhctl UX
```changes
section: dhctl
type: chore
summary: Grooming logs for dhctl
```
> [registry-packages-proxy] Grooming logs for dhctl

- dhctl/pkg/kubernetes/actions/resources/resources.go
- dhctl/pkg/template/resources.go
Fix ensure required namespaces logic. 
Now we do not return `ErrNotAllResourcesCreated` if one resource does not have existing namespace.
Resources will be skipped as long as no namespace is created (either by the resource list or by the deckhouse controller)
Affect DKP >=1.63
Creating resources fail with timeout error
Creating resources fail with timeout error
```changes
section: dhctl
type: fix
summary: Fix ensure required namespaces
```
> [dhctl] Fix ensure required namespaces

- modules/040-node-manager/crds/nodeuser.yaml
- modules/140-user-authz/crds/clusterauthorizationrule.yaml
- modules/150-user-authn/crds/dex-authenticator.yaml
- modules/150-user-authn/crds/dex-client.yaml
- modules/150-user-authn/crds/dex-provider.yaml
- modules/150-user-authn/crds/user.yaml
- modules/300-prometheus/crds/customprometheusrules.yaml
- modules/300-prometheus/crds/grafanaadditionaldatasources.yaml
- modules/300-prometheus/crds/grafanadashboarddefinition.yaml
- modules/300-prometheus/crds/prometheusremotewrite.yaml
- modules/301-prometheus-metrics-adapter/crds/clusterpodmetrics.yaml
- modules/302-vertical-pod-autoscaler/crds/verticalpodautoscaler.yaml
- modules/302-vertical-pod-autoscaler/crds/verticalpodautoscalercheckpoint.yaml
- modules/500-upmeter/crds/upmeterremotewrite.yaml
Mark old api as deprecated.
```changes
---
type:  chore
summary: marked the old api *.deckhouse.io as deprecated
---
type:  chore
summary: marked the old api *.deckhouse.io as deprecated
---
type:  chore
summary: marked the old api *.deckhouse.io as deprecated
---
type:  chore
summary: marked the old api *.deckhouse.io as deprecated
---
type:  chore
summary: marked the old api *.deckhouse.io as deprecated
---
type:  chore
summary: marked the old api *.deckhouse.io as deprecated
```
> [many] marked the old api *.deckhouse.io as deprecated

- dhctl/pkg/kubernetes/actions/resources/resources.go
- dhctl/pkg/log/logger.go
Fix panic during creation resources and add timestamps to debug log
Affect DKP >= 1.64
Bootstrap can fail with panic.
Improve debug information.
Bootstrap can fail with panic.
```changes
section: dhctl
type: fix
summary: Fix panic during creation resources and add timestamps to debug log
```
> [dhctl] Fix panic during creation resources and add timestamps to debug log

- candi/bashible/openapi.yaml
- ee/modules/030-cloud-provider-openstack/candi
- ee/modules/030-cloud-provider-vsphere/candi
- modules/040-node-manager/template_tests/module_test.go
- modules/040-node-manager/template_tests/standby_node_test.go
Deny to use cri type Docker in field defaultCRI in cluster configuration on bootstrap deckhouse .
this allow to deny use Docker cri type when field defaultCRI  is prompt as Docker.
if Docker cri type is prompt as defaultCRI stderr output is "defaultCRI should be one of [Containerd NotManaged]".
```changes
section:  dhctl
type: fix
summary: Deny use defaultCRI type as Docker 
```
> [dhctl] Deny use defaultCRI type as Docker 

- candi/cloud-providers/yandex/terraform-modules/static-node/main.tf
- candi/cloud-providers/yandex/terraform-modules/static-node/variables.tf
Updated the terraform module for the `static-node` resource in Yandex Cloud. Previously, the `diskType` parameter was hard-coded, but now it can be configured dynamically.
An missed revision that should have been included in the PR #8384 
The hard-coded `diskType` parameter limited the flexibility of our infrastructure as code implementations. 
After applying these changes, users will be able to define the `diskType` parameter for the `static-node` resource in the terraform module according to their specific requirements. 
```changes
type: fix 
summary: Fix hardcoded `diskType` parameter in `static-node`
```
> [cloud-provider-yandex]  Fix hardcoded `diskType` parameter in `static-node`

- modules/040-node-manager/templates/standby-holder/deployment.yaml
Disabled the alert for `standby-holder-nodes` as it was generating unnecessary noise. It is recommended to use `d8_node_group-*` metrics for nodeGroup monitoring.
Fixes the issue of unnecessary alerts when the node group reaches maximum capacity.
The alert for `standby-holder-nodes` will no longer trigger when the node group reaches maximum capacity.
section: node-manager  
type: fix  
summary: "Disabled unnecessary alert for `standby-holder-nodes` when node group reaches maximum capacity."  
> disable extended monitoring for standby-holder

- dhctl/pkg/config/meta.go
- dhctl/pkg/config/validation.go
Different cloud providers have different restrictions on resource names (instances, networks, etc.). In this case we added validation for YandexCloud.
This is not a complete solution because we cannot accurately validate the length of the claud resource name, which is the length of the prefix and the name, e.g. `bob-yc-9858` + `-master-` + `1`.
terraform-provider-yandex has validation for some resources, but not for all, for example here: https://github.com/yandex-cloud/terraform-provider-yandex/blob/9a7e19d14e32a9d5e05ff349afbc3ba2d60bb46e/yandex/resource_yandex_smartcaptcha_captcha.go#L92
Similar issue:
https://github.com/yandex-cloud/terraform-provider-yandex/issues/353#issuecomment-1614502414
At the moment we don't do prefix validation, based on which we then create cloud resources …
> [dhctl] Add validation rules for ClusterConfiguration.cloud.prefix specific to cloud providers

- modules/300-prometheus/templates/grafana/deployment-v10.yaml
Change grafana server root url to https://grafana.%publicDomainTemplate%
The `GF_SERVER_ROOT_URL` environment variable was left intact by a mistake while switching Grafana v10 to the default domain. This leads us to several problems, e.g.: Grafana generates the wrong URL for chart snapshots.
It would be nice to have this fix in any upcoming hotfix release to improve user experience.
Chart snapshots are generated with the correct URL: https://grafana.%publicDomainTemplate%
```changes
type: fix
summary: Fix Grafana root URL
impact: Grafana deployment will be rollout restarted due to environment variable change
```
> [prometheus] Fix Grafana server root URL

- ee/be/candi/bashible/bundles/altlinux/all/000_fix_udev_xgrp_error.sh.tpl
AltLinux 11 bootstrap process may experience a udev-related error when running apt-get install or apt-get remove commands. This error leads to a dramatic increase in apt-get's runtime, extending it by 5 to 10 times. 
This solves the timeout problem in the AltLinux 11 node bootstrap process. 
bashible creates the `xgrp` system group if it is specified in the udev config but is not present on the system. As a result, the system stops slowing down.
```changes
section: candi
type: fix 
summary: fix AltLinux 11 bootstrap ( udev error )
impact: 
```
> [candi] fix AltLinux 11 bootstrap ( udev error )

- candi/openapi/cluster_configuration.yaml
- candi/openapi/doc-ru-cluster_configuration.yaml
This PR adds a cross-reference for the `clusterDomain` parameter in the description to a section with recommendations on changing the value in a working cluster. 
This improves the ease of finding necessary information and enhances the user experience.
Previously, the mentioned section was not logically placed, making it difficult for users to locate it. 
This upgrade eases the navigation within the documentation and heightens its user-friendliness. 
```changes
section: docs
type: fix 
summary: Add link to description of clusterDomain parameter.
```
> [docs] Added link to description of clusterDomain parameter

- deckhouse-controller/pkg/debug/debug.go
- modules/002-deckhouse/docs/FAQ.md
- modules/002-deckhouse/docs/FAQ_RU.md
Update the documentation about the list of data the `collect-debug-info` command collects.
Brought the documentation up to date with the actual behavior.
```changes
type: fix
summary: Update the documentation about the list of data the `collect-debug-info` command collects.
```
> [deckhouse-controller] updated the documentation with the latest changes to the collect-debug-info command

- modules/300-prometheus/hooks/deprecate_outdated_grafana_dashboard_crd.go
- modules/300-prometheus/hooks/deprecate_outdated_grafana_dashboard_crd_test.go
Fix stuck GrafanaDashboardDeprecation alerts
Outdated grafana dashboard deprecation metrics must expire on hook start to resolve already deleted/fixed dashboards
GrafanaDashboardDeprecation alerts being auto-resolved within hook launch interval `1 hour` when required changes applied to existing dashboards
```changes
type: fix
summary: Fix stuck GrafanaDashboardDeprecation alerts
```
> [prometheus] Fix stuck GrafanaDashboardDeprecation alerts

- modules/300-prometheus/images/grafana-v10/grafana_home_dashboard.json
- modules/300-prometheus/images/grafana/grafana_home_dashboard.json
I have made a few changes in the `Controllers` panel in our Grafana home dashboard.
Previously, it was showing the number of pods managed by each controller type instead of the number of each controller type present. 
I have corrected this and now the dashboard shows accurate data: the amount of each type of controllers.
This change is important to get an accurate overview of the controllers present in our system. 
The previous misrepresentation might have led to confusion or misguided decisions. 
Now the dashboard will reflect the true state of our cluster by portraying the correct number of each type of controllers.
After the implementation of these changes, the `Controllers` panel in our Grafana home dashboard should provide a correct count of each type of controllers. 
```changes …
```
> [monitoring] Fix grafana home dashboard, panel `Controllers`

- modules/030-cloud-provider-yandex/images/yandex-csi-plugin/werf.inc.yaml
Add support a hybrid cluster in yandex CSI driver
In a hybrid cluster, the yandex CSI driver crashes with an error after startup
All functions of the Yandex CSI driver are functional in hybrid cluster
```changes
type: fix
summary: Add support a hybrid cluster in yandex CSI driver
```
> [cloud-provider-yandex] yandex csi add support hybrid cluster

- modules/021-cni-cilium/images/base-cilium-dev/werf.inc.yaml.txt
Disabling the upload of the service image `base-cilium-dev` to the final container registry.
`base-cilium-dev` is a service build image and it should not be included in the final container registry.
There should be no service images in the final container registry.
There should be no service images in the final container registry.
```changes
type: fix
summary: Disabling the upload of the service image `base-cilium-dev` to the final container registry.
impact: All cilium-agent pods will be restarted.
```
> [cni-cilium] Disabling the upload of the service image base-cilium-dev to the final container registry. cherry-pick to release-1.64

- modules/021-cni-cilium/images/agent/check-n-cleaning-iptables.sh
- modules/021-cni-cilium/images/agent/werf.inc.yaml
- modules/021-cni-cilium/templates/_agent-daemonset.tpl
The init-container for cilium-agent pod checks iptables-legacy for any unwanted rules and deletes them if found.
Previously, due to a configuration error, cilium-agent was always creating its rules in the iptables-legacy. 
The configuration error has now been fixed, and cilium-agent is creating its own rules in the correct table. 
However, previously created rules remain in the iptables-legacy table, even if the system is using iptables-nft.
Such behavior does not have a negative impact.
But having the rules in the wrong table can be confusing.
The rules created by the cilium-agent are present only in those iptables tables (nft or lagacy) that are used by the entire node.
```changes
type: fix
summary: wiping unwanted iptables-legacy rules
impact: All cilium-agent pods …
```
> [cni-cilium] wiping unwanted iptables-legacy rules. cherry-pick to release-1.64

- ee/modules/160-multitenancy-manager/images/multitenancy-manager/default/default.yaml
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/default/secure-with-dedicated-nodes.yaml
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/default/secure.yaml
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/helm/testdata/default_case/template.yaml
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/helm/testdata/secure_case/template.yaml
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/helm/testdata/secure_with_dedicated_node_case/resources.yaml
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/helm/testdata/secure_with_dedicated_node_case/template.yaml
- ee/modules/160-multitenancy-manager/images/multitenancy-manager/pkg/helm/testdata/without_ns_case/template.yaml
- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
It provides fix for incorrect prometheus labels in templates.
NetworkPolicy`s PodSelector in project templates does not work correctly for prometheus pods because they have another label.
NetworkPolicy`s PodSelector in project templates works correctly.
```changes
type: fix
summary: Fix prometheus labels for ingress traffic in Project templates.
```
```changes
type: fix
summary: Fix labels for prometheus pod antiAffinity.
```
> [multitenancy-manager] fix prometheus labels

- docs/documentation/_data/deckhouse-alerts.yml
- tools/helm_generate/runners/alert_templates/alert_templates.go
- tools/helm_generate/runners/alert_templates/template_values/340-monitoring-kubernetes.yaml
Render alerts in subdirectories of the `prometheus-rule` directory of a module.
Alerts in subdirectories of the `prometheus-rule` directory were not rendered. The PR fix alerts renderer to render all the DKP alerts, to display them on the site.
```changes
section: docs
type: fix
summary: Render missed DKP alerts in the documentation.
---
section: tools
type: fix
summary:  Fix alert rendering. Render alerts in subdirectories.
```
> [docs] Fix alert rendering. Render alerts in subdirectories

- dhctl/pkg/kubernetes/actions/manifests/manifests.go
- modules/002-deckhouse/templates/deployment.yaml
Add "kubectl.kubernetes.io/default-container" annotation to pod template in deploy/deckhouse.
kubectl exec/logs always prints "Defaulted container" when Pod has more than 1 container. Annotation "kubectl.kubernetes.io/default-container" helps to point kubectl to the default container in the Pod.
```
deckhouse-controller version
Defaulted container "deckhouse" out of: deckhouse, kube-rbac-proxy, init-downloaded-modules (init) 
deckhouse main (addon-operator v0.0.0-20241003110303-48341ac02dda, shell-operator v1.4.12, Golang go1.22.2)
-p '{"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/default-container":"deckhouse"}}}}}'
deployment.apps/deckhouse patched
deckhouse-controller version
deckhouse main (addon-operator v0.0.0-20241003110303-48341ac02dda, shell-operator …
```
> [deckhouse] chore: get rid of annoying "defaulted container" message

- modules/110-istio/templates/kiali/rbac-for-us.yaml
Add Kiali permissions to Prometheus to receive and display metrics.
- Kiali WEB-interface does not display metrics.
- There are errors in the logs:
```json
{"level":"error","time":"2024-10-15T11:41:18Z","message":"Failed to fetch Prometheus configuration: client_error: client error: 403"}
{"level":"error","time":"2024-10-15T11:41:18Z","message":"Failed to fetch Prometheus flags: client_error: client error: 403"}
```
Metrics in Kiali are displayed correctly.
```changes
section: istio
type: fix
summary: Fixed metrics display issue in Kiali.
```
> [istio] Fix metrics display issue in Kiali

- modules/007-registrypackages/images/crictl/werf.inc.yaml
- modules/007-registrypackages/images/kubernetes-cni/patches/cni-plugins/001-go-mod.patch
- modules/007-registrypackages/images/kubernetes-cni/patches/cni-plugins/README.md
- modules/007-registrypackages/images/kubernetes-cni/patches/plugins/001-go-mod.patch
- modules/007-registrypackages/images/kubernetes-cni/patches/plugins/README.md
- modules/007-registrypackages/images/kubernetes-cni/werf.inc.yaml
- modules/007-registrypackages/images/toml-merge/werf.inc.yaml
- modules/402-ingress-nginx/images/kruise/patches/00-gomod.patch
- modules/402-ingress-nginx/images/kruise/werf.inc.yaml
Fix cve's in images:
- registrypackages/kubernetes-cni-1-4-0
- registrypackages/crictl-1-31-1
- registrypackages/toml-merge-0-1
- ingress-nginx/kruise
```changes
```
> [cse] fix cve in ingress kruise/registrypackages

- deckhouse-controller/crds/module-config.yaml
- deckhouse-controller/crds/module-source.yaml
- deckhouse-controller/crds/module-update-policy.yaml
- ee/modules/160-multitenancy-manager/crds/projects.yaml
- ee/modules/160-multitenancy-manager/crds/projecttemplate.yaml
- ee/modules/650-runtime-audit-engine/crds/falco-audit-rules.yaml
- modules/015-admission-policy-engine/crds/operation-policy.yaml
- modules/015-admission-policy-engine/crds/security-policy.yaml
- modules/101-cert-manager/crds/crd-clusterissuers.yaml
- modules/101-cert-manager/crds/crd-issuers.yaml
- modules/140-user-authz/crds/authorizationrule.yaml
- modules/140-user-authz/crds/clusterauthorizationrule.yaml
- modules/150-user-authn/crds/dex-authenticator.yaml
- modules/150-user-authn/crds/dex-provider.yaml
- modules/150-user-authn/crds/group.yaml
- modules/150-user-authn/crds/user.yaml
- modules/402-ingress-nginx/crds/ingress-nginx.yaml
- modules/460-log-shipper/crds/cluster-log-destination.yaml
- modules/460-log-shipper/crds/cluster-logging-config.yaml
- modules/460-log-shipper/crds/pod-logging-config.yaml
Added backup.deckhouse.io/cluster-config label to Deckhouse CRD
Close https://github.com/deckhouse/deckhouse/issues/10091
```changes
type: feature
summary: Added backup.deckhouse.io/cluster-config label to Deckhouse CRD
```
> [deckhouse-controller] Added backup.deckhouse.io/cluster-config label to Deckhouse CRD

- modules/002-deckhouse/templates/webhook-handler/deployment.yaml
Fix RollingUpdate strategy for deployment.apps/webhook-handler.
Right now we use this strategy for `deployment.apps/webhook-handler` ( configuration is enabled only for deckhouse in ha mode)
```
{{- if (include "helm_lib_ha_enabled" .) }}
strategy:
type: RollingUpdate
rollingUpdate:
maxSurge: 0
maxUnavailable: 1
{{- end }}
```
We also use the affinity settings for this deployment.
When HA mode is disabled, maxSurge is reset to default settings. As a result, we have two replicasets at the moment. The old one with affinity settings, the new one without affinity. The new replicasets can't start, because affinity from the old replicasets prevents it, the old one can't terminate because of maxSurge.
After reducing number of masters from 3 to 1 we have a hung webhook-handler deployment.
After …
> [webhook-handler] Cannot replace the webhook-handler pod after several control-plain nodes have converged into one

- modules/300-prometheus/templates/prometheus/alert-relable-secret.yaml
- modules/300-prometheus/templates/prometheus/prometheus-external-labels-alert-relabel-secret.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Move externalLabels to remote_write and additionalAlertRelabelConfigs sections
When scraping metrics via the Federation API, labels from externalLabels are being added, which makes the series in long-term storage and regular Prometheus different. This behavior seems unclear, and we need the ability to control it.
We don't
When scraping metrics from long-term storage, labels from the externalLabels field will not be present in the response. However, when scraping from a regular Prometheus instance, these labels are included.
```changes
type: chore
summary: move externalLabels to remoteWrite section
```
> [prometheus] move externalLabels to remoteWrite and additionalAlertRelabelConfigs sections

- dhctl/pkg/operations/bootstrap/steps.go
- dhctl/pkg/system/node/ssh/cmd/scp.go
- dhctl/pkg/system/node/ssh/frontend/file.go
1. Add explicit preserve flag `WithPreserve(true)` for uploading files via SCP
2. Add full declaration of SSH reverse tunnel for registry-packages-proxy `-R bind_address:port:host:hostport`
1. Using SCP via teleport doesn't preserve file permissions, although plain scp preserves them by default. Setting -p explicitly fixes this
2. Same thing with reverse tunnel, if bind address is not declared tunnel is broken if connected via teleport (connections from remote host are `refused`)
These fixes allow for bootstrapping cluster using teleport, you also have to build `install` image with teleport on top using Dockerfile, and mount appropriate catalogues and ssh-agent socket when launching install container.
Also these fixes increase general robustness of bootstrap process
```changes
section: …
```
> [dhctl] Fixes for teleport

- testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml
- testing/cloud_layouts/Static/infra.tpl.tf
Move static tests to the separate `deckhouse-e2e-tests` project on the cloud provider.
Isolate DVP and DKP stands
```changes
type: feature
summary: Move static tests to the separate `deckhouse-e2e-tests` project on the cloud provider.
```
> [testing] Move static e2e tests to the separate cloud provider project

- docs/documentation/_data/sidebars/main.yml
- docs/site/_config.yml
Added experimental alert at static-routing-manager module.
```changes
section: docs
type: fix
summary: Added experimental alert at static-routing-manager module.
```
> [docs] Added experimental alert at static-routing-manager module

- modules/110-istio/templates/kiali/rbac-for-us.yaml
This PR focuses on optimizing and refactoring the existing RBAC rules by consolidating duplicate entries that granted the same permissions to overlapping resources. The rules have been streamlined to improve readability and maintainability while aligning with current Kubernetes API groups.
This change reduces redundancy in the RBAC configuration, minimizing complexity and improving future maintenance. The refactor ensures a more efficient and understandable access control policy, reducing the likelihood of errors or confusion.
- RBAC rules do not contain duplicates.
- Split rules are organized into groups.
- The formalization of rules follows the YAML format.
```changes
section: istio
type: chore
```
> [istio] Optimize the Kiali RBAC rules

- tools/kind-d8.sh
- Added a check condition to construct correct base64 arguments on different platforms
- Fix ubuntu/debian detection for lowercase distribution names
Base64 program versions for macOS  and Linux take different arguments. I've added a check condition to fix following error when installing from macOS:
```
base64: invalid option -- w
```
```changes
type: fix
summary: Fixes for Kind Getting Started EE installation.
```
> [kind] Accomodate for base64 BSD/Linux differences

- tools/kind-d8.sh
This PR removed all CRD MCs from kind script: https://github.com/deckhouse/deckhouse/pull/9593/files
But, we use `kind-d8.sh` directly from main in [our Getting Started](https://deckhouse.ru/products/kubernetes-platform/gs/kind/step2.html), so we need to return CRD ModuleConfigs until 1.65 release hits Stable
Currently kind-d8.sh script is broken, until 1.65 on Stable
We only need this during 1.64 release. After 1.65 hits Stable, this changes should be removed.
```changes
type: fix
summary: Fix kind installation on v1.64
```
> [kind] Enable *-crd modules for 1.64

- candi/control-plane-kubeadm/config.yaml.tpl
- candi/control-plane-kubeadm/patches/kube-apiserver.yaml.tpl
- modules/040-control-plane-manager/openapi/config-values.yaml
- modules/040-control-plane-manager/openapi/doc-ru-config-values.yaml
- modules/042-kube-dns/docs/FAQ.md
- modules/042-kube-dns/docs/FAQ_RU.md
Updating documentation  and  kubeadm config for seamless `clusterDomain` swapping
The current instruction to change the `clusterDomain` may cause short-term cluster issues. The updated instruction allows you to do this seamlessly without downtime, as described here:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#serviceaccount-token-volume-projection
> You can specify the --service-account-issuer argument multiple times, this can be useful to enable a non-disruptive change of the issuer. When this flag is specified multiple times, the first is used to generate tokens and all are used to determine which issuers are accepted. You must be running Kubernetes v1.22 or later to be able to specify --service-account-issuer multiple times.
You can specify an …
> Changing clusterDomain without downtime

- modules/002-deckhouse/templates/validation.yaml
Fix ValidatingAdmissionPolicy for checking update windows
If windows fields is empty slice it gives false negative
Avoid false negative check
```yaml
metadata:
name: deckhouse
spec:
settings:
update:
mode: AutoPatch
windows:
- from: "11:00"
to: "12:00"
- from: "15:23"
to: "12:13"
version: 1
```
```console
kubectl apply -f wrong-window.yaml
Error from server (Forbidden): error when creating "wrong-window.yaml": moduleconfigs.deckhouse.io "deck" is forbidden: ValidatingAdmissionPolicy 'update-windows.deckhouse.io' with binding 'update-windows.deckhouse.io' denied request: Invalid update windows. Start time (windows.from) should be less than the end time of the update window (windows.to)
```
---
```yaml …
```
> [deckhouse] Fix update windows validation policy

- dhctl/pkg/kubernetes/actions/resources/resources.go
- testing/cloud_layouts/AWS/WithoutNAT/resources.yaml
- testing/cloud_layouts/Azure/Standard/resources.yaml
- testing/cloud_layouts/EKS/WithoutNAT/resources.yaml
- testing/cloud_layouts/GCP/WithoutNAT/resources.yaml
- testing/cloud_layouts/OpenStack/Standard/resources.yaml
- testing/cloud_layouts/Static/resources.tpl.yaml
- testing/cloud_layouts/VCD/Standard/resources.tpl.yaml
- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/resources.yaml
- testing/cloud_layouts/vSphere/Standard/resources.yaml
Fix only one resource will create for namespace if it namespace does not exist
Affect DKP == 1.64.3
Fix https://github.com/deckhouse/deckhouse/pull/9714
When multiple resources will be created in namespace (which will be created in resources.yaml), we wait namespace creation only one firs resource. Another resources will skip by bug in the code 
Cannot create all resources by resources.yaml
```changes
section: dhctl
type: fix
summary: Only one resource will create for namespace if it namespace does not exist.
```
> [dhctl] Fix only one resource will create for namespace if it namespace does not exist

- testing/cloud_layouts/Static/infra.tpl.tf
- testing/cloud_layouts/Static/resources.tpl.yaml
- testing/cloud_layouts/Static/rosa-instance-bootstrap.sh
- testing/cloud_layouts/script.sh
Add ROSA Linux worker for e2e
Adding RosaOS for e2e tests
E2e tests use RosaOS
Add ROSA Linux worker for e2e
```changes
type: chore
summary: Add ROSA Linux worker for e2e.
```
> [chore] Add ROSA Linux worker for e2e

- dhctl/pkg/kubernetes/actions/deckhouse/install.go
After this pull request https://github.com/deckhouse/deckhouse/pull/9263 deckhouse can create deckhouse release firstly and bootstrap process will fail with error.
Bootstrap process can fail with error.
Bootstrap process can fail with error.
```changes
section: dhctl
type: fix
summary: Do not return error if deckhouse release exists.
```
> [dhctl] Do not return error if deckhouse release exists

- docs/site/js/customscripts.js
Fix second level topnav menu for GS and guides sections on the site.
```changes
section: docs
type: chore
summary: Fix second level topnav menu for GS and guides sections on the site.
```
> [docs] Fix second level topnav menu for GS and guides sections

- .github/ci_templates/web.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- tools/doc_check_links.sh
Fixed doc_check_links and web.yml file, now link linter does not process alerts and other unnecessary pages.
```changes
section: docs
type: fix 
summary: Fix documentation links checker.
```
> [docs][testing] Fix documentation links checker

- go_lib/dependency/requirements/requirements.go
Mechanism to check that some modules are disabled be update the Deckhouse release
We have to delete some modules but it should be expectedly by user
Linked with https://github.com/deckhouse/deckhouse/pull/10177
```console
NAME      PHASE     TRANSITIONTIME   MESSAGE
v1.65.0   Pending   2s               "disabledModules" requirement for DeckhouseRelease "1.77.0" not met: "delivery" module(s) have to be disabled
```
```changes
type: feature
summary: Add mechanism to check that desired modules are disabled before deckhouse update.
```
> [deckhouse-controller] Add requirements key for desired disabled modules

- tools/kind-d8.sh
Patch `kubelet-eviction-thresholds-exporter` container in `node-exporter` daemonset with variable `EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU=1` if run on macOS
A bit of a hack, but I don't think we should add specific handlers like this outside of the `kind-d8.sh` script.
Fixes https://github.com/deckhouse/deckhouse/issues/7069
The problem with threshold-exporter crashing is caused by enabled Rosetta emulation in Docker Desktop on Apple Silicon Macs
You can target it by passing the aforementioned env to container. Apparently, it even works if container is launched inside of another container such as kind
https://github.com/solo-io/gloo/issues/9800#issuecomment-2253078909
Another fix is to just disable `Use Rosetta for x86_64/amd64 emulation on Apple Silicon` in Docker Desktop settings.
No …
> [kind] Force QEMU on macOS for eviction-thresholds-exporter

- docs/site/_includes/getting_started/bm-private/partials/ingress-nginx-controller.yml.inc
Fix toleration for IngressNginxController for private bare metal. Set same as we do for BareMetal getting started.
```changes
section: docs
type: chore
summary: Update toleration of the IngressNginxController for private bare metal.
```
> [docs][getting_started] Fix toleration for IngressNginxController for private bare metal

- modules/500-dashboard/templates/dashboard/rbac-for-us.yaml
- modules/500-dashboard/templates/dashboard/secret.yaml
Grants `create secrets` permission to `dashboard` service account and deletes `kubernetes-dashboard-key-holder` secret template from the dashboard chart.
The dashboard machinery is designed to create/update its secret by itself, so we'd better not intervene into this process by creating secrets via helm releases. Otherwise, there might be some reconciliation issues when two controllers subsequently override a secret.
Dashboards works as expected and the `kubernetes-dashboard-key-holder` is in place with correct data.
```changes
type: chore
summary: Grant create secrets permission.
```
> [dashboard] grant create secrets permission

- helm_lib/Chart.lock
- helm_lib/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/templates/_module_init_container.tpl
- modules/000-common/images/alpine/Dockerfile
- modules/000-common/images/alpine/werf.inc.yaml
- testing/library/images_tags_generated.go
fix image selection logic for helm_lib_module_init_container_chown_nobody_volume and helm_lib_module_init_container_chown_deckhouse_volume.
You need to leave the image until the modules are migrated.
```changes
type: fix
summary: fixed pull/9992
```
> [common] fixed rm common/alpine

- ee/modules/500-operator-trivy/images/operator/Dockerfile
- ee/modules/500-operator-trivy/images/operator/patches/009-fix-policies-cache.patch
- ee/modules/500-operator-trivy/images/operator/patches/README.md
It provides fix for policies redownload error.
The operator tries to reload policies, but uses the old image.
The operator does not try to reload policies
```changes
type: fix
summary: Fix policies bundle error.
```
> [operator-trivy] fix policies bundle download

- modules/500-upmeter/images/upmeter/pkg/server/api/public_status.go
There is an issue with JSON API returning integers instead of words "Operational", "Degraded", or "Outage"
It breaks UI's
It is small fix that should be considered in a patch release
```changes
type: fix
summary: Fixed API status summary showing numbers instead of "Operational", "Degraded", or "Outage"
```
> [upmeter] Fix public API status values

- deckhouse-controller/cmd/deckhouse-controller/start.go
- deckhouse-controller/pkg/addon-operator/kube-config/backend/module_config.go
- deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_config.go
- deckhouse-controller/pkg/apis/deckhouse.io/validation/register.go
- deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_kubernetes_version.go
- deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_module_config.go
- deckhouse-controller/pkg/controller/controller.go
- deckhouse-controller/pkg/controller/models/definition.go
- deckhouse-controller/pkg/controller/models/module.go
- docs/documentation/_data/deckhouse-alerts.yml
- modules/002-deckhouse/templates/admission/validation.yaml
- modules/040-node-manager/module.yaml
- modules/300-prometheus/module.yaml
- modules/340-monitoring-deckhouse/monitoring/prometheus-rules/alerting.yaml
- modules/500-cilium-hubble/module.yaml
deckhouse-controller:
add validation for ModuleConfig file 
add alerts when module config has annotation
modules:
add new yaml parameters to make new validation behaviour. at now, `module.yaml` file is must have in every module folder
User can accidentally remove module. We need to warn him about consequences and waiting for his approve.
Until we not have user approve - we did'nt disable/delete module from cluster.
When we are trying to disable the module via the enabled: false or deleting the ModuleConfig, we have to ask for a confirmation, via the annotations.
If annotation is set 'modules.deckhouse.io/allow-disable: "true"' we can:
1) Mark ModuleConfig as disabled (spec.Enabled: false) 
2) Delete the ModuleConfig
Otherwise we want to deny the request with the message, which is set in …
> [deckhouse-controller] Add disable control for important modules

- deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_module_config.go
Checked pointers before dereference
When we change log-level in deckhouse ModuleConfig, we have an webhook error
```bash
error: moduleconfigs.deckhouse.io "deckhouse" could not be patched: Internal error occurred: failed calling webhook "module-configs.deckhouse-webhook.deckhouse.io": failed to call webhook: Post "https://deckhouse.d8-system.svc:4223/validate/v1alpha1/module-configs?timeout=10s": EOF
You can run `kubectl replace -f /tmp/kubectl-edit-680662504.yaml` to try this update again
```
Same with editing global ModuleConfig
```bash
error: moduleconfigs.deckhouse.io "global" could not be patched: Internal error occurred: failed calling webhook "module-configs.deckhouse-webhook.deckhouse.io": failed to call webhook: Post "https://deckhouse.d8-system.svc:4223/validate/v1alpha1/module-c …
```
> [deckhouse-controller] Fix deckhouse and global mc edit

- docs/documentation/_includes/nav-breadcrumbs.html
- docs/site/_includes/group-menu.html
Deleted `v1` in breadcrumbs of documentation pages.
```changes
section: docs
type: fix
summary: |
Deleted `v1` in breadcrumbs of documentation pages.
```
> [docs] Delete v1 in breadcrumbs of documentation pages

- modules/600-secret-copier/templates/validating.yml
- modules/600-secret-copier/templates/validation.yml
Add validation through `ValidatingAdmissionPolicy` to prohibit manual creation of secrets with label `secret-copier.deckhouse.io/enabled` outside of `default` namespace. 
This would help with accidental creation of secrets, including automatic creation with wrong `secretTemplates`, because such secrets would be deleted by `secret-copier` anyway.
```changes
type: chore
summary: Add validation of secrets with secret-copier labels
```
> [secret-copier] Add secret creation validation

- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
- modules/462-loki/templates/statefulset.yaml
- modules/500-upmeter/templates/upmeter/statefulset.yaml
Cherry-pick of #10150 to 1.64.
Remove migrator init containers from modules:
- upmeter
- loki
- prometheus
In some cases, this component can cause a CrashLoopBackoff in Pods within the modules.
We have clients who are experiencing issues due to this component.
```changes
section: upmeter, loki, prometheus
type: fix
summary: Removed migrator init containers from modules
```
> Removed migrator init containers from upmeter, loki and prometheus modules

- deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_kubernetes_version.go
- deckhouse-controller/pkg/controller/deckhouse-release/controller.go
- go_lib/dependency/extenders/deckhouseversion/extender.go
- go_lib/dependency/extenders/kubernetesversion/extender.go
It provides fix for extenders messages.
We have wrong logs and do not handle invalid base versions well.
Right logs and invalid base versions are handled well
```changes
type: fix
summary: Fix extenders message logs.
```
> [deckhouse] fix extenders message and error handling

- deckhouse-controller/pkg/controller/module-controllers/downloader/module_downloader.go
- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
Generate dockercfg for anonymous access if ModuleSource's dockercfg is empty
To work with anonymouse access to registry in modules
```changes
type: fix
summary: Generate empty docker auth for anonymous registry access.
```
> [deckhouse] Fill values dockercfg if anonymous access

- modules/110-istio/templates/control-plane/iop.yaml
Turn on the `Access Logs` and redirect them to `/dev/stdout`.
Currently, it is not possible to display AUDIT logs of AuthorizationPolicy.
When applying Authorization Policy with Action:AUDIT, audit events will be displayed in the sidecar istio-proxy stdout logs.
```changes
section: istio
type: chore
summary: Restoring the operation of the audit logs. To see your AuthorizationPolicies AUDIT results, restart application pods with istio sidecars.
```
> [istio] Restoring the operation of the audit logs.

- ee/modules/021-cni-cilium/images/egress-gateway-agent/cmd/main.go
- ee/modules/021-cni-cilium/images/egress-gateway-agent/werf.inc.yaml
Disable the metrics server in the `egress-gateway-agent` because we don't use it.
If the metrics server has not been explicitly turned off, it will by default be bound to *:8080. 
This can cause confusion, as if another application is already using this port, our application will not be able to start.
The `egress-gateway-agent` starts correctly even if port 8080 is already occupied by another application.
```changes
type: fix
summary: Disable the metrics server in the "egress-gateway-agent" because we don't use it.
impact: The pods of the egress-gateway-agent will be restarted.
```
> [cni-cilium] Disable the metrics server in the egress-gateway-agent.

- dhctl/pkg/preflight/registry.go
Fix registry credentials preflight check failure when `registryDockerCfg` contains empty auth for host, for example `{"auths":{"registry.deckhouse.io":{}}}`
```yaml
kind: InitConfiguration
deckhouse:
imagesRepo: registry.deckhouse.io/deckhouse/ce
registryDockerCfg: eyJhdXRocyI6eyJyZWdpc3RyeS5kZWNraG91c2UuaW8iOnt9fX0=
```
```
🎈 ~ Common: Global preflight checks
│ ┌ Checking PublicDomainTemplate is correctly
│ │ 🎉 Succeeded!
│ └ Checking PublicDomainTemplate is correctly (0.00 seconds)
│
│ ┌ Checking registry credentials are correct
│ │ ️⛱️️ Attempt #1 of 1 |
│ │ 	Checking registry credentials are correct failed, next attempt will be in 10s"
│ │ 	Error: authentication failed
│ │
│ └ Checking registry credentials are correct (0.49 seconds) FAILED
└ 🎈 ~ Common: …
```
> [dhctl] fix empty registry credentials preflight check failure

- dhctl/pkg/kubernetes/actions/manifests/manifests.go
- modules/002-deckhouse/hooks/migrate/remove_deckhouse_label_from_provider_cluster_static_cluster_config.go
- modules/040-control-plane-manager/create-d8-cluster-configuration.sh
Add migration to delete `heritage: deckhouse` label for `d8-provider-cluster-configuration`, `d8-static-cluster-configuration` and `d8-cluster-configuration` secrets.
Also, remove labels set from dhctl.
Close [issue](https://github.com/deckhouse/deckhouse/issues/9722)
We need to provide the ability to edit a secrets from more than just the feed deckhouse
Cloud cluster. before migration
After migration. Label removed another fields not changed
deckhouse ready after restart and secrets does not changes (skip migrations)
Static cluster
Before migration
After migration. Label removed another fields not changed
Deckhouse restarted successfully. Migration skipped.
hybrid cluster
After migration. Label removed another fields not changed
Deckhouse restarted successfully. Migration skipped …
> [dhctl] Remove heritage label from cluster-configuration secrets by default

- modules/040-node-manager/hooks/migration/migrate_existing_capi_sa.go
Migration for existing capi-controller-manager sa which adopts it for use in helm.
Without this migration, we got an error:
{"binding":"ConvergeModules","event.type":"OperatorStartup","level":"error","module":"node-manager","modules":"control-plane-manager,node-manager","msg":"ModuleRun failed in phase 'CanRunHelm'. Requeue task to retry after delay. Failed count is 9. Error: helm upgrade failed: Unable to continue with update: ServiceAccount \"capi-controller-manager\" in namespace \"d8-cloud-instance-manager\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to …
> [node-manager] CAPI sa migration

- docs/documentation/pages/DECKHOUSE-FAQ.md
- docs/documentation/pages/DECKHOUSE-FAQ_RU.md
- Add changes from PR #9792 to main branch.
- Add a step to manually pull the REGISTRY_PACKAGE_PROXY image.
```changes
section: docs
type: chore
summary: Update article about switching EE to CE.
```
> [docs] Update article about switching EE to CE and vice versa for 1.65 

- docs/documentation/_data/deckhouse-alerts.yml
- modules/340-monitoring-deckhouse/monitoring/prometheus-rules/node-os-requirements.yaml
Add centos 7 to D8NodeHasDeprecatedOSVersion alert.
CentOS Linux 7 End of Life: June 30, 2024.
```changes
section: monitoring-deckhouse
type: chore
summary: Add CentOS 7 to the `D8NodeHasDeprecatedOSVersion` alert.
```
> [monitoring-deckhouse] Add CentOS 7 to D8NodeHasDeprecatedOSVersion alert

- deckhouse-controller/crds/doc-ru-module-source.yaml
- deckhouse-controller/crds/module-source.yaml
- docs/site/_includes/getting_started/global/step_cluster_setup.html
- docs/site/_includes/getting_started/global/step_cluster_setup_ru.html
Added info about anonymous access to the container registry at specs and gs.
```changes
section: docs
type: chore
summary: Added info about anonymous access to the container registry.
```
> [docs] Added info about anonymous access to the container registry

- ee/modules/030-cloud-provider-zvirt/templates/csi/secret.yaml
This PR fixes 401 Unauthorized error in zvirt csi node
To fix 401 Unauthorized error in zvirt csi node
No 401 Unauthorized errors in zvirt csi node logs
```changes
type: fix
summary: 401 Unauthorized error fixed in zvirt csi-node.
```
> [cloud-provider-zvirt] Fix csi-node 401 Unauthorized

- modules/002-deckhouse/templates/validation.yaml
Fix validation
We have to revert condition to avoid other ModuleConfigs
In the kubernetes 1.26 other ModuleConfigs then `deckhouse` could not be updated
```changes
type: fix 
summary: Fix validation policy for update windows in kubernetes 1.26
```
> [deckhouse] Update validation for ModuleConfig with windows

- ee/be/modules/350-node-local-dns/images/coredns/werf.inc.yaml
- ee/be/modules/350-node-local-dns/images/iptables-loop/werf.inc.yaml
- ee/modules/450-network-gateway/images/snat/werf.inc.yaml
- modules/007-registrypackages/images/iptables/werf.inc.yaml
- modules/021-cni-cilium/images/agent/werf.inc.yaml
- modules/021-cni-cilium/images/bin-cilium/werf.inc.yaml
- modules/035-cni-flannel/images/flanneld/entrypoint/go.mod
- modules/035-cni-flannel/images/flanneld/entrypoint/go.sum
- modules/035-cni-flannel/images/flanneld/werf.inc.yaml
- modules/035-cni-simple-bridge/images/simple-bridge/werf.inc.yaml
- modules/036-kube-proxy/images/kube-proxy/werf.inc.yaml
- modules/050-network-policy-engine/images/kube-router/werf.inc.yaml
- modules/402-ingress-nginx/images/proxy-failover-iptables/failover/go.mod
- modules/402-ingress-nginx/images/proxy-failover-iptables/failover/go.sum
- modules/402-ingress-nginx/images/proxy-failover-iptables/werf.inc.yaml
- modules/500-openvpn/images/openvpn/entrypoint/go.mod
- modules/500-openvpn/images/openvpn/entrypoint/go.sum
- modules/500-openvpn/images/openvpn/werf.inc.yaml
Using the same binary files of `iptables` in all modules, which we build statically from source code.
From time to time, we encountered problems due to different versions of the `iptables` being used in different modules and on the host system.
In all modules and on the host system, we use the same binary of `iptables` to ensure compatibility and avoid any issues.
```changes
type: chore
summary: Replacing iptables with precompiled binaries.
impact: The pods will be restarted.
```
```changes
section: network-gatewy
type: chore
summary: Replacing iptables with precompiled binaries.
impact: The pods will be restarted.
```
```changes
type: chore
summary: Replacing iptables with precompiled binaries. …
```
> [iptables] Use same iptables in all modules

- tools/validation/release_requirements.go
Excludes `disabledModules` requirement from valudation.
This requirement is checked internally and it makes no sense to validate it.
Requirements validation is passed OK.
```changes
type: chore
summary: Exclude disabledModules requirement from valudation.
```
> [deckhouse] exclude disabledModules requirement from validation

- deckhouse-controller/pkg/controller/deckhouse-release/controller.go
- deckhouse-controller/pkg/controller/module-controllers/release/controller.go
- go_lib/updater/updater.go
Fix wrong index detection for deployed ModuleRelease
It can lead to a problem with detection of a deployed module release
```changes
type: fix 
summary: Fix deployed module release detection in the ModuleReleaseController.
```
> [deckhouse-controller] Fix ModuleRelease sorting

- modules/040-node-manager/images/machine-controller-manager/werf.inc.yaml
`machine-controller-manager` have an important [fix](https://github.com/deckhouse/mcm/pull/13).
```changes
type: fix
summary: Fix handling of machine creation errors in the `machine-controller-manager`(`vsphere` driver).
```
> [node-manager] Update `machine-controller-manager` version

- candi/bashible/common-steps/node-group/004_resize_partitions.sh.tpl
Extend regexp in `004_resize_partitions.sh` for detect lvm partition with capital letter and digit in name.
If the logical volume name contains an capital letter or digit (for example `Debian--12-vg--root` in picture below), it will not be defined as an LVM partition. As a result, the PhysicalVolume partition will not be resized and consequently neither will the LogicalVolume:
Correct resize lvm partition with capital letter and digit in name: 
```changes
section: candi
type: feature
summary: Extend regexp in `004_resize_partitions.sh` for detect lvm partition with capital letter and digit in name.
```
> [candi] extend regexp for detect lvm partition

- docs/documentation/_data/sidebars/main.yml
Fixed ceph-csi module deprecated alert.
```changes
section: <docs
type: fix 
summary: Fixed ceph-csi module deprecated alert.
```
> [docs] Fixed ceph-csi module deprecated alert

- dhctl/pkg/kubernetes/actions/converge/cloud_permanent_node_group_controller.go
- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/kubernetes/actions/converge/nodebootstrap.go
- dhctl/pkg/terraform/executor.go
- dhctl/pkg/terraform/pipeline.go
- dhctl/pkg/terraform/runner.go
- dhctl/pkg/terraform/runner_interface.go
- dhctl/pkg/terraform/runner_test.go
- dhctl/pkg/terraform/terraform_context.go
Add parallel bootstrap `cloudpermanent` nodes to dhctl.
Reduce time for bootstrap multiple nodes.
<details>
<summary>Before </summary>
</details>
<details>
<summary>After</summary>
</details>
```changes
section: dhctl
type: feature
summary: Add parallel bootstrap `cloudpermanent` nodes to dhctl.
```
> [dhctl] parallel bootstrap cloudpermanent nodes

- testing/cloud_layouts/Static/configuration.tpl.yaml
- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
Disable ebpfExporter for e2e tests on OS without eBPF available.
This causes tests to fail without any good reason.
Working e2e tests on Static and Yandex layouts
```changes
type: chore
summary: Disable ebpfExporter for tests on OS without eBPF available.
```
> [testing] Disable ebpfExporter for tests on OS without eBPF available

- candi/bashible/common-steps/node-group/041_configure_sysctl_tuner.sh.tpl
Fixes recurring min_free_kbytes warnings in dmesg caused by user-defined values. Adds a check for transparent_hugepage status before attempting to disable it, preventing unnecessary calls to set_recommended_min_free_kbytes function in linux kernel.
Every 10 minutes `/opt/deckhouse/bin/sysctl-tuner` checks that `transparent_hugepage` is disabled, this causes unwanted warnings in the kernel logs.
no unnecessary messages in kernel logs.
Logs example:
```
[Thu Oct 24 17:42:22 2024] min_free_kbytes is not updated to 11265 because user defined value 131072 is preferred
[Thu Oct 24 17:44:12 2024] min_free_kbytes is not updated to 11265 because user defined value 131072 is preferred
[Thu Oct 24 17:49:18 2024] min_free_kbytes is not updated to 11265 because user defined value 131072 is preferred …
```
> [candi] check transparent hugepages before disable

- testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/AWS/WithoutNAT/resources.yaml
https://github.com/deckhouse/deckhouse/issues/3082
CloudPermanent nodes are created by dhctl (via terraform). Adding such a node to each test will increase the required resources and time. It is also not possible to just substitute the CloudEphemeral node with the CloudPermanent, because, in this case, we stop testing the most frequent case of node creation.
Not releted to release
CloudPermanent nodes starts on e2e tests
```changes
section: ci
type: feature
summary: new CloudPermanent nodes starts on e2e tests.
```
> feat: add CloudPermanent for aws e2e

- dhctl/pkg/terraform/runner.go
print what will be destroyed in cloud when "terraform destroy" in dhctl
this allow to see what objects in cloud will be destroyed when dhctl destroy cluster
print all cloud objects will be destroyed when dhctl destroy cluster
```changes
section: dhctl
type: feature
summary: Print cloud objects which will be destroyed when dhctl destroy
```
> [dhctl] Print cloud objects which will be destroyed when dhctl destroy

- candi/bashible/bashbooster/50_registrypackages.sh
- candi/bashible/bb_package_install.sh.tpl
In the current implementation of DH, when installing in a closed environment, it is required to explicitly specify all single (not a network with a mask) IP addresses of master nodes in the no_proxy parameter, since the python library used in the `bb-package-fetch-blob` function cannot handle specifying a network with a mask (for example, `192.168.0.0/16`)
Since the `bb-package-fetch-blob` function is used only to receive packets from `bashible-apiserver`, I suggest explicitly adding the `bashible-apiserver` address to the `no_proxy` parameter within the function context.
With this change, it is no longer necessary to specify single (not a network with a mask) IP addresses of master nodes in the `no_proxy` parameter.
```changes
section: candi 
type: fix 
summary:  Added explicit addition …
```
> [candi][bashible] Added explicit addition of PACKAGES_PROXY_ADDRESSES into the NO_PROXY parameter

- modules/460-log-shipper/hooks/internal/vector/transform/source.go
- modules/460-log-shipper/hooks/testdata/es-5x/result.json
- modules/460-log-shipper/hooks/testdata/file-to-elastic/result.json
- modules/460-log-shipper/hooks/testdata/file-to-kafka-tls/result.json
- modules/460-log-shipper/hooks/testdata/file-to-kafka/result.json
- modules/460-log-shipper/hooks/testdata/file-to-loki/result.json
- modules/460-log-shipper/hooks/testdata/file-to-socket-cef-gelf/result.json
- modules/460-log-shipper/hooks/testdata/file-to-socket/result.json
- modules/460-log-shipper/hooks/testdata/file-to-splunk/result.json
- modules/460-log-shipper/hooks/testdata/file-to-vector/result.json
- modules/460-log-shipper/hooks/testdata/many-to-one/result.json
- modules/460-log-shipper/hooks/testdata/multiline-custom-pods/result.json
- modules/460-log-shipper/hooks/testdata/multiline-custom/result.json
- modules/460-log-shipper/hooks/testdata/multiline/result.json
- modules/460-log-shipper/hooks/testdata/multiple-dest/result.json
- modules/460-log-shipper/hooks/testdata/namespaced-source/result.json
- modules/460-log-shipper/hooks/testdata/one-dest/result.json
- modules/460-log-shipper/hooks/testdata/pair-datastream/result.json
- modules/460-log-shipper/hooks/testdata/simple-pair/result.json
- modules/460-log-shipper/hooks/testdata/throttle-with-filter/result.json
- modules/460-log-shipper/hooks/testdata/throttle/result.json
Move cleanup transform to be the last transform for a source
If we cleanup the file label before multiline, the [grouping](https://github.com/deckhouse/deckhouse/blob/7e36d7017fa4babcef6a7e33c8a34f907b387289/modules/460-log-shipper/hooks/internal/vector/transform/multiline.go#L40-L44) will not work as expected. As a result, logs from different pods will be concatenated together. 
Multiline doesn't work!
```changes
type: fix
summary: Move cleanup transform to be the last transform for a source. Fixes multiline parsing issue. 
```
> [log-shipper] Cleanup after source

- testing/cloud_layouts/OpenStack/Standard/configuration.tpl.yaml
- testing/cloud_layouts/OpenStack/Standard/resources.yaml
Switch OpenStack testing server flavor to custom
Allows to change allocated resources on e2e tests
Changed available resources on e2e
```changes
type: chore
summary: Switch OpenStack testing server flavor.
```
> [testing] Switch OpenStack testing server flavor

- modules/015-admission-policy-engine/crds/doc-ru-operation-policy.yaml
- modules/015-admission-policy-engine/crds/operation-policy.yaml
Describe your changes in detail.
Change files modules/015-admission-policy-engine/crds/doc-ru-operation-policy.yaml modules/015-admission-policy-engine/crds/operation-policy.yaml for fixing documentation. Some vars in examples in doc must be define in array.
The quality of documentation will improve
```changes
section: docs
type: fix 
summary: Change type of vars, which presents in example in documentation.
```
> [docs][OperationPolicy] Fix type of vars in documentation

- docs/documentation/_data/deckhouse-alerts.yml
- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/node.yaml
- modules/340-monitoring-kubernetes/templates/node-exporter/daemonset.yaml
Adds collecting of thresholds of sysctl parameter `net.ipv4.tcp_mem` and alert when `node_sockstat_TCP_mem_bytes` metric passes this threshold.
This fixes issue https://github.com/deckhouse/deckhouse/issues/4605 and improves monitoring over TCP. Monitoring net.ipv4.tcp_mem helps track the memory usage of the TCP stack, which is essential for diagnosing issues related to high memory consumption in network operations. Excessive TCP memory usage can lead to degraded performance, dropped connections, or even system crashes. By adding these metrics and alerts, we aim to proactively detect abnormal memory usage patterns, prevent potential outages, and ensure stable network performance.
-
We expect existance of alerts when TCP stack memory passes thresholds from second value of …
> [monitoring-kubernetes] collect tcp_mem metric and make alert when tcp memory pressure.

- candi/version_map.yml
- modules/007-registrypackages/images/d8/werf.inc.yaml
- modules/800-deckhouse-tools/images/web/werf.inc.yaml
Added `fromCacheVersion: <d8-cli version>` directive to d8-cli builds of deckhouse-tools module and adapted builds of d8 within deckhouse codebase to use go 1.23.
werf stuck using old cached build and so clients were not getting the latest versions with features and bugfixes
deckhouse-tools shows current release of d8-cli from version_map.yaml in it's interface instead of 0.3.2
```changes
type: fix
summary: Rebuild d8-cli images when used version changes
```
> [deckhouse-tools] Rebuild d8-cli images when used version changes

- modules/040-node-manager/openapi/config-values.yaml
Hotfix for PR https://github.com/deckhouse/deckhouse/pull/9436
Fix installing CE on OpenSuse.
1.65 has already been cut off.
```changes
type: fix
summary: Fix installing CE on OpenSuse.
```
> [node-manager] fixed pull/9436

- .github/workflow_templates/check-pr-milestone.yml
- .github/workflows/check-pr-milestone.yml
```changes
section: ci
type: fix
summary: Get new PR info on each run of the Check PR milestone job. This fixes the problem when developers need to make a commit to retrigger the job.
```
> [ci] Get new PR info on each run of the Check PR milestone job

- modules/300-prometheus/openapi/config-values.yaml
- modules/300-prometheus/openapi/doc-ru-config-values.yaml
- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
Adds an option to switch podAntiAffinity rule type for longterm Prometheus instance.
* Resolves an issue where the Kubernetes scheduler places both the longterm and main Prometheus instances on the same node after a failure of one of the nodes, leading to resource contention. Even after the node is fixed, this setup persists, worsening performance. Switching podAntiAffinty to `Required` ensures longterm instance won't be scheduled on the same node as main.
* Fixes https://github.com/deckhouse/deckhouse/issues/7216.
```changes
type: feature
summary: Added `longtermPodAntiAffinity` options to module.
```
> [prometheus] Add podAntiAffinity param for longterm

- .github/workflow_templates/build-and-test_release.yml
- .github/workflows/build-and-test_release.yml
Build other editions only after FE
This allows for faster builds thanks to using cache
FE should build first
```changes
section: ci
type: feature
summary: Build other editions only after FE.
```
> [ci] Build other editions only after FE

- ee/modules/110-istio/crds/istiofederation.yaml
- ee/modules/110-istio/hooks/ee/alliance_metadata_merge.go
- ee/modules/110-istio/hooks/ee/alliance_metadata_merge_test.go
- ee/modules/110-istio/hooks/ee/federation_discovery.go
- ee/modules/110-istio/hooks/ee/federation_discovery_test.go
- ee/modules/110-istio/hooks/ee/lib/crd/istiofederation.go
- ee/modules/110-istio/templates/federation/remote-services.yaml
- modules/110-istio/template_tests/module_test.go
- modules/110-istio/templates/control-plane/iop.yaml
Enabling automatic DNS name allocated the Istio service and excluding self-made IP address allocation for public service's ServiceEntry'es in Federation.
The self-made IP address iterator is no longer needed after enabling the automatic DNS name allocation of Istio service.
Istio Federation no longer contains information about the IP addresses of public services and interaction with them takes place using DNS names and internal IP addresses allocated by istio.
```changes
section: istio
type: chore
summary: Got rid of self-made IP address allocation for public service's ServiceEntries in Federation
```
> [istio] Getting rid of self-made IP address allocation for public service's ServiceEntry'es in Federation

- candi/bashible/common-steps/node-group/004_integrate_kubernetes_data_device.sh.tpl
Hotfix for PR https://github.com/deckhouse/deckhouse/pull/9666
Such a filter is not needed because there is a check below the code for such a situation with the correct behavior.
```changes
section: candi
type: fix 
summary: removed the single-disk output filter
```
> [candi] fixed pull/9666

- testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/AWS/WithoutNAT/resources.yaml
Switch to cheaper machines for e2e tests on AWS
```changes
type: chore
summary: Switch to cheaper machines for e2e tests on AWS.
```
> [testing] Switch to cheaper machines for e2e tests on AWS

- candi/version_map.yml
Marked k8s 1.26 as EOL in the table of supported versions.
```changes
section: docs
type: chore
summary: Marked K8s 1.26 as EOL in the table of supported versions.
```
> [docs] Marked k8s 1.26 as EOL in the table of supported versions

- modules/300-prometheus/hooks/disk_metrics.go
This PR adds timeout to exec request for disk metrics hook.
We urgently require this fix to prevent significant issues that may arise when both the disk subsystem and the Kubernetes API experience substantial slowdowns. Without implementing this solution, Prometheus could potentially enter an infinite waiting state while attempting to retrieve execution results from the API regarding free and used disk space. By addressing these inefficiencies, we ensure smoother operation and more reliable monitoring."
-
Disk space checking hook must enter timeout state on situations, when disk subsystem, Kubernetes API and whole system goes very slow.
Add timeout to exec request for disk metrics hook.
```changes
type: fix
summary: Timeout for disk metrics retrieve in Prometheus hook. …
```
> [prometheus] Add timeout to exec request for disk metrics hook.

- modules/000-common/images/init/werf.inc.yaml
Add `/bin/true` to `init` image
fixed https://github.com/deckhouse/deckhouse/pull/9992
upmeter create pod with command `true` https://github.com/deckhouse/deckhouse/blob/6383a6d200067fbaaf3f1483c21ad4187bd57735/modules/500-upmeter/images/upmeter/pkg/probe/checker/k8s_pod.go#L186-L188 and this binary does not exist in image and we have a errors in events like this
```
2m37s       Normal    Created              pod/upmeter-probe-scheduler-b7e18705                           Created container pause
2m37s       Warning   Failed               pod/upmeter-probe-scheduler-b7e18705                           Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "true": executable file not found in …
```
> [common] Add /bin/true to init image

- testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml
Previously used AMI for e2e tests on AWS was deprecated, switching to a new one.
Currently e2e tests on AWS fail due to using nonexistent AMI.
Working e2e on AWS
```changes
type: chore
summary: Updated AWS AMI.
```
> [testing] Update AWS AMI

- docs/documentation/_data/deckhouse-alerts.yml
- modules/500-upmeter/monitoring/prometheus-rules/alerting.yaml
Fix typo in alert description
```changes
type: chore
summary: Fix typo in alert description
```
> [upmeter] Fix typo in alert description

- modules/040-node-manager/crds/instance.yaml
Add to the instance a status about zvirtinstance
There is no way to track instance status
Impact business process
```changes
type: fix
summary: Add to the instance a status about zvirtinstance.
```
> [cloud-provider-zvirt] add zvirtinstanceclass to the instance

- docs/site/_includes/getting_started/existing/STEP_FINALIZE.md
- docs/site/_includes/getting_started/existing/STEP_FINALIZE_RU.md
Fixing the link in the DNS name template.
```changes
section: docs
type: chore
summary: Fixing the link in the DNS name template.
```
> [docs] Fixing the link in the DNS name template

- deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/deckhouse_release.go
- deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/register.go
- deckhouse-controller/pkg/controller/controller.go
- deckhouse-controller/pkg/controller/deckhouse-release/controller.go
- deckhouse-controller/pkg/controller/deckhouse-release/controller_test.go
- deckhouse-controller/pkg/controller/deckhouse-release/event.go
- deckhouse-controller/pkg/controller/deckhouse-release/event_test.go
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/apply-now-deckhouse-previous-release-is-not-ready.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/apply-now-manual-approval-mode-is-set.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/auto-deploy-patch-release-in-manual-mode.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/manual-approval-mode-with-canary-process.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/no-update-windows-configured.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/patch-out-of-update-window.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/pending-manual-release-on-cluster-bootstrap.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-with-apply-now-annotation-out-of-window.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-with-notification-settings.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/shutdown-and-evicted-pods.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/suspend-release.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/update-in-day-window.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/update-minimal-notification-time-without-configuring-notification-webhook.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/update-out-of-day-window.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/update-out-of-window.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/update-release-is-deployed.yaml
- deckhouse-controller/pkg/controller/module-controllers/source/controller_test.go
- deckhouse-controller/pkg/helpers/deckhouse_settings.go
Fixed a bug related to the fact that the state of the release object was not updated
(cherry picked from commit f482a320027e19cc154a53c20cf3c8bb524169ee)
Close https://github.com/deckhouse/deckhouse/issues/9823
The issue is relevant for the current production
```changes
type: fix
summary: Fixed a bug related to the fact that the state of the release object was not updated.
```
> [deckhouse-controller] DeckhouseRelease without annotations is not reconciled (#9838)

- deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go
- ee/se/modules/380-metallb/hooks/check_requirements_for_upgrade.go
- ee/se/modules/380-metallb/hooks/check_requirements_for_upgrade_test.go
- ee/se/modules/380-metallb/hooks/common_test.go
- ee/se/modules/380-metallb/requirements/check.go
- ee/se/modules/380-metallb/requirements/check_test.go
Add a check of the settings of the `metallb` module and its resources for compliance with the requirements of the new version of the module.
We require the customer to change the settings in the cluster themselves before cluster upgrade.
`Deckhouse` can't be upgraded until the settings meet the new module version requirements.
```changes
type: feature
summary: Added pre-upgrade compatibility check for metallb configuration.
```
> [metallb] Pre-upgrade compatibility check for metallb configuration

- candi/bashible/common-steps/all/099_reboot.sh.tpl
Switch `shutdown -r now` to delayed `shutdown -r -t 5` for able to correctly execute all scripts in bundle by bootstrap. 
Now we have failed reboot step and twice execute for execute bundle
```
┌ Execute bundle
│ ┌ ⛵ ~ Bootstrap: Checking bashible is ready
│ └ ⛵ ~ Bootstrap: Checking bashible is ready (0.49 seconds)
│
│ ┌ ⛵ ~ Bootstrap: Cleanup previous bashible run if need
│ │ Bashible instance not found. Start it!
│ └ ⛵ ~ Bootstrap: Cleanup previous bashible run if need (0.49 seconds)
│
│ ┌ Run step 000_add_node_users.sh
│ │ --- A lot of success log removed ---
│ └ Run step 098_set_permissions.sh (0.07 seconds)
│
│ ┌ Run step 099_reboot.sh
│ └ Run step 099_reboot.sh (0.17 seconds) FAILED
│
│ ️⛱️️ Attempt #1 of 30 |
│ 	Execute bundle failed, next attempt will be in 10s"
│ 	Error: bundle …
```
> [candi] Fix failed step reboot by bootstrap

- modules/150-user-authn/templates/dex/passwords.yaml
Fixes: #9706
Incorrect handling of group names for users in static configuration.
When users are created with groups containing only numbers, user login is performed without problems.
```changes
type: fix
summary: numbers in dex groups
```
> [user-authn] fix: numbers in dex groups

- modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
- modules/402-ingress-nginx/crds/ingress-nginx.yaml
Removes unnecessary check wether an Ingress Nginx is of version >= 1.9 when setting `annotationValidationEnabled`.
After deprecating 1.6, only >= 1.9 versions of Ingress Nginx controller left.
It's possible to set `annotationValidationEnabled` to `true` even if `controllerVersion` isn't set explicitly.
```changes
```
> [ingress-nginx] remove unnecessary validation and warnings

- docs/site/_data/i18n.yaml
- docs/site/_includes/head.html
- docs/site/pages/guides/PRODUCTION.md
- docs/site/pages/guides/PRODUCTION_RU.md
- Fix description generation on Getting Started pages
- Add the description for the guide.
```changes
section: docs
type: fix
summary: Fix description generation on Getting Started pages. Add the description for the guide.
```
> [docs][getting-started] Refactor description generation in GS pages

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
- modules/040-control-plane-manager/images/etcd-backup/entrypoint.sh
- modules/040-control-plane-manager/images/etcd-backup/werf.inc.yaml
- modules/040-control-plane-manager/templates/etcd-backup/cronjob.yaml
Corrected the check of sufficient free space it should remain more than 25% after copying the archive.
Added etcd dump compression.
Corrected documentation.
The past check was not safe for etcd and may have depleted the free disk space under etcd.
The change should go to the branch where it was added to avoid future problems.
```changes
type: fix 
summary: Fixed free space sufficiency detection for etcd-backup
```
> [control-plane-manager] Fixed free space sufficiency detection for etcd-backup

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- .golangci.yaml
- dhctl/go.mod
- ee/modules/025-static-routing-manager/hooks/iprulesets_handler.go
- global-hooks/discovery/kubernetes_version.go
- go.mod
- go_lib/hooks/tls_certificate/internal_tls.go
- modules/002-deckhouse/hooks/migrate/remove_deckhouse_label_from_provider_cluster_static_cluster_config.go
- modules/040-node-manager/hooks/chaos_monkey.go
- modules/150-user-authn/template_tests/kubeconfig_generator_config_test.go
- modules/402-ingress-nginx/hooks/update_ingress_address.go
- modules/460-log-shipper/hooks/validate_test.go
- modules/500-upmeter/hooks/smokemini/internal/scheduler/deleter.go
- testing/matrix/linter/rules/errors/errors.go
- testing/matrix/linter/rules/modules/images.go
- testing/matrix/linter/rules/modules/monitoring.go
- testing/matrix/linter/rules/modules/oss.go
- testing/matrix/linter/rules/modules/testgo.go
- testing/matrix/linter/rules/roles/wildcards.go
- testing/matrix/linter/rules/rules.go
- tools/go.mod
- werf.yaml
This PR updates the Go version to 1.23.
This update is necessary due to the addition of the dhctl dependency in the deckhouse-cli project, which requires Go 1.23 for compatibility.
Pipelines with Test Results:
https://github.com/deckhouse/deckhouse-test-2/actions/runs/11609963962
https://github.com/deckhouse/deckhouse-test-2/actions/runs/11610003870
After rebase(resolved conflicts by rebase):
https://github.com/deckhouse/deckhouse-test-2/actions/runs/11627516010
```changes
type: chore
summary: Use Go 1.23.
```
> [deckhouse] use Golang 1.23 for deckhouse-controller

- modules/150-user-authn/docs/USAGE.md
- modules/150-user-authn/docs/USAGE_RU.md
We use `spec.ttl` parameter in the `User` resource example. We must **explicitly point this out** for people reading the documentation.  
Users often copy the example, deploy it without removing `ttl`, and then get confused when `users` disappear from cluster.
But we won't remove `ttl` from the example because it is a preferred use case.
```changes
type: chore
summary:  Add a note about ttl in the user example
```
> [user-authn] Add a note about ttl in the user example

- ee/modules/110-istio/images/api-proxy/main.go
Fix SA token path in api-proxy container.
api-proxy can't authenticate to apiserver, so it can't handle remote requests.
Multiclusters malfunctioning.
Istio multiclusters don't work.
There aren't 401 messages in api-proxy's logs.
```changes
section: istio
type: fix
summary: SA token path in api-proxy container fixed.
```
> [istio] Fix SA token path in api-proxy container

- modules/600-secret-copier/templates/validation.yml
Allow deletion of secrets copied by `secret-copier` in the `ValidatingAdmissionPolicy`. It's needed e.g. when deleting a namespace.
Fix after PR https://github.com/deckhouse/deckhouse/pull/10066
Valid deletion of a secret in a namespace due to delete was throwing an error:
```
$ k -n network-policy delete secrets registrysecret
Error from server (Forbidden): secrets "registrysecret" is forbidden: ValidatingAdmissionPolicy 'secret-copier-label.deckhouse.io' with binding 'secret-copier-label.deckhouse.io' denied request: Creating secrets with `secret-copier.deckhouse.io/enabled` label outside of `default` namespace is forbidden
```
It fixes a bug (not a breaking one, but still)
```changes
type: chore
summary: Allow deletion by user of secrets created by secret-copier …
```
> [secret-copier] Allow secret-copier secrets deletion by user

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
Update etcd backup instructions in the FAQ.
```changes
type: chore
summary: Update etcd backup instructions in the FAQ.
```
> [control-plane-manager][docs] update etcd backup instructions in the FAQ

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
Some updates to our doc guide [How do I view the list of etcd members?](https://deckhouse.io/products/kubernetes-platform/documentation/v1/modules/040-control-plane-manager/faq.html#how-do-i-view-the-list-of-etcd-members)
- Fixed indents
- Updated `endpoint status` example to a script that automatically passes all control-plane node addresses.
Older example was incomplete and misleading.
```changes
type: chore
summary: Updated "How do I view the list of etcd members?" docs.
```
> [control-plane-manager] Updates to etcd members doc

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/node.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/nodes.json
- Change label selector to regexp to avoid problems with dot escaping. 
- This change resolves issues with broken dashboard panels when `node` label contain dots.
- Updates outdated panel type `graph` to `timeseries`
```changes
type: fix 
summary: Minor 'Nodes' dashboard improvements
```
> [monitoring-kubernetes] Fix 'Memory usage' panes in 'Nodes' dashboard

- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/node.json
- Adds the node CPU time steal metric to the "Basic CPU" panel in the "Node" dashboard.
- Updates outdated panel type `graph` to `timeseries`
- Improves dashboard readability for debugging CPU-related problems.
- Addresses the issue reported in https://github.com/deckhouse/deckhouse/issues/8164
```changes
type: chore 
summary: Minor "Node" dashboard improvements.
```
> [monitoring-kubernetes] Add steal to 'Node' dashboard 'CPU Basic' panel

- candi/bashible/common-steps/node-group/004_resize_partitions.sh.tpl
Right now, we have `LC_MESSAGES=en_US.UTF` which is unknown on almost all distros. And then `004_resize_partitions` step is running, we have warning:
```
/var/lib/bashible/bundle_steps/004_resize_partitions.sh: line 15: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF)
```
Removes the warning, which may lead to misunderstandings.
Tested on: Ubuntu 22.0.4, Centos 7, Astra 1.8 with ru locale.
```changes
section: candi
type: fix
summary: Fix LC_MESSAGES unknown locale
```
> [candi][bashible] Fix LC_MESSAGES unknown locale

- dhctl/pkg/kubernetes/actions/converge/master_node_group_controller.go
- dhctl/pkg/operations/converge/infra/hook/controlplane/hook_for_update_pipeline.go
- dhctl/pkg/operations/converge/infra/hook/controlplane/kube-proxy.go
In commander mode dhctl will now connect to puppet clusters via commander-agent api server tunneling instead of using ssh connections
```changes
section: dhctl
type: feature
summary: In commander mode connect to controlled clusters via commander agent instead of SSH
```
> [dhctl] In commander mode connect to controlled clusters via commander agent instead of SSH

- pkg/log/logger.go
When someone replace default source field - slog replacer panic
```changes
section: pkg
type: fix
summary: lib logger panic fix
```
> [pkg] logger cast panic fix

- modules/040-control-plane-manager/images/etcd-backup/entrypoint.sh
- modules/040-control-plane-manager/images/etcd-backup/werf.inc.yaml
Removed the removal of the old backup from etcd-backup
Code cleanup
```changes
type: chore
summary: Removed the removal of the old backup from etcd-backup
```
> [control-plane-manager] Removed the removal of the old backup from etcd-backup

- ee/modules/021-cni-cilium/templates/egress-policy/cilium-egress-policies.yaml
Fixed an issue with the "CiliumEgressGatewayPolicy" resource generation.
If we specify `excludedCIDRs` in resource `EgressGatewayPolicy`, in resulting `CiliumEgressGatewayPolicy` resource in the field `excludedCIDRs` added items from field `destinationCIDRs`.
Because of this, the `excludedCIDRs` field cannot be used.
This feature is used by clients in clusters.
We can use field `excludedCIDRs` in `EgressGatewayPolicy`.
```changes
section: cni-ciliim
type: fix
summary: Fixed `excludedCIDRs` option in EgressGatewayPolicies
```
> [cni-cilium] Fix egressGatewayPolicies

- docs/documentation/_data/supported_versions.yml
Updated  text for the EOL version of Kubernetes in DKP.
```changes
section: docs
type: fix 
summary: Updated  text for the EOL version of Kubernetes in DKP.
```
> [docs] Updated text for the EOL version of Kubernetes in DKP

- modules/040-node-manager/hooks/handle_node_templates.go
add ignore condition annotation "kubevirt.internal.virtualization.deckhouse.io/heartbeat" when hook  handle_node_templates execute
this allow to not trigger 'handle_node_templates' queue when annotation "kubevirt.internal.virtualization.deckhouse.io/heartbeat" applies on nodes
queue 'handle_node_templates' is not triggered if "kubevirt.internal.virtualization.deckhouse.io/heartbeat" annotation applies on nodes 
```changes
type: fix 
summary: ignore heartbeat annotation on hook
```
> [node-manager] ignore heartbeat annotation on hook

- dhctl/pkg/server/pkg/interceptors/interceptors.go
- dhctl/pkg/server/rpc/dhctl/abort.go
- dhctl/pkg/server/rpc/dhctl/bootstrap.go
- dhctl/pkg/server/rpc/dhctl/check.go
- dhctl/pkg/server/rpc/dhctl/commander_attach.go
- dhctl/pkg/server/rpc/dhctl/commander_detach.go
- dhctl/pkg/server/rpc/dhctl/converge.go
- dhctl/pkg/server/rpc/dhctl/destroy.go
- dhctl/pkg/server/rpc/dhctl/service.go
- dhctl/pkg/server/server/proxy.go
Improve grpc-server panic handling. Fixed line breaks in logs.
It is not expected to change behaviour of any dhctl operation not in commander-mode. 
```changes
section: dhctl
type: feature
summary: Improve panic handling. Fixed line breaks in logs.
```
> [dhctl] fix(dhctl-for-commander): add operations panic handler

- modules/021-cni-cilium/template_tests/module_test.go
We have merged [the PR](https://github.com/deckhouse/deckhouse/pull/10493) with broken tests on carelessness and broke the release branch :(.
It will fix the release and main branches.
It will fix the release branch.
```changes
type: fix
summary: fix for templates test
```
> [cni-cilium] fix template test

- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
Revert step five in Getting Started until 1.66 will be released
Ref: https://github.com/deckhouse/deckhouse/pull/9591
```changes
section: docs
type: fix
summary: Revert some steps for Bare Metal in the Getting Started until 1.66 will be released.
```
> [docs] Revert step five in Getting Started until 1.66 will be released

- ee/modules/500-operator-trivy/monitoring/grafana-dashboards/security/trivy.tpl
- ee/modules/500-operator-trivy/openapi/config-values.yaml
- ee/modules/500-operator-trivy/openapi/doc-ru-config-values.yaml
- ee/modules/500-operator-trivy/templates/configmap.yaml
- helm_lib/Chart.lock
- helm_lib/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/Chart.yaml
- helm_lib/charts/deckhouse_lib_helm/templates/_csi_node.tpl
- helm_lib/charts/deckhouse_lib_helm/templates/_monitoring_grafana_dashboards.tpl
- tools/validation/grafana_dashboard.go
This pr updates `operator-trivy` module with new configuration setting - `additionalVulnerabilityReportFields` which can be used to enrich trivy vulnerability reports with additional fields from trivy db.
Also, it updates Grafana dashboard delivery procedure with possibility to define a dashboard via go templates, fully or partially, - *.tpl files in `<module_name>/monitoring/grafana-dashboards/` directories are rendered before making their way to the resulting chart. 
The dashboard validation is also updated to check `*.tpl` files.
It allows users to add extra fields to Trivy vulnerability reports and these defined fields get automatically added to the Trivy Image Vulnerability Overview dashboard for filtering.
Closes #10427 
It's possible to define additional fields for vulnerability …
> [operator-trivy]  Add extra fields to vulnerability reports.

- modules/110-istio/templates/control-plane/iop.yaml
Enhancing upmeter-related resources ignoring by istiod.
The ENABLE_ENHANCED_RESOURCE_SCOPING flag extends the resources istiod will ignore by discoverySelectors in IOP. So, istiod will cool down a bit.
Also, [this flag is enabled by default in 1.22](https://github.com/istio/istio/issues/49696).
istiod has no logs about upmeter-related resources.
```changes
section: istio
type: fix 
summary: Enhancing upmeter-related resources ignoring by istiod
```
> [istio] Exclusion of the upmeter from Istio (in one more place)

- candi/cloud-providers/aws/openapi/cloud_discovery_data.yaml
- candi/cloud-providers/aws/terraform-modules/master-node/main.tf
- candi/cloud-providers/aws/terraform-modules/static-node/main.tf
- testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml
1. Cloud data discovery currently expects an AZ name in the format `ap-southeast-1a`. Updated regexp to support local AZs such as `ap-southeast-1-bkk-1a`.
2. If we create a master or static node in a local zone we must create an EIP in the network border group of that zone.
> If you have Local Zones or Wavelength Zones enabled, you can choose a network border group for AZs, Local Zones, or Wavelength Zones. Local Zones and Wavelength Zones may have different network border groups than the AZs in a Region to ensure minimum latency or physical distance between the AWS network and the customers accessing the resources in these Zones.
For example:
az: ap-southeast-1a - network border group: ap-southeast-1
az: ap-southeast-1b - network border group: ap-southeast-1
but
local az: …
> [cloud-providers][aws] fixes for deploying a cluster in a local zone

- candi/bashible/bundles/centos/all/004_install_mandatory_selinux_policies.sh.tpl
In the current version of Deckhouse, in bashible step `004_install_mandatory_selinux_policies.sh`  which installs settings for selinux, there is a condition according to which the allowed installation only if at the time of installation the selinux mode was `Enforced`. 
There is a problem that in an already deployed cluster it is impossible to switch the mode. Bashible not starting after change selinux mode.
I suggest removing the selinux status check.
I would only keep the check that the status check command works. This is needed to determine that the selinux module is present in the current package.
With this fix, the settings will always be created and it will be possible to switch the selinux mode in a deployed cluster
```changes
section: candi
type: fix 
summary: Change selinux …
```
> [candi][bashible] Change selinux configuration requirements in step 004_install_mandatory_selinux_policies.sh

- modules/150-user-authn/images/dex/Dockerfile
- modules/150-user-authn/images/dex/patches/README.md
- modules/150-user-authn/images/dex/patches/fix-offline-session-updates.patch
Add a patch to fix the problem with offline sessions that are not created/updated properly, which causes random refresh problems.
https://github.com/dexidp/dex/pull/3828
It affects token refreshing in all clusters.
```changes
type: fix
summary: Add a patch to fix the problem with offline sessions that are not created/updated properly, which causes random refresh problems.
```
> [user-authn] Fix offline session updates

- go.mod
- go.sum
- go_lib/hooks/ensure_crds/hook.go
- go_lib/hooks/ensure_crds/test_data/heritage.crd
- modules/000-common/crds/doc-ru-test-crd.yaml
- modules/110-istio/_crds/istio/0.990/test-crd.yaml
- modules/110-istio/_crds/istio/0.991/test-crd.yaml
- modules/110-istio/_crds/istio/0.992/test-crd.yaml
Considering that etcd has a default value of 1.5Mb, it was decided to set it to 2Mb, so that in most cases we would get a more informative error from Kubernetes, not just "short buffer"
```changes
type: fix
summary: Increased internal module CRD buffer
```
> [deckhouse-controller] Increased CRDs Installer buffer size

- deckhouse-controller/cmd/deckhouse-controller/start.go
- deckhouse-controller/pkg/controller/controller.go
Bumps addon-operator to support cache for helm resources manager.
Updates the controller-runtime manager's cache options and provides some other minor improvements.
The controller's manager cache should cache deckhouse.io api's objects like modules, module releases, etc.
Helm resources manager should cease listing objects when checking helm releases.
```changes
type: feature
summary: Update manager's cache.
```
> [deckhouse-controller] update manager's cache

- candi/version_map.yml
- modules/040-node-manager/images/cluster-autoscaler/patches/1.27/kruise-ads.patch
- modules/040-node-manager/images/cluster-autoscaler/patches/1.28/kruise-ads.patch
- modules/040-node-manager/images/cluster-autoscaler/patches/1.29/kruise-ads.patch
- modules/040-node-manager/images/cluster-autoscaler/patches/1.30/kruise-ads.patch
- modules/040-node-manager/images/cluster-autoscaler/patches/1.31/kruise-ads.patch
- modules/040-node-manager/images/cluster-autoscaler/patches/README.md
- modules/040-node-manager/images/cluster-autoscaler/werf.inc.yaml
Provides patches for 1.26-1.30 versions of the cluster autoscaler to support scaling for nodes running advanced daemonsets.
Without these patches, the cluster-autoscale of versions greater than 1.28 may experience problems scaling down a node running a pod created by an openkruise advanced daemonset. An example of such an error:
```
I1025 12:28:48.862141       1 cluster.go:160] node k8s-dev-worker-e5588484-5b8c9-vzkr7 cannot be removed: daemonset for d8-ingress-nginx/controller-nginx-b8sfm is not present, err: daemonset.apps "controller-nginx" not found
```
Also, these patches introduce yet additional logic when scaling down a node running advanced daemonset pods:
if a node group is set to something like: min:0 max:3, the autoscaler won't scale down the group to zero because last ADS pod …
> [node-manager] add patch for processing advanced daemonset pods

- modules/402-ingress-nginx/images/controller-1-10/Dockerfile
- modules/402-ingress-nginx/images/controller-1-10/patches/README.md
- modules/402-ingress-nginx/images/controller-1-10/patches/new-metrics.patch
- modules/402-ingress-nginx/images/controller-1-9/Dockerfile
- modules/402-ingress-nginx/images/controller-1-9/patches/README.md
- modules/402-ingress-nginx/images/controller-1-9/patches/new-metrics.patch
It provides new metrics for the nginx ingress controller.
Fixes #9914 
New metrics can be useful for analyzing nginx performance.
Worker processes:
Worker max connections:
Change worker max connections in the config map:
Open files limit:
```changes
type: feature
summary: Add worker_max_connections, worker_processes and worker_rlimit_nofile metrics.
impact: ingress-nginx controllers' pods will be recreated.
```
> [ingress-nginx] add max_worker_connection and max_worker_procesess metrics

- modules/200-operator-prometheus/crds/podmonitors.yaml
- modules/200-operator-prometheus/crds/probes.yaml
- modules/200-operator-prometheus/crds/prometheusrules.yaml
- modules/200-operator-prometheus/crds/scrapeconfigs.yaml
- modules/200-operator-prometheus/crds/servicemonitors.yaml
Add backup label to publicly used CRDs
Adding this label to CRD instructs `d8 backup cluster-config` command to backup all CRs of a Kind. It's great to have it at all publicly used CRDs. Since we allow direct use of the `PodMonitor`, `ServiceMonitor`, `ScrapeConfig`, `Probe` and `PrometheusRule` resources user may expect to find them in the backup as well.
We don't
`d8 backup cluster-config` command backups all CRs for these CRDs.
```changes
```
> [prometheus-operator] Add backup label to publicly used CRDs

- modules/150-user-authn/hooks/get_dex_client_crds.go
- modules/150-user-authn/hooks/get_dex_client_crds_test.go
- modules/150-user-authn/openapi/values.yaml
- modules/150-user-authn/templates/dex-client/secret.yaml
Fix [issue](https://github.com/deckhouse/deckhouse/issues/10172)
```changes
type: feature
summary: Add ability to set custom labels on autogenerated DexClient secret
```
> [user-authn] Add ability to set custom labels on autogenerated DexClient secret

- modules/300-prometheus/crds/customalertmanager.yaml
- modules/300-prometheus/crds/customprometheusrules.yaml
- modules/300-prometheus/crds/grafanaadditionaldatasources.yaml
- modules/300-prometheus/crds/grafanaalertschannel.yaml
- modules/300-prometheus/crds/grafanadashboarddefinition.yaml
- modules/300-prometheus/crds/prometheusremotewrite.yaml
Add backup label to publicly used CRDs
Adding this label to CRD instructs `d8 backup cluster-config` command to backup all CRs of a Kind. It's great to have it at all publicly used CRDs
We don't
`d8 backup cluster-config` command backups all CRs for these CRDs.
```changes
type: feature
summary: Added `backup.deckhouse.io/cluster-config` label to relevant module CRDs.
```
> [prometheus] Add backup label to publicly used CRDs

- candi/version_map.yml
Updated Deckhouse CLI to v0.4.0
```changes
section: candi
type: chore
summary: Update D8 CLI to 0.4.0
```
> [candi] Update D8 CLI to 0.4.0

- modules/200-operator-prometheus/crds/podmonitors.yaml
- modules/200-operator-prometheus/crds/probes.yaml
- modules/200-operator-prometheus/crds/prometheusrules.yaml
- modules/200-operator-prometheus/crds/scrapeconfigs.yaml
- modules/200-operator-prometheus/crds/servicemonitors.yaml
Fix value for label introduced in #10298 
`d8 backup cluster-config` command backups all CRs for these CRDs.
```changes
type: feature
summary: Fixed `backup.deckhouse.io/cluster-config` value.
```
> [operator-prometheus] Fix backup label value

- candi/cloud-providers/yandex/bashible/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/openstack/bashible/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/vcd/bashible/bootstrap-networks.sh.tpl
- ee/candi/cloud-providers/vsphere/bashible/bootstrap-networks.sh.tpl
Delete quotes for `primary_mac` value in bootstrap-network.  
Sometimes `primary_mac` value in `50-cloud-init.yaml` is wrapped in quotes, sometimes not.  This is a problem for correct execution bootstrap-network script.
This problem can affect the addition of new nodes to the cluster.
Correct execution of bootstrap-network script.
```changes
section: candi
type: fix
summary: Delete quotes for `primary_mac` value in bootstrap-network script.  
```
> [candi] del quotes for primary_mac value in bootstrap-network

- docs/documentation/pages/installing/README.md
- docs/documentation/pages/installing/README_RU.md
`VsphereInstanceClass` renamed to `VsphereClusterConfiguration`, `YandexInstanceClass` renamed to `YandexClusterConfiguration` as it should be.
Add links to additional supported cloud providers VCD and zVirt.
```changes
section: docs
type: chore
summary: fix mistakes in cloud cluster configuration resource names, add links to additional cloud providers
```
> [docs] fix mistakes in cloud cluster configuration resource names, add links to additional cloud providers

- docs/documentation/_data/sidebars/main.yml
- docs/site/_config.yml
Changed status of multitenancy-manager module from EE to CE.
Module has been moved from EE to CE in [PR](https://github.com/deckhouse/deckhouse/pull/10505).
```changes
section: docs
type:  chore
summary: Changed status of multitenancy-manager module from EE to CE.
```
> [docs] Changed status of multitenancy-manager module from EE to CE

- ee/modules/500-operator-trivy/openapi/config-values.yaml
- ee/modules/500-operator-trivy/openapi/doc-ru-config-values.yaml
- ee/modules/500-operator-trivy/template_tests/template_test.go
- ee/modules/500-operator-trivy/templates/configmap.yaml
Provides a new setting that allows downloading databases from insecure registries.
Some users may want to use the operator in an air-gapped environment, hosting images and databases in insecure registries.
Closes #10471 
Closes #6608 
Trivy-server is able to download databases/images from insecure registries.
```changes
type: chore
summary: Add a setting for downloading images from insecure registries.
```
> [operator-trivy] add insecure db registry and non-ssl registries

- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
In openSUSE, the PSI subsystem is disabled by default.
This fixes the EarlyOOMPodIsNotReady alert.
https://github.com/deckhouse/deckhouse/actions/runs/11786683587/job/32830473006
```changes
type: fix 
summary: e2e test disable earlyOomEnabled in yc
```
> [testing] e2e test disable earlyOomEnabled in yc

- testing/matrix/linter/rules/modules/oss.go
- testing/matrix/linter/rules/modules/oss_test.go
Corrected the spelling of 'Licence' to 'License' in `oss.go` and `oss_test.go` to maintain consistency and adhere to standard spelling. This should resolve potential configuration issues in Jekyll.
Ref:  #10593
```changes
type: chore
summary: Fix matrix test
```
> [testing]: Fix matrix test

- modules/402-ingress-nginx/templates/controller/admission.yaml
- modules/402-ingress-nginx/templates/validation.yaml
Fix validation rule
For multiply controllers we can have an error during the Ingress creation if we use `kubectl create` because it does not fille the `metadata.annotations` field with an empty object
```test-ingress.yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: test-spec
spec:
ingressClassName: nginx
rules:
- host: test-spec.apps.lmru.tech
http:
paths:
- backend:
service:
name: documentation
port:
name: http
path: /
pathType: ImplementationSpecific
```
```shell
ingress.networking.k8s.io/test-spec created
```
```changes
type: fix
summary: Fix ingress validation rule for multiply ingress-controllers.
```
> [ingress-class] Fix ingress class validation rule

- docs/documentation/_data/deckhouse-alerts.yml
- modules/040-node-manager/monitoring/prometheus-rules/early-oom.tpl
- modules/040-terraform-manager/monitoring/prometheus-rules/terraform-manager/terraform-state-exporter.tpl
- modules/110-istio/monitoring/prometheus-rules/versions.tpl
- modules/340-monitoring-custom/monitoring/prometheus-rules/reserved-domain.tpl
- tools/helm_generate/runners/alert_templates/template_values/040-node-manager.yaml
- tools/helm_generate/runners/alert_templates/template_values/110-istio.yaml
- tools/helm_generate/runners/alert_templates/template_values/340-monitoring-custom.yaml
- tools/helm_generate/runners/alert_templates/template_values/340-monitoring-kubernetes.yaml
- tools/helm_generate/runners/alert_templates/template_values/402-ingress-nginx.yaml
Fix `publicDomainTemplate` in alert templates.
```changes
section: tools
type: fix
summary: |
Fix `publicDomainTemplate` in alert templates.
```
> [docs] Fix publicDomainTemplate in alert templates

- docs/documentation/_data/deckhouse-alerts.yml
- ee/se/modules/380-metallb/hooks/check_requirements_for_upgrade.go
- ee/se/modules/380-metallb/hooks/check_requirements_for_upgrade_test.go
- ee/se/modules/380-metallb/hooks/common_test.go
- ee/se/modules/380-metallb/hooks/types.go
- ee/se/modules/380-metallb/hooks/typos.go
- ee/se/modules/380-metallb/monitoring/prometheus-rules/metallb.yaml
- ee/se/modules/380-metallb/requirements/check.go
- ee/se/modules/380-metallb/requirements/check_test.go
Add a check of the settings of the `metallb` module and its resources for compliance with the requirements of the new version of the module.
This pr extends the [previous one](https://github.com/deckhouse/deckhouse/pull/10289).
We require the customer to change the settings in the cluster themselves before cluster upgrade.
To handle [the new feature](https://github.com/deckhouse/deckhouse/pull/9658) in next release.
`Deckhouse` can't be upgraded until the settings meet the new module version requirements:
- All custom IPAddressPools and L2Advertisements are in the `d8-metallb` namespace.
- There are no `layer2` and `bgp` pools in the cluster at the same time.
- In custom L2Advertisements, if there are nodeSelectors, there is an element and this element consists of matchLabels (not …
> [metallb] Extended pre-upgrade compatibility configuration check

- testing/cloud_layouts/script.sh
Abandoned the use of yq in one place in the testing script in favor of python.
Add ignoring certificate validity in tests
Reduced the number of downloadable files for the tests to work.
e2e upgrade tests passed
```changes
type: chore
summary: Abandoned the use of yq in one place in the testing script in favor of python
```
> [testing] Abandoned the use of yq in one place in the testing script in favor of python

- dhctl/pkg/system/node/local/command.go
- dhctl/pkg/system/node/local/command_test.go
Fixed a data race that occured during calls to `*Command.Run()` in local cmd executions. The reason for race has been the `sync.WaitGroup`'s `Wait()` method was called before the `scanLines()` would start in a separate goroutine and call `Add(1)` on that same `WaitGroup`. This resulted in a race between reading stdout buffer and writing into it.
This fixes a bug that could potentially break installation process in standalone mode.
```changes
section: dhctl
type: fix
summary: Fix data race in local NodeInterface command executor
```
> [dhctl] fix data race in local NodeInterface command executor

- ee/modules/500-operator-trivy/openapi/config-values.yaml
- ee/modules/500-operator-trivy/openapi/doc-ru-config-values.yaml
Fix description for  `insecureDbRegistry` and   `insecureRegistries` of the operator-trivy module.
Ref: https://github.com/deckhouse/deckhouse/pull/10559
```changes
section: docs
type: chore
summary: Fix description for  `insecureDbRegistry` and   `insecureRegistries` of the operator-trivy module.
```
> [operator-trivy] fix description for `insecureDbRegistry` and   `insecureRegistries`

- docs/documentation/.helm/templates/_rewrites.tpl
- docs/documentation/.werf/nginx.conf
- docs/documentation/_data/sidebars/main.yml
- docs/documentation/_includes/revision_comparison_detail_table.liquid
- docs/documentation/_plugins/custom_hooks.rb
- docs/documentation/generate_cluster_configuration.sh
- docs/documentation/modules_generate_configuration.sh
- docs/documentation/modules_generate_cr.sh
- docs/documentation/modules_generate_ossinfo.sh
- docs/documentation/modules_list.sh
- docs/documentation/modules_menu_skip
- docs/documentation/modules_prepare.sh
- docs/documentation/pages/DECKHOUSE_CONFIGURE.md
- docs/documentation/pages/DECKHOUSE_CONFIGURE_RU.md
- docs/documentation/werf-web.inc.yaml
- modules/810-documentation/templates/ingress.yaml
- Adjust module naming to remove numeric prefixes in module URL on the site and in the `documentation` module.
- Build refactoring to improve efficiency.
```changes
section: docs, documentation
type: chore
summary: Get rid of numeric prefixes in module URL.
```
> [docs] Get rid of numeric prefixes in module URL on the site

- modules/015-admission-policy-engine/templates/mutatingwebhookconfiguration.yaml
Set reinvocationPolicy to `IfNeeded` 
MutatingWebhookConfiguration for gatekeeper is generic. It can be used in different situations and sometime we have to rerun the mutating webhook to keep mutated object up-to-date.
This option will allow to use the generic gatekeeper mutation with other webhooks, like istio
```changes
section: dmission-policy-engine
type: feature
summary: Set MutatingWebhookConfiguration reinvocationPolicy to `IfNeeded` to enable the use of webhook with other mutating webhooks
```
> [admission-policy-engine] Change MutatingWebhookConfiguration reinvocationPolicy

- docs/site/_includes/getting_started/dynamix/STEP_ENV.md
- docs/site/_includes/getting_started/dynamix/STEP_ENV_RU.md
- docs/site/_includes/getting_started/global/partials/NOTICES.liquid
- docs/site/_plugins/gs_generator.rb
Add warnings for SpaceVM, Red, and Dynamix platforms in the getting started.
```changes
section: docs
type: chore
summary: Add warnings for SpaceVM, Red, and Dynamix platforms in the getting started.
```
> [docs][getting started] Add notices for for SpaceVM, Red, and Dynamix

- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
Signed-off-by: Aleksey Gavrilov <alexey.gavrilov@flant.com>
(cherry picked from commit 425c205c810789e8be046eba694ca780c1f71558)
In openSUSE, the PSI subsystem is disabled by default.
This fixes the EarlyOOMPodIsNotReady alert.
https://github.com/deckhouse/deckhouse/actions/runs/11786683587/job/32830473006
```changes
type: fix 
summary: e2e test disable earlyOomEnabled in yc
```
> [testing] e2e test disable earlyOomEnabled in yc (#10583)

- dhctl/pkg/operations/converge/converger.go
this pr add human readable error when ssh host flag is not provided on dhctl converge
this will print human readable error if --ssh-host flag is not provided
output error is 
```
Not enough flags were passed to perform the operation.
Use dhctl converge --help to get available flags.
Ssh host flag is not provided. Need to pass --ssh-host
```
```changes
section: dhctl
type: fix 
summary: Add human readable error on dhctl converge except
```
> [dhct] Add human readable error on dhctl converge except

- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/operations/converge/infra/hook/controlplane/drain.go
- dhctl/pkg/operations/converge/infra/hook/controlplane/hook_for_destroy_pipeline.go
Skip remove labels if node was not found during converge.
Remove second converge operation.
Manual instruction for remove master does not work because in the instruction we delete node object and converge fail if node does not exist.
Mistake in the code run converge two times and second time without lock
Documentation does not work
```changes
section: dhctl
type: fix
summary: Skip remove labels if node was not found during converge.
---
section: dhctl
type: fix
summary: Do not run converge second time.
```
> [dhctl] Converge. Skip remove labels if node was not found

- docs/documentation/_data/supported_versions.yml
Rework recommendations for Quay registry.
`trivy-checks` cannot be pushed with error like this:
```
Nov 14 22:16:32.881 INFO  ║ [1 / 1] Pushing image kovalkov-quay.ru-central1.internal/user/dkp/security/trivy-checks:0
Nov 14 22:16:33.284 WARN  ║ It looks like you are using Project Quay registry and it is not configured correctly for hosting Deckhouse.
See the docs at https://deckhouse.io/documentation/v1/supported_versions.html#container-registry for more details.
TL;DR: You should retry push after allowing some additional types of OCI artifacts in your config.yaml as follows:
FEATURE_GENERAL_OCI_SUPPORT: true
ALLOWED_OCI_ARTIFACT_TYPES:
"application/vnd.aquasec.trivy.config.v1+json":
- "application/vnd.aquasec.trivy.db.layer.v1.tar+gzip"
"application/octet-stream":
- …
```
> [docs] Rework recomendations for Quay

- docs/documentation/_data/supported_versions.yml
- docs/site/backends/docs-builder-template/layouts/partials/openapi/format-schema.html
There is a error.  When docs-builder can't render templates, not all containers of the frontend deployment are ready, but something bad happens.  Investigating the issue.
If we have a global build error (affect all site), we need to mark readiness check to false, to respond with only good site
* global build error - our site has error when build default platform documentation
* module build error - will skip module build and try to rebuild all other site pages
Documentation site show result with errors and pods are still running in cluster
```
documentation-b5dbff57c-9rj95                        2/2     Running
```
Documentation site show 503 Service Temporarily Unavailable nginx page and pods are not ready in cluster
```
documentation-b5dbff57c-9rj95                        1/2 …
```
> [docs][module-builder] Improve error handling

- docs/site/backends/registry-modules-watcher/internal/backends/pkg/registry-scaner/cache/cache.go
In docs-builder, there was a problem in the logic of work. We check the modules for which we need to rebuild the documentation. Next, we define the modules that should be removed. And as a result, we get a complete removal of the documentation for the module.
To avoid such a situation, we need to reverse the sequence. That is, first we have to make a list of modules that need to be removed, and then add new modules that need to be rebuilt.
In order for module documentation to be collected and updated correctly. And at the same time, the documentation of modules that were removed from the register was deleted from the site.
When updating the documentation of modules, they are reflected on the site. When a module is uninstalled, its documentation is deleted from the site.
```changes …
```
> [docs] fix: delete old module docs then upload new

- modules/150-user-authn/hooks/get_dex_client_crds.go
- modules/150-user-authn/hooks/get_dex_client_crds_test.go
Some additionals labels and annotations for exlude in [PR](https://github.com/deckhouse/deckhouse/pull/10536)
helm/werf.io exclude for transfer to secrets
```changes
type: feature
summary: helm/werf.io labels exclude for transfer to secrets
```
> [user-authn] Add ability to set custom labels on autogenerated DexClient secret (additional labels/annotations)

- modules/040-node-manager/hooks/create_master_node_group_test.go
- modules/040-node-manager/hooks/get_crds_test.go
- modules/140-user-authz/hooks/handle_authorization_rules_test.go
- modules/140-user-authz/hooks/handle_cluster_authorization_rules_test.go
- modules/150-user-authn/hooks/get_dex_providers_crds_test.go
- modules/402-ingress-nginx/hooks/get_ingress_controllers_test.go
- testing/hooks/init.go
Provides defaulting for objects created in test environments via `KubeStateSet`/patch collector or kube client.
Closes #10459 
When an object is defined in a test environment, it's empty fields are filled with default values, in accordance with the object's Custom Resource Definition.
```changes
section: tests
type: chore
summary: Provide defaulting for Custom Resource in test environments.
```
> [testing] defaulting for CRs

- .github/dependabot.yml
- modules/000-common/images/vxlan-offloading-fixer/go.mod
- modules/000-common/images/vxlan-offloading-fixer/main.go
- modules/000-common/images/vxlan-offloading-fixer/werf.inc.yaml
- modules/021-cni-cilium/templates/_agent-daemonset.tpl
- modules/021-cni-cilium/templates/safe-agent-updater/daemonset.yaml
- modules/035-cni-flannel/templates/daemonset.yaml
- testing/library/images_tags_generated.go
An `init container` has been added to check and disable `tunnel segmentation offloading` on interfaces if a Node is running on VMware.
On nodes that are VMware virtual machines, enabling VXLAN leads to network errors. For example:
```
kubectl -n d8-ingress-nginx logs controller-nginx-xxxxx
...
E0923 15:17:59.744809       7 main.go:234] "Unexpected error discovering Kubernetes version" err="Get \"https://10.122.0.1:443/version\": dial tcp 10.122.0.1:443: i/o timeout" attempt=0
E0923 15:18:30.816854       7 main.go:234] "Unexpected error discovering Kubernetes version" err="Get \"https://10.122.0.1:443/version\": dial tcp 10.122.0.1:443: i/o timeout" attempt=1
```
and
```
kubectl -n d8-cni-cilium exec -ti agent-ppppp -c cilium-agent -- cilium-health status
...
node-yyyy:
Host connectivity …
```
> [cni-cilium, cni-flannel] Fixing a packet dropping issue when using VXLAN on a cluster running on VMware virtual machines

- dhctl/pkg/config/deckhouse_config.go
- dhctl/pkg/config/deckhouse_config_test.go
- dhctl/pkg/kubernetes/actions/deckhouse/install.go
- dhctl/pkg/kubernetes/actions/deckhouse/install_test.go
- dhctl/pkg/kubernetes/actions/deckhouse/module_config.go
- dhctl/pkg/kubernetes/actions/deckhouse/module_config_test.go
- dhctl/pkg/kubernetes/actions/manifests/manifests.go
- dhctl/pkg/kubernetes/actions/manifests/manifests_test.go
- dhctl/pkg/kubernetes/actions/resources/resouce_ready.go
- dhctl/pkg/kubernetes/actions/resources/resources.go
- dhctl/pkg/kubernetes/actions/task.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-deckhouse.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-resources.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/operations/bootstrap/steps.go
- dhctl/pkg/operations/bootstrap/steps_test.go
- dhctl/pkg/operations/commander/attach/attacher.go
- dhctl/pkg/operations/commander/detach/detacher.go
- dhctl/pkg/template/resources_test.go
- dhctl/pkg/template/testdata/resources/order.yaml
There is a situation where the cluster bootstrap terminates with an error. For this, we need to add module config `global` with parameter `modules.https.mode` `CustomCertificate` and CloudPermanent nodegroup `system` and for example `worker` with at least one replica. We have the following sequence:
- creating module configs
- cloud permanent node creation
- creating resources (such as the secret for `CustomCertificate` mode)
After applying module configs `global` with the `modules.https.mode` `CustomCertificate` parameter and creating nodegroup system, deckhouse hangs with the error
```
Queue 'main': length 30, status: 'sleep after fail for 32s (17s left of 32s delay)'
1. ModuleHookRun:main:kubernetes:150-user-authn/hooks/https/copy_custom_certificate.go:custom_certificates:OperatorStartu …
```
> [dhctl] Add tasks for moduleconfigs routines for post bootstrap and creating with resources phases

- deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go
- ee/fe/modules/300-prometheus/.build.yaml
- ee/fe/modules/300-prometheus/hooks/cm_check.go
- ee/fe/modules/300-prometheus/images/prometheuspp/werf.inc.yaml
- ee/fe/modules/300-prometheus/openapi/openapi-case-tests.yaml
- ee/fe/modules/300-prometheus/openapi/values.yaml
- ee/fe/modules/300-prometheus/templates/prometheus/pp/grafana-additional-ds.yaml
- ee/fe/modules/300-prometheus/templates/prometheus/pp/ingress.yaml
- ee/fe/modules/300-prometheus/templates/prometheus/pp/pdb.yaml
- ee/fe/modules/300-prometheus/templates/prometheus/pp/prometheus.yaml
- ee/fe/modules/300-prometheus/templates/prometheus/pp/service.yaml
- testing/library/images_tags_generated.go
- tools/build_includes/modules-FE.yaml
- tools/build_includes/modules-with-dependencies-FE.yaml
- tools/build_includes/modules-with-exclude-FE.yaml
Add ability to run Prom++ in parallel mode with classic Prometheus.
It's first to migrate to Prometheus to Prom++.
Yes, we need. To have possibility run new monitoring subsystem in cluster in stables channels. 
**Steps:**
- Deploy Deckhouse  from PR to cluster where the ConfigMap `prometheus-pp-envs` does not exist.
**Expected Result:**
- No objects related to Prom++ were created in the cluster.
- All Prometheus components continued to function as expected.
- Data scraping occurred in full, without interruption.
- Historical data was displayed correctly in the UI.
**Actual Result:**
- Behavior matched expected result; no Prom++ components were deployed.
- Prometheus functionality remained unaffected, with historical data and scraping functioning correctly.
---
**Steps:**
- Created the …
> Backport Prom++ to 1.65

- candi/control-plane-kubeadm/config.yaml.tpl
Fix kubeadm template. Error occurs if serviceAccount.issuer is added to mc control-plane-manager but additionalAPIAudiences is not specified
This fixes a bug in the kubeadm template
ServiceAccount Issuer has been successfully updated, no additionalAPIAudiences need to be specified
Test case 1:
only issuer
```yaml
metadata:
name: control-plane-manager
spec:
version: 1
enabled: true
settings:
apiserver:
serviceAccount:
issuer: https://api.example.com
```
```bash
cat /etc/kubernetes/manifests/kube-apiserver.yaml | grep -iE "issue|audience"
- --api-audiences=https://kubernetes.default.svc.cluster.local
- --service-account-issuer=https://api.example.com
```
Test case 2:
issuer + additionalAPIAudiences
```yaml
apiVersion: …
```
> [control-plane-manager] fix kubeadm template when changing ServiceAcciount Issuer

- deckhouse-controller/pkg/controller/module-controllers/source/controller.go
- deckhouse-controller/pkg/controller/module-controllers/source/helpers.go
It provides fix.
Deleting a module source with a non existing module, causes not found error.
No error during deleting a module source with a non existing module.
```changes
type: fix
summary: Fix source deletion error.
```
> [deckhouse] fix source deletion error

- modules/values-default.yaml
- modules/values-managed.yaml
It provides fix for default and managed bundles to enable multitenancy-manager.
multitenancy-manager should be enabled by default.
multitenancy-manager should be enabled by default.
multitenancy-manager enabled by default.
```changes
type: fix 
summary: Enable multitenancy-manager by default in default and managed bundles.
```
> [multitenancy-manager] fix default and managed bundles

- deckhouse-controller/pkg/apis/deckhouse.io/validation/register.go
- deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_kubernetes_version.go
- deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_module_config.go
- deckhouse-controller/pkg/apis/deckhouse.io/validation/validate_update_policy.go
- modules/002-deckhouse/templates/admission/validation.yaml
It provides update policy validation.
We need to prohibit creating module configs with non existing update policy, and prohibit deleting update policy that used by a  module config.
- delete update policy that used by a module config.
```
root@dev-master-0:~# k delete -f mup.yaml 
Error from server: error when deleting "mup.yaml": admission webhook "update-policies.deckhouse-webhook.deckhouse.io" denied the request: the 'test-alpha' update policy used in the 'test' module config
```
- create module configs with non existing update policy
```
root@dev-master-0:~# kubectl edit mc test 
error: moduleconfigs.deckhouse.io "test" could not be patched: admission webhook "module-configs.deckhouse-webhook.deckhouse.io" denied the request: the 'test1' module policy does not exist
```
```changes …
```
> [deckhouse] add update policies validation

- modules/021-cni-cilium/images/bin-cilium/patches/005-ebpf-dhcp-server.patch
- modules/021-cni-cilium/images/bin-cilium/werf.inc.yaml
- modules/021-cni-cilium/templates/configmap.yaml
Add dhcp server for pods implemented in cilium agent traffic control ebpf hook of lxc interfaces.
This dhcp server has fewer options than the virt-launcher dhcp server. List of not implemented options:
- 26 Interface MTU
- 121 Classless Static Route
- 119 Domain Search(only one basic fqdn cluster.local)
- 12 Host Name
- 15 Domain Name
DVP uses the DHCP for configuring guest network interfaces. It is now implemented by embedded to virt-launcher dhcp server which is linked to internal bridge in VM Pod. 
For optimizing purposes we need to redesign the in-Pod VM network scheme and get rid of internal bridge. So, we won't be able to use embedded dhcp server.
Every Pod in cluster will be able to request it's IP via dhcp:
```
root@nginx-77b4fdf86c-bxz5w:/# dhclient eth0 -v
...
Listening on …
```
> [cni-cilium] ebpf-powered dhcp server for pods

- docs/documentation/_includes/revision_comparison_detail_table.liquid
Add fixed width for cells with icon for the comparison table.
```changes
section: docs
type: chore
summary: Add fixed width for cells with icon for the comparison table.
```
> [docs] Add fixed width for cells with icon

- modules/500-openvpn/images/ovpn-admin/templates/client.conf.tpl
- modules/500-openvpn/templates/openvpn/configmap.yaml
OpenVPN server configuration parameters have been changed
When upgrading from OpenVPN 2.5.6 to OpenVPN 2.6.12, it became impossible to connect to the server due to incorrect configuration. The server used outdated options in the configuration.
This PR fix this issue
Clients can't connect
Old and new OpenvVPN can connect to openvpn using new and old client config
```changes
type: fix
summary: Fix supported ciphers list.
```
> [openvpn] fix supported ciphers list

- .github/workflow_templates/cve-weekly.yml
- .github/workflows/cve-weekly.yml
Weekly cve tests time out due to lack of resources on runners
https://github.com/deckhouse/deckhouse/actions/workflows/cve-weekly.yml
Change the runner for cve scanner to a more efficient one
Weekly cve tests are running smoothly
```changes
section: ci
type: fix
summary: Change the runner for cve scanner to a more efficient one.
```
> fix: change cve scaner runner

- modules/300-prometheus/crds/doc-ru-prometheusremotewrite.yaml
- modules/300-prometheus/crds/prometheusremotewrite.yaml
The deckhouse controller does not seem to support `patternProperties` for built-in modules OpenAPI spec, thus the #10317 merged recently breaks the prometheus module and stuck the controller's queue.
This PR replaces `patternProperties` with a comprehensive list of properties that are allowed at the moment.
Fixes a regression introduced in ##10317 
We don't, since the bug is not yet released, but we have to merge it ASAP to fix the main branch.
```changes
type: fix
summary: Fix headers configuration for PrometheusRemoteWrite resource.
```
> [prometheus] Fix of properties prometheus remote write

- Makefile
- modules/500-dashboard/images/dashboard/werf.inc.yaml
- modules/500-openvpn/images/openvpn/werf.inc.yaml
- modules/500-openvpn/images/ovpn-admin/werf.inc.yaml
- modules/500-openvpn/images/pmacct/werf.inc.yaml
- tools/lint-src-artifact/lint-src-artifact.go
Added a simple linting of src-artifact stapel build script via `make lint-src-artifact`. It will check that everything based on the `common/src-artifact` has `-src-artifact` suffix in the name and that it explicitly deletes `.git` dirs from everything that it clones. Also fixed a few src-artifact builds that were not removing `.git`.
We want to enforce some rules regarding `src-artifact` usage. This will lay the groundwork for it.
```changes
section: tools
type: chore
summary: implement src-artifact usage linter
```
> [tools] implement src-artifact usage linter

- modules/500-openvpn/images/ovpn-admin/werf.inc.yaml
Quickfixed `rm -r .git` in ovpn-admin build 
```changes
type: fix
summary: Fix .git removal in ovpn-admin image
```
> [openvpn] Fix .git removal

- modules/160-multitenancy-manager/images/multitenancy-manager/cmd/main.go
- modules/160-multitenancy-manager/images/multitenancy-manager/pkg/controller/project/main.go
- modules/160-multitenancy-manager/images/multitenancy-manager/pkg/controller/template/main.go
- modules/160-multitenancy-manager/images/multitenancy-manager/pkg/manager/project/main.go
- modules/160-multitenancy-manager/images/multitenancy-manager/pkg/manager/project/utils.go
- modules/160-multitenancy-manager/images/multitenancy-manager/pkg/manager/template/main.go
- modules/160-multitenancy-manager/images/multitenancy-manager/pkg/manager/template/utils.go
Improves the controller's bootstrap sequence by leveraging `retry.OnError` function to retry Init steps in case the controller's webhooks haven't started yet.
The controller starts smoothly, without multiple restarts.
The controller starts smoothly, without multiple restarts.
```changes
type: chore
summary: Add retry on startup.
```
> [multitenancy-manager] add retry on startup

- .github/ci_templates/build.yml
- .github/ci_templates/e2e_tests.yml
- .github/scripts/js/ci.js
- .github/scripts/js/constants.js
- .github/scripts/js/e2e/slash_workflow_command.js
- .github/workflow_templates/build-and-test_release.yml
- .github/workflow_templates/e2e.abort.multi.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vcd.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vcd.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Adds an option to build any edition on release issue with `/build/[edition]` command, and run e2e tests on any edition with `/e2e/use/edition/[edition]` command.
Resolves #4682 
Currently, e2e testing of various Deckhouse editions is somewhat inconvenient. This feature helps to streamline pre-release testing
Support for comment commands `/build/[edition]` and `/e2e/use/edition/[edition]`
```changes
section: ci
type: feature
summary: Add option to test any edition on release issue.
```
> [ci] Add option to test any edition on release issue

- .github/ci_templates/e2e_tests.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vcd.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vcd.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
- ee/candi/cloud-providers/vsphere/terraform-modules/master-node/main.tf
- testing/cloud_layouts/script.d/wait_cluster_ready/test_script.sh
- testing/cloud_layouts/vSphere/Standard/configuration.tpl.yaml
- testing/cloud_layouts/vSphere/Standard/resources.yaml
For convenience, it is necessary to transport e2e tests to another site
Prepare secrets and configuration to run testing on another VSphere platform
Test environments are launched and successfully completed on another site
Prepare secrets and configuration to run testing on another VSphere platform.
```changes
section: ci
type: chore
summary: Prepare secrets and configuration to run testing on another VSphere platform.
```
> transfer VSphere e2e

- .github/ci_templates/e2e_tests.yml
- .github/workflows/e2e-daily.yml
Fix automatic daily e2e test.
Daily automatic e2e test currently fails as not all expected variables are passed on automated run.
Working daily e2e test.
```changes
type: fix
summary: Fix automatic daily e2e test.
```
> [testing] Fix automatic daily e2e test

- ee/modules/015-admission-policy-engine/hooks/update_trivy_provider_config.go
- ee/modules/015-admission-policy-engine/hooks/update_trivy_provider_config_test.go
- ee/modules/015-admission-policy-engine/templates/trivy-provider/configmap.yaml
- ee/modules/015-admission-policy-engine/templates/trivy-provider/statefulset.yaml
- modules/015-admission-policy-engine/openapi/values.yaml
Fix trivy-provider configuration
Admission-policy-engine can stuck on bootstrap.
Because of BeforeHelm it generates the error:
```
* Create object: v1/ConfigMap/d8-admission-policy-engine/trivy-provider: namespaces "d8-admission-policy-engine" not found
```
and we can't run trivy-provider pod without the cm
```
NAME                     DATA   AGE
constraint-exporter      2      377d
istio-ca-root-cert       1      20d
kube-rbac-proxy-ca.crt   1      377d
kube-root-ca.crt         1      377d
```
enable the flag
```
spec:
enabled: true
settings:
denyVulnerableImages:
enabled: true
```
after
```
apiVersion: v1
data:
TRIVY_INSECURE: "false"
kind: ConfigMap
metadata:
annotations:
meta.helm.sh/release-name: admission-policy-engine
meta.helm.sh/release-namespace: d8-system
creationTimestamp: …
```
> fix provider bootstrap

- .github/workflow_templates/e2e-daily.yml
- .github/workflows/e2e-daily.yml
Enable EKS on daily e2e test.
```changes
type: feature
summary: Enable EKS on daily e2e test.
```
> [testing] Enable EKS on daily e2e test

- .github/ci_templates/e2e_tests.yml
- .github/scripts/js/ci.js
- .github/scripts/js/constants.js
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vcd.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vcd.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Fix e2e tests on alternative editions (non-FE) for PRs
Previous change to e2e test logic (changed in #9769) did not work with different ways to set edition. Fixed.
It should be possible to run e2e tests on alternative editions as was previously possible.
```changes
type: fix
summary:  Fix e2e tests on alternative editions for PRs.
```
> [testing] Fix e2e tests on alternative editions for PRs

- modules/040-node-manager/hooks/create_master_node_group_test.go
- testing/hooks/init.go
Provides `ApplyCRDefaults` method to the hook executor which can be used to enrich a CR with default values.
In some tests it may be desirable to create a CR definition from the scratch with default values to use it in tests.
Default values for a CR in the test environment can be set on demand.
```changes
type: chore
summary: Add a handler to apply default values to CRs.
```
> [testing] add a handler to apply default values to CRs

- .werf/werf-dev-install.yaml
Added locale package to install image
Resolve issue #10713
Using install image, users won't see a warning about locale
```changes
section: ci
type: fix
summary: Add locale package to install image, to fix warning about locale.
```
> Add locale package to install image

- candi/bashible/common-steps/node-group/000_add_node_users.sh.tpl
Fix for creating system users through the NodeUser mechanism:
1. `candi` iterates over all `nodeUser` entries in alphabetical order. Currently, if an unexpected error occurs while creating one of the users, the creation of subsequent users is halted. After the fix, an error will be returned for the failed user, and the system will attempt to create the next user in the list.
2. If a user with the same username but a different UID already exists in the system, an error will be returned:
```shell
kubectl get nodeuser ansible
NAME      UID      ISSUDOER   EXTRAGROUPS   NODEGROUPS   ERRORS                                                                                            AGE
ansible   100099   true                     ["master"]   {"yc-10676-tt-master-0":"User ansible already exists …
```
> [candi] nodeUser creation fix

- modules/150-user-authn/hooks/get_dex_client_crds.go
- modules/150-user-authn/hooks/get_dex_client_crds_test.go
- modules/150-user-authn/templates/dex-client/secret.yaml
fix [pr](https://github.com/deckhouse/deckhouse/pull/10536)
Disable transfer some label keys from dexclient to dexclient secret
```
"app",
"heritage",
"module",
"name",
"app.kubernetes.io/managed-by",
"argocd.argoproj.io/secret-type",
"argocd.argoproj.io/instance",
"certmanager.k8s.io/certificate-name",
```
> [user-authn] Fix dexclient secret recreate and add labelKeysToIgnore

- dhctl/pkg/kubernetes/actions/converge/master_node_group_controller.go
- dhctl/pkg/operations/converge/infra/hook/controlplane/kube-proxy.go
- dhctl/pkg/system/node/ssh/frontend/agent.go
Copy the SSH private keys provided by the user and the generated SSH private key(for a special user created for converge) to a new SSH session.
If we try to converge through bastion, we will get an access denied error.
```changes
section: dhctl
type: fix
summary: Fix converge through bastion
```
> [dhctl] Fix converge through bastion

- docs/site/werf.yaml
Use data for DVP topnav from the API and remove the stub.
```changes
section: docs
type: chore
summary: Use data for DVP topnav from the API.
```
> [docs] Use data for DVP topnav from the API

- modules/015-admission-policy-engine/webhooks/validating/security_policy.py
Fixes 
```
bash-5.2$ ./shell-operator queue list
Queue 'main': length 12, status: 'sleep after fail for 32s (29s left of 32s delay)'
1. EnableKubernetesBindings:::015-admission-policy-engine/webhooks/validating/security_policy.py:EnableKubernetesBindings:failures 172:run monitor: jqFilter: libjq filter '{
"name": .metadata.name,
"references": [.spec.policies.verifyImageSignatures[].reference]
}
': 'Cannot iterate over null (null)'
```
See above.
Hooks doesn't fail if there are no security policies without `.verifyImageSignatures` parameter.
```changes
type: chore
summary: Fix security-policy validation hook.
```
> [admission-policy-engine] fix jqfilter

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
Save information about built image (Werf render file and Werf buiild report file) locally.
```changes
section: ci
type: chore
summary: Save information about built image.
```
> [ci] Temporary: save info about built image

- .github/ci_templates/build.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
This reverts commit fb566e8c593b9f9dc054ba555268f9976f3c0589 (https://github.com/deckhouse/deckhouse/pull/10911)
```changes
section: ci
type: chore
summary: Revert:  Save build info (#10911)
```
> Revert "[ci] Save build info (#10911)"

- candi/version_map.yml
Updated Deckhouse CLI to latest
```changes
section: candi
type: chore
summary: Update D8 CLI to 0.7.0
```
> [candi] Update D8 CLI to 0.7.0

- .github/ci_templates/e2e_tests.yml
- .github/workflow_templates/build-and-test_release.yml
- .github/workflows/build-and-test_release.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vcd.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Prevent SE edition from being built if SE-plus was requested.
Current implementation for triggers of different editions tests inclusion rather than equality of edition names, causing build of different but similarily-named edition. Fixed.
```changes
section: ci
type: fix
summary: Prevent SE edition from being built if SE-plus was requested.
```
> [ci] Prevent SE edition from being built if SE-plus was requested

- docs/site/_includes/getting_started/global/partials/NOTICES.liquid
Changed info about editions in Getting Started  private environment.
```changes
section: docs
type:  chore
summary: Changed info about editions in Getting Started  private environment.
```
> [docs] Changed info about editions in Getting Started  private environment

- ee/be/modules/350-node-local-dns/images/iptables-loop/iptables-loop.sh
Fix stuck in iptables-loop script.
Sometimes the iptables loop script can get stuck after throwing exit code 1 (inotifywatch continues to watch file, but second part of pipe doesn't apply). As a result, no iptables rule is created and node-local-dns becomes unusable. 
Container iptables-loop will exit if entrypoint throws exit code. 
```changes
type: fix
summary: Fix stuck in iptables-loop script.
```
> [node-local-dns] fix stuck in iptables-loop

- testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/EKS/WithoutNAT/resources.yaml
We have bug in the main branch with global.storageClass, but we should use global.modules.storageClass in the future anyway.
EKS e2e was failed
```changes
section: tests
type: fix
summary: Fix eks e2e
```
> [tests] Fix eks e2e

- candi/bashible/common-steps/all/011_disable_floppy_drive.sh.tpl
Fix for #9761
Use `make-initrd` in  disable floppy step for altlinux.
```changes
section: candi
type: fix
summary: fix disable floppy drive step
```
> [candi] fix disable floppy drive step

- .github/ci_templates/e2e_tests.yml
- .github/workflow_templates/e2e-daily.yml
- .github/workflow_templates/e2e.abort.multi.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vcd.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vcd.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
K8s version for e2e tests is different from default k8s version in DKP
Currently the default k8s version is 1.29. e2e tests run on version 1.27. You need to make e2e tests run on version 1.29
e2e tests are run on version 1.29
```changes
section: ci
type: chore
summary: Change default k8s version for e2e.
```
> chore: change default k8s version for e2e

- ee/modules/500-operator-trivy/hooks/sbom_reports_cleanup.go
- ee/modules/500-operator-trivy/hooks/sbom_reports_cleanup_test.go
- ee/modules/500-operator-trivy/openapi/config-values.yaml
- ee/modules/500-operator-trivy/openapi/doc-ru-config-values.yaml
- ee/modules/500-operator-trivy/templates/deployment.yaml
Adds yet another setting for the module  - `disableSBOMGeneration`, which controls if the operator should generate SBOM reports when scanning images. By default it's set to `false`. Also, if `disableSBOMGeneration` transitions from `false` to `true`, `sbom_reports_cleanup` hook is executed once deleting current sbom reports from the cluster.
Having generation SBOM reports turned on in a cluster doesn't look like a good default setting as quite often these reports are left unrequested. Moreover, had a number of incidents related to having dozens of sbom reports in a cluster, which eventually would put some extra load on the cluster's kube api.
Closes #10090
There is a way provided for disabling SBOM generation functionality through the module's settings.
```changes …
```
> [operator-trivy] add an option for disabling sbom generation

- testing/cloud_layouts/script.d/wait_cluster_ready/test_alerts.sh
Disable ModuleConfigObsoleteVersion warning on e2e tests
```changes
type: fix
summary: Disable ModuleConfigObsoleteVersion warning on e2e tests.
```
> [testing] Disable ModuleConfigObsoleteVersion warning on e2e tests

- candi/openapi/init_configuration.yaml
- dhctl/pkg/config/deckhouse_config.go
- dhctl/pkg/config/deckhouse_config_test.go
- dhctl/pkg/config/types.go
- docs/site/pages/virtualization-platform/documentation/admin/install/steps/INSTALL.md
- docs/site/pages/virtualization-platform/documentation/admin/install/steps/INSTALL_RU.md
- testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml
In release 1.55 we deprecate next parameters of deckhouse init configuration
```
kind: InitConfiguration
deckhouse:
releaseChannel: 'Beta'
bundle: "Default"
logLevel: "Info"
```
in exchange for use `deckhouse` ModuleConfig settings.
We showed warnings about replacing, now we will return error and stop bootstrapping.
Remove deprecates
```changes
section: dhctl
type: fchore
summary: Forbid to use logLevel bundle and releaseChannel from deckhouse init configuration
impact: |
Please use deckhouse ModuleConfig settings for set releaseChannel and/or bundle and/or logLevel settings instead of use  InitConfiguration deckhouse section
```
> [dhctl] Forbid to use `logLevel` `bundle` and `releaseChannel` from deckhouse init configuration

- candi/cloud-providers/azure/terraform-modules/base-infrastructure/variables.tf
- testing/cloud_layouts/Azure/Standard/configuration.tpl.yaml
Fix for this pr: https://github.com/deckhouse/deckhouse/pull/9554
This PR fixes error:
```
Error: Unsupported attribute
on deckhouse/candi/cloud-providers/azure/layouts/standard/base-infrastructure/variables.tf line 53, in locals:
53:   nameservers                 = lookup(var.providerClusterConfiguration.nameservers, "addresses", null)
| var.providerClusterConfiguration is object with 9 attributes
This object does not have an attribute named "nameservers".
```
Converge may crash if nameservers are not specified
When creating `azurerm_virtual_network`, default nameserver will be used if no other nameserver is specified (as expected earlier).
It was tested as follows:
- Cluster was first deployed without nameservers 
- then the provider-cluster-configuration was changed (`kubectl -n …
> [candi][azure] Azure vNet DNS config fix

- modules/040-node-manager/templates/node-group/_bootstrap.tpl
Change bootstrap.sh behavior: exit immediately by getting 401/403 from master node by bootstrapping node with human readable exception
Resolve issue #2847
By using bootstrap.sh with expired token, exit immediately with human readable error message.
```changes
type: fix
summary: Fix bootstrap.sh behavior, exit with human readable message if it run with expired bootstrap token.
```
> Clarify error message on bootstrap token expiration

- Makefile
- tools/spelling/dictionaries/dev_OPS.dic
- tools/spelling/wordlist
Make spellcheck linter target the local repo and add `DVP` to the word list.
```changes
type: chore
summary: Fix spellcheck linter command to use local cache.
```
> [testing] Fix spellcheck linter command to use local cache

- deckhouse-controller/pkg/controller/moduleloader/sync.go
It sets module versions by deployed release at start.
See version in module CR.
```changes
type: feature
summary: Set modules versions by releases.
```
> [deckhouse] set module version

- dhctl/pkg/kubernetes/actions/manifests/manifests.go
- global-hooks/migrate/migrate_cluster_configuration_label.go
- global-hooks/migrate/migrate_cluster_configuration_label_test.go
It sets the 'name' label to the 'd8-cluster-configuration' secret.
Deckhouse controller caches the 'd8-cluster-configuration' secret by the 'name' label. This label was removed, and deckhouse cannot check k8s automatic version.
Deckhouse can check k8s automatic version
```changes
section: dhctl
type: fix
summary: Add the 'name' label to the 'd8-cluster-configuration' secret.
```
> [dhctl] fix cluster configuration secret name label

- deckhouse-controller/pkg/controller/controller.go
- deckhouse-controller/pkg/controller/module-controllers/config/status.go
- deckhouse-controller/pkg/controller/moduleloader/loader.go
It provides supporting the 'global' module conversions.
The 'global' module has conversions, but they are not loaded.
Fixes #11024
The 'global' module has conversions.
```
root@dev-master-0:~# k get mc
NAME                         ENABLED   VERSION   AGE    MESSAGE
admission-policy-engine      false     1         208d   
cni-cilium                   true      1         99d    
deckhouse                    true      1         286d   
descheduler                  false     2         74d    
documentation                false     1         285d   
echo                         true      1         37d    
flant-integration            false     1         286d   
global                       true      1         286d   Update available, latest spec.settings schema version is 2
```
Logs:
``` …
```
> [deckhouse] support global conversions

- modules/500-dashboard/templates/metrics-scraper/rbac-for-us.yaml
[dmt](https://github.com/deckhouse/dmt) found a bug in the openAPI spec file for the dashboard. The field was duplicated, resulting in a compilation error.
The error leads to a problem with the metrics-scapper deployment, and a problem with its operation. The fix will allow the specified service to work fully.
There are no errors in the openapi specs, the compilation of the helm chart passes without errors.
```changes
type: fix
summary: remove duplicated roleRef in dashboard templates
```
> [dashboard] fix: remove duplicated roleRef in dashboard templates

- modules/140-user-authz/hooks/handle_manage_bindings.go
- modules/140-user-authz/hooks/handle_manage_bindings_test.go
- modules/140-user-authz/templates/rbacv2/global/manage/roles/all/manager.yaml
- modules/140-user-authz/templates/rbacv2/global/manage/roles/deckhouse/manager.yaml
- modules/140-user-authz/templates/rbacv2/global/manage/roles/infrastructure/manager.yaml
- modules/140-user-authz/templates/rbacv2/global/manage/roles/kubernetes/manager.yaml
- modules/140-user-authz/templates/rbacv2/global/manage/roles/networking/manager.yaml
- modules/140-user-authz/templates/rbacv2/global/manage/roles/observability/manager.yaml
- modules/140-user-authz/templates/rbacv2/global/manage/roles/security/manager.yaml
- modules/140-user-authz/templates/rbacv2/global/manage/roles/storage/manager.yaml
It replaces use admin role with use user role for manage manager roles.
It reduces rights for manage manager roles.
Use user roles are created in system namespaces when manage manager roles are created.
Use roles for manage:all:manager:
Use roles for manage:security:manager:
```changes
type: feature
summary: Replace use admin roles with use user roles for manage manager roles.
impact: Reducing rights for manage manager roles.
```
> [rbacv2] replace use admin with use user for manage manager role

- modules/160-multitenancy-manager/images/multitenancy-manager/cmd/main.go
- modules/160-multitenancy-manager/images/multitenancy-manager/pkg/webhook/namespace/main.go
- modules/160-multitenancy-manager/templates/validation.yaml
Permits the upmeter-agent service account to create namespaces when `allowNamespacesWithoutProjects` is set to false.
Without it, upmeter-agent isn't able to perform `namespace creation` checks and reports fails.
Closes #10965
Upmeter-agent is able to create a namespace even when `allowNamespacesWithoutProjects` is set to false.
```changes
type: chore
summary: Allow upmeter-agent to create namespaces regardless the multitenancy-manager module's settings.
```
> [multitenancy-manager] add upmeter to the list of excluded service accounts which can create namespaces

- deckhouse-controller/pkg/apis/ensure_crds.go
- go_lib/hooks/ensure_crds/hook_test.go
Abstracted the kubernetes client for use in tests
```changes
```
> [deckhouse-controller] Improved CRDs Installer

- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
Revert step 5 of GS for 1.66 release.
```changes
section: docs
type: fix
summary: Revert step 5 of GS for 1.66 release.
```
> [docs][getting-started] Revert step 5 of GS for 1.66 release

- docs/documentation/_data/deckhouse-ports.yml
New network ports for VXLAN.
The table doesn't cover the new VXLAN ports configured in https://github.com/deckhouse/deckhouse/pull/9089.
The https://deckhouse.io/products/kubernetes-platform/documentation/v1/network_security_setup.html page has 4299 and 4298 VXLAN ports.
```changes
section: docs
type: fix
summary: New network ports for VXLAN described.
```
> [docs] New network ports for VXLAN

- testing/cloud_layouts/AWS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/Azure/Standard/configuration.tpl.yaml
- testing/cloud_layouts/EKS/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/Static/configuration.tpl.yaml
- testing/cloud_layouts/Yandex.Cloud/WithoutNAT/configuration.tpl.yaml
- testing/cloud_layouts/script.d/wait_cluster_ready/test_alerts.sh
Update module schema version for e2e tests.
```changes
type: chore
summary: Update module schema version for e2e tests.
```
> [testing] Update module schema version for e2e tests

- dhctl/pkg/operations/bootstrap/steps.go
With bootstrap an error may occur:
`❗ ~ bashible dependency tar error: execute command 'command': exit status 1 - Warning: Permanently`
This can lead to diagnostic confusion due to a misunderstanding of the "tar" component.
To avoid confusion during diagnostics, it is suggested to highlight the problematic component with quotation marks:
` ❗ ~ bashible dependency 'tar' error: execute command 'command': exit status 1 - Warning: Permanently`
```changes
section: dhctl
type: chore
summary: add quotes to highlight the error in the component when loading
```
> [dhctl] Add quotes to highlight the error in the component when loading

- .github/workflow_templates/deploy-channel.multi.yml
- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-early-access.yml
- .github/workflows/deploy-rock-solid.yml
- .github/workflows/deploy-stable.yml
Add release date labels to to dev, dev/install, dev/install-standalone images. Label example:
```
"Labels": {
"io.deckhouse.alpha-released": "2024-09-30T14:08:36Z"
}
```
Additional information present in image might be useful for debugging.
Labels present.
```changes
section: ci
type: feature
summary: Add release date labels to install images.
```
> [ci] Add release date labels to install images

- go_lib/configtools/validator.go
It provides fix for validating the 'global' module config.
Validating the 'global' module config does not work.
Validating works.
```
root@dev-master-0:~# k edit mc global
error: moduleconfigs.deckhouse.io "global" could not be patched: admission webhook "module-configs.deckhouse-webhook.deckhouse.io" denied the request: spec.settings are not valid (version 2):  1 error occurred: * global.test is a forbidden property  
```
```changes
type: fix
summary: Fix validating the 'global' module config.
```
> [deckhouse] fix global validation

- .github/workflows/deploy-alpha.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-early-access.yml
- .github/workflows/deploy-rock-solid.yml
- .github/workflows/deploy-stable.yml
Rerender Github Actions workflows.
```changes
section: ci
type: fix
summary: Rerender workflows.
```
> [ci] Rerender workflows

- dhctl/pkg/app/preflight.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/operations/bootstrap/state.go
- dhctl/pkg/preflight/check-cloud-api/providers.go
- dhctl/pkg/preflight/check-cloud-api/types.go
- dhctl/pkg/preflight/check-cloud-api/utils.go
- dhctl/pkg/preflight/check_cloud_api.go
- dhctl/pkg/preflight/check_cloud_api_test.go
- dhctl/pkg/preflight/common.go
- dhctl/pkg/preflight/preflight.go
- dhctl/pkg/preflight/registry.go
- dhctl/pkg/preflight/registry_test.go
- dhctl/pkg/preflight/ssh.go
Added a new `PostCloud` step that is executed only when bootstrapping occurs in a cloud environment. The `PostCloud` step runs after the first master server is created and SSH connectivity is verified. Within `PostCloud`, a check for "access to cloud API from the master host" has been implemented specifically for the cloud providers vSphere and OpenStack.
Two methods are used for this verification:
- **With HTTP Proxy**: An SSH tunnel is established to the master server, forwarding a port to the proxy. A GET request is then made to the cloud API using `localhost:22323` as the proxy.
- **Without HTTP Proxy**: A port is forwarded directly to the cloud API (e.g., `-L 22323:api.selvpc.ru:443`). A GET request is made to `localhost:22323` while specifying the original TLS SNI.
These changes …
> [dhctl] [cloud-provider-openstack] Add Openstack API availability check inside the cluster during deployment

- dhctl/pkg/kubernetes/actions/converge/master_node_group_controller.go
Do not interrupt converge if an error is returned when getting the master IP address.
In some cases(previous converge failed with quota limit error) the terraform state for the master node may contain an empty `master_ip_address_for_ssh` output variable.
```changes
section: dhctl
type: fix
summary: Fix the `master_ip_address_for_ssh` terraform output variable handling in converge.
```
> [dhctl](converge) Fix the `master_ip_address_for_ssh` terraform output variable handling

- deckhouse-controller/cmd/deckhouse-controller/register-go-hooks.go
- ee/se/modules/380-metallb/requirements/check.go
PR #9658 caused errors in requirements tests due to deletion of `check.go` file:
```shell
ERRORS:
* release.yaml ... ERROR: found requirements for non-existent module checks, please review release requirements in release.yaml
exit status 1
metallbHasStandardConfiguration
Validation failed.
```
Fixing an error.
CI does not generate errors in requirements tests.
```changes
type: fix
summary: Fixed the requirements test for the module.
```
> [metallb] Fix the requirements test for the module

- candi/version_map.yml
Updated D8 CLI to latest
```changes
section: candi
type: chore
summary: Updated Deckhouse CLI to v0.8.0
```
> Update d8 cli to 0.8.0

- deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/module_config.go
- deckhouse-controller/pkg/controller/module-controllers/config/controller.go
- deckhouse-controller/pkg/controller/module-controllers/config/sync.go
It returns the message about unknown module.
To know that a module is unknown.
```changes
type: fix
summary: Return unknown module message.
```
> [deckhouse] return unknown module message

- modules/140-user-authz/hooks/handle_manage_bindings.go
It improves the rbacv2 hook.
The hook executes at use binding changes
The hook does not execute at use binding changes.
```changes
type: fix
summary: Fix the rbacv2 hook.
```
> [user-authz] fix hook

- docs/documentation/_data/deckhouse-alerts.yml
- global-hooks/migrate/migrate_update_policy.go
- modules/140-user-authz/hooks/handle_manage_bindings.go
- modules/340-monitoring-deckhouse/monitoring/prometheus-rules/alerting.yaml
It fires alert at deprecated mup.
The module update policy now is specified by the module config, labelSelectors do not work, so we need to fire an alert at deprecated mup.
```changes
type: fix
summary: Fire alert at deprecated ModuleUpdatePolicy.
```
> [deckhouse] fire alert at deprecated mup

- candi/bashible/common-steps/all/064_configure_kubelet.sh.tpl
- candi/bashible/common-steps/all/083_disable_rsyslog_for_kubelet.sh.tpl
- candi/bashible/openapi.yaml
- candi/control-plane-kubeadm/openapi.yaml
- candi/openapi/cluster_configuration.yaml
- modules/040-node-manager/hooks/check_nodes_cri_test.go
- modules/040-node-manager/hooks/get_crds_test.go
delete docker support in source code and deny use docker cri type in cluster configuration
this deny use docker cri type
if Docker cri type is prompt as defaultCRI stderr output is "defaultCRI should be one of [Containerd NotManaged]".
```changes
section:  dhctl
type: fix
summary: Delete docker CRI type support.
```
> [dhctl] Delete support cri type docker 

- modules/002-deckhouse/templates/validation.yaml
Fixed: #10752
Restart must be allowed for objects containing annotation
`spec.template.metadata.annotation."kubectl.kubernetes.io/restartedAt"`
Deployment, StatefulSet, DaemonSet should do rollout restart gracefully
```changes
type: fix
summary: rollout restart for deckhouse workloads (heritage=deckhouse) is forbidden
```
> [deckhouse-controller] rollout restart for deckhouse workloads (heritage=deckhouse) is forbidden

- deckhouse-controller/pkg/controller/moduleloader/loader.go
It unsets the source for downloaded modules if it has the 'Embedded' source.
Somehow, downloaded module can have the 'Embedded' source.
Before restart: 
```
root@dev-master-0:~# kubectl get module echo -owide 
NAME   WEIGHT   RELEASE CHANNEL   SOURCE     VERSION   PHASE       ENABLED   DISABLED MESSAGE              READY
echo   910                        Embedded             Available   False     turned off by module config   False
```
After restart:
```
root@dev-master-0:~# kubectl get module echo -owide 
NAME   WEIGHT   RELEASE CHANNEL   SOURCE   VERSION   PHASE       ENABLED   DISABLED MESSAGE              READY
echo   910                                           Available   False     turned off by module config   False
```
```changes
type: fix
summary: Fix embedded …
```
> [deckhouse] fix embedded source for downloaded modules

- Makefile
After that PR #10952, `trdl` stopped running on local macOS due to features of an older version of `make`.
Fix the `make generate`.
In `make` version 3.81 `make generate` works. 
```changes
section: ci
type: chore
summary: Fixed 'trdl' startup in older versions of 'make'.
```
> [ci] Fix 'trdl' startup in older versions of 'make'

- modules/402-ingress-nginx/templates/controller/controller.yaml
Disabling `vertical-pod-autoscaler` for `istio-proxy` sidecar in `ingress-nginx`.
When `sidecar.resourcesManagement.static` is configured in `istio` module, the VPA in `ingress-nginx` module overrides the settings.
VPA ignores `istio-proxy` sidecar in `ingress-nginx`.
```changes
type: chore
summary: Disable VPA for Istio sidecar
```
> [ingress-nginx] Disable VPA for Istio sidecar

- .github/ci_templates/e2e_tests.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vcd.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Add an option to delete e2e cluster regardless of the test result.
This change allows for better automation of testing.
```changes
type: feature
summary: Add an option to delete e2e cluster regardless of the test result.
```
> Add an option to delete e2e cluster regardless of the test result

- candi/bashible/common-steps/all/098_update_node_labels.sh.tpl
- candi/bashible/common-steps/all/099_update_node_labels.sh.tpl
This bashible step allows to add, remove and edit node labels from local directory and it subdirectories. A full set of labels also stored in node annotation `node.deckhouse.io/last-applied-local-labels`, what allows to control only local set labels.
Path to local directory: `/var/lib/node_labels`
Labels format: `foo=bar`
Fixes #9767
Any labels, stored in any file in `/var/lib/node_labels` or it subdirectories must be applied to node. By changing and/or deleting, they must be changed/deleted from node as well.
```changes
section: candi
type: feature
summary: Added a way to control node labels from files, stored in local directory and it subdirectories.
```
> Add bashible step to update node labels from local directory

- dhctl/pkg/kubernetes/actions/resources/resouce_ready.go
- dhctl/pkg/kubernetes/actions/resources/resouce_ready_test.go
Some resource types did not pass the readiness check because they have conditions but do not have the `Ready` condition.
In this pull request, condition `Available` tracking has been added and also if conditions are present, but `Ready` or `Available` is not found in them, we wait for 5 threads to see these conditions appear and move to the `Ready` state because we cannot assume which controllers and `CRDs` users can deploy and what conditions these resources may have
Some resources created by dhctl cannot pass readiness check.
Some resources created by dhctl cannot pass readiness check. Users can affected and waiting this patch
```changes
section: dhctl
type: fix
summary: Resource readiness fix
```
> [dhctl] Resource readiness fix

- modules/200-operator-prometheus/templates/rbac-for-us.yaml
Change wildcards in the RBAC's verbs to the exhaustive list.
While it's **maybe** OK for the Prometheus operator to have full access to the CRs it owns, granting full access to configmaps secrets and statefulsets in any namespace may seem "too much" even though it's required for a normal Prometheus lifecycle.
If the `d8-monitoring` namespace is the only place where the prometheus operator can deploy the Prometheus in Deckhouse Kubernetes Platform, we can instead fix the `prometheus` module by adding Role and RoleBinding which grants operator permission for the `d8-monitoring` namespace only. This approach can not be used if we allow users to deploy their own Prometheus using our operator.
From this perspective, this PR is a great example of cutting corners.
We don't
```changes
section: …
```
> [prometheus-operator] Review wildcard RBAC

- modules/301-prometheus-metrics-adapter/templates/rbac-for-us.yaml
- testing/matrix/linter/rules/roles/wildcards.go
Review the wildcards in the `prometheus-metrics-adapter` module
Clarify the necessity of the wildcard in the module RBACs.
We don't
No functional changes. This PR adds few comments about the issue
```changes
```
> [prometheus-metrics-adapter] Review wildcard RBAC

- dhctl/pkg/operations/converge/infra/hook/controlplane/hook_for_destroy_pipeline.go
- dhctl/pkg/operations/converge/infra/hook/controlplane/hook_for_update_pipeline.go
> Dhctl converge fix panic 

- go.mod
In goland, dependencies are synchronized using the go list command.
If a dependency is specified with a version that does not exist, then we get an error. And because dependencies are updated regularly, we get a lot of warnings that distract us from our work.
The dependency itself is used directly through replace, that is, it does not affect the assembly of the project. And the changes are only needed to ensure that the go list commands run without errors.
Get rid of errors in Goland.
Goland performs dependency updates without warnings or errors.
```changes
section: chore
type: chore
summary: sync dependencies
```
> [chore] fix: sync dependencies

- dhctl/pkg/kubernetes/actions/converge/master_node_group_controller.go
- dhctl/pkg/operations/converge/infra/hook/controlplane/hook_for_destroy_pipeline.go
- dhctl/pkg/operations/converge/infra/hook/controlplane/hook_for_update_pipeline.go
Fix panic during commander masters converge.
Converge in commander mode causes panic when switching from multi-master to single-master:
<details>
<summary>converge log with error</summary>
```
2024-12-18T14:15:53Z - [INFO] - │ │ │ │ ┌ Drain node 'ngorobatov-dev3-master-0'
2024-12-18T14:16:16Z - [INFO] - │ │ │ │ │ 🎉 Succeeded!
2024-12-18T14:16:16Z - [INFO] - │ │ │ │ └ Drain node 'ngorobatov-dev3-master-0' (23.21 seconds)
2024-12-18T14:16:17Z - [INFO] - │ │ │ │ 
2024-12-18T14:16:17Z - [INFO] - │ │ │ │ Start watcher for file /tmp/dhctl/cache_aa583e01-bd48-11ef-abe9-5eb2409e8d30/88b68e1c0cc11a32620fa04dbc16daacf ↵
2024-12-18T14:16:17Z - [INFO] - │ │ │ │ c187b2d79ff27ebc642f5baed174887/ngorobatov-dev3-master-0.tfstate
2024-12-18T14:16:18Z - [INFO] - │ │ │ │ yandex_compute_instance.master: …
```
> [dhctl] Fix panic during commander masters converge

- go_lib/dependency/extenders/deckhouseversion/extender.go
It provides fix for deckhouse version parsing.
Deckhouse version parsing does not work for extender.
It works
```changes
type: fix
summary: Fix deckhouse version parsing.
```
> [deckhouse] fix deckhouse version parsing

- docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA.liquid
- docs/site/_includes/getting_started/global/partials/STEP_INSTALL_SCHEMA_RU.liquid
Fixed broken links at Getting Started.
```changes
section: docs
type: fix
summary: Fixed broken links at Getting Started.
```
> [docs] Fixed broken links at Getting Started

- modules/402-ingress-nginx/hooks/minimal_ingress_nginx_version.go
- modules/402-ingress-nginx/requirements/check.go
- modules/402-ingress-nginx/requirements/check_test.go
Added a check for the pre-release of the defaultControllerVersion value in the `ModuleConfig`.
The defaultControllerVersion MC parameter specifies the default version for IngressNginxControllers created without explicitly specifying the controller version.
The supported versions scope can change from release to release, if the defaultControllerVersion configured in cluster won't be supported in next release, the module will crash after update.
```changes
type: chore
summary: Added a release requirement check for defaultControllerVersion parameter.
```
> [ingress-nginx] Add requirements check for ModuleConfig defaultControllerVersion

- modules/110-istio/hooks/migration_delete_legacy_roles.go
- modules/110-istio/hooks/migration_delete_legacy_roles_test.go
The removal of legacy RBACs from the cluster created by the Istio operator before we switched to creating RBACs through the platform.
Legacy RBACs interfere with the operation of the IstioOperator reconcile in the cluster. There are errors in operator logs:
```
2024-11-20T18:01:33.652832Z     error   installer       Failed to delete resources with helm reconciler: rolebindings.rbac.authorization.k8s.io "istiod-v1x16" is forbidden: User "system:serviceaccount:d8-istio:operator" cannot delete resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "d8-istio", roles.rbac.authorization.k8s.io "istiod-v1x16" is forbidden: User "system:serviceaccount:d8-istio:operator" cannot delete resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "d8-istio", …
```
> [istio] delete legacy roles and rolebindings created by istio-operator

- modules/150-user-authn/hooks/get_dex_client_crds.go
- modules/150-user-authn/hooks/get_dex_client_crds_test.go
- modules/150-user-authn/templates/dex/oauth2client.yaml
Add `DexClient` that has `dexclient.deckhouse.io/allow-access-to-kubernetes` annotation to kubernetes `OAuth2Client` `trustedPeers`.
We want to allow some dex clients to authorize in kubernetes api.
```changes
type: feature
summary: add dexclient with the specific annotation to kubernetes client trustedPeers
```
> [user-authn] add dexclient with the specific annotation to kubernetes client trustedPeers

- modules/500-upmeter/crds/upmeterremotewrite.yaml
Add backup label to publicly used CRDs
Adding this label to CRD instructs `d8 backup cluster-config` command to backup all CRs of a Kind. It's great to have it at all publicly used CRDs
We don't
`d8 backup cluster-config` command backups all CRs for these CRDs.
```changes
type: feature
summary: Added `backup.deckhouse.io/cluster-config` label to relevant module CRDs.
```
> [upmeter] Add CR backup label

- dhctl/pkg/kubernetes/actions/converge/check.go
- dhctl/pkg/kubernetes/actions/converge/cloud_permanent_node_group_controller.go
- dhctl/pkg/kubernetes/actions/converge/converge.go
- dhctl/pkg/kubernetes/actions/converge/master_node_group_controller.go
- dhctl/pkg/kubernetes/actions/converge/node.go
- dhctl/pkg/kubernetes/actions/converge/node_group_controller.go
- dhctl/pkg/kubernetes/actions/converge/nodebootstrap.go
- dhctl/pkg/kubernetes/actions/converge/state.go
- dhctl/pkg/log/logger.go
- dhctl/pkg/operations/bootstrap/cluster-bootstrapper.go
- dhctl/pkg/operations/bootstrap/steps.go
- dhctl/pkg/terraform/executor.go
- dhctl/pkg/terraform/pipeline.go
- dhctl/pkg/terraform/runner.go
- dhctl/pkg/terraform/runner_interface.go
- dhctl/pkg/terraform/runner_test.go
- dhctl/pkg/terraform/single_shot_runner.go
- dhctl/pkg/terraform/state_saver.go
- dhctl/pkg/terraform/terraform_context.go
- dhctl/pkg/util/fs/file_watcher.go
- dhctl/pkg/util/retry/retry.go
Parallel bootstrap cloudpermanent nodegroups with nodes.
Reduces bootstrap time for cloud permanent nodes.
summary time of bootstrap 3 ng with 2 nodes in each:
<details>
<summary>Before (~ 693 seconds (203.30 + 242.30+ 247.99 )): </summary>
...
...
...
</details>
<details>
<summary>After (~ 252 seconds ):</summary>
...
</details>
```changes
section: dhctl
type: feature
summary: Parallel bootstrap cloud permanent node groups.
```
> [dhct] parallel bootstrap cloudpermanent nodegroup

- testing/cloud_layouts/Azure/Standard/configuration.tpl.yaml
- testing/cloud_layouts/Azure/Standard/resources.yaml
Change zones for Azure e2e tests.
Currently zone 2 in our region is unavailable.
```changes
type: chore
summary: Change zones for Azure e2e tests.
```
> [testing] Change zone for Azure e2e tests

- candi/bashible/common-steps/all/000_discover_node_ip.sh.tpl
Reword error when discover static node IP address.
If static node bootstrapping with IP address that is not included in internalNetworkCIDRs, return error: 
> Failed to discover node_ip but its required for static cluster bootstrap or static cluster nodes. 
that may confuse the user. 
Close #7337
The error message should say that no IP addresses were found on the node that match the current list of internalNetworkCIDRs.
```changes
section: candi
type: chore
summary: Reword error when discover static node IP address.
```
> [candi] reword discover node_ip error

- modules/002-deckhouse/templates/validation.yaml
In the current release, a problem arose when checking the possibility of a restart. If an object does not have the spec field that we are targeting, the check fails and, as a result, operations that should have been allowed are blocked.
Access check fix.
Lack of verification blocks the release of modules.
The absence of a spec section in a module does not block operations.
```changes
type: fix
summary: check spec object in validations
```
> [deckhouse-controller] check spec object in validations

- modules/021-cni-cilium/hooks/set_cilium_mode.go
- modules/021-cni-cilium/hooks/set_cilium_mode_test.go
Fixed set_silium_mode.go for Static clusters with configured VXLAN.
After preraring for getting rid of d8-cni-configuration secret in https://github.com/deckhouse/deckhouse/pull/10640 we broke the set_silium_mode.go hook — in Static clusters tunnelMode setting doesn't work anymore.
The Static clusters forced to use DirectWithNodeRoutes mode without any options.
It is possible to configure tunnelMode: VXLAN in Static clusters.
```changes
type: fix
summary: Fixed tunnelMode setting for Static clusters
```
> [cni-cilium] Fixing tunnelMode setting for Static clusters

- docs/documentation/_data/deckhouse-alerts.yml
- modules/300-prometheus/monitoring/prometheus-rules/grafana.yaml
After migrating to grafana v10  we need to change alert targets and some documentation refs.
To avoid fake alerts and misunderstanding in documents.
Some alerts are firing right now.
No fake alerts and correct docs.
```changes
type: fix 
summary: Rename targets for alerts and docs fixes
```
> [prometheus] Rename targets for alerts and docs fixes

- .dmtlint.yaml
Adding to okmeter error exception
After adding dmtlint, errors appeared in the okmeter module, you need to add them to exceptions to unblock development.
Linter works without errors
```changes
section: tesing
type: fix
summary: add okmeter to exclude dmtlint
```
> [testing] add okmeter to exclude dmtlint

- deckhouse-controller/pkg/controller/moduleloader/sync.go
It makes outdated deployed module releases superseded at start
In some cases, deployed releases may remain in the deployed status, we need to ensure only one deployed module release, so at restart we make all outdated deployed module releases superseded.
The module-release-controller runs in the concurrent mode, so several deployed module releases can start race.
Only one module release is deployed.
Several deployed modules releases:
```bash
kubectl get mr -l module=deckhouse-commander
NAME                          PHASE      UPDATE POLICY   TRANSITIONTIME   MESSAGE
deckhouse-commander-v1.3.19   Deployed   deckhouse       47d
deckhouse-commander-v1.3.20   Deployed   deckhouse       47d
deckhouse-commander-v1.4.18   Skipped    deckhouse       47d
deckhouse-commander-v1.4.19   Skipped …
```
> [deckhouse] fix several deployed module releases

- modules/400-descheduler/webhooks/conversion/deschedulers
Fix conversation from v1alpha1 to v1alpha2 (add nodeAffinityType default for removePodsViolatingNodeAffinity strategy).
```
kind: Descheduler
metadata:
name: legacy
spec:
deschedulerPolicy:
strategies:
removePodsViolatingInterPodAntiAffinity:
enabled: true
removePodsViolatingNodeAffinity:
enabled: true
```
converted to
```
apiVersion: deckhouse.io/v1alpha2
kind: Descheduler
metadata:
creationTimestamp: "2024-12-24T12:19:09Z"
generation: 1
name: legacy
resourceVersion: "466962272"
uid: fe156f1b-6c8a-4f05-afd2-6b36a7bb0f27
spec:
strategies:
removePodsViolatingInterPodAntiAffinity:
enabled: true
removePodsViolatingNodeAffinity:
enabled: true
nodeAffinityType:
- requiredDuringSchedulingIgnoredDuringExecution
```
---
```changes
type: fix …
```
> [descheduler] fix conversion

- docs/documentation/_data/deckhouse-alerts.yml
- modules/021-cni-cilium/monitoring/prometheus-rules/cni-checks.yaml
- modules/035-cni-flannel/monitoring/prometheus-rules/cni-checks.yaml
- modules/035-cni-simple-bridge/monitoring/prometheus-rules/cni-checks.yaml
Fixes for D8CNIMisconfigured alerts — renamed group and typos fixed.
Polk can't handle the alerts:
```
Couldn't create event due to error: Usage of current alert's trigger (D8CNIMisconfigured) is forbidden in grouping to prevent circular dependencies!
```
These alerts are important to handle before upgrading to 1.68.
Alerts are visible in polk.
```changes
type: fix
summary: Fixes for D8CNIMisconfigured alerts — renamed group and typos fixed.
```
> [monitoring] CNI misconfiguration alerts fix

- modules/400-descheduler/webhooks/conversion/deschedulers
Fix descheduler webhook. https://github.com/deckhouse/deckhouse/pull/11223
```changes
type: fix
summary: Fix descheduler webhook
```
> [descheduler] fix conversion (#11223)

- modules/007-registrypackages/images/containerd/patches/runc/001-readd-tuntap-to-default-device-rules.patch
- modules/007-registrypackages/images/containerd/patches/runc/README.md
- modules/007-registrypackages/images/containerd/werf.inc.yaml
Bump runc version to 1.2.3 and add patch to revert tun/tap to default device rules.
Since the release of runc v1.2.0, tuntap device access has been removed from the default device ruleset, causing problems when starting openvpn module:
```
[root@dev-master-0 ~]# kubectl -n d8-openvpn logs openvpn-0
Defaulted container "openvpn-tcp" out of: openvpn-tcp, ovpn-admin, kube-rbac-proxy, render-etc-hosts-with-cluster-domain-aliases (init), check-linux-kernel (init)
2024/12/25 06:24:47 open /dev/net/tun: operation not permitted
```
Restoring openvpn functionality.
```changes
section: containerd
type: fix
summary: Bump runc version to 1.2.3 and add patch to revert tun/tap to default device rules.
```
> [containerd] fix runc tun device permission error

- modules/150-user-authn/openapi/values.yaml
Fix error occurred after this change https://github.com/deckhouse/deckhouse/pull/11193
```
"Module hook failed, requeue task to retry after delay. Failed count is 2. Error: 2 errors occurred:\n\t* cannot apply values patch for module values\n\t* userAuthn.internal.dexClientCRDs.allowAccessToKubernetes is a forbidden property\n\n"
```
```changes
type: fix
summary: fix error in dexClient internal openapi spec
```
> [user-authn] fix dexClient internal openapi spec

- modules/040-node-manager/templates/node-group/_bootstrap.tpl
I changed the error output to stderr in the function
Currently, the error is piped to bash, which hides the reason for not executing the script.
```changes
type: fix
summary: in bootstrap output error text in stderr for function load_phase2_script
```
> [node-manager] in bootstrap output error text in stderr for function load_phase2_script

- modules/040-control-plane-manager/images/etcd-backup/entrypoint.sh
- modules/040-control-plane-manager/templates/etcd-backup/cronjob.yaml
Change free space detection for etcd-backup job.
The current logic for determining free space is not effective in cases where large disks are used (when calculating free space we assume that there should be more than 25% free space). To solve this problem, we consider that the backup cannot be larger than the etcd database itself, so we just need to make sure that there is enough space on the drives for twice the size of `etcdQuotaBackendBytes` to create backup correctly.
An example of the result of executing jobs with different `etcdQuotaBackendBytes` values:
<details>
<summary>etcdQuotaBackendBytes ~ 4GB </summary>
</details>
<details>
<summary>etcdQuotaBackendBytes ~ 8GB </summary>
</details>
```changes
type: feature
summary: Change of logic detection …
```
> [control-plane-manager] change free space detection for etcd-backup

- ee/se/modules/380-metallb/templates/l2lb/rbac-for-us.yaml
- ee/se/modules/380-metallb/templates/rbac-to-us.yaml
Fix metallb RBAC rules.
1. There are `d8:metallb:rbac-proxy` ClusterRoleBinding in both EE and SE redactions. It can break RBAC in cluster.
2. There is a new linter which found it.
1. A risk of ClusterRoleBinding collision.
All linters are quiet.
There are two ClusterRoleBindings in cluster:
* `d8:metallb:rbac-proxy`
* `d8:metallb:l2lb:rbac-proxy`
```changes
type: fix
summary: Fix metallb RBAC rules.
```
> [metallb] Fix RBAC rules

- modules/021-cni-cilium/monitoring/prometheus-rules/cni-checks.yaml
- modules/035-cni-flannel/monitoring/prometheus-rules/cni-checks.yaml
- modules/035-cni-simple-bridge/monitoring/prometheus-rules/cni-checks.yaml
Excluding unwanted labels from D8CNIMisconfigured alert.
The alert aggregation systems (i.e. polk) can't merge alerts after restarting deckhouse pod (the `pod` label is being changed) and creates the new one.
The D8CNIMisconfigured alert is designed to prepare setups for upgrading to 1.68.
Restarting deckhouse pod don't change the alert label set.
```changes
section: monitorint
type: fix
summary: Excluded unwanted labels from D8CNIMisconfigured alert.
```
> [monitoring] D8CNIMisconfigured alert fix — excluding unwanted labels

- dhctl/pkg/kubernetes/actions/manifests/manifests.go
Add `imagesRegistry` to the `deckhouse-registry` secret
During the bootstrap we don't have this field. It's set in the [deckhouse](https://github.com/deckhouse/deckhouse/blob/main/modules/002-deckhouse/templates/registry-secret.yaml#L25) module.
So, we have a small period of time. If deckhouse will reboot in this interval, it can lead that we will have no value here and it will be passed to the [release controller ](https://github.com/deckhouse/deckhouse/blob/44b9f34c9acf4de67c9775fcf20a3a50edc04614/deckhouse-controller/pkg/controller/deckhouse-release/controller.go#L274). This case will change the deckhouse image to the `:v1.XX.Y` without any registry.
It would be better to set it on boostrap, because we can :)
```changes
section: dhctl
type: fix
summary: Fix the deckhouse-registry …
```
> [dhctl] Add imagesRegistry variable during the bootstrap

- candi/bashible/common-steps/all/051_pull_and_configure_kubernetes_api_proxy.sh.tpl
- candi/control-plane-kubeadm/patches/etcd.yaml.tpl
- candi/control-plane-kubeadm/patches/kube-apiserver.yaml.tpl
- candi/control-plane-kubeadm/patches/kube-controller-manager.yaml.tpl
- candi/control-plane-kubeadm/patches/kube-scheduler.yaml.tpl
- ee/be/modules/350-node-local-dns/templates/daemonset.yaml
- ee/modules/450-network-gateway/templates/snat-daemonset.yaml
- modules/402-ingress-nginx/templates/failover/daemonset.yaml
Fix security context for static pods and iptables containers.
When we set default user (deckhouse) for all docker images, pods with manifests without proper security context fail to start due to wrong user.
```changes
section: core
type: fix
summary: fix security context for static pods and iptables containers
```
> [core] fix security context for static pods and iptables containers

- global-hooks/migrate/migrate_update_policy.go
It fires an alert about deprecated module update policy only for enabled modules.
No sense to fire the alert for disabled modules.
No sense to fire the alert for disabled modules.
Fire the alert only for enabled modules. 
```changes
type: fix
summary: Fire the deprecated module update policy alert only for enabled modules.
```
> [deckhouse] fire alert only for enabled modules

- modules/160-multitenancy-manager/images/multitenancy-manager/templates/_helpers.tpl
It provides fix for the normalize function to support RFC 1123
Fixes #10657
Groups with slash could be passed from keycloak, so projects cannot be created. 
```
apiVersion: deckhouse.io/v1alpha2
kind: Project
metadata:
creationTimestamp: "2024-12-23T18:17:42Z"
finalizers:
- projects.deckhouse.io/project-exists
generation: 1
labels:
projects.deckhouse.io/project-template: default
name: test-validation
resourceVersion: "247586735"
uid: 344acc65-b26d-4975-b694-4751f6b6a393
spec:
description: test-validation for group with /
parameters:
administrators:
- name: /Group_KVS
subject: Group
extendedMonitoringEnabled: true
podSecurityProfile: Baseline
resourceQuota:
limits:
cpu: 5
memory: 5Gi
requests:
cpu: 5
memory: 5Gi
storage: 1Gi
projectTemplateName: default
status:
conditions:
- …
```
> [multitenancy-manager] fix normalize function

- global-hooks/discovery/modules_images_tags.go
Fix images_digests regexp
We can't parse modules with a number in the name
keep module compatibility as fast as you can
```changes
type: fix
summary: Fix regexp for parsing image_digests.json.
```
> [deckhouse] Fix regexp for parsing images_digests.json

- modules/031-local-path-provisioner/templates/configmap.yaml
Fix security context for helperPod.
Currently, distroless images have the default user "deckhouse", which causes modules that should run as root to fail.
Related to #11309
Correct execution of helperPod local-path-provisioner.
```changes
type: fix
summary: Fix security context for helperPod.
```
> [local-path-provisioner] fix security context for helper-pod

- .github/workflow_templates/cve-weekly.yml
- .github/workflows/cve-weekly.yml
- Makefile
- tools/cve/base-images.sh
- tools/cve/html/body-part.tpl
- tools/cve/trivy-wrapper.sh
Updated the cve-weekly workflow to use our custom Trivy, which leverages internal vulnerability databases and security policies instead of the standard version.
This change ensures cve-weekly aligns with our security needs by using custom Trivy with internal databases and policies, providing more accurate and relevant vulnerability scanning.
The expected result is a more accurate and reliable cve-weekly workflow, leveraging internal vulnerability databases and policies to identify and report security issues that are relevant to our infrastructure.
```changes
section: ci
type:  chore
summary: Use our trivy to scan images
```
> [CVE] Transition to using our trivy

- modules/039-registry-packages-proxy/images/registry-packages-proxy/werf.inc.yaml
Reduce differences between cse and main branches. Standardize build
Migrate cse changes to main branch
Reduce differences between cse and main branches
```changes
section: registry-packages-proxy
type: chore
summary: Migrate cse changes to main branch
```
> chore: registry-packages-proxy src artifact

- modules/300-prometheus/templates/prometheus/rbac-to-us.yaml
Preparation for the new Observability module.  
This change grants the `label-proxy` in the Observability module access to Prometheus via a service account token.  
The `label-proxy` from the Observability module will successfully access Prometheus.
Allow observability label-proxy to access prometheus.
```changes
type: chore
summary: Service Account permission for observability label-proxy to prometheus.
impact: low
```
> [monitoring] Service Account permission for observability label-proxy to prometheus.

- modules/340-monitoring-kubernetes/monitoring/prometheus-rules/kubernetes/ebpf-exporter.yaml
Add node label for EbpfExporterKernelNotSupported alert.
To make EbpfExporterKernelNotSupported more informative for better debugging.
Node label in alerts description.
```changes
section: monitoring-kubernetes]
type: chore
summary: Add node label for EbpfExporterKernelNotSupported alert
```
> [monitoring-kubernetes] Node label for EbpfExporterKernelNotSupported alert

- modules/140-user-authz/hooks/handle_manage_bindings.go
- modules/140-user-authz/hooks/handle_manage_bindings_test.go
It moves the 'related-with' label to annotations.
Labels cannot contain some characters, but name can, so the hook fails. We need to move this label to annotations.
No the 'related with' label.
```
root@dev-master-0:~# kubectl get rolebindings -A -o json | jq '.items[] | select(.metadata.annotations["rbac.deckhouse.io/related-with"]) | {namespace: .metadata.namespace, name: .metadata.name, annotation: .metadata.annotations["rbac.deckhouse.io/related-with"]}'
{
"namespace": "d8-chrony",
"name": "d8:use:viewer:binding:mybinding",
"annotation": "mybinding"
}
{
"namespace": "d8-cloud-instance-manager",
"name": "d8:use:viewer:binding:mybinding",
"annotation": "mybinding"
}
{
"namespace": "d8-cloud-provider-openstack",
"name": "d8:use:viewer:binding:mybinding",
"annotation": "mybinding"
}
{ …
```
> [user-authz] move the 'related-with' label to annotations

- deckhouse-controller/pkg/controller/module-controllers/config/controller.go
It provides fix for deleting embedded modules configs.
The module-config-controller skips embedded modules, so the finalizer is not deleted, and the module config cannot be deleted. 
The module-config-controller skips embedded modules, so the finalizer is not deleted, and the module config cannot be deleted. 
Deleting embedded module config:
```
root@dev-master-0:~# kubectl get module upmeter 
NAME      WEIGHT   SOURCE     PHASE   ENABLED   READY
upmeter   500      Embedded   Ready   True      True
```
```
root@dev-master-0:~# kubectl get mc upmeter -oyaml
metadata:
creationTimestamp: "2024-12-26T14:45:33Z"
finalizers:
- modules.deckhouse.io/module-config
generation: 1
name: upmeter
resourceVersion: "250059259"
uid: …
```
> [deckhouse] fix deleting embedded module configs

- ee/modules/030-cloud-provider-dynamix/templates/cloud-data-discoverer/rbac-for-us.yaml
- modules/040-node-manager/hooks/set_instance_class_ng_usage.go
This PR fixes several non-critical bugs in `cloud-provider-dynamix` provider. 
```
ModuleHookRun:/modules/node-manager/update_instance_class_ng:kubernetes:040-node-manager/hooks/set_instance_class_ng_usage.go:ics:OperatorStartup:failures 1671:3 errors occurred:
* Patch object deckhouse.io/v1alpha1/DynamixInstanceClass//worker using application/merge-patch+json patch: apiVersion 'deckhouse.io/v1alpha1', kind 'DynamixInstanceClass' is not supported by cluster: DynamixInstanceClass.deckhouse.io """" not found
* Patch object deckhouse.io/v1alpha1/DynamixInstanceClass//frontend using application/merge-patch+json patch: apiVersion 'deckhouse.io/v1alpha1', kind 'DynamixInstanceClass' is not supported by cluster: DynamixInstanceClass.deckhouse.io """" not found
* Patch object …
```
> [cloud-provider-dynamix] RBAC fixes

- modules/300-prometheus/hooks/metrics_web_interfaces.go
- modules/300-prometheus/hooks/metrics_web_interfaces_test.go
The hook that generates metrics for service links 'Web Interfaces' Grafana panel now considers the https.mode: OnlyInURI parameter from the global configuration. If this parameter is set, the scheme for links is forced to https, even when TLS is not enabled in the ingress spec.
- This change ensures accurate generation of https links in metrics when https.mode: OnlyInURI is used
- Fixes https://github.com/deckhouse/deckhouse/issues/7306
- Metrics will correctly generate https links when https.mode: OnlyInURI is set, regardless of the ingress TLS spec.
```changes
type: fix 
summary: Ensure grafana `Web Interfaces` panel use 'https' in links when 'https.mode: OnlyInURI' is enabled
```
<!---
`impact_level: default` adds to changelog as …
> [prometheus] Make metrics-web-interfaces hook consider  https.mode: OnlyInURI

- docs/documentation/_data/deckhouse-alerts.yml
- modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring/cronjob.yaml
Added some commands for diagnostics when triggered alert for CronJobs
There was a request from a client who did not understand what Job was the problem with.
```
Check what's going on: `kubectl -n <namespace> describe job <example_job>`
You can check the status of the Job:
`kubectl -n <namespace> get job <example_job>`
You can check the status of pods created by Job:
`kubectl -n <namespace> get pods -l job-name=<example_job>`
```
```changes
type: chore
summary: Update alert for CronJobs
```
> [extended-monitoring] Update alert for CronJobs

- .github/ci_includes/werf_envs.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
Move GOPROXY from secrets to variables.
It is completely unnecessary to keep non-secret data in secrets and inconvenience ourselves with secret masking.
```changes
section: ci
type: chore
summary: Move GOPROXY from secrets to variables.
```
> [ci] Move GOPROXY from secrets to variables

- modules/040-node-manager/templates/caps-controller-manager/deployment.yaml
The synchronization period for the CAPS controller has been reduced from 10 minutes to 1 minute.
This helps us fix a number of issues that arise due to long controller response times. This is a small fix to give time to deal with the problem completely.
`SyncPeriod` description:
```
// This applies to all controllers.
//
// A period sync happens for two reasons:
// 1. To insure against a bug in the controller that causes an object to not
// be requeued, when it otherwise should be requeued.
// 2. To insure against an unknown bug in controller-runtime, or its dependencies,
// that causes an object to not be requeued, when it otherwise should be
// requeued, or to be removed from the queue, when it otherwise should not
// be removed.
```
Prevent problems with CAPS
CAPS will more frequently …
> [node-manager] tune caps sync period

- modules/002-deckhouse/images/webhook-handler/label-converter/go.mod
- modules/002-deckhouse/images/webhook-handler/label-converter/go.sum
- modules/002-deckhouse/images/webhook-handler/werf.inc.yaml
As part of the security closure, it is necessary to update the golang.org/x/net dependency to version 0.33.0 to resolve the issue CVE-2024-45338
Solving security problems
The working image does not contain any security issues
```changes
type: fix
summary: update golang.org/x/net to 0.33.0
```
> [deckhouse-controller] feat: update golang.org/x/net to 0.33.0

- modules/015-admission-policy-engine/crds/security-policy.yaml
Update x-doc-examples structure in SecurityPolicy CRD to show examples correctly in the documentation.
```changes
section: docs
type: chore
summary: Update x-doc-examples structure in SecurityPolicy CRD to show examples correctly in the documentation.
```
> [admission-policy-engine] update x-doc-examples structure in SecurityPolicy CRD

- ee/candi/cloud-providers/vcd/terraform-modules/master-node/main.tf
- ee/candi/cloud-providers/vcd/terraform-modules/static-node/main.tf
Ignore metadata changes in `vcd_vapp_vm` resource.
The `dhctl converge` command attempts to clear metadata if nothing has changed in the configuration.
Fix #11126.
```changes
section: candi
type: fix
summary: Ignore metadata changes in `vcd_vapp_vm` resource.
```
> [candi](vcd) Ignore metadata changes in `vcd_vapp_vm` resource

- modules/300-prometheus/templates/aggregating-proxy/rbac-to-us.yaml
- modules/300-prometheus/templates/prometheus/rbac-to-us.yaml
1. Removed ServiceAccount access from observability label-proxy to prometheus
2. Added ServiceAccount access from observability label-proxy to aggregating-proxy
We need this change, because without it, label-proxy gets gaps between metrics. Access to aggregating proxy must help to eliminate this gaps.
-
Gaps between metrics must be gone.
Allow access from observability label-proxy to prometheus aggregating proxy.
```changes
type: fix
summary: Observability must walk to aggregating proxy instead of directly to prometheus
```
> [monitoring] Fix wrong rbac for new observability module

- .github/ci_templates/web.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
Ensure ./tools/docs/link-checker/entrypoint.sh is executable before running the Docker container.
```changes
section: ci
type: chore
summary: Fix link-checker script execution in CI pipeline
```
> [ci] Fix link-checker script execution in CI pipeline

- .github/ci_templates/web.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
Change user for documentation links linter docker container.
This change helps to prevent littering runners with root-owned files.
```changes
section: ci
type: chore
summary: Switch user for web_links_test.
```
> [ci] Switch user for web_links_test

- modules/340-extended-monitoring/images/extended-monitoring-exporter/src/requirements.txt
- modules/340-extended-monitoring/images/extended-monitoring-exporter/werf.inc.yaml
Fixed CVEs
```changes
type: fix
summary: Fix extended-monitoring-exporter CVE 
```
> [extended-monitoring] Fix extended-monitoring-exporter CVEs

- docs/documentation/pages/module-development/STRUCTURE.md
- docs/documentation/pages/module-development/STRUCTURE_RU.md
- modules/101-cert-manager/docs/FAQ.md
- modules/101-cert-manager/docs/FAQ_RU.md
- modules/402-ingress-nginx/crds/doc-ru-ingress-nginx.yaml
- modules/402-ingress-nginx/crds/ingress-nginx.yaml
Correct links to module templates and config files in various docs.
```changes
section: docs
type: chore
summary: Correct links to module templates and config files in various docs.
```
> [docs] Fix broken links in documentation files

- docs/site/_includes/getting_started/bm/STEP_FINALIZE.md
- docs/site/_includes/getting_started/bm/STEP_FINALIZE_RU.md
- docs/site/_includes/getting_started/dvp/global/STEP_NODES.md
Add missing "create" command in "sudo -i d8 k create -f - <<EOF" in DVP and DKP Getting Started sections.
```changes
section: docs
type: fix
summary: Add missing "create" command in "sudo -i d8 k create -f - <<EOF" in DVP and DKP Getting Started sections.
```
> [docs] Fix missing "create" command in DVP and DKP Getting Started sections

- docs/documentation/_data/sidebars/main.yml
- modules/015-admission-policy-engine/docs/GATEKEEPER-CR.md
- modules/015-admission-policy-engine/docs/GATEKEEPER-CR_RU.md
- modules/015-admission-policy-engine/docs/README.md
- modules/015-admission-policy-engine/docs/README_RU.md
The current version of the documentation mentions gatekepeer's custom resources, but there is no separate page in the documentation listing these resources, as is done for the istio module.
This has raised questions among users of the documentation
Creating a separate page with Gatekeeper's custom resources will make the documentation more standardized, as such a page exists for the isito module.
```changes
section: docs, admission-policy-engine
type: fix 
summary:  Added a documentation page with Gatekeeper's Custom Resources.
```
> [docs][admission-policy-engine] Added a documentation page with Gatekeeper Custom Resources

- testing/matrix/linter/rules/modules/images.go
Disable outdated block of matrix tests.
```changes
type: chore
summary: Disable outdated block of matrix tests.
```
> [testing] Disable outdated block of matrix tests

- .github/ci_templates/e2e_tests.yml
- .github/scripts/js/ci.js
- .github/scripts/js/constants.js
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vcd.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-daily.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vcd.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Update CI templates to use label `e2e/use/cis` in e2e tests
If label set, we'll be able to deploy operator-trivy module into deployed cluster, to get CIS benchmark checks report
By setting label `e2e/use/cis` in PR, installation container in e2e test will start with environment variable `CIS_ENABLED` set to `true`
```changes
section: ci
type: feature
summary: Update CI templates to set CIS_ENABLED in e2e tests to true if e2e/use/cis label set.
```
> [CI] Add CIS label to e2e

- modules/500-dashboard/templates/ingress.yaml
Specified the correct certificates for ingress to access via kube-rbac-proxy.
Because users used their own tokens in kube-rbac-proxy, only SuperAdmin could get access.
```changes
type: fix 
summary: Specified the correct certificates for ingress to access via kube-rbac-proxy
```
> [dashboard] Specified the correct certificates for ingress to access via kube-rbac-proxy

- docs/documentation/_data/deckhouse-ports.yml
- modules/470-chrony/templates/daemonset.yaml
FIx ports conflict.
We have ports conflict between chrony-exporter and sds-node-configurator. 
Yes. 
To fix conflict. 
No ports conflict
```changes
type: fix 
summary: Fix ports conflict
```
> [chrony] Fix ports conflict

- modules/045-snapshot-controller/images/snapshot-controller/werf.inc.yaml
- modules/045-snapshot-controller/images/snapshot-validation-webhook/werf.inc.yaml
Fix snapshot-controller user and group for https://github.com/deckhouse/deckhouse/pull/11279
Application run by user with UID/GID 65534, but binary is owned by UID/GID 65535
Module binary can be executed inside container
```changes
type: fix
summary: Fix snapshot-controller user and group.
```
> [snapshot-controller] Fix user and group

- candi/version_map.yml
- modules/007-registrypackages/images/d8/werf.inc.yaml
Updated Deckhouse CLI to the latest
```changes
section: candi
type: chore
summary: Update Deckhouse CLi to v0.9.0
```
> [candi] Update Deckhouse CLi to v0.9.0

- modules/300-prometheus/images/grafana-v10/entrypoint/go.mod
- modules/300-prometheus/images/grafana-v10/entrypoint/go.sum
- modules/300-prometheus/images/grafana-v10/patches/security.patch
- modules/300-prometheus/images/grafana-v10/werf.inc.yaml
- modules/300-prometheus/templates/grafana/deployment-v10.yaml
Patch out grafana vulnerabilities to pass certification.
This PR fixes all possible vulnerabilities in grafana image found by trivy scanner. The only vulnerability that is not fixed is [CVE-2024-8986](https://avd.aquasec.com/nvd/cve-2024-8986). This issue however has no impact on a Deckhouse because the build process does not imply passing any credentials via the git URL.
We don't
The number of vulnerabilities is reduced to a minimum
```changes
type: fix
summary: Fix grafana CVEs
impact: grafana in cluster will be restarted as the image has changed
```
> [prometheus] Patch out grafana CVEs for CSE

- modules/300-prometheus/images/grafana-v10/entrypoint/go.mod
- modules/300-prometheus/images/grafana-v10/entrypoint/go.sum
- modules/300-prometheus/images/grafana-v10/patches/security.patch
- modules/300-prometheus/images/grafana-v10/werf.inc.yaml
- modules/300-prometheus/templates/grafana/deployment-v10.yaml
Patch out grafana vulnerabilities to pass certification.
This PR fixes all possible vulnerabilities in grafana image found by trivy scanner. The only vulnerability that is not fixed is [CVE-2024-8986](https://avd.aquasec.com/nvd/cve-2024-8986). This issue however has no impact on a Deckhouse because the build process does not imply passing any credentials via the git URL.
We don't
The number of vulnerabilities is reduced to a minimum
```changes
type: fix
summary: Fix grafana CVEs
impact: grafana in cluster will be restarted as the image has changed
```
> [prometheus] Patch out grafana CVEs

- ee/modules/150-user-authn/hooks/custom_logo.go
- ee/modules/150-user-authn/hooks/custom_logo_test.go
- ee/modules/300-prometheus/hooks/custom_logo.go
- ee/modules/300-prometheus/hooks/custom_logo_test.go
Apply custom logo only after the bootstrap
Namespace `user-authn` does not exists on the bootstrap, generating the cm will lead to the error `Create object: v1/ConfigMap/d8-user-authn/whitelabel-custom-logo: namespaces "d8-user-authn" not found` 
```changes
type: fix
summary: Apply custom logo after the bootstrap.
```
> Apply custom logo after the cluster bootstrap

- modules/300-prometheus/images/trickster/entrypoint/main.go
Fix path to trickster binary.
Trickster can't exec binary because of wrong path to binary.
To fix trickster builds.
Success builds.
```changes
type: fix
summary: Fix trickster binary path
```
>  [prometheus] Fix trickster binary path

- docs/documentation/_data/sidebars/main.yml
Transfer sections keepalived, metallb, network-gateway from "Bare Metal" to "Network Load Balancing".
```changes
section: docs
type: chore
summary: Transfer sections from "Bare Metal" to "Network Load Balancing".
```
> [docs] Transfer metallb and gateway docs to traffic balance section

- ee/be/modules/350-node-local-dns/templates/stale-dns-connections-cleaner/daemonset.yaml
Fix securityContext in stale-dns-connections-cleaner DaemonSet
There was a problem after the merge https://github.com/deckhouse/deckhouse/pull/11218:
`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/stale-dns-connections-cleaner": permission denied: unknown
`
```changes
type: fix
summary: Fixed securityContext in DaemonSet stale-dns-connections-cleaner
```
> [node-local-dns] fix securityContext for stale-dns-connections-cleaner

- docs/site/_assets/css/docs.scss
When adding a numbered list in the specifications, the margins are normally rendered.
```changes
section: docs
type: chore
summary: Update margin styles in lists.
```
> [docs][styles] Update margins in lists

- modules/150-user-authn/templates/dex-authenticator/deployment.yaml
Fix paths to url-exec-prober in dex-authenticator template.
fix https://github.com/deckhouse/deckhouse/pull/11332
In this pr,  path changed to /usr/local/bin/url-exec-prober in werf
```changes
type: fix
summary: bump dependencies for user-authn
```
> [chore] dex-authenticator path fix

- ee/be/modules/350-node-local-dns/images/stale-dns-connections-cleaner/werf.inc.yaml
Set capabilities NET_ADMIN (via setcap) on the executable file `stale-dns-connections-cleaner` so that there are no socket deletion errors.
```changes
type: fix
summary: Set capabilities (via setcap) on the executable file.
```
> [node-local-dns] fix CAPs for stale-dns-connections-cleaner

- modules/462-loki/images/loki/patches/0001-Update-crypto-net-packages.patch
Fixed CVEs
```changes
section: loki
type: fix
summary: Fix loki CVE 
```
> [loki] Fix minor loki CVE

- modules/462-loki/images/loki/patches/0001-Update-crypto-net-packages.patch
Fixed CVEs
```changes
section: loki
type: fix
summary: Fix loki CVE 
```
> [loki] Fix minor CVE

- modules/300-prometheus/images/grafana-dashboard-provisioner/werf.inc.yaml
Use statically linked python binary to run grafana dashboard provisioner hooks.
This forces the component to use common python static binary which is well maintained.
We don't
No changes for an end user.
```changes
type: chore
summary: use static python binary for the grafana dashboard provisioner
impact: grafana deployment will be rollout restarted
```
> [prometheus] Use statically linked python for grafana dashboard provisioner CSE

- modules/300-prometheus/images/grafana-dashboard-provisioner/werf.inc.yaml
Use statically linked python binary to run grafana dashboard provisioner hooks.
This forces the component to use common python static binary which is well maintained.
We don't
No changes for an end user.
```changes
type: chore
summary: use static python binary for the grafana dashboard provisioner
impact: grafana deployment will be rollout restarted
```
> [prometheus] Use statically linked python for grafana dashboard provisioner

- ee/se-plus/modules/030-cloud-provider-zvirt/images/cloud-data-discoverer/discoverer.go
This PR removes DisksMeta implementation from cloud-data-discoverer
Cluster orphaned disk discovery is broken in zvirt cloud-data-discoverer, we should remove it. 
cloud-data-discoverer will not crash anymore. 
```changes
type: fix
summary: remove DisksMeta from cloud-data-discoverer
```
> [cloud-provider-zvirt] remove DisksMeta from cloud-data-discoverer

- modules/300-prometheus/images/prometheus/README.md
- modules/300-prometheus/images/prometheus/patches/README.md
- modules/300-prometheus/images/prometheus/patches/fix-cve.patch
- modules/300-prometheus/images/prometheus/patches/sample_limit_annotation.patch
- modules/300-prometheus/images/prometheus/patches/successfully_sent_metric.patch
- modules/300-prometheus/images/prometheus/werf.inc.yaml
- modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
- modules/303-prometheus-pushgateway/images/pushgateway/werf.inc.yaml
- Update the Prometheus v2.45.2 -> v2.55.1
- New werf format (separate src-artifact/artifcat/final image)
- Repalce `npm build` step with pre-build static files for UI. 
- Add patch to fix CVE in net/crypto packages.
####
Manual regression tests:
- To improve security.
- Keep up with latest version.
```changes
type: chore
summary: Prometheus version v2.45.2 -> v2.55.1
```
> [prometheus] Upgrade Prometheus to v2.55.1

- .github/workflow_templates/build-and-test_dev.yml
- .github/workflows/build-and-test_dev.yml
Fix "Set waiting for e2e" CI job.
After introduction of runner autocleaning, jobs that do not pull code before starting will fail.  This job doesn't need to run on static runners anyway, so switching to ephemeral runners.
```changes
section: ci
type: fix
summary: Fix "Set waiting for e2e" job.
```
> [ci] Fix "Set waiting for e2e" job

- modules/340-extended-monitoring/docs/CONFIGURATION.md
- modules/340-extended-monitoring/docs/CONFIGURATION_RU.md
- modules/340-extended-monitoring/images/extended-monitoring-exporter/src/extended-monitoring.py
Add namespace-scoped overrides for threshold.extended-monitoring.flant.com labels
- Enable overriding default thresholds using `threshold.extended-monitoring.flant.com` labels at the namespace level.
- Small indention fixes for /metrics output.
- It enables applying diffirent threshold values for resources in a namespace without modifying each resources individually. Closes https://github.com/deckhouse/deckhouse/issues/8352  
-->
Namespace-level labels `threshold.extended-monitoring.flant.com`  will override the default thresholds.
```changes
type: feature
summary: Namespace-level `threshold.extended-monitoring.flant.com` labels now override default threshold values for objects lacking the label.
```
> [extended-monitoring] Add namespace-scoped overrides for threshold labels

- modules/200-operator-prometheus/images/prometheus-operator/patches/004_fix_cve.patch
- modules/200-operator-prometheus/images/prometheus-operator/patches/README.md
- modules/200-operator-prometheus/images/prometheus-operator/werf.inc.yaml
Adds patch to fix known CVEs in version v0.66.0
```
go get golang.org/x/net@v0.33.0
go get github.com/golang-jwt/jwt/v4@v4.5.1
go get google.golang.org/protobuf@v1.33.0
go get github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0
```
- Security compliance.
```changes
type: chore
summary: Fix prometheus-operator CVEs
```
> [operator-prometheus] Fix prometheus-operator CVEs

- modules/300-prometheus/images/promxy/patches/0001-update-crypto-net-cve.patch
Add patch to fix CVE-2024-51744 
`go: upgraded github.com/golang-jwt/jwt/v4 v4.5.0 => v4.5.1`
- Security compliance.
```changes
type: chore
summary: Fix Promxy CVE-2024-51744
```
> [prometheus] Promxy CVE patch

- .github/ci_templates/tests.yml
- .github/workflows/build-and-test_dev.yml
- .github/workflows/build-and-test_pre-release.yml
- .github/workflows/build-and-test_release.yml
Fix "dubious ownership" error in matrix tests.
```changes
section: ci
type: fix
summary: Fix "dubious ownership" error in matrix tests.
```
> [ci] Fix "dubious ownership" error in matrix tests

- .github/workflows/codeql.yml
Disable CodeQL on secondary repositories.
CodeQL is completely unnecessary for secondary repositories.
```changes
section: ci
type: chore
summary: Disable CodeQL on secondary repositories.
```
> [ci] Disable CodeQL on secondary repos

- modules/200-operator-prometheus/images/prometheus-operator/patches/004_fix_cve.patch
Adds patch to fix known CVEs in version v0.66.0
- Security compliance.
```changes
type: chore
summary: Fix prometheus-operator CVEs
```
> [operator-prometheus] Fix  prometheus-operator CVEs

- modules/021-cni-cilium/images/bin-cilium-envoy/patches/001-go-mod.patch
- modules/021-cni-cilium/images/bin-cilium-envoy/patches/README.md
- modules/021-cni-cilium/images/bin-cilium-envoy/werf.inc.yaml
- modules/021-cni-cilium/images/bin-cni-plugins/patches/001-go-mod.patch
- modules/021-cni-cilium/images/bin-cni-plugins/patches/README.md
- modules/021-cni-cilium/images/bin-cni-plugins/werf.inc.yaml
Update dependencies to fix vulnerabilities: 
- `bin-cilium-envoy`: CVE-2024-45338
- `bin-cni-plugins`: CVE-2024-45338
Vulnerability remediation.
```changes
type: fix
summary: Fixed vulnerabilities in sources.
```
> [cni-cilium] CSE: fix vulnerability in sources

- modules/303-prometheus-pushgateway/images/pushgateway/patches/001_fix_cve.patch
- modules/303-prometheus-pushgateway/images/pushgateway/patches/README.md
- modules/303-prometheus-pushgateway/images/pushgateway/werf.inc.yaml
- Rewrite Werf to include src-artifcat
- Fix CVEs using patch  
- Security compliance
-
```changes
section: prometheus-pushgateway
type: chore
summary: Pushgateway CVE fix
```
> [prometheus-pushgateway] pushgateway CVE fix

- candi/bashible/common-steps/all/006_fetch_registry_packages.sh.tpl
- candi/bashible/common-steps/all/062_install_kubelet_and_his_friends.sh.tpl
- candi/bashible/common-steps/cluster-bootstrap/035_install_kubeadm.sh.tpl
- modules/007-registrypackages/images/kubernetes-cni/patches/cni-plugins/001-go-mod.patch
- modules/007-registrypackages/images/kubernetes-cni/patches/plugins/001-go-mod.patch
- modules/007-registrypackages/images/kubernetes-cni/werf.inc.yaml
- modules/035-cni-flannel/images/flanneld/werf.inc.yaml
- testing/library/images_tags_generated.go
Update kubernetes-cni to 1.6.2 
Update flannel-cni to 1.6.0-flannel1
It's very cool to use the latest versions of apps and get rid of CVE.
```changes
section: candi
type: chore
summary: Bumped kubernetes-cni and flannel-cni binaries.
---
type: chore
summary: Bumped kubernetes-cni and flannel-cni binaries.
---
type: chore
summary: Bumped kubernetes-cni and flannel-cni binaries.
```
> [registrypackages] Update cni versions

- ee/modules/380-metallb/images/metallb/patches/001-update-go-libraries.patch
- ee/modules/380-metallb/images/metallb/werf.inc.yaml
- ee/se/modules/380-metallb/images/l2lb/patches/004-update-go-libraries.patch
- ee/se/modules/380-metallb/images/l2lb/werf.inc.yaml
Update dependencies to fix vulnerabilities: 
- `metallb/l2lb`: CVE-2024-41110, CVE-2024-45310
- `metallb/metallb`:  CVE-2024-41110, CVE-2024-45310
Vulnerability remediation.
```changes
type: fix
summary: Fixed vulnerabilities in sources.
```
> [metallb] fix vulnerability in sources

- ee/fe/modules/300-prometheus/.build.yaml
- ee/fe/modules/300-prometheus/templates/prometheus/longterm/prometheus.yaml
- ee/fe/modules/300-prometheus/templates/prometheus/prometheus.yaml
- tools/build_includes/modules-FE.yaml
- tools/build_includes/modules-with-dependencies-FE.yaml
- tools/build_includes/modules-with-exclude-FE.yaml
This PR marks the third phase of the migration from Prometheus to Prom++. We are moving prometheus longterm to Prom++ image, focusing on a complete switch to Prom++. Prom++ has been externalized into a separate module, and it is now possible to run Prom++ as a replacement for Prometheus longterm.
An initContainer has been added to the Prometheus longterm pod to ensure smooth data transitions. It performs data conservation and format conversion between Prometheus and Prom++ (both ways), ensuring compatibility and data integrity during the switch. If the Prom++ external module is enabled, Prom++ will be deployed; otherwise, Prometheus will be used as before.
This change is a critical step in the transition to Prom++. It provides users with the ability to consciously choose their monitoring …
> [prometheus] Add init container and switcher for prom longterm

- modules/300-prometheus/images/grafana-v10/werf.inc.yaml
The `prometheus/grafana-v10-src-files` image imports precompiled static assets from a git repository. Monaco library was not committed to that repo due to a `.gitignore` in `public/lib` thus the library is missing from the final image. 
The lack of the monaco library causes the query editor to malfunction. We have to rebuild the grafana image.
This bug has leaked to the 1.67 release and has to be fixed in the nearest patch release.
```changes
type: fix
summary: add the missing monaco JS library to the grafana image
impact: grafana deployment pods will be rollout restarted
```
> [prometheus] Add missing monaco library to grafana-v10 image for CSE

- modules/300-prometheus/images/grafana-v10/werf.inc.yaml
The `prometheus/grafana-v10-src-files` image imports precompiled static assets from a git repository. Monaco library was not committed to that repo due to a `.gitignore` in `public/lib` thus the library is missing from the final image. 
The lack of the monaco library causes the query editor to malfunction. We have to rebuild the grafana image.
This bug has leaked to the 1.67 release and has to be fixed in the nearest patch release.
```changes
type: fix
summary: add the missing monaco JS library to the grafana image
impact: grafana deployment pods will be rollout restarted
```
> [prometheus] Add missing monaco library to grafana-v10 image

- .dmtlint.yaml
- ee/modules/500-operator-trivy/templates/trivy-server.yaml
Adds an init container to chown the trivy-server's volume with correct user:group parameters.
Updating deckhouse from 1.67 to 1.67.6 breaks the trivy-server in case the trivy-server is using local-path-provision as a storage class (as this storage class doesn't respect fsGroup setting).
To bix broken trivy-server statefulset.
```changes
type: fix
summary: Add chowning init container to the trivy-server.
```
> [operator-trivy] add chowning init container

- deckhouse-controller/cmd/deckhouse-controller/main.go
- deckhouse-controller/pkg/apis/deckhouse.io/v1alpha1/deckhouse_release.go
- deckhouse-controller/pkg/controller/controller.go
- deckhouse-controller/pkg/controller/deckhouse-release/check_release.go
- deckhouse-controller/pkg/controller/deckhouse-release/check_release_test.go
- deckhouse-controller/pkg/controller/deckhouse-release/cleanup_deckhouse_release.go
- deckhouse-controller/pkg/controller/deckhouse-release/client_test.go
- deckhouse-controller/pkg/controller/deckhouse-release/controller.go
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/existed-release-suspended.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-canary-release-wave-0.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-canary-release-wave-4.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/have-new-deckhouse-image.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/image-hash-not-changed.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/inherit-release-cooldown.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/new-release-suspended.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/patch-release-has-own-cooldown.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-canary.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-cooldown.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-disruptions.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-has-requirements.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/release-with-changelog.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/restore-absent-releases-from-registry.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/resume-suspended-release.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/testdata/golden/step-by-step-update-successfully.yaml
- deckhouse-controller/pkg/controller/deckhouse-release/updater/update_task_calculator.go
Implements the idea that having a deployed DeckhouseRelease object in the cluster is mandatory.
Closes #11596 
Always having a deployed DeckhouseRelease object in the cluster facilitates:
- understanding which version the cluster is running on (from the users' point of view);
- calculating which deckhouse release should be applied next (from the controller's point of view).
If there is no deployed DeckhouseRelease in the cluster, it's recreated either using the corresponding release metadata from the registry or the current version of the deckhouse controller, in case the corresponding metadata can't be fetched.
```changes
type: chore
summary: Recreate missing deployed release.
```
> [deckhouse-controller] Recreate missing deployed release

- modules/140-user-authz/webhooks/validating/role_binding
Updates `user-authn` module's validation webhook with the matchConditions field excluding requests from `system:apiserver` user from validation.
Should be merged after creating a new tag for the shell-operator that would contain https://github.com/flant/shell-operator/pull/701.
It fixes the situation when the webhook-handler deployment is unavailable and the kube-apiserver has to reconcile/recreate some system clusterrolebindings.
Fixes #11020 
The kube-apiserver is able to recreate system clusterrolebindings on start regardless of the webhook-handler deployment state.
```changes
section: common, user-authn
type: chore
summary: Exclude system:kube-apiserver user from clusterrolebindings validation webhook.
```
> [user-authn] Exclude system:kube-apiserver user from clusterrolebindings validation webhook

- docs/documentation/_data/deckhouse-alerts.yml
- modules/040-control-plane-manager/monitoring/prometheus-rules/control-plane-manager.yaml
Update deprecated version of Kubernetes in prometheus alert: 1.27 will be deprecated
Now Kubernetes 1.27 is in EOL status — we would like to deprecate it to inform customers to update to supported version
```changes
type: chore
summary: Update D8KubernetesVersionIsDeprecated alert to set k8s v1.27 deprecated.
```
> [control-plane-manager] Update k8s deprecation/eol prometheus rules

- modules/402-ingress-nginx/images/controller-1-10/patches/README.md
- modules/402-ingress-nginx/images/controller-1-10/patches/default-backend-fix.patch
- modules/402-ingress-nginx/images/controller-1-10/werf.inc.yaml
- modules/402-ingress-nginx/images/controller-1-9/Dockerfile
- modules/402-ingress-nginx/images/controller-1-9/patches/README.md
- modules/402-ingress-nginx/images/controller-1-9/patches/default-backend-fix.patch
We are fixing a problem in the controller with incorrect attempts to resolve the endpoints addresses of the `Service` specified as the default backend.
We are fixing a problem with the controller when Ingress specifies `Service` with the `ExternalName` type as the main backend, and the default backend (using an annotation `nginx.ingress.kubernetes.io/default-backend `) - with the ClusterIP type. You can see the detailed cases here:
https://github.com/kubernetes/ingress-nginx/issues/12158
https://github.com/kubernetes/ingress-nginx/issues/12173
Successful operation of ingress, where service of external Name type is specified as the main backend, and service of ClusterIP type is specified as the default backend. It is often used to handle errors (404, 502) on a service with the ExternalName …
> [ingress-nginx] fix problem in controller with default backend for services with externalName type

- modules/340-monitoring-kubernetes/images/kube-state-metrics/patches/README.md
- modules/340-monitoring-kubernetes/images/kube-state-metrics/patches/fix-kube_pod_tolerations-deduplicate.patch
- Applies [this](https://github.com/kubernetes/kube-state-metrics/pull/2559/files) changes as patch, until it is included in the release version. 
-  Deduplicate metrics that currently create warnings in the logs of prometheus. 
```changes
type: fix 
summary: kube-state-metrics minor improvements
```
> [monitoring-kubernetes] Patch kube-state-metrics with tolerations dedup fix

- .github/scripts/js/constants.js
- .github/workflow_templates/e2e.abort.multi.yml
- .github/workflow_templates/e2e.multi.yml
- .github/workflows/e2e-abort-aws.yml
- .github/workflows/e2e-abort-azure.yml
- .github/workflows/e2e-abort-eks.yml
- .github/workflows/e2e-abort-gcp.yml
- .github/workflows/e2e-abort-openstack.yml
- .github/workflows/e2e-abort-static.yml
- .github/workflows/e2e-abort-vcd.yml
- .github/workflows/e2e-abort-vsphere.yml
- .github/workflows/e2e-abort-yandex-cloud.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vcd.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Add k8s 1.32 to CI
We'll be able to run e2e with k8s version 1.32
By setting label `e2e/use/k8s/1.32` with e2e/run/anything will run e2e with version 1.32 of kubernetes
```changes
section: ci
type: feature
summary: Add k8s 1.32 to CI.
```
> [CI] Add k8s 1.32

- ee/modules/650-runtime-audit-engine/images/falco/werf.inc.yaml
- ee/modules/650-runtime-audit-engine/images/k8s-metacollector/patches/Makefile.patch
- ee/modules/650-runtime-audit-engine/images/k8s-metacollector/patches/README.md
- ee/modules/650-runtime-audit-engine/images/k8s-metacollector/patches/go_mod.patch
- ee/modules/650-runtime-audit-engine/images/k8s-metacollector/werf.inc.yaml
- ee/modules/650-runtime-audit-engine/images/rules-loader/werf.inc.yaml
- modules/000-common/images/shell-operator/werf.inc.yaml
fixed cve in k8s-metacollector
fixed cve in rules-loader
```changes
type: fix 
summary: fixed cve in k8s-metacollector and rules-loader
```
> [runtime-audit-engine] fixed cve in k8s-metacollector and rules-loader

- modules/040-node-manager/images/capi-controller-manager/patches/001-go-mod.patch
- modules/040-node-manager/images/capi-controller-manager/patches/README.MD
- modules/040-node-manager/images/capi-controller-manager/werf.inc.yaml
Update go mod dependencies to fix CVEs in capi.
CVEs fixes.
```changes
type: chore
summary: Update go mod dependencies to fix CVEs in capi.
```
> [node-manager] bump go mod deps versions in capi

- candi/bashible/common-steps/all/002_add_system_proxy.sh.tpl
this pr allow to avoid special character '%' in systemd when use http,https proxy for containerd systemd unit.
original https://github.com/systemd/systemd/blob/8da70b9d3036591a02986ddaf3574dea4001d493/NEWS#L6488
this pr solve problem when containerd cannot use proxy because special character '%' in systemd.
command 
```
systemctl show --property Environment containerd-deckhouse
Environment=PATH=/opt/deckhouse/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin HTTP_PROXY=http://test123:examplepass%@localhost:3128 http_proxy=http://test123:examplepass%@localhost:3128 HTTPS_PROXY=http://test123:examplepass%@localhost:3128 https_proxy=http://test123:examplepass%@localhost:3128 NO_PROXY=127.0.0.1,169.254.169.254,127.0.0.1,169.254.169.254,cluster.local,10.111.0.0/16,10.222.0.0/16 …
```
> [containerd] Escape character '%' in systemd for work proxy in containerd configuration

- candi/bashible/common-steps/all/002_create_static_node_cleanup_script.sh.tpl
Add `/etc/sudoers.d/sudoers_flant_kubectl` to cleanup script.
The cleanup script leaves files created by DKP or its modules.
Delete `/etc/sudoers.d/sudoers_flant_kubectl` when cleanuping nodes.
```changes
section: candi
type: chore
summary: Add `/etc/sudoers.d/sudoers_flant_kubectl` to cleanup script.
```
> [candi] cleanup flant sudoers file

- candi/bashible/common-steps/all/011_disable_floppy_drive.sh.tpl
Reword message in floppy step message.
Different distributions use different ways to disable kernel modules in initramfs, so we can't and don't want to do it ourselves. Since in most cases this problem will not occur, but in rare cases (e.g. https://bugs.launchpad.net/ubuntu/+source/util-linux/+bug/1044111 ) it is useful to show the way to solve the problem.
```changes
section: candi
type: chore
summary: reword disable floppy step message
```
> [candi] reword disable floppy step message

- dhctl/pkg/operations/bootstrap/cluster-bootstrapper-abort.go
- dhctl/pkg/operations/destroy/destroy.go
Fix static cluster destroy behavior: discover additional master nodes and cleanup them through first master passed as --ssh-host flag
Fix the problem whole additional master nodes, didn't passed as --ssh-host, didn't cleanup
`dhctl destroy` cleanup all nodes of static cluster
```changes
section: dhctl
type: fix
summary: Fix destroy of static cluster: cleanup additional master nodes, didn't passed as --ssh-host.
```
> Fix static cluster master nodes destroy logic

- docs/site/pages/virtualization-platform/documentation/user/resource-managment/VM.md
- docs/site/pages/virtualization-platform/documentation/user/resource-managment/VM_RU.md
Fix typos in DVP virtual machines documentation.
```changes
section: docs
type: fix
summary: Fix typos in DVP virtual machines documentation.
```
> [docs] Fix typos in DVP virtual machines documentation

- docs/site/_includes/getting_started/global/partials/INSTALL_CONFIG_RU.liquid
The registry URL in `config.yml` in the Russian version has been fixed.
```changes
section: docs
type: fix
summary: |
The registry URL in `config.yml` in the Russian version has been fixed.
```
> [docs][getting-started] Fix URL in config.yml

- ee/se/modules/380-metallb/docs/EXAMPLES.md
- ee/se/modules/380-metallb/docs/EXAMPLES_RU.md
Fix yaml example in metallb module.
```changes
section: docs
type: fix
summary: Fix yaml example in metallb module.
```
> [docs] Fix yaml example in metallb module

- deckhouse-controller/pkg/controller/loader.go
- deckhouse-controller/pkg/controller/models/definition.go
- deckhouse-controller/pkg/controller/module-controllers/source/controller.go
It provides fix for the module requirements.
If a module has module dependency in requirements in the module def, it cannot be parsed, so the release is not created.  
It needs for backward compatibility.
Module yaml:
```
name: test
weight: 901
requirements:
kubernetes: ">= 1.26"
modules:
ingress-nginx: '> 1.0.0'
```
Module release:
```
root@dev-master-0:~# kubectl get mr test-v0.10.0 -oyaml
kind: ModuleRelease
metadata:
annotations:
release.deckhouse.io/notified: "false"
creationTimestamp: "2025-01-27T14:48:15Z"
generation: 1
labels:
module: test
modules.deckhouse.io/update-policy: alpha-auto
release-checksum: 3fea2c3636591b1092127de869a3cae3
source: test
name: test-v0.10.0
ownerReferences:
- apiVersion: deckhouse.io/v1alpha1
controller: true
kind: …
```
> [deckhouse] 1.64 fix module requirements

- modules/402-ingress-nginx/templates/controller/controller.yaml
The annotations section of the Helm-template for the ingress-controller has been corrected.
An error was made in pr8609, which resulted in the graceful shutdown for the ingress controller only working if Istio was additionally configured.
```changes
type: fix
summary: Fixed graceful shutdown for the ingress-controller pods.
impact: Pods of ingress-nginx controllers will be restarted.
```
> [ingress-nginx] Fix ds_eviction_annotation in ingress-nginx controllers pods

- testing/cloud_layouts/Static/configuration.tpl.yaml
Removing explicitly specified mc for CNI in Static layout. 
mc for CNI will be created automatically by dhctl.
An additional fix for #10517.
We need to check how `dhctl` selects and configures CNI if it has not been explicitly specified.
```changes
type: chore
summary: Removing explicitly specified mc for cni in Static layout.
```
> [testing] Removing explicitly specified mc for cni in Static layout.

- .dmtlint.yaml
- testing/cloud_layouts/script.sh
- testing/cloud_layouts/vSphere/Standard/configuration.tpl.yaml
- testing/cloud_layouts/vSphere/Standard/resources.yaml
The current template is unstable
Change bootstrap template e2e vsphere
```changes
section: ci
type: fix
summary: Change bootstrap template e2e vsphere.
```
> fix: vsphere e2e bootsrap template

- deckhouse-controller/pkg/controller/module-controllers/source/helpers.go
- deckhouse-controller/pkg/controller/moduleloader/loader.go
- deckhouse-controller/pkg/controller/moduleloader/types/definition.go
It provides fix for the module requirements.
If a module has module dependency in requirements in the module def, it cannot be parsed, so the release is not created.  
It needs for backward compatibility.
Module yaml:
```
name: test
weight: 901
requirements:
kubernetes: ">= 1.26"
modules:
ingress-nginx: '> 1.0.0'
```
Module release:
```
root@dev-master-0:~# kubectl get mr test-v0.10.0 -oyaml
kind: ModuleRelease
metadata:
annotations:
release.deckhouse.io/notified: "false"
creationTimestamp: "2025-01-27T14:48:15Z"
generation: 1
labels:
module: test
modules.deckhouse.io/update-policy: alpha-auto
release-checksum: 3fea2c3636591b1092127de869a3cae3
source: test
name: test-v0.10.0
ownerReferences:
- apiVersion: deckhouse.io/v1alpha1
controller: true
kind: …
```
> [deckhouse] cse 1.67 fix requirements

- deckhouse-controller/pkg/controller/loader.go
- deckhouse-controller/pkg/controller/models/definition.go
- deckhouse-controller/pkg/controller/module-controllers/source/controller.go
It provides fix for the module requirements.
If a module has module dependency in requirements in the module def, it cannot be parsed, so the release is not created.  
It needs for backward compatibility.
Module yaml:
```
name: test
weight: 901
requirements:
kubernetes: ">= 1.26"
modules:
ingress-nginx: '> 1.0.0'
```
Module release:
```
root@dev-master-0:~# kubectl get mr test-v0.10.0 -oyaml
kind: ModuleRelease
metadata:
annotations:
release.deckhouse.io/notified: "false"
creationTimestamp: "2025-01-27T14:48:15Z"
generation: 1
labels:
module: test
modules.deckhouse.io/update-policy: alpha-auto
release-checksum: 3fea2c3636591b1092127de869a3cae3
source: test
name: test-v0.10.0
ownerReferences:
- apiVersion: deckhouse.io/v1alpha1
controller: true
kind: …
```
> [deckhouse] cse 1.64 fix requirements

- modules/040-node-manager/templates/fencing-agent/nodegroupconfiguration.yaml
Correct condition in bash script nodegroup-watchdog.sh.
Fix bash script nodegroup-watchdog.sh for case, when softdog was already turned on.
type: fix
summary: "Script nodegroup-watchdog.sh for case, when softdog was already turned on, doesn't work correct."
```changes
start_wd() {
if [ -e "${WD}" ]; then
ls -lha /dev/watchdog* 2>/dev/null
rm -rf "${WD}"
touch /root/on
fi
```
> [node-manager] Fix ngc enable-watchdog-for-nodegroup.sh

- docs/site/_includes/getting_started/zvirt/partials/config.ru.yml.standard.other.inc
- docs/site/_includes/getting_started/zvirt/partials/config.yml.standard.other.inc
Fix links for zVirt documentation in Getting Started.
```changes
section: docs
type: chore
summary: Fix links for zVirt documentation in Getting Started.
```
> [docs][getting_started] Fix links for zVirt

- ee/modules/500-operator-trivy/images/operator/patches/008-bump-dependencies.patch
Update go sum, for fix "missing go.sum entry for module providing package".
```changes
type: chore
summary: Update go.sum.
```
> [operator-trivy] fix go sum deps

- ee/modules/030-cloud-provider-vcd/images/vcd-csi-plugin-legacy/patches/02-remove_pod_mount_path_when_NodeUnpublishVolume_is_called.patch
- ee/modules/030-cloud-provider-vcd/images/vcd-csi-plugin-legacy/patches/README.md
This PR backports [this fix from `cloud-director-named-disk-csi-driver v1.6.0`](https://github.com/vmware/cloud-director-named-disk-csi-driver/pull/251) to `vcd-csi-plugin-legacy` 
Fixes this issue: https://github.com/kubernetes/kubernetes/issues/122342
```changes
type: fix
summary: backport "remove pod mount path when NodeUnpublishVolume is called" patch to vcd-csi-plugin-legacy
```
> [cloud-provider-vcd] backport "remove pod mount path when NodeUnpublishVolume is called" patch to vcd-csi-plugin-legacy

- docs/documentation/_data/deckhouse-alerts.yml
- modules/021-cni-cilium/monitoring/prometheus-rules/cni-checks.yaml
- modules/035-cni-flannel/monitoring/prometheus-rules/cni-checks.yaml
- modules/035-cni-simple-bridge/monitoring/prometheus-rules/cni-checks.yaml
Reducing the severity of alerts regarding incorrect CNI configurations.
The previously configured severity for the CNI misconfiguration alert was too high.
A high-priority alert has been triggered in a significant number of clusters, which may cause confusion
```changes
type: chore
summary: The severity of alerts regarding incorrect CNI configurations has been reduced.
```
```changes
type: chore
summary: The severity of alerts regarding incorrect CNI configurations has been reduced.
```
```changes
section: cni-simple-bridge
type: chore
summary: The severity of alerts regarding incorrect CNI configurations has been reduced.
```
> [cni] Reducing the severity of alerts regarding incorrect CNI configurations.

- modules/035-cni-flannel/hooks/check_cni_configuration.go
- modules/035-cni-flannel/hooks/check_cni_configuration_test.go
Earlier (in [PR10640](https://github.com/deckhouse/deckhouse/pull/10640)), there was an error in the `check_cni_configuration` hook for the `cni-flannel` module. 
The values of the `PodNetworkMode` parameter in the secret `d8-cni-configuration` were expected to be uppercase, but they were actually in lowercase.
In this PR, we have corrected this issue
In clusters that use `cni-flannel`, this results in an error in the main `deckhouse` queue.
A release containing this issue is starting to be deployed to client clusters, which may cause confusion.
```changes
type: fix
summary: Fixed a bug in the `check_cni_configuration` hook that could cause the main queue in the `deckhouse` to stop.
```
> [cni-flannel] Fixing a faulty check in the `cni-flannel` module.

- modules/040-control-plane-manager/docs/FAQ.md
- modules/040-control-plane-manager/docs/FAQ_RU.md
Fix for removing master node labels to prevent rejoining the cluster.
```changes
section: docs
type: fix
summary: Fix for removing master node labels to prevent rejoining the cluster.
```
> [docs] Fix for removing master node labels to prevent rejoining the cluster

- candi/version_map.yml
Bump Deckhouse CLI to latest
```changes
section: candi
type: chore
summary: Update Deckhouse CLI to v0.9.2
```
> [candi] Bump Deckhouse CLI to v0.9.3

- docs/site/backends/docs-builder/internal/http/v1/handler.go
- docs/site/backends/registry-modules-watcher/internal/backends/pkg/sender/sender.go
Fixed: #10521
We are updating the endpoints used for docs-builder.
docs-builder only uses new endpoints. The old ones have been deleted.
```changes
section: docs
type: chore
summary: update API endpoints for document handling in docs-builder
```
> [docs] update API endpoints for document handling in docs-builder

- modules/007-registrypackages/images/d8/werf.inc.yaml
Use `task` from `common/task-artifact` image instead external dependency.
Build optimization.
```changes
type: chore
summary: Use `task` from `common/task-artifact` image instead external dependency.
```
> [registrypackages] fix go install deps in d8

- ee/modules/650-runtime-audit-engine/images/falco/werf.inc.yaml
The build is accelerated due to the fact that the registry includes the image without the build cache.
```changes
type: chore
summary: optimized falco-artifact image size
```
> [runtime-audit-engine] optimized falco-artifact image size

- .werf/defines/packages-proxies.tmpl
Fix alt package proxy for archive repos.
Archive repos use different path and required other proxy repo.
```changes
section: ci
type: chore
summary: Fix alt package proxy for archive repos.
```
> [ci] fix define alt package proxy

- modules/015-admission-policy-engine/templates/_helpers.tpl
- modules/015-admission-policy-engine/templates/policies/security-policy/constraint.yaml
There is a minor issue rendering D8HostNetwork constraints (if allowHostNetwork value of a security policy isn't set, the constraint is created with null value). Also, D8HostProcesses constraints were processed incorrectly (allowHostPID and allowHostIPC parameters set to true in a security policy might end up being ignored, unreasonably prohibiting corresponding settings).
Closes #10622 and fixes a couple of constraint rendering issues.
D8HostNetwork and D8HostProcesses constraints are rendered correctly.
```changes
type: chore
summary: Fix rendering constraints.
```
> [admission-policy-engine] Fix rendering constraints

- deckhouse-controller/pkg/debug/debug.go
Added a check that the module is enabled before getting its logs.
Closed https://github.com/deckhouse/deckhouse/issues/11652 
```changes
type: chore
summary: added check for enabled modules before getting debug logs
```
> [deckhouse-controller] added check for enabled modules before getting debug logs

- ee/modules/500-operator-trivy/images/operator/patches/008-bump-dependencies.patch
- ee/modules/500-operator-trivy/images/operator/werf.inc.yaml
Use go mod download instead tidy, update go.sum.
```changes
type: chore
summary: Use go mod download instead tidy, update go.sum.
```
> [operator-trivy] refactor build, use go mod download instead tidy

- modules/002-deckhouse/templates/deployment.yaml
- modules/015-admission-policy-engine/templates/README.md
- modules/160-multitenancy-manager/templates/multitenancy-manager/controller.yaml
Fixes anti-affinity rules for the deckhouse and multitenancy-manager modules.
When the `high availability` setting is set to true, there is a possibility that more than one deckhouse or multitenancy-manager pods could be scheduled on a single node, breaking the rule of highly available deployment.
```changes
section: deckhouse,multitenancy-manager
type: chore
summary: Fix affinity rules.
```
> [deckhouse, multitenancy-manager] fix affinity rules

- modules/340-extended-monitoring/templates/x509-certificate-exporter/deployment.yaml
- modules/340-extended-monitoring/templates/x509-certificate-exporter/podmonitor.yaml
Switch x509-certificate-exporter podMonitor port from exporter container to kube-rbac-proxy.
```changes
type: fix
summary: Minor x509-certificate-exporter improvements
```
> [extended-monitoring] Fix x509-certificate-exporter metrics port

- ee/fe/modules/300-prometheus/templates/prometheus/prometheus.yaml
- modules/300-prometheus/templates/prometheus/prometheus.yaml
Deckhouse prefers to run two Prometheus replicas when possible. In conjunction with the aggregation proxy, it gives some redundancy. It delivers the end user gapless charts in a cluster's Grafana even if one Prometheus replica is down for some period.
When the Prometheus StatefulSets is being rollout-restarted gaps can still occur.
The Prometheus readiness probe only checks if it can serve the requests: when one replica is ready, Kubernetes can terminate the other immediately. So we end up in the situation where the first replica has just started but never scraped any targets and the other one is being terminated and already has stopped the scraping process, hence having scraping gaps.
We should postpone the second replica stop until the first replica scrapes all the targets. The simplest …
> [prometheus] Improve prometheus rolling update

- modules/030-cloud-provider-aws/images/node-termination-handler/werf.inc.yaml
- modules/030-cloud-provider-aws/templates/node-termination-handler/daemonset.yaml
bump version aws-node-termination-handler to v1.22.1
Added support new event "Instance Rebalance Recommendation" 
aws-node-termination-handler reacts to the event "Instance Rebalance Recommendation" 
```changes
type: feature
summary: bump version aws-node-termination-handler to v1.22.1
```
> [cloud-provider-aws] bump version aws-node-termination-handler

- modules/110-istio/openapi/config-values.yaml
Wrong `ip` option in `alliance.ingressGateway.advertise` MC section.
The `alliance.ingressGateway.advertise` did not work correctly when specifying the `ip` option to change the communication address between clusters in the federation and multicluster. The correct option is `address`.
```changes
section: istio
type: fix
summary: Wrong `ip` option in `alliance.ingressGateway.advertise` MC section.
```
> [istio] Fix alliance.ingressGateway.advertise option address in api item

- .dmtlint.yaml
- tools/dmt-lint.sh
Updated dmt lint to version 0.0.29, added new linters. Which are added in warning-only mode.
Adding new checks and improving the operation of the linter
```changes
section: tools
type: chore
summary: update dmtlint configuration and bump DMT version to 0.0.29
```
> feat: update dmtlint configuration and bump DMT version to 0.0.29

- deckhouse-controller/pkg/controller/deckhouse-release/updater/requirements_checker.go
- go_lib/dependency/requirements/requirements.go
- go_lib/updater/updater.go
Skip DeckhouseRelease requirement if not registered
Skip requirements from modules, which are not included in the edition (CE for example)
This will unblock 1.66 CE release version
```changes
type: fix
summary: Skip DeckhouseRelease requirement if it's not registered.
```
> [deckhouse-controller] Skip requirement if not registered

- modules/021-cni-cilium/monitoring/grafana-dashboards/kubernetes-cluster/cilium-agent.json
- modules/042-kube-dns/monitoring/grafana-dashboards/kubernetes-cluster/dns/dns-coredns.json
- modules/300-prometheus/monitoring/grafana-dashboards/kubernetes-cluster/aggregating-proxy-cache.json
- modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/control-plane-status.json
- modules/340-monitoring-kubernetes-control-plane/monitoring/grafana-dashboards/kubernetes-cluster/kube-etcd3.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/ping-exporter-external.json
- modules/340-monitoring-kubernetes/monitoring/grafana-dashboards/kubernetes-cluster/nodes/ping-exporter-nodes.json
Updates deprecated  Grafana `graph` panel types with  `timeseries` + some minor dashboard improvements.
```changes
type:  chore
summary:  Minor dashboard improvements
```
> [prometheus] Update Grafana panels types `graph` -> `timeseries`

- candi/bashible/common-steps/all/003_install_mandatory_packages.sh.tpl
- modules/007-registrypackages/images/e2fsprogs/scripts/install
- modules/007-registrypackages/images/e2fsprogs/scripts/uninstall
- modules/007-registrypackages/images/e2fsprogs/werf.inc.yaml
- testing/library/images_tags_generated.go
added static resize2fs in e2fsprogs
Mandatory to be accepted in 1.68.0
https://github.com/deckhouse/deckhouse/pull/11585
https://github.com/deckhouse/deckhouse/pull/11634
```changes
type: chore
summary: added static resize2fs in e2fsprogs
```
> [registrypackages] added static resize2fs in e2fsprogs

- ee/be/modules/140-user-authz/images/webhook/src/internal/cache/cache.go
- ee/be/modules/140-user-authz/images/webhook/src/internal/cache/cache_test.go
- ee/be/modules/140-user-authz/images/webhook/src/internal/cache/retry.go
- ee/be/modules/140-user-authz/images/webhook/src/internal/web/hook/handler.go
- ee/be/modules/140-user-authz/images/webhook/src/internal/web/hook/handler_test.go
Updates the webhook cache's logic regarding fetching the preferred version of an apiGroup when processing a subjectaccessreview request without the "version" field or when the field equals to "*" (in case of an `auth can-i` requests).
Before the changes, the webhook would get the preferred version for the whole ApiGroup from the `/apis/<group_name>` path, yet the response would contain all possible apiVersions for the group (like v1, v1alpha1, v1alpha2, etc for `deckhouse.io` group), not the versions of the specific resource related to the group. 
For example, according to the current logic, checking `auth can-i securitypolicies` of `deckhouse.io` group would make the webhook check if `securitypolicies.v1.deckhouse.io` GVR is presented in the cluster and the request would fail with `not …
> [user-authz] fix can-i api request

- dhctl/pkg/kubernetes/actions/deckhouse/delete.go
- dhctl/pkg/operations/destroy/deckhouse.go
This pr allow delete persistentVolumes provided manually or contain reclaimPolicy other than Delete when dhctl destroy.
```
│ ┌ Delete PersistentVolumes provided manually or contain reclaimPolicy other than Delete.
│ │ d8-stronghold-data-0
│ │ pvc-006cc8f6-8d10-4129-bb9d-bac3587f1697
│ │ pvc-8d319b7e-f6b2-4191-aa3f-0a33d70c7600
│ │ pvc-dfa34b0b-d93b-43d9-b078-417210aee694
│ │ 🎉 Succeeded!
│ └ Delete PersistentVolumes provided manually or contain reclaimPolicy other than Delete. (0.06 seconds)
│
│ ┌ Wait for PersistentVolumes deletion
│ │ ️⛱️️ Attempt #1 of 45 |
│ │     Wait for PersistentVolumes deletion failed, next attempt will be in 15s"
│ │     2 PersistentVolumes with reclaimPolicy other than Delete in the cluster. Set their reclaim policy to Delete or remove them manually
│ │ …
```
> [dhctl] Fix Stronghold pv delete 

- ee/se-plus/modules/040-terraform-manager/images/terraform-manager-vsphere/werf.inc.yaml
cve fix in terraform-manager-vsphere and bump go version to 1.23
cve fix
```changes
type: fix
summary: cve fix in terraform-manager-vsphere and bump go version to 1.23
```
> [terraform-manager] cve fix in terraform-manager-vsphere

- modules/002-deckhouse/templates/validation.yaml
Relate error changes in ValidatingAdmissionPolicy for exceptions in exclude-restartedAt.
CSE release must be working
```changes
type: fix
summary: ValidatingAdmissionPolicy for exclude-restartedAt
```
> fix: ValidatingAdmissionPolicy for exclude-restartedAt

- docs/site/_assets/css/components/_header.scss
Fixed the display of the list in the header.
```changes
section: docs
type: chore
summary: Fix the display of the list in the header.
```
> [docs] Fix the display of the list in the header

- modules/002-deckhouse/templates/deployment.yaml
fix https://github.com/deckhouse/deckhouse/pull/10676
Return `helm_lib_envs_for_proxy` template to deckhouse deployment.
There is a case where a client uses `deckhouse.io` as registry, but the registry is only accessible via proxy. In this case `deckhouse` will not be able to get `deckhouse.io` to retrieve data about external modules
fix process of updating modules via proxy in some rare cases
```changes
type: fix
summary: return `helm_lib_envs_for_proxy` template to deckhouse deployment.
```
> [node-manager] no_proxy/http_proxy tuning fix 1

- deckhouse-controller/pkg/controller/module-controllers/source/controller.go
It unsets overridden if MPO does not exist.
After deleting MPO, modules still have overridden in the module source.
```changes
type: fix
summary: Unset overridden in module source.
```
> [deckhouse] fix overridden stuck in source

- deckhouse-controller/pkg/controller/module-controllers/source/controller.go
- go_lib/dependency/cr/cr.go
It limits tags.
To avoid server overwhelming.
```changes
type: fix
summary: Limit pulled modules.
```
> [deckhouse] limit pulled modules

- deckhouse-controller/pkg/helpers/register.go
- dhctl/cmd/dhctl/commands/bootstrap/bootstrap.go
- dhctl/cmd/dhctl/commands/bootstrap/phase.go
- dhctl/cmd/dhctl/commands/config.go
- dhctl/cmd/dhctl/commands/control-plane.go
- dhctl/cmd/dhctl/commands/converge.go
- dhctl/cmd/dhctl/commands/deckhouse.go
- dhctl/cmd/dhctl/commands/destroy.go
- dhctl/cmd/dhctl/commands/kube.go
- dhctl/cmd/dhctl/commands/lock.go
- dhctl/cmd/dhctl/commands/server.go
- dhctl/cmd/dhctl/commands/ssh.go
- dhctl/cmd/dhctl/commands/terraform.go
- dhctl/cmd/dhctl/main.go
- modules/040-terraform-manager/templates/terraform-auto-converger/deployment.yaml
- modules/040-terraform-manager/templates/terraform-state-exporter/deployment.yaml
Restrict dhctl command according to environment variable `DHCTL_CLI_ALLOWED_COMMANDS`. Allow in `terraform-auto-converger` only `converge-periodical` and `terraform check`, in `terraform-state-exporter` only `terraform converge-exporter`
Fixes #5206 
If environment variable `DHCTL_CLI_ALLOWED_COMMANDS` not set, all commands can be run with `dhctl`. If it set, only restricted list of commands can be executed. From `terraform-auto-converger` can be executed only `dhctl converge-periodical` and `dhctl terraform-state-exporter`, from `terraform-state-exporter`  only `dhctl terraform converge-exporter`.
```changes
section: dhctl
type: feature
summary: Added restriction to dhctl allowed command, according to environment variable DHCTL_CLI_ALLOWED_COMMANDS.
```
```changes …
```
> Add command restriction to dhctl; restrict commands in terraform-manager

- docs/documentation/_includes/sidebar_entry.html
- docs/site/_assets/css/docs.scss
- docs/site/_includes/sidebar_entry.html
- docs/site/backends/docs-builder-template/layouts/partials/sidebar.html
Changing badges in the sidebar.
Ref #11502 
```changes
section: docs
type: chore
```
> [docs] New badges in the sidebar

- modules/015-admission-policy-engine/templates/policies/security-policy/constraint.yaml
Corrects the way the presence of `seccomp profile` settings is checked in security policies.
if `seccomp` profiles aren't defined in the security policy, there should be no seccomp-related constraints for the policy in the cluster.
```changes
type: chore
summary: Fix seccomp profile settings in security policies.
```
> [admission-policy-engine] fix seccomp condition

- .github/actions/upload-d8-debug-logs/action.yaml
- .github/ci_templates/e2e_tests.yml
- .github/workflows/e2e-aws.yml
- .github/workflows/e2e-azure.yml
- .github/workflows/e2e-eks.yml
- .github/workflows/e2e-gcp.yml
- .github/workflows/e2e-openstack.yml
- .github/workflows/e2e-static.yml
- .github/workflows/e2e-vcd.yml
- .github/workflows/e2e-vsphere.yml
- .github/workflows/e2e-yandex-cloud.yml
Added log artifact generation on e2e test failure
When e2e tests fails and after time the cluster is deleted, there is no way to check the logs, what happened during the test process 
when e2e tests fail and the cluster is deleted, remains artifact with logs
```changes
section: ci
type: chore
summary: when e2e tests fail and the cluster is deleted, remains artifact with logs
```
> chore: Add create log artifacts when e2e test fails

- .github/actions/milestone-changelog/action.yml
add ee/se-plus/modules in allowed sections
it fixes changelog generator
```changes
section: ci
type: chore
summary: it fixes changelog generator
```
> chore: add ee/se-plus/modules to allowed sections

- .github/ci_templates/cve_tests.yaml
- .github/scripts/python/defectdojo_dev_tests_rotator.py
- .github/workflow_templates/cve-dev-test-rotator.yml
- .github/workflow_templates/cve-pr.yml
- .github/workflow_templates/cve-weekly.yml
- .github/workflows/cve-dev-test-rotator.yml
- .github/workflows/cve-pr.yml
- .github/workflows/cve-weekly.yml
- tools/cve/base-images.sh
- tools/cve/d8-images.sh
- tools/cve/trivy-wrapper.sh
- CVE now imports report to defectDojo instead of html.
- Each file report is per image and in .json format. (also accessible as action artifact)
- Scheduler changed to run at Wed and Sun, also will be run on push to main branch.
- Added ability to run cve test on PR
- HTML report generation and loop notifications are removed as defectDojo became an only vulnerability storage.
Use defectDojo as a single system to work with vulnerability reports
No impact to users
none
```changes
section: tools
type: chore
summary: no changes for a user
impact: no impact
```
> Trivy import reports to defectDojo

- candi/terraform_versions.yml
- ee/modules/040-terraform-manager/images/terraform-manager-openstack/patches/implement_openstack_compute_servergroup_v2_data_source.patch
- ee/modules/040-terraform-manager/images/terraform-manager-openstack/patches/readme.md
- ee/modules/040-terraform-manager/images/terraform-manager-openstack/patches/update_gomod.patch
- ee/modules/040-terraform-manager/images/terraform-manager-openstack/werf.inc.yaml
cve fix terraform-manager-openstack and bump go version
cve fix
```changes
type: fix
summary: cve fix terraform-manager-openstack and bump go version
```
> [terraform-manager] cve fix terraform-manager-openstack

- ee/se-plus/modules/040-terraform-manager/images/terraform-manager-zvirt/patches/003_update_gomod.patch
- ee/se-plus/modules/040-terraform-manager/images/terraform-manager-zvirt/patches/readme.md
- ee/se-plus/modules/040-terraform-manager/images/terraform-manager-zvirt/werf.inc.yaml
cve fix terraform-manager-zvirt and bump go version
cve fix
```changes
type: fix
summary: cve fix terraform-manager-zvirt and bump go version
```
> [terraform-manager] cve fix terraform-manager-zvirt

- modules/300-prometheus/images/grafana-v10/patches/security.patch
- modules/300-prometheus/images/grafana-v10/werf.inc.yaml
Update Grafana version to 10.4.15 to patch out some CVEs
To maintain overall security level.
We don't
```changes
type: chore
summary: update Grafana version to 10.4.15
impact: grafana deployment will be rollout restarted
```
> [prometheus] Bump grafana and patch CVEs

- candi/version_map.yml
Updated d8 cli to v0.10.3
```changes
section: candi
type: chore
summary: [candi] Update d8 cli to v0.10.3
```
> [candi] Update d8 cli to v0.10.3

- Makefile
- docs/documentation/Makefile
- docs/site/Makefile
- Add registry and registry-down targets in Makefile for site and documentation
- Update werf compose commands to include '--repo localhost:5000/docs' flag
- Ensure registry is running before starting services
The new build rules use `imageSpec` werf parameter which can't be used with local repo.
Error:
```
Error: phase build on image docs/web stage imageSpec handler failed: unable to builde stage "imageSpec": local storage are not supported at the moment. Please provide repo with --repo flag or WERF_REPO env variable
```
```changes
section: docs
type: chore
summary: Update Makefile to use local registry.
```
> [docs][chore] update Makefile to use local registry

- modules/021-cni-cilium/images/base-cilium-dev/werf.inc.yaml
- modules/110-istio/images/proxyv2-v1x21x6/werf.inc.yaml
- modules/300-prometheus/images/grafana-v10/werf.inc.yaml
The src-artifact image contains utilities that are not the source code of the platform components
Moving problematic utilities from src-artifact to artifact
```changes
type: chore
summary: Moving problematic utilities from src-artifact to artifact
---
type: chore
summary: Moving problematic utilities from src-artifact to artifact
```
> chore: migrate build tools

- tools/cve/base-images.sh
- tools/cve/d8-images.sh
defectDojo will auto close old findings on reimport if vulnerability is absent in the report
currently defectDojo not updates report
```changes
section: ci
type: fix
summary: none
impact: none
```
> defectDojo to auto close old findings

- docs/site/pages/virtualization-platform/documentation/admin/platform-management/node-management/OS.md
- docs/site/pages/virtualization-platform/documentation/admin/platform-management/node-management/OS_RU.md
- modules/040-node-manager/docs/EXAMPLES.md
- modules/040-node-manager/docs/EXAMPLES_RU.md
It is necessary to supplement the instructions for adding the root certificate and correct one link
The client added the certificate according to the [instructions from the official deckhouse website](https://deckhouse.io/products/virtualization-platform/documentation/admin/platform-management/node-management/os.html#adding-a-root-certificate).
He got confused because the `content` field, depending on the `OS`, may contain parameters that differ from those specified in the instructions.
For example, the `CERTS_FOLDER (/usr/local/share/ca-certificates)` is not present for `redos` and other `OS`, and their own are used.
I also found that the existing `bundles` link in the instruction leads to the [Custom resource NodeGroup](https://deckhouse.io/products/virtualization-platform/reference/cr/n …
> [docs] Update instructions for adding a root certificate

- CHANGELOG/CHANGELOG-v1.65.md
Fix 1.65 changelog.
```changes
section: docs
type: chore
summary: Fix 1.65 changelog.
```
> [docs] Fix 1.65 changelog

- modules/110-istio/images/common-v1x21x6/patches/002-gomod_gosum.patch
- modules/110-istio/images/common-v1x21x6/patches/003-server_test_fmtText.patch
- modules/110-istio/images/common-v1x21x6/patches/README.md
Fix CVE in Istio source code about problem in library quic-go/quic-go and related issues after updating using the expfmt library.
```changes
section: istio
type: chore
summary: Fix new CVE in CSE version
```
> [istio] Fix new CVE in CSE

- deckhouse-controller/files/kubectl_wrapper.sh
- werf.yaml
Forget change kubectl version in kubectl_wrapper in #11501
Kubectl does not work in deckhouse pod
```changes
type: fix
summary: Fix kubectl wrapper
```
> [deckhouse-controller] Fix kubectl wrapper

- candi/version_map.yml
Updated Deckhouse CLI to latest
```changes
section: candi
type: chore
summary: Update d8-cli to 0.10.4
```
> [candi] Update d8-cli to 0.10.4

- ee/modules/040-terraform-manager/images/terraform-manager-vcd/patches/gomod_update.patch
- ee/modules/040-terraform-manager/images/terraform-manager-vcd/werf.inc.yaml
cve fix terraform-manager-vcd and bump go version
cve fix
```changes
type: fix
summary: cve fix terraform-manager-vcd and bump go version
```
> [terraform-manager] cve fix terraform-manager-vcd

- ee/modules/040-terraform-manager/images/terraform-manager-huaweicloud/patches/gomod_update.patch
- ee/modules/040-terraform-manager/images/terraform-manager-huaweicloud/werf.inc.yaml
cve fix terraform-manager-huaveicloud and bump go version
cve fix
```changes
type: fix
summary: cve fix terraform-manager-huaweicloud and bump go version
```
> [terraform-manager] cve fix terraform-manager-huaweicloud

- ee/modules/015-admission-policy-engine/images/ratify/patches/02-go-mod.patch
- modules/015-admission-policy-engine/images/gatekeeper/patches/001-go-mod.patch
Bump golang deps version to fix cves.
Vulnerability fixes.
Not necessary.
```changes
type: chore
summary: bump deps version to fix cves
```
> [admission-policy-engine] bump deps version to fix cves

- modules/465-pod-reloader/images/pod-reloader/patches/go-mod.patch
- modules/465-pod-reloader/images/pod-reloader/werf.inc.yaml
Update pod-reloader component versions to fix CVE's.
```changes
section: ci
type: chore
summary: update pod-reloader component versions to fix CVE's
```
> [ci] update pod-reloader component versions to fix CVE's
